### ISSUE TITLE
 how to configure logstash5 and elasticsearch5

### ISSUE THREAD

**Issue by 191801737** [wazuh/wazuh-kibana-app#10]
dear all
[root@es-node1 ~]# /usr/share/kibana/bin/kibana-plugin list
wazuh@2.0.0-beta3

when Plugin installation complete i found  index  wazuh-monitoring-* and wazuh-alerts-* 
so i want know how to configure logstash5 and elasticsearch5

**Comment by snaow** [comment]
Hi,

We are preparing a detailed and full guide about how to install our full ecosystem: Wazuh HIDS 2.0, Wazuh API 2.0, Elastic Stack 5.0 and Wazuh App. We hope it will be ready soon.

In the meantime, please take a look into this quick guide an user create for us in our mailing list:

https://groups.google.com/d/msg/wazuh/BC2VzbUc6MI/FwZLgDBRBwAJ

Best regards,
Pedro Sanchez.

**Comment by snaow** [comment]
Hi @191801737,

We release the new documentation about how to install everything, take a look at:

- https://documentation.wazuh.com/current/installation-guide/index.html

Regards,
Pedro.
