### ISSUE TITLE
Broken report list pagination

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-kibana-app#1011]
Hi team, it seems that the list of reports in `Reporting` section is not paginating properly. When I click on the second page, it takes me to an empty page and cannot go back to the first one.
![image](https://user-images.githubusercontent.com/10210567/47910688-ed718a00-de93-11e8-9fa4-5de8493e04f6.png)
Thanks

**Comment by jesusgn90** [comment]
Done https://github.com/wazuh/wazuh-kibana-app/pull/1012

Thanks @manuasir
