### ISSUE TITLE
Fetch every field when downloading agents csv with no filters

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-kibana-app#1038]
Hello guys,

when trying to download a CSV from the agents list while applying no filters at all I can't see information related to agents groups.

Expected behavior: fetch every agent field provided by the Wazuh API when no filters are applied.

Regards.

**Comment by jesusgn90** [comment]
Duplicated (https://github.com/wazuh/wazuh-kibana-app/issues/1026), stay updated tracking that ticket instead, thanks @havidarou !
