### ISSUE TITLE
FATAL  Error: Optimizations failure.

### ISSUE THREAD

**Issue by aremai** [wazuh/wazuh-kibana-app#1042]
Hello all,
i just ran an OS update along with an update of wazuh and the elastic components.
I followed the update instructions according to your README.md and ran into the following error:

fyi i'm running the following:

- debian 9.6
- wazuh 3.7.0-1
- elasticsearch/kibana 6.5.1

`root@sec:~# sudo -u kibana NODE_OPTIONS="--max-old-space-size=3072" /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.7.0_6.5.1.zip
Attempting to transfer from https://packages.wazuh.com/wazuhapp/wazuhapp-3.7.0_6.5.1.zip
Transferring 17691773 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Command failed: /usr/share/kibana/node/bin/node /usr/share/kibana/src/cli --env.name=production --optimize.useBundleCache=false --server.autoListen=false --plugins.initialize=false
(node:1739) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

 FATAL  Error: Optimizations failure.
   8372 modules
    
    ERROR in ./plugins/wazuh/public/kibana-integrations/kibana-visualization.js
    Module not found: Error: Can't resolve './loader' in '/usr/share/kibana/plugins/wazuh/public/kibana-integrations'
    
    ERROR in ./plugins/wazuh/public/directives/index.js
    Module not found: Error: Can't resolve './wz-welcome-card/wz-welcome-card' in '/usr/share/kibana/plugins/wazuh/public/directives'

{"type":"log","@timestamp":"2018-11-26T12:24:41Z","tags":["plugin","warning"],"pid":1739,"path":"/usr/share/kibana/plugins/wazuh-logs","message":"Skipping non-plugin directory at /usr/share/kibana/plugins/wazuh-logs"}
{"type":"log","@timestamp":"2018-11-26T12:24:43Z","tags":["info","optimize"],"pid":1739,"message":"Optimizing and caching bundles for graph, monitoring, space_selector, login, logout, ml, dashboardViewer, apm, canvas, infra, wazuh, kibana, stateSessionStorageRedirect, status_page and timelion. This may take a few minutes"}
{"type":"error","@timestamp":"2018-11-26T12:30:48Z","tags":["fatal","root"],"pid":1739,"level":"fatal","error":{"message":"Optimizations failure.\n   8372 modules\n    \n    \u001b[1m\u001b[31mERROR in ./plugins/wazuh/public/kibana-integrations/kibana-visualization.js\n    Module not found: Error: Can't resolve './loader' in '/usr/share/kibana/plugins/wazuh/public/kibana-integrations'\u001b[39m\u001b[22m\n    \n    \u001b[1m\u001b[31mERROR in ./plugins/wazuh/public/directives/index.js\n    Module not found: Error: Can't resolve './wz-welcome-card/wz-welcome-card' in '/usr/share/kibana/plugins/wazuh/public/directives'\u001b[39m\u001b[22m\n","name":"Error","stack":"Error: Optimizations failure.\n   8372 modules\n    \n    \u001b[1m\u001b[31mERROR in ./plugins/wazuh/public/kibana-integrations/kibana-visualization.js\n    Module not found: Error: Can't resolve './loader' in '/usr/share/kibana/plugins/wazuh/public/kibana-integrations'\u001b[39m\u001b[22m\n    \n    \u001b[1m\u001b[31mERROR in ./plugins/wazuh/public/directives/index.js\n    Module not found: Error: Can't resolve './wz-welcome-card/wz-welcome-card' in '/usr/share/kibana/plugins/wazuh/public/directives'\u001b[39m\u001b[22m\n\n    at FsOptimizer.failedStatsToError (/usr/share/kibana/src/optimize/base_optimizer.js:379:27)\n    at compiler.run (/usr/share/kibana/src/optimize/fs_optimizer.js:47:26)\n    at onCompiled (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:241:12)\n    at applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:514:14)\n    at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:202:11)\n    at Compiler.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/CachePlugin.js:78:5)\n    at Compiler.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:206:13)\n    at compilation.seal.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:511:11)\n    at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:195:46)\n    at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:671:19)\n    at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:195:46)\n    at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:662:11)\n    at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:202:11)\n    at /usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/index.js:282:11\n    at step (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:90:11)\n    at done (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:99:22)\n    at /usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:105:15\n    at _class.boundWorkers (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:76:13)\n    at enqueue (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:96:17)\n    at /usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:116:11\n    at Array.forEach (<anonymous>)\n    at _class.runTasks (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:94:13)\n    at UglifyJsPlugin.optimizeFn (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/index.js:195:16)\n    at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:204:14)\n    at Compilation.compilation.plugin (/usr/share/kibana/node_modules/webpack/lib/BannerPlugin.js:67:5)\n    at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:206:13)\n    at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:657:10)\n    at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:202:11)"},"message":"Optimizations failure.\n   8372 modules\n    \n    ERROR in ./plugins/wazuh/public/kibana-integrations/kibana-visualization.js\n    Module not found: Error: Can't resolve './loader' in '/usr/share/kibana/plugins/wazuh/public/kibana-integrations'\n    \n    ERROR in ./plugins/wazuh/public/directives/index.js\n    Module not found: Error: Can't resolve './wz-welcome-card/wz-welcome-card' in '/usr/share/kibana/plugins/wazuh/public/directives'\n"}
"`

anyone else having this problem or is it completely related to my setup?

best,
theresa

**Comment by jesusgn90** [comment]
Hi @aremai ,

It seems like the Wazuh app package was not uploaded properly to production servers. We are currently working to fix it as soon as possible.

Regards

**Comment by jesusgn90** [comment]
Hello again @aremai ,

I've just tested again the plugin installation with a fresh build, it seems that the package was uploaded corrupted or something else.

![image](https://user-images.githubusercontent.com/8860227/49022112-65318c80-f194-11e8-8e27-17c90cc2aef2.png)

Please find attached package:

- https://packages.wazuh.com/wazuhapp/wazuhapp-3.7.0_6.5.1.zip

Checksums:

```
sha512sum
9f04042d3eaaa2da03374721ffe2ac4143e7cb92f60b2aafd498d49015d49c01051260e8be6030b971f595a2005aba65071428f34bc48fe1c3e3146bba3459ff  

md5sum
d17a0b7b81e398cf931ebb24e998f2a0  
```

Sorry about the inconveniences.

I'm going to close the issue, but don't hesitate to re-open it or open a new ticket if you are still facing troubles.

Best regards,
Jesús
