### ISSUE TITLE
Some UI improvements and bug fixes

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1050]
Hi team, this ticket is opened to improve our UI side (logic for showing content, views structure, ...)

- [x] Reduce the number of `ng-if` in sections such as Ruleset > Rule detail view. We must implement a dynamic logic so it's no longer needed to have a big view with a lot of `ng-if/ng-show` statements. 
- [x] We have to properly use the navbar on the Management > Monitoring tab to avoid UX frustration when using the Monitoring tab. At some point, the user thinks he can't go back and some other navigation known problems in Monitoring.
- [x] In our Dev Tools module we have a weird behavior: When an invalid block is inserted after a comment, the JSON parse fails in the previous blocks.
- [x] In our Dev Tools module we have an overlapped play button when the input box has a scrollbar.
- [x] Add options to sort agents list by "Registered date" and "Last keep alive" 
- [x] Replace Management > Reporting message for something different to the Kibana reporting name.
- [x] Try to simplify complex `if` conditions.
- [x] Test all the above points once completed

The next issues were closed because they are now included here: https://github.com/wazuh/wazuh-kibana-app/issues/595, https://github.com/wazuh/wazuh-kibana-app/issues/662, https://github.com/wazuh/wazuh-kibana-app/issues/867, https://github.com/wazuh/wazuh-kibana-app/issues/868, https://github.com/wazuh/wazuh-kibana-app/issues/920

**Comment by juankaromo** [comment]
Working on this branch https://github.com/wazuh/wazuh-kibana-app/tree/issue-1050
