### ISSUE TITLE
Code quality enhancement

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1052]
Hi team, this ticket is opened to give more quality to our code without modifying its logic.

- [x] Add comments to every function in server side
- [x] Add comments to every function in client side
- [x] Normalize naming convention. Variables, classes, file names...
- [x] Obtain a clean output from Eslint
- [x] Fully test the app once completed

The next issues were closed because they are now included here: https://github.com/wazuh/wazuh-kibana-app/issues/659, https://github.com/wazuh/wazuh-kibana-app/issues/660

**Comment by juankaromo** [comment]
Working on this branch https://github.com/wazuh/wazuh-kibana-app/tree/issue-1052
