### ISSUE TITLE
Update known-fields.js due to new template for AWS

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh-kibana-app#1053]
In this PR https://github.com/wazuh/wazuh/pull/1761, we changed the following field:

> data.aws.service.action.networkConnectionAction.remoteIpDetails.geoLocation.lat
> data.aws.service.action.networkConnectionAction.remoteIpDetails.geoLocation.lat

to:

> data.aws.service.action.networkConnectionAction.remoteIpDetails.geoLocation

It is not used in any visualization but it should be updated here:

> wazuh-kibana-app/server/integration-files/known-fields.js

**Comment by jesusgn90** [comment]
- [ ] Add that field to our known fields
- [ ] Replace that field in our AWS map visualization
