### ISSUE TITLE
Settings. Server did not respond

### ISSUE THREAD

**Issue by fortbendcounty** [wazuh/wazuh-kibana-app#1055]
![wazuh error](https://user-images.githubusercontent.com/45584557/49420585-c687cb80-f751-11e8-9974-de07b99dae7c.png)

Please help! I tried to add a client on Wazuh and I got "server not respond" error. I have rebooted the server many times. Python 2.7. All services are running. Agent is listed on Wazuh server. 

Thank you!

**Comment by jesusgn90** [comment]
Hi  @fortbendcounty ,

That message means the Wazuh API is not reachable or Elasticsearch is not reachable. 

Let's do the next checks:

1. Open a CLI and SSH into the instance where Kibana is installed.

```
ssh user@kibana_instance
```

2. Inside the Kibana instance, make a request pointing to your Wazuh API (same IP, port and credentials used in the Kibana form).

```
curl -u <user>:<password> http://192.168.1.26:55000
```

3. Inside the Kibana instance, make a request pointing to your Elasticsearch.

```
curl http://<elastic_ip>:9200
```

Please, paste the output here.

Best regards,
Jesús

**Comment by fortbendcounty** [comment]
Please look at outputs below. Thank you!

**Comment by jesusgn90** [comment]
Hi @fortbendcounty,

Well, it looks like your Wazuh API is not reachable or it's down. Same for Elasticsearch. 

Ok, what we are going to do is to check IPs from your instances and the affected services:

1. SSH into the Elasticsearch instance and give us the next information:

Network:

```
ifconfig
```

Elasticsearch configuration (remove sensible information or replace it):

```
cat /etc/elasticsearch/elasticsearch.yml
```

Check the Elasticsearch service:

```
systemctl status elasticsearch
```

2. SSH into the Wazuh API instance and give us the next information:

Check for `localhost`:

```
curl localhost:55000
```

Check the Wazuh API service:

```
systemctl status wazuh-api
```

Network:

```
ifconfig
```

-------------------------

Above commands provide us useful information about networking and service status for the affected components. Once you paste here that information I can look for errors or misconfigurations.

Thanks for your patience.

Regards,
Jesús

**Comment by fortbendcounty** [comment]
Dear  Jesús,

I pasted all the info below. Just so you know what everything is on one
Ubuntu 18 VM.

Thank you!

On Wed, Dec 5, 2018 at 6:52 AM Jesús Ángel <notifications@github.com> wrote:

> Hi @fortbendcounty <https://github.com/fortbendcounty>,
>
> Well, it looks like your Wazuh API is not reachable or it's down. Same for
> Elasticsearch.
>
> Ok, what we are going to do is to check IPs from your instances and the
> affected services:
>
>    1. SSH into the Elasticsearch instance and give us the next
>    information:
>
> Network:
>
> ifconfig
>
> 2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP
group default qlen 1000
    link/ether 00:15:5d:01:1b:32 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.65/24 brd 192.168.1.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::eeea:6286:ba22:d585/64 scope link noprefixroute
       valid_lft forever preferred_lft forever


>
>  Elasticsearch configuration (remove sensible information or replace it):
>
> cat /etc/elasticsearch/elasticsearch.yml
> # ======================== Elasticsearch Configuration =========================
> #
> # NOTE: Elasticsearch comes with reasonable defaults for most settings.
> #       Before you set out to tweak and tune the configuration, make sure you
> #       understand what are you trying to accomplish and the consequences.
> #
> # The primary way of configuring a node is via this file. This template lists
> # the most important settings you may want to configure for a production cluster.
> #
> # Please consult the documentation for further information on configuration options:
> # https://www.elastic.co/guide/en/elasticsearch/reference/index.html
> #
> # ---------------------------------- Cluster -----------------------------------
> #
> # Use a descriptive name for your cluster:
> #
> #cluster.name: my-application
> #
> # ------------------------------------ Node ------------------------------------
> #
> # Use a descriptive name for the node:
> #
> #node.name: node-1
> #
> # Add custom attributes to the node:
> #
> #node.attr.rack: r1
> #
> # ----------------------------------- Paths ------------------------------------
> #
> # Path to directory where to store the data (separate multiple locations by comma):
> #
> path.data: /var/lib/elasticsearch
> #
> # Path to log files:
> #
> path.logs: /var/log/elasticsearch
> #
> # ----------------------------------- Memory -----------------------------------
> #
> # Lock the memory on startup:
> #
> #bootstrap.memory_lock: true
> #
> # Make sure that the heap size is set to about half the memory available
> # on the system and that the owner of the process is allowed to use this
> # limit.
> #
> # Elasticsearch performs poorly when the system is swapping the memory.
> #
> # ---------------------------------- Network -----------------------------------
> #
> # Set the bind address to a specific IP (IPv4 or IPv6):
> #
> #network.host: 192.168.0.1
> #
> # Set a custom port for HTTP:
> #
> #http.port: 9200
> #
> # For more information, consult the network module documentation.
> #
> # --------------------------------- Discovery ----------------------------------
> #
> # Pass an initial list of hosts to perform discovery when new node is started:
> # The default list of hosts is ["127.0.0.1", "[::1]"]
> #
> #discovery.zen.ping.unicast.hosts: ["host1", "host2"]
> #
> # Prevent the "split brain" by configuring the majority of nodes (total number of master-eligible nodes / 2 + 1):
> #
> #discovery.zen.minimum_master_nodes:
> #
> # For more information, consult the zen discovery module documentation.
> #
> # ---------------------------------- Gateway -----------------------------------
> #
> # Block initial recovery after a full cluster restart until N nodes are started:
> #
> #gateway.recover_after_nodes: 3
> #
> # For more information, consult the gateway module documentation.
> #
> # ---------------------------------- Various -----------------------------------
> #
> # Require explicit names when deleting indices:
> #
> #action.destructive_requires_name: true
>
>
>
> Check the Elasticsearch service:
>
> systemctl status elasticsearch
>
> $ systemctl status elasticsearch
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled;
vendo
   Active: active (running) since Mon 2018-12-03 21:59:28 CST; 1 day 23h ago
     Docs: http://www.elastic.co
 Main PID: 785 (java)
    Tasks: 62 (limit: 4649)
   CGroup: /system.slice/elasticsearch.service
           ├─ 785 /usr/bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC
-XX:CMSIni
           └─1810
/usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_

Dec 03 21:59:28 [1]: Started Elasticsearch.

**Comment by fortbendcounty** [comment]
I figured out what my problem is. I typed in wrong IP of manager.

Thanks for trying to help.

**Comment by jesusgn90** [comment]
Hi @fortbendcounty ,

So your problem is solved now, right? Then, I'm going to close the ticket 

Kind regards,
Jesús
