### ISSUE TITLE
logstash unable to find JRuby

### ISSUE THREAD

**Issue by wafabenhamouda** [wazuh/wazuh-kibana-app#1062]
# Elastic Stack test

| Version | Revision | Branch |
| 6.5.1 | --- | --- |

Hello,

I have installed Wazuh server and Elastic Stack in the same system but my problem is that I can not see wazuh-alerts in the web interface despite I found them in the alerts.json file.
When I tried to troubleshoote the problem I found that the logstash service does not work properly.
I fact, I have a problem on starting the logstash service (please see the attached screenshot)

I hope you will solve my problem because I'm starting to lose hope.
Thank you in any case.

## CentOS (RHEL 6.7)

- [x] Check Elasticsearch logs.
[elasticsearch.log](https://github.com/wazuh/wazuh/files/2648300/elasticsearch.log)
- [ ] Check Logstash logs.
[logstash-plain.log](https://github.com/wazuh/wazuh/files/2648301/logstash-plain.log)
- [ ] Check Filebeat logs.
[filebeat.1.log](https://github.com/wazuh/wazuh/files/2648308/filebeat.1.log)
- the errors screenshots.
![error logstash1](https://user-images.githubusercontent.com/45624257/49506752-292ab580-f87f-11e8-99b6-fc1e73ca96de.png)
![error logstash2](https://user-images.githubusercontent.com/45624257/49506759-2c25a600-f87f-11e8-9669-b0a92be7ef21.png)

**Comment by wafabenhamouda** [comment]
Hello,

I fixed the directory permissions recursively for /etc/logstash.
Then, I restarted the logstash service and the same error appeared :

**_Configuration error. Not restarting. Re-run with configtest parameter for details_**

Then, I typed this command "/opt/logstash/bin/logstash --configtest -f /etc/logstash/conf.d/01-wazuh.conf", I get this message:

**_Unable to find JRuby.
If you are a user, this is a bug.
If you are a developer, please run 'rake bootstrap'. Running 'rake' requires the 'ruby' program be available._**

Then, I checked the logstash-plain.log file. I did not find previous error messages. Only INFO and WARN messages appear in this log file. (please see the attached file). 
[logstash-plain.log](https://github.com/wazuh/wazuh/files/2648961/logstash-plain.log)

Thank you again for your reply.

**Comment by jesusgn90** [comment]
Hello again @wafabenhamouda ,

Your Logstash directory permission error was solved. Let's dig into the JRuby error:

- How you installed Logstash? (yum, direct download, git clone...)
- Can you paste the output of the next commands?

```
ls /usr/share/logstash
ls /usr/share/logstash/vendor
```
thanks!

Regards,
jesús

**Comment by wafabenhamouda** [comment]
Hello,

I installed logstash with the command  _**yum install logstash-6.5.1**_

Please find below the requested output
![logstash](https://user-images.githubusercontent.com/45624257/49518433-f395c480-f89e-11e8-86ee-0a1821694910.PNG)

Thank you.

**Comment by jesusgn90** [comment]
That's pretty weird @wafabenhamouda ,

Please, can you check the value of the next environment variables?

```
echo $JAVA_HOME
echo $JAVACMD
echo $USE_RUBY
```
The may be empty but checking their content would be nice to continue our researching.

Regards

**Comment by wafabenhamouda** [comment]
Hello Mr Jesús,

If it helps, I installed logstash using this repo:

_[root@SITE1-L-MONIT-01 yum.repos.d]# cat /etc/yum.repos.d/logstash.repo
[logstash-2.1]
name=Logstash repository for 2.1.x packages
baseurl=https://packages.elastic.co/logstash/2.1/centos
gpgcheck=1
gpgkey=https://packages.elastic.co/GPG-KEY-elasticsearch
enabled=1_

Please find below the requested output:

[root@SITE1-L-MONIT-01 yum.repos.d]# echo $JAVA_HOME

[root@SITE1-L-MONIT-01 yum.repos.d]# echo $JAVACMD

[root@SITE1-L-MONIT-01 yum.repos.d]# echo $USE_RUBY

So, all of this variables are empty.

Best Regards,

**Comment by jesusgn90** [comment]
Oh yes @wafabenhamouda, your package may be broken or deprecated or something else, try to use the standard repository please (https://www.elastic.co/guide/en/logstash/current/installing-logstash.html#_yum): 

```
rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch
```
Open your logstash.repo and replace its content with the next one:

```
[logstash-6.x]
name=Elastic repository for 6.x packages
baseurl=https://artifacts.elastic.co/packages/6.x/yum
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
enabled=1
autorefresh=1
type=rpm-md
```

Remove Logstash:

```
yum remove logstash -y
```
Clear YUM cache:

```
yum clean all && rm -rf /var/cache/yum
```

Install Logstash again following our documentation https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/elastic_server_rpm.html#logstash, also take into account the `info` message that we provide regarding CentOS 6 and Logstash.

Let me know once done.

Regards,
Jesús

**Comment by wafabenhamouda** [comment]
Hello,

I followed exactly all the steps you gave me but I finally get the same error when I try to start logstash service:

_Configuration error. Not restarting. Re-run with configtest parameter for details_

When I typed this command "/opt/logstash/bin/logstash --configtest -f /etc/logstash/conf.d/01-wazuh.conf", I get this message:

_Unable to find JRuby.
If you are a user, this is a bug.
If you are a developer, please run 'rake bootstrap'. Running 'rake' requires the 'ruby' program be available._

Best Regards,

**Comment by wafabenhamouda** [comment]
Hello,

I I have installed logstash version 2.2.4 from this guide:
https://developers.redhat.com/blog/2016/06/07/how-to-install-elastic-stack-elk-on-red-hat-enterprise-linux-rhel/
now, logstash is running but in the logstash log file, I found two error messages that are always repeated (please see the attached file).
[logstash.log](https://github.com/wazuh/wazuh-kibana-app/files/2652520/logstash.log)

Do you have any idea how can I solve this two errors ?

Thank you

Best Regards,
Wafa Ben Hamouda

**Comment by wafabenhamouda** [comment]
Hello again,

Saw that nothing worked with wazuh-manager 3.7.0 on RHEL 6.7.
I searched on the forums. Consequently, I noticed that most of users recommand to use wazuh on RHEL 7 rather than RHEL 6.
I think that I will try this solution

**Comment by jesusgn90** [comment]
Hello again @wafabenhamouda ,

The Elastic stack components must fit certain versions, all the Elastic stack must be at the same version and Wazuh must fit your Elastic stack versions. 

Take a look at https://documentation.wazuh.com/current/installation-guide/compatibility_matrix/index.html for more information.

In addition, I want to say that both Elastic stack and Wazuh work better using Centos/RHEL 7 instead of Centos 6 because Centos 7 it's a newer OS, but it should work anyway.

When you say Logstash 2.2.4, this begins wrong, because you are using a non-supported version of Logstash.

Best regards,
Jesús

**Comment by wafabenhamouda** [comment]
Hello,

I tried KEL on RHEL 7 and it worked fine.

Thank you.
