### ISSUE TITLE
Wazuh logo dissapears in app 

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-kibana-app#1063]
This is a very minor aesthetics suggestion.

I noticed that when I had my browser window tiled, thus reducing the width of the window, that the Wazuh logo in the app was oddly small (right next to the Overview button): 
![wazuhresponsivelogo](https://user-images.githubusercontent.com/36071202/49515591-9c402600-f897-11e8-879c-ce42f21a64d6.png)
That is, if the window is less than 1200 pixels wide (and the left menu isn't collapsed) the logo will start to decrease in size and completely disappears when the window is 904 pixels wide. 
![vanishedlogo](https://user-images.githubusercontent.com/36071202/49515657-d3163c00-f897-11e8-9c3a-80fefbf2196a.png)
Could the `wz-responsive-img` class be adjusted in the future so that below a certain size (i.e., if the logo gets below 80 pixels wide) it switches to a different image of the social logo (just the wolf) at a fixed size?

As a side note, the image file name "new_logo_white.png" maybe should be changed.

**Comment by juankaromo** [comment]
Solved in PR #1074
