### ISSUE TITLE
Edit our config.yml file from the app

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1080]
- [x] The section Settings > Configuration view must be modified to add "edit" options.
- [x] The section Settings > Configuration must always show the applied settings.
- [x] The app must advise the user if a Kibana restart is needed in order to apply the new settings.
- [x] We always must have consistency between the applied settings and the uncommented settings under `config.yml`

**Comment by juankaromo** [comment]
Working on this branch https://github.com/wazuh/wazuh-kibana-app/tree/issue-1080
