### ISSUE TITLE
stuck at "Waiting Elasticsearch to be up" / "Waiting index \".kibana\" to be created and prepared...."

### ISSUE THREAD

**Issue by hex2a** [wazuh/wazuh-kibana-app#11]
I installed the latest plugin but dashboards, saved searches, etc are not created.

Installation: 
```
/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-2.0_5.2.2.zip

Attempting to transfer from https://packages.wazuh.com/wazuhapp/wazuhapp-2.0_5.2.2.zip
Transferring 16627532 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation complete
```

syslog:

```
kibana[1753]: {"type":"log","@timestamp":"2017-03-16T15:29:44Z","tags":["\u001b[34mwazuh\u001b[39m","initialize","info"],"pid":1753,"message":"Waiting Elasticsearch to be up..."}
kibana[1753]: {"type":"log","@timestamp":"2017-03-16T15:29:46Z","tags":["\u001b[34mwazuh\u001b[39m","initialize","info"],"pid":1753,"message":"Waiting index \".kibana\" to be created and prepared...."}
```

Connection to elasticsearch is working (".kibana" index exists and is green), and there seem to be no permission problems with any indices in the elasticsearch log.

**Comment by snaow** [comment]
Hi @hex2a,

Wazuh app waits until .kibana index is ready to initialize and install the configuration, the wait keeps trying every 3 seconds until the index is ready.
It seems like your index is up but the app still is not installing.

Could you run the following commands please to debug your installation?

`cat /usr/share/kibana/plugins/wazuh/package.json`

The output should be similar to:
```
{
  "name": "wazuh",
  "version": "2.0.0",
  "revision": "0328",
  "kibana": {
    "version" : "5.2.2"
  },
  "description": "Wazuh App",
  "main": "index.js",
  "keywords": [
    "kibana",
    "wazuh",
    "ossec"
  ],
.
.
.
```

Please extract Kibana->version field and use it on the command below: 

` curl -XGET your_elastic_server_ip:9200/.kibana/config/5.2.2`

Paste here the output and I will take a look.

Another active wait is set to run [client.info()](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#api-info),  response, checking Elastic status.

Last configuration I will ask you to ask is at /etc/kibana/kibana.yml setting "_elasticsearch.url_".

Thanks for your feedback and sorry for my too many requests.

Cheers @hex2a ! You have been a great help for Wazuh project : D

**Comment by hex2a** [comment]
cat /usr/share/kibana/plugins/wazuh/package.json

```
{
  "name": "wazuh",
  "version": "2.0.0",
  "revision": "0328",
  "kibana": {
    "version" : "5.2.2"
  },
  "description": "Wazuh App",
  "main": "index.js",
  "keywords": [
    "kibana",
    "wazuh",
    "ossec"
  ],
  "author": "Wazuh, Inc",
  "license": "GPL-2.0",
  "repository": {
    "type": "git",
    "url": "https://github.com/wazuh/wazuh-kibana-app.git"
  },
  "bugs": {
    "url": "https://github.com/wazuh/wazuh-kibana-app/issues"
  },
  "homepage": "https://www.wazuh.com/",
  "dependencies": {
    "angular-animate": "1.4.7",
    "angular-aria": "1.4.7",
    "angular-cookies": "1.4.7",
    "angular-material": "1.1.1",
    "angular-md5": "^0.1.10",
    "bootstrap": "3.3.6",
    "needle": "^1.0.0",
    "node-cron": "^1.1.2"
  }
}
```
curl -XGET -k "https://admin:admin@localhost:9200/.kibana/config/5.2.2"

```
{"_index":".kibana","_type":"config","_id":"5.2.2","_version":4,"found":true,"_source":{"buildNum":14723,"defaultIndex":"wazuh-alerts-*"}}%
```

/etc/kibana/kibana.yml
```
[..]
elasticsearch.url: https://localhost:9200
kibana.index: ".kibana"
elasticsearch.ssl.verify: false
[..]
```

**Comment by snaow** [comment]
Hi @hex2a,

We are still studying your issue, thanks for your response.

Everything looks right for me, I am thinking about the "elasticsearch.url" could be the problem, that is the value we set internally to run Elasticsearch JS API requests.
Are you using Nginx or Elastic shield? Do have Elasticsearch API (9200) basic authentication?
If so, I think we will need to adapt the App to log in using those credentials:
[JS API Elastic HTTPS Auth](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/auth-reference.html#_basic_auth)

Best regards,
Pedro.

**Comment by hex2a** [comment]
Hi,
I'm using the [search guard](https://github.com/floragunncom/search-guard/) elasticsearch plugin which provides basic authentication + HTTPS for the Elasticsearch REST API.

I just changed the /etc/kibana/kibana.yml file to use
`elasticsearch.url: https://admin:admin@localhost:9200`
instead of the `elasticsearch.username` and `elasticsearch.password` parameters, it seems to be working now.
The problem is elasticsearch JS client not setting the "auth" parameter.

**Comment by snaow** [comment]
Hi,

Perfect @hex2a, so I was on the right direction, I like your solution, still, we will add some extra setting at Wazuh App to fetch properly .username .password in case some users specify there the auth settings.

Thanks again for your feedback, so much appreciated.

**Comment by hex2a** [comment]
I think the best solution might be rewriting the requests to use the (internal?) kibana plugin API, `server.plugins.elasticsearch.callWithRequest`, this would also solve enabling CA verification for https connections, if set in the configuration. (see https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/auth-reference.html#_https_ssl)

**Comment by snaow** [comment]
You are right, we could use Kibana internal API, that way Kibana will handle all the requests, authentication credentials and Elasticsearch destination hosts hosts.

More info: 
https://www.timroes.de/2016/02/21/writing-kibana-plugins-custom-applications/#querying-elasticsearch

Or adapting our current code as follow:
```
const elasticsearchURL = serverConfig.get('elasticsearch.url');
const elasticsearchUser = serverConfig.get('elasticsearch.user');
const elasticsearchPassword = serverConfig.get('elasticsearch.password');
const client = new elasticsearch.Client({
	host: [
		{
		  host: elasticsearchURL,
		  auth: elasticsearchUser+":"+elasticsearchPassword 
		  protocol: 'https',
		  port: 9200
		}
	],
	ssl: {
		ca: fs.readFileSync(elasticsearch.caConfigFromKibanayml),
		rejectUnauthorized: true
	},
	apiVersion: '5.0'
});
```
https://github.com/wazuh/wazuh-kibana-app/blob/master/server/wazuh-monitoring.js#L8
https://github.com/wazuh/wazuh-kibana-app/blob/master/server/startup/initialize.js#L8
