### ISSUE TITLE
Refresh all index pattern known fields on the health check controller

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1101]
Currently, we are refreshing the known fields in these cases:

- Restarting Kibana 
- Changing the index pattern (menu and settings)
- Installing the app

We are missing one more case:

- [x] Refreshing all known fields each time the health check is fired (@jesuslinares)

Regards

**Comment by jesuslinares** [comment]
I just want to prevent that a user clicks on "Management > Index patterns > Refresh" and the number of fields is decreased until the user restarts Kibana.
