### ISSUE TITLE
Reduce default number of shards / replicas for the app indices

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1112]
Currently, we are using 5 shards / 1 replica per index, this should be reduced.

**Comment by jesusgn90** [comment]
https://github.com/wazuh/wazuh-kibana-app/pull/1113

**Comment by branchnetconsulting** [comment]
The documentation was never updated to reflect this change.   

It still says [here](https://documentation.wazuh.com/3.10/user-manual/kibana-app/reference/config-file.html#advanced-index-options) that the Wazuh app defaults to 

- .wazuh and .wazuh-version - 1 shard and 1 replica
- wazuh-monitoring-3.x-* - 5 shards and 1 replica

and [here](https://documentation.wazuh.com/3.10/installation-guide/installing-elastic-stack/elastic_tuning.html#setting-the-number-of-shards-and-replicas) it says that alerts/archives indices default to 5 shards and 1 replica.

It also says [here](https://documentation.wazuh.com/3.10/user-manual/kibana-app/reference/config-file.html#advanced-index-options) that the ***.replicas** settings "are only valid if they’re modified before starting the Kibana service for the very first time" which is not accurate.  Actually those settings are applied every time the Wazuh web app is opened, even if just previously you had manually set all Elasticsearch indices to have a specific number of replicas.

In conflict with the documentation, everything unexpectedly defaults to zero replicas now.  Please align the documentation with the actual defaults.  And when making end-user impacting changes like this, please clearly represent them in the release notes and changelog.  

This situation gives users the impression that they have replicas when they don't.  For me that assumption resulted in my biggest production cluster going red today.  Ouch.

Kevin
