### ISSUE TITLE
Uncaught ReferenceError: regeneratorRuntime is not defined trying to load Kibana plugin

### ISSUE THREAD

**Issue by stevemulligan** [wazuh/wazuh-kibana-app#1122]
I get the following error in latest version of Chrome when loading wazuh-kibana-app

I followed these instructions, using node version 8.11.4

https://documentation.wazuh.com/current/installation-guide/upgrading/latest_wazuh3_minor.html#upgrading-latest-minor

> commons.bundle.js:2 Uncaught ReferenceError: regeneratorRuntime is not defined
>     at Object.<anonymous> (commons.bundle.js:2)
>     at __webpack_require__ (vendors.bundle.js:2)
>     at Object.<anonymous> (commons.bundle.js:2)
>     at __webpack_require__ (vendors.bundle.js:2)
>     at Object.<anonymous> (commons.bundle.js:2)
>     at __webpack_require__ (vendors.bundle.js:2)
>     at Object.<anonymous> (commons.bundle.js:2)
>     at __webpack_require__ (vendors.bundle.js:2)
>     at Object.<anonymous> (commons.bundle.js:2)
>     at __webpack_require__ (vendors.bundle.js:2)

**Comment by jesusgn90** [comment]
Hi @stevemulligan ,

It seems like the installation went wrong on someway. Just to be sure, have you followed these steps?

```
# chown -R kibana:kibana /usr/share/kibana/optimize
# chown -R kibana:kibana /usr/share/kibana/plugins
# sudo -u kibana /usr/share/kibana/bin/kibana-plugin remove wazuh
# rm -rf /usr/share/kibana/optimize/bundles
# sudo -u kibana NODE_OPTIONS="--max-old-space-size=3072" /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.7.2_6.5.4.zip
```

Are you using Kibana 6.5.4?

Regards,
Jesús

**Comment by stevemulligan** [comment]
I ran through the above steps again this morning and it worked.  All I did was shutdown all running services first, so it might have been running out of memory before.  Thanks for your time.
