### ISSUE TITLE
Aws tags filter bar fixes

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#1130]
Hi team,

We have to forbid searching for node_name when the cluster is disabled in the agent's tags filter bar. 

On the other hand, we must disable the browser autocomplete function in search input, because if it appears it is placed on top of our autocomplete.

![image](https://user-images.githubusercontent.com/21195730/50974941-a683be80-14ec-11e9-9a2f-2f2935c70e3f.png)

Regards!

**Comment by jesusgn90** [comment]
Thanks @juankaromo , fixed here https://github.com/wazuh/wazuh-kibana-app/commit/cdde386c9712b271bf83c23212541b212471fcc5
