### ISSUE TITLE
Some 'discover' links not working when basePath is set

### ISSUE THREAD

**Issue by candlerb** [wazuh/wazuh-kibana-app#1134]
(Relates to #17)

* wazuh-manager 3.7.2-1
* wazuh-api 3.7.2-1
* elasticsearch 6.5.4
* logstash 1:6.5.4-1
* kibana 6.5.4
* Ubuntu 18.04.1; all components installed from deb packages

I have a reproducible case where basePath is not being honoured.

* Configure `/etc/kibana/kibana.yml` with:

    ```
    server.basePath: "/logs"
    server.rewriteBasePath: true
    ```

    (the latter setting will become default from Kibana 7.0 onwards).  You can test this, without a reverse proxy, by going to http://x.x.x.x:5601/logs
* Go to Discover tab
* Open the little triangle next to an event to open it up
* Note that `agent.id` and `rule.id` are hyperlinks

However these hyperlinks point to the wrong place:

* <http://x.x.x.x:5601/logs/app//app/wazuh#/agents-preview/?_g=()&agent=000>
* <http://ix-elk.int.soundmouse.net:5601/logs/app//app/wazuh#/manager/?tab=ruleset&ruleid=4713>

Notice the `/app//app/` in the path.  Clicking on the link gives a 404, but if you remove the extra `/app/` it works.

**Comment by jesusgn90** [comment]
Hi @candlerb ,
This is related to #1135 , it may seem different but it comes from the same place so I'm going to close this ticket and continue on the other one.

Regards
