### ISSUE TITLE
OwlH extension

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1140]
Hi team, the app needs a new extension for [OwlH](https://www.owlh.net/).

Tasks:

- [x] New extension. Default disabled.
- [x] Overview/agent new dashboard.
- [x] Review known fields for Kibana index pattern.
- [x] Review alerts template for Elasticsearch.
- [x] Review logstash configuration file

Regards

**Comment by izquierdolopez** [comment]
Buenas,

Gracias por la ayuda, a vuestra disposición, ya me decis lo que os haga
falta y cuando querais hacemos un call si es necesario.

*adjunto algunas cosillas. *

un logo.
template basado en el default con campos de Suricata y Zeek. (template.json)
Search, visualizations and dashboard - solo va un dashboard de momento con
8 visualizaciones y una búsqueda.  (owlh.json)

*Formato campo en Kibana*
Formato de campo signature_id -> el campo en kibana ha de verse como una
url, el enlace por defecto no ha de funcionar debe ser algo como https://
#/rule_info.php?{{value}}

*Texto para la extensión*

Titulo - OwlH Network Monitoring
Texto - Get visibility for your network security and behavior by
integrating Network IDS solutions like Suricata and Zeek (bro IDS). This
integration will help to analyze real-time traffic in on-premises, virtual
or cloud environments.
+info - http://www.owlh.net


*Para el overview. *
Estaria bien un grupo. el dashboard que os paso es el primero de varios que
iremos metiendo.

Titulo del grupo/objeto - OwlH Network Security Monitoring
(si hay grupo) Titulo del primer elemento del grupo - Network Security
Alerts.
Texto - Review and filter network security alerts.
logo - el adjunto.

Thanks,
Best Regards,
--

jose antonio izquierdo
m - +34 673 055 255
skype - izquierdo.lopez

**Comment by jesusgn90** [comment]
First approach: https://github.com/wazuh/wazuh-kibana-app/pull/1175

Pending: adapt Logstash configuration file, adapt Elasticsearch template
