### ISSUE TITLE
Handle error messages when they are too long

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#1155]
Hi team,

It'd be great if we could handle the length of error messages when they are too long and stand out from the toaster.

e.g:

![image](https://user-images.githubusercontent.com/21195730/51398036-d9f4c780-1b42-11e9-8200-4c1568a77dd1.png)

Regards.

**Comment by juankaromo** [comment]
Working on this branch https://github.com/wazuh/wazuh-kibana-app/tree/issue-1155

**Comment by jesusgn90** [comment]
Also added this https://github.com/wazuh/wazuh-kibana-app/commit/be563df711485f36fff5aa49850cbf122a041775
