### ISSUE TITLE
Edit local rules/decoders

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1161]
Tasks:

- [x] Create specific tab under Management > Ruleset
- [x] Use the editor directive we've already made for `agent.conf`
- [x] Just edit local rules/decoders
- [x] Only allowed if admin mode is enabled
- [x] Implement edit of CDB lists
- [x] API calls
- [x] Change the UI to adapt it to these new sections

Reference:
- https://documentation.wazuh.com/current/user-manual/ruleset/custom.html

**Comment by juankaromo** [comment]
Working on this branch https://github.com/wazuh/wazuh-kibana-app/tree/issue-1161

**Comment by juankaromo** [comment]
I've been making some requested UI changes in the new configuration editing sections.
The changes made are in branch https://github.com/wazuh/wazuh-kibana-app/tree/issue-1161
