### ISSUE TITLE
Restart agents from the app

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1162]
Tasks:

- [x] Add button to restart it (API call)

**Comment by juankaromo** [comment]
Working on this branch https://github.com/wazuh/wazuh-kibana-app/tree/issue-1162

**Comment by pablotr9** [comment]
Today's work:

- [ ] UI improvement in agent
- [ ] Show feedback when an agent is upgrading
- [ ] Test that an agent upgrade is successful and update feedback.
Currently, the agent is giving a time out when upgraded that has to be fixed

**Comment by pablotr9** [comment]
Today's work:

- [ ] Fix the feedback shown when an agent is upgrading.
- [ ] Fix timeout using "wait_for_complete" param when upgrading an agent.
When testing upgrading an agent, the API call replies an error 1715-"Error sending WPK file."

**Comment by juankaromo** [comment]
Today work
- [x] Making fixes and merging 3.9 to do PR
