### ISSUE TITLE
Edit manager configuration - 1st iteration - single node

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1163]
Tasks:

- [x] Create specific tab under Management 
- [x] Use the editor directive we've already made for `agent.conf`
- [x] Only allowed if admin mode is enabled
- [x] Manager

**Comment by juankaromo** [comment]
Merged with this branch https://github.com/wazuh/wazuh-kibana-app/tree/issue-1161
