### ISSUE TITLE
Support for more than one pattern on "wazuh-monitoring"

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1183]
Hi team,

Currently, we are supporting custom monitoring patterns just using our `config.yml`, and it's fine. Next improvement would be to allow multi-pattern for those environments where we have two Kibanas and one Elasticsearch.

#### Current behaviour

One Kibana overrides the monitoring template from another Kibana using the same `.kibana` index.

#### Expected behavior

Respect the monitoring template from another Kibana if it already exists.

#### Proposed solution

If the template exists and it's valid for our Kibana, just add our pattern to the index patterns list for `wazuh-agent` template.

**Comment by juankaromo** [comment]
Working on this branch https://github.com/wazuh/wazuh-kibana-app/tree/issue-1183
