### ISSUE TITLE
Back button improvements (2nd iteration)

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1197]
First iteration was https://github.com/wazuh/wazuh-kibana-app/issues/994

Tasks:

- [x] New configuration sections (XML editors)
- [x] Specific agent view

Regards

**Comment by juankaromo** [comment]
Working on this branch https://github.com/wazuh/wazuh-kibana-app/tree/issue-1197

**Comment by juankaromo** [comment]
Today fixes

- [ ] Buck button working in specific agent view
- [ ] New configuration sections
- [ ] New battery test

**Comment by juankaromo** [comment]
Today fixes

- [ ] New configuration sections
- [ ] Perform a new test battery

**Comment by juankaromo** [comment]
Today fixes

- [X] Fixed reload when click again in dev-tools being inside it
- [X] Fixed wrong behavior inside the cluster configuration section
- [X] Fixed some wrong injections
