### ISSUE TITLE
Edit manager configuration - 2nd iteration - cluster

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1198]
The first iteration was https://github.com/wazuh/wazuh-kibana-app/issues/1163

Tasks:

- [x] Cluster
  - [x] Master
  - [x] Worker

**Comment by juankaromo** [comment]
Working on this branch https://github.com/wazuh/wazuh-kibana-app/tree/issue-1198

**Comment by juankaromo** [comment]
- [x] I started with the issue firt aproach. Pablo continues.

**Comment by pablotr9** [comment]
- [ ] Edit configuration when we are in cluster mode:
    - [ ] Master
    - [ ] Worker
- [ ] When we change the selected node using the node selector, the configuration we are showing is the specified node's configuration.
- [ ]  Once we send the configuration, it says `Success. Node configuration has been updated`, we must add the node name to this message.
