### ISSUE TITLE
Refresh local ruleset lists once new rule is added

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1199]
Ensure that the ruleset lists are updated after adding a new item.

Tasks:

- [x] Local rules
- [x] Local decoders
- [x] CDB lists

**Comment by juankaromo** [comment]
Working on this branch https://github.com/wazuh/wazuh-kibana-app/tree/issue-1199

**Comment by juankaromo** [comment]
Today fixes
[ ] If files saving fails, the editor is not closed (all editions)
[ ] Added the new CDB list option
[ ] Refresh tables after insert new items
