### ISSUE TITLE
support kinaba 5.3.0?

### ISSUE THREAD

**Issue by duhd** [wazuh/wazuh-kibana-app#12]
support kinaba 5.3.0?

**Comment by snaow** [comment]
Hi @duhd,

Elastic Stack has released few hours ago the new versions 5.3.0, we could proudly say that we just have adapted our App to the latest Kibana version.

Quoting issue https://github.com/wazuh/wazuh/issues/93:
> 
> We will try to keep updated Wazuh App to work with latest Kibana version, but there are cases that the process of adapting the new version could take some days (in days case it was a few hours).
> 
> ....
> 
> Wazuh App 2.0 working with Kibana 5.3.0, check latest commit for details.
> 
> Package link
> https://packages.wazuh.com/wazuhapp/wazuhapp-2.0-5.3.0.zip
> 
> Plugin installation
> /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-2.0-5.3.0.zip

Best regards,
Pedro Sanchez.
