### ISSUE TITLE
Custom interval for Wazuh monitoring indices creation

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1209]
Some of our community users reported an [use case](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/wazuh/f7uuabMcxo8/_Ic4YNoQGgAJ) where it explains the need for a custom interval on Wazuh monitoring indices created from the Wazuh app. I think it's a good idea so we are going to implement it.

Tasks:

- [x] Keep current interval as daily
- [x] Add a new setting for `config.yml` file
- [x] Accept human-readable format for the interval
   - [x] Options: `h`, `d`, `w`, `m`

Regards

**Comment by juankaromo** [comment]
Working on this branch https://github.com/wazuh/wazuh-kibana-app/tree/issue-1183

**Comment by juankaromo** [comment]
Today's work

- [x] The name of the index is generated according to the selected interval
