### ISSUE TITLE
Restart manager/cluster button

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#1210]
Add the possibility to restart the manager or cluster in new configuration sections, in order to apply the changes made.

**Single host**:

- [x] ossec.conf editor
  - Restart button applies the manager. `/manager/restart`
  - Needs confirmation (skip|confirm)
- [x] Local rules/decoders/lists 
  - Restart button applies the manager. `/manager/restart`
  - Needs confirmation (skip|confirm)

**Cluster**:

- [x] ossec.conf editor
  - Restart button applies selected node. `/cluster/:node/restart`
  - Needs confirmation (skip|confirm)
- [x] Local rules/decoders/lists 
  - Restart button applies all nodes. `/cluster/restart`
  - Needs confirmation (skip|confirm)

**Comment by juankaromo** [comment]
Working in this branch https://github.com/wazuh/wazuh-kibana-app/tree/issue-1210

**Comment by juankaromo** [comment]
Today's work

- [x] Added always visible manager button
- [x] Implemented custom toaster with restart button

**Comment by juankaromo** [comment]
Today's work
**Single**
* [x]  ossec.conf editor
* Restart button applies the manager. `/manager/restart`
* Pop up confirmation (skip|confirm)
* [x]  Local rules/decoders/lists  
  * Restart button applies the manager. `/manager/restart`
  * Pop up confirmation (skip|confirm)
**Cluster**
* [x]  ossec.conf editor  
  * Restart button applies selected node. `/cluster/:node/restart`
  * Pop up confirmation (skip|confirm)
* [x]  Local rules/decoders/lists  
  * Restart button applies all nodes. `/cluster/restart`
  * Pop up confirmation (skip|confirm)

- [ ] Testing

**Comment by pablotr9** [comment]
Today's work:
-[ ] Restart manager/cluster button
* Restart button applies the selected node. `/cluster/:node/restart`
* Pop up confirmation (skip|confirm)
* When the button is clicked it becomes disabled until the api call is done.

**Comment by juankaromo** [comment]
Today's work:

- [x] Some refactor in config service
- [x] Validate config before restart manager/cluster
