### ISSUE TITLE
Issue when editing local ruleset

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1211]
Hi team, I've been testing these new features, they are great but we need to improve them:

- [x] Management > Configuration > Edit CDB Lists > Create new list
  - Once a new entry is added it sends the list, this is wrong, what we want here is adding one or more entries, then click on a (missing)  button for sending the list. If it was successfully uploaded then we must show the table with all the lists, and it should include our new list.
- [x] Management > Configuration > Edit CDB Lists  / Edit rules / Edit decoders
  - Once we click `save` the editor is closed and list refreshed, this is wrong, what we want here is wait until the uploading is completed, then depending on the result we should close the editor just if it was a success, otherwise the editor must be opened.
- [x] Management > Configuration > Edit CDB Lists
  - For the AWS list we have an error when adding a new entry, it says `Wazuh API error: 705 - Invalid CDB list. Line 1: TEMPLATE:# Filtering by Cloudtrail sources is no longer used.`, also the list is broken after doing that. **~blocked by API - branch: dev-edit-files-distributed~**
- [x] Management > Configuration > Edit CDB Lists
  - Some lists are composed just by keys (security-eventchannel), the editor is not allowing to add an entry for this kind of lists. **~blocked by API - branch: dev-edit-files-distributed~**
- [x] Management > Configuration > Edit CDB Lists 
  - Fill key value for an existing one list, then click on "+" for creating a new list, the key value we've used is still filled for the key value, this is wrong.
- [x] Management > Configuration > Edit configuration
  - If we change the selected node using the node selector, the configuration we are showing is still the master configuration.
- [x] Management > Configuration > Edit configuration
  - Once we send the configuration, it says `Success. Node configuration has been updated`, we must add the node name to this message
- [x] Management > Configuration > Edit CDB Lists
  - Unhandled rejection -> [wz-list-manager L88](https://github.com/wazuh/wazuh-kibana-app/blob/4d8543db745391d33db52c5fa2f12dd12d76cc12/public/directives/wz-list-manage/wz-list-manage.js#L88), this method also must be async/await
- [x] Management > Configuration > Edit CDB Lists  / Edit rules / Edit decoders
  - We are sending just for the master node, we must to explicitly explain it to the user. Next releases will include for worker nodes too, but at this moment we want just for the master and we must add some details about it
- [x] `$scope.currentList.name` is undefined when deleting an entry from a list and probably always because we are not giving value to that variable in almost use cases.

**Comment by juankaromo** [comment]
Working on this branch https://github.com/wazuh/wazuh-kibana-app/tree/issue-1211

**Comment by pablotr9** [comment]
* Management > Configuration > Edit configuration:
Fixed in https://github.com/wazuh/wazuh-kibana-app/issues/1198

**Comment by juankaromo** [comment]
Today fixes

- [x] All fixes related to Management > Configuration > Edit CDB Lists
