### ISSUE TITLE
Wazuhapp version problem

### ISSUE THREAD

**Issue by LFBernardo** [wazuh/wazuh-kibana-app#122]
Hi All,

Busy deploying Wazuh on ubuntu 16.04 LTS as per documentation. When I get to the part "/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp.zip" it fails with the following:

`root@Wazuh-srv:/tmp/test/kibana/wazuh# /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp.zip
Attempting to transfer from https://packages.wazuh.com/wazuhapp/wazuhapp.zip
Transferring 4459005 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [wazuh]. Expected [5.6.5]; found [5.6.4]"
`
I see that 5.6.5 is not yet available. Any ideas?

**Comment by LFBernardo** [comment]
extracted the package, updated version 5.6.4 in all files to 5.6.5 as a short term jig to get it to install. Haven't seen any errors so far.

**Comment by JuanjiJG** [comment]
Hi @LFBernardo!

Thank you for the report, we'll test the new ELK 5.6.5 and upload a compatible Wazuh App package. I'll let you know when it's ready.

Best regards,
Juanjo

**Comment by LFBernardo** [comment]
Much appreciated.

**Comment by JuanjiJG** [comment]
Hi again @LFBernardo!
The package is ready. You can use the following comands **(as root)** to install it.

1. First remove the old Wazuh App package
    * `/usr/share/kibana/bin/kibana-plugin remove wazuh`
2. Install the new app package:
    * `/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-2.1.1_5.6.5.zip`

Thank you for your patience!
Regards,
Juanjo

**Comment by LFBernardo** [comment]
Awesome, thanks Juanjo.
