### ISSUE TITLE
Show "configuration assessment" configuration

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1223]
For the next Wazuh version, it comes with a new module (`configuration-assessment`). We must show applied configuration like we are doing for any other module.

Ref: https://github.com/wazuh/wazuh-documentation/pull/906

Tasks:

- [x] Agent view

**Comment by juankaromo** [comment]
Working on this branch https://github.com/wazuh/wazuh-kibana-app/tree/issue-1223
