### ISSUE TITLE
Do not check the monitoring template if it's a worker or if it's disabled

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1231]
When using Kibana in **cluster** mode, this line should be executed by **indexers** but we are executing it regardless the node type:

https://github.com/wazuh/wazuh-kibana-app/blob/342120db22801a0dc8d10585b120140d0d5c2eb5/server/monitoring.js#L633

**Proposal**

Please, replace this:

```js
await this.checkTemplate();
```

with:

```js
if(this.ENABLED) {
  await this.checkTemplate();
}
```

**Comment by juankaromo** [comment]
Solved in branch https://github.com/wazuh/wazuh-kibana-app/tree/issue-1183
