### ISSUE TITLE
Ruleset edition - Testing 3.9.0

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1237]
Tasks:

- [x] Add a new rule
- [x] Edit an existing one rule
- [x] Add a new decoder
- [x] Edit an existing one decoder
- [x] Add a new CDB list
- [x] Edit an existing one CDB list
- [x] `/validation` must be called before restarting any manager, if it fails we should show the reason instead of restarting

Misc tasks:

- [x] Try all the error scenarios

**Comment by juankaromo** [comment]
### Testing result

- Add a new rule
**Ok. If it pass the validation, the results are as expected.**
- Edit an existing one rule
**FAIL!. Restart manager toaster not appear after save file.**
- Add a new decoder
**Ok. If it pass the validation, the results are as expected.**
- Edit an existing one decoder
**FAIL!. Restart manager toaster not appear after save file.**
- Add a new CDB list
**Ok. If it pass the validation, the results are as expected.**
- Edit an existing one CDB list
**Ok. If it pass the validation, the results are as expected.**
- `/validation` must be called before restarting any manager if it fails we should show the reason
**Ok. It's called after saving any file and before restarting any manager.**

Trying error scenarios. Bugs and improvements found:

- Height of some XML file editors must be adapted again.
- Back button behaviour is broken editing file again.
- It would be nice if we handle white spaces in new file name before send, cause we are getting this error: Param not valid. Path invalid.
- If we save a wrong rule, validation show us the error toaster. But, if we then save a correct decoder, validation show us the first rule error again, and not a decoder successfully saved toaster.

**Comment by juankaromo** [comment]
Working on above testing fixes in this branch https://github.com/wazuh/wazuh-kibana-app/tree/issue-1237

**Comment by juankaromo** [comment]
Today fixes:

- [x] Restart manager toaster when Edit an existing one rule.
- [x] Restart manager toaster when Edit an existing one decoder.
- [X] Fixed the height of some XML file editors
- [x] Forbid white spaces in a new file name
- [x] New warning toaster when file saves successfully, but the configuration has some error.

**Comment by juankaromo** [comment]
- [x] Added confirmation before restart manager/cluster/node and agents
