### ISSUE TITLE
Configuration assessment - Testing 3.9.0

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1239]
Tasks:

- [x] If no configuration is given, it should handle it properly
- [x] If the configuration is given but there are no scans, it should show a specific message.
- [x] If the configuration is given and we have data, it should show a list of policies
- [x] Each policy must be clickable, then we should see all executed checks for that policy
- [x] Switching between alerts/state should work as expected
- [x] Discover search bar should be hidden when the state tab is opened

Misc tasks:

- [x] Our config on-demand tab (agents) should show all related configuration blocks

**Comment by juankaromo** [comment]
### Testing result

- If no configuration is given, it should handle it properly.
**Ok. The results are as expected.**
- If the configuration is given but there are no scans, it should show a specific message.
**Ok. The results are as expected.**
- If the configuration is given and we have data, it should show a list of policies.
**Ok. The results are as expected.**
- Each policy must be clickable, then we should see all executed checks for that policy.
**Ok. The results are as expected.**
- Switching between alerts/state should work as expected.
**Ok. The results are as expected.**
- Discover search bar should be hidden when the state tab is opened.
**Ok. The results are as expected.**
- Our config on-demand tab (agents) should show all related configuration blocks.
**Ok. The results are as expected.**
