### ISSUE TITLE
Dev Tools - Testing 3.9.0

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1240]
Specific tasks for the latest additions:

- [x] In case we write the same query multiple times, it should select the current query, also it should work as expected.
- [x] When a valid query is selected, we should be able to execute it pressing `shift + enter`.
- [x] Recently added "Export JSON" button should download a JSON file with the exact output from the output console.

**Comment by juankaromo** [comment]
### Testing result

- In case we write the same query multiple times, it should select the current query, also it should work as expected
**Ok. The results are as expected.**
- When a valid query is selected, we should be able to execute it pressing `shift + enter`
**Ok. The results are as expected.**
- Recently added "Export JSON" button should download a JSON file with the exact output from the output console
**Ok. The results are as expected.**
