### ISSUE TITLE
Error handler - Testing 3.9.0

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1241]
Since we've done some small changes for that component, here are some useful tasks:

- [x] Generate a long message error, the toaster should be expanded up to ~550px
- [x] Generate a small message error, the toaster should have the default width

**Comment by juankaromo** [comment]
### Testing result

- Generate a long message error, the toaster should be expanded up to ~550px
**Ok. The results are as expected. (It's expanded up to 600px)**
- Generate a small message error, the toaster should have the default width
**Ok. The results are as expected.**
