### ISSUE TITLE
Manager configuration not showing syslog output settings

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-kibana-app#1245]
Hello team,
I've noticed the Managerment>Configuration interface doesn't show syslog output config of the manager.

Regards.

**Comment by jesusgn90** [comment]
![image](https://user-images.githubusercontent.com/8860227/52912104-fbb1ad80-32ac-11e9-9e32-0cb95134fd9a.png)

I think it's working as expected @havidarou , we may consider to move the place where it's currently located but it's showing the information. If it's fine for you, we close the ticket.

**Comment by jesusgn90** [comment]
After reviewing it with @havidarou we concluded it's just placed in the wrong place, it will be relocated for next versions, thanks!
