### ISSUE TITLE
Wazuh App - Authorization Exception

### ISSUE THREAD

**Issue by mathieu83470** [wazuh/wazuh-kibana-app#1266]
Hello,

To give a feedback to this issue https://github.com/wazuh/wazuh-kibana-app/issues/1203#issue-405679632

I upgraded Elasticsearch and Kibana version to 6.6.1 and last version of wazuh app with the same configuration but autorization errors continue. 
Can anyone tell me how to debug these errors messages logs ? 

![image](https://user-images.githubusercontent.com/46820664/53251570-43757200-36bd-11e9-95b3-c56033c85f93.png)

![image](https://user-images.githubusercontent.com/46820664/53252687-ca2b4e80-36bf-11e9-8eee-d272f906a96a.png)

Any new idea to resolve it? If not i will try with Elastic support.

**Comment by jesusgn90** [comment]
Hi @mathieu83470 ,

The error `2001` comes from https://github.com/wazuh/wazuh-kibana-app/blob/b920b6d455a2e895d3d758e9eb7ea5ebe6a1fc8c/server/controllers/wazuh-api-elastic.js#L40, this method is throwing the authorization exception when trying to get the API entries, https://github.com/wazuh/wazuh-kibana-app/blob/b920b6d455a2e895d3d758e9eb7ea5ebe6a1fc8c/server/controllers/wazuh-api-elastic.js#L42, then we are just calling an API endpoint from Elasticsearch at https://github.com/wazuh/wazuh-kibana-app/blob/b920b6d455a2e895d3d758e9eb7ea5ebe6a1fc8c/server/lib/elastic-wrapper.js#L537, as you can see, we are using `callWithInternalUser` which means it must take the user from your `/etc/kibana/kibana.yml`. If you are using `elastic` as user in that file, the exception should not be there.

We can try these two `curl` commands:

```
curl -u elastic:elastic_pass elastic_ip:9200/.wazuh/_search
curl -u kibana:kibana_pass elastic_ip:9200/.wazuh/_search
```

Regards

**Comment by mathieu83470** [comment]
Hi @jesusgn90 

Thanks for your help.

This error seems normal, ".wazuh" index is not set in ELK,
Wazuh-app must create it on startup no ? or i'm forgetting something?

![image](https://user-images.githubusercontent.com/46820664/53324956-72b8f880-38e2-11e9-8b5f-2a3508d4d8d9.png)

**Comment by jesusgn90** [comment]
Yes, the app must create it on startup. We can debug some other code lines in your Wazuh app.

It should create it at https://github.com/wazuh/wazuh-kibana-app/blob/b920b6d455a2e895d3d758e9eb7ea5ebe6a1fc8c/server/lib/elastic-wrapper.js#L166, but as I said, this method is using `callWithInternalUser` too, so I don't understand how your app is not being able to create it if your `/etc/kibana/kibana.yml` is using `elastic` as the user.

Check if we are using `elastic` as username:

```
cat /etc/kibana/kibana.yml | grep "elasticsearch.username"
```

Regards

**Comment by mathieu83470** [comment]
Yes kibana.yml config file is OK. 

![image](https://user-images.githubusercontent.com/46820664/53326195-3e930700-38e5-11e9-8ca8-10dd1be7198a.png)

But I'm not sure this authentication mode (basic) is enable with our Xpack configuration,
If I comment elasticsearch.username and elasticsearch.password lines, Kibana work fine too.

**Comment by jesusgn90** [comment]
Interesting, can we check the next two commands?

```
cat /etc/elasticsearch/elasticsearch.yml | grep "security.enabled"
cat /etc/kibana/kibana.yml | grep "security.enabled"
```

Regards

**Comment by mathieu83470** [comment]
![image](https://user-images.githubusercontent.com/46820664/53335562-18c52c80-38fc-11e9-94a9-0e34c7df1e74.png)

![image](https://user-images.githubusercontent.com/46820664/53335981-3e9f0100-38fd-11e9-8829-8d8695ab9388.png)

Thanks

**Comment by jesusgn90** [comment]
Hi @mathieu83470 ,

This is pretty weird, are you using some kind of reverse proxy software such as NGINX or something similar? My only suggestion is to review that some third party software is catching our auth headers or removing them in some way.

Is it possible?

Regards

**Comment by mathieu83470** [comment]
I don't think so, we have no proxy between Kibana server and Elasticsearch server.
Finally I don't understand why error message speaks about "Kibana" user in wazuh plugin , it's a hardcoded message or real return of Elasticsearch web service ?

![image](https://user-images.githubusercontent.com/46820664/53341170-1a4a2100-390b-11e9-9e3a-f497b2235aeb.png)

**Comment by jesusgn90** [comment]
> I don't think so, we have no proxy between Kibana server and Elasticsearch server.
> Finally I don't understand why error message speaks about "Kibana" user in wazuh plugin , it's a hardcoded message or real return of Elasticsearch web service ?
> 


Yes, it's the real output from Elasticsearch.

**Comment by jesusgn90** [comment]
Hello @mathieu83470 ,

Well, I could not reproduce your issue but I want to help you. 

Let's check if security is enabled internally in Elasticsearch:

```
curl elastic:9200/_xpack/security/_authenticate?pretty
```

Also, I want to add an extra log output for debugging purposes. Please, edit the file located at `/usr/share/kibana/plugins/wazuh/server/initialize.js`, https://github.com/wazuh/wazuh-kibana-app/blob/b920b6d455a2e895d3d758e9eb7ea5ebe6a1fc8c/server/initialize.js#L118-L119

Please, add a line like this:

```js
const debugUser = (((wzWrapper || {}).elasticRequest || {})._config || {}).username || 'UNKNOWN';
log('DEBUG', `KIBANA INTERNAL USER: ${debugUser}`);
```

And this is how your modification should look like:

```js
const checkAPIEntriesExtensions = async () => { 
   try {
      const debugUser = (((wzWrapper || {}).elasticRequest || {})._config || {}).username || 'UNKNOWN';
      log('DEBUG', `KIBANA INTERNAL USER: ${debugUser}`);
```

Save and close the file, now please restart Kibana:

```
systemctl restart kibana
```

After some minutes, your app log file (`/usr/share/kibana/optimize/wazuh-logs/wazuhapp.log`) should contain a line with the information we want to check:

```
cat kibana/optimize/wazuh-logs/wazuhapp.log | grep DEBUG
{"date":"2019-02-27T12:59:54.180Z","level":"error","location":"DEBUG","message":"KIBANA INTERNAL USER: elastic"}
```

Regards

**Comment by mathieu83470** [comment]
Hello @jesusgn90 ,

I'm trying to resolve it with Elastic support in same time but without sucess for now.... They tell me that it surely comes from the plugin if everything works except the wazuh plugin.

They can reproduce the "authorization error", setting "kibana" user in kibana.yml . It's like my Wazuh plugin can not read the .yml file.

This is the result of your command 
![image](https://user-images.githubusercontent.com/46820664/53495488-59f64180-3aa0-11e9-961e-f5274af892db.png)


With Initializes.js changes I have no "debug" logs
![image](https://user-images.githubusercontent.com/46820664/53495821-ffa9b080-3aa0-11e9-8ec4-37943a99a38d.png)

![image](https://user-images.githubusercontent.com/46820664/53496472-64b1d600-3aa2-11e9-8296-55299ee158af.png)

So, I added your debug code on other function (checkWazuhIndex) with this result
![image](https://user-images.githubusercontent.com/46820664/53496705-dbe76a00-3aa2-11e9-9b57-16584709053f.png)

Kibana.yml
![image](https://user-images.githubusercontent.com/46820664/53496930-5b753900-3aa3-11e9-825d-c0359ce4f661.png)

Thanks again for your time

**Comment by mathieu83470** [comment]
Hi @jesusgn90 

Finally I found my mistake!
I created a keystore during a previous installation and it contained the username and password and apparently keystore bypass kibana.yml config file...deleting it all is OK

![image](https://user-images.githubusercontent.com/46820664/53501468-80ba7500-3aac-11e9-9f8b-6c6e6d20a60c.png)


Thanks for all again

**Comment by jesusgn90** [comment]
Great, I'll keep this conversation in a safe place because this was the very first time I've seen this behavior and it was not so obvious for us, thanks for collaborating in the researching.

Best regards,
Jesús

**Comment by ElZakariyae** [comment]
Hello @jesusgn90 

My ELK installation:
opendistroforelasticsearch-1.1.0-1
opendistroforelasticsearch-kibana-1.1.0-1.x86_64
wazuhapp-3.9.4_7.1.1

I have the same issue as @mathieu83470, i can't access the wazuh from the kibana console. 

Error:
No permissions for [indices:data/read/field_caps]
[2019-09-10T18:45:00,242][INFO ][c.a.o.s.p.PrivilegesEvaluator] [No index-level perm match for User [name=kibanaserver, roles=[], requestedTenant=null] Resolved [aliases=[], indices=[.wazuh], allIndices=[.wazuh], types=[*], originalRequested=[.wazuh], remoteIndices=[]] [Action [indices:data/read/search]] [RolesChecked [own_index, kibana_server]]

Please could you help resolving this issue?

Thank's in advance.

**Comment by commdogg** [comment]
> Hello @jesusgn90
> 
> My ELK installation:
> opendistroforelasticsearch-1.1.0-1
> opendistroforelasticsearch-kibana-1.1.0-1.x86_64
> wazuhapp-3.9.4_7.1.1
> 
> I have the same issue as @mathieu83470, i can't access the wazuh from the kibana console.
> 
> Error:
> No permissions for [indices:data/read/field_caps]
> [2019-09-10T18:45:00,242][INFO ][c.a.o.s.p.PrivilegesEvaluator] [No index-level perm match for User [name=kibanaserver, roles=[], requestedTenant=null] Resolved [aliases=[], indices=[.wazuh], allIndices=[.wazuh], types=[*], originalRequested=[.wazuh], remoteIndices=[]] [Action [indices:data/read/search]] [RolesChecked [own_index, kibana_server]]
> 
> Please could you help resolving this issue?
> 
> Thank's in advance.

I realize this was closed, but I figured out a way past this with:
opendistroforelasticsearch-1.1.0-1 (docker)
opendistroforelasticsearch-kibana-1.1.0-1.x86_64 (docker)
wazuhapp-3.9.4_7.1.1

I edited this file:
`vi /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles.yml`
Added the following:
`# Wazuh access`
`wazuh_full_access:`
`  reserved: false`
`  index_permissions:`
`    -index_patterns:`
`     - ".wazuh*"`
`     allowed_actions:`
`       - crud`
I then added the role to the kibanaserver user in this file:
`vi /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml`
Changed to the following:
`kibanaserver:`
` hash: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX."`
  `reserved: true`
 ` backend_roles:`
 ` - "admin"`
  `- "wazuh_full_access"`
 ` description: "Demo kibanaserver user"`

I then ran the  `securityadmin_demo.sh` script (its in the root directory of the container)
After restarting the kibana and elasticsearch containers its working.  

I feel like the opendistro security plugins aren't documented very well.
V/R
