### ISSUE TITLE
Feature request - Agents tab improvements

### ISSUE THREAD

**Issue by LegitMigue** [wazuh/wazuh-kibana-app#1278]
Hello team,

It would be great to add the following features to the agent search bar:

- Add a filter key for agent name

Example: 
`agent_name: exampleAgentName`

- Add the possibility to use AND/OR logic statements between all the different filter keys

Examples:
`status : active OR group : exampleGroup`
`group : exampleGroup AND group : exampleGroup2 OR group: exampleGroup3`

Thanks!
King Regards.

**Comment by jesusgn90** [comment]
Hi @LegitMigue , 

I think the Wazuh app currently does it, take a look at this screenshot:

![image](https://user-images.githubusercontent.com/8860227/53719114-778b2880-3e5d-11e9-9edd-86224b1f2bab.png)

It adds `AND/OR` depending on the filters you are using. Let me know if it doesn't fit your needs.

Regards,
Jesús

**Comment by LegitMigue** [comment]
Hello @jesusgn90 ,

It allows you to use `OR` statements within the same filter:
![image](https://user-images.githubusercontent.com/10031239/53798395-77139000-3f38-11e9-8390-9cd6dfaed2f6.png)

And it allows you to use `AND` statements within different filters:
![image](https://user-images.githubusercontent.com/10031239/53798541-ba6dfe80-3f38-11e9-8c3b-471509af6fe3.png)

But it doesn't allow you to use `OR` withing different filters nor `AND` in the same filter.
I think this could be very useful in some cases.

What about including a new filter key for agent names?

Thanks!
Regards

**Comment by jesusgn90** [comment]
Hi @LegitMigue,

> But it doesn't allow you to use OR withing different filters nor AND in the same filter.

Future versions, feature request.

> What about including a new filter key for agent names?

Scheduled for 3.9.0, thanks

**Comment by LegitMigue** [comment]
Many thanks!

**Comment by juankaromo** [comment]
Hi @LegitMigue 

Filter key `name` has been included here https://github.com/wazuh/wazuh-kibana-app/pull/1288

Thanks
