### ISSUE TITLE
Agent syncrhonization status not properly updated

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-kibana-app#1302]
Hello team,

I've noticed if I check an agent's configuration while it is not synchronized, the respective icon:
![image](https://user-images.githubusercontent.com/5363328/54144244-9c6a3780-442b-11e9-8bf2-891d64716eb5.png)
 will show as `not synchronized` while I navigate through configuration menus, even if it is already synchronized.

Regards.

**Comment by juankaromo** [comment]
Hi @havidarou 

We've fixed this here https://github.com/wazuh/wazuh-kibana-app/pull/1305

Regards.
