### ISSUE TITLE
Testing 3.9.0 additions

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1316]
Hi team,

Here are some of the main additions for 3.9.0, we must ensure they are working as expected

- [x] Edit configuration for single host architecture
  - [x] Wrong configuration
  - [x] Right configuration
  - [x] Empty configuration
- [x] Edit configuration for cluster architecture 
  - [x] Master
  - [x] Worker
- [x] Edit ruleset
  - [x] Create rule
  - [x] Edit rule
  - [x] Create decoder
  - [x] Edit decoder
  - [x] Create CDB list
  - [x] Edit CDB list
  - [x] Remove files
  - [x] Wrong syntax (common to all use cases)
  - [x] **Right syntax, wrong content (common to all use cases) - _It would be convenient to show only one configuration error if it belongs to the type of file being edited. (to avoid showing rule validation errors in the ossec.conf edition)_**
- [x] Restart 
  - [x] Single host
  - [x] Master
  - [x] Worker
  - [x] Agent
- [x] **Assign/Unassign groups from agents - _When several agents fails in the multiple selector, we need tho show the agents error reasons somehow_**
  - [x] Multiple agents, last group for all of them
  - [x] Multiple agents, last group for some of them
  - [x] Multiple agents, all multigroup
  - [x] Single agent, last group
  - [x] Single agent, multigroup
  - [x] Group default
- [x] New log viewer
  - [x] Sorting
  - [x] Searching
  - [x] **Daemon selector - _An error has ocurred changing deamon. We have to investigate the cause because I haven't been able to replicate it_** 
  - [x] Real-time
  - [x] Node selector
- [x] SCA
  - [x] Policy list
  - [x] Checks list
  - [x] Expand rows
  - [x] Alerts, Visualizations
- [x] Tables
  - [x] **Resizable columns - _Some wrong behavior found on tables with expandible rows_**
  - [x] Dynamic columns
  - [x] Resize window (do not fetch twice)
- [x] Visualizations
  - [x] Keep an eye on recently added visualizations
  - [x] Expand visualization behavior
- [x] Cron jobs for discovering new known fields with no user action required (wazuh-alerts, wazuh-monitoring)
- [x] Configuration on-demand
  - [x] No errors
  - [x] No missing settings
  - [x] Using all the window height when available
  - [x] SCA and recently added settings
- [x] Switch AND/OR agents search bar
- [x] Agent sync status while navigating through config on-demand
- [x] Browser timezone for reporting

Share here the failed points, edit the above list using bold font for failed checks.

Once done, we'll do a new PR to fix all failed checks.

Best regards

**Comment by juankaromo** [comment]
### Testing report
Test passed **42 / 46**
Failed tests that need revision

**Comment by jesusgn90** [comment]
Good job @juankaromo !
