### ISSUE TITLE
UI/UX improvements needed for the incoming release

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1324]
Hi team, here are some new requirements that must be implemented for the next version. 

**View changes**
- [x] Add a way to store table column sizes and visible columns while the user is using the app so we must store that information as a session data in the browser (client-side). Example: agent list table, hide column C, resize column D. Those changes must be persistent while the user is using the app. @juankaromo https://github.com/wazuh/wazuh-kibana-app/pull/1325/commits/65431c9628b937d566aaf4912a7a671454d109d2
- [x] Once you click on an agent to see its detail view, we have a box on top the view where we can see the ID, IP, name, ID, registration date.. just under the "Restart agent" button. Please reduce the font size, and we should try to propose a new design for that box if possible (in a different branch) but definitively we must reduce the font size team. @juankaromo  https://github.com/wazuh/wazuh-kibana-app/pull/1325/commits/6bd42a6655f93c2b23ae8e79979ce7458056aa4e
![image](https://user-images.githubusercontent.com/8860227/54707885-6a9b5400-4b42-11e9-8fc1-9b551047fe9c.png)
- [x] Most of our tables have a "Formatted" link to download the raw data, there is a big white space between the rows and that link, reduce it as much as possible without breaking the table.
![image](https://user-images.githubusercontent.com/8860227/54707970-974f6b80-4b42-11e9-9817-2df748ad0514.png) @juankaromo https://github.com/wazuh/wazuh-kibana-app/pull/1325/commits/b06542c654306b94b02bd94f06b76fc856ad6e0e
- [x] The Discover button next to the agent name in the detail agent view is so small, we should increase its size or replace it with some other component. @juankaromo https://github.com/wazuh/wazuh-kibana-app/pull/1325/commits/6bd42a6655f93c2b23ae8e79979ce7458056aa4e
![image](https://user-images.githubusercontent.com/8860227/54707904-78e97000-4b42-11e9-91f6-6af4581a8982.png)
- [x] Ensure that the next extensions are coming disabled by default: OpenSCAP, Cis-Cat, Osquery, and Virustotal. @juankaromo https://github.com/wazuh/wazuh-kibana-app/pull/1325/commits/37f1e33a2513ee3aa3e9503a7a7199b2179e2001
- [x] Improve empty SCA results message, it's poor. @juankaromo https://github.com/wazuh/wazuh-kibana-app/pull/1325/commits/94eeff38a6c7bde2b7908d5d3cdbafddf08f36d2
![image](https://user-images.githubusercontent.com/8860227/54708057-cb2a9100-4b42-11e9-9707-42396ce744a7.png)
- [x] Replace the SCA icon with some other meaningful icon @juankaromo https://github.com/wazuh/wazuh-kibana-app/pull/1325/commits/6bd42a6655f93c2b23ae8e79979ce7458056aa4e
![image](https://user-images.githubusercontent.com/8860227/54742142-d4f2d980-4bc0-11e9-9b21-3da3bd237669.png) 
- [x] Agents > Inventory. Export CSV for Process and Package tables. @juankaromo https://github.com/wazuh/wazuh-kibana-app/pull/1325/commits/c0c21a8b5f48df0e7a1f5730226cd8d3b084fcdd
- [x] Agents > Inventory. Rename "Network addresses" to "Network settings". Increase div height or fix this table. @jesusgn90 - https://github.com/wazuh/wazuh-kibana-app/commit/df6026d82da9f1dd09f96407c177041e37b8f6b0
![image](https://user-images.githubusercontent.com/8860227/54742259-31ee8f80-4bc1-11e9-9550-f892ae826176.png)

**Dashboard changes**

- [x] Change the color palette for these visualizations, it's hard to see which color refers to each value.@jesusgn90 https://github.com/wazuh/wazuh-kibana-app/commit/4d439c1f048fe1df70f73fadc667146ea7b8c535, https://github.com/wazuh/wazuh-kibana-app/commit/d4fc6153df9fddb5cbea11591757f58e24d749b8
![image](https://user-images.githubusercontent.com/8860227/54707761-1c865080-4b42-11e9-989b-b1f982d05b8e.png)
- [x] No scroll-bars in visualizations, reduce to top 5 or increase the div height (this one is better)@jesusgn90 - https://github.com/wazuh/wazuh-kibana-app/commit/b296b7b9b899fcb19182fa40d50e602e580cb704, https://github.com/wazuh/wazuh-kibana-app/commit/83e7d4e5f493b0ee217f22e064f39a34c343cffd, https://github.com/wazuh/wazuh-kibana-app/commit/9c1c63b34e14db5f5e1d132c06bd4eec9e16275d
![image](https://user-images.githubusercontent.com/8860227/54708024-b8b05780-4b42-11e9-92a2-76dc2d0084cd.png)
- [x] Review the origin of the next four empty visualizations - SCA - Maybe some agents won't have alerts for those visualizations and we may want to replace them with some other ones. Also, we don't want 6 donuts in two rows, replace some of them, please. @jesusgn90  - https://github.com/wazuh/wazuh-kibana-app/commit/98a6a1e72275c017070f4ee1708db49f98ce4a1d
![image](https://user-images.githubusercontent.com/8860227/54708183-1e044880-4b43-11e9-9e87-455788d14cba.png)
- [x] So many donut visualizations in Overview > Integrity monitoring, please replace some of them with some other different visualizations. @jesusgn90 - https://github.com/wazuh/wazuh-kibana-app/commit/4adf83cf5c6a143dd055b368af2cce10114da522
- [ ] Agents status visualization shows half line on top. @jesusgn90
![image](https://user-images.githubusercontent.com/8860227/54741419-b4c21b00-4bbe-11e9-953b-2f72b73e69f3.png)
- [x] Agents status visualization, we need to show data always on this visualization, if the time range is lower than 15 min, we are going to force a minimum of 15 min for this visualization. In addition, the default fetching interval must be 15 min. @jesusgn90 - https://github.com/wazuh/wazuh-kibana-app/commit/36ffb6c8d909007352316f19530c9ef68a03509b, https://github.com/wazuh/wazuh-kibana-app/commit/da9caa44e413c3078777f723ef1dc1a2fbcc6fbb
- [x] "Top 10 Agent alerts" -> "Top 10 agents by alerts number" @jesusgn90 - https://github.com/wazuh/wazuh-kibana-app/commit/b296b7b9b899fcb19182fa40d50e602e580cb704
![image](https://user-images.githubusercontent.com/8860227/54741454-d02d2600-4bbe-11e9-8f40-98d34f93cdf5.png)
- [x] Size for the full-screen mode of visualizations must be reduced. @juankaromo 
![image](https://user-images.githubusercontent.com/8860227/54741526-108ca400-4bbf-11e9-9c7d-ca56ae5c1166.png)
- [x] PCI/GDPR dashboards. Replace visualization "Groups" with "Agents". @jesusgn90 - https://github.com/wazuh/wazuh-kibana-app/commit/8f14f90b46633101e422dab356def6340798cf33
- [x] PCI/GDPR dashboards. Add our old heatmap again, but keep the current dashboard as it, just add it. @jesusgn90 - https://github.com/wazuh/wazuh-kibana-app/commit/8f14f90b46633101e422dab356def6340798cf33
- [x] ~~SCA - Missing `sca.check.id` for this table visualization. @jesusgn90 - https://github.com/wazuh/wazuh-kibana-app/commit/22336fbd8e63b8e8620dfb9f561ed616cced8c81
![image](https://user-images.githubusercontent.com/8860227/54742389-901b7280-4bc1-11e9-8bae-08616cb33b34.png)~~
- [x] SCA - Remove dashboard, leave just the API information. Try to enrich the view with some API information. @jesusgn90 
- [x] "Show state" button is using a full row, we should place it at some other place or change how it looks. @juankaromo https://github.com/wazuh/wazuh-kibana-app/pull/1325/commits/b06542c654306b94b02bd94f06b76fc856ad6e0e
![image](https://user-images.githubusercontent.com/8860227/54742452-c5c05b80-4bc1-11e9-90e4-75d91f5d3f8d.png)

**Edition**

> CDB lists
- [x] Tables must fit full view height. @juankaromo https://github.com/wazuh/wazuh-kibana-app/pull/1325/commits/a5c558c1cc41c5d86f584e16566dda2a21eff65b 
- [x] When there are many results, we should show a "First" and "Last" actions so the user can reach the end easily. @juankaromo https://github.com/wazuh/wazuh-kibana-app/pull/1325/commits/a5c558c1cc41c5d86f584e16566dda2a21eff65b 
- [x] Add download CSV for this table. @juankaromo https://github.com/wazuh/wazuh-kibana-app/pull/1325/commits/a5c558c1cc41c5d86f584e16566dda2a21eff65b 
![image](https://user-images.githubusercontent.com/8860227/54741873-03bc8000-4bc0-11e9-8b58-a736d56b3301.png)
- [x] If "Save list" fails, the button is always loading. @juankaromo https://github.com/wazuh/wazuh-kibana-app/pull/1325/commits/b8b629dbfef53c644a90fea97a4db53104af1397
![image](https://user-images.githubusercontent.com/8860227/54742014-70d01580-4bc0-11e9-850d-083d616bf864.png)
> Ruleset
- [x] Do not format comments @juankaromo **API will solve it**
![image](https://user-images.githubusercontent.com/8860227/54742062-9a893c80-4bc0-11e9-899a-1123c7fdfbe3.png)
- [x]  "Manage CDB lists" @juankaromo  https://github.com/wazuh/wazuh-kibana-app/pull/1325/commits/b8b629dbfef53c644a90fea97a4db53104af1397
![image](https://user-images.githubusercontent.com/8860227/54761108-c1ac3200-4bf1-11e9-843c-a76a5a847ffe.png)

**Other bugs**
- [x] Edit master node configuration, don't save, switch to a worker node, it asks for restarting the worker. @juankaromo https://github.com/wazuh/wazuh-kibana-app/pull/1325/commits/282abb5dba660e55df2e8c7d309ad767cae7f496
- [x] Edit master node configuration, save, switch to a worker node so fast, it throws an error. @juankaromo https://github.com/wazuh/wazuh-kibana-app/pull/1325/commits/282abb5dba660e55df2e8c7d309ad767cae7f496
- [x] Reduce the job queue interval to 15 seconds, so the edge delay for a full restart is 30 seconds. @juankaromo https://github.com/wazuh/wazuh-kibana-app/pull/1325/commits/65431c9628b937d566aaf4912a7a671454d109d2
- [x] The next screenshot occurs when something is wrong regarding of Discover directive and filters and a lot of watchers involved (@jesusgn90). 
![image](https://user-images.githubusercontent.com/8860227/54708087-daa9da00-4b42-11e9-860e-1a5e4505a72b.png)

**Comment by juankaromo** [comment]
Working on this branch https://github.com/wazuh/wazuh-kibana-app/tree/ui-incoming
