### ISSUE TITLE
Feature request: Dark Wazuh app UI

### ISSUE THREAD

**Issue by sergiospa** [wazuh/wazuh-kibana-app#1326]
Hi team,

Recently, an user asked if there's an option to set a dark mode for our Kibana app. I think it would be a great idea, because:

• Brings more customization options.
• Helps against eye fatigue.
• It's cool.

Regards!
Sergio.

**Comment by jesusgn90** [comment]
Hi @sergiospa ,

Next Elastic major version (7.x) will include a global setting for manage themes such as the dark theme for the whole Kibana UI.

Reference: [click here](https://www.elastic.co/guide/en/kibana/7.0/breaking-changes-7.0.html#_dark_mode_is_now_global).

From my view, we should wait until we have it natively.

Regards

**Comment by itpropaul** [comment]
![image](https://user-images.githubusercontent.com/30813009/59286138-2ac5a380-8c3d-11e9-807a-5f2650ef9e04.png)
Can this issue be re-opened as there is now a global setting for Dark Mode. With it turned on, the Wazuh Kibana app is still light.
![image](https://user-images.githubusercontent.com/30813009/59286273-67919a80-8c3d-11e9-9f93-b456f862c4bb.png)
