### ISSUE TITLE
Vulnerability Configuration In Wazuh

### ISSUE THREAD

**Issue by priyeshmali777** [wazuh/wazuh-kibana-app#1330]
Hi

I Configured Wazuh Agent On Ubuntu 16.04 Server For Vulnerability  : =

<wodle name="syscollector">
  <disabled>no</disabled>
  <interval>1h</interval>
  <packages>yes</packages>
</wodle>

then i restart agent
------------------------------------------------------------------------------------------------------
and On the Wazuh Manager I Configured := 

<wodle name="vulnerability-detector">
  <disabled>no</disabled>
  <interval>5m</interval>
  <run_on_start>yes</run_on_start>
  <feed name="ubuntu-16">
    <disabled>no</disabled>
    <update_interval>1h</update_interval>
  </feed>
</wodle>

then i restart wazuh manager.

i also check in Wazuh management -> configuration -> main setting -> Vulnerability detector status  -> enble.

I can't Get Data releated to Vulnerability in Wazuh -> Overview-> Vulnerability ?
where i can find my configuration is correct and i get data releated to the vulnerability.
How Can I solve This Problem ?

**Comment by juankaromo** [comment]
Hi @priyeshmali777 

If you have alerts in Kibana but not of vulnerability, it is possible that the flow from alerts.json to elastic is fine but not the vulnerability configuration. (you can have a look at our documentation which explains how configure it https://documentation.wazuh.com/3.x/user-manual/capabilities/vulnerability-detection.html)


First you need to enable the manager module used to detect vulnerabilities in ossec.conf (`/var/ossec/etc/ossec.conf`)

Now, could you paste here your `<wodle name="vulnerability-detector">` configuration block? (you can use `cat /var/ossec/etc/ossec.conf | grep -i vulnerability -A20`)



On the other hand, you need to enable the agent module used to collect installed packages. To configure agent you can use **agent.conf** 

`/var/ossec/etc/shared/agent.conf`
(https://documentation.wazuh.com/3.x/user-manual/reference/centralized-configuration.html)

or **ossec.conf**
`/var/ossec/etc/ossec.conf`
(https://documentation.wazuh.com/3.x/user-manual/reference/ossec-conf/index.html)

Now, could you paste here your `<wodle name="syscollector">` configuration block? (you can use `cat /var/ossec/etc/shared/agent.conf | grep -i syscollector -A20`)

Let us know the results.
Best regards.

**Comment by priyeshmali777** [comment]
It's Working .
Thanks Dude For Your Help.

**Comment by jesusgn90** [comment]
You are welcome
