### ISSUE TITLE
UX enhancements before next release

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1331]
Hi team, 

- [x] Review that `$emit` and `$broadcast` are being used properly. `$rootScope` -> `$broadcast` -> `$scope`,  `$scope` -> `$emit` -> `$rootScope`. `stopPropagation` must be used if `$emit`, it does not work for `$broadcast`. @jesusgn90 
- [x] Once a user removes last entry from CDB list entries table, the table comes back to the first page. This is wrong, it should keep the current page. @juankaromo 
- [x] Split log and commands in "Configuration > Log collection > Localfiles". If it's a command it's always showing `-` for log related fields. On the other hand, log files are showing `-` for command related fields. @jesusgn90 
- [x] Eradicate "1014 - Error communicating with socket" API error @jesusgn90 
- [x] Remove auto-complete agents search bar. @jesusgn90 
- [x] Redesign rule details cards. @jesusgn90 
![image](https://user-images.githubusercontent.com/8860227/55143851-e8152480-513f-11e9-8cb9-fb08f2de6370.png)
- [x] Rules filters / Decoders filters are a hidden feature right now, we must add more information on how to use them or some tips about them, only developers know about their existence. @juankaromo 
![image](https://user-images.githubusercontent.com/8860227/55143972-24e11b80-5140-11e9-8f29-44e4b4eeb1e3.png)
- [x] Avoid column overlapping in table visualizations.
![image](https://user-images.githubusercontent.com/8860227/55144058-50fc9c80-5140-11e9-9474-8e90435cce7c.png)
![image](https://user-images.githubusercontent.com/8860227/55144113-6a9de400-5140-11e9-8fb8-6fff02e9676c.png)
- [x] ~~Add a way to show SHA1 and MD5 for FIM files table. @jesusgn90~~ (already done)
- [x] Ensure comments are properly formatted when file editor is being used. @juankaromo
- [x] Agent > SCA section. Rename it to "Security Configuration Assessment". Rename tab to "SCA" @jesusgn90 
- [x] Table columns must be clickable for sorting, not just the icon. @jesusgn90 
- [x] List all files in the custom ruleset table, do not allow to edit files that are not custom. @jesusgn90

**Comment by juankaromo** [comment]
Working on this branch https://github.com/wazuh/wazuh-kibana-app/tree/ux-enhancements

**Comment by jesusgn90** [comment]
All progress is now in [react-ui](https://github.com/wazuh/wazuh-kibana-app/tree/react-ui) branch, which includes commits from older branches involved in this task.

The "socket" error has been improved, an additional mechanism was added, also it now tries three times before concluding that it's failed and it recognizes the error codes related to socket problems. This new mechanism is on top of the "status" mechanism. 

All the management > configuration logic is being refactored, so we can debug or modify these sections in an easier way from now and onwards.

Tomorrow is expected to have the "socket", the "edition" and the "configuration" part done.

Regards
