### ISSUE TITLE
Add worker nodes configuration on-demand

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1335]
Right now, our app is showing the well-formatted configuration for the `master` node only. Since it's possible to edit the ossec.conf from a worker node, we should add the "preview" for worker nodes too.

- [x] Add node selector
- [x] Implement missing logic for switching nodes for config on-demand

**Comment by jesusgn90** [comment]
As I've explained in https://github.com/wazuh/wazuh-kibana-app/issues/1331#issuecomment-479563764, this task is almost done. 

- A Wazuh API branch must be merged into "3.9" branch, so we are using it from sources.
- We need to test this because we are refactoring all the controllers from configuration sections.
- We need to create a mechanism for handling switching to a worker node that is currently being restarted (not handled by the Wazuh API right now)

Regards

**Comment by juankaromo** [comment]
Working on the improvements in this branch https://github.com/wazuh/wazuh-kibana-app/tree/node-selector-on-demand
