### ISSUE TITLE
Export agent configuration

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1340]
Currently, we can see the applied configuration for an agent, the goal here is to export that configuration well formatted using the "Reporting" features.

- [x] Adapt the reporting module to receive _agent.conf_ like inputs.
- [x] Export agent configuration well formatted  

Regards

**Comment by juankaromo** [comment]
Working on this branch https://github.com/wazuh/wazuh-kibana-app/tree/export-agent-conf

**Comment by juankaromo** [comment]
**Update**

I have implemented the necessary methods in the backend to render new configuration tables. I have used recursive functions to obtain the tables, and there are only small adaptations for different data structures (arrays, object lists), and design aspects.

**Comment by juankaromo** [comment]
**Update**

Most of the configuration modules are already shown. We need to think about how to visualize more complex configurations in a generic way so that use it in other exports.

**Comment by juankaromo** [comment]
**Update**

I have finished checking all possible data structures, and they are already displayed correctly. I would still have to introduce the equivalence of the missing labels and take the configuration object to the backend.

Here is an example of the exported PDF (first iteration)

[wazuh-agent-002-configuration-1557760113.pdf](https://github.com/wazuh/wazuh-kibana-app/files/3173590/wazuh-agent-002-configuration-1557760113.pdf)

**Comment by juankaromo** [comment]
**Update**

I have refactored the report module for the agent configuration, taking the object to the backend, putting the missing labels and some minor fixes. 

Here is an example of the exported PDF

[wazuh-agent-002-configuration-1557833429.pdf](https://github.com/wazuh/wazuh-kibana-app/files/3177378/wazuh-agent-002-configuration-1557833429.pdf)

**Comment by juankaromo** [comment]
**Update**

This lacks affection in the details @juankaromo e.g:

We don't want technical words:

![image](https://user-images.githubusercontent.com/8860227/57770469-a7359700-7710-11e9-87d8-94e5765f345d.png)

So much white spaces between columns:

![image](https://user-images.githubusercontent.com/8860227/57770283-3d1cf200-7710-11e9-8d27-06c9e8b9a4ac.png)

Unnecessary word breaking:

![image](https://user-images.githubusercontent.com/8860227/57770432-9422c700-7710-11e9-9f71-4efca20711c1.png)

This is weird:

![image](https://user-images.githubusercontent.com/8860227/57770746-4c506f80-7711-11e9-8bf7-ecde7e30e84f.png)

Please guys, more love to your work!

**Comment by juankaromo** [comment]
Version with fixes 
[wazuh-agent-002-configuration-1557932350.pdf](https://github.com/wazuh/wazuh-kibana-app/files/3183140/wazuh-agent-002-configuration-1557932350.pdf)

**Comment by juankaromo** [comment]
**Update**

Today I modified the module with some changes that have been requested:
        - The logs are now shown grouped by log type.
        - Monitored directories are now displayed in a yes/no matrix

Here is an example of the exported PDF
[wazuh-agent-001-configuration-1558626138.pdf](https://github.com/wazuh/wazuh-kibana-app/files/3213066/wazuh-agent-001-configuration-1558626138.pdf)

**Comment by juankaromo** [comment]
**Update**

Some changes have been applied to the monitored directories table in order to reduce its width. Changes how avoiding some columns, or reduce the titles adding a legend. And now it looks like this:

![image](https://user-images.githubusercontent.com/21195730/58470523-292ab480-8142-11e9-9e88-8f7625e7e932.png)

Here is an example of the exported PDF of this iteration
[wazuh-agent-001-configuration-1559036854.pdf](https://github.com/wazuh/wazuh-kibana-app/files/3227055/wazuh-agent-001-configuration-1559036854.pdf)

**Comment by jesusgn90** [comment]
Please paste screenshot from the button where you start the report and add one more screenshot about the rendering process. Thanks

**Comment by juankaromo** [comment]
![report configuration](https://user-images.githubusercontent.com/21195730/58951592-d1b7c480-8791-11e9-93b5-e57043badbfe.gif)

**Comment by jesusgn90** [comment]
- Remove the "Generating PDF document..." message
- Replace the icon with the same as we are using for "Formatted"
- Move the text to the right of the blue bar
- Replace the text "Generate configuration report" with "PDF"
- While the PDF is being generated the download icon is a spinner

**Comment by juankaromo** [comment]
Hi @jesusgn90 

Following your advice, I've made the process cleaner

![report2](https://user-images.githubusercontent.com/21195730/58960343-4f39ff80-87a7-11e9-8e02-afc042b35f5b.gif)
