### ISSUE TITLE
Export group related information

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1341]
We have no way to export a group and its related information such as the agents or the files included in that group. We can do it by parts but definitively we want to collect all the information into one well-formatted exportable PDF.

Tasks:

- [x] Adapt the reporting module 
- [x] Minimum info
  - [x] Group name
  - [x] Configuration 
  - [x] Agents in the group

Regards

**Comment by juankaromo** [comment]
**Update**

The module has been adapted to accept this type of report. At the moment I have generated a first pdf with the table of agents. I have to make some corrections in the way the configuration object is painted so that it doesn't show up with errors.

**Comment by juankaromo** [comment]
**Update**

I have already managed to show all the configurations grouped by their filters, here is an example of this first iteration:

[wazuh-group-default-configuration-1558626305.pdf](https://github.com/wazuh/wazuh-kibana-app/files/3213046/wazuh-group-default-configuration-1558626305.pdf)

**Comment by jesusgn90** [comment]
No numbered titles:

![image](https://user-images.githubusercontent.com/8860227/59023941-1d7d7300-8851-11e9-8330-4b024a03afab.png)

 Move the agent list to the end of the file:

![image](https://user-images.githubusercontent.com/8860227/59023976-2ff7ac80-8851-11e9-9cda-03df7ec6f6a1.png)

Human readable please:

![image](https://user-images.githubusercontent.com/8860227/59024021-43a31300-8851-11e9-878a-3650896b70fa.png)

This should be a table:

![image](https://user-images.githubusercontent.com/8860227/59024042-4dc51180-8851-11e9-831f-d41dd6e5b69b.png)

Please test it with a huge amount of configurations, also try it with ~14K agents.

Regards

**Comment by juankaromo** [comment]
**Update**

Today I made the changes that have been requested. I show the table of agents at the end in case it is too long ~1k, the numbers have been removed and the logs have been grouped.

This is an example:

[wazuh-group-default-configuration-1559831932.pdf](https://github.com/wazuh/wazuh-kibana-app/files/3262118/wazuh-group-default-configuration-1559831932.pdf)

**Comment by juankaromo** [comment]
**Update**

Today I have been adapting some modules of the report that wasn't working properly. Also, other modules as `Labels` weren't being shown with the logic of the rendering method. That was fixes also.

Here is an example of this iteration result
[wazuh-group-default-configuration-1559912411.pdf](https://github.com/wazuh/wazuh-kibana-app/files/3266000/wazuh-group-default-configuration-1559912411.pdf)
