### ISSUE TITLE
Filters for ruleset are broken if looking custom rules

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1347]
Hi team,

1. Go to Management > Ruleset
2. Let's say the next filter: `path:etc/foo`
3. Turn on `Custom rules` switch
4. Filters are not applied

Regards

**Comment by juankaromo** [comment]
Solved in Splunk here https://github.com/wazuh/wazuh-splunk/commit/3cbc239f363d88eff24cf4ceca6d5dd83ac01efa

**Comment by juankaromo** [comment]
This issue has been added and solved in this one #1361

**Comment by jesusgn90** [comment]
Thanks @juankaromo
