### ISSUE TITLE
Do not allow to use the "AND" operator for the same field in agents search bar

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1353]
Hi team,

Latest agents search bar improvements were awesome but we must avoid using the _AND_ operator for the same field.

E.g:

```
node_name: wazuh AND node_name: foo
```

That query won't show anything because it's impossible.

Regards

**Comment by juankaromo** [comment]
Solved in Splunk here https://github.com/wazuh/wazuh-splunk/commit/ce5b7eda35af015a68010cd5b48d01576b21da25
