### ISSUE TITLE
Docker information

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#1355]
Hi team,

It would be nice to create a Docker dashboard section and a Docker configuration section.

- [x] Docker dashboard.
- [x] Docker configuration.

Regards,

**Comment by jesusgn90** [comment]
**Update**

Configuration on demand has been added  here https://github.com/wazuh/wazuh-kibana-app/pull/1365/commits/c6205ffaab15a8a8d871ba5efe9b9181799dac33

**Comment by jesusgn90** [comment]
**Update**

Dashboards have been added here https://github.com/wazuh/wazuh-kibana-app/pull/1367, including new known fields, icon, and visualizations.
