### ISSUE TITLE
Custom graphs fed by Wazuh API [first iteration]

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#1358]
Hi team,

It would be nice if we started implementing custom graphs to show data from our Wazuh API. In this **first iteration**, we would have to achieve the following points:

- [x] Load `angular-chart` library

**Test it and add some graphs with some useful API data in**
- [x] _Agents Preview_
- [x] _Agents SCA_

Regards.

**Comment by jesusgn90** [comment]
**Update**

In order to use this library, the only thing we need is to import it at the very top level loader (app.js), then inject it into the app modules, done here https://github.com/wazuh/wazuh-kibana-app/commit/ca4cd28a142aed51029c605492d0732e254c7a10.

```js
// angular-charts.js
import 'angular-chart.js';

// Set up Wazuh app
const app = uiModules.get('app/wazuh', ['ngCookies', 'ngMaterial', 'chart.js']);
```

**Comment by jesusgn90** [comment]
**Update**

Using the library in some view:

```html
<canvas 
     id="bar" 
     class="chart chart-bar"  
     chart-data="data" 
     chart-labels="labels" 
     chart-options="options" 
/>
```

Under the hood, it's using Chart.js, so we can take its docs as reference: https://www.chartjs.org/docs/latest/

**Comment by jesusgn90** [comment]
**Update**
Added Wazuh API charts for _Agents > SCA_ and _Agents preview_
