### ISSUE TITLE
Change 'Configuration not available' message.

### ISSUE THREAD

**Issue by adri9valle** [wazuh/wazuh-kibana-app#1360]
Hi team,

Since we are working in the next release, there are several changes in the *Management > Configuration* section. 

When you click over any module configuration and this module is not configured, the 'Configuration not available message' is wrong now, we should change it.

![image](https://user-images.githubusercontent.com/7983984/55882904-950e8900-5ba5-11e9-9d1c-a86aaeee7890.png)

- [x] Change the message when the configuration is not available.

Regards,

**Comment by jesusgn90** [comment]
**Update**

Small fix has done here https://github.com/wazuh/wazuh-kibana-app/commit/0d346e2f608938f0c75d520b59caeb5094758197#diff-7c0e2c629bece33ee248372b810c57fe, now we are not showing weird API errors and being more precise.
