### ISSUE TITLE
Some fixes after general review

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#1361]
After doing a global review of our apps, we have detected the following improvements that need to be implemented:

**Priority**
- [x] Change `ColResize` library to fix table resize behavior

**Other issues**
- [x] Expand the visualizations by clicking on the whole card header in Overview General, as it is only in agents.
- [x] The list of group agents has to be resizable and have custom columns.
- [x] The scroll in preview file of a group that is not agent.conf is broken, in addition, this container must fit all the possible height inside the view.
- [x] In the decoder details the regex comes out when we already have it on a separate card. Also, it is necessary to update the icons.
- [x] If in the APIs view I delete the last one I have a white box, however, if I enter the first time I do not.
- [x] In the agent search bar, the recycle bin should be replaced by an X and displayed only if there is content.
- [x] Node selector must not appear duplicated in `ossec.conf` editor view.
- [x] Add SCA regex fields in the checks table. Needs API implementation.
- [x] Filters for ruleset are broken if looking custom rules #1347

Regards.

**Comment by juankaromo** [comment]
Working on this branch https://github.com/wazuh/wazuh-kibana-app/tree/review-fixes

**Comment by juankaromo** [comment]
**Update**

The main task performed today was to the replacement of the colResize library with the jQuery resizable() method, to avoid wrong behaviors when resizing table columns. On the other hand, the rest of the tasks of the issue have been implemented in its entirety. It remains to review the dashboards of Osquery.

**Comment by jesusgn90** [comment]
_Expand the visualizations by clicking on the whole card header in Overview General, as it is only in agents._ Overview > General was the only one affected view, missing `octrl.` before `expand(n)` https://github.com/wazuh/wazuh-kibana-app/commit/1df0f7a49bd05e44bb3a0a3cfddb62f22ad35f0b

**Comment by juankaromo** [comment]
The weird behavior when resizing tables with the new jQuery method was due to the `euiTable--responsive` class that was being applied to the tables. https://github.com/wazuh/wazuh-kibana-app/pull/1362/commits/c2eb3225ebf3465b8e8b1ce4eaefc29d7e62bb9c

**Comment by juankaromo** [comment]
Issue #1347 (Filters for ruleset are broken if looking custom rules) has been solved here https://github.com/wazuh/wazuh-kibana-app/pull/1362/commits/980eb55667d6b313dccb95fd183a8cde4fe020c6
