### ISSUE TITLE
FIM files table is broken for Windows agents

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1368]
| Wazuh | Elastic | Revision |
|-----------|----------|--------------|
| 3.9.0    | 6.7.1   | 0430        |

Hi team, it seems like we introduced a bug with the latest table changes, as you can see, the FIM files table for Windows agents is broken:

![image](https://user-images.githubusercontent.com/8860227/56079194-5836d200-5df1-11e9-8e05-3630bb673ec4.png)

Note: Linux agents are fine

Proposal:

- [x] Add pagination, first and last
- [x] Truncate/Wrap long fields, add a tooltip 

Regards

**Comment by juankaromo** [comment]
Solved here https://github.com/wazuh/wazuh-kibana-app/commit/1e2a6df23973b7d03f79bc785389503361246aa2
