### ISSUE TITLE
Do not show pagination for one page tables

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1369]
Currently, we are showing `1` for tables with just one page of items. We should not show the pagination in those cases.

![image](https://user-images.githubusercontent.com/8860227/56079275-a8626400-5df2-11e9-8195-c0954314ddbd.png)

Regards

**Comment by juankaromo** [comment]
Solved here https://github.com/wazuh/wazuh-kibana-app/pull/1362/commits/196c5b717583032798da7791fa4f90ec06397f68
