### ISSUE TITLE
[Ruleset] Show file content for all ruleset files

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1370]
The files table we have for showing rules files must allow the user to see the XML content of those files. The user uses to copy existing rules before create/edit local rules.

![image](https://user-images.githubusercontent.com/8860227/56113373-f9429b80-5f5d-11e9-9552-594e5cefa2a8.png)

- [x] Instead of a `-`, we should show an _eye_ icon.
- [x] Once the _eye_ is clicked, show the XML content for that file.

Regards

**Comment by juankaromo** [comment]
Getting XML from a non-local file is pending-api https://github.com/wazuh/wazuh-api/issues/369

**Comment by juankaromo** [comment]
**Update**

The logic to open the editor if in a local rule or decoder, or to open a code viewer if it is a non-local rule has been implemented. Calls to get the XML from non-locals are pending API.

**Comment by juankaromo** [comment]
**Update**

Calls to get the XML from non-locals have been implemented. A flag called 'readOnly' has been added to 'ruleset-handler' service in order to send requests to `/etc/rules` in case of local rules, or to `/ruleset/rules` in case of non-locals.
