### ISSUE TITLE
[visualize] Fix top line of "Agents status" visualization

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1379]
Hi team, we need to found a way to make the top line be fully displayed and not just half of the line as the screenshot below:

![image](https://user-images.githubusercontent.com/8860227/56146473-90334600-5fa6-11e9-8395-d65ceccc047b.png)

Regards

**Comment by juankaromo** [comment]
**Update**
Fixed the problem of 'covered dots' with these patch styles:

```
.visChart__container .chart > svg{
  position: absolute;
}

.visChart__container svg g.points.line, 
.visChart__container svg g.points.area {
  display: contents;
}
```

**Comment by jesusgn90** [comment]
The next line is unsafe:

```js
if ((visParams || {}).valueAxes && (this.visData.series || [])[0]) {
```
Replace it with the next ones:

```js
const valueAxes = (visParams || {}).valueAxes || false;
const hasSeries = ((this.visData || {}).series || []).length;
if (valueAxes && hasSeries) {
```
