### ISSUE TITLE
Unify timezone for all dates

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1380]
Hi team, we have some dates being shown using the timezone from where they are generated, it would be nice if we can apply the browser timezone for all those dates.

Here is an example of a wrong date:

![image](https://user-images.githubusercontent.com/8860227/55144113-6a9de400-5140-11e9-8fb8-6fff02e9676c.png)

How to get the offset:

```js
const offset = new Date().getTimezoneOffset();
console.log(offset);
```

We did something similar for https://github.com/wazuh/wazuh-kibana-app/issues/1308, just extend that issue for all dates.

Regards

**Comment by juankaromo** [comment]
**Update**

This function has been used to add the timezone offset to data date:

**Comment by juankaromo** [comment]
**Update**

The dates of the scans, the dates included in the `wz-table`, and the dates of the logs have been adapted.
