### ISSUE TITLE
[visualize] Review Osquery dashboards

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1381]
The Osquery dashboards may have some bugs regarding of the visualizations.

- [x] Review all known fields for Osquery
- [x] Review all visualizations, some of them may be using fields that Wazuh is no longer using.
- [x] Add/Remove some visualizations for improving those dashboards.

Regards

**Comment by juankaromo** [comment]
Working on this branch https://github.com/wazuh/wazuh-kibana-app/tree/osquery-dashboard

**Comment by juankaromo** [comment]
**Update**

Some visualizations have been updated, and other ones have been added in both overview and agents dashboards. The known fields for Osquery have been reviewed and added news.
