### ISSUE TITLE
[elastic-7] Adapt the Wazuh app for Kibana 7.0.0

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1385]
~~__Blocked by https://github.com/wazuh/wazuh-kibana-app/issues/1382__~~

Main tasks:

- [x] _.kibana_ indices
- [x] Discover
- [x] Visualizations
- [x] Index patterns
- [x] Production package installation
- [x] Server side
- [x] Client side

Further details may be added.

Regards

**Comment by jesusgn90** [comment]
# Update 24/04/2019

A new branch has been added: [elastic-7](https://github.com/wazuh/wazuh-kibana-app/tree/elastic-7).

After some commits (from https://github.com/wazuh/wazuh-kibana-app/commit/ede4371285473ff3f0ae481fda48088ab4fd9443 to https://github.com/wazuh/wazuh-kibana-app/commit/53ce2797579f75b793aec8b37d1e9763deb9e92f) we have a Wazuh app that seems to be working as expected for the most basic actions that are expected to work after the modifications.

- The index patterns are being created and updated properly.
- Wazuh app related indices are being created and updated properly.
- Visualizations and Discover directives are working as expected.
- I've also tried to create a production package and it was installed successfully.
- Debug level is set to true by default for this app (`tailf optimize/wazuh-logs/wazuhapp-plain.log`)
- Restored auto-calc for the visualizations interval.

Here we can see some screenshots:

![image](https://user-images.githubusercontent.com/8860227/56671117-5b18a900-66b4-11e9-9fb4-9f3d77f2c176.png)

![image](https://user-images.githubusercontent.com/8860227/56671165-6ec40f80-66b4-11e9-934d-07f9981ad46c.png)

## Some notes

- Filters have changed, we need to investigate how to create no removable filters again.

![image](https://user-images.githubusercontent.com/8860227/56671779-7e902380-66b5-11e9-8ea3-b7feec63ebae.png)

- Most of our styles and fonts are broken.

![image](https://user-images.githubusercontent.com/8860227/56671254-9c10bd80-66b4-11e9-98b8-93cd99939563.png)

- All the old logic for reindexing from 5.x to 6.x has been removed.
- Some of the Kibana modules we were overwriting are now removed (no longer needed to overwrite some of them).
- They added an info bar on top of all the views, also it shows the app name, our app is using another app named Discover and sometimes the top bar takes that as the app name, we should review this.

![image](https://user-images.githubusercontent.com/8860227/56672218-4f2de680-66b6-11e9-9693-1295062c3c01.png)

## About the installation

- No need for increasing the memory heap limit.
- Instant installation. Now Kibana optimizes much faster than before, also it does all the optimizations at the same time once it starts, so the plugin installation is now less than a second.

```
sudo -u kibana /usr/share/kibana/bin/kibana-plugin install file:///tmp/wazuh-3.9.0.zip 
```

## About the upgrade procedure

- Not tested yet, however, I modified all the mapping for the app related indices and a few other internal things that probably will cause a breaking change from previous versions.

## Status

Basic usage is available, you can go ahead and build an alpha package to explore it on your own but it's still broken and other bugs will probably appear soon, not so much testing so far, just adapting it.

In any case, you may want to be a pioneer:

- https://github.com/wazuh/wazuh-tools/tree/master/vagrant/elastic/elastic-7-tmp 
- https://github.com/wazuh/wazuh/tree/elastic-7/extensions 
- https://github.com/wazuh/wazuh-kibana-app/tree/elastic-7

If you are more than a simple pioneer, Kibana dev is still using the next command:

```
yarn start --no-base-path --server.host="0.0.0.0" --elasticsearch.hosts="http://localhost:9200"
```

**Comment by jesusgn90** [comment]
# Update 25/04/2019

Some commits were pushed for correcting styles, but there are still some parts that lost their styles. Also, some of them have been cherry-picked to [3.9-6.7](https://github.com/wazuh/wazuh-kibana-app/tree/3.9-6.7).

Today I've been using the app, mainly focused on Kibana/Elastic related parts and it looks fine so far. Trying some filters combinations such as negation, pinned filters along with other combinations and they are working as expected.

**Dark mode**

The new introduced optional dark theme for Kibana is breaking all our UI, see this screenshot for a better understanding:

![image](https://user-images.githubusercontent.com/8860227/56749242-a220a000-6781-11e9-84ec-6b447b2e4d1b.png)

I've been researching and we have two options:

1. Modify Kibana related styles, enforcing our style, the quick solution.
2. Have a dynamic them as Kibana does, not so quick but the right solution.

**Removable implicit filters**

After some researching about the filters I've concluded that we should overwrite the filter React component so we can handle its properties, then we'd add a new condition for _implicit filters_ such as _cluster.name_. This is the affected component https://github.com/elastic/kibana/blob/v7.0.0/src/legacy/ui/public/filter_bar/filter_item.tsx

**Located how to modify the top bar app title**

![image](https://user-images.githubusercontent.com/8860227/56749665-75b95380-6782-11e9-97b3-f68237e42da1.png)

https://github.com/wazuh/wazuh-kibana-app/blob/36fbfe98b217911849af1c75ca6ed8a8876c3a46/public/kibana-integrations/kibana-discover.js#L204

**Other**

Fully removed `calcWzInterval` function, no longer needed, even for initialization time (Discover related, https://github.com/wazuh/wazuh-kibana-app/commit/36fbfe98b217911849af1c75ca6ed8a8876c3a46), we may want to make a backport for 6.7.x, I'll test it.

**Comment by jesusgn90** [comment]
**Some Kibana known issues that still exist**

- Auto-refresh is broken out of the Wazuh app https://github.com/elastic/kibana/issues/34507
- We still need to avoid updating field score https://github.com/elastic/kibana/issues/22426

**Comment by jesusgn90** [comment]
**View single document & Surrounding documents**

They are working as expected:

![image](https://user-images.githubusercontent.com/8860227/56751783-26c1ed00-6787-11e9-825e-67d33fd81a03.png)

![image](https://user-images.githubusercontent.com/8860227/56751840-3e997100-6787-11e9-8758-f6042e0ee6eb.png)

**Comment by jesusgn90** [comment]
## Update 26/04/2019

**Implicit filters**

After some researching inside the Kibana filter bar component, I've managed to solve the issue about removing implicit filters, this is a good improvement, some of the things that were broken are now fixed here https://github.com/wazuh/wazuh-kibana-app/commit/1a0a36cc26b85d661d02a2745662987afb2adfdc

**Comment by shawnbyday** [comment]
@jesusgn90 is there something special I need to do to be able to install this version to test it?
