### ISSUE TITLE
[elastic-7] X-Pack, Search Guard authentication and roles

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1387]
We need to ensure that our docs for enabling Elasticsearch security features are working as expected, this includes the next tasks:

- [x] X-Pack full admin
- [x] X-Pack limited roles
- [ ] Search Guard full admin __Blocked, there is no Search Guard 7.0.0 yet__
- [ ] Search Guard limited roles __Blocked, there is no Search Guard 7.0.0 yet__

Regards

**Comment by jesusgn90** [comment]
# Update 23/03/2019

## X-Pack security

I've started with the most simple X-Pack security implementation:

- 1 x ES node with security enabled
- 1 x Logstash authenticating against the ES node
- 1 x Kibana instance with login required
- Using the user `elastic` for all components.

Now I've just tried the standard password generation command:

```
/usr/share/elasticsearch/bin/elasticsearch-setup-passwords auto
```

It worked, then I've configured all the components as we used to do it before 7.x.

For Kibana, I've added the next lines to its configuration:

```yaml
# /etc/kibana/kibana.yml
...
xpack.security.enabled: true
elasticsearch.username: "elastic"
elasticsearch.password: "my-password"
```

For Logstash, I've added the credentials to the output section of its configuration:

```rb
# /etc/logstash/conf.d/01-wazuh.conf
...
output {
    elasticsearch {
        ...
        user => "elastic"
        password => "my-password"
    }
}
```

For Elasticsearch, I've enabled the security adding the next line to its configuration:

```yaml
# /etc/elasticsearch/elasticsearch.yml
...
xpack.security.enabled: true
```

Restart Elasticsearch, wait until it was ready, then restart Logstash and Kibana.

It worked as expected for Kibana:

![image](https://user-images.githubusercontent.com/8860227/56586688-731ef880-65e0-11e9-88ae-33fabda2440d.png)

Logstash is being authenticated, I have events:

![image](https://user-images.githubusercontent.com/8860227/56586849-bf6a3880-65e0-11e9-99e2-cc959de7e40b.png)

**Comment by jesusgn90** [comment]
# Update 25/04/2019

Today I've been playing around with the Wazuh app + Security, the app is working as expected (`elastic` user for both client and server side):

![image](https://user-images.githubusercontent.com/8860227/56752850-9042fb00-6789-11e9-9d86-a9563191940d.png)

![image](https://user-images.githubusercontent.com/8860227/56752886-a2bd3480-6789-11e9-89ed-3c3107907fa7.png)

This is a good thing cause the app server side is handling all the requests including security in the right way.

**Other**

After deleting the app related indices:

```
curl -XDELETE localhost:9200/.wazu*,.kiban* -u elastic:mypassword
```

The app is recovering all the indices just fine, this is important since the app is using the internal X-Pack user for that kind of actions such as creating indices, updating them, etc.

**Comment by juankaromo** [comment]
# Update 29/04/2019

Today I've been testing with the granular access roles in the Wazuh app. Now when we create new roles we have to indicate the minimum level of permission to access the spaces. If we leave the default level `none` it is not possible to log in with any user who has that role, getting this error: 

`{"statusCode":403,"error":"Forbidden","message":"Forbidden"}`

We need to establish a `read` level, which allows view objects and applications within all spaces, or the `all` level which allows view, edit, and share objects and apps within all spaces.

This is set in the create/edit role view:

![image](https://user-images.githubusercontent.com/21195730/56907602-e626e400-6aa4-11e9-9bd7-229888b311ae.png)

Once we can login, and test the permissions, we can check that they work correctly. A user who doesn't have permissions in the `.wazuh` index will get this warning in the API management window:

![image](https://user-images.githubusercontent.com/21195730/56906719-1a99a080-6aa3-11e9-9128-d5e5541d96b7.png)
