### ISSUE TITLE
Missing AWS Services configuration

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-kibana-app#1392]
Hi team,

It seems that the app's not currently displaying the AWS services section of the `aws-s3` wodle:

![image](https://user-images.githubusercontent.com/10210567/56204070-dfc94e80-6046-11e9-849b-5626e3f2ab2f.png)

As detailed above, there is only one `Buckets` tab.

If that information is requested to the API, indeed there is a section list named `services`:

```
"services": [
            {
              "type": "inspector",
              "access_key": "---------",
              "secret_key": "---------"
            }
          ]
``` 

Also, I've noticed that the key values of the services section are visible _plaintext_ in the Dev Tools section.

Cheers

**Comment by jesusgn90** [comment]
Thanks @manuasir !

Tasks:

- [ ] Hide both `access_key` and `secret_key` (replace with `******`)
- [ ] Add services sub-tab inside AWS configuration tab

**Comment by jesusgn90** [comment]
Fixed https://github.com/wazuh/wazuh-kibana-app/pull/1393
