### ISSUE TITLE
Fixes in agent SCA section

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#1399]
Hi team,

We've found some points that need fixing in agent's SCA view:

- [X] Weird flick navigating between policies https://github.com/wazuh/wazuh-kibana-app/commit/0560efc8e4f0a743dcfafbe5268f22af0e3ecfbe
- [X] Replace Rule(s) with Check, if there are two or more checks, it must say Checks, review this behavior for all the fields, we don't want (s). e982f07

Regards.

**Comment by juankaromo** [comment]
Weird flick navigating between sections has been solved here https://github.com/wazuh/wazuh-kibana-app/commit/0560efc8e4f0a743dcfafbe5268f22af0e3ecfbe

**Comment by jesusgn90** [comment]
- [ ] Replace `Rule(s)` with `Check`, if there are two or more checks, it must say `Checks`, review this behavior for all the fields, we don't want `(s)`.

**Comment by juankaromo** [comment]
> Replace `Rule(s)` with `Check`, if there are two or more checks, it must say `Checks`, review this behavior for all the fields, we don't want `(s)`.

Solved here https://github.com/wazuh/wazuh-kibana-app/pull/1397/commits/e982f072488e1cc415c7ff5f66047d67d2dfe09e
