### ISSUE TITLE
support kinaba 5.3.1????

### ISSUE THREAD

**Issue by jzxrm2006** [wazuh/wazuh-kibana-app#14]
support kinaba 5.3.1?

**Comment by alberpilot** [comment]
Hello Jzxrm2006

  We have developed wazuhapp for Kibana 5.3.1 and is under testing actually. It will be available really soon. 

Best regards,

**Comment by snaow** [comment]
@jzxrm2006 

New version is available, for 5.3.1 and 5.3.2.

Thanks,
Pedro.
