### ISSUE TITLE
Error adding agent to group

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-kibana-app#1416]
|Wazuh version|Install method|Platform|
|---|---|---|
| 3.8.2 | Packages | - |

Hello team,
sometimes, when adding an agent to a group I get the following response:

```
Warning. Group has been updated but an error has occured with the following agents
```

I've traced that error here: https://github.com/wazuh/wazuh-kibana-app/blob/v3.8.2-6.7.1/public/controllers/management/groups.js#L502

But I am not sure if it is directly related to the Wazuh API response or bad handling on the app code.

Regards.

**Comment by jesusgn90** [comment]
Hi @havidarou,

The Wazuh app is just telling you what the Wazuh API said about some agents. I think this should be debugged at Wazuh manager level in combination with the Wazuh API on debug mode. In any case, we'll review this situation in case we reproduce it, thanks for reporting it.

Regards
