### ISSUE TITLE
Dev Tools typo on API timeout

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-kibana-app#1428]
https://github.com/wazuh/wazuh-kibana-app/blob/4a3e6def7e7b13458a74a3f76d7e03397008995a/public/controllers/dev-tools/dev-tools.js#L584
Should be "Wazuh API is not reachable. Reason: timeout."

**Comment by jesusgn90** [comment]
Fixed https://github.com/wazuh/wazuh-kibana-app/commit/fdb8c59a1da1d105237d0659ac78e4595425103a
