### ISSUE TITLE
Improvements to lists editor

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-kibana-app#1438]
With the release of Wazuh version 3.9.0 the CDB lists are editable from within the app (Management→Ruleset→lists) it has given this Wazuh feature a much welcome user-friendly interface.

Once the lists are edited and saved it gives the handy option to perform a restart but not the option to compile the lists.
In order for a list to be run it is still necessary to run `/var/ossec/bin/ossec-makelists` on the manager. Adding another button to that effect in the list editor would complete the experience.

Additionally, the interface lacks the ability to accept pasting of large lists. It would be nice to be able to toggle between a cell-editing interface as it is now and a plain-text box where the list could be directly pasted. 

If only one is going to be kept, the plain-text option would be preferable.

**Comment by juankaromo** [comment]
**Update** As of 15/05 compile lists call it is not even planned by the API team. I mark this issue as **pending-api**

**Comment by jctello** [comment]
Correct. There's an issue for that: https://github.com/wazuh/wazuh/issues/3037.
Although maybe the correct place would be in the https://github.com/wazuh/wazuh-api repository.
Thanks

**Comment by juankaromo** [comment]
The part of to accept pasting of large lists in plain-text is implemented in this branch https://github.com/wazuh/wazuh-kibana-app/tree/plain-list-management

**Comment by jctello** [comment]
This PR should make it so lists are compiled on restart: https://github.com/wazuh/wazuh/pull/3897

**Comment by jctello** [comment]
As mentioned lists are now compiled on manager restart and list files can be uploaded.
