### ISSUE TITLE
Can't scroll to bottom after saving manager configuration

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-kibana-app#1439]
After saving the configuration on the manager the bottom of the configuration can no longer be accessed by scrolling.
![manager-config-scroll-1](https://user-images.githubusercontent.com/36071202/57462923-14ad7780-727a-11e9-8533-44fabae22db9.gif)
Selecting the text or reloading the page fixes this, but it is a minor inconvenience.

This is seen on both Firefox and Chromium (likely on all major browsers).

**Comment by juankaromo** [comment]
Hi @jctello 

This issue is solved here https://github.com/wazuh/wazuh-kibana-app/pull/1441. To do this we have inserted in 6.7.x a new functionality added for 7.0.x. (XML editors and visors dynamic heights).

Regards.
