### ISSUE TITLE
Feature Request - Ability to create new custom ruleset files

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-kibana-app#1443]
The ability to edit the ruleset through the Wazuh Kibana App greatly improves the experience of expanding Wazuh's capability for ingesting new types of logs, specially given the syntax checking features this adds over simply editing the rule files directly.

Wazuh also has the possibility of having more than one rules or decoders file, which helps organize rules and promotes better coding practices.

It would be great that in the same way that new list files can be added to the ruleset from within the App that also new rules and decoders could be added as well.

**Comment by adri9valle** [comment]
**Update**

The capability to create new ruleset files already exists, the problem is that in the view the variable that the `ng-show` checks if the **adminMode** is enabled in order to allow create a new file is badly referenced.

**Comment by adri9valle** [comment]
**Update**

Working on this issue I find out that the rules, decoders and CDB lists cannot be deleted

![no_delete](https://user-images.githubusercontent.com/7983984/60440634-85876500-9c15-11e9-902a-e5532d5aa0ae.gif)

**Comment by jctello** [comment]
This is available in 3.10 so it can be closed. 
Thanks for the great work team!
