### ISSUE TITLE
Visualize: "field" is a required parameter

### ISSUE THREAD

**Issue by yingshang** [wazuh/wazuh-kibana-app#145]
Saved "field" parameter is now invalid. Please select a new field.
Visualize: "field" is a required parameter
```
TypeError: "field" is a required parameter
    at FieldParamTypeProvider.FieldParamType.write (http://192.168.8.137:5601/bundles/wazuh.bundle.js?v=16337:67:978625)
    at http://192.168.8.137:5601/bundles/wazuh.bundle.js?v=16337:37:18422
    at AggParams.forEach (<anonymous>)
    at AggParams.AggTypesAggParamsProvider.AggParams.write (http://192.168.8.137:5601/bundles/wazuh.bundle.js?v=16337:37:18380)
    at AggConfig.VisAggConfigProvider.AggConfig.write (http://192.168.8.137:5601/bundles/wazuh.bundle.js?v=16337:16:81086)
    at AggConfig.VisAggConfigProvider.AggConfig.toDsl (http://192.168.8.137:5601/bundles/wazuh.bundle.js?v=16337:16:82021)
    at http://192.168.8.137:5601/bundles/wazuh.bundle.js?v=16337:67:975200
    at Array.forEach (<anonymous>)
    at AggConfigs.VisAggConfigsProvider.AggConfigs.toDsl (http://192.168.8.137:5601/bundles/wazuh.bundle.js?v=16337:67:974983)
    at http://192.168.8.137:5601/bundles/wazuh.bundle.js?v=16337:50:167607
```

**Comment by havidarou** [comment]
Hi Yingshang,

we've experienced this sometimes and I am not fully sure what is the casue.

My best guesses are (both are related):
1. Somehow visualizations needs data to work.
2. There's a templates/mappings issue with elasticsearch.

I would need you to paste the output of two elasticsearch commands:

```curl -XGET localhost:9200/_cat/templates?v```
```curl -XGET localhost:9200/_cat/indices?v```

And one more question:

did you start the logstash service before inserting the templates in elasticsearch?

Regards.

**Comment by jamesspi** [comment]
Hi,

I've experienced this before. This generally happens when you load visualisations before there any data is present within the elasticsearch indices, or if the particular field of the visualisation has not been populated yet.

This happens on the FIM and audit dashboards very often.

If you take a look at the "broken" visualisation, you will see something like "0 error" instead of the field name.

Check if the field/data is present in the discover tab. If data is there, you may simply need to refresh the index patterns and/or possibly reload the dashboard(s)/visualisation(s) in question.

Hope this helps!
James

**Comment by havidarou** [comment]
Hi @jamesspi 

thank you for your response.

That is why I was asking if logstash was started BEFORE inserting the elasticsearch templates.

Cause if that is the case, alerts will be inserted with the default template and then the visualizations won't recognize those alerts.

Regards.

**Comment by yingshang** [comment]
Thank you for your answer. I've already solved the problem. The main reason is that the index I built at elasticsearch is different from the configuration file in logstash

**Comment by yingshang** [comment]
After i found in two issue.
the one is i use rpm install logstash,i use comand start service`systemctl start logstash`,and logstash logs not error,but ela can't receive logs data.Later, I looked at the logstash's startup configuration file, and then changed the startup authority of the logstash to root to receive the log.

the another one issue is ela only receive wazuh server logs,can't receive agent logs

![11111](https://user-images.githubusercontent.com/11006249/34283304-fb1ed972-e705-11e7-828a-50a90a95e96b.png)


![Uploading 2222.png…]()

I hope to get your help, thank you.

**Comment by havidarou** [comment]
Hi  @yingshang different in what?

Regards.

**Comment by jesusgn90** [comment]
Hi @yingshang  it's been a month since the last response from our team, so I'm going to close this issue, if you are facing any more trouble feel free to create a new issue.

Best regards,
Jesús
