### ISSUE TITLE
Testing 3.9.1 - 6.7.2

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1452]
Tasks:

- [x] Verify background color Discover tab, Overview > Discover, Agents > Discover
- [x] Review all tables (resizable + no resizable)
- [x] Check configuration, rule, decoder, list editors error handling
- [x] Ensure Agent label configuration and Agent client configuration sections are shown the right information
- [x] Check Management > Logs scrolling
- [x] Go to Settings > About, Kibana version should be dynamic
- [x] Create a custom index pattern, check all is working using it
- [x] Verify the timezone for all the parts where we are using dates. **Fix** https://github.com/wazuh/wazuh-kibana-app/pull/1454
- [x] Ensure "dynamic height" for editors is working as expected

**Comment by juankaromo** [comment]
**Bug report**

Sometimes reports creation date contains a timestamp in itself, so when we add the browser timestamp, we are adding offset 2 times. We need to split by `.` (if it is present) and get only the date without offset.

![image](https://user-images.githubusercontent.com/21195730/57921840-9f0b6200-789e-11e9-878e-da41c2e100b2.png)

**Comment by jesusgn90** [comment]
@BraulioV reported https://github.com/wazuh/wazuh-kibana-app/issues/1455, I've fixed it here https://github.com/wazuh/wazuh-kibana-app/commit/fb112bbb81bdccec82f5b135214f13f42e56ab50
