### ISSUE TITLE
Edit group configuration tool seems to edit the agent.conf from other groups 

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-kibana-app#1455]
Hi team,

while testing the Groups section of the app, when I was trying to modify the agent.conf from a certain group, the text editor says that it is editing the agent.conf from another group instead of modifying the agent.conf from the group that I have selected. Here you can see an example.
![image (3)](https://user-images.githubusercontent.com/9081114/57939333-71d4a900-78ca-11e9-8088-0fdf6d71213a.png)

Further information:
- Wazuh version: v3.9.0
- Elastic Version: v6.7.2.

Regards.

**Comment by jesusgn90** [comment]
**Steps to reproduce**

1. Open group A
2. Open agent.conf of group A
3. Click on Groups in the nav links in the top of the view
4. Open group B
5. Open agent.conf of group B, it shows agent.conf of A

**Comment by jesusgn90** [comment]
**Fixed here https://github.com/wazuh/wazuh-kibana-app/commit/146f0738a9bf0531a4683b3d0484849eeb82a2b7**
