### ISSUE TITLE
Error when APP makes a DELETE API request

### ISSUE THREAD

**Issue by adri9valle** [wazuh/wazuh-kibana-app#1461]
Hi team,

Has been detected an error when trying to delete several agents with this API request `DELETE /agents?status=Disconnected&older_than=100s` concretely. The problem is that for this request the parameters are sent in the body of the request and is necessary to send them in the query string. 

- [x] Check for others possible API requests with errors.
- [x] Find the way to change how to make this type of API request without broke any other request.

Regards,

**Comment by jesusgn90** [comment]
Hi team,  

**Proposal**

Replace:

https://github.com/wazuh/wazuh-kibana-app/blob/bab06e572187ef35cdd7c92f912d5e5ee06592e5/public/controllers/dev-tools/dev-tools.js#L599-L602


with:

https://github.com/wazuh/wazuh-kibana-app/blob/e836fd11fa9ad14f08d52e3c19cc71d329b702d3/public/controllers/dev-tools/dev-tools.js#L599-L612

**Tests**

|                                            | GET | POST | PUT | DELETE |
|-------------------------------------|--------|---------|--------|--------------|
| NO PARAMS                      | --  | --   | --  | --     |
| INLINE PARAMS                | --  | --   | --  | --     |
| JSON PARAMS                  | --  | --   | --  | --     |
| INLINE + JSON PARAMS  | --  | --   | --  | --     |

**Comment by juankaromo** [comment]
**Tests results**

All tests have passed successfully.

- The `POST' method without PARAMS has not been tested because it does not make sense. 
- The `PUT` method with INLINE + JSON PARAMS has not been tested because we do not have any PUT request with more than one parameter.
