### ISSUE TITLE
"Invalid Date" when using Internet Explorer browser

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1469]
| Wazuh | Elastic | Rev |
|-----------|----------|-------|
| 3.9.x    | 6/7      | --     | 

**Description**

- Fields that should show a valid date are showing "Invalid Date".
- Chrome/Firefox working as expected
- Internet Explorer not working

**Steps to reproduce**

- As an example, you can open the agent list, the _registration date_ and the _last keep alive_ are being shown wrong.
- Another example would be the _syscheck_ and _rootcheck_ scan dates.

**Screenshots**

![image](https://user-images.githubusercontent.com/8860227/58253184-26a61480-7d68-11e9-9cf3-65e560b825d2.png)

![image](https://user-images.githubusercontent.com/8860227/58253170-1beb7f80-7d68-11e9-8440-b477e7afc7da.png)

**Comment by manuasir** [comment]
This also applies to Safari:
![image](https://user-images.githubusercontent.com/10210567/58866136-3868af80-86b8-11e9-8abd-c8083d7dcd40.png)

**Comment by juankaromo** [comment]
When we were removing the Zulu time stamp 'Z' we got a date in a format other than RFC2822 or ISO 8601 which are the only formats supported by Internet Explorer and Safari.

I have implemented another method to extract a clean Zulu time date that is compatible with all browsers. In this method I make a split of the string I receive and build date with a format supported by all browsers: 

`new Date(2019, 01, 07, 11, 00, 00); // yyyy, mm-1, dd, hh, mm, ss `

**Comment by jesusgn90** [comment]
Thanks @juankaromo , GJ

**Comment by juankaromo** [comment]
**Update**

Tested in Firefox and Chrome

![image](https://user-images.githubusercontent.com/21195730/59271448-2658b500-8c54-11e9-9be6-a81e30dcec69.png)
![image](https://user-images.githubusercontent.com/21195730/59271463-2bb5ff80-8c54-11e9-8e0d-e137fd5d670b.png)
