### ISSUE TITLE
Apply the right sorting depending on the list

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1471]
| Wazuh | Elastic | Rev |
|-----------|----------|--------|
| 3.x       | 6.x/7.x | --      |

**Description**

Some tables and lists have a default value for the initial sorting that not always makes sense.

**Steps to reproduce**

Open a section with a table, use the agents search bar, there are a lot of examples in the app.

**Screenshots**

Agents search bar:

![image](https://user-images.githubusercontent.com/8860227/58271712-f91f9200-7d8c-11e9-9a05-82c84a9c038d.png)

Checks list from an SCA policy:

![image](https://user-images.githubusercontent.com/8860227/58271905-7519da00-7d8d-11e9-9f90-fe2cce8164b1.png)

**Comment by juankaromo** [comment]
**Update**

The ordering process was being carried out badly because even if the `implicitFilter` was passed as a parameter, since `implicitSort` was not established, it was not ordered. This has been arranged in this way:

`this.sortDir = this.implicitSort !== false;`

**Comment by juankaromo** [comment]
**Update**

Added the correct sorting in the administration tables (rules, decoders, lists and files) including the `implicit-filter`.

Change the autocomplete results of the agents search bar have been sorted. To do this, we have taken into account upper and lower case, and numerical sorting, not alphabetical, with function like:

`.sort((a, b) => { return a.toString().localeCompare(b.toString(), undefined, { numeric: true, sensitivity: 'base' }) })`

**Comment by juankaromo** [comment]
**Update**

The default sorting of all tables has been fixed. Previously it was inverted, being the down arrow the ascending one, and the up arrow the descending one.

https://github.com/wazuh/wazuh-kibana-app/blob/6f3883fedfd93bf16c8398c50aac98906d629958/public/services/data-factory.js#L26

In addition, tables have been automatically sorted when initialized if there is an implicit sorting.

https://github.com/wazuh/wazuh-kibana-app/blob/6f3883fedfd93bf16c8398c50aac98906d629958/public/services/data-factory.js#L29
