### ISSUE TITLE
Syscollector network interfaces table doesn't paginate

### ISSUE THREAD

**Issue by Skeptor** [wazuh/wazuh-kibana-app#1474]
Wazuh | Elastic | Rev
-- | -- | --
3.9.x | 6/7 | --

**Description**

The `Network Interfaces` doesn't paginate the information but the `Network ports` always paginate at 6 elements. Due to this mismatching behaviour the `Network ports` table waste a lot of space instead of adapt the number of ports listed.

**Steps to reproduce**

Go to Agents > agent > Inventory Data

**Screenshots**

![image](https://user-images.githubusercontent.com/9034923/58330189-a26e9280-7e36-11e9-9c30-eabb97aface2.png)

**Comment by jesusgn90** [comment]
Thanks @Skeptor, we'll review this for further releases.

**Comment by jesusgn90** [comment]
Already fixed for 3.10, see https://github.com/wazuh/wazuh-kibana-app/issues/1484#issuecomment-499173212 for details. This issue is included in https://github.com/wazuh/wazuh-kibana-app/issues/1484 so I'm going to close this ticket, thanks.

Regards
