### ISSUE TITLE
Missing metrics for agent overview dashboard

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1475]
| Wazuh | Elastic | Rev |
|-----------|----------|-------|
| 3.x        | 6/7      | --     | 

**Description**

@algonba requested the same metrics as the Overview > General dashboard for the agents.

**Steps to reproduce**

N/A

**Screenshots**

![image](https://user-images.githubusercontent.com/8860227/58337066-48c19480-7e45-11e9-9e60-d7df3c1789ef.png)

**Comment by juankaromo** [comment]
**Update**

Metrics have been added to the general section of the agent, and their result is this:

![image](https://user-images.githubusercontent.com/21195730/58416798-11d8c200-8083-11e9-9041-5e8dbca4938a.png)
