### ISSUE TITLE
Feature request: searchable file editor

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-kibana-app#1486]
When editing a large configuration file (for example a Manager's configuration in the `Management / Configuration / Edit configuration` section) often the browser will fail to search within the large text box.

If would be ideal if hitting Ctrl+F would provide a search function native to the app so one could search for a specific section of the configuration without having to scroll through it. Or even having a small search box on the top-right of the editor box.

Additionally it would be great to be able to click on the errors specified on the top of the editor to jump to the relevant line.

**Comment by branchnetconsulting** [comment]
This issue reflects badly on the Wazuh Kibana app, making it harder to navigate large files like ossec.conf and agent.conf file in the web interface than when using vi.  Please address it.

**Comment by juankaromo** [comment]
Hi @jctello @branchnetconsulting 

This will be solved in 3.13 with the use of the text editors provided by the Elastic `eui` components framework.

![euigithub](https://user-images.githubusercontent.com/21195730/79969392-ba5cf500-8491-11ea-9f78-15e8413ab83a.gif)

Regards,
