### ISSUE TITLE
ReferenceError: getPainlessError is not defined

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-kibana-app#1490]
| Wazuh | Elastic | Rev |
|-----------|----------|-------|
|  3.9.1      |  7.1.0      | 0508 |

**Description**
I randomly got the following error in `Security events` tab. At that point, the full app was blank and it was necessary to refresh the page:

```
ReferenceError: getPainlessError is not defined
```

**Steps to reproduce**
I'm attaching here the very accurate steps that I performed, but I don't think this is relevant and this bug looks more like a kind of road race with Discover component.
1. Go to Management
2. Click on Cluster
3. Go to Overview
4. Click on Security events

**Additional context**
This was reproduced on an Amazon Linux 2 `t2.medium` instance. After digging a little bit in the code I just found this, which seems to be the fragment of code that provokes the error:

https://github.com/wazuh/wazuh-kibana-app/blob/214531d044fdaccb5455a491b4835b27e058eb9b/public/kibana-integrations/kibana-discover.js#L793-L795

I'd also like to remark that this occurred in a totally random way, I tried to reproduce twice and it couldn't be possible.

Thanks

**Comment by jesusgn90** [comment]
Hi @manuasir ,

https://github.com/wazuh/wazuh-kibana-app/blob/214531d044fdaccb5455a491b4835b27e058eb9b/public/kibana-integrations/kibana-discover.js#L794 is not defined.

An easy way to reproduce is to throw an error in https://github.com/wazuh/wazuh-kibana-app/blob/214531d044fdaccb5455a491b4835b27e058eb9b/public/kibana-integrations/kibana-discover.js#L792.

Here is an example:

```js
  function handleSegmentedFetch(segmented) {
    throw Error('fake error')
```

The solution would be importing https://github.com/elastic/kibana/blob/v7.1.0/src/legacy/core_plugins/kibana/public/discover/controllers/get_painless_error.ts on top of the file, testing it right now.

**Comment by jesusgn90** [comment]
Fixed here https://github.com/wazuh/wazuh-kibana-app/commit/43f5dd5f64065c618ba930b2a4087f0a9e706c0e for 3.9-7.1, thanks @manuasir
