### ISSUE TITLE
Please restore the Dashboard option to the App and the filters Actions menu

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh-kibana-app#1499]
Some time back, we used to have a Dashboard option along the top menu of the App, but it is gone now.  

![image](https://user-images.githubusercontent.com/13170654/58572829-6e1a1e00-820a-11e9-896e-e6ba75a1f54f.png)

I really miss this because it was the only way to cleanly pivot from an App dashboard to a custom dashboard and keep pinned filter criteria intact.  From a cyber-security threat hunting perspective, the ability to flexibly pivot like this is essential as there will always be a need to use custom dashboards outside of the standard ones included in the App.  Right now any time I need to pivot to a custom dashboard I lose all my filter criteria and have to rebuild it, which is quite awkward.  

On a related note please bring back the Filter Actions menu or at least introduce a Pin All and a Remove All option so that when we build up a stack of filters and then need to pivot, we don't have to pin each one separately, and when we want to clear our filters out we don't have to remove each one separately.

![image](https://user-images.githubusercontent.com/13170654/58574919-1a5e0380-820f-11e9-8ed1-a783377449fa.png)

Thanks for your consideration!
Kevin

**Comment by juankaromo** [comment]
Hi @branchnetconsulting 

The design works differently from several versions. Quite a few design changes are introduced in every version of our app with the aim of, in our opinion, improving the experience and navigation of the user. It is for this reason that we are undoubtedly trying to increase user satisfaction day by day, and for example, we now have many design changes issues opened (https://github.com/wazuh/wazuh-kibana-app/issues?q=is%3Aissue+is%3Aopen+label%3AUI%2FUX).

So having said that, any suggestion is welcome, and of course we will study all these changes you're proposing.

Greetings.

**Comment by jesusgn90** [comment]
@branchnetconsulting we've scheduled this ticket for Wazuh v3.11.x but we'll try to implement for v3.10.x if Kibana doesn't give us so many troubles, those are simple actions but they imply storing data in the `.kibana` index and a few other things. We'll update this task here.

**Comment by jesusgn90** [comment]
Related https://github.com/wazuh/wazuh-kibana-app/issues/1507, https://github.com/wazuh/wazuh-kibana-app/issues/1398

**Comment by juankaromo** [comment]
Since Kibana 7.6.X filters action menu is displayed in the Wazuh application by default.

![image](https://user-images.githubusercontent.com/21195730/79970885-e4171b80-8493-11ea-80d8-0803887f8ccd.png)

Regards,
