### ISSUE TITLE
wazuh time seems confused in China timezone +8:00

### ISSUE THREAD

**Issue by wttat** [wazuh/wazuh-kibana-app#1503]
All Unix system is Ubuntu 16.04
Installed By tar.xz

- Kibana-7.1.0 in 192.168.1.19
- elasticsearch-7.1.0 in 192.168.1.20
- logstash-7.1.0 in 192.168.1.21
- filebeat-7.1.0 in both 192.168.1.22 and 192.168.1.23

Installed as service

- Wazuh-3.9.1 included 
Wazuh manager Wazuh api in 192.168.1.22
Wazuh agent in 192.168.1.23

The filebeat.yml in 192.168.1.22 is :
![image](https://user-images.githubusercontent.com/29791466/58604993-ed6e2700-82c8-11e9-875f-e21f79d7253b.png)
![image](https://user-images.githubusercontent.com/29791466/58605000-f65ef880-82c8-11e9-9f35-26f22f3a8298.png)

The logstash's wazuh.conf in 192.168.1.21 is 
![image](https://user-images.githubusercontent.com/29791466/58605041-1ee6f280-82c9-11e9-943c-158b6c72b8e4.png)

The Wazuh's template is already installed in Kibana.
I can receive both the wazuh-3.*-monitoring indices and the wazuh-3.*-alert indices

However I find that  the wazuh-3.*-alert indice's time is confused,which the kibana can't display in either sorted by @timestamp or timestamp or nothing.I tried change the time span to 15hours or longer is no use
![image](https://user-images.githubusercontent.com/29791466/58605537-b3058980-82ca-11e9-88d8-fc73254e041f.png)

Through the wauzh in kibana I can't see any events which I can assume that it is blame to the time set too.

While in the wazuh in kibana management/logs the time is eariler 8 hours than now 
![image](https://user-images.githubusercontent.com/29791466/58605320-ebf12e80-82c9-11e9-8c86-df2f1a53fda3.png)
the time right now is 10:59 AM +8:00 while in the status tag is correct
![image](https://user-images.githubusercontent.com/29791466/58605513-9d905f80-82ca-11e9-862a-ec44c74239d1.png)

and i check the time is these system  is the same 
![image](https://user-images.githubusercontent.com/29791466/58605395-2eb30680-82ca-11e9-9aa6-c8dc25751e71.png)
I tried changed the kibana's dateFormat:tz to UTC is not work.

**Comment by wttat** [comment]
> Hi @wttat,
> 
> > The logstash's wazuh.conf in 192.168.1.21 is
> 
> Coming new in version Elastic 7.x, there is an architecture change introduced in Wazuh Stack. Logstash is no longer required, Filebeat will send the events directly to Elasticsearch server. In any case, you can still be using Logstash if needed following [our guide](https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/transform_logstash.html).
> 
> We've introduced a breaking change related to the time field used by the index patterns, you can read more about it here: https://documentation.wazuh.com/current/installation-guide/upgrading-elastic-stack/elastic_server_rolling_upgrade.html#field-migration-from-timestamp-to-timestamp
> 
> > The Wazuh's template is already installed in Kibana.
> 
> The template is now managed by Filebeat as you can see here: https://documentation.wazuh.com/current/installation-guide/installing-wazuh-server/wazuh_server_rpm.html#installing-filebeat
> 
> > However I find that the wazuh-3.*-alert indice's time is confused,which the kibana can't display in either sorted by @timestamp or timestamp or nothing.I tried change the time span to 15hours or longer is no use
> 
> This is related to the "@timestamp vs timestamp" [change](https://documentation.wazuh.com/current/installation-guide/upgrading-elastic-stack/elastic_server_rolling_upgrade.html#field-migration-from-timestamp-to-timestamp) we've introduced.
> 
> > While in the wazuh in kibana management/logs the time is eariler 8 hours than now
> 
> Logs are not managed by the Wazuh app, but we'll ping the core team in order to review those timestamps.
> 
> > I tried changed the kibana's dateFormat:tz to UTC is not work.
> 
> This will apply for the alerts and monitoring documents that you can see in the Discover/Dashboards but not for the rest of timestamps in the app (data coming from the Wazuh API and not from Elasticsearch).
> 
> I hope all this stuff is now clearer for you, let us know.
> 
> Best regards,
> 
> Adri

Thanks very much !

I removed the logstash from the system then changed the filebeat.yml to directly send data to the elasticsearch it totally works now.

![image](https://user-images.githubusercontent.com/29791466/58762924-8205ad00-8587-11e9-81ac-770264e703d3.png)

Recently I have no further need for the logstash so I will just leave it there.

Wish you all the best !

**Comment by adri9valle** [comment]
Hi @wttat,

You're welcome. Don't be hesitate to open a new thread in case of a new problem or doubt.

Of course, you're invited to join us in our [Slack community](https://wazuh.com/community/join-us-on-slack/).

Regards,
