### ISSUE TITLE
Report Wazuh generate automatically and send by mail

### ISSUE THREAD

**Issue by John33000** [wazuh/wazuh-kibana-app#1508]
**Describe the solution you'd like**
In plugin Wazuh => Security Event we can generate a report pdf. But there are not button for send by mail every week or evey month etc ... It would be nice to implement this. Thank you

**Comment by jesusgn90** [comment]
Related https://github.com/wazuh/wazuh-kibana-app/issues/1492

**Comment by jesusgn90** [comment]
This is in our roadmap @John33000 , stay updated tracking the ticket from my previous comment.

Thanks for your patience.

Regards
