### ISSUE TITLE
Agents search bar not applying filter when refreshing

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1511]
| Wazuh | Elastic | Rev |
|-----------|-----------|-------|
|  3.9.x   |  6.8/7.1 | n/a |

**Description**
If I click on Agents and then in "Add a filter or search" I type in all or part of one of the agent names, it successfully filters the list but if I click the Refresh button to the right, the full unfiltered list of agents appears even though the filter criteria still appears.

**Steps to reproduce**
1. Go to _Agents preview_
2. Click on the search bar
3. Write something that would reduce the results, eg: "specific agent name"
4. Click on the "Refresh" button
5. The results are reloaded, the filter is shown but it's not being applied.

**Screenshots**

![image](https://user-images.githubusercontent.com/8860227/59014145-2748ab80-883c-11e9-8207-341126a275ba.png)

![image](https://user-images.githubusercontent.com/8860227/59014174-434c4d00-883c-11e9-9341-7a2b59a57b45.png)

**Comment by juankaromo** [comment]
**Update**

Instead of launching directly to the `WazuhSearch` event, we launch an event that will be picked up by the search bar controller. There the query will be built with the filters in it and, now, the event `WazuhSearch` is launched.

**Comment by branchnetconsulting** [comment]
Wow, I reported this bug only a few hours ago and you guys have already fixed it.  You are fast!

Kevin
