### ISSUE TITLE
Granular options for agent configuration reports

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1518]
In https://github.com/wazuh/wazuh-kibana-app/issues/1340 we've created a new kind of reports for the Wazuh app, the agent configuration reports, with this ticket we are improving this new feature.

When the user clicks the _PDF_ button, we want to show a dropdown with the one check per component, this way the user can customize the report.

Example:

> I want a document where I can see the FIM configuration for the agent 003.

Something like this:

![image](https://user-images.githubusercontent.com/8860227/59093819-2172c900-8915-11e9-9a6c-29c14b430c73.png)

Related EUI components:

- https://elastic.github.io/eui/#/layout/popover
- https://elastic.github.io/eui/#/forms/selectable
- https://elastic.github.io/eui/#/navigation/button

**Comment by juankaromo** [comment]
**Update**

I have been having problems to load a list of options in the selectable, cause when I instantiate the options list in the state (how is explained in `eui` docs), in this way:

```js
    this.state = {
      options: ['option1', 'option2', 'option3'] as Option[],
      isPopoverOpen: false,
    };
```

I get the next error:

`'type assertion expressions' can only be used in a .ts file. [import Option]`

**Comment by juankaromo** [comment]
### **Update 10/06**

After being researching how to import `EuiSelectable`, I realized that the version of `eui` that Kibana uses doesn't support it. At this point, I decided to implement by myself a selectable-like component using `EuiCheckboxGroup`.

I've splitted the list of options according to the type of configuration we want to export; if we want to export an Agent configuration, the list of options is the list of possible components and modules that one agent could have. https://github.com/wazuh/wazuh-kibana-app/commit/44d85f85e2151b90ace6c1423bbe6f087c0bbddb This is shown below: 

![image](https://user-images.githubusercontent.com/21195730/59193874-6aca4f00-8b87-11e9-846f-1606392eedd7.png)

On the other hand, if we want to export a Group configuration, the options are two; the possibility of export the configuration with their filters, or the possibility to export the list of agents in the group. https://github.com/wazuh/wazuh-kibana-app/commit/33c76feb291360d168a697afd774e4f08ae9f6f7 This is shown below: 

![image](https://user-images.githubusercontent.com/21195730/59193842-48d0cc80-8b87-11e9-8979-e5ab97c4222b.png)

When we clicked on `Generate PDF report`, the Popover disappears, and a load ring appears in the button place, avoiding the user to clicking again.

![react-report](https://user-images.githubusercontent.com/21195730/59194255-bdf0d180-8b88-11e9-894e-c1c9aaa0750b.gif)

It is missing to introduce a button that allows the user to easily select or deselect all the elements of the list.

**Comment by juankaromo** [comment]
**Update**

Select all and unselect all buttons have been added to the component https://github.com/wazuh/wazuh-kibana-app/commit/8e23e2a1526c053e7936f7a1a45d4f1ec4bef4b3.  This is shown below:

![image](https://user-images.githubusercontent.com/21195730/59203116-37df8580-8b9e-11e9-98ba-dbfbad327a90.png)

**Comment by juankaromo** [comment]
### Update

Generate PDF report button now is disabled if any component/module in the list is checked, with the aim of not export empty reports.

![image](https://user-images.githubusercontent.com/21195730/59266021-ec34e680-8c46-11e9-8150-4d7b41d87ffc.png)

**Comment by juankaromo** [comment]
**Update**

The component selector to export now takes into account those components or modules that are not supported by the operating system of the agent and hides them from the list preventing the user to select them, because they will not appear in the report because they are not configurable for that agent.

e.g:

![image](https://user-images.githubusercontent.com/21195730/59425884-17e6d680-8dd7-11e9-9328-84ee9e42367f.png)

**Comment by juankaromo** [comment]
**Update**

The importable object that represents the compatibility matrix and through which extensions compatible with the agent's operating system are hidden or shown has been modified (by @jesusgn90 suggestion) by exchanging the values (before components) for the operating systems, and the values for the components (before operating systems).

Now it looks like this:

```

export const UnsupportedComponents = {
  'linux': [],
  'windows': ['audit', 'oscap', 'vuls', 'docker'],
  'darwing': ['audit', 'oscap', 'vuls', 'docker'],
  'other': ['audit', 'oscap', 'vuls', 'docker']
};

```
