### ISSUE TITLE
Issue: Wrong content for files in centralized configuration

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-kibana-app#1522]
| Wazuh | Elastic | Rev |
|-----------|----------|-------|
|  3.9.1    |  7.1.0  | 0508 |

**Description**
Short description of your issue.

**Steps to reproduce**
1. Go to the management section of the Wazuh App
2. Click on Groups and select a group
3. Click on the Content Tab
4. Select a file other than `agent.conf` or `ar.conf`(for example `merged.md` or any other added in the folder `/var/ossec/etc/shared/group/`)
5. Output is:
```
{
   "vars": {},
   controls: [
      {}
   ]
}
```
Regardless of the content of the file.

**Screenshots**
![image](https://user-images.githubusercontent.com/36071202/59184774-22069c00-8b6f-11e9-9056-545607eefb8d.png)

![image](https://user-images.githubusercontent.com/36071202/59184849-4498b500-8b6f-11e9-964f-a4757a05d24a.png)

**Comment by juankaromo** [comment]
Hi @jctello 

We show what we receive from the API by making a GET request about the contents of that file.

You can check it in the dev-tools doing a `GET /agents/groups/default/files/osquery-monitoring.conf`

Maybe it's a @wazuh/framework problem that isn't mapping the path `/linux/....` well?

**Comment by jctello** [comment]
True.
 I've verified this and narrowed down the root cause. 
Opened up this issue: https://github.com/wazuh/wazuh/issues/3497
So this one may be closed.
