### ISSUE TITLE
Wazuh plugin not showing all security events

### ISSUE THREAD

**Issue by NutellaPie** [wazuh/wazuh-kibana-app#1533]
Hi, I'm unable to view any alerts apart from "Windows Logon Success" alert that is being generated. I've tried to create some alerts by downloading the eicar test file on my agents but it is still not displaying on the dashboard

![Capture](https://user-images.githubusercontent.com/47778098/59553889-585c7500-8fce-11e9-8a75-d1c3c4fae020.PNG)

**Comment by juankaromo** [comment]
Hi @NutellaPie 

Have you checked if there are alerts related to the alerts you are creating in your alerts.json file?
If they don't appear there, you're not generating the alerts correctly.

Check this out and keep me updated.

**Comment by NutellaPie** [comment]
Hi, @juankaromo 

I have checked the alerts.json file and I am able to see some alerts which are present in the file but not displaying on the Wazuh dashboard in Kibana. Also, I have noticed that there are no alerts generated when I try to download the eicar test file on my agent. Would you know if the Wazuh agent detects such flies would it usually generate an alert?

Below is a screenshot of some of the alerts I’ve found in the file but not displaying on the dashboard (highlighted in blue)

![IMG_0015](https://user-images.githubusercontent.com/47778098/59596968-4c39fa00-912b-11e9-99f2-adf78f9fdd41.jpeg)

**Comment by juankaromo** [comment]
Hi @NutellaPie 

Just to be sure and keep researching your problem, have you tried increasing the time range of the alerts?

![image](https://user-images.githubusercontent.com/21195730/59609660-18090e00-9118-11e9-97e7-8ee65dd73020.png)

Let me know if you get any results.

**Comment by NutellaPie** [comment]
Hi @juankaromo 

Yes, I have increased it but it only shows one alert

**Comment by juankaromo** [comment]
Hi @NutellaPie 

I have tried to index an alert like the ones you indicate and it may be because some field contains a character that breaks the JSON and Elasticsearch can not index it. To make sure I haven't made a mistake in transferring the alerts to my environment, can you send them to me in text format? 

For example, can you send me the output of this command?

`cat /var/ossec/logs/alerts/alerts.json | grep 60797`

Regards

**Comment by NutellaPie** [comment]
Hi @juankaromo 

Here are the outputs for the command `cat /var/ossec/logs/alerts/alerts.json | grep 60797`

[outputs.log](https://github.com/wazuh/wazuh-kibana-app/files/3302473/outputs.log)

**Comment by juankaromo** [comment]
Hi @NutellaPie 

Well as see I have tried to index all the alerts that you have provided and I have not had any problem, so its format is correct. 

![image](https://user-images.githubusercontent.com/21195730/59741684-fae55400-926b-11e9-805f-d39864df7d40.png)

Maybe you are having some kind of problem with the template Elasticsearch, which makes you also happen what you comment on this thread: https://github.com/wazuh/wazuh-kibana-app/issues/1534

So let's continue the thread there. It is likely that when we fix the other problem, this will also be solved.

Regards.

**Comment by NutellaPie** [comment]
Hi @juankaromo 

Alright, thank you so much for your help

**Comment by NutellaPie** [comment]
Hi @juankaromo 

My issue is fixed after resolving the issue #1534 , thank you so much for your help!
