### ISSUE TITLE
No data shown in Inventory data

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#1535]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.9   | 7.1     | 514 |

**Description**
Short description of your issue.

**Steps to reproduce**

1. Go to 'Agents'
2. Click on 'any agent'
3. Go to 'Inventory data'

**Screenshots**
![image](https://user-images.githubusercontent.com/21195730/59584585-b2e4f680-90de-11e9-875f-d2693ca02506.png)

![image](https://user-images.githubusercontent.com/21195730/59584592-b8424100-90de-11e9-8646-58547be1ec4f.png)

**Additional context**
Looks like there's a bad import of the `KeyEquivalence` module.

**Comment by jesusgn90** [comment]
Hi @juankaromo , thanks for the fast response to this tiny bug, I've closed the PR because it was included updating the 3.10 branch https://github.com/wazuh/wazuh-kibana-app/commit/15fdbf7f18aef621a16a6ee05490416d2dc0d8db

Regards
