### ISSUE TITLE
Testing v3.9.3-7.1.1-rc1

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1541]
Tag: [v3.9.3-7.1.1-rc1](https://github.com/wazuh/wazuh-kibana-app/tree/v3.9.3-7.1.1-rc1)
Package: [wazuhapp-3.9.3_7.1.1-rc1.zip](https://packages-dev.wazuh.com/staging/app/kibana/wazuhapp-3.9.3_7.1.1-rc1.zip)
Revision: **0516**

Put extra attention to the next three points:

- [x] https://github.com/wazuh/wazuh-kibana-app/issues/1484
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/1535
- [x] No "Invalid Date" in Chrome, Firefox, Safari, Edge

Then, make the usual tests for any new release:

- [x] Overview
  - [x] Visualize, filters, searches
  - [x] Extensions
- [x] Management
  - [x] Ruleset
  - [x] Groups
  - [x] Configuration
  - [x] Status
  - [x] Logs
  - [x] Reporting
  - [x] Cluster
- [x] Agents
  - [x] Visualize, filters, searches
  - [x] Extensions
  - [x] Configuration
  - [x] Inventory (syscollector)
  - [x] FIM table
- [x] Dev Tools
  - [x] GET
  - [x] POST
  - [x] DELETE 
  - [x] PUT
- [x] Settings
  - [x] API entries
  - [x] App logs, rest of tabs of Settings

**Note: use always at least 1 x Windows agent, 1 x Linux agent, 1 x MacOS agent**

**Comment by juankaromo** [comment]
**Testing report**

Tests have been performed within a Kibana production environment.

-  #1484
![image](https://user-images.githubusercontent.com/21195730/59928544-46039080-943f-11e9-9ee5-7a9830d844a4.png)
In IE 11 the styles of the new welcome cards don't work properly. ❌In the rest of the browsers all OK. ✅
-  #1535
All tests have been carried out successfully. ✅
-   No "Invalid Date" in Chrome, Firefox, Safari, Edge
All tests have been carried out successfully. ✅

-   Overview
All tests have been carried out successfully. ✅
-   Management
All tests have been carried out successfully. ✅
-   Agents
All tests have been carried out successfully. ✅
-   Dev Tools
All tests have been carried out successfully. ✅
-   Settings
All tests have been carried out successfully. ✅

**Comment by jesusgn90** [comment]
- https://github.com/wazuh/wazuh-kibana-app/issues/1543 solved in https://github.com/wazuh/wazuh-kibana-app/commit/ccda8464b50be05bc5b3642f25f4972c8a7a2c03
- The IE problem will be scheduled for next versions since Edge is not affected, just older versions (aka Internet Explorer)
