### ISSUE TITLE
Agents > GDPR is showing descriptions for PCI DSS requirements

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1543]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.9   | 6.x/7.x     | n/a |

**Description**
Short description of your issue.

**Steps to reproduce**

1. Go to agents > :agent 
2. Click on GDPR dashboard

The list of requirements being shown is for PCI DSS instead of GDPR.

**Screenshots**

![image](https://user-images.githubusercontent.com/8860227/59929196-9cbd9a00-9440-11e9-84ad-00d6b3aa86e1.png)

**Additional context**
Please, the fix should be as easy as replacing it with the right requirements.

**Comment by juankaromo** [comment]
**Update**

The call to obtain the GDPR requirements was the same as to get the PCI ones.

`const gdprTabs = await this.commonData.getGDPR();` > `const gdprTabs = await this.commonData.getPCI();`
