### ISSUE TITLE
Testing v3.9.3-7.1.1-rc3

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1547]
Tag: [v3.9.3-7.1.1-rc3](https://github.com/wazuh/wazuh-kibana-app/tree/v3.9.3-7.1.1-rc3)
Package: [wazuhapp-3.9.3_7.1.1-rc3.zip](https://packages-dev.wazuh.com/staging/app/kibana/wazuhapp-3.9.3_7.1.1-rc3.zip)
Revision: **0517**

Put extra attention to the next three points:

- [x] Restore "rule.id" clickable Discover & Visualizations https://github.com/wazuh/wazuh-kibana-app/issues/1529
- [x] Wrong requirements list for GDPR https://github.com/wazuh/wazuh-kibana-app/issues/1543
- [x] No "Invalid Date" in Chrome, Firefox, Safari, Edge
- [x] Review all timezones

**Comment by juankaromo** [comment]
**Testing report**

Tests have been performed within a Kibana production environment.

-  Restore "rule.id" clickable Discover & Visualizations #1529
All tests have been carried out successfully. ✅
-  Wrong requirements list for GDPR #1543
All tests have been carried out successfully. ✅
-  No "Invalid Date" in Chrome, Firefox, Safari, Edge
All tests have been carried out successfully. ✅
- Review all timezones
...
