### ISSUE TITLE
Review broken things for Kibana 7.2.0

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1553]
Hi team, this ticket is intended to show all things broken for Kibana 7.2.0 after a first view.

Tasks:

- [x] Add comments about server-side errors.
- [x] Add comments about client-side errors.
- [x] Add comments about installing package errors.
- [x] Add any other useful information before planning the code fixing.

Regards

**Comment by juankaromo** [comment]
**Client-side errors** 

**Missing dependencies in kibana-discover.js**
- `ui/tooltip` is deprecated
- discover.js needs adapt 7.2 changes
`ui/doc_table/` is now on `plugins/kibana/discover/doc_table/`

**Comment by juankaromo** [comment]
**Server side errors**
New debug level's logs have been added. https://github.com/wazuh/wazuh-kibana-app/pull/1556/commits/5d183f79e0d2d386a9bf8e86dc269cd119d9ef3c

**Installing errors**
Plugin installation must be performed without _sudo_.
