### ISSUE TITLE
Review PUT and DELETE calls from management sections

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#1555]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.10   | 6.x 7.x      | 517|

**Description**
Dev tools requests bodies have been changed in 3.10 API for PUT and DELETE methods, so, we need to test all these methods calls from app management sections in order to find methods with bodies when now expects query strings.

**Steps to reproduce**

1. Go to 'Management > Groups'
2. Click on some group
3. Delete a some agents with the multiple agents selector.

**Screenshots**
![image](https://user-images.githubusercontent.com/21195730/60244253-4cb85a80-98ba-11e9-9969-065268ef28ce.png)

**Comment by adri9valle** [comment]
**Update**

I've checked all `DELETE` and `PUT` API calls and replace it from in body to in the query string.

Solved: https://github.com/wazuh/wazuh-kibana-app/pull/1557
