### ISSUE TITLE
Adapt Wazuh app for Kibana dark mode

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1562]
Hi team, 

The community asks for the dark mode for Kibana, and we should fix it as soon as possible.

The task is mainly focused on reviewing all our stylesheets, React components and any other component affected by the dark mode.

Tasks:

- [x] Adapt all the CSS
- [x] Adapt all components to load the styles properly depending on the selected mode
  - [x] Overview, Agent, Cluster dashboards
  - [x] Discover
  - [x] Menu directive
  - [x] Tables
  - [x] Settings
  - [x] Management

Once the tasks are completed, then test it.

- [x] Standard test battery for any Wazuh app using dark mode
- [x] Standard test battery for any Wazuh app using light (default) mode

**Comment by juankaromo** [comment]
What we are going to do is check at the beginning of the application to see if we have activated the dark mode.

https://github.com/wazuh/wazuh-kibana-app/blob/f3631c7e419d9576066bd67220bacbd8a6ad87f4/public/less/loader.js#L28

Once checked, if it's activated we'll load a custom dark theme stylesheet.

https://github.com/wazuh/wazuh-kibana-app/blob/f3631c7e419d9576066bd67220bacbd8a6ad87f4/public/less/loader.js#L30-L35

This is the first iteration. We have to make some more small adjustments, but we'll start here.

![image](https://user-images.githubusercontent.com/21195730/61213679-065e5a80-a706-11e9-9b74-dd13804c9c31.png)

**Comment by juankaromo** [comment]
**Update**

Consoles and XML editors (Codemirror integration) have been adapted to dark mode also. They check if global flag IS_DARK_THEME is active and if it's activated we'll load a custom dark theme stylesheet. Then, we'll apply it in Codemirror box instantiation.

https://github.com/wazuh/wazuh-kibana-app/blob/d1ff8a7d67548f42669fdf58f96293c44e336b8c/public/directives/wz-xml-file-editor/wz-xml-file-editor.js#L335

![image](https://user-images.githubusercontent.com/21195730/61274928-15e4ae80-a7ad-11e9-96ed-1c810bde5c90.png)

**Comment by juankaromo** [comment]
**Update**

I took advantage of the migration to the dark theme to change our nav-bar for a react component using EuiTabs. In this way, the component already adapts to the dark theme natively. To instantiate the component we simply do it in the following way:

```js
    this.rulesetTabsProps = {
      clickAction: tab => this.setRulesTab(tab),
      selectedTab: this.rulesetTab,
      tabs: [
        { id: 'rules', name: 'Rules' },
        { id: 'decoders', name: 'Decoders' },
        { id: 'cdblists', name: 'Lists' }
      ]
    };
```

The component is called `Tabs`, and it looks like this:

![image](https://user-images.githubusercontent.com/21195730/61305789-bc4fa480-a7eb-11e9-9155-805853f9520e.png)

**Comment by juankaromo** [comment]
**Update**

The styles of the consoles have been adapted for the dark theme of CodeMirror and thus resemble those of Kibana.

![image](https://user-images.githubusercontent.com/21195730/61722031-d3514200-ad69-11e9-946f-ad892522e951.png)

With this the adaptation is finished. It remains to be tested.
