### ISSUE TITLE
Testing for v3.9.3-6.8.1

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1563]
Tag: [v3.9.3-6.8.1](https://github.com/wazuh/wazuh-kibana-app/tree/v3.9.3-6.8.1)
Package: [wazuhapp-3.9.3_6.8.1.zip](https://packages-dev.wazuh.com/staging/app/kibana/wazuhapp-3.9.3_6.8.1.zip)
Revision: **0447**

Put extra attention to the next three points:

- [x] No "Invalid Date" in Chrome, Firefox, Safari, Edge

Then, make the usual tests for any new release:

- [x] Overview
  - [x] Visualize, filters, searches
  - [x] Extensions
- [x] Management
  - [x] Ruleset
  - [x] Groups
  - [x] Configuration
  - [x] Status
  - [x] Logs
  - [x] Reporting
  - [x] Cluster
- [x] Agents
  - [x] Visualize, filters, searches
  - [x] Extensions
  - [x] Configuration
  - [x] Inventory (syscollector)
  - [x] FIM table
- [x] Dev Tools
  - [x] GET
  - [x] POST
  - [x] DELETE 
  - [x] PUT
- [x] Settings
  - [x] API entries
  - [x] App logs, rest of tabs of Settings

**Note: use always at least 1 x Windows agent, 1 x Linux agent, 1 x MacOS agent**

**Comment by juankaromo** [comment]
**Testing report**

Tests have been performed within a Kibana production environment.

-   No "Invalid Date" in Chrome, Firefox, Safari, Edge
All tests have been carried out successfully. ✅

-   Overview
All tests have been carried out successfully. ✅
-   Management
All tests have been carried out successfully. ✅
-   Agents
All tests have been carried out successfully. ✅
-   Dev Tools
All tests have been carried out successfully. ✅
-   Settings
All tests have been carried out successfully. ✅
