### ISSUE TITLE
Can't found wazuhapp-3.9.3_7.2.0.zip

### ISSUE THREAD

**Issue by 0xa-saline** [wazuh/wazuh-kibana-app#1564]
Just try to use ELk7.2.0,I found this error.But I found this command in https://github.com/wazuh/wazuh-kibana-app/tree/a49c7c411fbc0c108a31f4d53335078025588e68

An error occurred when I tried to update with this prompt

sudo -u kibana /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.9.3_7.2.0.zip
Attempting to transfer from https://packages.wazuh.com/wazuhapp/wazuhapp-3.9.3_7.2.0.zip
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/https://packages.wazuh.com/wazuhapp/wazuhapp-3.9.3_7.2.0.zip/https://packages.wazuh.com/wazuhapp/wazuhapp-3.9.3_7.2.0.zip-7.2.0.zip
Plugin installation was unsuccessful due to error "No valid url specified."

curl -I -k https://packages.wazuh.com/wazuhapp/wazuhapp-3.9.3_7.2.0.zip
HTTP/1.1 403 Forbidden
Content-Type: application/xml
Connection: keep-alive
Date: Sun, 30 Jun 2019 17:30:33 GMT
Server: AmazonS3
X-Cache: Error from cloudfront
Via: 1.1 a3e09c13ab143be1bcbc3667dbf89540.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: SYD4-C1
X-Amz-Cf-Id: bLXX8JqWhh92IGkVaZa2bK_x-A1qW6MMgvoS-8S3uGEYRHx5pKTCmg==

**Comment by pablotr9** [comment]
Hi @0xa-saline,

Wazuh app 3.9.3-7.2.0 is not ready yet, we are working on it and it will be ready very soon,
Thanks for the patience,

Regards,
Pablo Torres
