### ISSUE TITLE
7.2.0 OSS - MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by turbotoni** [wazuh/wazuh-kibana-app#1565]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.9.3   | 7.2     | |

**Description**
Hi there!
There are some errors related to the Kibana 7.2.0 OSS build with the new 7.2.0 app
MODULE_NOT_FOUND: ansicolors 
Already fixed -> https://github.com/wazuh/wazuh-kibana-app/commit/1832bb0963b58cbb94b01eb5a5b4dae32f756206

MODULE_NOT_FOUND: winston
MODULE_NOT_FOUND: needle

**Steps to reproduce**
1. Download and install Kibana OSS
2. Download and install the file v3.9.3-7.2.0.zip provided in the releases tab
3. Start Kibana

**Screenshots**
![2019-07-01 10_54_30-plugins](https://user-images.githubusercontent.com/28643466/60423816-46deb400-9bef-11e9-8d76-a6d58ba7b6a0.png)
![2019-07-01 10_55_32-@904c73fad041_~](https://user-images.githubusercontent.com/28643466/60423817-46deb400-9bef-11e9-9725-0e620641241d.png)

**Comment by pablotr9** [comment]
Hi @turbotoni,

Wazuh app 3.9.3-7.2.0 is not ready yet, we are working on it and it will be ready very soon,
As soon as 3.9.3-7.2.0 app is released, if you still have this problem I will be more than happy to help.
Thanks for the patience

Regards,
Pablo Torres
