### ISSUE TITLE
Several errors found in 3.9.3 App version

### ISSUE THREAD

**Issue by adri9valle** [wazuh/wazuh-kibana-app#1568]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.9.3   | 7.2.0     | 518 |

**Description**
Hi team, several errors were found in the Wazuh Kibana App 3.9.3 version:

##### Ruleset and CDB lists
- [x] App Error when deleting ruleset file and impossible to create new ruleset files 
- [x] The App does not handle the error when creating a new ruleset file and the file name exists.

![image](https://user-images.githubusercontent.com/7983984/60600962-7dfcc300-9db1-11e9-833c-80c8e79448f8.png)
- [x] `Undefined` name when removing CDB list file.
- [x] App Hang up when editing a CDB list value (https://github.com/wazuh/wazuh-kibana-app/issues/1485)
(https://github.com/wazuh/wazuh-kibana-app/issues/1567)
- [x] When creating a new CDB list if filter the content and there are not matches the `Save` button is dissabled even if the CDB list is not empty.

![filter_cdb](https://user-images.githubusercontent.com/7983984/60583120-78d84d80-9d8a-11e9-9be0-f3ae14191cbf.gif)
- [x] When editing a CDB lists if a field is removed the rest of fields are hidden but the total items number shows that the list is not empty:

![removing_hide_cdb](https://user-images.githubusercontent.com/7983984/60583273-d2d91300-9d8a-11e9-987e-a336e8867afa.gif)
- [x] When you go to the last page clicking on `Last` button in the CDB list and this page has only one element, if the element is deleted the pagination does not work and the CDB list content keeps blank.

##### Performance
- [ ] Parallel requests in the Management section are queued 

##### UI/UX
- [x] `<ignore type=“sregex”>.tmp$|.swp$|.viminfo$</ignore>` is not shown in the agent configuration. 
- [x] Remove url from  `rule.id`. 
- [x] Syscheck visualization query is wrong.
- [ ] Multiple error messages flood the screen.(https://developers.google.com/web/tools/chrome-devtools/network/reference#timing) and trigger timeout

**Comment by adri9valle** [comment]
**Update**

I'm working with @pablotr9 in this branch [fixes-3.9.3-7.2.0](https://github.com/wazuh/wazuh-kibana-app/tree/fixes-3.9.3-7.2.0)

**Comment by adri9valle** [comment]
**Update** 

The following problems have been solved, the explanation can be found in their issues comments.

- App Hang up when editing a CDB list value (#1485)
- App Error when deleting ruleset file and imposible to create new ruleset files (#1567)

**Comment by adri9valle** [comment]
**Update**

The link to the `rule.id` has been removed from the table visualization in the dashboards.

**Comment by adri9valle** [comment]
**Update**

Syscheck visualization query  is now correct:

![image](https://user-images.githubusercontent.com/7983984/60511058-5b937880-9cd1-11e9-9e61-4aceb34ba0a6.png)

**Comment by adri9valle** [comment]
** Update**
 > `<ignore type=“sregex”>.tmp$|.swp$|.viminfo$</ignore>` is not shown in the agent configuration. 

It seems that this error comes from the core, the API connect with the socket but does not receive the necessary information then the API cannot returnet this data.

**Pending Core/Pending API**

**Comment by adri9valle** [comment]
**Update**

> Parallel requests in the Management section are queued (https://developers.google.com/web/tools/chrome-devtools/network/reference#timing) and trigger timeout

After some tests, we have reached the conclusion that the problem is not the parallelism. 

We thought that the problem could be because when there are several requests launched if the number of requests is bigger than 6 the rest are queued and the timeout of these meanwhiles was running. But this is not the problem.

Also, we thought that the problem could be cause for a `Promise.all()` with several requests, but this is not the problem either because is not necessary a `Promise.all()`  an independent request could be delayed more than the default timeout set (20 seconds) and provokes the error.

This problem is rather an environment or network problem because the time execution of the request is not greater than 20 seconds to provoke the error.

A possible solution is increase the timeout in order to try to prevent the error. The default timeout is set in 20 seconds but in `Settings > Configuration` it can be changed.

![image](https://user-images.githubusercontent.com/7983984/60516049-386ec600-9cdd-11e9-89ab-a405a0bd6b0b.png)

**Comment by adri9valle** [comment]
**Update**

> `Undefined` name when removing CDB list file.

Now works fine: 

![image](https://user-images.githubusercontent.com/7983984/60524067-2d6f6200-9cec-11e9-85ee-85fdc237642c.png)

**Comment by adri9valle** [comment]
**Update**

>  When editing a CDB lists if a field is removed the rest of fields are hidden but the total items number shows that the list is not empty.

While working on this issue I realized that the navigation between the CDB lists has problems too, when removing an item from the last page or when moving to the last page or first directly.

These problems have been solved here: https://github.com/wazuh/wazuh-kibana-app/pull/1569/commits/621a97b5e611a4b8ca86f9fa5bcbad5313f9fda2

**Comment by adri9valle** [comment]
**Update**

> When creating a new CDB list if filter the content and there are not matches the Save button is dissabled even if the CDB list is not empty.

Solved here: https://github.com/wazuh/wazuh-kibana-app/pull/1569/commits/91e4890424dc17e65cf668304a20464c9d950a59

**Comment by adri9valle** [comment]
**Update**

> ￼ The App does not handle the error when creating a new ruleset file and the file name exists.

![image](https://user-images.githubusercontent.com/7983984/60602697-95897b00-9db4-11e9-90d6-c518ee5e2fd7.png)


Solved.

**Comment by adri9valle** [comment]
**Update**

> Multiple error messages flood the screen.

I've tested it in a dashboard out of the Wazuh app and it occurs too:

![flood_dashboard_test](https://user-images.githubusercontent.com/7983984/60648088-800d6300-9e3f-11e9-819c-32d60d3f0e08.gif)

**Comment by adri9valle** [comment]
**Update**

The parallel requests error is provoked because when the `Promise.all()` launches several requests the API only receives the first, then the App is waiting for the other request which will be never resolved.

![image](https://user-images.githubusercontent.com/7983984/60663253-f40b3380-9e5e-11e9-84a4-0e49d0f8211b.png)

![image](https://user-images.githubusercontent.com/7983984/60663286-12712f00-9e5f-11e9-894a-56910c56caf7.png)

I'm trying to find out when and where are lost the other request.

**Comment by pablotr9** [comment]
**Update**
 - [ ] <ignore type=“sregex”>.tmp$|.swp$|.viminfo$</ignore> is not shown in the agent configuration. 
https://github.com/wazuh/wazuh/pull/3617

Ignore type sregex are now shown in both agent and manager configuration tabs:
![sregex](https://user-images.githubusercontent.com/35685689/60674832-49edd480-9e7b-11e9-92e0-0c855cd42fe2.png)
![sregexjson](https://user-images.githubusercontent.com/35685689/60674836-4b1f0180-9e7b-11e9-94bc-008e908d9889.png)

**Comment by pablotr9** [comment]
**UPDATE**
Ignored paths and sregex type were missing and have been added to Policy monitoring -> Ignored tab
![image](https://user-images.githubusercontent.com/35685689/60677821-dea80080-9e82-11e9-8b10-3935bbb9d613.png)

**Comment by adri9valle** [comment]
**Update**

> <ignore type=“sregex”>.tmp$|.swp$|.viminfo$</ignore> is not shown in the agent configuration.

Has been finished.
