### ISSUE TITLE
vulnerabilities dashboard: display all cve in Alert summary ?

### ISSUE THREAD

**Issue by aderumier** [wazuh/wazuh-kibana-app#1576]
Hi,

on vulnerabilities dashboard,  
The "alert summary" panel only display top 5 cve.
Is it possible to display all cve ?  (or is it possible to edit the visualisation ?)

**Comment by pablotr9** [comment]
Hi @aderumier ,

That specific visualization on our vulnerabilities dashboard is currently set to show the top 5 CVEs and that limit can't currently be modified but If you want to create a custom visualization with some specific requirements, you can easily do that following these steps:
 - Go `Kibana` -> `Visualize` tab
- Create a new visualization of **pie** type and then select the index pattern **wazuh-alerts-3.x-***
Then you can set the limit of CVEs of the visualization as shown in this next screenshot:
![image](https://user-images.githubusercontent.com/35685689/60812083-fb994800-a190-11e9-8481-25c53063110e.png)

I hope it helps, if you need anything else do not hesitate to ask again.

Regards,
Pablo Torres

**Comment by aderumier** [comment]
Hi,
yes I known that I can do a custom visualization, but it is possible to add it in the current wazuh dashboard ?  (If not, it could be a great improvement for next wazuh releases).

**Comment by pablotr9** [comment]
Hi @aderumier,
Indeed that would be a really nice new feature to include in our app, I have created a new issue and we'll study it, thank you so much for the suggestion:
https://github.com/wazuh/wazuh-kibana-app/issues/1578

If you have any other suggestions or need any help we are all ears!

Regards,
Pablo Torres
