### ISSUE TITLE
Filters broken for dashboards

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1583]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.9.3   | 7.2     | 520 |

**Description**
Filters are being applied the very first time, but if the user changes the tab and then go back, filters are now being applied as expected.

**Steps to reproduce**

1. Click Agents > :some_agent
2. Open Security Events
3. Now click on a different dashboard such as FIM
4. Go back to Security Events, now the `agent.id` filter is now being applied.

**Screenshots**

![image](https://user-images.githubusercontent.com/8860227/61110758-516b3a00-a488-11e9-83a6-bfa8914acbca.png)

As we can see, there is a mixing of alerts in the above screenshot.

**Comment by jesusgn90** [comment]
After some researching, I think we've found the main cause of this issue.

It's related to the latest changes in Discover directive, some functions are called for fetching data as it did before but now we have to check if the Wazuh filters are ready in one more place.

https://github.com/wazuh/wazuh-kibana-app/blob/0639d2eb58992f03e13dfeaa5fe016255818075a/public/kibana-integrations/kibana-discover.js#L399-L402

As we can see, the above function is updating the fetching source with no filter checks as other functions do. The solution was just adding our filter blocker at the very first line of that function https://github.com/wazuh/wazuh-kibana-app/commit/f50ac08bb3c752d41e6765f773642f0a10a31853.

```js
if(!filtersAreReady()) return;
```

That's like a lock for the Wazuh filters, and we were using it from a long time ago, but with the 7.2 changes we forgot to add the lock to the recently added event subscription named `filterUpdateSubscription`.

In any case, **pending testing**.

**Comment by juankaromo** [comment]
### Testing report

**Fully remove "rule.id" as URL feature #1584**

![image](https://user-images.githubusercontent.com/21195730/61123960-f5afa980-a4a5-11e9-8c30-32707078b933.png)

Rule link is removed in the Security Events Alerts summary rule.id table filed.  Test passed successfully. ✅

**Filters broken for dashboards #1583**

...
