### ISSUE TITLE
Improve process table in inventory tab for Linux agents

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1585]
**Describe the solution you'd like**
The Wazuh API is giving us more fields than we are showing to the user. We should add the missing fields.

**Additional context**
Here is how the table looks right now:

![image](https://user-images.githubusercontent.com/8860227/61111182-4bc22400-a489-11e9-85d1-2e716779c184.png)

And here we can see the fields given by the Wazuh API:

![image](https://user-images.githubusercontent.com/8860227/61111222-60062100-a489-11e9-9700-3ecbadfbcfb8.png)

**Comment by adri9valle** [comment]
**Update**

In windows have been added: `pid,ppid,vm_size` and in Unix system: `egroup,pid,ppid,cmd,argvs,vm_size,size,session`.

##### Windows
![image](https://user-images.githubusercontent.com/7983984/61122940-60abb100-a4a3-11e9-9f63-6266493b4f69.png)

##### Unix
![image](https://user-images.githubusercontent.com/7983984/61122980-74efae00-a4a3-11e9-825b-66a175bb34a1.png)

**Comment by jesusgn90** [comment]
![image](https://user-images.githubusercontent.com/8860227/61123561-f1cf5780-a4a4-11e9-8795-27ba75439fdd.png)

Please, resize some columns, it doesn't make sense having PPID column with the same width as CMD column for example.

**Comment by adri9valle** [comment]
**Update**

###### Backport testing 7.1.1

I did the cherry-pick in my local `3.9.3-7.1.1` branch and works properly.

```
git cherry-pick a913e8fc2ccdc6dd1087f190e5f740f4ee760362
```

**Comment by adri9valle** [comment]
> ![image](https://user-images.githubusercontent.com/8860227/61123561-f1cf5780-a4a4-11e9-8795-27ba75439fdd.png)
> 
> Please, resize some columns, it doesn't make sense having PPID column with the same width as CMD column for example.

Now this problem is solved in this commit https://github.com/wazuh/wazuh-kibana-app/pull/1590/commits/81513554c947f01024a8313604510ec91db8e936:

![image](https://user-images.githubusercontent.com/7983984/61133219-47aff980-a4bd-11e9-84f2-a70382192491.png)

**Comment by adri9valle** [comment]
**Update**

In 6.8.1 this problem has been solved too.

##### Windows 

![image](https://user-images.githubusercontent.com/7983984/61134977-04578a00-a4c1-11e9-8cff-14a54439d618.png)


##### Linux
![image](https://user-images.githubusercontent.com/7983984/61135025-1d603b00-a4c1-11e9-82b4-3f4b72fefda0.png)

**Comment by adri9valle** [comment]
**Update**

The processes table is hidden when the agent is MacOs.
