### ISSUE TITLE
[6.x] Cluster monitoring chart only shows master node events

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1586]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.9.3   | 6.8.1     | 448 |

**Description**
Our chart for alerts by node summary is not showing events from worker nodes, however, those nodes have alerts as I can see them in the Discover tab.

**Steps to reproduce**

1. Go to Management > Cluster
2. See the "Alerts by node" chart, it's not showing data for worker nodes.

**Screenshots**

![image](https://user-images.githubusercontent.com/8860227/61111840-c8a1cd80-a48a-11e9-8d5e-2197b89eaf3b.png)

![image](https://user-images.githubusercontent.com/8860227/61111883-e2431500-a48a-11e9-9b52-e119d9f2a406.png)

It doesn't make sense, we must to fix it.

**Comment by juankaromo** [comment]
Hi team,

We have tried to reproduce what is indicated but we have not succeeded. The alerts of the worker node **are being shown** in the monitoring graph.

We will continue investigating.

![image](https://user-images.githubusercontent.com/21195730/61115352-91371f00-a492-11e9-903c-c218b74832ae.png)


Regards
