### ISSUE TITLE
Review "Events over time" visualization in policy monitoring tab

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1602]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.9.3   | 6/7     | n/a |

**Description**
From our mailing list ([details](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/wazuh/CiUmkF3Pd68/majgK7gNDAAJ)), it's reported that our visualization "Events over time" for policy monitoring is being rendered in a weird way. We should review it.

**Screenshots**

![image](https://user-images.githubusercontent.com/8860227/61200720-ae622c80-a6e2-11e9-92df-d908f6b732ea.png)

Regards

**Comment by adri9valle** [comment]
This visualization has been changed. Now is a vertical bar visualization:

![image](https://user-images.githubusercontent.com/7983984/63342928-0aa51580-c34d-11e9-8825-20bc30a732fe.png)
