### ISSUE TITLE
Wazuh Reports download Forbidden

### ISSUE THREAD

**Issue by xufengnian** [wazuh/wazuh-kibana-app#1606]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.9.2-1   | 7.1.1     |  |

**Description**
 I generated a SCA report or vulner report ，but when I try to download it, the kibana response tell me "403 "error":"Forbidden""

**Steps to reproduce**

1. Go to 'Overview/SCA'
2. Click on 'Generate report'
3. Go to 'Management / Reporting' try to download the pdf
4. See error {"statusCode":403,"error":"Forbidden","message":"Forbidden"}

**Screenshots**
![image](https://user-images.githubusercontent.com/15324125/61271134-586eb100-a7d6-11e9-990b-175d0c74c488.png)

![image](https://user-images.githubusercontent.com/15324125/61271150-60c6ec00-a7d6-11e9-806f-84fb50798677.png)

**Additional context**
I try to find the pdf in kibana document "kibana-7.1.1-linux-x86_64/optimize/wazuh-reporting/wazuh-overview-sca-1563258046.pdf".And change mode 777 in the document,but it's useless.So I just want to know how to solve it,thx!

**Comment by juankaromo** [comment]
Hi @xufengnian 

Did you solve the problem? Or what's the current situation? It looks like it's a directory permission problem, an incorrect directory owner, or a Kibana custom spaces problem. For the latter, I recommend upgrading to the current version of Wazuh.

Do not hesitate to ask again if it is not solved or if you have any other doubt.

Regards

**Comment by jesusgn90** [comment]
Hi @xufengnian,

Long-time from your last response so I'm going to close this ticket. Please don't hesitate to re-open it or to create a new one if needed.

Kind regards
