### ISSUE TITLE
Agent→Discover will show Agent→Dashboard when page is refreshed

### ISSUE THREAD

**Issue by jojelupipa** [wazuh/wazuh-kibana-app#1611]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.x   | 6.x     | 444 |

**Description**
Using kibana v7.1.1 I realized that in the Agent/Discover section, if you reload the page it will jump into Dashboard instead of showing Discover again. It is not a big problem but it might not be the expected behaviour.

**Steps to reproduce**

1. Go to Agents
2. Go to any agent
3. Click on the `Discover`button
4. Reload the page (either manually, pressing F5 or Ctrl+R in Firefox)

Then it will have jumped into the Dashboard view instead of Discover view again.

**Screenshots**
Guess it's not necessary, it will just load a different page

**Additional context**
None

**Comment by juankaromo** [comment]
Hi @jojelupipa 

Thank you for reporting this. It will be fixed in future versions. Stay tuned to this ticket for progress. 

Regards.
