### ISSUE TITLE
Is there a plan to provide a multilingual solution?

### ISSUE THREAD

**Issue by MSG-maniac** [wazuh/wazuh-kibana-app#1636]
If there is a plan, I can provide a Chinese version of the translation work.

**Comment by juankaromo** [comment]
Hi @MSG-maniac 

Thank you very much for your suggestion and your willingness to contribute to the project. Currently, there are many high priority issues in our near roadmap that do not allow us to implement a multilingual solution (at this time). But don't worry, we will consider your request and get to work on it as soon as possible.

Stay tuned to this issue to see progress. 

Thank you very much again and greetings!

**Comment by juankaromo** [comment]
Hi @MSG-maniac
