### ISSUE TITLE
Rebuild HIPAA and NIST-800-53 dashboards

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#1638]
We need to rebuild and create some visualizations for the HIPAA and NIST-800-53 dashboards that give us rich information from the alerts.

Also, we need to change the way to show the requirements of PCI DSS, GDPR, HIPAA, and NIST-800-53.

- [x] New way to show the requirements. https://github.com/wazuh/wazuh-kibana-app/pull/1708
- [x] NIST Overview panel 
- [x] HIPAA Overview panel
- [x] NIST Agents panel 
- [x] HIPAA Agents panel

Regards,

**Comment by juankaromo** [comment]
Working on this branch https://github.com/wazuh/wazuh-kibana-app/tree/rebuild-hipaa-nist

**Comment by adri9valle** [comment]
**Update 30.07.19**

I've fixed several problems with the `HIPAA` and `NIST` extensions.

- The popover in the Overview and Agents welcome had not shown the  `HIPAA` and `NIST` extensions https://github.com/wazuh/wazuh-kibana-app/commit/61500997a87e8fce291b5275d8a73b376cae0edd
- The navbar in the overview section always shows  the  `HIPAA` and `NIST` extensions https://github.com/wazuh/wazuh-kibana-app/commit/bdb5fe08afeb13e3679356046d3cae84c96cf7c5
- The navbar in the agents section always shows  the  `HIPAA` and `NIST` extensions https://github.com/wazuh/wazuh-kibana-app/commit/2561314291ce2eaf46cae05fd86bd4bc6d3cfe75

**Comment by juankaromo** [comment]
**Update 30/07/2019**

We have some proposals to change the design of HIPAA and NIST-800-53 requirements selector.

@adri9valle propose this:

![image](https://user-images.githubusercontent.com/21195730/62135907-5b43c880-b2e3-11e9-98c4-1102ab0340f5.png)

The cards that would go down would be passed in carousel mode as well as now, but at a glance, you have several descriptions of the requirements without having to click on any simply pages.

Right now it's paginated and you also have to click.

![image](https://user-images.githubusercontent.com/21195730/62136072-acec5300-b2e3-11e9-8ffd-80f1a3f2c043.png)


@juankaromo propose this:

![image](https://user-images.githubusercontent.com/21195730/62136108-b7a6e800-b2e3-11e9-986e-aa0d929a74da.png)

It would be added that when clicking on the request the filter would be added to the search and the visualizations would be updated.

**Comment by juankaromo** [comment]
**Update 31/07/2019**

It is proposed to make a summary table of the severity of the requirements in alerts that have occurred. For them, a table would be made that would substitute a visualization and would be fed with the data of this one but using them in a component of React of type EuiTable.

![image](https://user-images.githubusercontent.com/21195730/62223697-ac23f180-b3b5-11e9-8b45-b4f82fcfcb2c.png)

**Comment by juankaromo** [comment]
Update 12/08/2019

Today I have been trying to do some "metric" visualizations to get the number of alerts per requirement. With this data, I will load a component that will show the cards with the available requirements, with the number of their alerts and their description. And finally, from each card, you can add a filter by clicking on it.

**Comment by adri9valle** [comment]
**Update 21.08.19**

The requirements of PCI DSS, GDPR, HIPAA, and NIST 800-53 have been changed. Previously the look was:

![image](https://user-images.githubusercontent.com/7983984/63429421-4528b400-c41a-11e9-8372-b8f3e44f6efe.png)

Now it looks like: 

![image](https://user-images.githubusercontent.com/7983984/63429458-67223680-c41a-11e9-8821-ab4de1c24698.png)

- [x] Changed the previous md-card for a carousel of cards in Overview.
- [ ] Changed the previous md-card for a carousel of cards in Agents.
- [ ] Fill the empty space if the last array of cards is minor that number which it was split.
- [ ] When the description is too large it is compressed and a footer is shown in order to expand it and show the full description. (The footer is shown but the expand capability is missing).

**Comment by adri9valle** [comment]
**Update 22.08.19**

- Avoided the carousel effect.
- Avoided the hover and focus styles that make the sensation of a clickable card.

**Comment by adri9valle** [comment]
**Update 23.08.19**

The HIPAA dashboard has been replaced in the agents section.

New look:

![image](https://user-images.githubusercontent.com/7983984/63587218-9fa14c00-c5a3-11e9-8b09-b55497f16765.png)
