### ISSUE TITLE
Testing for PR #1640

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1642]
Related PR: https://github.com/wazuh/wazuh-kibana-app/pull/1640

**Tests**

- [x] Health check
  - [x] Launch it with no API entries
  - [x] Launch it with API entries
- [x] Cookies
  - [x] API in the cookie not present in .wazuh
  - [x] API in the cookie also present in .wazuh
- [x] Cluster status changes
  - [x] Changing state in the top menu should update it
  - [x] Filters are properly set depending on the cluster status
- [x] There are no errors related to API credentials 2 seconds cache
- [x] There are no errors related to config.yml 10 seconds cache

**Comment by adri9valle** [comment]
**Update**

##### Health check
- Launch it with no API entries: The APPs redirects directly to the API configuration in order to add the first API entry.
- Launch it with API entries: The health check is successfully.
