### ISSUE TITLE
Agent search filter by name, lost when refreshing

### ISSUE THREAD

**Issue by migruiz4** [wazuh/wazuh-kibana-app#1649]
I team,

I found an issue with the Agents tab. When searching by agent name, if I click on the refresh button, my filter still appears on the UI but is not really applied:

![imagen](https://user-images.githubusercontent.com/37381070/62310177-3a1cdc80-b489-11e9-8907-75560850828b.png)

Searching by agent name, before clicking refresh:
![imagen](https://user-images.githubusercontent.com/37381070/62310264-69cbe480-b489-11e9-9163-a0d721bf09a8.png)

After clicking refresh:
![imagen](https://user-images.githubusercontent.com/37381070/62310383-b0214380-b489-11e9-8191-549496bad98e.png)

It also happens when combined with some other filters. After refreshing, ignores the name search but not the rest of the filters.

I found this issue in versions 3.9.2-6.8.0 and 3.9.3-7.2.0.

Best regards,
Miguel

**Comment by juankaromo** [comment]
Hi @migruiz4 

It has been solved here https://github.com/wazuh/wazuh-kibana-app/commit/15ef7b4c5d190bdf7cee37b7599535159ede31ba
