### ISSUE TITLE
Missing scrollbar on Firefox file viewer

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-kibana-app#1650]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.9.3   | 7.2.0     | 0532 |

**Description**
Scroll is missing for viewing ruleset files on Firefox

**Steps to reproduce**
Using Firefox (tested on 67.0.1 and 68.0.1 both on Windows and Linux)
1. Go to Management > Ruleset
2. Click on `Manage rule files
3. Click on `View this file` (the eye icon) for any default file
4. See there is no scroll bar on the right and the mouse wheel doesn't work.

**Screenshots**
![missing_scrollbar](https://user-images.githubusercontent.com/36071202/62310715-66852880-b48a-11e9-96ec-9bc27928e0c3.png)

**Additional context**
As a workaround you may select text by clicking and dragging outside of the viewed portion of the file or click on the text and then use the keyboard keys to navigate the file.
May be related to this: https://github.com/wazuh/wazuh-kibana-app/issues/1439

**Comment by pablotr9** [comment]
**Update**
Hi @jctello, thanks for reporting this.
I have also noticed that it is also happening at Management -> Configuration -> Main Configurations JSON/XML viewer.
It has been fixed here: https://github.com/wazuh/wazuh-kibana-app/commit/53aa38d209abbaa310c7a3ee2145a07ac8ed7334
