### ISSUE TITLE
Missing plugin for elasticsearch 6.8.2

### ISSUE THREAD

**Issue by alyakimov** [wazuh/wazuh-kibana-app#1651]
Hello! Could you build the plugin for elasticsearch 6.8.2?

**Comment by juankaromo** [comment]
Hi @alyakimov 

The new release of Wazuh 3.9.4 will include compatibility with ELK 6.8.2 (and also 7.2.0 and 7.3.0). 

We are testing it for any breaking change and release a version as robust as possible. We hope to have it ready very very soon if all testing goes well and It will be released in a few days, with the new version of Wazuh. I'll let you know here when we have it. 

Thanks for the patience!

Regards.
Juan Carlos

**Comment by x0james** [comment]
Also expect, do not know how long it will take?Thank you.

**Comment by juankaromo** [comment]
Hi @x0james 

Wazuh 3.9.4 has been released and gives us compatibility for ELK 6.8.2. You can find the app installation package here: https://packages.wazuh.com/wazuhapp/wazuhapp-3.9.4_7.3.0.zip

If you have any questions about how to update it, please do not hesitate to contact us.

Thanks for the patience!
Regards.

**Comment by alyakimov** [comment]
Hi! Thanks a lot!

**Comment by x0james** [comment]
Thanks a lot!
