### ISSUE TITLE
Defects reported by the DevOps team for v3.9.4-rc4

### ISSUE THREAD

**Issue by adri9valle** [wazuh/wazuh-kibana-app#1652]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.9.4   | 7.2     | 527 |

The DevOps team has figured out several realized about several bugs in the Wazuh App 3.9.4.

**Description**
- [x] Number of agents is not properly updated
- [x] Windows agent dashboard doesn't show failure logon access
- [ ] <del>Reports are setting European timezone </del>
- [x] Alerts of level 12 cannot be displayed in the table

**Steps to reproduce**
##### Number of agents is not properly updated
1 - "Go to Agents section, notice the number of agents and the list.
2 - Then, register a new agent and click on 'reload' button.
3 - The list is updated but not the total number of agents."
##### Windows agent dashboard doesn't show failure logon access
Try to badly connect to a Windows agent. The counter is not increased
##### Reports are setting European timezone 
"Be in USA. Then generate a report and notice the timestamp.
It's set to european timezone."
#####  Alerts of level 12 cannot be displayed in the table
"Overview > Security events. Notice there are alerts with level 12 or more.
Go to the table, there are no such alerts."

**Comment by adri9valle** [comment]
**Update 02.08.19**

##### Number of agents i not properly updated https://github.com/wazuh/wazuh-kibana-app/commit/2da573eace04196a13ada5f8af5cc66a7789f35a

This has been solved refreshing the agents summary again, the table was being refreshed but the stats are not.

**Comment by pablotr9** [comment]
**Update**
##### Alerts of level 12 cannot be displayed in the table
In case we had many rules with same description or same rule ID but different level, just one of them was being shown, now we show all the alerts regardless the rule description, level or ID. Fixed here: https://github.com/wazuh/wazuh-kibana-app/commit/285ef67a456d290e5fedd43a7c46816c963638a4
