### ISSUE TITLE
Beats and Wazuh. 

### ISSUE THREAD

**Issue by dwizel** [wazuh/wazuh-kibana-app#1669]
Beats and Wazuh
Hi Guys, new Wazuh/Linux person and new to deploying a SIEM and monitoring solution. I would like to know if it's possible to use beats with Wazuh or everything runs through the agent?

My server runs on a Ubuntu 16.04 with the latest Wazuh software. 

If possible I would like to monitor some Cisco routers and switches in my organization. I currently have Nfsen listening for Netflow, is it possible to configure Wazuh and Elasticsearch to listen on the same port?

**Comment by jsanchez91** [comment]
I dwizel,

You can install Wazuh and Beats components in the same ELK but they'll work separately. For example, Wazuh saves the alerts in the `wazuh-alerts-*` index and Auditbeat in the `auditbeat-*` index.

The Wazuh platform has the tools to cover the same functions of Beats components, you can see these links in the Wazuh documentation.

- **Network traffic**: https://documentation.wazuh.com/current/learning-wazuh/suricata.html
- **Keep watch for malicious command execution**: https://documentation.wazuh.com/current/learning-wazuh/audit-commands.html
- **System inventory**: https://documentation.wazuh.com/3.x/user-manual/capabilities/syscollector.html



On the question of monitoring Cisco devices, we have an article on our blog about this.

https://wazuh.com/blog/monitoring-network-devices-wazuh-hids/

I hope it helps. Please, don't hesitate to ask again if you have more doubts.

Best regards,
Jose.

**Comment by dwizel** [comment]
Thank you jsanchez91, I shall have a look at your recommended links and respond if I have any issues.

**Comment by dwizel** [comment]
Hi there again, I followed the step by step procedure to install wazuh from scratch. However I can't get elasticsearch to accept connections from remote locations. I have transformed it by sending filebeat logs to logstash and "filebeat test output" works okay but I when I curl elasticsearch using the IP I get a "connection refused"

**Comment by pablotr9** [comment]
Hi @dwizel ,

How does your **elasticsearch.yml** look like? that file can be found here: `/etc/elasticsearch/elasticsearch.yml`

Edit that file and add the following line:
`network.host: ELASTIC_IP`
Replace ELASTIC_IP with the Elastic server IP

That will allow connections from others IPs to ELASTIC_IP:9200, then you can simply do this curl from a remote IP to test if it's working:
`curl ELASTIC_IP:9200`

Let me know if it helps,

Regards,
Pablo Torres

**Comment by dwizel** [comment]
Okay, that worked when I used it's IP address but when I ran 'curl' it refused the connetion, is there a way to fix that?

**Comment by jsanchez91** [comment]
Hi @dwizel 

Have you restarted the Elasticsearch service after modifying the `elasticsearch.yml`?

To restart Elasticsearch:
```bash
systemctl restart elasticsearch
```

I hope it helps. Please, don't hesitate to ask again if you have more doubts.

Best regards,
Jose.

**Comment by fredt34** [comment]
I defined

    network.host: 0

which is 0.0.0.0 so it listens on both 127.0.0.1 / localhost and its network IP address. Makes things much easier!

**Comment by pablotr9** [comment]
Hi,

Thanks @fredt34 you are right that line should be enough to make it work.
This issue has been solved here https://github.com/wazuh/wazuh-kibana-app/issues/1683.
If you need anything else do not hesitate to reopen this issue or open a new issue

Best regards,
Pablo Torres
