### ISSUE TITLE
Alerts summary table is unreliable due to limitation

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-kibana-app#1671]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.9.4   | 7.3.0     | 0528 |

**Description**
When there are more than 50 different types of alerts the Summary table will omit some of the results, which can be very misleading as they seem to show only the most frequent so high level alerts are not really visible when sorting by level if they are less common.

**Steps to reproduce**

1. Have many alerts of different types. 
  a. On a testing environment the following one-liner may be run on the manager to achieve this:
```
for i in {1000..1100}; do now=$(date +%Y-%m-%dT%H:%M:%S.000+0000); echo '{"timestamp":"'$now'","rule":{"level":3,"description":"Injected alerts for testing","id":"'$i'","firedtimes":1,"mail":false,"groups":["syslog","sudo"],"pci_dss":["10.2.5","10.2.2"],"gpg13":["7.6","7.8","7.13"],"gdpr":["IV_32.2"]},"agent":{"id":"000","name":"master"},"manager":{"name":"master"},"id":"1565274509.75691","cluster":{"name":"wazuh","node":"node01"},"full_log":"Injected alerts for testing","predecoder":{"program_name":"sudo","timestamp":"Aug  8 14:28:27","hostname":"master"},"decoder":{"parent":"sudo","name":"sudo"},"data":{"srcuser":"vagrant","dstuser":"root","tty":"pts/0","pwd":"/home/vagrant","command":"/bin/su"},"location":"/var/log/secure"}' >> /var/ossec/logs/alerts/alerts.json ; done
```
   b. run this several times if you want these to have a higher count number
   c. You may add a couple of high level alerts for show:
```
for i in {1..2}; do now=$(date +%Y-%m-%dT%H:%M:%S.000+0000); echo '{"timestamp":"'$now'","rule":{"level":12,"description":"Injected alerts for testing","id":"'$i'","firedtimes":1,"mail":false,"groups":["syslog","sudo"],"pci_dss":["10.2.5","10.2.2"],"gpg13":["7.6","7.8","7.13"],"gdpr":["IV_32.2"]},"agent":{"id":"000","name":"master"},"manager":{"name":"master"},"id":"1565274509.75691","cluster":{"name":"wazuh","node":"node01"},"full_log":"Injected alerts for testing","predecoder":{"program_name":"sudo","timestamp":"Aug  8 14:28:27","hostname":"master"},"decoder":{"parent":"sudo","name":"sudo"},"data":{"srcuser":"vagrant","dstuser":"root","tty":"pts/0","pwd":"/home/vagrant","command":"/bin/su"},"location":"/var/log/secure"}' >> /var/ossec/logs/alerts/alerts.json ; done
```
2. Go to the Security Events dashboards
3. Scroll down to the Events Summary table
4. See only the events with higher counts are visible. 
  a. Sort by level and observe none of the ones with lower counts are visible

**Screenshots**
In the following image you may see that it is indicated that there are 2 level 12 events, however the table is sorted by level and it isn't showing anything above 7.
![image](https://user-images.githubusercontent.com/36071202/62713406-f8e27a80-b9fc-11e9-8e36-93a7437a2139.png)

**Additional context**
There was an attempt to fix this here:  https://github.com/wazuh/wazuh-kibana-app/commit/ec0e8885d9f1306523afbc87de01a31f24e36309 but it seems the issue prevails.

This table is limited to 51 results. Why not make it around the size of the ruleset? (~2700 rules, or 2066 rules level 3 or above) to make sure that at least in most cases it will have an entry for every possible ID. That would be changed [here](https://github.com/wazuh/wazuh-kibana-app/blob/master/server/integration-files/visualizations/overview/overview-general.js#L262).

**Comment by peppelinux** [comment]
I completely agree with this,
Also it should be great if a user could set the number of rows to be rendered
