### ISSUE TITLE
Can't Disable PCI-DSS in Kibana App

### ISSUE THREAD

**Issue by triggerman86** [wazuh/wazuh-kibana-app#168]
When I toggle the PCI-DSS setting off, it does not actually apply. 

How do I disable the PCI-DSS stuff if we don't use it?

**Comment by JuanjiJG** [comment]
Hi @dtmarr, and sorry for the late response.

We're aware of this issue with the *Extensions* settings. The team is working on fixing it.

We'll let you know when we release a new version of the Wazuh App with the appropiate bugfixes for this. Thanks for your patience.

Best regards,
Juanjo

**Comment by havidarou** [comment]
Hi @triggerman86 ,

this has already been fixed in our latest version.

Regards.
