### ISSUE TITLE
Elasticsearch not working when network.host is changed to listen on all ports

### ISSUE THREAD

**Issue by dwizel** [wazuh/wazuh-kibana-app#1683]
I've followed the Wazuh setup with transformation to pipe information to Logstash, however when I try to change the network.host to 0.0.0.0 elasticsearch crashes. I've increased the heap from 4g to 6g and that's still not fixing it. The error I get is "openjdk 64-bit server vm warning: option useconcmarksweepgc". Any help would be appreciated for a first time user.

**Comment by pablotr9** [comment]
Hi @dwizel ,

What version of Elasticsearch are you using? Are all of the other components (kibana,logstash,filebeat) the same version? 
Could you please share with us your Elasticsearch configuration file? you can find it in `/etc/elasticsearch/elasticsearch.yml`

Could you also attach the Elasticsearch error log, you can find that file in `/var/log/elasticsearch/(cluster-name|elasticsearch).log`

Regards,
Pablo Torres

**Comment by dwizel** [comment]
Hello Pablo, 
I am using the latest version 3.9, and yes the other components are all the same versions per the instructions from the Wazuh installation documentation page. This is a single node but I will attach the error log as well. Please be patient with me as I'm still new to this. 

[elasticconfig.txt](https://github.com/wazuh/wazuh-kibana-app/files/3499526/elasticconfig.txt)
[elasticlog.txt](https://github.com/wazuh/wazuh-kibana-app/files/3499527/elasticlog.txt)

**Comment by pablotr9** [comment]
Hi @dwizel ,

Take a look into your **_elasticsearch.yml_**:
```
...
# Set the bind address to a specific IP (IPv4 or IPv6):
#
# network.host: 0.0.0.0
....
```
*Just in case you didn't know it: lines starting with `#`  is a comment, so everything you write after the `#` will be ignored.

Could you please add this line to the **elasticsearch.yml**:
`network.host: 0.0.0.0`
and restart Elasticsearch :
`systemctl restart elasticsearch`
wait some seconds until Elasticsearch is up, you can check its status with this command:
`systemctl status elasticsearch`

Could you confirm that you are still receiving `connection refused` from the `curl elastic-ip:9200` from your remote server?
Does that remote server have access to the Elasticsearch server? we can know that using `telnet`  command (you'll have to install it if it's not already installed)
`telnet <elastic-ip> 9200`
Please paste the output of above command

Regards,
Pablo Torres

**Comment by dwizel** [comment]
I did remove the # after I changed it to 0.0.0.0, it started then failed. I have changed it to the IP address of my elastic server and it hasn't failed since then. I tried to curl it but the connection was refused. Be advised I am sending it to Logstash per Wazuh's documentation.

**Comment by pablotr9** [comment]
Hi @dwizel ,

Sorry for the late reply, the data flow should be as follows:
**Filebeat** -> **Logstash** -> **Elasticsearch**

You can test if Filebeat is successfully sending alerts to Logstash with this command (please paste the output of the following commands):
`filebeat test output`

Now let's check Logstash logs:
`tail /var/log/logstash/logstash-plain.log`

Now please check Elasticsearch status:
`systemctl status elasticsearch`

Now paste the output of this command:
`tail -n 100 /var/log/elasticsearch/my-cluster.log`

Check if you have access to that remote IP, we can check that with the command `telnet`:
`telnet <elastic-ip> 9200`

Regards,
Pablo Torres

**Comment by dwizel** [comment]
Not a problem Pabl. The command filebeat test output works. Elasticsearch is up and running and I have pasted the logs for the 2 you requested above. However telnet doesn't work, says connection is refused. 

[elasticlog.txt](https://github.com/wazuh/wazuh-kibana-app/files/3514596/elasticlog.txt)
[logstashlog.txt](https://github.com/wazuh/wazuh-kibana-app/files/3514597/logstashlog.txt)

**Comment by pablotr9** [comment]
Hi @dwizel ,

I can see that Logstash is sending alerts to Elasticsearch and they are successfully being received by Elasticsearch. Is your Logstash in the same machine as Elasticsearch? Could you share with us your Logstash configuration file? This file is located here:
`/etc/logstash/conf.d/01-wazuh.conf`
Can you access Kibana and visualize these alerts? 
If you are still receiving _Connection refused_ when doing a `curl` to your Elastic IP server from a remote machine, we should check if the machine is visible to that remote machine:
- In your Elasticsearch machine run this command:
`tcpdump -i any -n dst port 9200`
This will listen to all packages sent to the machine, so we can see if they are being received or not.

- Now (while the previous `tcpdump` is running and listening to all packages sent to it) in your remote machine send a `curl` to the Elastic server IP:
`curl elastic_ip:9200`

If the package was received by the Elasticsearch machine, `tcpdump` should have printed something similar to this:
```
08:27:49.555160 IP 172.16.2.1.37014 > 172.16.2.6.irdmi: Flags [.], ack 626, win 238, options [nop,nop,TS val 421449832 ecr 10728830], length 0
```

Keep me updated so we can give you further assistance.

Regards,
Pablo Torres

**Comment by dwizel** [comment]
Thanks Pablo, yes my Logstash is on the same machine as Elasticsearch (we are a small organization). The linne below is what I got from tcpdump: 
172.30.1.117.43598 > 172.30.1.117.9200: Flags [S], seq 2079676412, win 43690, options [mss 65495,sackOK,TS val 418068043 ecr 0,nop,wscale 7], length 0

I have also attached my Logstash config.
[logstashconf.txt](https://github.com/wazuh/wazuh-kibana-app/files/3527705/logstashconf.txt)

**Comment by pablotr9** [comment]
Hi @dwizel ,
I've tried to reproduce your issue with no success, let's sum up, 
The remote machine has access to the Elasticsearch machine, as I can see in the `tcpdump` command output.
When enabling `network.host: 0.0.0.0` your Elasticsearch fails but if that option is disabled or set to `localhost` it works fine locally, which indeed is weird.

Let's try, once again, to set network.host to 0.0.0.0, restart the service and check Elasticsearch logs.
1. Edit `elasticsearch.yml` (/etc/elasticsearch/elasticsearch.yml)
```
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
network.host: 0.0.0.0
#
```
2. Restart Elasticsearch:
`systemctl restart elasticsearch`
3. Check Elasticsearch logs, paste here the output of this command:
`tail -n 100 /var/log/elasticsearch/(cluster-name|elasticsearch).log`

Regards,
Pablo Torres

**Comment by dwizel** [comment]
Hi Pablo, 
I have done as you requested and attached 3 logs, same result had to comment it out to restore it. 
[elasresult.txt](https://github.com/wazuh/wazuh-kibana-app/files/3564849/elasresult.txt)
[elasresult1.txt](https://github.com/wazuh/wazuh-kibana-app/files/3564850/elasresult1.txt)
[elasresult2.txt](https://github.com/wazuh/wazuh-kibana-app/files/3564851/elasresult2.txt)

**Comment by pablotr9** [comment]
Hi @dwizel , thanks for the output,
We can see in your logs:
```
[2019-09-02T17:08:03,529][ERROR][o.e.b.Bootstrap          ] [CLAY-MON] node validation exception
[1] bootstrap checks failed
[1]: the default discovery settings are unsuitable for production use; at least one of [discovery.seed_hosts, discovery.seed_providers, cluster.initial_master_nodes] must be configured
```
Let's modify your `elasticsearch.yml` again, now add this:
```
node.name: node-1
cluster.initial_master_nodes: node-1
```
Also add  `network.host: 0.0.0.0` to the `elasticsearch.yml and restart Elasticsearch (`systemctl restart elasticsearch`) and let's see if it's now working successfully

Best regards,
Pablo Torres

**Comment by dwizel** [comment]
Oh man, you guys are the bomb. Sorry this took so long, as I said I am new to Linux (coming from a Windows background). I think it's stable now.

**Comment by pablotr9** [comment]
Hi @dwizel ,

Yes, I'm sorry it took so long to find the fix. If you need anything else do not hesitate to ask us again!

Best regards,
Pablo Torres

**Comment by GoodyIT** [comment]
it does not work for me.
my version is 7.8.1 and I set all the configs above.

**Comment by pablotr9** [comment]
Hi @GoodyIT ,

Could you please share with me your current configuration and Elasticsearch logs?
Elasticsearch logs
```
tail -n 100 /var/log/elasticsearch/(cluster-name|elasticsearch).log
```
(Replace cluster-name with the name of your cluster or if no name was specified the log file will be named `elasticsearch`)

Best Regards,
Pablo Torres

**Comment by mvdboogaard** [comment]
Hi @GoodyIT ,

You know also have to set: discovery.seed_hosts: ["host1", "host2"] 
You have to add at least your host which is hosting elasticsearch. If you have more host (cluster) you have to add them all.

**Comment by rushayt** [comment]
@Rhachi-tech 
Thanks, its saves my day
