### ISSUE TITLE
Keep user's filters when switching from Discover to Panel

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1685]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.9.5   | 7.3     | 0531 |

**Description**
Implicit and global filters are being kept when coming from Discover to Dashboard, but user's filters are being lost.

**Steps to reproduce**

1. Go to any dashboard.
2. Apply some filter.
3. Go to Discover from than dashboard.
4. Come back to the dashboard, the user's filters are gone.

**Screenshots**

![image](https://user-images.githubusercontent.com/8860227/63005507-01afd200-be7d-11e9-9012-8e117165bb53.png)

![image](https://user-images.githubusercontent.com/8860227/63005537-0d02fd80-be7d-11e9-87d8-a729a52b4018.png)

![image](https://user-images.githubusercontent.com/8860227/63005579-1e4c0a00-be7d-11e9-8dc1-23645f1b5be6.png)

**Comment by juankaromo** [comment]
This has been fixed here https://github.com/wazuh/wazuh-kibana-app/pull/1689. The applied filters are saved at the time of the return of the discover to apply them again in the dashboard.

**Comment by juankaromo** [comment]
**Testing**

#### Filter checks (Overview and Agents)    

- [x] "Overview/General/Dashboard -> Add `rule.level:7` -> Go to Overview/General/Discover" Filters shouldn't change
- [x] "Overview/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Overview/General/Discover" Filters shouldn't change
- [x] "Overview/General/Dashboard -> Add `rule.level:7` -> Go to Overview/FIM/Dashboard" The filter "rule.level:7" is removed
- [x] "Overview/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Overview/FIM/Dashboard" The filter "rule.level:7" persists
- [x] "Overview/General/Discover -> Add `rule.level:7` -> Go to Overview/FIM/Dashboard" The filter "rule.level:7" is removed
- [x] "Overview/General/Discover -> Add `rule.level:7` and make it pinned -> Go to Overview/FIM/Dashboard" The filter "rule.level:7" persists
- [x] "Overview/General/Discover -> Add `rule.level:7` -> Go to Overview/General/Dashboard" Filters shouldn't change
- [x] "Overview/General/Discover -> Add `rule.level:7` and make it pinned -> Go to Overview/General/Dashboard" Filters shouldn't change
- [x] "Overview/General/Dashboard -> Add `rule.level:7` -> Go to Agents/General/Dashboard" The filter "rule.level:7" is removed
- [x] "Overview/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Agents/General/Dashboard" The filter "rule.level:7" persists
- [x] "Agents/General/Dashboard -> Add `rule.level:7` -> Go to Agents/General/Discover" Filters shouldn't change
- [x] "Agents/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Agents/General/Discover" Filters shouldn't change
- [x] "Agents/General/Dashboard -> Add `rule.level:7` -> Go to Agents/FIM/Dashboard" The filter "rule.level:7" is removed
- [x] "Agents/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Agents/FIM/Dashboard" The filter "rule.level:7" persists
- [x] "Agents/General/Discover -> Add `rule.level:7` -> Go to Agents/FIM/Dashboard" The filter "rule.level:7" is removed
- [x] "Agents/General/Discover -> Add `rule.level:7` and make it pinned -> Go to Agents/FIM/Dashboard" The filter "rule.level:7" persists
- [x] "Agents/General/Discover -> Add `rule.level:7` -> Go to Agents/General/Dashboard" Filters shouldn't change
- [x] "Agents/General/Discover -> Add `rule.level:7` and make it pinned -> Go to Agents/General/Dashboard" Filters shouldn't change
- [x] "Agents/General/Dashboard -> Add `rule.level:7` -> Go to Overview/General/Dashboard" The filter "rule.level:7" is removed
- [x] "Agents/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Overview/FIM/Dashboard" The filter "rule.level:7" persists

- [ ] Go back from discover with an applied query. Sometimes shards fails.

**Comment by juankaromo** [comment]
**Update 21/08/2019**

_Go back from discover with an applied query. Sometimes shards fail._

This has been fixed checking if the query if an object after to upgrade it. 

https://github.com/wazuh/wazuh-kibana-app/blob/7abd62a614be97ada9e40c7eec8cfe0a7a6f91cf/public/kibana-integrations/kibana-discover.js#L673
