### ISSUE TITLE
FIM tab rework

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1697]
Hi team, 

The tab _Agent > FIM_ needs changes, here are some proposals:

- [x] State interface (now it's "Show files"), should be shown by default.
- [ ] <del>Expand the default number of rows for the files table to 100.</del>
- [ ] <del>Add SHA1 and MD5 hashes to the table.</del>
- [x] Show a new table with the configuration for that agent (directories, realtime, who-data, report changes, ignores, restricts...)
- [ ] Add a chart for showing the number of files by owner/group/permissions.
- [ ] Add a chart for showing the number of files by monitored directories.
- [x] If we click on a file, it should show some stats such as the number of alerts for that file or the option to filter alerts by that file.

**Comment by juankaromo** [comment]
Related with FIM module rework

#2153
#2156
