### ISSUE TITLE
Kibana basePath + Nginx

### ISSUE THREAD

**Issue by snaow** [wazuh/wazuh-kibana-app#17]
Wazuh App is not able to use "settings.basePath" from _kibana.yml_, causing some requests to fail.

All the request should add basePath to the URL if the setting is set.
For example, when getting the apiEntries:

- https://github.com/wazuh/wazuh-kibana-app/blob/master/public/controllers/settings.js#L76

**Comment by vpm-bradleyhession** [comment]
Any updates to this? Also experiencing this....

**Comment by JuanjiJG** [comment]
Hi @vpm-bradleyhession , sorry for the late response.

The team has been working on some bugfixes related to the base path, and we think there should be no more issues with that. If you're still having any sort of problem, please let us know, providing the following info:

* Wazuh-manager version
* Wazuh-api version
* Elastic stack versions (Elasticsearch, Logstash, Kibana)
* OS version

Thanks and regards.
Juanjo
