### ISSUE TITLE
Agent > FIM state makes filters dissapear

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1700]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.9/3.10   | 7.3     | n/a |

**Description**
Once you come back from FIM state inside an agent, filters are gone.

**Steps to reproduce**

1. Go to "Agent > FIM"
2. Click on "Show files"
3. Click on "Show alerts"
4. Filters are gone

**Screenshots**

![image](https://user-images.githubusercontent.com/8860227/63250089-1fa97800-c26b-11e9-9e7c-22a0c9d1b9e5.png)

![image](https://user-images.githubusercontent.com/8860227/63250123-2df79400-c26b-11e9-81f7-dd67a97da9f0.png)

![image](https://user-images.githubusercontent.com/8860227/63250133-34860b80-c26b-11e9-9d19-6b33c340c472.png)

**Comment by juankaromo** [comment]
**Update 19/08/2019**

The changes of view within the same section have been taken into account with a parameter not to delete the filters.

https://github.com/wazuh/wazuh-kibana-app/blob/86486c024a43fd21a816376bbe9b34821ae50e17/public/controllers/agent/agents.js#L386
