### ISSUE TITLE
Bugs found on Wazuh v3.10.0 - Kibana v7.3.0 / v7.3.1

### ISSUE THREAD

**Issue by adri9valle** [wazuh/wazuh-kibana-app#1726]
# Wazuh v3.10.0 - Kibana v7.3.0 / v7.3.1

#### Dashboards

- [x] Flick between dashboards, once the user is for example in "Overview > Security events" and then the user clicks on "Overview > FIM" a flick is happening, showing empty cards briefly.
- [x] Ensure all table visualizations are using sort by count.

#### UI/UX

- [ ] The interactive guide for adding agents is missing the repository addition, so the installation snippet would not work.
- [x] Management > Ruleset > Rules > Custom rules. Remove the lens for the column "Path", it's useless.
- [x] Management > Ruleset > Edit files. The "Restart cluster" action doesn't show information about the request.
- [x] Management > Groups > Edit agent.conf. Once "Cancel" is clicked, it shows "Agents" but the table is about files.
- [x] Management > Configuration > Restart. The top message bar is misplaced.

![image](https://user-images.githubusercontent.com/7983984/63928496-eb467080-ca4f-11e9-8215-0db47b15493c.png)

- [x] Hide lens in the file column (Management > Rules/Decoders)
![image](https://user-images.githubusercontent.com/7983984/64019567-c1fd1180-cb2f-11e9-8a60-11aab696fff3.png)

- [x] (Firefox only) The arrow of the input select has an old-style

![image](https://user-images.githubusercontent.com/7983984/64019597-dccf8600-cb2f-11e9-8f3a-a5d2648d2ca9.png)

#### Filters, query bar, Discover, visualizations

- [x] Bug introduced yesterday (8/28/2019). Go to "Overview > Security events", now go to "Overview > FIM", then go back to "Overview > Security events", the FIM filter is still being applied but it's not visible.
- [x] Pinned filter in a dashboard, unpinned in Discover, go back to the dashboard, it's still pinned.
- [x] Adding a filter of type exists is failing if it's added by hand. E.g: rule.id exists. Not the query bar but the filters.
- [x] View surrounding documents is working but showing two errors.
- [x] Firefox only. Kibana 7.3.0 has a known bug with the filters, after trying with Kibana 7.3.1 we can see it's fixed.
- [x] Go to "Overview > Security events". Add a filter e.g: "rule.level: 7". Make it pinned. Go to "Overview > FIM". From there, remove the pinned filter. Go back to "Overview > Security events", the pinned filter appears again.
- [x] ~~Adding new pinned filters is putting them on the left, before the implicit filters. New filters should be added on the right side.~~ Invalid. Every pinned filter is being added on the left on Kibana external Discover too, it's the expected behavior.

#### Extensions
- [x] In Overview, extensions HIPAA and NIST are not working if both PCI and GDPR are disabled.
- [x] Extensions in Agents are fully wrong.

#### Reporting (PDF)
- [x] The inventory report is missing some fields for the "Network settings" table. Also, the "Network ports" has an empty column named "Process". For the first one, the app is showing the data properly. For the second one, the app has no "Process" column for that table, this only applies to Windows agents.
- [x] Exporting PDF for SCA in a Windows agent shows some keys not being translated, also it shows some fields empty, it should show -- or -.

#### Admin mode
- [x] When admin mode is disabled, the "Save" button in ruleset custom files is being shown, the server is blocking the request but the button should not be there.

#### Other
- [x] In "Overview", the SCA tab still appears.
- [x] Chrome only. Last registered agent card box is not being shown in Management > Status.
- [x] Dynamic height for some configuration sections is not working as expected (not taking all the available space, reducing the card to a small card with a scroll bar)
- [x] Last registered agent box for a Never connected agent shows "undefined" in the last keep alive, it should show just -.
- [x] Should be reviewed. If a group has no custom configurations yet, the configuration report with no agents is a bit poor
- [x] Removing multiple agents using an object instead of URL query gave me an error, also, the @wazuh/framework has an unhandled exception that we've just reported them.
- [x] Flick. When using "Refresh" agents, a flick occurs, the table is shown, then it disappears and then it's shown again.
- [x] The very first time you enter the app (with no API entries stored yet), the menu is not being shown. After saving an API entry and refresh the page, it worked.
- [x] The Agent only belongs to the default group message can't be closed.

#### Export JSON tables
- [x] Downloading the list of CDB lists is broken.
- [x] Exporting the list of groups is trying to generate an agents CSV.

#### Dark mode

- [x] The menu height is wrong.
- [x] The index pattern selector in the menu is not being adapted.
- [x] The FIM files table is not being shown properly.
- [x] If there are no results in the Discover, there are two kinds of black background.
- [x] Adding agents into a group, makes them appear temporary with a wrong color.
- [x] The "Save list" button on "Ruleset > CDB lists" is not adapted.
- [x] Regardless of the dark mode is enabled or not, in Firefox the index pattern selector looks old-fashioned.

**Comment by adri9valle** [comment]
**Update 27.08.19**

Working on [fixes-3.10-7.3](https://github.com/wazuh/wazuh-kibana-app/tree/fixes-3.10-7.3)

**Comment by jesusgn90** [comment]
Fixes for CSV exporting: https://github.com/wazuh/wazuh-kibana-app/pull/1728
Fix "View surrounding documents": https://github.com/wazuh/wazuh-kibana-app/pull/1729

**Comment by jesusgn90** [comment]
It's all related @branchnetconsulting , we are fixing it. In any case, we'll do a double-check for your issue.

Thanks!

**Comment by jesusgn90** [comment]
"Pinned filter in a dashboard, unpinned in Discover, go back to the dashboard, it's still pinned." fixed here: https://github.com/wazuh/wazuh-kibana-app/pull/1731

**Comment by jesusgn90** [comment]
@branchnetconsulting https://github.com/wazuh/wazuh-kibana-app/issues/1726#issuecomment-525234971 is fixed in our current branch.

**Comment by jesusgn90** [comment]
And @branchnetconsulting https://github.com/wazuh/wazuh-kibana-app/issues/1726#issuecomment-525235932 is not fixed, I can reproduce a different thing but almost the same. I'll get back to you soon. 

Thanks

**Comment by jesusgn90** [comment]
Hello again @branchnetconsulting https://github.com/wazuh/wazuh-kibana-app/issues/1726#issuecomment-525235932 is fixed in https://github.com/wazuh/wazuh-kibana-app/pull/1733

**Comment by jesusgn90** [comment]
"Adding a filter of type exists is failing if it's added by hand. E.g: rule.id exists. Not the query bar but the filters." fixed here: https://github.com/wazuh/wazuh-kibana-app/pull/1735

**Comment by jesusgn90** [comment]
"The very first time you enter the app (with no API entries stored yet), the menu is not being shown. After saving an API entry and refresh the page, it worked." fixed here: https://github.com/wazuh/wazuh-kibana-app/pull/1737

**Comment by adri9valle** [comment]
**Update 29.08.19**

`Dynamic height for some configuration sections is not working as expected (not taking all the available space, reducing the card to a small card with a scroll bar)` has been solved in this PR https://github.com/wazuh/wazuh-kibana-app/pull/1743.
