### ISSUE TITLE
Bugs found on Wazuh v3.10.0 - Kibana v6.8.2

### ISSUE THREAD

**Issue by adri9valle** [wazuh/wazuh-kibana-app#1727]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.10   | 6.8.2     | |

# Wazuh v3.10.0 - Kibana v6.8.2

#### Dashboards

- [x] Flick between dashboards, once the user is for example in "Overview > Security events" and then the user clicks on "Overview > FIM" a flick is happening, showing empty cards briefly.
- [x] Ensure all table visualizations are using sort by count.

#### UI/UX

- [x] The interactive guide for adding agents is missing the repository addition, so the installation snippet would not work.
- [x] Management > Ruleset > Rules > Custom rules. Remove the lens for the column "Path", it's useless.
- [x] Management > Ruleset > Edit files. The "Restart cluster" action doesn't show information about the request.
- [x] Management > Groups > Edit agent.conf. Once "Cancel" is clicked, it shows "Agents" but the table is about files.

#### Filters, query bar, Discover, visualizations
- [x] Duplicated and no removable pinned filters. Go to Overview General, add a pinned Filter, go to the Main Discover, go back to Overview General.
- [x] Sometimes some dashboards get stuck loading.

#### Extensions
- [x] In Overview, extensions HIPAA and NIST are not working if both PCI and GDPR are disabled.

#### Reporting (PDF)
- [x] The inventory report is missing some fields for the "Network settings" table. Also, the "Network ports" has an empty column named "Process". For the first one, the app is showing the data properly. For the second one, the app has no "Process" column for that table, this only applies to Windows agents.
- [x] Exporting PDF for SCA in a Windows agent shows some keys not being translated, also it shows some fields empty, it should show -- or -.

#### Admin mode
- [x] When admin mode is disabled, the "Save" button in ruleset custom files is being shown, the server is blocking the request but the button should not be there.

#### Other
- [x] In Agents Preview, if the most active Agent is the manager, the metric doesn't show anything.
- [x] In Firefox the index pattern selector looks old-fashioned.
- [x] Selected API sometimes is not refreshed in the menu.
- [x] The active tab is not checked when its section is active in the menu.
- [x] The Agent only belongs to the default group message can't be closed.
- [x] The autocomplete text color in the dark mode is black and hard to see.

#### Export JSON tables
- [x] Downloading the list of CDB lists is broken.
- [x] Exporting the list of groups is trying to generate an agents CSV.

#### Spaces
- [x] xpackMainPlugin.registerFeature() for lock Kibana spaces is not available in 6.8. So we need to remove the hide/show plugin depending on space feature.

**Comment by juankaromo** [comment]
Working in fixes on this branch https://github.com/wazuh/wazuh-kibana-app/tree/fixes-3.10-6.8
