### ISSUE TITLE
Health Check. 3002 - Cannot read property 'enabled' of undefined (/api/check-stored-api)

### ISSUE THREAD

**Issue by artem-tomyuk** [wazuh/wazuh-kibana-app#1746]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.9.3   | 7.3     | 0 |

**Description**
cant register api in kibana app, getting error:
Health Check. 3002 - Cannot read property 'enabled' of undefined (/api/check-stored-api)
also in kibana logs there is message:
{"type":"response","@timestamp":"2019-08-28T14:47:59Z","tags":[],"pid":1729,"method":"post","statusCode":500,"req":{"url":"/api/ch
eck-stored-api","method":"post","headers":{"host":"","connection":"keep-alive","content-length":"13","accept"
:"application/json, text/plain, */*","kbn-version":"7.3.0","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebK
it/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36","content-type":"application/json","origin":"http://elk.kastapay.
org:5601","referer":"http://5601/app/wazuh","accept-encoding":"gzip, deflate","accept-language":"en-US,en;q=0.9,u
k-UA;q=0.8,uk;q=0.7,ru-UA;q=0.6,ru;q=0.5"},"remoteAddress":"","userAgent":"","referer":":5601/app/wazuh"},"res":{"statusCode":500,"responseTime":236,"contentLength":9},"message":"POST /api/check-stored-api 500 2
36ms - 9.0B"}

**Steps to reproduce**

1. Go to kibana app
2. fill in user, pass, url, port
3. hit save
4. go to agents tab
5. see error

![Screenshot at Aug 28 18-01-57](https://user-images.githubusercontent.com/41900715/63867874-42036a00-c9be-11e9-9955-4718e1d82078.png)

**Comment by juankaromo** [comment]
Hi @artem-tomyuk and @chicken231 ,

Your Wazuh API is v3.9.3 and the Wazuh Kibana app you're using needs v3.9.5. So you would have to upgrade your Wazuh manager and API to 3.9.5.

You can follow this guide to carry out the update https://documentation.wazuh.com/3.x/installation-guide/upgrading/latest_wazuh3_minor.html#upgrading-latest-minor.

If you have any other questions, don't hesitate to ask us.

Regards.

**Comment by artem-tomyuk** [comment]
@juankaromo its really helped thanks!

**Comment by chicken231** [comment]
The Wazuh Server Docker Image for `3.9.5` was just released a few hours ago. Tested it and it works.

If others find this thread, be warned: A change to the patch version, not major or minor, can break Wazuh (The Kibana plugin at least) for you.

**Comment by hregis** [comment]
Hello
I have the same error with a wazuh manager 3.9.5 and a kibana 6.8.2 (debian package)
Regards

**Comment by hregis** [comment]
Hello
I have the same error with a wazuh manager 3.9.5 and a kibana 7.3.0 (debian package)
Regards

**Comment by mcbradfordwcb** [comment]
We are having the same issue.  Nothing is working to fix the problem, we have been OOS for two days now.
