### ISSUE TITLE
Plugin installation was unsuccessful due to error "Plugin wazuh [7.3.0] is incompatible with Kibana [7.3.1]"

### ISSUE THREAD

**Issue by asucrews** [wazuh/wazuh-kibana-app#1753]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.9.5  | 7.3.1    | |

**Description**
Plugin installation was unsuccessful due to error "Plugin wazuh [7.3.0] is incompatible with Kibana [7.3.1]"

**Steps to reproduce**

/var/log# sudo -u kibana /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.9.5_7.3.0.zip
Attempting to transfer from https://packages.wazuh.com/wazuhapp/wazuhapp-3.9.5_7.3.0.zip
Transferring 23175004 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Plugin wazuh [7.3.0] is incompatible with Kibana [7.3.1]"
root@kibana-001:/var/log#

**Screenshots**

**Additional context**
Looks like ElasticCo updated on 8/22 to 7.3.1 from 7.3.0

**Comment by adri9valle** [comment]
Hello @asucrews,

> Looks like ElasticCo updated on 8/22 to 7.3.1 from 7.3.0

This is the problem, Kibana expects that the version of the plugin will be the same that the version of Kibana.

Currently, we're working in wazuh 3.10 for the Elastic stack 7.3.1 and the release will be soon. 

If you want to use Wazuh you need to downgrade the Elastic stack to 7.3.0, once Wazuh 3.10 for 7.3.1 will be released you can upgrade again. We'll keep you informed!

I hope it helps, if you have any problem or doubt with the downgrade, please, don't hesitate to ask again.

Regards,

Adri,

**Comment by fredt34** [comment]
Hi, any news on this? "of course" I installed ES and Kibana, in a fresh 7.3.1, _before_ installing Wazuh and trying to install the app & reading the docs... I've just lost 2 hours trying to downgrade Kibana and ES... I'd love to give the app a try!

**Comment by adri9valle** [comment]
Hi @fredt34,

Sorry for the late response, I'm glad to announce you the Wazuh 3.10.0 release.

This solves your problem, now, you can install it in Kibana 7.3.1 and 7.3.2. 

I hope it solves your problem, anyway if you have more doubts or problem don't hesitate to open a new issue.

Regards,

**Comment by Zenidd** [comment]
Hello @fredt34,

I'm closing this ticket due to inactivity. Do not hesitate to reopen this or open a new one if you need further guidance.

Greetings, JP Sáez

**Comment by mehran-01** [comment]
Same issue but different version using Wazuh 3.10.0 and Elasticsearch 7.2:

Plugin installation was unsuccessful due to error "Plugin wazuh [7.3.2] is incompatible with Kibana [7.2.0]"

**Comment by mehran-01** [comment]
Same issue but different version using Wazuh 3.10.0 and Elasticsearch 7.2.0:

Plugin installation was unsuccessful due to error "Plugin wazuh [7.3.2] is incompatible with Kibana [7.2.0]"

Which version of Wazuh is using Kibana 7.0.2 to downgrade Wazuh and match them(I don't want to upgrade Elasticsearch)

**Comment by adri9valle** [comment]
Hi @mehran-01,

You're using elasticsearch 7.2.0, if you want to still using 7.2.0 you have to install Wazuh 3.9.4 due is the last compatible Wazuh version.

Here you have the package [wazuhapp-3.9.4-7.2.0](https://github.com/wazuh/wazuh-kibana-app/releases/download/v3.9.4-7.2.0/wazuhapp-3.9.4_7.2.0.zip).

However, if you want to use Wazuh 3.10.0 you have to upgrade elasticsearch to 7.3.2. [wazuhapp-3.10.0-7.3.2](https://github.com/wazuh/wazuh-kibana-app/releases/download/v3.10.0-7.3.2/wazuhapp-3.10.0_7.3.2.zip).

Even so, I advise you to upgrade to our las Wazuh version 3.10.2 and upgrade elasticsearch to 7.3.2 too. [wazuhapp-3.10.2_7.3.2.zip](https://github.com/wazuh/wazuh-kibana-app/releases/download/v3.10.2-7.3.2/wazuhapp-3.10.2_7.3.2.zip).

Here you can check all our releases and the compatibility matrix: [Wazuh Kibana App releases](https://github.com/wazuh/wazuh-kibana-app/releases).

I hope it helps.

Regards,

**Comment by KirilllK** [comment]
Hi, I'm using Elasticsearch 7.4.0, and can't downgrade to previous version. But I'd love to give the app a try!

**Comment by pablotr9** [comment]
Hi @KirilllK ,

Do you need help with the downgrade of Elasticsearch or you just can not use an Elasticsearch version lower than 7.4.0?
If you have to specifically use the Elasticsearch 7.4.0 version, a compatible version of Wazuh App will be released very very soon and it will fully support Elasticsearch 7.4.0.

Stay tuned to our community channels (Google groups, Github, Slack. https://wazuh.com/community/)  and do not hesitate to ask us if you have any question!

Best regards,
Pablo Torres

**Comment by KirilllK** [comment]
Thanks a lot, i'll wait for new version.

**Comment by pablotr9** [comment]
Hi @KirilllK ,

Here you can find the release of Wazuh App 3.10.2 with Kibana 7.4.0: https://github.com/wazuh/wazuh-kibana-app/releases/tag/v3.10.2-7.4.0

You will need Wazuh manager version 3.10.2 (here you can find the installation guide https://documentation.wazuh.com/3.10/installation-guide/installing-wazuh-manager/index.html) and this is the command for the Wazuh plugin installation:
```
/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.10.2_7.4.0.zip
```

Let us know if you have any other question.

Best regards,
Pablo Torres

**Comment by juankaromo** [comment]
Hi @KirilllK

**Comment by kadafax** [comment]
Erf... while Upgrading the whole ELK host to CentOS 8.1, Kibana was upgraded to 7.5.2 and now I have the notorious error:
Plugin installation was unsuccessful due to error "Plugin wazuh [7.5.1] is incompatible with Kibana [7.5.2]"

**Comment by pablotr9** [comment]
Hi @kadafax ,

Kibana v7.5.2 was released a few hours ago, the team is currently working on the compatibility with Kibana 7.5.2 and testing it for any breaking change to release a new version as robust as possible. 

Meanwhile, you can downgrade Kibana to v7.5.1 and use our latest stable plugin [Wazuh v3.11.1-Kibana v7.5.1](https://packages.wazuh.com/wazuhapp/wazuhapp-3.11.1_7.5.1.zip).

Sorry for any inconvenience, the new version will be ready as soon as possible, if you have any other question, please let us know!

Kind Regards,
Pablo Torres

**Comment by kadafax** [comment]
Hi there, sorry for the noise I should have been more carefull. I've rolled back from backup and all is fine. Thank you for Wazuh :)

**Comment by pablotr9** [comment]
Hi @kadafax ,

Yes, downgrading Elasticsearch is not as easy as downgrading Kibana. An option could be removing Elasticsearch and reinstall it, but this will **REMOVE** all your data which is not the best option in most cases. To avoid losing your data you should create a [snapshot](https://www.elastic.co/guide/en/kibana/7.x/snapshot-repositories.html) of your data and then restore it.

But in this case, if you want to avoid upgrading/downgrading, as the version is only a patch (7.5.**1**), you can still use Elasticsearch 7.5.2 with Kibana 7.5.1. This is **NOT** recommended as mentioned in the official [Kibana repo](https://github.com/elastic/kibana#version-compatibility-with-elasticsearch) you will get a warning. 
The new Wazuh version (3.11.2-7.5.2) will be released very soon.

Best Regards,
Pablo Torres

**Comment by pablotr9** [comment]
Hi @kadafax ,

The new version of the Wazuh UI **3.11.2-7.5.2** has just been released. So you can now update to the latest version. You can find here the 3.11.2-7.5.2 package [wazuhapp-3.11.2_7.5.2.zip](https://packages.wazuh.com/wazuhapp/wazuhapp-3.11.2_7.5.2.zip) and the [release notes](https://github.com/wazuh/wazuh-kibana-app/releases/tag/v3.11.2-7.5.2)

Let me know if you have any other questions!

Best Regards,
Pablo Torres
