### ISSUE TITLE
[6.8] Discover window time interval broken in Wazuh Kibana app

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh-kibana-app#1758]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.9.5   | 6.8.2    | 454 |

**Description**
Cannot set reasonable time intervals for Wazuh Kibana app Discover window.

**Steps to reproduce**

1. Click on the Wazuh Kibana app Discover option between Agents and Dev tools, or while in a Wazuh Kibana app Security Events dashboard click on the Discover button in the upper right. 
2. Set your time window to "Last 30 days" and the histogram shows just one bar in the histogram (@timestamp per month).  
3. Click on the pull-down to change from Monthly to Daily and the screen reloads but nothing actually changes.

**Screenshots**
![image](https://user-images.githubusercontent.com/13170654/64068326-8e3feb80-cc04-11e9-8c42-49531090857b.png)

**Additional context**
I have reproduced the problem in both Firefox and Chrome.
The issue does not present itself in the 3.9.5/7.3.0 Wazuh Kibana app.  I presume the issue has been fixed for versions of the app using Elastic Stack 7.x, but needs to be corrected for Elastic Stack 6.x if we are still supporting recent Elastic Stack 6.x versions with the Wazuh Kibana app.

**Comment by jesusgn90** [comment]
Hi @branchnetconsulting thanks for reporting this.

The issue doesn't occur on 7.x, just on 6.x. We are going to fix it as soon as possible.

Regards,
Jesús

**Comment by jesusgn90** [comment]
Hi @branchnetconsulting ,

This issue is fixed for 6.8 here https://github.com/wazuh/wazuh-kibana-app/pull/1759/commits/e52eb127863645fe773e38d95c427783c18e9a65, we forgot to apply the fix we did for 7.x series in 6.8.

I'm going to close this ticket. Feel free to re-open it or to create a new one whenever you need it.

Regards,
Jesús

**Comment by branchnetconsulting** [comment]
Awesome, thanks Jesús!
