### ISSUE TITLE
Extend "Add new agent" component 

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1767]
The new component where we are explaining to the user how to register agents and we are providing a "copy & paste" dynamic snippet is cool, however, it should be used in more places of the Wazuh app.

Proposals:

- [x] If the app has API entries and the API tells us there are no agents, show the component to the user, for example in Overview.
    - [x] If there are not metrics of agents in Overview show the component
    - [x] If there are not agents and go to Management > Groups show the component.
- [x] Make it accessible from more place with light buttons/icons so the user can launch the component almost everywhere.
- [x] Take the Wazuh manager IP address from the selected API.
- [x] Option to add the WAZUH_PASSWORD

**Comment by jsanchez91** [comment]
[Pull Request 1818](https://github.com/wazuh/wazuh-kibana-app/pull/1818)

New improvements:
* The IP field of the component is autocompleted by the Wazuh-API
* If the `-P` option is enabled in the Wazuh manager, show entry to complete
* The component is showed in the `overview`
![in_overview](https://user-images.githubusercontent.com/3064506/65604549-f71e4780-dfa7-11e9-8eb2-3b8b5aefdb62.gif)

* The component is showed in `management -> groups`
![in_management_groups](https://user-images.githubusercontent.com/3064506/65604690-292fa980-dfa8-11e9-88fa-9e042c00b015.gif)

**Comment by jsanchez91** [comment]
Added the component in the `management => groups` view.

![groups_add_new_agent](https://user-images.githubusercontent.com/3064506/66320965-16aa5e00-e920-11e9-863c-e926786c5c74.gif)

**Comment by jsanchez91** [comment]
The component is removed from `Managents -> Groups` because throw an error when navigate to:
`agents -> [any agent] -> configuration -> groups [any group]`

**Comment by adri9valle** [comment]
Solved https://github.com/wazuh/wazuh-kibana-app/pull/1818

**Comment by branchnetconsulting** [comment]
With reference to the below example of incorporating the Wazuh registration password into the "Add new agent" form, I noticed that the wrong deployment variable names were appearing in the example animation below, referring the PASSWORD and to WAZUH_PASSWORD instead of the WAZUH_REGISTRATION_PASSWORD name that I understand to be correct according to https://documentation.wazuh.com/3.10/installation-guide/installing-wazuh-agent/deployment_variables/deployment_variables_linux.html#deployment-variables-linux
Likely this has already been fixed, but I bring it up just in case.

Kevin

> **Update 12.09.19**
> 
> Now the component gets the selected API address and the address input is filled with it. Also, is detected if it is necessary the use of the password in order to register a new agent and in this case an extra input is shown in order to type the password.
> 
> ![image](https://user-images.githubusercontent.com/7983984/64780833-b06d2e00-d561-11e9-9b54-4313685c3ff0.png)
> 
> ![add-agent-extend-1](https://user-images.githubusercontent.com/7983984/64780786-95022300-d561-11e9-8839-8ca09ba941d0.gif)
> 
> **Branch**: [extend-add-new-agent-1767](https://github.com/wazuh/wazuh-kibana-app/tree/extend-add-new-agent-1767)
