### ISSUE TITLE
wazuh-app plugin unsuccessful 

### ISSUE THREAD

**Issue by fwbagusf** [wazuh/wazuh-kibana-app#177]
Hi, 
I've problem on installing wazuh kibana plugin, it said I need kibana version 6.1.0 while I've installed the latest kibana version 6.1.1 .
I've try using your README link for kibana version 6.1.1 but still did not work. Any solution? 

Thanks

**Comment by havidarou** [comment]
Hi @fwbagusf ,

you can see what version of the plugin you have installed by looking at:

```/usr/share/kibana/plugins/wazuh/package.json```

It should be 6.1.1.

Regards.

**Comment by fwbagusf** [comment]
hi @havidarou  ,

Thanks for your response, but the problem I'm experience is installing Wazuh-Kibana Apps, using this command:
/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.1.0_6.1.1.zip
But unfortunately it failed and give me this error: 
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [wazuh]. Expected [6.1.0]; found [6.1.1]"

I believe that your suggestion is to know wazuh version after I've installed the plugins, Is there some steps I've missed or what should I do to resolve this ? As I believe that wazuh-kibana apps should already support kibana version 6.1.1
 
Thanks

**Comment by havidarou** [comment]
Hi @fwbagusf ,

Ok, then the problem is you have installed Kibana 6.1.0, that is why it expected 6.1.0, but you are installing the plugin for Kibana 6.1.1.

I highly recommend you to upgrade to Kibana 6.1.1 and then install the Wazuha pp plugin, as we do not provide backwards compatibility, so fixes and new developments are always in the last version.

Regards.

**Comment by fwbagusf** [comment]
Hi @havidarou 

Thanks for your quick response! 
Yeah you are right, after re-check my kibana currently on vers. 6.1.0 , seems I miss understand the error. 

As readme provided wazuh app for kibana versi 6.1.0 also, I then installing those version, and it seems it installed correctly as I would avoid to upgrade kibana for a while.

Thanks, we could close this issue.
