### ISSUE TITLE
Fully cover Overview dashboards and Discover with E2E tests

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1772]
As part of #1539, here are some proposals:

- [ ] Cover with E2E tests all sections from Overview
  - [x] **Security Events**:
    - [x] should `alertStats` values are correct
    - [x] should `alert level evolution` chart values are correct
    - [x] should `alert` chart values are correct
    - [x] should `top 5 agent` chart pie values are correct
    - [x] should `top 5 rule groups` chart pie values are correct
    - [ ] ~~should `agent status` chart values are correct~~
    - [x] should `alerts evolution - top 5 agents` chart values are correct
    - [x] should `alerts summary` table values are correct
    ---
     ##### Add filter `rule.level:7` 
    - [x] should `alertStats` values ​​are correct when add the filter ` rule.level: 7`
    - [x] should `alert level evolution` chart values are correct when add the filter ` rule.level: 7`
    - [x] should `alert` chart values are correct when add the filter ` rule.level: 7`
    - [x] should `top 5 agent` chart pie values are correct when add the filter ` rule.level: 7`
    - [x] should `top 5 rule groups` chart pie values are correct when add the filter ` rule.level: 7`
    - [ ] ~~should `agent status` chart values are correct~~ when add the filter ` rule.level: 7`
    - [x] should `alerts evolution - top 5 agents` chart values are correct when add the filter ` rule.level: 7`
    - [x] should `alerts summary` table values are correct when add the filter ` rule.level: 7`
    ---
     ##### Add to the query bar `rule.level:7` 
    - [x] should `alertStats` values ​​are correct when add to the query bar ` rule.level: 7`
    - [x] should `alert level evolution` chart values are correct when add to the query bar ` rule.level: 7`
    - [x] should `alert` chart values are correct when add to the query bar ` rule.level: 7`
    - [x] should `top 5 agent` chart pie values are correct when add to the query bar ` rule.level: 7`
    - [x] should `top 5 rule groups` chart pie values are correct when add to the query bar ` rule.level: 7`
    - [ ] ~~should `agent status` chart values are correct~~ when add to the query bar ` rule.level: 7`
    - [x] should `alerts evolution - top 5 agents` chart values are correct when add to the query bar ` rule.level: 7`
    - [x] should `alerts summary` table values are correct when add to the query bar ` rule.level: 7`
  - [x] **Integrity monitoring**:
    - [x] should `Alerts by action over time` values are correct
    - [x] should `Top 5 agents` values are correct
    - [x] should `Events summary` values are correct
    - [x] should `Rule distribution` values are correct
    - [x] should `Actions` values are correct
    - [x] should `Top 5 users` values are correct
    - [x] should `Alerts summary` values are correct
    ---
     ##### Add filter `rule.level:7`
    - [x] should `Alerts by action over time` values are correct  when add the filter ` rule.level: 7`
    - [x] should `Top 5 agents` values are correct  when add the filter ` rule.level: 7`
    - [x] should `Events summary` values are correct  when add the filter ` rule.level: 7`
    - [x] should `Rule distribution` values are correct  when add the filter ` rule.level: 7`
    - [x] should `Actions` values are correct  when add the filter ` rule.level: 7`
    - [x] should `Top 5 users` values are correct  when add the filter ` rule.level: 7`
    - [x] should `Alerts summary` values are correct  when add the filter ` rule.level: 7`
    ---
     ##### Add to the query bar `rule.level:7`
    - [x] should `Alerts by action over time` values are correct when add to the query bar ` rule.level: 7`
    - [x] should `Top 5 agents` values are correct when add to the query bar ` rule.level: 7`
    - [x] should `Events summary` values are correct when add to the query bar ` rule.level: 7`
    - [x] should `Rule distribution` values are correct when add to the query bar ` rule.level: 7`
    - [x] should `Actions` values are correct when add to the query bar ` rule.level: 7`
    - [x] should `Top 5 users` values are correct when add to the query bar ` rule.level: 7`
    - [x] should `Alerts summary` values are correct when add to the query bar ` rule.level: 7`

**Comment by jsanchez91** [comment]
I create a new branch and add a commit with the basic test environment.

Branch: [issue-1722](https://github.com/wazuh/wazuh-kibana-app/tree/issue-1772)

**Comment by jsanchez91** [comment]
I uploaded the code for the first test.

To avoid importing an index, we use an Elasticsearch client to extract data and compare it with the result of the view.

This first test covers the `alertStats` element of the `overview > general` view.

![image](https://user-images.githubusercontent.com/3064506/64344153-2f0c1d80-cfee-11e9-8ddf-7c092af99816.png)

The test is executed in three steps:
* The first step selects the time range for `today` in the Kibana application. At the same time, the test runs a query to Elasticsearch and saves the result.
* The test obtains the `alertStats` element of the web browser and using regex expressions saves the output values. With the result of the query, execute the necessary filters to obtain the expected values ​​of `alertStats`.
* Finally, the test compares `alertStat` data with Elasticsearch.

**Comment by jsanchez91** [comment]
For tests the area chart visualizations I create two new functional services.
- `areaService`: Extract the raw data from visualization and compose an object.
- `esAreaService`: Extract the raw data from Elasticsearch index and compose an object.

With the output of the two services is possible test a visualization.
```javascript 
// Get the visualization's data
const chartSelector: string = '#Wazuh-App-Overview-General-Alerts';
const values:object = await areaChart.getValues(chartSelector);

// Get the Elasticsearch's index data
const esValues:object = await esAreaChart.getData();      

// Convert the objects to string and compare these
expect(JSON.stringify(esValues))
  .to.be.equal(JSON.stringify(values));
```

**Comment by jsanchez91** [comment]
The last commits I sent to the issue of issue-1772 include:

* Two new services to verify visualizations of pie charts
* Modification in the `AreaChartProvider` class to cover the line graph visualizations
* Three new tests

**Comment by jsanchez91** [comment]
I push 5 commits with a new test.

The test verifies the data in the `alert summary` table
![image](https://user-images.githubusercontent.com/3064506/65052121-5b1e8b80-d96a-11e9-9e71-7f5715af94c8.png)

**Comment by jsanchez91** [comment]
I create 14 new tests to cover the 'overview-> general' visualizations when applying a filter or using the query bar.

**Comment by jsanchez91** [comment]
I open new PR to the branch `3.11-7.3`

[Add E2E tests to the enviroment](https://github.com/wazuh/wazuh-kibana-app/pull/1810)

**Comment by jsanchez91** [comment]
I update the branch with one commit to fix an error in an expected result of a tests.

Branch: issue-1722

**Comment by adri9valle** [comment]
Solved here https://github.com/wazuh/wazuh-kibana-app/pull/1810
