### ISSUE TITLE
Enhance the user experience and the user interface for the app

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1776]
Hi team,

The app needs to be improved at UI/UX level. We have a lot of features however not always is easy to find them or to use them. This ticket aims not to add new features but enhance the existing ones.

The purpose of this ticket is to have a place where we can track the progress on these tasks. The DRI of this task will add a comment with any new progress.

Some of the steps we should take care of would be the next ones:

- Ask the Operations team about the customers' needs they found on live meetings, things the customers are missing, things the operations think would add more value to our product.
- Look at the Cloud team too, they have different needs and different use cases, currently, they are doing some tasks by hand because the app can't do certain actions yet.
- Discuss and review all the views on the app with the Content team, they have the right knowledge about web design and how the navigation flow may be better for the user.
- Of course, put an eye on our community feedback, they are the direct users of our product and they know what they want of our app.

That's said, it's time to start with this task, adding mockups, ideas, conclusions from the talks with other teams, the daily progress.

Regards

**Comment by jsanchez91** [comment]
After the research work, we design some new concepts.

These concepts were published in this link:
[Mock-up preview](https://www.fluidui.com/editor/live/preview/cF9JcUZtTlNzYXRXUnNwOTVjS3RpZ2MydjlDaUZWWm4wQQ==)

New overview concept:
![image](https://user-images.githubusercontent.com/3064506/66200556-aa222b80-e6a1-11e9-9c86-1488260034b4.png)

Concepts of the `agent-status` component:
![image](https://user-images.githubusercontent.com/3064506/66200639-d76ed980-e6a1-11e9-9a3e-400acf88ac8a.png)

> In environments with many agents, the second concept is better because the numbers leave the edge of the component

This concept of the `status` component has a  switcher to change between agents connected number and alerts number
![image](https://user-images.githubusercontent.com/3064506/66201096-c4103e00-e6a2-11e9-80ed-7a9620e78aae.png)

> When you have a Wazuh cluster with multiple nodes, the component changes its behavior by displaying lines for each node and a line with the accumulated result

The "notifications" component is a good idea to communicate the news of the Wazuh platform to users, as well as the state of their environment.

![image](https://user-images.githubusercontent.com/3064506/66201352-73e5ab80-e6a3-11e9-850d-7e36a6c66496.png)

**Comment by jsanchez91** [comment]
The modules view, groups all the panels of the different modules and functionalities of Wazuh.

Each module will have a guide with the necessary information about its configuration and how to generate its alerts.

The general description will allow you to configure which modules will be shown in the list and if you wish to display the list of available modules or a module when accessing.

To the right of the dashboard of each module is a tab that shows a drop-down menu to quickly change the module.

The following animation shows the behavior.
![modules_poc](https://user-images.githubusercontent.com/3064506/66299711-5e1af500-e8f4-11e9-8865-4728ca8c3654.gif)

**Comment by jsanchez91** [comment]
The `modules` view is can be edited by the user. The top-right corner has a button to active the `editing mode`

When the `editing mode` is active, all modules have a drop-down menu with some options
* `Learn more`: Go to the module documentation.
* `Weight`: Set the position in the module list.
* `Show`: Enables or disables the module in the module list.

![module_edit](https://user-images.githubusercontent.com/3064506/66465061-6d2eae00-ea80-11e9-8a5f-7f7da99b0a9a.gif)

> It is also possible to change the position of the modules by drag and drop.

**Comment by juankaromo** [comment]
Hi team,

This issue has been divided into these others:

- It belongs to the general **epic** of Redesign https://github.com/wazuh/wazuh-kibana-app/issues/1825
- Improve app navigability https://github.com/wazuh/wazuh-kibana-app/issues/1965
- Welcome screen https://github.com/wazuh/wazuh-kibana-app/issues/1963
- Redesign overview dashboards navigation https://github.com/wazuh/wazuh-kibana-app/issues/1903
