### ISSUE TITLE
Log Filter between Wazuh Agent and Winlogbeat

### ISSUE THREAD

**Issue by dwizel** [wazuh/wazuh-kibana-app#1777]
Latest Wazuh version currently installed. 

Currently using the Wazuh agent and Winlogbeat to extract info from client PCs, however since getting Winlogbeat to work and go through Logstash (FIlebeat is also going through Logstash) my Wazuh alerts have stopped working. I've done some reading and I would like some help on how to filter the 2 different logs or whether it's possible. See 01-wazuh.conf details below. 

# Wazuh - Logstash configuration file
## Remote Wazuh Manager - Filebeat input
input {
    beats {
        port => 5000
        codec => "json_lines"
    }
}

output {
    elasticsearch {
        hosts => ["localhost:9200"]
        index => "wazuh-alerts-3.x-%{+YYYY.MM.dd}"
    }
}

input {
  beats {
    port => 5000
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "%{[@metadata][beat]}-%{[@metadata][version]}"
  }
}

**Comment by juankaromo** [comment]
Hi @dwizel ,

It seems that you are overwriting the input of the Wazuh alerts with the 'Winlogbeat' messages in Logstash, so the Wazuh alerts are traying to index in the 'Winlogbeat' index and make it impossible for you to see them in Kibana.

If you don't need to perform any modification of the `Winlogbeat` alerts, you can establish the output of this module to Elasticsearch directly. So your `winlogbeat.yml` must include this:

```js
output.elasticsearch:
  hosts:
    - localhost:9200
```

You can find more about how to configure `Winlogbeat` here: https://www.elastic.co/guide/en/beats/winlogbeat/current/winlogbeat-configuration.html

At this point, you don't need to configure anything about 'Winlogbeat' in Logstash, so you can leave the Logstash configuration file like this:

```js
# Wazuh - Logstash configuration file
## Remote Wazuh Manager - Filebeat input
input {
    beats {
        port => 5000
        codec => "json_lines"
    }
}

output {
    elasticsearch {
        hosts => ["localhost:9200"]
        index => "wazuh-alerts-3.x-%{+YYYY.MM.dd}"
    }
}
```

Try this configuration and tell us the results.

Regards.

**Comment by dwizel** [comment]
Okay so I have proceeded as suggested but now Wazuh is refusing to work. I did some looking around and I've attached the logs below. 

root@CLAY-MON:/var/ossec/api/configuration/auth# curl -u username:password http://localhost:55000/?pretty
curl: (52) Empty reply from server
root@CLAY-MON:/var/ossec/api/configuration/auth# tail -n20 /usr/share/kibana/optimize/wazuh-logs/wazuhapp.log 
{"date":"2019-09-07T01:08:57.087Z","level":"error","location":"initialize:saveConfiguration","message":"[cluster_block_exception] index [.wazuh-version] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"}
{"date":"2019-09-07T01:08:57.092Z","level":"debug","location":"initialize:checkKnownFields","message":"Security enabled: no"}
{"date":"2019-09-07T01:08:57.120Z","level":"debug","location":"initialize:checkKnownFields","message":"Found 6 index patterns"}
{"date":"2019-09-07T01:08:57.120Z","level":"debug","location":"initialize:checkKnownFields","message":"Found 2 valid index patterns for Wazuh alerts"}
{"date":"2019-09-07T01:08:57.120Z","level":"debug","location":"initialize:checkKnownFields","message":"Default index pattern found"}
{"date":"2019-09-07T01:08:57.120Z","level":"debug","location":"initialize:checkKnownFields","message":"Refreshing known fields for \"index-pattern:wazuh-alerts-3.x-*\""}
{"date":"2019-09-07T01:08:57.349Z","level":"error","location":"initialize:checkKnownFields","message":"[cluster_block_exception] index [.kibana_2] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"}
{"date":"2019-09-07T01:08:57.508Z","level":"debug","location":"monitoring:init","message":"Creating new index..."}
{"date":"2019-09-07T01:08:57.513Z","level":"error","location":"monitoring:createIndex","message":"Could not create wazuh-monitoring-3.x-2019.09.07 index on elasticsearch due to [index_creation_exception] failed to create index [wazuh-monitoring-3.x-2019.09.07]"}
{"date":"2019-09-07T01:08:57.514Z","level":"debug","location":"monitoring:init","message":"Checking if wazuh-monitoring pattern exists..."}
{"date":"2019-09-07T01:08:57.515Z","level":"debug","location":"monitoring:init","message":"Updating known fields for wazuh-monitoring pattern..."}
{"date":"2019-09-07T01:08:57.528Z","level":"info","location":"monitoring:init","message":"Didn't find wazuh-monitoring pattern for Kibana v6.x. Proceeding to create it..."}
{"date":"2019-09-07T01:08:57.637Z","level":"debug","location":"monitoring:createWazuhMonitoring","message":"No need to delete old wazuh-monitoring pattern."}
{"date":"2019-09-07T01:08:57.637Z","level":"debug","location":"monitoring:configureKibana","message":"Creating index pattern: wazuh-monitoring-3.x-*"}
{"date":"2019-09-07T01:08:57.639Z","level":"error","location":"monitoring:configureKibana","message":"[cluster_block_exception] index [.kibana_2] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"}
{"date":"2019-09-07T01:09:31.950Z","level":"debug","location":"wazuh-elastic:getTimeStamp","message":"Installation date: 2019-07-16T23:51:28.425Z. Last restart: 2019-09-06T02:36:09.378Z"}
{"date":"2019-09-07T01:09:32.016Z","level":"debug","location":"wazuh-api:checkStoredAPI","message":"1563321244719 exists"}
{"date":"2019-09-07T01:09:32.250Z","level":"error","location":"wazuh-api:makeRequest","message":"Wazuh API is online but Wazuh is not ready yet"}
{"date":"2019-09-07T01:09:33.299Z","level":"debug","location":"wazuh-api:makeRequest","message":"GET https://localhost:55000/agents/summary"}
{"date":"2019-09-07T01:09:33.514Z","level":"error","location":"wazuh-api:makeRequest","message":"Wazuh API is online but Wazuh is not ready yet"}


Is there a way to fix this? I have restarted both Wazuh-manager/api and kibana to see if this would fix it but that's not the case.

**Comment by dwizel** [comment]
I may be wrong but I think it's trying to create new alerts after removing the winlogbeat config and it's having a hard time. As I said I'm still new to Linux so bear with me.

**Comment by dwizel** [comment]
Can I please get some help on this?

**Comment by juankaromo** [comment]
Hi @dwizel  ,

`.kibana` (and alias) and `.wazuh-version`. indices are blocked, so they can't be updated.

Please execute the next command:

```
curl -XGET "http://localhost:9200/.kiban*,.wazuh-version/_settings?pretty"
```

Replace `localhost` with your Elasticsearch IP. If an index is blocked, you should see this as part of the index information:

```
"blocks" : {
          "read_only_allow_delete" : "true"
        },
```

If some index is blocked, use this command to unlock it (e.g.: .kibana_2):

```
curl -XPUT "http://localhost:9200/.kiban*/_settings" -H 'Content-Type: application/json' -d'
{
  "index": {
    "blocks": {
      "read_only_allow_delete": "false"
    }
  }
}'
```

You can verify it once done using the first command again:

```
curl -XGET "http://localhost:9200/.kiban*,.wazuh-version/_settings?pretty"
```

I hope it helps.

Best regards

**Comment by dwizel** [comment]
Can I please get some assistance with the above? Elasticsearch is not receiving WInlogbeat properly

**Comment by dwizel** [comment]
Please I need some assistance with this.

**Comment by pablotr9** [comment]
Hi @dwizel ,

We are sorry for the late reply, let's try to fix it, I'll need some information about your environment.
1. What version of Elasticsearch and Wazuh are you using?

2. If I understood right, Winlogbeat and Filebeat are sending logs to Logstash, and Logstash is sending those logs to Elasticsearch. In that case, are you making any data transformation with Logstash, otherwise Logstash should not be needed, you can easily send directly from Filebeat/Winlogbeat to Elasticsearch, is that your case let me know and I can help you configuring these components to send logs directly to Elasticsearch.

3. I can see in your previous logs 2 different errors:
```

**Comment by pablotr9** [comment]
Hi @dwizel ,

We are sorry for the late reply, let's try to fix it. I'll need some information about your environment.
1. What version of Elasticsearch and Wazuh are you using?

2. If I understood right, Winlogbeat and Filebeat are sending logs to Logstash, and Logstash is sending those logs to Elasticsearch. In that case, are you making any data transformation with Logstash? otherwise Logstash is not necessary, you can easily send directly from Filebeat/Winlogbeat to Elasticsearch, if that's your case let me know and I can help you configuring these components to send logs directly to Elasticsearch.

3. I can see in your previous messages 2 different errors:
```
[2019-09-13T11:06:52,504][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"wazuh-alerts-3.x-2019.09.13", :_type=>"_doc", :routing=>nil}, #LogStash::Event:0x76ebb515], :response=>{"index"=>{"_index"=>"wazuh-alerts-3.x-2019.09.13", "_type"=>"_doc", "_id"=>"rDQoKG0Bkp2mPb3amU7L", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse field [host] of type [keyword] in document with id 'rDQoKG0Bkp2mPb3amU7L'", "caused_by"=>{"type"=>"illegal_state_exception", "reason"=>"Can't get text on a START_OBJECT at 1:110"}}}}}
```
It looks like there's a mapping conflict, maybe an incorrect Wazuh template is installed in your Filebeat.

```
[2019-09-13T09:18:20,382][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"wazuh-alerts-3.x-2019.09.12", :_type=>"_doc", :routing=>nil}, #LogStash::Event:0x13eafebb], :response=>{"index"=>{"_index"=>"wazuh-alerts-3.x-2019.09.12", "_type"=>"_doc", "_id"=>nil, "status"=>400, "error"=>{"type"=>"validation_exception", "reason"=>"Validation Failed: 1: this action would add [2] total shards, but this cluster currently has [999]/[1000] maximum shards open;"}}}}
```
This one says that your Elasticsearch cluster is currently using 999 shards of a maximum 1000 shards. If you want to learn more about this Cluster Shard Limit, you should check this out: https://www.elastic.co/guide/en/elasticsearch/reference/master/misc-cluster.html#cluster-shard-limit


Let's now get some more information about your Elasticsearch/Logstash logs so we can fix those errors:

 4. Elasticsearch logs:
 `tail -n 100 /var/log/elasticsearch/elasticsearch.log`
 5. Logstash logs:
 `tail -n 100 /var/log/logstash/logstash-plain.log`
 6. Check Wazuh template in your Elasticsearch:
  `curl <Elastic_IP>:9200/_cat/templates/wazuh`

Please paste the output of the commands in a file and attach it to your reply.

Kind regards,
Pablo Torres

**Comment by dwizel** [comment]
[elasticsearch.txt](https://github.com/wazuh/wazuh-kibana-app/files/3678874/elasticsearch.txt)
[logstash-plain.txt](https://github.com/wazuh/wazuh-kibana-app/files/3678875/logstash-plain.txt)
[wazuhtemplate.txt](https://github.com/wazuh/wazuh-kibana-app/files/3678876/wazuhtemplate.txt)
Here you go. As per version I am using the installation for 3.9, previously I had an issue with Wazuh alerts not working when i accidentally made Beats config Winlogbeat in Logstash, after removing it that was resolved. I am now passing Winlogbeat logs directly to Elasticsearch in my config hence the issue.

**Comment by pablotr9** [comment]
Hi  @dwizel ,

Thanks for the commands output. If Logstash is not needed, could you try configuring Filebeat to send logs directly to Elasticsearch? You can do that by editing the `filebeat.yml` in `/etc/filebeat/filebeat.yml`:
```
output.elasticsearch.hosts: ['http://<ELASTIC_IP>:9200']
#output.logstash.hosts: ["<ELASTIC_IP>:5044"]
```
(Don't forget to comment or remove the Logstash output)


We are currently working on improving our Logstash documentation as it's having problem when configured with our Wazuh Filebeat module. (More info here https://github.com/wazuh/wazuh-documentation/issues/1873)

After configuring Filebeat to send logs to Elasticsearch, please restart Filebeat (`systemctl restart filebeat`) and check if it's working. If you are still getting errors, you may have an incorrect template in your Elasticsearch:
1. Check Filebeat template:
`cat /etc/filebeat/wazuh-template.json`
2. Check Elasticsearch template:
`curl <ELASTIC_IP>:9200/_template/wazuh`

Please paste the output of above commands in a file and attach it to your reply 

Best regards,
Pablo Torres

**Comment by dwizel** [comment]
Will apply these settings and let you know, moving forward I really want to use Wazuh for everything as I feel you guys are doing an amazing job, if I need/want to use the beat modules do I just pass them directly to Elasticsearch or through Filebeat? Currently I am trying to use Winlogbeat at the moment.

**Comment by dwizel** [comment]
[wazuh_curl.txt](https://github.com/wazuh/wazuh-kibana-app/files/3679918/wazuh_curl.txt)

[wazuh_template.txt](https://github.com/wazuh/wazuh-kibana-app/files/3679919/wazuh_template.txt)

**Comment by dwizel** [comment]
Getting errors with Filebeat, please see attached.

**Comment by pablotr9** [comment]
Hi @dwizel ,

Thanks for your kind words. The data flow should be: Wazuh-manager (`alerts.json`) -> Filebeat -> Elasticsearch, so every alert generated by Wazuh will be sent to Elasticsearch via Filebeat.

Why are you using Winlogbeat? You don't need to use it if you just want to use Wazuh, but if you are using it for any other purpose don't worry it can be used along with Wazuh. If you want to collect Windows logs you may find this link helpful: https://documentation.wazuh.com/3.10/user-manual/capabilities/log-data-collection/how-to-collect-wlogs.html

Regarding the Filebeat errors, the template look OK, could you share the errors you are obtaining?
- Is Filebeat sending logs to Elasticsearch?
`filebeat test output`
- Are `wazuh-alerts*` indices being created? 
`curl <ELASTIC_IP>:9200/_cat/indices`
- Elasticsearch logs:
`tail -n 200 /var/log/elasticsearch/elasticsearch.log`

Best regards,
Pablo Torres

**Comment by dwizel** [comment]
Sorry I have been away from work. Here are the results you requested. 
Filebeat test output: 
filebeat test output
Error initializing beat: error loading config file: yaml: line 53: did not find expected key

Are wazuh-alerts* indices being created?
curl <ELASTIC_IP>:9200/_cat/indices
[wazuh_indices.txt](https://github.com/wazuh/wazuh-kibana-app/files/3694952/wazuh_indices.txt)

Elasticsearch logs:
tail -n 200 /var/log/elasticsearch/elasticsearch.log
[elasticlog.txt](https://github.com/wazuh/wazuh-kibana-app/files/3694953/elasticlog.txt)

**Comment by dwizel** [comment]
Sorry I have been away from work. Here are the results you requested. 
Filebeat test output: 
filebeat test output
Error initializing beat: error loading config file: yaml: line 53: did not find expected key

Are wazuh-alerts* indices being created?
curl <ELASTIC_IP>:9200/_cat/indices
[wazuh_indices.txt](https://github.com/wazuh/wazuh-kibana-app/files/3694952/wazuh_indices.txt)

Elasticsearch logs:
tail -n 200 /var/log/elasticsearch/elasticsearch.log

**Comment by dwizel** [comment]
Hi Guys, can I get some help with this?

**Comment by juankaromo** [comment]
Hi @dwizel 

How you can see in the error message, `Error initializing beat: error loading config file: yaml: line 53: did not find expected key` there is an error in your `filebeat.yml` in `/etc/filebeat/filebeat.yml`.

It looks like the problem is with the indentation in your file in lines 53.

Please check this line or send us your file so we can review it ourselves.

Regards.

**Comment by dwizel** [comment]
Apologies for this, found the issue and Filebeat seems to be running, I also ran filebeat test output and it's working as well.
