### ISSUE TITLE
Custom integrations don't show up in the interface

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-kibana-app#1780]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.9   | 6.x/7.x     | Any |

**Description**
Custom integrations don't show up in the interface

**Steps to reproduce**

1. Configure a custom integration.
2. Check the configuration in the interface (Management > Configuration).

**Additional context**
I checked the Wazuh API's response and the information is there.

**Comment by jsanchez91** [comment]
We made a change in the code to render all instances of integration elements in the `ossec.conf` file

![image (7)](https://user-images.githubusercontent.com/3064506/66906733-77185a00-f008-11e9-9afc-d9b75a17a6ab.png)

PR: #1847
