### ISSUE TITLE
error when use ngMaterial

### ISSUE THREAD

**Issue by xycloud** [wazuh/wazuh-kibana-app#18]
I wanna use ngMaterial in kibana visual plugin, but get erorr:
```
Uncaught TypeError: angular.module(...).info is not a function (http://127.0.0.1:6001/app/kibana:4139)
```

could you give me some help about use ngMaterial, cause I see wazuh-kibana-app use it too

**Comment by snaow** [comment]
Hi @xycloud,

Sorry for late response.
I can not help you so much just with the error you pasted here, I think you need to validate angular.module is loaded in the controller you are using it.

Please see below a tutorial for creating Kibana apps, could be helpful:

- [https://www.timroes.de/2015/12/02/writing-kibana-4-plugins-basics/](https://www.timroes.de/2015/12/02/writing-kibana-4-plugins-basics/)

Take a look into our package.json where we define different packages as ngMaterial.

Regards,
Pedro.
