### ISSUE TITLE
Adapt how Labels configuration JSON response is shown

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#1816]
Hi team,

Due to this issue https://github.com/wazuh/wazuh/issues/3429, we need to adapt to how we show the agent's labels information in the configuration section.

Now, in 3.10, we show this configuration this way:

![image](https://user-images.githubusercontent.com/21195730/65592508-fe852700-df8e-11e9-9381-ae58cd32053c.png)

But with the new changes introduced in the issue above, the configuration is now shown this way:

![image](https://user-images.githubusercontent.com/21195730/65590978-fbd50280-df8b-11e9-9dc6-00fbbabe8568.png)

By the way, we need to add a new column to show the hidden field.

Regards.

**Comment by chemamartinez** [comment]
Hi @wazuh/frontend, 

Thanks for the quick update, the core part (https://github.com/wazuh/wazuh/pull/3490) has been already merged in 3.11.

Regards.
