### ISSUE TITLE
Add security privileges to the app

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-kibana-app#1822]
One user of the mailing lists asks about include Wazuh app privileges on the Kibana roles.
[Wazuh doesnt showing in Kibana Dashboard](https://groups.google.com/forum/#!topic/wazuh/HHscvcwCyWg)

![No privileges](https://groups.google.com/group/wazuh/attach/5ba32a0f0144f/Screenshot.png?part=0.1&authuser=0&view=1)

I did the first investigation to respond to the user, but we need to plan how the different user roles interact with the application to define the capabilities.
![privileges](https://groups.google.com/group/wazuh/attach/6e43e14c6a955/1569407142528.png?part=0.1&view=1&authuser=0)

**Comment by NerdSec** [comment]
Apparently, with the recent update, the plugin is not visible to non-admin users.

Wazuh version: 3.10.2
Kibana: 7.4.0

As described in the older Wazuh docs, I set up the roles:
https://documentation.wazuh.com/3.7/user-manual/kibana-app/configure-xpack/index.html

But the user is not able to see the Wazuh plugin in Kibana. I have implemented the solution that was mentioned [in the previous post](https://groups.google.com/forum/#!topic/wazuh/HHscvcwCyWg).

This allows non-admin users to see the plugin and then use it. Why is this not pushed in the latest release by default? The new index.js is as follows:

```
/*
 * Wazuh app - Module for Kibana plugin definition
 * Copyright (C) 2015-2019 Wazuh, Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * Find more information about this on the LICENSE file.
 */

// Imports the init module
import { initApp } from './init';
import { resolve } from 'path';


export default kibana =>
  new kibana.Plugin({
    id: 'wazuh',
    name: 'wazuh',
    require: ['kibana', 'elasticsearch'],
    uiExports: {
      app: {
        id: 'wazuh',
        title: 'Wazuh',
        description: 'Wazuh app for Kibana',
        icon: 'plugins/wazuh/img/icon.svg',
        main: 'plugins/wazuh/app'
      },
      hacks: ['plugins/wazuh/icon-style'],
      __bundleProvider__(kbnServer) {
        kbnServer.uiBundles.addPostLoader({
          test: /\.pug$/,
          include: resolve(__dirname, 'public'),
          loader: require.resolve('pug-loader'),
          enforce: undefined
        });
      }
    },
    init(server, options) {
      // Kibana spaces locker
      const xpackMainPlugin = server.plugins.xpack_main;

      if (xpackMainPlugin) {
        xpackMainPlugin.registerFeature({
          id: 'wazuh',
          name: 'Wazuh',
          app: ['wazuh', 'kibana', 'elasticsearch'],
          navLinkId: 'wazuh',
          icon: '/plugins/wazuh/img/icon.svg',
          privileges: {
            all: {
              app: ['wazuh'],
              savedObject: {
                all: ['wazuh-alerts-3.x-*', 'wazuh-monitoring-3.x-*'],
                read: ['wazuh-alerts-3.x-*', 'wazuh-monitoring-3.x-*'],
              },
              ui: ['save', 'show'],
            },
            read: {
              app: ['wazuh'],
              savedObject: {
                all: [],
                read: ['wazuh-alerts-3.x-*', 'wazuh-monitoring-3.x-*'],
              },
              ui: ['show'],
            },
          }
        });
      }



      return initApp(server, options);
    }
  });

```

**Comment by jsanchez91** [comment]
Hi @NerdSec,

We have this on the roadmap. The solution given in the post gives full access to the application to users without privileges. We are working on the capabilities that could have different user roles.

You can subscribe to this issue to see future changes and if you wish, you can give us your opinion.

Best regards,
Jose.
