### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by aknauss** [wazuh/wazuh-kibana-app#184]
Hi,

I have a blank page and have this error : 
error : 9 message : "Could not get data from elasticsearch" statusCode : 500

When I search on wazuh-elastic.js : it try to search on ".wazuh-version"  But it doesn't exist on my elastic...

here what I have : 
.wazuh                          DIwZS-QXSLqFn5m0lKo6hA
wazuh-monitoring-3.x-2018.01.15 RiSztf5YSyaGH1iqPXY2jg
wazuh-alerts-3.x-2018.01.16     9FIhTQaqTNiQMJgd41q_3A
wazuh-monitoring-3.x-2018.01.16 nbdbmdPrSdWOvC02231XaA9.9kb

If someone can help me...

Thanks a lot,
Franck

**Comment by JuanjiJG** [comment]
Hi @aknauss,

Did you upgrade from an earlier version of Wazuh (e.g Wazuh 2.1 to Wazuh 3.1)?

Maybe Elasticsearch is not working properly or is not running. Please check the status with:
`systemctl status elasticsearch`

Also, tell me what's your current version of Elasticsearch, Kibana and the Wazuh App. For the app, you can check the `package.json` file and look at the `revision` field. Paste on a comment all the information.

Best regards,
Juanjo

**Comment by aknauss** [comment]
No this is a first installation.

● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: enabled)
   Active: active (running) since mer. 2018-01-17 15:46:26 CET; 6min ago
     Docs: http://www.elastic.co
 Main PID: 33813 (java)
    Tasks: 71
   Memory: 13.4G
      CPU: 8min 17.404s
   CGroup: /system.slice/elasticsearch.service
           └─33813 /usr/bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+AlwaysPreTouch -server -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThr

  "name": "wazuh",
  "version": "3.1.0",
  "revision": "0375",
  "kibana": {
    "version": "6.1.1"

kibana                                                        6.1.1  
elasticsearch                                                 6.1.1
logstash                                                      1:6.1.1-1

**Comment by aknauss** [comment]
maybe this is the problem : 
# Kibana uses an index in Elasticsearch to store saved searches, visualizations
# and dashboards. It will create a new index if it doesn't already exist.
kibana.index: "**.kibana6**"

don't you think? but I can't change ir

**Comment by JuanjiJG** [comment]
Hi again @aknauss,

That is not the problem, our app creates all the necessary files in order to work properly.

Let's see if the templates are inserted correctly on Elasticsearch. Please open Kibana, and on the left bar, go to `Management/Index Patterns`, and paste a screenshot of that page.

Best regards,
Juanjo

**Comment by aknauss** [comment]
On kibana, this is me who created pattern "wazuh-alerts-3.x-*" because it didn't exist but it doesn't seems to work... : 
saved_objects :
[{id: "wazuh-alerts-3.x-*", type: "index-pattern", error: {statusCode: 404, message: "Not found"}}]

![image](https://user-images.githubusercontent.com/6724805/35052848-dbd43b7c-fba8-11e7-9615-3188e97cbe81.png)

**Comment by JuanjiJG** [comment]
Hi again @aknauss,

It looks like the templates were not inserted correctly. You should have at least two: `wazuh-alerts-3.x-*` and `wazuh-monitoring-3.x-*`

Do these steps in order to try to fix it:

1. Stop Logstash and Kibana:
`systemctl stop logstash`
`systemctl stop kibana`

2. Insert the templates and the sample alert:
`curl https://raw.githubusercontent.com/wazuh/wazuh/3.1/extensions/elasticsearch/wazuh-elastic6-template-alerts.json | curl -XPUT 'http://localhost:9200/_template/wazuh' -H 'Content-Type: application/json' -d @-`
`curl https://raw.githubusercontent.com/wazuh/wazuh/3.1/extensions/elasticsearch/wazuh-elastic6-template-monitoring.json | curl -XPUT 'http://localhost:9200/_template/wazuh-agent' -H 'Content-Type: application/json' -d @-`
`curl https://raw.githubusercontent.com/wazuh/wazuh/3.1/extensions/elasticsearch/alert_sample.json | curl -XPUT "http://localhost:9200/wazuh-alerts-3.x-"`date +%Y.%m.%d`"/wazuh/sample" -H 'Content-Type: application/json' -d @-`

3. Remove the optimizing bundles:
`rm -rf /usr/share/kibana/optimize/bundles`

4. Start again Logstash and Kibana:
`systemctl stop logstash`
`systemctl stop kibana`

Let me know if your problem gets solved or if you're still facing issues. Thanks for your patience.

Best regards,
Juanjo

**Comment by aknauss** [comment]
Hi,
Before I deleted in kibana my template I created manually
And I followed your step but in kibana no index showing with wazuh... :S

**Comment by JuanjiJG** [comment]
Hi again @aknauss,

Maybe something went wrong when inserting the templates. Try the following. Remove the configuration files for Kibana and the Wazuh App. Warning: The following commands will delete all your Kibana configuration (such as custom visualizations).
`curl -XDELETE localhost:9200/.kibana`

`curl -XDELETE localhost:9200/.wazuh`

`curl -XDELETE localhost:9200/.wazuh-version`

Try again to insert the templates again:
`curl https://raw.githubusercontent.com/wazuh/wazuh/3.1/extensions/elasticsearch/wazuh-elastic6-template-alerts.json | curl -XPUT 'http://localhost:9200/_template/wazuh' -H 'Content-Type: application/json' -d @-`

`curl https://raw.githubusercontent.com/wazuh/wazuh/3.1/extensions/elasticsearch/wazuh-elastic6-template-monitoring.json | curl -XPUT 'http://localhost:9200/_template/wazuh-agent' -H 'Content-Type: application/json' -d @-`

`curl https://raw.githubusercontent.com/wazuh/wazuh/3.1/extensions/elasticsearch/alert_sample.json | curl -XPUT "http://localhost:9200/wazuh-alerts-3.x-"date +%Y.%m.%d"/wazuh/sample" -H 'Content-Type: application/json' -d @-`

When you insert the templates with the provided command, what is the output you're getting?

You should get something like:
`{"acknowledged":true}`

That indicates that the template was inserted correctly.

Let me know if you still have doubts or problems.

Best regards,
Juanjo

**Comment by aknauss** [comment]
Ok It's very strange, I recreate index pattern alert manually for kibana and it seem to be ok. Howerver, template visualisation doesn't exist : 
SavedObjectNotFound "Possibly unhandled rejection: {"message":"Could not locate that visualization (id: Wazuh-App-Overview-PCI-DSS-Requirements-heatmap)","savedObjectType":"visualization","savedObjectId":"Wazuh-App-Overview-PCI-DSS-Requirements-heatmap"}"
(anonymous) @ commons.bundle.js?v=16350:35
commons.bundle.js?v=16350:35 SavedObjectNotFound "Possibly unhandled rejection: {"message":"Could not locate that visualization (id: Wazuh-App-Overview-PCI-DSS-requirements)","savedObjectType":"visualization","savedObjectId":"Wazuh-App-Overview-PCI-DSS-requirements"}"
(anonymous) @ commons.bundle.js?v=16350:35
commons.bundle.js?v=16350:35 SavedObjectNotFound "Possibly unhandled rejection: {"message":"Could not locate that visualization (id: Wazuh-App-Overview-PCI-DSS-Groups)","savedObjectType":"visualization","savedObjectId":"Wazuh-App-Overview-PCI-DSS-Groups"}"
(anonymous) @ commons.bundle.js?v=16350:35
commons.bundle.js?v=16350:35 SavedObjectNotFound "Possibly unhandled rejection: {"message":"Could not locate that visualization (id: Wazuh-App-Overview-PCI-DSS-Agents)","savedObjectType":"visualization","savedObjectId":"Wazuh-App-Overview-PCI-DSS-Agents"}"
(anonymous) @ commons.bundle.js?v=16350:35
commons.bundle.js?v=16350:35 SavedObjectNotFound "Possibly unhandled rejection: {"message":"Could not locate that visualization (id: Wazuh-App-Overview-PCI-DSS-Requirements-by-agent)","savedObjectType":"visualization","savedObjectId":"Wazuh-App-Overview-PCI-DSS-Requirements-by-agent"}"
(anonymous) @ commons.bundle.js?v=16350:35
commons.bundle.js?v=16350:35 SavedObjectNotFound "Possibly unhandled rejection: {"message":"Could not locate that visualization (id: Wazuh-App-Overview-PCI-DSS-Last-alerts)","savedObjectType":"visualization","savedObjectId":"Wazuh-App-Overview-PCI-DSS-Last-alerts"}"

I think, all preference for kibana ( index pattern, visualization, ... ) can't populate automatically ...
Hovewer as I said, my kibana index is .kibana6 and not .kibana 

How can I put all visulization template?

**Comment by aknauss** [comment]
ok I uploaded app_objects_file_alerts.json app_objects_file_monitoring.json by import object throught kibana frontend and all seems to works well.

I don't know why it won't populate itself...

**Comment by aknauss** [comment]
Hi,
I've testing your application, all seems to be ok.

Thanks a lot.
Franck

**Comment by jesusgn90** [comment]
Hi @aknauss I glad our team helped you, since your installation seems to be fine now, I'm going to close this issue. If you have any further trouble, open a new issue and our team will help you one more time. 

King regards,
Jesús
