### ISSUE TITLE
General timezone not changing Wazuh app logs timestamp.

### ISSUE THREAD

**Issue by DanielMorLoz** [wazuh/wazuh-kibana-app#1848]
| Wazuh | Elastic |
| ----- | ------- |
| 3.10.2   | 7.3.2     |

**Description**
Changing the general timezone doesn't change the Wazuh app logs timestamp.

**Steps to reproduce**

1. Go to Management/Kibana/Advanced Settings
2. Change *Timezone for date formatting* to something different than Browser
3. Go to Wazuh app/Management/Logs
4. Logs timestamp still uses browser timezone.

**Screenshots**
Manager timezone and logs:
```
[root@centOS7-2 ~]# timedatectl
      Local time: Wed 2019-10-16 11:42:57 UTC
  Universal time: Wed 2019-10-16 11:42:57 UTC
        RTC time: Wed 2019-10-16 11:42:57
       Time zone: UTC (UTC, +0000)
     NTP enabled: yes
NTP synchronized: yes
 RTC in local TZ: yes
      DST active: n/a

[root@centOS7-2 ~]# tail /var/ossec/logs/ossec.log 
2019/10/16 11:05:39 ossec-syscheckd: INFO: (6004): No diff for file: '/etc/ssl/private.key'
2019/10/16 11:05:39 rootcheck: INFO: Started (pid: 6409).
```

Kibana Logs:
![image](https://user-images.githubusercontent.com/47329460/66916175-fb73d880-f01a-11e9-87a4-0eed2eebaa4c.png)

Settings:
![image](https://user-images.githubusercontent.com/47329460/66916217-0dee1200-f01b-11e9-8476-5078d82e167a.png)

**Additional context**
I've seen this problem doesn't affect the Discover Section.
![image](https://user-images.githubusercontent.com/47329460/66916322-4857af00-f01b-11e9-9d53-785aef67819b.png)

**Comment by juankaromo** [comment]
Hi @DanielMorLoz 

The application of the timezone has now been corrected by applying the Kibana setting timezone. This was solved in this PR https://github.com/wazuh/wazuh-kibana-app/pull/1886/files

Regards
