### ISSUE TITLE
issues with integrity monitoring within the kibana wazuh app

### ISSUE THREAD

**Issue by shawhintech** [wazuh/wazuh-kibana-app#1851]
Hi team,

I was wondering if you can help me. I have the following versions of the software installed on my elk node as a new install

kibana-7.3.2-1.x86_64
elasticsearch-7.3.2-1.x86_64
logstash-7.3.2-1.noarch

my wazuh manager node is running
wazuh-manager-3.10.2-1.x86_64
wazuh-api-3.10.2-1.x86_64
filebeat-7.3.2-1.x86_64

one of the issues that i am facing is that, when i click the integrity monitoring tab in the wazuh app in kibana for any of the agents, i am not able to see any information or data despite changing the date filter up to 90 days historically.   can you help me troubleshoot this or understand why i am not able to see any integrity monitoring data? I followed the wazuh setup documentation, and filebeat is sending data to logstash. thank you so much in advance with any help

![image](https://user-images.githubusercontent.com/6080183/67020656-8365eb00-f0cc-11e9-8697-7608876607e1.png)

**Comment by pablotr9** [comment]
Hi @shawhintech ,

Let's first check that the data flow between wazuh-manager and Elasticsearch is working, to do that we can check Elasticsearch indices to see if `wazuh-alerts*` indices are being created:

`curl <ELASTICSEARCH_IP>:9200/_cat/indices/wazuh-alerts*`
Please paste the output of above command in your reply.

If `wazuh-alerts*` indices are created (and those indices are populated), it means Elasticsearch is successfully receiving logs, now we have to check why there are no Integrity Monitoring logs:
1. Is Integrity Monitoring configured in Wazuh? you can find more information here: https://documentation.wazuh.com/3.10/user-manual/capabilities/file-integrity/fim-configuration.html#basic-usage
2. If it's configured, are Integrity Monitoring alerts being generated by Wazuh? We can check alerts stored in _/var/ossec/logs/alerts/alerts.json_ :
`cat /var/ossec/logs/alerts/alerts.json | grep syscheck`

Best regards,
Pablo Torres

**Comment by shawhintech** [comment]
hi there- thank you so much for helping with this.  here is the output of the curl command-

[root@ca-sna-sec01 ~]# curl 10.201.99.84:9200/_cat/indices/wazuh-alerts*
green open wazuh-alerts-3.x-2019.10.18 VLvubIFwTYujRW0I1fsS7w 3 0   39 0 300.8kb 300.8kb
green open wazuh-alerts-3.x-2019.10.17 2vq8Vpo4RTec35XiXKMPIg 3 0 7588 0   6.7mb   6.7mb
[root@ca-sna-sec01 ~]#



as for wazuh configuration, integrity monitoring is indeed configured and can see syscheck in the alerts.json log for example

[root@ca-sna-sec01 ~]# cat /var/ossec/logs/alerts/alerts.json | grep syscheck
{"timestamp":"2019-10-18T04:34:53.998-0700","rule":{"level":7,"description":"Integrity checksum changed.","id":"550","firedtimes":1,"mail":true,"groups":["ossec","syscheck"],"pci_dss":["11.5"],"gpg13":["4.11"],"gdpr":["II_5.1.f"],"hipaa":["164.312.c.1","164.312.c.2"],"nist_800_53":["SI.7"]},"agent":{"id":"116","name":"nchebsapp401.nch.com","ip":"172.19.1.5"},"manager":{"name":"ca-sna-sec01"},"id":"1571398493.4838870","full_log":"File '/etc/blkid/blkid.tab' checksum changed.\nOld md5sum was: '52b397a0dd008cde28c32a5cb94158f0'\nNew md5sum is : '6e6b465c10d8d159ae4b053d6d6d0260'\nOld sha1sum was: '67bdcb4998ec77ed705d6a95b009381aa21e597c'\nNew sha1sum is : 'db603c1bb7b646ae950eab6997e357540a317ad6'\nOld sha256sum was: 'ae2e0de29d49296eb9bcebf430194571cc8b08260f7e8c28e3186f7f4e55faf8'\nNew sha256sum is : '42f3125659ca535dba1405ac58da7e2167e6d69020c644424eb64e53a2d6356b'\nOld modification time was: 'Thu Oct 17 12:18:26 2019', now it is 'Thu Oct 17 21:01:13 2019'\nOld inode was: '259793', now it is '259396'\n","syscheck":{"path":"/etc/blkid/blkid.tab","size_after":"1226","perm_after":"100644","uid_after":"0","gid_after":"0","md5_before":"52b397a0dd008cde28c32a5cb94158f0","md5_after":"6e6b465c10d8d159ae4b053d6d6d0260","sha1_before":"67bdcb4998ec77ed705d6a95b009381aa21e597c","sha1_after":"db603c1bb7b646ae950eab6997e357540a317ad6","sha256_before":"ae2e0de29d49296eb9bcebf430194571cc8b08260f7e8c28e3186f7f4e55faf8","sha256_after":"42f3125659ca535dba1405ac58da7e2167e6d69020c644424eb64e53a2d6356b","uname_after":"root","gname_after":"root","mtime_before":"2019-10-17T12:18:26","mtime_after":"2019-10-17T21:01:13","inode_before":259793,"inode_after":259396,"event":"modified"},"decoder":{"name":"syscheck_integrity_changed"},"location":"syscheck"}

**Comment by pablotr9** [comment]
Hi @shawhintech ,

We are happy to help! Let's try to find the solution to your issue:
We can see that `wazuh-alerts*` indices are created successfully and they have documents inside them, it means that the data flow is correct:
- green open wazuh-alerts-3.x-**2019.10.18** VLvubIFwTYujRW0I1fsS7w 3 0 **39** 0 300.8kb 300.8kb
- green open wazuh-alerts-3.x-**2019.10.17** 2vq8Vpo4RTec35XiXKMPIg 3 0 **7588** 0 6.7mb 6.7mb

----

I can see in your screenshot that you are trying to get File Integrity Monitoring alerts for the agent with `id:007` 
![image](https://user-images.githubusercontent.com/35685689/67096391-61499700-f1b8-11e9-8aab-f62960d99d3b.png)
Just to be sure (sorry for being repetitive) could you try checking the alerts.json to see if there are alerts of the group syscheck related to that specific agent? 
`cat /var/ossec/logs/alerts/alerts.json | grep syscheck | grep \"007\"`

-----

Now, as we can also see in the example log you sent, syscheck alerts are being generated for your agent with `id:116`
Could you please check the File Integrity Monitoring dashboard for that specific agent?
`Go Agents -> Agent id:116 -> File Integrity Monitoring` 
Make sure that the date filter is set to an old date range (e.g. last 90days)
Is the File Integrity Monitoring Dashboard loaded?


Best regards,
Pablo Torres

**Comment by shawhintech** [comment]
hi pablo,

i zeroed in on agent 116 since we know there are syscheck  alerts, but still am not seeing the fim dashboard loaded (screenshot attached)



![image](https://user-images.githubusercontent.com/6080183/67098875-f33aab00-f18a-11e9-9783-15e3296a872b.png)

**Comment by pablotr9** [comment]
Hi @shawhintech ,

Ok thank you, that's weird, let's now check if syscheck alerts are being indexed in Elasticsearch:
Do this request in `Kibana -> Dev Tools`, (you can also do a `curl` to Elasticsearch`)
```
GET wazuh-alerts-3.x*/_search
{
  "size": 1,
  "query": { 
    "bool": { 
      "must": [
        { "match": { "rule.groups":   "syscheck" }}
      ]
    }
  }
}
```

Also check if there are any error log in your Elasticsearch and Logstash:
Elasticsearch:
`tail -n 150 /var/log/elasticsearch/<ClusterName | elasticsearch.log>`
Logstash:
`cat /var/log/logstash/logstash-plain.log`
As the output size of above commands will be huge, please paste it in a file and attach it to your reply.

Best regards,
Pablo Torres

**Comment by shawhintech** [comment]
unfortunately i dont get the friendliest response when running that query :(

![image](https://user-images.githubusercontent.com/6080183/67102700-e9687600-f191-11e9-9538-5a50cdc67b21.png)

I have attached the tails as well from both elastic and logstash

thank you again for helping with this
[logstash-plain.log](https://github.com/wazuh/wazuh-kibana-app/files/3744591/logstash-plain.log)
[gc.log](https://github.com/wazuh/wazuh-kibana-app/files/3744593/gc.log)
[elasticsearch.log](https://github.com/wazuh/wazuh-kibana-app/files/3744594/elasticsearch.log)

**Comment by pablotr9** [comment]
Hi @shawhintech ,

It seems that you are doing that request in WAZUH dev tools, you have to do it in Kibana Dev Tools, you can find that tab here:
![image](https://user-images.githubusercontent.com/35685689/67180935-5de22580-f3db-11e9-88bb-d85f59c93509.png)

Regards,
Pablo Torres

**Comment by shawhintech** [comment]
thanks pablo! I ran this query in dev tools and here is the response I received


{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 6,
    "successful" : 6,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  }
}

**Comment by pablotr9** [comment]
Hi @shawhintech ,

Ok we can see that there are no alerts related to File Integrity Monitoring in your `wazuh-alerts*` indices, which is really weird, they are probably being lost in some step between Filebeat-Elasticsearch.
 I'll try to reproduce your environment, could you please send me the following files?
Filebeat.yml
`/etc/filebeat/filebeat.yml`
Logstash conf
`/etc/logstash/conf.d/01-wazuh.conf`
Elasticsearch.yml
`/etc/elasticsearch/elasticsearch.yml`

Regards,
Pablo Torres

**Comment by shawhintech** [comment]
thank you so much Pablo, I have all three log files attached below. Appreciate your review!
also not sure if i mentioned this earlier, but wazuh manager and filebeat are on a separate node than the elk stack

[filebeat.yml.txt](https://github.com/wazuh/wazuh-kibana-app/files/3754095/filebeat.yml.txt)
[01-wazuh.conf.txt](https://github.com/wazuh/wazuh-kibana-app/files/3754096/01-wazuh.conf.txt)
[elasticsearch.yml.txt](https://github.com/wazuh/wazuh-kibana-app/files/3754098/elasticsearch.yml.txt)

**Comment by pablotr9** [comment]
Hi @shawhintech ,

The problem is in Logstash as it's not configured correctly, we are currently working on improving our Logstash documentation as it's having some problems in newer versions.
Is Logstash needed in your environment? I can see that there is no data transformation in your Logstash config file.
In case you don't need Logstash for any specific purpose, I recommend you to remove it and use only Filebeat. Filebeat can also ship logs to Elasticsearch so Logstash is not needed. You only have to comment the `output.logstash` line and uncomment `output.elasticsearch` line of your `filebeat.yml`:
```
#output.logstash.hosts: ["10.201.99.84:5000"]
output.elasticsearch.hosts: ['http://10.201.99.84:9200']
```

If you need Logstash just let me know and I'll help you configuring it.

Best regards,
Pablo Torres

**Comment by shawhintech** [comment]
pablo,

thank you so much! as it turns out, changing my filebeat output to elaticsearch fixed the issue and i can now see data  within integrity monitoring.

I had one more concern, but want to first check with you, if it would be appropriate to follow up on this thread, or create a new thread? I am unable to see any data within vulnerability scanning after following relative documentation to enable scanning.

are there any known issues or considerations or things I can check to assist with vulnerability scanning within the wazuh app?

________________________________

**Comment by sujai-sivasamy** [comment]
Hello @pablotr9, I am facing the same issue and in my case, I can see the response for `Kibana -> Dev Tools` and logs are being shipped to "Elasticsearch" already. What would be missing here?
