### ISSUE TITLE
azure-logs wodle configuration should appear in Wazuh App

### ISSUE THREAD

**Issue by sergiospa** [wazuh/wazuh-kibana-app#1852]
**Description**

We should be able to check our `azure-logs` wodle configuration in the Wazuh App.
In `Management → Configuration` section, we can see our configuration for other wodles like `CIS-CAT` or `Amazon-s3`, but `azure-logs` is missing.

**Steps to reproduce**

1. Go to `Kibana → Wazuh app → Management → Configuration`
2. `azure-logs` wodle configuration isn't displayed.

**Screenshot**

![imagen](https://user-images.githubusercontent.com/30299229/67042718-bdfd7100-f128-11e9-87bd-38dd9f62f6a8.png)

Regards,
Sergio.

**Comment by pablotr9** [comment]
**Update**
Working on this branch: https://github.com/wazuh/wazuh-kibana-app/tree/3.11-7.4-azure-logs

We are still working on this new configuration section for Azure Logs:
![image](https://user-images.githubusercontent.com/35685689/67579757-67ee8600-f745-11e9-9f6a-77ce27862ed0.png)

**Comment by pablotr9** [comment]
**Update**
The text is correctly formatted and there was an error checking the Azure Logs wodle status that has also been fixed: https://github.com/wazuh/wazuh-kibana-app/commit/3d18ded8a0d34381f6e099ad1009229b74048fe6 https://github.com/wazuh/wazuh-kibana-app/commit/e040d11e44d671001b1a28529eb1dad922237a59
![azure-Kibana](https://user-images.githubusercontent.com/35685689/67671714-c3538a80-f976-11e9-8b2c-fd8dc77747b6.gif)

**Comment by juankaromo** [comment]
We need to adapt this issue to include it in the new Configuration React component. **ping** @Desvelao

**Comment by juankaromo** [comment]
This configuration section has been included in the new Configuration viewer React component here https://github.com/wazuh/wazuh-kibana-app/issues/1953.
