### ISSUE TITLE
Add the SCA condition field to the check information

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-kibana-app#1856]
Hi team,

Since https://github.com/wazuh/wazuh/pull/3631 and https://github.com/wazuh/wazuh/pull/4072, the SCA checks have a new field called `condition`. That check is as important and the own rules to determine the check result, so It should be shown in the check information:

![image](https://user-images.githubusercontent.com/29475387/67262634-d3b2c380-f4a5-11e9-9617-d7dbf1d04d65.png)

Changes in core and API are already merged and available in v3.11.0.

Regards.

**Comment by snaow** [comment]
Endpoint: `GET /sca/:agent_id/checks/:policy_id`
Field to be included in the view: `condition`
