### ISSUE TITLE
Adapt Wazuh app for new log rotation module

### ISSUE THREAD

**Issue by DaveVG1** [wazuh/wazuh-kibana-app#1857]
Hi team,

We should adapt the Wazuh app in order to include the new [log rotation](https://github.com/wazuh/wazuh/issues/3072) module options.
As for now,  the logging options are shown here:

![log](https://user-images.githubusercontent.com/10405193/67278898-3918ab80-f4ca-11e9-8cef-d69d38512cbd.png)

This module should be called "Log settings" and it should include three tabs: `alerts`, `archives` and`internal`. Every tab will have the same options:

- Plain format.
- JSON format.
- Compress rotation.
- Saved rotations.
- Schedule.
- Maximum log size.
- Minimum log size.
- Maximum log age.

This options are provided by:

- Endpoint: GET /manager/config/analysis/logging (for `alerts` and `archives` logs, only available in manager).
- Endpoint: GET /manager/config/monitor/logging (for internal `ossec.log`, for manager).
- Endpoint: GET /agents/:agent_id/config/agent/logging (for internal `ossec.log` for agents).

The requirements of the Wazuh version is the [fix-log-compression](https://github.com/wazuh/wazuh/tree/fix-log-compression) branch and of the Wazuh API version is 3.11

**Comment by Joanes04** [comment]
** Update **

We need the

**Comment by Joanes04** [comment]
**Update**

Log settings is now selectable from the **Main configurations**

![image](https://user-images.githubusercontent.com/9945959/68496466-b70edd80-0252-11ea-91ea-2d6f819b9d8c.png)

**Comment by Joanes04** [comment]
**Update**

The new log rotation module options is now ready, both in management and in the agent.

![image](https://user-images.githubusercontent.com/9945959/68598441-19f4b480-049f-11ea-9bee-03f34273160a.png)

![image](https://user-images.githubusercontent.com/9945959/68598470-2b3dc100-049f-11ea-8447-9e8bed585b20.png)

We have also removed the previous logging options in the global configurations, the logging options are now shown as follows:

![image](https://user-images.githubusercontent.com/9945959/68598644-7952c480-049f-11ea-82b9-78279cd5b2b8.png)

**Comment by Joanes04** [comment]
**Update 12/11/2019**

We've removed the **Main settings** options in the global configurations, the logging options are now shown as follows:

![image](https://user-images.githubusercontent.com/9945959/68668474-8aa3db80-0548-11ea-80f4-de87d51ddeb5.png)
