### ISSUE TITLE
Limitation: Link to groups page/tab from outside of the Kibana App

### ISSUE THREAD

**Issue by RamiusKahn** [wazuh/wazuh-kibana-app#1860]
| Wazuh | Elastic | 
| ----- | ------- |
| 3.10   | 7.3     |

**Description**
There is a limitation with the group URL that even if it is followed after the App is loaded it will only load the agent groups screen and not a specific group.

**Steps to reproduce**

`http://1.2.3.4:5601/app/wazuh#/manager/?_g=()&tab=groups&currentGroup=group.name`

immediately drops back to:
http://1.2.3.4:5601/app/wazuh#/manager/?_g=()

The ability to link to resources in the Wazuh Kibana App from external applications and documentation aids in user adoption of the Wazuh toolset.

**Comment by Desvelao** [comment]
### Changes
Added a URL control when the component is mounted using the `group` query param.

The next URL can be used to access from external sources to the group detail view:
```
KIBANA_HOST_ADDRESS/app/wazuh#/manager/?tab=groups&group=GROUP_NAME
```

Replace `KIBANA_HOST_ADDRESS` and `GROUP_NAME` for your case.
