### ISSUE TITLE
Limitation: Link to Agent from outside Kibana app

### ISSUE THREAD

**Issue by RamiusKahn** [wazuh/wazuh-kibana-app#1861]
| Wazuh | Elastic | 
| ----- | ------- |
| 3.10   | 7.3     |

**Description**
Linking to an agent's page from outside of the Wazuh Kibana app fails (Generates a blank page) if the Kibana app is not already open

**Steps to reproduce**
From an external source such as a web page or Google doc and with Wazuh Kibana app not open:
`http://1.2.3.4:5601/app/wazuh#/agents?agent=007` (or any connected/active agent)

The ability to link to resources in the Wazuh Kibana App from external applications and documentation aids in user adoption of the Wazuh toolset.

**Comment by juankaromo** [comment]
Hi @RamiusKahn , sorry for the late response,

We have listened to your feedback and requests and in the next release of Wazuh, which will be version 3.13.0, this limitation will disappear and it will be possible to navigate directly to an agent from outside Kibana. That is, if you access directly to this link `http://1.2.3.4:5601/app/wazuh#/agents?agent=007` it will open the agent's view, as you requested.

On the other hand, I would like to tell you that in 3.13.0 the agent view has been greatly modified. Now what you will find in this view is a summary of the most important information regarding the events of that agent. In addition you will have direct links to the view of its modules with a new navigation. The modules have been unified (Overview and Agents are now Modules) for better understanding and navigation within the app.

Thank you!

Regards,
