### ISSUE TITLE
Convert the Rule ID in the "Alerts Summary" to an html link to the corresponding Wazuh Discover page 

### ISSUE THREAD

**Issue by spothound** [wazuh/wazuh-kibana-app#1863]
Hello team! I open this issue to discuss a suggestion from the user Ray Klassen ir our [mailing list](https://groups.google.com/forum/#!topic/wazuh/IZ7Oq674OxM) 

**Describe the solution you'd like**

It would be interesting to convert the Rule ID in the "Alerts Summary" to an HTML link to the Wazuh Discover page with "rule.id : <Rule id from alerts summary> as the filter rule as accessing to such filtered discover page is a common task while reading the alerts summary. 

**Describe alternatives you've considered**

I have noticed that a similar feature existed on Kibana in previous versions and was removed apparently due to a migration on the Elasticsearch version which broke the relative paths and made such feature useless. I'm not sure about the feasibility of doing that with the current version of our software, but we could discuss it here. 

Please feel free to close this issue if it exists a good reason why this cannot be implemented.

**Additional information**

- This feature was included previously here with [this issue](https://github.com/wazuh/wazuh-kibana-app/issues/855) 
- Such feature was removed [in this issue](https://github.com/wazuh/wazuh-kibana-app/issues/1584) 

Best regards!

**Comment by AlexRuiz7** [comment]
That's the current behavior (Wazuh v4.3)

![image](https://user-images.githubusercontent.com/15186973/177824197-4dfb686d-e980-4a6e-9a76-ac6076cefb61.png)
