### ISSUE TITLE
Wazuh-app 3.10.2  kibana 6.8.3 not working

### ISSUE THREAD

**Issue by datadude816** [wazuh/wazuh-kibana-app#1867]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.10.2   | 6.8.3     | 444 |

**Description**
Wazuh- Kibana-app no settings page
"Something went wrong"
"Sorry but no valid index patterns were found

Running Kibana 6.8.3 with X-pack tried installing appropriate wazuh 3.10.2 plugin version.

Followed the x-pack guide for wazuh-app  3.8 ( nothing newer ) with documented roles and user defined in the roles...

**Steps to reproduce**

1. Downloaded wazuh app pliging 
https://packages.wazuh.com/wazuhapp/wazuhapp-3.10.2_6.8.3.zip

2. installed wazuh app plugin
sudo -u kibana NODE_OPTIONS="--max-old-space-size=3072" /usr/share/kibana/bin/kibana-plugin install file:/home/user/wazuhapp-3.10.2_6.8.3.zip (of course end install with ctl C as stuck at optimize for an hr)

3. follow wazuh 3.8 xpack guide
https://documentation.wazuh.com/3.8/user-manual/kibana-app/configure-xpack/defining-xpack-users.html

4. restart kibana

5. login with wazuh api admin user

6. select wazuh from menu

**Screenshots**

![wazuh-sww](https://user-images.githubusercontent.com/57238962/68047390-86033b80-fc9b-11e9-9a68-82d1220750dd.png)
![wazuh-nvipwf](https://user-images.githubusercontent.com/57238962/68047395-8996c280-fc9b-11e9-8a57-63afb0a109b8.png)
![wazuh-indexpattern-in-kibana](https://user-images.githubusercontent.com/57238962/68047407-8e5b7680-fc9b-11e9-8f26-95367fa3a1b9.png)

**Additional context**

Now I haven't populated any alert logs yet in elastic but should that be needed?

wazuhapp.log"

{"date":"2019-10-31T22:41:33.369Z","level":"info","location":"initialize","message":"Kibana index: .kibana"}
{"date":"2019-10-31T22:41:33.370Z","level":"info","location":"initialize","message":"App revision: 0462"}
{"date":"2019-10-31T22:41:33.370Z","level":"info","location":"initialize","message":"Total RAM: 24106MB"}
{"date":"2019-10-31T22:41:33.456Z","level":"info","location":"initialize:checkKnownFields","message":"Default index pattern not found, creating it..."}
{"date":"2019-10-31T22:41:33.511Z","level":"info","location":"monitoring:init","message":"Didn't find wazuh-monitoring pattern for Kibana v6.x. Proceeding to create it..."}
{"date":"2019-10-31T22:41:33.525Z","level":"info","location":"monitoring:configureKibana","message":"Created index pattern: wazuh-monitoring-3.x-*"}
{"date":"2019-11-01T17:44:41.418Z","level":"error","location":"initialize:checkKnownFields","message":"No Living connections"}
{"date":"2019-11-01T17:45:00.943Z","level":"error","location":"monitoring:cronTask","message":"No Living connections"}
{"date":"2019-11-01T17:46:24.023Z","level":"info","location":"initialize","message":"Kibana index: .kibana"}
{"date":"2019-11-01T17:46:24.024Z","level":"info","location":"initialize","message":"App revision: 0462"}
{"date":"2019-11-01T17:46:24.024Z","level":"info","location":"initialize","message":"Total RAM: 24106MB"}
{"date":"2019-11-01T17:46:24.180Z","level":"info","location":"initialize:checkKnownFields","message":"Default index pattern not found, creating it..."}
{"date":"2019-11-01T17:46:24.191Z","level":"error","location":"initialize:checkKnownFields","message":"[version_conflict_engine_exception] [doc][index-pattern:wazuh-alerts-3.x-*]: version conflict, document already exists (current version [1]), with { index_uuid=\"3FhhjcfFSvqYGmZyq_-_XQ\" & shard=\"0\" & index=\".kibana_10\" }

**Comment by juankaromo** [comment]
Hi @datadude816 

This happens when the template has not been applied correctly in Filebeat, or the configuration file is incorrect.

Download the Filebeat configuration file from the Wazuh repository for 6.X. This is pre-configured to forward Wazuh alerts to Elasticsearch:

```
curl -so /etc/filebeat/filebeat.yml https://raw.githubusercontent.com/wazuh/wazuh/v3.10.2/extensions/filebeat/6.x/filebeat.yml
chmod go+r /etc/filebeat/filebeat.yml
```

Download the alerts template for Elasticsearch for 6.X:

```
curl -so /etc/filebeat/wazuh-template.json https://raw.githubusercontent.com/wazuh/wazuh/v3.10.2/extensions/elasticsearch/6.x/wazuh-template.json
chmod go+r /etc/filebeat/wazuh-template.json
```

Restart Filebeat

`systemctl restart filebeat`

I hope this helps and please let us know the results.

Regards,

**Comment by datadude816** [comment]
please excuse the noob question here.

So you are saying there has to be alert index entries before being able to configure the API settings etc in the app?

**Comment by juankaromo** [comment]
Hi @datadude816 , you can force it to be applied by using the command below:

```
curl https://raw.githubusercontent.com/wazuh/wazuh/v3.10.2/extensions/elasticsearch/6.x/wazuh-template.json | curl -X PUT "http://localhost:9200/_template/wazuh" -H 'Content-Type: application/json' -d @-
```

The Wazuh app for Kibana needs the Elasticsearch template in order to work properly, so it’s important to make sure that it was properly inserted.

I hope this helps.

Regards,

**Comment by datadude816** [comment]
I loaded the template but it made no difference

**Comment by portalthiago** [comment]
same here.

**Comment by datadude816** [comment]
I found that the alert index has to be found, meaning it has to be created in elasticsearch AND contain some data...

The documentation does not reflect these details, simply having the index pattern in Kibana and the template loaded (as documentation would lead you to understand) aren't enough..

I am sure they have a good reason that they don't just create the .wazuh index (this does happen), populate it with something at install and just look for that so that you can at least configure the api for setup, an initial setup very likely isn't going to have alert data yet....mine didn't. 

These requirements just delayed the setup of the plugin and created an install flow that was disjointed..

**Comment by juankaromo** [comment]
Hi @datadude816 ,

Your index-patterns seems to be fine, but the Kibana index may be corrupt. If you haven’t got custom dashboards, we can delete the .kibana index and restart Kibana service one more time.

```
systemctl stop kibana
curl -XDELETE <elastic-ip>:9200/.kiban*
systemctl restart kibana
```
Wait a few seconds, then try again.

If it still doesn't work, please execute a tailf with multiple [ENTER] to clear the tailf output.

```
tailf /usr/share/kibana/plugins/wazuh-logs/wazuhapp.log
systemctl restart kibana
```

Finally please open a new browser tab and check the behavior. Paste the tailf exit here.

Regards.

**Comment by datadude816** [comment]
As I searched around before opening this issue, I saw where many answers were thought to be kibana index corruption. I don't believe this to be the case and suspect that is somewhat of an over used excuse.

As I said above, that is what fixed my issue.
