### ISSUE TITLE
Wazuh Agents appear as disconnected or pending

### ISSUE THREAD

**Issue by Aldugama** [wazuh/wazuh-kibana-app#1869]
Hello,

I installed Wazuh, along with Elasticsearch, Filebeat and Kibana. I don't know why, after installing two agents, that should be alive, appear to be disconnected or pending.

![image](https://user-images.githubusercontent.com/38432205/68120963-df22d780-ff06-11e9-840a-9e1349148eec.png)

Thanks beforehand.

**Comment by pablotr9** [comment]
Hi @Aldugama ,

What is the version of your Wazuh-manager and version of your Wazuh agents? 
Regarding the registration process, which registration method did you follow to register the agent?
You can find more info about the registration methods here: https://documentation.wazuh.com/3.10/user-manual/registering/registration-process.html#registration-methods

Best regards,
Pablo Torres

**Comment by Aldugama** [comment]
Both, Wazuh-manager and Wazuh agents are version 3.10.2. I used the simple registration service on windows agents: https://documentation.wazuh.com/3.10/user-manual/registering/windows-simple-registration.html

**Comment by pablotr9** [comment]
Hi @Aldugama .

That's weird, we will check some files/logs to see if everything is OK.

Please check the status of the wazuh agent:
```
systemctl status wazuh-agent
```
Now check the `ossec.log` of your **Wazuh-agent** and also check that same file in your **wazuh-manager**
```
tail -n 100 /var/ossec/logs/ossec.log
```
It would be also helpful to check the `ossec.conf` of the wazuh-agent:
```
cat /var/ossec/etc/ossec.conf
```
And finally, what is the output of this command (in wazuh-manager server):
```
/var/ossec/bin/agent_control -l
```

Please paste the output of above commands in a file and attach it to your reply.

Kind regards,
Pabo Torres

**Comment by Aldugama** [comment]
The problem has been solved, apparently it was a network problem, the netmask was not properly set in the wazuh-manager. Thank you very much for your help!

Best regards,
Alejandro

**Comment by SaraJ52** [comment]
@pablotr9  hello, trust you are doing good.
I would like to ask you about the next steps you were going to execute with @Aldugama . As I am facing a somewhat similar issue on my Wazuh. I have fetched the required files for further assess.
