### ISSUE TITLE
A message in the configuration view is ambiguous

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-kibana-app#1870]
When a section of the `Management -> configuration` has no information available, it displays an ambiguous message. In the title say the `Configuration not available` and in the body `There was a problem` 

![image](https://user-images.githubusercontent.com/3064506/68136565-c70e8080-ff25-11e9-81ed-75d85641ade2.png)

It is necessary to change the body message because the section is not configured in the master and that is not a problem.

**Comment by juankaromo** [comment]
Thanks @pablotr9 and @jsanchez91
