### ISSUE TITLE
Logo source fail after adding server.basePath

### ISSUE THREAD

**Issue by alen-z** [wazuh/wazuh-kibana-app#1871]
| Wazuh | Elastic |
| ----- | ------- |
| 3.10.1   | 7.3.1     |

**Description**
Logo does not render after adding in `kibana.yml`:
```yaml
server.basePath: "/kibana"
server.rewriteBasePath: true
```

**Steps to reproduce**

1. Go to Wazuh plugin in Kibana
2. Logo does not render

**Screenshots**
![Screenshot from 2019-11-05 11-20-00](https://user-images.githubusercontent.com/7421289/68199957-44d29a80-ffbf-11e9-80c9-3f66b9513469.png)

**Additional context**
We are using Nginx in front of Kibana:
```nginx
location ^~ /kibana {
    proxy_pass https://xyz_kibana;
    proxy_ssl_session_reuse on;
    proxy_ssl_verify off;
    proxy_ssl_trusted_certificate ...;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_next_upstream error timeout non_idempotent http_502;
}
```

**Comment by juankaromo** [comment]
Hi @alen-z 

We keep an eye on it and add it to our roadmap to fix it. Thanks a lot for your feedback.

**Comment by juankaromo** [comment]
This has been solved here https://github.com/wazuh/wazuh-kibana-app/pull/1888. It will be included in the next Wazuh release.
