### ISSUE TITLE
Google Cloud Platform integration

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#1873]
Hi team,

We need to implement a new integration with GCP adding a new dashboard for those alerts. To do this, we need to add Google Cloud Platform in the "Security information management" box. Will be defined visualizations we want to display in the dashboard.

**Steps**

- [x] Create the GCP box
- [x] Add logic to hide and show the new box
- [x] Implement the new GCP dashboard
- [x] Add visualizations to dashboard for Overview
- [x] Add visualizations to dashboard for Agents

Core issue https://github.com/wazuh/wazuh/issues/4015

**Comment by Joanes04** [comment]
Update: The GCP extension is now selectable from the extensions popover

**Comment by Joanes04** [comment]
Update: An initial version of the GCP extension dashboard is already operational

![capture_GCP_extension_1](https://user-images.githubusercontent.com/9945959/68379646-8f365180-014e-11ea-9753-893e0748fca0.gif)

**Comment by Joanes04** [comment]
**Update**

We have already added the first visualizations of the GCP extension. We will continue to add visualizations to the GCP dashboard.


![capture_GCP_extension_2](https://user-images.githubusercontent.com/9945959/68405667-cb82a580-0180-11ea-88dc-ff9baa6af179.gif)

**Comment by Joanes04** [comment]
**Update**
We have finished the overview dashboard, as shown in the images

![dashboard-overview-1](https://user-images.githubusercontent.com/9945959/68489134-c9831a00-0246-11ea-9d63-fb94cf6f9478.png)

![dashboard-overview-1](https://user-images.githubusercontent.com/9945959/68489149-cd16a100-0246-11ea-8958-d91df77e3e80.png)


We are already planning how we are going to design the **agent dashboard**.

**Comment by Joanes04** [comment]
**Update**
We have finished the overview dashboard (first version) for the agent, as shown in the images

![image](https://user-images.githubusercontent.com/9945959/68572380-85ba2b80-0465-11ea-9f86-ad2f25852016.png)

![image](https://user-images.githubusercontent.com/9945959/68572396-8bb00c80-0465-11ea-8bb3-190e5b0a6f16.png)
