### ISSUE TITLE
MITRE integration

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#1877]
Hi team,

We need to implement a new integration with MITRE adding a new dashboard for those alerts. On the other hand, we need to show all the MITRE ids in a table and show their details.

Core issue https://github.com/wazuh/wazuh/issues/3709

Tasks:
- [x] Add new "MITRE" extension (disabled by default)
    - [x] Allow the user to enable/disable the extension clicking on the eye icon
    - [x] Clicking on the new extension should open the new MITRE tab

The MITRE tab will be divided in 2 sections:
- [ ] MITRE table 
    - [x] Add a table with all the different Mitre tactics
    - [x] The API can only send 10 tactics per request, allow pagination in the table.
    - [ ] Allow ASC/DESC sorting
    - [x] Clicking on a specific tactic should show extra information about that tactic. (The idea is to show a flyout with the tactic information)
- [ ] MITRE dashboard

**Comment by pablotr9** [comment]
Hi team,

The new MITRE extension has been added to the `THREAT DETECTION AND RESPONSE` section.
This new extension is disabled by default.
We can now enable/disable the new MITRE extension clicking on the eye icon:
![mitreext](https://user-images.githubusercontent.com/35685689/68404273-92e1cc80-017e-11ea-9b58-05cfcacc7709.gif)

The MITRE table has been added.
Pagination has also been added to the table:
![mitreTable](https://user-images.githubusercontent.com/35685689/68404580-11d70500-017f-11ea-8185-f331cffaa49b.gif)

**Comment by pablotr9** [comment]
Hi team,

As we discussed, instead of a table we have created a card slider (_we are still working on it)_ that shows MITRE attacks ordered by the number of alerts in Elasticsearch of each of the attacks in the specified date range and with the applied filters
![cards](https://user-images.githubusercontent.com/35685689/68601759-46abca80-04a5-11ea-987d-3203319816ed.gif)

**Comment by pablotr9** [comment]
**Update** 
Current status of the MITRE overview tab:
- Mitre card slider example:
![MITRE-SLIDER](https://user-images.githubusercontent.com/35685689/68939077-0186e180-07a0-11ea-97ca-34948ed43811.gif)
- [ ] MITRE Overview dashboard:
![image](https://user-images.githubusercontent.com/35685689/68939135-20857380-07a0-11ea-94e9-f6a00e0e732c.png)

- [ ] MITRE Agents dashboard:
- [ ] Platforms and Data sources field are not being shown correctly 
![image](https://user-images.githubusercontent.com/35685689/68938944-aead2a00-079f-11ea-9378-77a9813db61a.png)
- [ ] Click on the attack name should filter by that attack. (in progress)
![image](https://user-images.githubusercontent.com/35685689/68940256-f4b7bd00-07a2-11ea-9fe9-24cecfe11306.png)

**Comment by pablotr9** [comment]
**UPDATE**
Some bugs we have found while testing this new MITRE tab:
 - When there are no results and then we change the time picker, the card slider gets bugged with incorrect results:
![errorMITRE](https://user-images.githubusercontent.com/35685689/69737340-8674e200-1134-11ea-80c1-731f8df165ac.gif)

**Comment by jsanchez91** [comment]
**Mockup v0.2.0**

This is another prototype of Mitre's dashboard:

### Tool for show and filter the `Tactics` and `Techniques` alerts

The tool shows the `Tactics` with alerts and its count:
![image (3)](https://user-images.githubusercontent.com/3064506/73758683-3c7b2e80-476b-11ea-8344-63faea945708.png)

It is possible to display all `Tactics` using the control in the upper left corner "show tactics without alerts".
![mitre_poc1](https://user-images.githubusercontent.com/3064506/73759264-fd011200-476b-11ea-955c-5bcbb1003f7a.gif)

The control under `Tactics` shows the `Techniques` and their count.
![mitre_poc2](https://user-images.githubusercontent.com/3064506/73759478-523d2380-476c-11ea-8f89-4046f09c1062.gif)

In the same way, the control in the upper left corner shows the 'Techniques' without alerts.
![mitre_poc3](https://user-images.githubusercontent.com/3064506/73759651-8a446680-476c-11ea-8d40-e68edf1a8787.gif)

All `Tactics` and `Techniques` have a context menu with controls to apply filters and display their related information.
![mitre_poc4](https://user-images.githubusercontent.com/3064506/73760023-122a7080-476d-11ea-9d1f-30c9b497c860.gif)

**Comment by juankaromo** [comment]
Here is the result of this first deliverable iteration

![Peek 2020-05-11 16-42](https://user-images.githubusercontent.com/21195730/81656660-7e390680-9437-11ea-88ea-557a68c50adb.gif)

Regards,
