### ISSUE TITLE
Issue with plugin installation : wazuh-versions.yaml is missing 

### ISSUE THREAD

**Issue by Theoooooo** [wazuh/wazuh-kibana-app#1881]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.10.2  | 7.4.2 | how can i check the rev ? |

Hello everyone,

i've been installing the wazuhapi and the kibana plugin recently but there is an issue with the installation of the plugin.

After installing the API, setting up credentials and installing the kibana app, i'm not able to configure any API into the app.

I got the following error :
![image](https://user-images.githubusercontent.com/33425208/68463845-cb7db680-020f-11ea-9006-02613fde718d.png)

In the logs of the app, i got the following error :
```
{"date":"2019-11-08T09:04:53.641Z","level":"error","location":"wazuh-api:getSetupInfo","message":"ENOENT: no such file or directory, open '/usr/share/kibana/plugins/wazuh/server/wazuh-version.json'"}
```

Is this file supposed to be installed with the app of do we have to create it manually ?
This file is also not present in the entire system.
I had to create is manually while i based my file of the one present in the repository at /server/wazuh-versions.yaml while changer the version of wazuh to 3.10.2 in the file.

Installed on CentOS 7 while following the official officiel documentation

**Comment by CODE-REaD** [comment]
I found today that `wazuh-version.json` was missing from https://packages.wazuh.com/wazuhapp/wazuhapp-3.10.2_7.4.2.zip.  My workaround was to obtain this file from https://github.com/wazuh/wazuh-kibana-app/blob/master/server/wazuh-version.json and save it to my `/usr/share/kibana/plugins/wazuh/server/` directory.

Long term, `wazuh-version.json` should be added to `wazuhapp-3.10.2_7.4.2.zip`.

**Comment by Theoooooo** [comment]
@CODE-REaD The file you've got is not the right one with the right version in it. It may have no impact but it's not from the correct branch. You got it from the Master branch unstead of the branch i indicate above

**Comment by CODE-REaD** [comment]
Thank you for pointing that out, @Theoooooo.

It seems that `wazuh-version.json` was added **only** to the master branch by @juankaromo on 9/13/19, and hard-coded with version 3.10.0 at that time (see https://github.com/wazuh/wazuh-kibana-app/blob/f8ed63ed48c2df75f04cceb639e90badc25011e0/server/wazuh-version.json),

I suppose that is the reason the file isn't present in  https://packages.wazuh.com/wazuhapp/wazuhapp-3.10.2_7.4.2.zip and also the reason for the version discrepancy.

**Comment by juankaromo** [comment]
Hi @Theoooooo and @CODE-REaD 

The file `wazuh-version.json` must not be in any branch, it must be created in the initialization of the app.

If you install the App as user kibana it should be created well by the `wazuh-version.json`, but if you installed it as root with the `--allow-root` parameter it seems that it never creates it.

It is possible that this is because `/usr/share/kibana/plugins/wazuh/` is created with `root:root`, and only the owner has write permissions.

So please uninstall the app and reinstall it with the following command:

```js
sudo -u kibana /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.10.2_7.4.2.zip
```

I hope you'll find it helpful.

Regards

**Comment by CODE-REaD** [comment]
@juankaromo, just to follow up: my experience corresponds with your description: when I installed the Wazuh plugin for Kibana as root, `wazuh-version.json` was not present; when I installed via `sudo -u kibana` yesterday the file was present following installation.

**Comment by juankaromo** [comment]
I am glad that this has been solved. This is a step in the installation that we will have to explain better in order to avoid this kind of problem in the future.

Regards,

**Comment by gittygoo** [comment]
@juankaromo I'm having the same problem when creating a docker that has the opendistro as a source image there i cant seem to sudo into the kibana user to run this command, any other alternatives?
