### ISSUE TITLE
XML validator false error for \<

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-kibana-app#1882]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.10.2 / 3.11.0   | 7.3.2 /  7.4.2    | 0546 / 0561 |

**Description**
XML validator doesn't accept an escaped `<` character which is valid (and used in our ruleset in, ` 0340-trend-osce_decoders.xml` for example). 

**Steps to reproduce**

1. Go to Manage > Ruleset > Decoders > Add new decoder file
2. Paste the contents of this [valid decoder](https://github.com/wazuh/wazuh-ruleset/blob/master/decoders/0340-trend-osce_decoders.xml), or any that is validly escaping the `<` character.
3. Try to save the file

**Screenshots**
![image](https://user-images.githubusercontent.com/36071202/68507659-bdaa4e80-026c-11ea-9c95-cf97139f7669.png)

**Additional context**
Note that this can be done via the command line and will work without issue.

**Comment by Joanes04** [comment]
**Update**

We've already solved the XML validator for accept an escaped <; character in the `Manage > Ruleset > Decoders > Add new decoder file` and the `Manage > Ruleset > Rule > Add new rule file`

![image](https://user-images.githubusercontent.com/9945959/68755685-2268fe80-0609-11ea-977b-d6e54e77c796.png)
