### ISSUE TITLE
wazuh-monitoring-3.x-2017.12.26 How to create and insert data？

### ISSUE THREAD

**Issue by zuoshouzz** [wazuh/wazuh-kibana-app#189]
Only the transmission of the /opt/ossec/logs/alerts/alerts.log log was seen and data was inserted into elasticsearch index => "wazuh-alerts-3.x -% {+ YYYY.MM.dd}", but at / extensions /logstash/01-wazuh-remote.conf did not see wazuh-monitoring-3.x-2017.12.26 such data processing

**Comment by havidarou** [comment]
Hi @zuoshouzz ,

wazuh-monitoring stores data regarding Wazuh agent's status and doesn't use any logstash configuration.

It is stored directly from the Wazuh app backend.

Regards.

**Comment by zuoshouzz** [comment]
thanks
