### ISSUE TITLE
`wait_for_complete` and `force` options don't work as they should

### ISSUE THREAD

**Issue by sergiospa** [wazuh/wazuh-kibana-app#1893]
|Wazuh version|Elastic version|Component|Install type|Install method|Platform|
|---|---|---|---|---|---|
| 3.10.2-31014 |7.4.2 (and any I believe)| Wazuh-API | Manager | Packages | CentOS Linux 7  |

### **Description**
I have been trying to downgrade an agent through our App `Dev tools` and it has been impossible so far. This is the only way Cloud customers can remotely downgrade agents, and that's why it's important to keep this functionality alive.

**Command:**
`PUT /agents/002/upgrade?version=3.8.2&force=1`

**Dev_tools output:**
```
{
  "error": 1749,
  "message": "Downgrading an agent requires the force flag. Use -F to force the downgrade"
}
```
`wait_for_complete` option doesn't work either:

**Command:**
`PUT /agents/002/upgrade?version=3.9.5&wait_for_complete`

**Dev_tools output:** 
```
{
  "error": 1,
  "message": "Error executing internal command. Timeout exceeded (1s)."
}

```

In debug mode, I can see `wait_for_complete` option is `false`:
```
WazuhAPI 2019-11-12 17:03:28 foo: Sending SIGTERM to CMD - Command: /var/ossec/framework/python/bin/python3 args:/var/ossec/api/models/wazuh-api.py stdin:{"function":"PUT/agents/:agent_id/upgrade","arguments":{"agent_id":"002","wait_for_complete":false}}
```
I tried with `wait_for_complete`, `wait_for_complete=1` and `wait_for_complete=true`, none of them works.

Regards,
Sergio.

**Comment by juankaromo** [comment]
ping @wazuh/framework

**Comment by juankaromo** [comment]
The parameters were being sent so far in the body of the request. The PUT and DELETE calls to the API seem to need those parameters to be by query string. This is the fix: 

https://github.com/wazuh/wazuh-kibana-app/commit/34d8d158c6a8341893689546c4fc350e8b341d0c

Regards,
