### ISSUE TITLE
"New file" editor doesn't allow saving twice

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-kibana-app#1896]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.10.2   | 7.3.2     | 0546 |

**Description**
When creating a new file for rules or decoders you can only save once before having to exit and reopen the file.

**Steps to reproduce**

1. Go to Management > Ruleset
2. Click on Manage rule files
3. Click on Add new rules file
4. Give a filename and content to the file
5. Save
6. Make any other change
7. Save again
8. Receive "FILE NAME ALREADY EXISTS" error
9. Notice changes are not saved.

**Screenshots**
![File name already exists error](https://user-images.githubusercontent.com/36071202/68757255-f307c100-060b-11ea-859c-7475c72260ea.gif)

**Additional context**
A prompt to overwrite would be a lot more user friendly , otherwise you must go back out to Rules after the first save, select "Manage rule files", toggle "Editable files" and then continue editing there.

**Comment by Joanes04** [comment]
**Update 02.12.2019**

Now, when we create a file for rules or decoders, it automatically takes us to edit it, thus eliminating the problem of overwriting files:

**Rules:**

![rules](https://user-images.githubusercontent.com/9945959/69972941-d8e24400-1522-11ea-9da8-1f133623bdb4.gif)

**Decoders:**

![decoders](https://user-images.githubusercontent.com/9945959/69973278-89504800-1523-11ea-9539-bc328638cd24.gif)

**Comment by jctello** [comment]
Great! thank you!
