### ISSUE TITLE
Migrating managent/ruleset list tables to React components

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-kibana-app#1899]
**Parent Issue: [Redesign tables using react EuiTables](https://github.com/wazuh/wazuh-kibana-app/issues/1829)**

This Issue is for reporting the progress of the `management/ruleset` table.

- [x] Rules
- [x] Decoders
- [x] CDB list

Branches:
- [euitables-ruleset-1829](https://github.com/wazuh/wazuh-kibana-app/tree/euitables-ruleset-1829)

**In addition:**
- [x] Keep on mind review and fix this behavior https://github.com/wazuh/wazuh-kibana-app/issues/1896

**Comment by Joanes04** [comment]
**Update**

An initial version of the modal confirm to remove files in CDB list is already operational

![gif](https://user-images.githubusercontent.com/9945959/68940621-f59d1e80-07a3-11ea-90ff-48e05826ba56.gif)

**Comment by Joanes04** [comment]
**Update**

We've disabled deleting lists for lists that are created by default:

![gif](https://user-images.githubusercontent.com/9945959/68954209-d7dfb180-07c3-11ea-960b-eb0be30599a8.gif)

**Comment by jsanchez91** [comment]
**Update**

We've updated the table with the capability of the sort the columns 

![sort_function](https://user-images.githubusercontent.com/3064506/68956151-c7c9d100-07c7-11ea-9d42-6d3494e286e1.gif)

**Comment by jsanchez91** [comment]
**Update**

* Move the filter Popover to a new component
* Remove the `updateItems` function

**Comment by Joanes04** [comment]
**Update 20.11.2019**

- Deleted [Codemirror Component for React.js](https://github.com/JedWatson/react-codemirror) to edit the files. We now use [Code Editor for Elastic UI Framework](https://elastic.github.io/eui/#/forms/code-editor):

![image](https://user-images.githubusercontent.com/9945959/69219602-76c52e80-0b73-11ea-91f2-4f3c33583409.png)

**Comment by Joanes04** [comment]
Issue [#1896](https://github.com/wazuh/wazuh-kibana-app/issues/1896) is solved thanks to the new ruleset and decoders saving:

![gif](https://user-images.githubusercontent.com/9945959/69353128-50d88080-0c7e-11ea-87a2-4e723dc0d455.gif)

**Comment by jsanchez91** [comment]
**Update**

Work in a new search/filter bar component.

![newSearchBar4](https://user-images.githubusercontent.com/3064506/69563020-9fed2100-0fb0-11ea-9eaa-d886f90556a1.gif)

![newSearchBar5](https://user-images.githubusercontent.com/3064506/69563026-a2e81180-0fb0-11ea-9559-c80a59a7e813.gif)

**Comment by jsanchez91** [comment]
**Update**

I had tried to use the `q` parameter in the request of the API to apply filters to the table, but some parameters not work.

I had open an Issue with this: [#4379](https://github.com/wazuh/wazuh/issues/4379)

I am working to implement a new filtering method in the search bar, which consists of a simple search by key and value.

---

In the background now is possible to get the values of a field from an async request
![request](https://user-images.githubusercontent.com/3064506/71418338-3f620a00-266a-11ea-9c5b-76b5897e71d7.gif)


When the field has many values the popover container grows infinitely, I have to fix this:
![infinite_fileds](https://user-images.githubusercontent.com/3064506/71418258-e7c39e80-2669-11ea-80c0-6a014fb2f628.gif)

**Comment by jsanchez91** [comment]
@victorst79 and I are working in finish the new ruleset section, this is the status of the view:

### Rules
![image](https://user-images.githubusercontent.com/3064506/73281789-c289f900-41f0-11ea-9eb7-1c6c444b388a.png)

- [ ] Pending finish the behavior of the filters button
- [ ] Know bug when adding filters and change to the `Management rules files` view
- [ ] When import a rule file the table not reload

**Comment by jsanchez91** [comment]
**Update**: 

All the bugs have been patched

**Comment by jsanchez91** [comment]
**Update 30/01/2020**

- Added new `prop` to the `SearchBar` to prevent loose the filters badges when updating the items suggestions 

- The rules table reload when uploading new files

- Fixed a warning error on `public/controllers/management/components/management/management-main.js`: The render method tried to update the component state. The code is moved to `componentWillMount`  method

- Fixed a warning error on `public/controllers/management/components/management/ruleset/main-ruleset.js`: When changing the view it tries to update the state of an unmounted component.

- Fixed multiple warning error on `public/controllers/management/components/management/ruleset/rule-info.js`: Some `li` elements had the same `key` property

**Comment by Desvelao** [comment]
TODO fixes:
- [ ] when import files, if throw error or no, no message is showed
- [ ] in **Manage rules** and click some of them (only works the eye), screen become white
- [ ] in **Manage Rules**, Custom Rules button doesn't work if it goes
- [ ] in **Manage files**, the search bar doesn't work if it goes to some file
- [ ] **CDB List**: save button should be disabled until it writes something in **key** field when add new lists
- [ ] **CDB List** if it put a repeated key or something is bad, it should show a toast or error message, it isn't showing anything now when add new lists
- [ ] **CDB List** key field come with "key" word which you have to delete, instead a placeholder
- [ ] Search bar: when you write, doesn't update you write, go one character behind
- [ ] **CDB List** - when you add a new list, if this exists, it shows that was susccesfully created. Leave and enter again, and shows previous file
- [ ] CDB List - pagination is missing, only 10 elements is shown
