### ISSUE TITLE
Add Support for Internationalization 

### ISSUE THREAD

**Issue by eduardohki** [wazuh/wazuh-kibana-app#19]
Please add Support for Internationalization, so we can be able to translate the Kibana App to other languages. 

For example, a recent study from a  brazilian IT Magazine reported that 93% of the brazilian IT professionals don't speak any other language than Portuguese. Among them, 83% of IT Managers don't speak English. 

So Wazuh could be more spread in my country if translated to pt_br. 

Thanks!

**Comment by snaow** [comment]
Hi @eduardohki,

That is a great idea! Since we are using AngularJS + MVC, we could add some templates for translations, we will add it to our roadmap, I will let you know with any progress.

Thanks for the feedback and ideas.

Best,
Pedro.

**Comment by JuanjiJG** [comment]
This suggestion has been added to our internal roadmap for further debate and research.
