### ISSUE TITLE
Redesign overview dashboards navigation

### ISSUE THREAD

**Issue by pablotr9** [wazuh/wazuh-kibana-app#1903]
Parent Issue: [Redesign](https://github.com/wazuh/wazuh-kibana-app/issues/1825)

This Issue is for reporting the progress of the Overview Dashboard navigation.
The idea is to change the current overview navigation to the navigation shown in this example image:
![menu dashboards](https://user-images.githubusercontent.com/35685689/69239788-4f825780-0b9b-11ea-9d91-a07f5a83641d.gif)

**Comment by pablotr9** [comment]
**Update**
Working on this branch:  https://github.com/wazuh/wazuh-kibana-app/tree/issue-1903
It has been added a new side nav to the overview section allowing navigation through all dashboards:
![exampleSideNav](https://user-images.githubusercontent.com/35685689/69439664-b47ab080-0d47-11ea-8b9d-00daefe5e30b.gif)

We can now list all the Wazuh extensions and show extra details of a specific extension as shown in this example:
![extensionsejemplo6](https://user-images.githubusercontent.com/35685689/69439470-4fbf5600-0d47-11ea-9b76-92f320cc1bb6.gif)

**Comment by pablotr9** [comment]
**Update**
We can now close/open the side navigation bar:
![openCloseSideNav](https://user-images.githubusercontent.com/35685689/69556258-b9886b80-0fa4-11ea-850d-45b027585016.gif)

The enable/disable extension button is now working as expected.
We have also added a new image with a dashboard example of the current extension: 
![exampleExtensionDetails](https://user-images.githubusercontent.com/35685689/69556362-dde44800-0fa4-11ea-958b-e018ea5df754.gif)

**Comment by pablotr9** [comment]
Some ideas/alternatives to improve navigation
![idea0](https://user-images.githubusercontent.com/35685689/74166679-45667700-4c27-11ea-97ad-7f01f0523829.gif)
![idea1](https://user-images.githubusercontent.com/35685689/74166680-45ff0d80-4c27-11ea-9e7a-5fbae869c223.gif)

**Comment by pablotr9** [comment]
**Update**
Popover menu + history of last dashboards visited:
![popovermenuHistory](https://user-images.githubusercontent.com/35685689/74635317-0fb11900-5166-11ea-9bee-7a87a38f3588.gif)

**Comment by pablotr9** [comment]
**Update**
A new idea of a Wazuh extensions directory where we can find examples/steps to install and configure our different supported extensions
![popovermenuExtensiondirectory](https://user-images.githubusercontent.com/35685689/74635719-e2189f80-5166-11ea-97d6-804a92423a2e.gif)

**Comment by juankaromo** [comment]
Closed by this issue #1965
