### ISSUE TITLE
Installing wazuh - filebeat - elastic - kibana server

### ISSUE THREAD

**Issue by Aldugama** [wazuh/wazuh-kibana-app#1905]
Hello Wazuh team, 

I've got two question: 

- I need to monitorize with Wazuh, round about 200 Windows agents, 1 fortigate, 50 switches and 10 access points. I would like to know what is your recommendation: just one server with the four services working or a server with wazuh and filebeat and another server with elasticsearch and kibana?

- I would also like to know what are your recommendations for the machine's specifications, how much CPU, RAM, and hard drive?

Greetings, Alejandro.

**Comment by JcabreraC** [comment]
Hello @aldugama,

The recommended hardware requirements it will depend on the needs you have: if you will monitor other types of devices (network devices),  the number of events per second generated, how long you will need the data to be online, etc..

Single server architecture for Manager Wazuh and Elastic Stack would be enough for 200 agents + several network devices (actually about 1000 agents per manager).
We recommend:
    - Processor: 8 cores
    - Memory: 16 GB RAM
    - Storage: 200GB Solid State Disk (SSD)
    - Operating system: Linux. We recommend CentOS.

You should take into consideration that  a Windows agent generates more events than a Linux agent. Depending on the requirements of the environment, we recommend distributing the Elastic manager installation and the Elastic software in two servers. If desired, you can make a high availability configuration with several nodes of Elastic and Wazuh, then the system will have the ability to work continuously in case of failure of any hardware component (e.g. hard disks).
In this case the recommendations are:
    - For each node of ElasticSearch and Kibana: 8 cores, 32 GB of RAM and 1TB of disk space.
    - By Wazuh manager: 4 cores, 16 GB of RAM and 1TB of disk space.

On the other hand, for further questions please we would like you to use our [#community Slack channel](https://wazuh.com/community/join-us-on-slack/) or the [Wazuh mail list](https://groups.google.com/forum/?hl=es#!forum/wazuh).

Best regards,
Juan Cabrera

**Comment by Aldugama** [comment]
Ok, thank you very much. That was really helpful.
