### ISSUE TITLE
kibana7.4.1 安装 wazuhapp以后无法配置api地址。

### ISSUE THREAD

**Issue by bloodzer0** [wazuh/wazuh-kibana-app#1935]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.x   | 7.x     | 444 |

kibana7.4.1 安装 wazuhapp以后无法配置api地址。

**Comment by juankaromo** [comment]
Hi @bloodzer0 

Thank you very much for reporting a bug and in this way make the project grow.

But could you be a little clearer in your explanation and write it in English? It is not clear to us what the problem is happening to you.

Thank you very much.

**Comment by bloodzer0** [comment]
> Hi @bloodzer0
> 
> Thank you very much for reporting a bug and in this way make the project grow.
> 
> But could you be a little clearer in your explanation and write it in English? It is not clear to us what the problem is happening to you.
> 
> Thank you very much.

I can't configure the wazuh API address on kibana's interface

**Comment by bloodzer0** [comment]
> Hi @bloodzer0
> 
> Thank you very much for reporting a bug and in this way make the project grow.
> 
> But could you be a little clearer in your explanation and write it in English? It is not clear to us what the problem is happening to you.
> 
> Thank you very much.

kibana：7.4.2
wazuh：3.10
wazuhapp：wazuhapp-3.10.2_7.4.2.

my error：
Wazuh App: Please set up Wazuh API credentials.
Settings. Error when loading Wazuh setup info

can you help me？

**Comment by juankaromo** [comment]
Hi @bloodzer0

From what I see it seems that you have skipped the window to configure the API. You must click here:

![image](https://user-images.githubusercontent.com/21195730/69873523-dd0b2900-12b8-11ea-890c-c0afe59ac7f1.png)

Then you will see a view similar to this one. Here you can enter the credentials to connect to the API. Once you have done so, click on Save, and you will be able to navigate through the application.

![image](https://user-images.githubusercontent.com/21195730/69873688-4ee37280-12b9-11ea-8efd-7c7a63414a75.png)

I hope this helps and please, let us know the results.

Regards,
Juan Carlos

**Comment by juankaromo** [comment]
Hi @bloodzer0

It looks like you've already solved your problem. If not, do not hesitate to reopen another issue.

Thank you very much!

Regards,
Juan Carlos
