### ISSUE TITLE
Issue with path .../plugins/wazuh/img/logo.svg behind reverse proxy

### ISSUE THREAD

**Issue by c-b-c** [wazuh/wazuh-kibana-app#1939]
Hello,

I've regocnized an issue related to the following path, which ist not working, if Kibana is served with server.basePath: "/kibana" and server.rewriteBasePath: true from behind a reverse proxy (HAProxy in our case)

The logo can not be displayed and as a consequence, the underlying items like Overview, Management, etc are inaccessible due to the placeholder for the missing graphic logo item blows the bar and covers all of the items.

Information to reporoduce:

Wazuh Version: 3.10.2
ELK: 7.4.2

Wazuh App is served under following path and works as expected

https://kibanahost.name/kibana/app/wazuh#

unless the following path

https://kibanahost.name/plugins/wazuh/img/logo.svg

if I manually add /kibana, so it becomes

https://kibanahost.name/kibana/plugins/wazuh/img/logo.svg

the logo is shown.

Thank you for Wazuh!

Best regards,

Christian

**Comment by pablotr9** [comment]
Hi @c-b-c ,

Thanks for reporting that bug, It looks that this is the same error as described here https://github.com/wazuh/wazuh-kibana-app/issues/1871.

It has already been fixed (https://github.com/wazuh/wazuh-kibana-app/pull/1888) and it will be included in the next release of Wazuh.

I hope it helps, if you have any other questions do not hesitate to ask us again!

Kind regards,
Pablo Torres

**Comment by c-b-c** [comment]
Thanks Pablo. I was actually reading through the tracker but did not see #1871 / #1888 so I thought I had to open a new. It is definitively the same bug.

**Comment by pablotr9** [comment]
Hi @c-b-c ,

Don't worry, I will close this issue, feel free to open a new issue if you need anything else!

Best regards,
Pablo Torres
