### ISSUE TITLE
Migrating Management/status and reports to React components

### ISSUE THREAD

**Issue by pablotr9** [wazuh/wazuh-kibana-app#1942]
**Parent Issue: [Redesign tables using react EuiTables](https://github.com/wazuh/wazuh-kibana-app/issues/1829)**

This Issue is for reporting the progress of the `management/status and reports` section.

- [x] Status
- [x] Logs
- [x] Cluster
- [x] Reporting

**Comment by Joanes04** [comment]
**Update 04.12.2019**

The migration of **Status** to React components is complete

- Cluster mode

![cluster](https://user-images.githubusercontent.com/9945959/70148768-18399d80-16a7-11ea-872d-2f6941df1e2b.gif)

- Manager mode

![manager](https://user-images.githubusercontent.com/9945959/70148781-212a6f00-16a7-11ea-8263-ea616b2ed9b3.gif)

**Comment by Joanes04** [comment]
**Update 04.12.2019**

The migration of **Reporting** to React components is complete:

![gif](https://user-images.githubusercontent.com/9945959/70530768-e9fb0880-1b53-11ea-9b99-de4df68af0f6.gif)
