### ISSUE TITLE
Visualize buttons in Discover view of Wazuh plugin broken

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-kibana-app#1944]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.10.2/3.11.0   | 7.4.2     | 0549/0561 |

**Description**
The Visualize buttons from the left bar of the Discover view of the Wazuh app will not carry over any information and instead just generate a generic bar graph.

**Steps to reproduce**

1. Go to any Dashboard within the Kibana Wazuh Plugin and Switch to Discover mode
2. Expand any field on the left column and hit visualize
3. See a generic bar visualization is created without any buckets or filters.

**Workaround**
The desired behavior can be seen by going to the Discover on the top left of Kibana (not Wazuh specific) and selecting Visualize from a field therein.

**Screenshots**
Observed behavior:
![BadVisualize](https://user-images.githubusercontent.com/36071202/70000130-a5231080-155a-11ea-9ef0-e21f9211e228.gif)

Workaround/Expected behavior:
![GoodVisualize](https://user-images.githubusercontent.com/36071202/70000157-b79d4a00-155a-11ea-8912-f3c8d78c77a2.gif)

**Comment by falkowich** [comment]
I can confirm that the interaction worked on v3.9.3.

![ezgif-6-4fca4663d35c](https://user-images.githubusercontent.com/1552705/70002931-d6eba580-1561-11ea-953f-31e7d5b21a3e.gif)

**Comment by juankaromo** [comment]
Hi @jctello and @falkowich 

This has been solved here https://github.com/wazuh/wazuh-kibana-app/commit/56d1340d75b0c7592f4399ef2a1427db55ad1992

Regards,
