### ISSUE TITLE
Agents Summary Screen 

### ISSUE THREAD

**Issue by Joanes04** [wazuh/wazuh-kibana-app#1963]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.13   | 7.6     | X |

**Description**

We are going to build a new welcome screen for agents, to offer the most important information to the user in a fast and easy way. It is important that you show the general state of all the sections, in a screen without vertical scroll.

**Steps**

- [x] Build the agent welcome screen using the selected mockups

**Comment by Joanes04** [comment]
**Update 17.12.2019**

**Mockup v0.1.0** 

- @jsanchez91 has created this first version of the welcome screen

![image](https://user-images.githubusercontent.com/9945959/70988815-c7706e80-20c2-11ea-9075-345d4bdb9b45.png)

**Comment by Joanes04** [comment]
**Update 17.12.2019**

**Mockup v0.1.1**

- @jsanchez91 has created two versions of the agent statistics

![image](https://user-images.githubusercontent.com/9945959/70988992-1ae2bc80-20c3-11ea-8092-409656349791.png)

**Comment by Joanes04** [comment]
**Update 26.12.2019**

**Mockup v0.2.0**

![image](https://user-images.githubusercontent.com/9945959/71476596-1797b100-27e6-11ea-8fcf-dacf89d56b39.png)

**Comment by Joanes04** [comment]
**Update 26.12.2019**

**Mockup v0.3.0**

![image](https://user-images.githubusercontent.com/9945959/71479430-aca1a680-27f4-11ea-9360-7bd313121e6b.png)

**Comment by juankaromo** [comment]
Mockup

![image](https://user-images.githubusercontent.com/21195730/81789112-cde50400-9503-11ea-842d-c11708412c58.png)

**Comment by juankaromo** [comment]
Implemented and released version of this agent's summary/welcome screen
![image](https://user-images.githubusercontent.com/21195730/84006820-b3217600-a96f-11ea-87cf-2bb61767ffbd.png)
