### ISSUE TITLE
Improve app navigability

### ISSUE THREAD

**Issue by pablotr9** [wazuh/wazuh-kibana-app#1965]
Hi team,

We have many different tabs/sections and sometimes navigability is confusing and the user has to click multiple times to do a specific action.

In order to make navigability easier for our users, we have to propose different navigation alternatives and evaluate these alternatives

### **Step 1** Design
- [x] Create several versions until we get close to what we want
- [x] Adapt the selected navigability mockup

### Implementation

The proposal chosen to carry out the new navigation menu is as follows:

![image](https://user-images.githubusercontent.com/21195730/77693748-23dc0780-6fa9-11ea-85e3-50cbda9d09c0.png)

It should be noted that this menu will be accessible by clicking on the Wazuh logo in the breadcrumb.

**Comment by pablotr9** [comment]
**0.1.0**
**Side navigation menu**
![image](https://user-images.githubusercontent.com/35685689/71010021-83de2a80-20eb-11ea-9fa1-95ee8402b57a.png)

**Comment by pablotr9** [comment]
**0.1.1**
**Side navigation menu - Collapsible**
![ejemploSideNav3](https://user-images.githubusercontent.com/35685689/71010314-f222ed00-20eb-11ea-9574-6feba9b8e7bb.gif)

**Comment by pablotr9** [comment]
**0.2.0**
**Drop-down dashboards menu**
![barra](https://user-images.githubusercontent.com/35685689/71010702-8725e600-20ec-11ea-9110-f8bbd5ec8836.gif)
![image](https://user-images.githubusercontent.com/35685689/71010790-9e64d380-20ec-11ea-88d9-8647407cd228.png)

**Comment by jsanchez91** [comment]
**Last update:**
### New component
The wzMenu was migrated to a react component by @pablotr9, this is the result:
![image](https://user-images.githubusercontent.com/3064506/73367264-971a1380-42af-11ea-88c3-3a2232127203.png)

---
### Management submenu
The management welcome menu has been deleted and its content moved to a submenu of wzMenu component.
![image](https://user-images.githubusercontent.com/3064506/73368445-44d9f200-42b1-11ea-92e6-00a79db35c83.png)

---
### Pending improvements
- [ ] Remove the arrow icon from the "Visualize" button.
![image](https://user-images.githubusercontent.com/3064506/73368825-ed885180-42b1-11ea-90ec-0e4364fedd82.png)

- [ ]  Close the management menu when you click on an item
![management_menu_not_close](https://user-images.githubusercontent.com/3064506/73369169-756e5b80-42b2-11ea-98a5-5e79d12a0299.gif)

---
### Known bugs
- [ ]  Standardize the margins of management views
> **Status**
> ![image](https://user-images.githubusercontent.com/3064506/73369465-f168a380-42b2-11ea-8216-5d20301a9a7c.png)

> **Cluster**
> ![image](https://user-images.githubusercontent.com/3064506/73369557-13fabc80-42b3-11ea-80d7-01833c960aa2.png)

> **Reporting**
> ![image](https://user-images.githubusercontent.com/3064506/73369635-35f43f00-42b3-11ea-8f82-c6305eb49c99.png)

- [ ] Fix the time range error in `management > cluster`
![image](https://user-images.githubusercontent.com/3064506/73369767-70f67280-42b3-11ea-95ca-252bef6527bd.png)

**Comment by juankaromo** [comment]
This is the final result of the new navigation (new menu and use of breadcrumbs):

![image](https://user-images.githubusercontent.com/21195730/78224655-32568180-74c9-11ea-8e26-1a5bceabb107.png)
