### ISSUE TITLE
Elasticsearch 7.5.1 compatibility

### ISSUE THREAD

**Issue by KirilllK** [wazuh/wazuh-kibana-app#1968]
Hi! I would like to try Wazuh, but I use the Elasticsearch 7.5.1 version.

**Comment by juankaromo** [comment]
Hi @KirilllK 

Elastic 7.5.1 was released yesterday 18/12, so we are testing it for any breaking change and release a version as robust as possible. We hope to have it ready very very soon if all testing goes well and It will be released in a few days, with the current or with the new version of Wazuh (3.11.0). I'll let you know here when we have it.

Thanks for the patience!

Regards.
Juan Carlos

**Comment by KirilllK** [comment]
Thanks a lot

**Comment by juankaromo** [comment]
Hi @KirilllK 

Wazuh 3.10.2-7.5.1 has been released and gives us compatibility for ELK 7.5.1. You can find the app installation package here: https://packages.wazuh.com/wazuhapp/wazuhapp-3.10.2_7.5.1.zip

If you have any questions about how to update it, please do not hesitate to contact us.

Thanks for the patience!
Regards.
