### ISSUE TITLE
Wazuh app starting error

### ISSUE THREAD

**Issue by Bars7878** [wazuh/wazuh-kibana-app#1978]
Hello!
After migration from 3.10.2 to 3.11.0 can`t start wazuh app for kibana. I got error message:
![image](https://user-images.githubusercontent.com/59124940/71436043-4afa1300-26f4-11ea-9418-c775cff999db.png)
but api wazuh-manager, wazuh-api work properly. API works when i make queries by curl. Kibana 7.5.1. Wazuh app 3.11_7.5.1. No seems error, just 3005 - Error reading file in wazuh app log (in debug mode too) and here 
![image](https://user-images.githubusercontent.com/59124940/71436186-edb29180-26f4-11ea-91f4-6f2b90ef8b5f.png).
Which file error reading? What does its meaning? How resolve it?

**Comment by pablotr9** [comment]
Hi @Bars7878 ,

Did you follow our upgrade guide? The Wazuh UI should **not** be installed using the **root** user.
Please try reinstalling it following these steps: https://github.com/wazuh/wazuh-kibana-app#upgrade

As you can see the Wazuh API configuration has been changed in this new version (v3.11), now you can add/remove/edit API entries by simply editing the `wazuh.yml` file which you can find here `/usr/share/kibana/plugins/wazuh/wazuh.yml`.

If there is any problem with any of your API entries, you can place your mouse over the question mark icon to get more information about it.
![image](https://user-images.githubusercontent.com/35685689/71465638-7e54a480-27bd-11ea-9520-0a440937b9e3.png)

If reinstalling the Wazuh UI doesn't fix your problem, please try removing your browser's cookies.

Let me know if it helps!

Kind regards,
Pablo Torres

**Comment by Bars7878** [comment]
Reinstalling the Wazuh UI and inkognito mode and using other browser doesn't fix problem.
Uninstalling wazuh app requires --allow-root:
b@wazuh:~$ sudo /usr/share/kibana/bin/kibana-plugin remove wazuh
Kibana should not be run as root.  Use --allow-root to continue.
b@wazuh:~$ 
its right?
Icon have a text 3005 - Error reading file:
![image](https://user-images.githubusercontent.com/59124940/71487641-3ec1a300-2825-11ea-808a-e0671039dcc7.png)
If i add any entries in kibana/plugins/wazuh/wazuh.yml its entries show in that window.
Open ports:
root@wazuh:~# netstat -tunap
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:1515            0.0.0.0:*               LISTEN      18356/ossec-authd
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1687/sshd       
tcp        0      0 127.0.0.1:55000         0.0.0.0:*               LISTEN      15045/nodejs    
tcp        0    464 10.128.0.2:22           x.x.x.x:52864     ESTABLISHED 19741/sshd: admin
tcp        0      0 10.128.0.2:54036        169.254.169.254:80      CLOSE_WAIT  1641/python3    
tcp        0      0 10.128.0.2:54042        169.254.169.254:80      ESTABLISHED 1641/python3    
tcp        0      0 10.128.0.2:54040        169.254.169.254:80      ESTABLISHED 1643/python3    
tcp        0      0 127.0.0.1:59472         127.0.0.1:9200          ESTABLISHED 1166/filebeat   
tcp        0      0 10.128.0.2:54038        169.254.169.254:80      ESTABLISHED 1640/python3    
tcp6       0      0 127.0.0.1:9200          :::*                    LISTEN      1222/java       
tcp6       0      0 ::1:9200                :::*                    LISTEN      1222/java       
tcp6       0      0 127.0.0.1:9300          :::*                    LISTEN      1222/java       
tcp6       0      0 ::1:9300                :::*                    LISTEN      1222/java       
tcp6       0      0 :::22                   :::*                    LISTEN      1687/sshd       
tcp6       0      0 127.0.0.1:9200          127.0.0.1:59472         ESTABLISHED 1222/java       
udp        0      0 0.0.0.0:68              0.0.0.0:*                           981/dhclient    
udp        0      0 10.128.0.2:123          0.0.0.0:*                           1559/ntpd       
udp        0      0 127.0.0.1:123           0.0.0.0:*                           1559/ntpd       
udp        0      0 0.0.0.0:123             0.0.0.0:*                           1559/ntpd       
udp        0      0 0.0.0.0:1514            0.0.0.0:*                           18410/ossec-remoted
udp6       0      0 fe80::4001:aff:fe80:123 :::*                                1559/ntpd       
udp6       0      0 ::1:123                 :::*                                1559/ntpd       
udp6       0      0 :::123                  :::*                                1559/ntpd       
root@wazuh:~# 

In wazuh-logs:
{"date":"2019-12-26T19:12:00.600Z","level":"error","location":"wazuh-api:checkStoredAPI","message":"Error reading file"}
{"date":"2019-12-26T19:12:02.636Z","level":"error","location":"wazuh-api:checkStoredAPI","message":"Error reading file"}
{"date":"2019-12-26T19:12:03.214Z","level":"error","location":"wazuh-api:checkAPI","message":"Error reading file"}
{"date":"2019-12-26T19:12:04.626Z","level":"error","location":"wazuh-api:checkAPI","message":"Error reading file"}

I think the problem is with the rights, but what file cant be read?


In additional:
root@wazuh:~# systemctl status wazuh-api
● wazuh-api.service - Wazuh API daemon
   Loaded: loaded (/etc/systemd/system/wazuh-api.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-12-25 05:45:40 UTC; 1 day 13h ago
     Docs: https://documentation.wazuh.com/current/user-manual/api/index.html
  Process: 15042 ExecStop=/bin/kill -HUP $MAINPID (code=exited, status=0/SUCCESS)
 Main PID: 15045 (nodejs)
    Tasks: 10
   Memory: 31.2M
      CPU: 3min 14.656s
   CGroup: /system.slice/wazuh-api.service
           └─15045 /usr/bin/nodejs /var/ossec/api/app.js
Dec 25 05:45:40 wazuh systemd[1]: Started Wazuh API daemon.
root@wazuh:~# 

root@wazuh:~# systemctl status wazuh
● wazuh.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
root@wazuh:~# systemctl status wazuh-manager
● wazuh-manager.service - Wazuh manager
   Loaded: loaded (/etc/systemd/system/wazuh-manager.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-12-25 06:50:38 UTC; 1 day 12h ago
  Process: 18142 ExecStop=/usr/bin/env ${DIRECTORY}/bin/ossec-control stop (code=exited, status=0/SUCCESS)
  Process: 18264 ExecStart=/usr/bin/env ${DIRECTORY}/bin/ossec-control start (code=exited, status=0/SUCCESS)
    Tasks: 88
   Memory: 261.6M
      CPU: 2d 23h 47min 20.382s
   CGroup: /system.slice/wazuh-manager.service
           ├─18343 /var/ossec/bin/ossec-integratord
           ├─18356 /var/ossec/bin/ossec-authd
           ├─18365 /var/ossec/bin/wazuh-db
           ├─18383 /var/ossec/bin/ossec-execd
           ├─18391 /var/ossec/bin/ossec-analysisd
           ├─18401 /var/ossec/bin/ossec-syscheckd
           ├─18410 /var/ossec/bin/ossec-remoted
           ├─18412 /var/ossec/bin/ossec-logcollector
           ├─18436 /var/ossec/bin/ossec-monitord
           └─18457 /var/ossec/bin/wazuh-modulesd
Dec 25 06:50:36 wazuh env[18264]: Started ossec-logcollector...
Dec 25 06:50:36 wazuh env[18264]: Started ossec-monitord...
Dec 25 06:50:36 wazuh env[18264]: 2019/12/25 06:50:36 wazuh-modulesd: WARNING: This vulnerability-detector declaration is deprecated. Use <vulnerability-detector> instead.
Dec 25 06:50:36 wazuh env[18264]: 2019/12/25 06:50:36 wazuh-modulesd: WARNING: 'disabled' option at module 'vulnerability-detector' is deprecated. Use 'enabled' instead.
Dec 25 06:50:36 wazuh env[18264]: 2019/12/25 06:50:36 wazuh-modulesd: WARNING: 'feed' option at module 'vulnerability-detector' is deprecated. Use 'provider' instead.
Dec 25 06:50:36 wazuh env[18264]: 2019/12/25 06:50:36 wazuh-modulesd: WARNING: 'feed' option at module 'vulnerability-detector' is deprecated. Use 'provider' instead.
Dec 25 06:50:36 wazuh env[18264]: 2019/12/25 06:50:36 wazuh-modulesd: WARNING: 'feed' option at module 'vulnerability-detector' is deprecated. Use 'provider' instead.
Dec 25 06:50:36 wazuh env[18264]: Started wazuh-modulesd...
Dec 25 06:50:38 wazuh env[18264]: Completed.
Dec 25 06:50:38 wazuh systemd[1]: Started Wazuh manager.
root@wazuh:~#

**Comment by Bars7878** [comment]
In additional:
![image](https://user-images.githubusercontent.com/59124940/71488237-2bfc9d80-2828-11ea-9c71-de4d580ba4f6.png)

**Comment by Bars7878** [comment]
![image](https://user-images.githubusercontent.com/59124940/71488262-59494b80-2828-11ea-9944-3b982cb8d1c1.png)

**Comment by Bars7878** [comment]
![image](https://user-images.githubusercontent.com/59124940/71488277-72ea9300-2828-11ea-982d-428d20d34457.png)

**Comment by pablotr9** [comment]
Hi @Bars7878 ,

> Reinstalling the Wazuh UI and inkognito mode and using other browser doesn't fix problem.
Uninstalling wazuh app requires --allow-root:
b@wazuh:$ sudo /usr/share/kibana/bin/kibana-plugin remove wazuh
Kibana should not be run as root. Use --allow-root to continue.
b@wazuh:$
its right?

No, as the error says `root` can't be used to manage Kibana plugins you should use the `kibana` user, let's try following these steps to reinstall the app:
1. Stop Kibana
```
systemctl stop kibana
```
2.  Remove the Wazuh plugin:
```
sudo -u kibana /usr/share/kibana/bin/kibana-plugin remove wazuh
```
3. Remove generated bundles
```
rm -rf /usr/share/kibana/optimize/bundles
```
4. Update file permissions. This will avoid several errors prior to updating the app:
```
chown -R kibana:kibana /usr/share/kibana/optimize
chown -R kibana:kibana /usr/share/kibana/plugins
```
5. Install the app (this is v3.11-7.5.1 if you are using a different a version please replace the package link)
```
sudo -u kibana /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.11.0_7.5.1.zip
```

Now that you have reinstalled the Wazuh UI without using root user,  try accessing it again and check if it's now working.
If you still have the same problem, we will enable the debug mode (in Wazuh API and Wazuh UI) so we can get more information so we can know what is really happening:
1. Enable Debug mode in Wazuh UI:
Edit the `wazuh.yml` (/usr/share/kibana/plugins/wazuh/wazuh.yml) and replace this line:
```
#logs.level: info
```
with:
```
logs.level: debug
```
Then restart Kibana ( once your problem is fixed you can disable the debug mode by setting the log level to info back again)

2. Enable Debug mode in Wazuh API:
Edit `config.js` file.  (/var/ossec/api/configuration/config.js) and replace this line:
```
config.logs = "info";
```
with 
```
config.logs = "debug";
```
Now restart Wazuh manager and Wazuh API:
```
systemctl restart wazuh-manager
systemctl restart wazuh-api
```


We now have enabled the debug mode in both Wazuh UI and Wazuh API, so let's now try accessing the Wazuh UI  and click on the `check connection` button and check the logs.
- Wazuh UI logs:
```
tail -n 50 /usr/share/kibana/optimize/wazuh-logs/wazuhapp.log
```
- Wazuh API logs: 
```
tail -n 50 /var/ossec/logs/api.log
```

Please paste the output in a file and attach it to your reply! 

Kind regards,
Pablo Torres

**Comment by Bars7878** [comment]
b@wazuh:~$ tail -n 50 /usr/share/kibana/optimize/wazuh-logs/wazuhapp.log
{"date":"2019-12-27T11:24:42.533Z","level":"debug","location":"manage-hosts:getHosts","message":"Getting hosts"}
{"date":"2019-12-27T11:24:42.534Z","level":"debug","location":"update-registry:getHosts","message":"Getting hosts from registry"}
{"date":"2019-12-27T11:24:42.534Z","level":"debug","location":"update-registry:readContent","message":"Reading wazuh-registry.json content"}
{"date":"2019-12-27T11:24:42.698Z","level":"debug","location":"wazuh-api:getTimeStamp","message":"Installation date: 2019-12-27T11:12:50.037Z. Last restart: 2019-12-27T11:23:1
7.291Z"}
{"date":"2019-12-27T11:24:42.869Z","level":"debug","location":"manage-hosts:getHostById","message":"Getting host default"}
{"date":"2019-12-27T11:24:42.869Z","level":"debug","location":"manage-hosts:getHosts","message":"Getting hosts"}
{"date":"2019-12-27T11:24:42.870Z","level":"debug","location":"wazuh-api:checkStoredAPI","message":"default exists"}
{"date":"2019-12-27T11:24:43.174Z","level":"error","location":"wazuh-api:checkStoredAPI","message":"Error reading file"}
{"date":"2019-12-27T11:24:43.586Z","level":"debug","location":"manage-hosts:getHosts","message":"Getting hosts"}
{"date":"2019-12-27T11:24:43.587Z","level":"debug","location":"update-registry:getHosts","message":"Getting hosts from registry"}
{"date":"2019-12-27T11:24:43.587Z","level":"debug","location":"update-registry:readContent","message":"Reading wazuh-registry.json content"}
{"date":"2019-12-27T11:24:43.750Z","level":"debug","location":"wazuh-hosts:cleanRegistry","message":"Cleaning registry"}
{"date":"2019-12-27T11:24:43.750Z","level":"debug","location":"update-registry:removeOrphanEntries","message":"Checking orphan registry entries"}
{"date":"2019-12-27T11:24:43.750Z","level":"debug","location":"update-registry:getHosts","message":"Getting hosts from registry"}
{"date":"2019-12-27T11:24:43.751Z","level":"debug","location":"update-registry:readContent","message":"Reading wazuh-registry.json content"}
{"date":"2019-12-27T11:24:43.751Z","level":"debug","location":"update-registry:removeHostEntry","message":"Removing entry"}
{"date":"2019-12-27T11:24:43.751Z","level":"debug","location":"update-registry:readContent","message":"Reading wazuh-registry.json content"}
{"date":"2019-12-27T11:24:43.752Z","level":"debug","location":"update-registry:writeContent","message":"Writting wazuh-registry.json content"}
{"date":"2019-12-27T11:24:43.936Z","level":"debug","location":"wazuh-api:checkAPI","message":"default is valid"}
{"date":"2019-12-27T11:24:43.936Z","level":"debug","location":"manage-hosts:getHostById","message":"Getting host default"}
{"date":"2019-12-27T11:24:43.936Z","level":"debug","location":"manage-hosts:getHosts","message":"Getting hosts"}
{"date":"2019-12-27T11:24:44.238Z","level":"debug","location":"wazuh-api:checkAPI","message":"default credentials are valid"}
{"date":"2019-12-27T11:24:44.238Z","level":"error","location":"wazuh-api:checkAPI","message":"Error reading file"}
{"date":"2019-12-27T11:24:48.774Z","level":"debug","location":"manage-hosts:getHosts","message":"Getting hosts"}
{"date":"2019-12-27T11:24:48.774Z","level":"debug","location":"update-registry:getHosts","message":"Getting hosts from registry"}
{"date":"2019-12-27T11:24:48.775Z","level":"debug","location":"update-registry:readContent","message":"Reading wazuh-registry.json content"}
{"date":"2019-12-27T11:24:48.951Z","level":"debug","location":"wazuh-api:checkAPI","message":"default is valid"}
{"date":"2019-12-27T11:24:48.951Z","level":"debug","location":"manage-hosts:getHostById","message":"Getting host default"}
{"date":"2019-12-27T11:24:48.951Z","level":"debug","location":"manage-hosts:getHosts","message":"Getting hosts"}
{"date":"2019-12-27T11:24:49.238Z","level":"debug","location":"wazuh-api:checkAPI","message":"default credentials are valid"}
{"date":"2019-12-27T11:24:49.238Z","level":"error","location":"wazuh-api:checkAPI","message":"Error reading file"}
{"date":"2019-12-27T11:24:50.165Z","level":"debug","location":"manage-hosts:getHosts","message":"Getting hosts"}
{"date":"2019-12-27T11:24:50.166Z","level":"debug","location":"update-registry:getHosts","message":"Getting hosts from registry"}
{"date":"2019-12-27T11:24:50.166Z","level":"debug","location":"update-registry:readContent","message":"Reading wazuh-registry.json content"}
{"date":"2019-12-27T11:24:50.336Z","level":"debug","location":"wazuh-api:checkAPI","message":"default is valid"}
{"date":"2019-12-27T11:24:50.337Z","level":"debug","location":"manage-hosts:getHostById","message":"Getting host default"}
{"date":"2019-12-27T11:24:50.337Z","level":"debug","location":"manage-hosts:getHosts","message":"Getting hosts"}
{"date":"2019-12-27T11:24:50.624Z","level":"debug","location":"wazuh-api:checkAPI","message":"default credentials are valid"}
{"date":"2019-12-27T11:24:50.624Z","level":"error","location":"wazuh-api:checkAPI","message":"Error reading file"}
{"date":"2019-12-27T11:30:00.832Z","level":"debug","location":"manage-hosts:getHosts","message":"Getting hosts"}
{"date":"2019-12-27T11:30:00.832Z","level":"debug","location":"update-registry:getHosts","message":"Getting hosts from registry"}
{"date":"2019-12-27T11:30:00.833Z","level":"debug","location":"update-registry:readContent","message":"Reading wazuh-registry.json content"}
{"date":"2019-12-27T11:30:00.835Z","level":"debug","location":"monitoring:loadCredentials","message":"Number of valid APIs found: 1"}
{"date":"2019-12-27T11:30:00.835Z","level":"debug","location":"monitoring:loadCredentials","message":"Calling checkAndSaveStatus for API: http://localhost:55000"}
{"date":"2019-12-27T11:30:00.835Z","level":"debug","location":"monitoring:checkAndSaveStatus","message":"Prepare OptionsObject for API: http://localhost:55000"}

=============================================================

b@wazuh:~$ tail -n 50 /var/ossec/logs/api.log
tail: cannot open '/var/ossec/logs/api.log' for reading: Permission denied
b@wazuh:~$ sudo tail -n 50 /var/ossec/logs/api.log
{"message": "Error reading file: /var/ossec/ruleset/VERSION", "error": 1005}
---
WazuhAPI 2019-12-27 11:24:40 foo: CMD - STDOUT: 77 bytes
WazuhAPI 2019-12-27 11:24:40 foo: Error reading file: /var/ossec/ruleset/VERSION
WazuhAPI 2019-12-27 11:24:40 foo: [127.0.0.1] GET /manager/info? - 200 - error: '1005'.
WazuhAPI 2019-12-27 11:24:42 foo: 127.0.0.1 GET /manager/info
WazuhAPI 2019-12-27 11:24:42 foo: CMD - Command: /var/ossec/framework/python/bin/python3 args:/var/ossec/api/models/wazuh-api.py stdin:{"function":"/manager/info","arguments":
{"wait_for_complete":false}}
WazuhAPI 2019-12-27 11:24:43 foo: CMD - Exit code: 0
WazuhAPI 2019-12-27 11:24:43 foo: CMD - STDOUT:
---
{"message": "Error reading file: /var/ossec/ruleset/VERSION", "error": 1005}
---
WazuhAPI 2019-12-27 11:24:43 foo: CMD - STDOUT: 77 bytes
WazuhAPI 2019-12-27 11:24:43 foo: Error reading file: /var/ossec/ruleset/VERSION
WazuhAPI 2019-12-27 11:24:43 foo: [127.0.0.1] GET /manager/info? - 200 - error: '1005'.
WazuhAPI 2019-12-27 11:24:43 foo: 127.0.0.1 GET /manager/info
WazuhAPI 2019-12-27 11:24:43 foo: CMD - Command: /var/ossec/framework/python/bin/python3 args:/var/ossec/api/models/wazuh-api.py stdin:{"function":"/manager/info","arguments":
{"wait_for_complete":false}}
WazuhAPI 2019-12-27 11:24:44 foo: CMD - Exit code: 0
WazuhAPI 2019-12-27 11:24:44 foo: CMD - STDOUT:
---
{"message": "Error reading file: /var/ossec/ruleset/VERSION", "error": 1005}
---
WazuhAPI 2019-12-27 11:24:44 foo: CMD - STDOUT: 77 bytes
WazuhAPI 2019-12-27 11:24:44 foo: Error reading file: /var/ossec/ruleset/VERSION
WazuhAPI 2019-12-27 11:24:44 foo: [127.0.0.1] GET /manager/info? - 200 - error: '1005'.
WazuhAPI 2019-12-27 11:24:48 foo: 127.0.0.1 GET /manager/info
WazuhAPI 2019-12-27 11:24:48 foo: CMD - Command: /var/ossec/framework/python/bin/python3 args:/var/ossec/api/models/wazuh-api.py stdin:{"function":"/manager/info","arguments":
{"wait_for_complete":false}}
WazuhAPI 2019-12-27 11:24:49 foo: CMD - Exit code: 0
WazuhAPI 2019-12-27 11:24:49 foo: CMD - STDOUT:
---
{"message": "Error reading file: /var/ossec/ruleset/VERSION", "error": 1005}
---
WazuhAPI 2019-12-27 11:24:49 foo: CMD - STDOUT: 77 bytes
WazuhAPI 2019-12-27 11:24:49 foo: Error reading file: /var/ossec/ruleset/VERSION
WazuhAPI 2019-12-27 11:24:49 foo: [127.0.0.1] GET /manager/info? - 200 - error: '1005'.
WazuhAPI 2019-12-27 11:24:50 foo: 127.0.0.1 GET /manager/info
WazuhAPI 2019-12-27 11:24:50 foo: CMD - Command: /var/ossec/framework/python/bin/python3 args:/var/ossec/api/models/wazuh-api.py stdin:{"function":"/manager/info","arguments":
{"wait_for_complete":false}}
WazuhAPI 2019-12-27 11:24:50 foo: CMD - Exit code: 0
WazuhAPI 2019-12-27 11:24:50 foo: CMD - STDOUT:
---
{"message": "Error reading file: /var/ossec/ruleset/VERSION", "error": 1005}
---
WazuhAPI 2019-12-27 11:24:50 foo: CMD - STDOUT: 77 bytes
WazuhAPI 2019-12-27 11:24:50 foo: Error reading file: /var/ossec/ruleset/VERSION
WazuhAPI 2019-12-27 11:24:50 foo: [127.0.0.1] GET /manager/info? - 200 - error: '1005'

**Comment by Bars7878** [comment]
Now i see which file read error, but why?

**Comment by pablotr9** [comment]
Hi @Bars7878 ,

As we can see in those logs there is a problem with the file `/var/ossec/ruleset/VERSION`, what version of Wazuh you installed? is it a fresh installation or you upgraded from an older version?

Let's check the permissions of that file:
`ll /var/ossec/ruleset/`
Please paste the output of that command to your reply.

Best regards,
Pablo Torres

**Comment by Bars7878** [comment]
Its upgrade from 3.10.2 to 3.11.
Now installed 3.11. Wazuh side work properly.
b@wazuh:/var$ sudo ls -l /var/ossec/ruleset/
total 52
drwxr-x--- 2 root ossec 20480 Dec 23 19:44 decoders
drwxr-x--- 2 root ossec 24576 Dec 23 19:44 rules
drwxr-x--- 2 root ossec  4096 Dec 23 19:45 sca
-rwxr-x--- 1 root root     43 Dec 23 21:33 VERSION

-rwxr-x--- 1 root root     43 Dec 23 21:33 VERSION Its a problem?

**Comment by pablotr9** [comment]
Hi @Bars7878 ,

Yes, it's a problem, the owner of that file should be root:ossec, could you please give us some more information? What upgrade process did you follow to upgrade Wazuh from 3.10.2 to 3.11? Thank you

To fix it, you can change the owner of that file with this command:
```
chown root:ossec /var/ossec/ruleset/VERSION
```
Then try to access the Wazuh UI and let me know if it's now working correctly.

Best regards,
Pablo Torres

**Comment by Bars7878** [comment]
Great thanks! I understand that problem, but dont know about how to enable debug... Thank you very much! For upgrade process i use instruction https://documentation.wazuh.com/3.2/installation-guide/upgrading/latest_wazuh3_minor.html#upgrading-latest-minor

**Comment by pablotr9** [comment]
Hi @Bars7878 ,

Happy to see it's working! I see the link you sent me is for Wazuh version 3.2, don't forget to follow the documentation for the latest version (v3.11).

I will close this issue, do not hesitate to reopen it or open a new one if you have any other problem!

Best regards,
Pablo Torres

**Comment by Bars7878** [comment]
Yes! But may be its will be interesting for you: after renaming ossec.conf.new to ossec.conf i receive a same issue. After checking debug i found: "Error reading cluster configuration: Requested component does not exist: [Errno 13] Permission denied: '/var/ossec/etc/ossec.conf'". After run ls -l:
b@wazuh:~$ sudo ls -l /var/ossec/etc/
total 92
-rw-r----- 1 root ossec  1229 Dec 27 18:18 client.keys
drwxrwx--- 2 root ossec  4096 Dec 23 19:45 decoders
-rw-r----- 1 root ossec 13494 Dec 18 11:06 internal_options.conf
drwxrwx--- 3 root ossec  4096 Nov 23 20:05 lists
-rw-r----- 1 root ossec   320 Sep 23 14:17 local_internal_options.conf
-rw-r----- 1 root ossec   127 Oct  2 21:06 localtime
-rw-rw---- 1 root ossec 10052 Dec 17 06:47 ossec.bck
-rw-rw---- 1 root root   9616 Dec 27 18:17 ossec.conf
-rw-rw---- 1 root ossec 10052 Dec 17 06:47 ossec.conf.old
lrwxrwxrwx 1 root root     20 Dec 18 11:06 ossec-init.conf -> /etc/ossec-init.conf
drwxrwx--- 2 root ossec  4096 Dec 23 19:44 rootcheck
drwxrwx--- 2 root ossec  4096 Dec 23 19:45 rules
drwxrwx--- 5 root ossec  4096 Dec 23 19:44 shared
-rw-r----- 1 root root   1176 Nov 23 20:05 sslmanager.cert
-rw-r----- 1 root root   1708 Nov 23 20:05 sslmanager.key
b@wazuh:~$ sudo chown root:ossec /var/ossec/etc/ossec.conf

and after sudo chown root:ossec /var/ossec/etc/ossec.conf and restart wazuh-manager all works fine. I have proposition for you: may be you can add a script to wazuh-manager which will check rights of files and correst them if needed or inform admin about incorrect rights of files?

**Comment by XCM-jj** [comment]
thank you ！
