### ISSUE TITLE
Wrong Visualisation Wazuh App Overview General Agents status

### ISSUE THREAD

**Issue by Mugen1991** [wazuh/wazuh-kibana-app#198]
Could it be, that the visualization **Wazuh App Overview General Agents status** is wrong? We had to change it to use **id.keyword** and **status.keyword** (Using Kibana 6.1.2)

Fixed visualization:
```
{
  "title": "Wazuh App Overview General Agents status",
  "type": "histogram",
  "params": {
    "type": "histogram",
    "grid": {
      "categoryLines": false,
      "style": {
        "color": "#eee"
      }
    },
    "categoryAxes": [
      {
        "id": "CategoryAxis-1",
        "type": "category",
        "position": "bottom",
        "show": true,
        "style": {},
        "scale": {
          "type": "linear"
        },
        "labels": {
          "show": true,
          "truncate": 100
        },
        "title": {}
      }
    ],
    "valueAxes": [
      {
        "id": "ValueAxis-1",
        "name": "LeftAxis-1",
        "type": "value",
        "position": "left",
        "show": true,
        "style": {},
        "scale": {
          "type": "linear",
          "mode": "normal"
        },
        "labels": {
          "show": true,
          "rotate": 0,
          "filter": false,
          "truncate": 100
        },
        "title": {
          "text": "Count"
        }
      }
    ],
    "seriesParams": [
      {
        "show": true,
        "mode": "normal",
        "type": "line",
        "drawLinesBetweenPoints": false,
        "showCircles": true,
        "interpolate": "cardinal",
        "lineWidth": 3.5,
        "data": {
          "id": "4",
          "label": "Count"
        },
        "valueAxis": "ValueAxis-1"
      }
    ],
    "addTooltip": true,
    "addLegend": true,
    "legendPosition": "right",
    "times": [],
    "addTimeMarker": false
  },
  "aggs": [
    {
      "id": "2",
      "enabled": true,
      "type": "date_histogram",
      "schema": "segment",
      "params": {
        "field": "@timestamp",
        "interval": "h",
        "customInterval": "2h",
        "min_doc_count": 1,
        "extended_bounds": {}
      }
    },
    {
      "id": "3",
      "enabled": true,
      "type": "terms",
      "schema": "group",
      "params": {
        "field": "status.keyword",
        "size": 5,
        "order": "desc",
        "orderBy": "_term"
      }
    },
    {
      "id": "4",
      "enabled": true,
      "type": "cardinality",
      "schema": "metric",
      "params": {
        "field": "id.keyword",
        "customLabel": "Count"
      }
    }
  ]
}
```

**Comment by havidarou** [comment]
Hi @Mugen1991 ,

I'll check it out.

Thanks!

**Comment by JuanjiJG** [comment]
Hi @Mugen1991,

Could you please tell us what's exactly the problem with that visualization? I've tested it on our dev environment and everything seems correct.
![vis](https://user-images.githubusercontent.com/10928321/35671536-00970202-073c-11e8-966b-20dd7b5cb4e8.PNG)

Our app is in constant development, and we're always working on improving it and fixing bugs. Can you go to the `package.json` file and send us the value of the `revision` field? We'll check it out to find any possible bugs in the revision you're using currently.

Thanks for your patience.

Best regards,
Juanjo

**Comment by Mugen1991** [comment]
Hi @JuanjiJG  
The revision was 0345. 
It could be, that the error apeared, because wazuh doesn't send directly to Elasticsearch but Logstash. All Visualisations worked except **Agent Status**. We had to switch from status to status.keyword.

**Comment by JuanjiJG** [comment]
Hi again @Mugen1991,

Seems like you're using an outdated version of our Wazuh App. I strongly recommend you to update to our latest stable versions. We're constantly working on improvements to the app and give it support for the latest versions of the Elastic stack.

* If you're using **Wazuh 3.0**, I recommend you to update to **Elastic 6.1.0** and use the following command:
`/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.0.0_6.1.0.zip`

* If you're using **Wazuh 3.1**, you should update to **Elastic 6.1.2** and use this command:
`/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.1.0_6.1.2.zip`

In the next days, we will release new versions of Wazuh and the Wazuh App, with new features, bugfixes and full compatibility with Elastic 6.1.3. If you want, you can wait until we release them, and I'll let you know when it's ready.

Thanks for your patience.

Best regards,
Juanjo

**Comment by JuanjiJG** [comment]
Hi @Mugen1991,

We've released a new version of the Wazuh App, with full compatibility with Elastic 6.1.3. You can download it right now and install with the following commands (as superuser):

1. **Stop Kibana**:
`systemctl stop kibana`

2. **Remove the old Wazuh App**:
`/usr/share/kibana/bin/kibana-plugin remove wazuh`

3. **Delete the optimizing bundles**. Don't worry, they will be re-generated after restarting the service:
`rm -rf /usr/share/kibana/optimize/bundles`

4. **Install the new Wazuh App plugin**: `/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.1.0_6.1.3.zip`

5. **Restart the Kibana service**:
`systemctl start kibana`

If you still have issues or questions about anything related to the Wazuh App, feel free to create a new issue here.

Best regards,
Juanjo

**Comment by jesusgn90** [comment]
Hi @Mugen1991, as @JuanjiJG suggested you, give a try to our new version of the Wazuh App and check if you are having the same problem with that visualization. If after upgrade you see that the problem persists, plase create a new issue and we will be glad to help you. 

I'm going to close this issue but as I said, feel free to open a new issue if you have troubles upgrading or any kind of trouble.

King regards,
Jesús

**Comment by tientmse62290** [comment]
Can any help me to visualize the json schema above? I'm newbie here and want to make a line chart like agent status
Thanks & best regards
