### ISSUE TITLE
Missing checks.fields option in Kibana web app config.yml

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh-kibana-app#1982]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.11   | any     | any |

**Description**

The Wazuh web app runs five health checks these days.

![image](https://user-images.githubusercontent.com/13170654/71630872-8785ad00-2bd3-11ea-9180-09c20f173103.png)

However only four are configurable in /usr/share/kibana/plugins/wazuh/config.yml

```
# ----------------------------------- Checks -----------------------------------
#
# Defines which checks must to be consider by the healthcheck
# step once the Wazuh app starts. Values must to be true or false.
#checks.pattern : true
#checks.template: true
#checks.api     : true
#checks.setup   : true

```

According to the latest [here](https://github.com/wazuh/wazuh-kibana-app/blob/master/wazuh.yml) it appears this is still the case in the master branch.

I propose adding a **checks.fields** option to optionally disable the "Check index pattern known fields" check.

Thanks,
Kevin Branch

**Comment by pablotr9** [comment]
Hi @branchnetconsulting ,

I have just added this PR with the new settings option `checks.fields` which allows enabling/disabling the `Check index pattern known fields` health check.

Indeed it could be helpful to users with some specific needs (e.g those who only need management section), but I have to mention that not checking the Known Fields can result in multiple errors when accessing any of our dashboards if the template/mappings are not correctly configured. In that case
that would be the responsibility of the final user as by default, the check is enabled. 

@juankaromo  what you think about this? Should we merge it?

**Comment by branchnetconsulting** [comment]
I have a case where one of my clients always has that "Check index pattern
known fields" check fail, though all the Wazuh app features work for them.
That is why I was especially interested in the option to suppress it.

Kevin

**Comment by juankaromo** [comment]
LGTM, merged.
