### ISSUE TITLE
cannot download wazuhapp

### ISSUE THREAD

**Issue by zcadqe897** [wazuh/wazuh-kibana-app#1983]
curl -sI https://packages.wazuh.com/wazuhapp/wazuhapp-3.11.0_7.5.1.zip
HTTP/1.1 403 Forbidden
Content-Type: application/xml
Connection: keep-alive
Date: Thu, 02 Jan 2020 07:44:32 GMT
Server: AmazonS3
X-Cache: Error from cloudfront
Via: 1.1 d19f6de4de1eb10d5b27d86de6b4a7d5.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: SIN52-C3
X-Amz-Cf-Id: QRmokat60xVD5FbEGzK2vUVqbdJMQAmBnXOQHA1dSLpfnbTdFyVEbA==

**Comment by alberpilot** [comment]
Hello @zcadqe897 

  Unfortunately, we undo the 3.11.0 release due to an important issue. More details: https://groups.google.com/forum/#!topic/wazuh/K6IkDAD68po. 

We will publish 3.11.1 soon, sorry for the inconvenience. 

Best regards, 
Alberto R

**Comment by juankaromo** [comment]
Hi @zcadqe897

Here you can find the release of Wazuh App 3.11.1 with Kibana 7.5.1: https://github.com/wazuh/wazuh-kibana-app/releases/tag/v3.11.1-7.5.1

You will need Wazuh manager version 3.11.1 (here you can find the installation guide https://documentation.wazuh.com/3.11/installation-guide/installing-wazuh-manager/index.html) and this is the command for the Wazuh plugin installation:
```
/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.11.1_7.5.1.zip
```

If you have any doubts, don't hesitate to open another issue. I'll close this one for now.

Best regards,
