### ISSUE TITLE
The unique API is not set as default

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-kibana-app#1988]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.11.x   | 6.8.6 - 7.3.2 - 7.5.1    | 581 |

**Description**
When the application is started with invalid API settings, corrected and the interactive guide closed, the API is not selected by default.

**Screenshots**

![Wazuh_default_api](https://user-images.githubusercontent.com/3064506/71729776-de43ee80-2e40-11ea-9f97-9636e37060af.gif)

**Comment by pablotr9** [comment]
**Update**
Fixed here: https://github.com/wazuh/wazuh-kibana-app/pull/2019/commits/6d33f508731b9220b11f3cc35ed54f9164a07876
![setUniqueApi](https://user-images.githubusercontent.com/35685689/72978981-abee3700-3dd7-11ea-87c1-984f8d72ec35.gif)
