### ISSUE TITLE
Plugin incompatible 

### ISSUE THREAD

**Issue by ghlilou97** [wazuh/wazuh-kibana-app#1990]
Hello, I wan't to know wich wazuh plugin is compatible with kibana 7.4.1 because i  get same error on both version 

-Plugin installation was unsuccessful due to error "Plugin wazuh [7.5.1] is incompatible with Kibana [7.4.1]"
-Plugin installation was unsuccessful due to error "Plugin wazuh [7.3.2] is incompatible with Kibana [7.4.1]"
Thanks

**Comment by juankaromo** [comment]
Hi @ghlilou97 ,

Unfortunately, we do not support Kibana 7.4.X in Wazuh 3.11.X. The last version of Wazuh with support for 7.4.X was 3.10.2. 

Our support policy for ELK consists of the following:

For each release of Wazuh, we will support:

- The latest version of 7.X (in this case 7.5.1).
- The latest version of 6.X (in this case 6.8.6) (This will also be discontinued in the future).
- The latest version compatible with OpenDistro (in this case 7.3.2).

I'm sorry I can't help you here, but I invite you to update you ELK (as far as possible) to 7.5.1, which has several changes and improvements.

Regards,
