### ISSUE TITLE
Migrating overview and agents dashboards to new component Visualize

### ISSUE THREAD

**Issue by Joanes04** [wazuh/wazuh-kibana-app#1992]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.12   | 7.5     | X |

**Description**

We're going to remove the agents dashboards, to unify all the dashboards in a new component called **Visualize**. The idea is to create a generic data structure that unifies the dashboards of both agents and overviews, and loads them dynamically.

**Steps**

- [x] Define the new data structure
- [x] Implement in the new structure the overview dashboards
- [x] Implement in the new structure the agents dashboards
- [x] Migrate **dashboard.html** to a react component
- [x] Migrate agent dashboards

**Comment by Joanes04** [comment]
**UPDATE**

We have started to define the new data structure like a **JSON**:

```
name_dashboard: {
    metrics: [
        {
            id: 'id_metric',
        },
    ],
    rows: [
        height: XXX.
        vis: [
            {
                title: 'title_visualization',
                id: 'id_visualization',
                width: XXX,
            },
        ],
    ]
}
```

**Comment by Joanes04** [comment]
**UPDATE** 

In the case of the HIPAA dashboard, we have several rows within a column:

![image](https://user-images.githubusercontent.com/9945959/72134605-d32f1800-3384-11ea-8b3c-9f3c3cd21cea.png)


So we have added a new use case to our data structure:

```
name_dashboard: {
    metrics: [
        {
            id: 'id_metric',
        },
    ],
    rows: [
        {
            height: XXX.
            vis: [
                {
                    hasRows: true,
                    rows: [
                        {
                            height: XXX,
                            vis: [
                                {
                                    title: 'title_visualization',
                                    id: 'id_visualization',
                                    width: XXX,
                                }
                            ],
                        },
                    ],
                },
            ],
        },
    ]
}
```

**Comment by Joanes04** [comment]
**UPDATE**

We have already migrated the overview dashboards to the new component: **visualize**. The new system of generic data structures is already in place.
We have cleaned up all the old code, removing the templates that are no longer used and unifying everything in a single file that we have called **dashboards.html**

**Comment by Joanes04** [comment]
**Update 13.01.2020**

**Mockup v0.0.1**

We have made a first version of the functionality to switch between overview and agent dashboards. We will explain how the views and their functionality will change.

1. We have only one overview view, in which in the upper right part, we add a new button to be able to select the agents view.

![image](https://user-images.githubusercontent.com/9945959/72266227-38516a80-361e-11ea-9afd-9340d9c72cb4.png)

2. When we click on `Select agent`, a **flyout** opens on the right side. In this **flyout** we have a table with the available agents, so we can select one of them

![image](https://user-images.githubusercontent.com/9945959/72266453-a9911d80-361e-11ea-89c6-065c59d413ed.png)

3. Once the agent is selected, the overview view changes and shows us the specific dashboard of that agent, and the possibility of going back to the previous view, pressing the close of the upper right button: `X Agent Selected: agent`

![image](https://user-images.githubusercontent.com/9945959/72266531-d6ddcb80-361e-11ea-9bb3-ade57ac49ef6.png)

**Comment by Joanes04** [comment]
**UPDATE 14.01.2020**

We have already migrated the agents dashboards to the new component: visualize-agents. The new system of generic data structures is already in place.
We have cleaned up all the old code, removing the templates that are no longer used.

**Comment by pablotr9** [comment]
**Update**
Both Visualize and Agents sections are now being loaded with a React component.

- We have to test that every single dashboard is working correctly with and without alerts of that specific section:

- [ ] Visualize
    - [ ] Security Events 
    - [ ] AWS
    - [ ] Integrity Monitoring
    - [ ] Policy Monitoring
    - [ ] System Auditing
    - [ ] Openscap
    - [ ] CIS-CAT
    - [ ] Vulnerabilities
    - [ ] VirusTotal
    - [ ] Osquery
    - [ ] Docker listener
    - [ ] PCI DSS
    - [ ] GDPR
    - [ ] HIPAA
    - [ ] NIST 800-53

- [ ] Agents
    - [ ] Security Events 
    - [ ] AWS
    - [ ] Integrity Monitoring
         - [ ] Syscheck table
         - [ ] Dashboard
    - [ ] Inventory Data
    - [ ] Policy Monitoring
    - [ ] System Auditing
    - [ ] Openscap
    - [ ] CIS-CAT
    - [ ] Vulnerabilities
    - [ ] VirusTotal
    - [ ] Osquery
    - [ ] Docker listener
    - [ ] PCI DSS
    - [ ] GDPR
    - [ ] HIPAA
    - [ ] NIST 800-53
