### ISSUE TITLE
Custom spaces don't works in the 7.5.X app

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#1995]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.11.X   | 7.5.X     | 581 |

**Description**
When we open the Kibana app under a custom space, the app crashes and shows 'too much recursion' errors. All the errors seem to be related to the digest cycle of angular.

**Steps to reproduce**

1. Open the app
2. Select a custom space (not default)
3. Enter in the Wazuh plugin

**Screenshots**
![image](https://user-images.githubusercontent.com/21195730/72143852-c4059580-3397-11ea-8ae6-25667473cc83.png)

**Comment by sentient** [comment]
I see this is planed for 3.12
I wonder how others are using the wazuh-app with limited access permission without custom spaces?
I though custom spaces is required(?) the control access to the app.

**Comment by juankaromo** [comment]
The error is due to a hook inside Kibana, which encodes and decodes the URL every time it changes (**locationChangeStart** event of the AngularJS $rootScope), which caused an infinite loop.

![urldecode](https://user-images.githubusercontent.com/21195730/73925417-508b7100-48ce-11ea-98b7-015ee0d4111a.gif)

https://github.com/elastic/kibana/blob/f421eec40b5a9f31383591e30bef86724afcd2b3/src/legacy/ui/public/chrome/api/sub_url_hooks.js#L40

That's when the AngularJS listeners of our plugin that detect the changes in the filters to apply them didn't stop running, giving rise to infinite cycles of AngularJS digest.

**Comment by juankaromo** [comment]
A custom app has been created for Wazuh 3.11.3 / ELK 7.5.2 that solves this problem
[wazuhapp-3.11.3_7.5.2-spaces.zip](https://github.com/wazuh/wazuh-kibana-app/files/4164370/wazuhapp-3.11.3_7.5.2-spaces.zip)

**Comment by sentient** [comment]
I there any way I can apply a patch to a 3.10.x with 7.5.0 ?
Not sure what has changed, and not sure how I can fix this issue myself of a specific version.

It seems very challenging to keep on following the latest from Elastic and Kibana and Wazuh where it is bug free.

Would be nice to have an LTS, or a process how patches can be applied to a prior build
