### ISSUE TITLE
Map visualization in AWS dashboard not work

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-kibana-app#2004]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.11.x   | 7.x     | xxx |

**Description**
Map visualization in the AWS dashboard not work. This visualization has two problems:

1. Not show all geolocation fields in the index
2. When the map is loaded, it is empty. To show the circles you need to click on the map.

**Additional context**
The error of the empty map is because we have some geolocation fields in the index:
* data.aws.service.action.networkConnectionAction.remoteIpDetails.geoLocation
* GeoLocation.location
* data.aws.service.action.portProbeAction.portProbeDetails.remoteIpDetails.geoLocation

**Comment by jsanchez91** [comment]
I opened this PR to fix the problem with the alerts without `GeoLocation` fields.

**Comment by juankaromo** [comment]
Patched here https://github.com/wazuh/wazuh-kibana-app/commit/dd31bd7a155354bc50fe0af22fca878607c8936a

**Comment by jsanchez91** [comment]
This PR solve it:

**Comment by AlexRuiz7** [comment]
**Port to 4.4:**

- `data.aws.service.action.networkConnectionAction.remoteIpDetails.geoLocation` --> exists in the index template
- `GeoLocation.location` --> does not exist in the index template.
- `data.aws.service.action.portProbeAction.portProbeDetails.remoteIpDetails.geoLocation` --> does not exist in the index template

**Comment by AlexRuiz7** [comment]
Closed by https://github.com/wazuh/wazuh/pull/4459
