### ISSUE TITLE
Missing SearchBar for time filter in Kibana Management>cluster

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#2017]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.11.X   | 7.5.X     | n/a |

**Description**
In the Management>Cluster section the search bar to apply the desired time range is not being displayed.

**Steps to reproduce**

1. Enable the Cluster
2. Go to Management/Cluster
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/21195730/72966250-b9e38e00-3dbe-11ea-83af-b0495519e121.png)

**Comment by t0wb0at** [comment]
Hi, @juankaromo!
Thanks, for reporting my issue, I appreciate it! Please let me know if I can help you to resolve this issue, I'll try to provide any information what I can.

**Comment by juankaromo** [comment]
Solved here https://github.com/wazuh/wazuh-kibana-app/commit/08901dfcbe509f17e4fab26877c8b7dae8a66bff

It will be included in **Wazuh 3.12** release

![image](https://user-images.githubusercontent.com/21195730/73752153-b35efa00-4760-11ea-9523-30e5a02be26c.png)

Many thanks!

**Comment by t0wb0at** [comment]
Thanks a lot, @juankaromo! 
Waiting for the release!
