### ISSUE TITLE
Add remoted and analysisd stats

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#2020]
Hi team,

We need to add the stats of the remoted demons and analysisd to the app. These should go in the Cluster section within Management.

The API calls to obtain the data are these:

```
curl -u foo:bar -k -X GET "https://127.0.0.1:55000/manager/stats/remoted?pretty"
curl -u foo:bar -k -X GET "https://127.0.0.1:55000/manager/stats/analysisd?pretty"

curl -u foo:bar -k -X GET "https://127.0.0.1:55000/cluster/worker-1/stats/remoted?pretty"
curl -u foo:bar -k -X GET "https://127.0.0.1:55000/cluster/worker-1/stats/analysisd?pretty"
```

Regards

**Comment by juankaromo** [comment]
At the moment, we are only displaying the output of this API calls on the new Statistics Management section. 

![image](https://user-images.githubusercontent.com/21195730/73761450-28393080-476f-11ea-9ec6-d3d40c49ed4f.png)


Now we need, to show time-based visualization feeds with the data stored on **wazuh-statistcs** index. @pablotr9

**Comment by jsanchez91** [comment]
**Update**

We improvement the view of the visualizations of `remoted` and `analysisd`

##### Remoted
![image](https://user-images.githubusercontent.com/3064506/89885338-360eb900-dbcb-11ea-93b0-3b58a16de0d8.png)

##### Analysisd
![image](https://user-images.githubusercontent.com/3064506/89885388-445cd500-dbcb-11ea-8163-b5c163801831.png)
