### ISSUE TITLE
Kibana 7.4.2 - Wazuh 3.11.2 Support

### ISSUE THREAD

**Issue by rhysxevans** [wazuh/wazuh-kibana-app#2022]
Hi

Any chance of getting a release of 3.11.2 that will work on Kibana 7.4.2 (Which looks like the next version of OpenDistro will be based on, from some of the commits)?

From what I have gleaned, is you are releasing on the last version of Kibana 6, OpenDistro required Kibana Version and latest Kibana version?

I am looking to align my stack (Currently 7.4.2) with OpenDistro moving forward, but would need to "stop" the Kibana upgrades and upgrade Wazuh separately, until that can happen. Once tracking alongside OpenDistro , I can review the options around migrating to it

Any help is appreciated

Thanks

**Comment by juankaromo** [comment]
Hi @rhysxevans  ,

Unfortunately, we have no support for Kibana 7.4.2 in Wazuh 3.11. The last version of Wazuh with support for 7.4.2 was 3.10.2.

As you well know and have mentioned, our policy of support for ELK consists of each version of Wazuh, giving support to:

- The latest version of 7.X (in this case 7.5.2).
- The latest version of 6.X (in this case 6.8.6) (This will also be discontinued in the future).
- The last version compatible with OpenDistro (in this case 7.3.2).

But don't worry, in case Opendistro releases a version with support for ELK 7.4.2, we will create and release a package for the current version (at this time 3.11.2) to support Opendistro. That is, if hypothetically tomorrow the update of Opendistro would be released, in a few days you would have available a package of the app for 3.11.2-7.4.2.

I hope this helps you and I am sorry for the inconvenience.

Regards,

**Comment by rhysxevans** [comment]
Hi

Ok, thanks for the clarification

Thanks
