### ISSUE TITLE
Windows updates table doesn't appear in the Inventory Data report

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#2024]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.11   | 7.x     | n/a|

**Description**
The new table that was created to show the Windows patches in the inventory data of a Windows agent is not shown when we make a report of this section.

**Steps to reproduce**

1. Go to a Windows agent
2. Click on Inventory Data
3. Make a report

**Screenshots**
![image](https://user-images.githubusercontent.com/21195730/73161750-91280500-40ec-11ea-9b7b-9a3347773e50.png)

**Comment by pablotr9** [comment]
The Windows updates table has been added to the Inventory Data report and merged here https://github.com/wazuh/wazuh-kibana-app/pull/2027
