### ISSUE TITLE
NewApi Review: api-tester.js

### ISSUE THREAD

**Issue by Joanes04** [wazuh/wazuh-kibana-app#2034]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.12   | 7.5     | X |

**Description**

In this issue we are going to adapt the functions that are executed to check the status of the API.

Currently two requests are called from FrontEnd to check the API status: `/api/check-api `and `/api/check-stored-api`. In this issue we will make the necessary changes to make it work with the new API 4.0.

**Steps**

- [x] Update check-api method @Joanes04 
- [x] Update check-stored-api method @Desvelao 

**Branchs**

- [check-api](https://github.com/wazuh/wazuh-kibana-app/tree/NewApi/check-api)
- [check-stored-api](https://github.com/wazuh/wazuh-kibana-app/tree/NewApi/check-stored-api)

**Parent issue**

[Review all API requests (inluded dev-tools autocomplete)](https://github.com/wazuh/wazuh-kibana-app/issues/2001)

**Comment by Joanes04** [comment]
**Check-api method**

We have adapted the check-api method of BackEnd to work with the new API 4.0. 
The main changes we have made:

- The main change is to pass through the new api-interceptor, and not directly a call to the needle:

> Old method

```
let response = await needle(
   'get',
   `${apiAvailable.url}:${apiAvailable.port}/manager/info`,
   {},
   ApiHelper.buildOptionsObject(apiAvailable)
);
```

> New method

```
let responseManagerInfo = await this.apiInterceptor.request(
   'GET',
   `${apiAvailable.url}:${apiAvailable.port}/manager/info`,
   {},
   req.payload.id
);
```

- Now, to check the status of the request, if it has been successful or has an error code, check the **status** field:

> Old method

```
// Check wrong credentials
if (parseInt(response.statusCode) === 401) {
   log('wazuh-api:checkAPI', `Wrong Wazuh API credentials used`);
   return ErrorResponse('Wrong credentials', 3004, 500, reply);
}
```

> New method

```
// Check wrong credentials
if (parseInt(responseManagerInfo.status) === 401) {
   log('wazuh-api:checkAPI', `Wrong Wazuh API credentials used`);
   return ErrorResponse('Wrong credentials', 3004, 500, reply);
}
```

- The request `/cluster/node` has been replaced in the new API 4.0 by `/cluster/local/info`

**Comment by Desvelao** [comment]
**checkStoredAPI**

Changes:

- removed request done with **neddle** by the new **interceptor**

  > Old method 

  ```js
  const response = await needle(
          'get',
          `${api.url}:${api.port}/manager/info`,
          {},
          credInfo
        );
  ```

  > New method

  ```js
  const responseManagerInfo = await this.apiInterceptor.request('get', `${api.url}:${api.port}/manager/info`, {}, id)
  ```

- The status of response come from **status** of response instead statusCode

  > Old method

  **checkStoredApi** didn't check the **statusCode** of the response because was wrap for try/catch block

  > New method

  ```js
  if (responseManagerInfo.status === 200 && responseManagerInfo.data) {
      ....
  }
  ```

- API endpint changes in API 4.0:

  - `/cluster/node` > `/cluster/local/info`
  - `/version` > is a field returned by `/manager/info`

- The response what **checkStoredApi** method returns hide **username** and **password** as well **secret** field (done before the change)

- In a error case, the new API returns the **message** in **detail** field:

  > Old method

  ```js
  throw new Error(message || `${api.url}:${api.port} is unreachable`);
  ```

  > New method 

  ```js
  throw new Error(responseManagerInfo.data.detail || `${api.url}:${api.port} is unreachable`);
  ```

- Removed ApiHelpet.buildOPtions Object what used **needle* requests

**Changes in checkResponseIsDown**

Adapted to response of new interceptor

> Old method

```js
checkResponseIsDown(response) {
    const responseBody = (response || {}).body || {};
    const responseError = responseBody.error || false;

    // Avoid "Error communicating with socket" like errors
    const socketErrorCodes = [1013, 1014, 1017, 1018, 1019];

    const isDown = socketErrorCodes.includes(responseError || 1);

    isDown && log('wazuh-api:makeRequest', 'Wazuh API is online but Wazuh is not ready yet');

    return isDown;
}
```

> New method

```js
checkResponseIsDown(response) {
    if(response.status !== 200){
      // Avoid "Error communicating with socket" like errors
      const socketErrorCodes = [1013, 1014, 1017, 1018, 1019];

      const isDown = socketErrorCodes.includes(response.data.code || 1);
  
      isDown && log('wazuh-api:makeRequest', 'Wazuh API is online but Wazuh is not ready yet');
  
      return isDown;
    }
    return false
}
```

**Comment by Joanes04** [comment]
**UPDATE**

When the cluster mode is disabled, the **check-api** does not work properly.
We detected that in the endpoint of the cluster check: `/cluster/status` when the cluster is enabled the response is:

```
{
  "data": {
    "enabled": "yes",
    "running": "yes"
  }
}
```

However, when the cluster is disabled, the answer is:

```
{
  "code": 3012,
  "dapi_errors": {},
  "detail": "Cluster is not running",
  "status": 500,
  "title": "Wazuh Internal Error",
  "type": "about:blank"
}
```

**Comment by Joanes04** [comment]
**UPDATE**

We have adapted the check-api and check-stored-api operation to work while fixing the issue: 
[API 4.0 Bug in GET /cluster/status](https://github.com/wazuh/wazuh/issues/4574)

The operation that we have left currently, must be changed when the issue is solved, because this adaptation, creates problems with the **check-api** and **check-stored-api** error control.
