### ISSUE TITLE
NewApi Review: agents section

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#2044]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.12   | 7.5     | X |

**Description**
In this issue we are going to replace the old api responses for new API responses in Agents section what use the interceptor. We are going to do it one by one.

**Branch** [NewApi/agents-section](https://github.com/wazuh/wazuh-kibana-app/tree/NewApi/agents-section)

**Parent issue** #2001

**Comment by Desvelao** [comment]
## Changes

- replaced `wzReq` function coming through props from AngularJS by `WzRequest` to do the API request in React components
- adapted the responses to API 4.0
- adapted `wz-table-eui` directive which used DataFactory to new response
- adapted `getPciRequirement`, `getGdprRequirement`, `getHipaaRequirement`, `getNistRequirement`, `getSysCollector` methods of `server/controllers/wazuh-api.js` file to response
-  agents' status is now lowercase and `never_connected` status is converted to `never_connected` in agents table and agent configuration

Route changes:

- `/agents/summary` > `agents/summary/status`
- `/rules/{requirement}` > `rules/requirement/{requirement}`

## Fixed

- Windows command for register agent

> `public/controllers/agent/components/register-agent.js`

old: `-1.msi -OutFile wazuh-agent.msi; .\wazuh-agent.msi /q ADDRESS=`

new: `-1.msi -OutFile wazuh-agent.msi; .\\wazuh-agent.msi /q ADDRESS`

reason: '\\' character is the escape character and didn't render ' \\' in the command `.wazuh-agent.msi`  => `.\wazuh-agent.msi` 

- fixed pagination in AgentsTable

## TODO

- [ ] `rules/mitre` need to be adapted to new API when Core merges it.

**Comment by Joanes04** [comment]
**UPDATE**

- When doing a syscheck scan of an agent, we have had to change the parameters that we send to the new API 4.0:

> Old format

```
await this.apiReq.request('PUT', `/syscheck`, {
   params: {
      list_agents: [this.$scope.agent.id]
   }
});
```

> New format

```
await this.apiReq.request('PUT', `/syscheck`, {
   params: {
      list_agents: this.$scope.agent.id
   }
});
```

- When we are going to **getItems** for an agent in **Intregity Monitoring**, we have had to change the format of the answers:

> Old format

```
const formattedFiles =  (((files || {}).data || {}).data || {}).items.map(this.formatFile);
    this.setState({
      monitoredFiles: formattedFiles,
      totalItems: (((files || {}).data || {}).data || {}).totalItems - 1,
      isProcessing: false,
});
```

> New format

```
const formattedFiles =  (((files || {}).data || {}).data || {}).affected_items.map(this.formatFile);
    this.setState({
      monitoredFiles: formattedFiles,
      totalItems: (((files || {}).data || {}).data || {}).total_affected_items - 1,
      isProcessing: false,
});
```

**Comment by Joanes04** [comment]
**UPDATE**

The entire issue has been completed, including **MITRE**, which has been added to API 4.0 and is working well in our branch.
