### ISSUE TITLE
NewApi Review: Settings section 

### ISSUE THREAD

**Issue by pablotr9** [wazuh/wazuh-kibana-app#2050]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.12   | 7.5     | X |

**Description**

In this issue, we are going to adapt all the API endpoints in Settings section to be fully compatible with the new format of Wazuh API 4.0.

- [x] Settings
    - [x] API
    - [x] Configuration
    - [x] Logs
    - [x] About

**Branches**

**Parent issue**

[Review all API requests (inluded dev-tools autocomplete)](https://github.com/wazuh/wazuh-kibana-app/issues/2001)

**Comment by Joanes04** [comment]
**UPDATE**

There is no endpoint in the setting section that refers to the Wazuh API, so it is fully adapted.
