### ISSUE TITLE
NewApi Review: DevTools section 

### ISSUE THREAD

**Issue by Joanes04** [wazuh/wazuh-kibana-app#2053]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.12   | 7.5     | X |

**Description**

In this issue, we are going to adapt all the API endpoints in DevTools section to be fully compatible with the new format of Wazuh API 4.0.

- [x] DevTools
   - [x] Review / Update requests
   - [x] Update the documentation links of API endpoints
   - [x] Review/Update autocomplete 

**Branches**

[NewApi/Devtools](https://github.com/wazuh/wazuh-kibana-app/tree/NewApi/devtools)

**Parent issue**

[Review all API requests (included dev-tools autocomplete)](https://github.com/wazuh/wazuh-kibana-app/issues/2001)

**Comment by Joanes04** [comment]
**UPDATE**

We have introduced some changes to adapt devtools to the new API:

- In the demo examples with which we started the devtools section, we had to change the status property of the `GET /agents` endpoint since it is now `active` and not `Active`:

> Old method

```
const demoStr =
   'GET /agents?status=Active\n\n#Example comment\nGET /manager/info\n\nGET /syscollector/000/packages?search=ssh\n' +
   JSON.stringify({ limit: 5 }, null, 2);
```

> New method

```
const demoStr =
   'GET /agents?status=active\n\n#Example comment\nGET /manager/info\n\nGET /syscollector/000/packages?search=ssh\n' +
   JSON.stringify({ limit: 5 }, null, 2);
```

- Currently, in API requests there was no separation between **params** and **body**. With the new API, we have to differentiate the query parameters from the body.

> Old method

```
const output = await this.apiReq.request(method, path, JSONraw);
```

> New method

```
const output = await this.apiReq.request(method, path, {
   params: params,
   body: body,
   devTools: true,
});
```

**Comment by Joanes04** [comment]
**UPDATE**

We are going to need to update the documentation, in this [section](https://documentation.wazuh.com/3.11/user-manual/kibana-app/features/dev-tools.html), because now if we are going to differentiate between using **in-line parameters** and **JSON-formatted parameters**.

- With the new API, the **in-line parameters** will be those sent in the **query**, for example: 

```
GET /syscollector/000/packages?limit=5
```

- The **JSON-formatted** parameters will be sent in the request via the **body**, for example:

```
POST /agents
{
  "ip": "10.0.10.11",
  "name": "NewHost_2"
}
```

**Comment by Desvelao** [comment]
Created a script to generate a file with the information about Wazuh API 4.0 mapped for use in Wazuh app.

Source location: `scripts/generate-api-4.0-info` directory.

Content:
  - a Javascript script
  - a sh script
  - a documentation file with links to the endpoint's documentation (it could need to be updated)
  - NPM script `generate-api-4.0-info`:
  To launch it, it is required a running Wazuh API instance where get the information throuth the Swagger json file. This runs the javascript script, replaces the file used in Wazuh app by the generated one, and removes the temporal directory.
  Run: `WAZUH_API_URL="<api_url>" generate:api-4.0-info`
  Example: `WAZUH_API_URL="https://172.16.1.2:55000" generate:api-4.0-info`

**Comment by Desvelao** [comment]
Updated API endpoints to 4.0

**Comment by Desvelao** [comment]
Added basic support for suggestions in:
- `query` parameters:
![dev-tools-request-query-suggestions](https://user-images.githubusercontent.com/34042064/94571771-9982a200-0270-11eb-963b-2568084e8012.gif)
- `body` parameters:
![dev-tools-request-body-suggestions](https://user-images.githubusercontent.com/34042064/94571840-aa331800-0270-11eb-89a0-f34a85d00b1f.gif)

**Comment by Desvelao** [comment]
Update:
- Request body suggestion now expand the property if this is of `type`: `object`
![dev-tools-request-body-suggestions-expand-object](https://user-images.githubusercontent.com/34042064/94910514-1a29e400-04a5-11eb-9577-d8063415be88.gif)
- Added a button to open the documentation of API endpoint. This button is shown if the input request matches an existing API endpoint
![image](https://user-images.githubusercontent.com/34042064/94911477-7b05ec00-04a6-11eb-9196-b157e5dd5478.png)

The API endpoints, that are new in 4.0, need to be updated the documentation link.
