### ISSUE TITLE
NewApi Review: Monitoring 

### ISSUE THREAD

**Issue by pablotr9** [wazuh/wazuh-kibana-app#2055]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.12   | 7.5     | X |

**Description**

In this issue, we are going to adapt all the API endpoints in the Monitoring file to be fully compatible with the new format of Wazuh API 4.0.

**TODO**
- [x] Check that wazuh-monitoring indices are being populated with correct data.

**Branches**

[NewApi/monitoring](https://github.com/wazuh/wazuh-kibana-app/tree/NewApi/monitoring)

**Parent issue**

[Review all API requests (inluded dev-tools autocomplete)](https://github.com/wazuh/wazuh-kibana-app/issues/2001)

**Comment by pablotr9** [comment]
**Update**
API endpoints have been updated. Do not merge this branch until we assure that the `wazuh-monitoring` indices are being populated correctly.

**Comment by Joanes04** [comment]
**UPDATE**

We have adapted the function **checkAndSaveStatus** for the new API 4.0:

- In the `/server/lib/api-helper.js` file:

> Old version

```
const response = await needle(
   'get',
   `${getPath(api)}/agents`,
   payload,
   options
);
```

> New version

```
const response = await this.apiInterceptor.request(
   'GET',
   `${getPath(api)}/agents`,
   { params: payload },
   { idHost: api.id }
);
```

- In the `/server/monitoring.js` file:

> Old version

```
const clusterName =
        (((isCluster || {}).body || {}).data || {}).enabled === 'yes'
          ? await needle('get', `${getPath(api)}/cluster/node`, {}, options)
          : false;
```

> New version

```
const clusterName =
      (((isCluster || {}).data || {}).data || {}).enabled === 'yes'
      ? await this.apiInterceptor.request('GET', `${getPath(api)}/cluster/local/info`, {},  { idHost: api.id})
      : false;
```
