### ISSUE TITLE
Cant See Wazuh App on Kibana

### ISSUE THREAD

**Issue by kisienya** [wazuh/wazuh-kibana-app#2067]
Hi,
Really appreciate this project.
I have installed the following packages:

Wazuh version 3.11.3
Elasticsearch version 7.5.2
Kibana Version 7.5.2
wazuhapp Version 3.11.3_7.5.2

**Description**
I cannot find wazuhapp on Kibana web interface. I see no errors on logs....What am I doing wrong?

**Comment by victorst79** [comment]
Hi @kisienya 
These are the installation steps:

- With sudo:

```
sudo -u kibana /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.12.0_7.5.2.zip
```

- Without sudo:

```
su -c '/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.12.0_7.5.2.zip' kibana
```

Restart Kibana

- Systemd:

```
systemctl restart kibana
```

- SysV Init:

```
service kibana restart
```
Have you followed them correctly?, In case the error persists, could you please share the kibana logs? You can use the following command: 
```
journalctl | grep kibana
```

Regards,
Victor Santaella

**Comment by kisienya** [comment]
Hi thanks for the quick response. 

See the logs from kibana server restart
Feb 05 22:56:57  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:56:57Z","tags":["info","plugins-system"],"pid":13062,"message":"Setting up [15] plugins: [security,licensing,code,timelion,features,spaces,translations,uiActions,newsfeed,inspector,embeddable,advancedUiActions,expressions,eui_utils,data]"}
Feb 05 22:56:57  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:56:57Z","tags":["info","plugins","security"],"pid":13062,"message":"Setting up plugin"}
Feb 05 22:56:57  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:56:57Z","tags":["warning","plugins","security","config"],"pid":13062,"message":"Generating a random key for xpack.security.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.security.encryptionKey in kibana.yml"}
Feb 05 22:56:57  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:56:57Z","tags":["warning","plugins","security","config"],"pid":13062,"message":"Session cookies will be transmitted over insecure connections. This is not recommended."}
Feb 05 22:56:57  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:56:57Z","tags":["info","plugins","licensing"],"pid":13062,"message":"Setting up plugin"}
Feb 05 22:56:57  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:56:57Z","tags":["info","plugins","code"],"pid":13062,"message":"Setting up plugin"}
Feb 05 22:56:57  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:56:57Z","tags":["info","plugins","timelion"],"pid":13062,"message":"Setting up plugin"}
Feb 05 22:56:57  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:56:57Z","tags":["info","plugins","features"],"pid":13062,"message":"Setting up plugin"}
Feb 05 22:56:57  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:56:57Z","tags":["info","plugins","spaces"],"pid":13062,"message":"Setting up plugin"}
Feb 05 22:56:57  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:56:57Z","tags":["info","plugins","translations"],"pid":13062,"message":"Setting up plugin"}
Feb 05 22:56:57  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:56:57Z","tags":["info","plugins","data"],"pid":13062,"message":"Setting up plugin"}
Feb 05 22:57:05  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:05Z","tags":["warning","legacy-plugins"],"pid":13062,"path":"/usr/share/kibana/src/legacy/core_plugins/visualizations","message":"Skipping non-plugin directory at /usr/share/kibana/src/legacy/core_plugins/visualizations"}
Feb 05 22:57:06  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:06Z","tags":["info","plugins","licensing"],"pid":13062,"message":"Imported changed license information from Elasticsearch for the [data] cluster: type: basic | status: active"}
Feb 05 22:57:07  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:07Z","tags":["info","plugins-system"],"pid":13062,"message":"Starting [8] plugins: [security,licensing,code,timelion,features,spaces,translations,data]"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:kibana@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:elasticsearch@7.5.2","info"],"pid":13062,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:xpack_main@7.5.2","info"],"pid":13062,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:graph@7.5.2","info"],"pid":13062,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:monitoring@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:spaces@7.5.2","info"],"pid":13062,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:security@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:searchprofiler@7.5.2","info"],"pid":13062,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:ml@7.5.2","info"],"pid":13062,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:tilemap@7.5.2","info"],"pid":13062,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:watcher@7.5.2","info"],"pid":13062,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:grokdebugger@7.5.2","info"],"pid":13062,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:dashboard_mode@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:logstash@7.5.2","info"],"pid":13062,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:beats_management@7.5.2","info"],"pid":13062,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:apm_oss@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:apm@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:interpreter@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:expressions@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:maps@7.5.2","info"],"pid":13062,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:canvas@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:license_management@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:cloud@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:index_management@7.5.2","info"],"pid":13062,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:console@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:console_extensions@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:index_lifecycle_management@7.5.2","info"],"pid":13062,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:kuery_autocomplete@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:metrics@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:infra@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["info","task_manager"],"pid":13062,"message":"Initialising Task Manager with UUID: af6a8787-4e80-4688-9ec3-d74fbebe52e4"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:task_manager@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:rollup@7.5.2","info"],"pid":13062,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["status","plugin:transform@7.5.2","info"],"pid":13062,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:11  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:11Z","tags":["info","siem"],"pid":13062,"message":"Plugin initializing"}
Feb 05 22:57:12  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:12Z","tags":["info","siem"],"pid":13062,"message":"Plugin done initializing"}
Feb 05 22:57:12  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:12Z","tags":["status","plugin:siem@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:12  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:12Z","tags":["status","plugin:remote_clusters@7.5.2","info"],"pid":13062,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:12  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:12Z","tags":["status","plugin:cross_cluster_replication@7.5.2","info"],"pid":13062,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:12  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:12Z","tags":["status","plugin:upgrade_assistant@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:12  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:12Z","tags":["status","plugin:uptime@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:12  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:12Z","tags":["status","plugin:oss_telemetry@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:12  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:12Z","tags":["status","plugin:file_upload@7.5.2","info"],"pid":13062,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:12  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:12Z","tags":["warning","encrypted_saved_objects"],"pid":13062,"message":"Generating a random key for xpack.encrypted_saved_objects.encryptionKey. To be able to decrypt encrypted saved objects attributes after restart, please set xpack.encrypted_saved_objects.encryptionKey in kibana.yml"}
Feb 05 22:57:12  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:12Z","tags":["status","plugin:encrypted_saved_objects@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:12  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:12Z","tags":["status","plugin:data@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:12  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:12Z","tags":["status","plugin:lens@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:12  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:12Z","tags":["status","plugin:snapshot_restore@7.5.2","info"],"pid":13062,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:12  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:12Z","tags":["status","plugin:kibana_react@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:12  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:12Z","tags":["status","plugin:navigation@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:12  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:12Z","tags":["status","plugin:region_map@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:12  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:12Z","tags":["status","plugin:telemetry@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:12  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:12Z","tags":["status","plugin:timelion@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:12  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:12Z","tags":["status","plugin:ui_metric@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:12  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:12Z","tags":["status","plugin:markdown_vis@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:12  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:12Z","tags":["status","plugin:metric_vis@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:12  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:12Z","tags":["status","plugin:table_vis@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:12  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:12Z","tags":["status","plugin:tagcloud@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:12  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:12Z","tags":["status","plugin:vega@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:12  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:12Z","tags":["status","plugin:elasticsearch@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
Feb 05 22:57:13  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:13Z","tags":["license","info","xpack"],"pid":13062,"message":"Imported license information from Elasticsearch for the [data] cluster: mode: basic | status: active"}
Feb 05 22:57:13  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:13Z","tags":["status","plugin:xpack_main@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
Feb 05 22:57:13  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:13Z","tags":["status","plugin:graph@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
Feb 05 22:57:13  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:13Z","tags":["status","plugin:searchprofiler@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
Feb 05 22:57:13  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:13Z","tags":["status","plugin:ml@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
Feb 05 22:57:13  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:13Z","tags":["status","plugin:tilemap@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
Feb 05 22:57:13  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:13Z","tags":["status","plugin:watcher@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
Feb 05 22:57:13  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:13Z","tags":["status","plugin:grokdebugger@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
Feb 05 22:57:13  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:13Z","tags":["status","plugin:logstash@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
Feb 05 22:57:13  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:13Z","tags":["status","plugin:beats_management@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
Feb 05 22:57:13  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:13Z","tags":["status","plugin:index_management@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
Feb 05 22:57:13  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:13Z","tags":["status","plugin:index_lifecycle_management@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
Feb 05 22:57:13  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:13Z","tags":["status","plugin:rollup@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
Feb 05 22:57:13  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:13Z","tags":["status","plugin:transform@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
Feb 05 22:57:13  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:13Z","tags":["status","plugin:remote_clusters@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
Feb 05 22:57:13  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:13Z","tags":["status","plugin:cross_cluster_replication@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
Feb 05 22:57:13  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:13Z","tags":["status","plugin:file_upload@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
Feb 05 22:57:13  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:13Z","tags":["status","plugin:snapshot_restore@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
Feb 05 22:57:13  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:13Z","tags":["info","monitoring","kibana-monitoring"],"pid":13062,"message":"Starting monitoring stats collection"}
Feb 05 22:57:13  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:13Z","tags":["status","plugin:maps@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
Feb 05 22:57:13  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:13Z","tags":["status","plugin:spaces@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
Feb 05 22:57:14  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:14Z","tags":["reporting","warning"],"pid":13062,"message":"Generating a random key for xpack.reporting.encryptionKey. To prevent pending reports from failing on restart, please set xpack.reporting.encryptionKey in kibana.yml"}
Feb 05 22:57:14  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:14Z","tags":["status","plugin:reporting@7.5.2","info"],"pid":13062,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Feb 05 22:57:14  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:14Z","tags":["listening","info"],"pid":13062,"message":"Server running at http://0.0.0.0:3333"}
Feb 05 22:57:15  kibana[13062]: {"type":"log","@timestamp":"2020-02-05T11:57:15Z","tags":["info","http","server","Kibana"],"pid":13062,"message":"http server running at http://0.0.0.0:3333"}

**Comment by victorst79** [comment]
Hi @kisienya 
Apparently I don't see any error in the logs. 
Could you please reinstall the application and share the output with me after finishing?
Use this small reference extracted from the documentation to remove the application and be able to reinstall it. 

**To uninstall Elasticsearch:**
```
apt-get remove elasticsearch
```

There are files marked as configuration and data files. Due to this designation, the package manager doesn’t remove those files from the filesystem. 
The complete files removal action is a user responsibility. It can be done by removing the folder `/var/lib/elasticsearch` and `/etc/elasticsearch`.

**To uninstall Kibana:**
```
apt-get remove kibana
```
As in the previous case, the complete files removal can be done by removing the folder `/var/lib/kibana` and `/etc/kibana`.

[Source](https://documentation.wazuh.com/3.11/installation-guide/installing-elastic-stack/elastic_server_deb.html#uninstall)

**Comment by kisienya** [comment]
Hi Victor,

I managed to install wazuh-app successfully
This link does not work: https://packages.wazuh.com/wazuhapp/wazuhapp-3.12.0_7.5.2.zip
This one does: https://packages.wazuh.com/wazuhapp/wazuhapp-3.11.3_7.5.2.zip

**Comment by kisienya** [comment]
@victorst79 thanks for your help
