### ISSUE TITLE
New Management > Configuration theme error

### ISSUE THREAD

**Issue by Joanes04** [wazuh/wazuh-kibana-app#2068]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.12   | 7.5     | n/a|

**Description**
When you use JSON viewer in management > configuration, the following error is caused:

![image](https://user-images.githubusercontent.com/9945959/73865613-89b1db80-4811-11ea-9f31-3232ae9c0265.png)

**Steps to reproduce**

1. Go to 'Management -> Configuration'
2. Click on any configuration
3. Click on JSON viewer:
![image](https://user-images.githubusercontent.com/9945959/73865810-dbf2fc80-4811-11ea-8439-8b803212a217.png)
4. See error in 'console'

**Comment by Desvelao** [comment]
I tried editors in other sections as Groups and Ruleset, and these have the same error.

Groups section
![Anotación 2020-02-06 083712](https://user-images.githubusercontent.com/34042064/73915616-0ac5ad00-48bc-11ea-9a07-d9a5b96209b6.jpg)

Ruleset/Rules
![Anotación 2020-02-06 083755](https://user-images.githubusercontent.com/34042064/73915642-16b16f00-48bc-11ea-81e9-257dee4a1827.jpg)

**Comment by Desvelao** [comment]
If **EuiCodeEditor** React component has as prop `theme='github'`, **couldn't load module ace/theme/ or it didn't call define** error disapears. It is required import this in CodeEditor definition file to set theme as github

```js
import 'brace/theme/github';
```

It occurs a strange case with `Uncaught SyntaxError: Unexpected token '<'` error. With theme as github setted, the first time you open the editor, the error is throwed, if you leave and go back to code editor, the error isn't showed again.

![Anotación 2020-02-06 084339](https://user-images.githubusercontent.com/34042064/73917142-1d8db100-48bf-11ea-9789-a15569ebb767.jpg)

![Anotación 2020-02-06 084608](https://user-images.githubusercontent.com/34042064/73917335-78bfa380-48bf-11ea-8153-0c2edec09906.jpg)

This error come from:
- **http:/KIBANA_SERVER_IP:5601/app/snippets/xml.js** for`mode='xml'` in EuiCodeEditor
- **http:/KIBANA_SERVER_IP:5601/app/snippets/json.js** for`mode='json'` in EuiCodeEditor

**Comment by juankaromo** [comment]
It seems that is a Kibana bug https://github.com/elastic/kibana/issues/49964

**Comment by juankaromo** [comment]
I close the issue, this will be fixed in the next versions of Kibana. We don't have to do anything.

Regards,
