### ISSUE TITLE
Management button keeps selected when redirecting to Agents section

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-kibana-app#2078]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.11.3   | 7.5.2    | 0584 |

**Description**

Management button keeps selected when redirecting to Agents section.

**Steps to reproduce**

1. Go to 'Management > Groups'
2. Click on any group.
3. Check the currently selected button in the upper navbar.
4. Click on any agent belonging to the selected group. The selected button does not change.

**Screenshots**
![peek](https://user-images.githubusercontent.com/10210567/74337362-71593800-4da0-11ea-8eaf-856810d23f33.gif)

Cheers

**Comment by juankaromo** [comment]
Solved in 3.13 with the new navigation and main menu design. 

Regards,
