### ISSUE TITLE
Unable to view any agent events, kibana app keeps going back to starting page

### ISSUE THREAD

**Issue by djmgit** [wazuh/wazuh-kibana-app#2081]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.11.3   | 7.5.2     | 444 |

**Description**
Kibana app keeps getting reloaded, ie, the first page (where it does all the checks) keeps coming up.
Its super slow. Whenever the security events for a particular agent is clicked on, the app hangs and goes back to the wazuh api hosts listing page. Some times even on clicking agents it the app goes back to the first page.

**Steps to reproduce**

1. Open wazuh app
2. Click on agents
3. Select an agent
4. Select security events or integrity  check events.

At the same time there are the following errors in the console:

![wazuh_console](https://user-images.githubusercontent.com/16368427/74539908-e1b0b680-4f64-11ea-97b4-4cd3b6bbaae9.png)

The wazuh api is pingable from the kibana host, and all the checks are passing on the first loading page. 
However I am not able to view any agent event.
It shows ```Fetching data``` then goes back to wither the first page or shows list of wazuh api hosts.

**Comment by Joanes04** [comment]
Hi @djmgit ,

From what you're telling me, there seems to be an infinite loop in the app's load cycles. This is a known bug within a custom space in the Wazuh apps for 7.5.x, are you using them?

If so, we've created an app fixing this for 3.11.3-7.5.2. Can you test it and let us know if this keeps happening?

[wazuhapp-3.11.3_7.5.2-spaces.zip](https://github.com/wazuh/wazuh-kibana-app/files/4164411/wazuhapp-3.11.3_7.5.2-spaces.zip)

Tell me the results,
Regards,

**Comment by djmgit** [comment]
@Joanes04 hey, thanks a lot for the quick reply.

Yeah, it seems to be going into infinite loop, and yes I am using custom namespace.
I will use the app you shared and get back to you.

**Comment by djmgit** [comment]
@Joanes04 
The app is working, visualizations are working now.

Thanks a lot, will get back if there are further issues.

**Comment by Joanes04** [comment]
Thanks to you @djmgit . I close this issue. Any other questions or problems, don't hesitate to open another ticket.

Regards,
Alberto Andújar
