### ISSUE TITLE
Vulnerability detector problem with debian alerts

### ISSUE THREAD

**Issue by grg121** [wazuh/wazuh-kibana-app#2082]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.11.2  | 7.5.1     | 444 |

**Description**
We've detected that the vulnerability detector dashboard is not showing some Debian (buster) alerts while they exit and can be consulted in explorer.  

![ss1](https://user-images.githubusercontent.com/15269938/74563889-1412e180-4f6e-11ea-9ce0-f37c4ff56b3d.png)

We've seen that the `data.vulnerability.severity` filed appears empty for those alerts and we think that maybe this could be the problem. It is possible that the Debian oval used by VD is not generating any severity level feed for the alert and, for this reason, Kibana is not showing them.

We should discuss if modifying such a dashboard while vulnerability detector problem with `data.vulnerability.severity` is fixed.

![ss2](https://user-images.githubusercontent.com/15269938/74564075-74a21e80-4f6e-11ea-9ae6-38ff5a83c6e1.png)

**Steps to reproduce**

1. Bring up an EK environment with wazuh-docker v3.11.2_7.5.1 
2. Register a Debian buster agent created with the [cicd-team vagrantfile](https://github.com/wazuh/wazuh-tools/blob/master/vagrant/cicd_team/Vagrantfile)
3. Manager conf:
```
<vulnerability-detector>
    <enabled>yes</enabled>
    <interval>50s</interval>
    <ignore_time>10m</ignore_time>

    <run_on_start>yes</run_on_start>
    <provider name="canonical">
      <enabled>no</enabled>

      <os>precise</os>
      <os>trusty</os>
      <os>xenial</os>
      <os>bionic</os>
      <update_interval>1h</update_interval>
    </provider>
    <provider name="debian">
      <enabled>yes</enabled>
      <os>wheezy</os>
      <os>stretch</os>
      <os>jessie</os>
      <os>buster</os>
      <update_interval>1h</update_interval>
    </provider>
    <provider name="redhat">
      <enabled>no</enabled>
      <update_from_year>2010</update_from_year>
      <update_interval>1h</update_interval>
    </provider>
    <provider name="nvd">
      <enabled>no</enabled>
      <update_from_year>2010</update_from_year>
      <update_interval>1h</update_interval>
    </provider>
  </vulnerability-detector>
```
4. Agent conf:
```
  <wodle name="syscollector">
    <disabled>no</disabled>
    <interval>1h</interval>
    <scan_on_start>yes</scan_on_start>
    <hardware>yes</hardware>
    <os>yes</os>
    <network>yes</network>
    <packages>yes</packages>
    <ports all="no">yes</ports>
    <processes>yes</processes>
  </wodle>
```
5. Uninstall `openssl` and reinstall it 
6. Restart the agent to force a syscollector scan.
7. Check kibana dashboard.

Best regards!

**Comment by juankaromo** [comment]
Hi! This issue was solved in 3.13.0,

Regards
