### ISSUE TITLE
Wazuh Kibana App overwriting custom field formatting

### ISSUE THREAD

**Issue by rhysxevans** [wazuh/wazuh-kibana-app#2086]
| Wazuh | Elastic |
| ----- | ------- | 
| 3.11.3  | 7.4.2     |

**Description**
Wazuh keeps overwriting any index formatting put in place

**Steps to reproduce**

1. Go to Index Patterns
2. Click on Wazuh-alerts-3.x-*
3. Select a number field 
4. Set the field format to "Bytes"  and save
5. Go to discover confirm change
6. Open Wazuh Kibana App
7. View index pattern format now for number field changed  (this should have reverted to blank (default)

**Screenshots**

This is a bad field to select but for illustration
![image](https://user-images.githubusercontent.com/18271636/74777029-9bbf5f80-5290-11ea-8ceb-a54ab52d203f.png)

There seems to be some of this going on in elastic-wrapper.js
```js
      // Updating known fields
      const data = await this.elasticRequest.callWithInternalUser('update', {
        index: this.WZ_KIBANA_INDEX,
        type: '_doc',
        id: id.includes('index-pattern:') ? id : 'index-pattern:' + id,
        body: {
          doc: {
            type: 'index-pattern',
            'index-pattern': {
              timeFieldName: 'timestamp',
              fields: currentFieldsString,
              fieldFormatMap: `{
                  "data.virustotal.permalink":{"id":"url"},
                  "data.vulnerability.reference":{"id":"url"},
                  "data.url":{"id":"url"}
                }`,
              sourceFilters: '[{"value":"@timestamp"}]'
            }
          }
        }
      });
```

Any way to get our changes not to be overwritten, or at least limit the changes to specific fields or have the ability to set specific field to not excluded ?

Any help is appreciated

**Comment by jsanchez91** [comment]
Hi @rhysxevans,
This is expected behavior because if we don't do this check it is possible to lose data in some visualizations.

If you want to make this change permanent, add this to the "elastic-wrapper.js".
An example using the "GeoLocation.area_code" field:

```js
// Updating known fields
const data = await this.elasticRequest.callWithInternalUser('update', {
  index: this.WZ_KIBANA_INDEX,
  type: '_doc',
  id: id.includes('index-pattern:') ? id : 'index-pattern:' + id,
  body: {
    doc: {
      type: 'index-pattern',
      'index-pattern': {
        timeFieldName: 'timestamp',
        fields: currentFieldsString,
        fieldFormatMap: `{
            "data.virustotal.permalink":{"id":"url"},
            "data.vulnerability.reference":{"id":"url"},
            "data.url":{"id":"url"},
            "GeoLocation.area_code":{"id":"bytes"} // The new format
          }`,
        sourceFilters: '[{"value":"@timestamp"}]'
      }
    }
  }
});
```

Then restart the Kibana service to apply the changes.
```
systemctl restart kibana
```

I hope it helps. Please, don't hesitate to ask again if you have more doubts
Best regards,
Jose.

**Comment by rhysxevans** [comment]
Hi

Thanks, for the info

Thanks
