### ISSUE TITLE
Move Wazuh app configuration file to optimize folder

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#2087]
Hi team,

After the migration of the APIs configured in the app from the `.wazuh` index to the app configuration file `wazuh.yml` there was a problem when updating the app. 

Because of how Kibana manages the plugins, to make an upgrade it is necessary to delete the plugin and reinstall the new version. This causes that the configuration file (that is inside the path of the plugin) is lost and is restored by the file that comes included in the new version. So far this does not seem to have been a problem, but with the new API management, this problem becomes more important as the custom configured APIs are lost when upgrading.

**Upgrade Scenario from 3.10.**
Here there is no problem because the .wazuh index still existed and there is a procedure when initializing the app where the migration of the data from the index to the configuration file is done.

**Upgrade Scenario from 3.11.X to 3.11.y**
This scenario is the most conflictive because there is no migration and that is where the problem occurs. The solution is to specify in the upgrade guide of the Wazuh documentation that a manual backup of the configuration file `wazuh.yml` must be done, update the plugin, and then restore the saved file. Within versions 3.11.X no changes have been made to the file, so no settings have been added or removed that could break this backup.

**Future scenarios and proposed solution**
It is proposed to move the wazuh.yml file to the `/usr/share/kibana/optimize` directory, which is not removed when the plugin is updated. Before a new installation, the existence of this file will be checked. If it does not exist, it will be created with the current logic. If it already exists, no changes will be made.

In addition, a modification of the structure of this directory will be made, in order to have all the resources of Wazuh in the same path.

That's why the directory is going to take the following distribution:

```
/usr/share/kibana/optimize
└── wazuh/
    ├── logs/
    |    ├── wazuhapp.log
    |    └── wazuhapp-plain.log
    ├── downloads/
    |    └── reports/
    └── config/
         └── wazuh.yml
```

Regards,

**Comment by pablotr9** [comment]
**Update**
Working on this branch: https://github.com/wazuh/wazuh-kibana-app/tree/3.12-7.6-optimize-wazuh-directory

As mentioned in the issue, the ../optimize/ folder has been restructured with this distribution:
```
/usr/share/kibana/optimize
└── wazuh/
    ├── logs/
    |    ├── wazuhapp.log
    |    └── wazuhapp-plain.log
    ├── downloads/
    |    └── reports/
    └── config/
         └── wazuh.yml
```

- [ ] Fresh installation 
   - [ ] Check that logs are stored in the `/usr/share/kibana/optimize/wazuh/logs/` folder
   - [ ] Check that reports are stored in the `/usr/share/kibana/optimize/wazuh/downloads/reports/` folder
   - [ ] Check that the `wazuh.yml` is created with the default content if it not exists.
- [ ] Upgrade from an older version to a newer version (in this case from 3.10.2 to 3.12.0)
   - [ ] Check that the Wazuh entries are migrated from the old .wazuh index to the wazuh.yml ( `/usr/share/kibana/optimize/wazuh/config/wazuh.yml` 
   - [ ] If the wazuh.yml already exists, maintain its content

**Comment by juankaromo** [comment]
The modification of the upgrade to 3.12 guide in Wazuh Docs must also be taken into account. Ping @pablotr9

**Comment by juankaromo** [comment]
Docs PR https://github.com/wazuh/wazuh-documentation/pull/2274
