### ISSUE TITLE
Not showing Wazuh's server alerts on the boards

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#2095]
Hi team,

In some contexts like Wazuh Cloud it is useless to show alerts from Wazuh's own servers on the dashboards. E.g:

![image](https://user-images.githubusercontent.com/21195730/75231840-75c91c00-57b6-11ea-9ebc-cf512c18440f.png)

We will have to create a new configuration to set the possibility of showing or not these alerts in the dashboards. The new configuration parameter will be placed in the `wazuh.yml` configuration file  with the following name:

`visualize.serverAlerts`

Regards,

**Comment by jsanchez91** [comment]
We add a new option to wazuh.yml: "HideManager" by default is true. 

Now the alerts of the manager (agent.id:000) not shown in any visualization or in Discover of the WazuhUI.

It was added with this PR: https://github.com/wazuh/wazuh-kibana-app/pull/2102
