### ISSUE TITLE
Automate connection from Wazuh App to the API

### ISSUE THREAD

**Issue by toniblyx** [wazuh/wazuh-kibana-app#21]
Hi guys,
I'm wondering if there is any way to perform step 4 [here](https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/connect_wazuh_app.html) from the command line.

I'm writing an AWS CloudFormation template to automate deployment of ELK, Wazuh and other security tools and I want to automate that step as well. 
Thanks in advance!

**Comment by snaow** [comment]
Hi @toniblyx,

Yes we have a way. Wazuh App has internally two APIs (wazuh-elastic, wazuh-api).
We could use the second one to push a new manager credentials entry.

> API Endpoint to perform the request: /api/wazuh-api/settings
> Method: PUT
> headers: kbn-version: "5.4.0"
> Content-Type: "application/json"
> payload:

> {
>   "user": "test",
>   "password": "pwEncodedInBase64",
>   "url": "http://wazuh_restful_api_ip",
>   "port": "55000",
>   "manager": "wazuh-manager-hostname",
>   "insecure": "true",
>   "active": true,
>   "extensions": {
>     "oscap": true,
>     "audit": true,
>     "pci": true
>   }
> }

A cURL example:

`curl -X PUT -H 'kbn-version: 5.4.0' -H "Content-Type: application/json" --data '{"user": "test","password": "pwEncodedInBase64","url": "http://wazuh_restful_api_url","port": "55000","manager": "miManager","insecure": "true","active": true,"extensions": {"oscap": true, "audit": true, "pci": true}}' http://kibana_ip_address:5601/api/wazuh-api/settings`

Expected output:

> {
>   "statusCode": 200,
>   "message": "ok",
>   "response": {
>     "_index": ".kibana",
>     "_type": "wazuh-configuration",
>     "_id": "AVwSNk_gPNYxNZoXSRJQ",
>     "_version": 1,
>     "result": "created",
>     "forced_refresh": true,
>     "_shards": {
>       "total": 1,
>       "successful": 1,
>       "failed": 0
>     },
>     "created": true
>   }
> }

Let us know if it does the trick for you.

Thanks,
Pedro.

**Comment by toniblyx** [comment]
That's awesome @snaow, I'll try it. FYI: I'm currently using two layers and two instances in a VPC, public subnet with wazuh server + kibana and another instance in a private subnet with ElasticSearch + Logstash. I plan to make that template public, hopefully soon. Thanks guys!

**Comment by snaow** [comment]
Whoa @toniblyx ! It will be great! Please ask us anything you need for the template creations, and thanks for planning in contributing back, we really appreciate.

Best,
Pedro.

**Comment by toniblyx** [comment]
Hi Pedro, I'm trying this code to add a manager from a shell script and it doesn't work, I always get "Authentication failed":

```
LOCAL_IPV4=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
KIBANA_SERVER=$LOCAL_IPV4
WAZUH_API_USER=wazuh
WAZUH_API_PASSWORD=Temp01
WAZUH_API_PASSWORD_BASE64=$(echo $WAZUH_API_PASSWORD | base64)
WAZUH_API_SERVER=localhost
WAZUH_API_PORT=55000
WAZUH_INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)

cd /var/ossec/api/configuration/auth
echo $WAZUH_API_PASSWORD | node htpasswd -ci user $WAZUH_API_USER
systemctl restart wazuh-api

# Connect the Wazuh App with the API
curl -X PUT -H 'kbn-version: 5.4.0' -H "Content-Type: application/json" \
  --data '{"user": "'$WAZUH_API_USER'","password": "'$WAZUH_API_PASSWORD_BASE64'",
  "url": "http://'$WAZUH_API_SERVER'","port": "'$WAZUH_API_PORT'","manager": "'$WAZUH_INSTANCE_ID'",
  "insecure": "true","active": true,"extensions": {"oscap": true, "audit": true,
  "pci": true}}' http://$KIBANA_SERVER:5601/api/wazuh-api/settings
```
If I add same values manually through Kibana web interface it works good. I think it is something wrong in the way I'm adding the base64 encoded password. Any idea?

**Comment by toniblyx** [comment]
ok, I got it fixed. I set Manager as $WAZUH_INSTANCE_ID, and I figured out that has to be the hostname, not any other ID (I wanted to use the EC2 instance ID because it is an unique value, hostname it is not).
So using 
`WAZUH_INSTANCE_ID=$(hostname)`
it works.
