### ISSUE TITLE
Avoid creating the wazuh-monitoring index pattern if it is disabled

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#2100]
Hi team,

When a user has disabled the wazuh-monitoring index from the Wazuh WUI settings (`wazuh.monitoring.enabled: false`) the creation of the index is omitted in the initialization of the app.

However, the index-pattern (`wazuh-monitoring-3.x-*`) is always created when the app is started, whether the setting is disabled or not.

Currently, if we avoid the creation of the index-pattern through the same setting as with the index, the app fails in some sections where this index is consulted (dashboards for example).

We must study the possibility of working with the app without this index-pattern when the user does not want to create it.

Regards.

**Comment by Joanes04** [comment]
**Update**

We have added the control to not create the monitoring index pattern, if the option `wazuh.monitoring.enabled` is equal to false.

Now if the option is disabled, when restarting kibana the index pattern of wazuh-monitoring is not created, and we have checked that the application continues working normally.
