### ISSUE TITLE
RBAC: Adapt to SearchGuard

### ISSUE THREAD

**Issue by Joanes04** [wazuh/wazuh-kibana-app#2105]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.12   | 7.6     | X |

**Description**

In this issue we will detail the changes needed in our BackEnd to capture user data logged into our Wazuh UI if you are using SearchGuard extension.
This step is necessary to perform the authentication, so the issue parent is [RBAC: New Api authentication](https://github.com/wazuh/wazuh-kibana-app/issues/2103).

**Comment by Joanes04** [comment]
**UPDATE**

Every time we need to get a new **token**, we will need the user data logged-in by **SearchGuard**. To get the data for the logged-in user, we'll use the following function inside our **api-interceptor.js** file:

```
if(this.server.plugins.searchguard) {
    this.server.plugins.searchguard.getSearchGuardBackend().authinfo(req.headers).then(user => {
      // user: The logged-in user data
    })
}
```

**Comment by gdiazlo** [comment]
The parent issue was closed. Closing as an orphan.
