### ISSUE TITLE
RBAC: Adapt to OpenDistro

### ISSUE THREAD

**Issue by Joanes04** [wazuh/wazuh-kibana-app#2106]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.12   | 7.6     | X |

**Description**

In this issue we will detail the changes needed in our BackEnd to capture user data logged into our Wazuh UI if you are using OpenDistro.
This step is necessary to perform the authentication, so the issue parent is [RBAC: New Api authentication](https://github.com/wazuh/wazuh-kibana-app/issues/2103).

**Comment by Joanes04** [comment]
**UPDATE**

Every time we need to get a new **token**, we will need the user data logged-in by **OpenDistro**. To get the data for the logged-in user, we'll use the following function inside our **api-interceptor.js** file:

```
if(this.server.plugins.security) {
    server.plugins.opendistro_security.getSecurityBackend().authinfo(req.headers).then(user => {
      // user: The logged-in user data
    })
}
```

**Comment by jsanchez91** [comment]
Implemented the interface "ISecurityFactory" to create the class "OpendistroFactory"

https://github.com/wazuh/wazuh-kibana-app/blob/4.0-7.8.0-rbac/server/lib/security-factory/factories/opendistro-factory.ts
