### ISSUE TITLE
RBAC: Manage Users and Roles in Wazuh UI

### ISSUE THREAD

**Issue by Joanes04** [wazuh/wazuh-kibana-app#2107]
Hi team,

The Wazuh UI should be able to manage Users, Roles and Policies, a new section for each of them will be created.

Regards,

**Comment by pablotr9** [comment]
**UPDATE**

## **Menu**
![image](https://user-images.githubusercontent.com/35685689/93880393-b69dfa80-fcdd-11ea-8d2e-e3240b11793e.png)

-----

## **USERS** 
***ONLY** superusers/admin users can access this section 
- **_Elasticsearch_** (Xpack): `elastic` user.
- **_Elasticsearch OSS_** (Opendistro): `admin` user.

When accessing the Users section with a non-admin user:
![image](https://user-images.githubusercontent.com/35685689/93880984-93c01600-fcde-11ea-9019-9e2514cfc4bc.png)

--- 

When accessing the Users section with an admin user:
- It shows the full list of users of the current security platform (XPACK or Opendistro) .
**How to create a new user for Wazuh UI RBAC?** Users must be created in the Security section of Kibana.
![image](https://user-images.githubusercontent.com/35685689/93881084-bb16e300-fcde-11ea-88c5-7847aa9c8ce1.png)

By default, users **won't** have any permissions to use Wazuh UI. To add new permissions, we can add roles to the users by simply clicking in the user and selecting the list of roles:
![Peek 2020-09-22 14-32](https://user-images.githubusercontent.com/35685689/93882539-a89da900-fce0-11ea-89b8-0ca30e490a49.gif)

## **ROLES** 
**ONLY** users with enough `security:` permissions can access this section. 
- It allows users to view, edit and create roles
![image](https://user-images.githubusercontent.com/35685689/93894645-40a28f00-fcef-11ea-9d8c-54ad67cdb5d6.png)
![Peek 2020-09-22 16-16](https://user-images.githubusercontent.com/35685689/93894660-439d7f80-fcef-11ea-85e7-6af464bb05cb.gif)


## **POLICIES**
**ONLY** users with enough `security:` permissions can access this section. 
- It allows users to view, edit and create policies
![image](https://user-images.githubusercontent.com/35685689/93895557-4056c380-fcf0-11ea-856f-5a98bae423d4.png)
![Peek 2020-09-22 16-22](https://user-images.githubusercontent.com/35685689/93895398-11405200-fcf0-11ea-8c7c-c12a21508da2.gif)
