### ISSUE TITLE
Unable to install wazuh app on kibana on Ubuntu 18 LTS

### ISSUE THREAD

**Issue by tbhaxor** [wazuh/wazuh-kibana-app#2109]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.11.4   | 6.x     | 444 |

**Description**
After setting up everything, i tried to install the kibana plugin for wazuh

Wazuh Version: 3.11.4
Kibana Version: 7.6.0

So i tried the following command
```
sudo -u kibana /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.11.4_7.6.0.zip
```
The message said that it was successfully installed.

So i tried to restart the kibana
```
sudo systemctl restart kibana
```
The kibana was restarted successfully, 

When i accessed by kibana web UI, it is saying "**Kibana server is not ready yet**".

So i tried to reboot the system (read on some forum), but still i am getting same issue

**Comment by tbhaxor** [comment]
Update: I have tried with https://packages.wazuh.com/wazuhapp/wazuhapp-3.11.2_7.5.2.zip this plugin app, the issue isn't solved yet

**Comment by Desvelao** [comment]
Hi, @tbhaxor 

Could you please share Kibana logs? To do this, use:
`journalctl | grep kibana`

Also attach Kibana configuration file: `/etc/kibana/kibana.yml`

**Comment by tbhaxor** [comment]
Hi @Desvelao it started working after sometime. Now this thing is beyond my understanding

**Comment by Desvelao** [comment]
I'm glad it's working again. If you have any other problems, don't hesitate to ask
