### ISSUE TITLE
[Global dashboards] Unify Overview and Agent dashboards

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#2110]
Hi team,

In our purpose to divide the app into alerts and states, we're going to unify all the alerts into global dashboards.

To do this we're going to have to unify all the current dashboards in one place, and we should be able to switch between them, as well as switch between agent view and overview in a simple and agile way.

Dynamic display loading has already been implemented using JSON, so we will simply need to switch the JSON from origin to switch between dashboards.

Now we must follow the next steps:

- [x] Implement functionality to switch between overview and agent view (agent selector)
- [x] Switch between dashboards and agent view and discover optimally
- [x] Link from Agent's view to its global dashboard

Regards.

**Comment by juankaromo** [comment]
Branch: https://github.com/wazuh/wazuh-kibana-app/tree/agents-in-visualize

**Comment by pablotr9** [comment]
**Update**
This has been migrated and adapted to the 3.13 version (branch https://github.com/wazuh/wazuh-kibana-app/tree/3.13-7.6-changes-new-design)

Tests:
- [ ] Access a dashboard using the menu popover (from a different section like Management->Rules)
- [ ] Change the dashboard from another dashboard with no agents filters.
- [ ] Change the dashboard from another dashboard with agents filters.
- [ ] Access a dashboard from the Overview welcome screen.
- [ ] Refresh the page without agents filters.
- [ ] Refresh the page with agents filters.

- Filters (Dashboard):
 - [ ] Add an agent filter using the Agent table
 - [ ] Remove agents filters using the `Remove Agents` button.
 - [ ] Add an agent filter using Kibana Search Bar
 - [ ] Add an agent filter using both Agent table and search bar
 - [ ] Add agent filter and modify it using the Agent Table.
 - [ ] Add different filters or edit the time range without an agent filter
 - [ ] Add different filters or edit the time range with an agent filter.
 - [ ] Go to discover with no agents filters
 - [ ] Go to discover with agents filters

- Filters (Discover):
 - [ ] Add an agent filter using the Agent table
 - [ ] Remove agents filters using the `Remove Agents` button.
 - [ ] Add an agent filter using Kibana Search Bar
 - [ ] Add an agent filter using both Agent table and search bar
 - [ ] Add agent filter and modify it using the Agent Table.
 - [ ] Add different filters or edit the time range without an agent filter
 - [ ] Add different filters or edit the time range with an agent filter.
 - [ ] Go to discover with no agents filters
 - [ ] Go to discover with agents filters

-Agents section:
- [ ] Click on the dashboard button,  a new page should be open with the overview dashboard with that section selected and the filter of the agent
