### ISSUE TITLE
Add sample data to dashboards

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#2115]
Hi team,

We need to add to Elasticsearch sample data and alerts to feed the Wazuh App dashboards so that users can see a real example of the views provided in that panel.

To do this, we will add a new section to the new visualize menu to add sample data, similar to the one Kibana has:

![image](https://user-images.githubusercontent.com/21195730/75773734-c1e40580-5d4e-11ea-8e3b-2bb5ab60c20d.png)

We can diversify the creation of this example data into sections. For example, create example data for 'THREAT DETECTION AND RESPONSE' or data for 'REGULATORY COMPLIANCE'. 

This data will be inserted into a new ` wazuh-sample-data` index so that it does not get mixed up with the actual alerts and can be removed when the user wishes.

- [x] Create new section to add sample data @victorst79 
- [x] Create a method to generate fake alerts of every module @jesusrodriguezl @Joanes04 @victorst79 @Desvelao 
- [x] Index this alerts in the new index @Desvelao 

Regards.

**Comment by victorst79** [comment]
Sample data reference:

![sample-data-reference](https://user-images.githubusercontent.com/25077237/76394009-0d149e80-6375-11ea-8a94-5212581def39.gif)

**Comment by Desvelao** [comment]
# Add modules data

**Notes:**
Alerts are generated with a script in the app backend.
For each sample data category an index is created with shards/replicas as configurated in **wazuh.yml**. This index has as name `<index_pattern_without_*>-sample-<category>`. For example, `wazuh-alerts-3.x--sample-security`.
In each dashboard, it will show a callout to warn that there is sample data installed.

**Backend changes**
4 app server endpoints added:
- *GET* `/elastic/samplealerts/{pattern}` - check if there is sample data installed.
- *GET* `/elastic/samplealerts/{pattern}/{category}` - check if there is sample data installed for a category.
- *POST* `/elastic/samplealerts/{pattern}/{category}` - add sample data for that category.
- *DELETE* ``/elastic/samplealerts/{pattern}/{category}` - remove sample data (index) for that category.

**Preview**
![add_modules_data_preview](https://user-images.githubusercontent.com/34042064/79355699-4e810680-7f3e-11ea-9277-bf6125c84171.png)

**Adding/removing data**
![add_sample_data_add_remove](https://user-images.githubusercontent.com/34042064/79356015-b9324200-7f3e-11ea-8fd1-fc83b8930a73.gif)

**Sample data callout in modules**
![sample_data_callout](https://user-images.githubusercontent.com/34042064/79356500-555c4900-7f3f-11ea-9780-123575ecc6cf.png)

**More screenshots**
![openscap_sample_data](https://user-images.githubusercontent.com/34042064/79358032-06afae80-7f41-11ea-8a30-41cab67f28be.png)

![vulnerabilities](https://user-images.githubusercontent.com/34042064/79358293-4ffffe00-7f41-11ea-8550-b88c332d5d89.png)

![mitre_sample_data](https://user-images.githubusercontent.com/34042064/79357910-e7188600-7f40-11ea-9992-23fa04103f9e.png)

**Comment by Desvelao** [comment]
**Problems**
- [ ] There is some problem with dashboard stats for the modules when use the new menu to go to a module. If this, is accessed from Overview (where modules cards) or some other app section, it seems that module stats are loaded and show correctly.
- [ ] VirusTotal heatmap visualization show a rare error
![virustotal_heatmap_visualization_error](https://user-images.githubusercontent.com/34042064/79359743-3fe91e00-7f43-11ea-8bba-fafc0248cb15.jpg)

**Comment by Desvelao** [comment]
**Files:**
script: `server/lib/generate-alerts/generate-alerts-script.js`
modules sample data: `server/lib/generate-alerts/sample-data`

We need to generate sample data for:
- [ ] Authentication @Desvelao 
- [ ] AWS
- [ ] Integrity monitoring
- [ ] Servers (apache)
- [ ] Policy monitoring
- [ ] System Auditing
- [ ] OpenSCAP
- [ ] CIS-CAT
- [x] Vulnerabilities @Joanes04 
- [ ] VirusTotal
- [ ] Osquery
- [ ] Docker listener
- [ ] MITRE ATT&CK

**Comment by Desvelao** [comment]
# Admin mode
Management of sample data is only avaliable when is **admin mode**.

Changes:
- Sample data appears in Management section of Wazuh menú when admin mode
![Anotación 2020-04-27 103602](https://user-images.githubusercontent.com/34042064/80355326-38e1da00-8878-11ea-9a0e-96af7146c0a0.jpg)

- Sample data card in Management
![sample-data-management-admin-mode](https://user-images.githubusercontent.com/34042064/80365720-574fd180-8888-11ea-8dd4-58e3ac038ae9.jpg)

- Wazuh visualize callout
![sample-data-callout-admin-mode](https://user-images.githubusercontent.com/34042064/80355307-31223580-8878-11ea-9e7c-368d101115e0.jpg)

- If try to enter to sample data section in no admin mode, buttons are disabled and the app redirects to app root path.
