### ISSUE TITLE
Bad scrolling behavior of top bar in Kibana plugin

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-kibana-app#2131]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.11.4   | 7.6.1     | 0858 |

**Description**
If the data usage banner of the Elastic Stack is not dismissed, the top bar of the Wazuh Kibana Plugin will be show in a bad position when scrolling.

**Steps to reproduce**

1. Do a fresh install of Kibana and the Wazuh plugin
2. Do not dismiss the "Help us improve" banner
3. Enter the Wazuh Kibana plugin
4. Scroll. 
5. Notice this affects dashboards as well as the discover modes.

**Screenshots**
![badbar](https://user-images.githubusercontent.com/36071202/76409556-cf247400-638e-11ea-82fe-34836b3a850a.gif)

**Additional context**
The same issue is not observed in other Kibana plugins, for example the native Kibana Discover plugin:

![okbar](https://user-images.githubusercontent.com/36071202/76409692-0430c680-638f-11ea-93e4-95f175553ff2.gif)

This is seen in both Firefox and Chrome. This may also occur with other Kibana banners.

**Comment by juankaromo** [comment]
Hi @jctello 

This has been solved here https://github.com/wazuh/wazuh-kibana-app/commit/5a2ca042a803c07ac75c5b2e16e3c66348377b14 and will be published in Wazuh 3.12.1.

Thank you very much for reporting it!
