### ISSUE TITLE
Unable to install kibana-plugin in Redhat OS

### ISSUE THREAD

**Issue by surendarsuren27** [wazuh/wazuh-kibana-app#2139]
Kibana version 7.6.1

Trying to install search-guard plugin in kibana but getting below error

Plugin installation was unsuccessful due to error "Cannot delete files/directories outside the current working directory. Can be overridden with the `force` option."

My kibana is running in /data/kibana

**Comment by juankaromo** [comment]
Hi @surendarsuren27 

Since the release of Kibana 7.6.0, the installation of the plugins must be done from the Kibana home directory. Please try these steps:

```
cd /usr/share/kibana
sudo -u kibana bin/kibana-plugin install <package-url>
```
I hope this helps and please, let us know the results.

Regards,
Juan Carlos

**Comment by surendarsuren27** [comment]
@juankaromo Thanks for your reply.
This is my kibana home directory -->/data/kibana-7.6.1-linux-x86_64/bin
Command ran: ./kibana-plugin install file:///data/softwares/search-guard-kibana-plugin-7-7.6.1-40.1.0.zip

Console output:
[tsfunc@xxxxxxxx bin]$ ./kibana-plugin install file:///data/softwares/search-guard-kibana-plugin-7-7.6.1-40.1.0.zip
Attempting to transfer from file:///data/softwares/search-guard-kibana-plugin-7-7.6.1-40.1.0.zip
Transferring 37610818 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Cannot delete files/directories outside the current working directory. Can be overridden with the force option."

**Comment by juankaromo** [comment]
Hi @surendarsuren27 
Try this:

```
cd /data/kibana-7.6.1-linux-x86_64
sudo -u kibana bin/kibana-plugin install file:///data/softwares/search-guard-kibana-plugin-7-7.6.1-40.1.0.zip
```

Regards,
Juan Carlos

**Comment by surendarsuren27** [comment]
Hi @juankaromo , we dont have user called kibana so that we have created equivalent user is tsfunc.

So ran the command as below,
bin/kibana-plugin install file:///data/softwares/search-guard-kibana-plugin-7-7.6.1-40.1.0.zip

**Comment by surendarsuren27** [comment]
@juankaromo running from the kibana home directory it works. Many thanks
