### ISSUE TITLE
API selector from the navbar

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#2143]
Hi team,

Due to the support for MSSP by Wazuh cloud, it has seemed that you need to be able to change APIs easily, as is being done with the index pattern from the main menu bar.

To carry out his we are going to follow these steps:

- [x] Add in our wazuh.yml the settings needed to show this selector. It will be disabled by default. If it is disabled, the API name will be displayed as before
- [x] Show the selector in the wz-menu component if it is enabled.
- [x] Reuse the behavior of switching APIs and selecting a default one from the Settings controller.

Regards.

**Comment by pablotr9** [comment]
**Update**
Working on this branch https://github.com/wazuh/wazuh-kibana-app/tree/3.13-7.6-wzmenu-improvements

The selector API has been added to the new WzMenu created in ReactJS:
We can now easily change the API and see any change in the Wazuh UI when editing the `wazuh-yml`  wtihout restarting or refreshing the page:
![full-example](https://user-images.githubusercontent.com/35685689/77421138-91324180-6dcb-11ea-80d9-a8079a10d4d1.gif)
![example-settings-devtools](https://user-images.githubusercontent.com/35685689/77421331-f128e800-6dcb-11ea-9409-a04a1c9f4448.gif)
![apiselector-dashboard-example](https://user-images.githubusercontent.com/35685689/77421341-f4bc6f00-6dcb-11ea-90f3-a9cc1f4fe3f9.gif)
