### ISSUE TITLE
Kibana 7.6.1 (nodejs) crash when wazuh-app plugin is installed 

### ISSUE THREAD

**Issue by deni2604** [wazuh/wazuh-kibana-app#2145]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.11.4   | 7.6.1     | 444 |

**Description**
I have upgraded Elasticsearch from 7.5.2 (with a working wazuh-app) to 7.6.1
I have installed the required wazuh-app: https://packages.wazuh.com/wazuhapp/wazuhapp-3.11.4_7.6.1.zip
Everything went well in the upgrade (elasticsearch, filebeat, ...) except for kibana that does not start, producing a nodejs crash.
After I have removed the wazuh-app plugin (bin/kibana-plugin remove wazuh), Kibana was starting without any errors.
Could you please help?

**Steps to reproduce**
root@# export NODE_OPTIONS="--max-old-space-size=4096"
root@# sudo -u kibana bin/kibana -c /etc/kibana/kibana.yml

<--- Last few GCs --->

[4149:0x28d4ee0]    99410 ms: Mark-sweep 1338.4 (1444.8) -> 1322.1 (1442.8) MB, 559.9 / 0.0 ms  (average mu = 0.170, current mu = 0.127) allocation failure scavenge might not succeed
[4149:0x28d4ee0]   100051 ms: Mark-sweep 1336.7 (1442.8) -> 1323.0 (1444.3) MB, 569.0 / 0.0 ms  (average mu = 0.142, current mu = 0.112) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================
0: ExitFrame [pc: 0x28be9c65be1d]
Security context: 0x2ba82051e6e9 <JSObject>
    1: 0x119d8ae87a31 <Symbol: Symbol.split>(aka [Symbol.split]) [0x2ba820509641](this=0x164ddc73aea1 <JSRegExp <String[5]: \r?\n>>,0x164ddc73ae29 <String[14]: _AbstractLayer>,0x119d8ae826f1 <undefined>)
    2: split [0x2ba8205106c9](this=0x164ddc73ae29 <String[14]: _AbstractLayer>,0x164ddc73aea1 <JSRegExp <String[5]: \r?\n>>)
    3: w(aka w) [0xbbbd1502b79]...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8fa090 node::Abort() [bin/../node/bin/node]
 2: 0x8fa0dc  [bin/../node/bin/node]
 3: 0xb0052e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [bin/../node/bin/node]
 4: 0xb00764 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [bin/../node/bin/node]
 5: 0xef4c72  [bin/../node/bin/node]
 6: 0xef4d78 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [bin/../node/bin/node]
 7: 0xf00e52 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [bin/../node/bin/node]
 8: 0xf01784 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [bin/../node/bin/node]
 9: 0xf043f1 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [bin/../node/bin/node]
10: 0xecd448 v8::internal::Factory::AllocateRawWithAllocationSite(v8::internal::Handle<v8::internal::Map>, v8::internal::PretenureFlag, v8::internal::Handle<v8::internal::AllocationSite>) [bin/../node/bin/node]
11: 0xeda545 v8::internal::Factory::NewJSArray(v8::internal::ElementsKind, v8::internal::PretenureFlag) [bin/../node/bin/node]
12: 0xeda651 v8::internal::Factory::NewJSArrayWithElements(v8::internal::Handle<v8::internal::FixedArrayBase>, v8::internal::ElementsKind, int, v8::internal::PretenureFlag) [bin/../node/bin/node]
13: 0x8b7aa4  [bin/../node/bin/node]
14: 0x11a7be4 v8::internal::Runtime_RegExpSplit(int, v8::internal::Object**, v8::internal::Isolate*) [bin/../node/bin/node]
15: 0x28be9c65be1d
Aborted

**Screenshots**
Not Applicable

**Additional context**
I am running the Elasticsearch stack on a Debian 10.3 fully patched
ES : xpack.security.enabled: true
elasticsearch, filebeat, kibana : 7.6.1
Wazuh-api, wazuh-manager: 3.11.4
NodeJS: 10.15.2~dfsg-2
Host    : Virtual machine running on VMware ESXi
CPU    : 6 CPU
RAM   : 8 GB
HDD    : 400 gigs

**Comment by pablotr9** [comment]
Hi @deni2604 , 

Could you please edit the file `/etc/default/kibana` by adding a new line at the end with the following content: 
`NODE_OPTIONS="--max-old-space-size=4096"`
and restart Kibana service:
`systemctl restart kibana`
Please note that it can take a few minutes.

Let me know if it helps!

Best Regards,

**Comment by deni2604** [comment]
Hi all, 
Adding the line in the /etc/default/kibana has solved the problem!
Many thanks
Best regards

**Comment by pablotr9** [comment]
Hi @deni2604 ,

If you have any other problems, please do not hesitate to ask us again! 
You can also join our Slack channel or our Google mailing list, more info [here](https://wazuh.com/community/)

Best Regards,
