### ISSUE TITLE
Add new FIM settings on configuration on demand

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#2147]
Hi team,

After the rework of the FIM module some new settings have been added that have to be shown in the on-demand configuration of the interface.

The API call is `GET /agents/<agent-id>/config/syscheck/syscheck`, and the new settings in the response data message is:

```js
      "synchronization": {
        "enabled": "yes",
        "max_interval": 3600,
        "interval": 20,
        "response_timeout": 30,
        "queue_size": 16384,
        "max_eps": 1000
      },
      "max_eps": 100,
      "process_priority": 10,
      "database": ""
    }
```

We have to add these settings for both the current branch `3.12.1` `[3.12-7.6]` (in angular.js) and the redesigned app `[3.13-7.6]`, in this case in React.js

Regards.

**Comment by Desvelao** [comment]
**3.13-7.6** ReactJS
These new fields are for manager and agents. They are always returned.

- Added a new tab **Synchronization**
![synchronization fields](https://user-images.githubusercontent.com/34042064/77541769-6ddbc500-6ea5-11ea-8cf9-9d40b1a57e5f.png)
📝  TODO: need a description, waiting response of core team to add
- ***max_eps***, ***process_priority*** and ***database*** fields are displayed in **General** tab
![new fields in general tab ](https://user-images.githubusercontent.com/34042064/77534818-a5447480-6e99-11ea-8bdf-dc68b65b2e00.jpg)

**Comment by Desvelao** [comment]
**3.12-7.6** - AngularJS
- Synchornization tab
![synchornization tab](https://user-images.githubusercontent.com/34042064/77638494-8d332a80-6f57-11ea-9013-7bdae07e57e4.png)

- **max_eps**, **process_priority** and **database** fields are displayed in **General** tab
![new fim settings i general tab](https://user-images.githubusercontent.com/34042064/77638441-75f43d00-6f57-11ea-886b-69bde643736f.png)

**Comment by Desvelao** [comment]
**Update:**
- Added *skip_dev*, *skip_sys* and *skip_proc* settings what were missing to ReactJS and AngularJS branches in general tab

General tab in React with these settings.
![new-fim-settings](https://user-images.githubusercontent.com/34042064/77900192-f7acd900-727d-11ea-9675-a6ddca84cb6c.png)
