### ISSUE TITLE
Integrity monitoring States view for agent

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#2153]
Hi team,

We need to redesign the Integrity monitoring section to add the states and redistribute the way the data is displayed.

The result has to be this:

![image](https://user-images.githubusercontent.com/21195730/77525885-ffd5d480-6e89-11ea-9bbd-e4a2b002b980.png)

In the scenario where we have no configuration for this module and no monitored directories, we should display a message similar to this one:

![image](https://user-images.githubusercontent.com/21195730/77526295-a326e980-6e8a-11ea-99d7-3a768c3416cd.png)

Regards,

**Comment by jsanchez91** [comment]
We created the branch [integrity_monitoring_states#2153](https://github.com/wazuh/wazuh-kibana-app/tree/integrity_monitoring_states%232153)

The first commit with the component structure is added, and its implementation.
![image](https://user-images.githubusercontent.com/3064506/77563065-121f3500-6ec1-11ea-9a09-4b43cb139b58.png)

**Comment by jsanchez91** [comment]
We update the `state` component of the new view of Integrity monitoring.

![image](https://user-images.githubusercontent.com/3064506/77932139-6c4b3c00-72ad-11ea-890f-e188e5ef3181.png)

The new view has the possibility to filter the table data by many fields, like as `file` or `uname`
![filter_bar_fields](https://user-images.githubusercontent.com/3064506/77933548-3a3ad980-72af-11ea-8ad9-b5cd9ed47200.gif)

Multiple filters can be combined to improve searches
![filter_bar_multi](https://user-images.githubusercontent.com/3064506/77934115-e977b080-72af-11ea-9929-085338249585.gif)

**Comment by jsanchez91** [comment]
**Updates**:

- Fixed the `search` suggestion
![image](https://user-images.githubusercontent.com/3064506/79580315-1ce87680-80c9-11ea-99b5-24c1b5499e68.png)

- Added context menu to the filters badges
![image](https://user-images.githubusercontent.com/3064506/79580472-528d5f80-80c9-11ea-8128-f3d9862ecf6d.png)

- You can edit the filters from the context menu
![image](https://user-images.githubusercontent.com/3064506/79580688-adbf5200-80c9-11ea-9328-777f82b472e0.png)

- Quickly reverse the filter operator in the context menu
![filter_bar_invert_operators](https://user-images.githubusercontent.com/3064506/79581034-26261300-80ca-11ea-8c0d-ceaf900b5061.gif)

- Quickly change the conjunction of the filter in the context menu
![filter_bar_invert_conjuntion](https://user-images.githubusercontent.com/3064506/79581267-7ef5ab80-80ca-11ea-8c83-82915223d289.gif)
