### ISSUE TITLE
Integrity monitoring files detail view

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#2156]
Hi team,

We are going to implement a new view, using a Flyout component, to see the detail of a monitored FIM file.

In it, we are going to show the details of the file, besides a history of alerts that happened in that file. 

To make this history, a component that can be reused by other modules in the future will be made.

The result has to be this:

![image](https://user-images.githubusercontent.com/21195730/77560531-e5b5e980-6ebd-11ea-9b3d-52b5298da888.png)

Regards,

**Comment by Joanes04** [comment]
**Update**

We have added, in the detail view, some fields that can be clicked to add a filter to the FIM file table. The operation is as seen in the GIF: 

![links](https://user-images.githubusercontent.com/9945959/79779176-f49a8b00-8307-11ea-9976-ac28a98a9552.gif)

**Comment by pablotr9** [comment]
**Update**

FIM table, we can now click in a file to get extra detail, these extra details can be divided in 2 different sections:
1. File details:
All details from the API requests 'GET /syscheck/<AGENT_ID>' are shown
![image](https://user-images.githubusercontent.com/35685689/79831291-6aa1ff00-83a7-11ea-9fc7-de5c3bbae8c2.png)

2. Related alerts:
It lists the related alerts of that file, we can add new filters or change the date range to filter these alerts:
![image](https://user-images.githubusercontent.com/35685689/79831829-78a44f80-83a8-11ea-989f-09572a4ad7fa.png)
We can also expand these new alerts to check its information: Table (syscheck alerts), JSON (it shows the full alert JSON) and Rule (It shows rule data like location, level, compliance)
![image](https://user-images.githubusercontent.com/35685689/79832235-4ba46c80-83a9-11ea-8e3b-a173faf32ae1.png)


To do that we have adapted our backend method to make requests to Elasticsearch (` POST /elastic/alerts` ). 
The method now accepts both Elasticsearch bool query and a list of key:values filters, this is how the new method looks like:
```
  POST /elastic/alerts
   {
     elasticQuery: {bool: {must: [], filter: [{match_all: {}}], should: [], must_not: []}}
     filters: [{rule.groups: "syscheck"}, {agent.id: "001"} ]
     from: "now-1y"
     to: "now"
     offset: 0
     pattern: "wazuh-alerts-3.x-*"
     sort: {timestamp: {order: "asc"}}
   }
```
