### ISSUE TITLE
Agents with lost registration date report messy broken date

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh-kibana-app#2162]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.12.0 | ossec-authd | Manager | n/a | n/a |

Apparently there was a bug in the wazuh-manager 3.11 upgrade process that wiped out the  **/var/ossec/queue/agents-timestamp** file that contains the registration dates for agents as seen under the Agents table in the Wazuh web UI.  The default behavior of the UI in the case of agents existing in the registration database but having no record in **agents-timestamp**, is to display the date `1969/12/31 20:00:00`.

Please make the Web UI display `n/a` instead of `1969/12/31 20:00:00` as the registration date for agents whose registration date is missing.  It would look so much cleaner.

Thanks,
Kevin Branch

**Comment by juankaromo** [comment]
Hi @branchnetconsulting,

Thanks for letting us know, we add it to the current sprint for Wazuh 3.13.

Regards,

**Comment by pablotr9** [comment]
Hi @branchnetconsulting ,

I just tried to reproduce your error with no success, when a date is wrong all I can see is  '`-`'  instead of that date you mention, could you please check what is the output of the Wazuh API when the registration date is wrong? thanks!

Regards,
