### ISSUE TITLE
Kibana "JSON.parse: unexpected character at line 1" when wazuh plugin is enabled.

### ISSUE THREAD

**Issue by gyterpena** [wazuh/wazuh-kibana-app#2164]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.12.0-1   | 7.6.1     | 444 |

**Description**
After upgrading to 3.12 and kibana 7.6.1 existing dashboards(not wazuh related) fail to load with

Debug: internal, implementation, error
    SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at server.route.handler (/etc/kibana/src/legacy/core_plugins/elasticsearch/lib/create_proxy.js:85:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)

[esaggs] > [esaggs] > [esaggs] > [esaggs] > [esaggs] > [esaggs] > [esaggs] > [esaggs] > [esaggs] > [esaggs] > JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Steps to reproduce**

1. Install wazuh kibana plugin. (give node.js 2048M RAM as it fails to optimize with defaults)
2. open any dashboard with visualizations

**Additional context**
After removing wazuh plugin dashboards load ok.

**Comment by victorst79** [comment]
Hi @gyterpena.

Could you please share with me the Kibana logs?
`sudo journalctl -xe | grep kibana`

**Comment by gyterpena** [comment]
We run it from supervisord, there is no explicit error in the logs. It could be related to heap size as running with 3072M RAM works better.

**Comment by victorst79** [comment]
Hi @gyterpena,

Great, any other problems you have do not hesitate to open another issue and if your problem has been solved please close the issue.
Have a nice day!

Regards,
Victor Santaella.
