### ISSUE TITLE
kibana 7.6.2 - wazuh app

### ISSUE THREAD

**Issue by username-player** [wazuh/wazuh-kibana-app#2171]
Hello i belive u r working on it..

After upgrade kibana to 7.6.2  today in simultaneus with wazuh-manager & api:
Got stuck on this:

 sudo -u kibana bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.12.0_7.6.1.zip
Attempting to transfer from https://packages.wazuh.com/wazuhapp/wazuhapp-3.12.0_7.6.1.zip
Transferring 23174659 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Plugin wazuh [7.6.1] is incompatible with Kibana [7.6.2]"

thx in adv.

**Comment by pablotr9** [comment]
Hi @username-player,

Thanks for letting us know, the team is currently working on the new package for Kibana 7.6.2, we are testing it for any breaking change and release a version as robust as possible. We hope to have it ready very very soon if all testing goes well and It will be released in a few days. I'll let you know here when we have it.

Meanwhile, you can downgrade Kibana and use the 3.12.0-7.6.1 plugin while the 3.12.0-7.6.2 plugin is released.

Thank you for your patience!

Best Regards,
Pablo Torres

**Comment by username-player** [comment]
Gracias @pablotr9  for the fast reply..

**Comment by pablotr9** [comment]
Hi @username-player,

The new package of Wazuh 3.12.0-7.6.2 has just been released, you can find the release notes and the package here: https://github.com/wazuh/wazuh-kibana-app/releases/tag/v3.12.0-7.6.2

If you have any other questions, please let us know!

Best Regards,
Pablo Torres
