### ISSUE TITLE
Problem connecting to API

### ISSUE THREAD

**Issue by 8arcly** [wazuh/wazuh-kibana-app#2172]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.12   | 7.6.1     | 0870 |

**Description**
Problems with connecting to Wazuh API after upgrade from 3.10.2-1.

**Steps to reproduce**

1. Go to 'Wazuh App in Kibana'
2. App checks for 'index pattern, remplate, known fields' are ok, bit API connection and API version ends with `Wazuh App: Please set up Wazuh API credentials` and redirects to 'Wazuh API configuration'
3. Credentials in `/usr/share/kibana/optimize/wazuh/config/wazuh.yml` are set. Connection test for API entry is successfull. Status is Online. But any retry to use application goes to state described in point 2.
4. Attempt to run action 'set as default' on 'Wazuh API configuration' ends with popup `_this$apiEntries$this is undefinied`
5. API log:
```
tail -n20 /var/ossec/logs/api.log
WazuhAPI 2020-04-01 12:22:30 wazaaa: [127.0.0.1] GET /agents/000? - 200 - error: '0'.
WazuhAPI 2020-04-01 12:22:32 wazaaa: [127.0.0.1] GET /cluster/status? - 200 - error: '0'.
WazuhAPI 2020-04-01 12:28:07 wazaaa: [127.0.0.1] GET /manager/info? - 200 - error: '0'.
WazuhAPI 2020-04-01 12:28:09 wazaaa: [127.0.0.1] GET /agents/000? - 200 - error: '0'.
WazuhAPI 2020-04-01 12:28:11 wazaaa: [127.0.0.1] GET /cluster/status? - 200 - error: '0'.
WazuhAPI 2020-04-01 12:29:40 wazaaa: [127.0.0.1] GET /manager/info? - 200 - error: '0'.
WazuhAPI 2020-04-01 12:29:42 wazaaa: [127.0.0.1] GET /agents/000? - 200 - error: '0'.
WazuhAPI 2020-04-01 12:29:44 wazaaa: [127.0.0.1] GET /cluster/status? - 200 - error: '0'.
WazuhAPI 2020-04-01 12:29:46 wazaaa: [127.0.0.1] GET /manager/info? - 200 - error: '0'.
WazuhAPI 2020-04-01 12:29:48 wazaaa: [127.0.0.1] GET /agents/000? - 200 - error: '0'.
WazuhAPI 2020-04-01 12:29:50 wazaaa: [127.0.0.1] GET /cluster/status? - 200 - error: '0'.
WazuhAPI 2020-04-01 12:29:56 wazaaa: [127.0.0.1] GET /manager/info? - 200 - error: '0'.
WazuhAPI 2020-04-01 12:29:58 wazaaa: [127.0.0.1] GET /agents/000? - 200 - error: '0'.
WazuhAPI 2020-04-01 12:30:00 wazaaa: [127.0.0.1] GET /cluster/status? - 200 - error: '0'.
WazuhAPI 2020-04-01 12:30:03 wazaaa: [127.0.0.1] GET /agents/?offset=0&limit=1&q=id!%3D000 - 200 - error: '0'.
WazuhAPI 2020-04-01 12:30:05 wazaaa: [127.0.0.1] GET /cluster/status? - 200 - error: '0'.
WazuhAPI 2020-04-01 12:30:07 wazaaa: [127.0.0.1] GET /agents/?offset=0&limit=500&q=id!%3D000 - 200 - error: '0'.
WazuhAPI 2020-04-01 12:32:04 wazaaa: [127.0.0.1] GET /manager/info? - 200 - error: '0'.
WazuhAPI 2020-04-01 12:32:06 wazaaa: [127.0.0.1] GET /agents/000? - 200 - error: '0'.
WazuhAPI 2020-04-01 12:32:08 wazaaa: [127.0.0.1] GET /cluster/status? - 200 - error: '0'.
```
6. WazuhApp log:
```
tail -n20 /usr/share/kibana/optimize/wazuh/logs/wazuhapp-plain.log
error: 2020/04/01 12:18:35: manage-hosts:getHostById: Cannot convert undefined or null to object
error: 2020/04/01 12:18:35: wazuh-api:checkStoredAPI: Cannot convert undefined or null to object
error: 2020/04/01 12:18:44: manage-hosts:getHostById: Cannot convert undefined or null to object
error: 2020/04/01 12:18:44: wazuh-api:checkStoredAPI: Cannot convert undefined or null to object
error: 2020/04/01 12:18:44: manage-hosts:getHostById: Cannot convert undefined or null to object
error: 2020/04/01 12:18:44: wazuh-api:checkStoredAPI: Cannot convert undefined or null to object
error: 2020/04/01 12:18:54: manage-hosts:getHostById: Cannot convert undefined or null to object
error: 2020/04/01 12:18:54: wazuh-api:checkStoredAPI: Cannot convert undefined or null to object
error: 2020/04/01 12:22:7: manage-hosts:getHostById: Cannot convert undefined or null to object
error: 2020/04/01 12:22:7: wazuh-api:checkStoredAPI: Cannot convert undefined or null to object
error: 2020/04/01 12:22:15: manage-hosts:getHostById: Cannot convert undefined or null to object
error: 2020/04/01 12:22:15: wazuh-api:checkStoredAPI: Cannot convert undefined or null to object
error: 2020/04/01 12:22:26: manage-hosts:getHostById: Cannot convert undefined or null to object
error: 2020/04/01 12:22:26: wazuh-api:checkStoredAPI: Cannot convert undefined or null to object
error: 2020/04/01 12:29:36: manage-hosts:getHostById: Cannot convert undefined or null to object
error: 2020/04/01 12:29:36: wazuh-api:checkStoredAPI: Cannot convert undefined or null to object
error: 2020/04/01 12:29:44: manage-hosts:getHostById: Cannot convert undefined or null to object
error: 2020/04/01 12:29:44: wazuh-api:checkStoredAPI: Cannot convert undefined or null to object
error: 2020/04/01 12:29:54: manage-hosts:getHostById: Cannot convert undefined or null to object
error: 2020/04/01 12:29:54: wazuh-api:checkStoredAPI: Cannot convert undefined or null to object
```

**Screenshots**

![obraz](https://user-images.githubusercontent.com/62991765/78128816-d4696180-7416-11ea-8a30-5389843afc81.png)
![obraz](https://user-images.githubusercontent.com/62991765/78128857-e945f500-7416-11ea-9873-e2ed03f4bf9b.png)
![obraz](https://user-images.githubusercontent.com/62991765/78129049-3cb84300-7417-11ea-942e-c56f9a1f0b2c.png)
![obraz](https://user-images.githubusercontent.com/62991765/78129104-58bbe480-7417-11ea-9701-c976ee04235d.png)

**Additional context**
So far I've tried to reinstall app and wazuh api, deleted wazuh indices in elasticsearch.
API configured via `/var/ossec/api/scripts/configure_api.sh` to HTTPS with generated by script self-signed sertificates and custom username.
API is reachable in curl
```
curl -u wazaaa:[pass] -k "https://127.0.0.1:55000?pretty"
{
   "error": 0,
   "data": {
      "msg": "Welcome to Wazuh HIDS API",
      "api_version": "v3.12.0",
      "hostname": "debian-buster-1",
      "timestamp": "Wed Apr 01 2020 13:00:47 GMT+0200 (Central European Summer Time)"
   }
}

```
All components (ELK, Wazuh) are in the same host.

**Comment by jsanchez91** [comment]
Hi @8arcly,

It could be due to an incorrect cookie in the cache, perhaps due to an earlier version installed.

You need to delete all cookies stored in your browser and try to enter the Wazuh application again.

In Firefox you must press F12 to open the developer tools. In them, go to Storage, and Delete all <kibana_ip> cookies:

![image](https://user-images.githubusercontent.com/3064506/78132602-52306b80-741d-11ea-8f3a-98c68eb67dd6.png)

In Chrome you must press F12 to open the developer tools. In them, go to Application, and Delete all <kibana_ip> cookies:

![image](https://user-images.githubusercontent.com/3064506/78132627-5d839700-741d-11ea-975d-cf4913fc80ba.png)

Tell us the results,
Regards.

**Comment by 8arcly** [comment]
Hi @jsanchez91 ,

Yep! That's it!
Thank you so much.
I spent two days reviewing each piece of configuration on the server side and did not think that the problem could be on the client side.
Regards.
