### ISSUE TITLE
Wazuh package v.3.12.1 for Kibana with version 7.4.2 is missed

### ISSUE THREAD

**Issue by esfateev** [wazuh/wazuh-kibana-app#2191]
New Wazuh package v.3.12.1 for Kibana with version 7.4.2 is missed. 
Could you please prepare package?

Thanks!
BR, Eugene

**Comment by pablotr9** [comment]
Hi @esfateev!

In each release, Wazuh supports the latest version of Kibana (7.6.2) the latest for Opendistro (7.6.1) and the latest for the 6.x branch (6.8.8).

Opendistro updated its Elasticsearch from 7.4.2 to 7.6.1 and we support its latest version, you can find this package here [3.12.1-7.6.1](https://github.com/wazuh/wazuh-kibana-app/releases/tag/v3.12.1-7.6.1)
If updating is not possible, you can find the latest Wazuh package compatible with Kibana 7.4.2 here: [3.12.0-7.4.2](https://github.com/wazuh/wazuh-kibana-app/releases/tag/v3.12.0-7.4.2)


Regards,

**Comment by esfateev** [comment]
Thanks for the clarification!

BR, Eugene
