### ISSUE TITLE
Support for other environment variables on "Deploy a new agent" command snippet. 

### ISSUE THREAD

**Issue by ducthinh993** [wazuh/wazuh-kibana-app#2193]
**Describe the solution you'd like**
By default command snippet on "Deploy a new agent" page only support env var WAZUH_MANAGER_IP. Example:

```bash
sudo WAZUH_MANAGER_IP='wazuh.example.com' yum install https://packages.wazuh.com/3.x/yum/wazuh-agent-3.12.2-1.x86_64.rpm
```
Incase of using env var like WAZUH_PROTOCOL, the command snippet not added.

**Describe alternatives you've considered**
Wazuh app should looking for all supported env var and updated on command snippet.
For example: If I define those env var WAZUH_MANAGER_IP='wazuh.example.com', WAZUH_PROTOCOL="TCP" it should showing:
```bash
sudo WAZUH_MANAGER_IP='wazuh.example.com' WAZUH_PROTOCOL="TCP" yum install https://packages.wazuh.com/3.x/yum/wazuh-agent-3.12.2-1.x86_64.rpm
```

**Additional context**

**Comment by jctello** [comment]
It is worth noting that when password is enabled in the authentication daemon the Wazuh Kibana Plugin is smart enough to notice that and provide a field for the password.
![image](https://user-images.githubusercontent.com/36071202/79229458-56b84380-7e63-11ea-9706-fd18a1d4c314.png)

This behavior could be easily replicated with the communication protocol.

**Comment by juankaromo** [comment]
Related https://github.com/wazuh/wazuh-kibana-app/issues/2382

**Comment by juankaromo** [comment]
Hi @ducthinh993 

In the next release of Wazuh, the version 4.0, will have a series of improvements regarding this proposal that you present us.

Now, we will show the variable `WAZUH_MANAGER` filled with the default api, or the setting agents_enrollment_dns if it is activated.

On the other hand the variable `WAZUH_REGISTRATION_PASSWORD` will be filled, if it is activated, with the result of the call `GET /agents/000/config/auth/auth`, and it will be shown in the code snipet as ****

On the other hand we obtain the protocol using `GET /agents/000/config/request/remote` call and detect if remoted is on UDP (Wazuh 4.0 is TCP by default) to add a `PROTOCOL="UDP"`.

Finally, we have introduced a new setting in the App that is `agents_enrollment_dns=""`. By default it is empty and will not be used, but if it has any value set in wazuh.yml, then the `WAZUH_MANAGER` will be filled by default with the content of this variable.

With that, the agent deployment would have to be copy and paste.  

Regards,
