### ISSUE TITLE
Dont show anything in Overview tab

### ISSUE THREAD

**Issue by tatdatpham** [wazuh/wazuh-kibana-app#22]
I saw some image demo, have many chart in Overview tab but when i installed plugin in kibana, i dont see anything in Overview tab.
Im using Kibana 5.4. (wzauh-kibana-app for kibana 5.4). Everything function is woking except Overview tab
Demo
![image](https://cloud.githubusercontent.com/assets/3429970/26091482/bd119066-3a35-11e7-808f-3a55f866312d.png)

My Overview tab

![image](https://cloud.githubusercontent.com/assets/3429970/26091536/0cbfd384-3a36-11e7-9e02-3bbbe48e6534.png)

Thanks!

**Comment by alberpilot** [comment]
Hello @tatdatpham 

  Looks like if communication between filebeat and logstash is not working. Following this steps:
(https://documentation.wazuh.com/current/installation-guide/installing-wazuh-server/wazuh_server_rpm.html#installing-filebeat)

Verify the file **/etc/filebeat/filebeat.yml**. In Section 

```
output:
  logstash:
    hosts: ["ELASTIC_SERVER_IP:5000"]
```

The Logstash IP address must be placed. (In documentation says ELASTIC_SERVER_IP because we assume a same machine with ElasticSearch and logstash, but it can be differents). Restart filebeat service (`systemctl restart filebeat` in systemd or `service filebeat restart` in SysV Init. 

Once verified, please take a look at /var/log/filebeat/filebeat in order to see if the communication is correct. 

If the problem still and the filebeat log shows a logstash - filebeat communication problem it's necessary verify if a secure communication was done through certificate, the used IP address inside the certificate must be the Logstash server IP address. Then, verify a correct transfer of the certificate in the filebeat machine. 
 
Take a look at /var/log/logstash/logstash-plain.log could be useful in order to verify that Logstash is working properly. 

Also, depending of your installation (if is Wazuh Manager and Elastic Stack all in same server, or if it is distributed, etc) the problem could be different. Once verified please let us know if it's working or what is appears in the logs. 

Best regards,

**Comment by tatdatpham** [comment]
yeah, i know that, and readly setup and config.
i see log from wazuh-alert-* indices, saw dashboard (image)

![image](https://cloud.githubusercontent.com/assets/3429970/26115340/ee4ae700-3a89-11e7-8017-38837a7fb75b.png)
![image](https://cloud.githubusercontent.com/assets/3429970/26115399/1741d344-3a8a-11e7-8c12-333ba96c4824.png)

But i still dont see anything in Overview Tab. Thanks!

**Comment by snaow** [comment]
Hi @tatdatpham,

Thanks for your feedback, let me try to help here.
I can see how you are already getting events on Elastic, thanks for the screenshots.

The problem could be related to internal filters and/or Elasticsearch internal requests.

**Wazuh App default filters**

We have the option to add several Wazuh APIs to our Wazuh App, we could choose what API we want to get the data from at "Settings" tab. 
Cause we need to filter all the data in our panels with the Manager we have set, we are using an internal filter like this one: "manager.name: managerName" for all the Elasticsearch queries/aggregations.
Could you run the following commands to check if the filters are working right?

**Get last Elasticsearch alert: Manager name**

`curl -XGET http://kibana_ip_address:5601/elasticsearch/wazuh-alerts-2017.05.16/wazuh/_search?size=1`
          
Expected output

```
...
      {
        "_index": "wazuh-alerts-2017.05.16",
        "_type": "wazuh",
        "_id": "AVwOkWd_PNYxNZoXSAKy",
        "_score": 1,
        "_source": {
          "agent": {
            "ip": "10.0.0.121",
            "name": "vpc-agent-debian",
            "id": "003"
          },
          "manager": {
            "name": "vpc-ossec-manager"
          },
...
```


**Get Wazuh App settings: Manager name**

`curl -XGET http://kibana_ip_address:5601/api/wazuh-api/apiEntries`

Expected output

```
...
      "api_user": "test",
      "api_password": "pwEncoded",
      "url": "http://miapi",
      "api_port": "55000",
      "insecure": "true",
      "component": "API",
      "active": true,
      "manager": "vpc-ossec-manager",
      "extensions": {
        "oscap": true,
...
```


Field manager.name on first output must match field manager in second output.
Are the identical in your servers?

**Elasticsearch internal requests**
We send a request to get alert count for a certain period of time, if the Elasticsearch connection is not working properly inside the App, we would get an error and "No results found" message appears.

`curl -XPOST -H 'kbn-version: 5.4.0' -H "Content-Type: application/json" --data '{"fields":[],"manager":"vpc-ossec-manager","timeinterval":{"gte":"now-1d","lt":"now"}}' http://kibana_server_ip:5601/api/wazuh-elastic/alerts-count/`

Expected output:

`{"statusCode":200,"data":99267}`

"data" field should be greater than 0.

Let me know the output of those commands so we can find out what is happening there.

Thanks!

**Comment by rossengeorgiev** [comment]
@tatdatpham If you have x-pack installed on your elastic cluster, make sure you have it installed in kibana as well.

**Comment by tatdatpham** [comment]
Hi @snaow , this is output for your command ..

`curl -XGET http://kibana_ip_address:5601/elasticsearch/wazuh-alerts-2017.20/wazuh/_search?size=1`

```
{
  "took": 213,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": null,
    "hits": [

    ]
  }
}
```

`curl -XGET http://kibana_ip_address:5601/api/wazuh-api/apiEntries`

> My manager name is : Wazuh

`curl -XPOST -k -u kibana:password -H 'kbn-version: 5.4.0' -H "Content-Type: application/json" --data '{"fields":[],"manager":"vpc-ossec-manager","timeinterval":{"gte":"now-1d","lt":"now"}}' https://my-ip/api/wazuh-elastic/alerts-count/`

`{"statusCode":200,"data":0}`

Thansk.

**Comment by snaow** [comment]
@tatdatpham @rossengeorgiev is right about the X-pack, I can see how you are using "HTTPS", do you have an Nginx proxy set up or X-Pack ?

Please re-run last command with your own manager name, you are using "vpc-ossec-manager".
I need to confirm manager.name field from alerts match with manager stored in Wazuh App.

If you are using X-pack, Nginx and/or different basePath let me know please.

Best regards,
Pedro.

**Comment by tatdatpham** [comment]
@snaow , sorry, i run command with my manager name, and got same result 
`{"statusCode":200,"data":0}`
I'm using x-pack

**Comment by snaow** [comment]
I can see you have a "type" field with "ossec-alert", could you check your "_type" field? You could open an alert in Discovery tab and check it.
Our default requests are made searching for indices "_wazuh-alerts-*_" with _type "_wazuh_".

If you are using X-Pack, have you install x-pack plugin for Kibana? What user do you have set in kibana.yml? We are inheriting the privilegies from that user on Wazuh App, meaning we will need read / write data permissions.

**Comment by tatdatpham** [comment]
@snaow  sure, type is "ossec-alert"
![image](https://cloud.githubusercontent.com/assets/3429970/26211046/b0126934-3c1b-11e7-9c55-0957dbf9dfb6.png)

> have you install x-pack plugin for Kibana? 
Yes.

> What user do you have set in kibana.yml? 
"Elastic".

> If you are using X-Pack, have you install x-pack plugin for Kibana? What user do you have set in kibana.yml? We are inheriting the privilegies from that user on Wazuh App, meaning we will need read / write data permissions.

 "Elastic" is user default (xpack) and this user have full privilegies  (super admin)

**Comment by snaow** [comment]
Hi @tatdatpham,

I think we discovered what is happening in your installation.
I did replicate your environment (just to be sure) using a different document type, "ossec-alert", like you have.

Wazuh App is performing all the request looking for "wazuh" type, if you have a different type, it won't work.
The reason to do this is purely performance, Elasticsearch is faster if we specify a document type.
You could take a look to the Logstash configuration template in Wazuh repository:

> https://github.com/wazuh/wazuh/blob/master/extensions/logstash/01-wazuh.conf#L38

Let me know if that change fix your issue.
Best,
Pedro.

**Comment by tatdatpham** [comment]
thanks for your support. I found my problem.
I setup API in setting on kibana but after that, i changed hostname server Ossec manager. So it's problem.
I try to remove api and add api again, Everything is woking. 
Thanks !

**Comment by snaow** [comment]
Great @tatdatpham I am glad you finally solved the issue.
I am curious, did you change the document type as well isn't it ? 

Best,
Pedro.

**Comment by tatdatpham** [comment]
@snaow  . sure, i must change document_type to "wazuh". Overview tab is worked with "wazuh" type 👍
