### ISSUE TITLE
Pagination is not shown in table-type visualizations long alerts

### ISSUE THREAD

**Issue by Joanes04** [wazuh/wazuh-kibana-app#2203]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.12.2   | 7.6.2     | n/a |

**Description**
The pagination controls in the table-type Kibana visualizations are not shown depending on the size of the box.

**Steps to reproduce**

1. Go to any dashboards
2. Navigate to the Alerts Summary table, with the titles of the very long alerts
3. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/9945959/80111964-8b588900-854e-11ea-9c3a-4adaee60552c.png)

![image](https://user-images.githubusercontent.com/9945959/80112056-a925ee00-854e-11ea-9440-fead499a0dc7.png)

**Comment by juankaromo** [comment]
This has been fixed for the next release of Wazuh 3.13

![vulnspagination](https://user-images.githubusercontent.com/21195730/80190865-36337a80-8615-11ea-8dd4-903510b54711.gif)

Regards,
