### ISSUE TITLE
Format options in wazuh-alerts index-pattern overwritten by Wazuh plugin

### ISSUE THREAD

**Issue by migruiz4** [wazuh/wazuh-kibana-app#2207]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.12.2   | 7.6.2     | 444 |

**Description**
Any custom format option applied to the wazuh-alerts-3.x-* index-pattern is overwritten and removed when the Wazuh plugin performs the knownFields refresh.

This issue is caused because the app does consider dynamic and custom fields in the configuration, but the FieldFormat configuration is updated with a static dictionary, overwriting any user change. (Lines 291-295)

https://github.com/wazuh/wazuh-kibana-app/blob/b1aff90794dea780db5a210fd9a01328c0eebaf1/server/lib/elastic-wrapper.js#L281-L300

**Steps to reproduce**

1. Go to 'Management>Kibana>Index-patterns>wazuh-alerts-3.x-*'
2. Edit any field name and change its format. For example, add URL format to a 'string' field.
3. Open Wazuh app and make sure the 'Checks' page appears (Open incognito mode if not)

**Screenshots**
Steps 1-2
![image](https://user-images.githubusercontent.com/37381070/80242253-5f7bf700-8665-11ea-8f74-2df19af06b7b.png)

Step 3
![image](https://user-images.githubusercontent.com/37381070/80242464-af5abe00-8665-11ea-9933-092b3b4657a9.png)

Step 4
![image](https://user-images.githubusercontent.com/37381070/80242603-e3ce7a00-8665-11ea-924b-99a70237a769.png)

**Additional context**
This issue happens with any field, custom or not. Only fields `data.virustotal.permalink`, `data.vulnerability.reference` and `data.url` keep their format as it is hardcoded in the plugin.

**Comment by juankaromo** [comment]
Hi @migruiz4 

This has been fixed here https://github.com/wazuh/wazuh-kibana-app/issues/2425, along with the removal of all known fields logic. This will be fixed from 4.0.

Regards,
