### ISSUE TITLE
Enable new panels for Vulns and AWS

### ISSUE THREAD

**Issue by toniblyx** [wazuh/wazuh-kibana-app#221]
Hi, 
I have enabled Vuls and AWS (3.1) and I don't find documentation to enable their panels in Kibana. Would you mind to point me to the right direction please?
Thanks in advance!

**Comment by JuanjiJG** [comment]
Hi @toniblyx,

Currently, our latest version of the Wazuh App has an extension for Amazon Web Services and VirusTotal, in addition to the already existing extensions (PCI, OpenSCAP and Audit). The team is working on a VULS tab for the app, and it will be available in the next release.

To enable or disable the extensions, go to the `Settings` tab of the app (located on the upper right corner of the app interface).
![paso1](https://user-images.githubusercontent.com/10928321/35553397-10244a36-0598-11e8-9d47-85b85b4c1b3e.PNG)

Then, you need to open the `Extensions` tab and enable or disable the extensions you need.
![paso2](https://user-images.githubusercontent.com/10928321/35553441-3107f748-0598-11e8-8c27-852956235b94.png)

Now you can go to `Overview` or `Agents` and you will see the tabs enabled according to your Extensions preferences.

Feel free to comment again if you still have questions or issues about anything related to Wazuh.

Best regards,
Juanjo

**Comment by toniblyx** [comment]
Thanks @JuanjiJG, I knew that section but I only see PCI-DSS, OpenSCAP and Audit extensions. How can I add the new ones?
Using App version 3.1.0, Revision 0378

**Comment by JuanjiJG** [comment]
Hello again @toniblyx,

My apologies, I used a development version of the App to capture that screenshot. Our latest stable release is the 378 revision, which doesn't contain this new tabs.

I will let you know when we release a new version of the app, which will contain the new ones. Thanks for your patience.

Regards,
Juanjo

**Comment by toniblyx** [comment]
Thanks!

**Comment by JuanjiJG** [comment]
Hi @toniblyx,

We recently released a new version of the Wazuh App, both compatible with Kibana 6.1.2 and 6.1.3, bugfixes, performance improvement, a better error handler and new AWS and VirusTotal tabs.

You can download them right now and install with the following commands (as superuser):

1. **Stop Kibana**:
`systemctl stop kibana`

2. **Remove the old Wazuh App**:
`/usr/share/kibana/bin/kibana-plugin remove wazuh`

3. **Delete the optimizing bundles**. Don't worry, they will be re-generated after restarting the service:
`rm -rf /usr/share/kibana/optimize/bundles`

4. **Install the new Wazuh App plugin**:
    * **For Wazuh 3.1 and Elastic 6.1.2**: `/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.1.0_6.1.2.zip`
    * **For Wazuh 3.1 and Elastic 6.1.3**: `/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.1.0_6.1.3.zip`

On the next days, we will release a new version of Wazuh and the Wazuh App, with a brand-new vulnerabilities functionality, and also a new tab on the app. For now, you can enjoy our latest and revised version, and I will let you know when we release the next version.

Best regards,
Juanjo

**Comment by toniblyx** [comment]
Thanks Juanjo, that worked like a charm.

Now I'm dealing with AWS logs and getawslog.py which is a bit tricky, I'll probably open another issue about it soon. Thanks again and good job!

**Comment by JuanjiJG** [comment]
Hi @toniblyx,

I'm glad you solved your problem! Don't hesitate to post a new issue if you have more doubts or problems with Wazuh, we'll be happy to help you. :)

Best regards,
Juanjo
