### ISSUE TITLE
Fix reference column in Alert summary table

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh-kibana-app#2214]
**Description**
As part of the [Epic 4749](https://github.com/wazuh/wazuh/issues/4749), we made some modifications to the `vulnerability-detector` alerts fields. One of the changes is the removal of the `reference` string field (it was the vulnerability URL) and the inclusion of the `references` JSON array field (now we have an array of URLs).
As a result of this change, we lost the table displayed in the Alerts summary. The reason is that this table was making use of the `reference` field for one of its columns.
We suggest removing this column in order to get back the table and lets the user the possibility to know the references by expanding the alerts.

**Steps to reproduce**

1. Configure the vulnerability-detector in the Wazuh manager to perform vulnerability scans in any registered agent.
2. Wait for the scan and go to the Wazuh app in Kibana. Open an agent and click on vulnerabilities. You will si a list of alerts in the table **Alerts summary**
3. Upgrade the Wazuh manager to a version including the changes implemented in [Epic 4749](https://github.com/wazuh/wazuh/issues/4749) and wait for a new scan.
4. Go again to the agent vulnerabilities and you will see the **Alerts summary** table empty.

**Screenshots**

- Before
![image](https://user-images.githubusercontent.com/5703274/80613225-5c8d5780-8a13-11ea-9cb8-d095ce710266.png)

- After
![image](https://user-images.githubusercontent.com/5703274/80613260-69aa4680-8a13-11ea-9dd8-7b9fb2c32804.png)

**Comment by Joanes04** [comment]
Hi @DProvinciani ,

We have modified the vulnerability alert summary table. Now we don't show the **reference** anymore, but we show the **CWE Reference** field. The modifications have been included both for **Overview** and for the **agent** view, as the images show:

**Overview**

![image](https://user-images.githubusercontent.com/9945959/81588518-a4eb3480-9386-11ea-95e8-ab50ec07b6c0.png)

**Agents**

![image](https://user-images.githubusercontent.com/9945959/81588632-cfd58880-9386-11ea-9b54-f06b84f21714.png)

**Comment by DProvinciani** [comment]
Great! Just one question. Have you reviewed this with other teammates? The thing is that the CWE reference is not provided for all the alert reports. This is information that will depend on the feed that generates the vulnerability alert.
In my current vulnerability database, there are 7395 over 102119 CVEs that don't contain this information.

**Comment by Joanes04** [comment]
Hi @DProvinciani,

It has been discussed with the team, and it has been a proposal from @chemamartinez 

Kind regards,
Alberto

**Comment by chemamartinez** [comment]
Hi @DProvinciani, @wazuh/frontend, @Joanes04,

I proposed adding one of the remaining metadata fields to complete the table, and suggested two as examples that could fit in it: the `published` date and the `CWE reference`. As Diego has discovered, the CWE could not be present for some CVEs, so I think it is better to replace it by `published`.

In my current DB, the field `published` is only missing for one CVE of more than 200.000 entries.

Best regards,
Chema.

**Comment by Joanes04** [comment]
Hi @DProvinciani and @chemamartinez,

As you mentioned, we have modified the table so that it appears Published and not CWE reference. We show two images of how it looks:

**Overview**

![image](https://user-images.githubusercontent.com/9945959/81691701-36ac7d80-942b-11ea-87ac-47e1fe27f10e.png)

**Agents**

![image](https://user-images.githubusercontent.com/9945959/81692122-e84bae80-942b-11ea-914b-8dc993a0f757.png)

Best regards,
Alberto

**Comment by DProvinciani** [comment]
Looks great! Thanks @Joanes04!
