### ISSUE TITLE
Add support to Opendistro

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-kibana-app#2219]
The default configuration of Kibana with Opendistro does not work properly. Some requests made from Kibana to Elasticsearch are not being handled and generate some unexpected errors and behaviors.

These requests are classified into three groups:
1. Request made by the user
2. The request made by the WazuhUI for statistics and configuration
3. The request made by the WazuhUI to create and maintain `wazuh-monitoring`

#### Request made by the user:
- Generate Reports
![image](https://user-images.githubusercontent.com/3064506/81046246-3b67b380-8eb8-11ea-924c-d69c93c0642c.png)

- Get alerts from integrity monitoring
![image](https://user-images.githubusercontent.com/3064506/81046923-a665ba00-8eb9-11ea-8f47-59a27525faa4.png)

 

#### Request made by the WazuhUI for statistics and configuration
- Top agent in agents summary
![image](https://user-images.githubusercontent.com/3064506/81046738-4ff87b80-8eb9-11ea-8c4c-137988ea15fa.png)

- Initialize the WazuhUI
![image](https://user-images.githubusercontent.com/3064506/81047159-27bd4c80-8eba-11ea-9c6d-d5099abec052.png)

#### Request made by the WazuhUI for `wazuh-monitoring`
- Cloud does not check if the index exists
![image](https://user-images.githubusercontent.com/3064506/81047212-415e9400-8eba-11ea-819b-ce0cd8e7aa1c.png)

To solve this it is necessary to modify some requests to use the authorization context of the registered user in Kibana.
On the other hand, it is necessary to generate a new Opendistro role to extend the authorization context of the user `kibanaserver` and explain how to configure it in the Wazuh documentation.

**Comment by juankaromo** [comment]
Related issue #1319

**Comment by jsanchez91** [comment]
This is the basic configuration of the WazuhUI role

```js
{
  "index_permissions": [
    {
      "index_patterns": [
        "wazuh-*",
        ".wazuh*"
      ],
      "dls": "",
      "fls": [],
      "masked_fields": [],
      "allowed_actions": [
        "indices_all"
      ]
    }
  ],
  "tenant_permissions": [],
  "cluster_permissions": []
}
```

**Comment by jsanchez91** [comment]
Two new roles:

**wazuh_ui_admin**
```json
{
  "index_permissions": [
    {
      "index_patterns": [
        "wazuh-*"
      ],
      "dls": "",
      "fls": [],
      "masked_fields": [],
      "allowed_actions": [
        "indices_all"
      ]
    },
    {
      "index_patterns": [
        ".kibana",
        ".kibana*"
      ],
      "dls": "",
      "fls": [],
      "masked_fields": [],
      "allowed_actions": [
        "read",
        "delete",
        "manage",
        "index"
      ]
    }
  ],
  "tenant_permissions": [],
  "cluster_permissions": []
}
```

**wazuh_ui_user**
```json
{
  "index_permissions": [
    {
      "index_patterns": [
        "wazuh-*"
      ],
      "dls": "",
      "fls": [],
      "masked_fields": [],
      "allowed_actions": [
        "read"
      ]
    }
  ],
  "tenant_permissions": [],
  "cluster_permissions": []
}
```
