### ISSUE TITLE
Reporting was aborted error

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#2220]
**Description**
It has been reported that on occasion certain users when they click on generate reports page shows an error `5029 - Reporting was aborted (Cannot read property '2' of undefined) (/reports)` and
no report is generated.

**Steps to reproduce**

1. Go to a Dashboard
2. Click on Report
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/21195730/81065823-7b409200-8edc-11ea-857a-954e3669d7f1.png)

**Comment by MagnusVMI** [comment]
I have the same issue, seems to work on inventory but not when tring to export securty events or  Integrity monitoring.
Do you need more information about this bug?

/ Magnus

**Comment by jsanchez91** [comment]
This may be resolved in branch `4.0-7.8.0-RBAC`, but needs to be confirmed

**Comment by pablotr9** [comment]
All dashboard report have been checked and sections that fail have been fixed here: https://github.com/wazuh/wazuh-kibana-app/pull/2494

**Comment by CW-7CS** [comment]
I have still had this exact same issue after installing wazuh yesterday.
