### ISSUE TITLE
strange problem with opendistro and wazuh-app

### ISSUE THREAD

**Issue by mareban** [wazuh/wazuh-kibana-app#2229]
Hi,

I try to install wazuh-app 3.12.3_7.6.1 for odfe (es 7.6.1) and the installation seems to be OK, index alert and monitoring were created !

But when i go to kibana, select the wazuh app no results are shown !!!
I check what was indexed and the timestamp, manager.name, and agent.id field was not there !!
So i enrich the log with fluentd who receive the log from the filebeat (with wazuh module installed) and put a timestamp field (in UTC) and force the manager.name to the name of my wazuh-manager to have some results shown, but for the agent.id i don't know what to do because this field comes from the registered agent, and the agent id is a string like this 
![image](https://user-images.githubusercontent.com/11810873/81471920-fa8fd780-91f4-11ea-8a36-de8f59afc4ea.png)

I've tried to remove and reinstall wazuh-app several time, and still have the problem :-(

Is it a known problem, do i miss something, why some fields are not indexed (timestamp, manager.name), and why the app cannot select the agent because the filter looks for a 001 and the agent.id is a string like "....-....-....-) ?? If i select the agent manually and save it, the results are shown for that agent.

Can someone help me please ?

Thank you.

**Comment by mareban** [comment]
I forgot to mention that no .wazuh was created too ! Maybe downgrade to 3.11 or 3.10 would help ??

Thx.

**Comment by jsanchez91** [comment]
Hi @mareban,

The agent.id value is created by Filebeat.

Could you share your Filebeat.yml with me to check it out?

**Comment by mareban** [comment]
Hello, 

Thanks for your reply ! Here it is below !
I've followed the install procedure from the Wazuh Website, maybe i've missed something ?
I had no problem on my previous installation with an  older version of wazuh and ES 7.3.1 :-) 

Thanks for your help.

 

# Wazuh - Filebeat configuration file
filebeat.modules:
  - module: wazuh
    alerts:
      enabled: true
    archives:
      enabled: false

      setup.template.json.enabled: true
      setup.template.json.path: '/etc/filebeat/wazuh-template.json'
      setup.template.json.name: 'wazuh'
      setup.template.overwrite: true
      setup.ilm.enabled: false

tags: ["ossec"]

#filebeat_prospectors:
#processors:
#       - add_fields:
#                fields: 
#  source:filebeat
#               timestamp: {current time}

output.logstash.hosts: ['localhost:5044']

**Comment by mareban** [comment]
oohh sorry for markdown

**Comment by jsanchez91** [comment]
Your Filebeat settings don't seem to be the latest version. Could you try updating your Filebeat settings?

To update follow these steps:

Update your `filebeat.yml` file
```bash
curl -so /etc/filebeat/filebeat.yml https://raw.githubusercontent.com/wazuh/wazuh/v3.12.3/extensions/filebeat/7.x/filebeat.yml
chmod go+r /etc/filebeat/filebeat.yml
```

I see you use logstash, if you don't have any sub-process in logstash you can send the alerts directly with Filebeat to Elasticsearch. Edit the last line of the `filebeat.yml`:
```yml
# Send to logstash
output.logstash.hosts: ['localhost:5044']

# Send to elasticsearch
output.elasticsearch.hosts: ['http://localhost:9200']
```

Download the index template:
```bash
curl -so /etc/filebeat/wazuh-template.json https://raw.githubusercontent.com/wazuh/wazuh/v3.12.3/extensions/elasticsearch/7.x/wazuh-template.json
chmod go+r /etc/filebeat/wazuh-template.json
```

Download the Wazuh module for Filebeat:
```bash
curl -s https://packages.wazuh.com/3.x/filebeat/wazuh-filebeat-0.1.tar.gz | sudo tar -xvz -C /usr/share/filebeat/module
```

Restart filebeat:
```bash
systemctl daemon-reload
systemctl enable filebeat.service
systemctl start filebeat.service
```
Check if your new alerts have the right agent.id and let me know.

**Comment by mareban** [comment]
Hello,

It was what i've done, but i remove filebeat-oss, reinstall it with the same config file and module !!
I configure the elasticsearch output instead of logstash (forward to a fluentd agent), ilm is disabled and i've got an error from ES (elasticsearch-oss with opendistro), and i' got a message saying that thereis a permission issue to create the _xpack index !!??

If i put my initial config file, everything are indexed, but still problem with timestamp, agend.id and manager.name, and still no .wazuh index created !

This need to be set by filebeat, but   i'm confused about how is it done : with the wazuh module or with the fields.yml ??

Thanks for your help.

**Comment by jsanchez91** [comment]
Sorry for the late response,

I have some questions:

Did you remove Filebeat-oss and reinstall Filebeat-oss or did you install Filebeat?

The 'wazuh' index was removed in version 3.11, the WazuhUI does not create this index in version 3.12. May you have problems if your Kibana internal user doesn't have permissions to check if it exists on start the application.
WazuhUI migrates the configuration of `.wazuh` if it exists to wazuh.yml.

Generate a new role with allowed actions `all_indices` on these index patterns: `wazuh-*`, `.wazuh*`.

On the other hand, could you share with me an alert with the wrong fields?

**Comment by mareban** [comment]
Hello,

Thanks for you reply !

yes i've reinstalled filebeat-oss (same version as elasticsearch-oss for odfe), and the wazuh app too !

For the permission problem, i've gave the all_access role to kibanaserver in the meantime.

So, i''ll no more worry about the .wazuh anymore :-)

I 've no alert, in the discovery panel i can't see anything cause of the timestamp not filled (that's why fill up it with fluentd), same for manager.name, and for the agent-id (i can't do that for the moment), if i select the right agent.id it's OK !

But i've seen a post about wazuh app overwriting  the index pattern (and excluding the @timestamp), and have the same problem too.

I don't know what to do, but i know that i had no problem with odfe en es 7.3.1 ! 

I don't know if it is a broken change or if i miss something maybe, but i double/triple check, and i don't know what to do to use Wazuh as i used to do until my update !!

Is the 3.11 would be a better plan ??

If you need some more information, you're welcome.

Thanks for your help, i'll appreciate.

**Comment by mareban** [comment]
Hello,

Finally, i send the filebeat logs directly to elasticsearch, and everything is OK  now :-) ! Here is a copy of my filebeat.yml :   

**# Wazuh - Filebeat configuration file
filebeat.modules:
  - module: wazuh
    alerts:
      enabled: true
    archives:
      enabled: false

setup.template.json.enabled: true
setup.template.json.path: '/etc/filebeat/wazuh-template.json'
setup.template.json.name: 'wazuh'
setup.template.overwrite: true
setup.ilm.enabled: false

tags: ["ossec"]

output.elasticsearch.hosts: ['localhost:9200']
output.elasticsearch.username: xxxxxxxxx
output.elasticsearch.password: 'xxxxxxxx'
output.elasticsearch.protocol: https
output.elasticsearch.ssl.verification_mode: none
output.elasticsearch.setup.ilm.enabled: false
output.elasticsearch.setup.template.name: 'wazuh'
output.elasticsearch.setup.template.pattern: 'wazuh-alerts-3.x-*'**


 Thank you very much for your help.

All the best.
