### ISSUE TITLE
after kibana install wazuh-app, kibana can't start correctly

### ISSUE THREAD

**Issue by yimingsir** [wazuh/wazuh-kibana-app#2235]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| v3.12.3 | 7.6.2 | 444 |

**Description**
kibana can run correctly. after kibana install wazuh-app, kibana can't start correctly.
kibana version 7.6.2
wazuh-app version 3.12.3
I install wazuh-app using the steps by offical document.
link: https://documentation.wazuh.com/3.12/installation-guide/installing-elastic-stack/elastic_server_deb.html

kibana page show "Kibana server is not ready yet"

kibana error log 

> May 15 11:06:21 172-16-244-28 kibana[24902]: {"type":"log","@timestamp":"2020-05-15T03:06:21Z","tags":["info","plugins","apm"],"pid":24902,"message":"Setting up plugin"}
May 15 11:06:21 172-16-244-28 kibana[24902]: {"type":"log","@timestamp":"2020-05-15T03:06:21Z","tags":["info","plugins","share"],"pid":24902,"message":"Setting up plugin"}
May 15 11:06:21 172-16-244-28 kibana[24902]: {"type":"log","@timestamp":"2020-05-15T03:06:21Z","tags":["info","plugins","bfetch"],"pid":24902,"message":"Setting up plugin"}
May 15 11:06:21 172-16-244-28 kibana[24902]: {"type":"log","@timestamp":"2020-05-15T03:06:21Z","tags":["info","savedobjects-service"],"pid":24902,"message":"Waiting until all Elasticsearch nodes
May 15 11:06:21 172-16-244-28 kibana[24902]: {"type":"log","@timestamp":"2020-05-15T03:06:21Z","tags":["info","savedobjects-service"],"pid":24902,"message":"Starting saved objects migrations"}
May 15 11:06:21 172-16-244-28 kibana[24902]: {"type":"log","@timestamp":"2020-05-15T03:06:21Z","tags":["info","plugins-system"],"pid":24902,"message":"Starting [22] plugins: [taskManager,siem,lic
May 15 11:06:24 172-16-244-28 kibana[24902]: {"type":"log","@timestamp":"2020-05-15T03:06:24Z","tags":["info","optimize"],"pid":24902,"message":"Optimizing and caching bundles for core, graph, mo
May 15 11:06:27 172-16-244-28 kibana[24902]: Browserslist: caniuse-lite is outdated. Please run next command `npm update`
May 15 11:06:27 172-16-244-28 kibana[24902]: Browserslist: caniuse-lite is outdated. Please run next command `npm update`
May 15 11:06:27 172-16-244-28 kibana[24902]: Browserslist: caniuse-lite is outdated. Please run next command `npm update`

**Comment by jsanchez91** [comment]
Hi @yimingsir,

Did you execute this command?

```bash
cat >> /etc/default/kibana << EOF
NODE_OPTIONS="--max_old_space_size=2048"
EOF
```

**Comment by yimingsir** [comment]
> Hi @yimingsir,
> 
> Did you execute this command?
> 
> ```shell
> cat >> /etc/default/kibana << EOF
> NODE_OPTIONS="--max_old_space_size=2048"
> EOF
> ```

After execution, still report the error

**Comment by jsanchez91** [comment]
Do you restart Kibana after executing the command?
```bash
systemctl restart kibana
```

If you have restarted Kibana, could you run this command and share the output?

```bash
journalctl -xe | grep "kibana"
```

**Comment by yimingsir** [comment]
> Do you restart Kibana after executing the command?
> 
> ```shell
> systemctl restart kibana
> ```
> 
> If you have restarted Kibana, could you run this command and share the output?
> 
> ```shell
> journalctl -xe | grep "kibana"
> ```

After restart kibana and waiting for a while, kibana run normal.
Thanks your answer.
