### ISSUE TITLE
ODFE 1.7 - Wazuh app not compatible

### ISSUE THREAD

**Issue by TaLoN1x** [wazuh/wazuh-kibana-app#2236]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.12   | 7.6.1     | 874 / 593 |

**Description**
After installing wazuh-kibana-app on Open Distro For Elasticsearch 1.7.0 Kibana is refusing to start up. Crashes with following error:
May 15 14:41:48 localhost kibana[117388]: FATAL  Error: only one instance of babel-polyfill is allowed

**Steps to reproduce**

1. Install ODFE1.7
2. Install Wazuh-App on kibana
3. Start service

**Additional context**
I have tried both Revision 874 and 593, all resulted in same problem. Removing of the plugin, full reinstallation of Kibana and even deployment on new cluster results with the same outcome.

**Comment by antonisnyc94** [comment]
To fix this you should edit: 
/usr/share/kibana/plugins/wazuh/node_modules/babel-polyfill/lib/index.js

And replace:
if (global._babelPolyfill) {
  throw new Error("only one instance of babel-polyfill is allowed");
}
global._babelPolyfill = true;


**WITH:**
if (global._babelPolyfill) {
 global._babelPolyfill = false;
}
 else {
global._babelPolyfill = true;}

**Comment by TaLoN1x** [comment]
thnx you. It helped

**Comment by jsanchez91** [comment]
This error will be corrected in the next release.

We have removed the "babel-polyfill" from our dependencies because Kibana now integrates this package.

On the other hand, we have changed the "simple-tail" package because it was trying to get the "babel-polyfill" from the node_modules folder of the WazuhUI plugin.

**Comment by gittygoo** [comment]
@jsanchez91  Getting the same problem , i have noticed a new wazuhapp-3.12.3_7.7.1 release, is this fixed there?

**Comment by jsanchez91** [comment]
Hi @gittygoo,

We have updated the package in v3.12.3-7.7.0, with the fix for this bug.
Try installing the package again, if you have any problems or doubts do not hesitate to ask.
