### ISSUE TITLE
Additional default filter for kibana

### ISSUE THREAD

**Issue by srikarduplo** [wazuh/wazuh-kibana-app#2237]
Can we have an additional default rule level filter apart from the existing one(manager.name: wazuh-manager), say rule.level >7.

Context: There is an option in the wazuh config to log alerts more than a particular level. But the compliance standard wants all the data to be available for auditing purpose. So I dont want to change the config and let all alerts save to ES for auditing. And for the display, if we show all the alerts it would be cumbersome. So instead if we have this additional filter(rule.level>7) by default in kibana, it would be easier for person who looks at the issues in kibana.

**Comment by jsanchez91** [comment]
Hi @srikarduplo,

The search bar has a method for saving your custom queries and filters. You might find this interesting.

In this animation, you can see how to save a query for later use.
![saved_filters](https://user-images.githubusercontent.com/3064506/82233033-accf4980-992f-11ea-8196-680be72c7c5e.gif)

On the other hand, it could be interesting to add global custom filters in the WazuhUI configuration, we will take it into account for future developments.

**Comment by TaLoN1x** [comment]
I find this extremely useful for my deployment also. The level could be costumisable

**Comment by MalekBerrich** [comment]
Hi @jsanchez91 
By default, the Wazuh server monitors its own ip address . In my case i got another wazuh manager(another ip address) sending alerts to the first manager so how can I see these alerts (change filtred ip address) 
![image](https://user-images.githubusercontent.com/77490947/203780831-aad72753-f75c-4a17-909c-532695175beb.png)
