### ISSUE TITLE
Compatible wazuh plugin with Kibana 7.7

### ISSUE THREAD

**Issue by nenominal** [wazuh/wazuh-kibana-app#2238]
I've updated the ELK stack to 7.7 and unfortunately the Wazuh plugin is not compatible.

`Plugin installation was unsuccessful due to error "Plugin wazuh [7.6.2] is incompatible with Kibana [7.7.0]"
`
Do you plan to have a fix compatibility to this version or should I downgrade ?

**Comment by juankaromo** [comment]
Hi @nenominal 

Elastic 7.7.0 was released really recently, so we are testing it for any breaking change and release a version as robust as possible. We hope to have it ready very very soon if all testing goes well and It will be released in a few days, with the current or with the new version of Wazuh (3.13.0). I'll let you know here when we have it.

Thanks for the patience!

Regards.
Juan Carlos

**Comment by nenominal** [comment]
@juankaromo , thanks man, I have all the patience with this great project :-)
Keep up the good work and I'll test it when it's out.

**Comment by juankaromo** [comment]
Wazuh 3.12.3 with support for ELK 7.7.0 has just been released. 

Here is the link to the Wazuh app https://packages.wazuh.com/wazuhapp/wazuhapp-3.12.3_7.7.0.zip
