### ISSUE TITLE
It still shows enabled when disabling Vulnerability Decetor in ossec.conf

### ISSUE THREAD

**Issue by JayceCao** [wazuh/wazuh-kibana-app#2239]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.11.0   | 7.5.1     | |

**Description**
I already disabled `Vulnerability Decetor` in ossec.conf, but in `Management -> Configuration -> Vulnerabilities`, it still shows `enabled`.

**Screenshots**
![image](https://user-images.githubusercontent.com/17915615/82418715-e7f88680-9aaf-11ea-9652-52a77432c602.png)
![image](https://user-images.githubusercontent.com/17915615/82418764-f9419300-9aaf-11ea-8d4a-366c9d997579.png)

**Comment by Desvelao** [comment]
Hi @JayceCao, it seems that is a bug, it will be fixed in upcoming releases.

Thank you very much for reporting this problem.

Best regards.

**Comment by juankaromo** [comment]
Fixed here https://github.com/wazuh/wazuh-kibana-app/commit/fb6ae439ea49fcf24a4be647d865896319791238
