### ISSUE TITLE
Develop-new-features

### ISSUE THREAD

**Issue by DyyDOS** [wazuh/wazuh-kibana-app#2246]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.12.3  | 7.6.2    | 0874|

**Description**
Clone wazuh-kibana-app into source code kibana, start kibana get issuse loop restart at change wazuh-registry.json", no error appear
**Steps to reproduce**
1. I used to link tutorial https://github.com/wazuh/wazuh-kibana-app/wiki/Develop-new-features by Jesús Ángel 
2. Yarn start kibana 
![image](https://user-images.githubusercontent.com/21251999/82854886-ee658300-9f33-11ea-8fe1-9deef3dda35f.png)
3. I checked log wazuh, log below
![image](https://user-images.githubusercontent.com/21251999/82854937-15bc5000-9f34-11ea-829a-ec61f9aa5edd.png)

**Comment by jsanchez91** [comment]
Hello @DyyDOS,

Add the `--no-watch` option to the "yarn start" command.

```bash
yarn start --no-base-path --server.host="0.0.0.0" --elasticsearch.url="http://elastic" --no-watch
```

**Comment by DyyDOS** [comment]
hi @jsanchez91 , thanks you so much
