### ISSUE TITLE
Wazuh icon in kibana is oversized in kibana 7.7 in dark mode

### ISSUE THREAD

**Issue by s3curetty** [wazuh/wazuh-kibana-app#2247]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.12   | 7.7     | latest |

**Description**
Wazuh icon in kibana is oversized in kibana 7.7 in dark mode

**Steps to reproduce**

1. Enable dark mode in kibana
2. Open sidebar
3. Observe the wazuh icon

**Screenshots**
![Screenshot_20200526_192608](https://user-images.githubusercontent.com/6697226/82910877-cc4a2000-9f88-11ea-9642-dca660933d29.png)

**Comment by Joanes04** [comment]
Hi @s3curetty,

Thank you very much for the feedback, we take note and for the next version 3.13 it will be solved. When we have the fix of the problem I'll let you know in this issue.

Thanks again!

**Comment by Joanes04** [comment]
Hi @s3curetty ,

We have already fixed the bug in the next commit: https://github.com/wazuh/wazuh-kibana-app/commit/0eb7176026dd7245d3225bd808c6f9a3017f3609

As I told you before, this solution will be in the new version 3.13. Thank you very much for sharing the bug, I proceed to close the issue.

**Comment by s3curetty** [comment]
Thanks @Joanes04 that was swift.
