### ISSUE TITLE
ERROR Could not check if the index wazuh-monitoring-3.x-*

### ISSUE THREAD

**Issue by tdslot** [wazuh/wazuh-kibana-app#2249]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.12.3   | 7.6.2    | 0874 |

**Description**
Couple days ago we did upgrade of `KIBANA_VERSION = 7.6.0` and `WAZUH_VERSION = 3.11.3`
to `KIBANA_VERSION = 7.6.2` and `WAZUH_VERSION = 3.12.3`
In kibana log file located at `/usr/share/kibana/optimize/wazuh/logs/wazuhapp.log` we getting error massage `ERROR Could not check if the index wazuh-monitoring-3.x-2020.05.27 exists due to Authorization Exception`.

In documentation is written that index should be created automatically but there is no any index in index list.

How we can solve this error?

**Comment by pablotr9** [comment]
Hi @tdslot,

In this case the user that is doing requests into Elasticsearch is the user configured in the `kibana.yml` file (`elasticsearch.username`) and not the currently logged in user. It looks like that user doesn't have enough permissions to read and write from `wazuh-monitoring-3.x*` indices so please check that it has enough permissions to read/write from wazuh-* indices.

Could you also please check logs from Elasticsearch and share those logs with me? You can find Elasticsearch logs here:
`cat /var/log/elasticsearch/<clusterName>.log `
(you will have to replace clusterName with the name of your cluster, or if you didn't set any name by default its name will be `elasticsearch`)

Regards,

**Comment by tdslot** [comment]
Hello @pablotr9 ,

I checked user and is running  under kibana user with all administration permissions.
```
{
    "kibana": {
        "username": "kibana",
        "roles": [
            "kibana_system"
        ],
        "full_name": null,
        "email": null,
        "metadata": {
            "_reserved": true
        },
        "enabled": true
    }
}
```

Here is also `kibana_system` role config:
```
{
    "kibana_system": {
        "cluster": [
            "monitor",
            "manage_index_templates",
            "cluster:admin/xpack/monitoring/bulk",
            "manage_saml",
            "manage_token",
            "manage_oidc",
            "cluster:admin/xpack/security/privilege/builtin/get",
            "delegate_pki",
            "cluster:admin/ilm/get",
            "cluster:admin/ilm/put"
        ],
        "global": {
            "application": {
                "manage": {
                    "applications": [
                        "kibana-*"
                    ]
                }
            }
        },
        "indices": [
            {
                "names": [
                    ".kibana*",
                    ".reporting-*"
                ],
                "privileges": [
                    "all"
                ],
                "allow_restricted_indices": false
            },
            {
                "names": [
                    ".monitoring-*"
                ],
                "privileges": [
                    "read",
                    "read_cross_cluster"
                ],
                "allow_restricted_indices": false
            },
            {
                "names": [
                    ".management-beats"
                ],
                "privileges": [
                    "create_index",
                    "read",
                    "write"
                ],
                "allow_restricted_indices": false
            },
            {
                "names": [
                    ".apm-agent-configuration"
                ],
                "privileges": [
                    "all"
                ],
                "allow_restricted_indices": false
            }
        ],
        "applications": [],
        "run_as": [],
        "metadata": {
            "_reserved": true
        },
        "transient_metadata": {
            "enabled": true
        }
    }
}
```
And I don't have logs where it shows something that is error related  with that index.

**Comment by pablotr9** [comment]
Hi @tdslot,

The `kibana_system` role has the necessary permissions for the management of Kibana indices, you can see that in the role config you shared with me that it only has permissions on these indices: `.kibana*, .monitoring*, .management-beats and .apm-agent-configuration` but it doesn't have any permission for Wazuh indices.
You will have to create a new role that includes all permissions for `wazuh*` indices and assign that new role to the user that is being used in the kibana.yml

**Comment by tdslot** [comment]
Hello @pablotr9 ,

Thank you for help. We created new user and role that inherits two roles:
 
- kibana_system (built-in)
- kibana-wazuh-app (new)

```
{
    "kibana-wazuh-app": {
        "cluster": [],
        "indices": [
            {
                "names": [
                    "wazuh-monitoring-3.x-*"
                ],
                "privileges": [
                    "all"
                ],
                "allow_restricted_indices": false
            }
        ],
        "applications": [],
        "run_as": [],
        "metadata": {},
        "transient_metadata": {
            "enabled": true
        }
    }
}
```

Now works and log there is no errors anymore.

Thanks.

Tadas
