### ISSUE TITLE
Change wazuh default index/default page.

### ISSUE THREAD

**Issue by tekletade** [wazuh/wazuh-kibana-app#2252]
I want to the default wazuh index interface, means now the index(first page) is Overview page; But in the first search I want to see Security events(i.e. Overview----->Security events) page,

I make it like this one <<server.defaultRoute: /app/wazuh>>, but by default it displays the overview page, but what i want is that make <<Security events>> page that is with in Overview as a default page,
I try it like below but not works:
server.defaultRoute: /app/wazuh/overview#/general     //general is the name of Security events link.

With thanks!

**Comment by Joanes04** [comment]
Hi @tekletade ,

Thank you very much for your idea. I have opened an issue to develop this feature. You can follow the evolution of it here #2258 

Again thank you very much for your contribution, anything you can contribute in the other issue.

Regards,
Alberto
