### ISSUE TITLE
Deprecate aws fields 

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-kibana-app#2260]
In version 3.13 the following fields change:

- `data.aws.awsRegion` to `data.aws.region`
- `data.aws.aws_account_id` to `data.aws.accountId`

To prevent loss of information, we will update the Filebeat pipeline to copy the old field into the new one in any alert containing it.

**Comment by jsanchez91** [comment]
Added two new ingests to the Filebeat module in this PR: https://github.com/wazuh/wazuh/pull/4459

![image](https://user-images.githubusercontent.com/3064506/84660341-fd2ecc80-af18-11ea-9b7c-ca56f4011d78.png)

**Comment by AlexRuiz7** [comment]
Closed by https://github.com/wazuh/wazuh/pull/4459
