### ISSUE TITLE
Not able download reports

### ISSUE THREAD

**Issue by nkhljswl** [wazuh/wazuh-kibana-app#2267]
Hi All,

I am getting below error while downloading reports.

    {"statusCode":403,"error":"Forbidden","message":"Forbidden"}

I am not using x-pack. Could anyone please help me out with this?

**Comment by Joanes04** [comment]
Hello @nkhljswl,

Could you tell us which version you are currently working on? We'd need to have the versions of both the ELK and Wazuh that you're working on.

It seems that the problem you are having may be due to a bad permission setting on the report folders. In the latest versions of Wazuh, the report is downloaded to the path: `/usr/share/kibana/optimize`
One possible solution may be to update the following permissions:

```
chown -R kibana:kibana /usr/share/kibana/optimize
chown -R kibana:kibana /usr/share/kibana/plugins
```

But it depends on which version of Wazuh UI you're using, I'm waiting for this information

Regards,
Alberto

**Comment by nkhljswl** [comment]
@Joanes04 

Thanks for the quick reponse.

Wazuh version "v3.12.3"
Kibana Version Kibana 7.7.0

I tried with both commands but no luck.

**Comment by Joanes04** [comment]
Hi @nkhljswl ,

I tried to reproduce your error and I didn't succeed. Are you using **customs spaces**? Could you share the permissions for the route: `/usr/share/kibana/optimize/wazuh/downloads`?

Regards,
Alberto

**Comment by nkhljswl** [comment]
Hi @Joanes04 

I am not using custom space. 

Please see the below permissions

    [root@wazuh-elk siemadmin]# ls -l /usr/share/kibana/optimize/wazuh/downloads
    total 0
    drwxr-xr-x. 2 kibana kibana 96 Jun 16 09:35 reports

**Comment by Joanes04** [comment]
Hi @nkhljswl ,

Could you send me a snapshot of the request that's returning status code 403? To access this request, you have to enter the web inspector in developer mode, and access the Network tab. Once inside, you have to try to download the report that causes the error, and access the payload of the call that returns the error 403.

![image](https://user-images.githubusercontent.com/9945959/84782733-abee0e00-afe8-11ea-9bf2-cd82471071f9.png)

I await your response,
Alberto

**Comment by nkhljswl** [comment]
Hi Alberto,

Please find the screenshot below.

![image](https://user-images.githubusercontent.com/29570856/84784624-9b935e80-affb-11ea-9e53-0d2ac35ac47a.png)

**Comment by Joanes04** [comment]
Hi @nkhljswl ,

Could you search that tab for the request that returned the 403 status and share the payload and what's in the "preview" tab?

I await your response, 
Alberto

**Comment by nkhljswl** [comment]
Hi @Joanes04 

I could't find any response with 403 status. I would like share one more information with you.

I am running kibana with root. 

`nohup node --max_old_space_size=4096 --no-warnings /usr/share/kibana/src/cli --allow-root &`

Not sure if this may be the reason of error. 

If i run kibana without root i get below error.
`[root@wazuh-elk nginx]# sudo -u kibana node --max_old_space_size=4096 --no-warnings /usr/share/kibana/src/cli`
`Kibana does not support the current Node.js version v10.21.0. Please use Node.js v10.19.0.`

But i am using v10.19.0 as default node.js version

![image](https://user-images.githubusercontent.com/29570856/85377197-c6c10500-b549-11ea-84e1-812ef5b12802.png)

**Comment by Joanes04** [comment]
Hi @nkhljswl ,

Definitely, the problem with the reports comes from running kibana with "root". 

In the image, we can see that you are using node version 10.19.0, but in **root**. You have to check which node version you have active without **root**. 
Try changing your node version, outside of **root**, and running kibana without **root**.

Another option can be to run kibana with the following command, which uses the node version that integrates kibana into your installation, so you should have no problems:

```
sudo -u kibana /usr/share/kibana/node/bin/node --max_old_space_size=4096 --no-warnings /usr/share/kibana/src/cli
```

Regards,
Alberto

**Comment by Joanes04** [comment]
Hi @nkhljswl ,

You seem to have the application installed incorrectly. I recommend that you make a new installation of the app, following the steps of the documentation (https://github.com/wazuh/wazuh-kibana-app)

You can perform an upgrade by following these steps (remember the version you have of Kibana and Wazuh for the installation package):

## Upgrade

Note: In Wazuh 3.12.0 (regardless of the Elastic Stack version) the location of the wazuh.yml has been moved from `/usr/share/kibana/plugins/wazuh/wazuh.yml` to `/usr/share/kibana/optimize/wazuh/config/wazuh.yml`.

Stop Kibana

- Systemd:

```
systemctl stop kibana
```

- SysV Init:

```
service kibana stop
```

Copy the wazuh.yml to its new location. (Only needed for upgrades from 3.11.x to 3.12.y)

```
mkdir -p /usr/share/kibana/optimize/wazuh/config
cp /usr/share/kibana/plugins/wazuh/wazuh.yml /usr/share/kibana/optimize/wazuh/config/wazuh.yml
```

Remove the app using kibana-plugin tool

```
cd /usr/share/kibana/
sudo -u kibana bin/kibana-plugin remove wazuh
```

Remove generated bundles

```
rm -rf /usr/share/kibana/optimize/bundles
```

Update file permissions. This will avoid several errors prior to updating the app:

```
chown -R kibana:kibana /usr/share/kibana/optimize
chown -R kibana:kibana /usr/share/kibana/plugins
```

Install the app

```
cd /usr/share/kibana/
sudo -u kibana bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.13.0_7.7.1.zip
```

Update configuration file permissions.

```
sudo chown kibana:kibana /usr/share/kibana/optimize/wazuh/config/wazuh.yml
sudo chmod 600 /usr/share/kibana/optimize/wazuh/config/wazuh.yml
```

Restart Kibana

- Systemd:

```
systemctl restart kibana
```
 
- SysV Init: 
 
``` 
service kibana restart 
```

**Comment by nkhljswl** [comment]
Thanks @Joanes04 

I need to plan the upgrade activity since i am running Wazuh on production. 

I need one more info. After upgrade, do I need to register agents again on Wazuh manager?

**Comment by Joanes04** [comment]
Hi @nkhljswl ,

You can follow the guide to update the official documentation: https://documentation.wazuh.com/3.13/upgrade-guide/upgrading/index.html

By following the steps correctly, you don't have to register again the agents in the Wazuh manager, they would still be configured once updated.

Any doubt, you can use our [slack channel](https://wazuh.com/community/join-us-on-slack/), our [Google group](https://groups.google.com/forum/#!forum/wazuh) or in our [Github](https://github.com/wazuh/).

Regards,
Alberto
