### ISSUE TITLE
New plugin for Kibana 7.8.0

### ISSUE THREAD

**Issue by VN1977** [wazuh/wazuh-kibana-app#2294]
Hi,
Today I have upgraded ELK to new version 7.8.0. New kibana has the different interface so there is no more wazuh image.
 
![изображение](https://user-images.githubusercontent.com/25663601/85108768-f35ae100-b218-11ea-98d2-7f14f8888b7a.png)

**Comment by victorst79** [comment]
Hi @VN1977 :wave: 

Elastic 7.8.0 was released really recently, so we are testing it for any breaking change and release a version as robust as possible. We hope to have it ready very very soon if all testing goes well and It will be released in a few days, with the new version of **Wazuh (3.13.0)**. I'll let you know here when we have it.

Thanks for the patience!

Regards,
Victor Santaella.

**Comment by frankfoti** [comment]
Is there an ETA on this yet?

**Comment by victorst79** [comment]
Hi @frankfoti 

We are working on 7.8.0 compatibility at the moment, it should be ready very soon.
Version 3.13 was already prepared with 7.7.0 and 7.7.1.
Anyway, 7.8.0 should be between this week or the next in the worst case, sorry for the inconvenience.
Have a great day.

Regards,
Victor Santaella.

**Comment by juankaromo** [comment]
Hi @VN1977 and @frankfoti ,

The new package of Wazuh 3.13.0-7.8.0 has just been released, you can find the release notes and the package here: https://github.com/wazuh/wazuh-kibana-app/releases/tag/v3.13.0-7.8.0

If you have any other questions, please let us know!

Best Regards,
Juan Carlos

**Comment by frankfoti** [comment]
Help.  The 7.8 plugin breaks the Kibana index pattern all wazuh-* patterns.   The timestamp is broken.  My customer is frustrated.  Can someone help please?  Thanks

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________
