### ISSUE TITLE
The selected index-pattern is not present. No template found for the selected index-pattern.

### ISSUE THREAD

**Issue by zaxcer** [wazuh/wazuh-kibana-app#230]
Hello,

after update to 6.0 my ELK stack with wazuh plugin installed I cant go to Wazuh plugin tab in Kibana.

The error is:

```
 Performing checks...(4/4)
Ups, something went wrong...
  The selected index-pattern is not present.
  No template found for the selected index-pattern.
  {"data":{"statusCode":500,"error":9,"message":"Could not get data from elasticsearch"},"status":500,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","headers":{"Accept":"application/json, text/plain, */*","kbn-version":"6.1.2"},"timeout":4000,"url":"/api/wazuh-elastic/setup"},"statusText":"Internal Server Error","html":"Unexpected error. Please, report this error.","message":"Unexpected error. Please, report this error."}
```

I reuploaded the templates, reinstalled plugin and still got this issue. 

I recently removed the .wazuh index and it worked like couple of seconds untill i tried to connect to my Wazuh enviroment and error returned.

**Comment by havidarou** [comment]
Hi @zaxcer ,

sorry you are having problems.

The new version of the Wazuh app performs some checks prior to loading the app.

Your installation is failling in two of them:

1. Can't detect the index-pattern used for the visualizations.
2. Can't detect a proper template being applied to the pattern.

Even though the checks fail, you can still try to navigate through the app if you press F5 in that same browser tab.

But let's try to find out why this is happening.

- Check your index-patterns in Kibana:

  - Open Kibana, go to management, index-patterns and check what is listed there.

- Check the templates being applied in Elasticsearch:

  - ```curl localhost:9200/_cat/templates?v``` 

Regards!

**Comment by zaxcer** [comment]
Thank you for your response @havidarou !


```
[root@--- ~]# curl --noproxy localhost  'localhost:9200/_cat/templates?v'
name                          index_patterns             order      version
.monitoring-es                [.monitoring-es-6-*]       0          5050099
.ml-anomalies-                [.ml-anomalies-*]          0          5060399
wazuh-agent                   [wazuh-monitoring*]        0
.monitoring-kibana            [.monitoring-kibana-6-*]   0          5050099
triggered_watches             [.triggered_watches*]      2147483647
.ml-notifications             [.ml-notifications]        0          5060399
.watch-history-6              [.watcher-history-6*]      2147483647
.ml-state                     [.ml-state]                0          5060399
kibana_index_template:.kibana [.kibana]                  0
.ml-meta                      [.ml-meta]                 0          5060399
.monitoring-alerts            [.monitoring-alerts-6]     0          5050099
logstash                      [logstash-*]               0          50001
.monitoring-logstash          [.monitoring-logstash-6-*] 0          5050099
wazuh                         [wazuh-alerts-3.*]         0
watches                       [.watches*]                2147483647
security-index-template       [.security]                1000
[root@--- ~]# curl --noproxy localhost  'localhost:9200/_cat/indices?v' | grep wazuh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21414  100 21414    0     0  11869      0  0:00:01  0:00:01 --:--:-- 11870
yellow open   wazuh-monitoring-3.x-             5PIX4ZysQIOIPNr_DA7OsQ   5   1          0            0      1.2kb          1.2kb
yellow open   wazuh-monitoring-2018.01.15       pi58-JSQSweBN7CwiTEBBA   5   1          1            0        6kb            6kb
yellow open   wazuh-alerts-3.x-2018.01.16       n2OZoNkNQ-WjWlpZfh2DEA   5   1          1            0     10.5kb         10.5kb
yellow open   wazuh-alerts-3.x-2018.01.28       Ii4SmyrISMyqogqXA7FVdg   5   1          8            0       49kb           49kb
yellow open   wazuh-alerts-3.x-2018.01.20       XPqGnwzcQfWfetrSEvG_xQ   5   1          1            0     10.5kb         10.5kb
yellow open   wazuh-alerts-3.x-2018.01.17       nMtDe_CRSwCnGAms9EipbA   5   1          1            0     10.5kb         10.5kb
yellow open   wazuh-alerts-3.x-2018.01.19       ClwVZEnsTVixlh8-DYIE1A   5   1          1            0     10.5kb         10.5kb
yellow open   wazuh-alerts-3.x-2017.12.28       b1-fPtfoQNS19fPUczbJKg   5   1        372            0    547.7kb        547.7kb
yellow open   wazuh-alerts-3.x-2018.02.01       JDmysL3rR6Owpov-PncS-Q   5   1          1            0     26.8kb         26.8kb
yellow open   wazuh-alerts-3.x-2018.01.18       NwMFP2xVTmC1k3l3On6MuQ   5   1          0            0      1.2kb          1.2kb
yellow open   wazuh-alerts-3.x-2017.12.27       AmRL7W2kRDKRPHg6Mrq2cA   5   1         17            0     66.3kb         66.3kb
yellow open   wazuh-alerts-2018.01.15           f4ALO86QTTKxGaRHrlPhMQ   5   1          1            0     19.6kb         19.6kb
yellow open   wazuh-alerts-3.x-2018.01.26       3JG4q8NCRn6ku6eokIbL1A   5   1          1            0     10.5kb         10.5kb
yellow open   wazuh-alerts-3.x-2018.01.21       rodQqyPdS_645hqNwlvI2g   5   1          0            0      1.2kb          1.2kb
yellow open   wazuh-alerts-3.x-2018.01.29       u14ZMGiHT5yzCYPnikZvYw   5   1          5            0     71.2kb         71.2kb
yellow open   wazuh-alerts-3.x-2018.01.15       KPPJt8uRRsiNBRrq8T3M9A   5   1         46            0    284.8kb        284.8kb
yellow open   .wazuh                            5C_yE5jTQCq8GrguesFmzA   5   1          1            0     10.2kb         10.2kb
yellow open   wazuh-alerts-3.x-2018.01.24       GGLlCFiAQCKKjCJdgTKk8w   5   1          1            0     10.5kb         10.5kb
yellow open   wazuh-alerts-3.x-2018.01.22       v2dOaMV9SZmGt_wzJrWCLA   5   1          8            0     75.9kb         75.9kb
yellow open   wazuh-alerts-3.x-2018.01.27       _HgDOPVRThml2STG0owgHQ   5   1          0            0      1.2kb          1.2kb
yellow open   wazuh-alerts-3.x-2018.01.25       1jADnSg7TVSS7oM-5NW-Ew   5   1          0            0      1.2kb          1.2kb
yellow open   wazuh-monitoring-3.x-2018.02.01   W1jMEJLESFWjeF4trOYxog   5   1         33            0    248.6kb        248.6kb
yellow open   wazuh-alerts-3.x-2018.01.23       Df1MOVDOT-Gih_BOOIcWow   5   1         86            0    577.6kb        577.6kb
```



Also from kibana management side i see:
```
 Create Index Pattern
    wazuh*
   NOTRELATED*
   NOTRELATED*
   NOTRELATED*
    wazuh-alerts-*
    wazuh-alerts-3.x-*
    wazuh-monitoring-3.x-*
```

Thank you again for your time and help.

**Comment by zaxcer** [comment]
OK, so I solved the problem by deleting the .kibana index, after kibana.service restart it created itself again and everything seems to be ok now.

Remamber, you lose all custom visualisations you created in Kibana.

**Comment by havidarou** [comment]
Hi @zaxcer ,

glad you got it working!

Regards.

**Comment by Majordon** [comment]
1+

**Comment by JuanjiJG** [comment]
Hi @Majordon,

Could you please provide more information about your problem? What are your current Wazuh and Kibana versions? You can check that out using the following commands:
```
cat /etc/ossec-init.conf
cat /usr/share/kibana/package.json | grep version
```
If you're getting the same error on the app startup:
```
The selected index-pattern is not present. No template found for the selected index-pattern.
```
Please execute the following commands so we can see your current list of indices and templates:
```
curl -XGET localhost:9200/_cat/indices?v
curl -XGET localhost:9200/_cat/templates?v
```
Regards,
Juanjo

**Comment by ppunjaisee** [comment]
Hi Juanjo,

Please find the screenshot as follows;

<img width="305" alt="1" src="https://user-images.githubusercontent.com/43665094/46193414-0c32ad00-c339-11e8-8d50-1b9a78566cd5.PNG">

Also last 20 lines of log;

[root@secumon01 auth]# tail -n20 /usr/share/kibana/optimize/wazuh-logs/wazuhapp.log
{"date":"2018-09-28T06:47:21.394Z","level":"info","location":"[monitoring][checkTemplate]","message":"Updating wazuh-monitoring template..."}
{"date":"2018-09-28T06:47:21.400Z","level":"info","location":"[initialize][checkWazuhIndex]","message":"Checking .wazuh index."}
{"date":"2018-09-28T06:47:21.400Z","level":"info","location":"[initialize][checkWazuhVersionIndex]","message":"Checking .wazuh-version index."}
{"date":"2018-09-28T06:47:21.406Z","level":"info","location":"[initialize][checkWazuhVersionIndex]","message":".wazuh-version document does not exist. Initializating configuration..."}
{"date":"2018-09-28T06:47:21.496Z","level":"info","location":"[initialize][checkKnownFields]","message":"x-pack enabled: no"}
{"date":"2018-09-28T06:47:21.508Z","level":"info","location":"[initialize][checkKnownFields]","message":"Found 7 index patterns"}
{"date":"2018-09-28T06:47:21.509Z","level":"info","location":"[initialize][checkKnownFields]","message":"Found 1 valid index patterns for Wazuh alerts"}
{"date":"2018-09-28T06:47:21.509Z","level":"info","location":"[initialize][checkKnownFields]","message":"Default index pattern found"}
{"date":"2018-09-28T06:47:21.509Z","level":"info","location":"[initialize][checkKnownFields]","message":"Refreshing known fields for \"index-pattern:wazuh-alerts-3.x-*\""}
{"date":"2018-09-28T06:47:21.576Z","level":"info","location":"[initialize][checkKnownFields]","message":"App ready to be used."}
{"date":"2018-09-28T06:47:22.381Z","level":"error","location":"[initialize][saveConfiguration]","message":"[resource_already_exists_exception] index [.wazuh-version/ovhAC0aAQxy-N7iF5eJ6Lg] already exists, with { index_uuid=\"ovhAC0aAQxy-N7iF5eJ6Lg\" & index=\".wazuh-version\" }"}
{"date":"2018-09-28T06:47:22.401Z","level":"error","location":"[initialize][init]","message":"[document_missing_exception] [wazuh-version][1]: document missing, with { index_uuid=\"ovhAC0aAQxy-N7iF5eJ6Lg\" & shard=\"0\" & index=\".wazuh-version\" }"}
{"date":"2018-09-28T06:47:22.402Z","level":"error","location":"[initialize][checkKibanaStatus]","message":"[document_missing_exception] [wazuh-version][1]: document missing, with { index_uuid=\"ovhAC0aAQxy-N7iF5eJ6Lg\" & shard=\"0\" & index=\".wazuh-version\" }"}
{"date":"2018-09-28T06:47:23.167Z","level":"info","location":"[monitoring][init]","message":"Creating today index..."}
{"date":"2018-09-28T06:47:24.229Z","level":"info","location":"[initialize][checkWazuhIndex]","message":"Index .wazuh created."}
{"date":"2018-09-28T06:47:25.028Z","level":"info","location":"[monitoring][init]","message":"Checking if wazuh-monitoring pattern exists..."}
{"date":"2018-09-28T06:47:25.032Z","level":"info","location":"[monitoring][init]","message":"Didn't find wazuh-monitoring pattern for Kibana v6.x. Proceeding to create it..."}
{"date":"2018-09-28T06:47:25.099Z","level":"info","location":"[monitoring][createWazuhMonitoring]","message":"No need to delete old wazuh-monitoring pattern."}
{"date":"2018-09-28T06:47:25.099Z","level":"info","location":"[monitoring][configureKibana]","message":"Creating index pattern: wazuh-monitoring-3.x-*"}
{"date":"2018-09-28T06:47:25.169Z","level":"info","location":"[monitoring][configureKibana]","message":"Created index pattern: wazuh-monitoring-3.x-*"}
[root@secumon01 auth]#

Regards,
Pakorn

**Comment by JuanjiJG** [comment]
Hi @ppunjaisee,

This is not the correct issue. Heres the link: https://github.com/wazuh/wazuh/issues/1474

We'll continue the conversation on the original issue.

Regards,
Juanjo

**Comment by eobi** [comment]
name                        index_patterns                order      version
.management-beats           [.management-beats]           0          70000
.ml-anomalies-              [.ml-anomalies-*]             0          7020099
.ml-meta                    [.ml-meta]                    0          7020099
.monitoring-kibana          [.monitoring-kibana-7-*]      0          7000199
.data-frame-internal-1      [.data-frame-internal-1]      0          7020099
.kibana_task_manager        [.kibana_task_manager]        0          7020099
.monitoring-es              [.monitoring-es-7-*]          0          7000199
.monitoring-beats           [.monitoring-beats-7-*]       0          7000199
.watches                    [.watches*]                   2147483647 
.ml-state                   [.ml-state*]                  0          7020099
.logstash-management        [.logstash]                   0          
wazuh-agent                 [wazuh-monitoring-3.x-*]      0          
.ml-config                  [.ml-config]                  0          7020099
.data-frame-notifications-1 [.data-frame-notifications-*] 0          7020099
.ml-notifications           [.ml-notifications]           0          7020099
.monitoring-logstash        [.monitoring-logstash-7-*]    0          7000199
.triggered_watches          [.triggered_watches*]         2147483647 
.monitoring-alerts-7        [.monitoring-alerts-7]        0          7000199
.watch-history-9            [.watcher-history-9*]         2147483647

**Comment by eobi** [comment]
health status index                           uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   wazuh-monitoring-3.x-2019.07.14 IG4UzYKGQhegbkjE320gkQ   2   0        480            0    284.9kb        284.9kb
yellow open   .wazuh-version                  iSC0wQUQThCfqWbvgQ9VHw   1   1          1            0      5.2kb          5.2kb
green  open   .kibana_2                       mVTiZJPbSo6EzsoNtSiqOw   1   0          6            0     55.8kb         55.8kb
green  open   wazuh-monitoring-3.x-2019.07.11 L1GjiJ02T02WaOHIOO83Sg   2   0          0            0       566b           566b
yellow open   .wazuh                          dqciy_ZSQt-KXxG4tAU41A   1   1          1            0     11.2kb         11.2kb
green  open   wazuh-monitoring-3.x-2019.07.15 MmEPmCw1Qrm2hiSiqFVl0Q   2   0        553            0      317kb          317kb
yellow open   wazuh-alerts-3.x-2019.07.15     ALxyQLbRSeKjWuIoWvcLjQ   1   1          1            0     37.1kb         37.1kb
green  open   .kibana_task_manager            cYzcPC6GTFW3lOIqsSRa_g   1   0          2            0     12.8kb         12.8kb
green  open   wazuh-monitoring-3.x-2019.07.13 QrgmRcNhSXCUspaEWvcvBg   2   0        480            0      318kb          318kb
green  open   wazuh-monitoring-3.x-2019.07.12 W-e4d2MzSyeziXdHRKX_dw   2   0        365            0    393.2kb        393.2kb
green  open   .kibana_1                       eXIsZdoSRGOCpC7WB0dJGg   1   0          4            3       64kb           64kb
