### ISSUE TITLE
Invalid 'wazuh-app-version'

### ISSUE THREAD

**Issue by skidrow52** [wazuh/wazuh-kibana-app#2319]
I upgraded from to 3.13 using the yum update command not realizing will end up with issues, after the upgrade using yum Wazuh doesnt start 

3005 - Invalid 'wazuh-app-version' header. Expected version '3.13.x', and found '3.12.x'.

[root@manager ~]# cat /etc/yum.repos.d/wazuh.repo
[wazuh_repo]
gpgcheck=1
gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH
enabled=1
name=Wazuh repository
baseurl=https://packages.wazuh.com/3.x/yum/
protect=1

[root@manager ~]# cat /etc/ossec-init.conf
DIRECTORY="/var/ossec"
NAME="Wazuh"
VERSION="v3.13.0"
REVISION="31306"
DATE="Wed Jun 17 16:02:21 UTC 2020"
TYPE="server"

[root@manager ~]# cat /usr/share/kibana/plugins/wazuh/package.json | grep version
  "version": "3.12.3",
    "version": "7.6.2"

**Comment by Desvelao** [comment]
Hi @skidrow52 

You need update:
- Elastic stack to 7.7.x
- Wazuh app to 3.13.0 avaliable for Kibana 7.7.0 and 7.7.1 https://github.com/wazuh/wazuh-kibana-app#installation

You can prevent accidental upgrades of Wazuh, disabling the Wazuh repository:
`sed -i "s/^enabled=1/enabled=0/" /etc/yum.repos.d/wazuh.repo`

**Comment by skidrow52** [comment]
Thank you for your prompt response, I am lost it seems, I tried to upgrade the packages as per the instructions with the following response now

Plugin installation was unsuccessful due to error "Plugin wazuh [7.7.1] is incompatible with Kibana [7.6.2]"

When I try to upgrade Kibana I get this 

[root@manager kibana]# yum install kibana-7.7.1
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.isu.net.sa
 * extras: mirrors.isu.net.sa
 * updates: mirrors.isu.net.sa
Resolving Dependencies
--> Running transaction check
---> Package kibana.x86_64 0:7.7.1-1 will be installed
--> Processing Conflict: kibana-oss-7.6.2-1.x86_64 conflicts kibana
--> Processing Conflict: kibana-7.7.1-1.x86_64 conflicts kibana-oss
--> Finished Dependency Resolution
Error: kibana-oss conflicts with kibana-7.7.1-1.x86_64
Error: kibana conflicts with kibana-oss-7.6.2-1.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest





> Hi @skidrow52
> 
> You need update:
> 
> * Elastic stack to 7.7.x
> * Wazuh app to 3.13.0 avaliable for Kibana 7.7.0 and 7.7.1 https://github.com/wazuh/wazuh-kibana-app#installation
> 
> You can prevent accidental upgrades of Wazuh, disabling the Wazuh repository:
> `# sed -i "s/^enabled=1/enabled=0/" /etc/yum.repos.d/wazuh.repo`

**Comment by Desvelao** [comment]
Hi @skidrow52 , you need upgrade Elasticsearch, Kibana and Filebeat to the same version. For Wazuh 3.13.0, you need `7.7.0` or `7.7.1` version of these components.

You can find how to do this in https://documentation.wazuh.com/3.13/upgrade-guide/upgrading-elastic-stack/#installation-elastic-legacy.

For your case, 7.6.2 to 7.7.1 https://documentation.wazuh.com/3.13/upgrade-guide/upgrading-elastic-stack/elastic_server_minor_upgrade.html

**Comment by skidrow52** [comment]
I tried to upgrade all the components but then Kibana doesnt start and everything gets messed up, the last snapshot i have was before upgrade unfortunately, what is the best way to downgrade to ver 3.12

________________________________

**Comment by Desvelao** [comment]
Hi @skidrow52 , KIbana show the message of `Kibana server is not ready yet` and it doesn't start? Did you increase the Kibana heap size after upgrade it? Kibana can take some time after first start.
```
# cat >> /etc/default/kibana << EOF
NODE_OPTIONS="--max_old_space_size=2048"
EOF```

To see Kibana errors, can you share the output of:
`# journalctl -xe | grep kibana`

**Comment by frankfoti** [comment]
I upgraded Elastic stack to 7.8.0,  installed kibana plugin wazuhapp-3.13.0_7.8.0,  restarted kibana and wazuh dashboard shows error; Invalid 'wazuh-app-version' header. Expected version '3.13.x', and found '3.12.x'

I tried upgrading the wazuh-api on the wazuh server and does not upgrade:

[root@wazuh-1 ~]# yum upgrade wazuh-api
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: repos.dfw.quadranet.com
 * extras: centos.mirror.constant.com
 * updates: ftp.osuosl.org
No packages marked for update

Any Ideas?

**Comment by Desvelao** [comment]
Hi @frankfoti , could you follow the steps to upgrade Wazuh app for Kibana described in https://github.com/wazuh/wazuh-kibana-app#upgrade? Special attention to `Remove generated bundles` step.

Check installed Wazuh API with:
`# cat /var/ossec/api/package.json | grep version`

Wazuh API and Wazuh app for Kibana should match same version.

**Comment by frankfoti** [comment]
I was able to resolve the upgrade to 3.13 by editing vi /etc/yum.repos.d/wazuh.repo and setting enabled=1.

Now I cannot get the index patters to show up in discover, even recreated them and using @timestamp.  I also dropped all the indexes and let the recreate via the api...  Any Ideas?

**Comment by juankaromo** [comment]
I'm closing this issue because it was continued here https://github.com/wazuh/wazuh-kibana-app/issues/2340
