### ISSUE TITLE
Anchors do not work correctly in MITRE flyout

### ISSUE THREAD

**Issue by victorst79** [wazuh/wazuh-kibana-app#2325]
Wazuh | Elastic | Rev
-- | -- | --
3.13 | 7.7.0 - 7.7.1 | x

Description

Hi team!

The anchors inside the MITRE flyouts are not working correctly, with this issue you want to fix this feature in all browsers.

![image](https://user-images.githubusercontent.com/25077237/85669262-f265fb80-b6bf-11ea-9fda-16dd90ec481d.png)

**Comment by Joanes04** [comment]
**UPDATE**

Hi team!

This has been solved in the next PR: https://github.com/wazuh/wazuh-kibana-app/pull/2349

Regards, 
Alberto
