### ISSUE TITLE
Server did not respond(/reports ) Generating Pdf Reports 

### ISSUE THREAD

**Issue by Shad0w-D0rk3R** [wazuh/wazuh-kibana-app#2332]
Hii,
    I using wazuh  kibana plugin (wazuhapp-3.13.0_7.7.0) generating reports i'm getting this error.

-->Server did not respond(/reports )<--

elasticserach and kibana version: 7.7.0
![Reports_error](https://user-images.githubusercontent.com/30574883/85813365-9fa04880-b780-11ea-8f94-530003bb0e5f.JPG)

**Comment by victorst79** [comment]
Hi @Shad0w-D0rk3R 

Apparently the interface you have shared is a version of the App, lower than _3.13-7.7_, in this case I recommend that you check the versions of your environment and delete all cache and application data in the web browser.

To check which version of Wazuh you have installed run this command:
```
sudo cat /var/ossec/etc/ossec-init.conf
```
To check the version of Kibana and Wazuh App, you can check it from the application.
For **Kibana** go to **Management** in the menu and here it appears what version you have installed.
For **Wazuh App** in the **About** inside App settings you can see what version of the application you have installed.

To delete the application and cache data, open the console (DevTools) of your browser, go to Application in the case of Chrome, if you use Firefox go to storage.
In Chrome there is a menu tab on the left called 'Clear storage'. For Firefox in the 'Storage' tab, and right click on the Application url, delete all the information from all the dropdowns.

Espero que esto te sirva de ayuda!

Victor Santaella,
Regards.

**Comment by juankaromo** [comment]
I am going to close this issue due to inactivity although feel free to reopen it if you need it.

Regards,
