### ISSUE TITLE
Groups cannot be deleted

### ISSUE THREAD

**Issue by Joanes04** [wazuh/wazuh-kibana-app#2339]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.13   | 7.7     | - |

**Description**

When you click on the button to delete a group, nothing happens. A modal should come out, for confirmation to delete a group, but nothing comes out.

**Steps to reproduce**

1. Go to 'Management > Groups'
2. Click on the delete group icon
3. Wait for the modal to open
4. The modal comes out when you change to the detail view

**Screenshots**

![delete_group](https://user-images.githubusercontent.com/9945959/85847634-0be27280-b7a8-11ea-8389-eccfbdf6ea46.gif)

**Comment by Desvelao** [comment]
Component didn't update after change `showModal` prop.

Allow rendering when this property changes in the `shouldComponentUpdate` method fixes it.

**Comment by juankaromo** [comment]
Fixed here https://github.com/wazuh/wazuh-kibana-app/pull/2342
