### ISSUE TITLE
wazuh kibana plugin 7.8 breaks the kibana index pattern

### ISSUE THREAD

**Issue by frankfoti** [wazuh/wazuh-kibana-app#2340]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.13   | 7.8     | ??? |

Help.  The 7.8 plugin breaks the Kibana index pattern all wazuh-* patterns.   The timestamp is broken.  My customer is frustrated.  Can someone help please?  Thanks

If you install the plugin it creates the wazuh index patterns
The index patter does not  display data in the discover tab
The timestamp on the index pattern gets set to exclude
Even if I create a new index wazuh-alert*  that pattern gets changed in terms of timestamp
If I reomve the plugin and create the index pattern again the problem goes away
But the I have no monitoring data update and no wazuh dashboards in kibana

Thanks

**Comment by pablotr9** [comment]
HI @frankfoti !

> If you install the plugin it creates the wazuh index patterns

If any of our index patterns don't exist (wazuh-alerts-3.x-* or wazuh-monitoring-3.x-*)  they are automatically created by the Wazuh App and that is the expected behavior, 

> The index patter does not display data in the discover tab

Could you please check that you have indices (and these indices have data) that matches the index pattern ?

> The timestamp on the index pattern gets set to exclude
Even if I create a new index wazuh-alert* that pattern gets changed in terms of timestamp

What you mean? The timestamp field used in the index pattern should be `timestamp`, otherwise the Wazuh App dashboards won't work.



Could you please give us some more information or any error logs that you could share with us? this way we can give you further assistance

Best Regards,
Pablo Torres

**Comment by frankfoti** [comment]
I needed to remove the plugin due to production needs.  I will try to set up a dev environment to reproduce it if I can.

1) I do see the index patterns getting created and recreated when the kibana wazuh plugin is installed
2) The data definately exists and verified in dev tools
3) The alert data was not visible in discover or the wazuh module
4) The timestamp in the index pattern has a Source Field defined and is then excluded. Please confirm.
5) I have this template installed:
    curl -so template.json https://raw.githubusercontent.com/wazuh/wazuh/v3.13.0/extensions/elasticsearch/7.x/wazuh-template.json
6)  I have this pipeline running:
   curl -so /etc/filebeat/wazuh-ecs-pipeline.json https://raw.githubusercontent.com/HKcyberstark/wazuh-ecs/master/wazuh-ecs-pipeline.json

I attached examples from #4 in another environment I have.  Hopefully I can reproduce this later today in a dev environment.

Thanks

![image](https://user-images.githubusercontent.com/30085032/86005800-1472bd00-b9e3-11ea-8a30-8d73c4318ddc.png)

**Comment by frankfoti** [comment]
I have approval to attempt the kibana wazuh plugin install again.  Is it possible to schedule that when you are available?

**Comment by pablotr9** [comment]
Hi @frankfoti ! sorry for the wait, let me remind you that you can also join our Slack community channels https://wazuh.com/community/join-us-on-slack/ 

The Time Filter field should be `timestamp` and not `@timestamp`, this is how my index pattern looks like (it was automatically created by the App) 
![image](https://user-images.githubusercontent.com/35685689/86091556-64698680-baac-11ea-98e4-ccbb3fe0499b.png)

The source filter you mention looks like this:
![image](https://user-images.githubusercontent.com/35685689/86091724-abf01280-baac-11ea-9ad5-739ffc750951.png)

Please, let me know the process you follow during the plugin installation so I can give you further assistance.

Best Regards,
Pablo Torres

**Comment by frankfoti** [comment]
I was able to install a new ELK, wazuh, kibana environment ES 7.8 and wazuh 3.13 with no issues.  Not sure why the upgraded environment caused issues.  When I get  permission to work in the broken environment I will continue.

Thanks

**Comment by juankaromo** [comment]
Hi @frankfoti ,

Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our Slack channel or subscribe to our mailing list.

Regards,
