### ISSUE TITLE
Including extension on newly created ruleset file gives wrong error

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-kibana-app#2347]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.13.0   | 7.7.0     | 0880 |

**Description**
When creating a new rule or decoder file, if the extension is included in the filename the error `Error saving CDB list: Wazuh API error: 704 - Invalid path` pops up.  This error should not be specific to CDB lists.

Given that the field box's message is `Type your new rules file name here` some users may type in the extension, if this is going to be autocompleted by the Wazuh platform then it would improve the user's experience if it would not add the `.xml` extension if it already has it. 

**Steps to reproduce**

1. Go to Wazuh > Management > Rules
2. Click on Add New Rules File
3. Fill filename ending in `.xml`
4. Click Save
5. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/36071202/86157750-213d0100-bb08-11ea-8d9f-52537156d59e.png)

![image](https://user-images.githubusercontent.com/36071202/86158099-96a8d180-bb08-11ea-937a-d8b3853c830a.png)

**Comment by jctello** [comment]
Similarly if a cdb list file is created with a `.cdb` extension, no error is given but the file is not shown in the interface. Which may lead to confusion.

**Comment by Joanes04** [comment]
Hi @jctello 

Thank you very much for reporting the bugs. We've already solved all the points you're talking about:

- You can now save rules, with the ending **.xml**
- The text of error messages in rules and decoders has been corrected.
- You can now save CDB lists with the ending **.cdb**

Regards,
Alberto
