### ISSUE TITLE
Editable Security Events/Events

### ISSUE THREAD

**Issue by GeorgePatsias** [wazuh/wazuh-kibana-app#2352]
Hello,

I would suggest that on Security Events/Events, the **Selected fields** on the left if it possible to be editable.

Thanks for your time.

**Comment by Joanes04** [comment]
Hi @GeorgePatsias 

Right now the default fields in Security events / Events are not configurable. This feature is not included in our roadmap and we cannot implement it at the moment.

What you can do right now, once you are in Events, select the ones you need. If we add this feature to our roadmap later, we will notify you in this issue. 

Thank you very much for your contribution, any question don't hesitate to open a new issue.

Regards, 
Alberto
