### ISSUE TITLE
Migrate DevTools to React

### ISSUE THREAD

**Issue by pablotr9** [wazuh/wazuh-kibana-app#2364]
Hi team,

The DevTools section is still using AngularJs, we need to migrate this section to ReactJs as we have already done with most of our components.
The idea is to make this new Dev Tools component as similar as possible to the Kibana DevTools. Example:
![image](https://user-images.githubusercontent.com/35685689/86914433-a33cb380-c120-11ea-9515-e763ee6a052c.png)

**UPDATE**  (added here https://github.com/wazuh/wazuh-kibana-app/commit/1e8d48d2740e9892278ceac3d1840ecdba5b210b)
It has been created a new DevTools Component based on the Sense Editor used in Kibana DevTools (https://github.com/elastic/kibana/tree/952b61e049f803acd20c8bbedec5d35aa3f384ff/src/plugins/console/public/application/models/sense_editor) 

This is how the new Wazuh DevTools look like:
![image](https://user-images.githubusercontent.com/35685689/86914990-8785dd00-c121-11ea-9889-690d97dff354.png)

### Requests
The keyboard shortcut to run requests has been changed to **CTRL + ENTER**.
It's now possible to run multiple selected requests 
![Peek 2020-07-08 14-41](https://user-images.githubusercontent.com/35685689/86919858-23ffad80-c129-11ea-9ae8-a1e4098febe2.gif)

### Tabs
It has also been added the possibility to open different output tabs:
![Peek 2020-07-08 14-46](https://user-images.githubusercontent.com/35685689/86920285-d6d00b80-c129-11ea-8494-9aa7aeefa1f1.gif)

### History 
The last 150 requests are now stored and the user can now easily restore old requests:
![Peek 2020-07-08 14-48](https://user-images.githubusercontent.com/35685689/86921422-6a560c00-c12b-11ea-9907-c4f2b962e17b.gif)

### Copy and Paste
As its based on the SenseEditor, now it's possible to copy and paste CURL requests and they are translated in the editor syntax.
![Peek 2020-07-08 13-54](https://user-images.githubusercontent.com/35685689/86915644-97ea8780-c122-11ea-821e-e113210c48b3.gif)

### Autocompletion
As we write a request some suggestions will be shown
![image](https://user-images.githubusercontent.com/35685689/86917990-4fcd6400-c126-11ea-9e00-5fe80a646e8e.png)

**Comment by juankaromo** [comment]
It would be interesting to add the possibility to copy the cURL requests from the console and paste them in Dev Tools translating them to their format as Kibana does.

![output2](https://user-images.githubusercontent.com/21195730/87538949-58c9b280-c69d-11ea-8f0e-63a870fa4f0c.gif)

**Comment by victorst79** [comment]
Some improvements have been added in the responsive of this view, now the selection tabs become a select according to the width of the screen and the device.

Vertical resize:
![devtool-vertical-resize](https://user-images.githubusercontent.com/25077237/87555722-1fea0780-c6b6-11ea-8f24-0126104f4811.gif)

Window resize:
![resize-windows](https://user-images.githubusercontent.com/25077237/87556146-98e95f00-c6b6-11ea-8a8b-75383cc28fa6.gif)

**Comment by victorst79** [comment]
Hi team!

I have been working to add two new functionalities within the new DevTools.
The first added functionality is that the user can export the Kibana requests as cURL, it also works in reverse.

![image](https://user-images.githubusercontent.com/25077237/88395654-b5298200-cdc1-11ea-8615-fe10867ac482.png)

The other functionality is that you can go to the documentation related to an endpoint from the DevTools.

![example-redirect](https://user-images.githubusercontent.com/25077237/88397658-8eb91600-cdc4-11ea-9589-c9c469e18329.gif)
