### ISSUE TITLE
Dashboards are not refreshed properly if "Remove All" filters is used.

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-kibana-app#2367]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.13.0   | 7.7.1  | 0880 |

**Description**
If the "Remove All" option is selected from the "Change all filters" drop-down menu is used, unexpected behavior occurs, in which previously added filters are not removed and if a new filter is added and removed the change will not be reflected.

**Steps to reproduce**

1. Go to any dashboard
2. Add any filter (for example click on a visualization)
3. Click on the "Change all filters" button (below the search bar) then select "Remove All"
4. See how filter is still in effect
5. Add another filter and it will refresh appropriately
6. remove this filter and see it still in effect. 

**Screenshots**
![output](https://user-images.githubusercontent.com/36071202/86952749-bcab2300-c153-11ea-8037-012e1a098aae.gif)

**Additional context**
This does not affect custom dashboards in Kibana. I suspect it may have to do with the hard-coded filters in the dashboards (like cluster.name).

**Comment by juankaromo** [comment]
Hi @jctello 

This was already solved here https://github.com/wazuh/wazuh-kibana-app/pull/2331 but there was no time for it to come out in 3.13.0. It will be released in the next Wazuh release. 

Thanks a lot for the feedback!
Regards,

**Comment by jctello** [comment]
Great, thanks! :-)
