### ISSUE TITLE
Health Check. Error Pattern Handler (getPatternList)

### ISSUE THREAD

**Issue by 71Imapla** [wazuh/wazuh-kibana-app#2368]
| Wazuh | Elastic | filebeat |
| ----- | ------- | --- |
| 3.13.0   | 7.7.0     | 7.7.0 |

 rpm -qa | egrep "wazuh|filebeat"
wazuh-api-3.13.0-1.x86_64
wazuh-manager-3.13.0-1.x86_64
filebeat-7.7.0-1.x86_64

cat /usr/share/kibana/plugins/wazuh/package.json | grep version
  "version": "3.13.0",
    "version": "7.7.0"

apt show elasticsearch-oss
Package: elasticsearch-oss
Version: 7.7.0

**Description**
Getting "Health Check. Error Pattern Handler (getPatternList)" Error

![image](https://user-images.githubusercontent.com/31081438/86979579-8d39ed80-c136-11ea-9436-0849957fe793.png)

**Steps to reproduce**

1. Go to  kibana server
2. Click on Wazuh App icon
3. See error

**Screenshots**
See above.

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by 71Imapla** [comment]
Forgot to mention that I saw this in the lower right hand corner which indicates that it is attempting to create the index pattern:
![image](https://user-images.githubusercontent.com/31081438/86979782-06394500-c137-11ea-871f-e44e5dc0c50f.png)

**Comment by pablotr9** [comment]
Hi @71Imapla, 

Can you try accessing the App using an Incognito Window? this way we can know if it's a cache issue.
Please let me know if you still receive the same error when using Incognito Mode so I can give you further assistance.
Also check in the `Kibana -> Management -> Index pattern` section if the index pattern `wazuh-alerts-3x-*` was created.

Best Regards,
Pablo Torres

**Comment by 71Imapla** [comment]
Same issue in private mode:
![image](https://user-images.githubusercontent.com/31081438/87048537-ae3f2480-c1b0-11ea-8e85-789b12be94be.png)

Index Pattern:
![image](https://user-images.githubusercontent.com/31081438/87048600-c44ce500-c1b0-11ea-9500-77ce6188dff2.png)

**Comment by pablotr9** [comment]
Hi @71Imapla, 
For some reason the index pattern couldn't be created. Can you check if you have any `wazuh-alerts-3.x-*` indices created? 
Please run this request in Kibana DevTools:
```
GET _cat/indices
```
The index pattern cannot be created if indices do not exist. 
Could you also please check the browser DevTools console? Press F12 and check if there's any error in it.

Regards,
Pablo Torres

**Comment by 71Imapla** [comment]
I have not used dev tools before - however I think I executed the request correctly:
![image](https://user-images.githubusercontent.com/31081438/87160599-10169180-c278-11ea-8e0a-f5f93029058c.png)

**Comment by 71Imapla** [comment]
Note the wazuh_user only has (or should only have) permissions to see its own indices

**Comment by 71Imapla** [comment]
Looking at the elasticsearch log:
[2020-07-10T06:52:14,393][INFO ][c.a.o.s.p.PrivilegesEvaluator] [some-elasticsearch-node-dev-null] No cluster-level perm match for User [name=wazuh_user, backend_roles=[], requestedTenant=null] Resolved [aliases=[*], allIndices=[*], types=[*], originalRequested=[*], remoteIndices=[]] [Action [cluster:admin/ingest/pipeline/put]] [RolesChecked [wazuh_user, own_index, kibana_user]]

**Comment by 71Imapla** [comment]
![image](https://user-images.githubusercontent.com/31081438/87163445-35a59a00-c27c-11ea-8958-74f8c7b9e1d0.png)

**Comment by 71Imapla** [comment]
We found that we did not have this file;  stat /etc/filebeat/wazuh-template.json: no such file or directory.  Downloaded per instructions, rebooted and we have the following:

```
Jul 10 07:42:19 wazuh-filebeat-node-01 filebeat[3170]: 2020-07-10T07:42:19.364-0700        INFO        template/load.go:101        template with name 'wazuh' loaded.
Jul 10 07:42:19 wazuh-filebeat-node-01 filebeat[3170]: 2020-07-10T07:42:19.364-0700        INFO        [index-management]        idxmgmt/std.go:295        Loaded index template.
Jul 10 07:42:24 wazuh-filebeat-node-01 filebeat[3170]: 2020-07-10T07:42:24.850-0700        INFO        [monitoring]        log/log.go:145        Non-zero metrics in the last 30s        {"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":50,"time":{"ms":54}},"total":{"ticks":240,"time":{"ms":252},"value":240},"user":{"ticks":190,"time":{"ms":198}}},"handles":{"limit":{"har...
Jul 10 07:42:25 wazuh-filebeat-node-01 filebeat[3170]: 2020-07-10T07:42:25.037-0700        ERROR        [publisher_pipeline_output]        pipeline/output.go:106        Failed to connect to backoff(elasticsearch(https://elasticsearch02-dev-null:9200)): Connection marked as failed because the onConnect callback failed: 1 error: Error loading pipeline for fileset wazu...
Jul 10 07:42:25 wazuh-filebeat-node-01 filebeat[3170]: 2020-07-10T07:42:25.037-0700        INFO        [publisher_pipeline_output]        pipeline/output.go:99        Attempting to reconnect to backoff(elasticsearch(https://elasticsearch02.dev-null:9200)) with 4 reconnect attempt(s)
Jul 10 07:42:25 wazuh-filebeat-node-01 filebeat[3170]: 2020-07-10T07:42:25.038-0700        INFO        [esclientleg]        eslegclient/connection.go:263        Attempting to connect to Elasticsearch version 7.7.0
Jul 10 07:42:25 wazuh-filebeat-node-01 filebeat[3170]: 2020-07-10T07:42:25.060-0700        INFO        template/load.go:169        Existing template will be overwritten, as overwrite is enabled.
Jul 10 07:42:25 wazuh-filebeat-node-01 filebeat[3170]: 2020-07-10T07:42:25.061-0700        INFO        template/load.go:109        Try loading template wazuh to Elasticsearch
Jul 10 07:42:25 wazuh-filebeat-node-01 filebeat[3170]: 2020-07-10T07:42:25.162-0700        INFO        template/load.go:101        template with name 'wazuh' loaded.
Jul 10 07:42:25 wazuh-filebeat-node-01 filebeat[3170]: 2020-07-10T07:42:25.162-0700        INFO        [index-management]        idxmgmt/std.go:295        Loaded index template.

**Comment by pablotr9** [comment]
Hi @71Imapla ,
The current logged in user should have read/write permissions on `wazuh-*` indices.

The index pattern can not be created if there are no wazuh-alerts* indices, as I can see in the output of the `GET _cat/indices` you don't  have any wazuh-alerts-3.x-* .
Please, make sure that Filebeat is correctly installed and configured, you can check if Filebeat can connect to Elasticsearch with this command:
```
filebeat test output
```

Regards,
Pablo Torres

**Comment by 71Imapla** [comment]
@pablotr9 :

filebeat test output was successful.  Can you comment on this:

```
Jul 10 07:42:19 wazuh-filebeat-node-01 filebeat[3170]: 2020-07-10T07:42:19.364-0700        INFO        template/load.go:101        template with name 'wazuh' loaded.
Jul 10 07:42:19 wazuh-filebeat-node-01 filebeat[3170]: 2020-07-10T07:42:19.364-0700        INFO        [index-management]        idxmgmt/std.go:295        Loaded index template.
Jul 10 07:42:24 wazuh-filebeat-node-01 filebeat[3170]: 2020-07-10T07:42:24.850-0700        INFO        [monitoring]        log/log.go:145        Non-zero metrics in the last 30s        {"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":50,"time":{"ms":54}},"total":{"ticks":240,"time":{"ms":252},"value":240},"user":{"ticks":190,"time":{"ms":198}}},"handles":{"limit":{"har...
Jul 10 07:42:25 wazuh-filebeat-node-01 filebeat[3170]: 2020-07-10T07:42:25.037-0700        ERROR        [publisher_pipeline_output]        pipeline/output.go:106        Failed to connect to backoff(elasticsearch(https://elasticsearch02-dev-null:9200)): Connection marked as failed because the onConnect callback failed: 1 error: Error loading pipeline for fileset wazu...
Jul 10 07:42:25 wazuh-filebeat-node-01 filebeat[3170]: 2020-07-10T07:42:25.037-0700        INFO        [publisher_pipeline_output]        pipeline/output.go:99        Attempting to reconnect to backoff(elasticsearch(https://elasticsearch02.dev-null:9200)) with 4 reconnect attempt(s)
Jul 10 07:42:25 wazuh-filebeat-node-01 filebeat[3170]: 2020-07-10T07:42:25.038-0700        INFO        [esclientleg]        eslegclient/connection.go:263        Attempting to connect to Elasticsearch version 7.7.0
Jul 10 07:42:25 wazuh-filebeat-node-01 filebeat[3170]: 2020-07-10T07:42:25.060-0700        INFO        template/load.go:169        Existing template will be overwritten, as overwrite is enabled.
Jul 10 07:42:25 wazuh-filebeat-node-01 filebeat[3170]: 2020-07-10T07:42:25.061-0700        INFO        template/load.go:109        Try loading template wazuh to Elasticsearch
Jul 10 07:42:25 wazuh-filebeat-node-01 filebeat[3170]: 2020-07-10T07:42:25.162-0700        INFO        template/load.go:101        template with name 'wazuh' loaded.
Jul 10 07:42:25 wazuh-filebeat-node-01 filebeat[3170]: 2020-07-10T07:42:25.162-0700        INFO        [index-management]        idxmgmt/std.go:295        Loaded index template.
```

It appears the wazuh template is loaded - but we this error " 1 error: Error loading pipeline for fileset wazu..."

**Comment by 71Imapla** [comment]
Here is more detail:

```
 ERROR        [publisher_pipeline_output]        pipeline/output.go:106        Failed to connect to backoff(elasticsearch(https://dev.null-node4:9200)): Connection marked as failed because the onConnect callback failed: 1 error: Error loading pipeline for fileset wazuh/alerts: couldn't load pipeline: couldn't load json. Error: 403 Forbidden: {"error":{"root_cause":[{"type":"security_exception","reason":"no permissions for [cluster:admin/ingest/pipeline/put] and User [name=wazuh_user, backend_roles=[]

**Comment by 71Imapla** [comment]
We end up granting permissions that the error was outlining.  It is now working. Thanks for your assistance.
