### ISSUE TITLE
Agent page does not work

### ISSUE THREAD

**Issue by golaso** [wazuh/wazuh-kibana-app#2396]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.13.0/1   | 7.8.0     | ??? |

**Description**
I'm using wazuh VM.
Agent pages for HP-UX and Solaris 11 agents do not work.

**Steps to reproduce**

1. Install wazuh-agent on HP-UX ans Solaris servers using corresponding manuals
2. Register wazuh-agents using manual https://documentation.wazuh.com/3.13/user-manual/registering/index.html#register-agents
3. Go to kibana -> wazuh app -> agents -> click on hp-ux agent (see screenshots attached)

Other wazuh-agents like linux and aix work correctly.
I tried both 3.13.0 and 3.13.1 versions.

**Screenshots**
![041](https://user-images.githubusercontent.com/42374572/88074429-13672280-cb80-11ea-8c7e-1145d949047b.png)
![042](https://user-images.githubusercontent.com/42374572/88074437-14984f80-cb80-11ea-8ab9-d8b2e70f2e04.png)
![043](https://user-images.githubusercontent.com/42374572/88074445-16faa980-cb80-11ea-93ae-c80d3d5c5cfe.png)
![044](https://user-images.githubusercontent.com/42374572/88074453-18c46d00-cb80-11ea-8e44-85ede4e72fca.png)
![045](https://user-images.githubusercontent.com/42374572/88074456-1b26c700-cb80-11ea-8821-b938c8a47911.png)

**Comment by juankaromo** [comment]
Hi @golaso 

Could you check if you get any message in your browser's development console (by pressing F12) when loading the view of that agent? If so, please share it with us so that we can identify the problem.

Thank you very much!
Regards,

**Comment by golaso** [comment]
Hi @juankaromo 
Yes, having such errors in Chrome
![046](https://user-images.githubusercontent.com/42374572/88381692-89050580-cdaf-11ea-8d05-588dd975cab4.png)

**Comment by jsanchez91** [comment]
Hi @golaso,

We have prepared a solution for this error, we will publish it in the next release.

Here's how to fix it

Stop Kibana
```bash
systemctl stop kibana
```

Download and unzip this file in your Kibana environment.

[agents-welcome.zip](https://github.com/wazuh/wazuh-kibana-app/files/4972494/agents-welcome.zip)

Replace the file `agents-welcome.js` for the original:
```bash
mv agents-welcome.js /usr/share/kibana/plugins/wazuh/public/components/common/welcome/agents-welcome.js
```
 
Remove the optimize bundle folder to regenerate the cache
```bash
rm -Rf /usr/share/kibana/optimize/bundles
```

Start kibana
```bash
systemctl start kibana
```

Please tell me if you can see the agent after you change the file.
Thanks!

**Comment by juankaromo** [comment]
Solved here https://github.com/wazuh/wazuh-kibana-app/issues/2398

**Comment by golaso** [comment]
@juankaromo 
Thanks, the fix works for all kinds of agents.
Are you planning new release with it supporting Elastic 7.8.0 ?

**Comment by jsanchez91** [comment]
Hi @golaso!
I'm glad it's working for you, 
Probably the next release of support for Elasticsearch 7.8.0.

Our releases always support the latest version published by Elasticsearch and the latest version supported by Opendistro security

Related links:
- [Elasticsearch - Past releases](https://www.elastic.co/downloads/past-releases)
- [Opendistro - Version history](https://opendistro.github.io/for-elasticsearch-docs/version-history/)
