### ISSUE TITLE
Not getting anything on Audit tab

### ISSUE THREAD

**Issue by rossengeorgiev** [wazuh/wazuh-kibana-app#24]
![image](https://user-images.githubusercontent.com/2720787/27966363-e705abbc-6336-11e7-9460-e12125de5b4f.png)

**Comment by malbarral** [comment]
Hello @rossengeorgiev 

How did you get this error? Did you update the App?

If you did, you have to remove the bundles `rm -rf /usr/share/kibana/optimize/bundles` and then restart Kibana.

Best regards,
Manuel

**Comment by rossengeorgiev** [comment]
I'm on 5.4.0, and that tab hasn't ever worked I think. I went from Overview to Audit, and got the above.

**Comment by malbarral** [comment]
Hi @rossengeorgiev,

Sorry for late response. As you say, we insert a sample alert when installing the Wazuh App. 
If you did not insert the sample alert, insert it running this command in one of your ES node:

```
curl https://raw.githubusercontent.com/wazuh/wazuh-kibana-app/master/server/startup/integration_files/alert_sample.json | curl -XPUT "http://localhost:9200/wazuh-alerts-"`date +%Y.%m.%d`"/wazuh/sample" -H 'Content-Type: application/json' -d @-
```
When the alert is inserted, in the Kibana interface, go to `Management > Index patterns > wazuh-alerts-*`. Then, click on the Refresh icon.
![image](https://user-images.githubusercontent.com/8999208/28812564-8db7a03e-7695-11e7-94eb-e5f4dc438dd9.png)

Please, let us know if it works.
Best regards,
Manuel Albarral

**Comment by rossengeorgiev** [comment]
Thanks @malbarral that resolved the issue. Page works now, and so does the `Audit` dashboard.
