### ISSUE TITLE
Unsecure file permission of /usr/share/kibana/optimize/wazuh/config/wazuh.yml

### ISSUE THREAD

**Issue by NitroCao** [wazuh/wazuh-kibana-app#2402]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.13.1   | 7.8     | |

**Description**
The permission of the file `/usr/share/kibana/optimize/wazuh/config/wazuh.yml` is unsecure, everyone can see the password of REST API. 
![CleanShot 2020-07-25 at 12 22 16@2x](https://user-images.githubusercontent.com/17915615/88448553-a3071c80-ce71-11ea-81b9-e65b6bd3fc8e.png)

* OS: `CentOS 7`, installed through RPM package.

**Comment by jsanchez91** [comment]
Hello @NitroCao,
Thanks for letting us know.

We created a PR to solve this on the next launch. When this change is applied, the new installations of the plugin will create the file with the correct permissions.

Regards,
Jose
