### ISSUE TITLE
The alarm index cannot open reporting an error when trying to load data on the vulnerabilities.

### ISSUE THREAD

**Issue by guilhermerezendemarques** [wazuh/wazuh-kibana-app#2403]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.13.1   | 7.8     | |

**Description**
The alarm index cannot open reporting an error when trying to load data on the vulnerabilities.

Error open discovery or events in Vulnerability .

illegal_argument_exception at shard 1index wazuh-alerts-3.x-2020.07.26node Gzlm8UdvTXOatDck47kecg
Type
illegal_argument_exception
Reason
Field [data.vulnerability.updated] of type [keyword] does not support custom formats

**Screenshots**

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.
![error](https://user-images.githubusercontent.com/33107798/88492292-23b43e80-cf80-11ea-88f5-1c89b656728a.JPG)

**Comment by jsanchez91** [comment]
Hi @guilhermerezendemarques,

For some reason your elastic search adds the field "data.vulnerability.update" to the mapping as type "keyword".

The correct type is "date", we can try to force the change by following these steps

1. Open Kibana and got to `Dev Tools`
![image](https://user-images.githubusercontent.com/3064506/88517801-b4763300-cfef-11ea-921f-b58a6f74e69e.png)

2. Copy and paste this command in the left side of the console and run the command
```JSON
PUT wazuh-alerts-3.x-*/_mapping
{
  "properties": {
    "data.vulnerability.updated": {
      "type": "date"
    }
  }
}
```

![image](https://user-images.githubusercontent.com/3064506/88518825-65c99880-cff1-11ea-9fff-cd253f2cc215.png)

Let me know the result on the right side and if the problem has been solved

**Comment by nycterent** [comment]
just letting you know that i have experienced the same issue

**Comment by nycterent** [comment]
when trying to apply the fix I get: 

`{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "mapper [data.vulnerability.updated] of different type, current_type [keyword], merged_type [date]"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "mapper [data.vulnerability.updated] of different type, current_type [keyword], merged_type [date]"
  },
  "status" : 400
}
`

**Comment by jsanchez91** [comment]
Hi @nycterent  

Thanks for trying to remap the fields, another solution is to check the indexes with a wrong mapping and reindex them.

The first step is to detect the indexes that have mapped the field as `keyword`, execute this command in the Kibana Dev Tools:
```
GET wazuh-alerts-3.x-*/_mapping/field/data.vulnerability.updated
```

It is also necessary to check if the value of the field is a date, execute this command and check that there are no values that are not date.
```
GET wazuh-alerts-3.x-*/_search
{
  "_source": "data.vulnerability.updated", 
  "query": {
    "exists": {"field": "data.vulnerability.updated"}
  }
}
```
---
> **Let me know if any values are different from the date type before you reindex**
---
Now is time to reindex, assuming the only one affected index is wazuh-alerts-3.x-2020.07.27 (repeat this procedure if you have more affected indices), go to your server's terminal and execute these commands:
 
Stop filebeat (or logstash)
```
systemctl stop filebeat
```

2. Reindex affected index into a backup index:
```
curl -X POST "elastic_ip:9200/_reindex" -H 'Content-Type: application/json' -d'
{
	"source": {
		"index": "wazuh-alerts-3.x-2020.07.27"
	},
	"dest": {
		"index": "wazuh-alerts-3.x-backup"
	}
}'
```

3. Remove affected index:
```
curl -XDELETE elastic_ip:9200/wazuh-alerts-3.x-2020.07.27
```
4. Reindex backup index into a new index (using same name as before):
```
curl -X POST "elastic_ip:9200/_reindex" -H 'Content-Type: application/json' -d'
{
	"source": {
		"index": "wazuh-alerts-3.x-backup"
	},
	"dest": {
		"index": "wazuh-alerts-3.x-2020.07.27"
	}
}'
```

5. Remove backup index:
```
curl -XDELETE elastic_ip:9200/wazuh-alerts-3.x-backup
```

6. Restart filebeat
```
systemctl start filebeat
```

**Comment by juankaromo** [comment]
Hi @nycterent ,

Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our Slack channel or subscribe to our mailing list.

Regards,
