### ISSUE TITLE
Reporting fails when agent is pinned and compliance controls are visited

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-kibana-app#2410]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.13.1   | 7.8.0     | 0883 |

**Description**
Reports fail to be generated when an agent is pinned and the Controls tab of a compliance's dashboard is visited before clicking on generating it. 
The error output being: `5029 - Reporting was aborted (Cannot read property '_source' of undefined)`.

**Steps to reproduce**

1. From the dropdown menu select the Security Configuration Assessment module
2. Select an agent
3. From the dropdown menu select the PCI-DSS dashboard
4. Select the Controls tab
5. Switch back to the Dashboard tab
6. Click on Generate report

**Screenshots**

![image](https://user-images.githubusercontent.com/36071202/88951426-3c7d6680-d296-11ea-85bc-35f90b4df1f4.png)

**Additional context**
This is probably related to https://github.com/wazuh/wazuh-kibana-app/issues/2220 .
In this case the instructions to reproduce are clear.

**Comment by jsanchez91** [comment]
![bug_confirmed](https://user-images.githubusercontent.com/3064506/89896423-b50ced00-dbdd-11ea-9e9d-62a79585cfff.gif)

```JSON
```

**Comment by jsanchez91** [comment]
**Update**

The error has been fixed, it was due to a problem with updating the component.
![report_fixed](https://user-images.githubusercontent.com/3064506/90223876-28497580-de0f-11ea-9e0c-256a96a016a2.gif)
