### ISSUE TITLE
Rules details show blank page

### ISSUE THREAD

**Issue by pablotr9** [wazuh/wazuh-kibana-app#2411]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.13   | 7.x     | - |

**Description**
When we open the details section of a rule, if any of the `details.` fields is an object, the current tab fails and shows a blank page. 
The app expect these fields to be a string, and when they are an object the component fails.

**Steps to reproduce**

1. Create a custom rule and add this line to the rule:
```
    <list field="hostname" lookup="match_key_value" check_value="enabled">etc/lists/test</list>
```
2. Click on **Management** -> **Rules** -> **Local rules** -> Click on the new rule
3. See error

![image (84)](https://user-images.githubusercontent.com/35685689/89030735-633cab00-d331-11ea-95a8-52807eb6c816.png)

![image (85)](https://user-images.githubusercontent.com/35685689/89030727-5ddf6080-d331-11ea-862e-0e287454b6fd.png)

**Comment by juankaromo** [comment]
Fixed here https://github.com/wazuh/wazuh-kibana-app/commit/68f22db538d1520bac0cff327257066d90af5d0d
