### ISSUE TITLE
RBAC: Remove adminMode

### ISSUE THREAD

**Issue by victorst79** [wazuh/wazuh-kibana-app#2414]
**Description**
The entire _adminMode_ system will be removed by the new role system. All places where _adminMode_ is located and their use have been identified. The following table indicates how it is used and what file it is in.

**Progress**
- [x] Sample data: sample-data.tsx
- [x] ???: management-welcome.js
- [x] CallOut Sample-data: wz-visualize.js
- [x] ???: wz-menu-management.js
- [x] Settings: wz-menu-settings.js
- [x] ???: agents-preview.js
- [x] ???: agent.js
- [x] ???: group.js
- [x] ???: management.js
- [x] Configuration overview: configuration-overview.js
- [x] ???: configuration-switch.js
- [x] check admin mode: wz-fetch.js
- [x] management agents: actions-buttons-agents.js
- [x] group configuration: actions-buttons-files.js
- [x] new group: actions-buttons-main.js
- [x] ???: group-agents-table.js
- [x] group config editor| groups-editor.js
- [x] setAdminMode: groups-overview.js
- [x] ???: groups-table.js
- [x] ???: check-admin-mode.js
- [x] remove agent from group: columns-agents.js
- [x] edit group configuration: columns-mains.js
- [x] manage files, rules, cdblist...: actions-buttons.js
- [x] cdb list rules: list-editor.js
- [x] ruleset-editable: ruleset-editor.js
- [x] ???: ruleset-overview.js
- [x] ???: ruleset-table.js
- [x] ???: section-selector.js
- [x] check admin mode request:  check-admin-mode.js
- [x] show action in cdb list: ruleset/..../columns.js
- [x] restart cluster: actions-buttons-main.js
- [x] ???: status-overview.js
- [x] check admin mode request: management/.../check-admin-mode.js
- [x] ???: settings.js
- [x] redux update adminMode: appStateActions.js
- [x] redux reducer: appStateReducers.js
- [x] allow request adminMode: wazuh-api.js
- [x] set initial value for adminMode in Redux: app.js
- [x] initial admin value in config: get-config.js
- [x] initial wazuh config: initial-wazuh-config.js
- [x] update configuration backend: update-configuration.js
- [x] devtools admin mode: dev-tools.js
- [x] sample data app backend: wazuh-elastic.js

**Comment by Desvelao** [comment]
The routes for sample data were using the admin mode validation to do the requested actions.
- `POST /elastic/samplealerts/{category}`
- `DELETE /elastic/samplealerts/{category}`

Update configuration pf wazuh.yml file requires admin mode too.

These 2 actions need to be replaced by `administrator` user role of Wazuh API.
