### ISSUE TITLE
Add new configuration view settings for GCP integration

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#2418]
Hi team,

In 3.13.x it is added a new settings the new Google Cloud Platform integration. Here I paste the output of the API request:

```
<gcp-pubsub>
    <pull_on_start>yes</pull_on_start>
    <interval>1m</interval>
    <project_id>wazuh-dev</project_id>
    <subscription_name>wazuhdns</subscription_name>
    <logging>debug</logging>
    <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
</gcp-pubsub>
```

It seems that the module path is not `wodles/gcp-pubsub` , it is `wodles/gcloud` , at least in the manager, I don't know in the agent (the logical thing is that it is the same path in both).

Docs reference  https://documentation.wazuh.com/3.13/user-manual/reference/ossec-conf/gcp-pubsub.html

Regards,

**Comment by Desvelao** [comment]
## Screenshots
- <ins>**Google Cloud Pub/Sub module in Configuration main**</ins>:

  - Manager
![image](https://user-images.githubusercontent.com/34042064/90119915-76e90800-dd5a-11ea-8085-dd4cb22720da.png)
  - Agent
![image](https://user-images.githubusercontent.com/34042064/90119998-941dd680-dd5a-11ea-8fc0-f8ae16e0c60f.png)

<ins>**When there is no configuration for the module**</ins>

![image](https://user-images.githubusercontent.com/34042064/90121099-dc89c400-dd5b-11ea-9c10-fc7df6b92aaf.png)

<ins>**Module configuration preview**</ins>

![image](https://user-images.githubusercontent.com/34042064/90121702-96813000-dd5c-11ea-9ce5-eb687ec2df8f.png)
