### ISSUE TITLE
KIbana app for 3.13 with no namespace issue

### ISSUE THREAD

**Issue by djmgit** [wazuh/wazuh-kibana-app#2421]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.13   | 7.x     |  |

We have recently upgraded our Wazuh manager to 3.5 from 3.11. During the setup of 3.11 manager and the kibana app we faced issue with the app which was continuously going to crashed state. #2081 is the corresponding issue.
@Joanes04 provided me with a different built of the kibana app which handled kibana with namespaces which in all probability had caused the issue in the first place.

Now we will have to change the kibana app again to make it support 3.13. Is the app mentioned in the doc has got the required fix for kibana namespaces? If not, where can I find the required build?

**Comment by Joanes04** [comment]
Hi @djmgit ,

From the version of **Wazuh UI 3.13.X** is already solved the problem you told me for the custom namespace, so you can install the new release without problems. 
Any other question, do not hesitate to comment. 

Regards,
Alberto
