### ISSUE TITLE
Security Events redesing

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#2428]
Hi team,

It would be interesting to give a face-lift to the `Security events` module, since it is the general module and the most frequently used. As I leave in the sketch below, a redistribution of the visualizations is requested. In addition, we can put a table with the last 5 alerts, similar to the one we already use in the flyouts of FIM and MITRE, and with the clickable fields to take you to their panel.

![image](https://user-images.githubusercontent.com/21195730/90023090-98db7f80-dcb3-11ea-8d69-2ef8dff43765.png)

The steps to be executed are:

- [x] Change the `Alerts` visualization to a new one called Top Mitre ATT&CK tactics.
- [x] Remove the `Top 5 rules groups` and `Agents status` visualizations, and replace them with the visualization below (`Alerts Evolution - Top 5 agents`)
- [x] Create a new Table containing the last 5 alerts, which can be expanded with their information. Similar to what we already do in flyouts.

Regards,

**Comment by pablotr9** [comment]
This is how the new dashboard looks like:
![image](https://user-images.githubusercontent.com/35685689/90601752-f6625580-e1f8-11ea-9090-ad66208e601e.png)
The new table shows the first 10.000 results of the current search:
![image](https://user-images.githubusercontent.com/35685689/90602126-87393100-e1f9-11ea-9e80-f1e71d333c36.png)
