### ISSUE TITLE
Navigable agents name in Events

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#2429]
Hi team,

In 3.13 the possibility was introduced that in the Discover of the modules (Events tab) you could click on certain fields and these would be navigable to their respective panels.

Now it's asked that the `agent.name` field (that is available in all the modules) is navigable, and it takes to the Welcome Screen of this agent.

![image](https://user-images.githubusercontent.com/21195730/90024381-1653bf80-dcb5-11ea-8d13-4a0a7ffe8cf9.png)

Keep in mind that the ideal is that it comes out only if you are NOT inside an agent, otherwise it would always be the same value all the column (because you are filtering by an agent).

Regards,

**Comment by Desvelao** [comment]
Module/Events tab has been refactorized:
- Created a function to enhance some alert fields. It can be expanded as necessary:
  - `rule.id`: redirect in a new tab to `#/manager/rules?tab=rules&redirectRule={RULE_ID}`.
  - `agent.id`: redirect in a new tab to `#/agents?tab=welcome&agent={AGENT_ID}`.
  - `agent.name`: redirect in a new tab to `#/agents?tab=welcome&agent={AGENT_ID}`.
  - `syscheck.path`: open a flyout.
  - `rule.mitre.id`: open a flyout.
- Removed FIM and MITRE custom Events components

Screenshot:
![enhance-discover-table-cells](https://user-images.githubusercontent.com/34042064/90728194-c3859380-e2c4-11ea-9d76-349dc8ec513f.png)
