### ISSUE TITLE
Wazuh 4.0: Fix broken sections

### ISSUE THREAD

**Issue by pablotr9** [wazuh/wazuh-kibana-app#2431]
Hi team, 
With the latest Wazuh API v4, many sections have stopped working and needs to be fixed:

- [x] Management -> Logs. The table is stuck on loading. Fixed here: f8f0641690514aeca63148f843e57fd3902baaf4
![image](https://user-images.githubusercontent.com/35685689/90119605-11951700-dd5a-11ea-8844-ac87f6106144.png)

- [x] Management -> Logs: Filtering by log level doesn't work. Fixed here: 041bd99d67e2c3783dd2989eb290ed66e488a432
- [x] Management -> Logs: Debug2 level is missing. Fixed here: c6d88ab90973fd71161e82033153a234052832bb
- [x] Management -> Logs: Filter by daemon doesn't work. Fixed here: c1c80c67e3f23134521030bf57779c5113a8c470

- [x] Management -> Status. Section stuck on loading. Fixed here: 2efa014563e708348a20ca15084157e73a1abfef
![image](https://user-images.githubusercontent.com/35685689/90123508-3c359e80-dd5f-11ea-841e-4abf43db62f5.png)

- [ ] Management -> Status. Version is missing: (Pending API)
![image](https://user-images.githubusercontent.com/35685689/90128054-82dac700-dd66-11ea-8b85-b64e0c4ab7b2.png)

- [x] Management -> Rules. Error saving rules files: Fixed here: 66cc9ee446674b6b39c16b739151c072da906731
![image](https://user-images.githubusercontent.com/35685689/90128294-f5e43d80-dd66-11ea-836c-cf366c4f1227.png)
- [x] Management -> Decoders. Error saving decoders files: Fixed here: 66cc9ee446674b6b39c16b739151c072da906731
- [x] Management -> CDB Lists. Error saving CDB lists files: Fixed here: 66cc9ee446674b6b39c16b739151c072da906731
- [x] Management -> Configuration. Error saving ossec.conf file: Fixed here: a164420961fbb7b292593c677d930a7233c8ebed

- [x] With the new format in the v4 API, all failed request are now treated as successful requests and the toast shows that the action was ok even when it fails. Fixed here: 1ce44d60f38d3794ba42eb9cce41ab497a28814c
![Peek 2020-08-14 10-23](https://user-images.githubusercontent.com/35685689/90229618-7e6ee680-de18-11ea-913b-75b44e49b0c7.gif)

- [x] Management -> Groups throws an error. Fixed here: cbcc35d4f862428720d742c43c26c464699f96be
![image](https://user-images.githubusercontent.com/35685689/90233474-816cd580-de1e-11ea-8ae8-62710ef9efd8.png)

- [x] Management -> Groups: Edit group configuration doesn't work. Fixed here: cbcc35d4f862428720d742c43c26c464699f96be

- [x] Agents -> Search bar doesn't work Fixed here: b6ecab56ade59920355952b8e7b19ccac59eb3ab
![image](https://user-images.githubusercontent.com/35685689/90237535-b5e39000-de24-11ea-8733-29ca11e9e7d0.png)

- Related issue https://github.com/wazuh/wazuh-kibana-app/issues/2441

**Comment by pablotr9** [comment]
Working on this branch: https://github.com/wazuh/wazuh-kibana-app/tree/4.0-7.8-fix-sections

**Comment by jsanchez91** [comment]
- [ ] On Kibana start: When no index pattern has been created, starting the Kibana wazuh service throws an error
##### Error:
```
server    log   [11:36:15.484] [error] Wazuh app had en error importing objects into Elasticsearch.Unexpected token u in JSON at position 0
```
##### Solution: Change the error message 
```
server    log   [11:43:29.694] [error] Wazuh app had en error importing objects into Elasticsearch. No index pattern found, open the interface to generate
```

**Comment by jsanchez91** [comment]
- [ ] Modules -> IIntegrity monitoring -> Inventory: Filters don't work

##### Error:
![image](https://user-images.githubusercontent.com/3064506/90383168-0f93c680-e080-11ea-889d-0d22736c6f76.png)

##### Solved
![image](https://user-images.githubusercontent.com/3064506/90384158-6e0d7480-e081-11ea-9aae-af368e3c4c86.png)

**Comment by jsanchez91** [comment]
- [ ] Modules -> IIntegrity monitoring -> Custom discover (Flyout): The details of the rules are not displayed correctly

![image](https://user-images.githubusercontent.com/3064506/90391373-520fd000-e08d-11ea-9d23-3b31200eb71d.png)

**Comment by jsanchez91** [comment]
- [ ] Modules -> IIntegrity monitoring -> Events -> Discover flyout: When the page reloads after opening the details of a file, the details do not open again
![file_details_error](https://user-images.githubusercontent.com/3064506/90477146-2c390880-e12b-11ea-998f-53bb6a9cbede.gif)

**Comment by jsanchez91** [comment]
- [ ] Modules -> Any module: Reload changes the selected agent
![error_agent_pinned_reload](https://user-images.githubusercontent.com/3064506/90501155-30295280-e14c-11ea-9800-42135584b265.gif)

**Comment by pablotr9** [comment]
- [ ] Statistics: Breadcrumb is not updated.
- [ ] Statistics: Visualizations are blank

![image](https://user-images.githubusercontent.com/35685689/90604252-daf94980-e1fc-11ea-9822-3dd9e05a5a0c.png)

**Comment by pablotr9** [comment]
- [ ] Editing ossec.conf with cluster enabled throws an error.
- [ ] If the cluster mode is modified from the app it only takes effect if we manually restart the Wazuh server.
- [ ] If the cluster mode is modified, the app needs to be opened in a new tab to refresh the cookie value as it's refreshed in the healthcheck (it should be refreshed if we refresh the current tab)

**Comment by pablotr9** [comment]
- [ ] If we are in Management -> Configuration. The wrong Configuration section of Settings is highlighted
![image](https://user-images.githubusercontent.com/35685689/90724159-5ec73a80-e2be-11ea-966a-2df3a9120142.png)

**Comment by pablotr9** [comment]
- [ ] Management -> Cluster is not loading Timelion visualizations: 
![image](https://user-images.githubusercontent.com/35685689/90729806-63442100-e2c7-11ea-8288-2dd1e25def2a.png)

**Comment by pablotr9** [comment]
The Security Alerts table is not working correctly
![image](https://user-images.githubusercontent.com/35685689/90864382-d6fe3080-e390-11ea-8bcb-795274ff4d21.png)

**Comment by jsanchez91** [comment]
- [ ] Agents -> Inventory data: The tables do not work properly, the search and paging must be corrected.
- [ ] Agents -> Inventory data: The downloaded CSV does not apply search filter
- [ ] Agents: The downloaded CSV does not apply the filters
