### ISSUE TITLE
SCA section bug fixes and improvements

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#2441]
Hi team,

We need to fix some bugs and make some improvements within the SCA section. They are listed below:

- [x] All the commands appear together on the same line
![image](https://user-images.githubusercontent.com/21195730/90608372-d33ca380-e202-11ea-925d-c100e948acfb.png)

- [x] I wonder if this also applies to rationals or descriptions, which we cannot put aside). @jsanchez91 
![image](https://user-images.githubusercontent.com/21195730/90608390-d9328480-e202-11ea-99b7-12fcf8527822.png)

- [x] There is no help for the user on how to search. Nor is there any autocompletion. @jsanchez91 
![image](https://user-images.githubusercontent.com/21195730/90608411-e3548300-e202-11ea-98f8-d29f39859104.png)

- [x] These numbers can be clicked and the filter applied. @Desvelao 
![image](https://user-images.githubusercontent.com/21195730/90608428-ea7b9100-e202-11ea-9ae6-f449d0dd008b.png)

- [x] When I download the report in the "Export formatted" button, it downloads a file with double extension: .csv.csv @jsanchez91 
![image](https://user-images.githubusercontent.com/21195730/90608435-eea7ae80-e202-11ea-9d73-05625c486e9d.png)

- [x] Too much font size and bold: @jsanchez91 
![image](https://user-images.githubusercontent.com/21195730/90608441-f23b3580-e202-11ea-9797-bbb626f26c50.png)

- [x] The agent pin doesn't change the content when I change agents (There's the pin in the windows and what I see is redhat data). @Desvelao 
❓ This seems to be working in the current branch `4.0-7.8-fix-sections`
![image](https://user-images.githubusercontent.com/21195730/90608450-f6675300-e202-11ea-806f-adc68934252c.png)

- [x] Same in the main SCA panel @Desvelao 
🔧 It now shows to SCA policies table
![image](https://user-images.githubusercontent.com/21195730/90608459-f9624380-e202-11ea-9f42-bac7d7e7d08f.png)

- [x] Color EuiHealth for the agents with `never_connected` status @Desvelao 
![image](https://user-images.githubusercontent.com/34042064/90765493-4ff67d00-e2ea-11ea-9a11-76d3e4dae9d5.png)

Regards,

**Comment by jsanchez91** [comment]
These changes have been added in this PR: https://github.com/wazuh/wazuh-kibana-app/pull/2445
