### ISSUE TITLE
Registering agent by using dashboard

### ISSUE THREAD

**Issue by nizarakbarm** [wazuh/wazuh-kibana-app#245]
Sorry, is there a reason why in wazuh 3.1.0 cannot register agent by using dashboard?

**Comment by JuanjiJG** [comment]
Hi @nizarakbarm,

Currently, Wazuh doesn't support agent registering through the app. We'll be working on this functionality in the future.

If you still have more questions or problems, feel free to post a new issue in our repository.

Regards,
Juanjo
