### ISSUE TITLE
Bugs found during testing of 4.0.0 - 7.8.0

### ISSUE THREAD

**Issue by pablotr9** [wazuh/wazuh-kibana-app#2457]
Hi team, 

These are the bugs we have found while testing WUI 4.0.0-7.8.0  (https://github.com/wazuh/wazuh-kibana-app/issues/2451) 

- [x] Security Alerts table (Security events) is not updated with KQL filters (rule.level >= 10)
- [x] Inventory data report is not showing all tables, only 2 are being shown in the generated PDF.
- [x] Management -> Status -> Last registered agent: It was always showing manager information. It has been fixed and it now shows the latest registered agent.
- [x] DevTools filters were not correctly sent to the API so they were being ignored. Fixed
- [x] Management -> Logs: Export as CSV button is missing
- [x] Management -> Groups: Edit current search does not update the result
- [x] Generate report error in `Modules/Security` events when the table is empty
![image](https://user-images.githubusercontent.com/34042064/92734294-b36b4c00-f378-11ea-83d8-035745674e28.png)
- [x] Colors stats are missing in Dark mode
![image](https://user-images.githubusercontent.com/34042064/92734820-2c6aa380-f379-11ea-8c73-fe1d62deeebf.png)
![image](https://user-images.githubusercontent.com/34042064/92746346-81131c00-f383-11ea-9ec6-bb6fb7c24f2f.png)

- [x] Generating report of a group throws an error: 
![image](https://user-images.githubusercontent.com/35685689/92737155-3097c080-f37b-11ea-9644-b5b070e9a6f9.png)
- [x] Remove `Promise.error` of `fetch-api.js`
- [x] Error after restart cluster when save a custom rule
![image](https://user-images.githubusercontent.com/34042064/92738105-f7138500-f37b-11ea-8de1-daffe6206528.png)
- [x] Adding agents to group - Dark mode
![image](https://user-images.githubusercontent.com/34042064/92739688-6fc71100-f37d-11ea-8286-caed0a5de178.png)
- [x] Error exporting group details with granular options
![image](https://user-images.githubusercontent.com/34042064/92740253-e237f100-f37d-11ea-98ce-b954828dcbfd.png)
- [x] Restarting the cluster after save ossec.conf in Management/Configuration
![image](https://user-images.githubusercontent.com/34042064/92741349-cda82880-f37e-11ea-9704-0692ddf06e79.png)
- [x] Export button is missing in Management/Configuration for an agent
- [x] Agent stats in Management directory doesn't apply the filter in Agents
![image](https://user-images.githubusercontent.com/34042064/92760021-993d6800-f390-11ea-9052-e6d1b164af11.png)
- [x] Management -> Rules: PCI filter is not working: 
![image](https://user-images.githubusercontent.com/35685689/92876491-72bc1300-f40a-11ea-873e-f18f5c807cd1.png)
- [x] Export of group files as CSV throws an error
- [x] Endpoint `/api/request` with `path=/ping` is not working. Adapted to 4.0 
- [x] `wazuhNotReadyYet` callout continues showing after the restart of `WzRestartClusterOrManagerCallout`  component fails
- [x] The closing button of the popover does not work 
![popover_close](https://user-images.githubusercontent.com/3064506/93057578-6fc15c80-f66e-11ea-9116-9de00395a40b.gif)
- [x] When selecting or deselecting an agent, the columns of the "Security Alerts" table must be refreshed
![unpin_agent](https://user-images.githubusercontent.com/3064506/93058892-45709e80-f670-11ea-9ece-a602d1cf2c2c.gif)
- [x] In low resolution the columns of the "Security Alerts" table overlap
![image](https://user-images.githubusercontent.com/3064506/93059330-d5164d00-f670-11ea-945d-a3099c32cb70.png)
- [x] When add `rule.mitre.id` column to discover in Module/Events, if the cell had `-` as value, the method of enhancing the cells fails
- [x] SCA is missing in the Modules directory when it is showing in Wazuh main menu
- [x] Wazuh logo in Kibana side menu is distorted when going to `Stack Monitoring`.
> This happens in Kibana 7.8.0 no OSS sections, like `Stack Monitoring` and `Canvas` and can't be solved. Kibana 7.9.0 fixed on this issue: https://github.com/elastic/kibana/pull/69767 (changes: https://github.com/elastic/kibana/commit/43f60ef7dde1566a924cd9a89838c8d2f8c6980f)

![image](https://user-images.githubusercontent.com/34042064/93356552-9da9cb00-f83f-11ea-93c8-9a1c5d557c3f.png)

- [x] Health check is not showing some errors 
![image](https://user-images.githubusercontent.com/35685689/93484454-36088400-f902-11ea-8b51-21e072f85efe.png)

**Comment by jsanchez91** [comment]
PR with the changes: https://github.com/wazuh/wazuh-kibana-app/pull/2417
