### ISSUE TITLE
[Development] Broken section Management > Status

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-kibana-app#2458]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.x   | 7.x     | 4001|

**Steps to reproduce**

1. Go to 'Management section'
2. Click on 'Status'
3. Open browser console
4. See errrors

**Screenshots**
![image](https://user-images.githubusercontent.com/10210567/92774700-05729880-f39e-11ea-81ea-54706ebf5b75.png)

**Comment by Desvelao** [comment]
The fetch data method was unhandled. Added a try/catch block

**Comment by Desvelao** [comment]
An error is happening in some environments:
![image](https://user-images.githubusercontent.com/34042064/93876601-66bc3500-fcd7-11ea-99a5-d772c42dc121.png)

To solve this problem:
Modify the value of `validate_responses` of `Ture` to `False` in `/var/ossec/api/scripts/wazuh-apid.py`:
```
validate_responses=False
```
