### ISSUE TITLE
[Development] Error responses in PUT /statistics endpoint

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-kibana-app#2459]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.x   | 7.x     | 4001 |

**Steps to reproduce**

1. Go to Statistics section
2. See errors in the browser's console.

**Screenshots**
![image](https://user-images.githubusercontent.com/10210567/92778472-7f585100-f3a1-11ea-99b9-a5cc1a4bc58a.png)

**Comment by pablotr9** [comment]
Closing this issue as it couldn't be reproduced in latest version (branch `4.0-7.8`)
