### ISSUE TITLE
need 7.9.1.zip

### ISSUE THREAD

**Issue by yjzskid** [wazuh/wazuh-kibana-app#2463]
wazuh 3.13.1
Plugin installation was unsuccessful due to error "Plugin wazuh [7.9.0] is incompatible with Kibana [7.9.1]"

so help

**Comment by pablotr9** [comment]
Hi @yjzskid ! 

Our Wazuh plugin for Kibana is not compatible with Kibana 7.9.1, the team is currently working on it and it will be ready as soon as possible! 
You can downgrade your Kibana to 7.9.0 so you can install our latest Wazuh plugin version for Wazuh v3.13.1.

If you want to know more about available versions, please check our compatibility matrix here:  https://github.com/wazuh/wazuh-kibana-app#wazuh---kibana---open-distro-version-compatibility-matrix

Best Regards,
Pablo Torres
