### ISSUE TITLE
The suggested credentials to connect to the API are outdated.

### ISSUE THREAD

**Issue by s-ocando** [wazuh/wazuh-kibana-app#2464]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.0   | 7.8.0     | 4001 |

**Description**
The suggested credentials to connect to the API are outdated. 

**Steps to reproduce**

1. Make a new installation where Kibana is installed in a different host that the Wazuh manager. 
2. Navigate to the Wazuh Kibana plugin. 
3. Read error message. 

**Screenshots**
![image](https://user-images.githubusercontent.com/61882981/93065976-a9e42b80-f679-11ea-8c36-4ce3cc7d7e5b.png)

The configuration file currently looks like: https://github.com/wazuh/wazuh-kibana-app/blob/4.0-7.8/server/lib/initial-wazuh-config.js#L174-L179

**Comment by pablotr9** [comment]
Thanks @s-ocando, this has been fixed here: https://github.com/wazuh/wazuh-kibana-app/commit/d3776b015f5e4cab7346f5b1f8af039e5fe7afa3
