### ISSUE TITLE
Support for kibana version 7.9.1 

### ISSUE THREAD

**Issue by VN1977** [wazuh/wazuh-kibana-app#2465]
Could you please release the new version for kibana 7.9.1.

**Comment by jsanchez91** [comment]
Hi @VN1977,

Wazuh 3.13.1 with support for ELK 7.9.1 has just been released.

Here is the link to the Wazuh app https://packages.wazuh.com/wazuhapp/wazuhapp-3.13.1_7.9.1.zip
