### ISSUE TITLE
ERROR3099 - Some Wazuh daemons are not ready in node

### ISSUE THREAD

**Issue by Wolvez1911** [wazuh/wazuh-kibana-app#2466]
I am getting this error from the Kibana app on a new install on Debian 10:
ERROR3099 - Some Wazuh daemons are not ready in node
'node01' (wazuh-modulesd->failed, ossec-analysisd->failed,
ossec-execd->failed, wazuh-db->failed, ossec-remoted->failed)

I have Elasticsearch(7.9.1) and Logstash(7.9.1) installed as a 3 node cluster and Wazuh(3.13.1), Filebeat(7.9.1), and Kibana(7.9.0) on a separate node.  I am seeing Wazuh alerts and my firewall logs in discover in Kibana so I am assuming that Elasticsearch, Logstash, Filebeat and Kibana are all working correctly.

From what I can tell all the Wazuh-manager processes are running but the Wazuh-api seems to think they are not.  I tried my best but wasn't able to figure it out on my own.  I need a little push in the right direction.  I'm sure you will need more info.  Just let me know what you need.

# /var/ossec/bin/ossec-control status
`wazuh-clusterd not running...
wazuh-modulesd is running...
ossec-monitord is running...
ossec-logcollector is running...
ossec-remoted is running...
ossec-syscheckd is running...
ossec-analysisd is running...
ossec-maild is running...
ossec-execd is running...
wazuh-db is running...
ossec-authd is running...
ossec-agentlessd not running...
ossec-integratord not running...
ossec-dbd not running...
ossec-csyslogd not running...`

# systemctl status wazuh-manager.service
`● wazuh-manager.service - Wazuh manager
   Loaded: loaded (/etc/systemd/system/wazuh-manager.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2020-09-13 18:12:16 PDT; 20h ago
    Tasks: 94 (limit: 2355)
   Memory: 247.9M
   CGroup: /system.slice/wazuh-manager.service
           ├─20247 /var/ossec/bin/ossec-authd
           ├─20261 /var/ossec/bin/wazuh-db
           ├─20284 /var/ossec/bin/ossec-execd
           ├─20298 /var/ossec/bin/ossec-maild
           ├─20305 /var/ossec/bin/ossec-analysisd
           ├─20345 /var/ossec/bin/ossec-syscheckd
           ├─20362 /var/ossec/bin/ossec-remoted
           ├─20403 /var/ossec/bin/ossec-logcollector
           ├─20455 /var/ossec/bin/ossec-monitord
           └─20510 /var/ossec/bin/wazuh-modulesd

Sep 13 18:12:08 zwk env[20167]: Started ossec-execd...
Sep 13 18:12:08 zwk env[20167]: Started ossec-maild...
Sep 13 18:12:09 zwk env[20167]: Started ossec-analysisd...
Sep 13 18:12:10 zwk env[20167]: Started ossec-syscheckd...
Sep 13 18:12:11 zwk env[20167]: Started ossec-remoted...
Sep 13 18:12:12 zwk env[20167]: Started ossec-logcollector...
Sep 13 18:12:13 zwk env[20167]: Started ossec-monitord...
Sep 13 18:12:14 zwk env[20167]: Started wazuh-modulesd...
Sep 13 18:12:16 zwk env[20167]: Completed.
Sep 13 18:12:16 zwk systemd[1]: Started Wazuh manager.`

# systemctl status wazuh-api.service
`● wazuh-api.service - Wazuh API daemon
   Loaded: loaded (/etc/systemd/system/wazuh-api.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2020-09-13 22:08:28 PDT; 16h ago
     Docs: https://documentation.wazuh.com/current/user-manual/api/index.html
 Main PID: 24255 (nodejs)
    Tasks: 11 (limit: 2355)
   Memory: 53.7M
   CGroup: /system.slice/wazuh-api.service
           └─24255 /usr/bin/nodejs /var/ossec/api/app.js

Sep 13 22:08:28 zwk systemd[1]: Started Wazuh API daemon.`

# curl -u shaiPewohp3YooQu:xxxxxxxxxxxxxxxxxxxx -X GET localhost:55000/manager/info?
`{"error":1017,"message":
  "Some Wazuh daemons are not ready in node 'node01' 
  (wazuh-modulesd->failed, 
  ossec-analysisd->failed, 
  ossec-execd->failed, 
  wazuh-db->failed, 
  ossec-remoted->failed)"}`

# cat /usr/share/kibana/optimize/wazuh/logs/wazuhapp.log
`{"date":"2020-09-14T21:02:54.780Z","level":"info","location":"initialize","message":"Kibana index: .kibana"}
{"date":"2020-09-14T21:02:54.781Z","level":"info","location":"initialize","message":"App revision: 0885"}
{"date":"2020-09-14T21:02:54.781Z","level":"info","location":"initialize","message":"Total RAM: 1996MB"}
{"date":"2020-09-14T21:02:56.215Z","level":"info","location":"initialize","message":"App ready to be used."}
{"date":"2020-09-14T21:18:00.018Z","level":"error","location":"wazuh-api:makeRequest","message":"Wazuh API is online but Wazuh is not ready yet"}
{"date":"2020-09-14T21:18:00.313Z","level":"error","location":"wazuh-api:makeRequest","message":"Wazuh API is online but Wazuh is not ready yet"}
{"date":"2020-09-14T21:18:00.471Z","level":"error","location":"update-registry:updateAPIHostname","message":"Cannot set property 'extensions' of undefined"}
{"date":"2020-09-14T21:18:00.471Z","level":"error","location":"wazuh-api:setExtensions","message":"Cannot set property 'extensions' of undefined"}
{"date":"2020-09-14T21:18:00.564Z","level":"error","location":"wazuh-api:makeRequest","message":"Wazuh API is online but Wazuh is not ready yet"}
`

# cat /var/ossec/logs/api.log
`...
WazuhAPI 2020-09-14 14:02:58 shaiPewohp3YooQu: [::ffff:127.0.0.1] GET /cluster/status? - 200 - error: '1017'.
WazuhAPI 2020-09-14 14:15:01 shaiPewohp3YooQu: [::ffff:127.0.0.1] GET /agents/?offset=0&limit=1&q=id!%3D000 - 200 - error: '1017'.
WazuhAPI 2020-09-14 14:15:02 shaiPewohp3YooQu: [::ffff:127.0.0.1] GET /cluster/status? - 200 - error: '1017'.
WazuhAPI 2020-09-14 14:18:00 shaiPewohp3YooQu: [::ffff:127.0.0.1] GET /manager/info? - 200 - error: '1017'.
WazuhAPI 2020-09-14 14:30:01 shaiPewohp3YooQu: [::ffff:127.0.0.1] GET /agents/?offset=0&limit=1&q=id!%3D000 - 200 - error: '1017'.
...`

**Comment by Wolvez1911** [comment]
I found the cause of my issue.  /proc was mounted with **hidepid=2**.  Changing this to **hidepid=1** fixed the issue.  Hopefully this helps someone else.

**Comment by goetzk** [comment]
I spent almost a full day trying to find this solution before it was directed to me in Slack. In case it helps lift this result in to someone elses Google results here are the most relevant keywords i used.

wazuh kibana 500
wazuh "INFO: Checking API host id [default]"
ERROR 3099 - Some Wazuh daemons are not ready yet in node "manager 01"

Thanks Wolvez for the solution and mari0rh for pointing me to it!
