### ISSUE TITLE
[Backport] Expand supported deployment variables to 3.13.x

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-kibana-app#2468]
Hi team,

We need to copy the code of this Issue https://github.com/wazuh/wazuh-kibana-app/issues/2382 to version 3.13.1

When the remote connection of the Manager uses the TCP protocol, the parameter `PROTOCOL="TCP"` must be added to the snippet code

**Comment by pablotr9** [comment]
Added here: e754f1daa9711ec96d6fb3701cb292abb018815b
