### ISSUE TITLE
Wazuh API seems to be down

### ISSUE THREAD

**Issue by Himanshu2244** [wazuh/wazuh-kibana-app#2470]
Hi, Please help fixing the issue.

I have installed wazuh(V 3.13.1) wazuh_api(V3.13.1), filebeat(V7.9.1), elasticsearch(V7.9.1) and kibana(V7.9.1). 

I could able to load the kibana UI on the browser however the api is not working. Here is the network call error: message":"3005 - Client network socket disconnected before secure TLS connection was established","code":3005,"statusCode":500}
<img width="1440" alt="Screenshot 2020-09-18 at 17 55 04" src="https://user-images.githubusercontent.com/52542432/93597109-22c7e800-f9d8-11ea-90a6-65b048debdb6.png">

API LOG:
T /cluster/status? - 400 - error: '802'.
WazuhAPI 2020-09-18 10:00:00 : [::ffff:10.5.144.213] GET /agents?offset=0&limit=1&q=id!%3D000 - 400 - error: '802'.
WazuhAPI 2020-09-18 10:00:00 : [::ffff:10.5.144.213] GET /cluster/status? - 400 - error: '802'.
WazuhAPI 2020-09-18 11:29:56 : Listening on: http://:::55000
WazuhAPI 2020-09-18 12:00:48 api: [::1] User: "api" - Authentication failed.

**Comment by adampielak** [comment]
`grep "^config" /var/ossec/api/configuration/config.js`

**Comment by Himanshu2244** [comment]
here it is:
[root@wazuh-server ~]# grep "^config" /var/ossec/api/configuration/config.js
config.ossec_path = "/var/ossec";
config.host = "0.0.0.0";
config.port = "55000";
config.https = "no";
config.basic_auth = "yes";
config.BehindProxyServer = "no";
config.logs = "info";
config.cors = "yes";
config.cache_enabled = "yes";
config.cache_debug = "no";
config.cache_time = "750";
config.log_path = config.ossec_path + "/logs/api.log";
config.use_only_authd = false;
config.drop_privileges = true;
config.experimental_features  = false;
config.secureProtocol = "TLSv1_2_method";
config.honorCipherOrder = true;
config.ciphers =  "";
[root@wazuh-server ~]#

**Comment by adampielak** [comment]
Change config.https = "no" to "yes"

**Comment by Himanshu2244** [comment]
here it is:
[root@wazuh-server ~]# grep "^config" /var/ossec/api/configuration/config.js
config.ossec_path = "/var/ossec";
config.host = "0.0.0.0";
config.port = "55000";
config.https = "no";
config.basic_auth = "yes";
config.BehindProxyServer = "no";
config.logs = "info";
config.cors = "yes";
config.cache_enabled = "yes";
config.cache_debug = "no";
config.cache_time = "750";
config.log_path = config.ossec_path + "/logs/api.log";
config.use_only_authd = false;
config.drop_privileges = true;
config.experimental_features  = false;
config.secureProtocol = "TLSv1_2_method";
config.honorCipherOrder = true;
config.ciphers =  "";
[root@wazuh-server ~]#

**Comment by Himanshu2244** [comment]
Thanks it worked
