### ISSUE TITLE
[4.0] Filters added by the user, are blocked in Modules/Mitre/Framework

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#2473]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.x   | 7.x     | 444 |

**Description**
Filters are blocked in Modules/Mitre/Framework if these are added before to go this tab. They can't be removed

**Steps to reproduce**

1. Go to Modules/MITRE ATT&CK/Dashboard
2. Add a filter using the `+ Add filter` button of Kibana search bar. In the gif, the filter is added with a button of Mitre flyout, but it works the same way.
3. Go to Framework tab
4. The filter, that was added, is blocked (it can't be removed). If you go to Dashboard or Events tabs, the filter is removable.

**Gif**
![mitre-fixed-filter-framework](https://user-images.githubusercontent.com/34042064/93764750-f26c8d80-fc13-11ea-8f30-620c45483656.gif)

**Comment by pablotr9** [comment]
Hi team,
After some debugging, I found that in Inventory sections, the filters are being blocked after 500ms, well after the implicit param is checked, this time should be reduced as we do in our Dashboards/Events tabs, otherwise they will always be blocked
`/public/kibana-integrations/kibana-discover.js`
```
  $scope.$watch('fetchStatus', () => {
    if ($scope.fetchStatus !== fetchStatuses.UNINITIALIZED) {
      if ($scope.fetchStatus === fetchStatuses.LOADING) {
        setTimeout(() => {
          modulesHelper.hideCloseButtons();
        }, $scope.tabView === 'inventory' ? 500 : 100);
      } else {
        modulesHelper.activeNoImplicitsFilters();
      }
    }
  });
```
