### ISSUE TITLE
PDF reports contains wrong data

### ISSUE THREAD

**Issue by pablotr9** [wazuh/wazuh-kibana-app#2474]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.13.x   | 7.x     | --- |

PDF reports show that some sections are disabled when they are enabled or vice versa.

As these images show, the integrity monitoring section is **not disabled** but the PDF says that is **not enabled**:
 It's just a typo as the PDF should say `Integrity monitoring disabled` instead of `Integrity monitoring enabled`
![image](https://user-images.githubusercontent.com/35685689/93778053-c22dea80-fc25-11ea-9283-d972c05afb89.png)
![image](https://user-images.githubusercontent.com/35685689/93778094-cd811600-fc25-11ea-87a2-171591c094ea.png)

This error affects this list of values in our PDFs:
- Buffer enabled 
- Policy monitoring service enabled
- OpenSCAP integration enabled
- CIS-CAT integration enabled
- Osquery integration enabled
- Syscollector integration enabled
- Active response enabled
- Command enabled
- Docker listener enabled
- Integrity monitoring enabled

**Comment by jesuslinares** [comment]
Kudos to Ankur Yagnik for reporting this bug in our [Slack community](https://wazuh.com/community/join-us-on-slack).
