### ISSUE TITLE
[4.0] Security sections bugs

### ISSUE THREAD

**Issue by pablotr9** [wazuh/wazuh-kibana-app#2483]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.0   | 7.8     | - |

During testing of the new Security section, a few bugs have been found and need to be fixed:
- [x] If creating a policy fails, no error message is shown
- [x] Policies with ID between with 1-99 are now reserved
- [x] Roles with ID between 1-99 are now reserved
- [x] Policy creation form is not cleaned after closing the flyout
- [x] Typo in Roles edit section (it says `roles` instead of `policies`)
- [x] Roles table is missing the reserved badge
- [x] Current section is not highlighted in the main Menu

**Comment by frankeros** [comment]
The bug "Current section is not highlighted in the main Menu" was fixed with [#2567](https://github.com/wazuh/wazuh-kibana-app/pull/2567)
