### ISSUE TITLE
Empty inventory data in Solaris agents

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-kibana-app#2484]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.x   | 7.x     | --- |

**Description**
 We have been informed that there is no data in the 'inventory data' view of the Solaris agents

**Steps to reproduce**

1. Register a Solaris agent
2. Open the WazuhUI and go to `Agents > [solaris_agent] > inventory data
3. All tables are empty

**Screenshots**
![image (75)](https://user-images.githubusercontent.com/3064506/93996093-1bb32800-fd92-11ea-8981-d0bd228ada59.png)
![inventorysolaris](https://user-images.githubusercontent.com/3064506/93996097-1c4bbe80-fd92-11ea-8854-81ca6d69aa5e.gif)

**Comment by gabiwassan** [comment]
Hi!

Testing and trying to reproduce the error, I found that for SolarisOS the call `GET /syscollector/<ID_AGENT>/os` brings the information, but not for `GET /syscollector/<ID_AGENT>/hardware`.
So we have 2 problems:
1. The hardware GET call works for the rest of the agents, the problem could be with SolarisOS.
2. Component rendering is not performed correctly if one of the 2 objects returns empty or without data.
