### ISSUE TITLE
Ability to persist created filters between sessions

### ISSUE THREAD

**Issue by slavag** [wazuh/wazuh-kibana-app#2493]
**Describe the solution you'd like**
I would like the ability to keep filters when I leave the Wazuh app and then come back

**Describe alternatives you've considered**
At this stage the only alternative is to create a filter each time I'm entering the Wazuh APP

**Additional context**
When I'm in main wazuh (version 3.13.2) dashboard, and created a filter (pinned across all apps) switching to Kibana dashboard and then return back to Wazuh, filter disappears, and each time I need to create a new one.

**Comment by pablomarga** [comment]
Hi @slavag , first of all sorry for the delay of our answer.  To save a query you should click on **save query** button. I´ll add a video so you could see how to do it, hope it helps.
![video_community](https://user-images.githubusercontent.com/46006326/99797685-03f8e580-2b30-11eb-813d-b48afa091f74.gif)

<img width="356" alt="Captura de pantalla 2020-11-20 a las 12 52 34" src="https://user-images.githubusercontent.com/46006326/99797775-2ab71c00-2b30-11eb-8008-b1ff2da9aef1.png">

**Comment by slavag** [comment]
Thanks, I guess it's in Wazuh 4 ?
Thanks

**Comment by pablomarga** [comment]
Yes, my screenshots are from Wazuh 4.0 but this is also available in Wazuh 3.13.2. If you have any further question don´t hesitate to tell me.

**Comment by pablomarga** [comment]
Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our [Slack channel](https://wazuh.com/community/join-us-on-slack/) or subscribe to our mailing list.
