### ISSUE TITLE
It's not compliant with kibana 5.5

### ISSUE THREAD

**Issue by tatdatpham** [wazuh/wazuh-kibana-app#25]
I installed ur plugin in kibana 5.5 and kibana doesn't working. I found some update for custome plugin in here
[https://github.com/elastic/kibana/issues/12707#issuecomment-314216338](https://github.com/elastic/kibana/issues/12707#issuecomment-314216338)

**Comment by snaow** [comment]
Hi @tatdatpham,

Kibana latest 5.5.0 release was 6 days ago, it took some time to us but finally we accommodate our App to fully work with the new version.
Every time Kibana release a new version, we need to adapt ours (they do not allow plugins in lower versions), some references from our Mailing list and Github to this matter:

- https://github.com/wazuh/wazuh/issues/93
- https://github.com/wazuh/wazuh-kibana-app/issues/15
- https://github.com/wazuh/wazuh-kibana-app/issues/14
- https://github.com/wazuh/wazuh-kibana-app/issues/12
- https://groups.google.com/forum/#!topic/wazuh/QseQ9qA4NLY
- https://groups.google.com/forum/#!topic/wazuh/XEVbxSlAa5A

We can feel this is something is going to keep happening to us in the future and we are studying to create some automatics scripts or prevent this situation Kibana give us every three weeks.

Now, the new version is available and you could download it from:

- https://packages.wazuh.com/wazuhapp/wazuhapp-2.0_5.5.0.zip

We are updating our documentation and Github READMEs.

I hope you can give us some feedback, don't doubt to send us any error you find.

Best regards,
Pedro 'snaow' Sanchez.

**Comment by StasGoshtein** [comment]
After upgrading all moving parts to 5.5.0 ( Kibana, ES and Wazuh) it seems to work, but getting this errors on the top of the overview screen:

Saved "field" parameter is now invalid. Please select a new field.
Visualize: "field" is a required parameter

**Comment by snaow** [comment]
HI @StasGoshtein,

The error you are getting is triggered when Wazuh App or Dashboards are rendering some field names which do not have any data present in the cluster.

Please, run the following command in one of yours Elasticsearch nodes to insert a sample alert:

```
curl https://raw.githubusercontent.com/wazuh/wazuh-kibana-app/master/server/startup/integration_files/alert_sample.json | curl -XPUT "http://localhost:9200/wazuh-alerts-"`date +%Y.%m.%d`"/wazuh/sample" -H 'Content-Type: application/json' -d @-
```

Then, locate in Kibana interface and refresh index patterns by clicking in:

 ```
Management > Index patterns > wazuh-alerts-* > Refresh Icon
```

![image](https://user-images.githubusercontent.com/1519428/28808418-b19bd4f8-7630-11e7-8eb8-27182d10cfb3.png)


Let us know if it works. Sorry for late response.

Best regards,
Pedro 'snaow' Sanchez.

**Comment by StasGoshtein** [comment]
Thank you - working now.

**Comment by webboy47** [comment]
Hi,
 M having similar issue,
Output of 
==curl -XPOST -H 'kbn-version: 5.4.0' -H "Content-Type: application/json" --data '{"fields":[],"manager":"vpc-ossec-manager","timeinterval":{"gte":"now-1d","lt":"now"}}' http://localhost:5601/api/wazuh-elastic/alerts-count/


is == {"statusCode":400,"error":"Bad Request","message":"Browser client is out of date, please refresh the page"}.

Best Regards.
Sanjay

**Comment by snaow** [comment]
Hi @webboy47,

What is your current Kibana version ? I can see you are using "_kbn-version_" 5.4.0 in your cURL request, you should use the header matching your current Kibana version.

I think you should use as well your Wazuh Manager hostname value within "_manager_" field.

Please let us know what is your current situation in Wazuh App so we can help you better.

Best regards,
Pedro.

**Comment by havidarou** [comment]
I'm proceeding to close this issue as it now follows in #38
