### ISSUE TITLE
Improvement security section messages

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-kibana-app#2503]
Hi team!

In the "Users" tab of the new "Security" section, if the Kibana environment does not have any security plugins installed, the following message is displayed.

![image.png](https://images.zenhubusercontent.com/56122648638e718c995d88f9/5f16c188-61aa-431c-bee9-6b190b2c2e80)

It is necessary to detect this case to change the warning message with a quick reference to install one of the supported plugins 

Requirements: 
- [x] Detect the security plugin installed on the front-end
- [x] Create a new prompt message
- [x] Create conditions to display the correct prompt

**Comment by Desvelao** [comment]
Update:
- The prompt is showed cotrolled by `appStateReducers.currentPlatform` variable of Redux Store
- A prompt component was created
- And the `Users` component was guarded with the prompt and the condition to show it.

Screenshot:
![image](https://user-images.githubusercontent.com/34042064/96998577-f56cdd80-1533-11eb-8288-be7328e0f703.png)
