### ISSUE TITLE
Want to Copy Wazuh Dash Visuals to Custom Dash

### ISSUE THREAD

**Issue by gsunseri** [wazuh/wazuh-kibana-app#2507]
Hello!

I would like to copy visuals from the Wazuh dashboard in Kibana to my custom dashboard in kibana so they are all in one place. Anyone know how to do this?

Thanks!

**Comment by Desvelao** [comment]
Hi @gsunseri 

To copy a Wazuh app visualization to Kibana and you can use in a custom dashboard, follow the next steps:
1. Localize the visualization you want to copy
The Wazuh app visualizations are stored in files within the `server/integration-files/visualizations` directory.

For example, we go to copy `Groups` visualization located in `server/integration-files/visualizations/overview/overview-audit.js` of Wazuh app for Kibana source code.

![image](https://user-images.githubusercontent.com/34042064/94788502-f054bc80-03d3-11eb-88d1-4fbb2df0ea77.png)

2. Create a visualization without configuration
2.1. Go to Visualize
![image](https://user-images.githubusercontent.com/34042064/94784217-242ce380-03ce-11eb-8061-8453bb593de9.png)
2.2. Create a visualization
![image](https://user-images.githubusercontent.com/34042064/94784371-576f7280-03ce-11eb-96d6-6691bad33c36.png)
![image](https://user-images.githubusercontent.com/34042064/94784455-779f3180-03ce-11eb-97b9-6c0f43a78cf1.png)
2.3. Select the Wazuh alerts index pattern you are using (you could using `wazuh-alerts-3.x-*`)
![image](https://user-images.githubusercontent.com/34042064/94788931-94d6fe80-03d4-11eb-8371-b2eb30032c94.png)

2.4. Save the visualization. It is not necessary to add a configuration for it. Set a name and save.
![image](https://user-images.githubusercontent.com/34042064/94784712-db295f00-03ce-11eb-9bc5-b6bf0e2c22d4.png)
![image](https://user-images.githubusercontent.com/34042064/94789331-1464cd80-03d5-11eb-8541-5fa66a505c8d.png)

3. Modify the visualization
We need to modify the visualization that we have just created.
3.1. Go to Stack Management > Stack Management
![image](https://user-images.githubusercontent.com/34042064/94784882-1af04680-03cf-11eb-8deb-091832ad65d8.png)
![image](https://user-images.githubusercontent.com/34042064/94784983-43784080-03cf-11eb-965b-28dd63d00f7f.png)
3.2. Click on the inspect button of visualization we created to see the visualization data:
![image](https://user-images.githubusercontent.com/34042064/94785253-a669d780-03cf-11eb-80fc-74226e2aa046.png)
3.3. Replace the visualization data with the Wazuh visualization we want to copy. Wazuh app visualizations contain these fields:
- `visState`
- `uiStateJSON`
- `description`
- `version`
- `kibanaSavedObjectMeta.searchSourceJSON`
![image](https://user-images.githubusercontent.com/34042064/94786797-bb476a80-03d1-11eb-8ab3-4054649190e5.png)

Modify in the `kibanaSavedObjectMeta.searchSourceJSON`, the `index` field, to match the Wazuh alerts index pattern you are using, (in my case `wazuh-alerts-*`, but you could are using `wazuh-alerts-3.x-*`)
![image](https://user-images.githubusercontent.com/34042064/94788238-97852400-03d3-11eb-969c-d1a47a5e5c94.png)

Save the visualization
![image](https://user-images.githubusercontent.com/34042064/94787503-ad461980-03d2-11eb-9abd-335b2139167e.png)

As a result, now we can use this visualization in our custom Kibana dashboard.
![image](https://user-images.githubusercontent.com/34042064/94789969-ef248f00-03d5-11eb-82fb-87bb477e8980.png)

**Comment by jsanchez91** [comment]
Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our Slack channel or subscribe to our mailing list.
