### ISSUE TITLE
check index pattern known fields

### ISSUE THREAD

**Issue by joker2013** [wazuh/wazuh-kibana-app#2509]
| Wazuh | Elastic | 
| ----- | ------- | 
| 3.9.4  | 6.8     |

**While loading the Kibana app I am getting the following error**
conf filebeat.yml and GET _template/wazuh presented [ #2363 ](https://github.com/wazuh/wazuh-kibana-app/issues/2363#issuecomment-702280158)

 ![photo_2020-10-01_20-26-47](https://user-images.githubusercontent.com/5401399/94842803-7c8ed000-0424-11eb-8f5d-6eb556b46550.jpg)

what could be the problem ?

**Comment by pablotr9** [comment]
Hi @joker2013 !

First of all, let me recommend you to upgrade Wazuh and Elasticsearch/Kibana. The latest Wazuh version is 3.13.2 and Elasticsearch 7.9.2.

Regarding your problem with the index pattern known fields, could you please trying refreshing the index pattern in **Kibana** -> **Management** -> **Index Pattern**. 
After that refresh, try removing the browser cache data as the App could be using an old index pattern.

If that doesn't work, could you please check the mapping of the wazuh-alerts* indices?
Run this request in Kibana Dev Tools and share the output with me:
```
GET wazuh-alerts*
```

Best Regards,
Pablo Torres

**Comment by jsanchez91** [comment]
Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our Slack channel or subscribe to our mailing list.

**Comment by joker2013** [comment]
> Привет @ joker2013 !
> 
> Прежде всего, позвольте мне порекомендовать вам обновить Wazuh и Elasticsearch / Kibana. Последняя версия Wazuh - 3.13.2 и Elasticsearch 7.9.2.
> 
> Что касается вашей проблемы с известными полями шаблона индекса, не могли бы вы попробовать обновить шаблон индекса в **Kibana** -> **Управление** -> **Шаблон индекса** .
> После этого обновления попробуйте удалить данные кеша браузера, поскольку приложение может использовать старый шаблон индекса.
> 
> Если это не сработает, не могли бы вы проверить сопоставление индексов wazuh-alerts *?
> Запустите этот запрос в Kibana Dev Tools и поделитесь со мной результатом:
> 
> ```
> GET wazuh-alerts*
> ```
> 
> С уважением,
> Пабло Торрес

  "error": 603,
  "message": "The requested URL was not found on this server",
  "data": false
