### ISSUE TITLE
Error on new refresh know fields

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-kibana-app#2510]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.x  | 7.9.1     | --- |

**Description**
Hi team!

An error is detected in the new "refresh-know-fields", the error is produced by the following request:

Request:
```
https://<host>/api/index_patterns/_fields_for_wildcard?pattern=wazuh-alerts-*&meta_fields=_source
```

Request header
```
GET /api/index_patterns/_fields_for_wildcard?pattern=wazuh-alerts-*&meta_fields=_source HTTP/1.1
Host: <host>
Connection: keep-alive
kbn-version: 7.9.1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
Content-Type: application/json
Accept: */*
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://<host>/app/wazuh
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: wz-user=wazuh; wz-api=wazuh; security_storage=Fe26.2**; wz-token=**; security_authentication=Fe26.2**
```

```
HTTP/1.1 400 Bad Request
Server: nginx/1.12.2
Date: Fri, 02 Oct 2020 13:25:11 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 64
Connection: keep-alive
kbn-name: kibana
cache-control: private, no-cache, no-store, must-revalidate
set-cookie: security_authentication=Fe26.2**; Max-Age=3600; Expires=Fri, 02 Oct 2020 14:25:11 GMT; HttpOnly; Path=/
```

Response
```json
{"statusCode":400,"error":"Bad Request","message":"Bad Request"}
```
**Steps to reproduce**

1. Run health-check

**Screenshots**
![image](https://user-images.githubusercontent.com/3064506/94928861-941d9580-04c4-11eb-8bc4-9045605cd704.png)

**Additional context**
- ODFE 1.10.1.0

**Comment by Desvelao** [comment]
I build an environment with:
- ODFE 1.10.1
- Kibana 7.9.1 with `security-opendistro-plugin v1.10.1.0`
- Wazuh app branch `4.0-7.9`

and the error is not happening. This problem is happening in a `demo` environment.

It could be related to a rare bug: https://discuss.elastic.co/t/bad-request-when-refreshing-index-pattern-fields/220202/3 In that discussion the user solved the problem reinstalling the environment from scratch.

**Comment by jsanchez91** [comment]
This error only occurs when an unofficial version of the Opendistro security plugin for Kibana is installed.

```ts
"name": "opendistro_security",
"version": "1.10.1.0",
```
