### ISSUE TITLE
Plugin installation was unsuccessful due to error "Plugin wazuh [7.9.1] is incompatible with Kibana [7.9.2]"

### ISSUE THREAD

**Issue by SpeTr0x** [wazuh/wazuh-kibana-app#2513]
[root@localhost kibana]# sudo bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.13.2_7.9.1.zip --allow-root
Attempting to transfer from https://packages.wazuh.com/wazuhapp/wazuhapp-3.13.2_7.9.1.zip
Transferring 30508040 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Plugin wazuh [7.9.1] is incompatible with Kibana [7.9.2]"

**Comment by jsanchez91** [comment]
Hi @SpeTr0x,

That error occurs because you are trying to install the wrong package.
Try installing this package: https://packages.wazuh.com/wazuhapp/wazuhapp-3.13.2_7.9.2.zip

On the other hand, I see that you install the package as root, try to install it with this command:
```
sudo -u kibana bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.13.2_7.9.1.zip 
```
We recommend that you check our installation guide:
[Installing Elastic Stack](https://documentation.wazuh.com/3.13/installation-guide/installing-elastic-stack/index.html).

I hope this helps you, don't hesitate to ask if you have any further questions.

**Comment by SpeTr0x** [comment]
Hi @jsanchez91 ,
thanks for the reply, i'm using an OpenShift Enterprise system RHEL based, 
could you please see if i'm doing wrong? 
`[root@localhost kibana]# sudo -u kibana bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.13.2_7.9.2.zip`

> Babel could not write cache to file: /usr/share/kibana/optimize/.babel_register_cache.json
> due to a permission issue. Cache is disabled.
> Plugin installation was unsuccessful due to error "ENOENT: no such file or directory, mkdir"

**Comment by SpeTr0x** [comment]
i used a registered user other than kibana and the issue is the same

**Comment by jsanchez91** [comment]
Hi @SpeTr0x,

Try to run these commands:

```
chown -R kibana:kibana /usr/share/kibana/optimize
chown -R kibana:kibana /usr/share/kibana/plugins
```

**Comment by SpeTr0x** [comment]
sorry i was dumb xD
@jsanchez91 , thank you so much

**Comment by jsanchez91** [comment]
I'm glad I could help you, if everything is resolved I'll close the Issue.

If you have any further questions, please do not hesitate to reopen the Issue or use our [slack channel](https://wazuh.com/community/join-us-on-slack/), our [Google group](https://groups.google.com/forum/#!forum/wazuh)

Regards

**Comment by brijeshjaiswal1** [comment]
how to check the compatibility of plugin wazuh with Kibana Package.
