### ISSUE TITLE
Changes on JWT token

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-kibana-app#2523]
Hello team!

The content of the JWT token has changed, in this issue are the details: https://github.com/wazuh/wazuh/issues/6201

We must review how this change affects WazuhUI and make the necessary changes.

Goals:
- [x] Run the plugin under the latest revision of Wazuh 4.0: https://github.com/wazuh/wazuh/tree/4.0 
- [x] Adapt server-side
- [x] Adapt browser-side

**Comment by Desvelao** [comment]
## JWT changes
- Updated ApiInterceptor with the new response of endpoints:
  - `security/user/authenticate`
  - `security/user/authenticate/run_as`
- Added `WzAuthentication.getUserPolicies` method to get the policies
- Adapted `WzAuthentication.refresh` to get the policies and set them in Redux store
