### ISSUE TITLE
Bug in the "Manage agents of group" component. 

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-kibana-app#2531]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.0   | 7.9     | 444 |

**Description**
The component search bar does not filter agents within the selector

**Screenshots**
![filter_agents](https://user-images.githubusercontent.com/3064506/95876099-028b0f00-0d73-11eb-84dc-d594893a421c.gif)

**Comment by Desvelao** [comment]
**Update**
- Created `WzFieldSearchDelay ` component (same as EuiFieldSearch but search after a delay on an input term change)
- Fixed the filter in the search bar
- Replaced `EuiFieldSearch` by `WzFieldSearchDelay` component
