### ISSUE TITLE
The configuration is applied after a period of time

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-kibana-app#2534]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.x   | 7.x     | 444 |

When modifying the configuration from the `settings > configuration` view, the changes take some time to be applied.

![configuration_delay](https://user-images.githubusercontent.com/3064506/95883115-d4113200-0d7a-11eb-8753-eb5bace6e6f5.gif)

## Context:
To solve this error we must take into account the following elements:

**WazuhConfig service**: This object implements a singleton pattern to have a single instance with the configurations of the application. When changing views a request is made again to the backend to update the object containing the configuration.
https://github.com/wazuh/wazuh-kibana-app/blob/master/public/react-services/wazuh-config.js#L15

**getConfiguration method**: Due to the time it takes to obtain the configuration of the wazuh.yml file, the last reading of the file is stored in memory for 10 seconds.
https://github.com/wazuh/wazuh-kibana-app/blob/master/server/lib/get-configuration.js#L21

**Comment by Desvelao** [comment]
Update
Fixed applying changes in the server-side and frontend-side app configuration cache object. Added a function to convert the number-type values which are string in the inputs.
