### ISSUE TITLE
Loop in the logout

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-kibana-app#2536]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.x   | 7.x     | 444 |

**Description**
When the Kibana session is closed because the session time has expired, accessing it again produces a loop.

**Steps to reproduce**

1. Enter in the app
2. Wait for the session to expire
3. Login again

**Screenshots**
![looping](https://user-images.githubusercontent.com/3064506/95888205-1473ae80-0d81-11eb-95f5-260782e9cda9.gif)

**Additional context**
This error has been reported using the Opendistro security plugin for Kibana.

**Comment by jsanchez91** [comment]
**Update**

A check has been added to the error handling so that if the session expires it will be redirected to the login

**Comment by daniejstriata** [comment]
Is this check done on SAML Logout?
