### ISSUE TITLE
auto-updating index pattern breaks filebeat pattern for discover tab

### ISSUE THREAD

**Issue by pingkrimson** [wazuh/wazuh-kibana-app#2562]
I've had this issue with a new filebeat 7.9.2 index pattern since updating the wazuh kibana app to the latest version according to the documentation here: 
https://documentation.wazuh.com/3.13/development/packaging/generate-wazuh-kibana-app.html?highlight=kibana%20wazuh%20plugin

After adding the an index pattern for the filebeat index, it is visible for a short time in discover, and then kibana will thrown an error. Viewing the index pattern in the management tab shows the @timestamp field is marked as excluded and has a source filter.
By commenting out the following block of code the issue appears to go away:
https://github.com/wazuh/wazuh-kibana-app/blob/b1aff90794dea780db5a210fd9a01328c0eebaf1/server/lib/elastic-wrapper.js#L281-L300

My question is, why is this happening only to my filebeat-7.9.2-custom index pattern and not my other index patterns when I re-create each. And, what am I breaking by commenting out this block of code? The wazuh plugin appears to still be working normally after this change.
here are notes from an elastic discussion thread concerning this issue: 
https://discuss.elastic.co/t/what-is-excluded-column-in-kibana-index-pattern/252667/5

**Comment by Desvelao** [comment]
Hi @pingkrimson ,

Wazuh app uses `timestamp` field as **time field**, not `@timestamp`.

The `sourceFilters` property in that block of code, only removes the `@timestamp` field when fetching the document source. Here is the block of code for `exclude` the `@timestamp` field: https://github.com/wazuh/wazuh-kibana-app/blob/b1aff90794dea780db5a210fd9a01328c0eebaf1/server/lib/elastic-wrapper.js#L264-L270

The update of the index pattern is done to secure that the data is correct to show the visualizations in the dashboards. If you modified the format of some field in that index pattern, this function update with the known fields (in <v4.0.0), too.

**Comment by snaow** [comment]
Hi @pingkrimson,

Do you need any more help? Did you encounter the same error again? Thanks for your feedback

**Comment by Desvelao** [comment]
I close this issue due to inactivity.
