### ISSUE TITLE
Question about modules

### ISSUE THREAD

**Issue by a108a108** [wazuh/wazuh-kibana-app#2565]
Hi guys,
in the screenshots on the wazuh's website there are modules like:
"Incident Response", "Malware Detection", "Log Data Analysis" which do not exists in the actual app and in general the existing are different. Why is that ?

**Comment by jsanchez91** [comment]
Hi @a108a108,

The screenshots you mention try to summarize the capabilities provided by the different Wazuh modules.

In our roadmap we plan to analyze the information generated by wazuh to build dashboards that cover different security and data analysis purposes.

You can check the progress in the next issue: https://github.com/wazuh/wazuh-kibana-app/issues/2452

**Comment by frankeros** [comment]
Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our Slack channel or subscribe to our mailing list.
