### ISSUE TITLE
Multiple errors in the security section

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-kibana-app#2569]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.x   | 7.9.x     | 4004 |

I am testing in the security section, these are the errors I found.

- [ ] Frequently, the 'police' request returns an error 500

Request:
```JSON
{"method":"GET","path":"/security/policies","body":{},"id":"default"}
```
Response:
```JSON
{"message":"3013 - Wazuh Internal Error","code":3013,"statusCode":500}
```

- [ ] Navigate quickly between the tabs launches the health-check
![security_health_check](https://user-images.githubusercontent.com/3064506/97332278-98965d80-187a-11eb-9072-7249237dadb9.gif)

- [ ] Sometimes the actions selector is empty 
![image](https://user-images.githubusercontent.com/3064506/97332521-d6938180-187a-11eb-85c5-9366cd2bd677.png)

**Comment by Desvelao** [comment]
I checked in local and private environments and the errors aren't appearing. 

These seem to be related to problems with the API in the environment where they were located. It could be caused by the Wazuh installed manager version.

**Comment by jsanchez91** [comment]
Confirmed, errors are produced by an old manager version.
