### ISSUE TITLE
Hide empty columns of the processes table of the MacOS agents

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-kibana-app#2570]
Hello team, 
In the inventory view some columns of the table "Processes" are empty. These should not be displayed.

![image](https://user-images.githubusercontent.com/3064506/97334039-84536000-187c-11eb-8802-04cce0a7a994.png)

> Check the other tables with all types of agents, and hide the columns if they are empty

**Comment by pablomarga** [comment]
Hi team, to fix this error I changed the way the columns were generated and filter it depending on the OS.
