### ISSUE TITLE
Wazuh Kibana 4 plugin api connection error

### ISSUE THREAD

**Issue by S733** [wazuh/wazuh-kibana-app#2571]
I'm trying to install wazuh app to an already running elastic stack. I installed wazuh manager using ubuntu package and installed kibana plugin in elastic stack kibana docker v7.9.2. Although I installed wazuh v4, after restarting the kibana docker I got  wazuh-alerts-3.x-* index not found error in kibana. I started filbeat from wazuh manager server and then "wazuh-alerts-4.x-* index created and that error stopped showing. Now I'm facing api not connecting issue, although curl can connect to the wazuh manager without any issue and the api logs also showing authenticaton successful message. Following is the message I'm getting in the kibana plugin log.

##/usr/share/kibana/optimize/wazuh/logs/wazuhapp-plain.log

```
update-registry:updateToken: Cannot read property 'default' of undefined
monitoring:checkAndSaveStatus: Cannot read property 'default' of undefined
initialize:checkKnownFields:  No index pattern found, open the interface to generate
update-registry:updateToken: Cannot read property 'default' of undefined
wazuh-api:checkStoredAPI: Cannot read property 'default' of undefined
update-registry:updateToken: Cannot read property 'default' of undefined
wazuh-api:checkStoredAPI: Cannot read property 'default' of undefined
update-registry:updateToken: Cannot read property 'default' of undefined
wazuh-api:checkAPI: Cannot read property 'default' of undefined
update-registry:updateToken: Cannot read property 'default' of undefined
monitoring:checkAndSaveStatus: Cannot read property 'default' of undefined
```

##/usr/share/kibana/optimize/wazuh/config/wazuh.yml
```
hosts:
  - default:
     url: https://xx.xx.xx.xx
     port: 55000
     username: wazuh-wui
     password: wazuh-wui
```

##wazuh-manger api.log

`INFO: wazuh-wui xx.xx.xx.xx "GET /security/user/authenticate" done in 262.00000000062573ms: 200
`

Kibana plugin about page

![Screenshot](https://user-images.githubusercontent.com/48009625/97405764-2ecf8f80-191e-11eb-98b8-ad16297f2cad.png)

**Comment by jsanchez91** [comment]
Hi @S733,

From what you say it seems that you have updated the environment to v4 and it is possible that you are missing some steps. In our documentation, you can find the steps to update the environment of Kibana.
[Upgrading Kibana - Wazuh documentation](https://documentation.wazuh.com/4.0/upgrade-guide/elasticsearch-kibana-filebeat/upgrading-elastic-stack.html#upgrading-kibana).

Check the following steps:
- Stop Kibana service
- Remove Kibana bundles
```bash
rm -rf /usr/share/kibana/optimize/bundles
```
- Remove `wazuh-registry.json`
```bash
rm -f /usr/share/kibana/optimize/wazuh/config/wazuh-registry.json
```
- Start Kibana service
- Remove the index-pattern `wazuh-alerts-3.x-*`
> Open the Kibana interface and go to: `Stack Management > Index patterns`

**Comment by S733** [comment]
@jsanchez91 thanks for the reply, I installed v3.13 plugin and api connection was ok. To test v4 I removed the plugin, deleted the kibana container, deleted all the 3.x indexes and installed v4 plugin in the newly creating kibana container. As I deleted the kibana docker volume, I think all the traces of the previous installation was removed. 

Cannot read property '**default**' of undefined. 
If I change the **default** to any other name, I get the same error with that newname undefined. Is there anything set in the wazuh-server other than the default name which is throwing the error.?

**Comment by jsanchez91** [comment]
Did you clear the browser data? Could you try to access with your browser in incognito mode?

**Comment by S733** [comment]
@jsanchez91 same error in incognito mode

![Screenshot from 2020-10-28 15-30-47](https://user-images.githubusercontent.com/48009625/97422067-4e24e780-1933-11eb-9376-42cce6babc91.png)

**Comment by S733** [comment]
Did a fresh installation of elastic stack and wazuh plugin worked fine. I think somethings are left behind when upgrading from 3x version to 4. 

- I installed  v3x plugin on elastic 7.9.1 --> working fine
- Uninstalled wazuh plugin, deleted plugin files and deleted all wazhu* index, index pattern and index templates.
- Upgraded elastic stack to 7.9.2
- Installed v4 and got api connection error "Cannot read property 'default' of undefined".

Is this a plugin issue or if the plugin is writing data to any system index also ?

**Comment by S733** [comment]
Thanks for the reply, it's installing fine now. I think the issue was that the installation was never completed. As I was testing it on a low config system, the cpu & memory usage gets higher and OS wil hang and go non responisve after restarting kibana. After I upgraded to a higher cofig system and tested again, and now its installing fine and the errors are gone.
