### ISSUE TITLE
ENOENT: no such file or directory, open '/usr/share/kibana/optimize/wazuh/config/wazuh-registry.json'

### ISSUE THREAD

**Issue by thinhnguyen-cxa** [wazuh/wazuh-kibana-app#2573]
| Wazuh | Opendistro for Elastic | Rev |
| ----- | ------- | --- |
| 4.x   | 1.11.0 (ES 7.9.1)     | |

**Description**
Short description of your issue.

**Steps to reproduce**

1. Click on Wazuh menu at sidebar

**Screenshots**
The error showing on Kibana UI

![image](https://user-images.githubusercontent.com/62975133/97520620-41a19d00-19ce-11eb-8d2d-2b75017bdd34.png)

**Additional context**
The error log on kibana pod
```bash
bash-4.2$ tail -f /usr/share/kibana/optimize/wazuh/logs/wazuhapp-plain.log 
error: 2020/10/29 2:53:29: wazuh-hosts:getHostsEntries: ENOENT: no such file or directory, open '/usr/share/kibana/optimize/wazuh/config/wazuh-registry.json'
error: 2020/10/29 2:53:29: update-registry:readContent: ENOENT: no such file or directory, open '/usr/share/kibana/optimize/wazuh/config/wazuh-registry.json'
error: 2020/10/29 2:53:29: update-registry:getHosts: ENOENT: no such file or directory, open '/usr/share/kibana/optimize/wazuh/config/wazuh-registry.json'
error: 2020/10/29 2:53:29: wazuh-hosts:getHostsEntries: ENOENT: no such file or directory, open '/usr/share/kibana/optimize/wazuh/config/wazuh-registry.json'
error: 2020/10/29 2:53:30: update-registry:readContent: ENOENT: no such file or directory, open '/usr/share/kibana/optimize/wazuh/config/wazuh-registry.json'
error: 2020/10/29 2:53:30: update-registry:getHosts: ENOENT: no such file or directory, open '/usr/share/kibana/optimize/wazuh/config/wazuh-registry.json'
error: 2020/10/29 2:53:30: wazuh-hosts:getHostsEntries: ENOENT: no such file or directory, open '/usr/share/kibana/optimize/wazuh/config/wazuh-registry.json'
error: 2020/10/29 2:53:30: update-registry:readContent: ENOENT: no such file or directory, open '/usr/share/kibana/optimize/wazuh/config/wazuh-registry.json'
error: 2020/10/29 2:53:30: update-registry:getHosts: ENOENT: no such file or directory, open '/usr/share/kibana/optimize/wazuh/config/wazuh-registry.json'
error: 2020/10/29 2:53:30: wazuh-hosts:getHostsEntries: ENOENT: no such file or directory, open '/usr/share/kibana/optimize/wazuh/config/wazuh-registry.json'
error: 2020/10/29 2:58:3: update-registry:readContent: ENOENT: no such file or directory, open '/usr/share/kibana/optimize/wazuh/config/wazuh-registry.json'
error: 2020/10/29 2:58:3: update-registry:getHosts: ENOENT: no such file or directory, open '/usr/share/kibana/optimize/wazuh/config/wazuh-registry.json'
```

**Comment by Desvelao** [comment]
Hi @thinhnguyen-cxa , the `wazuh-registry.json` file, located in `<KIBANA_PATH>/optimize/wazuh/config` folder, is created by Wazuh app when Kibana is started if the file doesn't exist previously.

Could you try to restart Kibana?
`systemctl restart kibana`

If that doesn't work:

Check the permissions of `<KIBANA_PATH>/optimize/wazuh/config`, could you share the output?
`ls -la /usr/share/kibana/optimize/wazuh/config`

**Comment by thinhnguyen-cxa** [comment]
Hi @Desvelao,
Thanks for reply. This is the output
![image](https://user-images.githubusercontent.com/62975133/97551900-23f02a00-1a06-11eb-8ac7-5700bca62278.png)

**Comment by Desvelao** [comment]
Could you update the permissions of next directories?
```bash
chown -R kibana:kibana /usr/share/kibana/optimize
chown -R kibana:kibana /usr/share/kibana/plugins
```

And restart Kibana:
`systemctl restart kibana`

**Comment by thinhnguyen-cxa** [comment]
Hi @Desvelao ,
Thanks for your support, you save my day.
Need to chown before install wazuh plugins.

I will close the issue

**Comment by rm3nchaca** [comment]
In some cases it doesn't work because wazuh runs with the "ossec" user, just need to give read permision.
