### ISSUE TITLE
Opendistro LDAP authentication doesnt work with Wazuh Kibana app

### ISSUE THREAD

**Issue by antonisnyc94** [wazuh/wazuh-kibana-app#2575]
Hello,

We are using LDAP as a backend authentication for our opendistro elasticsearch stack. The users in that environment are shown with their full name instead of their username alone. e.g instead of be represented as jdailey a user is represented as "Jamie Dailey" after she authenticates. This makes it impossible to map a user for RBAC in Wazuh Kibana and no one can access the plugin unless they have a local account.

One recommendation is for having the option for wazuh to also include a full name when creating a user, and check the full name as well when checking for permissions.

Thanks a lot,
Tony

**Comment by frankeros** [comment]
Hi @antonisnyc94,

Thanks for your recommendation. 
As a workaround, there is a configuration of opendistro that can you use to map your custome LDAP property to the user_name property of the auth context that is used by the Wazuh app to mapping roles.

The config is `username_attribute`, you can read about it here https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration/ldap/#configuration-summary

I was able to apply the Wazuh `readonly` role to an LDAP user, I used the docker example provided in the same [doc](https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration/ldap/#docker-example ) as environment to do this.
In the example, the property `username_attribute` is set to the LDAP field `cn` in the config.yml file.

So I set this role mapping for the LDAP user `jroe` from the example.
![image](https://user-images.githubusercontent.com/26828184/99088688-1d87b380-25ab-11eb-945e-dd4fdb7f7b1a.png)

You should check if the Wazuh user that you have set in `kibana-path/optimize/wazuh/config/wazuh.yml` (wazuh-kibana-app v4.*) has allowed the property run_as .
You can check this in the Wazuh app in Dev Tools Sections running as `admin` user this query `GET /security/users/me`, it should return the user `wazuh-wui` with `allow_run_as: true`.
![image](https://user-images.githubusercontent.com/26828184/99090198-15307800-25ad-11eb-859d-7875a9085f4c.png)

Please let me know any update. Regards!

**Comment by antonisnyc94** [comment]
Hey @frankeros,

It's been a long time since I firstly created the opendistro cluster so I totally forgot about such a choice! Changing the username_attribure to sAMAccountName and mapping the users through the procedure mentioned above solved my problem!

Thanks a ton and stay safe,
Tony

**Comment by frankeros** [comment]
Hi @antonisnyc94,

I'm glad to hear that, thanks for the feedback.
Stay safe too!!
Franco

**Comment by astateofmind01** [comment]
> Hi @antonisnyc94,
> 
> Thanks for your recommendation.
> As a workaround, there is a configuration of opendistro that can you use to map your custome LDAP property to the user_name property of the auth context that is used by the Wazuh app to mapping roles.
> 
> The config is `username_attribute`, you can read about it here https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration/ldap/#configuration-summary
> 
> I was able to apply the Wazuh `readonly` role to an LDAP user, I used the docker example provided in the same [doc](https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration/ldap/#docker-example) as environment to do this.
> In the example, the property `username_attribute` is set to the LDAP field `cn` in the config.yml file.
> 
> So I set this role mapping for the LDAP user `jroe` from the example.
> ![image](https://user-images.githubusercontent.com/26828184/99088688-1d87b380-25ab-11eb-945e-dd4fdb7f7b1a.png)
> 
> You should check if the Wazuh user that you have set in `kibana-path/optimize/wazuh/config/wazuh.yml` (wazuh-kibana-app v4.*) has allowed the property run_as .
> You can check this in the Wazuh app in Dev Tools Sections running as `admin` user this query `GET /security/users/me`, it should return the user `wazuh-wui` with `allow_run_as: true`.
> ![image](https://user-images.githubusercontent.com/26828184/99090198-15307800-25ad-11eb-859d-7875a9085f4c.png)
> 
> Please let me know any update. Regards!

Hi Frank, 

is it possible to filter for the LDAP group and not the username? With the username it works but it's not quite what i want (to manage users in LDAP and in Wazuh) so it would be nice to assign the roles to LDAP groups, not users.

Any hints? 

Thanks.

**Comment by astateofmind01** [comment]
Nvm, i think i found it. 

it's backend_roles instead of user_name.
