### ISSUE TITLE
Index patterns incorrect, instead of wazuh-alerts-*

### ISSUE THREAD

**Issue by thinhnguyen-cxa** [wazuh/wazuh-kibana-app#2577]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.x   | 7.x     | 1 |

**Description**

Index patterns incorrect, instead of `wazuh-alerts-*` 

**Steps to reproduce**

1. Let wazuh running in several hours
2. Click on Wazuh menu
3. Click on Index list

**Screenshots**

![image](https://user-images.githubusercontent.com/62975133/97727309-d9080c80-1b02-11eb-92d4-361d14a678ca.png)

**Additional context**
* Wazuh running on Kubernetes in cluster mode.
* 1 Master
* 2 Worker

**Comment by jsanchez91** [comment]
Hi @thinhnguyen-cxa,

To avoid this error when creating index patterns, click on `Show advanced options` and type the title of the index pattern in the `Custom index pattern ID` field.

![image](https://user-images.githubusercontent.com/3064506/98525917-6e30a100-2279-11eb-8260-62cdd72af632.png)

Let me know if this solved your problem.
