### ISSUE TITLE
hosts in wazuh-registry.json are always empty

### ISSUE THREAD

**Issue by vsenko** [wazuh/wazuh-kibana-app#2582]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.0.0-1   | 7.9.3     | 444 |

**Description**
After upgrade to Wazuh 4.0 hosts section in file `/usr/share/kibana/optimize/wazuh/config/wazuh-registry.json` is always empty:
```
{"name":"Wazuh App","app-version":"4.0.0","revision":"4005","installationDate":"2020-11-02T09:52:33.231Z","lastRestart":"2020-11-02T09:52:33.231Z","hosts":{}}
```

As far as I understand, the consequence are the following lines in `/usr/share/kibana/optimize/wazuh/logs/wazuhapp-plain.log`:
```
error: xxx: wazuh-hosts:getHostsEntries: TypeError: Cannot convert undefined or null to object
error: xxx: manage-hosts:getHostById: Cannot convert undefined or null to object
error: xxx: wazuh-api:checkStoredAPI: Cannot convert undefined or null to object
```

Eventually Wazuh App displays the following error in Web GUI when testing API connection: `2001 - TypeError: Cannot convert undefined or null to object``

**Steps to reproduce**

It seems like this is a result of several problems I had during upgrade from 3.13 to 4.0. I'm not sure if it's easy to reproduce.

**Screenshots**

**Additional context**
I would be grateful for a hint about how to debug the mechanism that builds `wazuh-registry.json` file.

**Comment by vsenko** [comment]
This is an erroneous bug report, excuse me!

`hosts` in `wazuh-registry.json` are not required to be populated.

My problem was caused by misconfiguration.

**Comment by ball822** [comment]
@vsenko 
I met the issue, may I know how to fix it?

**Comment by vsenko** [comment]
@ball822, excuse me but too much time have passed, I don't remember.
