### ISSUE TITLE
Sample data indices name should take index pattern in use

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#2593]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.x   | 7.x     | 400x |

**Description**
The sample data indices name is created with a fixed prefix. This prefix should depend on the index pattern selected when go to add the sample data instead of a fixed prefix.

- [ ] Modify backend endpoints to create/delete/exist sample data indice of category
- [ ] Modify frontend to send the current index pattern in use
- [ ] Add a warning if the current pattern in use hasn't a template. The visualizations wouldn't work without the correct field mappings.

**Comment by frankeros** [comment]
This approach is complicating the way that the index pattern should match with a valid template. Making that the sample data has unknown fields for the index pattern.

For example, the default index pattern is `wazuh-alerts-*` and the current default template is `wazuh-alerts-4.x-*`
If we use the selected index pattern to create a new sample index it will be named, for example, `wazuh-alerts-sample-security`, which is not included by the template pattern.
![image](https://user-images.githubusercontent.com/26828184/99691501-0e4fac80-2a68-11eb-8bdb-e02214c22793.png)
This would imply several changes in all sample data logic. 

To make this more simple we will add a new config that allows defining the prefix for the sample alerts indices.
![image](https://user-images.githubusercontent.com/26828184/99692282-e876d780-2a68-11eb-896e-cc06dc3220f8.png)
