### ISSUE TITLE
Ability to add/remove agents from the app

### ISSUE THREAD

**Issue by rossengeorgiev** [wazuh/wazuh-kibana-app#26]
Hello Wazuh Team,
Are there any plans having an UI to manage agents, add/remove ?
I know the REST API can do it.

**Comment by malbarral** [comment]
Hello @rossengeorgiev ,
Yes, it will be available soon.
Best regards.

**Comment by malbarral** [comment]
Hello @rossengeorgiev ,

This functionallity is available in the Wazuh App 2.1.

Best regards,
Manuel Albarral
