### ISSUE TITLE
[NIDS] Management

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-kibana-app#2605]
Parent issue | https://github.com/wazuh/wazuh-kibana-app/issues/2603
------------------|----------------------------------------------------------------------------

### Description
Adding a new panel for the management of Wazuh-NIDS to the Management view

### Task
> administration
- [ ] link to main NIDS Management panel [[NIDS MAIN PANEL]](https://app.zenhub.com/workspaces/owlh-5f2a6282cbfe150012fd4b75/issues/owlh-net/owlh-uireact/16)

**Comment by gdiazlo** [comment]
We will revisit this effort in the future.
