### ISSUE TITLE
Elasticsearch stop indexing data to alerts index daily

### ISSUE THREAD

**Issue by S733** [wazuh/wazuh-kibana-app#2612]
| Wazuh | Elastic | Rev |
| --------- | --------- | ----- |
|  4.0.0   |  7.9.2   | 4004 |

**Description**
Elasticsearch will stop indexing data to  wazuh-alerts index daily at midnight. I will be able to see new data only after restarting filebeat, which will create a new index and then elasticsearch will start indexing data till midnight 12:00 AM, again I need to restart to get the data indexed to eleasticsearch. My current index name format is wazuh-alerts-4.x-2020.11.11. How to fix this issue, I coundn't find any erros in elasticseatch and filebeat logs.

Also how do I change the daily index creation and move to monthly or yearly index name formats (wazuh-alerts-4.x-2020). 

Wazuh manager was installed using ubuntu package and filebeat is running as docker container. Elastic stack is running as docker container on another server.

**Comment by frankeros** [comment]
Hi @S733, 

The problem with that Filebeat stops indexing data, sounds like there is an issue with the cluster environment.
You can check the Filebeat service logs to try to find some detail about the issue running these commands:

- First, you need to access the bash of the docker container where Wazuh manager and Filebeat is running
  Run `$ docker container ps` to obtain the list of docker containers ids, take the id of the Wazuh manager container.

- Then run `$ docker container exec -it <CONTAINER-ID> bash`, replace <CONTAINER-ID> with the id that you took before.
    
- Once you are in the container console, you can run `$ journalctl -xe -u filebeat` to read the last service logs if are there.
  Or you can check if there are some logs about the issue in the filebeat logs `$ cat /var/log/filebeat/filebeat`.

Also, you can share with us the filebeat config to check it, running `$ cat /etc/filebeat/filebeat.yml`.

Another thing that you can do, is check if the container of Elastick stack has available space:

- First, get the docker image id that you are using for the Elastic stack container, run `$ docker images` and take the corresponding id.

- Then run `$ docker run --rm --privileged <IMAGE-ID> df -h`, replace <IMAGE-ID> with the id that you took before. 
 And check if there is available space.

Regarding change the period of index creation, let me ask the team if it's possible

I'll be waiting for your comments. Regards!

**Comment by frankeros** [comment]
Hi @S733, 

Regarding changing the period of index creation, here is some information that you can consider useful.

To change the period of index creation in Filebeat you should modify the Wazuh [module](https://documentation.wazuh.com/4.0/installation-guide/open-distro/all-in-one-deployment/all_in_one.html#installing-filebeat) for Filebeat. 
You should change this section on the json file https://github.com/wazuh/wazuh/blob/master/extensions/filebeat/7.x/wazuh-module/alerts/ingest/pipeline.json#L50-L55. 
And here is the documentation about this config https://www.elastic.co/guide/en/elasticsearch/reference/master/date-index-name-processor.html.
To change this config depends on how do you have the docker cluster mounted. 
You can try editing the json from here `$ cat /usr/share/filebeat/module/wazuh/alerts/ingest/pipeline.json` into the Wazuh manager container.

Regards!

**Comment by S733** [comment]
> Hi @S733,
> 
> The problem with that Filebeat stops indexing data, sounds like there is an issue with the cluster environment.
> You can check the Filebeat service logs to try to find some detail about the issue running these commands:
> 
> * First, you need to access the bash of the docker container where Wazuh manager and Filebeat is running
>   Run `$ docker container ps` to obtain the list of docker containers ids, take the id of the Wazuh manager container.
> * Then run `$ docker container exec -it <CONTAINER-ID> bash`, replace `<CONTAINER-ID>` with the id that you took before.
> * Once you are in the container console, you can run `$ journalctl -xe -u filebeat` to read the last service logs if are there.
>   Or you can check if there are some logs about the issue in the filebeat logs `$ cat /var/log/filebeat/filebeat`.
> 
> Also, you can share with us the filebeat config to check it, running `$ cat /etc/filebeat/filebeat.yml`.
> 
> Another thing that you can do, is check if the container of Elastick stack has available space:
> 
> * First, get the docker image id that you are using for the Elastic stack container, run `$ docker images` and take the corresponding id.
> * Then run `$ docker run --rm --privileged <IMAGE-ID> df -h`, replace `<IMAGE-ID>` with the id that you took before.
>   And check if there is available space.
> 
> Regarding change the period of index creation, let me ask the team if it's possible
> 
> I'll be waiting for your comments. Regards!



Thanks for the reply. There is no error related to this in filebeat and elasticsearch logs. Actually I think the issue is with filebeat not reading the alerts.json file after 12 AM. Because when I inspected the file I can see that the file was created on 12 AM ( crtime: 0x5fac7b02:13a289fc -- Thu Nov 12 00:00:02 2020 ). Is there a log rotate settings or someting which deletes and creates the alerts.json file daily, and filebeat not reading the newly created alerts.json file. I have changed the input file in filebeat settings to /var/ossec/logs/alerts/*.json. I'll update here if it reads the newly created file.

**Comment by S733** [comment]
> Hi @S733,
> 
> Regarding changing the period of index creation, here is some information that you can consider useful.
> 
> To change the period of index creation in Filebeat you should modify the Wazuh [module](https://documentation.wazuh.com/4.0/installation-guide/open-distro/all-in-one-deployment/all_in_one.html#installing-filebeat) for Filebeat.
> You should change this section on the json file https://github.com/wazuh/wazuh/blob/master/extensions/filebeat/7.x/wazuh-module/alerts/ingest/pipeline.json#L50-L55.
> And here is the documentation about this config https://www.elastic.co/guide/en/elasticsearch/reference/master/date-index-name-processor.html.
> To change this config depends on how do you have the docker cluster mounted.
> You can try editing the json from here `$ cat /usr/share/filebeat/module/wazuh/alerts/ingest/pipeline.json` into the Wazuh manager container.
> 
> Regards!

thanks, got the settings. But after updating the settings to "index_name_format": "yyyy.MM" and restarting filebeat, the new index  name was "wazuh-alerts-4.x-2020.11.12". It is not taking the settings, anywhere else I need to change to get this applied

**Comment by frankeros** [comment]
> cat /usr/share/filebeat/module/wazuh/alerts/ingest/pipeline.json

Hi @S733, 
thanks for your feedback. 

I asked again about the pipelines and one more step to apply the changes was missing.
After changing the pipeline config and restart Filebeat, you should run `$ filebeat setup --pipelines`
It should force to send to Elastic the new config.

To check it, you can run this query in Kibana UI in Dev Tools section
`GET /_ingest/pipeline/filebeat*`
This returns the filebeat pipelines, so you can check if the change was applied.
![image](https://user-images.githubusercontent.com/26828184/98958969-97ec0100-24e1-11eb-8d1c-b9026f046496.png)

Please let me know of any update. Regards!

**Comment by frankeros** [comment]
> thanks, got the settings. But after updating the settings to "index_name_format": "yyyy.MM" and restarting filebeat, the new index name was "wazuh-alerts-4.x-2020.11.12". It is not taking the settings, anywhere else I need to change to get this applied

**Comment by S733** [comment]
> > thanks, got the settings. But after updating the settings to "index_name_format": "yyyy.MM" and restarting filebeat, the new index name was "wazuh-alerts-4.x-2020.11.12". It is not taking the settings, anywhere else I need to change to get this applied
> 
> Hi @S733,
> thanks for your feedback.
> 
> I asked again about the pipelines and one more step to apply the changes was missing.
> After changing the pipeline config and restart Filebeat, you should run `$ filebeat setup --pipelines`
> It should force to send to Elasticsearch the new config.
> 
> To check it, you can run this query in Kibana UI in Dev Tools section
> `GET /_ingest/pipeline/filebeat*`
> This returns the filebeat pipelines, so you can check if the change was applied.
> ![image](https://user-images.githubusercontent.com/26828184/98958969-97ec0100-24e1-11eb-8d1c-b9026f046496.png)
> 
> Please let me know of any update. Regards!

Thanks a lot that did the trick.

**Comment by frankeros** [comment]
> > > thanks, got the settings. But after updating the settings to "index_name_format": "yyyy.MM" and restarting filebeat, the new index name was "wazuh-alerts-4.x-2020.11.12". It is not taking the settings, anywhere else I need to change to get this applied
> > 
> > 
> > Hi @S733,
> > thanks for your feedback.
> > I asked again about the pipelines and one more step to apply the changes was missing.
> > After changing the pipeline config and restart Filebeat, you should run `$ filebeat setup --pipelines`
> > It should force to send to Elasticsearch the new config.
> > To check it, you can run this query in Kibana UI in Dev Tools section
> > `GET /_ingest/pipeline/filebeat*`
> > This returns the filebeat pipelines, so you can check if the change was applied.
> > ![image](https://user-images.githubusercontent.com/26828184/98958969-97ec0100-24e1-11eb-8d1c-b9026f046496.png)
> > Please let me know of any update. Regards!
> 
> Thanks a lot that did the trick.

I'm glad to hear that. 
Well, I'll be waiting for any update regarding the issue.

**Comment by S733** [comment]
> > > > thanks, got the settings. But after updating the settings to "index_name_format": "yyyy.MM" and restarting filebeat, the new index name was "wazuh-alerts-4.x-2020.11.12". It is not taking the settings, anywhere else I need to change to get this applied
> > > 
> > > 
> > > Hi @S733,
> > > thanks for your feedback.
> > > I asked again about the pipelines and one more step to apply the changes was missing.
> > > After changing the pipeline config and restart Filebeat, you should run `$ filebeat setup --pipelines`
> > > It should force to send to Elasticsearch the new config.
> > > To check it, you can run this query in Kibana UI in Dev Tools section
> > > `GET /_ingest/pipeline/filebeat*`
> > > This returns the filebeat pipelines, so you can check if the change was applied.
> > > ![image](https://user-images.githubusercontent.com/26828184/98958969-97ec0100-24e1-11eb-8d1c-b9026f046496.png)
> > > Please let me know of any update. Regards!
> > 
> > 
> > Thanks a lot that did the trick.
> 
> I'm glad to hear that.
> Well, I'll be waiting for any update regarding the issue.



The index name change is ok now, but the filebeat issue is still there. New alerts.json creating daily at 12AM not picking up by filebeat. I created a cron job to restart filebeat docker at 12:30 until the issue get fixed.

**Comment by frankeros** [comment]
Hi @S733 
the problem was solved? Do you have another question about this issue?

Regards

**Comment by frankeros** [comment]
Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our Slack channel or subscribe to our mailing list.
