### ISSUE TITLE
Wazuh API seems to be down

### ISSUE THREAD

**Issue by martinchako** [wazuh/wazuh-kibana-app#2617]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.x   | 7.x     | 444 |

**Description**
After upgrade from wazuh3.x to v4. Accessing wazuh app in kibana results with error message:

Wazuh API seems to be down
3003 - Missing param: API USERNAME

I'm using default username and password (wazuh) in : /usr/share/kibana/optimize/wazuh/config/wazuh.yml
kibana kibana 4506 Nov 12 10:26 /usr/share/kibana/optimize/wazuh/config/wazuh.yml

Followed all instructions from: https://documentation.wazuh.com/4.0/upgrade-guide/elasticsearch-kibana-filebeat/upgrading-elastic-stack.html#upgrading-kibana

also checked https://github.com/wazuh/wazuh-kibana-app/issues/2571

but nothing is working.

I'm able to authenticate using TOKEN using curl:

curl -k -X GET "https://localhost:55000/"  -H  "Authorization: Bearer $TOKEN"
{"data": {"title": "Wazuh API REST", "api_version": "4.0.1", "revision": 40006, "license_name": "GPL 2.0", "license_url": "https://github.com/wazuh/wazuh/blob/4.0/LICENSE", "hostname": "hostname", "timestamp": "2020-11-12T15:57:12+0000"}, "error": 0}

**Steps to reproduce**

1. Go to http://x.x.x.x:5601/app/wazuh#/settings?_g=()&tab=api

**Screenshots**
![Screenshot_20201112_175219](https://user-images.githubusercontent.com/2771622/98963147-00ea6d80-2510-11eb-953c-c360b8ea75bb.png)

**Additional context**

wazuhapp-plain.log:

debug: 2020/11/12 10:41:55: cron:parse-interval: Using the next interval: 0 */15 * * * *
debug: 2020/11/12 10:41:55: monitoring:configuration: wazuh.monitoring.enabled: true
debug: 2020/11/12 10:41:55: monitoring:configuration: wazuh.monitoring.frequency: 900 (0 */15 * * * *) 
debug: 2020/11/12 10:41:55: monitoring:configuration: wazuh.monitoring.pattern: wazuh-monitoring-* (index prefix: wazuh-monitoring-)
debug: 2020/11/12 10:41:55: init:initApp: Waiting for Kibana migration jobs
debug: 2020/11/12 10:41:56: init:initApp: Kibana migration jobs executed successfully
info: 2020/11/12 10:41:56: initialize: Kibana index: .kibana
info: 2020/11/12 10:41:56: initialize: App revision: 4008
info: 2020/11/12 10:41:56: initialize: Total RAM: 3784MB
debug: 2020/11/12 10:41:56: monitoring:checkKibanaStatus: Waiting for Kibana and Elasticsearch servers to be ready...
debug: 2020/11/12 10:41:56: cron:parse-interval: Using the next interval: 0 */15 * * * *
debug: 2020/11/12 10:41:56: reporting: Class constructor started
debug: 2020/11/12 10:41:56: cron:parse-interval: Using the next interval: 0 */15 * * * *
debug: 2020/11/12 10:41:56: reporting: Class constructor finished properly
debug: 2020/11/12 10:41:57: monitoring:init: Creating/Updating wazuh-agent template...
debug: 2020/11/12 10:41:57: monitoring:checkTemplate: Updating wazuh-monitoring template...
debug: 2020/11/12 10:41:57: initialize:checkWazuhIndex: Checking .wazuh index.
debug: 2020/11/12 10:41:57: initialize[checkwazuhRegistry]: Checking wazuh-version registry.
debug: 2020/11/12 10:41:57: initialize[checkwazuhRegistry]: No need to delete old .wazuh-version index
debug: 2020/11/12 10:41:57: initialize[checkwazuhRegistry]: wazuh-version registry does not exist. Initializing configuration.
debug: 2020/11/12 10:41:57: initialize:saveConfiguration: Wazuh configuration registry inserted
debug: 2020/11/12 10:41:57: initialize:checkKnownFields: Security enabled: no
debug: 2020/11/12 10:41:57: initialize:checkKnownFields: Found 2 index patterns
debug: 2020/11/12 10:41:57: initialize:checkKnownFields: Found 1 valid index patterns for Wazuh alerts
debug: 2020/11/12 10:41:57: initialize:checkKnownFields: Default index pattern found
debug: 2020/11/12 10:41:57: initialize:checkKnownFields: Refreshing known fields for "index-pattern:wazuh-alerts-*"
info: 2020/11/12 10:41:57: initialize: App ready to be used.
debug: 2020/11/12 10:41:57: monitoring:init: Creating new index...
debug: 2020/11/12 10:41:58: monitoring:init: Checking if wazuh-monitoring-* index pattern exists...
debug: 2020/11/12 10:41:58: monitoring:init: Updating known fields for wazuh-monitoring pattern...
debug: 2020/11/12 10:41:58: monitoring:init: Skipping wazuh-monitoring pattern creation. Already exists.
debug: 2020/11/12 10:42:49: manage-hosts:getHosts: Getting hosts
debug: 2020/11/12 10:42:49: update-registry:getHosts: Getting hosts from registry
debug: 2020/11/12 10:42:49: update-registry:readContent: Reading wazuh-registry.json content
debug: 2020/11/12 10:42:49: manage-hosts:getHosts: Getting hosts
debug: 2020/11/12 10:42:49: update-registry:getHosts: Getting hosts from registry
debug: 2020/11/12 10:42:49: update-registry:readContent: Reading wazuh-registry.json content
debug: 2020/11/12 10:42:49: manage-hosts:getHosts: Getting hosts
debug: 2020/11/12 10:42:49: update-registry:getHosts: Getting hosts from registry
debug: 2020/11/12 10:42:49: update-registry:readContent: Reading wazuh-registry.json content
debug: 2020/11/12 10:42:49: manage-hosts:getHosts: Getting hosts
debug: 2020/11/12 10:42:49: update-registry:getHosts: Getting hosts from registry
debug: 2020/11/12 10:42:49: update-registry:readContent: Reading wazuh-registry.json content
debug: 2020/11/12 10:42:51: wazuh-elastic:getTemplate: Template is valid: yes
debug: 2020/11/12 10:42:57: manage-hosts:getHosts: Getting hosts
debug: 2020/11/12 10:42:57: update-registry:getHosts: Getting hosts from registry
debug: 2020/11/12 10:42:57: update-registry:readContent: Reading wazuh-registry.json content
debug: 2020/11/12 10:42:57: manage-hosts:getHosts: Getting hosts
debug: 2020/11/12 10:42:57: update-registry:getHosts: Getting hosts from registry
debug: 2020/11/12 10:42:57: update-registry:readContent: Reading wazuh-registry.json content
debug: 2020/11/12 10:42:58: manage-hosts:getHosts: Getting hosts
debug: 2020/11/12 10:42:58: update-registry:getHosts: Getting hosts from registry
debug: 2020/11/12 10:42:58: update-registry:readContent: Reading wazuh-registry.json content
debug: 2020/11/12 10:42:59: update-registry:readContent: Reading wazuh-registry.json content
error: 2020/11/12 10:42:59: update-registry:updateAPIHostname: Cannot set property 'extensions' of undefined
error: 2020/11/12 10:42:59: wazuh-api:setExtensions: Cannot set property 'extensions' of undefined
debug: 2020/11/12 10:42:59: wazuh-hosts:cleanRegistry: Cleaning registry
debug: 2020/11/12 10:42:59: update-registry:removeOrphanEntries: Checking orphan registry entries
debug: 2020/11/12 10:42:59: update-registry:getHosts: Getting hosts from registry
debug: 2020/11/12 10:42:59: update-registry:readContent: Reading wazuh-registry.json content
debug: 2020/11/12 10:42:59: update-registry:removeHostEntry: Removing entry
debug: 2020/11/12 10:42:59: update-registry:readContent: Reading wazuh-registry.json content
debug: 2020/11/12 10:42:59: update-registry:writeContent: Writting wazuh-registry.json content
debug: 2020/11/12 10:45:0: manage-hosts:getHosts: Getting hosts
debug: 2020/11/12 10:45:0: manage-hosts:getHosts: Getting hosts
debug: 2020/11/12 10:45:0: manage-hosts:getHosts: Getting hosts
debug: 2020/11/12 10:45:0: manage-hosts:getHosts: Getting hosts
debug: 2020/11/12 10:45:0: update-registry:getHosts: Getting hosts from registry
debug: 2020/11/12 10:45:0: update-registry:readContent: Reading wazuh-registry.json content
debug: 2020/11/12 10:45:0: update-registry:getHosts: Getting hosts from registry
debug: 2020/11/12 10:45:0: update-registry:readContent: Reading wazuh-registry.json content
debug: 2020/11/12 10:45:0: update-registry:getHosts: Getting hosts from registry
debug: 2020/11/12 10:45:0: update-registry:readContent: Reading wazuh-registry.json content
debug: 2020/11/12 10:45:0: update-registry:getHosts: Getting hosts from registry
debug: 2020/11/12 10:45:0: update-registry:readContent: Reading wazuh-registry.json content
debug: 2020/11/12 10:47:39: manage-hosts:getHosts: Getting hosts
debug: 2020/11/12 10:47:39: update-registry:getHosts: Getting hosts from registry
debug: 2020/11/12 10:47:39: update-registry:readContent: Reading wazuh-registry.json content
debug: 2020/11/12 10:47:39: manage-hosts:getHosts: Getting hosts
debug: 2020/11/12 10:47:39: update-registry:getHosts: Getting hosts from registry
debug: 2020/11/12 10:47:39: update-registry:readContent: Reading wazuh-registry.json content
debug: 2020/11/12 10:47:39: manage-hosts:getHosts: Getting hosts
debug: 2020/11/12 10:47:39: update-registry:getHosts: Getting hosts from registry
debug: 2020/11/12 10:47:39: update-registry:readContent: Reading wazuh-registry.json content
debug: 2020/11/12 10:47:39: manage-hosts:getHosts: Getting hosts
debug: 2020/11/12 10:47:39: update-registry:getHosts: Getting hosts from registry
debug: 2020/11/12 10:47:39: update-registry:readContent: Reading wazuh-registry.json content
debug: 2020/11/12 10:47:39: manage-hosts:getHosts: Getting hosts
debug: 2020/11/12 10:47:39: update-registry:getHosts: Getting hosts from registry
debug: 2020/11/12 10:47:39: update-registry:readContent: Reading wazuh-registry.json content
debug: 2020/11/12 10:47:39: manage-hosts:getHosts: Getting hosts
debug: 2020/11/12 10:47:39: update-registry:getHosts: Getting hosts from registry
debug: 2020/11/12 10:47:39: update-registry:readContent: Reading wazuh-registry.json content
debug: 2020/11/12 10:47:41: wazuh-elastic:getTemplate: Template is valid: yes
debug: 2020/11/12 10:47:46: manage-hosts:getHosts: Getting hosts
debug: 2020/11/12 10:47:46: update-registry:getHosts: Getting hosts from registry
debug: 2020/11/12 10:47:46: update-registry:readContent: Reading wazuh-registry.json content
debug: 2020/11/12 10:47:48: manage-hosts:getHosts: Getting hosts
debug: 2020/11/12 10:47:48: update-registry:getHosts: Getting hosts from registry
debug: 2020/11/12 10:47:48: update-registry:readContent: Reading wazuh-registry.json content
debug: 2020/11/12 10:47:50: manage-hosts:getHosts: Getting hosts
debug: 2020/11/12 10:47:50: update-registry:getHosts: Getting hosts from registry
debug: 2020/11/12 10:47:50: update-registry:readContent: Reading wazuh-registry.json content
debug: 2020/11/12 10:47:51: update-registry:readContent: Reading wazuh-registry.json content
error: 2020/11/12 10:47:51: update-registry:updateAPIHostname: Cannot set property 'extensions' of undefined
error: 2020/11/12 10:47:51: wazuh-api:setExtensions: Cannot set property 'extensions' of undefined
debug: 2020/11/12 10:47:51: wazuh-hosts:cleanRegistry: Cleaning registry
debug: 2020/11/12 10:47:51: update-registry:removeOrphanEntries: Checking orphan registry entries
debug: 2020/11/12 10:47:51: update-registry:getHosts: Getting hosts from registry
debug: 2020/11/12 10:47:51: update-registry:readContent: Reading wazuh-registry.json content
debug: 2020/11/12 10:47:51: update-registry:removeHostEntry: Removing entry
debug: 2020/11/12 10:47:51: update-registry:readContent: Reading wazuh-registry.json content
debug: 2020/11/12 10:47:51: update-registry:writeContent: Writting wazuh-registry.json content
debug: 2020/11/12 10:48:46: manage-hosts:getHosts: Getting hosts
debug: 2020/11/12 10:48:46: update-registry:getHosts: Getting hosts from registry
debug: 2020/11/12 10:48:46: update-registry:readContent: Reading wazuh-registry.json content
debug: 2020/11/12 10:50:0: manage-hosts:getHosts: Getting hosts
debug: 2020/11/12 10:50:0: manage-hosts:getHosts: Getting hosts
debug: 2020/11/12 10:50:0: manage-hosts:getHosts: Getting hosts
debug: 2020/11/12 10:50:0: update-registry:getHosts: Getting hosts from registry
debug: 2020/11/12 10:50:0: update-registry:readContent: Reading wazuh-registry.json content
debug: 2020/11/12 10:50:0: update-registry:getHosts: Getting hosts from registry
debug: 2020/11/12 10:50:0: update-registry:readContent: Reading wazuh-registry.json content
debug: 2020/11/12 10:50:0: update-registry:getHosts: Getting hosts from registry
debug: 2020/11/12 10:50:0: update-registry:readContent: Reading wazuh-registry.json content
debug: 2020/11/12 10:50:0: manage-hosts:getHosts: Getting hosts
debug: 2020/11/12 10:50:0: update-registry:getHosts: Getting hosts from registry
debug: 2020/11/12 10:50:0: update-registry:readContent: Reading wazuh-registry.json content

**Comment by frankeros** [comment]
Hi @martinchako,

It maybe can be caused by cookies, try to clear the application data from your browser or try to run the app in private/incognito mode.
If this doesn't work, you should review the Kibana migration [guide]( https://documentation.wazuh.com/4.0/upgrade-guide/elasticsearch-kibana-filebeat/upgrading-elastic-stack.html#upgrading-kibana), 
taking spetial attention in this steps:

- Replace the value user by username and set the username and password as wazuh in the file `/usr/share/kibana/optimize/wazuh/config/wazuh.yml`

and 

- Remove generated bundles and the `wazuh-registry.json` file 

Please let me know of any update. Regards!

**Comment by jpuris** [comment]
I've run into same issue. The problem was that in 3.x username was allowed to be with `user` key in the config/setting yaml, however in 4.x it has to be `username`.
Check your `/usr/share/kibana/optimize/wazuh/config/wazuh.yml`

Im the migration guide, it says "Replace the value user by username", however it is not the value we need to replace but the key name.

**Comment by martinchako** [comment]
> I've run into same issue. The problem was that in 3.x username was allowed to be with `user` key in the config/setting yaml, however in 4.x it has to be `username`.
> Check your `/usr/share/kibana/optimize/wazuh/config/wazuh.yml`
> 
> Im the migration guide, it says "Replace the value user by username", however it is not the value we need to replace but the key name.

That was it. Thank you very much!

**Comment by arizonacomet** [comment]
> > I've run into same issue. The problem was that in 3.x username was allowed to be with `user` key in the config/setting yaml, however in 4.x it has to be `username`.
> > Check your `/usr/share/kibana/optimize/wazuh/config/wazuh.yml`
> > Im the migration guide, it says "Replace the value user by username", however it is not the value we need to replace but the key name.
> 
> That was it. Thank you very much!

I am Facing the Same issue can you pls help me out?
