### ISSUE TITLE
Kibana App - Management - Configuration - Edit configuration opens Master's configuration when visualizing Worker's configuration

### ISSUE THREAD

**Issue by v45ch3** [wazuh/wazuh-kibana-app#2619]
This is for Wazuh Cloud

**Description**
In Wazuh Cloud Kibana App, when you are in any Worker's visualization, and you click on the Edit button, it opens the configuration of the Master node. Although you can then change which node you want to configure from the dropdown list, I think it would be more intuitive if it opened the configuration of the node you're visualizing.

**Steps to reproduce**

1. Go to Wazuh Kibana App
2. Go to Management >> Configuration
3. Select any Worker node from the right's dropdown list
4. Click on Edit configuration
5. Check that the configuration is the Master's configuration

**Screenshots**

![Screenshot 1](https://user-images.githubusercontent.com/3842259/98990523-55d6b580-2509-11eb-9496-cd50a30d89cb.png)
![Screenshot 2](https://user-images.githubusercontent.com/3842259/98990526-5707e280-2509-11eb-8eda-98e97aac11ec.png)

**Additional context**
I have checked this behavior in a cloud instance.

**Comment by pablomarga** [comment]
Hi @v45ch3, what Wazuh ui version are you using?

**Comment by pablomarga** [comment]
Hi @v45ch3 I attach a gif where you can check the behaviour. In my case everything is correctly done.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/46006326/100596400-6bffb680-32fc-11eb-83bd-c865727b966a.gif)

**Comment by pablomarga** [comment]
Hi @v45ch3 due to inactivity and the fact that the problem seems to be solved I´m closing the issue. If the problem is not what I answered don´t hesitate to ask again and reopen the issue.
Greetings.
