### ISSUE TITLE
Missing step in "Deploy a new agent" view

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh-kibana-app#2623]
In the "Deploy a new agent" view, there are 3 steps:
![image](https://user-images.githubusercontent.com/1523318/99243446-f88c7e00-2800-11eb-9dfb-d5cfb47e76b5.png)

Since the agent service is not started automatically, the deployed agent will be disconnected. It is necessary to add a step like:
> 4. Start agent: systemctl start wazuh-agent

Note: This is not necessary for the O.S where the agent is started automatically (Windows).

**Comment by Desvelao** [comment]
Update:
- Added a step to Centos/REHL and Debian/Ubuntu to restart the agent:

  - Centos/RHEL
![image](https://user-images.githubusercontent.com/34042064/99268117-0eac3580-2825-11eb-9ebd-44875f9d9dc2.png)

  - Debian/Ubuntu
![image](https://user-images.githubusercontent.com/34042064/99268174-1a97f780-2825-11eb-97e9-830f190ba2cf.png)

- Added text to describe the possibility of set this setting in the step 2
![image](https://user-images.githubusercontent.com/34042064/99268289-3e5b3d80-2825-11eb-96bd-c96d97be9f63.png)
