### ISSUE TITLE
Cannot install plugin due to possibly-incorrect folder structure

### ISSUE THREAD

**Issue by zmeggyesi** [wazuh/wazuh-kibana-app#2636]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.0.1   | 7.10.0     | 4009 |

**Description**
I've changed the Kibana version number in the plugin, but installation is still failing with `Plugin installation was unsuccessful due to error "No kibana plugins found in archive"`.  
I had to rewrite Kibana to 7.10.0 after an upgrade of the `wazuh-manager` package brought with it a new version of Elastic/Filebeat, which already went ahead and upgraded the data, so a rollback became impossible.

**Steps to reproduce**
Attempting to run `root@watch-dog:/usr/share/kibana# sudo -u kibana /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.0.1_7.9.3-1.zip` fails with the above error.

**Comment by frankeros** [comment]
Hi @zmeggyesi,

Unfurtenely we don't have support for Kibana 7.10.0 right now, we are working on that.
Please install a previous version of Kibana, we recommend the 7.9.3. 
You can check our compatibility matrix with Kibana versions here https://github.com/wazuh/wazuh-kibana-app#wazuh---kibana---open-distro-version-compatibility-matrix.

Regards!

**Comment by frankeros** [comment]
Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our Slack channel or subscribe to our mailing list.
