### ISSUE TITLE
Manager restart in rule editor does not work with Wazuh cluster enabled

### ISSUE THREAD

**Issue by s-ocando** [wazuh/wazuh-kibana-app#2640]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.0.1   | 7.9.1     | 4008 |

**Description**
If the Wazuh cluster is enabled, after saving `local_rules.xml` and using the button to restart the cluster the Wazuh managers fail to restart.  

**Steps to reproduce**

1. Enable the Wazuh cluster configuration. 
2. Edit any rule file (such as `local_rules.xml`) using the Wazuh Kibana plugin. 
3. Save and click restart the manager using the wui.
4. Check the API logs to verify that no petition to restart the manager was made (although the wui shows no error message).  

**Screenshots**
![image](https://user-images.githubusercontent.com/61882981/99665925-91720200-2a6a-11eb-8c70-36489b747466.png)

**Additional context**

If Wazuh cluster is enabled the Wazuh Kibana plugin fails to restart the manager when asked, for example, after editing  `local_rules.xml`. From the API logs `/var/ossec/logs/api.log` it can be seen that there is not an actual petition to restart the manager: 
 

```
2020/11/19 12:02:57 INFO: wazuh 127.0.0.1 "GET /cluster/status" done in 99.9999999994543ms: 200
2020/11/19 12:02:59 INFO: wazuh 127.0.0.1 "GET /cluster/configuration/validation" done in 2333.9999999998327ms: 200
2020/11/19 12:03:01 INFO: wazuh 127.0.0.1 "GET /manager/status" done in 146.99999999993452ms
```

When the Wazuh cluster is disabled the petition to restart the manager is actually made as can be seen in this logs: 

```
2020/11/19 11:48:09 INFO: wazuh 127.0.0.1 "GET /manager/configuration/validation" done in 3213.999999999942ms: 200
2020/11/19 11:48:11 INFO: wazuh 127.0.0.1 "GET /cluster/status" done in 87.99999999973807ms: 200
2020/11/19 11:48:13 INFO: wazuh 127.0.0.1 "GET /manager/configuration/validation" done in 2373.9999999997963ms: 200
2020/11/19 11:48:13 INFO: wazuh 127.0.0.1 "PUT /manager/restart" done in 61.99999999989814ms: 200
2020/11/19 11:48:15 INFO: unknown_user 127.0.0.1 "GET /manager/status" done in 2.9999999997016857ms: 
```

**Comment by gabiwassan** [comment]
Fixede on https://github.com/wazuh/wazuh-kibana-app/pull/2651
