### ISSUE TITLE
Problem in the visualization of new reserved resources of the Wazuh API

### ISSUE THREAD

**Issue by SitoRBJ** [wazuh/wazuh-kibana-app#2643]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.0.1   | 7.9.1 (Open Distro 1.11) | 4009 |

**Description**
In Wazuh Cloud we have created reserved users and rules in the Wazuh API, but the APP does not reflect this. As @davidjiglesias 
 says, it is necessary to make any API resource with an ID between 1 and 99 reserved, that is, to appear as reserved and without giving the option to delete.

I believe that the option to increase the range (1 to 99) in future versions is contemplated.

**Steps to reproduce**

To be able to reproduce it, it is necessary to add a resource with an ID between 1 and 99. 

**Screenshots**

![image](https://user-images.githubusercontent.com/8913336/99693386-96937900-2a8b-11eb-9ded-f9e2f638138e.png)

![image](https://user-images.githubusercontent.com/8913336/99693541-c5115400-2a8b-11eb-8330-b5562b32709e.png)

**Comment by Desvelao** [comment]
Fixed b3f4f7537a714a5f27f072f7b5e1288aaf1fe74d
