### ISSUE TITLE
Initialization Script Hanging 

### ISSUE THREAD

**Issue by mxamusic** [wazuh/wazuh-kibana-app#2650]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|4.0| All In One Instillation | Manager | Unattended Installation | Debian 10 |

Installation Script is taking forever to initialize Kibana. I tried the step by step guide and the same result Kibana Server is not ready because its not Initialized 

![image](https://user-images.githubusercontent.com/16447622/99904686-ec635d80-2ce5-11eb-9540-a8283ce51c4c.png)

**Comment by pablomarga** [comment]
Hi @danimegar could you show me the output of executing `service kibana status` ?

**Comment by mxamusic** [comment]
Hi @pablomarga Please find below the requested screenshot 

![image](https://user-images.githubusercontent.com/16447622/100074058-b5ad5480-2e57-11eb-9b7d-4ad7ccef32c9.png)

**Comment by pablomarga** [comment]
Could you show me the output of `journalctl -u kibana` if you prefer to save this output the command would be` journalctl -u kibana > logs_kibana.txt`

**Comment by mxamusic** [comment]
Can't add it as comment so I uploaded the log text file 
[logs_kibana.txt](https://github.com/wazuh/wazuh-kibana-app/files/5589055/logs_kibana.txt)

**Comment by pablomarga** [comment]
Please execute this command and show me the output `setcap 'cap_net_bind_service=+ep' /usr/share/kibana/node/bin/node`

**Comment by mxamusic** [comment]
```shell
root@demeter:/home/saluslab# setcap 'cap_net_bind_service=+ep' /usr/share/kibana/node/bin/node
bash: setcap: command not found
root@demeter:/home/saluslab# apt install setcap
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package setcap
```

**Comment by pablomarga** [comment]
You need to install this package first `sudo apt-get install libcap2-bin libcap2`

**Comment by mxamusic** [comment]
The Tool is already installed yet can't use it 

![image](https://user-images.githubusercontent.com/16447622/100197289-8d832b80-2f13-11eb-9424-b7a42a778b76.png)

**Comment by pablomarga** [comment]
Could you show me the output of this two commands? 
```
dpkg -L some-package
dpkg -L libcap2-bin
```

**Comment by mxamusic** [comment]
![image](https://user-images.githubusercontent.com/16447622/100204308-28ccce80-2f1d-11eb-92f9-8a42e6410890.png)

**Comment by mxamusic** [comment]
I ran the tool now what can I check for

![image](https://user-images.githubusercontent.com/16447622/100204495-5b76c700-2f1d-11eb-8f52-cf4445ea6e75.png)

**Comment by pablomarga** [comment]
Try now to init Kibana using ´systemctl start kibana´ and tell me if kibana server is now ready and you can access to it. Check also the status of kibana with ´systemctl status kibana.service´

**Comment by mxamusic** [comment]
![image](https://user-images.githubusercontent.com/16447622/100205987-384d1700-2f1f-11eb-805b-66561f139606.png)

**Comment by mxamusic** [comment]
now its working Thanks a lot for your support so the only issue was for setcap command

**Comment by pablomarga** [comment]
I'm glad I could help you, if everything is solved I'll close the Issue.
If you have any further questions, please do not hesitate to reopen the Issue or use our [slack channel](https://wazuh.com/community/join-us-on-slack/), or our [Google group](https://groups.google.com/forum/#!forum/wazuh)
Regards
