### ISSUE TITLE
Agent deployment URLs don't work for some versions or architectures

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-kibana-app#2652]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.0.1   | 7.9.1     | 4010 |

**Description**
URLs provided in the agent deployment don't fully cover the possible versions and architectures that Wazuh supports. Notably CentOS/RHEL5 use a different URL than the one provided as do all Linux architectures other than x86_64

**Steps to reproduce**

1. Go to the Agents section
2. Click on Deploy New Agent
3. Select RedHat / CentOS
4. Attempt to use on RHEL5, a 32-bit, aarch64 or armhf computer.

**Screenshots**
![image](https://user-images.githubusercontent.com/36071202/100005630-894af700-2dc9-11eb-95bb-c937e4e98f6e.png)

**Additional context**
For agents with CentOS/RHEL5 the valid URLs are:
- https://packages.wazuh.com/4.x/yum5/i386/wazuh-agent-4.0.1-1.el5.i386.rpm for 32 bit
- https://packages.wazuh.com/4.x/yum5/x86_64/wazuh-agent-4.0.1-1.el5.x86_64.rpm for 64 bit

The package provided for the CentOS/RHEL 6 and above would not work for the following architectures:
- [i386](https://packages.wazuh.com/4.x/yum/wazuh-agent-4.0.1-1.i386.rpm)
- [aarch64](https://packages.wazuh.com/4.x/yum/wazuh-agent-4.0.1-1.aarch64.rpm)
- [armhf](https://packages.wazuh.com/4.x/yum/wazuh-agent-4.0.1-1.armv7h.rpm)

For Debian/Ubuntu and similar:
 - [i386](https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.0.1-1_i386.deb)
 - [aarch64](https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.0.1-1_arm64.deb)
 - [armhf](https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.0.1-1_armhf.deb)

**Comment by Desvelao** [comment]
## Changes

- Added OS version and OS architecture steps.
- Modified the package URL which depends on OS, OS version, and OS architecture selected
- Modified the OS selection button by a button group
- Improved the logic to generate the install agent command
- Added a message in the install agent step when some OS options are not selected
- Hid the start agent step when there are OS options not selected
- Improved some texts
