### ISSUE TITLE
FIM does not generate information from my windows file server.

### ISSUE THREAD

**Issue by aobaldia15** [wazuh/wazuh-kibana-app#2658]
Hello, I am trying to use the FIM function to scan the integrity of the files in my file server in windows server 2012 standard, in the Wazuh console it shows that the agent is connected, but nothing is registered in the FIM module Can you help me what am I doing wrong?
![FIM](https://user-images.githubusercontent.com/74997791/100172695-e19bfa80-2e96-11eb-83a4-d82e418c60fd.PNG)

**Comment by frankeros** [comment]
Hi @aobaldia15
do you still have the same problem?

**Comment by frankeros** [comment]
Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our Slack channel or subscribe to our mailing list.
