### ISSUE TITLE
Kibana_Black_theme

### ISSUE THREAD

**Issue by nu11secur1ty** [wazuh/wazuh-kibana-app#2659]
Hello friends, the Black theme of Kibana is not working properly.
![black_theme](https://user-images.githubusercontent.com/3677559/100241263-2ded4600-2f3c-11eb-9d5d-bba205d5ebd9.PNG)
BR

**Comment by xr09** [comment]
Hey @nu11secur1ty thanks for the report, this issue was transfered to the Kibana app repository.

**Comment by jsanchez91** [comment]
Hi @nu11secur1ty,

This error is caused by the opendistro security plugin version 1.10.1,  try to replace it with version 1.11.0.

Could you check which version you have installed?

```
/usr/share/kibana/bin/kibana-plugin list
```

**Comment by nu11secur1ty** [comment]
Will...

**Comment by nu11secur1ty** [comment]
# FROM amazon/opendistro-for-elasticsearch-kibana:1.10.1
# Fix
FROM amazon/opendistro-for-elasticsearch-kibana:1.11.0

![black_theme](https://user-images.githubusercontent.com/3677559/100333946-d6061c00-2fdb-11eb-8814-3061c9f14914.PNG)
fix it, tnx and BR

**Comment by nu11secur1ty** [comment]
The problem is fixed!
BR
