### ISSUE TITLE
Wrong parameters in the dev-tools autocomplete section

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-kibana-app#2675]
| Wazuh | Elastic | Rev |
| -------  | ------  | ---- |
| 4.0.3     | 7.9.3   | 4013 |

**Description**
The Dev-tools utility of the plugin is not showing correct information in the syntax of the endpoints.

For instance, when trying to delete an agent it's showing an incorrect syntax:

![image](https://user-images.githubusercontent.com/23264276/101044211-6239b580-357f-11eb-848e-877a9ea41d05.png)

Regards,

Miguel Casares

**Comment by pablomarga** [comment]
Hi teams, this syntax error is fixed, now it removes the `?` when it is wrong and if you got more than one `?` no hints are showed :
![Grabación-de-pantalla-2020-12-15-a-las-10 55 40](https://user-images.githubusercontent.com/46006326/102203913-75c31580-3ec9-11eb-9ef3-b39c3f6cd980.gif)
