### ISSUE TITLE
Agent Status Issue

### ISSUE THREAD

**Issue by ddean1984** [wazuh/wazuh-kibana-app#2678]
| Wazuh 4.0.3 | Elastic 7.9.3 | Wazuh App 4.0.3 | 4014

**Description**
The wazuh app is not showing the correct agent statuses on the overview page. Once an agent connects the disconnected agent's value turns to a 1. Once the agent moves from disconnected to active all numbers are turned to zeros and the agent doesn't increment the active value. If I click on the agent through the vulnerabilities window then I can see the agent without any issues as active. I can see all alerts for the agent. 

![image](https://user-images.githubusercontent.com/56353078/101358429-d4084c80-3868-11eb-8b03-d1446f6ee5fe.png)
![image](https://user-images.githubusercontent.com/56353078/101358478-e7b3b300-3868-11eb-893f-53a47bae5011.png)

**Comment by dragospe** [comment]
Seconding this issue. 

Using the current ansible deployment from the master branch of [wazuh-ansible](https://github.com/wazuh/wazuh-ansible) with the `wazuh-odfe-single.yml` playbook, I see

![image](https://user-images.githubusercontent.com/15849936/101680991-7bcf7700-3a2f-11eb-83b6-9c7530b83df1.png)

before adding any agents. 

When a single agent is registered via enrollment with the `wazuh-agent.yml` playbook, the "dashes" change to 0's:

![image](https://user-images.githubusercontent.com/15849936/101681249-df59a480-3a2f-11eb-8a55-f29c2f8172d0.png)

I too can confirm that the agent receives a client.keys, establishes a connection on 1514/tcp to the manager, and appears in `agent_control -l` on the manager, and that the agent dashboard can be navigated to indirectly through the vulnerabilities window.

Clicking on the 0's takes you to the "Deploy a new agent" wizard. 

Removing the agent turns the 0's on the dashboard back to -'s.

Adding a second agent changes the number on the dashboard to 1:

![image](https://user-images.githubusercontent.com/15849936/101681857-cdc4cc80-3a30-11eb-80ed-e57fb633269c.png)


I think the ordering is going [ -, 0, 1, 2, ...] when it should be [-, 1, 2, ...]

**Comment by ddean1984** [comment]
This is the exact issue that I am seeing. I will check tomorrow to see if an agent shows up as active for me if I add two. I have only tested with one agent. I recently thought it may be related to the monitoring index but I deleted it and allowed it to recreate and did not notice any change. I compared some of the plugin files to my good server and I did not see any differences.

**Comment by gabiwassan** [comment]
Hi @ddean1984,
Please upload a screenshot of following the section: Wazuh -> Settings -> About. 
I'll try to reproduce it and verify the problem.

If you already updated the Wazuh App. Please, verify the following steps: https://documentation.wazuh.com/4.0/upgrade-guide/elasticsearch-kibana-filebeat/upgrading-open-distro.html#upgrading-kibana.
Finally, I recommend you to clear the browser's cache.

**Comment by ddean1984** [comment]
The Wazuh App has been installed and I have manually updated it outside of the playbook to make sure it wasn't an issue with the playbook. The issue still remains. Thank you for your help!

![image](https://user-images.githubusercontent.com/56353078/101906080-66b92c00-3b86-11eb-9c85-aec98c962960.png)

**Comment by ddean1984** [comment]
It appears that the Cache clear in my browser has alleviated the issue I reported. I did not put much faith in that being the fix. Thank you for the suggestion and I believe I will be clearing the cache as step #1 from here on out.
