### ISSUE TITLE
How to create a custom indices

### ISSUE THREAD

**Issue by sikandarqaisar** [wazuh/wazuh-kibana-app#2688]
Hello,
I wanted to create a multiple indices for different agents
**Requirement**
Actually I wanted to run agents for multiple AWS accounts. Each agent on separate AWS account and for that I need separate index for each AWS account. I don't know it's possible or not and if you guys have any other suggestion.

**Comment by gabiwassan** [comment]
Hi @sikandarqaisar,
You can try putting a label to the agent, for example: `aws_account = account1` and then in filebeat you can construct the name of the index as: `wazuh-alerts-<label_aws_account>`

Here you have the documentation: https://documentation.wazuh.com/4.0/user-manual/kibana-app/reference/configure-indices.html#kibana-configure-indices

**Comment by sikandarqaisar** [comment]
Thanks @**gabiwassan**,
It's working fine thanks for your time.
