### ISSUE TITLE
Offer configuration for Wazuh alert indices creation

### ISSUE THREAD

**Issue by pgaufillet** [wazuh/wazuh-kibana-app#2699]
When running Wazuh on small/medium size Information System, creating one index per day is often too much, and makes very difficult to store more than 6 months of logs in Elasticsearch. It should be possible to specify how often Wazuh is creating new indices (without having to change the code), as for Wazuh agent monitoring indices: daily, weekly, monthly for example.

**Comment by Desvelao** [comment]
Hi @pgaufillet ,

The  `alerts` and `archives` (if enabled) indices are created by Filebeat, not by the app for Kibana. The `wazuh` module for Filebeat has a pipeline where define as the `alerts` or `archives` indices name will be. By default, the indices will be daily (if there are alerts generated for that day).

You could modify these pipelines (`alerts` and/or `archives`) to set index name at which these indices will be created. The pipeline files are:
- `alerts`: `<FILEBEAT_MODULES_PATH>`/wazuh/alerts/ingest/pipeline.json`
- `archives`: `<FILEBEAT_MODULES_PATH>`/wazuh/archives/ingest/pipeline.json`

where `<FILEBEAT_MODULES_PATH>` is the Filebeat path installation usually located in `/usr/share/filebeat`.

## Example
For example, if you would want the `alerts` indices are created monthly with the next format `wazuh-alerts-YYYY.MM`.

1. Go to edit the `alerts` pipeline file of `wazuh` module:
```
/usr/share/filebeat/wazuh/alerts/ingest/pipeline.json
```
2. Search the `date_index_name` processor. More info about this processor can be found [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/date-index-name-processor.html).

This processor in the pipeline looks like this:
```json
{
  "date_index_name": {
    "field": "timestamp",
    "date_rounding": "d",
    "index_name_prefix": "{{fields.index_prefix}}",
    "index_name_format": "yyyy.MM.dd",
    "ignore_failure": false
  }
}

```

3. Change the `index_name_format` to `yyyy.MM.ww` and `date_rounding` to `w` and save the file. The `w` means `week`.

The result will be:
```json
{
  "date_index_name": {
    "field": "timestamp",
    "date_rounding": "M",
    "index_name_prefix": "{{fields.index_prefix}}",
    "index_name_format": "yyyy.MM",
    "ignore_failure": false
  }
}
```
4. To Filebeat applies the changes in the pipeline saved in Elasticsearch:
```
filebeat setup --pipelines
```

**Comment by frankeros** [comment]
Hi @pgaufillet, were you able to solve this problem?

**Comment by pgaufillet** [comment]
Hello @frankeros,

on my side it is working since I have applied the workaround - similar to the explanation of @Desvelao - found around Dec 1st on the mailing list. For sure it works, but it is far from being perfect as this file has to be merged when upgrading Wazuh. For now I take care of it by setting `/usr/share/filebeat/module/wazuh`as a local git repository. Nevertheless it remains uncomfortable.

I still recommend another solution (`/var/ossec/etc/<conf file>`, Kibana setting, etc.) for this kind of configuration parameter.

**Comment by frankeros** [comment]
Thanks for the feedback, 
We are going to consider this improvement in conjunction with the Wazuh API team to check the possibility of modifying these Filebeat configs through some endpoints and a UI.
I hope to give you news soon 

Regards
