### ISSUE TITLE
Wrong index name

### ISSUE THREAD

**Issue by avinchakov** [wazuh/wazuh-kibana-app#27]
Hi,
If you delete indexes wazuh-monitoring-* and restart wazuh-api. 
It have creating a new index but with an old date. For example:
Today - 2017.08.24, but wazuh created index with name wazuh-monitoring-2017.07.31.
Example from logs:
```
{
  "_index": "wazuh-monitoring-2017.07.31",
  "_type": "agent",
  "_id": "AV4UHQpTw_N0NWwPJFyV",
  "_version": 1,
  "_score": null,
  "_source": {
    "status": "Disconnected",
    "ip": "172.16.27.90",
    "id": "136",
    "name": "us-web-stage-01",
    "@timestamp": "2017-08-24T12:00:01.102Z",
    "host": "us-log-system-01"
  },
  "fields": {
    "@timestamp": [
      1503576001102
    ]
  },
  "sort": [
    1503576001102
  ]
}
```
I have index rotation by curator and this index wazuh-monitoring-2017.07.31 deleted every day at now((((

**Comment by malbarral** [comment]
Hello @avinchakov ,

When a new index is created, the date in the index name is retrieved from the server where Kibana is installed. Please, make sure that the date in this server is correct.

Best regards,
Manuel Albarral

**Comment by avinchakov** [comment]
Date is correct, also I use ntp.
I tried to update ELK/Wazuh manager/Wazuh agents. 
It created index wazuh-monitoring-2017.08.25. But on the following days no indexes were created.
Do not create daily indices.

**Comment by avinchakov** [comment]
Every day I see such events in ossec.log:
2017/08/30 00:00:01 ossec-monitord: ERROR: Couldn't rename '/logs/ossec.json' to '/logs/ossec/2017/Aug/ossec-29.json'

Who creates wazuh-monitoring-"date" index?

**Comment by malbarral** [comment]
It is created by the Wazuh App, for that reason, the used date is the server with Kibana date. The code to retrieve the date is really simple, just calling Date in JavasScript to retrieve the current date and format the index name.

**Comment by avinchakov** [comment]
Today wazuh didn't create wazuh-monitoring-2017.08.31, again...

```
server1# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

server1# dpkg -l | grep wazuh
ii  wazuh-api                            2.1.0-1trusty                              amd64        
ii  wazuh-manager                        2.1.0-1trusty                              amd64 

server1# date
Thu Aug 31 06:36:38 MSK 2017
```

**Comment by havidarou** [comment]
Hi @avinchakov,

we are currently thinking of a new way of doing this.

Furthermore, there was an issue with the date in a prior version (maybe it is the one you are referring), so if you update to the latest 2.x version in Wazuh it may be fixed.

For a better solution though, we are still on it.

Regards.

**Comment by avinchakov** [comment]
Hi,
I updated to 3.0.0 and problem was solved. Thank you!
