### ISSUE TITLE
Kibana URL changing constantly between "black-screen", "health-check" and "settings"

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-kibana-app#2720]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.13.2   | 7.9.1     | 0886|

**Description**
When going to the Security events dashboard, the URL randomly changes between the aforementioned URL and it's reloading forever but the page is not changing.

This happening randomly quickly.

![image](https://user-images.githubusercontent.com/23264276/103439752-ef842e80-4c3f-11eb-96b0-63de4c46380f.png)

![image](https://user-images.githubusercontent.com/23264276/103439773-2e19e900-4c40-11eb-8a01-c2852e51fd0a.png)

![image](https://user-images.githubusercontent.com/23264276/103439784-45f16d00-4c40-11eb-891a-63752aa59efb.png)

Regards,

Miguel Casares

**Comment by frankeros** [comment]
This happens in 4.x whit ODFE when the session expires too.
The cause is a loop between validations in pattern-handler.js and wz-request.js
when they try to change the location after an error.

**Comment by gabiwassan** [comment]
Tests were carried out with the environment described in the issue, locally but I was unable to reproduce the error:
```
WAZUH_BRANCH = 3.13.2
ODFE_VERSION = 1.10.1
FILEBEAT_VERSION = 7.9.1
Elastic Wazuh
3.13.2 7.9.1
```
The same tests were also carried out with the new version:
```
WAZUH_BRANCH = 4.1
ODFE_VERSION = 1.12.0
FILEBEAT_VERSION = 7.10.0
```
_Note: It errors playing the demo, remains to test whether this is solved with the new version once it is deployed in demo._

**Comment by MiguelCasaresRobles** [comment]
Hello team,

I observed this again in the 4.1.4 version. It happens after being idle within the configured session timeout (before logging out) and by clicking on the screen (inside the Wazuh plugin section)

**Comment by karquieta** [comment]
Hello team

I'm having this problem too even when I made the upgrade to 4.2.1, and it's impossible to use the tool. Did you change something in the configuration files to avoid this to happen?

**Comment by frankeros** [comment]
Hi @karquieta 
There are no changes in the configuration file that involves this issue. 
It could be a cache problem if it starts after an upgrade. Please follow this guide o try using incognito/private mode in your browsers.

If the error is still there, please share the version of the browser are you using, and the Wazuh versions that you came from before the upgrade.

**Comment by karquieta** [comment]
Hi @frankeros 

I got help from the wazuh group on slack, and they recommended me to change a configuration file of JAVA extending the RAM that JAVA uses, and I stopped having this issue. 

Thanks for your attention 👍🏻

**Comment by gdiazlo** [comment]
Being worked on #4028
