### ISSUE TITLE
Wazuh UI log shows an error that must be info or warning

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-kibana-app#2726]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.0.3  | 7.9.1 | 4013 |

**Description**
Using the latest OVA we noticed that some ERROR messages are maybe not ERROR but INFO or WARNING.

![image](https://user-images.githubusercontent.com/3830293/103643318-c40d8680-4f54-11eb-87c1-34a7339c70b6.png)

The message 
```
2021/01/04 14:00:00  ERROR  You must provide a max size
```
means that the Wazuh UI makes a Wazuh API query. This query returns no agents registered. If so, this logged message must not appear. 

Best regards, 
Alberto R

**Comment by pablomarga** [comment]
Hi @alberpilot it was resolved in the branch `4.0 - 7.10`
