### ISSUE TITLE
[4.0-7.10] Bughunt in Agents

### ISSUE THREAD

**Issue by gabiwassan** [wazuh/wazuh-kibana-app#2729]
Parent issue | https://github.com/wazuh/wazuh-kibana-app/issues/2727
------------ | -------------
Branch | [4.0-7.10](https://github.com/wazuh/wazuh-kibana-app/tree/4.0-7.10)

### Description
In order to fix behaviors and styles issues.

**Comment by gabiwassan** [comment]
Fixed loop on load agents, and error when trying to enter in a particular agent.

**Comment by frankeros** [comment]
- Fixed d3 on agent-preview 
- Fixed menu error when an agent is unpinned
