### ISSUE TITLE
Bughunt with Open Distro 1.12

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#2753]
Parent issue | https://github.com/wazuh/wazuh-kibana-app/issues/2727
------------ | -------------
Branch | [4.0-7.10](https://github.com/wazuh/wazuh-kibana-app/tree/4.0-7.10)

### Checks 
- [x] Creation of `wazuh-alerts-*` index pattern.
- [x] Creation of `wazuh-monitoring-*` index pattern.
- [x] Creation of `wazuh-statistics-*` index pattern.
- [x] Creation of `wazuh-agent` template (monitoring job).
- [x] Creation of `wazuh` data folder in `<KIBANA_DATA>/wazuh`.
- [x] Testing with a `readonly` Wazuh API role user using the `run_as` option. Created a rule to assign the Wazuh API role.
- [x] Testing with another user to check the `reports` bucket (one by user) 
- [x] Check `brace` imports are working and the editors work as expected

**Comment by Desvelao** [comment]
### Detected problems
- [ ] Clean ODFE 1.12 install
![image](https://user-images.githubusercontent.com/34042064/104012895-e7347200-51b0-11eb-8d78-d268e1d33a0f.png)
Using the `kibanaserver` user. This has no permissions to create indices for `wazuh-monitoring` and other server tasks

**Comment by Desvelao** [comment]
The Management/Statistics visualizations are not working in the next case:
Using `Private` tenant, with the `wazuh-statistics-*`index pattern created, there an error about the index pattern is not found despite to exist. If the `wazuh-statistics-*`index pattern is created in `Global` tenant, the visualizations seem to be working.

This needs to be investigated.

**Comment by gabiwassan** [comment]
Verified using the `brace` library with OpenDistro
![image](https://user-images.githubusercontent.com/11060558/104491433-fd776f00-55b0-11eb-8f0b-2649ad95f028.png)
Note: `EuiCodeEditor` components use `brace` library to render.
