### ISSUE TITLE
Report's creation dates set to 1970-01-01T00:00:00.000Z 

### ISSUE THREAD

**Issue by Phandora** [wazuh/wazuh-kibana-app#2772]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.0.3  | 7.9.1    | 4015|

## Description

When checking the generated reports in the `Management > Reporting` tab, the report's creation dates are set to **1970-01-01T00:00:00.000Z**.

The dates do not match the ones showed in the `/usr/share/kibana/optimize/wazuh/downloads/reports` directory. 

## Steps to reproduce

1. Generate report.
2. Go to `Management > Reporting`
3. Check the report's creation dates

## Screenshots

- **Response using the Developer Tools**:

![image](https://user-images.githubusercontent.com/33484080/104326745-5b8d4f00-54ea-11eb-8a54-9bfef840ed3b.png)

- **Content of the `/usr/share/kibana/optimize/wazuh/downloads/reports` path**:

![image](https://user-images.githubusercontent.com/33484080/104327344-f423cf00-54ea-11eb-9e78-d7ef4538957d.png)

## Additional context

OS: `Oracle Linux 7.9`

> On filesystems where birthtime is not available, this field may instead hold either the ctime or 1970-01-01T00:00Z (ie, Unix epoch timestamp 0). This value may be greater than atime or mtime in this case. On Darwin and other FreeBSD variants, also set if the atime is explicitly set to an earlier value than the current birthtime using the utimes(2) system call. https://nodejs.org/api/fs.html#fs_stats_birthtimems

**Comment by Desvelao** [comment]
I checked this with the next environment:
Machine:
```
[vagrant@localhost config]$ cat /etc/*release
Oracle Linux Server release 7.7
NAME="Oracle Linux Server"
VERSION="7.7"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Oracle Linux Server 7.7"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:7:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.7
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.7
Red Hat Enterprise Linux Server release 7.7 (Maipo)
Oracle Linux Server release 7.7
```
Kibana dev 7.10.0

The date is correctly shown:
![image](https://user-images.githubusercontent.com/34042064/104623498-b8c40480-5692-11eb-8610-5e5c5a7cf733.png)

**Comment by Desvelao** [comment]
Environment:
OS: Oracle Linux 7.9

[vagrant@oracle7 kibana]$ cat /etc/*release
Oracle Linux Server release 7.9
NAME="Oracle Linux Server"
VERSION="7.9"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Oracle Linux Server 7.9"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:9:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.9
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.9
Red Hat Enterprise Linux Server release 7.9 (Maipo)
Oracle Linux Server release 7.9

The problem occurs:
![image](https://user-images.githubusercontent.com/34042064/104723235-405f5100-572f-11eb-9c36-61776dfc9416.png)
![image](https://user-images.githubusercontent.com/34042064/104723215-38071600-572f-11eb-883b-2a65bae0a58a.png)

**Comment by Desvelao** [comment]
## Fix
The returned creation date was `birthtime`. This could be 1970-01-01T00:00:00.000Z.

Solution:
Now, the date is set to the first truthy value of :
`birthtimeMs` > `mtimeMs` > `ctimeMs` > `atimeMs`

Returns the field with the formmated date:
`birthtimeMs` -> `birthtime
`mtimeMs` ->  `mtime`
`ctimeMs` -> `ctime`
`atimeMs` -> `atime`
