### ISSUE TITLE
Ability to store Wazuh API credentials in Kibana keystore

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-kibana-app#2777]
**Describe the solution you'd like**
Right now, Wazuh API credentials are stored in clear text under `/usr/share/kibana/optimize/wazuh/config`.

Adding support to read them from Kibana keystore will add a layer of security.

Kibana keystore reference: https://www.elastic.co/guide/en/kibana/current/secure-settings.html

**Comment by AlexRuiz7** [comment]
Duplicate: #3637
