### ISSUE TITLE
The alerts time does not match in the Security event dashboard and events tabs

### ISSUE THREAD

**Issue by Phandora** [wazuh/wazuh-kibana-app#2785]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| v4.0.3  | 7.9.1  | 40010|

**Description**

The alerts time does not match in the Security event dashboard and events tabs.

**Steps to reproduce**

1. Go to `Wazuh >  Modules > Security events > Dashboard`
2. Check the time of the alerts
3. Go to `Wazuh >  Modules > Security events > Events`
4. Check the time of the alerts
5. The time does not match

**Screenshots**

![image](https://user-images.githubusercontent.com/33484080/104895819-a12c9a80-5976-11eb-8e47-0442642d76ec.png)

![image](https://user-images.githubusercontent.com/33484080/104895846-a8ec3f00-5976-11eb-8d33-3c00f4f8ae8d.png)

**Additional context**

The same issue happens in the **4.0.4** version. `Browser timezone` is used for date formatting.

**Comment by lucio2047** [comment]
Hi Phandora. Thank you very much. I´d like to add some information by using a picture:

![image](https://user-images.githubusercontent.com/77062482/104907245-11dab380-5985-11eb-9f12-ecbeb462aae0.png)

But I expand the event I see the following difference:

![image](https://user-images.githubusercontent.com/77062482/104907485-77c73b00-5985-11eb-8fac-e78fa710f74b.png)

What do you think?

Virtual machine and operating system have correct timezone setting, no problem about it.

Thank you very much.

**Comment by frankeros** [comment]
> Hi Phandora. Thank you very much. I´d like to add some information by using a picture:
> 
> ![image](https://user-images.githubusercontent.com/77062482/104907867-0340cc00-5986-11eb-8a57-6af12c080108.png)
> 
> But I expand the event I see the following difference:
> 
> ![image](https://user-images.githubusercontent.com/77062482/104907485-77c73b00-5985-11eb-8fac-e78fa710f74b.png)
> 
> What do you think?, I can see the problem is on the **_data.win.system.systemTime_**
> 
> Virtual machine and operating system have correct timezone setting, no problem about it.
> 
> Thank you very much.

Hi @lucio2047 
This is happening because the value of the Kibana setting `Timezone for date formatting` is set in another timezone.
![image](https://user-images.githubusercontent.com/26828184/105180793-c271c000-5b09-11eb-869f-bcf100427322.png)

**Comment by lucio2047** [comment]
Hi frankeros. That solution does not resolve my problem. Here it is my current configuration:

![image](https://user-images.githubusercontent.com/77062482/105184148-4db17c80-5b2f-11eb-9c03-537ceb854cc9.png)

But the problem persists.

Thank you very much!

**Comment by frankeros** [comment]
@lucio2047 
The field `data.win.system.systemTime` is generated by the wazuh-agent with its timezone and saved as a` string` (data type), the field `timestamp` too, but is saved as a` date` (data type).
So, Kibana is using the above setting to formating all fields with  `date` data type . This means that if you wazuh-agent has the timezone UTC -02: 00 but your browser has the timezone UTC -01: 00 `data.win.system.systemTime` and` timestamp` will be shown with 1 hour of diff.

**Comment by lucio2047** [comment]
Hi , thank you very much.

Then the problem is the agent and it is not the server? Should I check the
timezone on server where the agents is installed?

Thank you very much.

**Comment by frankeros** [comment]
Yes please check it, in case the timezone of your wazuh-manager, wazuh-agent, and your browser where you are using the Wazuh App are the same, maybe it's a bug in the alert generation and we will report to the corresponding team.

**Comment by lucio2047** [comment]
Thank you very much:

Please, how Could I check the timezone for my Wazuh Manager, Agents and my
Chrome browser?

My Kibana has configured "browser" as a timezone setting

Thank you very much.

**Comment by lucio2047** [comment]
Hello everyone,

1) Wazuh-manager timezone: is correct. Wazuh is mounting over a Centos OS which has correct time zone GMT+1 Madrid.
2) Agents are installed over Windows operating system with correct timezone: GMT +1.
3) Kibana hast BROWER timezone setting configured, and my Google Chrome has the correct timezone.

Could you help me?

Thank you very much.

**Comment by frankeros** [comment]
Hi @lucio2047 
can you open this 

> Hello everyone,
> 
>     1. Wazuh-manager timezone: is correct. Wazuh is mounting over a Centos OS which has correct time zone GMT+1 Madrid.
> 
>     2. Agents are installed over Windows operating system with correct timezone: GMT +1.
> 
>     3. Kibana hast BROWER timezone setting configured, and my Google Chrome has the correct timezone.
> 
> 
> Could you help me?
> 
> Thank you very much.

in a new issue, in order to follow up and try to help you.
Thanks

**Comment by lucio2047** [comment]
Hi frankeros. I just opened a new case at the morning. I need to solve this problem.

Thank  you very much.

**Comment by zarat** [comment]
Any updates on that case? The timestamp in the API also differs from timestamp in the dashboard in my case.
