### ISSUE TITLE
Properly logout of Wazuh API when logging out of the application

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-kibana-app#2789]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.0.4   | 7.9.1/7.9.3     | 4015 |

**Description**
The Kibana APP is not calling [DELETE /security/user/authenticate](https://documentation.wazuh.com/4.0/user-manual/api/reference.html#operation/api.controllers.security_controller.logout_user) to logout current Wazuh API user and revoke the issued JWT token when logging out of the application.

This causes the JWT token to remain valid and allows to replay a previously-captured request after a user logs out of the application.

Regards,

David J. Iglesias

**Comment by gabiwassan** [comment]
Working on this issue on this [PR](https://github.com/wazuh/wazuh-kibana-app/pull/2972)

**Comment by gabiwassan** [comment]
> Working on this issue on this [PR](https://github.com/wazuh/wazuh-kibana-app/pull/2972)

PR on revision. For the moment only work for Open Distro on an explicit logout
