### ISSUE TITLE
Slow in the cluster and does not find the index

### ISSUE THREAD

**Issue by fernandonsilveira** [wazuh/wazuh-kibana-app#2805]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.0.4   | 7.9.3     | |

**Description**

When I try to access Wazuh in Kibana, it does not find the indexes and causes a very slow speed in the entire ElasticSearch cluster (9 data nodes + 3 kibana).
The index and template exist on the server, as listed below. My indexes are big, maybe he is getting lost, at the time of the check. The default Index is configured with wazuh-alerts- *.
What can I do to test to improve and collect more information about the problem?

**Template**
wazuh                            [wazuh-alerts-4.x-*, wazuh-archives-4.x-*]   0          1       
wazuh-agent                      [wazuh-monitoring-3.x-*, wazuh-monitoring-*] 0  

**Index Wazuh**
green  open   wazuh-alerts-4.x-worker-04-2021.01.21              n06OV8BgSRK_q6J-hA8CZQ   3   1    6528482            0     10.9gb          5.4gb
green  open   wazuh-archives-4.x-worker-06-2021.01.21            yfQFYD8mR9G6hsyhJQRXWQ   3   1   33507729            0     81.6gb         41.2gb
green  open   wazuh-archives-4.x-worker-04-2021.01.21            DTAUSxBaS_GaG2iLO3n5UQ   3   1   76010520            0    142.8gb         71.3gb
green  open   wazuh-archives-4.x-worker-02-2021.01.21            8kcpLQJbQgeubSP7pODFxg   3   1    6939702            0       33gb         16.3gb
green  open   wazuh-archives-4.x-worker-13-2021.01.21            _-W7EkH0QZa2XgGhWxyelg   3   1      18436            0     24.8mb         12.3mb
green  open   wazuh-archives-4.x-svprjsiem-wk1-2021.01.21        vVDpEmqkQQyIl2LBIwiMQA   3   1    1050350            0      2.3gb          1.1gb
green  open   wazuh-archives-4.x-worker-01-2021.01.21            N9otqS_mTg-RlUrY3njggg   3   1      76443            0    165.3mb         82.6mb
green  open   wazuh-archives-4.x-svpspsiem-wk1-2021.01.21        vuv-nchyS4mLJKq7t1KTmA   3   1    1173271            0      2.8gb          1.4gb
green  open   wazuh-archives-4.x-worker-05-2021.01.21            qL9D0JRyT_6UvCQp4iGOKA   3   1   26937707            0     53.6gb         27.2gb
green  open   wazuh-archives-4.x-svprjsiem-wk2-2021.01.21        VmhS0B0JTamKtHpb4Hs_Kw   3   1      22264            0     30.3mb           15mb
green  open   wazuh-archives-4.x-worker-12-2021.01.21            4pgHlktzRWagG5MTCuxg9A   3   1      14752            0     28.5mb         14.3mb
green  open   wazuh-monitoring-2021.01.21                        ynhkXRyCQ0WeYGAVYvBrfw   2   0          0            0       416b           416b
green  open   wazuh-archives-4.x-worker-07-2021.01.21            gBnvsWgISdqjSGR7m8NILQ   3   1    1311774            0    500.1mb        250.1mb
green  open   wazuh-archives-4.x-master-2021.01.21               VatAp08vRfmk-utPMY1Kzg   3   1     155002            0    127.6mb         63.7mb
green  open   wazuh-archives-4.x-svpspsiem-wk2-2021.01.21        j-VP4rTWRmq7orlRV9mX1A   3   1     281504            0    993.6mb        496.5mb
green  open   wazuh-archives-4.x-worker-03-2021.01.21            UdxN7AAQStuVYFods5m3CQ   3   1      29468            0     35.3mb           16mb

**Screenshots**
(https://user-images.githubusercontent.com/11836293/105411801-9f7f0300-5c12-11eb-9bf7-c08fcf592d53.png)

Hugs
Fernando

**Comment by frankeros** [comment]
Hi @fernandonsilveira, 
sorry for the delay, maybe you could try to create more specific index patterns, maybe one per worker
for example 
```
wazuh-alerts-4.x-worker-01-*
wazuh-alerts-4.x-worker-02-*
wazuh-alerts-4.x-worker-03-*
....
``` 
Then you will able to choose from the Wazuh app which you want to explore.

**Comment by frankeros** [comment]
Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our Slack channel or subscribe to our mailing list.
