### ISSUE TITLE
Filters do not work in agents preview

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-kibana-app#2810]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.0.4   | 7.10.0 | 4016 |

**Description**
The filters in the agent list display do not seem to work correctly.

1 - While writing the query, the message: `'the field " is not valid' is displayed`.
2 - After writing the query, the `<field_name>=` is automatically added at the end.

https://user-images.githubusercontent.com/23462183/105490035-757e1d00-5cb4-11eb-82f1-c5649339015a.mp4

3 - If you use the following filter, it is written 3 times.

https://user-images.githubusercontent.com/23462183/105490053-7adb6780-5cb4-11eb-8f02-7b2628f4f898.mp4

As a general conclusion, it appears that neither simple nor compound filters work.

**Console**

![image](https://user-images.githubusercontent.com/23462183/105489963-5e3f2f80-5cb4-11eb-889a-795c4af99391.png)

Best regards.

**Comment by asteriscos** [comment]
Hi Jonathan, this is a known issue from a previous version we are working on. It will be solved ASAP after we are done with issues related to Elastic 7.10.
Thank you
