### ISSUE TITLE
Restarting manager after updating configuration does not update manager Health Check status

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-kibana-app#2814]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.0.4   | 7.10.0     | 4016 |

**Description**
When you restart Wazuh Manager from the app it does not notify correctly to the user when the manager is running.

**Steps to reproduce**

1. Go to Management >  Configuration
2. Change any configuration of the manager
3. Restart wazuh manager
![manager_configuration_restarting_1](https://user-images.githubusercontent.com/11089305/105494135-a5c8ba00-5cba-11eb-9b4f-178608d33e51.png)

4. This error page is displayed. Even when Wazuh manager is ready, this does not notify the user about Health Check new status.
![manager_configuration_restarting_2](https://user-images.githubusercontent.com/11089305/105494146-a9f4d780-5cba-11eb-916c-8033c990eef8.png)

After more than 1 minute yellow panel where inform that manager is restarting, disappears, but error codes in Health Check are still been displayed
![manager_configuration_restarting_3](https://user-images.githubusercontent.com/11089305/105494306-df012a00-5cba-11eb-8e9a-058fca333a0e.png)

**Extra data**
Tested on Firefox and chromium

**Comment by jmv74211** [comment]
Hello team,

I have been testing the rules and decoders updating, and when restarting the manager this happens too.

![image](https://user-images.githubusercontent.com/23462183/105506355-42468880-5cca-11eb-97f9-3b0a02a303a2.png)

**Console log error**

**Comment by gabiwassan** [comment]
PR whit [fix](https://github.com/wazuh/wazuh-kibana-app/pull/2820).
