### ISSUE TITLE
Search resume fails to show after bad search input

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-kibana-app#2822]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.0.4  | 7.10.0     | 4016 |

**Description**
After introducing an erroneous search expression in the security event search tab, the resume of the search results shows as `--` and continues showing this way even after correcting the search. It is necessary to reload the page in the browser so it starts showing correctly.

**Steps to reproduce**

1. Go to 'Modules/Security events'
2. Click on 'Search' and introduce a correct search e.g: `rule.level >= 10 and agent.name: centos7*`. Check that the resume shows propperly.
![image](https://user-images.githubusercontent.com/19505384/105684380-2a068180-5ef5-11eb-8df8-10782e05f5ff.png)
3. Change the search term to an incorrect one, e.g: `rule.level >= 10and agent.name: centos7*`. Check the result:
![image](https://user-images.githubusercontent.com/19505384/105684726-a00ae880-5ef5-11eb-8630-e9f7aea799e2.png)
4. Revert the change and verify that the resume still shows like in step 3.
![image](https://user-images.githubusercontent.com/19505384/105684865-c597f200-5ef5-11eb-8d62-858d5c6b440f.png)

Regards,
Daniel Folch

**Comment by Desvelao** [comment]
# Changes
- If the request failed, the `loading` status didn't change the `false`. Managed the request with a `.catch`.
- The results keeps the previous value after the request is successfully completed
