### ISSUE TITLE
Index pattern is not created after specifying a new one in the app configuration

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-kibana-app#2826]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.0.4   | 7.10.0 | 4016 |

**Description**

After updating the index pattern in the configuration section, if it does not exist, no message is created or displayed indicating that the index pattern does not exist.

https://user-images.githubusercontent.com/23462183/105699609-e8cb9d00-5f07-11eb-8863-6be689f7528b.mp4

It is requested that at least the user is notified that the index pattern does not exist and that it is created manually, or that it is automatically added if it does not exist.

Best regards.

**Comment by frankeros** [comment]
@jmv74211 the index patterns are created only when the Health-check occurs. 
Please try the same but open another page with the app or force with `https://<url>/app/wazuh/health-check`

**Comment by jmv74211** [comment]
Hi @frankeros,

Indeed, by deleting the `wazuh-alerts-*` index pattern and forcing a new health check the new index pattern is created.

Perhaps as an improvement, it would be necessary to clarify this to the user who has configured this new index pattern, since for example in my case, I did not know that to use the new one I would have to delete the previous one.

Best regards.

**Comment by pablomarga** [comment]
Hi @jmv74211 we are currently working on it in #2985
