### ISSUE TITLE
Paused interface when going to the Wazuh APP from the Kibana menu through Discover

### ISSUE THREAD

**Issue by SitoRBJ** [wazuh/wazuh-kibana-app#2831]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.0.4 | 7.10.0 (Open Distro 1.12.0 | 4016 |

**Description**

The interface is paused when trying to access the Wazuh APP from the Kibana menu if we have previously navigated through the Discover section.

**Steps to reproduce**

1. Log in Kibana and access directly to the Wazuh APP
2. Click on Discover in the Kibana menu
3. Click on Wazuh APP in the Kibana menu
4. See error in browser console

**Screenshots**

![image](https://user-images.githubusercontent.com/8913336/105740421-83909f80-5f39-11eb-8887-b93208e5af2b.png)

![image](https://user-images.githubusercontent.com/8913336/105740426-855a6300-5f39-11eb-9483-e6c7ad8b2aa1.png)

![image](https://user-images.githubusercontent.com/8913336/105740447-88555380-5f39-11eb-9101-2b1ba2218a86.png)

**Comment by gabiwassan** [comment]
Hi, elasticsearch has logged this error in this [issue](https://github.com/elastic/kibana/issues/78182), right now I'm looking for a possible workaround.
