### ISSUE TITLE
Rows per page selector in SCA doesn't work

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-kibana-app#2835]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.0.4   | 7.10.0     | 4016|

**Description**
If you try to change the rows per page value while viewing SCA policy results, it doesn't do anything.

**Steps to reproduce**

1. Go to `Modules/Dashboards`.
2. Pin an agent.
3. Go to `SCA`.
4. Select a policy.
5. Change `Rows per page` value.

**Screenshots**

https://user-images.githubusercontent.com/9081114/105753428-f81f0a80-5f48-11eb-96ad-f9cdb078bd6d.mp4

**Additional context**
This happens on Windows in Chrome-based browsers.

**Comment by BraulioV** [comment]
Hi again, 

A quick update on this issue. This error affects any of the buttons at the bottom of the list: 
![image](https://user-images.githubusercontent.com/9081114/105755690-f0ad3080-5f4b-11eb-9cbe-2323fece6b88.png)

**Comment by frankeros** [comment]
Related to https://github.com/wazuh/wazuh-kibana-app/issues/2801#issuecomment-764838773
a PR is ready to solve this
