### ISSUE TITLE
SCA events shows events/checks of other agents

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-kibana-app#2837]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.0.4   | 7.10.0     | 4016|

**Description**
If you try to change the rows per page value while viewing SCA policy results, it doesn't do anything.

**Steps to reproduce**

1. Go to `Modules/Dashboards`.
2. Pin an agent (in this case, a Windows agent)
3. Go to `SCA`.
4. Select Events.

**Screenshots**

![image](https://user-images.githubusercontent.com/9081114/105754568-86e05700-5f4a-11eb-89af-66001f5f549a.png)
![image](https://user-images.githubusercontent.com/9081114/105754611-9495dc80-5f4a-11eb-8780-4a6d2ce84b25.png)

**Additional context**
This happens on Windows in Chrome-based browsers. Also, this may be related to https://github.com/wazuh/wazuh-kibana-app/issues/2818

**Comment by frankeros** [comment]
Related to #2818
