### ISSUE TITLE
SCA information is not shown for authorized agents

### ISSUE THREAD

**Issue by s-ocando** [wazuh/wazuh-kibana-app#2842]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.0.4   | 7.10.0     | 4016 |

**Description**

A user with read permission to an agent is unable to see the SCA information for said agent. 

**Steps to reproduce**

1. Assign read permissions for a limited number of agents to an elastic user. 
2. Enter Kibana with said user and go to an authorized agent view. 
3. Click on the SCA option. 
4. See error.

I'm attaching a GIF showing the error and also showing the current user security policies (read permissions for agent 001). 

**Screenshots**
![output](https://user-images.githubusercontent.com/61882981/105846842-0b7bb580-5fdd-11eb-9aba-b73ea9b0c5b3.gif)

**Additional context**
The following error is shown in the Console: "3013 - Permission denied: Resource type: agent:id."  This issue is likely related to https://github.com/wazuh/wazuh-kibana-app/issues/2801#issuecomment-765339027.

**Comment by Desvelao** [comment]
I investigated a little bit about the problem.

The `SCA: Last scan` does a request to `/sca/{agentID}` endpoint. This endpoint requires other permission different of 
- action: `agent:read`
- resource: `agent:id:{agentID}`

The required permission is:
- action: `agent:read`
- resource: `agent:id:{agentID}`

`agent:read` related endpoints:
![image](https://user-images.githubusercontent.com/34042064/105872351-99b26480-5ffa-11eb-8284-ba22ce0438d7.png)

We can check the `/sca/{agentID}` endpoint is not included for the `agent:read` action.

`sca:read` related endpoints:
![image](https://user-images.githubusercontent.com/34042064/105872579-dda56980-5ffa-11eb-8845-9f9e939b1a84.png)

The ReactJS component is `ScaScan` (`public/components/common/welcome/components/sca_scan/sca_scan.tsx`).

As a suggestion, perhaps we could wrap this component with a `withUserAuthorizationPrompt` HOC to show the required permission for this view if the user doesn't own it.
