### ISSUE TITLE
Configuration tags normalization to Wazuh standard - Kibana changes

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh-kibana-app#2856]
### Description

As part of the usability improvements, one of them is to normalize the configuration tags used in the `ossec.conf` file to the Wazuh standard. This supposes a change in all the tags that make use of the word `ossec` and should be replaced with `wazuh`.

After analyzing the default configuration file, it was identified that the only tag that should be modified is `<ossec_config>`. This supposes changes in the next set of files:

```
	- public/components/add-modules-data/module-guide.js
```

**Comment by palaciosjeremias** [comment]
This a tracking issue, meant to reflect the changes done in the wazuh/wazuh repository by the Core team for v5.0.0 replacing ossec-config tag.
These changes need to be considered for Wazuh 5.0 release.

Note: This are breaking changes.
