### ISSUE TITLE
Performance analyzer errors 

### ISSUE THREAD

**Issue by VictorMorenoJimenez** [wazuh/wazuh-kibana-app#2880]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.0   | 7.10.0     | 4101-1 |

**Description**
Hi team,
After upgrading the app to 4.1.0-7.10.0 we are getting the following errors in system logs:
```
Feb  2 09:43:25 ip-172-31-36-201 performance-analyzer-agent-cli: 09:43:25.381 [pa-reader] ERROR com.amazon.opendistro.elasticsearch.performanceanalyzer.reader.ReaderMetricsProcessor - Error reading file '/usr/share/elasticsearch/data/batch_metrics_enabled.conf': java.nio.file.NoSuchFileException: /usr/share/elasticsearch/data/batch_metrics_enabled.conf
```
The module performance analyzer shouldn't be active.
**Steps to reproduce**

1. Install app.
2. Check system logs.

We installed the app in AZL2 system with Elastic, Kibana and manager in the same node.
```
[root@ip-172-31-36-201 logs]# cat /etc/os-release 
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

**Screenshots**
![image](https://user-images.githubusercontent.com/44369304/106582287-1df97000-6544-11eb-9390-fe97ae052b77.png)

Regards,
Víctor.

**Comment by Desvelao** [comment]
This does not seem to be related to the app directly but to a configuration of the Open Distro module for Elasticsearch.
