### ISSUE TITLE
Restarting manager after changing configuration does not update manager status in app

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-kibana-app#2882]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.0   | 7.10 | 4101-1 |

Hello team,

Recently, the CICD team opened an issue to report a problem when restarting the wazuh manager via app after updating a custom rule, decoder... The related issue is this https://github.com/wazuh/wazuh-kibana-app/issues/2814.

For this new version `4.1.0-7.1.0` , we have done the same tests, and we have noticed that in Windows firefox there is the same problem, that is, The manager is restarted successfully but the app is not able to show when the manager has been restarted but waits until it gives a timeout.

https://user-images.githubusercontent.com/23462183/106589399-45ecd180-654c-11eb-9127-688eccc076a1.mp4

The app error message is as follows:

![image](https://user-images.githubusercontent.com/23462183/106589538-661c9080-654c-11eb-9b89-4e42dcbf5b12.png)

![image](https://user-images.githubusercontent.com/23462183/106589721-9ebc6a00-654c-11eb-9834-00db78ba95c7.png)

I have tested this on Linux firefox, Linux chrome and Windows Chrome and it works, but not for firefox (I have checked this several times, even changing rules configuration too). 

The Windows firefox version is `84.0.2 (32 bit)`.

It is requested to investigate and solve this case.

**Steps to reproduce**

- Change a custom rule or decoder in Windows firefox
- Save and restart manager

Best regards.

**Comment by frankeros** [comment]
This is related to #2878

**Comment by Desvelao** [comment]
I checked this and it seems I don't have that problem.
![restart-manager-after-edit-rule](https://user-images.githubusercontent.com/34042064/109652922-a9284e80-7b60-11eb-8b29-e3ad8f95bbd6.gif)

`Firefox` (Windows): `85.0 (64-bit)`
`Dev branch: 4.1-7.10`

**Comment by Desvelao** [comment]
I tested in the `info` environment and I could not experience the problem.
