### ISSUE TITLE
Wazuh app menu and logo randomly disappear

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-kibana-app#2884]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.0   | 7.10.0     | 4101-1 |

**Description**
In some scenarios the main app menu doesn't load and it forces to reload the entire page to display it again.

**Steps to reproduce**
1. Go to main Kibana page
2. Click on three bars menu of Kibana.
3. Click on Wazuh inside Wazuh section
4. See that Wazuh logo menu doesn't appear.
5. Reload entire Kibana page to make it appears.

**Screenshots**
Chrome on Linux
![image](https://user-images.githubusercontent.com/10661307/106591941-2c995480-654f-11eb-86c5-3d060800b3f3.png)

Firefox vs Chrome on Windows
![image](https://user-images.githubusercontent.com/10661307/106591975-38851680-654f-11eb-83d7-f63eac8501ee.png)

**Additional context**
It's a random display error maybe produced by slow connection or Kibana service restarts.
Browser versions:
Firefox Linux 82.0.3 (64-bit)
Chrome Linux 88.0.4324.96 (Official Build) (64-bit)

Firefox Windows 85.0 (64-bit)
Chrome Windows 88.0.4324.104 (Official build) (64 bits)
Edge Windows 88.0.705.56 (Official build) (64-bit)

**Comment by gabiwassan** [comment]
Hi @okynos,
I have tried to reproduce the problem without success, it is possible that you send us more information, a screenshot of the browser console could be very useful. Thank you!

**Comment by gabiwassan** [comment]
The issue is closed because it was not possible to reproduce the problem, in case it arises again feel free to open a new issue. 
Regards
