### ISSUE TITLE
Agent search in a group shows all agents when agent name has "strange characters"

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-kibana-app#2885]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.0   | 7.10.0     | 4101-1 |

**Description**

When you search by agent name in a group with "strange" characters, all agent's are shown. This should not be the expected behaviour, it should be shown an error message informing the user that the input is not valid or otherwise no group should be displayed.

**Steps to reproduce**

- Go to Management > Groups
- Select a group
- Search an agent using a string with "weird" characters as 'ç' or '中国'
- All agents are shown

**Screenshots**

![agent_search_error_weird_characters](https://user-images.githubusercontent.com/11089305/106592310-a598ac00-654f-11eb-822b-8ee2ea050188.png)

**Additional context**
This happens in all browsers and systems

**Comment by frankeros** [comment]
This will be fixed in a future version, with a new component because it is a common error in several tables of the application.

**Comment by Desvelao** [comment]
### Changes
A new component was created that combines a search bar and a table `TableWithSearchBar`.

- Refactorized the logic in the `Management` > `Groups` > group > `Agents` to use the new component `TableWithSearchBarWzAPI`
- Removed `colums-agents.js` file and moved its content
- Created `WzButtonPermissionsModalConfirm` component
- Removed logic to open the modal to delete an agent from a group. Now it uses `WzButtonPermissionsModalConfirm`


We will replace other search bar + table components in other sections for the new custom components.
