### ISSUE TITLE
When clicking on a decoder element its information is not displayed

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-kibana-app#2888]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.0   | 7.10 | 4101-1 |

Hello team,

When clicking in one element of the decoder list to see its details, the info does not appear.

https://user-images.githubusercontent.com/23462183/106595232-87cd4600-6553-11eb-85bd-d15113f8e454.mp4

![image](https://user-images.githubusercontent.com/23462183/106595201-7edc7480-6553-11eb-9294-ae0167e042fe.png)

It is requested to solve this error.

Best regards.

**Comment by Desvelao** [comment]
The view is crashing due to some details key were of `object` type and these weren't managed.

Fixed in the PR: https://github.com/wazuh/wazuh-kibana-app/pull/2903
