### ISSUE TITLE
Can't edit through the app empty rules and decoders files that already exist in the host

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-kibana-app#2893]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.0  | 7.10.0     | 4101-1 |

**Description**
Hi team, 

If the user has already created files in `/var/ossec/etc/rules` and `/var/ossec/etc/decoders`, they are listed in `Manage rules` as expected 
![image](https://user-images.githubusercontent.com/9081114/106598450-06c47d80-6558-11eb-8981-203f95de2492.png)

But, if you try to edit one of them and it is empty, the app shows an empty page.
![image](https://user-images.githubusercontent.com/9081114/106598589-3ecbc080-6558-11eb-8452-827718307f0a.png)

**Steps to reproduce**

1. Create an empty file in `/var/ossec/etc/rules` or `/var/ossec/etc/decoders`.
2. Go to `Management > Rules|Decoders > Custom rules|decoders > Manage rules|decoders files`.
3. Edit the empty file.

**Extra info**
This happens in Windows using Chrome-based browsers.

**Comment by Rebits** [comment]
Similarly, this issue happens also for group configuration. 
If you try to edit an empty `agent.conf`, the app will not display anything. Also in case of using the Export PDF option, the following error is displayed:

https://user-images.githubusercontent.com/11089305/106614801-0cc45980-656c-11eb-9178-de1be7ea14cd.mp4

**Comment by gabiwassan** [comment]
Hi @BraulioV, 
I have tried to reproduce the error but I have not succeeded, could you give me more information about how to reproduce it?

**Comment by sortizowlh** [comment]
When resolv.conf file is empty, autoFormat functions throws an error. 
Solved adding empty string when the file is empty.

**Comment by sortizowlh** [comment]
Checked at controller endpoint when array retrieved is empty
