### ISSUE TITLE
Indicate to the user that he can order the search reports

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-kibana-app#2897]
Hello team,

Doing app testing, I would like to propose an improvement of management/reporting filters.

By default, no icon appears next to the field name, however, when you click on it, an icon appears afterward that allows you to sort it in ascending or descending order. 

https://user-images.githubusercontent.com/23462183/106603335-7473a800-655e-11eb-8825-18f1d1a34a66.mp4

I propose to put an icon for the normal mode/state (neither ascending nor descending) to indicate to the user that he can click there and sort the search.

Best regards.

**Comment by pablomarga** [comment]
Hi @jmv74211 this table is a component from elastic, the current behaviour is that the `Created`  table is sorted descending by default.

https://user-images.githubusercontent.com/46006326/112621529-26767480-8e2a-11eb-9154-ab18d34a0b68.mov
