### ISSUE TITLE
Access to forbidden agents information when exporting agents list

### ISSUE THREAD

**Issue by s-ocando** [wazuh/wazuh-kibana-app#2900]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.0  | 7.10.0     | 4101-1 |

**Description**

A user can get information about all the available agents, including unauthorized ones, when exporting the agents' list. 

In this example, the user is authorized to read agent 005, and it can be observed that when exporting the agents' list it also includes information about agent 006. 

![output](https://user-images.githubusercontent.com/61882981/106610819-80b03300-6567-11eb-94d2-52eb3842097a.gif)

**Comment by Desvelao** [comment]
I tested the PR with an user with permission only to read one agent ant the `Export formatted` in `Agents` section generates a `.csv` with that agent. It is working.
