### ISSUE TITLE
Wazuh app section appears at the bottom

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-kibana-app#2904]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.0   | 7.10.0     | 4101-1 |

**Description**
We saw that Wazuh app section has been moved to the top of the Kibana menu but, in Firefox Linux version it appears a the bottom.

**Steps to reproduce**

1. Open Kibana webpage
2. Click on three bars menu (Kibana menu).
3. See the menu at the bottom.

**Screenshots**
![image](https://user-images.githubusercontent.com/10661307/106608623-ec44d100-6564-11eb-9105-fcddac5402ed.png)

**Additional context**
Tested on:
- Firefox 82.0.3 (64-bit)
- Firefox 84.0.2
- Firefox 85.0

**Comment by frankeros** [comment]
Hi @okynos 
Always happens? please ensure that cache is cleared.

**Comment by okynos** [comment]
After try to **remove all browsers cache** seems to be working fine, thanks @frankeros for the help!

Issue closed.

Regards.
