### ISSUE TITLE
Kibana modifies ossec.conf layout

### ISSUE THREAD

**Issue by yanazaeva** [wazuh/wazuh-kibana-app#2905]
| Wazuh  | Elastic | Rev |
| -------- | ------- | ---- |
|4.0.4      | 7.9.1    | -     |

**Description**
When you modify the _ossec.conf_ file using the Kibana App, the layout changes, meaning that if you had:
`<rule_id>5501</rule_id><!-- Login Session Open -->`

or

`<rule_id>5501</rule_id><rule_id>60109</rule_id>`

once you save it, restart the manager, and refresh the configuration will appear as:
`<rule_id>5501</rule_id>
`

or 

`<rule_id>5501</rule_id>
<rule_id>60109</rule_id>`

This interferes with the user's choice of writing the comments in a wanted place. 

**Steps to reproduce**

1. If you go to **Kibana app -> Wazuh -> Management -> Configuration -> Edit configuration** and set, for example: 
`<alerts_log>yes</alerts_log> <!-- Test -->`

if you save, restart the manager, and refresh, this configuration will change to: 
`<alerts_log>yes</alerts_log> 
`

**Screenshots**
![image](https://user-images.githubusercontent.com/67015786/106625172-b7417a00-6576-11eb-84be-0e4e439b8c1a.png)

after saving, restarting, and refreshing:
![image](https://user-images.githubusercontent.com/67015786/106625384-e48e2800-6576-11eb-989d-ab46e1e13376.png)

This layout will be visible using the cmd too:
![image](https://user-images.githubusercontent.com/67015786/106625536-08516e00-6577-11eb-8ee7-38baf71a383f.png)

**Additional context**
If you modify the _ossec.conf_ file in the cmd, the layout remains the same. This just happens when you modify it using the Kibana App.

**Comment by CPAlejandro** [comment]
Hi, I have been investigating and I have realized that the error was produced by an API endpoint used to save the document in the manager, I have contacted the department in charge of the API and they told me that the error has been fixed and they have changed the endpoint. As soon as the API department merges the change, we will put a solution.
