### ISSUE TITLE
Upgrade from 4.0.4-7.9.3 produces an error and the suggested command throw error

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-kibana-app#2906]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.0   | 7.10.0     | 4101-1 |

**Description**
While we are upgrading to 4.1.0 7.10.0 inside the OVA we found a problem related with the folder `/usr/share/kibana/data` we received an error saying that doesn't exist but copying the commands seems to throw an error. Create the folder and give it permissions solves the error dialog (this folder doesn't mention in installation documentation).

**Steps to reproduce**

1. Download OVA 4.0.4-1.11.0
2. SSH to it.
3. Upgrade following this documentation article https://documentation.wazuh.com/4.0/upgrade-guide/elasticsearch-kibana-filebeat/upgrading-open-distro.html (Changing URLs by current one).
4. Log in Kibana and see the error dialog.
5. Copy commands and see the bash error.

**Screenshots**
![image](https://user-images.githubusercontent.com/10661307/106623065-85c7af00-6574-11eb-981e-6a156a0f1f20.png)

Regards!

EDIT: Seems that in this branch is well referenced https://github.com/wazuh/wazuh-kibana-app/blob/4.1-7.10/README.md

**Comment by frankeros** [comment]
Hi @okynos, we have the documentation for this requirement in the main branch for 4.1-7.10
https://github.com/wazuh/wazuh-kibana-app/tree/4.1-7.10#upgrade
I'm closing this issue.

**Comment by okynos** [comment]
Sorry to reopen this matter, but there is another problem here. The command that it's inside the dialog doesn't work well
`chmod -R kibana:kibana /usr/share/kibana/data` throw an error in bash.
