### ISSUE TITLE
Modules are not enabled depending on the type of browser 

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-kibana-app#2911]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.0  | 7.10.0     | 4101-1 |

Hello team,

Testing the modules wazuh app, I have noticed that when you enable a new module in firefox, this is not updated in chrome views, even though you do multiple screen reloads (F5).

I have checked this case with Linux firefox, Linux chrome and macOS safari, and I have observed the following:

- If you enable a module in Linux firefox, it is enabled for macOS safari, but not for Linux chrome
- If you enable a module in macOS safari, it is enabled for Linux firefox, but not for Linux chrome
- If you enable a module in Linux chrome, it is not enabled either Linux firefox or macOS safari.
- As for windows browsers, I have checked that firefox Linux changes are done for firefox Windows but not for chrome Windows, and chrome Linux changes are done for chrome Windows but not for firefox Windows.

Below I show an example of these commented cases.

In order from left to right: Linux firefox, Linux chrome and macOS safari

https://user-images.githubusercontent.com/23462183/106723975-fc61bc80-6607-11eb-8716-5632a72acab1.mp4

Best regards.

**Comment by gabiwassan** [comment]
Hi @jmv74211, 
I am going to try to reproduce this behavior, but for the moment I suggest that you verify in this type of test clear the cache of the respective browsers, since it is common for this to happen due to the cache.

**Comment by gabiwassan** [comment]
The issue is closed because it was not possible to reproduce the problem, in case it arises again feel free to open a new issue. 
Regards
