### ISSUE TITLE
An unauthorized user can retrieve agents groups information

### ISSUE THREAD

**Issue by s-ocando** [wazuh/wazuh-kibana-app#2919]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.0  | 7.10.0     | 4101-1 |

**Description**

An unauthorized user can retrieve agents groups information, which is also shown momentarily when refreshing the groups' page before saying is forbidden.

Two issues can be seen here:
- The user is not authorized to read agents groups but can retrieve groups' information using `GET /groups` in Dev Tools.  
- When refreshing the page `Managements > Groups` the groups' information is shown momentarily before saying "You have no permissions". This behaviour is also observed in other sections like CDB lists. 

![output](https://user-images.githubusercontent.com/61882981/106746850-663b8f80-6623-11eb-90c7-3839d4ee91eb.gif)

**Comment by frankeros** [comment]
Hi @s-ocando 

This point should be reported to the API team, cause the endpoint is allowing get the information.
>     * The user is not authorized to read agents groups but can retrieve groups' information using `GET /groups` in Dev Tools.

I'm adding @davidjiglesias to the thread

**Comment by s-ocando** [comment]
The issue regarding `GET /groups` is fixed here: https://github.com/wazuh/wazuh/pull/7342
