### ISSUE TITLE
Agent view: sort by agent OS doesn't work

### ISSUE THREAD

**Issue by SpotHound** [wazuh/wazuh-kibana-app#2920]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.0  | 7.10.0     | 4101-1 |

Hello team,

We've detected that the option to sort agents by OS doesn't work on firefox nor chrome (tested on Linux)

https://user-images.githubusercontent.com/15269938/106749574-fb8c5300-6626-11eb-8ca3-1da499238a0c.mp4

**Comment by frankeros** [comment]
Hi @SpotHound 
The title and the description indicates that the column `name` is not sorting well, but in the video, you pointed to the `Os` column 
Can you fix the issue, please?

**Comment by SpotHound** [comment]
Yes, you're right, I've fixed that, thank you!
