### ISSUE TITLE
Formatted logs report cannot be exported

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-kibana-app#2924]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.0  | 7.10.0     | 4101-1 |

**Description**

When trying to export the logs we receive an error message and the log files are not downloaded.

**Steps to reproduce**

1. Go to 'Management/Logs.'
2. Click on 'Export formatted'

**Video**

- Chrome

https://user-images.githubusercontent.com/19505384/106762133-d5ba7a80-6635-11eb-94de-73dd465f864d.mp4

- Firefox

https://user-images.githubusercontent.com/19505384/106762155-db17c500-6635-11eb-91c7-2418d3028e72.mp4

Regards,
Daniel Folch

**Comment by VictorMorenoJimenez** [comment]
Hi team,
We noticed that is also happening when exporting files from a Group. 

![image](https://user-images.githubusercontent.com/44369304/106766503-39df3d80-663a-11eb-9e41-733d52379521.png)

After clicking `Generate PDF report`
![image](https://user-images.githubusercontent.com/44369304/106766547-4794c300-663a-11eb-804c-f2337f75feb6.png)
