### ISSUE TITLE
Style bug in Settings/Configuration module in Safari macOS

### ISSUE THREAD

**Issue by VictorMorenoJimenez** [wazuh/wazuh-kibana-app#2926]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.0  | 7.10.0     | 4101-1 |

Hi team,
We noticed that there is a style bug in Safari macOS `Version 14.0 (16610.1.23.1.3)` in `Settings/Configuration` module.

![image](https://user-images.githubusercontent.com/44369304/106773012-e3293200-6640-11eb-99c9-193c12910d3b.png)

Regards,

Víctor.

**Comment by pablomarga** [comment]
After several tries with @VictorMorenoJimenez  we've found that the style bug was for using VirtualBox. When using it outside VirtualBox it looks fine.

![Captura de pantalla 2021-02-11 a las 11 19 33](https://user-images.githubusercontent.com/46006326/107625117-25173100-6c5c-11eb-8d95-99e639c3a4e4.png)
