### ISSUE TITLE
Agents section is not shown when authorized agents are specified using only group ID 

### ISSUE THREAD

**Issue by s-ocando** [wazuh/wazuh-kibana-app#2933]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.0   | 7.10.0     | 4101-1 |

**Description**

In this example, a user is allowed to read agents from GroupA but the agents section is not displayed. If at least one more agent is added to the allowed agents list using an ID instead of a group then this section is displayed and includes the newly added agent (006 in this example) and the agents from GroupA.

![output](https://user-images.githubusercontent.com/61882981/106889757-baf50e00-66e8-11eb-841b-d23e21ed6e9f.gif)

**Comment by Desvelao** [comment]
This section only could be acceded with the `agent:id` action permission. 

I fixed it to access with `agent:group` action permission too.

PR: https://github.com/wazuh/wazuh-kibana-app/pull/2941
