### ISSUE TITLE
An error message is displayed when changing a group's configuration although the user has the right permissions

### ISSUE THREAD

**Issue by s-ocando** [wazuh/wazuh-kibana-app#2937]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.0   | 7.10.0     | 4101-1 |

**Description**

An error message appears stating `3013-Permission denied` after changing a group centralized configuration although the user has the right permissions. The configuration is updated despite of the error message.

![error](https://user-images.githubusercontent.com/61882981/106894179-e7ac2400-66ee-11eb-9a0a-e0f18e5e5194.png)

![permissions](https://user-images.githubusercontent.com/61882981/106894198-ed096e80-66ee-11eb-85c5-afc585bc18f9.png)

**Comment by sortizowlh** [comment]
Add to button permissions the `cluster:status` permission
