### ISSUE TITLE
Fix the unpin button in agent selection modal

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#2949]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.x   | 7.x     | 400x |

**Description**
The unpin button in the agent selection modal doesn't work. It doesn't unpin the agent.

**Steps to reproduce**

1. Go to Modules
2. Click on `Explore agent` button
3. Clink on the `Unpin agent` button
4. The agent continues pinned

**Screenshots**
![image](https://user-images.githubusercontent.com/34042064/107266994-9382a600-6a46-11eb-92f9-d3b40d4ddfe8.png)

**Comment by CPAlejandro** [comment]
Checking this issue, i can unpin the agent, but i found that when you unpinned the agent, the displays don´t show any data:

https://user-images.githubusercontent.com/17100196/108060045-a4d73e00-7056-11eb-8158-886866981f8e.mp4
