### ISSUE TITLE
Unable to go back to the visual editor after clicking on "Switch to JSON editor" when creating a new role mapping

### ISSUE THREAD

**Issue by s-ocando** [wazuh/wazuh-kibana-app#2957]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.0   | 7.10.2    | 4101-1 |

**Description**
When creating a new role mapping if the user clicks on "Switch to JSON editor" then is unable to go back to the visual editor as a message appears "Current rule can't be edited using visual editor"

![output](https://user-images.githubusercontent.com/61882981/107642591-610ac000-6c75-11eb-8016-963374e04689.gif)

**Comment by Desvelao** [comment]
I tested the PR:

If the editor has:
- `{}` can switch to the visual editor
- empty: the user can return to the visual editor. I am not sure if this behavior is we want
![image](https://user-images.githubusercontent.com/34042064/108077130-7d8b6b80-706c-11eb-8fe6-5edd9adf2c14.png)
