### ISSUE TITLE
FIM and SCA inventory content showing UTC timestamp

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-kibana-app#2960]
Hello team,

Currently, the Inventory section in the Wazuh app of the SCA and FIM capabilities are showing by default the timestamp in UTC format in contrast to the rest of the alerts and visualizations that are in the same format as the browser timezone.

For instance, for FIM Inventory, the modified file is showing the last analysis field in UTC but below is showing it in the timezone of my browser:

![image](https://user-images.githubusercontent.com/23264276/107686392-71d32a00-6ca5-11eb-804d-8ea990fdb008.png)

Also, for SCA, the last scan is in UTC:

![image](https://user-images.githubusercontent.com/23264276/107686525-a2b35f00-6ca5-11eb-96db-b74e6238fe44.png)

To be consistent, by default those fields should be converted to the respective timezone.

Regards,

Miguel Casares

**Comment by frankeros** [comment]
We'll show all dates (when they are date type) in the app formatted with the time zone configured in the Kibana settings `Timezone for date formatting (dateFormat:tz)`

**Comment by Desvelao** [comment]
### Changes
- Applied the `TimeService` to get the date formated with the browser time zone
