### ISSUE TITLE
SCA refresh button located in SCA dashboard is not refreshing the last scan date

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-kibana-app#2962]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.0  | 7.10  | 4101-2 |

**Description**

If we perform the SCA scan for a specific agent, and we use the refresh button to update the time when the scan was performed this does not seem to be updated. However, if we navigate to another tab and get back to this one, the date is refreshed.

It seems is only refreshing the result of the checks.

**Screenshots**

![image](https://user-images.githubusercontent.com/23264276/107690145-0475c800-6caa-11eb-8b25-33dd49a30b6c.png)

Regards,

Miguel Casares

**Comment by Desvelao** [comment]
### Changes
- Added a request to get the policy when refreshing
- Fixed the date format in the policy checks and policies table

![image](https://user-images.githubusercontent.com/34042064/107804335-0c923e00-6d64-11eb-836f-56b28385cba9.png)
