### ISSUE TITLE
The agents evolution graph shows information about unauthorized agents

### ISSUE THREAD

**Issue by s-ocando** [wazuh/wazuh-kibana-app#2966]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.0   | 7.10.0     | 4101-2 |

The agents evolution graph shows information about unauthorized agents. In this example, the user is authorized to read agent 001 but in the evolution graph is able to see information about two agents (one of which is not allowed to read). 

Also in details "Most active agent" the name of an unauthorized agent is shown.  

![Evolution_graph_error](https://user-images.githubusercontent.com/61882981/107761275-632f5600-6d2b-11eb-8b36-69921e950df4.png)

**Comment by sortizowlh** [comment]
Added user with specific permissions for test this issue.

**Comment by sortizowlh** [comment]
- Adding filter key to query object
`"query": {
                  'bool':{
                    'filter':[
                      {"match_phrase":{"cluster.name":"wazuh"}},
                      {"terms": { "agent.id": ["001"] } }
                    ]
                 }
                },`
- Check `discoverPendingUpdates` to change or replace the default object with filter key.
- Testing with custom filter: `Not results found`

![imagen.png](https://images.zenhubusercontent.com/5f2980436c83d247c928e37e/f17f3af4-77be-40be-896e-e8a6f41c760d)

**Comment by sortizowlh** [comment]
- Added agents to filter object to show only allowed agents by the user
- Get filter object for agents-preview is always empty. Adding filters to this chart doesn't show anything.
- Error adding filters on console: `server    log   [19:28:42.486] [error][data][elasticsearch] [version_conflict_engine_exception]: [search-telemetry:search-telemetry]: version conflict, required seqNo [2510], primary term [8]. current document has seqNo [2511] and primary term [8]
`
