### ISSUE TITLE
Vulnerabilities dashboard

### ISSUE THREAD

**Issue by tonyjoseph-sfo** [wazuh/wazuh-kibana-app#2990]
Hi is it possible to get the list of vulnerabilities with clickable link, a reference url as a summary in the vulnerabilities dashboard. like the picture given below.
![image](https://user-images.githubusercontent.com/61675354/108590306-b8e9ab00-7388-11eb-9d55-326f88e01811.png)

but what i am getting is this
![image](https://user-images.githubusercontent.com/61675354/108590320-d6b71000-7388-11eb-89bc-04b918cba408.png)

**Comment by frankeros** [comment]
We'll add this alerts summary for all modules.

**Comment by Machi3mfl** [comment]
Adding `Alert summary table` in all Modules.

- [ ] Added in Module > Vulnerabilities. Applying current dashboard filters in table (In process)

**Comment by Machi3mfl** [comment]
Adding `Alert summary table` in all Agents Modules

**SECURITY INFORMATION MANAGEMENT**
- [x] Added in `Agent > Security Events` 
- [ ] Added in `Agent > Integrity Monitoring` 
- [ ] Added in `Agent > Amazon AWS`
- [ ] Added in `Agent > Google Cloud Platform`

AUDITING AND POLICY MONITORING
- [x] Added in `Agent > Policy Monitoring` 
- [ ] Added in `Agent > System Audit` 
- [ ] Added in `Agent > Security Configuration Assessment` 

**THREAT DETECTION AND RESPONSE**
- [x] Added in `Module > Vulnerabilities` 
- [ ] Added in `Module > VirusTotal` 
- [ ] Added in `Module > OsQuery` 
- [ ] Added in `Module > MITRE ATT&CK` 

**REGULATORY COMPLIANCE**
- [x] Added in `Module > PCI DSS` 
- [x] Added in `Module > NIST 800-53`
- [x] Added in `Module > TSC`
- [x] Added in `Module > GDPR`
- [x] Added in `Module > HIPAA`
