### ISSUE TITLE
Issue with installting the plugins. 

### ISSUE THREAD

**Issue by msalemcentrilogic** [wazuh/wazuh-kibana-app#2991]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3x   | 6.x     | 444 |

**Description**
Short description of your issue.

Having issues installing the Plugin in Kibana, 

[root@umissec01 kibana]# sudo -u kibana bin/kibana-plugin install https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.1.0_7.10.2-1.zip
Attempting to transfer from https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.1.0_7.10.2-1.zip
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.1.0_7.10.2-1.zip/https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.1.0_7.10.2-1.zip-7.10.0.zip
Plugin installation was unsuccessful due to error "No valid url specified."
[root@umissec01 kibana]#

**Steps to reproduce**

**Screenshots**

**Additional context**
OS = CentOS7 

Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by Desvelao** [comment]
Hi @msalemcentrilogic,

Dis you received this log when you tried to install the plugin into Kibana? It looks strange to me.
```
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.1.0_7.10.2-1.zip/https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.1.0_7.10.2-1.zip-7.10.0.zip
```

It seems there is some strange with the log `zip-7.10.0.zip` part and `7.10.2-1.zip`. What Kibana version do you have? Did you use a valid package URL?

Could you try again the plugin installation step?

```
cd /usr/share/kibana
sudo -u kibana bin/kibana-plugin install https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.1.0_7.10.2-1.zip
```

If you Kibana version is `7.10.0` use `https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.1.0_7.10.0-1.zip` plugin package URL instead.

**Comment by msalemcentrilogic** [comment]
I used the 4.1 step-by-step installaltion: 

https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh_agent_package_linux.html

It usually craps out here: 
Step 4 in Kibana: 

Install the Wazuh Kibana plugin. The installation of the plugin must be done from the Kibana home directory as follows:
# cd /usr/share/kibana
# sudo -u kibana /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.1.0_7.10.0-1.zip

it seems to duplicate the URL .

**Comment by Desvelao** [comment]
Hi @msalemcentrilogic, the command seems to be correct.

This error happens when the URL was mistyped.
```
Plugin installation was unsuccessful due to error "No valid url specified."
```

I tried to install with that command and the installation was successful with that package URL. Are you sure you didn't mistype the package URL? Could you provide a screenshot of the terminal/console when trying to install the app package?

**Comment by msalemcentrilogic** [comment]
Thanks for support :) ... 

here is the command where it fails and I have atttached the CLI output to show as well 

```
[root@umissec01 kibana]# sudo -u kibana /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.1.0_7.10.0-1.zip
Creating home directory for kibana.
Attempting to transfer from https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.1.0_7.10.0-1.zip
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.1.0_7.10.0-1.zip/https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.1.0_7.10.0-1.zip-7.10.0.zip
Plugin installation was unsuccessful due to error "No valid url specified."

[wazuh.txt](https://github.com/wazuh/wazuh-kibana-app/files/6042616/wazuh.txt)

```

**Comment by Desvelao** [comment]
Hi @msalemcentrilogic ,

Could you try to download the package and install it with the next commands?

```
wget -O /tmp/wazuh_kibana-4.1.0_7.10.0-1.zip https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.1.0_7.10.0-1.zip
cd /usr/share/kibana
sudo -u kibana bin/kibana-plugin install file:///tmp/wazuh_kibana-4.1.0_7.10.0-1.zip
```

**Comment by msalemcentrilogic** [comment]
Hello Desvelao, 

yes sir, that did the trick. 

2021-02-26 04:35:24 (55.1 MB/s) - ‘/tmp/wazuh_kibana-4.1.0_7.10.0-1.zip’ saved [32718669/32718669]

[root@umissec01 certs]# cd /usr/share/kibana
[root@umissec01 kibana]# sudo -u kibana bin/kibana-plugin install file:///tmp/wazuh_kibana-4.1.0_7.10.0-1.zip
Creating home directory for kibana.
Attempting to transfer from file:///tmp/wazuh_kibana-4.1.0_7.10.0-1.zip
Transferring 32718669 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation complete

**Comment by Desvelao** [comment]
I am glad it's working! 😄
