### ISSUE TITLE
getListOfIndexPatterns() function

### ISSUE THREAD

**Issue by khangcnttspkt** [wazuh/wazuh-kibana-app#2992]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.0   | 7.10.2     | 4101 |

In wazuh version 4.0.1, In my case I need to edit file: /usr/shared/kibana/plugin/wazuh/public/react-services/saved-objects.js.
I edited function getListOfIndexPatterns() with another request.

In wazuh version 4.1.0, I cannot find 
static async getListOfIndexPatterns() {
try {
const result = await GenericRequest.request(
'GET',
/api/saved_objects/_find?type=index-pattern&search_fields=title
);
const indexPatterns = ((result || {}).data || {}).saved_objects || [];

  return indexPatterns;
} catch (error) {
  return ((error || {}).data || {}).message || false
    ? error.data.message
    : error.message || error;
}
}

Can help me how to find this function in Wazuh 4.1.0?

**Comment by Desvelao** [comment]
HI @khangcnttspkt , 

The function keeps in for 4.1.0 too. It is in the same file, you can check it for:
- `4.1.0-7.10.0`: https://github.com/wazuh/wazuh-kibana-app/blob/v4.1.0-7.10.0/public/react-services/saved-objects.js#L24-L38
- `4.1.0-7.10.2`: https://github.com/wazuh/wazuh-kibana-app/blob/v4.1.0-7.10.2/public/react-services/saved-objects.js#L24-L38

**Comment by khangcnttspkt** [comment]
> HI @khangcnttspkt ,
> 
> The function keeps in for 4.1.0 too. It is in the same file, you can check it for:
> 
> * `4.1.0-7.10.0`: https://github.com/wazuh/wazuh-kibana-app/blob/v4.1.0-7.10.0/public/react-services/saved-objects.js#L24-L38
> * `4.1.0-7.10.2`: https://github.com/wazuh/wazuh-kibana-app/blob/v4.1.0-7.10.2/public/react-services/saved-objects.js#L24-L38

Hi @Desvelao ,

Thank you for reply me,

But when I download pakage: https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.1.0_7.10.2-1.zip
and install with kibana-plugin, the path "public/react-services/saved-objects.js" do not exist.

**Comment by Desvelao** [comment]
Hi @khangcnttspkt,

> But when I download pakage: https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.1.0_7.10.2-1.zip
and install with kibana-plugin, the path "public/react-services/saved-objects.js" do not exist.

So you edit the file from the package. Yes, you are right. For package for Kibana 7.10.x, the app source files are transpiled. You have 2 options:
- search the transpiled file whih contains the request in `plugins/wazuh/target` directory 
- do the change in the source file, build a custom package and install it.

To found the request you want to change in the transpiled files, you could do the change in the next file:
Search in the transpiles files in `kibana/wazuh/target` directory for the package the request `/api/saved_objects/_find?type=index-pattern&search_fields=title`. The `wazuh.chun.9.js` file has the request you want. You can do the change in `<KIBANA_PATH>/plugins/wazuh/target`.

Screenshot of package:
![image](https://user-images.githubusercontent.com/34042064/108686714-1bac8500-74f6-11eb-8efd-faeb2d5f4e84.png)

**Comment by khangcnttspkt** [comment]
> Hi @khangcnttspkt,
> 
> > But when I download pakage: https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.1.0_7.10.2-1.zip
> > and install with kibana-plugin, the path "public/react-services/saved-objects.js" do not exist.
> 
> So you edit the file from the package. Yes, you are right. For package for Kibana 7.10.x, the app source files are transpiled. You have 2 options:
> 
> * search the transpiled file whih contains the request in `plugins/wazuh/target` directory
> * do the change in the source file, build a custom package and install it.
> 
> To found the request you want to change in the transpiled files, you could do the change in the next file:
> Search in the transpiles files in `kibana/wazuh/target` directory for the package the request `/api/saved_objects/_find?type=index-pattern&search_fields=title`. The `wazuh.chunk.9.js` file has the request you want. You can do the change in `<KIBANA_PATH>/plugins/wazuh/target`. After the change, you could need to delete the browser cache.
> 
> Screenshot of package:
> ![image](https://user-images.githubusercontent.com/34042064/108686714-1bac8500-74f6-11eb-8efd-faeb2d5f4e84.png)

I have edited file /urs/shared/kibana/plugins/wazuh/target/public/wazuh.chunk.9.js.
But after restart kibana and delete the browser cache. But not effect.
![image](https://user-images.githubusercontent.com/26158447/108688267-4adce980-752a-11eb-9ad0-ad62af3ebd1a.png)

**Comment by Desvelao** [comment]
Did you delete the files cache? Could you try with another browser or incognito mode?

**Comment by khangcnttspkt** [comment]
I using incognito mode and clear cache in browser but not effect.

**Comment by Desvelao** [comment]
Your browser is using one of the `.br` o `.gz` instead the `.js` file you replaced, by this reason you could not see the change. You have to modify these files too, but you can't edit directly, these files are compressed:
- `wazuh.chunk.9.js.br`
- `wazuh.chunk.9.js.br`

To do this:
1. Remove the compressed files:
```
rm wazuh.chunk.9.js.br wazuh.chunk.9.js.br
```
2. Create the compressed files:
I assume you did the change you wanted in `wazuh.chunk.9.js`.
- Generate `wazuh.chunk.9.js.gz`
```
gzip -c wazuh.chunk.9.js > wazuh.chunk.9.js.gz
```
- Generate `wazuh.chunk.9.js.br`
```
brotli -c wazuh.chunk.9.js > wazuh.chunk.9.js.br
```

If you don't have installed the `brotli` package, you have to get it.

For Centos 7, you can install `brotli` package with the next commnads:
```
yum install https://extras.getpagespeed.com/release-el7-latest.rpm
yum install brotli
```

After that, delete the files cache.

**Comment by khangcnttspkt** [comment]
> Your browser is using one of the `.br` o `.gz` instead the `.js` file you replaced, by this reason you could not see the change. You have to modify these files too, but you can't edit directly, these files are compressed:
> 
> * `wazuh.chunk.9.js.br`
> * `wazuh.chunk.9.js.gz`
> 
> To do this:
> 
> 1. Remove the compressed files:
> 
> ```
> rm wazuh.chunk.9.js.br wazuh.chunk.9.js.gz
> ```
> 
> 1. Create the compressed files:
>    I assume you did the change you wanted in `wazuh.chunk.9.js`.
> 
> * Generate `wazuh.chunk.9.js.gz`
> 
> ```
> gzip -c wazuh.chunk.9.js > wazuh.chunk.9.js.gz
> ```
> 
> * Generate `wazuh.chunk.9.js.br`
> 
> ```
> brotli -c wazuh.chunk.9.js > wazuh.chunk.9.js.br
> ```
> 
> If you don't have installed the `brotli` package, you have to get it.
> 
> For Centos 7, you can install `brotli` package with the next commands:
> 
> ```
> yum install https://extras.getpagespeed.com/release-el7-latest.rpm
> yum install brotli
> ```
> 
> After that, delete the files cache.

Hi @Desvelao ,

Thank you very much, this work for me, thank a lot.

**Comment by Desvelao** [comment]
I am glad it is working! :smile:
