### ISSUE TITLE
Wazuh menu partially blocked by Kibana navigation menu

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-kibana-app#2994]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.0   | 7.10.0     | 4101-3 |

**Description**
Whenever the Kibana navigation menu on the left is open the Wazuh drop-down menu is partially blocked.
Even when this Navigation bar is docked. So users that prefer this view cannot change between Modules, Management, Agents, Settings, etc.

**Steps to reproduce**

1. Click on the three horizontal bars of the Kibana navigation menu
2. Select Dock navigation from the bottom
2. Click on the Wazuh menu
3. See how it blocks the left column of the Wazuh menu

**Screenshots**
![image](https://user-images.githubusercontent.com/36071202/108723973-1dda0800-7525-11eb-950a-ff8ea981825d.png)

**Comment by Desvelao** [comment]
### Changes
- Overlay the Wazuh menu to the Kibana menu when it is opened or docked

Screenshots
![image](https://user-images.githubusercontent.com/34042064/109628597-3a88c800-7b43-11eb-9ad8-e00f08f710bb.png)
![image](https://user-images.githubusercontent.com/34042064/109628660-496f7a80-7b43-11eb-8213-43481d0ea333.png)
