### ISSUE TITLE
When agent.conf content is removed, can't edit file again.

### ISSUE THREAD

**Issue by sortizowlh** [wazuh/wazuh-kibana-app#2996]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.1   | 7.10.0     | 4102|

**Description**
When agent.conf content is removed, can't edit again this file

**Steps to reproduce**

1. Go to Management > Groups
2. Create a new group.
3. Enter this group and go to tab Files.
4. Remove agent.conf content

Now, when trying to edit the file again, it fails with this error:

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5f2980436c83d247c928e37e/47bff87a-e3a7-4276-b150-9eb178c1166d)

**Comment by Desvelao** [comment]
I checked this and it seems it is working.

This line is setting the content to empty string when no result is returned:
https://github.com/wazuh/wazuh-kibana-app/blob/4.1-7.10/public/controllers/management/components/management/groups/utils/columns-files.js#L42-L44
