### ISSUE TITLE
wazuh-kibana-app 3.2.1 error

### ISSUE THREAD

**Issue by damayu2013** [wazuh/wazuh-kibana-app#300]
Great Project!  But I got some problem:

ENV:
OS: CentOS 7
wazuh-manager:  wazuh-manager-3.2.1-1.x86_64.rpm
wazuh-api: wazuh-api-3.2.1-1.x86_64.rpm
ELK and filebeat: 6.2.2
wazuh-kibana: wazuhapp-3.2.1_6.2.2.zip

![tim 20180307202012](https://user-images.githubusercontent.com/16527289/37092079-60b2ad20-2245-11e8-84eb-6feb4c556d7f.png)

Got ERROR:
![tim 20180307202139](https://user-images.githubusercontent.com/16527289/37092100-7327ed58-2245-11e8-93a5-8efe845c437c.png)

![tim 20180307202030](https://user-images.githubusercontent.com/16527289/37092118-8187b31a-2245-11e8-851d-1274cdfdc0e7.png)

**Comment by damayu2013** [comment]
I am sorry;  I miss the step:

curl https://raw.githubusercontent.com/wazuh/wazuh/3.2/extensions/elasticsearch/wazuh-elastic6-template-alerts.json | curl -XPUT 'http://localhost:9200/_template/wazuh' -H 'Content-Type: application/json' -d @-

curl https://raw.githubusercontent.com/wazuh/wazuh/3.2/extensions/elasticsearch/wazuh-elastic6-template-monitoring.json | curl -XPUT 'http://localhost:9200/_template/wazuh-agent' -H 'Content-Type: application/json' -d @-

it's OK;

**Comment by JuanjiJG** [comment]
Hello @damayu2013,

I'm glad that you solved your problem!

Don't hesitate to post a new issue if you have more errors using the Wazuh app. Every comment and feedback is very appreciated!

Regards,
Juanjo
