### ISSUE TITLE
Clicking on police L1 it shows me data from policy L1 and data from policy L2 on SCA

### ISSUE THREAD

**Issue by CPAlejandro** [wazuh/wazuh-kibana-app#3000]
By clicking on police L1 it shows me data from policy L1 and data from policy L2.
Also if I enter L1 and refresh, I get the L2 data
https://images.zenhubusercontent.com/62186486/daa4996d-4add-41be-b5e5-7b7fcbd207c2/scabug.mp4

**Comment by Desvelao** [comment]
### Changes
The request to get the SCA policy with the results and name is wrong formulated and all policies are returned and selected the first. The parameters to filter the selected SCA policy is built wrong way.
