### ISSUE TITLE
Testing 4.1.1-7.10.0 - Specific changes

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#3002]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.1   | 7.10.0     | 4102|

**Description**
Testing.

Test with browsers:
- Chrome
- Firefox
- Safari

Checks:
- [x] Basic (without security)
- [x] ODFE 1.12.0
- [x] X-Pack

Test suite:

Prompt to show the unsupported module for the selected agent
Added a X-Frame-Options header to the backend responses
Added toast with refresh button when new fields are loaded
An error message is displayed when changing a group's configuration although the user has the right permissions
Fix Security events table is empty when switching the pinned agents
Fix disabled switch visual edit button when json content is empty
Fixed main and More menus for unsupported agents
Fixed forcing a non numeric filter value in a number type field
Fixed wrong number of alerts in Security Events
Fixed search with strange characters of agent in Management groups
Fix the statusCode error message
Fix the SCA policy stats didn't refresh
Fixed loading of AWS index fields even when no AWS alerts were found
Fix some date fields format in FIM and SCA modules
Fix a non-stop error in Manage agents when the user has no permissions
Can't edit empty rules and decoders files that already exist in the manager
Support for alerts index pattern with different ID and name
Fix the unpin agent in the selection modal
Fix properly logout of Wazuh API when logging out of the application (only for OpenDistro)
Fix login error when AWS Elasticsearch and ODFE is used
Migrated manager and cluster files endpoints and their corresponding RBAC

**Comment by Desvelao** [comment]
- [ ] The table is empty while the visualizations are displaying information. It happens sometimes
- [ ] The toast is displayed when no new alerts with new fields are inserted
- [ ] Show a prompt with group:read group:id:* instead the specific group
- [ ] Some errors when try to see decoders details
- [ ] Configuration view of a specific agent is not loading
- [ ] The toast is still appearing without a refresh button AWS views (ODFE)
- [ ] Can't switch from json editor to visual editor (ODFE)
- [ ] In Chrome, can add level.error ="e" and display bad request toast (ODFE)
- [ ] Date shown with UTC SCA (ODFE)

**Comment by frankeros** [comment]
Tanking `Some errors when try to see decoders details`

----

PR #3003

**Comment by pablomarga** [comment]
Taking `Show a prompt with group:read group:id:* instead the specific group`

**Comment by frankeros** [comment]
Refreshing the page in Modules / Alerts Security with an Agent pinned the views crash.
![image](https://user-images.githubusercontent.com/26828184/108848278-91305800-75bf-11eb-81b4-d9dde99d49a4.png)

**Comment by frankeros** [comment]
>     * Security events: The table is empty while the visualizations are displaying information. It happens sometimes

The fix of this issue has been removed from this version and the fix will be added in the next revision.
