### ISSUE TITLE
Change all dates labels to Kibana formatting time zone

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3009]
Hi team, 
we must show all dates in Wazuh application (date type fields) using the UI settings of Kibana `dateFormat` and `dateFormat:tz` to keep all dates in the same format. 
Here is an example
![image](https://user-images.githubusercontent.com/26828184/109497268-8d457f80-7a70-11eb-8210-36eeb56b0265.png)

---

These settings are able to be set into `Kibana / Stack Management / Advanced Settings`
![image](https://user-images.githubusercontent.com/26828184/109496279-35f2df80-7a6f-11eb-8359-45986332fc05.png)

## Tasks ##
- [ ] Survey the places to change the dates format
- [ ] Migrate them using the `UiSettingsClient` from `kibana/public`

**Note**:  use `getUiSettings().get` from `public/kibana-services.ts` to get the settings values.

**Comment by sortizowlh** [comment]
added export functions at `time-service.js` for get Kibana date format and to format given dates.

**Comment by sortizowlh** [comment]
Modified `time-service.js`:
- Removed class. Now, there is only one function.
- Call change: Now the function `formatUIDate` is called instead of the function `offset `
