### ISSUE TITLE
Wazuh dev tools does not performing autocomplete for all body query options

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3010]
Wazuh dev tools do not perform autocomplete for all body query options

It should display the suggestions for the body properties corresponding to the endpoint that you are wrinting.

**Comment by gabiwassan** [comment]
I was doing tests on the code to be able to apply the use of autocomplete for request bodies, but I had to make many changes that did not lead me to anything, it has a lot of code fixed on fixed and difficult to apply changes :(
I could start segmenting and separating the code to be able to apply bigger changes that do not generate problems in the future, but it takes more time.

**Comment by gdiazlo** [comment]
Being worked at #4050
