### ISSUE TITLE
user creation

### ISSUE THREAD

**Issue by Sivavamsiraju** [wazuh/wazuh-kibana-app#3014]
How to create users in wazuh i tried to create the user but unable to login 
When i tried to login its showing an error application not found pls try to help to solve this

**Comment by asteriscos** [comment]
Hi @Sivavamsiraju,
I understand you are trying to create a user for `Open Distro for Elastic Search` or maybe using _x-pack_ and then use it to login on `Kibana`. I will give you a quick example, but it would help a lot if you could specify exactly **what you are trying to achieve, which security plugin are you using, which error did the app show** (and where) and any extra info like screenshots.


To create a user using **ODFE** you must be able to login with an **admin account** and then click on the **Security** item found on the **main menu**:

![Screenshot from 2021-02-25 14-03-09](https://user-images.githubusercontent.com/9343732/109191404-e82b5e00-7774-11eb-8ae6-3d1b37499596.png)

On the left list you will find the **Internal User** item. Select it and in the next view click on **Create Internal user**
![Screenshot from 2021-02-25 14-03-21](https://user-images.githubusercontent.com/9343732/109191919-6982f080-7775-11eb-856b-a5d9dabf7f37.png)

Fill in the fields and create the user. After this you should be able to log in
![Screenshot from 2021-02-25 14-04-34](https://user-images.githubusercontent.com/9343732/109192170-ad75f580-7775-11eb-954a-c551a556c5ac.png)

Here's some additional information that may prove useful:
https://documentation.wazuh.com/4.0/user-manual/elasticsearch/elastic_tuning.html

Hope this helps!

Best,
Federico Rodriguez

**Comment by Sivavamsiraju** [comment]
> 
> 
> Hi @Sivavamsiraju,
> I understand you are trying to create a user for `Open Distro for Elastic Search` or maybe using _x-pack_ and then use it to login on `Kibana`. I will give you a quick example, but it would help a lot if you could specify exactly **what you are trying to achieve, which security plugin are you using, which error did the app show** (and where) and any extra info like screenshots.
> 
> To create a user using **ODFE** you must be able to login with an **admin account** and then click on the **Security** item found on the **main menu**:
> 
> ![Screenshot from 2021-02-25 14-03-09](https://user-images.githubusercontent.com/9343732/109191404-e82b5e00-7774-11eb-8ae6-3d1b37499596.png)
> 
> On the left list you will find the **Internal User** item. Select it and in the next view click on **Create Internal user**
> ![Screenshot from 2021-02-25 14-03-21](https://user-images.githubusercontent.com/9343732/109191919-6982f080-7775-11eb-856b-a5d9dabf7f37.png)
> 
> Fill in the fields and create the user
> ![Screenshot from 2021-02-25 14-04-34](https://user-images.githubusercontent.com/9343732/109192170-ad75f580-7775-11eb-954a-c551a556c5ac.png)
> 
> Once the user is created you should map it with the role it needs:
> ![Screenshot from 2021-02-25 14-56-19](https://user-images.githubusercontent.com/9343732/109195830-c2ed1e80-7779-11eb-82e5-329905bb06b5.png)
> ![Screenshot from 2021-02-25 14-56-49](https://user-images.githubusercontent.com/9343732/109195847-c7193c00-7779-11eb-8d59-cc471964182e.png)
> 
> Here's some additional information that may prove useful:
> https://documentation.wazuh.com/4.0/user-manual/elasticsearch/elastic_tuning.html
> 
> Role mapping:
> https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/users-roles/#map-users-to-roles
> 
> Hope this helps!
> 
> Best,
> Federico Rodriguez

Thank you so much Federico Rodriguez But still i am facing a issue that when i am giving some roles and mapping with users its not working so can you share that which type roles should i give to users like L1,L2 ansd L3

Thanks In Advance

**Comment by asteriscos** [comment]
Hi Sivavamsiraju,
to be able to provide you a specific solution it would be really helpful to have more information about your issue. For instance, **what is it that is not working?** **Are you unable to login?** or may be **is there a specific feature that is not working?** **Are you using Open Distro or may be x-pack to handle the security layer?**
I'm asking this because there are basically 2 sets of authentication and authorization configurations that are involved. One is for Elastic Search and the other one is to set Wazuh API permissions.

Wazuh API RBAC:
https://documentation.wazuh.com/current/user-manual/api/rbac/index.html

Elastic roles:
https://www.elastic.co/guide/en/elasticsearch/reference/current/get-started-roles.html

Best,
Federico Rodriguez

**Comment by frankeros** [comment]
Hi @Sivavamsiraju 
could you solve this problem?

**Comment by pablomarga** [comment]
Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our [slack channel](https://wazuh.com/community/join-us-on-slack/) or subscribe to our [mailing list](https://groups.google.com/forum/#!forum/wazuh).
