### ISSUE TITLE
Wazuh API is down error after changing master node configuration

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-kibana-app#3023]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.1   | 7.10.0     | N/A |

**Description**
After changing the master node configuration back and forth between enabled and disabled, the Wazuh API connection check never completes.

**Steps to reproduce**

1. Go to Management, Configuration
2. Ensure the master node is selected (default) and click on Edit configuration
3. Look for the `cluster` section and set:
  - `<disabled>yes</disabled>`
4. Click on Save and then on Restart master
5. Let the entire process finish and then repeat the process to change back to:
  - `<disabled>no</disabled>`
6. Click on Save and then on Restart master
7. Error appears

**Screenshots**
![image](https://user-images.githubusercontent.com/48716145/109183584-63e5d480-778e-11eb-91ea-3b140ab0f97a.png)

Clicking on `Go To App` will work, but the check should finish correctly.

The master node API is working correctly after the last restart:
```
2021/02/25 16:24:31 INFO: Listening on 0.0.0.0:55000..
2021/02/25 16:24:33 INFO: unknown_user 10.0.0.151 "GET /manager/status" done in 0.013s: 400
2021/02/25 16:24:33 INFO: unknown_user 10.0.0.151 "GET /security/user/authenticate" done in 0.003s: 400
2021/02/25 16:24:33 INFO: unknown_user 10.0.0.151 "GET /manager/info" done in 0.003s: 400
2021/02/25 16:24:36 INFO: wazuh 10.0.0.151 "GET /manager/status" done in 0.079s: 200
2021/02/25 16:24:36 INFO: wazuh 10.0.0.151 "GET /cluster/status" done in 0.094s: 200
2021/02/25 16:24:36 INFO: wazuh 10.0.0.151 "GET /cluster/nodes" done in 0.099s: 200
2021/02/25 16:25:01 INFO: wazuh 10.0.0.151 "GET /manager/stats/remoted" done in 0.115s: 200
2021/02/25 16:25:01 INFO: wazuh 10.0.0.151 "GET /manager/stats/analysisd" done in 0.058s: 200
```

**Comment by CPAlejandro** [comment]
I have tried to reproduce it with ODFE and without security, with Chrome and Firefox but in all 4 cases it has done perfectly without showing me the error that appears to you
