### ISSUE TITLE
Network Device

### ISSUE THREAD

**Issue by Sivavamsiraju** [wazuh/wazuh-kibana-app#3024]
I am Trying to add my local network device(TP link)  into wazuh to monitor logs but i am unable to add can anyone help me out to add my network devices into wazuh to monitor network logs

**Comment by Sivavamsiraju** [comment]
pls help on this i trying to monitor network syslogs grom wazuh but i am unable to configure it

**Comment by frankeros** [comment]
Hi @Sivavamsiraju 
I figured out that you have several drawbacks with your  Wazuh environment, please check out our documentation [here](https://documentation.wazuh.com/current).

> I am Trying to add my local network device(TP link) into wazuh to monitor logs

For this, you can check this https://documentation.wazuh.com/current/user-manual/registering/index.html


> pls help on this i trying to monitor network syslogs grom wazuh but i am unable to configure it

For this, you can check https://documentation.wazuh.com/current/user-manual/manager/manual-syslog-output.html?highlight=syslogs

If you need more specific help, please tell us with more details about what are you trying and what errors are getting.

**Comment by frankeros** [comment]
Hi @Sivavamsiraju 
could you solve this problem?

**Comment by pablomarga** [comment]
Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our [slack channel](https://wazuh.com/community/join-us-on-slack/) or subscribe to our [mailing list](https://groups.google.com/forum/#!forum/wazuh).

**Comment by pablomarga** [comment]
Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our [slack channel](https://wazuh.com/community/join-us-on-slack/) or subscribe to our [mailing list](https://groups.google.com/forum/#!forum/wazuh).
