### ISSUE TITLE
Cluster setup

### ISSUE THREAD

**Issue by Sivavamsiraju** [wazuh/wazuh-kibana-app#3029]
Hi Pls help me on this 
i am trying to setup wazuh cluster enviornment on my 5 systems can one help me how to setup it

**Comment by frankeros** [comment]
Hi @Sivavamsiraju
I figured out that you have several drawbacks with your Wazuh environment, please check out our documentation here.


> i am trying to setup wazuh cluster enviornment on my 5 systems can one help me how to setup it

For this, you can check https://documentation.wazuh.com/current/installation-guide/open-distro/distributed-deployment/step-by-step-installation/wazuh-cluster/index.html

If you need more specific help, please tell us with more details about what are you trying and what errors are getting.

**Comment by frankeros** [comment]
Hi @Sivavamsiraju 
could you solve this problem?

**Comment by pablomarga** [comment]
Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our [slack channel](https://wazuh.com/community/join-us-on-slack/) or subscribe to our [mailing list](https://groups.google.com/forum/#!forum/wazuh).
