### ISSUE TITLE
Elasticsearch template : No template found for the selected index-pattern

### ISSUE THREAD

**Issue by b4b857f6ee** [wazuh/wazuh-kibana-app#3031]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.1-1   |  7.10.2-1    |  |

**Description**
upgrade from 3.13 to 4.1.1

**Steps to reproduce**

Follow the upgrade procedure here (from the 3.13 OVA)

https://documentation.wazuh.com/current/upgrade-guide/upgrading-wazuh.html

I get this : 

RUN -> : curl 'http://127.0.0.1:9200/api/saved_objects/index-pattern/wazuh-alerts-3.x-*' -X DELETE  -H 'Content-Type: application/json' -H 'kbn-version: 7.10.2' -k
Message :
{"error":"no handler found for uri [/api/saved_objects/index-pattern/wazuh-alerts-3.x-*] and method [DELETE]"}

When i try to update the template a get : 
curl -X PUT "http://localhost:9200/_template/wazuh" -H 'Content-Type: application/json' -d @wazuh-template.json
Message : {"acknowledged":true}  but i get nothing. 

I have create the index pattern : wazuh-alerts-4.x-* myself but i can't create the archives one.

![image](https://user-images.githubusercontent.com/36012515/109515906-e8469900-7aa7-11eb-8cae-77314910c46f.png)

I can access the APP.

![image](https://user-images.githubusercontent.com/36012515/109515523-7706e600-7aa7-11eb-82f0-6a832b419b9c.png)

I always get this ; 
![image](https://user-images.githubusercontent.com/36012515/109515606-8f770080-7aa7-11eb-9ebd-df17d6bebade.png)

But i got this : curl -k https://127.0.0.1:55000
{"title": "Unauthorized", "detail": "No authorization token provided"}

I have test with foo and bar and the default wazuh-wui:wazuh-wui but nothing.

Any idea? :)

Thank you!

**Comment by gabiwassan** [comment]
Hello @b4b857f6ee,
Could you check the templates? 
Using Kibana Dev Tools: `GET _cat/templates`

On the other hand, to remove old indices could you do with this [guide](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-delete-index.html) or if you want to keep your old indices you could reindex them with this [guide](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html) and I recommend using Dev Tools for safety. 

Regards.

**Comment by b4b857f6ee** [comment]
> GET _cat/templates

Hello,
Result : 
wazuh       [wazuh-alerts-4.x-*, wazuh-archives-4.x-*]   0 1 
wazuh-agent [wazuh-monitoring-3.x-*, wazuh-monitoring-*] 0   

I just delete the 3.x

Looks ok now, no error.
Thank you.

**Comment by Techkrunch** [comment]
Just change the 127 address to the current host address 

It worked for me

Thank me later

> [b4b857f6ee](/b4b857f6ee)
