### ISSUE TITLE
Flyout date filter also changes main date filter

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-kibana-app#3040]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.1   | 7.10     | 4102 |

**Description**
When changing the date filter inside a details flyout, it also changes the main view date filter. 

**Steps to reproduce**

1. Go to `Mitre` -> `Framework`
2. Click on any of the list items to open the _flyout_
3. Change the **date filter** inside the _flyout_
4. Close the _flyout_ and check it also changed the date of the background view

**Screenshots**
![datechange](https://user-images.githubusercontent.com/9343732/109688942-97947600-7b63-11eb-8da3-49cd30fca98a.gif)

**Additional context**
This seems to happen in all browsers and system.

**Comment by pablomarga** [comment]
Working with @Desvelao, we saw that the problem was related to a parameter (`timefilter`) that was globally share. Trying to change this so when you applied this filter only change the date in the flyout.
