### ISSUE TITLE
Testing 4.1.1 rev 4103

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3044]
| Version | Revision |
| ---------: | -----------: |  
|4.1.1|4103|

Do specific test for changes in revision 4103, in the next prod environments

- [x] ODFE  1.12.0
- [x] ODFE  1.13.0
- [x] No security 7.10.2 
- [x] No security 7.11.0
- [x] X-Pack 7.10.2
- [x] X-Pack 7.11.0

### Added

- Refactor of some prompts [#3015](https://github.com/wazuh/wazuh-kibana-app/pull/3015)
- Add `run_as` setting to example host configuration in Add new API view [#3021](https://github.com/wazuh/wazuh-kibana-app/pull/3021)

### Fixed

-Fix SCA policy detail showing name and check results about another policy [#3007](https://github.com/wazuh/wazuh-kibana-app/pull/3007)
- Fixed that alerts table is empty when switching pinned agents [#3008](https://github.com/wazuh/wazuh-kibana-app/pull/3008)
- Creating a role mapping before the existing ones are loaded, the page bursts [#3013](https://github.com/wazuh/wazuh-kibana-app/pull/3013)
- Fix pagination in SCA checks table when expand some row [#3018](https://github.com/wazuh/wazuh-kibana-app/pull/3018)
- Fix manager is shown in suggestions in Agents section [#3025](https://github.com/wazuh/wazuh-kibana-app/pull/3025)
- Fix disabled loading on inventory when request fail [#3026](https://github.com/wazuh/wazuh-kibana-app/pull/3026)
- Fix restarting selected cluster instead of all of them [#3032](https://github.com/wazuh/wazuh-kibana-app/pull/3032)
- Fix pinned agents don't trigger a new filtered query [#3035](https://github.com/wazuh/wazuh-kibana-app/pull/3035)
- Overlay Wazuh menu when Kibana menu is opened or docked [#3038](https://github.com/wazuh/wazuh-kibana-app/pull/3038)

**Comment by gabiwassan** [comment]
X-Pack 7.10.2 ✅
