### ISSUE TITLE
The graph for `Events processed` is showing data of all nodes

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3068]
| Wazuh | Elastic |
| ----- | ------- |
| 4.1   | 7.10     |

**Description**
The graph for `Events processed` in `Management / Statistics` is showing data of all nodes when a particular node is selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/26828184/110688662-9812b980-81c0-11eb-8a0e-d1477336ddf7.png)

**Comment by pablomarga** [comment]
Found that the error was related to how the query is and that `-` is a special character in Lucene Language
