### ISSUE TITLE
The values of the suggestions are badly filtered in Agents

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3070]
| Wazuh | Elastic |
| ----- | ------- | 
| 4.1.2  | 7.10    | 

**Description**
The values of the suggestions are badly filtered when some text is added in the search bar of the Agents table.

**Steps to reproduce**

1. Go to Agents
2. Type in the search bar 'id=04'
4. See other options without '04' text

**Screenshots**
![image](https://user-images.githubusercontent.com/26828184/110852118-b516bd80-8290-11eb-8b41-4a549925cc85.png)

**Additional context**
Sames happen with other fields like `name`
Tested in wazuh.demo.com

**Comment by Machi3mfl** [comment]
Issue create in `wazuh/wazuh` https://github.com/wazuh/wazuh/issues/8152

**Comment by frankeros** [comment]
Blocked by https://github.com/wazuh/wazuh/issues/8152
