### ISSUE TITLE
Wrong name for "TCP sessions" visualization.

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh-kibana-app#3073]
The `TCP sessions` visualization in `Wazuh > Management > Statistics > Listener engine` is showing the average of sessions instead of the total sessions as the name suggest.

For example, my deployment has 7 workers with ~300 TCP sessions per worker (2100 in total, that corresponds with the active agents). The visualization shows an average of "300" instead of 2100.
![image](https://user-images.githubusercontent.com/1523318/110940596-76880e00-8337-11eb-92db-745ab4dae377.png)

I think we need both visualizations: average and total.

**Comment by eze9252** [comment]
Hi @jesuslinares ,

I propose the next fix: 

In TCP sessions, show two metrics: total tcp sessions and average:

![image](https://user-images.githubusercontent.com/36004787/112211067-39a2fd80-8bfa-11eb-890e-20bcb261d9cb.png)

 Tell me what you think.


Regards
