### ISSUE TITLE
Index pattern setting not used for choosing from existing patterns

### ISSUE THREAD

**Issue by DGawr** [wazuh/wazuh-kibana-app#3074]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.2   | 7.10     | - |

**Description**
The value set for the "default index pattern to use on the app" ([pattern setting](https://documentation.wazuh.com/current/user-manual/kibana-app/reference/config-file.html#pattern)) is not used for choosing a pattern to load when multiple valid Wazuh indices exist.

Furthermore since the request used in [saved-objects.js](https://github.com/wazuh/wazuh-kibana-app/blob/master/public/react-services/saved-objects.js#L28) does not use the `sort_field` option the index pattern used can be somewhat random, since apparently Kibana's API does not have a default sorting.

**Steps to reproduce**

1. Configure multiple valid Wazuh index patterns (e.g. wazuh-alerts-* and wazuh-archives-*)
2. Access the Wazuh app "for the first time" (clear all cookies or use private browsing mode)
3. The Wazuh app chooses one of the available index patterns, basically the first valid one from the list (not the default pattern one). Depending how the Kibana API sorts them, it can differ when trying multiple times.

**Additional context**
During initialization of the Wazuh app [checkPatterns()](https://github.com/wazuh/wazuh-kibana-app/blob/master/public/components/health-check/health-check.tsx#L60) is used to check for valid indices and set it. When no cookie exists, it calls [getListOfWazuhValidIndexPatterns()](https://github.com/wazuh/wazuh-kibana-app/blob/master/public/react-services/saved-objects.js#L45) and uses the first index from the list. At this point the default index pattern from the configuration could be chosen, if it exists, and the first one from the list as a backup, if it does not exist.

**Comment by Desvelao** [comment]
Hi @DGawr,

You are right, select the first valid index pattern in the list which fulfills the minimum requirements to be usable by the app without taking into account the default index in the configuration.

Thank you so much for report it.
