### ISSUE TITLE
Invalid rule configuration leading to critical error in the Wazuh-manager

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-kibana-app#3078]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
|4.0.4  | 4.0.1.7 | 7.10.0 | 

Hello team,

If we save a rule with a bad syntax in the Rules section, the file is saved and after manually restarting the manager, it stops working with a critical signal.

**Steps to reproduce**

1. Go to 'Management > Rules > Custom rules > local_rules.xml.'
2. Add invalid configuration
```
  <rule id="221" level="3" overwrite="yes">
    <category>ossec</category>
    <decoded_as>syscollector</decoded_as>
    <description>Syscollector event.</description>
    <interval>10m</interval>
  </rule>
```
4. Save
![image](https://user-images.githubusercontent.com/23264276/111451382-ac4f3d00-8711-11eb-867e-49ee34fe3fd7.png)

Although we have a warning showing us that the configuration is invalid, the file was saved and if we manually restart the manager we find the following error:
```
2021/03/17 09:14:17 ossec-analysisd: ERROR: Invalid option 'interval' for rule '221'.
2021/03/17 09:14:17 ossec-analysisd: CRITICAL: (1220): Error loading the rules: 'etc/rules/local_rules.xml'
```

If a bad configuration is applied, the file should not be saved. This may potentially be affecting other configurations or files in the plugin. 

In addition, in the latest version, it throws an error instead of a `warning` but it is saving the file anyway.

**Additional context**
Possibly related: https://github.com/wazuh/wazuh-kibana-app/issues/2891

**Comment by asteriscos** [comment]
Hi team,

I was able to reproduce and fix the rollback issue. A pull request was just created.

When editing an existing file
![Screenshot from 2021-03-18 15-42-23](https://user-images.githubusercontent.com/9343732/111681880-83f33b80-8802-11eb-9e93-af8cce1b10bb.png)

When creating a new one
![Screenshot from 2021-03-18 15-41-39](https://user-images.githubusercontent.com/9343732/111681909-88b7ef80-8802-11eb-9407-98083b9c2a73.png)
