### ISSUE TITLE
Add the STATUS and TYPE of the vulnerabilities to the vulnerabilities view that affect each agent

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh-kibana-app#3093]
**Describe the solution you'd like**

As part of the epic https://github.com/wazuh/wazuh/issues/7749, we are adding new information to the agents' vulnerabilities inventory. This new information will be:

- `status`: It indicates whether the vulnerability is `VALID`, `PENDING`, or `OBSOLETE`.
- `type`: It indicates whether the vulnerability affects the `OS` or a particular `PACKAGE`.

This information should be taken into account to select the vulnerabilities that will be displayed in the vulnerabilities view that affect each agent created as part of the issue https://github.com/wazuh/wazuh-kibana-app/issues/3011.

For simplifying the understanding of the information by the users, we will display only the vulnerabilities in `VALID` and `PENDING` status of any `type` (`OS` or `PACKAGE`). But no information will be provided on the status of the vulnerabilities displayed.

For details about the modifications implemented in the API endpoint used for this, check the issue https://github.com/wazuh/wazuh/issues/7972.

**Comment by frankeros** [comment]
Also, refactor the table with the new table component.
