### ISSUE TITLE
Display alerts for authorized user's agent only - Alerts table

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3094]
Hi team,
In order to display alerts for authorized user's agents only, we need to filter them in some sections of the app.

- [x] Alerts table in Security Alerts

Related to #3088

**Comment by CPAlejandro** [comment]
**Actual state:**
I have managed to make the Security Alerts table filter by the allowed agents, it would be missing that Total,
Level 12 or above alerts, Authentication failure and Authentication success filter as well
