### ISSUE TITLE
HELP MEEEEE !

### ISSUE THREAD

**Issue by vanduc9a2** [wazuh/wazuh-kibana-app#3101]
I’ve set up new WAZUH sever – The local sever (Single-host architectures)
 - wazuh-manager : v3.9.5
 - wazuh-api     : v3.9.5
 - wazuh app     : v3.9.0
 - Elasticksearch: 6.7.1
 - kibana        :6.7.1
 - logtash       : 6.7.1
Because this is Single-host architectures, so filebeat is unnecessary, and I hadn’t used. error incurred system such as: No security problem found. while var/ossec/logs/alerts/alerts.json has a change capacity
-I’m very glad and looking forward to the help
-If you need for more information or meeting, please contact me via UltraViewer : ( ID:38 113 699 Pass: 2228 )
Thank you very much!!!

![1](https://user-images.githubusercontent.com/60965425/112251256-7ec43f80-8c8d-11eb-8304-d30daa2affd3.png)
![2](https://user-images.githubusercontent.com/60965425/112251280-8ab00180-8c8d-11eb-84e4-a8230fd2c480.png)
![3](https://user-images.githubusercontent.com/60965425/112251284-8d125b80-8c8d-11eb-9369-ecef32783b2a.png)
![4](https://user-images.githubusercontent.com/60965425/112251289-8f74b580-8c8d-11eb-918b-e7cbb1e87bd2.png)
![5](https://user-images.githubusercontent.com/60965425/112251364-b16e3800-8c8d-11eb-819b-ee31ccf1a358.png)

**Comment by Desvelao** [comment]
Hi @vanduc9a2 ,

Check the next things:
1. Try to change the range time in Kibana and check if there are alerts. In your screenshots, you are using `15 minutes` from now. Try with `a day` or some higher.
2. Check you have `wazuh-alerts-3.x-*` indices. Go to Kibana Dev Tools section and do the request:
```
GET /_cat/indices
```
3. If you don't have `wazuh-alerts-3.x-*` indices in Elasticsearch, you could a problem with Logstash or the Logstash - Elasticsearch connection.
3.1. Check the Logstash is running. Depending on your service manager:
- `service logstash status`
- `systemctl status logstash`
3.2. Review the Logstash logs:
```
cat /var/log/logstash/logstash.log
```
3.3. Check the Logstash configuration is working
```
logstash --config.test_and_exit -f <the config file/folder>
```
Share the Logstash configuration and please obfuscate the sensitive data.

**Comment by vanduc9a2** [comment]
Tks U for ! let me try's

**Comment by vanduc9a2** [comment]
> Hi @vanduc9a2 ,
> 
> Check the next things:
> 
> 1. Try to change the range time in Kibana and check if there are alerts. In your screenshots, you are using `15 minutes` from now. Try with `a day` or some higher.
> 2. Check you have `wazuh-alerts-3.x-*` indices. Go to Kibana Dev Tools section and do the request:
> 
> ```
> GET /_cat/indices
> ```
> 
> 1. If you don't have `wazuh-alerts-3.x-*` indices in Elasticsearch, you could a problem with Logstash or the Logstash - Elasticsearch connection.
>    3.1. Check the Logstash is running. Depending on your service manager:
> 
> * `service logstash status`
> * `systemctl status logstash`
>   3.2. Review the Logstash logs:
> 
> ```
> cat /var/log/logstash/logstash.log
> ```
> 
> 3.3. Check the Logstash configuration is working
> 
> ```
> logstash --config.test_and_exit -f <the config file/folder>
> ```
> 
> Share the Logstash configuration and please obfuscate the sensitive data.

Hi Desvelao! 
Glad to get your help, I'm from Vietnam so my English is very bad, please understand!
My problem followed your solution, still with no success. can you add my facebook (https://www.facebook.com/profile.php?id=100014367636868) for discussion?
![api](https://user-images.githubusercontent.com/60965425/112945872-0b27a400-915f-11eb-8e46-1af4dae2f4ec.png)
![elas](https://user-images.githubusercontent.com/60965425/112945879-0c58d100-915f-11eb-8456-4082c2dd831d.png)
![kibana 1](https://user-images.githubusercontent.com/60965425/112945880-0c58d100-915f-11eb-8330-b90f62a7d801.png)
![logtan](https://user-images.githubusercontent.com/60965425/112945884-0cf16780-915f-11eb-95d9-4c7a3d54110d.png)
![wz ma](https://user-images.githubusercontent.com/60965425/112945885-0d89fe00-915f-11eb-9c5e-df37de4d1e5b.png)

**Comment by Desvelao** [comment]
Hi @vanduc9a2 , 

Thank you for the screenshots. It seems you don't have `wazuh-alerts-3.x-*` indices and all the services are running.

Could you check and share the Logstash logs? Review if there is some type of error.
```
cat /var/log/logstash/logstash.log
```

Check the connection between Logstash and Elasticsearch is working:
```
logstash --config.test_and_exit -f <path to wazuh logstash configuration file>
```

Could you share the Logstash configuration file? Please obfuscate the sensitive data.

**Comment by vanduc9a2** [comment]
Hi @Desvelao ,
![logtask 3](https://user-images.githubusercontent.com/60965425/113236530-3a5d2300-92cf-11eb-9d3b-db5c8d0c9092.png)
you will see, I haven't no file logstash or that directory
