### ISSUE TITLE
[ASK] Integrity Monitoring | There are no results for selected time range. Try another one.

### ISSUE THREAD

**Issue by zeroneshb** [wazuh/wazuh-kibana-app#3112]
Hello guys,
I got this message on Integrity Monitoring Dashboard, "There are no results for selected time range. Try another one."

![Screenshot_2021-03-30_17-09-39](https://user-images.githubusercontent.com/81616028/112974303-82b7fc00-917c-11eb-8b7b-84ae6b79cb4e.png)

I've tried the solution from [this post](https://github.com/wazuh/wazuh-kibana-app/issues/1851), and ran on dev tools this code :
`GET wazuh-alerts-4.x*/_search
{
  "size": 1,
  "query": { 
    "bool": { 
      "must": [
        { "match": { "rule.groups":   "syscheck" }}
      ]
    }
  }
}`

Then this is the reply  I got

`#! Deprecation: this request accesses system indices: [.kibana_1], but in a future major version, direct access to system indices will be prevented by default
{
  "took" : 19,
  "timed_out" : false,
  "_shards" : {
    "total" : 6,
    "successful" : 6,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 410,
      "relation" : "eq"
    },
    "max_score" : 1.6457059,
    "hits" : [
      {
        "_index" : "wazuh-alerts-4.x-2021.03.30",
        "_type" : "_doc",
        "_id" : "MveLgngBO-PDGSE4y9FL",
        "_score" : 1.6457059,
        "_source" : {
          "syscheck" : {
            "uname_after" : "ossecr",
            "mtime_after" : "2021-03-30T09:51:33",
            "inode_before" : 547958,
            "size_after" : "899268",
            "gid_after" : "1000",
            "mtime_before" : "2021-03-30T09:51:23",
            "mode" : "realtime",
            "path" : "/var/ossec/etc/shared/default/merged.mg",
            "sha1_after" : "8d90b6150174a937852c7fcf33fa097f0518c5e6",
            "changed_attributes" : [
              "mtime",
              "inode"
            ],
            "gname_after" : "ossec",
            "uid_after" : "113",
            "perm_after" : "rw-rw----",
            "event" : "modified",
            "md5_after" : "fd756ba04d9c32c8848d4608bec41251",
            "sha256_after" : "052b992f4dcef2c2f735ac66e7a539363240e43db4d615a64d9a34ea41639bd7",
            "inode_after" : 548036
          },
          "agent" : {
            "name" : "ossecserver",
            "id" : "000"
          },
          "manager" : {
            "name" : "ossecserver"
          },
          "rule" : {
            "mail" : false,
            "level" : 7,
            "pci_dss" : [
              "11.5"
            ],
            "hipaa" : [
              "164.312.c.1",
              "164.312.c.2"
            ],
            "tsc" : [
              "PI1.4",
              "PI1.5",
              "CC6.1",
              "CC6.8",
              "CC7.2",
              "CC7.3"
            ],
            "description" : "Integrity checksum changed.",
            "groups" : [
              "ossec",
              "syscheck",
              "syscheck_entry_modified",
              "syscheck_file"
            ],
            "nist_800_53" : [
              "SI.7"
            ],
            "gdpr" : [
              "II_5.1.f"
            ],
            "firedtimes" : 17,
            "mitre" : {
              "technique" : [
                "Stored Data Manipulation"
              ],
              "id" : [
                "T1492"
              ],
              "tactic" : [
                "Impact"
              ]
            },
            "id" : "550",
            "gpg13" : [
              "4.11"
            ]
          },
          "decoder" : {
            "name" : "syscheck_integrity_changed"
          },
          "full_log" : """File '/var/ossec/etc/shared/default/merged.mg' modified
Mode: realtime
Changed attributes: mtime,inode
Old modification time was: '1617097883', now it is '1617097893'
Old inode was: '547958', now it is '548036'
""",
          "input" : {
            "type" : "log"
          },
          "@timestamp" : "2021-03-30T09:51:34.047Z",
          "location" : "syscheck",
          "id" : "1617097894.414539",
          "timestamp" : "2021-03-30T09:51:34.047+0000"
        }
      }
    ]
  }
}
`

So I wondered what I was doing wrong that cause "**There are no results for selected time range. Try another one**." in **Integrity Monitoring Dashboard** ?

Please help me...

Thank you...

**Comment by zeroneshb** [comment]
Update :
I tried to remove any agent, and get this data from the server :
![Screenshot_2021-03-30_17-48-42](https://user-images.githubusercontent.com/81616028/112977502-569e7a00-9180-11eb-850a-3a4c295013c2.png)
So, I think my problem is, I can not retrieve data from the agent in Integrity Monitor.

**Comment by Machi3mfl** [comment]
Hi @zeroneshb, In order to provide some help here.
We need to check out if the FIM configuration is correct.
Please follow this docs and tell me if the problem persist: [File Integrity Configuration](https://documentation.wazuh.com/current/user-manual/capabilities/file-integrity/fim-configuration.html#configuring-reporting-file-and-registry-value-changes)

Looking forward to your reply.
Best regards.

Maximiliano

**Comment by zeroneshb** [comment]
> Hi @zeroneshb, In order to provide some help here.
> We need to check out if the FIM configuration is enabled in Agent and Wazuh manager:
> 
> Manager Configuration -> Go to `Management > Configuration > Integrity Monitoring`
> ![image1](https://user-images.githubusercontent.com/6089438/113011181-ebd54a80-914f-11eb-9f22-a8077c451bcd.png)
> 
> Agent Configuration -> Go to` Agents > Select Agent > Configuration > Integrity Monitoring`
> ![image2](https://user-images.githubusercontent.com/6089438/113011522-42428900-9150-11eb-8158-64dc26e5194f.png)
> 
> If the problem persist please try to configuring again de FIM Module with this doc [File Integrity Configuration](https://documentation.wazuh.com/current/user-manual/capabilities/file-integrity/fim-configuration.html#configuring-reporting-file-and-registry-value-changes)
> 
> Looking forward to your reply.
> Best regards.
> 
> Maximiliano

Thank you for your reply, @Machi3mfl ....
The FIM Module was enabled in Wazuh Manager, but get some errors in Agent section :
![Screenshot_2021-03-31_01-26-11](https://user-images.githubusercontent.com/81616028/113038080-44dcc700-91c0-11eb-9dc3-f9c960720b95.png)

Any suggest? I tried to modify the ossec.conf, but everytime i tried to edit that conf file, then i tried to restart the wazuh-manager service and then restart the elasticsearch service, I got error message said that the elasticsearch service error with timeout. Is it necessary to restart the elasticsearch service too after modify the ossec.conf ?

**Comment by zeroneshb** [comment]
> Hi @zeroneshb, probably you have an error in Agent configuration, restarting the agent is enough.
> To help you, we need to know what is your Agents SO and Wazuh version.
> You can see that in `Agents Table`.
> Please check it and tell me.

Dear @Machi3mfl ,
I am so sorry, I don't get it. Where I can get the Agent SO that you asked?
for now, I just have 2 agents.
![Screenshot_2021-03-31_10-33-02](https://user-images.githubusercontent.com/81616028/113086796-9317b780-920c-11eb-9cb4-ec2db98c1809.png)

Here is my Wazuh Version : 4.1.4 rev. 4150
![Screenshot_2021-03-31_10-32-18](https://user-images.githubusercontent.com/81616028/113086825-a6c31e00-920c-11eb-8b30-83ae4ac9c64f.png)

**Comment by Machi3mfl** [comment]
Thanks for your reply @zeroneshb.
We need to check if you have an error in yours agents configuration.
Please, tell me what you have in agents configuration file and logs file.
You can find the agent configuration in `/var/ossec/etc/ossec.conf` and logs in `/var/ossec/logs/ossec.log`.

**Comment by frankeros** [comment]
Hi @zeroneshb, 
Were you able to solve this issue? In that case please close the issue please.
Or if the error still happening, kindly share the info required above.

Best.

**Comment by frankeros** [comment]
Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our [slack channel](https://wazuh.com/community/join-us-on-slack/) or subscribe to our [mailing list](https://groups.google.com/forum/#!forum/wazuh).
