### ISSUE TITLE
Add help links in the Elastic Header

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3119]
We need to add our help and doc links into the `Help` button of the Elastic top bar.

Here are the 3 possible options in the most liked order taking care of the tech availability of the changes.

This item should be added by the Kibana plugin `core.chrome`.
See [setHelpExtension](https://github.com/elastic/kibana/blob/7.10/src/core/public/chrome/chrome_service.tsx#L452) and [setHelpSupportUrl](https://github.com/elastic/kibana/blob/7.10/src/core/public/chrome/chrome_service.tsx#L458) methods.

1 - The Kibana items are totally removed and only the Wazuh links are showed
![image](https://user-images.githubusercontent.com/26828184/113632798-2fddb900-9642-11eb-8c90-36d4dd47102e.png)

2 - The Kibana items are unfocused by changing their styles to gray, but still available
![image](https://user-images.githubusercontent.com/26828184/113632837-3c621180-9642-11eb-9234-59465fe4a532.png)

3 - The current Kibana items combined with the Wazuh items.
![image](https://user-images.githubusercontent.com/26828184/113633171-da55dc00-9642-11eb-986b-d08a999ef268.png)

**Comment by Desvelao** [comment]
I was investigating, and only option 3 can be done.

I reviewed the Kibana source code and there a prefixed variable that controls if the KIbana help links are rendered. But I could find a way to bypass or set the variable `useDefaultContent`.
`useDefaultContent` is a `defaultProps` set as `true` of the `HeaderHelpMenuUI` ReactJS component : https://github.com/elastic/kibana/blob/v7.10.2/src/core/public/chrome/ui/header/header_help_menu.tsx#L370

Definition of Kibana help links:
https://github.com/elastic/kibana/blob/v7.10.2/src/core/public/chrome/ui/header/header_help_menu.tsx#L188-L230

Render of help links (Kibana and extension help links): https://github.com/elastic/kibana/blob/v7.10.2/src/core/public/chrome/ui/header/header_help_menu.tsx#L345-L349

**Comment by Desvelao** [comment]
### Changes
- Add `outerAngularWrapperRoute: true` property in the AngularJS routes. This does Kibana ignores set the extension links and they could be removed when changing of the route. Check Kibana source code [here](https://github.com/elastic/kibana/blob/v7.10.2/src/plugins/kibana_legacy/public/angular/angular_config.tsx#L344-L362) and [here](https://github.com/elastic/kibana/blob/v7.10.2/src/plugins/kibana_legacy/public/angular/angular_config.tsx#L66-L71)
- Set the extension help links with [setHelpExtension](https://github.com/elastic/kibana/blob/7.10/src/core/public/chrome/chrome_service.tsx#L452) in `renderApp` function. This requires the `coreStart` Kibana service to use `coreStart.http.prepend` method.
- Add Google groups SVG icon
