### ISSUE TITLE
Wazuh-kibana-app 5.0 agent process unification compliant.

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh-kibana-app#3123]
## Description
This issue aims to modify the way in which verifications are made or Wazuh core processes are used in the internal workings of this repository, given the epic: https://github.com/wazuh/wazuh/issues/7981

For this, the following repository occurrences are listed so that they can be analyzed, modified and/or adapted based on the requirement.

Current: execd, logcollector and syscheckd exist in the Wazuh ecosystem.
Expected: unify the old process behavior under the guardianship of wmodulesd. 
Versions in which it should be applied: >= 5.0 

**Occurrences:**
https://github.com/wazuh/wazuh-kibana-app/search?q=execd
https://github.com/wazuh/wazuh-kibana-app/search?q=syscheckd
https://github.com/wazuh/wazuh-kibana-app/blob/34a7422668f5880ee75b0ba9ec0f5cbd91c1fe7e/server/lib/api-request-list.json
https://github.com/wazuh/wazuh-kibana-app/blob/34a7422668f5880ee75b0ba9ec0f5cbd91c1fe7e/common/api-info/endpoints.json

**Comment by Dwordcito** [comment]
Hi @frankeros, I am writing to ask if they could analyze these changes and for what estimated date could they have them?

**Comment by frankeros** [comment]
> Hi @frankeros, I am writing to ask if they could analyze these changes and for what estimated date could they have them?

Hi @Dwordcito we're taking this issue in the next sprint (Apr 5 May 3)

**Comment by Dwordcito** [comment]
@frankeros could this be closed?
