### ISSUE TITLE
The selected index-pattern is not present.

### ISSUE THREAD

**Issue by lukayeh** [wazuh/wazuh-kibana-app#3129]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.0-1   | 7.10     | - |

```rpm -qa | grep opendistro
opendistro-performance-analyzer-1.12.0.0-1.noarch
opendistro-index-management-1.12.0.1-1.noarch
opendistro-alerting-1.12.0.2-1.noarch
opendistro-reports-scheduler-1.12.0.0-1.noarch
opendistroforelasticsearch-1.12.0-1.noarch
opendistro-anomaly-detection-1.12.0.0-1.noarch
opendistro-security-1.12.0.0-0.noarch
opendistro-knn-1.12.0.0-1.noarch
opendistro-job-scheduler-1.12.0.0-1.noarch
opendistro-knnlib-1.12.0.0-1.x86_64
opendistro-sql-1.12.0.0-1.noarch
opendistroforelasticsearch-kibana-1.12.0-1.x86_64
```

**Description**
We have upgraded our Opendistro instance along with Wazuh from 3.13 to 4.1.0 following all the documentation provided, however when accessing the kibana-wazuh plugin we receive the following:

![image](https://user-images.githubusercontent.com/11060558/114082159-d1078200-9883-11eb-86d9-2e1cce5ff3ba.png)

- The selected index-pattern is not present.
- No template found for the selected index-pattern.
- Health Check. Error: requires type and id

Oddly, when switching to the "Private" Tenancy I am able to access the control panel. The issue seems to be with the global tennancy. 

Index patterns do exist:

```--
wazuh-alerts-* (Default)
wazuh-monitoring-*
wazuh-statistics-*
```

Along with others specific to us. 

**Steps to reproduce**

1. Go to 'wazuh' in Opendistro Kibana.

**Screenshots**
[https://i.imgur.com/aCKlxdM.png](url)

**Additional context**
n/a

**Comment by gabiwassan** [comment]
Hello @lukayeh 
Maybe you have generated conflicts in the indexes, you can verify them with the following curl:
`curl "https://<ELASTICSEARCH-IP>:9200/_cat/indices" -u <ELASTIC-USER> -k`
And please send us the results.

**Comment by lukayeh** [comment]
Hi @gabiwassan 

Wazuh specific indices below:

```reen open wazuh-monitoring-2021.03.30                             Itmbey02TmGX91dBzRa3iQ 2 0     15582      0      4mb      4mb
green open wazuh-monitoring-3.x-2020.11.02                         3wA47MafSgeuKZkAp7UXTw 2 0     97006      0   19.7mb   19.7mb
green open wazuh-monitoring-3.x-2020.11.01                         9HSrToUjRwucYcphfwjnhA 2 0     97344      0   19.3mb   19.3mb
green open wazuh-monitoring-3.x-2020.11.04                         dG_0IAOJQ4ipOEQdP69GwQ 2 0     49348      0   11.2mb   11.2mb
green open wazuh-monitoring-3.x-2020.11.03                         Jod7zeTBSmChWv8DeXhOyA 2 0     97344      0   18.9mb   18.9mb
green open wazuh-alerts-4.x-2021.03.31                             fKbMqiJFQCCFm-D3xGLAuQ 3 1     89303      0   93.9mb   46.9mb
green open wazuh-alerts-4.x-2021.03.30                             iK9iBoB_RI2wI_8uphG4uQ 3 1      9123      0   12.7mb    6.3mb
green open wazuh-monitoring-2021.04.01                             A3fAI-ezSFOqdZinhBqI7A 2 0     95488      0   16.9mb   16.9mb
green open wazuh-monitoring-2021.04.03                             fDTA2nstRbmINGJAwzuQbA 2 0    107797      0   20.3mb   20.3mb
green open wazuh-monitoring-2021.04.02                             lGuG5Vv2RiyAVAtYmW0dzQ 2 0     73854      0   13.5mb   13.5mb
green open wazuh-monitoring-2021.04.09                             FyVNGW85QRK2GR7LuYf1dw 2 0     36181      0    8.1mb    8.1mb
green open wazuh-monitoring-2021.04.08                             wWq2_C1lQ0iKcbGrvGsEjA 2 0    107797      0     19mb     19mb
green open wazuh-monitoring-2021.04.05                             SziC1TY-Q9G4hThmGtgYUA 2 0    108543      0   19.1mb   19.1mb
green open wazuh-monitoring-2021.04.04                             9we9WhMgQDGF7ANTCVsT1Q 2 0    107797      0   19.9mb   19.9mb
green open wazuh-monitoring-2021.04.07                             5JogIRWvTPurjBRIxzDX0A 2 0     76465      0     14mb     14mb
green open wazuh-monitoring-2021.04.06                             rWTyL7Z1Ta6t_viJZwRxww 2 0     63830      0   11.8mb   11.8mb
100  147k  100  147k    0     0   272k      0 --:--:-- --:--:-- --:--:--  272k
green open wazuh-statistics-2021.13w                               deVvCgibR9Wew6v6lA_H7g 2 0     22038      0    4.5mb    4.5mb
green open wazuh-statistics-2021.14w                               E2lpB601S66bxaPcPvKxww 2 0     16496      0    3.4mb    3.4mb
green open wazuh-alerts-4.x-2021.04.07                             r3xX1PURTDmVLHWy39b8Sg 3 1     83000      0   88.7mb   44.6mb
green open wazuh-alerts-4.x-2021.04.06                             saEf7LqRQ86Ri9aJqzY1pA 3 1     36328      0     40mb   19.8mb
green open wazuh-alerts-4.x-2021.04.05                             eUQ7PZtaQoyAA0o7wXbp5g 3 1     82465      0   86.9mb   43.4mb
green open wazuh-alerts-4.x-2021.04.04                             srrqguHvSJyRwakTY6HD1Q 3 1     79332      0   81.7mb   40.9mb
green open wazuh-alerts-4.x-2021.04.09                             6cxhpoTxT4WP10-XvJ8bkw 3 1     25749      0   31.9mb   16.2mb
green open wazuh-alerts-4.x-2021.04.08                             C12B1mDlTJiZ75Pn97EKCQ 3 1     84133      0   92.5mb     46mb
green open wazuh-alerts-4.x-2021.04.03                             25uDeW5YQbi2NKCAx1TU1Q 3 1     79354      0   81.5mb   40.7mb
green open wazuh-alerts-4.x-2021.04.02                             bs_lPH_sRvuhfXE_KEBcDg 3 1     81783      0     84mb     42mb
green open wazuh-alerts-4.x-2021.04.01                             0fSqpZc4RvOJvoX_fJoAow 3 1     93633      0   92.6mb   46.3mb```

**Comment by gabiwassan** [comment]
Hi @lukayeh 
Thank you very much for the info.
I give you some considerations, from this [guide](https://documentation.wazuh.com/current/upgrade-guide/elasticsearch-kibana-filebeat/upgrading-open-distro.html#upgrading-kibana) it is possible that you missed doing some steps (especially the one to remove old patterns).

I will ask you if it is possible:
- Ejecute in Kibana Dev Tools: `GET /_cat/templates` and send me the results.
- Check in the Network of your browser the errors of these requests and send them to me.
- Finally and very important that you clear all the cache of your browser.

Best regards!

**Comment by lukayeh** [comment]
Thanks @gabiwassan 

**templates**
```
wazuh            [wazuh-alerts-4.x-*, wazuh-archives-4.x-*]                                                                                                                 01 
metricbeat-7.8.0 [metricbeat-7.8.0-*] 1   
template_1       [fluentd*] 0   
filebeat         [filebeat-*] 0   
wazuh-agent      [wazuh-monitoring-*] 0   
tenant_template  [.kibana_-*_*, .kibana_0*_*, .kibana_1*_*, .kibana_2*_*, .kibana_3*_*, .kibana_4*_*, .kibana_5*_*, .kibana_6*_*, .kibana_7*_*, .kibana_8*_*, .kibana_9*_*] 0   
metricbeat-7.7.0 [metricbeat-7.7.0-*] 1 
```

**Network Tab**
```
wazuh.plugin.js:2 POST https://logs/api/saved_objects/index-pattern/wazuh-alerts-* 409 (Conflict)
GET https://logs/api/saved_objects/index-pattern 404 (Not Found)
```

I have cleared the cache and still receiving the same error!

Thanks,

Luka

**Comment by gabiwassan** [comment]
It is possibly the index .kibana is having conflicts due to aliases, you could try to eliminate it, but VERY IMPORTANT that first, you go to `Kibana/Stack Management/Saved Objects` and export all saved objects except wazuh.
You have to stop Kibana and run: `curl -X DELETE -u <kibana-user>:<kibana-pass>'https://localhost:9200/.kibana'`

I suggest exporting them in little chunks (little ndjson files) to avoid the 'too big file' error from Kibana when you try to re-import the objects.
![image](https://user-images.githubusercontent.com/11060558/114236557-26ad5e80-9958-11eb-99d0-7de7687b185f.png)

**Comment by lukayeh** [comment]
Thanks @gabiwassan I have removed all other index patterns and its working with just the wazuh patterns, so it's clear we have a conflict somewhere, we have three kibana servers behind a NGINX load balancer with a address like `logs.com` when we hit the nodes individually wazuh works but when we hit via the load balancer we get this error:

```3013 - Request failed with status code 401```

This appears to be because its trying to hit `https://logs.com/api/request` and the API is only available on localhost for security purposes can we adjust this?

we'll go through adding index patterns now to find the conflict

Thanks,

**Comment by lukayeh** [comment]
Hi @gabiwassan 

So we did the following

1. Stopped Kibana on all servers in the cluster.
2. Deleted .kiban* indice
3. Started Kibana and wazuh opens as expected.
4. Add our custom index patterns required by product and now we get the conflict.
5. I have tried adding the patterns manually but it seems wazuh doesn't want to play nice with any other index patterns.

![image](https://user-images.githubusercontent.com/12659390/114682523-135b1400-9d07-11eb-8ae0-45eda26366d2.png)

I also see this in the logs: ```{"date":"2021-04-14T08:53:11.453Z","level":"debug","location":"wazuh-elastic:getTemplate","message":"Template is valid: no"}```

but if that was the case i'd expect it not to work before we had the custom index patterns.

**Comment by gabiwassan** [comment]
Hi @lukayeh, 
Thank you very much for all the information, I will try to reproduce the problem to give you an answer.
Regards

**Comment by gabiwassan** [comment]
Hi @lukayeh ,
A possible workaround could be that you manually create the index pattern and remove the **check** from `wazuh.yml` so that the `health-check` does not control it, while we try to reproduce and fix this problem.

**_wazuh.yml_**
Where kibana is installed: `/usr/share/kibana/data/wazuh/config/wazuh.yml`
`checks.pattern: false`

Steps for create index-pattern:
1. Go to `Stack Management / Index patterns  / Create index pattern`
![image](https://user-images.githubusercontent.com/11060558/114888762-e9295500-9ddf-11eb-9a5d-58c7bb086b3f.png)

2. Add your index-pattern name and click _**Next step**_:
![image](https://user-images.githubusercontent.com/11060558/114889166-3efdfd00-9de0-11eb-85c8-af3648798002.png)

3. Select on Time field: `@timestamp`
4. Click on `Show advanced settings` and write your `<your-custom-index-pattern-id>`
![image](https://user-images.githubusercontent.com/11060558/114889338-69e85100-9de0-11eb-9838-bbe8e358c310.png)

In order to reproduce your issue, could you share your list of saved objects including your custom index pattern, please?
You could take it from Kibana / Stack Management / Saved Objects

Best regards!

**Comment by lukayeh** [comment]
Hi @gabiwassan 

Thanks for your response unfortunately the work around didn't work:

![image](https://user-images.githubusercontent.com/12659390/114898910-708bbe00-9e0a-11eb-9353-22f392bab231.png)

If it's okay I'll email you the list of saved objects to avoid sharing them on this public git.

Thanks,

**Comment by gabiwassan** [comment]
Hi @lukayeh,
Could you solve this problem? Did you try to upgrade to the new version 4.1.5?
Best regards.

**Comment by gabiwassan** [comment]
HI, @lukayeh 
It is possible that the wazuh index-pattern problem is due to the fact that you have more than 20 index-patterns, so it may not bring you all of them since it has a default limit of 20, when it tries to get the list of index-patterns, if it cannot find the wazuh-alerts-* it tries to create it and it conflicts because it already exists.
You can check it in this request:
![image](https://user-images.githubusercontent.com/11060558/116607986-0a726100-a909-11eb-9343-bea1d45ee4fc.png)
(this request is made during the _**health-check**_)

Regards

**Comment by lukayeh** [comment]
Hi @gabiwassan thanks for this, is there any way to adjust that limit?

Thanks,

**Comment by gabiwassan** [comment]
Hi @lukayeh,
We are working on a fix with the solution to this problem in `v4.1.5`

Best!

**Comment by gabiwassan** [comment]
Hi @lukayeh,
[Here](https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.1.5_7.10.2-1.zip) I give you a package with the fix to this problem, could you update and check?

Best!

**Comment by lukayeh** [comment]
Hi @gabiwassan 

I have that package version applied already as we upgraded to latest to attempt to resolve this issue however still see the issue you specified:

![image](https://user-images.githubusercontent.com/12659390/119847378-d63b9180-bf02-11eb-975d-9e9d479c3a17.png)

Thanks,

**Comment by lukayeh** [comment]
@gabiwassan did some digging around in the code, and I think only one part was updated whilst wazuh.plugin.js also needs modifying:

![image](https://user-images.githubusercontent.com/12659390/119848739-f91a7580-bf03-11eb-8a7a-588f62b7da08.png)

`"GET","/api/saved_objects/_find?type=index-pattern&search_fields=title"`

Needs to look like:

`_find?type=index-pattern&search_fields=title&per_page=10000`

I think that will fix it...

**Comment by gabiwassan** [comment]
Hi @lukayeh,
Were you able to solve the problem?

**Comment by gabiwassan** [comment]
Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our [slack channel](https://wazuh.com/community/join-us-on-slack/) or subscribe to our [mailing list](https://groups.google.com/forum/#!forum/wazuh).
