### ISSUE TITLE
Inconsitence of timefilter in some app sections

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#3133]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.x   | 7.10.0     | 4016 |

**Description**
The `timestamp` filter used in the Elasticsearch related request is inconsistent.

The filter is different for `Module > Mitre > Framework` and `Module > Mitre Dashboard/Events`. In one case use the value of the search bar and in another case a specific time.

Other section could are related:
- Regulatory compliance modules > Controls
- Security events module > Dashboard > Security events table ( Discover component )
- Flyout which contains alerts (related to Discover > KbnSearchBar component)

We should review the timestamp filters applied in the Elasticsearch related requests for all the app and keep the consistency.

**Screenshots**
![image](https://user-images.githubusercontent.com/34042064/114171904-3ebfb680-9935-11eb-86e5-91faf53fc10a.png)
![image](https://user-images.githubusercontent.com/34042064/114172002-5e56df00-9935-11eb-805e-7c6151ea6c17.png)
![image](https://user-images.githubusercontent.com/34042064/114172414-eccb6080-9935-11eb-8ddb-33a58b82ee98.png)

**Comment by Machi3mfl** [comment]
Hi Team and @Desvelao. 
We are has been checking those functionalities. 
We have two requests, the elastic request called `es` and the `alerts` request generated by wazuh plugin.
In each case, the `time range filters` have syntax differences but testing the request body syntax in kibana dev tools we check that both returns the same results.

Test with `from` and `to` range:
<img width="1439" alt="Screen Shot 2021-04-21 at 16 12 58" src="https://user-images.githubusercontent.com/6089438/115608935-467c4500-a2bd-11eb-94af-69311f4becaa.png">

Test with `gte`,`lte` and `format` range:
<img width="1440" alt="Screen Shot 2021-04-21 at 16 13 20" src="https://user-images.githubusercontent.com/6089438/115609512-0073b100-a2be-11eb-81f4-4725e65ee66a.png">

After having investigated i think is better don't touch this feature. Maybe in the future if some user report a difference between the responses, we can investigate to make a better solution.

Thanks to contact us.
