### ISSUE TITLE
Login out from the app should deprecate the Wazuh API token too. / 'Logout' is invalidating the Wazuh API token. 

### ISSUE THREAD

**Issue by matiasmoreno876** [wazuh/wazuh-kibana-app#3136]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.3 | 7.11.2   | 4104 |

**Description**
Test case: Login out from the app should deprecate the Wazuh API token too. 
Test case: 'Logout' is invalidating the Wazuh API token. 

**Steps to reproduce**

1. Go to Login (user:elastic, pass: elastic)
2. I copy token from the cookies (wz-token)
3. I execute any request with the token (the request is execute correctly)
4. Logout user 
5. I execute any request with the same token.

Expected result: The request should generate an error (the token is invalid) .

Current result: The request is successful

[Link comment](https://github.com/wazuh/wazuh-kibana-app/issues/3034#issuecomment-816759981)

**Comment by frankeros** [comment]
fixed on #3138
