### ISSUE TITLE
Errors keep repeating instead of just 1

### ISSUE THREAD

**Issue by CPAlejandro** [wazuh/wazuh-kibana-app#3139]
When you enter the app with `wazuh-manager` stopped, you find the button to retry the connection with the api, but if you press it and `wazuh-manager` is still down, an error message is generated again identical to the one that already had.
![image (2).png](https://images.zenhubusercontent.com/5fe2fae7f5b0400775dc08b8/81a6a648-e100-4734-82b3-618a53216a03)

**Comment by frankeros** [comment]
fixed on #3145
