### ISSUE TITLE
Broken Wazuh logo with custom server.basePath 

### ISSUE THREAD

**Issue by VictorMorenoJimenez** [wazuh/wazuh-kibana-app#3142]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.4   | 7.10.0     | 4105 |

**Description**
After changing `server.basePath` in `kibana.yml` configuration file, everything works as expected except from the Wazuh logo in Kibana app.

**Steps to reproduce**

In this Slack thread you'll find the steps to reproduce the error: https://wazuh.slack.com/archives/C0A933R8E/p1618087573130700

**Screenshots**
Logo is not found:
![image](https://user-images.githubusercontent.com/44369304/114517385-95cbd100-9c3e-11eb-80d0-1d27094a3229.png)

![image](https://user-images.githubusercontent.com/44369304/114517372-92384a00-9c3e-11eb-8ffb-bf1bdd820f89.png)

Greetings,
Víctor.

**Comment by ar0dd** [comment]
Hey folks.

I think there is another one. Would you like me to open another ticket?

![image](https://user-images.githubusercontent.com/42455358/115068289-11888080-9ec0-11eb-932b-8f4b07e110dd.png)
