### ISSUE TITLE
wazuh-monitoring index management improvements

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-kibana-app#3147]
Hello team,

Wazuh monitoring index settings should be changed to increase performance, adapting to use cases valid for the majority of users.

Specifically I refer to:
- wazuh.monitoring.creation
- wazuh.monitoring.shards

A good default value for `wazuh.monitoring.shards` should be 1 because unless the environment is huge, it will lead to really small shards.

Moreover, `wazuh.monitoring.creation` being a daily process multiplies the number of shards in the cluster, adding even more overhead.

Regards,

Javier.

**Comment by Desvelao** [comment]
Hi, I was investigating about the index size using this https://www.elastic.co/guide/en/elasticsearch/reference/current/size-your-shards.html, and we will change the `wazuh.monitoring.creation` setting from daily (`d`) to weekly (`w`).

@havidarou , do you think the suggested change in `wazuh.monitoring.shards` setting from `2` to `1` is required?
