### ISSUE TITLE
Permissions issue for modifying rules and decoders on 4.2

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-kibana-app#3148]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.2   | 7.10.2     | 4201 |

**Description**
Editing rules from the WUI is forbidden for the admin user.

**Steps to reproduce**

With a fresh installation and the `admin` user go to Management > Rules or decoders and see that the options to Manage Rule files or adding a new rule file is greyed out. Opening the custom rule or decoder file will work but will not allow the user to save.

Using `run_as` results in the same behavior.

**Screenshots**
![image](https://user-images.githubusercontent.com/36071202/114611935-cee95d00-9ca1-11eb-8da9-fcbac76c3b73.png)

**Comment by frankeros** [comment]
This was temporally fixed on #3140, but it needs to be refactored to support the Wazuh API actions resources, that currently, these have some issues reported in https://github.com/wazuh/wazuh/issues/8193
We're using this issue to follow the refactor.
Thanks
