### ISSUE TITLE
Wrong Kibana version in the Welcome message in Settings > About

### ISSUE THREAD

**Issue by s-ocando** [wazuh/wazuh-kibana-app#3153]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.2.0  | 7.10.2  | 4201 |

**Description**
Wrong Kibana version in `Settings > About`. As can be seen in the screenshot, the message says  `Welcome to the Wazuh app for Kibana 7.10.0` and it should say Kibana `7.10.2`. 

**Screenshots**
![image](https://user-images.githubusercontent.com/61882981/114670066-e99fee00-9d02-11eb-9dfb-f430f159181d.png)

**Comment by eze9252** [comment]
I tested and I see it well:

![Captura de pantalla de 2021-04-15 12-21-10](https://user-images.githubusercontent.com/36004787/114894760-4a075c00-9de5-11eb-889d-131bd41d583f.png)

Maybe the problem is the cache browser, clean cache and try again.

**Comment by eze9252** [comment]
I couldn't reproduce this problem, maybe the problem was an incorrect configuration that was already solved in the latest version.
