### ISSUE TITLE
Agent Install Command for macOS Incorrect

### ISSUE THREAD

**Issue by madhatta-ct** [wazuh/wazuh-kibana-app#3156]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.0.4  | 7.9.3     | 4016 |

**Description**
When selecting a group, the command string generated by the Wazuh app for macOS installation is incorrect, it generated the variable " WAZUH_AGENT_GROUP='GroupName' but the correct syntax should be WAZUH_AGENT_GROUP 'GroupName' without the =

**Steps to reproduce**

1. Go to 'Wazuh > Agents > Deploy New Agent
2. Click on 'MacOS'
3. Select a group
4. You see the the command generated is "curl -so wazuh-agent.pkg https://packages.wazuh.com/4.x/macos/wazuh-agent-4.0.4-1.pkg && sudo launchctl setenv WAZUH_MANAGER='10.0.0.72' WAZUH_REGISTRATION_PASSWORD='************' WAZUH_AGENT_GROUP='default' sudo installer -pkg ./wazuh-agent.pkg -target /" 

**Additional context**
I also have a dev box on 4.1 and it exhibits the same syntax

**Comment by frankeros** [comment]
Hi @madhatta-ct 
this issue is related to #3058 and it was resolved in #3066.

I'm closing this issue. If you have any questions, you can also use our [slack channel](https://wazuh.com/community/join-us-on-slack/) or subscribe to our [mailing list](https://groups.google.com/forum/#!forum/wazuh).

**Comment by madhatta-ct** [comment]
My pleasure!
Thanks a stack!
