### ISSUE TITLE
Error 404 using NGINX

### ISSUE THREAD

**Issue by pablomarga** [wazuh/wazuh-kibana-app#3157]
When you configure nginx to use the option `server.basePath` of kibana for changing the url after the health check there is a 404 error 

https://user-images.githubusercontent.com/46006326/114698118-ffbba780-9d1e-11eb-9a18-b146b577f1c7.mp4

**Comment by Desvelao** [comment]
Clicking on the button from breadcrumb does the same error:
![image](https://user-images.githubusercontent.com/34042064/114724384-c7769200-9d3b-11eb-94c8-15c2932bb66b.png)
