### ISSUE TITLE
Hide/Block the Wazuh app depending by role or config

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3164]
**Describe the solution you'd like**
Certain environments need to exclude the Wazuh app access for certain roles, spaces, or tenants. 
The proper approach should be to find a way to deny access through Elastic (ODFE / X-Pack) policies.

**Describe alternatives you've considered**
An alternative way could be through the Wazuh app (code) with some policies or configs to deny the access.

**Additional context**
The solution should take care of the indices, patterns, templates, etc, too.

**Comment by frankeros** [comment]
Related to #1601

**Comment by Desvelao** [comment]
I was investigating a little bit and I found as the `Canvas` Kibana plugin could be added to features when using X-Pack. This should be tried if it works and adds it to the app.
https://github.com/elastic/kibana/blob/v7.11.2/x-pack/plugins/canvas/server/plugin.ts#L42-L69
