### ISSUE TITLE
Add confirmation message when close forms without saving

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3183]
**Describe the solution you'd like**
In order to avoid accidentally closing forms without saving, they should open a confirmation message, with the options for cancel o close.

Some sections are:
- Security: 
  - [x] Users (create / edit)
  - [x] Policies (create / edit)
  - [x] Roles (create / edit)
  - [x] Role Mapping (create / edit)
- Managet: 
  - [x] Rules (editor)
  - [x] Decoders (editor)
  - [x] Groups Config (editor)
  - [x] Cluster Condig (editor)
  
  TODO: Add all forms or editors to be changed.
 

![image](https://user-images.githubusercontent.com/26828184/115263412-cbbff800-a10b-11eb-9f48-605ab88fd5a7.png)

**Comment by pablomarga** [comment]
Created modal when creating role mapping, studying the way of refactor so I could reuse the component

**Comment by pablomarga** [comment]
Changing logic so that the modal is controlled directly inside the child component due to it caused the modal to open once the flyout was closed, this happened in all security sections

**Comment by pablomarga** [comment]
Done Users, Roles and Role Mapping, also edit of policies. Creating a component of create policy because now it is created in the parent component so the state is saved even after closing the flyout.
