### ISSUE TITLE
Inability to change password of non-reserved Wazuh API user in Wazuh web interface

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh-kibana-app#3185]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.4   | 7.10.0 with OpenDistro | 4105 |

Passwords for Wazuh API users cannot be changed in Wazuh web interface, unless you game the web interface.
For a newly created Wazuh API user, if you change its password in the web interface, the **Accept** button remains greyed out and you cannot save the change.  However, if you add/remove a role from such a user, in addition to changing the password, then the **Accept** is un-greyed and all changes can be saved.  
This appears to be a bug in the web form's ability to detect if changes have been made so that the **Accept** button gets un-greyed only once a change has been entered in.

**Comment by frankeros** [comment]
Hi @branchnetconsulting 
this issue was solved in this PR #3080, and it will be included for the release v4.2.0-7.10.2 that will be published very soon.
Thanks for reporting it.

I'm clossing it.
