### ISSUE TITLE
Pivoting to index patterns besides wazuh-alerts-* broken in Wazuh web interface

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh-kibana-app#3186]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.4   | 7.10.0 with OpenDistro | 4105 |

Cannot pivot to other legitimate index patterns in web app, like `wazuh-archives-*`.  It always acts like it accepts the click but snaps back to `wazuh-alerts-*` every time.
In plain Discover mode I can move between the index patterns just fine.
This bug emerged sometime after Wazuh 4.0.4.

I've reproduced this on multiple Wazuh managersr and web browsers.

**Comment by branchnetconsulting** [comment]
I'm not talking about the intermittently missing index-pattern drop-down menu issue present in 4.0.X.  You can always work around that with a shut-ctrl-R in the web browser.  In this issue, when I click on the **WAZUH** link, the Wazuh web app shows me the dropdown with the proper index patterns listed, but if I click on anything but wazuh-alerts-* is still acts exactly like I had chosen **wazuh-alerts-***

**Comment by frankeros** [comment]
Yes, you are right it's a bug. 
Thank you very much for reporting it.
