### ISSUE TITLE
Ruleset test tool only provides output when an alert will be generated

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-kibana-app#3193]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.2.0   | 7.10.0     | 4201-7 |

**Description**
The Ruleset test tool now only provides valuable output when an event generates an alert.
The tool is intended for use specifically when creating rules for new types of logs.
If the final match is a level 0 rule it should indicate which was the rule that matched.
If it doesn't match a rule but does match a decoder and fields are extracted this information should be provided.

**Steps to reproduce**

In Ruleset Test try any of the following logs:
- Apr 23 14:24:23 localhost sshd[21490]: Connection closed
- generic error message

They provide the `No result found for: ` answer followed by the log.

The API Response provides the desired output:
```
{
	"output": {
		"timestamp": "2021-04-23T14:58:20.687+0000",
		"rule": {
			"description": "sshd: ssh connection closed.",
			"id": "5722",
			"firedtimes": 1,
			"mail": false,
			"groups": [
				"syslog",
				"sshd"
			],
			"pci_dss": [
				"10.2.5"
			],
			"gdpr": [
				"IV_32.2"
			],
			"hipaa": [
				"164.312.b"
			],
			"nist_800_53": [
				"AU.14",
				"AC.7"
			],
			"tsc": [
				"CC6.8",
				"CC7.2",
				"CC7.3"
			],
			"level": 0
		},
		"agent": {
			"id": "000",
			"name": "dev420odfe"
		},
		"manager": {
			"name": "dev420odfe"
		},
		"id": "1619189900.628601",
		"full_log": "Apr 23 14:24:23 localhost sshd[21490]: Connection closed",
		"predecoder": {
			"program_name": "sshd",
			"timestamp": "Apr 23 14:24:23",
			"hostname": "localhost"
		},
		"decoder": {
			"name": "sshd"
		},
		"location": "logtest"
	}
}
```

```
{
	"output": {
		"timestamp": "2021-04-23T14:59:21.075+0000",
		"rule": {
			"level": 2,
			"description": "Unknown problem somewhere in the system.",
			"id": "1002",
			"firedtimes": 1,
			"mail": false,
			"groups": [
				"syslog",
				"errors"
			],
			"gpg13": [
				"4.3"
			]
		},
		"agent": {
			"id": "000",
			"name": "dev420odfe"
		},
		"manager": {
			"name": "dev420odfe"
		},
		"id": "1619189961.628601",
		"full_log": "generic error message",
		"decoder": {},
		"location": "logtest"
	}
}
```

**Comment by jctello** [comment]
When creating decoders it is very useful to be able to first test decoders before creating any matching rules.
Currently testing a log that matches a decoder without matching a rule will again return the `No result found` message.
For example:
```
Apr 28 13:43:51 localhost local_decoder_example: test
```
Should result in: 
```
**Phase 1: Completed pre-decoding.
        full event: 'Apr 28 13:43:51 localhost local_decoder_example: test'
        timestamp: 'Apr 28 13:43:51'
        hostname: 'localhost'
        program_name: 'local_decoder_example'

**Phase 2: Completed decoding.
        name: 'local_decoder_example'
```

Instead it returns:
```
No result found for:  Apr 28 13:43:51 localhost local_decoder_example: test 
```
This is testing with the app compiled at https://github.com/wazuh/wazuh-kibana-app/commit/87fba0138c087f66f7d4d23dd6fd6a8faefef722

**Comment by frankeros** [comment]
we move the comment to a new issue https://github.com/wazuh/wazuh-kibana-app/issues/3348
