### ISSUE TITLE
Require the permission - manager:read_file (file:path:/etc/ossec.conf)

### ISSUE THREAD

**Issue by saidhfm** [wazuh/wazuh-kibana-app#3195]
I am getting this error in the configuration tab of Wazuh GUI

Require the permission - manager:read_file (file:path:/etc/ossec.conf)
<img width="1091" alt="Screenshot 2021-04-26 at 11 11 59 PM" src="https://user-images.githubusercontent.com/40364562/116126944-ddddff80-a6e4-11eb-9674-b53c49ab8dfd.png">

**Comment by pablomarga** [comment]
Hi @saidhfm could you tell me which Wazuh version and revision do you have? You can check it on Settings > About

**Comment by saidhfm** [comment]
wazuh v4.1.0

**Comment by pablomarga** [comment]
It was a known issue for 4.1.0. It was fixed in Wazuh 4.1.5 so if you upgrade to this version this should not happen.

**Comment by frankeros** [comment]
Hi @saidhfm, could you solve this problem?

**Comment by saidhfm** [comment]
Yes problem is solved.i gave updated the version

Thanks
