### ISSUE TITLE
Error displaying the SCA panel on allowed agents

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh-kibana-app#3201]
**Wazuh version: 4.1.5**

Hi team,

We have been testing what is described in this community question. We have created a user that has been mapped with kibana_user. After that, we have followed all the user's steps in our environment. Then we have logged in with the user user1 and we have found that the SCA panel is not displayed correctly even having permissions to do so.

### Create policy:
![create_policy](https://user-images.githubusercontent.com/15522808/116572262-1f042880-a90c-11eb-8d98-8fa663ae07fc.png)

### Create role:
![create_role](https://user-images.githubusercontent.com/15522808/116572271-20cdec00-a90c-11eb-89a7-78f0a5f7ee39.png)

### Create role mapping:
![create_role_mapping](https://user-images.githubusercontent.com/15522808/116572282-2297af80-a90c-11eb-95d7-9692c1d58a49.png)

### Agents in group1:
![dev_tools_admin_check_group](https://user-images.githubusercontent.com/15522808/116572452-4529c880-a90c-11eb-93a1-c8ae209d7797.png)

### Agents not belonging to group1:
![dev_tools_admin_check_agents](https://user-images.githubusercontent.com/15522808/116572603-68ed0e80-a90c-11eb-91b7-3567d5229e49.png)

### User1 agent 004 main panel:
![user1_main_panel](https://user-images.githubusercontent.com/15522808/116572674-799d8480-a90c-11eb-9442-ca1cc3924574.png)

### User1 agent 004 SCA panel:
![user1_agent004_sca_panel](https://user-images.githubusercontent.com/15522808/116572904-a356ab80-a90c-11eb-9968-6ff34a584a3f.png)

### User1 permissions:
![user1_permissions](https://user-images.githubusercontent.com/15522808/116572934-aa7db980-a90c-11eb-99e4-47df5a18d9cd.png)

### Dev-tools with user1:
![dev_tools_sca_004](https://user-images.githubusercontent.com/15522808/116573007-bb2e2f80-a90c-11eb-8cc4-35beddcaf129.png)

![dev_tools_sca_005](https://user-images.githubusercontent.com/15522808/116573022-be292000-a90c-11eb-901e-28cbb09284e7.png)

Agent 005 does not belong to group 1.

**Comment by frankeros** [comment]
Hi @AdriiiPRodri 
This issue is related to #3180. And was solved in #3181.

This will be released in the `4.2.0` version
Thanks for reporting it.

I'm closing this issue.

**Comment by snaow** [comment]
Related email thread: https://groups.google.com/u/1/g/wazuh/c/_6vGNC_DAqk
