### ISSUE TITLE
Error exporting CSV report in Discover

### ISSUE THREAD

**Issue by psybustermk2** [wazuh/wazuh-kibana-app#3205]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.4   | 7.10.0     | 4105 |

**Description**
"Error downloading report" when trying to download CSV from Discover.

**Steps to reproduce**

1. Go to 'Discover'
2. Add filter 'rule.groups: vulnerability-detector'
3. Add 'agent.name', 'data.vulnerability.package.name', 'data.vulnerability.package.version', 'data.vulnerability.cve', and 'data.vulnerability.severity'.
4. Click 'Reporting'
5. Click 'Generate CSV'
6. See 'Download error'

**Screenshots**
![image](https://user-images.githubusercontent.com/1694810/116783956-35ed7b00-aac4-11eb-9449-976ff7a50e22.png)

**Additional context**
Request payload
`
{"query_url":"/app/discover#/view/5eb161a0-aa79-11eb-9035-3b02b8e65a6b?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-30T12:33:45.754Z',to:'2021-05-01T12:33:45.754Z'))&_a=(columns:!(agent.name,data.vulnerability.package.name,data.vulnerability.package.version,data.vulnerability.cve,data.vulnerability.severity),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'wazuh-alerts-*',key:rule.groups,negate:!f,params:(query:vulnerability-detector),type:phrase),query:(match_phrase:(rule.groups:vulnerability-detector)))),index:'wazuh-alerts-*',interval:auto,query:(language:kuery,query:''),sort:!())","time_from":1619786025751,"time_to":1619872425752,"report_definition":{"report_params":{"report_name":"On_demand_report","report_source":"Saved search","description":"In-context report download","core_params":{"base_url":"/app/discover#/view/5eb161a0-aa79-11eb-9035-3b02b8e65a6b","report_format":"csv","time_duration":"PT24H","saved_search_id":"5eb161a0-aa79-11eb-9035-3b02b8e65a6b"}},"delivery":{"delivery_type":"Kibana user","delivery_params":{"kibana_recipients":[]}},"trigger":{"trigger_type":"On demand"}}}
`

Response
statusCode | 500
-- | --
error | "Internal Server Error"
message | "Cannot read property 'settings' of undefined"

Kibana logs
`
{"type":"log","@timestamp":"2021-05-01T13:27:10Z","tags":["error","plugins","opendistroReportsKibana"],"pid":16649,"message":"Failed to generate report: TypeError: Cannot read property 'settings' of undefined"}
{"type":"log","@timestamp":"2021-05-01T13:27:10Z","tags":["error","plugins","opendistroReportsKibana"],"pid":16649,"message":"TypeError: Cannot read property 'settings' of undefined\n    at getMaxResultSize (/usr/share/kibana/plugins/opendistroReportsKibana/server/routes/utils/savedSearchReportHelper.ts:163:35)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
{"type":"error","@timestamp":"2021-05-01T13:27:10Z","tags":[],"pid":16649,"level":"error","error":{"message":"Internal Server Error","name":"Error","stack":"Error: Internal Server Error\n    at HapiResponseAdapter.toError (/usr/share/kibana/src/core/server/http/router/response_adapter.js:132:19)\n    at HapiResponseAdapter.toHapiResponse (/usr/share/kibana/src/core/server/http/router/response_adapter.js:86:19)\n    at HapiResponseAdapter.handle (/usr/share/kibana/src/core/server/http/router/response_adapter.js:81:17)\n    at Router.handle (/usr/share/kibana/src/core/server/http/router/router.js:164:34)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":"?timezone=Asia/Singapore","query":{"timezone":"Asia/Singapore"},"pathname":"/api/reporting/generateReport","path":"/api/reporting/generateReport?timezone=Asia/Singapore","href":"/api/reporting/generateReport?timezone=Asia/Singapore"},"message":"Internal Server Error"}
{"type":"response","@timestamp":"2021-05-01T13:27:10Z","tags":[],"pid":16649,"method":"post","statusCode":500,"req":{"url":"/api/reporting/generateReport?timezone=Asia%2FSingapore","method":"post","headers":{"host":"xx.xx.xx.xx","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0","accept":"*/*","accept-language":"en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7,zh-TW;q=0.6","accept-encoding":"gzip, deflate, br","referer":"https://xx.xx.xx.xx/app/discover","content-type":"application/json","kbn-version":"7.10.0","pragma":"no-cache","origin":"https://xx.xx.xx.xx","content-length":"1151","connection":"keep-alive"},"remoteAddress":"yy.yy.yy.yy","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0","referer":"https://xx.xx.xx.xx/app/discover"},"res":{"statusCode":500,"responseTime":141,"contentLength":9},"message":"POST /api/reporting/generateReport?timezone=Asia%2FSingapore 500 141ms - 9.0B"}
`

**Comment by MauGaP** [comment]
Hi! how are you? Sorry for the late response.

I created a new environment using Open Distro, and I'm trying to reproduce this issue.

I'm asuming the visualization on Kibana looks ok, but your problem is only the export. So it should't be needed, but, can you share us the elastic logs? so we can desestimate that?.

Any other information you can share us about the environment you have could point us where this can come from, I.E Kibana version or Open Distro if you use it.

**Comment by frankeros** [comment]
Hi @psybustermk2, this is a known issue of Opendistro 1.12.
Were you able to solve the problem?

**Comment by frankeros** [comment]
Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our [slack channel](https://wazuh.com/community/join-us-on-slack/) or subscribe to our [mailing list](https://groups.google.com/forum/#!forum/wazuh).
