### ISSUE TITLE
WUI error logs

### ISSUE THREAD

**Issue by SitoRBJ** [wazuh/wazuh-kibana-app#3209]
**Describe the solution you'd like**

Without even having started using the product (no agents are registered), the APP logs show error messages:

![image](https://user-images.githubusercontent.com/8913336/116877497-52052f80-ac1e-11eb-8d4e-0dd497cc3354.png)

The Wazuh OVA also has the error logs:

![image](https://user-images.githubusercontent.com/8913336/117435191-dcef6e00-af2d-11eb-9193-f5568740ea85.png)

**Describe alternatives you've considered**

Clean log.

**Comment by CPAlejandro** [comment]
**Today's feedback**
Found all the possible errors that are generated with ODFE, X-Pack and without security, solved the extensions error and improving the code to have more explicit error logs and avoid those errors at the beginning

**Comment by CPAlejandro** [comment]
**Today's feedback**
Found the problem that generated the `response error`, this is how elasticsearch returns them, working on giving a message with which you can know exactly what is a permission failure and checking that the same does not happen in similar calls

**Comment by CPAlejandro** [comment]
**Today's feedback**
Created a high order function to be able to treat try catches in the same way, if they are of the same type.
Testing it for ODFE, X-Pack and non-security environments
