### ISSUE TITLE
Too long installation.

### ISSUE THREAD

**Issue by gagantous** [wazuh/wazuh-kibana-app#321]
I have tried install Wazuh app for kibana. In the documentatin quote said.

> The Kibana plugin installation process may take several minutes. Please wait patiently

I thought at that moment "Okay i think that's okay. i just need to wait "several minutes" "
But 2 hours later, the installation didnt complete yet......
is this a normal behaviour ?
only appear this text.

> Attempting to transfer from https://packages.wazuh.com/wazuhapp/wazuhapp-3.2.1_6.2.2.zip
> Transferring 4058679 bytes....................
> Transfer complete
> Retrieving metadata from plugin archive
> Extracting plugin archive
> Extraction complete
> Optimizing and caching browser bundles...

**Comment by JuanjiJG** [comment]
Hello @gagantous,

Definitely, that is not a normal behaviour when installing the Wazuh App.

Did you execute the command to **increase the default Node.js heap memory limit**? In the past, we've experienced some issues related to the installation process due to this, and it's very important to configure it prior to the installation:
`export NODE_OPTIONS="--max-old-space-size=3072"`

In addition to that, could you please tell me what are your **system hardware specifications**? Or if you're using a virtual machine, the current configuration applied to it.

Thanks for your patience.

Regards,
Juanjo

**Comment by gagantous** [comment]
Hi @JuanjiJG 

Thanks for your replies.  After a few minutes after i posted my question on this thread, installation succed.

But i got an error in my `elasticsearch` and `logstash` services. I just restarts both services and it works just fine

**Elasticsearch services**
```
root@debian:/home/debian# service elasticsearch status
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled)
   Active: failed (Result: exit-code) since Mon 2018-03-19 18:01:55 WITA; 15min ago
     Docs: http://www.elastic.co
  Process: 2701 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -p ${PID_DIR}/elasticsearch.pid --quiet (code=exited, status=1/FAILURE)
 Main PID: 2701 (code=exited, status=1/FAILURE)

Mar 19 15:20:28 debian systemd[1]: Started Elasticsearch.
Mar 19 18:01:55 debian systemd[1]: elasticsearch.service: main process exited, code=exited, status=1/FAILURE
Mar 19 18:01:55 debian systemd[1]: Unit elasticsearch.service entered failed state.
```
**Logstash Services**
```
root@debian:/home/debian# service logstash status
● logstash.service - logstash
   Loaded: loaded (/etc/systemd/system/logstash.service; enabled)
   Active: failed (Result: start-limit) since Mon 2018-03-19 16:16:02 WITA; 2h 29min ago
  Process: 3130 ExecStart=/usr/share/logstash/bin/logstash --path.settings /etc/logstash (code=exited, status=1/FAILURE)
 Main PID: 3130 (code=exited, status=1/FAILURE)

Mar 19 16:16:02 debian systemd[1]: logstash.service: main process exited, code=exited, status=1/FAILURE
Mar 19 16:16:02 debian systemd[1]: Unit logstash.service entered failed state.
Mar 19 16:16:02 debian systemd[1]: logstash.service holdoff time over, scheduling restart.
Mar 19 16:16:02 debian systemd[1]: Stopping logstash...
Mar 19 16:16:02 debian systemd[1]: Starting logstash...
Mar 19 16:16:02 debian systemd[1]: logstash.service start request repeated too quickly, refusing to start.
Mar 19 16:16:02 debian systemd[1]: Failed to start logstash.
Mar 19 16:16:02 debian systemd[1]: Unit logstash.service entered failed state.

```

I used VM for my setup. 

OS : Debian 8
Base memory : 2048MB

I did that command `export NODE_OPTIONS="--max-old-space-size=3072"`, but i dont know if that command working or not...

**Comment by JuanjiJG** [comment]
Hello again @gagantous,

I'd suggest you increase your VM to, **at least, 4GB of RAM**. In our internal tests and evaluations, we've experienced a minimum stable behaviour of the Elastic Stack with this amount of RAM.

The Elastic team recommends even higher amounts of RAM, but for small deployment or testing purposes, you can go with 4GB of RAM.

You can read more information [here ](https://www.elastic.co/guide/en/elasticsearch/guide/master/hardware.html)and [here](https://www.elastic.co/guide/en/elasticsearch/guide/master/heap-sizing.html), from the Elastic Stack documentation.

Let me know if you increase your VM's RAM and you're still running into problems.

Thanks for your patience.

Best regards,
Juanjo

**Comment by gagantous** [comment]
Hello @JuanjiJG 

I have increased my VM to at least 4GB of RAM. and it works great (y) 

Thank you for your guide. I really appreciate it (y)

**Comment by JuanjiJG** [comment]
I'm glad you solved your problem @gagantous !

Feel free to post a new issue if you still have questions or problems about Wazuh. We'll be happy to help you.

Regards,
Juanjo
