### ISSUE TITLE
MacOS agent installation command fails

### ISSUE THREAD

**Issue by SitoRBJ** [wazuh/wazuh-kibana-app#3211]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.5   | 7.10.2    | Cloud 4106 |

**Description**

macOS agent installation command has typo:

```bash
curl -so wazuh-agent.pkg https://packages.wazuh.com/4.x/macos/wazuh-agent-4.1.5-1.pkg && sudo launchctl setenv WAZUH_MANAGER '4e2ca3c9471b.devcloud.wazuh.com' WAZUH_REGISTRATION_PASSWORD='pass' && sudo installer -pkg ./wazuh-agent.pkg -target /
```
```bash
WAZUH_REGISTRATION_PASSWORD='pass' 
```
Equal char is not necessary

- Output

```bash
curl -so wazuh-agent.pkg https://packages.wazuh.com/4.x/macos/wazuh-agent-4.1.5-1.pkg && sudo launchctl setenv WAZUH_MANAGER '4e2ca3c9471b.devcloud.wazuh.com' WAZUH_REGISTRATION_PASSWORD='pass' && sudo installer -pkg ./wazuh-agent.pkg -target /
Usage: launchctl setenv <<key> <value>, ...>
```

**Steps to reproduce**

1. Go to 'WUI agents section'
2. Click on 'Deploy a new agent'
3. Click on 'MacOS'
4. See error in 'Install and enroll the agent'

**Screenshots**

![image](https://user-images.githubusercontent.com/8913336/116878770-19665580-ac20-11eb-9a1e-8c5725dfab1e.png)

**Comment by frankeros** [comment]
It was solved in https://github.com/wazuh/wazuh-kibana-app/pull/3171

I'm closing this issue.
