### ISSUE TITLE
 Testing 4.2.0 compatibility 7.12.1

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3213]
| Wazuh | Elastic |
| ----- | ------- | 
| 4.2.0   | 7.12.1     | 

**Description**
Testing compatibility with Kibana 7.12.1

Test with browsers:
- Chrome
- Firefox
- Safari

Test with the theme:
- Light
- Dark

Checks:
- [x] General checks 
- [x] X-Pack checks

**Comment by CPAlejandro** [comment]
Created the following issues with problems found:

- [Wazuh appear two times in the main bar 4.2-7.12.1](https://github.com/wazuh/wazuh-kibana-app/issues/3218)

- [An error is generated when inserting, removing or pinning a filter](https://github.com/wazuh/wazuh-kibana-app/issues/3219)

**Comment by CPAlejandro** [comment]
- [Visualizations error when generating a pdf in dark mode] (https://github.com/wazuh/wazuh-kibana-app/issues/3224)

- [Bug generating a PDF in an agent config] (https://github.com/wazuh/wazuh-kibana-app/issues/3225)

**Comment by matiasmoreno876** [comment]
**Bugs found today:**

- https://github.com/wazuh/wazuh-kibana-app/issues/3229
