### ISSUE TITLE
Research and propouse of the new desing of the MITRE section.

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3214]
| EPIC |
| --- |
| #3202 |

**Description**

Hi team, we need to redesign the current `MITRE ATT&CK - Framework` section to allow the users to explore all resources from the MITRE DB taken care of the UX.

There is a WIP [prototype](https://www.figma.com/file/SODejd1Uq8cO4yBGS54666/Wazuh-App---WIP?node-id=199%3A20945) from UX we can take as the start point of the redesign. 

Acceptance Criteria:
- As user I want to be able to explore all the data picking between related resources in the same section (without refresh).
- The objective of the section should be displayed **ONLY** (no related to Wazuh) MITRE information.
- As user I want to be able to search a key word for all the DB.
- As user I want to be able to search a key word for a specific resource.

Tasks:
- [x] Research for current solutions for this feature.
- [x] Design some solutions propose and validate them.
- [x] Mockup the correspondings views and issues.

<details>
<summary>Current section design</summary>
<p>

![image](https://user-images.githubusercontent.com/26828184/116930120-b8497c80-ac35-11eb-9046-f2e60af1a61d.png)

![image](https://user-images.githubusercontent.com/26828184/116930089-b089d800-ac35-11eb-9ff9-ffdd878ed008.png)
</p>
</details>

**Comment by gabiwassan** [comment]
![Uploading image.png…]()

**Comment by frankeros** [comment]
This proposal was approved, we are moving on developing this new section.
