### ISSUE TITLE
An error is generated when inserting, removing or pinning a filter

### ISSUE THREAD

**Issue by CPAlejandro** [wazuh/wazuh-kibana-app#3219]
An error is generated when inserting, removing or pinning a filter or when you enter to a SCA section, as you can see here:
![image.png](https://images.zenhubusercontent.com/5fe2fae7f5b0400775dc08b8/5fa86c01-ff2e-45d8-ba2d-6cfb6ca637f1)

**Comment by mpRegalado** [comment]
Was able to replicate it in google chrome but not in firefox, investigating what causes it.

**Comment by mpRegalado** [comment]
The moment the loading animation finishes, the container for the graph gets a height of 16px. Forcing a parent container of that height in a native kibana visualization prompts the same response, so we should inspect the loading transition and and find when does the container go from 16px to full height
