### ISSUE TITLE
Replace empty registry value name in FIM inventory

### ISSUE THREAD

**Issue by Molter73** [wazuh/wazuh-kibana-app#3220]
**Description**
We've been working on wazuh/wazuh#8253.

Due to how Windows works, whenever a registry key is created a default value inside of it is also created which has an empty string as its name and is visualized as `(Default)` in regedit. In order to solve the false positive alerts we need to store the default value's name as an empty string on the agent DB, since Windows allows you to create a value named `(Default)` and would collide as it is doing with the name `@`. This causes the UI to show an empty field and might look a little weird:

![default_value](https://user-images.githubusercontent.com/20206636/117016886-6f57fd80-acf3-11eb-81cf-87db2c18d9f8.png)

We have considered changing the name through a view on the manager's DB, but that could create an increased load on every query done on the FIM inventory. Similarly, we thought about changing it in the API but since it only does a simple SQL query, adding additional logic could prove challenging. Also, neither of these solutions would allow the user to easily distinguish between a default registry value and a registry value named `(Default)`.

**Comment by frankeros** [comment]
The change also should be applied in the detail of a `Windows Registry` detail from the `Integrity monitoring / Inventory` section.
![image](https://user-images.githubusercontent.com/26828184/118968925-d8ba4c00-b942-11eb-9ff8-d02f43ee7c60.png)
