### ISSUE TITLE
Bug generating a PDF in an agent config

### ISSUE THREAD

**Issue by CPAlejandro** [wazuh/wazuh-kibana-app#3225]
- Bug log collection looks double when generating a pdf in the configuration of an agent

![image.png](https://images.zenhubusercontent.com/5fe2fae7f5b0400775dc08b8/2cc51641-80e8-4409-9252-b19f92814644)

- `Who data` appears three times with different information
![image](https://user-images.githubusercontent.com/17100196/117124735-fd39f400-ad98-11eb-8ca0-4eb1a48edd37.png)

**Comment by Desvelao** [comment]
The `Who data` block seems to be:
- 1
![image](https://user-images.githubusercontent.com/34042064/117126825-99fd9100-ad9b-11eb-91e8-bef2bd1b8469.png)

- 2
![image](https://user-images.githubusercontent.com/34042064/117126901-b4d00580-ad9b-11eb-867e-d8faf45a6799.png)

- 3
![image](https://user-images.githubusercontent.com/34042064/117126966-c9ac9900-ad9b-11eb-9459-6d3c056a8eda.png)

We should rename the title of the blocks.
