### ISSUE TITLE
Wazuh integrity file monitoring not working on Ubuntu agent

### ISSUE THREAD

**Issue by tech-santosh** [wazuh/wazuh-kibana-app#3231]
Installed wazuh agent on ubuntu. Enabled FIM (File Integrity monitoring) at agent end but nothing showing in Wazuh monitoring web UI. Following is agent config:

#### Configuration file:
  
  <syscheck>
    <disabled>no</disabled>

    
    <frequency>43200</frequency>

    <scan_on_start>yes</scan_on_start>

    
    <directories>/etc,/usr/bin,/usr/sbin</directories>
    <directories>/bin,/sbin,/boot</directories>

    
    <directories check_all="yes" realtime="yes">/home/ubuntu</directories>
    <directories check_all="yes" realtime="yes" report_changes="yes">/home/ubuntu/data</directories>
    <directories check_all="yes">/etc,/usr/bin,/usr/sbin</directories>
    <directories check_all="yes">/root/users.txt,/bsd,/root/db.html</directories>
    <alert_new_files>yes</alert_new_files>

**Comment by gabiwassan** [comment]
Hi @tech-santosh ,
You could check and send us the response to these requests from the wazuh dev tool.
```
GET / syscheck /: agent_id
GET / syscheck /: agent_id / last_scan
```
And you could also check if in `/var/ossec/logs/ossec.log` you have any errors.

Best!

**Comment by frankeros** [comment]
Hi @tech-santosh, could you solve this problem?

**Comment by frankeros** [comment]
Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our [slack channel](https://wazuh.com/community/join-us-on-slack/) or subscribe to our [mailing list](https://groups.google.com/forum/#!forum/wazuh).
