### ISSUE TITLE
The evolution graph of agents shows the agents for all configured APIs

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3239]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.2.0   | 7.x     | 4201 |

**Description**
The evolution graph of agents shows the agents for all configured APIs

**Acceptance Criteria**
The evolution graph must display only the agents included by the current API. But this only can be applied by the manager and workers' names included in the monitoring indices. 
This will only work properly if the clusters' names and their workers' names from each APIs are different.

By @wazuh/frontend
**Steps to reproduce**

1. Go to 'Agents'

**Screenshots**
![image](https://user-images.githubusercontent.com/26828184/117833756-fe619a00-b24c-11eb-9dd1-5cc84f4118d3.png)

**Tasks:** 
- [x] Add filter by managers names corresponding to the current API only for the Agents evolution graph
- [x] Add the business rule to the Troubleshooting for Kibana in the documentation web.

**Comment by frankeros** [comment]
**IMPORTANT:**
The will only work properly if the clusters' names and their workers' names from each APIs are different.

By @wazuh/frontend

**Comment by mpRegalado** [comment]
- Problems with the environment/setup
	“Incorrect Kibana version in plugin [wazuh]” when installing the Wazuh Kibana plugin
	No template found for the selected index pattern
- Problems with the Wazuh API
	Wazuh API seems to be down
	Could not connect to API with id: default: 3003 - Missing param: API USERNAME
	
- Problems using the App
	I do not see alerts in the Wazuh Kibana plugin
	Wazuh Kibana plugin page goes blank
	“Conflict with the Wazuh app version” error is displayed
	Agent evolution showing agents from all APIs
	
None of the above solutions are fixing my problem
Link to (github, slack)

**Comment by mpRegalado** [comment]
Submitted PR with the changes to documentation https://github.com/wazuh/wazuh-documentation/pull/3914
