### ISSUE TITLE
Permission error generating monitoring indices

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3247]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.2.0   | 7.11.2     | 4201-10 |

**Description**
In an environment with X-Pack after an update from 7.10.2 to 7.11.2, a security exception was logged when the app tried to create the monitoring index.
It could be exceptional, but just in case we should try to reproduce it.

**Additional context**
<details>
<summary>Logs</summary>
<p>
May 11, 2021 @ 13:45:08  ERROR  Could not create wazuh-monitoring-2021.05.11 index on elasticsearch due to security_exception
May 11, 2021 @ 13:45:08  ERROR  security_exception
May 11, 2021 @ 14:00:03  ERROR  Could not create wazuh-monitoring-2021.05.11 index on elasticsearch due to security_exception
May 11, 2021 @ 14:00:03  ERROR  security_exception
May 11, 2021 @ 14:00:04  ERROR  Could not create wazuh-monitoring-2021.05.11 index on elasticsearch due to security_exception
May 11, 2021 @ 14:00:04  ERROR  security_exception
May 11, 2021 @ 14:00:07  ERROR  Could not create wazuh-monitoring-2021.05.11 index on elasticsearch due to security_exception
May 11, 2021 @ 14:00:07  ERROR  security_exception
May 11, 2021 @ 14:00:09  ERROR  Could not create wazuh-monitoring-2021.05.11 index on elasticsearch due to security_exception
May 11, 2021 @ 14:00:09  ERROR  security_exception
May 11, 2021 @ 14:15:03  ERROR  Could not create wazuh-monitoring-2021.05.11 index on elasticsearch due to security_exception
May 11, 2021 @ 14:15:03  ERROR  security_exception
May 11, 2021 @ 14:15:04  ERROR  Could not create wazuh-monitoring-2021.05.11 index on elasticsearch due to security_exception
May 11, 2021 @ 14:15:04  ERROR  security_exception
May 11, 2021 @ 14:15:07  ERROR  Could not create wazuh-monitoring-2021.05.11 index on elasticsearch due to security_exception
May 11, 2021 @ 14:15:07  ERROR  security_exception
May 11, 2021 @ 14:15:08  ERROR  Could not create wazuh-monitoring-2021.05.11 index on elasticsearch due to security_exception
May 11, 2021 @ 14:15:08  ERROR  security_exception
May 11, 2021 @ 14:45:03  ERROR  Could not create wazuh-monitoring-2021.05.11 index on elasticsearch due to security_exception
May 11, 2021 @ 14:45:03  ERROR  security_exception
May 11, 2021 @ 14:45:04  ERROR  Could not create wazuh-monitoring-2021.05.11 index on elasticsearch due to security_exception
May 11, 2021 @ 14:45:04  ERROR  security_exception
May 11, 2021 @ 14:45:07  ERROR  Could not create wazuh-monitoring-2021.05.11 index on elasticsearch due to security_exception
May 11, 2021 @ 14:45:07  ERROR  security_exception
May 11, 2021 @ 14:45:08  ERROR  Could not create wazuh-monitoring-2021.05.11 index on elasticsearch due to security_exception
May 11, 2021 @ 14:45:08  ERROR  security_exception
May 11, 2021 @ 15:00:02  ERROR  Could not create wazuh-monitoring-2021.05.11 index on elasticsearch due to security_exception
May 11, 2021 @ 15:00:02  ERROR  security_exception
May 11, 2021 @ 15:00:04  ERROR  Could not create wazuh-monitoring-2021.05.11 index on elasticsearch due to security_exception
May 11, 2021 @ 15:00:04  ERROR  security_exception
May 11, 2021 @ 15:00:07  ERROR  Could not create wazuh-monitoring-2021.05.11 index on elasticsearch due to security_exception
May 11, 2021 @ 15:00:07  ERROR  security_exception
May 11, 2021 @ 15:00:09  ERROR  Could not create wazuh-monitoring-2021.05.11 index on elasticsearch due to security_exception
May 11, 2021 @ 15:00:09  ERROR  security_exception
May 11, 2021 @ 15:15:03  ERROR  Could not create wazuh-monitoring-2021.05.11 index on elasticsearch due to security_exception
</p>
</details>

**Comment by mpRegalado** [comment]
**Steps I took to recreate**
I created an elastic production enviroment with a container for elasticsearch, wazuh manager, wazuh agent and kibana, and installed the wazuh app on the kibana container.

Upon launching the wazuh app, I saw similar logs in the output of my Kibana instance and the app displayed errors regarding the missing indexes.
**My understanding on the issue**
It seems like the error is caused by lacking permissions on the default user `kibana_system`, I created a new user role that allowed access to the indexes `wazuh-statistics-*` , `wazuh-monitoring-*` and `wazuh-alerts-*` and created a new user with the role just created as well as `kibana_system`. Replacing the credentials in `config/kibana.yml` and restarting the service made the indexes accesible and the error to cease.
