### ISSUE TITLE
When using Ruleset Test, each request is made in a different session instead of all in the same session

### ISSUE THREAD

**Issue by CPAlejandro** [wazuh/wazuh-kibana-app#3249]
When using Ruleset Test, each request is made in a different session instead of all in the same session.

To test it, we create a rule that takes into account the frequency parameter and when executing several logs in ruleset test, we see that the firedtimes parameter is always 1, which indicates that each request is made in a different session.

![image.png](https://images.zenhubusercontent.com/5fe2fae7f5b0400775dc08b8/33eb4ccf-3bb9-4081-99ab-e7b0fd81bd54)

On the other hand, if we execute the same test in the manager by executing the following command: / var / ossec / bin / wazuh-logtest, then we add the logs and see how the firedtimes parameter that it returns increases, instead of always being 1.

![image.png](https://images.zenhubusercontent.com/5fe2fae7f5b0400775dc08b8/852e5d7a-df0a-433b-8787-d09447233e58)

**Comment by Desvelao** [comment]
***New requirements to implement***
- Add button to close the Logtest session
- Keep the session global to the app
