### ISSUE TITLE
[Reports] The alerts of vulnerabilities is not completly displayed in the report

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#3275]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.x   | 7.x     | 4xxx |

**Description**
The alert count displayed in the Vulnerabilities dashboard module is not according to the showing in the report. We should review why it is happening. We should display 

**Steps to reproduce**

1. Go to the Vulnerabilities dashboard module and see the alert count by criticality
2. Generate a report
3. Go to Management > Reporting and open the last report generated
4. See the `Alerts summary section and review the alert count. These are not according to stats displayed in the dashboard

**Screenshots**
![image](https://user-images.githubusercontent.com/34042064/118963068-5ba0ce00-b966-11eb-9ec6-09d6905ff1cc.png)
![image](https://user-images.githubusercontent.com/34042064/118963117-68252680-b966-11eb-9fed-559eadb5d66b.png)

**Comment by pablomarga** [comment]
After some research we found that this problem was due to the `size` parameter of the visualization that made this kind of table. So we decided to check other modules that also have the same problem and increased the `size` of each one if it was neccesary
