### ISSUE TITLE
Issue adding Wazuh-API to Kibana

### ISSUE THREAD

**Issue by ayeitzabee** [wazuh/wazuh-kibana-app#329]
Afternoon/Morning,

I am getting the following error when I attempt to add the Wazuh API into Kibana:
Settings. Could not connect with Wazuh API, please check url and port and try again

I can access the API fine from outside the server, with http://10.1.1.104:55000/?pretty producing the following:
`{ "error": 0, "data": "Welcome to Wazuh HIDS API" }`

The error message from inside the devtools is:
```
{statusCode: 500, error: 5, message: "The requested URL was not found on this server"}
error
:
5
message
:
"The requested URL was not found on this server"
statusCode
:
500
```

I have opened up all the relevant firewall rules and disable selinux so now I am just stumped.

**Comment by JuanjiJG** [comment]
Hello @ayeitzabee,

I need to know some information about your current system. Could you please tell me what's your current version of the Wazuh Manager and Wazuh API?

Also, I need to know your current Wazuh app version. Could you please send me the content of the `package.json` file? It's located at `/usr/share/kibana/plugins/wazuh/package.json`.

Thanks for your patience.

Regards,
Juanjo

**Comment by ayeitzabee** [comment]
Thanks @JuanjiJG ,

Wazuh Manager: v2.1.1
Wazuh API: v3.2.1

And I have attached the package.json 

Thanks again!
[package.zip](https://github.com/wazuh/wazuh-kibana-app/files/1835633/package.zip)

**Comment by ayeitzabee** [comment]
Ah your a legend, worked first time after updating.

Thank you very much!

**Comment by JuanjiJG** [comment]
You're welcome @ayeitzabee!

I'm going to close this issue then. Feel free to post a new thread if you have more questions about Wazuh, and we'll be pleased to help you.

Best regards,
Juanjo
