### ISSUE TITLE
Create the detail section for Mitre Intelligence resources

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3293]
| Parent Issue | Blocked by |
| :---: | :---: |
| #3202 | #3291 |

**Description**
We need to create the detail section for the Mitre Intelligence resource items.
The details should display all information about the selected item and all the related resources.

**Acceptance Criteria**
- The design must be based on this proposal #3214 
- The detail of each item should be displayed dynamically 
- All related resources can be opened from the detail without page refresh (lazy loading)
- The fields `ID` (wazuh) and `Short name` should not be displayed

Get the Wazuh API endpoints from [#wazuh/wazuh/7819](https://github.com/wazuh/wazuh/issues/7819)

- [x] Add detail section.
- [x] Add related resources and navigation.

**Comment by CPAlejandro** [comment]
- [ ] Create a component with the flyouts.
- [ ] Make sure that the flyout redirect properly and clean to other flyouts

**Comment by CPAlejandro** [comment]
**Today's feedback**
Creating the component and adapting it to the new fields.

**Comment by CPAlejandro** [comment]
**Today's feedback** 
Generated the header and working on the subtables.
I leave pending: extract and display all the important data from the subtables and handle the behavior of the flyout when it has to redirect you to another flyout

**Comment by CPAlejandro** [comment]
**Today's feedback**
Navigation already working.
I only leave the bug pending that when navigating, does not move you to the beginning of the flyout, but leaves you at the height you were already
![image](https://user-images.githubusercontent.com/17100196/120825514-c1da4300-c559-11eb-8596-a6c5f1a3cd90.png)
![image](https://user-images.githubusercontent.com/17100196/120825667-e6ceb600-c559-11eb-8670-9014692e2522.png)
