### ISSUE TITLE
How to create a custom dashboard for a particular user he has to see his own dashboard instead of the standard dashboard

### ISSUE THREAD

**Issue by Sivavamsiraju** [wazuh/wazuh-kibana-app#3295]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.x   | 6.x     | 444 |

**Description**
Short description of your issue.

**Steps to reproduce**

**Screenshots**

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by frankeros** [comment]
Hi @Sivavamsiraju you should create a new Dashboard from `Kibana / Dashboard` 
![image](https://user-images.githubusercontent.com/26828184/120853913-bcc5c580-c552-11eb-9e16-5f4995f2cedb.png)
You could find helpful these links 
https://documentation.wazuh.com/current/user-manual/kibana-app/reference/custom-dashboard.html?highlight=dashboard
https://www.elastic.co/guide/en/kibana/current/dashboard.html

Regarding allowing the user to only see this dashboard you should use some security plugins for Kibana: X-Pack, or Opendistro.

You can check our tutorial for installations with [Opendistro](https://documentation.wazuh.com/current/installation-guide/open-distro/all-in-one-deployment/all_in_one.html#installing-elasticsearch)

Then you should create a custom workspace ([tenant](https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/multi-tenancy/#add-tenants) for Opendistro [space](https://www.elastic.co/guide/en/kibana/7.x/xpack-spaces.html) for X-Pack) then map the user into the new workspace. The dashboard should be created into this workspace.

If you need more information about any of these steps, please let me know.
Regards

**Comment by frankeros** [comment]
Hi @Sivavamsiraju, were you able to solve your problem?

**Comment by frankeros** [comment]
Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our [slack channel](https://wazuh.com/community/join-us-on-slack/) or subscribe to our [mailing list](https://groups.google.com/forum/#!forum/wazuh).
