### ISSUE TITLE
CDB list view not working with IPv6

### ISSUE THREAD

**Issue by DGawr** [wazuh/wazuh-kibana-app#3296]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.5  | 7.10.0  | 4106 |

**Description**
When using IPv6 addresses in CDB lists by encapsulating them between quotation marks (according to [Wazuh Issue #3967](https://github.com/wazuh/wazuh/issues/3976)) they don't get displayed correctly on load.

**Steps to reproduce**

1. Create CDB list and add IPv6 as key (e.g. `"dead:beef::0:0:0:0:0"`).
2. Exit and reopen the created list.

**Screenshots**
![image](https://user-images.githubusercontent.com/49725600/119475371-62a45380-bd4d-11eb-85bf-6be0674e14d7.png)

**Additional context**
The colons in the IPv6 notation break the string splitting used in [list-editor.js#L92](https://github.com/wazuh/wazuh-kibana-app/blob/master/public/controllers/management/components/management/ruleset/list-editor.js#L92).

Possible workaround:
```diff
contentToObject(content) {
  const items = {};
  const lines = content.split('\n');
  lines.forEach(line => {
-   const split = line.split(':');
+   if (line.startsWith('"')) {
+     let split = line.split('":');
+     split[0] += '"';
+   }
+   else {
+     const split = line.split(':');
+   }
    const key = split[0];
    const value = split[1] || '';
    if (key) items[key] = value; // Prevent add empty keys
  });
  return items;
}
```

**Comment by MauGaP** [comment]
Hi @DGawr!
Sorry for the late response.

I'm trying to reproduce it, can you show us an example of what you are trying to achieve (key and value)?

As can you see using `:` from the UI is not allowed. The comment that you referenced is modifying the file from the manager manually.

**Comment by DGawr** [comment]
For example the entry `"dead:beef:0:0:0:0:0:0":Testvalue` would be a valid entry for a CDB list, no matter if added manually or through the web UI. It's the correct way to add an IPv6 address according to the referenced issue.

But here is the problem: Once you add an IPv6 entry like that, either manually into the file or through the web UI, the web UI becomes useless because it breaks any entries that contain an IPv6 entry.

The UI needs to support this syntax because otherwise CDB lists just break once they are edited through it (possibly even without noticing it).

**Comment by MauGaP** [comment]
Hi! thanks for your reply

We will move this issue into our backlog, and prioritize when these changes can be included
Also, thanks for the suggested code changes.

Best!
