### ISSUE TITLE
Migrate kibana-discover (Angular) as a React component

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3299]
| Parent Issue | 
| #3276 |

**Description**
In order to migrate our plugin to React, we need to check the viability to encapsulate the current Angular component `kibana-discover` as a single Angular component inside a React component. This'll allow us to implement a React app with a single Angular component instead of an Angular App with React directives.

**Tasks**
- [ ] Investigate move Kibana-Discover as a single Angular component
- [ ] Investigate how to implement current event handler from kibana-discover in rootScope with redux for the new components.

**Comment by gdiazlo** [comment]
We will revisit this effort in the future.
