### ISSUE TITLE
Issue with Wazuh Overview

### ISSUE THREAD

**Issue by ayeitzabee** [wazuh/wazuh-kibana-app#330]
Hello again, 

I have run into another issue since connecting to the Wazuh API.
Now I can not access the overview or any agents without the following screen appearing:
![image](https://user-images.githubusercontent.com/37641758/37746212-daaf795c-2dc4-11e8-95c1-8a6b4b3dd4a9.png)

**Comment by JuanjiJG** [comment]
Hello @ayeitzabee,

I'm sorry you're having such problems with the Wazuh app.

First, let's try resetting your Kibana and Wazuh app installation. The following commands need to be executed **as superuser**. Keep in mind that this will erase all your Wazuh app configuration, such as stored API credentials, custom visualizations, etc.

1. Stop the Kibana and Logstash services:
```bash
systemctl stop logstash
systemctl stop kibana
```

2. Delete the Wazuh app indices and the `.kibana` index. *Warning:* Deleting the `.kibana` index will remove your custom Kibana visualizations and saved searches. 
```bash
curl -XDELETE localhost:9200/.kibana
curl -XDELETE localhost:9200/.wazuh
curl -XDELETE localhost:9200/.wazuh-version
```

3. Delete the Kibana optimization bundles. Don't worry about this, they're just cached files for faster loading times when using Kibana.
```bash
rm -rf /usr/share/kibana/optimize/bundles
```

4. Restart the Kibana and Logstash services:
```bash
systemctl restart logstash
systemctl restart kibana
```

Now, when you open the app again, you'll have to insert again your Wazuh API credentials. Please, let me know about the results, to see if now everything is working again.

Thanks for your patience.

Best regards,
Juanjo

**Comment by ayeitzabee** [comment]
Hi again,

So that is working out fine now, but I have run into another issue! (I have a feeling the tutorial I followed to setup Wazuh and Kibana was flawed)
Now it seems like none of my agents I have setup are sending events to Wazuh.
If this is asking too much of this thread where else could I ask this question/get help.

Regards,
Kade Hampson | IT Manager

**Comment by JuanjiJG** [comment]
Hello again @ayeitzabee,

We could check the current status of your agents. Please, execute the following API call to get a list of your agents and its status:
```
curl -u <api_user>:<api_password> -XGET "http://localhost:55000/agents?pretty"
```
Please, paste here the output.

Also, we could see the logs on one of your agents. Restart the agent and later, get the content of the logs file (the following commands must be executed **as superuser**):
```
systemctl restart wazuh-agent
tail -f /var/ossec/logs/ossec.log
```

Please, paste the output of the logs file too. Thanks for your patience.

Regards,
Juanjo

**Comment by ayeitzabee** [comment]
Hi again,

Sorry for the delay in responding to this, here is the result of the curl command:
`{
   "error": 0,
   "data": {
      "totalItems": 4,
      "items": [
         {
            "status": "Active",
            "name": "RRSJROK-V-IDS-01.reesjones.local",
            "ip": "127.0.0.1",
            "dateAdd": "2018-03-22 10:35:00",
            "version": "Wazuh v3.2.1",
            "manager_host": "RRSJROK-V-IDS-01.reesjones.local",
            "lastKeepAlive": "9999-12-31 23:59:59",
            "os": {
               "major": "7",
               "name": "CentOS Linux",
               "uname": "Linux |RRSJROK-V-IDS-01.reesjones.local |3.10.0-693.21.1.el7.x86_64 |#1 SMP Wed Mar 7 19:03:37 UTC 2018 |x86_64",
               "platform": "centos",
               "version": "7",
               "codename": "Core",
               "arch": "x86_64"
            },
            "id": "000"
         },
         {
            "status": "Active",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00",
            "group": "default",
            "name": "RRSJCXA01",
            "mergedSum": "53922705578e51dfce0c8fbd0d0cf47b",
            "ip": "any",
            "dateAdd": "2018-03-23 13:59:35",
            "version": "Wazuh v2.0.1",
            "manager_host": "RRSJROK-V-IDS-01.reesjones.local",
            "lastKeepAlive": "2018-03-28 09:30:26",
            "os": {
               "uname": "Microsoft Windows Server 2012 Datacenter Edition (full)  (Build 9200)"
            },
            "id": "003"
         },
         {
            "status": "Active",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00",
            "group": "default",
            "name": "RRSJCXA03",
            "mergedSum": "53922705578e51dfce0c8fbd0d0cf47b",
            "ip": "any",
            "dateAdd": "2018-03-23 14:22:18",
            "version": "Wazuh v2.0.1",
            "manager_host": "RRSJROK-V-IDS-01.reesjones.local",
            "lastKeepAlive": "2018-03-28 09:32:44",
            "os": {
               "uname": "Microsoft Windows Server 2012 Datacenter Edition (full)  (Build 9200)"
            },
            "id": "004"
         },
         {
            "status": "Active",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00",
            "group": "default",
            "name": "RRSJROK-V-Z01",
            "mergedSum": "53922705578e51dfce0c8fbd0d0cf47b",
            "ip": "10.1.1.100",
            "dateAdd": "2018-03-23 16:46:30",
            "version": "Wazuh v2.0.1",
            "manager_host": "RRSJROK-V-IDS-01.reesjones.local",
            "lastKeepAlive": "2018-03-28 09:32:19",
            "os": {
               "uname": "Microsoft Windows Server 2012 Datacenter Edition (full)  (Build 9200)"
            },
            "id": "006"
         }
      ]
   }
}`

And here is the output of the log file, I left it running for about 5 minutes:

`2018/03/28 09:34:13 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/httpd/access_log'.
2018/03/28 09:34:13 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/audit/audit.log'.
2018/03/28 09:34:13 ossec-logcollector: INFO: (1950): Analyzing file: '/var/ossec/logs/active-responses.log'.
2018/03/28 09:34:13 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/messages'.
2018/03/28 09:34:13 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/secure'.
2018/03/28 09:34:13 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/maillog'.
2018/03/28 09:34:13 ossec-logcollector: INFO: Started (pid: 13298).
2018/03/28 09:34:43 ossec-syscheckd: INFO: Syscheck scan frequency: 43200 seconds
2018/03/28 09:35:13 ossec-syscheckd: INFO: Starting syscheck scan (forwarding database).
2018/03/28 09:35:13 ossec-syscheckd: INFO: Starting syscheck database (pre-scan).`

**Comment by JuanjiJG** [comment]
Hello again @ayeitzabee, and sorry for the late response.

Let's try something different to see if your agents are sending alerts to the manager.

First of all, we could try to see if there are alerts from your agents in the `alerts.json` file.
```bash
cat /var/ossec/logs/alerts/alerts.json | grep 003
```

This will search for alerts from the agent with id `003`.

Next, we're gonna see if Logstash is capable of reading the `alerts.json` file. Execute the following command as superuser:
```bash
lsof /var/ossec/logs/alerts/alerts.json
```

Paste here the output of the `lsof` command, and let me know if the `cat` command is showing alerts from that agent.

One thing you can do to trigger an alert is open an SSH session to one of your agents, so we can make sure that there's an alert and it will be sent to the manager.

Thanks for your patience.

Best regards,
Juanjo

**Comment by jesusgn90** [comment]
Hello @ayeitzabee, since @JuanjiJG has no response from long time this issue should be closed. Open a new issue if you are facing problems. 

Regards,
Jesús
