### ISSUE TITLE
[Feature Request] More visible information in columns in Agent Section

### ISSUE THREAD

**Issue by dariommr** [wazuh/wazuh-kibana-app#3305]
Hello Team,
I am reaching you to ask for an enhancement for the App:

## Description
We need that the column width in the Agent section of the Wazuh App for Kibana can be more visible
Currently, it cuts the information, and sometimes it is needed to see as much information as possible inside that table.

## Alternatives
As alternatives:
- Make the column's width adjustable.
- Add carriage returns in every column (or the ones that contain large information)
- Making the columns wider for the OS names, Groups, and Dates.

## Context
You can see on the following examples in which the information is being cut:
![image](https://user-images.githubusercontent.com/37050249/119870869-337e1580-bef8-11eb-9fc0-2979475d189e.png)
In the following, we are not able to see the OS Version, because of the large name the OS have:
![image](https://user-images.githubusercontent.com/37050249/119870973-55779800-bef8-11eb-9d08-1926f3ef5c53.png)

I hope this could be helpful.
Thank you in advance.

**Comment by havidarou** [comment]
Duplicated https://github.com/wazuh/wazuh-kibana-app/issues/3627
