### ISSUE TITLE
Wazuh 4.1.5 / Elasticsearch/Kibana 7.10.2 - Wazuh API seems to be down via Kibana plugin (3099 - ERROR3099 - Invalid credentials) but manual access from Kibana server is working

### ISSUE THREAD

**Issue by troal** [wazuh/wazuh-kibana-app#3307]
| Wazuh | Elastic | Rev|Plugin used |
| ----- | ------- | ---|--- |
| 4.1.5   |  7.10.2   | 4106 | https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.1.5_7.10.2-1.zip |
| 4.1.5   |  7.11.2   |  4107 | https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.1.5_7.11.2-1.zip |

**Description**
I am encountering a connection problem from Kibana plugin toward Wazuh API.
Have tried with both Kibana/Elasticsearch 7.11.2 (plugin has now disappeared from master README version compatibility matrix..) and with Kibana/Elasticsearch 7.10.2 stack and plugin => same issue. 

**Screenshots**
error from kibana ui wazuh plugin:
![image](https://user-images.githubusercontent.com/687796/119969980-cf378080-bfe1-11eb-887d-340822d1fb10.png)

manual test working from kibana server (obviously with test creds):
![image](https://user-images.githubusercontent.com/687796/119970435-4a009b80-bfe2-11eb-8523-96e7407cf8f9.png)

test via kibana ui wazuh plugin "Check connection" button:
![image](https://user-images.githubusercontent.com/687796/119971060-140fe700-bfe3-11eb-8b7d-dc273a8690be.png)

associated kibana wazuh pluging conf:
![image](https://user-images.githubusercontent.com/687796/119971906-250d2800-bfe4-11eb-9867-a6223549a237.png)

no warning/error in elasticsearch/kibana/wazuh cluster logs

I feel quite stucked;  looking for help! :)

**Comment by troal** [comment]
```if useful, plugin debug log of an attempt 

{"date":"2021-05-28T10:29:35.846Z","level":"debug","location":"manage-hosts:getHosts","message":"Getting hosts"}
{"date":"2021-05-28T10:29:35.846Z","level":"debug","location":"update-registry:getHosts","message":"Getting hosts from registry"}
{"date":"2021-05-28T10:29:35.846Z","level":"debug","location":"update-registry:readContent","message":"Reading wazuh-registry.json content"}
{"date":"2021-05-28T10:29:35.847Z","level":"debug","location":"manage-hosts:getHostById","message":"Getting host sec-wazuh-int"}
{"date":"2021-05-28T10:29:35.847Z","level":"debug","location":"manage-hosts:getHosts","message":"Getting hosts"}
{"date":"2021-05-28T10:29:35.847Z","level":"debug","location":"APIUserAllowRunAs:check","message":"Check if API user undefined (sec-wazuh-int) has run_as"}
{"date":"2021-05-28T10:29:36.073Z","level":"debug","location":"wazuh-api:checkAPI","message":"sec-wazuh-int is valid"}
{"date":"2021-05-28T10:29:36.074Z","level":"debug","location":"manage-hosts:getHostById","message":"Getting host sec-wazuh-int"}
{"date":"2021-05-28T10:29:36.075Z","level":"debug","location":"manage-hosts:getHosts","message":"Getting hosts"}
{"date":"2021-05-28T10:29:36.080Z","level":"debug","location":"manage-hosts:getHostById","message":"Getting host sec-wazuh-int"}
{"date":"2021-05-28T10:29:36.080Z","level":"debug","location":"manage-hosts:getHosts","message":"Getting hosts"}
{"date":"2021-05-28T10:29:36.095Z","level":"debug","location":"manage-hosts:getHostById","message":"Getting host sec-wazuh-int"}
{"date":"2021-05-28T10:29:36.095Z","level":"debug","location":"manage-hosts:getHosts","message":"Getting hosts"}

and matching attempt in wazuh api logs
2021/05/28 18:29:36 INFO: unknown_user 10.252.3.220 "GET /security/user/authenticate" with parameters {} and body {} done in 0.005s: 401
2021/05/28 18:29:36 INFO: unknown_user 10.252.3.220 "GET /security/user/authenticate" with parameters {} and body {} done in 0.005s: 401

while with manual attempt from kibana server with same creds i have
2021/05/28 18:25:44 INFO: wazuh-wui 10.252.3.220 "GET /security/user/authenticate" with parameters {"raw": "true"} and body {} done in 0.233s: 200
2021/05/28 18:25:44 INFO: wazuh-wui 10.252.3.220 "GET /" with parameters {} and body {} done in 0.054s: 200

using 
curl -k -X GET "https://10.252.1.194:55000/" -H "Authorization: Bearer $(curl -u wazuh-wui:wazuh-wuiU1# -k -X GET 'https://10.252.1.194:55000/security/user/authenticate?raw=true')"

**Comment by troal** [comment]
i have tried add wazuh-api certificate to kibana server trusted store but still not luck.

Manual command still working and this time without `-k` option
```[root@sec-kibana ~]# curl -X GET "https://10.252.1.194:55000/?pretty=true" -H "Authorization: Bearer $(curl -u wazuh-wui:wazuh-wuiU1# -X GET 'https://10.252.1.194:55000/security/user/authenticate?raw=true')"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   271  100   271    0     0   1030      0 --:--:-- --:--:-- --:--:--  1030
{
   "data": {
      "title": "Wazuh API REST",
      "api_version": "4.1.5",
      "revision": 40114,
      "license_name": "GPL 2.0",
      "license_url": "https://github.com/wazuh/wazuh/blob/4.1/LICENSE",
      "hostname": "sec-wazuh-int-master.xxxxx.local",
      "timestamp": "2021-05-28T11:47:10+0000"
   },
   "error": 0
}

but have restarted kibana / tried browser incognito mode; but plugin still refuse to connect to wazuh api (same logs as above)

**Comment by gabiwassan** [comment]
Hi @troal,
In order to help you and checking your configuration it is possible that in the `wazuh.yml` file where you have your credentials, you have the wrong key `user:` it should be `username:`

Best!

**Comment by troal** [comment]
Thank you so much @gabiwassan, fixing the key instantly solved my problem.
Cheers!

**Comment by gabiwassan** [comment]
I'm glad I could help you, if everything is resolved I'll close the Issue.
If you have any further questions, please do not hesitate to reopen the Issue or use our [slack channel](https://wazuh.com/community/join-us-on-slack/), our [Google group](https://groups.google.com/forum/#!forum/wazuh)
