### ISSUE TITLE
Testing compatibility with Kibana 7.13.4 and 7.14.2

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3310]
| Wazuh | Elastic |
| ----- | ------- | 
| 4.2.2   | 7.13.4/7.14.2     | 

**Description**
Testing compatibility with Kibana 7.13.0

Test type: 
- Regression 

Test with browsers:
- Chrome
- Firefox
- Safari

Test with the theme:
- Light
- Dark

Checks:
- [x] General checks 
- [x] X-Pack checks

Issues related:

- [x] https://github.com/wazuh/wazuh-kibana-app/issues/3636
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/3629
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/3576

**Comment by Machi3mfl** [comment]
### Kibana `7.13.4` and Wazuh Kibana `4.2.2` incompatibility.

- Implemented `xpack` environment `4.2.2-rc1-7.13.4` in production mode
- Implemented `xpack` environment `4.2.2-rc1-7.13.4` in development mode

Researching about compatibility problem **(In progress)**

### Errors Screenshots in UI:

<img width="1440" alt="Screen Shot 2021-09-23 at 15 53 41" src="https://user-images.githubusercontent.com/6089438/134566907-05f321cc-3424-4e31-ac62-2573a0ba995a.png">

<img width="1439" alt="Screen Shot 2021-09-23 at 15 41 50" src="https://user-images.githubusercontent.com/6089438/134566916-c3ba0492-b90f-4899-83e8-a61614097300.png">


### Debugging errors 

**Catching error in console**
<img width="1537" alt="Screen Shot 2021-09-23 at 15 53 16" src="https://user-images.githubusercontent.com/6089438/134567119-c0e8a041-9e73-4b61-850d-890022d047ca.png">

**Error in chunk file**
`logInspectorRequest (https://localhost:5601/9007199254740991/bundles/plugin/wazuh/4.2.2-4203-1/wazuh.chunk.1.js:211117:118)`
<img width="1300" alt="Screen Shot 2021-09-23 at 15 51 15" src="https://user-images.githubusercontent.com/6089438/134567303-d9652597-d447-4311-89d1-36ccf24027d5.png">

**Error in `kibana-discover > logInspectorRequest > getRequestInspectorStats`**
<img width="813" alt="Screen Shot 2021-09-23 at 15 52 12" src="https://user-images.githubusercontent.com/6089438/134567528-3d68113e-393c-48b8-b4f0-7786a39c24cd.png">

**Comment by matiasmoreno876** [comment]
### Kibana `7.14.2` and Wazuh Kibana `4.2.2` incompatibility.

- Implemented `xpack` environment `4.2.2-rc1-7.14.2` in production mode
- Implemented `xpack` environment `4.2.2-rc1-7.14.2` in development mode

Researching about compatibility problem **(In progress)**

> When we enter the main screen of the health check, the app cannot advance even though the checks have been carried out correctly

### Errors Screenshots in UI:

![image](https://user-images.githubusercontent.com/49887871/134581060-cd48ff0e-af2a-4a50-82c7-e980d3fc6886.png)

![image](https://user-images.githubusercontent.com/49887871/134581431-e3e6feb5-172b-4ca6-a496-6c66eb7776a1.png)

![image](https://user-images.githubusercontent.com/49887871/134581502-7c5a4f3a-c77f-40d6-b87f-67d71cf25a0c.png)

**Comment by Machi3mfl** [comment]
## Changes Notes Kibana 7.11.2 to 7.13.4 - Resolving incompatibility

### Error in `kibana/src/plugins/data/common/search/search_source/inspect/inspector_stats.ts > getRequestInspectorStats`

<img width="1439" alt="Screen Shot 2021-09-23 at 15 41 50" src="https://user-images.githubusercontent.com/6089438/134708041-708420f3-7c26-45e1-99b1-de41bd3d682b.png">

- function getRequestInspectorStats is not public in new version. Not exported

**Posible Solution:** Copy the function and pasted in wazuh `kibana-services.js`

**Before - After**
<img width="1363" alt="Screen Shot 2021-09-24 at 13 12 05" src="https://user-images.githubusercontent.com/6089438/134707336-f9103fa2-0ab0-4ab8-b180-43e18e6bdb0a.png">

### Error in `/kibana/src/plugins/data/common/search/search_source/search_source.ts`
<img width="718" alt="Screen Shot 2021-09-24 at 13 18 39" src="https://user-images.githubusercontent.com/6089438/134708199-41ffa474-b002-4562-9b56-665aacb8b574.png">

-  function `$scope.searchSource.getSearchRequestBody()` changed to sync (before async)

**Posible Solution:** remove .then in `kibana-discover.js`

**Before - After**


<img width="1364" alt="Screen Shot 2021-09-24 at 13 11 09" src="https://user-images.githubusercontent.com/6089438/134707277-cd03a00a-d7dd-4c97-bd67-f7d589616eb0.png">

**Comment by matiasmoreno876** [comment]
### Wazuh 4.2.2 status update and Kibana 7.14.2 in development mode

Currently the application runs in development mode with the changes made as detailed by @Machi3mfl above.

> screenshot

![image](https://user-images.githubusercontent.com/49887871/134757859-252fb7bc-e878-45b1-ba62-4ffd69c453d8.png)

![image](https://user-images.githubusercontent.com/49887871/134757863-c2c07bbc-103a-43b3-8713-1f4a0d65d722.png)

![image](https://user-images.githubusercontent.com/49887871/134757878-001a7396-2d62-4477-8be6-fcb379a53afd.png)

> But when we want to generate a package to test in production environments, we get the following error:


![image](https://user-images.githubusercontent.com/49887871/134757922-7de41444-abcc-41dc-a046-d600e3b29a21.png)

![image](https://user-images.githubusercontent.com/49887871/134757928-239d7102-94dd-4b81-b470-31129f79fca4.png)

**Comment by CPAlejandro** [comment]
**Bugs and issues found in 7.13.4**

- When we switch the size of the windows in Agent pannel, this error appear:
![image (21)](https://user-images.githubusercontent.com/17100196/134938040-ee881284-94b7-41e0-9d65-764e328a5689.png)

- In the Wazuh Menu same Pannels like Management or Setting appear in a different form
![image (22)](https://user-images.githubusercontent.com/17100196/134938177-666dd424-ce4d-4dd6-a10a-67ee24377025.png)

**Comment by CPAlejandro** [comment]
We have found this error while we tried to build a package of the app for Kibana 7.14.2:
![image](https://user-images.githubusercontent.com/17100196/135085236-65fd2043-3bdb-43c7-bf77-1688bcbf992e.png)

We found a solution following these steps:
- Modify the file: `/src/plugins/discover/application/apps/main/components/layout/discover_layout.scss`
- Change `@import 'src/core/public/mixins` --> `@import '../../../../../../../../core/public/mixins';`

**Comment by matiasmoreno876** [comment]
**Bugs and issues found in 7.14.2**

**Reporting**
> Should work with no custom filters.

![Should work with no custom filters](https://user-images.githubusercontent.com/49887871/135296622-66f213fc-5db0-46e7-a319-66012b531ffd.gif)

> Using custom filters, the report must apply the custom filters.

![Using custom filters, the report must apply the custom filters](https://user-images.githubusercontent.com/49887871/135296798-6caa52ee-fa21-4730-be47-50e3abcce497.gif)

> Using custom filters and custom query, the report must apply the custom filters and the custom query.

> Using a custom query, the report must apply the custom query.

![Using a custom query, the report must apply the custom query](https://user-images.githubusercontent.com/49887871/135297140-f6fddff2-8d5f-421b-b892-c39c82ba78bb.gif)
