### ISSUE TITLE
WzSearchBar component malfunction with suggestions that contain " and " or " or "

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#3325]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.x   | 7.x     | 400x|

**Description**
The `WzSearchBar` component can't search when the suggestions values contain the " and " or " or " string.

It is because the query is split by these strings into substrings and provokes a malfunction in the search bar. As consequence, it displays bad suggestions and can't search because thinks the query is not completed.

This could be caused by the regular expression in https://github.com/wazuh/wazuh-kibana-app/blob/4.2-7.10/public/components/wz-search-bar/lib/q-interpreter.ts#L34

**Steps to reproduce**

1. Go to `Agents` and type in the search bar something like `name=wazuh and `
2. Check the suggestion or try to do the search

**Screenshots**
![image](https://user-images.githubusercontent.com/34042064/120495318-e0ef9e00-c3bc-11eb-9bc9-1f0c912510d4.png)

**Comment by AlexRuiz7** [comment]
Might be resolved by #4088
