### ISSUE TITLE
Group agent management table does not update on error

### ISSUE THREAD

**Issue by mpRegalado** [wazuh/wazuh-kibana-app#3332]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.x   | 7.x     | 444 |

**Description**
When you have a 2 column management interface, such as the "Manage Agents" in the groups section, if there is an error while processing the operation, the state does not update to reflect what operations have been applied at the moment, leaving the possibility of further errors.

This is different from the behavior on a successful operation where it navigates the user out of the panel, forcing it to load the correct state if opened again.

**Steps to reproduce**

1. Go to 'Management -> Groups -> Specific Group'
2. Click on 'Manage Agents'
3. Attempt to add multiple agents to the group, at least one of which is never connected.
4. See that all the agents are still on the right side column, and removing the never connected agent and attempting to apply changes leads to more error messages.

**Screenshots**
![agentTable](https://user-images.githubusercontent.com/80431234/120780569-8d01c800-c528-11eb-9906-6e5993d1be87.gif)

**Additional context**
Same issue stands with any other error, like trying to remove agents with at least one not belonging to any other group.
I reproduced the issue in 4.2-7.12.1-dev and 4.1.5-7.10.0-prod

**Comment by sortizowlh** [comment]
Different errors when trying to add disconnected agents and never connected agents to a group:

- Disconnected
![imagen](https://user-images.githubusercontent.com/47242022/132532217-3ee39a81-9279-4430-9a87-6d4f11143f9b.png)
- Never connected
![imagen](https://user-images.githubusercontent.com/47242022/132532273-99fc0cbe-394d-4ce4-ab1e-f2839de67aec.png)

**Comment by sortizowlh** [comment]
- Save the previous state.
- Check if agents are allocated in their correct previous position
- Move agents to their previous position
