### ISSUE TITLE
Api selector toggle does not disable the api selector

### ISSUE THREAD

**Issue by mpRegalado** [wazuh/wazuh-kibana-app#3335]
| Wazuh | Elastic |
| ----- | ------- |
| 4.2   | 7.10    |

**Description**
The toggle for the API selector does not hide the selector itself even after a page refresh.

**Steps to reproduce**

1. Launch an environment with 2 working APIs
2. Go to App->Settings->Configuration
2. Click on API selector
3. See that the selector is still there and still working.
4. Refresh
5. See that the selector is still there and still working

**Screenshots**
![apiSelectorToggle](https://user-images.githubusercontent.com/80431234/120833804-82642480-c562-11eb-9be5-44d06820a703.gif)

**Additional context**
I discovered the issue with an `xpack dev` installation and the user `elastic` , I doubt this is relevant but it's worth mentioning since `elastic` has superuser permissions.

**Comment by Desvelao** [comment]
Should we remove this app setting? I don't see the use cases for this functionality.

**Comment by frankeros** [comment]
We should remove this unnecessary config.
