### ISSUE TITLE
When creating decoders it is very useful to be able to first test decoders before creating any matching rules.

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3348]
When creating decoders it is very useful to be able to first test decoders before creating any matching rules.
Currently testing a log that matches a decoder without matching a rule will again return the `No result found` message.
For example:
```
Apr 28 13:43:51 localhost local_decoder_example: test
```
Should result in: 
```
**Phase 1: Completed pre-decoding.
        full event: 'Apr 28 13:43:51 localhost local_decoder_example: test'
        timestamp: 'Apr 28 13:43:51'
        hostname: 'localhost'
        program_name: 'local_decoder_example'

**Phase 2: Completed decoding.
        name: 'local_decoder_example'
```

Instead it returns:
```
No result found for:  Apr 28 13:43:51 localhost local_decoder_example: test 
```
This is testing with the app compiled at https://github.com/wazuh/wazuh-kibana-app/commit/87fba0138c087f66f7d4d23dd6fd6a8faefef722

_Originally posted by @jctello in https://github.com/wazuh/wazuh-kibana-app/issues/3193#issuecomment-828471625_

**Comment by sortizowlh** [comment]
Tested logtest for rulesets and decoders.

Check if the data is from a ruleset or from a decoder and show data depending on the case.

![image](https://user-images.githubusercontent.com/47242022/124752610-5a346080-df28-11eb-9a51-a0e847dbce63.png)
![image](https://user-images.githubusercontent.com/47242022/124754010-f9a62300-df29-11eb-8884-72144697953e.png)
