### ISSUE TITLE
Make elements on the agent preview page tile correctly at low widths

### ISSUE THREAD

**Issue by mpRegalado** [wazuh/wazuh-kibana-app#3354]
**Describe the solution you'd like**
Related to https://github.com/wazuh/wazuh-kibana-app/issues/3229
In 7.10, the agent page does tile correctly before exiting the side of the screen, however, when it does, the agent evolution graph does not fill the full width
![image.png](https://images.zenhubusercontent.com/609a3b93e47a8d8edbaeef34/9077fed8-af26-48c0-9dca-80bde8195379)

**Describe alternatives you've considered**
The `EuiFlexGroup` has props defined to handle these situations precisely, setting the `wrap` property in the flex container that houses the 3 elements and a `min-width` in each of the children should work.
https://elastic.github.io/eui/#/layout/flex

**Comment by Machi3mfl** [comment]
This issue was resolved in #3854
