### ISSUE TITLE
[Regresion] Test all issues in 7.10 7.11 and 7.12

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-kibana-app#3360]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.2  | 7.12     | 444 |

**Description**
Test all fixes made for Kibana **7.12** compatibility. It should be also be tested in **7.10** and **7.11** for retro-compatibility.

Test with browsers:

- Chrome
- Firefox
- Safari

Test with the themes:

- Light
- Dark

Fixes:
- [x] [visualization label overlap](https://github.com/wazuh/wazuh-kibana-app/pull/3355)
- [x] [Fix error due short graphs](https://github.com/wazuh/wazuh-kibana-app/pull/3349)
- [x] [Fix export to csv table button 7.11 & 7.12](https://github.com/wazuh/wazuh-kibana-app/pull/3358)
- [x] [Hide Wazuh breadcrumb label and Wazuh api selector css fix](https://github.com/wazuh/wazuh-kibana-app/pull/3347)
- [x] [Fix/elastic UI upgrade breaking changes in 7.11 and 7.12](https://github.com/wazuh/wazuh-kibana-app/pull/3345)
- [x] [Normalize visData table property for 7.12 retro-compatibility](https://github.com/wazuh/wazuh-kibana-app/pull/3323)
- [x] [Fix visualizations with dark mode background in PDF report](https://github.com/wazuh/wazuh-kibana-app/pull/3315)
- [x] General checks

**Comment by mpRegalado** [comment]
**Testing 7.12.1 on safari**
- [ ]  visualization label overlap
- [ ]  Fix error due short graphs
- [ ]  Fix export to csv table button 7.11 & 7.12
- [ ]  Hide Wazuh breadcrumb label and Wazuh api selector css fix
- [ ]  Fix/elastic UI upgrade breaking changes in 7.11 and 7.12
- [ ]  Normalize visData table property for 7.12 retro-compatibility
- [ ]  Fix visualizations with dark mode background in PDF report
- [ ]  General checks

**Comment by mpRegalado** [comment]
**Testing 7.12.1 on chrome**

- [ ]  visualization label overlap
- [ ]  Fix error due short graphs
- [ ]  Fix export to csv table button 7.11 & 7.12
- [ ]  Hide Wazuh breadcrumb label and Wazuh api selector css fix
- [ ]  Fix/elastic UI upgrade breaking changes in 7.11 and 7.12
- [ ]  Normalize visData table property for 7.12 retro-compatibility
- [ ]  Fix visualizations with dark mode background in PDF report
- [ ]  General checks

**Comment by mpRegalado** [comment]
**Testing 7.12.1 on Firefox**

- [ ]  visualization label overlap
- [ ]  Fix error due short graphs
- [ ]  Fix export to csv table button 7.11 & 7.12
- [ ]  Hide Wazuh breadcrumb label and Wazuh api selector css fix
- [ ]  Fix/elastic UI upgrade breaking changes in 7.11 and 7.12
- [ ]  Normalize visData table property for 7.12 retro-compatibility
- [ ]  Fix visualizations with dark mode background in PDF report

**Comment by mpRegalado** [comment]
Testing on 7.10.2 Chrome

- [ ]  visualization label overlap
- [ ]  Fix error due short graphs
- [ ]  Fix export to csv table button 7.11 & 7.12
- [ ]  Hide Wazuh breadcrumb label and Wazuh api selector css fix
- [ ]  Fix/elastic UI upgrade breaking changes in 7.11 and 7.12
- [ ]  Normalize visData table property for 7.12 retro-compatibility
- [ ]  Fix visualizations with dark mode background in PDF report
- [ ]  General checks
