### ISSUE TITLE
Deployment commands use agent-auth instead of enrollment

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh-kibana-app#3361]
| Wazuh | Elastic |
| ----- | ------- |
| 4.1   | 7.10  |

**Description**
The one-step deployment command in Windows, like using PowerShell **Invoke-WebRequest** uses the legacy **agent-auth** to request a key for the deployed agent. And the different registration options are targeted to agent-auth options.
I.e.: Using **Invoke-WebRequest** command with  **WAZUH_REGISTRATION_PASSWORD** option will call **agent-auth** with **-P** flag.
But, **agent-auth** is a binary that will be deprecated and should be replaced with the new enrollment feature.
Also, using agent-auth to ask for keys with a password will only work during the deployment. Out of the box, enrollment is enabled by default, so if the agent fails to communicate with the manager and automatically asks for a new key, this new request will not use the required password and will fail.
The deployment commands should set the environment to work with enrollment. In this way, **WAZUH_REGISTRATION_PASSWORD** should create the **./etc/authd.pass** file and write the password. This will allow enrollment to work using the required password each time is necessary.

**Comment by gdiazlo** [comment]
This is closed by https://github.com/wazuh/wazuh-packages/issues/633
