### ISSUE TITLE
Using Invoke-WebRequest for agent deployment wrongly parse WAZUH_REGISTRATION_PASSWORD option

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh-kibana-app#3362]
| Wazuh | Elastic |
| ----- | ------- |
| 4.1   | 7.1.0     |

**Description**
Using Invoke-WebRequest to deploy an agent fails when parsing **WAZUH_REGISTRATION_PASSWORD** option if the string contains a white space.
Wazuh registration password supports white spaces, but, this command wrongly parses the white space of the string in **WAZUH_REGISTRATION_PASSWORD** and tries to pass the tail of the option to the msi installer as an extra installation option making it fail.

**Comment by gdiazlo** [comment]
Closed by https://github.com/wazuh/wazuh-packages/issues/633
