### ISSUE TITLE
Improving search functionality in Log management

### ISSUE THREAD

**Issue by mpRegalado** [wazuh/wazuh-kibana-app#3364]
**Describe the solution you'd like**
When using the search bar in the Logs section, it would be good if it filtered by the text as it is seen, right now it only filters by the description on the log, and trying to write a date, for example, yields no results.

**Describe alternatives you've considered**
We could also add date field in the same way there is a daemon selector instead of modifying the behavior of the search bar, and that way all the information displayed could be filtered on their own terms.

**Comment by frankeros** [comment]
It's related to #3264 
I'm closing this issue
