### ISSUE TITLE
Insufficient merge: Broken README.md

### ISSUE THREAD

**Issue by iasdeoupxe** [wazuh/wazuh-kibana-app#3365]
As mentioned in https://github.com/wazuh/wazuh-kibana-app/pull/3352#discussion_r648556355 that merge request has introduced some unresolved merge conflicts here:

https://github.com/wazuh/wazuh-kibana-app/blob/master/README.md#from-404---4016

https://github.com/wazuh/wazuh-kibana-app#wazuh---kibana---open-distro-version-compatibility-matrix

![broken_readme](https://user-images.githubusercontent.com/39667843/121769035-a5de2f00-cb61-11eb-8251-48c0565c9bc6.png)

**Comment by frankeros** [comment]
Thanks, @iasdeoupxe for reporting it.
