### ISSUE TITLE
Fortigate log monitoring with Wazuh-manager

### ISSUE THREAD

**Issue by landgekr** [wazuh/wazuh-kibana-app#3366]
Hello, 
I've got a Fortigate firewall v6.0.9  and I'm trying to monitor it's logs with Wazuh.

I can see the logs being monitored in /var/ossec/logs/archives/

But I can't find these logs in kibana. I don't know why.

**Comment by landgekr** [comment]
Adding some more information
1. We have Wazuh 4.1 on ubuntu 20.04
2. sharing  bin/wazuh-logtest output for test log

Type one log per line

{"timestamp":"2021-06-12T08:27:47.775+0000","agent":{"id":"000","name":"clbavlinsi01"},"manager":{"name":"clbavlinsi01"},"id":"1623486467.413512635","full_log":"Jun 12 13:57:47 INCALSOFTBAVFG6H0E01 CEF:0|Fortinet|Fortigate|v6.0.9|00011|traffic:forward dns|4|deviceExternalId=FG6H0E5819905201 FTNTFGTlogid=0000000011 cat=traffic:forward FTNTFGTsubtype=forward FTNTFGTlevel=warning FTNTFGTvd=root FTNTFGTeventtime=1623486467 src=172.17.201.68 spt=61850 deviceInboundInterface=unknown-0 FTNTFGTsrcintfrole=undefined dst=192.168.207.13 dpt=53 deviceOutboundInterface=unknown-0 FTNTFGTdstintfrole=undefined FTNTFGTpoluuid=7ef83b66-0cac-51eb-65e5-bb8cb4e9d405 externalId=1484872905 proto=17 act=dns FTNTFGTpolicyid=426 FTNTFGTpolicytype=policy app=DNS FTNTFGTappcat=unscanned FTNTFGTcrscore=5 FTNTFGTcraction=262144 FTNTFGTcrlevel=low FTNTFGTdstdevtype=Windows PC FTNTFGTdstdevcategory=Windows Device FTNTFGTdstosname=Windows 10 / 2016 FTNTFGTdstunauthuser=clbavwindc01$ FTNTFGTdstunauthusersource=kerberos FTNTFGTmasterdstmac=00:15:5d:cf:04:0a FTNTFGTdstmac=00:15:5d:cf:04:0a FTNTFGTdstserver=1","predecoder":{"program_name":"CEF","timestamp":"Jun 12 13:57:47","hostname":"INCALSOFTBAVFG6H0E01"},"decoder":{},"location":"172.20.0.110"}

**Phase 1: Completed pre-decoding.
        full event: '{"timestamp":"2021-06-12T08:27:47.775+0000","agent":{"id":"000","name":"clbavlinsi01"},"manager":{"name":"clbavlinsi01"},"id":"1623486467.413512635","full_log":"Jun 12 13:57:47 INCALSOFTBAVFG6H0E01 CEF:0|Fortinet|Fortigate|v6.0.9|00011|traffic:forward dns|4|deviceExternalId=FG6H0E5819905201 FTNTFGTlogid=0000000011 cat=traffic:forward FTNTFGTsubtype=forward FTNTFGTlevel=warning FTNTFGTvd=root FTNTFGTeventtime=1623486467 src=172.17.201.68 spt=61850 deviceInboundInterface=unknown-0 FTNTFGTsrcintfrole=undefined dst=192.168.207.13 dpt=53 deviceOutboundInterface=unknown-0 FTNTFGTdstintfrole=undefined FTNTFGTpoluuid=7ef83b66-0cac-51eb-65e5-bb8cb4e9d405 externalId=1484872905 proto=17 act=dns FTNTFGTpolicyid=426 FTNTFGTpolicytype=policy app=DNS FTNTFGTappcat=unscanned FTNTFGTcrscore=5 FTNTFGTcraction=262144 FTNTFGTcrlevel=low FTNTFGTdstdevtype=Windows PC FTNTFGTdstdevcategory=Windows Device FTNTFGTdstosname=Windows 10 / 2016 FTNTFGTdstunauthuser=clbavwindc01$ FTNTFGTdstunauthusersource=kerberos FTNTFGTmasterdstmac=00:15:5d:cf:04:0a FTNTFGTdstmac=00:15:5d:cf:04:0a FTNTFGTdstserver=1","predecoder":{"program_name":"CEF","timestamp":"Jun 12 13:57:47","hostname":"INCALSOFTBAVFG6H0E01"},"decoder":{},"location":"172.20.0.110"}'

**Phase 2: Completed decoding.
        name: 'json'
        agent.id: '000'
        agent.name: 'clbavlinsi01'
        full_log: 'Jun 12 13:57:47 INCALSOFTBAVFG6H0E01 CEF:0|Fortinet|Fortigate|v6.0.9|00011|traffic:forward dns|4|deviceExternalId=FG6H0E5819905201 FTNTFGTlogid=0000000011 cat=traffic:forward FTNTFGTsubtype=forward FTNTFGTlevel=warning FTNTFGTvd=root FTNTFGTeventtime=1623486467 src=172.17.201.68 spt=61850 deviceInboundInterface=unknown-0 FTNTFGTsrcintfrole=undefined dst=192.168.207.13 dpt=53 deviceOutboundInterface=unknown-0 FTNTFGTdstintfrole=undefined FTNTFGTpoluuid=7ef83b66-0cac-51eb-65e5-bb8cb4e9d405 externalId=1484872905 proto=17 act=dns FTNTFGTpolicyid=426 FTNTFGTpolicytype=policy app=DNS FTNTFGTappcat=unscanned FTNTFGTcrscore=5 FTNTFGTcraction=262144 FTNTFGTcrlevel=low FTNTFGTdstdevtype=Windows PC FTNTFGTdstdevcategory=Windows Device FTNTFGTdstosname=Windows 10 / 2016 FTNTFGTdstunauthuser=clbavwindc01$ FTNTFGTdstunauthusersource=kerberos FTNTFGTmasterdstmac=00:15:5d:cf:04:0a FTNTFGTdstmac=00:15:5d:cf:04:0a FTNTFGTdstserver=1'
        id: '1623486467.413512635'
        location: '172.20.0.110'
        manager.name: 'clbavlinsi01'
        predecoder.hostname: 'INCALSOFTBAVFG6H0E01'
        predecoder.program_name: 'CEF'
        predecoder.timestamp: 'Jun 12 13:57:47'
        timestamp: '2021-06-12T08:27:47.775+0000'

**Comment by landgekr** [comment]
Adding some more information

We have Wazuh 4.1 on ubuntu 20.04
sharing bin/wazuh-logtest output for test log
Type one log per line

{"timestamp":"2021-06-12T08:27:47.775+0000","agent":{"id":"000","name":"clbavlinsi01"},"manager":{"name":"clbavlinsi01"},"id":"1623486467.413512635","full_log":"Jun 12 13:57:47 INCALSOFTBAVFG6H0E01 CEF:0|Fortinet|Fortigate|v6.0.9|00011|traffic:forward dns|4|deviceExternalId=FG6H0E5819905201 FTNTFGTlogid=0000000011 cat=traffic:forward FTNTFGTsubtype=forward FTNTFGTlevel=warning FTNTFGTvd=root FTNTFGTeventtime=1623486467 src=172.17.201.68 spt=61850 deviceInboundInterface=unknown-0 FTNTFGTsrcintfrole=undefined dst=192.168.207.13 dpt=53 deviceOutboundInterface=unknown-0 FTNTFGTdstintfrole=undefined FTNTFGTpoluuid=7ef83b66-0cac-51eb-65e5-bb8cb4e9d405 externalId=1484872905 proto=17 act=dns FTNTFGTpolicyid=426 FTNTFGTpolicytype=policy app=DNS FTNTFGTappcat=unscanned FTNTFGTcrscore=5 FTNTFGTcraction=262144 FTNTFGTcrlevel=low FTNTFGTdstdevtype=Windows PC FTNTFGTdstdevcategory=Windows Device FTNTFGTdstosname=Windows 10 / 2016 FTNTFGTdstunauthuser=clbavwindc01$ FTNTFGTdstunauthusersource=kerberos FTNTFGTmasterdstmac=00:15:5d:cf:04:0a FTNTFGTdstmac=00:15:5d:cf:04:0a FTNTFGTdstserver=1","predecoder":{"program_name":"CEF","timestamp":"Jun 12 13:57:47","hostname":"INCALSOFTBAVFG6H0E01"},"decoder":{},"location":"172.20.0.110"}

**Phase 1: Completed pre-decoding.
full event: '{"timestamp":"2021-06-12T08:27:47.775+0000","agent":{"id":"000","name":"clbavlinsi01"},"manager":{"name":"clbavlinsi01"},"id":"1623486467.413512635","full_log":"Jun 12 13:57:47 INCALSOFTBAVFG6H0E01 CEF:0|Fortinet|Fortigate|v6.0.9|00011|traffic:forward dns|4|deviceExternalId=FG6H0E5819905201 FTNTFGTlogid=0000000011 cat=traffic:forward FTNTFGTsubtype=forward FTNTFGTlevel=warning FTNTFGTvd=root FTNTFGTeventtime=1623486467 src=172.17.201.68 spt=61850 deviceInboundInterface=unknown-0 FTNTFGTsrcintfrole=undefined dst=192.168.207.13 dpt=53 deviceOutboundInterface=unknown-0 FTNTFGTdstintfrole=undefined FTNTFGTpoluuid=7ef83b66-0cac-51eb-65e5-bb8cb4e9d405 externalId=1484872905 proto=17 act=dns FTNTFGTpolicyid=426 FTNTFGTpolicytype=policy app=DNS FTNTFGTappcat=unscanned FTNTFGTcrscore=5 FTNTFGTcraction=262144 FTNTFGTcrlevel=low FTNTFGTdstdevtype=Windows PC FTNTFGTdstdevcategory=Windows Device FTNTFGTdstosname=Windows 10 / 2016 FTNTFGTdstunauthuser=clbavwindc01$ FTNTFGTdstunauthusersource=kerberos FTNTFGTmasterdstmac=00:15:5d:cf:04:0a FTNTFGTdstmac=00:15:5d:cf:04:0a FTNTFGTdstserver=1","predecoder":{"program_name":"CEF","timestamp":"Jun 12 13:57:47","hostname":"INCALSOFTBAVFG6H0E01"},"decoder":{},"location":"172.20.0.110"}'

**Phase 2: Completed decoding.
name: 'json'
agent.id: '000'
agent.name: 'clbavlinsi01'
full_log: 'Jun 12 13:57:47 INCALSOFTBAVFG6H0E01 CEF:0|Fortinet|Fortigate|v6.0.9|00011|traffic:forward dns|4|deviceExternalId=FG6H0E5819905201 FTNTFGTlogid=0000000011 cat=traffic:forward FTNTFGTsubtype=forward FTNTFGTlevel=warning FTNTFGTvd=root FTNTFGTeventtime=1623486467 src=172.17.201.68 spt=61850 deviceInboundInterface=unknown-0 FTNTFGTsrcintfrole=undefined dst=192.168.207.13 dpt=53 deviceOutboundInterface=unknown-0 FTNTFGTdstintfrole=undefined FTNTFGTpoluuid=7ef83b66-0cac-51eb-65e5-bb8cb4e9d405 externalId=1484872905 proto=17 act=dns FTNTFGTpolicyid=426 FTNTFGTpolicytype=policy app=DNS FTNTFGTappcat=unscanned FTNTFGTcrscore=5 FTNTFGTcraction=262144 FTNTFGTcrlevel=low FTNTFGTdstdevtype=Windows PC FTNTFGTdstdevcategory=Windows Device FTNTFGTdstosname=Windows 10 / 2016 FTNTFGTdstunauthuser=clbavwindc01$ FTNTFGTdstunauthusersource=kerberos FTNTFGTmasterdstmac=00:15:5d:cf:04:0a FTNTFGTdstmac=00:15:5d:cf:04:0a FTNTFGTdstserver=1'
id: '1623486467.413512635'
location: '172.20.0.110'
manager.name: 'clbavlinsi01'
predecoder.hostname: 'INCALSOFTBAVFG6H0E01'
predecoder.program_name: 'CEF'
predecoder.timestamp: 'Jun 12 13:57:47'
timestamp: '2021-06-12T08:27:47.775+0000'

**Comment by landgekr** [comment]
We are not able to see GeoLocation tags on SSL VPN Logs, 

We want geotag of data.remip field.

**Comment by CPAlejandro** [comment]
To add the geotag of data.remip you would have to:

1.  Add the geoip processor:

File: `/usr/share/filebeat/module/wazuh/alerts/ingest/pipeline.json`

Add something like:
```
{
  "geoip": {
    "field": "data.remip",
    "target_field": "GeoLocation",
    "properties": ["city_name", "country_name", "region_name", "location"],
    "ignore_missing": true,
    "ignore_failure": true
  }
},
```
If you want it for the ingest pipeline then add it to /usr/share/filebeat/module/wazuh/archives/ingest/pipeline.json

2. Update the ingest pipelines

`filebeat setup --pipelines`

You could check that the pipeline/s have been updated by making the following request using the Kibana Dev Tools and checking that the processor you added is there.

`GET _ingest / pipeline`

Keep in mind that this change applies to new alerts that will go through the pipeline.

**Comment by CPAlejandro** [comment]
Regarding the logs in `/var/ossec/logs/archives` , in the files that contain that folder everything would be logging (having a configuration in the manager enabled for this). This would be all the logs collected and it does not imply that they will launch an alert, which would be in `/var/ossec/logs/alerts`. Mention that the information contained in the files in `/var/ossec/logs/archives` can be stored in Elasticsearch by enabling the Filebeat configuration `filebeat.yml` in the manager (which you could access in `/etc/filebeat/filebeat.yml` in the host of your manager) the enabled of archives (set it to true) and would have to restart Filebeat (which you could do with a `service filebeat restart` or `systemctl restart filebeat`).
```
filebeat.modules:
  - module: wazuh
    alerts:
      enabled: true
    archives:
      enabled: true

```
Also regarding what you tell us about archives activated in the manager, this would be taking up a lot of space since it would save all the logs.
Our advice would be if you pass these logs to Elasticsearch, that you add a log retention policy for a range of time, for which I leave you this [link](https://wazuh.com/blog/wazuh-index-management/).

**Comment by frankeros** [comment]
Hi @landgekr 
were you able to solve your problem?

**Comment by frankeros** [comment]
Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our [slack channel](https://wazuh.com/community/join-us-on-slack/) or subscribe to our [mailing list](https://groups.google.com/forum/#!forum/wazuh).
