### ISSUE TITLE
Format Windows permissions in FIM inventory

### ISSUE THREAD

**Issue by Molter73** [wazuh/wazuh-kibana-app#3370]
As described in wazuh/wazuh#8585, we will be changing how we store permissions in the inventory for Windows from a string with a custom format to JSON. In order for users to properly visualize this JSON, some changes might be required in the Integrity Inventory section for them to properly fit the screen.

**Comment by CPAlejandro** [comment]
**Current State**
Pending to https://github.com/wazuh/wazuh/pull/9765
