### ISSUE TITLE
Compatibility with Kibana latest version

### ISSUE THREAD

**Issue by pauloroberto-vortx** [wazuh/wazuh-kibana-app#3375]
Hi, do you have any plans to update the Wazuh Plugin to work on the latest version of Kibana?

**Comment by frankeros** [comment]
Hi @pauloroberto-vortx 
we are working to provide support to Kibana 7.12 and it will be released possibly next month.
Regarding to 7.13 is in our road map provide support too in the coming months.
If you have any other questions, please don't hesitate to ask.
Regards.

**Comment by frankeros** [comment]
I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our [slack channel](https://wazuh.com/community/join-us-on-slack/) or subscribe to our [mailing list](https://groups.google.com/forum/#!forum/wazuh).
