### ISSUE TITLE
Wazuh initialization failing when Elasticsearch contains more than 10 index patterns

### ISSUE THREAD

**Issue by JPLachance** [wazuh/wazuh-kibana-app#338]
Greetings again! 😄 

After a long investigation, I finally figured out that [the Elasticsearch query to list index patterns](https://github.com/wazuh/wazuh-kibana-app/blob/8c1b72406c8cc721fe2c3d1e1aa34baf53c4d077/server/api/wazuh-elastic.js#L127) is only querying the first 10 patterns.

Listing only the first 10 results is the default behavior in Elasticsearch:
![screen shot 2018-03-23 at 17 32 51](https://user-images.githubusercontent.com/3448802/37854423-40ccac6c-2ec1-11e8-83c1-b76dd495efee.png)

So, in the UI, the [checkPatterns](https://github.com/wazuh/wazuh-kibana-app/blob/6b89fa1b84b76c678bcbf932f0493d4d3bb16e2b/public/controllers/health-check.js#L21) function is always failing even if the pattern exists because it's the last one in the list of 51 patterns.

It means that on any Elasticsearch installation with more than 10 index patterns, the Wazuh application initialization may fail randomly or all the time.

Solution: add the `size` parameter in the Query!
![screen shot 2018-03-23 at 17 52 41](https://user-images.githubusercontent.com/3448802/37854860-14f4456c-2ec3-11e8-920b-e93d150f6ced.png)

In the [Kibana source code](https://github.com/elastic/kibana/blob/f93b76285b0fec16306a1c28b3fe91d8d80d8b14/src/core_plugins/kibana/public/management/sections/objects/_objects.js#L13), we can see they solved that issue by querying the first 10000 results. I think it could be a safe bet!

Thanks for your time!

**Comment by havidarou** [comment]
Hi @JPLachance ,

you are certainly right!

We will take this into consideration for the next release!

Thank you very much.

Regards.

**Comment by jesusgn90** [comment]
@JPLachance as we discussed on the other issue, this is going to be fixed on [https://github.com/wazuh/wazuh-kibana-app/pull/339](https://github.com/wazuh/wazuh-kibana-app/pull/339) so I'm going to close this issue.

One more time, thanks for your feedback and your support, it's great @JPLachance !

Best regards,
Jesús
