### ISSUE TITLE
Research info about the module

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3380]
| Wazuh version | 
|---|
|4.3.0|

### Research info about the module

We need to research information about the Office365 module.
- Look for sample alerts
- Get to know subscription schemas
- Evaluate the information that deserves to be highlighted to use in visualizations and the custom tab

**Comment by mpRegalado** [comment]
The data provided by the `office365 API` is stored in the alert log and sent to the elastic index through the usual channels. The data is obtained through a set of subscriptions that the user can opt in or out of through the configuration file.

The data stored in the elastic index follows the same pattern as other alerts and contains an object in `data.office365` that passes all the information collected from the `office365 API` [as described in their documentation](https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema). It also provides a `Subscription` field that informs which of the subscriptors that are enabled provided this report.
