### ISSUE TITLE
[Module] [GitHub] Dashboard design proposal

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3382]
| Wazuh version | 
|---|
|4.3.0|

Parent issue: #3372

Hello team,

According to #wazuh/wazuh-kibana-app/issues/3372 , we are to incorporate the new GitHub section in the App.
Also, we need a design for the section to the information provided. We need to create the UX ensuring the easy and intuitive reading and searching of the whole info

At the end of this EPIC, these tasks should be done:

- [x] Research and propose ta design of the GitHub Module section.
- [ ] Create and add the visualizations

**Comment by eze9252** [comment]
![github3](https://user-images.githubusercontent.com/36004787/123246160-c73a0600-d4e5-11eb-9187-2912d16e08f0.png)
![github2](https://user-images.githubusercontent.com/36004787/123246166-c7d29c80-d4e5-11eb-8ab0-6cf72c0f1bc8.png)
![github1](https://user-images.githubusercontent.com/36004787/123246169-c86b3300-d4e5-11eb-9871-a5522e4ac3e7.png)

**Comment by Desvelao** [comment]
### Changes
- Added metrics by unique count of: `Organizations` , `Repositories` and `Actors`
- Modified the style of `Top alert type by Organization` visualization

Screenshot
![image](https://user-images.githubusercontent.com/34042064/123829918-22fbf900-d903-11eb-805a-2c96fb6351cc.png)
