### ISSUE TITLE
Create a base module for the office365

### ISSUE THREAD

**Issue by mpRegalado** [wazuh/wazuh-kibana-app#3391]
There should be a module for office 365 accessible through the navigation menu to build the rest of the functions upon.

This module should meet the following requirements:

- [x] It appears in the navigation menu in the `Modules` submenu
- [x] It appears as an entry in the modules directory with an adequate icon.
- [x] You can toggle it through the `settings/modules` menu

**Comment by sortizowlh** [comment]
Closed with [this commit](https://github.com/wazuh/wazuh-kibana-app/commit/7105b65ca7c27abe9aa7c59e78911686db247e7c)
