### ISSUE TITLE
[Module] [Github] Panel for exploring the module capabilities

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#3403]
| Wazuh version | 
|---|
|4.3.0|

Parent issue: #3372

### Create a tab for exploring the module capabilities
TODO
- [x] Create mockup
- [x] Develop the view following the approved mockup

**Comment by CPAlejandro** [comment]
As a possible proposal:
**Create a table very similar to that of Miter / Intelligence in which:**
-  You can move a table of `Action Category` or `Organization` or `Actors` or any other field that may be relevant, which we could choose with a selector at the top right
-  Then when selecting any of these categories, the subgroup that would have of this will be shown on the left (all the different actions/organizations/... with a counter showing the number of times each one appears)
-  On the right, we would show a table with information about this, in the case of choosing `Action Category` we could the `sub-actions, the actor, the organization, and the description, and when clicking to open a flyout with all the information about it (Something similar to JSON but better presented)

**Comment by Desvelao** [comment]
Info

We can search partial search in the field `data.github.action` using the `wildcard` query, like:
```
GET _search
{
  "query": {
    "wildcard": {
      "data.github.action": {
        "value": "repo*"
      }
    }
  }
}
```

**Comment by eze9252** [comment]
![Captura de pantalla de 2021-06-28 16-14-47](https://user-images.githubusercontent.com/36004787/123651795-13f64780-d82c-11eb-9c1d-a7c5cd02f399.png)
![Captura de pantalla de 2021-06-28 16-09-02](https://user-images.githubusercontent.com/36004787/123651798-148ede00-d82c-11eb-8bd4-3f84b22f35e6.png)
![Captura de pantalla de 2021-06-28 16-05-29](https://user-images.githubusercontent.com/36004787/123651801-15277480-d82c-11eb-91d1-df48a098e9a9.png)

**Comment by Desvelao** [comment]
We are going to use the same structure that defines here: https://github.com/wazuh/wazuh-kibana-app/issues/3422

Until we get a final version and create the components. We could explore how to expose the important information of the module.

We could consider the next approach:

Main view:
Highlighted entities:
  - Organizations
  - Repositories
  - Actors
  - Action types?
  
 Detail view:
 - Organizations:
   - Visualizations: Alert evolution, top repositories, top actors, top action types
   - Table to explore the alerts
  - Repositories:
    - Visualizations: Alert evolution, top actors, top action types
    - Table to explore the alerts
  - Actors:
    - Visualizations: Alert evolution, top organizations, top actors, top action types
    - Table to explore the alerts
   - Action types:
    - Visualizations: Alert evolution, top organizations, top repositories, top actors,
    - Table to explore the alerts

**Comment by Desvelao** [comment]
We created a view as it is used in the Office 365 module.

The main menu contains:
- Search bar with simple mode with has some selectors for User, Organization, Repositories and Actions
- Aggregation table for each entity (User, Organization, Repositories and Actions) that displays the count of alerts with that entity. Each row of these tables opens a drill-down view.

- Drill-down views
  - User
![image](https://user-images.githubusercontent.com/34042064/129195163-35bb4387-35b1-4f0c-a4be-424053c267f7.png)
  - Organization
![image](https://user-images.githubusercontent.com/34042064/129195761-468fa111-ea47-45b0-a5c8-dd572710b629.png)
  - Repository
![image](https://user-images.githubusercontent.com/34042064/129195847-378d844f-dfb3-4489-80c9-dbc7e21707bd.png)
  - Actions
![image](https://user-images.githubusercontent.com/34042064/129195923-db8472de-618c-478d-840f-8563d6de7212.png)
