### ISSUE TITLE
count data.win.eventInfo.bytesReceived or data.win.eventInfo.bytesTransfered

### ISSUE THREAD

**Issue by hastaki** [wazuh/wazuh-kibana-app#3414]
Hello
I have logs of this type

![img](https://user-images.githubusercontent.com/86711270/123928228-65224a80-d996-11eb-93ea-7fe300d05751.PNG)

I want to receive the amount of bytes in the dashboard (data.win.eventInfo.bytesReceived or data.win.eventInfo.bytesTransfered),tell me how you can implement this

**Comment by gabiwassan** [comment]
Hi @hastaki , at the moment you cannot add a dashboard, just modifying the code. 
But you can create your own dashboard, you should create a new Dashboard from `Kibana / Dashboard` 

![image](https://user-images.githubusercontent.com/26828184/120853913-bcc5c580-c552-11eb-9e16-5f4995f2cedb.png)

You could find helpful these links 
https://documentation.wazuh.com/current/user-manual/kibana-app/reference/custom-dashboard.html?highlight=dashboard
https://www.elastic.co/guide/en/kibana/current/dashboard.html

Regarding allowing the user to only see this dashboard you should use some security plugins for Kibana: X-Pack, or Opendistro.

You can check our tutorial for installations with [Opendistro](https://documentation.wazuh.com/current/installation-guide/open-distro/all-in-one-deployment/all_in_one.html#installing-elasticsearch)

Then you should create a custom workspace ([tenant](https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/multi-tenancy/#add-tenants) for Opendistro [space](https://www.elastic.co/guide/en/kibana/7.x/xpack-spaces.html) for X-Pack) then map the user into the new workspace. The dashboard should be created into this workspace.

If you need more information about any of these steps, please let me know.
Regards

**Comment by gabiwassan** [comment]
Hi @hastaki, at the moment you cannot add a dashboard into the Wazuh App, just modifying the code.
But you can create multiple visualizations and add them to a customized dashboard in Kibana.
`Kibana / Visualization`
`Kibana / Dashboard`

![image](https://user-images.githubusercontent.com/26828184/120853913-bcc5c580-c552-11eb-9e16-5f4995f2cedb.png)

Here you can select your fields:
![image](https://user-images.githubusercontent.com/11060558/123971528-85e7a180-d990-11eb-9c04-859790fafcb5.png)

You could find helpful these links
https://documentation.wazuh.com/current/user-manual/kibana-app/reference/custom-dashboard.html?highlight=dashboard
https://www.elastic.co/guide/en/kibana/current/dashboard.html
https://www.elastic.co/guide/en/kibana/current/visualize.html

If you need more information about any of these steps, please let me know.
Regards

**Comment by hastaki** [comment]
> Привет @hastaki , на данный момент вы не можете добавить панель инструментов в приложение Wazuh, просто изменив код.
> Но вы можете создать несколько визуализаций и добавить их на настраиваемую панель управления в Kibana.
> `Kibana / Visualization`
> `Kibana / Dashboard`
> 
> ![изображение](https://user-images.githubusercontent.com/26828184/120853913-bcc5c580-c552-11eb-9e16-5f4995f2cedb.png)
> 
> Здесь вы можете выбрать свои поля:
> ![изображение](https://user-images.githubusercontent.com/11060558/123971528-85e7a180-d990-11eb-9c04-859790fafcb5.png)
> 
> Вы можете найти полезные эти ссылки
> [https://documentation.wazuh.com/current/user-manual/kibana-app/reference/custom-dashboard.html?highlight=dashboard ](https://documentation.wazuh.com/current/user-manual/kibana-app/reference/custom-dashboard.html?highlight=dashboard)
> [https://www.elastic.co/guide/en /kibana/current/dashboard.html ](https://www.elastic.co/guide/en/kibana/current/dashboard.html)
> https://www.elastic.co/guide/en/kibana/current/visualize.html
> 
> Если вам нужна дополнительная информация о любом из этих шагов, дайте мне знать.
> С Уважением

I still can't do exactly the addition of bytes.
Either I do not understand your answer, or recommendations

**Comment by gabiwassan** [comment]
Sorry but maybe I didn't understand what you need, in order to be able to help you, can you tell me where do you need to see these fields exactly? can you specify what dashboard are you talking about?
Best!

**Comment by hastaki** [comment]
> Sorry but maybe I didn't understand what you need, in order to be able to help you, can you tell me where do you need to see these fields exactly? can you specify what dashboard are you talking about?
> Best!

I get data by the number of bytes transferred per RDP session
 user per day enters a session several times, I want to get the amount of bytes per day
But when you try to select this line in the search, it is missing
![hub](https://user-images.githubusercontent.com/86711270/124588224-39ed9e80-de61-11eb-8bc5-da9969b684e2.png)
data.win.eventInfo.bytesReceived or data.win.eventInfo.bytesTransfered
as I understand it, the reason is that these data are not numbers or dates
