### ISSUE TITLE
Add the ability to change monitoring index creation frequency

### ISSUE THREAD

**Issue by JPLachance** [wazuh/wazuh-kibana-app#344]
Greetings! 😄 

This one is a feature request!

At the moment, the Wazuh Kibana application is creating one index per day to store monitoring events. Let's suppose we drop indices after 90 days, using Wazuh on top of our current Elasticsearch cluster will, after 90 days, have created 90 indices to store those monitoring events.

Those indices are not very large. Would it be possible to give us the ability to create one index per week instead of per day?

Best regards and thanks for your help!

**Comment by havidarou** [comment]
Hi @JPLachance ,

we can take this into consideration for a future release, see if there aren't any other implications, etc.

Thanks for your feedback! I'll keep you updated.

Regards.

**Comment by jesusgn90** [comment]
Hello @JPLachance and @havidarou , 

one point here is we can remove single-day index whenever an index is malformed or corrupt for any reason. This is not so strange as you can think guys, wrong template, wrong Logstash, etc. you know.

On the other hand it could be a good enhacement for sure. From my view it could be an optional configuration and preserving single-day index by default. This way we leave the experimented user to set a desired frequency but not break with new users.

No commit has been added to this feature, it was only to join this discussion.

Regards,
Jesús

**Comment by JPLachance** [comment]
Hello @jesusgn90,

I agree it should be an optional configuration. The reason why we need that it because our Elasticsearch cluster is already quite big (more than 700 indices). Adding a new tool that creates one index per day is noticeable.

Giving us the ability to create an index per week instead of per day would reduce the footprint of the Wazuh Kibana application in our cluster.

Regards,

Jean-Philippe Lachance

**Comment by jesusgn90** [comment]
Hi @JPLachance after discussing with the team, we concluded the next improvements for the wazuh-monitoring management: https://github.com/wazuh/wazuh-kibana-app/issues/440, track that issue to stay updated. It will fit some of your needs and some of our users needs. Maybe in a future release we'll be closer to your ideas but this time it implies important architecture decissions, any case you are always welcome.

Best regards,
Jesús
