### ISSUE TITLE
Support for Elastic Stack 7.12 

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-kibana-app#3461]
Hello team,

I'm opening this issue to ask for Elastic Stack support for 7.12 and the Wazuh 4.2.0 version.

Reference: https://www.elastic.co/guide/en/elasticsearch/reference/7.12/release-highlights.html

Regards,

Miguel Casares

**Comment by rulai-jianfang** [comment]
Same here, 7.10 and 7.11 will fail on gvm vulnerability scan, thanks!

**Comment by frankeros** [comment]
Hello, the support for 7.12 was included in 4.2.1, we expect it to be released in the next month. 

I'm closing this issue now.
