### ISSUE TITLE
Add the capability of customize the logo of the app

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3491]
|Target version | 4.2.1 |
|---|---|

**Describe the solution you'd like**
Several users have the need to customize the logo of the app, currently, it could be performed by replacing the logo file with the new one with the same file name, but there are some styles that are affecting the logo and they can't be customized.

We need to remove these hardcoded styles and add the capability to customize the logo in an easy way.

**Describe alternatives you've considered**
We could add an optional configuration to achieve this.

**Comment by matiasmoreno876** [comment]
> Steps to reproduce

1. Go to Settings/Configuration
2. Search the section` Logo Customization`
![image](https://user-images.githubusercontent.com/49887871/127556630-1c091d79-2818-4af7-8c57-f599399a29d9.png)
3. Define the name to the app logo, logo sidebar and health check.
4. You have to add the new logos in the `/usr/share/kibana/plugins/wazuh/public/assets` path inside the Kibana container
![image](https://user-images.githubusercontent.com/49887871/127556763-ac7350a6-160d-4b8b-a24e-2a8120b24de5.png)
example: `icon_blue_2.svg `and `logotype-2.svg`
5. Change the name and save
![image](https://user-images.githubusercontent.com/49887871/127556876-1186a908-39cc-4f80-bdd8-9ae2a38392e3.png)
![image](https://user-images.githubusercontent.com/49887871/127556905-616e4d43-386b-4bb8-aa24-94317f109c9b.png)
![image](https://user-images.githubusercontent.com/49887871/127556926-7d54ecba-f558-4fd9-a0ef-9c8467b05764.png)

**Comment by frankeros** [comment]
We need to change the logo in reports too
please move the path to the description, the user should only set the name

**Comment by matiasmoreno876** [comment]
Done!
![image](https://user-images.githubusercontent.com/49887871/127694420-ea82915c-14a3-4be5-8bbc-868009371ea6.png)

Now the logos of the following reports can be modified.
List of affected reports:

- Security events
- Integrity monitoring
- Policy monitoring
- System auditing
- Vulnerabilities
- MITRE ATT&CK
- PCI DSS
- GDPR
- HIPAA
- NIST 800-53
- TSC
- Agents

![image](https://user-images.githubusercontent.com/49887871/127695128-b6305e05-ab7d-4e68-9d63-ccd39d050c23.png)
