### ISSUE TITLE
New feature for the vulnerability module: "host infected summary"

### ISSUE THREAD

**Issue by mradaszewski92** [wazuh/wazuh-kibana-app#3501]
<html><body>

Wazuh | Elastic | Rev
-- | -- | --
4.1.5 | 7.10.2 | 4107

</body>
</html>

**Describe the solution you'd like**
Hi team, Please kindly add a new endpoint to REST Api to summarize the amount of vulnerability you have on the host. At the moment, it is not possible to download information about how vulnerable the system is, and this is useful in larger organizations where vulnerabilities are managed, e.g. from the level of Jira.

**Describe alternatives you've considered**

**Additional context**

**Comment by frankeros** [comment]
Hi, @mradaszewski92 thanks for using Wazuh

We already added a new section in the Vulnerabilities module which has similar that what you need

![image](https://user-images.githubusercontent.com/26828184/127191967-fc178b4f-b86b-463f-9452-8c651bf3d080.png)

The endpoint that it is using is `GET /vulnerability/:agent_id`, both the endpoint and the section will be released with the 4.2.0 version in the next weeks.

I'm closing this issue. If you have any questions, you can also use our [slack channel](https://wazuh.com/community/join-us-on-slack/) or subscribe to our [mailing list](https://groups.google.com/forum/#!forum/wazuh).

**Comment by mradaszewski92** [comment]
I can not wait !! Thank you !
