### ISSUE TITLE
Managing mash modules: Blocking individual modules for users created in kibana or logged in by AD

### ISSUE THREAD

**Issue by mradaszewski92** [wazuh/wazuh-kibana-app#3502]
**Describe the solution you'd like**
Dear team,
Please add to your "road map" the function of managing access to selected Wazuha modules from the Kibana level. The problem arises in larger organizations, above 1k + employees.
It is about blocking the ability to open (and preview) selected Wazuh modules (SCA, Vulnerability, File integiry monitoring) with permissions. Is it even possible?

**Describe alternatives you've considered**

**Additional context**

**Comment by eze9252** [comment]
Hi @mradaszewski92 

You can´t hide this modules. If you want to prevent certain users from seeing certain alert information, you could limit the permissions offered by the security plugin you are using. Thus when entering the module, despite being able to enter and see the views it has, no information will be displayed.

Regards

**Comment by frankeros** [comment]
Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our [slack channel](https://wazuh.com/community/join-us-on-slack/) or subscribe to our [mailing list](https://groups.google.com/forum/#!forum/wazuh).
