### ISSUE TITLE
Error when trying to add a new decoder with an escaped `<` character

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh-kibana-app#3504]
| Wazuh | Elastic | 
| ----- | ------- | 
| 4.1.0   | 7.10.2  |

**Description**

There is an [error](https://wazuh-team.slack.com/archives/C038AR25C8N/p1667231342070619?thread_ts=1667218264.604339&cid=C038AR25C8N) when trying to add a new decoder with an escaped `<` character from the Wazuh APP.
The decoder is added successfully and no errors appear when adding the decoder to the XML decoder file without using the APP.

For example, if we try to add the following decoder:

```
<decoder name="custom-1">
    <prematch>\<\d+>something</prematch>
</decoder>
```

There will be an error with the following message:

`element parse error: invalid tagName: \d+
`

`tagName` will vary depending on what is following the `<` character.

This error does not appear if we try to escape a different character from the ones that must be escaped: [Characters escaping](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/regex.html) section of the Wazuh documentation.

**Steps to reproduce**

1. Go to **Wazuh/management/decoders**
2. Click on **add new decoders file**
3. Write a decoder including the **<** character escaped.

**Screenshots**

![image-issue](https://user-images.githubusercontent.com/57481331/127287291-6e93e421-d2e5-48c8-b978-1af798711b0c.png)

**Comment by asteriscos** [comment]
After testing this issue by making a curl request to Wazuh API, **seems the API also does not support escaping characters in the decoders XML**.

Related Issue: 
https://github.com/wazuh/wazuh/issues/7777

For further information see the attached request dump file.
[debugdump.txt](https://github.com/wazuh/wazuh-kibana-app/files/7129566/debugdump.txt)
