### ISSUE TITLE
Virustoatl

### ISSUE THREAD

**Issue by Sivavamsiraju** [wazuh/wazuh-kibana-app#3514]
How to integrate the virus total in the wazuh Cloud

help me on this.....

Thanks in Advance.

**Comment by mikykeane** [comment]
Hello @Sivavamsiraju , 

I have sent you an email so we can continue our conversation there. 

But summarizing, the Virustotal integration works exactly the same in Wazuh Cloud than On-Prem. Here is our documentation: https://documentation.wazuh.com/current/upgrade-guide/elasticsearch-kibana-filebeat/upgrading-open-distro.html#upgrading-kibana

The difference is that you need to configure Wazuh through the UI in Kibana. 

Best regards, 
Miguel Keane

**Comment by Sivavamsiraju** [comment]
it was working @mikykeane thanks for the guidence
