### ISSUE TITLE
Respect the kibana.index parameter when storing saved searches, visualizations and dashboards

### ISSUE THREAD

**Issue by JPLachance** [wazuh/wazuh-kibana-app#352]
Greetings!

In the `kibana.yml`, there is a cool parameter, `kibana.index`. The default value is `.kibana`, but we can put whatever we want there, for example, `kibana.index: ".wazuh_kibana"`. 😃 

That parameter defines where Kibana stores saved searches, visualizations and dashboards. See the [Kibana configuration documentation](https://www.elastic.co/guide/en/kibana/current/settings.html).

At the moment, the use of the `.kibana` index is hardcoded at many places in the Wazuh Kibana application code. [Here is an example](https://github.com/wazuh/wazuh-kibana-app/blob/9990a63a42df395b2acee828635662da77fdd565/server/api/wazuh-elastic.js#L77). Therefore, went we try to change the `kibana.index` parameter value, the Wazuh Kibana application is not working.

Instead of using `.kibana`, would it be possible to read the `kibana.index` value and use it?

Thanks for your help!

**Comment by havidarou** [comment]
Hi @JPLachance ,

you are right and this wouldn't take us much effort, so probably will be ready in the next relase.

Regards!

**Comment by jesusgn90** [comment]
Hi @JPLachance ,

awesome feedback as always, you are a great user for us. On the other hand I want to announce you we've added this to our roadmap and I'm currently testing this feature added on https://github.com/wazuh/wazuh-kibana-app/commit/d4ba9fb2c2e1c2c7a105b9c3668c5f0b2b53f0eb , from now and onward we will always respect the kibana.yml specific index. You need to wait for next packages to see it in action, any case you can track the branch [3.2-xpack-rbac](https://github.com/wazuh/wazuh-kibana-app/tree/3.2-xpack-rbac) if interested on it. Thanks!

Best regards,
Jesús

**Comment by JPLachance** [comment]
This is awesome! Thanks :)

**Comment by jesusgn90** [comment]
Hi @JPLachance , your comments are always welcome and we take them into consideration, some features take more time than other but as you can see, we research about them.

Have a nice day!
