### ISSUE TITLE
Regression 4.2.0 with core v4.2.0-RC13

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3538]
| Wazuh | Revision | RC | Core RC |
| --: | --: | --: | --: | 
| 4.2.0 | 4201 | 10 |  x  |

Hello team, in order to check the quality of the app 4.2.0 r4201 we need to perform these tasks
- [x] Planning regression of revision
 ### Objective:
 This regression should determine if there are new bugs using the new release candidate of Wazuh. 
 We are going to make more emphasis on test cases that use Wazuh API than ElasticSearch API.

### Planned environments
|distro|browser|kibana v|    
| -- | -- | -- | 
|ODFE (1.13.2)|Chrome|7.10.2|
|Xpack|Firefox|7.11.2|

- [x] Execution of the regression

Environment | Status | total | Pass | Review | KO
-- | -- | -- | -- | -- | --
ODFE - Chrome - 7.10.2 | pending | 150 - 0% | 91 - 61% | 57 - 38% | 2 - 1%
Xpack - Firefox - 7.11.2 | pending | 150 - 0% | 139 - 93% | 7 - 5% | 4 - 3%

- Additional tests:

 Scenarios | Pass |
-- | -- |
 Rulesets -CRUD rules, decoders, lists | [x] |
 Operations with Agents | [x] |
 Operations with Agent groups | [x] |
 Operations with Cluster configurations | [x] |
 Statistics and monitoring frequency tuning | [x] |
 Modules - FIM - Inventory | [x] |
 Modules - Mitre - Framework | [x] |
 Modules - Vulnerabilities - Inventory | [x] |
 Modules - Security config assessment - Inventory | [x] |
 Modules - Regulatory compliane - Controls | [x] |
 
>Found Errors:
- https://github.com/wazuh/wazuh-kibana-app/issues/3576 `'Export formated' button does not work`
- https://github.com/wazuh/wazuh-kibana-app/issues/3577 `Logs are not ordered descending as toggle says`
- https://github.com/wazuh/wazuh-kibana-app/issues/3578 `Logging out of the API should deprecate the token`
- https://github.com/wazuh/wazuh-kibana-app/issues/3579 `Index pattern selector not displayed`

>Cosmetic Errors:
- https://github.com/wazuh/wazuh-kibana-app/issues/3580 `Process table sorting treats numbers as strings`
- https://github.com/wazuh/wazuh-kibana-app/issues/3581 `Resizing the browser window has some responsive inconsistencies`

>Opportunities to Upgrade:
- https://github.com/wazuh/wazuh-kibana-app/issues/3582 `Add a loader to every raw data download link (csv, json files, etc)`
- https://github.com/wazuh/wazuh-kibana-app/issues/3583 `Open documentation links in a new browser tab`

**Comment by AlexRuiz7** [comment]
Tests for Wazuh 4.2.0-rc12 on a [ODFE - Chrome - 7.10.2] environments are near to completition.

Check the status [here](https://docs.google.com/spreadsheets/d/1jq9PtOveZELhI2LNaZHJAqu2vlqQwop3iZx1QPx60Lk/edit#gid=896433239).

**Comment by matiasmoreno876** [comment]
> ## Test Run in Safari - 7.10.2 - 4.2.0-rc13:

- [x] CRUD Rules
- [x] Exploratory testing in the view of Rules
- [x] CRUD Decoders
- [x] Exploratory testing in the view of Decoders
- [x] CRUD CDB List 
- [x] Exploratory testing in the view of CDB List

> ## Errors Found

- Timeout: The 'Export Formatted' button does not work, in Management --> Rules
![Grabación de pantalla 2021-08-17 a la(s) 12 13 58](https://user-images.githubusercontent.com/49887871/129790590-a23d7733-356b-471c-aa76-de09ab2f7e7f.gif)

> ## Upgrade opportunity found

- Add a loader when we execute 'Export Formatted'. In the Rules, Decoders, and CBD List views

**Comment by MauGaP** [comment]
> Test Run Chrome - 7.11.2 - v4.2.0-rc13
[ ] Rules (CRUD)
[ ] Decoders (CRUD)
[ ] CBD Lists (CRUD)
[ ] operations with agents and agents groups:
 - view agents details
 - add a new agent
 - create agents group
 - delete agents group 
 - exploratory testing with dowloads (reports, etc)
 - validating agent files
> Errors found: none

**Comment by AlexRuiz7** [comment]
# Test Run in Firefox - 7.11.2 - v4.2.0-rc13
54% of tests have been completed.
## Completed tests
The following test sets have been completed:
- [X] Overview UI
- [X] Mangement status
- [X] Management home UI
- [X] Management - Cluster
- [X] Management - Logs
- [X] Management - Reporting
- [ ] Management - Ruleset (3 tests still TBD)
- [ ] Management - Groups (2 tests still TBD)
- [X] DevTools
- [ ] Agents Preview (3 tests still TBD)
- [X] Agent specific UI
- [X] App menu
- [X] Backend jobs - Monitoring
- [X] Backend jobs - Statistics
- [X] Logout security

## Failed tests
These tests have failed, as the app didn't work as expected:

- Management - Logs: descending sort should apply a descending sort
  - Descending sort actually applies an ascending sort.
- Logout security: login out from the app should deprecate the Wazuh API token too 
  - Token is still active after logout and can be used on a curl command to query the Wazuh API.
- App menu: Index pattern selector should show if there is more than one index pattern
  - A new index pattern have been created, but the index pattern selector does not show.
- Agent UI: Inventory tables
  - Network Ports table is only sortable by 2 of the 4 columns. Columns headers use different fonts, depending whether it's sortable or not.
  - Processes table does not sort correctly by the PID, VM size nor Size columns. 
![wazuh-4 2 0-rc13-inventory-processes](https://user-images.githubusercontent.com/15186973/129900085-10a203aa-9c7d-496c-8e71-56c29a2d94ff.gif)

**Comment by matiasmoreno876** [comment]
> ## Test Run in Safari - 7.10.2 - 4.2.0-rc13:

- [x] Operations With Agents
- [x] Full Exploratory testing in the view of Agents
- [x] Operations with Agent groups
- [x] Operations with Cluster configurations

> ## Errors Found

- When you go to the Agents -> Create new agent, and select any configuration to perform, if you click on To verify the connection with the Manager, please follow this document. the link opens correctly in a new tab but without any information to show (broken link)

![Grabación de pantalla 2021-08-18 a la(s) 14 41 14](https://user-images.githubusercontent.com/49887871/129970929-de0ea43e-c4c8-4ab0-af9b-d3672a5e46e8.gif)

> ## Upgrade opportunity found

- When you enter the Agents -> Create new agent, the Wazuh Documentation link opens in the current window, removing the user from the configurations, perhaps the best way would be to show that info in a new window.

![Grabación de pantalla 2021-08-18 a la(s) 14 36 00](https://user-images.githubusercontent.com/49887871/129970980-4eb2ec77-32e8-447e-9046-c63f28b4877c.gif)
