### ISSUE TITLE
Rename field

### ISSUE THREAD

**Issue by hastaki** [wazuh/wazuh-kibana-app#3540]
Hello
I have a field data.win.eventInfo.ipAddress
i need to rename it to data.win.eventdata.ipAddress
To read IPlocation,
how can I do this, if you can write in detail, because I read a lot of instructions and nothing helped me
![image](https://user-images.githubusercontent.com/86711270/128348793-20b2b564-11bf-4d1d-ad16-c8548a34a8ca.png)

**Comment by frankeros** [comment]
Hello @hastaki 
the simplest option to do this for every new log is adding a processor in the ingest pipeline of alerts of the module Wazuh for Filebeat. 

You can find this module in `/usr/share/filebeat/module/wazuh/`, it's installed in the step 4 of this [guide](https://documentation.wazuh.com/current/installation-guide/open-distro/all-in-one-deployment/all_in_one.html#installing-filebeat).
You should add a new processor in `alerts/ingest/pipeline.json` for example

```json
    ...
    {
      "rename":
      {
         "fields":
         {
           "from": "data.win.eventInfo.ipAddress",
           "to": "data.win.eventdata.ipAddress"
         },
         "ignore_missing": true,
         "ignore_failure": true
      }
    },
    ...
```
after that, you need to force Elastic to take the changes running 
```bash
filebeat setup --pipelines
```
then restart all services just in case Filebeat, ElasticSearch, and Kibana

for the older fields maybe you need to re-index the old indices please check [this](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/docs-reindex.html)

please let me know if this was helpful for you

Best!

**Comment by hastaki** [comment]
filebeat setup --pipelines
Exiting: 1 error: Error loading pipeline for fileset wazuh/alerts: couldn't load pipeline: couldn't load json. Error: 400 Bad Request: {"error":{"root_cause":[{"type":"parse_exception","reason":"[field] required property is missing","property_name":"field","processor_type":"rename"}],"type":"parse_exception","reason":"[field] required property is missing","property_name":"field","processor_type":"rename"},"status":400}. Response body: {"error":{"root_cause":[{"type":"parse_exception","reason":"[field] required property is missing","property_name":"field","processor_type":"rename"}],"type":"parse_exception","reason":"[field] required property is missing","property_name":"field","processor_type":"rename"},"status":400}

**Comment by frankeros** [comment]
My bad, the property `fields` is an array, I just fixed the main answer. 
You could set many renames in the same block
```json
    ...
    {
      "rename":
      {
         "fields":
         [
           {
             "from": "data.win.eventInfo.ipAddress",
             "to": "data.win.eventdata.ipAddress"
           },
           {
             "from": "a.g",
             "to": "d.e"
           }
         ],
         "ignore_missing": true,
         "ignore_failure": true
      }
    },
    ...
```

**Comment by frankeros** [comment]
The correct way to use `rename` processor  in this version is

**Comment by frankeros** [comment]
`

**Comment by hastaki** [comment]
thanks
fixed the pipeline file itself
added just one more line there
your team helped
filebeat setup --pipelines
For some reason, I have not seen such a command anywhere
Previously, I fixed this file and no changes occurred, but after this command everything worked
