### ISSUE TITLE
Installing Multiple Wazuh Agent in a single command

### ISSUE THREAD

**Issue by Sivavamsiraju** [wazuh/wazuh-kibana-app#3546]
Hi I am trying to install agents on our enviornment,

And i want to install multiple no of agents in our enviormnent at once using terraform.

CAn any one help me out on this how to configure.

i ahve already installed the wazuh server using the terraform.

Thanks In Advance.

**Comment by eze9252** [comment]
Hi @Sivavamsiraju

**Comment by eze9252** [comment]
Hi @Sivavamsiraju 

You can configure a orchestration tool that run a command on each agent host. When you define each agent machine you can add a command that installs the agent. More information about the [agent installation commands](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/index.html)

Currently Wazuh works with several orchestration tools that are not exactly like Terraform but maybe can help with your issue and you can check it in the link our repo:

- [ansible](https://github.com/wazuh?q=ansible&type=&language=) 
- [puppet](https://github.com/wazuh?q=puppet&type=&language=)
- [chef](https://github.com/wazuh?q=chef&type=&language=)
- [bosh](https://github.com/wazuh?q=bosh&type=&language=)
- [salt](https://github.com/wazuh?q=salt&type=&language=)

About Terraform, generally is used to Cloudformation,  we also provide an example of using [Terraform in AWS ](https://github.com/wazuh/wazuh-cloudformation)with the templates for the Cloudformation and you can use it in other clouds platforms as well.

Regards.

**Comment by frankeros** [comment]
Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our [slack channel](https://wazuh.com/community/join-us-on-slack/) or subscribe to our [mailing list](https://groups.google.com/forum/#!forum/wazuh).
