### ISSUE TITLE
you may not have wazuh alerts indice environment

### ISSUE THREAD

**Issue by raksinfo** [wazuh/wazuh-kibana-app#3547]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.x   | 6.x     | 444 |

**Description**
Short description of your issue.

**Steps to reproduce**

**Screenshots**

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by Desvelao** [comment]
Hi @raksinfo 
It seems you could not have indices related to Wazuh alerts or alerts which don't match the filters in some place of the app.

Could you post a screenshot of the error you are getting and the place in the app where it is happening?
What version of the Wazuh app for Kibana are you using?

**1. Check you have alert indices on Elasticsearch**
Using the Kibana Dev tools, see the screenshot.
```
GET /_cat/indices
```
![image](https://user-images.githubusercontent.com/34042064/129149480-6b786c0e-da70-4ec1-bd08-ac21d2f6cf8b.png)

As you can see in the results of the request, I have some indices of Wazuh alerts called `wazuh-alerts-YYYY-MM-DD` (YYYY=year, MM=month, DD=day). If you are using a version of Wazuh as 3.x, your indices could be called as `wazuh-alerts-3.x-YYYY-MM-DD`.

If you don't have indices related to Wazuh alerts, you could have some problem with Filebeat, which forwards the alerts generated for Wazuh managers to Elasticsearch.

**2. Check the `Filebeat-Elasticsearch` connection**
In the Wazuh manager, execute the next command:
```
filebeat test output
```

**Comment by frankeros** [comment]
Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our [slack channel](https://wazuh.com/community/join-us-on-slack/) or subscribe to our [mailing list](https://groups.google.com/forum/#!forum/wazuh).
