### ISSUE TITLE
keep getting blank page in wazuh-kibana-app v4.1.5-7.10.2

### ISSUE THREAD

**Issue by ScRiPt1337** [wazuh/wazuh-kibana-app#3548]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.5   | 7.10.2    | 444 |

**Description**
keep getting blank page if I build wazuh-kibana-app v4.1.5-7.10.2 in my own machine

**Steps to reproduce**

1. Go to https://github.com/wazuh/wazuh-kibana-app/releases/tag/v4.1.5-7.10.2
2. Download source code.zip
3. run command yarn install && yarn build
4. install the zip from build dir as kibana plugin

**Screenshots**
[screenshot](https://i.ibb.co/KqHk9XC/Capture.png)

**Additional context**
distro : ubuntu 20.04
node version : v14.17.4
nvm version : 0.35.3
yarn version : 1.22.5
i am getting this error in console
kbn-ui-shared-deps.js:434 TypeError: Cannot read property 'jsx' of undefined
    at wz_agent_selector_wrapper_WzAgentSelectorWrapper.render (wazuh.chunk.2.js:62)
    at Ka (kbn-ui-shared-deps.js:434)
    at Ga (kbn-ui-shared-deps.js:434)
    at Ms (kbn-ui-shared-deps.js:434)
    at gl (kbn-ui-shared-deps.js:434)
    at fl (kbn-ui-shared-deps.js:434)
    at ol (kbn-ui-shared-deps.js:434)
    at el (kbn-ui-shared-deps.js:434)
    at $l (kbn-ui-shared-deps.js:434)
    at kbn-ui-shared-deps.js:434

**Comment by frankeros** [comment]
Hello @ScRiPt1337, thanks for using Wazuh!

This is a known issue updating the Wazuh plugin for the same Kibana version. 
Kibana gets the static bundles with cache headers, so the browser keeps the in cache the old Wazuh plugin bundles generating conflicts with the new ones. 
The easy way to solve this is by forcing the browser to disable the cache for the first time after update the plugin.
Please follow this [guide](https://documentation.wazuh.com/current/user-manual/kibana-app/troubleshooting.html#wazuh-kibana-plugin-page-goes-blank) to do it.

Best!

**Comment by ScRiPt1337** [comment]
my cache is already disabled and i update the plugin according to [docs](https://github.com/wazuh/wazuh-kibana-app#wazuh---kibana---open-distro-version-compatibility-matrix)

**Comment by frankeros** [comment]
is the problem still there with the cache disabled?

**Comment by ScRiPt1337** [comment]
> is the problem still there with the cache disabled?

yes I am still having the same problem

**Comment by ScRiPt1337** [comment]
> normally this problem is solved by following the guide that I mentioned before.
> https://documentation.wazuh.com/current/user-manual/kibana-app/troubleshooting.html#wazuh-kibana-plugin-page-goes-blank
> 
> Are you using a different browser than the ones mentioned in the guide?
> does the problem occur in incognito or private mode?

yes I already tried them and yes the problem  occur   in incognito too

**Comment by frankeros** [comment]
>  I am having the issue I successfully build the zip file but when I install it I am getting the blank screen and the error in console

how are you building the code? are you using Kibana dev?
You can find the steps to build the app in the [wiki](https://github.com/wazuh/wazuh-kibana-app/wiki/Build-Wazuh-app-package#building-wazuh-app-package-for-kibana-710-or-higher) of this repo

**Comment by ScRiPt1337** [comment]
It fixed thanks for the wiki I should not use the main branch for build the plugin
