### ISSUE TITLE
Wazuh App: Please set up Wazuh API credentials.

### ISSUE THREAD

**Issue by singhmona27** [wazuh/wazuh-kibana-app#3572]
| Wazuh | Kibana | 
| ----- | ------- | 
| 4.1.5   | 7.10.2  | 

**Description**
Click on Wazuh menu at sidebar
this error is coming:

`Wazuh App: Please set up Wazuh API credentials.  
Settings. Error getting API entries  
Cannot initialize Settings`

**Steps to reproduce**
Click on Wazuh menu at sidebar

**Screenshots**

![telegram-cloud-photo-size-5-6120722920067149310-y](https://user-images.githubusercontent.com/81926524/130044486-259dcd77-4e1c-470a-8a57-c49fba5f4d22.jpg)

**Comment by frankeros** [comment]
Hello @singhmona27 
It's a new installation? 

Did you edit your wazuh.yml file to set new Wazuh API credentials? 
Please let me know more info about your environment or the scenario when this problem occurs 
Thanks

**Comment by frankeros** [comment]
Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our [slack channel](https://wazuh.com/community/join-us-on-slack/) or subscribe to our [mailing list](https://groups.google.com/forum/#!forum/wazuh).

**Comment by sayanTlregtech** [comment]
Hey I am also facing the same problem can anyone help me?
