### ISSUE TITLE
Operating system field overlaps with Cluster node field

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-kibana-app#3584]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.2.0   | 7.10.2     | 4201-10 | ODFE |

| Browser |
| ------- |
| Chrome|

The Agent tab for windows shows an overlapping as you can see in the image below:
![image](https://user-images.githubusercontent.com/3830293/130819550-0c76c1b1-0799-46d9-9b55-395e946615a7.png)

The Operating system field overlaps with the cluster node. 

Regards, 
Alberto R

**Comment by yenienserrano** [comment]
it was already solved for version 4.3
