### ISSUE TITLE
[Wazuh v4.2.0 - Kibana v7.11.2] stuck at check page

### ISSUE THREAD

**Issue by LubinLew** [wazuh/wazuh-kibana-app#3588]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.2.0   | 7.11.2     | 4xxx | Basic |

| Browser |
| ------- |
| Chrome(92.0.4515.159), Firefox(91.0.2)|

**Description**
stuck at check page.
if you access other pages from bar, all pages are blank.

**Logs**
```bash
cat /usr/share/kibana/data/wazuh/logs/wazuhapp.log 
{"date":"2021-08-30T06:22:13.934Z","level":"info","location":"initialize","message":"Kibana index: .kibana"}
{"date":"2021-08-30T06:22:13.936Z","level":"info","location":"initialize","message":"App revision: 4201-11"}
{"date":"2021-08-30T06:22:13.937Z","level":"info","location":"initialize","message":"Total RAM: 7821MB"}
```

**Screenshots**
![stuck](https://user-images.githubusercontent.com/12081311/131296025-15777459-85b5-4618-9a55-7699cdacc8f2.png)

![error](https://user-images.githubusercontent.com/12081311/131296340-69224d83-0d65-4084-bfd1-a9154d3dde96.png)
**Additional context**
Install 
```bash
# step0 - install kibana from offical repo
yum install -y kibana-7.11.2

# step1
wget https://github.com/wazuh/wazuh-kibana-app/releases/download/v4.2.0-7.11.2/wazuh_kibana-4.2.0_7.11.2-1.zip
mv wazuh_kibana-4.2.0_7.11.2-1.zip /tmp/
chmod 0666 /tmp/wazuh_kibana-4.2.0_7.11.2-1.zip
sudo -u kibana /usr/share/kibana/bin/kibana-plugin install file:///tmp/wazuh_kibana-4.2.0_7.11.2-1.zip

# step2
# modify /usr/share/kibana/data/wazuh/config/wazuh.yml

# step3
systemctl restart kibana
```

**Comment by asteriscos** [comment]
Hi @LubinLew 
Thanks for reporting the issue. There was an issue building the package mentioned in the [wiki](https://github.com/wazuh/wazuh-kibana-app/wiki/Build-Wazuh-app-package#important). It will be fixed very soon, but if you are in a hurry, in the meantime there's a temporary package with this building issue fixed.
https://packages-dev.wazuh.com/pre-release/ui/kibana/wazuh_kibana-4.2.0_7.11.2-1.zip

As soon as the release link is fixed I will update this post. 
Thanks again for reaching us!

**Comment by LubinLew** [comment]
https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.2.0_7.11.2-1.zip this building works well
