### ISSUE TITLE
The Groups report does not display correctly

### ISSUE THREAD

**Issue by matiasmoreno876** [wazuh/wazuh-kibana-app#3594]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.2.1   | 7.10.2     | 4202-1 | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
The Groups report does not display correctly

**Preconditions**
1. -

**Steps to reproduce**
1. Navigate to Management --> Groups
2. Select an group 
3. Click on _Export PDF_
4. Go to Management --> Reporting
5. Click on the generated report

**Expected Result**
1. The user should can view all the information generated correctly inside of the report

**Actual Result**
1. The column _Registration date_ doesn't view correctly, it's cut. 

**Screenshots**
![Grabación de pantalla 2021-09-03 a la(s) 16.10.31.gif](https://images.zenhubusercontent.com/604f5c96c82b9774a8c706bc/851b2c5a-836e-4e01-bf8f-4f5e5134ae5c)

**Comment by eze9252** [comment]
We closed this issue because we couldn't reproduce the error.
We tested for versions 4.2.1 and 7.10.2 and the report renders correctly.
