### ISSUE TITLE
Question about the Kibana App

### ISSUE THREAD

**Issue by a108a108** [wazuh/wazuh-kibana-app#3596]
Hi guys,

will future releases of the app are going to support ODFE since it's not going to be developed anymore for versions above 7.10.2 ?
Maybe there will be an app for OpenSearch Dashboards 1.0.0+ instead?

**Comment by frankeros** [comment]
Hi @a108a108  
The default version compatible with Wazuh will be ES 7.10.2 and ODFE in a while. 
We are working on a completely new app from the bottom related to OpenSearch, we hope to release this new app earliest in 2022. 
But possibly we publish a simplest compatibility with OpenSearch before that.

**Comment by a108a108** [comment]
Hi @frankeros,
Thank you for the answer!
