### ISSUE TITLE
Support server.basePath in kibana config for wazuh plugin

### ISSUE THREAD

**Issue by tienthanh2509** [wazuh/wazuh-kibana-app#3599]
Hi Wazuh team,

Currently, the plugin for Kibana is using hardcode base path `/`, therefore, if I change the config to another path some parts of the plugin and docker image is don't work anymore

```yaml
# kibana.yml
server.basePath: "/wazuh"
```

Icon broken
![image](https://user-images.githubusercontent.com/1713444/132954833-0867c922-11e7-4125-98e8-b9057e550b9f.png)

Init script don't work due to only support `https://127.0.0.1:5601/`

```sh
# kibana_settings.sh
...
curl ${auth} -POST -k https://127.0.0.1:5601/api/kibana/settings -H "Content-Type: application/json" -H "kbn-xsrf: true" -d@${default_index}
rm -f ${default_index}

sleep 5
# Configuring Kibana TimePicker.
curl ${auth} -POST -k "https://127.0.0.1:5601/api/kibana/settings" -H "Content-Type: application/json" -H "kbn-xsrf: true" -d \
'{"changes":{"timepicker:timeDefaults":"{\n  \"from\": \"now-12h\",\n  \"to\": \"now\"}"}}'

...
```

So I suggest the plugin and docker image support `server.basePath` config
Thanks for the great plugin.

**Comment by eze9252** [comment]
Hi @tienthanh250
