### ISSUE TITLE
Wazuh Elasticsearch Template Missing

### ISSUE THREAD

**Issue by cwidloe** [wazuh/wazuh-kibana-app#36]
The Template file as listed in the install instructions is missing from GitHub
https://raw.githubusercontent.com/wazuh/wazuh-kibana-app/master/server/startup/integration_files/template_file.json

I used instead
https://raw.githubusercontent.com/wazuh/wazuh-kibana-app/2.1/server/startup/integration_files/template_file.json

**Comment by havidarou** [comment]
@cwidloe Hi,

as you can see in the installation guide (https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/elastic_server_rpm.html#elastic-server-rpm), we reference the 2.1 branch in the links.

Regards.

**Comment by cwidloe** [comment]
Thanks, Just released I am following the 2.0 install guide. Thanks for the fast reply
