### ISSUE TITLE
Vulnerabilities dashboards don't load properly.

### ISSUE THREAD

**Issue by alejandroorg** [wazuh/wazuh-kibana-app#3607]
| Wazuh | Elastic | Rev  | Security |
| ------| -------  | ---- | -------- |
| 4.2    | 1.13.2   | 4xxx | ODFE |

| Browser |
| ------- |
| Chrome |

**Description**
Vulnerabilities dashboards, and the other dashboards from Wazuh don't load properly but we receive events for vulnerability detector.

**More information**
In the debugger console I found this:
![Captura de pantalla (18)](https://user-images.githubusercontent.com/83119522/133596583-43f1c3da-720e-4c21-b761-bb9573ea8d59.png)

I checked that the mapping was applied properly, using the admin user. I can use visualize with the fields that get us problems in the debbuger console.

You will see the error in the attached screenshot.
![Captura de pantalla (7)](https://user-images.githubusercontent.com/83119522/133595553-9f3bf126-e96a-48c7-9132-ec8ddc372187.png)
![Captura de pantalla (8)](https://user-images.githubusercontent.com/83119522/133595646-23802e9c-bcf2-4d58-934f-3b7366f2e836.png)

Thank you in advance!

**Comment by AlexRuiz7** [comment]
We could not reproduce this issue.

@alejandroorg please try again using the recent 4.3.0 version and if the error persists please provide more information about the error and how to reproduce it.

Thank you in advance.

**Comment by AlexRuiz7** [comment]
This dashboard was removed as it is being reworked.
