### ISSUE TITLE
Multi-select component handler bug on shearcher

### ISSUE THREAD

**Issue by gabiwassan** [wazuh/wazuh-kibana-app#3608]
When selecting items and then performing a search, the list of items changes, so if we select items from the search result, the items checked are not correct.

![Peek 2021-09-03 18-28](https://user-images.githubusercontent.com/9343732/132043376-130ce86e-ec5a-4997-8c2a-8ba4bb887d08.gif)

_Originally posted by @asteriscos in https://github.com/wazuh/wazuh-kibana-app/pull/3568#pullrequestreview-746323704_

**Comment by AlexRuiz7** [comment]
Closing this issue has the related PR was already merged.
