### ISSUE TITLE
Users without write permissions can create sample data using the wazuh kibana plugin

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-kibana-app#3611]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.2   | 7.10.2/7.11.2     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
When a user with only read permissions accesses the Wazuh plugin it can create sample data in the index but it is unable to remove it. Also, after reloading the page it can create a new set of sample data.

**Preconditions**
1. A user with a role that only allows it to read the wazuh-index

**Steps to reproduce**
1. Navigate to 'Settings -> Sample data'.
2. Click on 'Add data'.
3. Click on 'Remove data' an error will pop up.
4. Reload the page
5. Click on 'Add data'.

**Expected Result**
1. Read-only users should not be able to add data to the `wazuh-*` indices.

**Actual Result**
1. The user can add an indefinite amount of data to the indices.

**Screenshots**

https://user-images.githubusercontent.com/19505384/134018849-b236a87d-9d47-4182-8b95-70d8768e849e.mp4

**Comment by Mayons** [comment]
This behavior is reproducible on 4.3 RC2 wazuh-kibana-app on kibana 7.10.2. On Google Chrome Browser.
The first time that the new user access to wazuh multiple errors are displayed (screenshots added)
And when the
![Create new user](https://user-images.githubusercontent.com/33849347/147664440-9e1061dd-5ab0-4065-9b24-a61dac80e973.png)
![Errors displayed when user accces to sample data page](https://user-images.githubusercontent.com/33849347/147664443-9bcfd4ca-6dad-4c77-8157-43cd161d2f77.png)
![Firts login errors](https://user-images.githubusercontent.com/33849347/147664445-cc22f511-be0f-48a7-8f3e-c58bf86e46c9.png)
![Sample data added](https://user-images.githubusercontent.com/33849347/147664446-e525a5b8-ca5c-403b-bc39-c37732a88b08.png)
![Set Role](https://user-images.githubusercontent.com/33849347/147664448-d998385f-4ef5-4eb4-86d8-ca67a7e9e862.png)
![Set role second part](https://user-images.githubusercontent.com/33849347/147664450-9a7fb20d-5b40-40cb-8c18-8ed354cd3e5f.png)
 user tries to generate sample data, the app shows an error during the first time but the user is able to add the three types of sample data anyway.
The user is not able to remove the sample data.

**Comment by Machi3mfl** [comment]
### Changes:

- The user to manage the sample alerts endpoint has changed to `currentUser` (logged in elastic). Before we use the `internalUser` defined in kibana.yml
- Added new "Permission denied" message errors in sample-data responses.
https://user-images.githubusercontent.com/6089438/148972401-1de9d64d-bb51-4517-a43d-f554b28d215a.mov

- Added new CallOut with information about privileges in sample-data view.
<img width="1440" alt="Screen Shot 2022-01-11 at 11 19 24" src="https://user-images.githubusercontent.com/6089438/148972520-0a5a8bee-9e50-4654-ae93-d69cba0f9400.png">

**Comment by Desvelao** [comment]
## Changes
The addition of sample data was using the internal user of Kibana, this has been changed to use the logged user in https://github.com/wazuh/wazuh-kibana-app/pull/3795
