### ISSUE TITLE
Evolution visualitation isn't respond in large time ranges in Agent view

### ISSUE THREAD

**Issue by eze9252** [wazuh/wazuh-kibana-app#3613]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc |

**Description**
The `Evolution` visualization of `Agents` section takes much time when the time range is large and as result, there are so many documents to retrieve. This causes that visualization to be slow to show.

**Steps to reproduce**
1. In environments with a large number of agents, set a large range of time.
2. The `Evolution` visualization takes so much time to render

**Comment by Desvelao** [comment]
The problem could be related to a large number of results of the request. We are going to research what to do with the visualization in #3623.
