### ISSUE TITLE
Sample data warning does not appear for readonly users

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-kibana-app#3620]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.2   | 7.10.2/7.11.2     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**

The warning saying that there is sample data in a dashboard does not appear if we access the app with a user that only has read permissions.

**Preconditions**

1. An user with only read permissions.

**Steps to reproduce**

1. Add sample data
2. Login with a user with only read permissions for Wazuh indices.
3. Go to `security events`

**Expected Result**

1. The warning always appears.

**Actual Result**

1. The warning does not appear for readonly users.

**Screenshots**

https://user-images.githubusercontent.com/19505384/134375184-159148f4-9531-4338-bf43-f6106047fb81.mp4

**Comment by AlexRuiz7** [comment]
Related issue #3611

**Comment by Machi3mfl** [comment]
Now, all the requests to check if sample alerts exist will be done with the `internalUser`
Is necessary to check sample alerts without permissions errors.

Fixed

<img width="1440" alt="Screen Shot 2022-03-07 at 15 12 09" src="https://user-images.githubusercontent.com/6089438/157096597-85c5ff3f-0ead-471d-a784-dd797986b99c.png">


https://user-images.githubusercontent.com/6089438/157096747-cceaf3e3-41ee-4bf1-9771-1a49b814d040.mov

**Comment by Desvelao** [comment]
The callout with the warning about the existence of sample data of Wazuh alerts, depends on a request done by the logged/current user to check if there are some of the indices whose names match the composed name for the sample data indices. If the user has no the required permission, the request should fail and the callout is not displayed.

The name of the sample data indices is defined by:
```
<WAZUH_SAMPLE_ALERTS_PREFIX>sample-<SAMPLE_ALERTS_CATEGORY>
```
where:
- `<WAZUH_SAMPLE_ALERTS_PREFIX>`: is defined in the plugin setting `alerts.sample.prefix`
- `<SAMPLE_ALERTS_CATEGORY>` is a fixed string that depends on the current categories of sample alerts
![image](https://user-images.githubusercontent.com/34042064/162183442-df598a14-8e7d-4510-ac5a-b7968a6d694c.png)

**Comment by Desvelao** [comment]
The problem should be related to missing permissions in the current/logged user. Give it the required permissions, should do the toast appear.

**Comment by Desvelao** [comment]
# Wazuh installation
I was reviewing the default configurations for new installations explained in the Wazuh documentation.

## Kibana - Open Distro for Elasticsearch
Documentation: https://documentation.wazuh.com/current/installation-guide/open-distro/all-in-one-deployment/all-in-one.html#elasticsearch-users-and-roles

The configuration files for Elasticsearch define:
- Role: `wazuh_ui_user` with the `read` group permission. This group gives the permissions:
  - `indices:data/read*`
  - `indices:admin/mappings/fields/get*`
![image](https://user-images.githubusercontent.com/34042064/162184765-a67c5c69-a450-4043-b3b8-10c254054dc1.png)
and no includes the permission to check if exists the indices of sample data.
- User: `wazuh_user` with the role `wazuh_ui_user` role.

This configuration causes this user can't check the existence of sample data indices. This affects the mentioned callout is not displayed when there sample data indices and the `Settings/Sample data` where appears a toast displaying an error related to permissions:
![image](https://user-images.githubusercontent.com/34042064/162185496-f0d40612-94c0-4d46-a6f0-b431bbabee2f.png)

It would be recommended to add the required permission to the predefined `wazuh_user` user.

Another interesting thing would be to add a permission group that contains the `read` group permission and the required permission to check the existence of sample data indices. This group permission could be used by the user, to configure custom roles to work with the Wazuh plugin.

**Comment by AlexRuiz7** [comment]
Blocked by https://github.com/wazuh/wazuh-packages/issues/1446

**Comment by AlexRuiz7** [comment]
Configuration files:
- [roles.yml](https://github.com/wazuh/wazuh-packages/blob/4.4/unattended_installer/config/indexer/roles/roles.yml) 
- [roles_mapping.yml](https://github.com/wazuh/wazuh-packages/blob/4.4/unattended_installer/config/indexer/roles/roles_mapping.yml)
- [internal_users.yml](https://github.com/wazuh/wazuh-packages/blob/4.4/unattended_installer/config/indexer/roles/internal_users.yml)

**Comment by Machi3mfl** [comment]
I'm working with the new configuration of roles, roles_mapping, and internal_users to see how is the new behavior of Sample data without the removed `wazuh_ui_user`.
Initially, this issue was created because the prompt message of applied sample data doesn't show when the user has read_only permissions. But at this time that role will not exists by default in the wazuh installation (4.4 version). In conclusion, with the new configuration, this issue will not happen anymore in the 4.4 version because we don't have a read-only user by default.

### Next step:

- [ ] Check the entire app behavior with the new default configurations (roles, roles_mapping, and internal_users). Check if the application works as we expected.
