### ISSUE TITLE
agents-table.js unnecessary heavy load requests

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-kibana-app#3621]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.2.1   | 7.10.2     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
In `agents-table.js` there are `/agents` requests which are only used to count the total amount of agents. The response is an array of agents with all their properties. This should be optimized to have the least amount of information.
There is another bug in **line 90** where `totalItems` property does not exist and should be replaced by `affected_items`

**Screenshots**

![image](https://user-images.githubusercontent.com/9343732/134389668-73142206-4cab-4d73-8fb0-6313ecf56605.png)

**Comment by frankeros** [comment]
@wazuh/frontend we need to refactor all usage of the limit param in Wazuh API calls

**Comment by yenienserrano** [comment]
**Description**

change of request for one that does not return data that is not necessary to optimize times

**PR**

Agents table unnecessary heavy load requests [#3686](https://github.com/wazuh/wazuh-kibana-app/pull/3686)

**Check List**

- [x]  Change of request


![image](https://user-images.githubusercontent.com/63758389/142058226-7950160d-2ab0-46b1-8096-3cb7cbde80f0.png)
