### ISSUE TITLE
Inventory data does not have filter on Network ports table

### ISSUE THREAD

**Issue by HanesSciarrone** [wazuh/wazuh-kibana-app#3622]
|Wazuh version|
|---|
|v4.3.0 |

## Description
Hi Team!!

This issue aims to report a bug found on the port table of Inventory data for Wazuh 4.3 but it is not ruled out that it may be in previous versions.. Kibana is not able to filter the Network ports table by Port or IP on Linux, macOS and Windows OS.

## Steps to reproduce

1. Install a Wazuh agent 4.3 in any OS.
2. Install a Wazuh manager on Ubuntu 20.04.
3. Open Kibana app and go to **Agents** option, select any agent and open **Inventory data** option.
4. Try to find the option to filter the Network ports table.

## Expected result
- See an option to filter this table similar to has package table.

![image](https://user-images.githubusercontent.com/58960358/134411251-d7cd5045-d227-4bc9-9cd8-6e399a290083.png)

## Current result
- Table doesn't show the filter option

![image](https://user-images.githubusercontent.com/58960358/134411096-63427f30-434f-4b72-8178-d9d991b004b0.png)

Best regards
Hanes

**Comment by AlexRuiz7** [comment]
Filter bar has been applied

![image](https://user-images.githubusercontent.com/15186973/135445563-15cbfa85-1e39-45e3-ad43-1d9d0c3d7ae4.png)
