### ISSUE TITLE
Index fields error after enabling Docker Extension.

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-kibana-app#3641]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.2.0   | 7.10.2    | 4201-11 | ODFE |

| Browser |
| ------- |
| Chrome|

**Description**
An index fields error is appearing in Kibana UI when looking for Docker events and Docker Extension is enabled.

**Preconditions**
1. Enable Docker extension

**Steps to reproduce**
1. Navigate to `Modules directory` > `Docker listener`
2. Wait for Kibana to search events.

**Expected Result**
1. That events are being displayed.

**Actual Result**
1. The events are not being displayed and an error shows up:
![Screenshot from 2021-10-01 11-16-43](https://user-images.githubusercontent.com/33964202/135635324-6fcea6f3-04a5-4d1f-884e-457c1a3079bb.png)
2. Refreshing the page does not solve the error.

**Additional context**
I have configured the Docker extension by modifying the `wazuh-registry.json`.

**Comment by yenienserrano** [comment]
I could not reproduce it

![image](https://user-images.githubusercontent.com/63758389/212682142-618b1f38-1a21-4778-9bd8-6d67821b20f3.png)
