### ISSUE TITLE
OpenSearch compatible Wazuh App request

### ISSUE THREAD

**Issue by dariommr** [wazuh/wazuh-kibana-app#3644]
Hello Team,

Looking at the needs of users moving from ELK Basic License to OpenSearch (formerly OpenDistro), I am requesting a Wazuh App compatible with OpenSearch Dashboards to fit the needs of those who need to migrate to this platform.

These are the reasons the users state:
- The new licensing methods in Elasticsearch
- The stop in the OpenDistro development
- The known vulnerabilities in the current version of OpenDistro for Elasticsearch.

I hope this could be clear enough.
Thank you in advance.

**Comment by dariommr** [comment]
I was analyzing the vulnerabilities in Elasticsearch 7.10.2 and it seems they are all related to capabilities that are not present in OpenDistro (All related to ELK default flavor). Since this is the strongest reason for moving to OpenSearch, I will proceed to close the issue.
Thank you in advance!

**Comment by StefanSa** [comment]
Hi @dariommr 
That would be great if this would be eralisert soon, the appropriate to the topic this block entry of Open Distro:
[https://opendistro.github.io/for-elasticsearch/blog/2021/12/the-future-of-open-distro/](url)

**Comment by Desvelao** [comment]
We are working on supporting OpenSearch Dashboards. There is an open issue about the development https://github.com/wazuh/wazuh-kibana-app/issues/3794

**Comment by fadjar340** [comment]
Can't wait for this release..
Just installed OpenSearch 1.2.3 and need to install wazuh using helm chart.....

Thanks for this awesome system....


Regards,
Fadjar Tandabawana

**Comment by QuanTran91** [comment]
I also have a question: Will Wazuh app continue to support ElasticSearch as well?

**Comment by dariommr** [comment]
Hello @QuanTran91 
Yes, in the early future there are no plans to deprecate the Wazuh App for Elasticsearch.
Kind regards.

**Comment by gdiazlo** [comment]
Related to #3794
