### ISSUE TITLE
Wrong visualization for EventChannel localfiles

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-kibana-app#3646]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.2.3  | 7.10.2  | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox|

**Description**
Logcollector `localfile` configuration blocks allows different types/kind of `log_formats`. Currently Agent>Configuration>Log data analysis>Log collection location is grouping some `log_formats` in tabs, but showing `eventchannel` configuration as as if they were the `command` or `full_command` type.

**Preconditions**
1. Have at least one Windows Agent connected that use Windows EventChannel for collecting logs. This is the default configuration for Windows Vista or newer .

**Steps to reproduce**
1. Navigate to 'Agent' section
2. Click on any Windows Agent
3. Click on 'Configuration'
4. Scroll down to 'Log data analysis' and click on 'Log collection'

**Expected Result**
1. `localfiles` defined with `eventchannel` as `log_format` are shown in `EventChannel/EventLog` section or at least in `Logs`. TBD 

**Actual Result**
1. `localfiles` defined with `eventchannel` as `log_format` are shown in `Commands` section. as if they were the `command` or `full_command` type.

**Screenshots**

![image (13)](https://user-images.githubusercontent.com/1791430/136451395-f34b43a3-69dc-4e90-b567-ad13e0e4eaae.png)

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by branchnetconsulting** [comment]
Presumably event channel log sources deserve their own tab right between the `Logs` and `Commands` tabs instead of being treated like Commands.  This would allow for the full information to be accounted for about which event channels are being analyzed with all relevant settings.  

Please fix this.  We can't see our agents' effective eventchannel configuration at all at this point.

Thanks,
Kevin

**Comment by Machi3mfl** [comment]
## Preview solution

The windows events `(eventchannel)` are included in `Commands` section

https://user-images.githubusercontent.com/6089438/159049867-194a1da4-38cf-45d9-ac24-cb90e45e4576.mov

## Solution scope

- Add a new `"Windows Events"` tab in `Agent > Configuration > Log collector`
- Exclude `windows localfiles` from `Commands` tab.
- Filter the `windows localfiles` with `logformat` = `eventchannel` and `eventlog`

#### `Logcollector > Localfiles` new filters
1. `Logs` when `localfile` have `file` property
2. `Windows Events` when `localfile' have `logformat` property equals `eventchannel` or `eventlog`
3. `Commands` when `localfile' have `logformat` property equals `command`

## Windows Events Tab Content
- **Tab Title:** `Windows Events`
- **Tab content tile and subtitle:** `Windows events logs` `List of Windows logs that will be processed`
- **Panel items title:**  
   **`< 4.2.5` agent version:** `logformat +  target`
  **`> 4.3` agent version:** `channel + (logformat)`
   
## Tab content
- `Log format (logformat)`
- `Channel (channel)` when `logformat` is `eventchannel` or `Log` when `logformat` is `eventlog` `(only have data if agent > 4.2.5 version)`
- `Query (query)`
- `Only-future-events (only-future-events)`
- `Reconnect time reconnect_time`

**Core partner**: @jnasselle

**Comment by Machi3mfl** [comment]
## Solution screenshots

`with 4.25 agent version`

<img width="1438" alt="Screen Shot 2022-03-18 at 11 20 56" src="https://user-images.githubusercontent.com/6089438/159051260-53204d31-4cff-4c38-90e0-c8222edc4cee.png">

https://user-images.githubusercontent.com/6089438/159050963-3a2867ad-0b77-4502-b69b-9fbfaf46a261.mov

`with 4.3 agent version`

<img width="1440" alt="Screen Shot 2022-03-18 at 13 00 43" src="https://user-images.githubusercontent.com/6089438/159051401-63a74597-8f21-40af-b573-4915feb6d614.png">

https://user-images.githubusercontent.com/6089438/159051487-b8fbec2f-4d4f-4557-be64-76014daa6742.mov

`with 4.3 agent version and localfile eventlog`

<img width="1438" alt="Screen Shot 2022-03-18 at 14 21 05" src="https://user-images.githubusercontent.com/6089438/159052275-7e16b8c4-497d-4356-8efe-b0f7c49b8bd7.png">

https://user-images.githubusercontent.com/6089438/159052330-31fad5d4-c111-46f6-9aa6-f76a51d0e658.mov

**Comment by Machi3mfl** [comment]
#### Testing considerations:

1. Go to `Agent > Configuration > Log collector`
2. Compare screen with screenshot added in preview comment.

`Test PR adding a windows agent 4.2.5.` 
[https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-windows.html](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-windows.html)
`Test PR with windows agent 4.3` 
[https://packages-dev.wazuh.com/pre-release/windows/wazuh-agent-4.3.0-1.msi](https://packages-dev.wazuh.com/pre-release/windows/wazuh-agent-4.3.0-1.msi)

**Comment by Mayons95** [comment]
Testing in progress

**Comment by Mayons95** [comment]
Test OK, details attached on PR

**Comment by branchnetconsulting** [comment]
I look forward to this fix appearing in 4.4.   I am concerned that in the examples above that the Commands tab appears to be replaced with the new "Windows Events" tab.  You aren't really dropping the Commands tab, are you?

**Comment by Machi3mfl** [comment]
Hi @branchnetconsulting, thanks for sharing your concern with us. But the `Commands` doesn't disappear, only we separate the windows event-channel logs from the command tab, creating a new one called `Windows Events`.
The purpose of that is separate the logs and have more specific data for each case. 

I leave a screenshot for the case when the agent isn't a windows agent. In this case, we will find the `command`.
<img width="1418" alt="Screen Shot 2022-06-23 at 13 08 15" src="https://user-images.githubusercontent.com/6089438/175346685-0a4c99d5-b603-45dd-ab23-24c19f2fedd1.png">

**Comment by branchnetconsulting** [comment]
Ah, so you mean that if there are no Commands defined for a given agent, then the Commands section does not appear at all?  Very nice!  Thanks for clarifying.

**Comment by Machi3mfl** [comment]
### Added Unit test for `Command` and `Windows Events` tabs in the `Log Collection` panel

<img width="926" alt="Screen Shot 2022-06-27 at 09 47 22" src="https://user-images.githubusercontent.com/6089438/175945125-594e1a97-1736-4716-853c-1bb1f1c1198a.png">

**Comment by Machi3mfl** [comment]
Feature resolven in #3905
