### ISSUE TITLE
Add missing MITRE Tactics IDs

### ISSUE THREAD

**Issue by jcruzlp** [wazuh/wazuh-kibana-app#3647]
Hello team, as an user reported here: https://github.com/wazuh/wazuh/issues/10490 we're missing some of the MITRE IDs
The missing Techniques are:
- [T1543](https://attack.mitre.org/techniques/T1543/)
- [T1546](https://attack.mitre.org/techniques/T1546/)
- [T1547](https://attack.mitre.org/techniques/T1547/)
- [T1548](https://attack.mitre.org/techniques/T1548/)
- [T1569](https://attack.mitre.org/techniques/T1569/)

Actually, seems that the MITRE IDs goes until the ID 1614: https://attack.mitre.org/techniques/T1614/
And our mapping goes until 1539 https://github.com/wazuh/wazuh-kibana-app/blob/master/public/components/overview/mitre/lib/mitre_techniques.ts

Would be possible to add them to our WUI?

**Comment by yenienserrano** [comment]
**Description**

Fix details and search

**Issues Resolved**

Add missing MITRE Tactics IDs [#3647](https://github.com/wazuh/wazuh-kibana-app/issues/3647)

**Test**

`/Modules/MITER ATT & CK/framework` and check that they are up to T1614 and see the details


**Check List**

- [x]   Fix details and search

![image](https://user-images.githubusercontent.com/63758389/139870826-095a2162-8154-4e9b-bbe4-30631a758652.png)
![image](https://user-images.githubusercontent.com/63758389/139870892-ad21b26e-173c-4fa1-997e-e0c7dbd4d68d.png)
