### ISSUE TITLE
Security Alerts table does not correctly update time range

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-kibana-app#3648]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.2.2   | 7.10.2     | 4203-1 | ODFE |

| Browser |
| ------- |
| Firefox / Chrome  |

**Description**
Security Alerts table (`module-discover-table`) in the Security Events dashboard does not update to reflect the time range filter until the user exits and re-enters the dashboard.

**Steps to reproduce**
1. Navigate to Security Events
2. Scroll down and see the most recent event on the Security Events table
3. Scroll up and modify the time range from the top-right selector or by clicking and dragging any Date Histogram graph
4. Scroll back down and notice that the most recent event is still the same

**Expected Result**
1. The table should update as all other visualizations in the page do

**Actual Result**
1. The page is unaffected until either the page is reloaded or the user moves to another section and returns.

**Screenshots**
![image](https://user-images.githubusercontent.com/36071202/137183964-00cd3b40-385b-41ac-a323-87c547410384.png)
Note how all graphs on the screenshot are between 2:02 to 2:36 am but the first events on the table are from 19:31

**Comment by Machi3mfl** [comment]
Fixed

https://user-images.githubusercontent.com/6089438/141181893-3f10f7ab-d30d-47fc-9f30-15c4b7f7b6aa.mov
