### ISSUE TITLE
Implement .wazuh-vis index to store visualizations

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#365]
Currently, the Wazuh app stores all its visualizations into the .kibana index. The goal is to implement a new, separated index to store them, avoiding, even more, the use of own Kibana indices.

**Comment by jesusgn90** [comment]
This issue has no sense any more since we are changing the way we handle the visualizations. See  https://github.com/wazuh/wazuh-kibana-app/issues/380 for more information.

Best,
Jesús
