### ISSUE TITLE
Role users_admin doesn't work properly

### ISSUE THREAD

**Issue by mattgrow** [wazuh/wazuh-kibana-app#3650]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.2   | 7.10     | 4xxx | ODFE |

| Browser |
| ------- |
| Chrome|

**Description**
Role users_admin doesn't work properly

**Preconditions**
1. I want to create user with permissions to add/delete users/roles/roles mapping and nothing else

**Steps to reproduce**
1. Create internal user: Security > Internal users
2. Create role: Security > Roles. Indexes *, read permissions
3. Map created internal user to created role
4. Goes to Wazuh > Security > Roles mapping
5. Create Role mapping: select role "users_admin" and select created (first step) internal user
6. Login using created internal user
7. Goes to Wazuh >  Security > Users and see "This sections requires administrative role"

**Expected Result**
1. Access to Wazuh >  Security > Users

**Actual Result**
1. Alert: "This section requires administrator role"

**Screenshots**
![wazuh_security_users](https://user-images.githubusercontent.com/86667307/137372677-918a3098-aa46-47fb-b56b-9d1d38feeaff.PNG)

**Comment by mattgrow** [comment]
Hi gabiwassan,

I test it, 'administrator' role works properly. But I need that User only had rights to create/delete users, not other rights

Best regards

**Comment by AlexRuiz7** [comment]
Closed for inactivity
