### ISSUE TITLE
Support for Kibana 7.14.x

### ISSUE THREAD

**Issue by sshipway** [wazuh/wazuh-kibana-app#3658]
**Describe the solution you'd like**
A release of the plugin suitable for kibana 7.14.x (or 7.15.x), the versions available in ES Cloud.

**Describe alternatives you've considered**
I have tried using an earlier version of Kibana, such as 7.10.2 or 7.12.1; however these are not compatible with the ES Cloud which must be the identical version of kibana but currently only allows 7.14.0, 7.14.2 and 7.15.1 to be installed.

**Additional context**
ES Cloud does not allow Kibana plugins to be installed; therefore, you need to run a local kibana in parallel.  However this must be exactly the same version as the ES Cloud kibana, and you only have options to install or upgrade to the latest in the 7.14 and 7.15 branches.

**Comment by gabiwassan** [comment]
Hi @sshipway, 
In the following weeks the compatible plugin for 7.13 and 7.14 is coming out, it will be announced on our social media.
This is the [issue](https://github.com/wazuh/wazuh-kibana-app/issues/3310) in progress.

Best!
