### ISSUE TITLE
Implement user-dependant dynamic visualizations

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#366]
Right now, visualizations are loaded from a common pool. Thus, changes in the index-pattern used by the visualizations are global. There are certain environments (especially big ones) which need them to be local, and this task will try to accomplish that.

This issue is part of the refactoring process that is being made for the Wazuh app backend.

**Comment by JuanjiJG** [comment]
This is almost done thanks to the incredible work made by @havidarou and @jesusgn90 in #360.

**Comment by jesusgn90** [comment]
Hello team, this is done on https://github.com/wazuh/wazuh-kibana-app/pull/360 as @JuanjiJG said. We need to fully test it of course, but on a default installation and on an upgraded from 2.x installation, it's working as expected. 

From my view this is closed, if we find some trouble while using it, I think we should create specific issues if so.

Best,
Jesús
