### ISSUE TITLE
Release 4.3.0 - Release Candidate 1 - Kibana UI regression testing

### ISSUE THREAD

**Issue by MauGaP** [wazuh/wazuh-kibana-app#3684]
We will perform testing for the following issues:

**Changelog**
| *Added* | Tested in |
| ------------- | ------------- |
| Added ability to filter the results fo the Network Ports table in the Inventory data section #3639 |
| Added new endpoint service to collect the frontend logs into a file #3324 |
| Improved the frontend handle errors strategy: UI, Toasts, console log and log in file #3327 #3321 #3367 #3373 #3374 #3390 #3410 #3408 #3429 #3427 #3417 #3462 #3451 #3442 #3480 #3472 #3434 #3392 #3404 #3432 #3415 #3469 #3448 #3465 #3464 #3478 |
| Added fields status and type in vulnerabilities table #3196 |
| Added Intelligence tab to Mitre Att&ck module #3368 #3344 |
| Added sample data for office365 events #3424 |
| Created a separate component to check for sample data #3475 |
| Added a new hook for getting value suggestions #3506 |
| Added dinamic simple filters and adding simple GitHub filters fields 3531 |
| Added configuration viewer for Module Office365 on Management > Configuration #3524 |
| Added base Module Panel view with Office365 setup #3518 |
| Added specifics and custom filters for Office365 search bar #3533 |
| Adding Pagination and filter to drilldown tables at Office pannel #3544. |
| Simple filters change between panel and drilldown panel #3568. |
| Added new fields in Inventory table and Flyout Details #3525 |

| *Changed* | Tested in |
| ------------- | ------------- |
| Changed ossec to wazuh in sample-data #3121 |
| Changed empty fields in FIM tables and syscheck.value_name in discovery now show an empty tag for visual clarity #3279 |
| Adapted the Mitre tactics and techniques resources to use the API endpoints #3346 |
| Moved the filterManager subscription to the hook useFilterManager #3517 |
| Change filter from is to is one of in custom searchbar #3529 |
| Refactored as module tabs and buttons are rendered #3494 |
| Updated depracated and new references authd #3663 | All 
| Added time subscription to Discover component #3549 |
| Refactored as module tabs and buttons are rendered #3494 |
| Testing logs using the Ruletest Test don't display the rule information if not matching a rule. #3446 |
| Changed format permissions in FIM inventory #3649 |
| Changed of request for one that does not return data that is not necessary to optimize times. #3686 | All

| *Fixed* | Tested in |
| ------------- | ------------- |
| Fixed creation of log files #3384 |
| Fixed double fetching alerts count when pinnin/unpinning the agent in Mitre Att&ck/Framework #3484 |
| Query config refactor #3490 |
| Fixed rules and decoders test flyout clickout event #3412 |
| Notify when you are registering an agent without permissions #3430 |
| Remove not used redirectRule query param when clicking the row table on CDB Lists/Decoders #3438 |
| Fixed the code overflows over the line numbers in the API Console editor #3439 |
| Don't open the main menu when changing the seleted API or index pattern #3440 |
| Fix error message in conf managment #3443 |
| Fix size api selector when name is too long #3445 |
| Fixed error when edit a rule or decoder #3456 |
| Fixed index pattern selector doesn't display the ignored index patterns #3458 |
| Fixed error in /Management/Configuration when cluster is disabled #3553 | All
| Fix the pinned filters were removed when accessing to the Panel tab of a module #3565 | All
| Fixed multi-select component searcher handler #3645 | All
| Fixed order logs properly in Management/Logs #3609 |
| Fixed the Wazuh API requests to GET // #3661 | All
| Fixed missing mitre tactics #3675 | All
| Fix CDB list view not working with IPv6 #3488 |
| Fixed the bad requests using Console tool to PUT /active-response API endpoint #3466 |
| Fixed group agent management table does not update on error #3605 |
| Fixed not showing packages details in agent inventory for a freeBSD agent SO #3651 |
| Fixed wazuh token deleted twice #3652 |
| Fixed handler of error on dev-tools #3687 |
| Fixed compatibility wazuh 4.3 - kibana 7.13.4 #3685 |
| Fixed registry values without agent pinned in FIM>Events #3689 | All
| Fixed breadcrumbs style compatibility for Kibana 7.14.2 #3688 |
| Fixed security alerts table when filters change #3682 | All
| Fixed error that shows we're using X-Pack when we have Basic #3692 | All
| Fixed blank screen in Kibana 7.10.2 #3700 |

**Testing environments:**

|*First Cicle*| done |
| ------------- | ------------- |
| ODFE - Firefox - 7.10.2 | Tested by @MauGaP 
| Basic - Chrome - 7.12 | Tested by @CPAlejandro 
| Basic - Safari - 7.13.4 | 
| Xpack - Chrome - 7.13.4 | Tested by @CPAlejandro 
| Basic - Safari - 7.14.2 | Tested by @CPAlejandro 
| X-Pack - Chrome - 7.14.2 | Tested by @MauGaP 

|*Second Cicle*| WIP |
| ------------- | ------------- |
| ODFE - safari - 7.10.2 | @matiasmoreno876 
| Xpack  - Firefox - 7.12.1 | @gabiwassan 
| Basic - Chrome - 7.13.4 | @asteriscos 
| Xpack - Safari - 7.13.4 | @Machi3mfl 
| Xpack - Firefox - 7.14.2 | @yenienserrano 
| Basic - Chrome\Safari - 7.14.2 | @CPAlejandro

**Comment by CPAlejandro** [comment]
Errors or bugs founded in Chrome with Kibana 7.13.4:

- Empty Dashboards when we pin an agent
![image (9)](https://user-images.githubusercontent.com/17100196/142196035-1b2c5848-7d8a-4918-b116-c33c3727a5f3.png)
Despite the fact that are events:
![image (10)](https://user-images.githubusercontent.com/17100196/142196071-186a04d0-8a5e-4ef9-919a-8ae74a62a4de.png)

- I have seen this error once, trying to create a report after unpin an agent:
![image (11)](https://user-images.githubusercontent.com/17100196/142196186-b612db46-92b7-42d7-871e-9e1b9b12ec63.png)

- In Api Console, when you run an `GET` this error appear in the browser console:
![image (12)](https://user-images.githubusercontent.com/17100196/142196335-af39254d-ce1a-4948-8a27-24adcf87898e.png)

- When you write a GET or PUT in Api Console or when you go to another new line, this errors appear as well in browser console:
![image (12)](https://user-images.githubusercontent.com/17100196/142196410-71b8242a-629b-45fc-81f2-007d28fc3ea3.png)

- The name of JSON when you export data in API Console is `export.json`, it would be `api_console.json` for example.

- Sometimes, when you enter to the view of an agent, the table Events Count Evolution is empty and doesn't show that it hasn't any data:
![image (14)](https://user-images.githubusercontent.com/17100196/142196619-b22a53f4-8f75-4934-8f90-51556c0cb971.png)

**Comment by CPAlejandro** [comment]
**Error and bugs founded in Chrome 7.12.1 with Chrome and Basic**

- Persist the error when you edit a group configuration, save it and try to go back, the app tells you about unsaved changes
- The name of the file exported from API console is `export.json`

**Comment by CPAlejandro** [comment]
Testing Kibana 7.14.2 with ElasticSearch Basic, i have found a bug going to Role Mapping, it appear an error message, if you go then to other Security windows and come back, the error appears twice.
![image (15)](https://user-images.githubusercontent.com/17100196/142439285-092357a6-9b60-4d76-8515-ed99bbc118a8.png)

**Comment by CPAlejandro** [comment]
Methods to know whether or not you have X-Pack:

- Check that there is a CA certificate in the _ssl object `context.core.elasticserach.asCurrentUser.xpack`

- Licensing plugin with [license.check](https://github.com/elastic/kibana/blob/v7.10.2/x-pack/plugins/security/server/routes/users/get_all.ts)

- Make request from fronted to `/internal/users/me` or other X-Pack endpoint and see if it fails
