### ISSUE TITLE
Add key request settings to the Authd configuration

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-kibana-app#3690]
Hi team,

As part of https://github.com/wazuh/wazuh/issues/10399 new options have been added to the Registration Service configuration. Here you can see the API response when adding the new `key_request` block.

```js
# curl -k -X GET "https://localhost:55000/agents/000/config/auth/auth" -H "Authorization: Bearer $TOKEN"
{
  "data": {
    "auth": {
      "port": 1515,
      "disabled": "no",
      "remote_enrollment": "yes",
      "use_source_ip": "no",
      "purge": "yes",
      "use_password": "no",
      "ssl_verify_host": "no",
      "ssl_auto_negotiate": "no",
      "ciphers": "HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH",
      "ssl_manager_cert": "etc/sslmanager.cert",
      "ssl_manager_key": "etc/sslmanager.key",
      "key_request": {
        "enabled": "yes",
        "exec_path": "python3 /root/key_request_db.py",
        "socket":"/tmp/key_request_socket",
        "timeout": 60,
        "threads": 1,
        "queue_size": 1024
      },
      "force": {
        "enabled": "yes",
        "key_mismatch": "yes",
        "disconnected_time": {
          "enabled": "no",
          "value": 3600
        }
      }
    }
  },
  "error": 0
}
```

The goal of this issue is to be able to see the new block `key_request` and its options inside the `Registration Service` section. This block is optional so it can be missing in the API response.

![image](https://user-images.githubusercontent.com/29475387/142596700-864e7184-4ad9-46b5-9aff-8c4f57d2b9cc.png)

Best regards.

**Comment by Machi3mfl** [comment]
### When `key request` is `disabled`

<img width="1439" alt="Screen Shot 2022-04-06 at 15 41 09" src="https://user-images.githubusercontent.com/6089438/162053439-835ea604-b182-4ef2-b79d-87b7d692b8d5.png">

### When `key request` is `enabled`

<img width="1440" alt="Screen Shot 2022-04-06 at 15 40 28" src="https://user-images.githubusercontent.com/6089438/162053715-65e2b9f8-0b62-4c3c-b757-6ee8a71c6fe6.png">

**Comment by Mayons95** [comment]
Testing Steps:
Navigate to Management/Configuration/
Check that the key request field it's displayed

To change the value disable/enable edit the ossec.conf file on the auth section, replace the existing config with the following:

auth>
    <force>
        
        <enabled>yes</enabled>
    </force>
    <key_request>
        <enabled>yes</enabled>
        <exec_path>/usr/bin/python /home/script.py</exec_path>
        <timeout>60</timeout>
        <threads>1</threads>
        <queue_size>1024</queue_size>
    </key_request>
    <disabled>no</disabled>
    <port>1515</port>
    <use_source_ip>no</use_source_ip>
    <purge>yes</purge>
    <use_password>no</use_password>
    <ciphers>HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH</ciphers>
    
    <ssl_verify_host>no</ssl_verify_host>
    <ssl_manager_cert>etc/sslmanager.cert</ssl_manager_cert>
    <ssl_manager_key>etc/sslmanager.key</ssl_manager_key>
    <ssl_auto_negotiate>no</ssl_auto_negotiate>
  </auth>
