### ISSUE TITLE
Wrong redirect to settings screen after login

### ISSUE THREAD

**Issue by Machi3mfl** [wazuh/wazuh-kibana-app#3694]
| Wazuh | Elastic | Security |
| ----- | -------  | -------- |
| 4.2   | 7.x      | ODFE |

| Browser |
| ------- |
| Safari |

**Description**
After the user logout and login is redirected to the settings screen instead of the overview screen.
Only happen in Safari.

https://user-images.githubusercontent.com/6089438/143490808-4a73b958-0a00-40e5-ab9b-5a156daa07de.mov

**Additional context**
Check force delete token.
PRs related:
https://github.com/wazuh/wazuh-kibana-app/pull/3138
https://github.com/wazuh/wazuh-kibana-app/pull/3638

**Comment by matiasmoreno876** [comment]
In this PR #3701 I implement a possible solution, adding a delay in the execution of the request that deprecates the token, it is 5sec

**Comment by matiasmoreno876** [comment]
**I ran tests with the following browsers:**

### Safari ✅ 

![Safari-browser](https://user-images.githubusercontent.com/49887871/146036307-f44674be-40b1-4bd8-bd3e-28bde6450006.gif)

### Firefox ✅ 

![Firefox-browser](https://user-images.githubusercontent.com/49887871/146036418-cd2a8e88-3f39-4986-b60d-b6ef93a04062.gif)

### Chrome ✅ 

![Chrome-browser](https://user-images.githubusercontent.com/49887871/146036485-e4f76a20-77be-4123-8a73-38f9fed29901.gif)

### Brave ✅ 

![Brave-browser](https://user-images.githubusercontent.com/49887871/146036565-103a5a63-4130-4846-a4c3-932485f2c04b.gif)
