### ISSUE TITLE
Official Elastic integration support.

### ISSUE THREAD

**Issue by andylow** [wazuh/wazuh-kibana-app#3697]
Currently Wazuh is best fit with it's own build Kibana and Open-Distro Elasticsearch.

Now I'm using Elastic Cloud, and it is difficult to me to integrate Wazuh with my existing Elastic Cloud.

Would like to request split the Kibana extension/plugin as separate package which allow to install in Official Kibana.

**Comment by Desvelao** [comment]
Hi @andylow,

Wazuh Kibana app is a plugin for Kibana. You can install it in your Kibana instance if there is a Wazuh app compatible with the Kibana version that you are using. Check the [Wazuh Kibana app compatibility matrix](https://github.com/wazuh/wazuh-kibana-app#wazuh---kibana---open-distro-version-compatibility-matrix)

Open Distro for Elasticseach offers a set of plugins open source for Elasticsearch and Kibana (oss versions). Open Distro for Elasticsearch offers packages to install Elasticsearch and Kibana including its own plugins but the bases are Elasticsearch and Kibana (oss versions).

**Comment by acherifi** [comment]
Problem with that is that ES cloud only allows 7.16 or 7.15. 
So when using the opendistro kibana release which is in 7.10, it is impossible for Kibana to connect to the cloud since the Cloud instance contains unknown fields. 
Using a "vanilla"  Kibana and installing Wazuh on top of it does not seem to work either

**Comment by Desvelao** [comment]
> Problem with that is that ES cloud only allows 7.16 or 7.15. So when using the opendistro kibana release which is in 7.10, it is impossible for Kibana to connect to the cloud since the Cloud instance contains unknown fields. Using a "vanilla" Kibana and installing Wazuh on top of it does not seem to work either

Thank you @acherifi for the information.

At this moment, unfortunately, Wazuh app for Kibana is compatible up to Kibana `7.14.2`. We are working to support Kibana `7.15.x` and `7.16.x`.

There is an issue to check the compatibility with Kibana `7.16.x` https://github.com/wazuh/wazuh-kibana-app/issues/3749.

**Comment by Desvelao** [comment]
Hi @jeffery-jen 

Sorry, but I don't understand what you mean.

If you want to use the Wazuh app for Kibana, you can install it in the supported Kibana versions (see the [compatibility matrix](https://github.com/wazuh/wazuh-kibana-app#wazuh---kibana---open-distro-version-compatibility-matrix)).

For another hand, referring to the Elasticsearch versions, it is recommended to use the same version for Kibana and Elasticsearch, but you could have different versions of them while they are compatible.

What do you mean by your own Elasticsearch? Do you mean to use the Elasticsearch that includes the Open Distro for Elasitcsearch plugins? The default guide of Wazuh to install Elasticsearch and Kibana, use the packages of Open Distro for Elasticsearch, but there is a guide to use the basic license for Elastic stack too, see [Wazuh with Elastic stack basic license](https://documentation.wazuh.com/current/installation-guide/more-installation-alternatives/elastic-stack/index.html).

**Comment by stiansvalstad** [comment]
Hi!
I'm wondering if anyone has any insight to when the Wazuh app for Kibana will support Elastic version 7.16?
Would be awesome to know how far away official support is.

(I'm in a scenario where a downgrade of elastic is not possible)

**Comment by Desvelao** [comment]
Hi @stiansvalstad, our current intention is to release a plugin compatible with `Wazuh 4.3.0` for **Kibana**:
- `7.10.2`
- `7.16.3`
- `7.17.0`

But this could change. I don't have an ETA for the release.

**Comment by AlexRuiz7** [comment]
Latest app versions are compatible with Elastic 7.16.x and 7.17.x
