### ISSUE TITLE
dashboard file intergrity :No results found

### ISSUE THREAD

**Issue by lapnt** [wazuh/wazuh-kibana-app#37]
Hi all,

I have a issues with dashboard.
Please , help me fix it
![image](https://user-images.githubusercontent.com/26154789/31607613-31fafa78-b297-11e7-8a48-1defceab02e1.png)

**Comment by malbarral** [comment]
Hi @lapnt,

Do you have data in Discover tab? 

Probably, Elasticsearch is not receiving alerts. To check if the alerts.json file is being read paste here the result of the command: `lsof /var/ossec/logs/alerts/alerts.json`

Best regards,
Manuel Albarral

**Comment by lapnt** [comment]
tks,
yes, Discover tab have data.
![image](https://user-images.githubusercontent.com/26154789/31608391-68f4c83a-b29a-11e7-9031-d5f0c5b3dae4.png)


When i choose time is 60 days
![image](https://user-images.githubusercontent.com/26154789/31608332-3992ab02-b29a-11e7-915b-e95946463b41.png)
but time in  7 days not show 
![image](https://user-images.githubusercontent.com/26154789/31608360-547c0af8-b29a-11e7-9ff1-470968e5da24.png)

lsof /var/ossec/logs/alerts/alerts.json
![image](https://user-images.githubusercontent.com/26154789/31608190-a0e17b90-b299-11e7-9673-ef7baab276d7.png)

**Comment by malbarral** [comment]
It is possible that don't exist FIM alerts. To look for them, use this query in the Discover tab: `rule.groups:"syscheck"`

Best regards,
Manuel Albarral

**Comment by lapnt** [comment]
but how to show on file-intergrity dashboad :(

**Comment by malbarral** [comment]
I mean, check in Discover tab that there exist FIM alerts. If the File Integrity Monitoring dashboard doesn't show any result, I'm pretty sure that there are not alerts to show. Please, search in Discover tab for `rule.groups:"syscheck"` for the last 15 minutes and paste here the results.

**Comment by lapnt** [comment]
please see it
![image](https://user-images.githubusercontent.com/26154789/31617802-6012cf26-b2ba-11e7-876f-91dbf19c06b9.png)

**Comment by malbarral** [comment]
It seems to be a date issue. Check this thread in Kibana [https://discuss.elastic.co/t/timezone-utc-00-00-getting-converted-on-kibana-display-to-05-30/38727](https://discuss.elastic.co/t/timezone-utc-00-00-getting-converted-on-kibana-display-to-05-30/38727). Try to change the Kibana advanced configuration and set the `dateFormat:tz` option.

**Comment by lapnt** [comment]
thanks, i will try 👍

**Comment by JuanjiJG** [comment]
It's been more than a month since the last response to this issue, so we proceed to close it.

Regards.
