### ISSUE TITLE
Search by cluster node on Agents preview list

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#370]
This issue is part of the implementation of the distributed API and cluster daemon on the Wazuh app. When the app begins the refactoring process for adapting to the new Wazuh changes, we'll have to add a new search bar to filter by cluster node on the list of agents.

**Comment by jesusgn90** [comment]
Done here https://github.com/wazuh/wazuh-kibana-app/pull/538
