### ISSUE TITLE
PCI-DSS Dashboard missing controls tab (4.3 RC1)

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-kibana-app#3702]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 7.10     | 4301-0 | Basic, ODFE, Xpack |

**Description**
The PCI-DSS dashboard is missing the Controls tab which is present in all other compliance dashboards as well as being present in 4.2.

![image](https://user-images.githubusercontent.com/36071202/144102235-19cb79e2-f201-4b23-ae57-1f1420936ba2.png)

4.3 RC1:
![image](https://user-images.githubusercontent.com/36071202/144102184-58cf50fc-7a14-4bd4-ae38-2f1d4e3c17ad.png)

**Additional context**
This is done using the current pre-release package found here: https://packages-dev.wazuh.com/pre-release/ui/kibana/wazuh_kibana-4.3.0_7.10.2-1.zip

**Comment by Desvelao** [comment]
Fixed in:
branch `4.3-7.10`: https://github.com/wazuh/wazuh-kibana-app/commit/43f0516282db3b4317649fd8635fbd69b0d4280e
branch `4.3-7.10---RC1`: https://github.com/wazuh/wazuh-kibana-app/commit/1b875ac4a76d06ac7e3c2854392da9f6230cdec9
