### ISSUE TITLE
Events table is not sorting fields

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-kibana-app#3718]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 7.13.4     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome |

**Description**
Module -> Events table is not sorting fields.

**Steps to reproduce**
1. Navigate to _Security Events_ (or any other module)
2. Click on _Events_ tab
3. Sort fields asc or desc
4. Check if field is being sorted

**Expected Result**
1. Table rearranges to sort field

**Actual Result**
1. fields are not sorted

**Screenshots**
![Peek 2021-12-02 18-59](https://user-images.githubusercontent.com/9343732/145403788-0bf72a88-84e0-4458-95d4-8693fa5314f8.gif)

**Comment by Desvelao** [comment]
I checked this case in Kibana dev:
- `7.10.2`
- `7.14.2`
and used:
- `Events` tab of the Wazuh plugin
- `Discover` plugin

The behavior is the same.

The displayed case is sorted too by the `Time` column, if you apply another sorting column, the result takes into consideration all sorting columns.

I am not sure what is the result you expected, but if there are multiple sorting columns, the result takes into consideration all the sorting columns. If you want to sort by one column, you should remove other sorting columns.
