### ISSUE TITLE
New tab - Syscollector inventory

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#372]
Wazuh has a new option for collecting data from our agents, it's called Syscollector. The Wazuh app needs a new tab in order to show this new capability to the app users.

New API calls will be needed in order to implement this, and also more debate about the final UI design for this new tab.

**Comment by jesusgn90** [comment]
Included here https://github.com/wazuh/wazuh-kibana-app/tree/3.3-issue-573
