### ISSUE TITLE
Support for Kibana 7.16.x?

### ISSUE THREAD

**Issue by sqall01** [wazuh/wazuh-kibana-app#3727]
Hi,

I wanted to ask if the support for Kibana 7.16.x is on the roadmap and if you have a rough estimate when you think you will support it. With the log4j vulnerability discovered last week, it was vital to update Elasticsearch to 7.16.x to mitigate/fix the vulnerability and now the wazuh plugin is no longer working.

Thanks for your work,
sqall

**Comment by fhielpos** [comment]
Hello team,

The support for this should be based on Elasticsearch 7.16.2 and Wazuh 4.2.5.

Regards,
Franco Hielpos

**Comment by havidarou** [comment]
Duplicate https://github.com/wazuh/wazuh-kibana-app/issues/3749
