### ISSUE TITLE
Release 4.3.0 - Release Candidate 2 - Kibana UI regression testing

### ISSUE THREAD

**Issue by MauGaP** [wazuh/wazuh-kibana-app#3730]
Fixed creation of log files #3384 :white_check_mark:
Fixed double fetching alerts count when pinnin/unpinning the agent in Mitre Att&ck/Framework #3484 :x: (Reopen PR)
Query config refactor #3490 :white_check_mark:
Fixed rules and decoders test flyout clickout event #3412:white_check_mark:
Notify when you are registering an agent without permissions #3430:white_check_mark:
Remove not used redirectRule query param when clicking the row table on CDB Lists/Decoders #3438 :white_check_mark:
Fixed the code overflows over the line numbers in the API Console editor #3439:white_check_mark:
Don't open the main menu when changing the seleted API or index pattern #3440
Fix error message in conf managment #3443 :white_check_mark:
Fix size api selector when name is too long #3445 :white_check_mark:
Fixed error when edit a rule or decoder #3456
Fixed index pattern selector doesn't display the ignored index patterns #3458 :white_check_mark:
Fixed error in /Management/Configuration when cluster is disabled #3553 :white_check_mark:
Fix the pinned filters were removed when accessing to the Panel tab of a module #3565 :white_check_mark:
Fixed multi-select component searcher handler #3645   :white_check_mark:
Fixed order logs properly in Management/Logs #3609 :white_check_mark: 
Fixed the Wazuh API requests to GET // #3661 :white_check_mark: 
Fixed missing mitre tactics #3675:white_check_mark:
Fix CDB list view not working with IPv6 #3488 :white_check_mark:
Fixed the bad requests using Console tool to PUT /active-response API endpoint #3466 :white_check_mark:
Fixed group agent management table does not update on error #3605 :clock1: (No se puede probar por la issue de que no se pueden agregar agentes de manera indivudual)
Fixed not showing packages details in agent inventory for a freeBSD agent SO #3651 :white_check_mark:
Fixed wazuh token deleted twice #3652 :question:
Fixed handler of error on dev-tools #3687 :question:
Fixed compatibility wazuh 4.3 - kibana 7.13.4 #3685 :white_check_mark:
Fixed registry values without agent pinned in FIM>Events #3689 :white_check_mark:
Fixed breadcrumbs style compatibility for Kibana 7.14.2 #3688 :white_check_mark:
Fixed security alerts table when filters change #3682  :white_check_mark:
Fixed error that shows we're using X-Pack when we have Basic #3692 :white_check_mark: 
Fixed blank screen in Kibana 7.10.2 #3700 :white_check_mark:
Fixed related decoder link undefined parameters error #3704 :white_check_mark:
Fixing Flyouts in Kibana 7.14.2 #3708 :white_check_mark:
Fixing the bug of index patterns in health-check due to bad copy of a PR #3707 :white_check_mark:
Fixed styles and behaviour of button filter in the flyout of Inventory section for Integrity monitoring and Vulnerabilities modules #3733 :x: (Reported bug: https://github.com/wazuh/wazuh-kibana-app/issues/3785)
Fixed height of Evolution card in the Agents section when has no data for the selected time range #3733 :x: (Reported bug: https://github.com/wazuh/wazuh-kibana-app/issues/3786)
Fix clearing the query filter doesn't update the data in Office 365 and GitHub Panel tab #3722
Fix wrong deamons in filter list #3710 :white_check_mark:
Fixing bug when create filename with spaces and throws a bad error #3724 :white_check_mark:
Fixing bug in security User flyout nonexistant unsubmitted changes warning #3731
Fixing redirect to new tab when click in a link #3732 :white_check_mark:
Fixed missing settings in Management/Configuration/Global configuration/Global/Main settings #3737 :white_check_mark:
Fixed Maximum call stack size exceeded error exporting key-value pairs of a CDB List #3738 :white_check_mark:
Fixed regex lookahead and lookbehind for safari #3741
Fixed Vulnerabilities Inventory flyout details filters #3744 :white_check_mark:

**Comment by yenienserrano** [comment]
**Description**
When you want to add a new agent with the interactive guide, if we select windows, it breaks

**Issue**
Problem adding windows agents with the interactive guide [#3752](https://github.com/wazuh/wazuh-kibana-app/issues/3752)

**Screenshot**
![image](https://user-images.githubusercontent.com/63758389/147490889-a6986764-e460-47f0-a5e0-8c65305e0af8.png)

**Comment by yenienserrano** [comment]
**Description**
Lets add index patterns that do not exist and shows them in the selector

**Issue**
Add invalid index pattern [#3754](https://github.com/wazuh/wazuh-kibana-app/issues/3754)

**Comment by Mayons** [comment]
We proceed to close this issue since the testing of Release 4.3.0 - Release Candidate 2 - Kibana UI regression testing is done.
@mauceballos @MauGaP
