### ISSUE TITLE
The application does not handle token expiration when a report request is been generated

### ISSUE THREAD

**Issue by Mayons** [wazuh/wazuh-kibana-app#3743]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.2.5  | 7.13.1|  | Xpack |

| Browser |
| ----- |
| Chrome|

**Description**
When the wazuh token expires, and a report generation is requested, the application responds an Internal Server Error (Error code 500).

**Preconditions**
1. Kibana should be running

**Steps to reproduce**
1. Login with valid credentials
2. Wait until Wazuh Token expires
3. Request the generation of any report

**Expected Result**
1. A banner should be displayed with a message informing that the session is expired and the report couldn't be generated

**Actual Result**
1. A banner is displayed with the message "Reporting was aborted (Request failed with status code 401)

**Screenshots**
![image.png](https://images.zenhubusercontent.com/61aa085f76e57e2cf22704e0/1d2a18bb-e3ad-4b96-9785-d97b9333c415)

**Additional context**
Response Body of Generate Report Request:
500 Internal Server Error
{"statusCode":500,"error":"Internal Server Error","message":"5029 - Reporting was aborted (Request failed with status code 401)"}

**Comment by Desvelao** [comment]
## Research
The requests to generate PDF reports are using the `GenericRequest` service that doesn't manage the refreshing of the Wazuh API token.

## Changes
- Replaced the service used from `GenericRequest.request` to `WzRequest.generiqReq` and adapted parameters to work.
