### ISSUE TITLE
Agent management screen filters not working properly.

### ISSUE THREAD

**Issue by abohorqu** [wazuh/wazuh-kibana-app#3750]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.2.5   | 7.10.2| 4206-1 | ODFE  |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**:

Hello team,

We have identified that the filters in the Wazuh Kibana App, Agents tab are not working properly. A specific case is the following:

![image](https://user-images.githubusercontent.com/73501120/147355055-ac0ea2f0-2697-4b8b-9656-30e6d7d5121f.png)

As seen above, trying to filter the agents by `os.platform` and `group` is ignoring a part of the query.

The same thing happens using AND statements:

![image](https://user-images.githubusercontent.com/73501120/147355186-6b2d7304-469d-4fa9-a058-2f652bf5d50f.png)

Another example using just the group filter:

![image](https://user-images.githubusercontent.com/73501120/147355235-21553285-8efb-45cc-b06f-b20485443d66.png)

Please let me know if more information is needed.

**Comment by AlexRuiz7** [comment]
Solved in https://github.com/wazuh/wazuh/issues/10642
