### ISSUE TITLE
Problem adding windows agents with the interactive guide

### ISSUE THREAD

**Issue by yenienserrano** [wazuh/wazuh-kibana-app#3752]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 7.14.2     | 4xxx |  Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
When you want to add a new agent with the interactive guide, if we select windows, it breaks

**Preconditions**
1. use kibana 7.14.2

**Steps to reproduce**
1. Navigate to 'Agents'
2. Click on 'Deploy new agent'
3. Click on  'Windows'

**Expected Result**
1. 
![image](https://user-images.githubusercontent.com/63758389/147490265-5b675bac-023d-4577-b7af-614d010945c3.png)

**Actual Result**
1. 
![image](https://user-images.githubusercontent.com/63758389/147488776-35f41f73-af75-4aef-b614-b56a876824e1.png)

**Comment by Desvelao** [comment]
The versions of `@elastic/eui` package used by Kibana, changed as the text was highlighted in the component `EuiCodeBlock`.

| Kibana | `@elastic/eui` | Text highlight |
| ---- | ---- | ---- |
| 7.10.2 | 29.3.2 | `"highlight.js": "^9.18.5"` |
| 7.13.2 | 32.1.1 | `"highlight.js": "^9.18.5"` |
| 7.14.0 | 34.5.2 | `"refractor": "^3.3.1"` |
| 7.16.2 | 39.1.3 | `"refractor": "^3.5.0"` |

The code of Wazuh app for Kibana was using `ps` as the language, but this value is not valid for Kibana versions with `@elastic/eui` using `refractor`. `powershell` is a valid value for `highlight.js` and `refractor` packages.
