### ISSUE TITLE
Report generation failed when agent filter is applied

### ISSUE THREAD

**Issue by Mayons** [wazuh/wazuh-kibana-app#3758]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 7.16.1 | 4.3 RC2 | Xpack |

| Browser |
| ------- |
| Chrome, Firefox|

**Description**
When the user selects filtering by an agent in the TSC module (or others) and tries to generate a report, this report failed.

**Preconditions**
1. It needs to be logged with valid credentials 
2. It needs to have data in order to generate the report
3. It needs to have at least one agent registered

**Steps to reproduce**
1. Navigate to  TSC Dashboard
2. Set filter by agent
3. Generate the report

**Expected Result**
1. The report should be generated

**Actual Result**
1. An error is displayed, and the report is not being generated

**Screenshots**
https://drive.google.com/file/d/1I-b0NjYrCnhRrBVYzsVAPbyDt8o0nJbW/view?usp=sharing

**Additional context**
@Desvelao mentioned that it can be related to a problem with a hidden table in that module.

**Comment by Desvelao** [comment]
This is fixed in https://github.com/wazuh/wazuh-kibana-app/pull/3748.
