### ISSUE TITLE
I need help for WazuhAPI  foo: [::ffff:127.0.0.1] User: "foo" - Authentication failed.

### ISSUE THREAD

**Issue by Abozaidy** [wazuh/wazuh-kibana-app#3766]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
can you help me to resolve this issue 
[root@server ~]# cat /usr/share/kibana/plugins/wazuh/package.json | grep version
  "version": "3.11.1",
    "version": "7.5.1"
you can see the screenshot below 
https://ibb.co/PspbbSk
No template found for the selected index-pattern.
Check for Wazuh API version loading
Check Wazuh API connection loading
Check Elasticsearch template error

[root@server ~]# tail -n 50 /var/ossec/logs/api.log
WazuhAPI 2021-12-31 00:00:00 foo: Rotated: /var/ossec/logs/api/2021/Dec/api-31-1.gz
WazuhAPI 2021-12-31 00:00:00 foo: [::ffff:127.0.0.1] User: "foo" - Authentication failed.
WazuhAPI 2021-12-31 00:00:00 foo: [::ffff:127.0.0.1] User: "foo" - Authentication failed.
WazuhAPI 2021-12-31 00:15:00 foo: [::ffff:127.0.0.1] User: "foo" - Authentication failed.
WazuhAPI 2021-12-31 00:15:00 foo: [::ffff:127.0.0.1] User: "foo" - Authentication failed.
WazuhAPI 2021-12-31 00:30:00 foo: [::ffff:127.0.0.1] User: "foo" - Authentication failed.
WazuhAPI 2021-12-31 00:30:00 foo: [::ffff:127.0.0.1] User: "foo" - Authentication failed.
WazuhAPI 2021-12-31 00:45:00 foo: [::ffff:127.0.0.1] User: "foo" - Authentication failed.
WazuhAPI 2021-12-31 00:45:00 foo: [::ffff:127.0.0.1] User: "foo" - Authentication failed.
WazuhAPI 2021-12-31 00:50:59 : Listening on: http://10.1.1.221:55000

**Screenshots**
https://ibb.co/PspbbSk

**Comment by Abozaidy** [comment]
Plz i need help

**Comment by asteriscos** [comment]
Hi!
first things first. Let's check wazuh.yml credentials are correct by making an authentication curl request to the API:
`curl -u foo:bar -k -X GET "https://localhost:55000/security/user/authenticate"`

where **_foo:bar_** (default credentials) are the **_user:password_** set up in `/usr/share/kibana/plugins/wazuh/wazuh.yml `

The answer of the request should be something like:
`{"data": {"token": "eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjQzNzExMDg1LCJleHAiOjE2NDM3MTE5ODUsInN1YiI6IndhenVoIiwicnVuX2FzIjpmYwezZSwicmJhY19yb2xlcyI6WzFdLCJyYmFjX21vZGUiOiJ3aGl0ZSJ9.AVVfokHAv3mcNb8GKNAVCCSo5XPhgn_ubhNmb72eOYvndFslsDcpJrH73A5yh3ygpzt5tAQh3DAORUCpO8HbZi6jAdiXpFeTMpasdfrmokQk2f8w-mUBMsCBUqS50IkPWWY1sdsaasdUpMtet4X-5cVjUTm7Il-YT65VOqwehD7H-sQB_dBsH"}, "error": 0}`

Also, 3.11 is a pretty old version and you will probably benefit with several new features by upgrading Wazuh to its latest version (Wazuh 4.3 is coming soon)
https://documentation.wazuh.com/current/docker/upgrade-guide.html
