### ISSUE TITLE
Text overlaps the console play button on Devtools API console

### ISSUE THREAD

**Issue by Mayons** [wazuh/wazuh-kibana-app#3770]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 7.16.1 | 4.3 RC2 | Xpack |

| Browser |
| ------- |
| Firefox, Chrome|

**Description**
When the line of code is long, the text of the code overlaps the play button of the API console

**Preconditions**
Not apply

**Steps to reproduce**
1. Login with valid credentials
2. Navigates to the API Console on Wazuh Devtools.
3. Type a long code line 

**Expected Result**
1. The code should not overlap with the play button

**Actual Result**
1. The code overlap with the play button

**Screenshots**
![Screenshot from 2021-12-31 12-48-11.png](https://images.zenhubusercontent.com/61aa085f76e57e2cf22704e0/d937ead3-1f3d-45b0-bb0f-338727c85bbd)
**Additional context**
Not apply

**Comment by Desvelao** [comment]
## Possible solution
- Add a background to the button/s of same color of highlighted line
