### ISSUE TITLE
Wazuh error: Health check error: requires type and id

### ISSUE THREAD

**Issue by Clilbalk** [wazuh/wazuh-kibana-app#3773]
Hey, I'm using Wazuh 4.1.5 and Kibana 7.10.0

Description:
Each time trying to load the Wazuh page on Kibana this error popped up.
The issue is similar to issue #3129 yet the workarounds suggested didn't work.
The index patterns for Wazuh were created.

Screenshots:
![image](https://user-images.githubusercontent.com/97022423/147915605-9991642a-716f-4e79-828a-d77b4babd613.png)

**Comment by yenienserrano** [comment]
Hi @Clilbalk. Thanks for using wazuh.
a question what security system do you use?
