### ISSUE TITLE
Added wrong character in Register agent code

### ISSUE THREAD

**Issue by Machi3mfl** [wazuh/wazuh-kibana-app#3784]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 7.10     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Safari|

**Description**
Added additional character when dragging inside `Install and enroll the agent` code block in `Register agent`.
Only happen when `windows` O.S is selected.

https://user-images.githubusercontent.com/6089438/148111292-91b43ccd-6b1f-4896-8443-51a2c874985c.mov

**This issue will be fixed by this related issue: #3762**

**Comment by Desvelao** [comment]
This bug only happens in Safari and it could be related to the ReactJS component used from the `@elastic/eui` library.

There is an issue https://github.com/wazuh/wazuh-kibana-app/issues/3762 with some requests for the new agent deployment section whose solution changes as the user copy the command and this bug would not happen.
