### ISSUE TITLE
Test Cases Writing and Organization

### ISSUE THREAD

**Issue by Mayons** [wazuh/wazuh-kibana-app#3797]
This issue is created with the goal of tracking the effort to reorganize1 the existing test cases repositories and the writing of new test cases to cover new scenarios.

**Comment by mauceballos** [comment]
This goal included the new tool to write Test Cases 
[testquality.com](https://www.testquality.com/)

- Credentials:

> - user: wazuh.front@gmail.com
> - pass: Fr0nt2022

I share the screen with the current total of the test cases.

![Screenshot from 2022-01-20 09-33-57](https://user-images.githubusercontent.com/76791841/150344119-37ce29b2-ccdf-4234-a914-d0909423cedc.png)

**Comment by Mayons** [comment]
@asteriscos @Desvelao @yenienserrano
