### ISSUE TITLE
Release 4.3.0 - Release Candidate 3 - Kibana UI regression testing

### ISSUE THREAD

**Issue by Mayons** [wazuh/wazuh-kibana-app#3798]
**For Kibana 7.10.2** 
PRs:
Dashboards PDF report error when switching pinned agent (https://github.com/wazuh/wazuh-kibana-app/pull/3748)
[FIX] [API Console] Styles of action buttons overlaying the request text (https://github.com/wazuh/wazuh-kibana-app/pull/3772)
[FIX] Component rendering of command to deploy new Windows agent(https://github.com/wazuh/wazuh-kibana-app/pull/3753)
[FIX] [REPORTING] [MODULES] Rule ID value in tables related to top results (https://github.com/wazuh/wazuh-kibana-app/pull/3775)
[FIX] [HEALTH CHECK] Run template and fields checks depends on the app configuration(https://github.com/wazuh/wazuh-kibana-app/pull/3783)
[FIX] [Modules] [Panel] Update aggregation data when the time filter is changed (https://github.com/wazuh/wazuh-kibana-app/pull/3790)
Enhance agent deployment UI (https://github.com/wazuh/wazuh-kibana-app/pull/3792)
Github/Office365 multi-select filters fix to get suggested values (https://github.com/wazuh/wazuh-kibana-app/pull/3787)
Feature/rebranding logos
Changed user for manage sample data (https://github.com/wazuh/wazuh-kibana-app/pull/3795)
FEAT]: Add new options of auth for the Registration service configuration heavy_check_mark
[FIX] [GROUPS] Fixes creating a new group with invalid name and no display the remove button in the agents table for the default group heavy_check_mark
[Feature] Rebranding heavy_check_mark
[Feature] Centralize mentions to the plugin platform
[Health check] Fixed when set the default app settings in the plugin platform (Kibana). Pass the health check and review the metaFields, timelion:max_buckets, timepicker:timeDefaults heavy_check_mark
[README.md] [Viewer] Apps screenshots contains the rebranding (logos changes, modules directory icons changes according to the UI)
Set custom logos and the app should display the custom logos instead of the Wazuh logos (menu, sidebar, loading, health check, reports) heavy_check_mark
Changed references to the plugin Platform. See Settings/About and another sections that must reproduce. See wazuh/wazuh-kibana-app@8ccc2c4 wazuh/wazuh-kibana-app@a2150e2 heavy_check_mark
new authd options wazuh/wazuh-kibana-app@3532602
Generate sample data and review the alerts were generated with different IDs, not only 000 wazuh/wazuh-kibana-app@74ff7d3 heavy_check_mark
[Health check] Fixed when set the default app settings in the plugin platform (Kibana). Pass the health check and review the metaFields, timelion:max_buckets, timepicker:timeDefaults
[README.md] [Viewer] Apps screenshots contains the rebranding (logos changes, modules directory icons changes according to the UI) heavy_check_mark
Set custom logos and the app should display the custom logos instead of the Wazuh logos (menu, sidebar, loading, health check, reports)
Changed references to the plugin Platform. See Settings/About and another sections that must reproduce. See wazuh/wazuh-kibana-app@8ccc2c4 wazuh/wazuh-kibana-app@a2150e2
new authd options wazuh/wazuh-kibana-app@3532602 heavy_check_mark
Generate sample data and review the alerts were generated with different IDs, not only 000 wazuh/wazuh-kibana-app@74ff7d3
Closed Issues: 
Added wrong character in Register agent code (https://github.com/wazuh/wazuh-kibana-app/issues/3784)
The height of the evolution card is smaller than the other cards.(https://github.com/wazuh/wazuh-kibana-app/issues/3786)

Pending Issues: 
Issues abiertas relacionadas con cosas fixeadas en previas RC:
The filter button it's overlapping the text (https://github.com/wazuh/wazuh-kibana-app/issues/3785)
https://github.com/wazuh/wazuh-kibana-app/issues/3762 (https://github.com/wazuh/wazuh-kibana-app/issues/3762)

**For Kibana 7.16.2**
PRs:
Fix add single agent to group (https://github.com/wazuh/wazuh-kibana-app/pull/3776)
[FIX] [Modules] Avoid the implicit filters can be removables (https://github.com/wazuh/wazuh-kibana-app/pull/3777)
Fixed Office365/Github module the side panel tab (https://github.com/wazuh/wazuh-kibana-app/pull/3778)
[FIX] [MODULES] [MITRE ATT&CK] [Intelligence] Wrap text in the Description column for the resources info table (https://github.com/wazuh/wazuh-kibana-app/pull/3780)
Fixed visualization echTooltip position (https://github.com/wazuh/wazuh-kibana-app/pull/3781)
Fixed the styles on the evolution card (https://github.com/wazuh/wazuh-kibana-app/pull/3796/#)

**Comment by Mayons** [comment]
Kibana 7.10.2 RC3 Regression Testing Started

**Comment by Mayons** [comment]
End Kibana 7.10.2 RC3 Regression Testing
Kibana 7.16.1 RC3 Regression Testing Started

**Comment by Mayons** [comment]
End Kibana 7.16.1 RC3 Regression Testing
Kibana 7.16.3 RC3 Regression Testing Started

**Comment by Machi3mfl** [comment]
Finished `Kibana 7.16.3 RC3` Regression Testing for `Safari`  ✅
