### ISSUE TITLE
wazuh kibana app is giving me "Saved "field" parameter is now invalid" error

### ISSUE THREAD

**Issue by 6mile** [wazuh/wazuh-kibana-app#38]
Just installed brand new Wazuh server and when I open the Overview and use the General tab I get this:
![screen shot 2017-10-17 at 10 34 44 pm](https://user-images.githubusercontent.com/7798480/31666280-fcdc9ec0-b38e-11e7-86d6-3300e48c98f5.png)

I searched the github issues and found that StasGoshtein mentioned the same error in #25  
The response was to import the sample alerts and refresh the field list but that's not working for me.  When I do a: 
`curl https://github.com/wazuh/wazuh-kibana-app/tree/2.1/server/startup/integration_files/alert_sample.json | curl -XPUT "http://localhost:9200/wazuh-alerts-"`date +%Y.%m.%d`"/wazuh/sample" -H 'Content-Type: application/json' -d @-` 
I get an error saying:
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse"}],"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"not_x_content_exception","reason":"Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes"}},"status":400}

Was running elastic stack 5.6.3 but have now downgraded to 5.6.2 which is working on my dev box, so it appears that the issue is not with the elastic versions but rather with changes made to the wazuh kibana app recently.  Perhaps related to the branching change?  Anyhow, that's beside the point.  A system that was built 14 days ago is working.

Using wazuh-manager 2.1.1

**Comment by havidarou** [comment]
@eastside-hustle You can try to delete the template:

```curl -XDELETE host_to_elastic:9200/_template/wazuh```

And then reinsert the template and the alert_sample.json.

I recommend you to carefully follow our installation guide: https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/index.html

When you say brand new Wazuh server, the Elastic Stack was newly installed too?

Regards.

**Comment by eastside-hustle** [comment]
HI, my issues were two fold:  first, because the Wazuh doco doesn't mention staying away from new versions of the Elastic stack my automation uses version "latest" so when my instance was built it grabbed the latest version of Kibana (5.6.3-1) which is not supported.  Downgrading to 5.6.2 fixed the issue.  The other main issue was that after your recent merge my automation was pointing at the wazuh master branch.  Once I changed everything to point at branch "2.1" things mostly started working.  There are still a few gotchas in the documentation but I now know that I should basically *never* point at branch "master" as what is master will change.

**Comment by havidarou** [comment]
@eastside-hustle Hi, our version 2.1.1 works with Elastic Stack 5.6.3.

It's probable that the problem you were facing was due to the master branch pointing thing.

Regards.

**Comment by sid2rao** [comment]
@eastside-hustle 
I ran in the same error, and trying to downgraded ELK to 5.6.3. But, I cannot find the Wazuhapp for 5.6.3. When I use this instruction below, from the doc, it gets Wazuhapp for 5.6.4, and does not install,
/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp.zip

**Comment by havidarou** [comment]
Hi @sid2rao,

the link you are referencing always belongs to the latest stable release.

You can find a list of all of the packages in our README.md. (https://github.com/wazuh/wazuh-kibana-app/blob/master/README.md)

The specific link you are asking for is this: https://packages.wazuh.com/wazuhapp/wazuhapp-2.1.1_5.6.3.zip

Regards.

**Comment by havidarou** [comment]
Hi @weisst 

we have released our 3.0.0 version, which goes along Elastic Stack 6.0.1.

There are tons of bug and fixes in the app, so I recommend you to upgrade to it.

You can follow our installation guide (it also has an upgrading guide) in: https://documentation.wazuh.com/current/installation-guide/index.html

Regards.
