### ISSUE TITLE
There is no displayed a error message when trying to create a group using a name with special characters

### ISSUE THREAD

**Issue by Mayons** [wazuh/wazuh-kibana-app#3802]
Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 7.10.2     | 4.3 RC2 | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
There is no displayed error message when trying to create a group using a name with special characters

**Preconditions**
1. 

**Steps to reproduce**
1. Navigate to Management/Groups
2. Click on the "Add a new group" button
3. Enter a group name using special characters. Eg: Test()*

**Expected Result**
1. A message it's displayed informing that special characters are not available for groups name

**Actual Result**
1. There is no displayed message when the user tries to create a group using special characters as a group name.

**Comment by Mayons** [comment]
This is still reproducible on Kibana 7.17.0 @Desvelao 

https://user-images.githubusercontent.com/33849347/154119858-9de2d7ea-447e-49ce-9358-b9e23143cd1b.MOV

**Comment by Desvelao** [comment]
Hi @Mayons, did you use a release candidate package or a branch/tag?

I updated the development branch `4.3-7.16` today. If you experienced the problem using this branch, update your local branch and try again to verify.
