### ISSUE TITLE
Main Agent Dashboard sometimes shows the information on MITRE and Compliance, but other times does not.

### ISSUE THREAD

**Issue by Esmirbec** [wazuh/wazuh-kibana-app#3808]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.2.5  | 7.10.2 | 
| Browser |
| ------- |
| Chrome, Firefox, Edge|

**Description**
Main Agent Dashboard sometimes shows the information on MITRE and Compliance, but other times does not.
**Preconditions**
1. 

**Steps to reproduce**
1. Navigate to 'Agents'
2. Click on 'an Agent'
3. Scroll down to 'MITRE and Compliance'

**Expected Result**
1.  See MITRE information and see Compliance information

**Actual Result**
1. Sometimes it shows it for one agent only, but not at other times. It only shows it for that one agent, but not for the other five agents.

**Screenshots**
![Showing information](https://user-images.githubusercontent.com/98118776/150401393-48b31b11-2055-48b3-b4e4-d5cca1ff7fe5.png)

![Not showing information](https://user-images.githubusercontent.com/98118776/150401423-662fdd46-189b-4be2-8f13-66f0e9c54bd4.png)

**Comment by Desvelao** [comment]
Hi @Esmirbec , 

The visualizations and tables in the agent summary dashboard show data depending on a range of time. In the first screenshot, where you have data, the range of time is set to `Last 7 days`. In the second one, the range of time is `Last 24 hours`. If you have alerts for this agent in the selected range of time, the data should appear.

Could you check if there some request that is failing?
1. Open the browser dev tools and navigate to the `Network` tab (F12)
2. Clear the request history
![image](https://user-images.githubusercontent.com/34042064/150958745-8d3df6ab-2691-4462-881c-222336fea657.png)
3. Navigate to the agent summary tab where you are having problems when no data is displayed. Share a screenshot of requests displayed in the `Network` tab of browser dev tools
![image](https://user-images.githubusercontent.com/34042064/150958891-28300dd7-fdcb-459c-9e96-e8c83e720f27.png)
> In the above screenshot, the request worked without problems

If you have some request displayed with the text of red color, that means the request failed. You could review the response and share it to get more information. Moreover, you could share information about the request payload to be sure that the parameters were correct.

**Comment by Esmirbec** [comment]
Hi Antonia,

Thanks for writing back to me.
There are vulnerabilities in those agents and no matter what I change the filter to, they do not show.
I deleted my installation of Wazuh and I tried the unattended installation.
That works fine and I can see vulnerabilities.

It is when you use the Step-by-step guided installation, that something does not go through properly and the Wazuh fails to show vulnerabilities.
I even tried Step-by-step on different Linux distros and it fails to show vulnerabilities each time.

I will keep my unattended install as that seems to work.

Thanks for your help.

Esmir

**Comment by Desvelao** [comment]
Hi, the issue with the vulnerabilities that you mention, is: https://github.com/wazuh/wazuh-kibana-app/issues/3807

Is this the problem you described on this issue referred to the agent dashboard, solved for you?

**Comment by Esmirbec** [comment]
I solved it by reinstalling Wazuh. This time I used unattended install and that worked.
So, there must be an issue with step-by-step install directions.


************************************************
Esmir Bećirović
Sr. Network Administrator
Parkland School District
1210 Springhouse Road
Allentown, PA 18104
External: (610) 351-5612
Internal: 65563
************************************************

**Comment by Desvelao** [comment]
Thank you for replying!

I will close the issue because it was solved.
