### ISSUE TITLE
Wazuh App Overview OSCAP Top 5 agents - Severity high with no bars with long agent names

### ISSUE THREAD

**Issue by spartantri** [wazuh/wazuh-kibana-app#381]
Hi,

The visualization `Wazuh App Overview OSCAP Top 5 agents - Severity high` is not properly displayed when the agent names are long, it looks ok by changing the X-Axis rotation to horizontal and truncate to 25 characters.

Cheers!

**Comment by JuanjiJG** [comment]
Hello @spartantri,

Could you please share a screenshot of your app so we can see the problem?

We'll take your feedback into consideration, and we'll provide a fix if it's necessary in future Wazuh app releases.

Thanks and regards,
Juanjo

**Comment by spartantri** [comment]
Hi @JuanjiJG , here are the screen shots.
X Axis vertical and trucate to 100
![before](https://user-images.githubusercontent.com/12847733/38892475-977e4b18-4287-11e8-93a8-b44d8302a963.png)
X Axis horizontal and truncate to 25
![after](https://user-images.githubusercontent.com/12847733/38892474-97671d94-4287-11e8-99d2-80441333f43b.png)

Cheers!

**Comment by JuanjiJG** [comment]
Hello again @spartantri,

I've added this to our project board, and we'll work on it for future releases. You can keep track on this issue to see future progress.

Regards,
Juanjo

**Comment by JuanjiJG** [comment]
Hello @spartantri,

This issue has been fixed in #429.

Thanks for your report and your patience. Now I'll proceed to close this issue. If you still have questions or problems with anything related to Wazuh, don't hesitate to open a new issue.

Regards,
Juanjo
