### ISSUE TITLE
[Tools/APIConsole] The `#` character provokes a `Parse error` when not used as comment

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#3810]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
The `#` character provokes a `parse error` in the API Console when is not used as the first character of the line. This bug is avoiding to create a user with a password that contains that character. It could be affecting other endpoints when using this character.

## Tasks
- [x] Research the reason for the problem
- [x] Apply the fix to solve it

**Preconditions**
1. 

**Steps to reproduce**
1. Navigate to `Tools/API Console`.
2. Add the next code:
```
POST /security/users
{
  "username": "custom",
  "password": "1234abcD#"
}
```
3. A parse error is displayed in the UI.

**Expected Result**
1. There should not be an error when parsing the API request.

**Actual Result**
1. A parse error is displayed in the UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/34042064/150745220-424bf2e6-344d-4a78-8f50-5e4833249301.png)

**Comment by vikas1389** [comment]
Thanks for accepting this as Bug and creating issue! Please let us know when the fix comes in.

**Comment by Desvelao** [comment]
## Research
The lines that contain the `#` characterare ignored and this does the JSON objects of body request breaks.

## Changes
Only ignore the lines that start with `#` character
