### ISSUE TITLE
Windows Version for Win 11 is incorrect in Inventory Data

### ISSUE THREAD

**Issue by kmfreder1** [wazuh/wazuh-kibana-app#3816]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.2.5   | 7.12.1     | 4206-1 | Xpack |

**Description**
Windows 11 is showing up as Windows 10 in the Inventory Data and on the Agents pages. 

**Preconditions**
1. Upgraded Win 10 Pro to Win 11 through Windows Updates process

**Steps to reproduce**
1. Upgrade Win 10 Pro to Win 11 through Windows Updates process
2. Go to Wazuh>Agents and see the OS associated with the newly upgraded host.
3. Click on agent and on the agent page, see the Operating System data. 
4. Click on Inventory Data and see OS data.

**Expected Result**
1. These data will show the correct Windows version. 

**Actual Result**
1. Windows 10 is referenced even while the build number is correct. 

**Screenshots**
![image](https://user-images.githubusercontent.com/28792720/151231240-e9de9744-92b6-439e-9ac5-baf72d258773.png)

**Comment by asteriscos** [comment]
Hi!
Thanks a lot for bringing it up. This is [a known issue](https://github.com/wazuh/wazuh/issues/10464) which was fixed for Wazuh 4.3, which will soon be released.
