### ISSUE TITLE
Avoid sorting by 'Agents' and 'Configuration checksum' fields in the Groups menu.

### ISSUE THREAD

**Issue by yanazaeva** [wazuh/wazuh-kibana-app#3819]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2 | Wazuh UI | Wazuh UI | - | - |

## Description

Currently, if we go to **Management -> Groups**, and try to order by the `Agents` field or the `Configuration checksum` field, we can see these messages being displayed:
![image](https://user-images.githubusercontent.com/67015786/151792964-7b7a79e6-69f1-49c3-a467-2f2da2cad9d4.png)

These errors appear as there is no API query to sort these values, making the `Name` value the only one that can be sorted. The aim of this issue is to disable the previously mentioned fields from being selected in order to sort them, thus avoiding these errors.

**Comment by mradaszewski92** [comment]
if i can suggest. The idea of sorting by the number of hosts make sense in large environment :)

**Comment by gdiazlo** [comment]
We will fix this and will add the ability to sort by Agents count as @[mradaszewski92](https://github.com/mradaszewski92) suggested. 

We will disable the header `Configuration checksum`  so it is not clickable for ordering.

**Comment by Desvelao** [comment]
# Changes
- Disabled the sorting by the `Agents` due to do it, causes the view breaks:
![image](https://user-images.githubusercontent.com/34042064/161931899-d3bcabea-52b3-473b-8ac3-352309a8df34.png)
