### ISSUE TITLE
Wazuh logo is not rendering 

### ISSUE THREAD

**Issue by Mayons** [wazuh/wazuh-kibana-app#3820]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 7.10.2, 7.16.1 | 4.3 RC3|ODFE|

| Browser |
| ------- |
| Firefox|

**Description**
Wazuh logo is not rendered on Kibana Menu, Wazuh Menu, and on the health check.

**Preconditions**
1. 

**Steps to reproduce**
1. Login to kibana with valid credentials
2. Open the Wazuh plugin

**Expected Result**
1. The Wazuh logo should be rendered on Kibana Menu, Wazuh Menu, and on he Health Check

**Actual Result**
1. The Wazuh logo is not being rendered

**Screenshots**
![Screenshot from 2022-01-31 10-42-11.png](https://images.zenhubusercontent.com/61aa085f76e57e2cf22704e0/694959c1-2689-4e2a-8291-b9cd60be880c)
![image.png](https://images.zenhubusercontent.com/61aa085f76e57e2cf22704e0/8560863b-245c-40f6-8525-f56123884429)
![image.png](https://images.zenhubusercontent.com/61aa085f76e57e2cf22704e0/55d0830e-a1ba-4989-9964-59c94b0a162b)
![Screenshot from 2022-01-31 11-00-20.png](https://images.zenhubusercontent.com/61aa085f76e57e2cf22704e0/0b9b1dfa-5dca-4ee7-9b61-9d34f228845f)

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by Mayons** [comment]
On Chrome browser, the logos are well displayed

**Comment by Desvelao** [comment]
I tested with `Firefox 95.0.2 (64-bit) for Windows 10` and the logos are rendered to me.

Can someone of @wazuh/frontend test it?

**Comment by Mayons** [comment]
This issue was related to a browser problem.
It was tested in a clean browser and works as it's expected.
