### ISSUE TITLE
The agent evolution chart is continuously in loading state

### ISSUE THREAD

**Issue by Mayons** [wazuh/wazuh-kibana-app#3830]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3 | 7.17.0 | 4.3 RC3 | Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
The evolution chart is continuously in a loading state

**Preconditions**
1. Have at least one agent connected to the manager

**Steps to reproduce**
1. Navigate to the agent page

**Expected Result**
1. The agent evolution start should be displayed

**Actual Result**
1. The agent evolution chart is continuously in loading state

**Screenshots**
If applicable, add screenshots to help explain your problem.![image.png](https://images.zenhubusercontent.com/61aa085f76e57e2cf22704e0/2505e2ce-53ea-4428-bb93-cbb5052222bd)

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by Machi3mfl** [comment]
Solution:
- Created new component `wz-kibana-vis`
- Added visualization comprobations. 
- If visualization is valid to render, the component will render the  `kibana-vis` component

Advantages:
- This component will prevent the error in  `kibana > 7.16`  visualization plugin when index pattern doesn't exist.


Screenshot 
<img width="1439" alt="Screen Shot 2022-02-21 at 15 25 58" src="https://user-images.githubusercontent.com/6089438/155009437-5bdd01a4-ffc0-4fec-8f97-6a261d286088.png">
