### ISSUE TITLE
Release 4.3.0 - Release Candidate 4 - Kibana UI regression testing

### ISSUE THREAD

**Issue by Mayons** [wazuh/wazuh-kibana-app#3835]
This issue is created to track the effort to test the RC4 for Wazuh-Kibana app
Kibana version to running the regression:
7.10.2
7.16.3
7.17.0 

Changelog
4.3.0-7.10.2-rc4
Replaced the year in the copyright displayed in the reports page footer
[Fix internal xpack user request forbidden](https://github.com/wazuh/wazuh-kibana-app/pull/3831)
4.3.0-7.16.x-rc4
Replaced the year in the copyright displayed in the reports page footer
[Fix internal xpack user request forbidden](https://github.com/wazuh/wazuh-kibana-app/pull/3831)
4.3.0-1.2.0-rc2
Replaced the year in the copyright displayed in the reports page footer
Fixed error due to the OpenSearch Dashboards version when trying to install the generated package in production

**Comment by matiasmoreno876** [comment]
Bug found [#3844 Graphs are not shown in the reports (Safari)](https://github.com/wazuh/wazuh-kibana-app/issues/3844)

**Comment by MauGaP** [comment]
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

Environment | Total | Pass % | Pending % | KO %
-- | -- | -- | -- | --
ODFE - Chrome - 7.10.2 | 154 | 97% | 2% | 1%
ODFE - Safari - 7.10.2 | 157 | 89% | 11% | 0%
Xpack - Chrome - 7.16.3 | 154 | 95% | 5% | 0%
Xpack - Firefox - 7.16.3 | 154 | 95% | 5% | 0%
Xpack - Safari - 7.16.3 | 154 | 91% | 9% | 0%
Xpack - Safari - 7.17.0 | 154 | 95% | 5% | 0%
Xpack - Chrome - 7.17.0 | 154 | 79% | 21% | 0%
OSFE - Chrome - 1.2.0 | 154 | 86% | 14% | 0%
OSFE - Safari - 1.2.0 | 157 | 13% | 87% | 0%


</body>
</html>

**Comment by MauGaP** [comment]
Environment | Total | Pass % | Pending % | KO %
-- | -- | -- | -- | --
ODFE - Chrome - 7.10.2 | 153 | 99% | 0% | 1%
ODFE - Safari - 7.10.2 | 153 | 93% | 2% | 0%
Xpack - Chrome - 7.16.3 | 153 | 97% | 3% | 0%
Xpack - Firefox - 7.16.3 | 153 | 97% | 3% | 0%
Xpack - Safari - 7.16.3 | 153 | 95% | 5% | 0%
Xpack - Safari - 7.17.0 | 153 | 97% | 2% | 0%
Xpack - Chrome - 7.17.0 | 153 | 100% | 0% | 0%
OSFE - Chrome - 1.2.0 | 153 | 94% | 3% | 3%
OSFE - Safari - 1.2.0 | 153 | 94% | 3% | 3%

Total | 1377
Pass | 1327
Pending | 29
KO | 11

**Comment by MauGaP** [comment]
Environment | Total | Pass % | Pending % | KO %
-- | -- | -- | -- | --
ODFE - Chrome - 7.10.2 | 153 | 99% | 0% | 1%
ODFE - Safari - 7.10.2 | 153 | 95% | 0% | 0%
Xpack - Chrome - 7.16.3 | 153 | 99% | 0% | 0%
Xpack - Firefox - 7.16.3 | 153 | 99% | 0% | 0%
Xpack - Safari - 7.16.3 | 153 | 99% | 0% | 0%
Xpack - Safari - 7.17.0 | 153 | 97% | 0% | 0%
Xpack - Chrome - 7.17.0 | 153 | 99% | 0% | 0%
OSFE - Chrome - 1.2.0 | 153 | 95% | 0% | 3%
OSFE - Safari - 1.2.0 | 153 | 97% | 0% | 3%
Wazuh - Dashboard - Chrome - 1.2.0 | 153 | 57% | 36% | 5%
Wazuh - Dashboard - Firefox - 1.2.0 | 153 | 42% | 57% | 1%

Total | 1683
-- | --
Pass | 1498
Pending | 142
KO | 20

**Comment by asteriscos** [comment]
Environment | Total | Pass % | Pending % | KO %
-- | -- | -- | -- | --
ODFE - Chrome - 7.10.2 | 153 | 99% | 0% | 1%
ODFE - Safari - 7.10.2 | 153 | 95% | 0% | 0%
Xpack - Chrome - 7.16.3 | 153 | 99% | 0% | 0%
Xpack - Firefox - 7.16.3 | 153 | 99% | 0% | 0%
Xpack - Safari - 7.16.3 | 153 | 99% | 0% | 0%
Xpack - Safari - 7.17.0 | 153 | 97% | 0% | 0%
Xpack - Chrome - 7.17.0 | 153 | 99% | 0% | 0%
OSFE - Chrome - 1.2.0 | 153 | 95% | 0% | 3%
OSFE - Safari - 1.2.0 | 153 | 97% | 0% | 3%
Wazuh - Dashboard - Chrome - 1.2.0 | 153 | 92% | 0% | 7%
Wazuh - Dashboard - Firefox - 1.2.0 | 153 | 93% | 3% | 4%
Wazuh - Dashboard - Safari - 1.2.0 | 153 | 71% | 20% | 9%

Total | 1836
-- | --
Pass | 1737
Pending | 35
KO | 41

**Comment by Mayons** [comment]
Environment | Total | Pass % | Pending % | KO %
-- | -- | -- | -- | --
ODFE - Chrome - 7.10.2 | 153 | 99% | 0% | 1%
ODFE - Safari - 7.10.2 | 153 | 95% | 0% | 0%
Xpack - Chrome - 7.16.3 | 153 | 99% | 0% | 0%
Xpack - Firefox - 7.16.3 | 153 | 99% | 0% | 0%
Xpack - Safari - 7.16.3 | 153 | 99% | 0% | 0%
Xpack - Safari - 7.17.0 | 153 | 97% | 0% | 0%
Xpack - Chrome - 7.17.0 | 153 | 99% | 0% | 0%
OSFE - Chrome - 1.2.0 | 153 | 95% | 0% | 3%
OSFE - Safari - 1.2.0 | 153 | 97% | 0% | 3%
Wazuh - Dashboard - Chrome - 1.2.0 | 153 | 92% | 0% | 7%
Wazuh - Dashboard - Firefox - 1.2.0 | 153 | 96% | 0% | 4%
Wazuh - Dashboard - Safari - 1.2.0 | 153 | 87% | 9% | 3%

Total | 1836
-- | --
Pass | 1766
Pending | 14
KO | 32

**Comment by Mayons** [comment]
<google-sheets-html-origin><style type="text/css"></style>

Environment | Total | Pass % | Pending % | KO %
-- | -- | -- | -- | --
ODFE - Chrome - 7.10.2 | 153 | 99% | 0% | 1%
ODFE - Safari - 7.10.2 | 153 | 95% | 0% | 0%
Xpack - Chrome - 7.16.3 | 153 | 99% | 0% | 0%
Xpack - Firefox - 7.16.3 | 153 | 99% | 0% | 0%
Xpack - Safari - 7.16.3 | 153 | 99% | 0% | 0%
Xpack - Safari - 7.17.0 | 153 | 97% | 0% | 0%
Xpack - Chrome - 7.17.0 | 153 | 99% | 0% | 0%
OSFE - Chrome - 1.2.0 | 153 | 95% | 0% | 3%
OSFE - Safari - 1.2.0 | 153 | 97% | 0% | 3%
Wazuh - Dashboard - Chrome - 1.2.0 | 153 | 93% | 0% | 5%
Wazuh - Dashboard - Firefox - 1.2.0 | 153 | 96% | 0% | 4%
Wazuh - Dashboard - Safari - 1.2.0 | 153 | 96% | 0% | 3%

**Comment by Mayons** [comment]
Regression task closed.
