### ISSUE TITLE
Different background colors in overview page on the agent section

### ISSUE THREAD

**Issue by Mayons** [wazuh/wazuh-kibana-app#3842]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 7.16.3    | 4.3 RC4 |Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
There are displayed different colors in the overview page on the agent section

**Steps to reproduce**
1. Navigate to the overview page

**Expected Result**
1. The background color is universal on all the page

**Actual Result**
1. There are different background colors on the agent section on the overview page

**Screenshots**
https://files.slack.com/files-pri/TMYFNFQ3W-F032Q1NQWFM/screen_shot_2022-02-11_at_09.52.25.png
![image.png](https://images.zenhubusercontent.com/61aa085f76e57e2cf22704e0/6f173588-b1fe-43ac-bf53-588480b89968)
**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by chantal-kelm** [comment]
I spoke with Daiana from design and she told me that she thinks it's good how the contrasting colors are currently.
