### ISSUE TITLE
Add step to start Windows Service to installation instructions

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-kibana-app#3843]
With the changes in this PR:
https://github.com/wazuh/wazuh/pull/12271

The Windows agent will not start automatically when using the deployment variables, we need to reflect these changes in the instructions given to the user by the Kibana plugin.

**Comment by Desvelao** [comment]
### Changes

- Added the step to start the Windows agent after the installation
 ![image](https://user-images.githubusercontent.com/34042064/154049407-764485ba-56e2-4f7f-bfa4-631cebeadd2f.png)
