### ISSUE TITLE
Add DB limit settings to the FIM configuration

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-kibana-app#3849]
Hi team,

As part of https://github.com/wazuh/wazuh/issues/9103 new options have been added to the FIM configuration in order to limit the number of entries in the FIM databases. 

Before the change, the FIM configuration was limited to file entries and look like:
```xml
<!-- Maximum number of files to be monitored -->
<file_limit>
  <enabled>yes</enabled>
  <entries>100000</entries>
</file_limit>
```

In the WUI, it is represented as follows:
![image](https://user-images.githubusercontent.com/29475387/154239622-b5a096cf-fc4e-476d-a052-5e70c60a6d9f.png)

Now, that block is replaced by:
```xml
<!-- Maximum number of entries to be monitored -->
<db_entry_limit>
  <enabled>yes</enabled>
  <files>50000</files>
  <registries>50000</registries>
</db_entry_limit>
```

So this change should be applied in the WUI as well.

## Update

The requirements for these settings changed, here the latest update:

- Instead of the `db_entry_limit` block, the `file_limit` block remains in use, and also a new block called `registry_limit` is added with the same appearance as the `file_limit`.
```
    <registry_limit>
      <enabled>yes</enabled>
      <entries>100000</entries>
    </registry_limit>
```

- Inside the synchronization config, a new setting called `thread_pool` is added. It specifies the number of threads used by the FIM database synchronization. FIM will use the minimum number between the configured value and the number of CPU cores of the system.
```
<synchronization>
  <thread_pool>1</thread_pool>
</synchronization>
```

Best regards,
Chema.

**Comment by Machi3mfl** [comment]
Solution screenshot:

<img width="1440" alt="Screen Shot 2022-03-23 at 14 06 32" src="https://user-images.githubusercontent.com/6089438/159756651-54bdc33a-4d1f-4e05-8690-27e8eb635999.png">


New Title, subtitle and label texts based on: [Syscheck options for v4.4](https://github.com/wazuh/wazuh-documentation/blob/adc4ed3ff50a544f0f903ed223b89df1aeb56975/source/user-manual/reference/ossec-conf/syscheck.rst)

**Comment by Machi3mfl** [comment]
Testing:
This PR depends on [9103-replace-fim-db-dbsync](https://github.com/wazuh/wazuh/tree/9103-replace-fim-db-dbsync) `wazuh/wazuh` branch

**Comment by chemamartinez** [comment]
Hi team,

The requirements for these settings changed, here the latest update:

- Instead of the `db_entry_limit` block, the `file_limit` block remains in use and also a new block called `registry_limit` with the same appearance as the `file_limit`.
```xml
    <registry_limit>
      <enabled>yes</enabled>
      <entries>100000</entries>
    </registry_limit>
```
- Inside the `synchronization` config, a new setting called `thread_pool` is added. It specifies the number of threads used by the FIM database synchronization. FIM will use the minimum number between the configured value and the number of CPU cores of the system.
```xml
<synchronization>
  <thread_pool>1</thread_pool>
</synchronization>
```

Any questions, please ask @wazuh/watchdogs team.

**Comment by Machi3mfl** [comment]
Issue solved in https://github.com/wazuh/wazuh-kibana-app/pull/3913
