### ISSUE TITLE
Enabling vulnerability checks

### ISSUE THREAD

**Issue by spartantri** [wazuh/wazuh-kibana-app#385]
Hi,

How may I enable the vulnerability checks on the agents?

I changed the ossec.conf as shown below but the vulnerability tab is empty, my test agents have no internet connectivity so where should I store the `ssg-rhel-7-ds.xml` file for the checks?

```
  <wodle name="open-scap">
    <disabled>no</disabled>
    <timeout>1800</timeout>
    <interval>1d</interval>
    <scan-on-start>yes</scan-on-start>

    <content type="xccdf" path="ssg-rhel-7-ds.xml">
      <profile>xccdf_org.ssgproject.content_profile_pci-dss</profile>
      <profile>xccdf_org.ssgproject.content_profile_common</profile>
    </content>
    <content type="xccdf" path="cve-redhat-7-ds.xml"/>
  </wodle>
```

Regards,
Manuel

**Comment by JuanjiJG** [comment]
Hello @spartantri,

That XML code is for configuring [Open-SCAP](https://documentation.wazuh.com/current/user-manual/capabilities/policy-monitoring/openscap/index.html). Our vulnerability detection tool uses a different configuration.

To enable the vulnerability detection tool on your agents, you only need to configure `syscollector` on their `ossec.conf` file, so they can send their system info to the manager, who will perform the analysis. Keep in mind that you need at least the 3.2.0 version of Wazuh, but I recommend you to use our latest version, 3.2.1.

You can read more information [in our documentation](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection.html), but let me give you a brief explanation of the necessary steps:

1. Configure the `ossec.conf` file on each agent with the `syscollector` module:
```XML
<wodle name="syscollector">
  <disabled>no</disabled>
  <interval>1h</interval>
  <packages>yes</packages>
</wodle>
```

2. Restart your agents:
```bash
systemctl restart wazuh-agent
```

3. Configure the `ossec.conf` file on the manager with the `syscollector` and `vulnerability-detector` modules:
```XML
<wodle name="syscollector">
  <disabled>no</disabled>
  <interval>1h</interval>
  <packages>yes</packages>
</wodle>

<wodle name="vulnerability-detector">
  <disabled>no</disabled>
  <interval>1d</interval>
  <run_on_start>yes</run_on_start>
  <update_ubuntu_oval interval="15h" version="16,14">yes</update_ubuntu_oval>
  <update_redhat_oval interval="15h" version="7,6">yes</update_redhat_oval>
</wodle>
```

4. Restart the manager
```bash
systemctl restart wazuh-manager
```

Now you have to wait some minutes until the scan finishes. Then, you should be able to see content on the Vulnerabilities tab of the Wazuh app.

Regarding your question about the Internet connection on your agents, it's not necessary for this vulnerability detection tool. Only the manager needs an Internet connection. In next versions of Wazuh, we'll provide the possibility of using local OVAL databases for performing the scans.

If you have more questions, feel free to post a new comment.

Regards,
Juanjo

**Comment by JuanjiJG** [comment]
Hello again @spartantri,

It's been more than a month since the last response to this issue. I'll proceed to close it. Don't hesitate to open a new one if you have questions or need help with Wazuh.

Regards,
Juanjo

**Comment by valour1992** [comment]
Hello ,
How can we test its capability for malware detection for test environment any suggestion or refernces?

**Comment by stoksoz1** [comment]
Hi,
Can we use debian10 for this open-scap security control?

Second question is where we put the xml file on wazuh server?

Thanks
