### ISSUE TITLE
Release 4.3.0 - Release Candidate 6 - UI regression testing

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#3858]
# Testing release candidate
## Wazuh app for Kibana 4.3.0-7.10.2-rc6
- Added step to start the Windows agent in the deploy new agent guide https://github.com/wazuh/wazuh-kibana-app/pull/3846
- Fixed long agent names in the Details card of the Agents section https://github.com/wazuh/wazuh-kibana-app/pull/3845
- Changed links to documentation referencing to Kibana app by Wazuh dashboard https://github.com/wazuh/wazuh-kibana-app/commit/7e1a91746a113145f8df87d485a32174b7318127

## Wazuh app for Kibana 4.3.0-7.16.3-rc6 and 4.3.0-7.17.0-rc6
- Added step to start the Windows agent in the deploy new agent guide https://github.com/wazuh/wazuh-kibana-app/pull/3846
- Fixed long agent names in the Details card of the Agents section https://github.com/wazuh/wazuh-kibana-app/pull/3845
- Changed links to documentation referencing to Kibana app by Wazuh dashboard https://github.com/wazuh/wazuh-kibana-app/commit/7e1a91746a113145f8df87d485a32174b7318127
- Added a check to see if there are monitoring indices in the `Evolution` visualization of Agents section https://github.com/wazuh/wazuh-kibana-app/pull/3854

## Wazuh app for Wazuh dashboard 4.3.0-1.2.0-rc4
- Added step to start the Windows agent in the deploy new agent guide https://github.com/wazuh/wazuh-kibana-app/pull/3846
- Fixed long agent names in the Details card of the Agents section https://github.com/wazuh/wazuh-kibana-app/pull/3845
- Fixed redirection of View surrounding documents and View single document buttons https://github.com/wazuh/wazuh-kibana-app/commit/1fe8eef01a776908c56e8b4c502a01854f19df57)
- Renamed the references to the plugin platform (name, installation path, owner user, ower group, help links) https://github.com/wazuh/wazuh-kibana-app/commit/461611954009d13fdf4f59777526c4ca58be16fd

# Results
## Wazuh app for Kibana 4.3.0-7.10.2-rc6
| Test | Result |
| ---   | -----   |
| Added step to start the Windows agent in the deploy new agent guide | ✅  |
| Fixed long agent names in the Details card of the Agents section | ✅  |
| Changed links to documentation referencing to Kibana app by Wazuh dashboard | ✅ |

## Wazuh app for Kibana 4.3.0-7.16.3-rc6
| Test | Result |
| ---   | -----   |
| Added step to start the Windows agent in the deploy new agent guide |  ✅  |
| Fixed long agent names in the Details card of the Agents section | ✅ |
| Changed links to documentation referencing to Kibana app by Wazuh dashboard | ✅ |
| Added a check to see if there are monitoring indices in the `Evolution` visualization of Agents section | ✅ |

## Wazuh app for Kibana 4.3.0-7.17.0-rc6
| Test | Result |
| ---   | -----   |
| Added step to start the Windows agent in the deploy new agent guide | ✅  |
| Fixed long agent names in the Details card of the Agents section |  ✅|
| Changed links to documentation referencing to Kibana app by Wazuh dashboard |✅|  |
| Added a check to see if there are monitoring indices in the `Evolution` visualization of Agents section | ✅ |

## Wazuh app for Wazuh dashboard 4.3.0-1.2.0-rc6
| Test | Result |
| ---   | -----   |
| Added step to start the Windows agent in the deploy new agent guide | ✅ |
| Fixed long agent names in the Details card of the Agents section | ✅ |
| Fixed redirection of View surrounding documents and View single document buttons | ✅ |
| Renamed the references to the plugin platform (name, installation path, owner user, ower group, help links)  | ✅ |

**Comment by Desvelao** [comment]
Test:
⚠️ Added step to start the Windows agent in the deploy new agent guide https://github.com/wazuh/wazuh-kibana-app/pull/3846

The is a different behavior when using screens with small sizes like mobile phones. The stats related to the agent names are being displayed in the same lane instead of different lines.

Before:
![image](https://user-images.githubusercontent.com/34042064/155307680-30b5f9b4-2d85-4116-869a-acf969c705d9.png)

RC5:
![image](https://user-images.githubusercontent.com/34042064/155308071-a48c7123-2743-498e-9fe2-e5d3d7640671.png)

**Comment by Desvelao** [comment]
## Issue changes
- Modified the issue to `rc6` for Kibana and `rc4` for Wazuh dashboard

**Comment by Machi3mfl** [comment]
Tested in `7.10.2` (Chrome and Safari)
<img width="1433" alt="Screen Shot 2022-02-23 at 12 53 57" src="https://user-images.githubusercontent.com/6089438/155356860-0a578cdb-a6a1-4154-979a-0924e6215640.png">

Added step to start the Windows agent in the deploy new agent guide 

Fixed long agent names in the Details card of the Agents section 

Changed links to documentation referencing to Kibana app by Wazuh dashboard
