### ISSUE TITLE
Could not locate that index-pattern (id: wazuh-alerts-3.x-*)

### ISSUE THREAD

**Issue by Strepsil** [wazuh/wazuh-kibana-app#386]
Hi, 

I have been banging my head against the wall for a couple of days now regarding index-pattern not found. The installation has been done multiple times now with both uninstalling the whole ELK setup with Wazuh, and then re-installing everything fresh. 

Here is the error I'm receiving:

![error](https://user-images.githubusercontent.com/35831623/38979095-87cc2284-43b9-11e8-92d6-26ae8c3c5188.PNG)

_cat/indices?v:

![error2](https://user-images.githubusercontent.com/35831623/38979237-ea3541ee-43b9-11e8-8b80-9644b9487abf.PNG)
 
And here are the patterns: 

![error3](https://user-images.githubusercontent.com/35831623/38979342-2954775a-43ba-11e8-8dcd-1dfd978fbf8e.PNG)

The API is working and I have gotten computers to log information into wazuh-alerts-3.x-*. 

If you need more information I will gladly paste the commands and show the results :)

**Comment by jesusgn90** [comment]
Hi @Strepsil ,

please could you paste the output of the next command?

```
# curl elastic_ip:9200/.kibana/_search?pretty -H 'Content-Type: application/json' -d'{"size":9999}' -s | grep -i "index-pattern"
```

This way we can check if your index pattern for wazuh-alerts-3.x-* is created on a wrong way checking its `_id` thanks

Regards,
Jesús

**Comment by Strepsil** [comment]
Hi @jesusgn90 

Here is the output: 

`curl elastic_ip:9200/.kibana/_search?pretty -H 'Content-Type: application/json' -d'{"size":9999}' -s | grep -i "index-pattern"
        "_id" : "index-pattern:wazuh-alerts-3.x-*",
          "type" : "index-pattern",
          "index-pattern" : {
        "_id" : "index-pattern:wazuh-monitoring-3.x-*",
          "type" : "index-pattern",
          "index-pattern" : {
`

**Comment by jesusgn90** [comment]
Ok @Strepsil , they are fine. 

Now we are going to discard any browser related error. Could you please open a new incognito window on your browser and try it again?

Best,
Jesús

**Comment by Strepsil** [comment]
@jesusgn90 

Still the same error, but now I'm not even getting to the discover page in the wazuh tab.

![error4](https://user-images.githubusercontent.com/35831623/38981687-449970d2-43c0-11e8-8152-ce1f253420c9.PNG)

**Comment by jesusgn90** [comment]
At this point my suggestion is to force the Wazuh app to re-create the main indices as follow:

```
# systemctl stop kibana
# curl -XDELETE elastic_ip:9200/.kibana,.wazuh,.wazuh-version
# systemctl restart kibana
```

wait few seconds and open a new incognito window on your browser to try again.

Best regards,
Jesús

**Comment by Strepsil** [comment]
@jesusgn90 

same problem :(

**Comment by Strepsil** [comment]
Also if I go to the settings tab in Wazuh and look under "Pattern" I can see that index-pattern there that I'm trying to use and it says `wazuh-alerts-3.x-*`, one thing is that I can't choose another pattern, event though I have the `wazuh-monitoring-3.x-*`, but maybe that is by design?

**Comment by Strepsil** [comment]
This shouldn't be a issue I guess but maybe I should explain it also. When I installed the plugin, because I'm behind a outgoing proxy and the `./kibana-plugin` don't have a option to use for example like curl `--noproxy <host>`. So i just downloaded the .zip and the used file:\\\usr\share\........ to install Wazuh.

**Comment by jesusgn90** [comment]
@Strepsil the `wazuh-monitoring-3.x-*` index pattern is only used to generate the visualization Agents Status and is not useful to use on the whole app, that's because we don't able the user to select it. Regarding to your installation way from file, it's ok, we use it lot of times while developing.

Let's check more in deep what's happening here. 

Please, could you paste the output of the next command? (in order to check mapping being applied to your latest index)

```
# curl elastic_ip:9200/wazuh-alerts-3.x-2018.04.19/_mapping?pretty
```

Where `-2018.04.19` should be your latest wazuh-alerts index created, you can check it from `curl elastic_ip:9200/_cat/indices`

Also I think you could be outdated, which Elasticsearch version do you have?
Which Wazuh App revision do you have?

```
# curl elastic_ip:9200 -s | grep number
# cat /usr/share/kibana/plugins/wazuh/package.json | grep -i -E "version|revision"
```

Thanks in advance,
Jesús

**Comment by Strepsil** [comment]
Here is the _mapping: 
`wazuh-alerts-3.x-2018.04.19/_mapping?pretty
{
  "wazuh-alerts-3.x-2018.04.19" : {
    "mappings" : {
      "wazuh" : {
        "dynamic_templates" : [
          {
            "string_as_keyword" : {
              "match_mapping_type" : "string",
              "mapping" : {
                "doc_values" : "true",
                "type" : "keyword"
              }
            }
          }
        ],
        "properties" : {
          "@timestamp" : {
            "type" : "date",
            "format" : "dateOptionalTime"
          },
          "@version" : {
            "type" : "text"
          },
          "AlertsFile" : {
            "type" : "keyword"
          },
          "GeoLocation" : {
            "properties" : {
              "area_code" : {
                "type" : "long"
              },
              "city_name" : {
                "type" : "keyword"
              },
              "continent_code" : {
                "type" : "text"
              },
              "coordinates" : {
                "type" : "double"
              },
              "country_code2" : {
                "type" : "text"
              },
              "country_code3" : {
                "type" : "text"
              },
              "country_name" : {
                "type" : "keyword"
              },
              "dma_code" : {
                "type" : "long"
              },
              "ip" : {
                "type" : "keyword"
              },
              "latitude" : {
                "type" : "double"
              },
              "location" : {
                "type" : "geo_point"
              },
              "longitude" : {
                "type" : "double"
              },
              "postal_code" : {
                "type" : "keyword"
              },
              "real_region_name" : {
                "type" : "keyword"
              },
              "region_name" : {
                "type" : "keyword"
              },
              "timezone" : {
                "type" : "text"
              }
            }
          },
          "agent" : {
            "properties" : {
              "id" : {
                "type" : "keyword"
              },
              "ip" : {
                "type" : "keyword"
              },
              "name" : {
                "type" : "keyword"
              }
            }
          },
          "cluster" : {
            "properties" : {
              "name" : {
                "type" : "keyword"
              }
            }
          },
          "command" : {
            "type" : "keyword"
          },
          "data" : {
            "properties" : {
              "account_domain" : {
                "type" : "keyword"
              },
              "account_name" : {
                "type" : "keyword"
              },
              "action" : {
                "type" : "keyword"
              },
              "audit" : {
                "properties" : {
                  "acct" : {
                    "type" : "keyword"
                  },
                  "auid" : {
                    "type" : "keyword"
                  },
                  "command" : {
                    "type" : "keyword"
                  },
                  "cwd" : {
                    "type" : "keyword"
                  },
                  "dev" : {
                    "type" : "keyword"
                  },
                  "directory" : {
                    "properties" : {
                      "inode" : {
                        "type" : "keyword"
                      },
                      "mode" : {
                        "type" : "keyword"
                      },
                      "name" : {
                        "type" : "keyword"
                      }
                    }
                  },
                  "egid" : {
                    "type" : "keyword"
                  },
                  "enforcing" : {
                    "type" : "keyword"
                  },
                  "euid" : {
                    "type" : "keyword"
                  },
                  "exe" : {
                    "type" : "keyword"
                  },
                  "exit" : {
                    "type" : "keyword"
                  },
                  "file" : {
                    "properties" : {
                      "inode" : {
                        "type" : "keyword"
                      },
                      "mode" : {
                        "type" : "keyword"
                      },
                      "name" : {
                        "type" : "keyword"
                      }
                    }
                  },
                  "fsgid" : {
                    "type" : "keyword"
                  },
                  "fsuid" : {
                    "type" : "keyword"
                  },
                  "gid" : {
                    "type" : "keyword"
                  },
                  "id" : {
                    "type" : "keyword"
                  },
                  "key" : {
                    "type" : "keyword"
                  },
                  "list" : {
                    "type" : "keyword"
                  },
                  "old-auid" : {
                    "type" : "keyword"
                  },
                  "old-ses" : {
                    "type" : "keyword"
                  },
                  "old_enforcing" : {
                    "type" : "keyword"
                  },
                  "old_prom" : {
                    "type" : "keyword"
                  },
                  "op" : {
                    "type" : "keyword"
                  },
                  "pid" : {
                    "type" : "keyword"
                  },
                  "ppid" : {
                    "type" : "keyword"
                  },
                  "prom" : {
                    "type" : "keyword"
                  },
                  "res" : {
                    "type" : "keyword"
                  },
                  "session" : {
                    "type" : "keyword"
                  },
                  "sgid" : {
                    "type" : "keyword"
                  },
                  "srcip" : {
                    "type" : "keyword"
                  },
                  "subj" : {
                    "type" : "keyword"
                  },
                  "success" : {
                    "type" : "keyword"
                  },
                  "suid" : {
                    "type" : "keyword"
                  },
                  "syscall" : {
                    "type" : "keyword"
                  },
                  "tty" : {
                    "type" : "keyword"
                  },
                  "type" : {
                    "type" : "keyword"
                  },
                  "uid" : {
                    "type" : "keyword"
                  }
                }
              },
              "command" : {
                "type" : "keyword"
              },
              "data" : {
                "type" : "keyword"
              },
              "dstip" : {
                "type" : "keyword"
              },
              "dstport" : {
                "type" : "keyword"
              },
              "dstuser" : {
                "type" : "keyword"
              },
              "file" : {
                "type" : "keyword"
              },
              "id" : {
                "type" : "keyword"
              },
              "logon_type" : {
                "type" : "keyword"
              },
              "oscap" : {
                "properties" : {
                  "check" : {
                    "properties" : {
                      "description" : {
                        "type" : "text"
                      },
                      "id" : {
                        "type" : "keyword"
                      },
                      "identifiers" : {
                        "type" : "text"
                      },
                      "oval" : {
                        "properties" : {
                          "id" : {
                            "type" : "keyword"
                          }
                        }
                      },
                      "rationale" : {
                        "type" : "text"
                      },
                      "references" : {
                        "type" : "text"
                      },
                      "result" : {
                        "type" : "keyword"
                      },
                      "severity" : {
                        "type" : "keyword"
                      },
                      "title" : {
                        "type" : "keyword"
                      }
                    }
                  },
                  "scan" : {
                    "properties" : {
                      "benchmark" : {
                        "properties" : {
                          "id" : {
                            "type" : "keyword"
                          }
                        }
                      },
                      "content" : {
                        "type" : "keyword"
                      },
                      "id" : {
                        "type" : "keyword"
                      },
                      "profile" : {
                        "properties" : {
                          "id" : {
                            "type" : "keyword"
                          },
                          "title" : {
                            "type" : "keyword"
                          }
                        }
                      },
                      "return_code" : {
                        "type" : "long"
                      },
                      "score" : {
                        "type" : "double"
                      }
                    }
                  }
                }
              },
              "protocol" : {
                "type" : "keyword"
              },
              "pwd" : {
                "type" : "keyword"
              },
              "security_id" : {
                "type" : "keyword"
              },
              "srcip" : {
                "type" : "keyword"
              },
              "srcport" : {
                "type" : "keyword"
              },
              "srcuser" : {
                "type" : "keyword"
              },
              "status" : {
                "type" : "keyword"
              },
              "subject" : {
                "properties" : {
                  "account_domain" : {
                    "type" : "keyword"
                  },
                  "account_name" : {
                    "type" : "keyword"
                  },
                  "logon_id" : {
                    "type" : "keyword"
                  },
                  "security_id" : {
                    "type" : "keyword"
                  }
                }
              },
              "system_name" : {
                "type" : "keyword"
              },
              "title" : {
                "type" : "keyword"
              },
              "tty" : {
                "type" : "keyword"
              },
              "type" : {
                "type" : "keyword"
              },
              "uid" : {
                "type" : "keyword"
              },
              "url" : {
                "type" : "keyword"
              }
            }
          },
          "date" : {
            "type" : "date"
          },
          "decoder" : {
            "properties" : {
              "accumulate" : {
                "type" : "long"
              },
              "fts" : {
                "type" : "long"
              },
              "ftscomment" : {
                "type" : "keyword"
              },
              "name" : {
                "type" : "keyword"
              },
              "parent" : {
                "type" : "keyword"
              }
            }
          },
          "direction" : {
            "type" : "keyword"
          },
          "entity" : {
            "type" : "keyword"
          },
          "full_log" : {
            "type" : "text"
          },
          "host" : {
            "type" : "keyword"
          },
          "id" : {
            "type" : "keyword"
          },
          "ip" : {
            "type" : "keyword"
          },
          "location" : {
            "type" : "keyword"
          },
          "manager" : {
            "properties" : {
              "name" : {
                "type" : "keyword"
              }
            }
          },
          "message" : {
            "type" : "text"
          },
          "notes" : {
            "type" : "keyword"
          },
          "offset" : {
            "type" : "keyword"
          },
          "path" : {
            "type" : "keyword"
          },
          "predecoder" : {
            "properties" : {
              "hostname" : {
                "type" : "keyword"
              },
              "program_name" : {
                "type" : "keyword"
              },
              "timestamp" : {
                "type" : "keyword"
              }
            }
          },
          "previous_log" : {
            "type" : "text"
          },
          "previous_output" : {
            "type" : "keyword"
          },
          "program_name" : {
            "type" : "keyword"
          },
          "rule" : {
            "properties" : {
              "cis" : {
                "type" : "keyword"
              },
              "cve" : {
                "type" : "keyword"
              },
              "description" : {
                "type" : "keyword"
              },
              "firedtimes" : {
                "type" : "long"
              },
              "frequency" : {
                "type" : "long"
              },
              "groups" : {
                "type" : "keyword"
              },
              "id" : {
                "type" : "keyword"
              },
              "info" : {
                "type" : "keyword"
              },
              "level" : {
                "type" : "long"
              },
              "mail" : {
                "type" : "boolean"
              },
              "pci_dss" : {
                "type" : "keyword"
              }
            }
          },
          "source" : {
            "type" : "keyword"
          },
          "syscheck" : {
            "properties" : {
              "diff" : {
                "type" : "keyword"
              },
              "event" : {
                "type" : "keyword"
              },
              "gid_after" : {
                "type" : "keyword"
              },
              "gid_before" : {
                "type" : "keyword"
              },
              "gname_after" : {
                "type" : "keyword"
              },
              "gname_before" : {
                "type" : "keyword"
              },
              "inode_after" : {
                "type" : "keyword"
              },
              "inode_before" : {
                "type" : "keyword"
              },
              "md5_after" : {
                "type" : "keyword"
              },
              "md5_before" : {
                "type" : "keyword"
              },
              "mtime_after" : {
                "type" : "date",
                "format" : "dateOptionalTime"
              },
              "mtime_before" : {
                "type" : "date",
                "format" : "dateOptionalTime"
              },
              "path" : {
                "type" : "keyword"
              },
              "perm_after" : {
                "type" : "keyword"
              },
              "perm_before" : {
                "type" : "keyword"
              },
              "sha1_after" : {
                "type" : "keyword"
              },
              "sha1_before" : {
                "type" : "keyword"
              },
              "size_after" : {
                "type" : "long"
              },
              "size_before" : {
                "type" : "long"
              },
              "uid_after" : {
                "type" : "keyword"
              },
              "uid_before" : {
                "type" : "keyword"
              },
              "uname_after" : {
                "type" : "keyword"
              },
              "uname_before" : {
                "type" : "keyword"
              }
            }
          },
          "title" : {
            "type" : "keyword"
          },
          "type" : {
            "type" : "text"
          }
        }
      }
    }
  }
}
`

Here is the grep:
`curl elastic_ip -s | grep number`
    `"number" : "6.2.3",`

`cat /usr/share/kibana/plugins/wazuh/package.json | grep -i -E "version|revision"`
  `"version": "3.2.1",`
  `"revision": "0387",`
   `"version": "6.2.3"`

`curl elastic_ip/_cat/indices -s |grep kibana`
`green  open .kibanai6                       YPIGBHpfTYGqcdwbZu0Fsg 1 0      3 0   22.5kb   22.5kb`
`yellow open .kibana                         jMkRS9a9TuOVyejznBsIjg 5 1    265 1  237.6kb  237.6kb`

**Comment by jesusgn90** [comment]
Ok, the mapping seems to be ok but that `.kibanai6` index is weird, I've never seen it before. Have you created it for any purpose? If not the case, please try one more time removing the main indices, but this time do it as follow:

```
# systemctl stop kibana
# curl -XDELETE elastic_ip:9200/.kibana,.kibanai6,.wazuh,.wazuh-version
# systemctl restart kibana
```

Also it's good to know that your Wazuh app revision has the recently added feature of logs so before execute the above commands, please execute a `tailf` with multiple `[ENTER]` to clear the `tailf` output. Please, open a new CLI and execute the next command before execute the above commands.

```
# tailf /usr/share/kibana/plugins/wazuh-logs/wazuhapp.log
Press [ENTER] up to the screen is clear, then remove indices and restart Kibana on the first CLI tab
```

One more question, are you using X-Pack?

Best regards,
Jesús

**Comment by Strepsil** [comment]
Nah, we aint using X-pack in this test environment. 

Here is the output from tailf:

`{"date":"2018-04-19T11:08:46.735Z","level":"info","location":"initialize.js","message":"Initializing"}`

`{"date":"2018-04-19T11:08:47.460Z","level":"error","location":"monitoring.js checkKibanaStatus","message":"Waiting for Kibana and Elasticsearch servers to be ready..."}`

`{"date":"2018-04-19T11:08:47.944Z","level":"error","location":"monitoring.js checkKibanaStatus","message":"An error occurred"}`

`{"date":"2018-04-19T11:08:47.962Z","level":"info","location":"initialize.js checkKibanaStatus","message":"Didn't find .kibana index..."}`

`{"date":"2018-04-19T11:08:47.965Z","level":"info","location":"initialize.js checkKibanaStatus","message":"No need to create the .kibana template, already exists."}`

`{"date":"2018-04-19T11:08:48.045Z","level":"info","location":"initialize.js checkKibanaStatus","message":"Successfully created .kibana index."}`

`{"date":"2018-04-19T11:08:48.059Z","level":"error","location":"initialize.js init 6","message":"[index_not_found_exception] no such index, with { resource.type=\"index_expression\" & resource.id=\".wazuh-version\" & index_uuid=\"_na_\" & index=\".wazuh-version\" }"}`

`{"date":"2018-04-19T11:08:48.072Z","level":"info","location":"initialize.js createIndexPattern","message":"Creating index pattern: wazuh-alerts-3.x-*"}`

`{"date":"2018-04-19T11:08:48.080Z","level":"info","location":"initialize.js createIndexPattern","message":"Created index pattern: wazuh-alerts-3.x-*"}`

`{"date":"2018-04-19T11:08:48.082Z","level":"info","location":"initialize.js importObjects","message":"Importing objects (Searches, visualizations and dashboards) into Elasticsearch..."}`

`{"date":"2018-04-19T11:08:48.110Z","level":"info","location":"initialize.js importAppObjects","message":"Waiting for index pattern creation to complete..."}`

`{"date":"2018-04-19T11:08:48.172Z","level":"info","location":"initialize.js init","message":"Index .wazuh created."}`

`{"date":"2018-04-19T11:08:48.208Z","level":"info","location":"initialize.js saveConfiguration","message":"Wazuh configuration inserted"}`

`{"date":"2018-04-19T11:08:48.254Z","level":"info","location":"initialize.js importObjects","message":"Templates, mappings, index patterns, visualizations, searches and dashboards were successfully installed. App ready to be used."}`

`{"date":"2018-04-19T11:08:48.265Z","level":"info","location":"initialize.js importAppObjects","message":"Importing/Updating index pattern known fields..."}`

`{"date":"2018-04-19T11:08:48.276Z","level":"info","location":"initialize.js importAppObjects","message":"Importing/Updating Wazuh app visualizations..."}`

`{"date":"2018-04-19T11:08:48.378Z","level":"info","location":"initialize.js importAppObjects","message":"Wazuh app visualizations were successfully installed. App ready to be used."}`

`{"date":"2018-04-19T11:08:50.947Z","level":"error","location":"monitoring.js checkKibanaStatus","message":"Waiting for Kibana and Elasticsearch servers to be ready..."}`

`{"date":"2018-04-19T11:08:50.953Z","level":"info","location":"monitoring.js init","message":"Creating/Updating wazuh-agent template..."}`

`{"date":"2018-04-19T11:08:50.953Z","level":"info","location":"monitoring.js checkTemplate","message":"Updating wazuh-monitoring template..."}`

`{"date":"2018-04-19T11:08:50.994Z","level":"info","location":"monitoring.js init","message":"Creating today index..."}`

`{"date":"2018-04-19T11:08:51.000Z","level":"info","location":"monitoring.js init","message":"Checking if wazuh-monitoring pattern exists..."}`

`{"date":"2018-04-19T11:08:51.006Z","level":"error","location":"monitoring.js init","message":"Didn't find wazuh-monitoring pattern for Kibana v6.x. Proceeding to create it..."}`

`{"date":"2018-04-19T11:08:51.019Z","level":"info","location":"monitoring.js init","message":"No need to delete old wazuh-monitoring pattern."}`

`{"date":"2018-04-19T11:08:51.020Z","level":"info","location":"monitoring.js configureKibana","message":"Creating index pattern: wazuh-monitoring-3.x-*"}`

`{"date":"2018-04-19T11:08:51.030Z","level":"info","location":"monitoring.js configureKibana","message":"Created index pattern: wazuh-monitoring-3.x-*"}`

`{"date":"2018-04-19T11:08:51.032Z","level":"info","location":"monitoring.js importAppObjects","message":"Importing Wazuh app visualizations..."}`

`{"date":"2018-04-19T11:08:51.064Z","level":"info","location":"monitoring.js importAppObjects","message":"Wazuh app visualizations were successfully installed. App ready to be used."}`

`{"date":"2018-04-19T11:10:00.554Z","level":"error","location":"monitoring.js getConfig","message":"no credentials"}`

**Comment by jesusgn90** [comment]
Ok @Strepsil , so this time we can be sure there is only one `.kibana` index (`curl elastic_ip:9200/_cat/indices`)?

Are you coming from an upgrade process from Wazuh 2.x, Elastic 5.x, etc ?

It would be nice too if you paste the output of the next command (to check Elasticsearch itself):

```cat /var/log/elasticsearch/elasticsearch.log | grep -i -E "error|warn|critical"```

All are your Elastic components at the same version right?

Best regards,
Jesús

**Comment by Strepsil** [comment]
Yes, right now there is only 1 .kibana

Here is the Warning messages, please see that the .kibanai6-index is really old (timestamp is earlier today).

Here is the output from elasticsearch.log

`[2018-04-19T09:03:25,562][WARN ][o.e.c.a.s.ShardStateAction] [afrodite] [.kibanai6][0] received shard failed for shard id [[.kibanai6][0]], allocation id [SJDQWBfuQ62_UwH44cW5Fg], primary term [12], message [mark copy as stale]`

`[2018-04-19T14:36:56,745][WARN ][o.e.d.z.ElectMasterService] [afrodite] value for setting "discovery.zen.minimum_master_nodes" is too low. This can result in data loss! Please set it to at least a quorum of master-eligible nodes (current value: [-1], total number of master-eligible nodes used for publishing in this round: [2])`

**Comment by Strepsil** [comment]
Here is the earliest output from the file: 

`Apr 19 11:13:11 XXXXXXXXXXX kibana[7134]: {"type":"log","@timestamp":"2018-04-19T09:13:11Z","tags":["plugin","warning"],"pid":7134,"path":"/usr/share/kibana/plugins/wazuh-logs","message":"Skipping non-plugin directory at /usr/share/kibana/plugins/wazuh-logs"}`
`Apr 19 13:08:44 XXXXXXXXXXX kibana[8458]: {"type":"log","@timestamp":"2018-04-19T11:08:44Z","tags":["plugin","warning"],"pid":8458,"path":"/usr/share/kibana/plugins/wazuh-logs","message":"Skipping non-plugin directory at /usr/share/kibana/plugins/wazuh-logs"}`

All the other errors where from way before, and this is at least something that we are getting now after your help :) 

Our environment dosn't come from an upgrade process, we upgrade our ELK-stack from 6.1.1 to 6.2.3, and then we installed Wazuh. So we didn't do any upgrade with Wazuh, just a clean installation.

Here is a screenshot from the "Overview"-tab with the errors from the console:
![error5](https://user-images.githubusercontent.com/35831623/38994724-71fc9500-43e7-11e8-872e-2d49c6a6ec9c.PNG)

Thanks for the help Jesús btw, you are really doing a great job!!!!

**Comment by jesusgn90** [comment]
Thanks @Strepsil ! ,

the two logs saying wazuh-logs not a plugin directory are right, its only a warning and it means it's skipping the logs directory, it's ok.

Regarding to the console errors I only see 304 codes, they mean are content already downloaded, they are not harmful.

I need some more in deep from that developer tool from Chrome, look at 404 and/or 500 error codes. Also open the _Console_ tab to see if there is any error. Any time you change from tab on the developer tools you should refresh (F5) the page. Any red-line you see is welcome. Thanks.

Regards,
Jesús

**Comment by Strepsil** [comment]
Sorry but in the console windows there is nada.... only some risks regarding http and paswords blablabla..... And I cant find any 404 and/or 505.... My college just installed the same version of all the components in ELK and then installed the same Wazuh-version as me, same errors..... 

I downloaded the OVA-file and startated to compare the different .yml and I cant find anything that would cause this. I think I will maybe try building this up from the source instead of going with yum, what do you think?

**Comment by Strepsil** [comment]
I'm going with CentOS 7 and I'm not running SELinux in this setup. 

I will try setting up a new test rigg with the same version as I have on ELK when I get home (no proxy this time).

**Comment by jesusgn90** [comment]
Oh @Strepsil, that's pretty weird, my desired environment to develop is usually a CentOS 7 without SELinux, so it's like you environment. At this point, my suggestion is to try without the proxy, this way we can check if that's or not the key here... Let me know your results when you are at home.

Best regards,
Jesús

**Comment by Strepsil** [comment]
Yeah sure!

**Comment by Strepsil** [comment]
@jesusgn90 

Sorry for not posting anything last night, needed to rest my brain some.... I'm doing a clean installation now at work and I will follow your guide now with every step. That is included the ELK stack, I will post when I'm done.

**Comment by Strepsil** [comment]
Could it have something to do with the indexes that was still present in the other environment? So if I would like to install Wazuh into production I will have to remove all the indexes that I have today? : /

**Comment by jesusgn90** [comment]
Ok @Strepsil since your environment is now working, I think we can close this issue, but let us know first. Regarding to your other environment I suggest you to always follow our documentation step by step, otherwise things could go wrong. Elastic stack is complex and the order you make the things is important.

Regarding to your last question about your other environment I don't know the health of your indices and if they are corrupted or not. They could be wrong and won't work any more. Since we have done some checks and different ways to solve it without success I think they are fully broken. Sorry @Strepsil .

If you have any doubt with your new environment, or any other kind of problem we can help you.

Best,
Jesús

**Comment by Strepsil** [comment]
Okey, yeah I think we can close this now. But I just want to know if your recommendation for installing Wazuh is to just reinstall the OS and then follow the guide? 

Thanks a ton for your help!!!!!

**Comment by jesusgn90** [comment]
Not exactly what I meant but definetively you should be extremely careful whenever you deploy a full stack environment since there are critical parts where you can complicate the things. Sometimes it's easy to fix it but not always.

Any case I'm glad you finally have a fine environment and happy to help. We are here to help our community, as you said, I'm going to close this issue and don't hesitate to post any new problem you are facing.

King regards,
Jesús
