### ISSUE TITLE
[BUG] [HEALTH CHECK] `undefined is not an object (evaluating indexPatternToSelect.id)`

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#3862]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
An error is displayed in the index pattern check of the health check.
```
undefined is not an object (evaluating indexPatternToSelect.id)
```

We don't know how to replicate the problem but it seems there is a logic error in the source code when trying to access the `id` property of an `undefined` variable. See https://github.com/wazuh/wazuh-kibana-app/blob/4.3-7.10/public/components/health-check/services/check-index-pattern/check-index-pattern-object.service.ts#L73-L77

**Task**

- [ ] research about how to replicate the problem
- [ ] clarify the logic to apply in the section of source code to solve it

**Screenshots**
![image](https://user-images.githubusercontent.com/34042064/155711456-69d9d5f9-b784-4c63-8c4e-b24905cd8f6b.png)

**Comment by Desvelao** [comment]
## Research

There is a error when the next section was ported to the refactor of health check.
https://github.com/wazuh/wazuh-kibana-app/blob/1159f8158105ed08612bf25bece8bc5a94a28226/public/react-services/pattern-handler.js#L67-L72

**Comment by AlexRuiz7** [comment]
PR : https://github.com/wazuh/wazuh-kibana-app/pull/3868
