### ISSUE TITLE
'secure' flag for security_authentication cookie

### ISSUE THREAD

**Issue by root360-AndreasUlm** [wazuh/wazuh-kibana-app#3865]
**Describe the solution you'd like**
Since the implementation of https://github.com/wazuh/wazuh-kibana-app/issues/2790 which added the `secure` flag for the cookies `wz-user` and `wz-token` a new cookie was introduced called `security_authentication`.
This cookie seems to contain critical information and should be flagged as `secure`.

1) Can you add the `secure` flag for the cookie `security_authentication`, too?

**Describe alternatives you've considered**
Checked Wazuh documentation if there is a setting to enable it, but non found so far.

**Additional context**
This issue was found during our annual security audit.

**Comment by Desvelao** [comment]
Hi, @root360-AndreasUlm 

I guess you are using Open Distro for Elasticsearch, the `security_authentication` cookie comes from the `security` plugin for Kibana of Open Distro for Elasticsearch.

If you want that cookie to be flagged as `secure`:
1. Add to the Kibana configuration:
```yml
opendistro_security.cookie.secure: true
```

Take into account, that you need to enable the SSL for Kibana in its configuration and use or create a certificate if you don't have it, so the setting for the cookie takes effect.
```yml
server.ssl.enabled: true
server.ssl.certificate: <PATH_TO_KIBANA_CERTIFICATE>
server.ssl.key: <PATH_TO_KIBANA_KEY>
```

After modifying the Kibana configuration file, restart Kibana.
```sh
# depending on your service manager
systemctl restart kibana
# or
service kibana restart
```

With these configurations, you can get the cookie as `secure`.
![image](https://user-images.githubusercontent.com/34042064/156174745-e41f3bf7-a484-420a-aaa3-b168e5ad1768.png)

**Comment by root360-AndreasUlm** [comment]
@Desvelao Sorry, I forgot to mention our environment but you are right it's opendistro.
Thank you very much for the hint. We'll change out configuration accordingly.
