### ISSUE TITLE
Functional inventory

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#3870]
| Wazuh version | Component | Install type | Install method   | Platform   |
| ------------- | --------- | ------------ | ---------------- | ---------- |
| 5.0.0         | Dashboard | - | Packages/Sources | -  |

 - [ ] Relate each functionality with its panel/screen, the queries made
  to the ELK or the Wazuh API calls used to get the data, and a
  template of the events (elk documents) from which we can generate
  synthetic data to make the UI functionality behave as desired.

  - [ ]  Start asking the questions each panel answers.
 
  - [ ]  Gap analysis from what the documentation says to what we have in
  place

**Comment by Mayons** [comment]
The task to perform are:
Analyze the different sections of the Wazuh App to identify the different calls that the sections (Dashboards, tables, etc) does to the Wazuh API and the ELK service.
Sections:

-  Modules
- Management
- Security
- Settings
- Agents
- Tools

**Comment by Mayons** [comment]
Modules
Security information management :white_check_mark: 
Auditing and Policy Monitoring :white_check_mark: 
Threat detection and response :white_check_mark: 
Regulatory Compliance :white_check_mark:

**Comment by gdiazlo** [comment]
Closed first iteration. See Functional Inventory in Docs repository.
