### ISSUE TITLE
compatibility kibana 8.0.X

### ISSUE THREAD

**Issue by fhm20** [wazuh/wazuh-kibana-app#3873]
Hello,
I would like to know if wazuh 4.3.0rc4 or the wazuh-kibana-app plugin will be compatible with elasticssearch/kibana 8.0.X
Thanks

**Comment by mauceballos** [comment]
Hi fhm20

Thank you for using Wazuh!

Release 4.3 will come out with compatibility for the versions that have been tested and that support for 8.X will come out in later releases.

I hope this helps.  Regards.

**Comment by AlexRuiz7** [comment]
No, Wazuh 4.3.0 will support up to Kibana 7.17. Kibana 8.x will be supported on later releases.
