### ISSUE TITLE
run_as attribute is missing - Wazuh - Dashboard

### ISSUE THREAD

**Issue by Mayons** [wazuh/wazuh-kibana-app#3876]
| Wazuh |OSFE | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 1.2.0 | RC6|WZ - Dashboard|

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
RBAC functionality is not working because "run_as" attribute is missing from the "wazuh.yml" file on wazuh-dashboard app.

**Preconditions**
1. 

**Steps to reproduce**
1. Up the docker containers
2. Look for the wazuh.yml file

**Expected Result**
1. "run_ass" attribute should be declared

**Actual Result**
1. "run_ass" attribute is missing

**Screenshots**
![image.png](https://images.zenhubusercontent.com/61aa085f76e57e2cf22704e0/de24e418-1108-406f-b764-dcfda23218b4)

**Additional context**

**Comment by vcerenu** [comment]
Added, within the entrypoint, the option to add an environment variable `$RUN_AS`, which adds its value to the `run_as` option within the API configuration. Default value is `false`

**Comment by Mayons** [comment]
Test OK ! 
RBAC it's working on Wazuh Dashboard
