### ISSUE TITLE
Agent's vulnerability dashboard rework 

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#3883]
Because of some reworks made in Wazuh 4.3 release (see https://github.com/wazuh/wazuh/issues/12580 ) , and the nature of the current dashboard, we need to remove the current dashboard in favor of a new one, which will use the inventory data for its presentation.

Dashboard to remove:

![image](https://user-images.githubusercontent.com/2181918/157098357-c55a6911-6f66-46ec-b19f-a4892d963d3b.png)

We need to design indicators and widgets, following the style and approach used in the SCA module. The new dashboard should fit in the inventory tab, in a space similar to this screenshot:

![image](https://user-images.githubusercontent.com/2181918/157100581-aab596a6-16df-4ff0-b8ec-977c94793b64.png)

We need to:

- [ ] Analyze the inventory information we have available, plus the new API summary endpoint
- [ ] Identify the most relevant visualizations to be included in the dashboard using the reviewed information
- [ ] Implement the dashboard into the inventory tab

**Comment by Desvelao** [comment]
## Changes
- Removed the `Dashboard` tab for the `Vulnerabilities` module
- Added 3 new panels to the `Inventory` tab
  - `Severity`: visualization
  - `Details`: stats of severity and last full scan and last partial scan
  - `Summary`: visualization with a selector that displays the top result of the selected vulnerability property
  
## Screenshots
![inventory-dashboard](https://user-images.githubusercontent.com/34042064/159271666-423be9c6-325f-4c12-9984-aa1220b11a14.gif)

**Comment by atlantsecurity** [comment]
Removing the dashboard to show all vulnerabilities for all agents was... kinda... not wise. Are you planning to return it?

**Comment by grepcatman** [comment]
I too would really appreciate bringing a dashboard showing all vulnerabilities.  Building one seems non-trivial.

**Comment by AnhTuanNguyenn** [comment]
hope you bring it back ^^
