### ISSUE TITLE
Agent's vulnerability events table

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#3884]
Update the agent's vulnerability events table to include a row with the status of the vulnerability. The API reports the status of a vulnerability inside the object we already use, but only when the vulnerability is new. There are changes in the API to always include the status.

Also, the data vulnerability severity should always appear with a value instead of a dash.

A quick sketch looks like (notice the extra column status to the right of the screenshot):

![image](https://user-images.githubusercontent.com/2181918/157104997-aefd449d-2d97-43d5-b445-543b2a64513f.png)

**Comment by Desvelao** [comment]
## Result
![events-vulnerability-status](https://user-images.githubusercontent.com/34042064/159271712-471d0eb1-5cf0-4d07-9a6d-f28410e36e1a.gif)

**Comment by AlexRuiz7** [comment]
Done in https://github.com/wazuh/wazuh-kibana-app/pull/3893
