### ISSUE TITLE
Agent's vulnerability inventory detail

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#3890]
Related to #3883  and #3884 we also need to include all the fields listed in https://github.com/wazuh/wazuh/issues/12591 in the details panel in the vulnerabilities inventory page.

![image](https://user-images.githubusercontent.com/2181918/157626494-ba3aaeac-01a1-4840-841b-caaaeb2472a1.png)

**Comment by Desvelao** [comment]
## Result
![details](https://user-images.githubusercontent.com/34042064/159271689-dc413a68-366a-4124-8df0-4cc54bfbd39e.gif)
