### ISSUE TITLE
Customizable email and website information in reports

### ISSUE THREAD

**Issue by dariommr** [wazuh/wazuh-kibana-app#3892]
Hello Team,

Having in mind the user can change the logo in the report for its own logo, please consider allowing the modification of the website and email placed at the top right in the report's header. The information we would like to customize is:
- `info@wazuh.com`
- `https://wazuh.com/`

Thank you in advance!

**Comment by AlexRuiz7** [comment]
## Data requirements

- Contact email
- Webpage

That information needs to be provided to the app, and stored. 
Currently, these values are constants of the app. To make them customizable, we'll need to expose these values in the settings section, where the user will be able to change them.

![image](https://user-images.githubusercontent.com/15186973/187663664-670f73cc-c56a-467e-a9e9-0f7c7bb62676.png)

**Comment by AlexRuiz7** [comment]
Will be added in #4426
