### ISSUE TITLE
Wazuh compatibility with Elastic 7.17.1

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-kibana-app#3895]
Hello team,

Flaws were recently discovered in Elastic 7.17.0 version making it vulnerable. As per my understanding, our latest test version was 7.17.0 according to https://github.com/wazuh/wazuh-kibana-app/issues/3835

We may consider testing 7.17.1 for the release as recommended: https://discuss.elastic.co/t/elastic-stack-7-17-1-security-update/298447

Regards,

Miguel Casares

**Comment by haodketernal** [comment]
how about this release

**Comment by AlexRuiz7** [comment]
Done in #4054.
