### ISSUE TITLE
Agent selector on inventory does not update the data

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#3899]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 7.x     | -| - |

| Browser |
| ------- |
| All |

**Description**
In the Vulnerability inventory tab,  if we change the agent displayed in the top-right widget, the inventory does not get updated. 

**Preconditions**
1.  

**Steps to reproduce**
1. Navigate to Vulnerabilities inventory
2. Click on Agent selector and select other agent
3. The inventory does not get updated

**Expected Result**
1.  The inventory gets updated

**Actual Result**
1.  The inventory does not get updated

**Screenshots**

https://user-images.githubusercontent.com/2181918/158572674-26a62ba9-e66d-4fc9-8360-5091c7420146.mp4

**Additional context**

This issue might be present in other inventory modules. We need to check whether this issue is affecting them.

**Comment by Desvelao** [comment]
## Changes
- Added `endpoint` property as dependency and parameter to redo the request. The `endpoint` property contains the agent ID.

**Comment by gdiazlo** [comment]
Closed by https://github.com/wazuh/wazuh-kibana-app/pull/3901
