### ISSUE TITLE
Any chance for wazuh-app 2.1.1 for ES 5.5.0 ?

### ISSUE THREAD

**Issue by rossengeorgiev** [wazuh/wazuh-kibana-app#39]
Or if it's not possible, point me to instruction on how to build it myself.

**Comment by malbarral** [comment]
Hi @rossengeorgiev, 

The Wazuh app 2.1.0 supports Wazuh 2.1.1. I have generated for you a package for Kibana 5.5.0, but it has not been tested. It is based in the package https://packages.wazuh.com/wazuhapp/wazuhapp-2.1.0_5.5.1.zip. You can download it here:

https://packages.wazuh.com/wazuh-dev/wazuhapp-2.1.0_5.5.0.zip

We will not develop for wazuh-app 2.1.1 for Elastic 5.5.0 anymore, sorry for the inconvenience.

Hope it works,
Manuel Albarral

**Comment by rossengeorgiev** [comment]
Getting access denied on that URL. Is it possible to  build the packages myself?

**Comment by malbarral** [comment]
Hello @rossengeorgiev,

Here you can download the package: http://packages.wazuh.com.s3.amazonaws.com/wazuh-dev/wazuhapp-2.1.0_5.5.0.zip

It will be available til the server refreshs.

Best regards,
Manuel Albarral

**Comment by rossengeorgiev** [comment]
@malbarral I end up putting https://packages.wazuh.com/wazuhapp/wazuhapp-2.1.0_5.5.1.zip and ES 5.5.0. Seems to work. Overview wouldn't load, but after adding the `wazuh-monitoring-*` index pattern it started working.
