### ISSUE TITLE
Implement CSV export from lists

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#390]
Implement a new `Export as CSV` button for all the lists found on the Wazuh app.

**Comment by jesusgn90** [comment]
__Update:__

A new server route has been implemented for this purpose on https://github.com/wazuh/wazuh-kibana-app/tree/3.2-csv-export

You could test it as follow:

```
curl -XPOST localhost:5601/api/wazuh-api/csv -H'Content-Type: application/json' -H'kbn-version: 6.2.4' -d'{"path":"<api_endpoint>","id":"<api_entry_id>"}'
```

Example: 

```
curl -XPOST localhost:5601/api/wazuh-api/csv -H'Content-Type: application/json' -H'kbn-version: 6.2.4' -d'{"path":"/agents","id":"1524561570158"}'
```
It should returns a CSV response or an error response(JSON).

Regards,
Jesús

**Comment by jesusgn90** [comment]
__Update:__

- Added filters. This parameter is optional and could be malformed (server-side sanitized)
- Implemented on ruleset and logs tabs. Working as expected using filters. Next step is to apply it on groups, groups/content, groups/agents and agents using filters as well.

Regards,
Jesús

**Comment by jesusgn90** [comment]
Done here https://github.com/wazuh/wazuh-kibana-app/pull/431
