### ISSUE TITLE
Backslash breaks the exported JSON result

### ISSUE THREAD

**Issue by elwali10** [wazuh/wazuh-kibana-app#3902]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.2.5   | 7.10.2     | 4205-1 | ODFE|

| Browser |
| ------- |
| Chrome, Firefox|

**Description**
When the data returned by the API contains a backslash `\` results in a non-valid exported JSON.

**Steps to reproduce**
1. Navigate to '"API Console'
2. Retrieve results for SCA win policy `GET /sca/004/checks/sca_win_audit?result=failed`
3. Export it: 
![image](https://user-images.githubusercontent.com/16334770/155138306-0be64a98-371a-4a9e-9118-edf7a99dc007.png)

**Expected Result**
1. A valid JSON : 
![image](https://user-images.githubusercontent.com/16334770/155138369-e689b9eb-18d9-4324-a740-0b9e807ac761.png)

**Actual Result**
1. Invalid JSON : 
![image](https://user-images.githubusercontent.com/16334770/155138473-73e5aedb-1eb7-4c96-89c7-80f52bb78161.png)

**Additional context**
The issue adds a complexity layer to manipulate the results.

**Comment by yenienserrano** [comment]
**Description:**

Removed backslash replacement to display the same answer on the page

**PR:**

Export a valid json [#3909](https://github.com/wazuh/wazuh-kibana-app/pull/3909)

**Test:**

1. Navigate to '"API Console'
2. Retrieve results for SCA win policy `GET /sca/004/checks/sca_win_audit?result=failed`
3. Export it
4. Copy the exported into a json validator


**Screenshot:**
![image](https://user-images.githubusercontent.com/63758389/159505798-dae5aaa3-7973-4064-8471-b09632b38217.png)
![image](https://user-images.githubusercontent.com/63758389/159505895-c1f645f5-951f-4213-8282-5720647c2675.png)
