### ISSUE TITLE
Several "The index pattern was refreshed successfully" panel appears after restarting

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-kibana-app#3923]
Wazuh | Opensearch | Rev | Security
-- | -- | -- | --
4.3.0 | 1.2.0 | 4301-1 | Wazuh Indexer

| Browser |
| ------- |
|Firefox|

**Description**

During [Windows Event](https://github.com/wazuh/wazuh/issues/12896#issuecomment-1081885456) manual testing, using OVA installation, it has been detected the following behavior:

![panels](https://user-images.githubusercontent.com/11089305/160623027-0e32ee43-5f77-424f-9783-ea790fffa652.png)

Multiple _The index pattern was refreshed successfully panels_ appear making navigability difficult.

### Steps to reproduce
- Add a new rule files -> Management > Rules > Add new rule files. 
For example:
```
<group name="windows,sysmon,">

<rule id="115001" level="10">
  <if_group>windows</if_group>
  <field name="win.eventdata.ruleName" type="pcre2" >technique_id=T1053,technique_name=Scheduled Task</field>
  <description>A Newly Scheduled Task has been Detected on $(win.system.computer)</description>
  <mitre>
    <id>T1053</id>
  </mitre>
</rule>

<rule id="115002" level="10">
  <if_group>windows</if_group>
  <field name="win.eventdata.ruleName" type="pcre2" >technique_id=T1073,technique_name=DLL Side-Loading</field>
  <description>DLL Side-Loading Detected on $(win.system.computer)</description>
  <mitre>
    <id>T1073</id>
    <id>T1574.002</id>
  </mitre>
</rule>

<rule id="115003" level="10">
  <if_group>windows</if_group>
  <field name="win.eventdata.ruleName" type="pcre2" >technique_id=T1218.010,technique_name=Regsvr32</field>
  <description>Signed Binary Proxy Execution using Regsvr32 Detected on $(win.system.computer)</description>
  <mitre>
    <id>T1218</id>
    <id>T1117</id>
  </mitre>
</rule>

<rule id="115004" level="10">
  <if_group>windows</if_group>
  <field name="win.eventdata.ruleName" type="pcre2" >technique_id=T1518.001,technique_name=Security Software Discovery</field>
  <description>Security Software Discovery Attempt has been Detected on $(win.system.computer)</description>
  <mitre>
    <id>T1518</id>
  </mitre>
</rule>

<rule id="115005" level="10">
  <if_group>windows</if_group>
  <field name="win.eventdata.ruleName" type="pcre2" >technique_id=T1548.002,technique_name=Bypass User Access Control</field>
  <description>Privilege Escalation Through Bypass of UAC has been Detected on $(win.system.computer)</description>
  <mitre>
    <id>T1548.002</id>
    <id>T1088</id>
  </mitre>
</rule>

</group>
```
- Save and restart using the interface
- Go to Modules > Security Events > Events
- Multiple panels of  _The index pattern was refreshed successfully panels_ appears

**Comment by Desvelao** [comment]
The toast message is displayed by each field which is unknown. These fields are the highlighted in the screenshot:
![image (1)](https://user-images.githubusercontent.com/34042064/160645578-02d349af-ceee-4dc4-a16a-19820b71da3f.png)

It would be desirable the toast were displayed only one time.

**Comment by Desvelao** [comment]
## Research

I tried to replicate the problem and I did not experience it, the toast only was displayed one time when I opened the row of an alert that had multiple unknown fields. I use the OVA for `4.3.0`.

The [method to refresh the index pattern fields has a flag](https://github.com/wazuh/wazuh-kibana-app/blob/4.3-7.10/public/components/common/modules/events.tsx#L204-L221) that would be avoiding that it was displayed more than one time. My supposition is that could have some race condition that executes the function to refresh the known fields and pass the condition with the flag causing the index pattern fields to be refreshed and the toast message displayed multiple times.

**Comment by Desvelao** [comment]
# Remediation
We could not replicate the problem, but we think is caused to a race condition. We modified the source code to try to avoid it on the pull request  [#3937](https://github.com/wazuh/wazuh-kibana-app/pull/3937).
