### ISSUE TITLE
MITRE techniques are not correctly linked

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-kibana-app#3928]
Wazuh | Opensearch | Rev | Security
-- | -- | -- | --
4.3.0 | 1.2.0 | 4301-1 | Wazuh Indexer

| Browser |
| ------- |
|Firefox|

**Description**

During [Windows Event](https://github.com/wazuh/wazuh/issues/12896#issuecomment-1082106195) manual testing, using OVA installation, it has been detected the following behavior:

MITRE techniques changed in https://github.com/wazuh/wazuh/issues/11168, are not correctly linked:

![image](https://user-images.githubusercontent.com/80041853/160656382-ca47ee55-9a3f-46bd-b492-2b1a835d0d77.png)
![image](https://user-images.githubusercontent.com/80041853/160656850-11189643-f64d-47b1-89a5-85ca382d17f5.png)

The techniques' ID should be `T1021.001` and `T1078.002`

**Comment by gdiazlo** [comment]
Closed by https://github.com/wazuh/wazuh-kibana-app/pull/3944.
