### ISSUE TITLE
Vulnerabilities inventory details flyout date-picker

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-kibana-app#3932]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 7.10     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
Vulnerabilities inventory details flyout is not being affected by its date-time selector. Instead, seems to be filtering the date by the Events view date-time selector.

**Preconditions**
1. Have wazuh-agents with vulnerabilities

**Steps to reproduce**
1. Navigate to _Vulnerabilities / Inventory_
2. Click on table row to open _Details flyout_
3. Use the date-picker to change the results

**Expected Result**
1. Details flyout filters its alerts by the date-time selector

**Actual Result**
1. it doesn't. Seems to be affected by Events tab date-picker

**Screenshots**

![Peek 2022-03-31 12-03](https://user-images.githubusercontent.com/9343732/161031130-7d19d6e9-be8d-42c2-8cd3-e69aa59d02f9.gif)

**Comment by Desvelao** [comment]
Solved in: https://github.com/wazuh/wazuh-kibana-app/pull/3947
