### ISSUE TITLE
Github integration panel information overflows panel limits

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-kibana-app#3938]
| Wazuh indexer | Rev  | Security |
| ------------ | ---- | -------- |
| 4.3.0 | 4301-1| Indexer |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

As you can see here, in the panel of the Github module, the information overflows the limit:

![image](https://user-images.githubusercontent.com/23264276/161261573-7586d7be-39e1-478e-aaf2-a1701b477c16.png)

**Comment by Desvelao** [comment]
PR: https://github.com/wazuh/wazuh-kibana-app/pull/3945
