### ISSUE TITLE
Error log on a successful installation

### ISSUE THREAD

**Issue by juliancnn** [wazuh/wazuh-kibana-app#3941]
After doing a clean installation of the `wazuh-dashboard`, the following error can be seen in the log `/usr/share/wazuh-dashboard/data/wazuh/logs/wazuhapp.log`:

```
ERROR  Could not check if the index .wazuh exists due to no permissions for create, delete or check
```

**To Reproduce**
1. Install the `wazuh-dashboard`
2. Start the service
3. Check the logs in `/usr/share/wazuh-dashboard/data/wazuh/logs/wazuhapp.log`

### Complete log:
```
Mar 30, 2022 @ 18:34:58  INFO  Wazuh dashboard index: .kibana
Mar 30, 2022 @ 18:34:58  INFO  App revision: 4301-1
Mar 30, 2022 @ 18:34:58  INFO  Total RAM: 3929MB
Mar 30, 2022 @ 18:34:58  ERROR  Could not check if the index .wazuh exists due to no permissions for create, delete or check
Mar 30, 2022 @ 18:34:58  ERROR  connect ECONNREFUSED 127.0.0.1:55000
Mar 30, 2022 @ 18:37:03  INFO  Wazuh dashboard index: .kibana
Mar 30, 2022 @ 18:37:03  INFO  App revision: 4301-1
Mar 30, 2022 @ 18:37:03  INFO  Total RAM: 3929MB
Mar 30, 2022 @ 18:37:03  ERROR  Could not check if the index .wazuh exists due to no permissions for create, delete or check
Mar 30, 2022 @ 18:40:00  ERROR  resource_already_exists_exception
Apr 1, 2022 @ 09:25:04  INFO  Wazuh dashboard index: .kibana
Apr 1, 2022 @ 09:25:04  INFO  App revision: 4301-1
Apr 1, 2022 @ 09:25:04  INFO  Total RAM: 3929MB
Apr 1, 2022 @ 09:25:04  ERROR  Could not check if the index .wazuh exists due to no permissions for create, delete or check
```

**Expected behavior**

A successful installation should not show error logs.

**Screenshots**

![image](https://user-images.githubusercontent.com/1891958/161281063-93bc941d-6bd4-4d97-b360-6f98ddf26030.png)

**Comment by gdiazlo** [comment]
The index .wazuh was deprecated . We will remove the code related to this check, and the error should disappear.

**Comment by Desvelao** [comment]
We will remove the migration tasks related to the `.wazuh` and `.wazuh-version` indices that are deprecated.

Pull request: https://github.com/wazuh/wazuh-kibana-app/pull/4098
