### ISSUE TITLE
Add icon "Google group"

### ISSUE THREAD

**Issue by Iglesiasdai** [wazuh/wazuh-kibana-app#3943]
we need to replace the mail icon with the Google group icon

![image](https://user-images.githubusercontent.com/77293605/161540340-d737dae0-0cd4-433b-9ba7-7adc09473ba6.png)

**Comment by Iglesiasdai** [comment]
![googlegroup-01](https://user-images.githubusercontent.com/77293605/161540868-9a8b375a-4ee2-48e4-8cd2-95a879b3520a.svg)

**Comment by Desvelao** [comment]
# Changes
Replaced the icons in:
- `Settings/About` section
- plugin platform help

https://github.com/wazuh/wazuh-kibana-app/pull/3949#issue-1193236382
