### ISSUE TITLE
Alert selected from the "Dashboard" section don't show any details.

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-kibana-app#3948]
# Description 

Working on Issue [#12902](https://github.com/wazuh/wazuh/issues/12902) , we detected that when we click on a alert from the Dashboard section it doesn't show any details or redirect to these events. 
Is it correct?

## Details: 

|Wazuh version |Install type| OS type |
|---|---|---|
| 4.3 | Manager | [AMI - Wazuh_v4.3.0](https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#ImageDetails:imageId=ami-0e062a80bd73a63b6)|

|Wazuh version |Install type |Platform|
|---|---|---|
| 4.3| Agent| Amazon Linux (aws) |

### Local_internal_options

> wazuh_modules.debug=2
> monitord.rotate_log=0

------------

## Steps to reproduce

1. In the manager, edit /`var/ossec/etc/ossec.conf` vulnerability detection section with [Ossec.conf - VD - Manager.txt](https://github.com/wazuh/wazuh/files/8381886/Ossec.conf.-.VD.-.Manager.txt).
2. Registered and connected agent with the manager.
3. Restart Agent and Manager.
4. We detected a vulnerability alert with a package `perl` on `/var/ossec/logs/alerts/alerts.log` on Manager. 
5. Login in the Wazuh UI. 
6. Go to Vulnerabilities Section
7. Go to Dashboard Section.
8. Click on an alert from the "Most common rules" section.
    ![imagen](https://user-images.githubusercontent.com/3978434/161747068-f3c454dd-4d87-4e30-a7df-43e70d76019d.png)

 ## Results

  -  `Current Results:` Nothing happens. It doesn't show details of the vulnerability. It doesn't redirect to another page with details of it. 
  -  `Expected Results:` The event selected shows a pop-up with details.

**Comment by Desvelao** [comment]
Hi @damarisg, the highlighted section is a row of a visualization table generated with the plugin platform core. It is expected that it doesn't have the mentioned functionalities such as opening/redirecting to another section to show more information. Instead, the table cells can have other functionality such as adding some filter to the search.

By another hand, the `Dashboard` tab for the `Vulnerabilities` module will be removed in `4.3.0`.

**Comment by asteriscos** [comment]
This issue will be closed due to the _Vulnerabilities Inventory Rework_ PR #3893 which makes Vulnerabilities Dashboard obsolete.
