### ISSUE TITLE
Allow sorting by `Agents` column in the table of `Management/Groups`

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#3950]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
The users should be able to sort by the `Agents` column in the table of `Management/Groups`.

Blocked by: https://github.com/wazuh/wazuh/issues/12432

**Comment by yenienserrano** [comment]
solve:

- #4323
