### ISSUE TITLE
4.3.0 Considerations for Office365 panel

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-kibana-app#3951]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3.0   |      | 4301-1 | |

| Browser |
| ------- |
| all|

Hello team,

I'm opening this case because we should review the following in the Office365 panel:

![image](https://user-images.githubusercontent.com/23264276/161956107-bea3a6d8-923f-4e5d-bfbe-73d52a661c69.png)

In this panel, we state this module configuration is on the Wazuh manager, but in one of the configuration definitions: `Collect event generated since Wazuh agent was started`, we mention this is working on the agent. This definition does not seem to match the documentation: https://documentation-dev.wazuh.com/4.3-rc/user-manual/reference/ossec-conf/office365-module.html#only-future-events

It is not matching this definition either: 
![image](https://user-images.githubusercontent.com/23264276/161957022-47e81b0d-6ffd-4beb-944d-525c97395b31.png)

**Comment by Desvelao** [comment]
Fixed in https://github.com/wazuh/wazuh-kibana-app/pull/3952.
