### ISSUE TITLE
Ruleset search bars don't sanitize input

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-kibana-app#3968]
In the Management > {Rules, Decoders, CDB lists} screens if special characters such as `&` or `;` (ampersand or semicolon) are used in the search bar an error occurs.
![image](https://user-images.githubusercontent.com/36071202/162951443-9bfbca42-dece-4c5b-bb9f-75007fdf0115.png)

The full error dialog shows:
![image](https://user-images.githubusercontent.com/36071202/162952691-46c9cd64-6853-4ce0-8d58-953950b0d90d.png)
```
_callee3/_callee3$/<@https://WAZUH-DASHBOARD-ADDRESS/1/bundles/plugin/wazuh/wazuh.chunk.7.js:5:1885772
```
It's worth doing a thorough investigation of this as this may be indicative of a potential code injection possibility. 

On 4.2.x the input is accepted although it won't find rules with a matching description. 
![image](https://user-images.githubusercontent.com/36071202/162952443-b16c2ecf-194e-4629-bb28-1116ffeea150.png)

Finally the error message `Error when get the items of rules` is grammatically incorrect and confusing.

**Comment by havidarou** [comment]
Related to https://github.com/wazuh/wazuh-kibana-app/issues/4312

**Comment by Desvelao** [comment]
I was researching a problem with a particular API search in the Wazuh plugin. When the value of search query parameter contains `&`, the API replies that is not a valid format.

I was testing to do the desired request, without expected results. I don't know if this request is allowed by the API. I asked to the colleagues for more information. https://wazuh-team.slack.com/archives/GNW3K8S6N/p1675758334586629

Some tests with cURL:
> Manager used: `4.4.0` built from sources `v4.4.0-beta1`

```sh
wz_api_token=$(curl -u wazuh:wazuh -s -k -X POST "https://localhost:55000/security/user/authenticate?raw=true")
curl -k -H "Authorization: Bearer ${wz_api_token}" https://localhost:55000/rules -G --data-urlencode "search=att&ck"
{"title": "Bad Request", "detail": "'att&ck' is not a 'search'. Failed validating 'format' in schema: {'format': 'search', 'type': 'string'}. On instance: 'att&ck'"}
curl -k -H "Authorization: Bearer ${wz_api_token}" https://localhost:55000/rules -G --data-urlencode "search=att%26ck"
{"title": "Bad Request", "detail": "'att&ck' is not a 'search'. Failed validating 'format' in schema: {'format': 'search', 'type': 'string'}. On instance: 'att&ck'"}
```

API logs:
```
2023/02/07 08:20:02 INFO: wazuh 172.18.0.1 "GET /rules" with parameters {"search": "att&ck"} and body {} done in 0.075s: 400
2023/02/07 08:20:45 INFO: wazuh 172.18.0.1 "GET /rules" with parameters {"search": "att%26ck"} and body {} done in 0.018s: 400
```

I attach some screenshots when using the Wazuh plugin.

![Image](https://user-images.githubusercontent.com/34042064/217193330-035d9989-60e6-4b27-ae5a-b14e9389604f.png)
![Image](https://user-images.githubusercontent.com/34042064/217193385-05ac616c-9f84-4dca-a024-a68d2ce847bc.png)

API logs:
```
2023/02/07 08:24:16 INFO: wazuh-wui 172.18.0.3 "GET /rules" with parameters {"search": "att&ck", "offset": "0", "limit": "10", "sort": "+id"} and body {} done in 0.018s: 400
2023/02/07 08:24:59 INFO: wazuh-wui 172.18.0.3 "GET /rules" with parameters {"search": "att%26ck", "offset": "0", "limit": "10", "sort": "+id"} and body {} done in 0.017s: 400
Issue: https://github.com/wazuh/wazuh-kibana-app/issues/3968
```

**Comment by Desvelao** [comment]
According to the @vicferpoy , the `search` query parameter has a regex restriction.

![image](https://user-images.githubusercontent.com/34042064/217207034-a68384ad-afb3-4aed-aef9-42aa7d5a2bc1.png)
![image](https://user-images.githubusercontent.com/34042064/217207208-ffdaf6bf-ba3f-4389-a44f-7e354140b4e5.png)

The `search` query parameter doesn't support any characters. I don't know the reason for this, according to @davidjiglesias this could be related to SQL injection or any other sort of thing.

I asked @gdiazlo what is the action item taking into account the shared information.

**Comment by Desvelao** [comment]
According to @davidjiglesias , we could the `q` query parameter instead.

Another issue suggering this approach: https://github.com/wazuh/support/issues/171

**Comment by Desvelao** [comment]
We move this issue to 4.5.0 because it needs some changes in the search bar and there is an epic issue https://github.com/wazuh/wazuh-kibana-app/issues/4312 to redone it.

**Comment by gdiazlo** [comment]
Closing this as the development is being done in https://github.com/wazuh/wazuh-kibana-app/issues/4312
