### ISSUE TITLE
wazuh-modulesd high memory usage

### ISSUE THREAD

**Issue by spartantri** [wazuh/wazuh-kibana-app#398]
Hi,

I created an ossec alert to watch for proceses using over 3% RAM except for logstash (over 10%) and elasticsearch (over 30%). The alarm is triggering from time to time by `wazuh-modulesd`, what is its purpose and is there a way to limit the maximum memory it can use?

The alarm triggers every 2 minutes once a process exceeds the 3% mark and in this case it went from 3.6% to 48% in around 1 hour increasing gradually then the alarm went off, apparently this have the side effect of putting the wazuh agents in `disconnected` state which come back after an ossec restart in the manager (`/var/ossec/bin/ossec-control restart`).

My alarm output:
```
ossec: output: 'Memory Hungry Processes':
%Mem	%CPU	vsize	PID	CMD
48.0	2.8	7881720	18534	/var/ossec/bin/wazuh-modulesd
```

My local ossec rule:
```
<group name="ossec,">
  <rule id="536" level="8">
    <if_sid>530</if_sid>
    <match>ossec: output: 'Memory Hungry Processes</match>
    <check_diff />
    <description>Running proccesses that use over 3% of system memory.</description>
    <group>starvation,</group>
  </rule>
</group>
```
My ossec.conf localfile:
  ```
<localfile>
    <log_format>full_command</log_format>
    <command>echo -e "%Mem\t%CPU\tvsize\tPID\tCMD";ps -eo pmem,pcpu,vsize,pid,cmd |egrep -v "^ [012]." | sort -k 1 -nr | egrep "(ossec|aws|logstash|elasticsearch)" |sed -re 's,^( ?\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(.*),\1\t\2\t\3\t\4\t\5,' |egrep -v "^3.+elasticsearch" |egrep -v "^ [0-9].+logstash"</command>
    <alias>Memory Hungry Processes</alias>
    <frequency>120</frequency>
  </localfile>
```

While I got this fixed is there any API call to get the status of the agents directly? I would like to avoid writing a script to query kibana for those alarms and restart the server process if the agents disconnect.

Alert for memory usage:
![wazuh](https://user-images.githubusercontent.com/12847733/39133632-eeb6748c-4714-11e8-92fa-7cd22491bb59.PNG)

Alert vs Monitoring:
![wazuh2](https://user-images.githubusercontent.com/12847733/39134201-552b7982-4716-11e8-9316-7d072778b14e.PNG)

Thanks a lot in advance for the support!
Cheers!

**Comment by jesusgn90** [comment]
Hello @spartantri 

`modulesd` is the daemon related to the `wodles` processes defined on your `ossec.conf`. A `wodle` is a Wazuh module, you could read about them here https://documentation.wazuh.com/current/user-manual/reference/daemons/wazuh-modulesd.html

Some Wazuh modules could have a memory peak at some step of their execution such `vulnerability-detector` or `OpenSCAP`. They load a considerable amount of data in order to work properly but they free the memory once done. The team is currently working on some known memory peaks that could be optimized.

Could you please check all entries on your `ossec.conf` matching the next format:

```xml
  <wodle name="...">
    ...
  </wodle>
```

```
# cat /var/ossec/etc/ossec.conf
```

Regards,
Jesús

**Comment by JuanjiJG** [comment]
Hello again @spartantri,

It's been more than a month since the last response to this issue. I'll proceed to close it. Don't hesitate to open a new one if you have questions or need help with Wazuh.

Regards,
Juanjo

**Comment by spartantri** [comment]
Thanks Juanjo, is there any plan to limit the maximum amount of memory the process can use? or maybe at least have a way to schedule it to run during weekends or between 3-4AM for example.

Cheers!

**Comment by JuanjiJG** [comment]
Hello @spartantri, and sorry for the late response.

I don't have information about that. If you're interested, you can open an issue on [this repository](https://github.com/wazuh/wazuh/issues), so the Wazuh core team can give you more details of future planning for `wazuh-modulesd`.

Regards,
Juanjo

**Comment by nikhilsingh42** [comment]
Do Wazuh have any default  rule for cpu and ram  utilization check?

**Comment by spartantri** [comment]
You can close this, it's been long since I don't see this alarm, the latest versions are not showing this issue anymore
