### ISSUE TITLE
Validate the information to add a new Agent

### ISSUE THREAD

**Issue by mauceballos** [wazuh/wazuh-kibana-app#3996]
- > Path:   **Agent Page**
     
- > Section:  **Agent Creation**

- > Feature:  ****

- > Scenario: **Validate the information to add a new Agent**

- > Test Case: 
    
    Given the browser is in Agents of the Wazuh menu
    When the user selects a Deploy new agent
    Then the browser navigates the new deploy agent page
    And a box with four steps to the different settings is displayed
    And a first step ""1-title"" is displayed and the following ""options"" 
    
    | 1-title |
    |-------------------------|
    |  Choose the Operating system |
    
    | Options |
    |-------------------------|
    | Red Hat / CentOS |
    | Debian / Ubuntu | 
    | Windows | 
    | MacOS |
    
    And a second step ""2-title"" with the ""2-description"" are displayed and the following ""2-information"" by default
    
    | 2-title |  2-description | 2-information|
    |-------------------------|-------------------------|-------------------------|
    |Wazuh server address | You can predefine the Wazuh server address with the enrollment.dns Wazuh app setting. | 172.19.0.4   |
    
    And a third step ""3-title"" with the ""3-description"" are displayed and the following drop-down with Select group by default ""3-information""
    
    |        3-title             |         3-description              | 3-information  |
    |-------------------------|-------------------------|-------------------------|
    |Assign the agent to a group | Select one or more existing groups | Select group   |
    
    And a fourth step ""4-title"" is displayed
    
    |     4-title                |
    |-------------------------|
    | Install and enroll the agent |
    
    And a "message"" by default is displayed
    
    |            message                |
    |-------------------------|
    |Please select the Operating system.|
    
    And an X button in the top right is displayed

**Comment by Mayons95** [comment]
Move to Done, because PR is merged
