### ISSUE TITLE
Validate that a filter added on Agent/Module/Event it's displayed on any Agent/Module

### ISSUE THREAD

**Issue by mauceballos** [wazuh/wazuh-kibana-app#4012]
- > Path:   **Agent/Modules**
     
- > Section:  **Agent/Modules**

- > Feature:  **Filters**

- > Scenario: **Validate that a filter added on Agent/Module/Event it's displayed on any Agent/Module**

- > Test Case:

      Given the user is on Agent/Event
      When the user add a new filter
      And the user make filter pin
      Then the filter label is displayed
      And the user navigate to any agent/module 
      And the filter label is displayed.
    
    |Module|
    |-------|
    |Security Events|
    |Integrity Monitoring|
    |Vulnerabilities|
    |MITRE ATT&CK|
    |Policy Monitoring|
    |System Auditing|
    |Security configuration assessment|
    |PCI DSS|
   |GDPR |
    |HIPAA|
    |NIST 800-53|
    |TSC|

**Comment by Mayons** [comment]
Test Case automated.
Changes are merged on Feature/frontend branch
