### ISSUE TITLE
Validate that the filter is not displayed on Agents module.

### ISSUE THREAD

**Issue by mauceballos** [wazuh/wazuh-kibana-app#4016]
- > Path:   **Agent/Modules**
     
- > Section:  **Agent/Modules**

- > Feature:  **Filters**

- > Scenario: **Filter - Agent/Module - Unpinned**

- > Test Case:

@Scenario: Validate that the filter is not displayed on Agents module.

      Given the user is in a particular module
      And the user have added a filter
      When the user navigate to agent/module
      Then the filter it's no displayed
      
      |Module|
      |-------|
      |Security Events|
      |Integrity Monitoring|
      |Vulnerabilities|
      |MITRE ATT&CK|
      |Policy Monitoring|
      |System Auditing|
      |Security configuration assessment|
      |PCI DSS|
      |GDPR|
      |HIPAA|
      |NIST 800-53|
      |TSC|

**Comment by gdiazlo** [comment]
We will revisit this at a later date, as recent changes on this component will affect all the related tests.
