### ISSUE TITLE
Validate that a filter added on Agent/Module/Dashboard it's displayed on Agent/Module/Event

### ISSUE THREAD

**Issue by mauceballos** [wazuh/wazuh-kibana-app#4017]
- > Path:   **Agent/Modules**
     
- > Section:  **Agent/Modules**

- > Feature:  **Filters**

- > Scenario: **Filter - Agent Module - Dashboard/Events**

- > Test Case:

@Scneario: Validate that a filter added on Agent/Module/Dashboard it's displayed on Agent/Module/Event
    
    Given the user is on Agent/Module
    When the user add a new filter
    Then the filter label is displayed
    And the user navigate to Module/Event page
    And the filter label is displayed.

**Comment by Mayons** [comment]
Automated test case. Changes are merged on feature/frontend branch
