### ISSUE TITLE
Validate delete filter on Module/Event

### ISSUE THREAD

**Issue by mauceballos** [wazuh/wazuh-kibana-app#4022]
- > Path:   **Modules**
     
- > Section:  **Modules**

- > Feature:  **Filters**

- > Scenario: **Filter - Modules/Event - Remove Filter**

- > Test Case:

@Scenario:  Validate delete filter on Agent/Module/Event

    Given The kibana admin user is logged in using xpack and the wazuh logo is displayed
    When The user goes to <Module Name>
    And The user adds a new filter
    And The user checks filter label is added
    And The user removes the applied filter
    Then The user checks filter label is not added

    |Module|
    |-------|
    |Security Events|
    |Integrity Monitoring|
    |Vulnerabilities|
    |MITRE ATT&CK|
    |Policy Monitoring|
    |System Auditing|
    |Security configuration assessment|
    |PCI DSS|
    ||GDPR
    |HIPAA|
    |NIST 800-53|
    |TSC|

**Comment by Mayons** [comment]
Working on a refactor
