### ISSUE TITLE
Circular re-directions - Infinite loop

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-kibana-app#4028]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.2   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
There are some cases in which an infinite redirection loop is produced. The app router should have a circuit breaker to avoid it and also those cases should be identified and fixed.

- [x] Identify which scenarios produce a circular redirection
- [x] Fix looping scenarios

Related to #3929

**Comment by asteriscos** [comment]
There seems to be cyclic cases when the Error Orchestrator `plugins/wazuh/public/react-services/error-orchestrator/error-orchestrator-base.ts` tries to log an error and fails:
![Screenshot from 2022-04-19 20-28-49](https://user-images.githubusercontent.com/9343732/164071743-0c2b72b6-1287-4e01-bcd6-5fc73796503e.png)


Also there are cases when the window url is already `health-check` and it redirects to _**/health-check**_ anyway.
`plugins/wazuh/public/react-services/generic-request.js`
![Screenshot from 2022-04-19 20-22-46](https://user-images.githubusercontent.com/9343732/164070809-d1db3869-739a-45fb-ba97-508042fd101a.png)

**Comment by asteriscos** [comment]
The following angularJs router resolvers re-directions where analyzed:

![image](https://user-images.githubusercontent.com/9343732/164288864-5f46b214-445d-4d2e-9693-61f0db4f613a.png)



The proposed solution would involve avoiding `/blank-screen` wzConfig resolver which makes a request that potentially involves a redirection in case of an error.

![image](https://user-images.githubusercontent.com/9343732/164288518-3c6c914a-2be9-4c96-9720-f5deed08a0ca.png)



Also prevent recursive re-directions when a `GenericRequest` provokes an exception:

![image](https://user-images.githubusercontent.com/9343732/164289389-d53aad2e-9c61-499a-888e-dd4f746ca5d9.png)


And don't redirect to `/settings` in case `/health-check` resolver fails:

![image](https://user-images.githubusercontent.com/9343732/164289744-50b548e2-53a6-4c0d-8059-1a79faf2e0c0.png)

**Comment by Desvelao** [comment]
One loop could be caused due to the user session expired. More information in https://github.com/wazuh/wazuh-kibana-app/issues/3929#issuecomment-1105368811

**Comment by asteriscos** [comment]
> A loop could be caused due to the user session expired. More information in [#3929 (comment)](https://github.com/wazuh/wazuh-kibana-app/issues/3929#issuecomment-1105368811)

I tested the pull request fixing this issue by leaving the application idle for more than an hour. After this period of time I interacted with Wazuh menu and **the app was immediately redirected to the login page**.
