### ISSUE TITLE
`See full error` toast button exception

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-kibana-app#4030]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.2   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
When an error toast pops up, sometimes the `See full error` button does nothing and throws an exception in the console.

**Steps to reproduce**
1. Force an error, like killing _wazuh-modulesd_ process in the manager
![image](https://user-images.githubusercontent.com/9343732/163846376-9f2ce059-127b-409f-8ae3-e25d36db1678.png)

**Expected Result**
1. Clicking the See full error button should open a modal with a full description of the error
2. In case there's no additional information, the button should not appear

**Actual Result**
1. Clicking the button does nothing and throws an exception

**Screenshots**
![Peek 2022-04-18 19-10](https://user-images.githubusercontent.com/9343732/163845884-9766720a-4081-4812-83c7-d43460644ed0.gif)

![Screenshot from 2022-04-18 19-11-14](https://user-images.githubusercontent.com/9343732/163845907-572f3106-06a0-4428-b402-92b0fb20de9c.png)

**Comment by Machi3mfl** [comment]
## Tested on Kibana 7.10.2 - Opendistro 1.2.0 - Wazuh 4.2.5

This issue doesn't exist on 4.2.5. The error toast doesn't have the button `"See full error"`

<img width="1440" alt="Screen Shot 2022-04-28 at 14 03 45" src="https://user-images.githubusercontent.com/6089438/165812382-a718d9b4-d441-44ea-8b42-533ef87f5a50.png">

**Comment by Machi3mfl** [comment]
## Research

We found the problem reason. The error occurs when the error toast doesn't receive an error and instead receives only a message.
Because of that, the error toast doesn't have the error context to show it when the user clicks the `"See full error"` button.

**Long Term Solution:**
- We must manage the error throws via an error service or something. I will open a new issue to treat this feature. 

**Short Term Solution:**
- Fix all the throw errors on `wz-request`, ensure all throw error returns a error instance and not a string.

**Comment by Machi3mfl** [comment]
Solution:

https://user-images.githubusercontent.com/6089438/165832381-0577aa96-2b54-4793-8450-04500834113b.mov

**Comment by mauceballos** [comment]
Test kibana 7.10 OK

![toast-error](https://user-images.githubusercontent.com/76791841/166057930-7ea7680c-f221-4b78-b47d-4af3326116fc.gif)

**Comment by jhaos** [comment]
Hi, we are getting the same problem in Wazuh 4.3 in the OVA and in a cloud environment. 

![imagen](https://user-images.githubusercontent.com/32964229/168051897-b66f4c91-dca4-4085-a1de-f02fdd9af286.png)

Both versions environments: 4.3.0.
Both App revision: 4301-1.

- Ways to replicate the error in cloud environment:

  1. Restarting the service and going to Wazuh > Settings > API Configuration. This will prompt the button but when clicking on it the error in the console triggers.
  2. Restarting the service and going to Wazuh > Modules > Any module. This will prompt the button but when clicking on it the error in the console triggers.
  3. If the configuration file is empty and we click in Save button. This will prompt the button but when clicking on it the error in the console triggers.

- Way to replicate in OVA
  1. Restarting the service and going to Wazuh > Settings > API Configuration. This will prompt the button but when clicking on it the error in the console triggers.

**Comment by jhaos** [comment]
Hi, we are getting the same problem in Wazuh 4.3 in the OVA and in a cloud environment. 

![imagen](https://user-images.githubusercontent.com/32964229/168051897-b66f4c91-dca4-4085-a1de-f02fdd9af286.png)

Both versions environments: 4.3.0.
Both App revision: 4301-1.

- Ways to replicate the error in cloud environment:

  1. Restarting the service and going to Wazuh > Settings > API Configuration. This will prompt the button but when clicking on it the error in the console triggers.
  2. Restarting the service and going to Wazuh > Modules > Any module. This will prompt the button but when clicking on it the error in the console triggers.
  3. If the configuration file is empty and we click in Save button. This will prompt the button but when clicking on it the error in the console triggers.

- Way to replicate in OVA
  1. Restarting the service and going to Wazuh > Settings > API Configuration. This will prompt the button but when clicking on it the error in the console triggers.

**Comment by Machi3mfl** [comment]
The initial case detected in this issue was fixed.
We opened a new issue to analyze and treat in-depth error management in the app.
New issue: [https://github.com/wazuh/wazuh-kibana-app/issues/4145](https://github.com/wazuh/wazuh-kibana-app/issues/4145)
