### ISSUE TITLE
Github action for execute automated test case - Cypress

### ISSUE THREAD

**Issue by Mayons** [wazuh/wazuh-kibana-app#4031]
This issue is created to track the effort to create a new Github action to execute an execution of an automated test case.

**Comment by Mayons95** [comment]
We worked in this issue with @matiasmoreno876 @mauceballos and @MauGaP.

**Comment by Mayons95** [comment]
Working with @matiasmoreno876 trying to solve an error during the installation of Wazuh - Kibana - App.
We are having some problems with the installation of the Xpack Plugin.

Working with this steps on the action: 
1) Setup environment variables:
2) Download the wazuh-app-environments


![Image](https://user-images.githubusercontent.com/104914131/170034499-70412f4e-d7ae-4088-8e69-0a994fb80f3a.png)


3) Configuring templates docker environment


![Image](https://user-images.githubusercontent.com/104914131/170034529-3fdf34ab-b675-44b4-8fcd-83a3c79e23d4.png)


4) Starting containers


![Image](https://user-images.githubusercontent.com/104914131/170034580-a61b0efc-0f83-4ebf-a1c0-d7d22d8fdc1a.png)


5) Download proyect from wazuh-packages


![Image](https://user-images.githubusercontent.com/104914131/170034600-0f4c570e-5997-4456-80e4-d29daec60e1b.png)


6) Building packages
7) Installing package


![Image](https://user-images.githubusercontent.com/104914131/170034635-c09b2ad8-a137-4e94-8f23-0f2de8324c88.png)



![Image](https://user-images.githubusercontent.com/104914131/170034687-4988b9fc-f374-410a-84e1-8e6089bb60b0.png)


8) Configuring ip container wazuh
9) Download project wazuh-qa
10) Install cypress dependencies
11) Run cypress test
