### ISSUE TITLE
Tenant popup appears when switch to offline API

### ISSUE THREAD

**Issue by Machi3mfl** [wazuh/wazuh-kibana-app#4033]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.2  | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
When an API is offline, the dropdown should not let you choose it. Research the tenants and the multi API support.

**Steps to reproduce**
1. Switch between APIs
2. Logout and Login
3. Tenant popup appears

**Comment by Machi3mfl** [comment]
### Disable tenancy popup via `kibana.yml`

Add setting `opendistro_security.multitenancy.enabled: true` on kibana.yml.

**Result:**  The popup doesn't disappear.

<img width="1439" alt="Screen Shot 2022-04-20 at 14 54 09" src="https://user-images.githubusercontent.com/6089438/164503633-a69bca6c-eec6-4773-96e1-c23c1ee3f5da.png">

Researching on opensearch repository, we found that exists issues about this.

- [Tenancy selection prompt keeps on appearing even if disabled ](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/2)
- [[BUG] Totally disable tenancy](https://github.com/opensearch-project/security-dashboards-plugin/issues/838)
- [Global tenant still enabled despite setting to disabled](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/9)

## Conclusions:

This issue doesn't seem to have a solution in the short term. The ideal solution is to fix this feature on the source code (by the opensearch team).

**Comment by Machi3mfl** [comment]
### Alternatives solutions:

- We can make the fix on the source code and do a Pull Request to the `opendistro-for-elasticsearch` repository. And wait that the pull request be approved.
- Customize the `security-dashboards-plugin` fixing this behavior and make a package to use it in our environments.
We have an approach on this issue: #3496 `ODFE 1.13.0 Select your tenant message popping up every time we log in`

**Comment by Machi3mfl** [comment]
## Current solution

- Skip tenant selection if tenant is specified in URL.
Example: `http://wazuh:5601/app/wazuh?security_tenant=<tenant_name>`

### Implementation:

1. Add the following config in `kibana.yml`
`server.defaultRoute: /app/wazuh?security_tenant=<tenant_name>` or `uiSettings.overrides.defaultRoute: /app/wazuh?security_tenant=<tenant_name>`

This will add this config to the URL and skip the tenant popup.

### Resources: 
- [https://github.com/opensearch-project/security-dashboards-plugin/pull/605](https://github.com/opensearch-project/security-dashboards-plugin/pull/605) `Add tenant parameter to shared url`
- [https://github.com/opensearch-project/security-dashboards-plugin/pull/586](https://github.com/opensearch-project/security-dashboards-plugin/pull/586) `Skip tenant selection if tenent is specified in URL`

**Comment by gdiazlo** [comment]
The problem with the URL solution is that if we open a link in another window, the URL must have also the tenant selection included. That would force us to change all the links within the application to incorporate it. Some times this will be impossible depending on the component which generates the link.

**Comment by gdiazlo** [comment]
We are going to use the mitigation proposed in https://github.com/wazuh/wazuh-packages/pull/1471 and implemented in https://github.com/wazuh/wazuh-packages/pull/1479/files

The key change here besides disabling the multi-tenancy by default is to disable the pop-up function by passing it a hard-coded false value.

We need to check that when we enable multi-tenancy in a deployment, we can access the tenant selection through the top-right user menu, where log out is.

**Comment by gdiazlo** [comment]
@wazuh/qa is also testing it with the packages. Their progress is in https://github.com/wazuh/wazuh-qa/issues/2816

**Comment by gdiazlo** [comment]
The fix was applied and released as a modification of the package.
