### ISSUE TITLE
Improve messages in the agent installation instructions 

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#4036]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | -    | -| - |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
The message should be improved. We can change to:

```Running this command will not enroll the agent if it is doing an upgrade. See Wazuh documentation.```

Also, the link to the documentation should open a new tab in the browser.

**Screenshots**
![image](https://user-images.githubusercontent.com/2181918/163942848-ee0432e3-f910-43b5-8d2b-a3eea290b8b3.png)

**Comment by yenienserrano** [comment]
Solved #4040

**Comment by yenienserrano** [comment]
Updated proposal ✅ 
![image](https://user-images.githubusercontent.com/63758389/164208378-f1ef24c4-4801-41f6-a2fa-5fb66893232a.png)

**Comment by Mayons** [comment]
The message is displayed on step 5 for an installation of Debian/Ubuntu - X86_64 architecture. Is this correct ? @yenienserrano 
![image](https://user-images.githubusercontent.com/33849347/165365288-cc0a9e69-cdb0-4e25-b3a1-5f8e622635ba.png)

**Comment by gdiazlo** [comment]
Update:

The message about the need to be an administrator should be above the command:

![image](https://user-images.githubusercontent.com/2181918/165559051-bb91e43d-a684-4a45-92c0-cb47b290ac97.png)

**Comment by yenienserrano** [comment]
Updated:

![image](https://user-images.githubusercontent.com/63758389/165562614-79ffa292-8adf-4946-9bc9-767fea39e91f.png)

**Comment by Desvelao** [comment]
Solved in https://github.com/wazuh/wazuh-kibana-app/pull/4040.
