### ISSUE TITLE
Improve messages on agent installation walkthrough

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#4037]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | - | -| - |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
Improve the message showing we can use an IP address and also a domain name in the field.

```Define the Wazuh server IP address / name using the enrollment.dns setting below```

**Screenshots**

![image](https://user-images.githubusercontent.com/2181918/163943062-57b7b2f3-9be4-4c6a-b38e-9f7e03b2ab7c.png)

**Comment by yenienserrano** [comment]
Solved #4040

**Comment by gdiazlo** [comment]
Update proposal: 

`This is the address the agent uses to communicate with the Wazuh server. It can be an IP address or a fully qualified domain name (FQDN).`

@yenienserrano please update the PR with the new proposal.

**Comment by yenienserrano** [comment]
Updated proposal ✅

**Comment by Mayons** [comment]
Test OK 
![image](https://user-images.githubusercontent.com/33849347/165364615-9d47abb9-3793-4552-9074-2209cf3b0a52.png)

**Comment by Desvelao** [comment]
Solved in https://github.com/wazuh/wazuh-kibana-app/pull/4040.
