### ISSUE TITLE
Consistency in pagination widget

### ISSUE THREAD

**Issue by chantal-kelm** [wazuh/wazuh-kibana-app#4041]
**Describe the solution you'd like**
Currently in some tables of the application we find inconsistencies in the pagination widget, in some cases it has been reported that it only has one option. For this, it is necessary to carry out an analysis in all the tables and verify in which of them the inconvenience appears.

**Describe alternatives you've considered**
One of the possible solutions is to maintain consistency in the options that are presented to us, for example to show the following alternatives for the number of rows to show (10 15 25 50 100)

**Additional context**
Rows per page widget - in some tables there is only one option for the widget. we need to remove the widget in this case, or support multiple options

**Comment by chantal-kelm** [comment]
**Research**

Modules -> security events, widget shows 10 25 50
Management -> Rules, widget shows 10 15 25 50 100
Management -> Decoders, widget shows 10 15 25 50 100
Management -> Cbd lists, widget shows 10 15 25 50 100
Management -> Groups, widget shows 10 25 50 100
Management -> Reporting, widget shows 10 25 50
Security -> Users, widget shows 10 25 50
Security -> Roles, widget shows 10 25 50
Security -> Policies, widget shows 10 25 50
Security -> Roles mapping, widget shows 10 25 50
Settings -> Api, widget shows 10 25 50

As long as there are less than 10 results the widget is shown to choose from
in some tables the widget has the numbers 10 25 50 and in others 10 15 25 50 100
In the agents table, the widget does not appear

**Comment by matiasmoreno876** [comment]
Currently we can observe the behavior of the widget, entering the following route, Modules -> MITRE ATT&CK

![image](https://user-images.githubusercontent.com/49887871/164067701-86c82ede-52c7-403f-bdfc-f9b81cd7a58a.png)

**Comment by Mayons** [comment]
TEST OK! 
![image](https://user-images.githubusercontent.com/33849347/165523162-2811e46f-db12-46c5-a765-dc720cadddc9.png)
