### ISSUE TITLE
Grammatical error and absence of capitalization in the State field

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-kibana-app#4044]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 7.x     | 4301-1 | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Firefox |

**Description**
The text "Date add" is incorrect and the value of "Status" is not capitalized.

**Preconditions**
1. A registered agent must exist

**Steps to reproduce**
1. Navigate to Management -> Status

**Expected Result**
1. The field in the "Last registered agent" section must be "Date added"
2. The value of the "Status" field should be capitalized (E.g: Active)

**Actual Result**
1. The text "Date add" is incorrect and the value of "Status" is not capitalized.

**Screenshots**
![image](https://user-images.githubusercontent.com/39094716/164022136-5cafd3ef-8880-4d6e-abc8-035521d136d4.png)

**Comment by Mayons** [comment]
Reproducible on RC6
Kibana 7.16.3

**Comment by chantal-kelm** [comment]
**Correction of field and value in the section: last registered agent**

**Preconditions**
1. A registered agent must exist

**Steps to reproduce**
1. Navigate to Management -> Status

As you can see in the image in the section: 'last registered agent' there is a field that says "Date add" and it should say "Date added", you can also see that the value of the Status field is "active" and it should be "Active"

![Screenshot from 2022-05-02 12-43-56](https://user-images.githubusercontent.com/99441266/166263906-02aeb5f0-af74-4eca-b9cb-72f0867cfe9a.png)

In this image you can see the corrected errors

![Screenshot from 2022-05-02 12-45-49](https://user-images.githubusercontent.com/99441266/166264214-d91957f4-123e-497e-a701-3fb6291665dc.png)
