### ISSUE TITLE
Can't remove cluster filters

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-kibana-app#4045]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 7.x     | 4301-1 | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Firefox |

**Description**
In the Cluster section (within Management) when an existing but negated filter is added, it cannot be removed.
It has a workaround (refresh the page and enter the Cluster section again).

**Preconditions**
1. A cluster must exist

**Steps to reproduce**
1. Navigate to Management -> Cluster
2. Click on 'Add filter'
3. Add the same filter as the existing one but negated it.

**Expected Result**
1. The App should allow removing the added filter.

**Actual Result**
1. Is not possible to remove the added filter.

**Screenshots**

https://user-images.githubusercontent.com/39094716/164027500-ecdfc38f-de08-402a-a879-ad90132dc9d2.mp4

**Comment by gdiazlo** [comment]
These mechanics come from the ability to select different endpoints. This filter affects the whole application. 

https://user-images.githubusercontent.com/2181918/164730503-541f1efa-cc62-47b8-ab11-991a3f0f47d3.mp4

Interestingly, in the opensearch-dashboard discover, the filters using the same field are rewritten appropriately.

https://user-images.githubusercontent.com/2181918/164731547-7b10a715-dcd2-4b2d-bd97-369bbe7fd1d9.mp4

But not so in our discover section.

![image](https://user-images.githubusercontent.com/2181918/164732126-9cb0e541-96b1-4e33-9d90-de44255f8291.png)

 This could mean there is code in the opensearch-dashboard discover native plugin to solve this.

**Comment by yenienserrano** [comment]
**solved:** 

- #4112

**Comment by matiasmoreno876** [comment]
@yenienserrano This error also appears for kibana versions greater than 7.16.x, we need a PR pointing to the branch [4.3-7.16](https://github.com/wazuh/wazuh-kibana-app/tree/4.3-7.16)

**Comment by mauceballos** [comment]
Testing on kibana v7.10.2 OK

![4112](https://user-images.githubusercontent.com/76791841/165830448-b93b4d78-5c07-4023-bc30-3e385dcaff6b.gif)

**Comment by Desvelao** [comment]
Solved in https://github.com/wazuh/wazuh-kibana-app/pull/4112.
