### ISSUE TITLE
Error when restarting the cluster and changing the environment

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-kibana-app#4046]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 7.x     | 4301-1 | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Firefox |

**Description**
When restarting the cluster and changing the environment the App shows an error.

**Preconditions**
1. At least 2 environments should exist

**Steps to reproduce**
1. Navigate to 'Management -> Logs'
2. In another tab, navigate to 'Management -> Status' and select 'Restart the cluster'
3. In 'Management -> Logs' select another environment.

**Expected Result**
1. The App should refresh the 'Management -> Logs' view

**Actual Result**
1. An error is displayed when the view is refreshed

**Screenshots**

https://user-images.githubusercontent.com/39094716/164044197-25d66754-ac8e-4a46-882d-ab7fb3fb63e6.mp4

**Comment by Mayons** [comment]
Reproducible on RC6 
Kibana 7.16.3
![image](https://user-images.githubusercontent.com/33849347/164065498-3cef6542-e4ae-427e-91a8-8a51517292f8.png)

**Comment by AlexRuiz7** [comment]
Solved by #4110
