### ISSUE TITLE
Improve the visibility of the information displayed in the Table Details of the "Inventory" section.

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-kibana-app#4049]
## Description

This issue is a possible improvement. It does not affect Wazuh's performance. It just improves visibility by making the information clear and organized. 
After speaking with Gabriel and Santiago, it was necessary to open this topic to follow up. 

## Details: 

|Wazuh version |Install type| OS type |
|---|---|---|
| 4.3 | Manager | [AMI - Wazuh_v4.3.0](https://us-east-1.console.aws.amazon.com/ec2/v2/home?region=us-east-1#ImageDetails:imageId=ami-0b2eeba579427f8bb)|

|Wazuh version |Install type |Platform|
|---|---|---|
| 4.3| Agent| Amazon Linux (AWS) |

### Local_internal_options

> wazuh_modules.debug=2
> monitord.rotate_log=0

## Steps
   1. I Registered and connected agent with the manager.
   2. I Restart Agent and Manager.
   3. I generated an alert  `yum install -y perl-5.16.3-294.amzn2.x86_64`
   4. I detected a vulnerability alert with a package `perl` on `/var/ossec/logs/alerts/alerts.log` on Manager. 
   5. Login in the Wazuh UI. 
   6. Go to Vulnerabilities Section

 ## Results

  - **`Current Results:`** On the Inventory tab of the Vulnerabilities module, we can see the information on the last full scan and last partial scan in the Details section. 
  
    ![imagen](https://user-images.githubusercontent.com/3978434/164072903-6f07527a-7819-42dc-89f6-fa1bbd305a3c.png)

  
  - `Expected Results:` On the Inventory tab of the Vulnerabilities module, we can see the information on the last full scan and last partial scan in the Details section.  
     If we separate it as a table or with lines the information could be clear. Example:
        
      ![imagen](https://user-images.githubusercontent.com/3978434/164072778-dc9e0c2c-7822-4462-bd22-9e6496cd8387.png)

**Comment by gdiazlo** [comment]
We will work on other designs. We  will work a proposal.

**Comment by AlexRuiz7** [comment]
## Proposal

The team discussed this issue and proposed to follow the design used on the summary header of the main Agent view:

![image](https://user-images.githubusercontent.com/15186973/170019652-0e478f1e-8050-4ee8-a45c-53f7bf70b1da.png)


![image](https://user-images.githubusercontent.com/15186973/170019600-dfecbefc-36d7-42a2-806c-1aad12184073.png)

This proposal implies:

- The use of different HTML elements to distinguish between the label and the value, preferably on a vertical layout, but not mandatory.
- The use of a bold font for the vale (timestamp).
- The use of different font sizes for the label (smaller) and the value (bigger).

With this, we achieve a better UI that allows the user to easily and quickly identify the information that matters, improving the UX.

**Comment by Desvelao** [comment]
Solved in https://github.com/wazuh/wazuh-kibana-app/pull/4169

## Changes
- replaced as the full and partial scan dates are displayed

# Screenshot
![image](https://user-images.githubusercontent.com/34042064/170490840-87eaa5a8-d175-4853-a40d-f538d5fd4deb.png)
