### ISSUE TITLE
Security Events cannot be accessed after selecting a time range

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-kibana-app#4052]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3  | 7.x     | 4301-1 | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Firefox|

**Description**
When we select a time frame in Security Events>Events, and we try to access Dashboard, we get an error and we can't access against Security Events until we refresh the page. 

**Steps to reproduce**
1. Navigate to Modules>Security Events>Events
2. With the mouse, select a time frame in the chart.
3. Access to Modules>Security Events>Dashboard

**Expected Result**
1.  Go back to Dashboard

**Actual Result**
1. Error message:

![image](https://user-images.githubusercontent.com/80041853/164189881-8cfe65e1-c87b-44c7-b0c1-0bf6bc959211.png)

**Screenshots**

https://user-images.githubusercontent.com/80041853/164189959-ac70ec00-8b0c-4173-858d-adba79ce48c0.mp4

**Comment by AlexRuiz7** [comment]
Some more details:
------------

- Request URL: https://demo.wazuh.info/elastic/alerts
- Request Payload: 
```
{
  "index": "wazuh-alerts-*",
  "body": {
    "query": {
      "bool": {
        "must": [
          {
            "range": {
              "timestamp": {
                "gte": "2022-04-01T21:38:54.004Z",
                "lte": "2022-04-14T22:35:10.922Z",
                "format": "epoch_millis"
              }
            }
          },
          {
            "match": {
              "agent.id": "001"
            }
          }
        ],
        "filter": [
          {
            "match_all": {}
          },
          {
            "match_phrase": {
              "cluster.name": {
                "query": "wazuh1"
              }
            }
          },
          {
            "match_phrase": {
              "agent.id": {
                "query": "001"
              }
            }
          },
          {
            "match_phrase": {
              "cluster.name": {
                "query": "wazuh1"
              }
            }
          },
          {
            "match_phrase": {
              "agent.id": {
                "query": "001"
              }
            }
          }
        ],
        "should": [],
        "must_not": []
      }
    },
    "size": 10,
    "from": 0,
    "sort": {
      "timestamp": {
        "order": "desc"
      }
    }
  }
}
```

- Request Response:
```json
{"statusCode":500,"error":"Internal Server Error","message":"4010 - search_phase_execution_exception"}
```

**Comment by juliamagan** [comment]
It also happens when we select a time range in Agents>Evolution:

https://user-images.githubusercontent.com/80041853/164202349-8ce3d737-6577-4e5c-8d94-98330a0490de.mp4

**Comment by matiasmoreno876** [comment]
Currently, if we select the date range manually, the error still occurs.

https://user-images.githubusercontent.com/49887871/165594526-6d468792-6f31-496b-b8e1-5aa5d473c5df.mov

**Comment by matiasmoreno876** [comment]
Also, when we get the error screen and click refresh and then try to enter security events again, the view keeps crashing.

https://user-images.githubusercontent.com/49887871/165594919-20fbb731-34b3-495e-8ffc-1f4fd8b5f8c1.mov

**Comment by matiasmoreno876** [comment]
I am still not finding what is the origin of the problem, I leave in detail the logs that the app throws when generating the error.

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/49887871/165595293-5e3d0d42-f1c7-433e-88ec-43f0eb602b57.png">

**Comment by Mayons** [comment]
TEST OK on Kibana 7.10.2 
I tried to test it on 7.16 but I can't build the app with this environment

**Comment by Desvelao** [comment]
Solved in https://github.com/wazuh/wazuh-kibana-app/pull/4115.
