### ISSUE TITLE
Support Elastic Stack 7.16.X and 7.17.X all minor versions

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#4054]
We need to generate packages for 7.16.X and 7.17.X for all minor versions:

- [x] 7.17.3
- [x] 7.17.2
- [x] 7.17.1
- [x] 7.17.0

- [x] 7.16.3
- [x] 7.16.2
- [x] 7.16.1
- [x] 7.16.0

We need to ensure: 
- The release notes do not contain information which might cause our app to malfunction
- Our app installs without errors
- We test the application with a single browser
  - We can navigate through all main modules
  - We can contact the API and get results
  - The discover works with sample data

These smoke tests should focus in general functionality, as the detailed test were already done in major versions.

**Comment by Mayons** [comment]
- **Release Notes For Kibana 7.16.0**

- Updates browser support: Google Chrome, Microsoft Edge, Mozilla Firefox, and ApplemSafari browser support has been updated. For more information, refer to [#112523](https://github.com/elastic/kibana/pull/112523).
- Removes legacy data table: The legacy aggregation-based data table and vis_type_table.legacyVisEnabled setting are no longer supported. For more information, refer to [#111339](https://github.com/elastic/kibana/pull/111339).
- Removes the legacy area, bar, and line charts library: The legacy aggregation-based area, bar, and line charts are no longer supported. For more information, refer to [#110786](https://github.com/elastic/kibana/pull/110786).
- Removes the Timelion app: The Timelion app is no longer supported. For more information, refer to [#110255](https://github.com/elastic/kibana/pull/110255)
- Replaces Osquery scheduled query groups with packs: Queries are now scheduled using packs. For more information, refer to [#107345](https://github.com/elastic/kibana/pull/107345).

**Comment by Mayons** [comment]
[Release Notes For Kibana 7.16.1](https://www.elastic.co/guide/en/kibana/7.16/release-notes-7.16.1.html#fixes-v7.16.1)
Wazuh-Kibana-App for Kibana 7.16.1 - Test OK

**Comment by Mayons** [comment]
Packages generated for Kibana: 7.16.2 and 7.16.3

**Comment by Mayons** [comment]
[Release Notes For Kibana 7.16.2](https://www.elastic.co/guide/en/kibana/7.16/release-notes-7.16.2.html)
Wazuh-Kibana-App for Kibana 7.16.3
- [x] The release notes do not contain information which might cause our app to malfunction
- [x] Our app installs without errors
- [x] We test the application with a single browser
  - [x] We can navigate through all main modules
  - [x] We can contact the API and get results
  - [x] The discover works with sample data
