### ISSUE TITLE
Warn the user that the file will be replaced

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-kibana-app#4056]
## Context
The application does not warn the user when loading a file with the same name as an existing file.

**Where this happens:**
- Management/Rules
- Management/Decoders

https://user-images.githubusercontent.com/39094716/164232221-505af226-b728-436f-b053-f624f8e64f1a.mp4

## Requested feature
A warning message is needed for the user to know the impact of this action.

**Comment by Mayons** [comment]
Behavior is reproducible on 4.3 RC6 on Kibana 7.16.3

**Comment by yenienserrano** [comment]
The way I see to solve it is to load the files to be imported to see if the file already exists, if it exists show the user that the file already exists and if it continues it will overwrite it.

**Comment by yenienserrano** [comment]
In order to be able to see if the file you want to upload exists, you can use the `/rules/files` endpoint looking for the filenames

**Comment by yenienserrano** [comment]
Estoy trabajando en una forma de que el usuario vea qué archivos ya existen y pueda eliminarlos de la lista de importación.

**Comment by yenienserrano** [comment]
I was investigating why 5 files had been put as maximum, and I found [this issue](https://github.com/wazuh/wazuh-kibana-app/issues/1770), when the component was created, I saw that it lost a functionality that it had when this issue occurred for example, I will work on recovering the functionality.

**Comment by yenienserrano** [comment]
Solve:
- #4180
