### ISSUE TITLE
Red line at the end of the graph

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-kibana-app#4058]
Delete the red line at the end of the graph in events section.

https://user-images.githubusercontent.com/26927338/164235533-60e21b2d-a3ff-415c-a69f-3fbcf7596b43.mp4

**Comment by gdiazlo** [comment]
This design is present in the discover plugin in kibana and opensearch-dashboards. The red line shows that the bucket of the histogram is incomplete at that location.

https://user-images.githubusercontent.com/2181918/164728858-73a7e8ef-fabc-4efb-a892-c7352b768573.mp4

In the dark layout is difficult to see that in the background there are lines which show where a bucket start and ends.
