### ISSUE TITLE
No error message is displayed when uploading an empty file

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-kibana-app#4059]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3 (RC6)   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Firefox |

**Description**
When uploading an empty file the API returns an error but the front-end does not show any message.
This bug was found in:
- Management/Rules
- Management/Decoders

**Steps to reproduce**
1. Create an empty file
2. Navigate to 'Management/Rules' or 'Management/Rules'
3. Select the 'Add new (rules | decoders) file' option
4. Upload the empty file

**Expected Result**
1. An error message should be displayed

**Actual Result**
1. No error message is displayed

**Screenshots**

https://user-images.githubusercontent.com/39094716/164238291-e3d96051-d93a-4024-9bab-dacc15564845.mp4

**Comment by gdiazlo** [comment]
Related to #4056 If combined both the results a deleted file without  warnings.

**Comment by AlexRuiz7** [comment]
Pending independent Pull Request.
