### ISSUE TITLE
No spinner is displayed when exporting a table

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-kibana-app#4060]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3 (RC6)   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Firefox |

**Description**
When the user exports a table no "loading" message or spinner is displayed to notify the user that the request is being processed.

This feature is not in any view of the "Management" section.

**Steps to reproduce**
1. Navigate to 'Management/(Rules | Decoders | etc.)'
2. Click on 'Export formatted'

**Expected Result**
1. A "loading" message or spinner should be displayed

**Actual Result**
1. No "loading" message or spinner is displayed

**Screenshots**

https://user-images.githubusercontent.com/39094716/164241496-91e8ecc4-a3a5-4601-a2bb-365c167019ac.mp4

**Comment by gdiazlo** [comment]
This behavior has been reproduced in 4.2.6.
