### ISSUE TITLE
The icon is not correct in the 'files' section

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-kibana-app#4064]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3 (RC6)   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Firefox |

**Description**
The actual icon represents the "view" action, but when the option is selected the App allows editing the file.

**Steps to reproduce**
1. Navigate to 'Management/Groups'
2. Select any group
3. Select the 'Files' tab within the group details

**Expected Result**
1. An 'edit' icon should be displayed in the 'Actions' column

**Actual Result**
1. A 'view' icon is displayed

**Screenshots**

https://user-images.githubusercontent.com/39094716/164263565-4e64d810-5e45-4aba-8352-07543e1b9560.mp4

**Comment by yenienserrano** [comment]
solved: 
- #4114
