### ISSUE TITLE
The 'unselect all' option is useless

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-kibana-app#4065]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3 (rc6)   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Firefox |

**Description**
When the user wants to export the information of the group in PDF format 2 options are displayed; if both are unselected then the 'Generate PDF report' option is disabled. So, the 'Unselect all' option is useless. 

**Preconditions**
1. A group must exist

**Steps to reproduce**
1. Navigate to 'Management/Groups'
2. Select any group
3. Select the 'Export PDF' option

**Requested change**
The 'Unselect all' option should be deleted because only 2 options are available and this option isn't useful for the user.

**Screenshots**

https://user-images.githubusercontent.com/39094716/164265823-48867688-a2c6-4db1-b8e7-96e71a398d88.mp4

**Comment by gdiazlo** [comment]
We should remove the select all and unselect all. Two entries are not something which needs to be automated I think.
