### ISSUE TITLE
Improvement of agent charts

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-kibana-app#4077]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 7.x     | 4301| Basic, ODFE, Xpack |

| Browser |
| ------- |
| Firefox|

**Description**
While testing the agent status we could see that the status chart has a little red/grey line when all the agents are active. If we put the mouse on that line, we can see `0 Never connected`.

In the evolution chart, we could see that we can decrease the time range, but we cannot increase it again. Also, when we set the legend, one is more to the right than the other, like being centered. Perhaps it is more visual that they are aligned. Finally, if one of the points is at the maximum (at the top of the graph), it is cut off and only half of it is visible.

**Steps to reproduce**
1. Navigate to Agents
2. Check the status graphic
3. Check the evolution graphic and try to edit it

**Screenshots**

https://user-images.githubusercontent.com/80041853/164458676-ec924426-ba4e-409f-9c93-305bbec4ba23.mp4

**Comment by gdiazlo** [comment]
Related to #3071

**Comment by Desvelao** [comment]
# Research

> While testing the agent status we could see that the status chart has a little red/grey line when all the agents are active. If we put the mouse on that line, we can see 0 Never connected.

We go to replace the component that renders the visualization of `Agent status` with a donut visualization that is used in other sections and review the problem.

> In the evolution chart, we could see that we can decrease the time range, but we cannot increase it again. Also, when we set the legend, one is more to the right than the other, like being centered. Perhaps it is more visual that they are aligned. Finally, if one of the points is at the maximum (at the top of the graph), it is cut off and only half of it is visible.
This visualization, in recent versions, has a simple time picker. 

We will review the style suggestions when we redefine the visualization types.

**Comment by Desvelao** [comment]
We replaced the `Status` visualization with another component that has no the mentioned problem. This change is included in  https://github.com/wazuh/wazuh-kibana-app/pull/4166.

![image](https://user-images.githubusercontent.com/34042064/170277454-36504de7-1241-410b-b6a4-6657d6c174d7.png)

**Comment by Mayons95** [comment]
https://github.com/wazuh/wazuh-kibana-app/pull/4166. Reviewed
TEST OK
