### ISSUE TITLE
Could not fetch .wazuh-version index "status":500

### ISSUE THREAD

**Issue by chester0309** [wazuh/wazuh-kibana-app#408]
I'm facing problem when accessing Wazuh App on Kibana,
Kibana version :  6.2.4
Wazuh version : 3.2.1_6.2.4

![2018-04-25_120244](https://user-images.githubusercontent.com/21052105/39227111-08502c4a-4881-11e8-9ce9-975a4fdc6c42.png)

**Comment by JuanjiJG** [comment]
Hello @chester0309,

Let me try to help you with this.

First of all, let's get all your currently inserted indices with the following command:
```
curl -XGET localhost:9200/_cat/indices?v
```

Also, I would need your Wazuh app logs, so execute this command too:
```
cat /usr/share/kibana/plugins/wazuh-logs/wazuhapp.log
```
And paste here the results, on a new comment.

In addition to that, let me ask you a question: Did you perform a **clean installation** of Wazuh and the Elastic Stack, or was it an **upgrade** from an earlier version?

Thanks for your patience.

Regards,
Juanjo

**Comment by chester0309** [comment]
Hi @JuanjiJG , Thanks for your response, here is the output : 

curl -XGET elasticsearch-svr:9200/_cat/indices?v
health	status	index							uuid					pri	rep	docs.count	docs.deleted	store.size	pri.store.size
yellow	open	.kibana							ZZFUdKM3Sp2vgxb6H_aoiQ	1	1	100	1	152kb	152kb
yellow	open	.wazuh							rsbppbyvTOWCylSvih-3Ig	1	1	1	0	9.9kb	9.9kb
yellow	open	.wazuh-version					qZ7jmZbSQyqOL3cQ_mPtzg	1	1	0	0	261b	261b
yellow	open	beat-2018.04.22					oK7vf-s8TJG1l3UU2XFGfQ	3	1	3090	0	1.5mb	1.5mb
yellow	open	beat-2018.04.23					FfYmZFJHQiGrs-tYeLyqdw	3	1	1526	0	913.8kb	913.8kb
yellow	open	filebeat-6.2.2-2018.04.11		PI6ILmSyRwevReOTthDJNA	3	1	11671	0	3.5mb	3.5mb
yellow	open	filebeat-6.2.2-2018.04.12		ee1tk8A1RfiUOqIMKYQHHA	3	1	213	0	381.5kb	381.5kb
yellow	open	syslog-2018.04.24				K4RA1xAjQ0iaFgd1WzDe_g	3	1	21785	0	9.7mb	9.7mb
yellow	open	syslog-2018.04.25				3-QW9tG1RNuDOtc6QqXr1g	3	1	6215	0	3mb	3mb
yellow	open	test-syslog	Z					vvs9_dJRwG1ZB0JkH6koQ	5	1	0	0	1.2kb	1.2kb
yellow	open	test-syslog-kafka				zYZf9WNQQ6-Azl6mVOauZA	5	1	0	0	1.2kb	1.2kb
yellow	open	test-system						EAIwZePaT5y8DxhKm47FZg	3	1	0	0	690b	690b
yellow	open	wazuh-alerts-3.x-2018.03.13		Ww1ZHNN-QkueA6yFqasoTQ	5	1	1	0	34.1kb	34.1kb
yellow	open	wazuh-monitoring-3.x-2018.04.24	PPyLjTygQESvGZWiD4GPmA	3	1	0	0	690b	690b
yellow	open	wazuh-monitoring-3.x-2018.04.25	VvJXzRKNR3q2SLgYttiWRw	3	1	14	0	179.5kb	179.5kb

cat /usr/share/kibana/plugins/wazuh-logs/wazuhapp.log
{"date":"2018-04-25T04:30:27.434Z","level":"info","location":"[initialize]","message":"Kibana index: .kibana"}
{"date":"2018-04-25T04:30:28.095Z","level":"info","location":"[monitoring][checkKibanaStatus]","message":"Waiting for Kibana and Elasticsearch servers to be ready..."}
{"date":"2018-04-25T04:30:28.661Z","level":"info","location":"[monitoring][init]","message":"Creating/Updating wazuh-agent template..."}
{"date":"2018-04-25T04:30:28.662Z","level":"info","location":"[monitoring][checkTemplate]","message":"Updating wazuh-monitoring template..."}
{"date":"2018-04-25T04:30:28.678Z","level":"info","location":"[initialize][checkWazuhIndex]","message":"Checking .wazuh index."}
{"date":"2018-04-25T04:30:28.679Z","level":"info","location":"[initialize][checkWazuhVersionIndex]","message":"Checking .wazuh-version index."}
{"date":"2018-04-25T04:30:28.688Z","level":"info","location":"[initialize][checkWazuhVersionIndex]","message":".wazuh-version document does not exist. Initializating configuration..."}
{"date":"2018-04-25T04:30:29.068Z","level":"info","location":"[initialize][checkKnownFields]","message":"x-pack enabled: no"}
{"date":"2018-04-25T04:30:29.070Z","level":"info","location":"[monitoring][init]","message":"Creating today index..."}
{"date":"2018-04-25T04:30:29.073Z","level":"error","location":"[initialize][saveConfiguration]","message":"[resource_already_exists_exception] index [.wazuh-version/qZ7jmZbSQyqOL3cQ_mPtzg] already exists, with { index_uuid=\"qZ7jmZbSQyqOL3cQ_mPtzg\" & index=\".wazuh-version\" }"}
{"date":"2018-04-25T04:30:29.079Z","level":"info","location":"[initialize][checkKnownFields]","message":"Found 23 index patterns"}
{"date":"2018-04-25T04:30:29.082Z","level":"info","location":"[initialize][checkKnownFields]","message":"Found 1 valid index patterns for Wazuh alerts"}
{"date":"2018-04-25T04:30:29.083Z","level":"info","location":"[initialize][checkKnownFields]","message":"Default index pattern found"}
{"date":"2018-04-25T04:30:29.084Z","level":"info","location":"[initialize][checkKnownFields]","message":"Refreshing known fields for \"index-pattern:wazuh-alerts-3.x-*\""}
{"date":"2018-04-25T04:30:29.085Z","level":"info","location":"[monitoring][init]","message":"Checking if wazuh-monitoring pattern exists..."}
{"date":"2018-04-25T04:30:29.093Z","level":"info","location":"[monitoring][init]","message":"Skipping wazuh-monitoring pattern creation. Already exists."}
{"date":"2018-04-25T04:30:29.094Z","level":"info","location":"[initialize][checkKnownFields]","message":"App ready to be used."}
{"date":"2018-04-25T04:30:29.095Z","level":"error","location":"[initialize][init]","message":"[document_missing_exception] [wazuh-version][1]: document missing, with { index_uuid=\"qZ7jmZbSQyqOL3cQ_mPtzg\" & shard=\"0\" & index=\".wazuh-version\" }"}
{"date":"2018-04-25T04:30:29.096Z","level":"error","location":"[initialize][checkKibanaStatus]","message":"[document_missing_exception] [wazuh-version][1]: document missing, with { index_uuid=\"qZ7jmZbSQyqOL3cQ_mPtzg\" & shard=\"0\" & index=\".wazuh-version\" }"}
{"date":"2018-04-25T04:36:29.808Z","level":"info","location":"[initialize]","message":"Kibana index: .kibana"}
{"date":"2018-04-25T04:36:30.589Z","level":"info","location":"[monitoring][checkKibanaStatus]","message":"Waiting for Kibana and Elasticsearch servers to be ready..."}
{"date":"2018-04-25T04:36:31.204Z","level":"info","location":"[monitoring][init]","message":"Creating/Updating wazuh-agent template..."}
{"date":"2018-04-25T04:36:31.205Z","level":"info","location":"[monitoring][checkTemplate]","message":"Updating wazuh-monitoring template..."}
{"date":"2018-04-25T04:36:31.230Z","level":"info","location":"[initialize][checkWazuhIndex]","message":"Checking .wazuh index."}
{"date":"2018-04-25T04:36:31.232Z","level":"info","location":"[initialize][checkWazuhVersionIndex]","message":"Checking .wazuh-version index."}
{"date":"2018-04-25T04:36:31.243Z","level":"info","location":"[initialize][checkWazuhVersionIndex]","message":".wazuh-version document does not exist. Initializating configuration..."}
{"date":"2018-04-25T04:36:31.377Z","level":"info","location":"[initialize][checkKnownFields]","message":"x-pack enabled: no"}
{"date":"2018-04-25T04:36:31.389Z","level":"info","location":"[initialize][checkKnownFields]","message":"Found 23 index patterns"}
{"date":"2018-04-25T04:36:31.395Z","level":"info","location":"[initialize][checkKnownFields]","message":"Found 1 valid index patterns for Wazuh alerts"}
{"date":"2018-04-25T04:36:31.396Z","level":"info","location":"[initialize][checkKnownFields]","message":"Default index pattern found"}
{"date":"2018-04-25T04:36:31.397Z","level":"info","location":"[initialize][checkKnownFields]","message":"Refreshing known fields for \"index-pattern:wazuh-alerts-3.x-*\""}
{"date":"2018-04-25T04:36:31.409Z","level":"info","location":"[initialize][checkKnownFields]","message":"App ready to be used."}
{"date":"2018-04-25T04:36:31.419Z","level":"info","location":"[monitoring][init]","message":"Creating today index..."}
{"date":"2018-04-25T04:36:31.438Z","level":"error","location":"[initialize][saveConfiguration]","message":"[resource_already_exists_exception] index [.wazuh-version/qZ7jmZbSQyqOL3cQ_mPtzg] already exists, with { index_uuid=\"qZ7jmZbSQyqOL3cQ_mPtzg\" & index=\".wazuh-version\" }"}
{"date":"2018-04-25T04:36:31.447Z","level":"info","location":"[monitoring][init]","message":"Checking if wazuh-monitoring pattern exists..."}
{"date":"2018-04-25T04:36:31.452Z","level":"info","location":"[monitoring][init]","message":"Skipping wazuh-monitoring pattern creation. Already exists."}
{"date":"2018-04-25T04:36:31.454Z","level":"error","location":"[initialize][init]","message":"[document_missing_exception] [wazuh-version][1]: document missing, with { index_uuid=\"qZ7jmZbSQyqOL3cQ_mPtzg\" & shard=\"0\" & index=\".wazuh-version\" }"}
{"date":"2018-04-25T04:36:31.455Z","level":"error","location":"[initialize][checkKibanaStatus]","message":"[document_missing_exception] [wazuh-version][1]: document missing, with { index_uuid=\"qZ7jmZbSQyqOL3cQ_mPtzg\" & shard=\"0\" & index=\".wazuh-version\" }"}
{"date":"2018-04-25T04:41:39.237Z","level":"info","location":"[initialize]","message":"Kibana index: .kibana"}
{"date":"2018-04-25T04:41:39.908Z","level":"info","location":"[monitoring][checkKibanaStatus]","message":"Waiting for Kibana and Elasticsearch servers to be ready..."}
{"date":"2018-04-25T04:41:40.457Z","level":"error","location":"[monitoring][getConfig]","message":"no credentials"}
{"date":"2018-04-25T04:41:40.489Z","level":"info","location":"[monitoring][init]","message":"Creating/Updating wazuh-agent template..."}
{"date":"2018-04-25T04:41:40.490Z","level":"info","location":"[monitoring][checkTemplate]","message":"Updating wazuh-monitoring template..."}
{"date":"2018-04-25T04:41:40.521Z","level":"info","location":"[initialize][checkWazuhIndex]","message":"Checking .wazuh index."}
{"date":"2018-04-25T04:41:40.525Z","level":"info","location":"[initialize][checkWazuhVersionIndex]","message":"Checking .wazuh-version index."}
{"date":"2018-04-25T04:41:40.543Z","level":"info","location":"[initialize][checkWazuhVersionIndex]","message":".wazuh-version document does not exist. Initializating configuration..."}
{"date":"2018-04-25T04:41:40.700Z","level":"info","location":"[initialize][checkKnownFields]","message":"x-pack enabled: no"}
{"date":"2018-04-25T04:41:40.713Z","level":"info","location":"[initialize][checkKnownFields]","message":"Found 24 index patterns"}
{"date":"2018-04-25T04:41:40.722Z","level":"info","location":"[initialize][checkKnownFields]","message":"Found 1 valid index patterns for Wazuh alerts"}
{"date":"2018-04-25T04:41:40.723Z","level":"info","location":"[initialize][checkKnownFields]","message":"Default index pattern found"}
{"date":"2018-04-25T04:41:40.724Z","level":"info","location":"[initialize][checkKnownFields]","message":"Refreshing known fields for \"index-pattern:wazuh-alerts-3.x-*\""}
{"date":"2018-04-25T04:41:40.741Z","level":"info","location":"[initialize][checkKnownFields]","message":"App ready to be used."}
{"date":"2018-04-25T04:41:40.748Z","level":"info","location":"[monitoring][init]","message":"Creating today index..."}
{"date":"2018-04-25T04:41:40.770Z","level":"error","location":"[initialize][saveConfiguration]","message":"[resource_already_exists_exception] index [.wazuh-version/qZ7jmZbSQyqOL3cQ_mPtzg] already exists, with { index_uuid=\"qZ7jmZbSQyqOL3cQ_mPtzg\" & index=\".wazuh-version\" }"}
{"date":"2018-04-25T04:41:40.777Z","level":"error","location":"[initialize][init]","message":"[document_missing_exception] [wazuh-version][1]: document missing, with { index_uuid=\"qZ7jmZbSQyqOL3cQ_mPtzg\" & shard=\"0\" & index=\".wazuh-version\" }"}
{"date":"2018-04-25T04:41:40.778Z","level":"error","location":"[initialize][checkKibanaStatus]","message":"[document_missing_exception] [wazuh-version][1]: document missing, with { index_uuid=\"qZ7jmZbSQyqOL3cQ_mPtzg\" & shard=\"0\" & index=\".wazuh-version\" }"}
{"date":"2018-04-25T04:41:42.138Z","level":"info","location":"[monitoring][createIndex]","message":"Successfully created today index."}
{"date":"2018-04-25T04:41:42.141Z","level":"info","location":"[monitoring][init]","message":"Checking if wazuh-monitoring pattern exists..."}
{"date":"2018-04-25T04:41:42.149Z","level":"info","location":"[monitoring][init]","message":"Skipping wazuh-monitoring pattern creation. Already exists."}
{"date":"2018-04-25T04:52:04.340Z","level":"info","location":"[initialize]","message":"Kibana index: .kibana"}
{"date":"2018-04-25T04:52:05.122Z","level":"info","location":"[monitoring][checkKibanaStatus]","message":"Waiting for Kibana and Elasticsearch servers to be ready..."}
{"date":"2018-04-25T04:52:05.857Z","level":"info","location":"[monitoring][init]","message":"Creating/Updating wazuh-agent template..."}
{"date":"2018-04-25T04:52:05.858Z","level":"info","location":"[monitoring][checkTemplate]","message":"Updating wazuh-monitoring template..."}
{"date":"2018-04-25T04:52:05.897Z","level":"info","location":"[initialize][checkWazuhIndex]","message":"Checking .wazuh index."}
{"date":"2018-04-25T04:52:05.900Z","level":"info","location":"[initialize][checkWazuhVersionIndex]","message":"Checking .wazuh-version index."}
{"date":"2018-04-25T04:52:05.918Z","level":"info","location":"[initialize][checkWazuhVersionIndex]","message":".wazuh-version document does not exist. Initializating configuration..."}
{"date":"2018-04-25T04:52:06.074Z","level":"info","location":"[initialize][checkKnownFields]","message":"x-pack enabled: no"}
{"date":"2018-04-25T04:52:06.089Z","level":"info","location":"[initialize][checkKnownFields]","message":"Found 24 index patterns"}
{"date":"2018-04-25T04:52:06.098Z","level":"info","location":"[initialize][checkKnownFields]","message":"Found 1 valid index patterns for Wazuh alerts"}
{"date":"2018-04-25T04:52:06.099Z","level":"info","location":"[initialize][checkKnownFields]","message":"Default index pattern found"}
{"date":"2018-04-25T04:52:06.100Z","level":"info","location":"[initialize][checkKnownFields]","message":"Refreshing known fields for \"index-pattern:wazuh-alerts-3.x-*\""}
{"date":"2018-04-25T04:52:06.122Z","level":"info","location":"[initialize][checkKnownFields]","message":"App ready to be used."}
{"date":"2018-04-25T04:52:06.133Z","level":"info","location":"[monitoring][init]","message":"Creating today index..."}
{"date":"2018-04-25T04:52:06.143Z","level":"error","location":"[initialize][saveConfiguration]","message":"[resource_already_exists_exception] index [.wazuh-version/qZ7jmZbSQyqOL3cQ_mPtzg] already exists, with { index_uuid=\"qZ7jmZbSQyqOL3cQ_mPtzg\" & index=\".wazuh-version\" }"}
{"date":"2018-04-25T04:52:06.145Z","level":"info","location":"[monitoring][init]","message":"Checking if wazuh-monitoring pattern exists..."}
{"date":"2018-04-25T04:52:06.155Z","level":"info","location":"[monitoring][init]","message":"Skipping wazuh-monitoring pattern creation. Already exists."}
{"date":"2018-04-25T04:52:06.407Z","level":"error","location":"[initialize][init]","message":"[document_missing_exception] [wazuh-version][1]: document missing, with { index_uuid=\"qZ7jmZbSQyqOL3cQ_mPtzg\" & shard=\"0\" & index=\".wazuh-version\" }"}
{"date":"2018-04-25T04:52:06.408Z","level":"error","location":"[initialize][checkKibanaStatus]","message":"[document_missing_exception] [wazuh-version][1]: document missing, with { index_uuid=\"qZ7jmZbSQyqOL3cQ_mPtzg\" & shard=\"0\" & index=\".wazuh-version\" }"}

**Comment by jesusgn90** [comment]
Hello @chester0309 , 

as I can see here:

```yellow	open	.wazuh-version	qZ7jmZbSQyqOL3cQ_mPtzg	1	1	0	0	261b	261b```

your `.wazuh-version` has a size of 261b, this is pretty weird, your index is corrupted or simply wrong because the `.wazuh-version` usually takes about 5kb.

* On the other hand you have said Elastic stack 6.2.4 but 6.2.2?
* Is your Wazuh app installed from official package or sources?

Any case please reply us with the answer to the above questions and try the next tip:

```
# curl -XDELETE elastic_ip:9200/.wazuh-version
# systemctl restart kibana
```

Wait about 10 s and then open a new window on your browser. Definetively there is something wrong on your `.wazuh-version`

Also you could check the content of your `.wazuh-version` index, it should looks like this:

```
# curl elastic_ip:9200/.wazuh-version/_search?pretty
{
  "took" : 6,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : ".wazuh-version",
        "_type" : "wazuh-version",
        "_id" : "1",
        "_score" : 1.0,
        "_source" : {
          "name" : "Wazuh App",
          "app-version" : "3.2.1",
          "revision" : "0388",
          "installationDate" : "2018-04-25T07:33:58.000Z",
          "lastRestart" : "2018-04-25T07:33:58.095Z"
        }
      }
    ]
  }
}
```

Regards,
Jesús

**Comment by chester0309** [comment]
Thanks @jesusgn90 for your reply, after delete .wazuh_version & restart the kibana, it's okay now.

**Comment by jesusgn90** [comment]
Ok @chester0309 , have a nice day.

Regards,
Jesús
