### ISSUE TITLE
10 rows is the only possible option in `Intelligence` section

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-kibana-app#4083]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 7.x     | 4301-1 | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Firefox|

**Description**
In the `Intelligence` section, we can't select the number of rows to display because the only available option is 10.

**Steps to reproduce**
1. Navigate to Modules>MITRE ATT&CK>Intelligence
2. Try to change the number of rows

**Expected Result**
1. Change the number of rows (15, 25, 50...)

**Actual Result**
1. The only possible option is 10 

**Screenshots**
![rows](https://user-images.githubusercontent.com/80041853/164487377-1cffdb48-d1ab-4288-8db9-1756f0759bd8.png)

**Comment by gdiazlo** [comment]
This issue is already being tracked in https://github.com/wazuh/wazuh-kibana-app/issues/4041
