### ISSUE TITLE
Agent installation instructions - the command to install windows might not work

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#4085]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx |  - |

**Description**
The command to install an agent displayed by the UI step-by-step guide is:

`Invoke-WebRequest -Uri https://packages.wazuh.com/4.x/windows/wazuh-agent-4.3.0-1.msi -OutFile wazuh-agent-4.3.0.msi; ./wazuh-agent-4.3.0.msi /q WAZUH_MANAGER='10.0.0.241' WAZUH_REGISTRATION_SERVER='10.0.0.241' `

This command, if executed in a powershell in c:\windows\system32 even with administrator privileges, does not work. This seems to be a common scenario.

![image](https://user-images.githubusercontent.com/2181918/164560564-45959469-e44d-4fda-89a9-6eb7b802a73c.png)

This command works correctly if it is executed from the user `$home` directory. We can modify this command by:

`Invoke-WebRequest -Uri https://packages.wazuh.com/4.x/windows/wazuh-agent-4.2.6-1.msi -OutFile "$home\wazuh-agent-4.2.6.msi"; Invoke-Expression "$home\wazuh-agent-4.2.6.msi /q WAZUH_MANAGER='wazuh' WAZUH_REGISTRATION_SERVER='wazuh'"`

which will use the user `$home` folder regardless of where it is executed to solve this. But this approach will assume the user $home is defined and writable. Which most of the time should be true.

We should agree with the @wazuh/cicd team and @wazuh/core on this.

**Comment by gdiazlo** [comment]
We need to update @wazuh/content to reflect the change in the documentation.

**Comment by santiago-bassett** [comment]
Do we want to use $home? What are other vendors doing?

**Comment by alberpilot** [comment]
After the solution applied here: https://github.com/wazuh/wazuh-packages/issues/633 there is no need to include the variable `WAZUH_REGISTRATION_SERVER` in the command, with only `WAZUH_MANAGER` the agent is enrolled.

**Comment by okynos** [comment]
Hello team,

I have done a research about this problem. We got the following facts:
- The default path in Powershell varies from users `vagrant` has `C:\Windows\System32`. Administrator has `C:\Users\Administrator`
- The `vagrant` user can't see any new file in System32 folder so it cannot see the MSI.
- The `Administrator` user cannot see the files downloaded into System32 but it can execute them.
- The System32 folder has special permissions as Windows system points out. It's recommended to avoid working in such directory.
- It's a matter of file occlusion of `vagrant` user, that doesn't allow such user to launch the installer.
- The same problem exists with another installers like notepad++ MSI file.

Here we have got different traces of working and error installation.
[working-trace.txt](https://github.com/wazuh/wazuh-kibana-app/files/8553729/working-trace.txt)
[error-trace.txt](https://github.com/wazuh/wazuh-kibana-app/files/8553730/error-trace.txt)

Recommended command (tested) to set into the Wazuh app:
```
Invoke-WebRequest -Uri https://packages.wazuh.com/4.x/windows/wazuh-agent-4.3.0-1.msi -OutFile C:\wazuh-agent-4.3.0.msi; C:\wazuh-agent-4.3.0.msi /q WAZUH_MANAGER='xxx.xxx.xxx.xxx' WAZUH_REGISTRATION_SERVER='xxx.xxx.xxx.xxx' WAZUH_AGENT_GROUP='default'; rm C:\wazuh-agent-4.3.0.msi
```
I don't recommend the use of `$home` variable that it could lack in Windows XP or another versions.


Comparison with Chocolatey install:
```
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
```

**Comment by okynos** [comment]
| Vendor | Install command |
|:--:|--|
| CrowdStrike | `msiexec.exe /i CrowdStrikeInstaller.msi CID=123456qweasdzxc` |
| LogRythm |  |
| SumoLogic |  |
| Datadog |  |
| TrendMicro |  |
| AtomiCorp |  |
| Splunk |  |
| FleetDM |  |
| Osquery |  |
| Tanium |  |
| SentinelOne |  |
| Carbonblack |  |
| Kubernetes |  |
| Docker |  |
| Falco |  |
| Grafana |  |
| Elastic |  |
|  |  |
|  |  |
|  |  |

**Comment by snaow** [comment]
In progress. @wazuh/qa testing.

**Comment by jmv74211** [comment]
After the review of this issue https://github.com/wazuh/wazuh-qa/issues/2855, it was determined that the command worked correctly, with the exception of a particular version of Windows 7.

Further investigation was performed at https://github.com/wazuh/wazuh-qa/issues/2869, and it was concluded that **the `Invoke-WebRequest` command was added as of powershell v3** (see [This cmdlet was introduced in PowerShell 3.0.](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7.2&viewFallbackFrom=powershell-3.0))

After installing Windows 7 Service Pack 1 and Service Pack 2, it has been possible to upgrade the powershell version from `2.0` to `5.1`, and it has been verified that the command [now works correctly](https://github.com/wazuh/wazuh-qa/issues/2869#issuecomment-1119864652).

@fedepacher has yet to check that the command works correctly for powershell v3.0. 

In case it works correctly with this version (it should), it is proposed to add a message that PowerShell v3 or higher is required for Windows.

**Comment by AlexRuiz7** [comment]
PR to Splunk: https://github.com/wazuh/wazuh-splunk/pull/1315

**Comment by Desvelao** [comment]
# Changes

We added the requirement of PowerShell 3.0 or later in these PRs:
- plugin for Kibana: https://github.com/wazuh/wazuh-kibana-app/pull/4142
- plugin for Splunk: https://github.com/wazuh/wazuh-splunk/pull/1322

**Comment by jmv74211** [comment]
After the tests performed by @fedepacher [here](https://github.com/wazuh/wazuh-qa/issues/2869#issuecomment-1125364026), we can conclude that on Windows the command:

```
Invoke-WebRequest -Uri https://packages.wazuh.com/4.x/windows/wazuh-agent-4.3.0-1.msi -OutFile ${env:tmp}\wazuh-agent-4.3.0.msi; msiexec.exe /i ${env:tmp}\wazuh-agent-4.3.0.msi /q WAZUH_MANAGER='xxx.xxx.xxx.xxx' WAZUH_REGISTRATION_SERVER='xxx.xxx.xxx.xxx' WAZUH_AGENT_GROUP='default'
```


works for powershell versions >= 3.0
