### ISSUE TITLE
The vulnerability summary does not properly link vulnerabilities

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-kibana-app#4087]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 7.x     | 4301-1 | Basic, ODFE, Xpack |

| Browser |
| --- |
| Firefox|

### Description

In the Vulnerability menu of an agent, the summary does not properly link the vulnerability by name.

In this example, we can see desired vulnerability if we filter by severity (critical), but if we filter using the name specified in the summary no vulnerabilities appear.

https://user-images.githubusercontent.com/11089305/164709051-701f6acd-dc35-4ba8-b5ce-ecb101cccbe0.mp4

**Comment by gdiazlo** [comment]
We need to investigate this with @wazuh/framework as seems the API response comes empty, but the request contains all chars of the name.

**Comment by mcarmona99** [comment]
When clicking on:

`Mozilla FIrefox 53.0 (x64 en-US) (509) (x)
`

in the `summary` section, the API log for the endpoint requested is the following:

`2022/04/27 13:55:50 INFO: wazuh-wui <ip> "GET /vulnerability/001" with parameters {"select": "cve,architecture,version,name,severity,cvss2_score,cvss3_score,detection_time,title,condition,updated,published,external_references", "q": "name=Mozilla FIrefox 53.0 (x64 en-US)", "offset": "0", "limit": "10", "sort": "+name"} and body {} done in 0.015s: 200`

The `q` parameter is used.


I have replicated this without the Wazuh dashboard. The parameters used in the API request are `wait_for_complete=true` and `q=name=Mozilla FIrefox 53.0 (x64 en-US)`


Final query after framework processing:

`SELECT name as 'name',version as 'version',condition as 'condition',status as 'status',title as 'title',updated as 'updated',external_references as 'external_references',architecture as 'architecture',cve as 'cve',type as 'type',cvss2_score as 'cvss2_score',detection_time as 'detection_time',severity as 'severity',cvss3_score as 'cvss3_score',published as 'published' FROM vuln_cves WHERE (name = 'Mozilla FIrefox 53.0 ' COLLATE NOCASE)   ORDER BY name ASC LIMIT 500 OFFSET 0`

As we can see, the value for `name` has been truncated.

When calling `_substitute_params`, request has value `{'name$0': 'Mozilla FIrefox 53.0 ', 'offset': 0, 'limit': 500}`. The name was already truncated.

In the `_parse_query` method of `WazuhDBQuery`,

`query_regex` is `re.compile("(\\()?([\\w.]+)([=!=<>~]{1,2})([\\[\\]\\w _\\-\\.:\\\\/']+)(\\))?([,;])?")`

`q` is `'name=Mozilla FIrefox 53.0 (x64 en-US)'`

`self.query_regex.findall(self.q)` is equal to `[('', 'name', '=', 'Mozilla FIrefox 53.0 ', '', '')]`


The problem then has to do with the `query_regex`: `(\()?([\w.]+)([=!=<>~]{1,2})([\[\]\w _\-\.:\\/']+)(\))?([,;])?`

```
(\()?

([\\w.]+)

([=!=<>~]{1,2})

([\[\]\w _\-\.:\\/'\(\)]+)

(\))?

([,;])?
```

`([\[\]\w _\-\.:\\/'\(\)]+)` is the decoded value (after the field and the operator). Adding the `(` and `)` characters could solve this (despite being a more complex regex).

After the change:

```
>>> query_regex=re.compile("(\()?([\w.]+)([=!=<>~]{1,2})([\[\]\w _\-\.:\\/'\(\)]+)(\))?([,;])?")
>>> query_regex.findall('name=Mozilla FIrefox 53.0 (x64 en-US)')
[('', 'name', '=', 'Mozilla FIrefox 53.0 (x64 en-US)', '', '')]
```


While doing more tests to validate this new regex, I have seen that it does not work for queries containing brackets, for instance, **q:** `(log=test,status=outstanding);cis=5.2 Debian Linux,pci_dss=2`

`query_regex.findall(query)` result is:

```
[
('(', 'log', '=', 'test', '', ','), ('', 'status', '=', 'outstanding)', '', ';'), 
('', 'cis', '=', '5.2 Debian Linux', '', ','), 
('', 'pci_dss', '=', '2', '', '')
]
```

As we can see, the second bracket has matched the fourth group (field value).

Investigation in progress, 2 possible solutions: fixing the q to allow brackets and using the filter with a new schema.

**Comment by AlexRuiz7** [comment]
Fixed
