### ISSUE TITLE
Multiple `The index pattern was refreshed successfully` appears when Github module is accessed

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-kibana-app#4091]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 7.x     | 4301-1 | Basic, ODFE, Xpack |

| Browser |
| --- |
| Firefox|

### Description

If the GitHub module is activated but no events have been generated,  multiple `The index pattern was refreshed successfully.` panel appears every time the Github > Dashboard menu is accessed.

### Video

https://user-images.githubusercontent.com/11089305/164712645-2b683690-b067-41d5-961b-75b01527750e.mp4

**Comment by gdiazlo** [comment]
We will work on improving the usability of these pop-up messages.

**Comment by AlexRuiz7** [comment]
Duplicated on #3918
