### ISSUE TITLE
Update `GET /agents/summary/status` response handler

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#4096]
## Description

The response provided by the endpoint `GET /agents/summary/status` has been changed on Wazuh 4.4.
As a result, we need to adjust our code accordingly.

For a full description of the changes, head to the original issue [#12363](https://github.com/wazuh/wazuh/issues/12363).

**Comment by yenienserrano** [comment]
Solve:

- #3874

**Comment by AlexRuiz7** [comment]
Closed, as this is a duplicated of [#1309](https://github.com/wazuh/wazuh-splunk/issues/1309)
