### ISSUE TITLE
TypeError in Management/Rules

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-kibana-app#4105]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 7.x     | 4301-1 | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Firefox|

**Description**
If we search a rule file, we get:
```
Uncaught TypeError: this.inputRef is undefined
```

**Preconditions**
1. Demo environment

**Steps to reproduce**
1. Navigate to Management/Rules
2. Click on Manage rules
3. Search a file

**Comment by gdiazlo** [comment]
Happens 4.2.6.

**Comment by AlexRuiz7** [comment]
Partially fixed on #4125 (workaround)

This issue will stay open until we find a better solution.

**Comment by AlexRuiz7** [comment]
Work continues in #4174
