### ISSUE TITLE
Highlighted characters on API console get obscured

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh-kibana-app#4106]
| Wazuh | Installation procedure
| ----- | ------- | 
| Wazuh Dashboard 4.3.0 | Step by step  |

| Browser |
| ------- |
| Chrome |

**Description**
On the API console, when we highlight characters (to copy an API response for instance), they get completely obscured. This brings a terrible user experience in my opinion.

**Preconditions**
1. Install the Wazuh Dashboard (4.3.0)

**Steps to reproduce**
1. Navigate to `Tools`
2. Click on `API console`
3. Select/highlight characters

**Expected Result**
Characters should be highlighted, but still readable.

**Actual Result**
Characters get completely obscured and the user cannot read what has selected.

**Screenshots**

https://user-images.githubusercontent.com/37274979/165341583-f53c8f4c-9004-470b-b518-a6efe8e58abc.mp4

**Additional context**

Bug found during the manual test for the Wazuh Dashboard on `v4.3.0-RC6`: https://github.com/wazuh/wazuh/issues/13226#issuecomment-1109869994

**Comment by gdiazlo** [comment]
Closed by #4051
