### ISSUE TITLE
Warning when accessing the documentation in the demo environment

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-kibana-app#4107]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 7.x     | 4301-1 | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Firefox|

**Description**
A warning appears if we access the documentation of API Console in demo environment.

**Preconditions**
1. Demo environment

**Steps to reproduce**
1. Navigate to Tools>API Console
2. Click on `?` 

**Actual Result**
1. `Storage access automatically granted for origin “https://documentation.wazuh.com” on “https://demo.wazuh.info”.`

**Screenshots**

https://user-images.githubusercontent.com/80041853/165481176-e85f9c89-db83-4a04-9444-196c8d1766dc.mp4

**Comment by gdiazlo** [comment]
This message is information the browser vendor includes to let developers know of upcoming changes of some behaviours. In this case it is related to https://hacks.mozilla.org/2021/02/introducing-state-partitioning/ and https://hacks.mozilla.org/2022/02/improving-the-storage-access-api-in-firefox/ In other browsers, this might be different.
