### ISSUE TITLE
Only master IP is suggested during agent deployment in a Wazuh cluster

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-kibana-app#4109]
Using the deploy new agent section from the Wazuh WUI, only the Wazuh master address is included even though we have set up a Wazuh cluster with a master and a worker node.

**Describe the solution you'd like**
All the available node IPs in the Wazuh cluster should appear in the IP section.

**Additional context**
It may be difficult to extract the available IPs from the Wazuh WUI as the interface only connects to the master API.

**Comment by AlexRuiz7** [comment]
The nodes' IPs can be obtained from the API, using the `GET /cluster/nodes` endpoint.

**Comment by Machi3mfl** [comment]
### Solution details
- Replace the current `Server Adress` Input with a `Select Input` with Node IPs.
![Selection_088](https://user-images.githubusercontent.com/6089438/197016507-6c2450c2-9175-4bcc-a833-4485f38dd63f.png)
- Get Node IPs from `/cluster/nodes`
- Add the Selected Node IP in the command using the WAZUH_MANAGER parameter

### Considerations (questions)
- What to do when the environment doesn't have cluster enabled
- Could select more than one Node IP or only one.

**Comment by gdiazlo** [comment]
The server address is used to build the agent install command. It generated the variable WAZUH_MANAGER so the agent install command automatically initializes and enrolls the agent into Wazuh.

We documented the variable usage in https://documentation.wazuh.com/current/user-manual/deployment-variables/deployment-variables-windows.html, a user might want to specify multiple IP addresses or FQDNs separated by semicolons.

I think we need to enable a user to select multiple IP addresses.

**Comment by Machi3mfl** [comment]
## New solution Status
![image](https://user-images.githubusercontent.com/6089438/197254408-7005341f-a572-4944-a3dd-2f49485c9251.png)
### Considerations
- Replace free input with node IP suggestions
- Added Combobox to the `Address Server` input to allow users multiple server address (nodes) selections.
- We add the in the `WAZUH_MANAGER` command parameter the node IPs delimiters by a semicolon when the selection is multiple.
### Steps
- [ ] Choose which fields show in the Combobox options (name or IP or both)
- [ ] Choose the description text
- [x] Add testing for the new behavior (component) **In progress...** :reloj_de_arena_en_marcha:

**Comment by Machi3mfl** [comment]
Reponed issue because is related with #4318 
Details in [https://github.com/wazuh/wazuh-kibana-app/issues/4318#issuecomment-1295303570](https://github.com/wazuh/wazuh-kibana-app/issues/4318#issuecomment-1295303570)

**Comment by chantal-kelm** [comment]
According to what we have discussed with the Framework team these are the cases that we are going to take into account:

- In all cases the client can only choose one IP.

- When the client has the IP address set then in the server address field you will see that IP address, and the protocol will be tcp.

- In case the user does not have the IP address set then a selector will be shown in server address where the manager and cluster will be shown, the user can choose one from there or write one.

**Comment by Machi3mfl** [comment]
Issue solved in #4776

**Comment by Machi3mfl** [comment]
Bug found in manual testing fixed in PR https://github.com/wazuh/wazuh-kibana-app/pull/4849
