### ISSUE TITLE
4.3.0 Disable policy monitoring and system auditing dashboards by default in Wazuh Dashboard

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-kibana-app#4113]
Hello team,

I'm opening this issue to consider disabling the `policy monitoring` and `system auditing`.

Policy monitoring has the same utility as SCA (or we explain that in the dashboard). In addition to that, if we click on the dashboard most likely we are going to see **Rootcheck malware detection** alerts as the filter is using the `Rootcheck` group: 
![image](https://user-images.githubusercontent.com/23264276/165705813-541d3f7a-2301-4607-beff-f116059bf635.png)
![image](https://user-images.githubusercontent.com/23264276/165705865-b92ef9a1-615b-4b2a-9ced-5669bd95e4e1.png)

This could be misleading for the users.

The same happens with the `system auditing` as it requires extra step configuration on the server (aside from Wazuh configuration) to get results. The first time you access this one will be empty.

Regards,

Miguel Casares

**Comment by chantal-kelm** [comment]
Legend:

:green_circle:: Enabled
:red_circle:: Disabled

|  | App | Manager | Default App  | 
| --- |  --- | --- | --- | 
| [Open-Scap](https://documentation.wazuh.com/current/user-manual/capabilities/policy-monitoring/openscap/oscap-configuration.html#basic-usage) | :red_circle: | :red_circle: | :red_circle: | 
| [vulnerability-detector](https://github.com/wazuh/wazuh-kibana-app/issues/5044) | :green_circle: | :green_circle: | :green_circle: | 

Security Information Management

|  | Default App  | 
| --- |  --- |
| [Security events](-) | :green_circle: | 
| [Integrity monitoring](-) | :green_circle: | 
| [Office 365]() | :red_circle: | 
| [Amazon AWS](-) | :red_circle: | 
| [Google Cloud Platform](-) | :red_circle: | 
| [GitHub](-) | :red_circle: | 

Auditing and Policy Monitoring

|  | Default App  | 
| --- |  --- |
| [Policy monitoring](-) | :green_circle: | 
| [Security configuration assessment](-) | :green_circle: | 
| [System auditing](-) | :green_circle: | 
| [OpenSCAP](-) | :red_circle: | 
| [CIS-CAT](-) | :red_circle: | 

Threat Detection and Response

|  | Default App  | 
| --- |  --- |
| [Vulnerabilities](-) | :green_circle: | 
| [MITRE ATT&CK](-) | :green_circle: | 
| [VirusTotal](-) | :red_circle: | 
| [Osquery](-) | :red_circle: | 
| [Docker listener](-) | :red_circle: | 

Regulatory Compliance

|  | Default App  | Enabled |
| --- |  --- | --- |
| [PCI DSS](-) | :green_circle: | 
| [NIST 800-53](-) | :green_circle: | 
| [GDPR](-) | :red_circle: | :green_circle: |
| [HIPAA](-) | :red_circle: | :green_circle: |
| [TSC](-) | :red_circle: | :green_circle: |

**Comment by gdiazlo** [comment]
This will be worked on in the future on new issues. We will revisit this when we have a cleaner picture of what we want to achieve.
