### ISSUE TITLE
Prerelease Wazuh-dashboard, Elastic & splunk tests

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#4128]
Test all versions of the app install and work as expected:

* test all environment restart process
* test all versions install and start normally
* test main modules and dashboard work as expected

@matiasmoreno876  / @chantal-kelm 

- [x] wazuh-dashbard 4.3 
- [x] 7.17.3
- [x] 7.17.2
- [x] 7.17.1
- [x] 7.17.0

@Machi3mfl  / @Mayons 

- [x] 7.16.3 (bug found on [comment](https://github.com/wazuh/wazuh-kibana-app/issues/4128#issuecomment-1116337036))
- [x] 7.16.2 (bug found on [comment](https://github.com/wazuh/wazuh-kibana-app/issues/4128#issuecomment-1116337036))
- [x] 7.16.1
- [x] 7.16.0
- [x] 7.10.2

@MauGaP / @mauceballos 

- [x] 8.2.6
- [x] 8.2.5
- [x] 8.2.4
- [x] 8.2.3
- [x] 8.2.2
- [x] 8.2.1
- [x] 8.2.0

@asteriscos / @yenienserrano / @chantal-kelm 
- [x] 8.1.10
- [x] 8.1.9
- [x] 8.1.8
- [x] 8.1.7.2
- [x] 8.1.7.1
- [x] 8.1.7
- [x] 8.1.6
- [x] 8.1.5
- [x] 8.1.4
- [x] 8.1.3
- [x] 8.1.2
- [x] 8.1.1

**Comment by Machi3mfl** [comment]
### Testing 7.16.x and 1.17.x 

### Bug found 
- Wrong responsive in Agents dashboard. Evolution details card exceeded width. This error hide the agents evolutions visualization.

<img width="1438" alt="Screen Shot 2022-05-03 at 11 53 37" src="https://user-images.githubusercontent.com/6089438/166502874-508967d4-93aa-4d42-9929-06909575f710.png">

**Fix PR:** [https://github.com/wazuh/wazuh-kibana-app/pull/4130](https://github.com/wazuh/wazuh-kibana-app/pull/4130)

**Comment by chantal-kelm** [comment]
In 7.17.x the error mentioned by Maxi in the comment above is not seen. Attached image

![Screenshot from 2022-05-03 15-29-53](https://user-images.githubusercontent.com/99441266/166520423-d416ce3b-4d64-4433-b390-a007d2bf8d8d.png)
