### ISSUE TITLE
The agent's name remains in the menu when we change environment

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-kibana-app#4131]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 7.x     | 4301-1 | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Firefox|

**Description**
The agent's name remains in the menu when changing the environment while viewing Security Events.

**Preconditions**
1. Demo environment

**Steps to reproduce**
1. Navigate to Agents
2. Select an agent
3. Go to Security Events>Events
4. Change the environment

**Expected Result**
1. Change the agent name

**Actual Result**
1. The agent's name remains in the menu

**Screenshots**

https://user-images.githubusercontent.com/80041853/166698710-a49d46bb-9691-4252-96cb-9fbb615833af.mp4

**Comment by gdiazlo** [comment]
Being worked on https://github.com/wazuh/wazuh-kibana-app/issues/4035
