### ISSUE TITLE
we need to include the Cypress tags on the automation test

### ISSUE THREAD

**Issue by mauceballos** [wazuh/wazuh-kibana-app#4139]
**Describe the solution**
We need to include the cypress tags to run specific test cases for each execution

**Comment by mauceballos** [comment]
command run :
`npx cypress-tags run -e TAGS='@about'`

**Comment by mauceballos** [comment]
I share the [PR](https://github.com/MauGaP/wazuh-cypress/pull/1l)

**Comment by Mayons95** [comment]
PR Approved. I proceed to close this Issue
CC: @MauGaP @mauceballos @gdiazlo
