### ISSUE TITLE
Vulnerabilities summary dashboard

### ISSUE THREAD

**Issue by phanikumar944** [wazuh/wazuh-kibana-app#4140]
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by twilliams-sift** [comment]
Reading through the slack channel I can understand the issue with vulnerabilities being reported multiple times, but I'm just gonna throw another voice in here saying that it'd be great to have this implemented.

**Comment by AlexRuiz7** [comment]
This issue will be tracked in https://github.com/wazuh/wazuh-kibana-app/issues/4431

Closing this as it's duplicated
