### ISSUE TITLE
QA - Automation Task - Github Actions

### ISSUE THREAD

**Issue by mauceballos** [wazuh/wazuh-kibana-app#4147]
After build a github action based on the issue https://github.com/wazuh/wazuh-kibana-app/issues/4031 we perform some executions, discovering some issues related with the use of memory of the browser by cypress (for more information please visit the following issue: https://github.com/wazuh-fe-qa/wazuh-cypress/issues/30 ).
To solved this problem we define some task to perfom:

1. Edit cypress settings from value: `"numTestsKeptInMemory": 0,`
2. Changes features definition to use backgrounds
example: 

```
Feature: Validate that the pinned filter label is displayed

  As a Wazuh user
  I want to set a new filter from the agent page
  in order to manage them
  Background:
    Given The admin user is logged in using xpack
    And The user navigates to the agent page
    And The user navigates to the agent dashboard
    And The user navigates to agentModule <Module Name>
    And The user moves to events page
    And The user adds a new filter
    And The user pins a filter
    And The user navigates to the agent page
    And The user navigates to the agent dashboard

  @filter
  Scenario Outline: The user add and pin filter - Check across the modules - from event page
    When is navigates to agentModule <Module Name>
    Then The user checks if the filter is displayed
    Examples:
      | Module Name          |
      | Security Events      |
      | Integrity Monitoring |
      | System Auditing      |
      | Vulnerabilities      |
      | Mitre & Attack       |
      | GDPR                 |
      | HIPAA                |
      | NIST                 |
      | TSC                  |
      | Policy Monitoring    |
      | PCIDSS               |
```

3. To improve the performance of our test we need to avoid use long css and xpath selector, so we need to add some data-test atributes for a list of components in our app.
4. To improve and take an advantaje of the github action, we decided to implement some labels to run some specific tests depends of which test label is called.
5. Finally, we are going to make new suite of test cases to perform a smoke test execution with the goal to test a long amount of packages in different versions of Kibana or OpenSearch, Wazuh Dashboard, etc.

**Comment by Mayons95** [comment]
Related with 4031
