### ISSUE TITLE
Visual Testing, Analysis and research

### ISSUE THREAD

**Issue by mauceballos** [wazuh/wazuh-kibana-app#4165]
We analyze with @mauceballos differents tools for visual testing.
We decided to continue working with a tool that @MauGaP recommended to us. This tool is Micoo.

We choose Micoo because it's simple to be easy to use, and we have already the folder structure to implement readily in our repo.
Visual testing it's going to be used to test some static pages that should not change over time.
It's going to be used only to test UI components and not to test any functionality.

**Comment by mauceballos** [comment]
This task is to Analysis and research to Include the visual testing on the cypress project.

**Comment by mauceballos** [comment]
After doing research I found the next information:

_"Visual testing is used to examine what happened at the point of software failure by defining the data in such a way that the developer can quickly identify the reason of failure, and the information is expressed clearly so that any other developer can utilize this information.
The general meaning of visual is optical means what we can see. Therefore, visual testing requires the video recording of the entire process. It captures everything that happens at the time of system testing in video format. Tester gives a picture in a picture webcam and audio commentary from microphones as an input value."_


**Advantages of Visual Testing**

- Visual testing is cheap because information is recorded in video form. So, we don't need to replicate the information in any other form. It saves money.
- Visual testing provides portability. A tester can provide video to any other tester if the type of software is same. So, in the case of system failure, we don't loss the data.
- Visual testing saves the time of testing as if once the testing process is done and saved in visual form so, we do not need to test software again. Developer can identify the defect by seeing the video.
- Visual testing requires the minimum number of special skills.
- Visual testing requires minimum part preparation because there is a need to find only the reason for system failure.

**Disadvantages of Visual Testing:**

- Visual testing is suitable only for the surface which can be visible so, need to arrange suitable surface.
- Visual testing cannot detect hidden defects; it can detect only larger defects.
- To record clear visible video lighting must be well implemented.
- It follows only rules does not emulate human inspections.
- Scratches and cracks can create misinterpretation.
- Visual testing does not provide component variations on the product if there is variation in software components it cannot be tested via visual testing.

> Ref:

- > https://www.javatpoint.com/visual-testing
- > https://docs.cypress.io/guides/tooling/visual-testing


**Conclusion**:

We believe that it would be useful to implement visual testing for certain specific test cases with which we should build a test suite, specific to run with visual testing.
which does not mean that we should stop developing, executing and maintaining functional test cases.
Firstly, we should identify and analyze which are the scenarios that we should develop and include in the visual testing suite and what effort it would take us to implement said strategy.

**Comment by mauceballos** [comment]
implementation:

installation of "cypress-plugin-snapshots" in the repository for frontend tests, to start tests on the environment.

```
npm install cypress-image-snapshot
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: wazuh-kibana-app-automation@1.0.0
npm ERR! Found: cypress@9.7.0
npm ERR! node_modules/cypress
npm ERR!   dev cypress@"^9.7.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer cypress@"^4.5.0" from cypress-image-snapshot@4.0.1
npm ERR! node_modules/cypress-image-snapshot
npm ERR!   cypress-image-snapshot@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/mauri/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mauri/.npm/_logs/2022-05-27T11_19_03_490Z-debug-0.log

```

The Cypress version supported for visual testing plugin installation is "cypress": "^4.5.0".
We are currently using the lasted version "cypress": "^9.7.0".

_To perform a preliminary test we should create a new visual testing repo._

**Comment by mauceballos** [comment]
According to the last meeting with the QA team and together with what was discussed in the team, the imementation of Resemble JS will begin

[Resemble](https://rsmbl.github.io/Resemble.js/)

**Comment by mauceballos** [comment]
we **continue** the research on Visual Testing. We will analyze and implement **MICOO** for the **Wazuh App** testing repo.

<details>

![Screenshot from 2022-08-10 10-18-11](https://user-images.githubusercontent.com/76791841/183912525-e0b65671-42b3-439c-82ef-dfd04028fa26.png)

![Screenshot from 2022-08-10 10-18-28](https://user-images.githubusercontent.com/76791841/183912520-e98cf22e-bfbd-4d33-aa4e-7aa8cc9e6453.png)

</details>

**Comment by Mayons95** [comment]
We decided to close this issue since the objective of it was to relieve the research task of the tool to perform visual test.
