### ISSUE TITLE
Add support for Kibana 7.17.4

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#4194]
We need to support all minor versions of Elastic stack 7.17.X.

This version solves a CVE in elastic stack by updating the JVM version as per https://discuss.elastic.co/t/elastic-stack-7-17-4-and-8-2-1-security-update/305530

We need to review the change log of the release https://www.elastic.co/guide/en/elasticsearch/reference/7.17/release-notes-7.17.4.html

**Comment by nconder** [comment]
7.17.4 did break the site for me. 
kibana "version": "7.17.4",
WAZUH_VERSION="v4.3.3"

**Comment by Desvelao** [comment]
Hi @nconder ,

The error is related to that you have installed a Wazuh plugin that is not compatible with Kibana 7.17.4. Maybe you had Kibana in a lower version working with a compatbile Wazuh plugin and you upgraded to Kibana 7.17.4. Take in account that if you upgrade Kibana, you need to install the compatible Wazuh plugin for that Kibana version. Currently, we don't have any published package for Kibana 7.17.4. You can see the compatibility of Wazuh plugin and Kibana versions in https://github.com/wazuh/wazuh-kibana-app/wiki/Compatibility#wazuh---kibana---open-distro-for-elasticsearch-version-compatibility-matrix.

In this issue, we want to give support for Kibana 7.17.4.

**Comment by nconder** [comment]
> Hi @nconder ,
> 
> The error is related to that you have installed a Wazuh plugin that is not compatible with Kibana 7.17.4. Maybe you had Kibana in a lower version working with a compatbile Wazuh plugin and you upgraded to Kibana 7.17.4. Take in account that if you upgrade Kibana, you need to install the compatible Wazuh plugin for that Kibana version. Currently, we don't have any published package for Kibana 7.17.4. You can see the compatibility of Wazuh plugin and Kibana versions in https://github.com/wazuh/wazuh-kibana-app/wiki/Compatibility#wazuh---kibana---open-distro-for-elasticsearch-version-compatibility-matrix.
> 
> In this issue, we want to give support for Kibana 7.17.4.

Hi @Desvelao thank you, I am aware of this incompatibility. Do you have an estimated adoption timeline to support minor Kibana versions? I need to decide if I should try to somehow role this change back, wait it out, or rebuild.
