### ISSUE TITLE
Kibana 7.16.x 7.17.x agents tooltip background

### ISSUE THREAD

**Issue by yenienserrano** [wazuh/wazuh-kibana-app#4201]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3.4   | 7.16.x 7.17.x

**Description**
The agent status graph tooltip appears without background when the cursor is placed on top of it

**Steps to reproduce**
1. Navigate to Agents
2. Hover in status chart

**Expected Result**
![image](https://user-images.githubusercontent.com/63758389/171904222-408e6ecc-bb6e-458e-8b44-c95cfbe0258f.png)

**Actual Result**
![image (1)](https://user-images.githubusercontent.com/63758389/171904285-234d8731-6124-4e11-af81-9f746db0b8f2.png)

**Screenshots**

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by Desvelao** [comment]
Solved in https://github.com/wazuh/wazuh-kibana-app/pull/4198.

# Changes
- Added `echTooltip` class and adapted the HTML structure to the styles are applied. The `echTooltip` is defined by the plugin platform.
