### ISSUE TITLE
Update agent installation command for all agents

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#4204]
**Describe the solution you'd like**

We need to revise all agents command. For example, debian does not come with `curl `installed by default, we need to change it to use `wget ` instead, as this command comes by default.

For example: 

`wget https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.3.3-1_amd64.deb -O wazuh-agent-4.3.3.deb && sudo WAZUH_MANAGER='pvcga636385p.cloud.wazuh.com' WAZUH_REGISTRATION_PASSWORD='F7y8JwV9XOq8NiqY1WPeoIqqoT8nxZtx' WAZUH_AGENT_GROUP='default' dpkg -i ./wazuh-agent-4.3.3.deb`

 @wazuh/cicd team will devise the exact command we need to tell the user in the agent installation wizard, and @wazuh/frontend will update the UI to reflect the changes appropriately.

Related issues:

 - #4178

**Comment by okynos** [comment]
Research made here -> https://github.com/wazuh/wazuh-packages/issues/1625

**Comment by chantal-kelm** [comment]
**Added:**
Operating systems,
Versions, 
Architectures, 
Commands of Install and enroll the agent y 
Commands to Start the agent.
The unit tests are being worked on.

This issue is being resolved together with this other issue https://github.com/wazuh/wazuh-kibana-app/issues/4178 in the same PR. 

For this PR to close, we are waiting to receive the instructions to show when the user clicks on a deprecated operating system.

**Comment by chantal-kelm** [comment]
This is how the 'Deploy a new agent' section looks like now, while the issue is still blocked by https://github.com/wazuh/wazuh-documentation/issues/5561.


https://user-images.githubusercontent.com/99441266/189145948-4605c982-6fcc-4756-bfae-b05b47b3aed4.mp4

**Comment by chantal-kelm** [comment]
After the update of the information that yesterday did the ci cd team, today I finished the development and this is how it looks:

https://user-images.githubusercontent.com/99441266/189947396-4652d1f4-c0d5-4567-9add-e0688aa17962.mp4

**Comment by chantal-kelm** [comment]
Today, @okynos updated me on the information:

Amazon Linux 1 es un fork (Derivado) de CentOS 6
Amazon Linux 2 es un fork de CentOS 7
Amazon Linux 2022 es algo parecido a RHEL 9
RedHat y Oracle linux son lo mismo practicamente que CentOS
RedHat 6 es como CentOS 6
Oracle Linux 6 lo mismo

**Comment by chantal-kelm** [comment]
This is what the 'Deploy new agent' section looks like.

https://user-images.githubusercontent.com/99441266/194108984-9bdf8c60-589d-4f6b-9e91-131db1bc9ebb.mp4

**Comment by chantal-kelm** [comment]
Today a small message has been added with a link to documentation for AIX, HP-UX and Solaris OS. This is how it looks like:

https://user-images.githubusercontent.com/99441266/194386947-999a35fb-9fba-4dd0-ab5a-9751e008802c.mp4

**Comment by Machi3mfl** [comment]
## Status
- [ ] Order the OS buttons in the Deploy new Agent steps. Solved in [commit](https://github.com/wazuh/wazuh-kibana-app/pull/4647/commits/c464416926d8fbdabf6884419dd00aacb6e6e889)

**Comment by chantal-kelm** [comment]
Added links for these OS:

AIX 6.1 TL9+
HP-UX 11.31+
Solaris 10u11 SPARC
Solaris 11.3+ SPARC
CentOS 5.11
Debian 7+

 and removed messages and links for these:

CentOS 5 and 6
RedHat 5 and 6
Debian 7, 8 and 9
ubuntu 14
Windows XP, Vista, 2008, 7
