### ISSUE TITLE
Management and Settings -> logs page: the load button appears half hidden

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#4206]
**Describe the solution you'd like**
When navigating with safari browser to Management -> Logs, the default style shows the page as follows: 

![image](https://user-images.githubusercontent.com/2181918/172043181-bf967af6-f2f7-4f45-8f43-5a981e24a79d.png)

We need to redesign this so:
* the load more events button appears at the end of the page, and it is visible, without scrolling 
* if we load more events, the button does not move. Instead, the text area showing the logs increases its contents, and the scrollbar takes care of the log's movement.
* in a responsive environment, we use the same behavior

**Comment by Machi3mfl** [comment]
### For testing

1. Go to `Management > Logs`
2. Check that `"Load more logs"` appears without being cut off.
3. Try point 2 with different browser resolutions.
