### ISSUE TITLE
Could not connect to API id [default]: 3099 - ERROR3099 - Wazuh not ready yet ||| Could not connect to API id [wazuhapi]: 3099 - ERROR3099 - Invalid credentials

### ISSUE THREAD

**Issue by Maverick-07** [wazuh/wazuh-kibana-app#4208]
Having the above errors while opening the wazuh manager Please help me

![image](https://user-images.githubusercontent.com/54700990/172044576-9e937fa6-6b40-4c6a-b0e0-e823fe473db6.png)
![image](https://user-images.githubusercontent.com/54700990/172044594-580b5f05-54ad-4491-b87c-8f753445e5f7.png)

**Comment by gdiazlo** [comment]
The error state the credentials to access the API are invalid. How did you install Wazuh? Did you use the[ official documentation guides](https://documentation.wazuh.com/current/installation-guide/index.html), [the installation assistant](https://documentation.wazuh.com/current/quickstart.html#installing-wazuh) or the [step-by-step guide](https://documentation.wazuh.com/current/installation-guide/wazuh-server/step-by-step.html)? 
Did you change the default configuration? Can you check the API following [this documentation](https://documentation.wazuh.com/current/user-manual/api/getting-started.html)?

**Comment by iceman3k** [comment]
I am also getting the above error for any modification to the ossec.conf file. 
Here is the addition I am trying to add so far, a Syslog listener, and a call script to grab office 365 data:
`<remote>
  <connection>syslog</connection>
  <port>514</port>
  <protocol>tcp</protocol>
  <allowed-ips>10.0.0.0/8</allowed-ips>
  <local_ip>10.2.0.18</local_ip>
</remote>

<remote>
  <connection>secure</connection>
  <port>1514</port>
  <protocol>tcp,udp</protocol>
  <queue_size>16384</queue_size>
  <rids_closing_time>5m</rids_closing_time>
</remote>

<wodle name="command">
  <disabled>no</disabled>
  <command>/var/ossec/etc/scripts/office_365.py --contentType Audit.Exchange Audit.SharePoint DLP.All Audit.General Audit.AzureActiveDire>
  <interval>24h</interval>
  <ignore_output>yes</ignore_output>
  <run_on_start>yes</run_on_start>
  <timeout>0</timeout>
</wodle>
`

Here are the guides:
https://wazuh.com/blog/monitor-office-365-with-wazuh/
https://documentation.wazuh.com/current/user-manual/capabilities/log-data-collection/how-it-works.html#remote-syslog

**Comment by iceman3k** [comment]
I am also getting the above error for any modification to the ossec.conf file with the provided script for office365.
Here is the addition I am trying to add so far:
```
<wodle name="command">
  <disabled>no</disabled>
  <command>/var/ossec/etc/scripts/office_365.py --contentType Audit.Exchange Audit.SharePoint DLP.All Audit.General Audit.AzureActiveDirectory --hours 24 --tenantId #### --clientId #### --clientSecret ####</command>
  <interval>24h</interval>
  <ignore_output>yes</ignore_output>
  <run_on_start>yes</run_on_start>
  <timeout>0</timeout>
</wodle>
```
Here is the guide:
https://wazuh.com/blog/monitor-office-365-with-wazuh/

**Comment by matiasmoreno876** [comment]
Hello,
Thank you for using Wazuh!
Could you please confirm what Wazuh version and Elastic Stack are you using?
On the other hand, please check the following things:
Check all the services are running:
`systemctl status wazuh-manager`  (In the wazuh server)
`systemctl status filebeat`  (In the wazuh server)
`systemctl status elastisearch` (In the Elasticsearchserver)
`systemctl status kibana`  (In the kibana server)
Check that you haven’t ran out of space on the Wazuh manager and` Elasticsearch`.
Check the file `/usr/share/kibana/data/wazuh/config/wazuh.yml` has the contents similar to this:
```
hosts:
  - default:
     url: https://<your wazuh server ip or localhost if is an all in one>
     port: 55000
     username: wazuh-wui
     password: wazuh-wui
     run_as: false
```

Aditionally you can do this:
Stop the Kibana service : `systemctl stop kibana`
Remove wazuh-registry.json file : `rm /usr/share/kibana/data/wazuh/config/wazuh-registry.json`
Restart the Kibana service so the file will be re-created : `systemctl restart kibana`
Remove the browser cache (cookies, local storage, etc...)
Try to access Kibana again
Let me know if this is helpful and of any details,
Cheers,
Matias From Wazuh team.

**Comment by AlexRuiz7** [comment]
Closed due to inactivity.
