### ISSUE TITLE
Redesign of add agent page--page bottom text

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#4210]
**Describe the solution you'd like**

Update the selected phrase from the next screenshot to use "Wazuh server" instead of Manager.

![image](https://user-images.githubusercontent.com/2181918/172042832-be6dfdad-b65c-42cc-8d43-ba5effe6d074.png)

Related issues:
* #4205

**Comment by yenienserrano** [comment]
Solve:

- #4239
