### ISSUE TITLE
Reporting option

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-kibana-app#422]
Hello team

  To have an option of creating reports could be an awesome feature. It's very useful in the most of environments and it's a feature requested. 

Best regards, 
Alberto R.

**Comment by alberpilot** [comment]
Hi @havidarou 

  It's not the same. I talk about a report with graphics, data, all in one single report sent by email in html format (example). 
  E.g: I design a dashboard with all Wazuh visualizations I like and with some additional visualizations I did. I would like to have all this data into html (or similar format) sent daily by email to me and to people who I want to report. 

If you have any doubt, please let me know. 
Thanks!
Cheers, 
Alberto R.

**Comment by jesusgn90** [comment]
Hello again team, a first approach has been implemented here https://github.com/wazuh/wazuh-kibana-app/pull/510. This issue should be still opened cause the task is not fully completed. We need to add data from the Wazuh API, implement a background reporting proccess, mail options, etc.

Regards,
Jesús
