### ISSUE TITLE
Security events dashboard is empty 

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh-kibana-app#4220]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3.4   | 7.x     | 40316 | - |

| Browser |
| ------- |
| Chrome, Firefox|

**Description**

During the manual tests for `4.3.4` release (https://github.com/wazuh/wazuh/issues/13693), it was found that after a step-by-step installation of the Wazuh stack (Manager-Indexer-Dashboard) the corresponding dashboard of the `Security Events` tab is empty. It was confirmed that there are events.

**Steps to reproduce**
1. Install Wazuh Dashboard step-by-step
2. Register an agent and generate some alerts
3. Go to the `Security Events` tab, you'll find all the alerts listed in the table but all the graphs are empty

**Expected Result**
 We expected to see the events plotted
![screenshot-01-Wazuh-Security-Analytics1](https://user-images.githubusercontent.com/65046601/172244665-34c439af-8801-4f6c-b8b4-1462eab20834.png)

**Actual Result**
The Dashboard is empty
![dashboard_empty](https://user-images.githubusercontent.com/65046601/172244362-d5bc4a2f-7b05-4eeb-9142-2b1aaeb46d85.png)

**Additional context**
The issue was reproduced in several environments. Some of them updated the default credentials, some of them not.

<details>
<summary>Snapshots</summary>

![miguel_1](https://user-images.githubusercontent.com/65046601/172245366-5ddea0fa-049f-44ed-81a0-e577c3d460ff.png)
![miguel_2](https://user-images.githubusercontent.com/65046601/172245385-182f4409-7b8c-4616-ae70-07dcfe193cc2.png)
</details>

- Manager CentOS 8. Firefox 101.0. OS Arch

<details>
<summary>Snapshots</summary>

![hanes_1](https://user-images.githubusercontent.com/65046601/172245869-dd6d8a40-790f-4297-bec4-e422c14d97e9.png)
![hanes_2](https://user-images.githubusercontent.com/65046601/172245887-6eca899f-9858-4cd7-9493-c45271d0ae81.png)
</details>

- Manager Ubuntu 22. Firefox 91.10.0esr. OS Debian

<details>
<summary>Snapshots</summary>

![chromium](https://user-images.githubusercontent.com/65046601/172246200-cf287f70-b371-4c96-8901-6bca56ed4de6.png)
</details>

- Manager CentOS 7. Chromium Versión 101.0.4951.64. OS Manjaro

**Comment by gdiazlo** [comment]
Related issue:
* #4221

**Comment by davidjiglesias** [comment]
Fixed in: https://github.com/wazuh/wazuh-kibana-app/issues/4199

We had an error introduced that was causing the visualizations not to load in any of the App panels.
The issue above is supposed to fix this error, we will close this one when we double-check that everything is working correctly

Thanks for reporting.

**Comment by gdiazlo** [comment]
After the PR the dashboard shows as it should.

![image](https://user-images.githubusercontent.com/2181918/172656462-7ce4acb9-14c2-4324-a58e-1a62c79086bc.png)
