### ISSUE TITLE
Content security policy and 401 errors when login and logout  the UI

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-kibana-app#4221]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3.4  | 7.x     | 4305 | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox|

**Description**
Console errors in the DEMO environment UI.

**Steps to reproduce**
1. Login into Wazuh UI
2. Navigate through the UI
3. Logout

**Expected Result**
1. I expect not to see errors in the  console

**Actual Result**
1.  I see some errors in the console:
    * Content security policy error
    *  401 errors

https://user-images.githubusercontent.com/26927338/172249488-6c450e85-eba9-4c85-a064-06111a44f163.mp4

**Comment by gdiazlo** [comment]
Related issue:
* #4220

**Comment by snaow** [comment]
Fixed in: https://github.com/wazuh/wazuh-kibana-app/issues/4199

We had an error introduced that was causing the visualizations not to load in any of the App panels. 
The issue above is supposed to fix this error, we will close this one when we double-check that everything is working correctly

Thanks for reporting.

**Comment by AlexRuiz7** [comment]
The first error message is expected and generated by the platform, not us. In fact, it's informed that a single error message is expected on the log directly next to the first error.

On the other hand, once the PR was merged, the dashboard shows as it should, and the `Type was not set` error no longer shows up.

![image](https://user-images.githubusercontent.com/2181918/172656462-7ce4acb9-14c2-4324-a58e-1a62c79086bc.png)
