### ISSUE TITLE
Release 4.3.4 RC1 - Wazuh UI Manual Testing 

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#4223]
Wazuh v4.3.4 - Kibana 7.10.2, 7.16.x, 7.17.x - Revision 4305

## Added

Added the pending agent status to some sections that were missing:
* #4166 
* #4188

## Tests for #4166

Test 0: Validate the pages:

-  Agents
-  Modules/SCA
- Modules Directory
- Management/Status
- Agent Selector
- Group's Agent

and validate the new UI.

### Agents

- **Test 1:** Status visualization:

Click on the legend's labels, adding a filter to the search bar
Include the Pending status

- **Test 2**: Details panels:

Click on the agent status stat, adding a filter to the search bar
Include the Pending status

- **Test 3**: Evolution visualization:

status colors are equals to the other panels

- **Test 4**: Search bar

status suggestion includes pending status

### Agent selector

- **Test 5:** status suggestion includes pending status
- **Test 6:** status column displays the status indicator and the label.
- **Test 7**: If there is a selected agent, it displays the status indicator and the agent name (ID) as a label.

### Management/Groups/
- **Test 8**: (in group) Search bar: status suggestion includes pending status

### Modules directory
- **Test 9**: Display the agent count by status, including pending state

### Management/Status

- **Test 10**: Display the agent count by status, including pending state
- **Test 11:** Display the agent status using the labels.
- **Test 12:** The agent count should display as expected when loading the first time or change the manager using the manager node selector for a cluster mode

Reviewing the files changed, access to the sections, and using an agent with status same of change, see that is working as expected.

#### Modules/File integrity monitoring/Inventory

- **Test 13**: active: display the data
- **Test 14:** not active: display a prompt related to the agent status

### Modules/SCA/Inventory

- **Test 15**: never_connected: prompt with a message related to the agent status
- **Test 16**: not never_connected: display the data

### Agent/Stats:

- **Test 17:** active: display the data
- **Test 18**: not active: display a prompt related to the agent status

### Agent/Inventory

- **Test 19:** active: display the data
- **Test 20**: disconnected: display a prompt related to the agent status
- **Test 21**: never_connected: display a prompt related to the agent status

### Agent/Overview:

- **Test 22**: never_connected: display a prompt related to the agent status
- **Test 23**: no never_connected: display the data

### Agents Table

- **Test 24:** not never_connected: not display the button to open the agent configuration
- **Test 25:** Status column is rendered with an indicator that depends on the agent status and a label without _ character
- **Test 26**: For window width < 1200, only display the indicator and not the status label

### Agent/Configuration

- **Test 27:** active: display the section
- **Test 28**: never_connected: display a prompt related to the agent status

### <Module> - Generate a report in PDF

- **Test 29**: not active: display a message with the current state of the agent.
- **Test 30**: The order of agent status are: active, disconnected, pending, never_connected

## Changed

- Replaced the visualization of Status panel in Agents 
  - covered by prior tests
- Replaced the visualization of policy in Modules/Security configuration assessment/Inventory
  -- covered by prior tests
- Consistency in the colors and labels used for the agent status #4166 #4199
  - covered by prior tests
- Replaced how the full and partial scan dates are displayed in the Details panel of Vulnerabilities/Inventory 
  -  **Test 31**: Generate vulnerabilities for an agent and go to Vulnerabilities/Inventory and see the Details` panel, the dates should be rendered as expected

## Fixed
- Fixed that the platform visualizations didn't use some definitions related to the UI on Kibana 7.10.2 #4166
  - covered by prior tests
- Fixed a toast message with a successful process appeared when removing an agent of a group in Management/Groups and the agent appears in the agent list after refreshing the table #4167
  - **Test 32**: Remove an agent of a group in Management/Groups/<Group>/Manage agents. The toast message should appear after the Wazuh API request is done.
- Fixed import of an empty rule or decoder file #4176
  - **Test 33:** Navigate to Management/rules or decoders, Try uploading an empty file, See the warning
- Fixed overwriting of rule and decoder imports #4180
  - **Test 34:** Go to "Management/Rules or Decoders", Click on "Manage rules files" or "Manage decoders files", Click on "Import files", import files with or without the overwrite option

|Test      | Chrome | Safari | Firefox  | Package |
| -- | -- | -- | -- | -- |
| Test 1   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    🟢 /🔴        |
 
Status legend:
⚫ - None
🔴 - Rejected
🟢 - Approved

In the case of 🔴, create and link the issue.

**Comment by yenienserrano** [comment]
Wazuh Dashboard - In Progress

|Test      | Chrome | Safari | Firefox  | Package |
| -- | -- | -- | -- | -- |
| Test 1   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    wazuh-4.3.4-1.zip        |
| Test 2   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    wazuh-4.3.4-1.zip        |
| Test 3   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    wazuh-4.3.4-1.zip        |
| Test 4   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    wazuh-4.3.4-1.zip        |
| Test 5   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    wazuh-4.3.4-1.zip        |
| Test 6   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    wazuh-4.3.4-1.zip        |
| Test 7   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    wazuh-4.3.4-1.zip        |
| Test 8   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    wazuh-4.3.4-1.zip        |
| Test 9   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    wazuh-4.3.4-1.zip        |
| Test 10   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    wazuh-4.3.4-1.zip        |
| Test 11   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    wazuh-4.3.4-1.zip        |
| Test 12   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    wazuh-4.3.4-1.zip        |
| Test 13   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |   wazuh-4.3.4-1.zip       |
| Test 14   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    wazuh-4.3.4-1.zip       |
| Test 15   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    wazuh-4.3.4-1.zip        |
| Test 16   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    wazuh-4.3.4-1.zip        |
| Test 17   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    wazuh-4.3.4-1.zip        |
| Test 18   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    wazuh-4.3.4-1.zip       |
| Test 19   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    wazuh-4.3.4-1.zip        |
| Test 20   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    wazuh-4.3.4-1.zip        |
| Test 21   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    wazuh-4.3.4-1.zip       |
| Test 22   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    wazuh-4.3.4-1.zip        |
| Test 23   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    wazuh-4.3.4-1.zip        |
| Test 24   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    wazuh-4.3.4-1.zip       |
| Test 25   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    wazuh-4.3.4-1.zip        |
| Test 26   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    wazuh-4.3.4-1.zip        |
| Test 27   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    wazuh-4.3.4-1.zip        |
| Test 28   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    wazuh-4.3.4-1.zip        |
| Test 29   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |   wazuh-4.3.4-1.zip        |
| Test 30   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    wazuh-4.3.4-1.zip        |

**Comment by asteriscos** [comment]
Wazuh Dashboard - In Progress

|Test      | Chrome | Safari | Firefox  | Package |
| -- | -- | -- | -- | -- |
| Test 1   |     🟢     |     :black_circle:    |       🟢     |    wazuh_kibana-4.3.4_7.17.0-1.zip        |
| Test 2   |     🟢     |     :black_circle:    |       🟢     |    wazuh_kibana-4.3.4_7.17.0-1.zip        |
| Test 3   |     🟢     |     :black_circle:    |       🟢     |    wazuh_kibana-4.3.4_7.17.0-1.zip        |
| Test 4   |     🟢     |     :black_circle:    |       🟢     |    wazuh_kibana-4.3.4_7.17.0-1.zip        |
| Test 5   |     🟢     |     :black_circle:    |       🟢     |    wazuh_kibana-4.3.4_7.17.0-1.zip        |
| Test 6   |     🟢     |     :black_circle:    |       🟢     |    wazuh_kibana-4.3.4_7.17.0-1.zip        |
| Test 7   |     🟢     |     :black_circle:    |       🟢     |    wazuh_kibana-4.3.4_7.17.0-1.zip        |
| Test 8   |     🟢     |     :black_circle:    |       🟢     |    wazuh_kibana-4.3.4_7.17.0-1.zip        |
| Test 9   |     🟢     |     :black_circle:   |       🟢     |    wazuh_kibana-4.3.4_7.17.0-1.zip        |
| Test 10   |     🟢     |     :black_circle:   |       🟢     |    wazuh_kibana-4.3.4_7.17.0-1.zip        |
| Test 11   |     🟢     |     :black_circle:   |       🟢     |    wazuh_kibana-4.3.4_7.17.0-1.zip        |
| Test 12   |     🟢     |     :black_circle:   |       🟢     |    wazuh_kibana-4.3.4_7.17.0-1.zip        |
| Test 13   |     🟢     |     :black_circle:   |       🟢     |   wazuh_kibana-4.3.4_7.17.0-1.zip       |
| Test 14   |     🟢     |     :black_circle:   |       🟢     |    wazuh_kibana-4.3.4_7.17.0-1.zip       |
| Test 15   |     🟢     |     :black_circle:   |       🟢     |    wazuh_kibana-4.3.4_7.17.0-1.zip        |
| Test 16   |     🟢     |     :black_circle:   |       🟢     |    wazuh_kibana-4.3.4_7.17.0-1.zip        |
| Test 17   |     🟢     |     :black_circle:   |       🟢    |    wazuh_kibana-4.3.4_7.17.0-1.zip        |
| Test 18   |     🟢     |     :black_circle:   |       🟢    |    wazuh_kibana-4.3.4_7.17.0-1.zip       |
| Test 19   |     🟢     |     :black_circle:   |       🟢    |    wazuh_kibana-4.3.4_7.17.0-1.zip        |
| Test 20   |     🟢     |     :black_circle:   |       🟢    |    wazuh_kibana-4.3.4_7.17.0-1.zip        |
| Test 21   |     🟢     |     :black_circle:   |       🟢    |    wazuh_kibana-4.3.4_7.17.0-1.zip       |
| Test 22   |     🟢     |     :black_circle:   |       🟢    |    wazuh_kibana-4.3.4_7.17.0-1.zip        |
| Test 23   |     🟢     |     :black_circle:   |       🟢    |    wazuh_kibana-4.3.4_7.17.0-1.zip        |
| Test 24   |     🟢     |     :black_circle:   |       🟢    |    wazuh_kibana-4.3.4_7.17.0-1.zip       |
| Test 25   |     🟢     |     :black_circle:   |       🟢    |    wazuh_kibana-4.3.4_7.17.0-1.zip        |
| Test 26   |     🟢     |     :black_circle:   |       🟢    |    wazuh_kibana-4.3.4_7.17.0-1.zip        |
| Test 27   |     🟢     |     :black_circle:   |       🟢    |    wazuh_kibana-4.3.4_7.17.0-1.zip        |
| Test 28   |     🟢     |     :black_circle:   |       🟢    |    wazuh_kibana-4.3.4_7.17.0-1.zip        |
| Test 29   |     🟢     |     :black_circle:   |       🟢    |   wazuh_kibana-4.3.4_7.17.0-1.zip        |
| Test 30   |     🟢     |     :black_circle:   |       🟢    |    wazuh_kibana-4.3.4_7.17.0-1.zip        |

**Comment by Mayons95** [comment]
Wazuh Kibana App - Kibana 7.16.2 - In progress

|Test      | Chrome | Safari | Firefox  | Package |
| -- | -- | -- | -- | -- |
| Test 1   |     🟢     |     :black_circle:    |       🟢     |    wazuh_kibana-4.3.4_7.16.2-1.zip        |
| Test 2   |     🟢     |     :black_circle:    |       🟢     |    wazuh_kibana-4.3.4_7.16.2-1.zip        |        
| Test 3   |     🟢     |     :black_circle:    |       🟢     |    wazuh_kibana-4.3.4_7.16.2-1.zip        |       
| Test 4   |     🟢     |     :black_circle:    |       🟢     |    wazuh_kibana-4.3.4_7.16.2-1.zip        |      
| Test 5   |     🟢     |     :black_circle:    |       🟢     |    wazuh_kibana-4.3.4_7.16.2-1.zip        |
| Test 6   |     🟢     |     :black_circle:    |       🟢     |    wazuh_kibana-4.3.4_7.16.2-1.zip        |
| Test 7   |     🟢     |     :black_circle:    |       🟢     |   wazuh_kibana-4.3.4_7.16.2-1.zip       |
| Test 8   |     🟢     |     :black_circle:    |       🟢     |    wazuh_kibana-4.3.4_7.16.2-1.zip       |
| Test 9   |     🟢     |     :black_circle:   |       🟢     |    wazuh_kibana-4.3.4_7.16.2-1.zip       |
| Test 10   |     🟢     |     :black_circle:   |       🟢     |   wazuh_kibana-4.3.4_7.16.2-1.zip       |
| Test 11   |     🟢     |     :black_circle:   |       🟢     |    wazuh_kibana-4.3.4_7.16.2-1.zip        |
| Test 12   |     🟢     |     :black_circle:   |       🟢     |   wazuh_kibana-4.3.4_7.16.2-1.zip        |
| Test 13   |     🟢     |     :black_circle:   |       🟢     |   wazuh_kibana-4.3.4_7.16.2-1.zip       |
| Test 14   |     🟢     |     :black_circle:   |       🟢     |    wazuh_kibana-4.3.4_7.16.2-1.zip       |
| Test 15   |     🟢     |     :black_circle:   |       🟢     |    wazuh_kibana-4.3.4_7.16.2-1.zip        |
| Test 16   |     🟢     |     :black_circle:   |       🟢     |    wazuh_kibana-4.3.4_7.16.2-1.zip       |
| Test 17   |     🟢     |     :black_circle:   |       🟢    |    wazuh_kibana-4.3.4_7.16.2-1.zip        |
| Test 18   |     🟢     |     :black_circle:   |       🟢    |   wazuh_kibana-4.3.4_7.16.2-1.zip       |
| Test 19   |     🟢     |     :black_circle:   |       🟢    |    wazuh_kibana-4.3.4_7.16.2-1.zip        |
| Test 20   |     🟢     |     :black_circle:   |       🟢    |   wazuh_kibana-4.3.4_7.16.2-1.zip        |
| Test 21   |     🟢     |     :black_circle:   |       🟢    |    wazuh_kibana-4.3.4_7.16.2-1.zip       |
| Test 22   |     🟢     |     :black_circle:   |       🟢    |    wazuh_kibana-4.3.4_7.16.2-1.zip       |
| Test 23   |     🟢     |     :black_circle:   |       🟢    |    wazuh_kibana-4.3.4_7.16.2-1.zip       |
| Test 24   |     🟢     |     :black_circle:   |       🟢    |    wazuh_kibana-4.3.4_7.16.2-1.zip       |
| Test 25   |     🟢     |     :black_circle:   |       🟢    |    wazuh_kibana-4.3.4_7.16.2-1.zip        |
| Test 26   |     🟢     |     :black_circle:   |       🟢    |    wazuh_kibana-4.3.4_7.16.2-1.zip       |
| Test 27   |     🟢     |     :black_circle:   |       🟢    |    wazuh_kibana-4.3.4_7.16.2-1.zip        |
| Test 28   |     🟢     |     :black_circle:   |       🟢    |    wazuh_kibana-4.3.4_7.16.2-1.zip        |
| Test 29   |     🟢     |     :black_circle:   |       🟢    |   wazuh_kibana-4.3.4_7.16.2-1.zip        |
| Test 30   |     🟢     |     :black_circle:   |       🟢    |    wazuh_kibana-4.3.4_7.16.2-1.zip        |

**Comment by mauceballos** [comment]
Wazuh Kibana App - Kibana 7.17.1 

|Test      | Chrome | Safari | Firefox  | Package |
| -- | -- | -- | -- | -- |
| Test 1   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip        |
| Test 2   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip        |
| Test 3   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip        |
| Test 4   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip        |
| Test 5   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip        |
| Test 6   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip        |
| Test 7   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip        |
| Test 8   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip        |
| Test 9   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip        |
| Test 10   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip        |
| Test 11   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip        |
| Test 12   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip        |
| Test 13   |     🟢     |     ⚫   |       🟢     |   wazuh_kibana-4.3.4_7.17.1-1.zip       |
| Test 14   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip       |
| Test 15   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip        |
| Test 16   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip        |
| Test 17   |     🟢     |    ⚫    |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip        |
| Test 18   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip       |
| Test 19   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip        |
| Test 20   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip        |
| Test 21   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip       |
| Test 22   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip        |
| Test 23   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip        |
| Test 24   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip       |
| Test 25   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip        |
| Test 26   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip        |
| Test 27   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip        |
| Test 28   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip        |
| Test 29   |     🟢     |     ⚫   |       🟢     |   wazuh_kibana-4.3.4_7.17.1-1.zip        |
| Test 30   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip        |
| Test 31   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip        |
| Test 32   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip        |
| Test 33   |     🟢     |     ⚫   |       🟢     |   wazuh_kibana-4.3.4_7.17.1-1.zip        |
| Test 34   |     🟢     |     ⚫   |       🟢     |    wazuh_kibana-4.3.4_7.17.1-1.zip        |

**Comment by Mayons95** [comment]
Wazuh Kibana App - Kibana 7.16.3 - In progress

|Test      | Chrome | Safari | Firefox  | Package |
| -- | -- | -- | -- | -- |
| Test 1   |     🟢     |     :black_circle:    |       🟢     |    wazuh_kibana-4.3.4_7.16.3-1.zip        |
| Test 2   |     🟢     |     :black_circle:    |       🟢     |    wazuh_kibana-4.3.4_7.16.3-1.zip         |        
| Test 3   |     🟢     |     :black_circle:    |       🟢     |    wazuh_kibana-4.3.4_7.16.3-1.zip         |       
| Test 4   |     🟢     |     :black_circle:    |       🟢     |    wazuh_kibana-4.3.4_7.16.3-1.zip         |      
| Test 5   |     🟢     |     :black_circle:    |       🟢     |    wazuh_kibana-4.3.4_7.16.3-1.zip         |

**Comment by AlexRuiz7** [comment]
## Kibana 7.10.2

| Test    | Chrome         | Safari         | Firefox        | Package                         |
| ------- | -------------- | -------------- | -------------- | ------------------------------- |
| Test 1  | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 2  | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 3  | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 4  | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 5  | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 6  | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 7  | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 8  | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 9  | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 10 | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 11 | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 12 | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 13 | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 14 | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 15 | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 16 | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 17 | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 18 | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 19 | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 20 | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 21 | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 22 | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 23 | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 24 | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 25 | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 26 | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 27 | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 28 | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 29 | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 30 | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 31 | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 32 | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 33 | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |
| Test 34 | :green_circle: | :black_circle: | :green_circle: | wazuh_kibana-4.3.4_7.10.2-1.zip |

**Comment by matiasmoreno876** [comment]
## Wazuh Dashboard 4.3.4

| Test    | Chrome         | Safari         | Firefox        | Package                         |
| ------- | -------------- | -------------- | -------------- | ------------------------------- |
| Test 1  | :black_circle: | :green_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 2  | :black_circle: | :green_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 3  | :black_circle: | :green_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 4  | :black_circle: | :green_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 5  | :black_circle: | :green_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 6  | :black_circle: | :green_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 7  | :black_circle: | :green_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 8  | :black_circle: | :green_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 9  | :black_circle: | :green_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 10 | :black_circle: | :green_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 11 | :black_circle: | :green_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 12 | :black_circle: | :green_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 13 | :black_circle: | :green_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 14 | :black_circle: | :green_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 15 | :black_circle: | :green_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 16 | :black_circle: | :green_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 17 | :black_circle: | :green_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 18 | :black_circle: | :green_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 19 | :black_circle: | :green_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 20 | :black_circle: | :green_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 21 | :black_circle: | :green_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 22 | :black_circle: | :green_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 23 | :black_circle: | :green_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 24 | :black_circle: | :green_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 25 | :black_circle: | :green_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 26 | :black_circle: | :green_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 27 | :black_circle: | :black_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 28 | :black_circle: | :black_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 29 | :black_circle: | :black_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 30 | :black_circle: | :black_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 31 | :black_circle: | :black_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 32 | :black_circle: | :black_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 33 | :black_circle: | :black_circle: | :black_circle: | wazuh-4.3.4-1.zip |
| Test 34 | :black_circle: | :black_circle: | :black_circle: | wazuh-4.3.4-1.zip |
