### ISSUE TITLE
API health check execute and fail when Wazuh Server restarting is still happening

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-kibana-app#4225]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3.4   | 7.10.2     | 4305 | - |

| Browser |
| ------- |
| Chrome, Firefox|

**Preconditions**
1. Wazuh Dasboard access

**Steps to reproduce**
1. Login to Wazuh Dashboard
2. Go to Managment > Configuration
4. Click Edit configuration
5. Make a valid configuration change
6. Save it and click on Restart Manager

**Expected Result**
1. Global health check page shows up, showing a label at the top with the label "Restarting Manager, please wait". All health checks runs OK and Wazuh Dashboard is accesible

**Actual Result**
1. Global health check page shows up, showing a label at the top with the label "Restarting Manager, please wait". API health check immediately fails. Once "Restarting Manager, please wait" label disappears, API health check need to be re-run in order to access Wazuh Dasboard

**Screenshots**
![image](https://user-images.githubusercontent.com/1791430/172382140-514bb1a9-746f-4d0a-9be4-9a5d74500eed.png)

**Additional context**
API health check fails because wazuh-apid daemon it's part of wazuh server, and will fail until wazuh-server is restarted

**Comment by davidjiglesias** [comment]
Duplicated and related with https://github.com/wazuh/wazuh-kibana-app/issues/4181
