### ISSUE TITLE
Inappropriate permissions' handling in MITRE intelligence section

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-kibana-app#4243]
Hello,

The RBAC permissions in the MITRE intelligence section of the Wazuh Dashboard are not being properly handled.

If we enter the MITRE inventory section without read permissions, the following errors appear:

![image](https://user-images.githubusercontent.com/48716145/173307193-1774352e-35e1-4451-878a-e1feff821d18.png)

**Comment by Desvelao** [comment]
Solved in:
- https://github.com/wazuh/wazuh-kibana-app/pull/4261 for [4.3-7.10](/wazuh/wazuh-kibana-app/tree/4.3-7.10)
- https://github.com/wazuh/wazuh-kibana-app/pull/4271 for [4.3-7.16](/wazuh/wazuh-kibana-app/tree/4.3-7.16)
- https://github.com/wazuh/wazuh-kibana-app/pull/4272 for [4.3-1.2-wzd](/wazuh/wazuh-kibana-app/tree/4.3-1.2-wzd)
