### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'closed')

### ISSUE THREAD

**Issue by yenienserrano** [wazuh/wazuh-kibana-app#4247]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**

When you are in Settings -> Configuration and navigate to another view you get the error `Uncaught TypeError: Cannot read properties of null (reading 'closed')` in console

**Steps to reproduce**
1. Navigate to 'Settings -> Configuration'
2. Navigates to another view
3. See error in console

**Expected Result**
1. No errors should be displayed

**Actual Result**
1. An error appears

**Screenshots**

https://user-images.githubusercontent.com/63758389/173332758-4cf31a51-c447-46c1-9858-31b8b59a6d49.mp4

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by Desvelao** [comment]
Duplicated https://github.com/wazuh/wazuh-kibana-app/issues/4772
