### ISSUE TITLE
Make the agent info ribbon scroll with the rest of the content

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#4256]
**Describe the solution you'd like**

A user navitages to the agent overview page using a device with an uncommon resolution ( like a MS Surface) and it renders like this: 

![image](https://user-images.githubusercontent.com/2181918/173501107-134700b3-345e-4ec2-97ec-96cf83887ec6.png)

That render hasn´t been scrolled, but look like if it were scrolled to the bottom of the page.

We want to redesign the page so the ribbon with the agent status and information scrolls like the rest of the content.

**Comment by matiasmoreno876** [comment]
In the attempt to replicate the problem, different impediments had to be passed by the development environments.

Currently when trying to set up the development environments of the Wazuh app, specified in this PR [#4435](https://github.com/wazuh/wazuh-kibana-app/pull/4435). They presented different errors in my laptop, which led to delay the investigation and resolution of the issue, the same errors will be worked at another time.

In order not to present a blockade by the development environments, it was decided to use the old environments, which are in the following repository https://github.com/matiasmoreno876/wazuh-app-environments

**Comment by Tostti** [comment]
Merged PR https://github.com/wazuh/wazuh-kibana-app/pull/4516 and the backports
