### ISSUE TITLE
Enable filters when using real-time mode on Manager/Logs

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#426]
Hello team,

Currently, the real-time mode on the *Manager/Logs* tab disables the filters. We should add the option to use filters in this mode.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
__Update:__ 

Hello team, this feature request is almost done on branch https://github.com/wazuh/wazuh-kibana-app/tree/3.2-filters-realtime-logs

Regards,
Jesús

**Comment by jesusgn90** [comment]
Done here https://github.com/wazuh/wazuh-kibana-app/pull/433
