### ISSUE TITLE
Compatibility matrix show wrong kibana version 7.17.4

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-kibana-app#4262]
Hello team, a user has reported a typo in the [compatibility matrix](https://github.com/wazuh/wazuh-kibana-app/wiki/Compatibility), specifically, for Wazuh app 4.3.4 and Kibana 7.17.4, it is showing a link to 7.17.3, this must be changed to 7.17.4

- https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.3.4_7.17.3-1.zip

by

- https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.3.4_7.17.4-1.zip

Regards, Raúl.

**Comment by Desvelao** [comment]
Fixed. Thank you so much for reporting!
