### ISSUE TITLE
Several Ruleset tab navigation bugfixes

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#427]
Fix several navigation issues on the new Ruleset tab.

Current tasks:
- [x] Make the Ruleset button open again the full list when viewing the Detail section.
- [x] Give colour to the rule description on the Detail view.
- [ ] Fix the strange error related to the tables. The steps to reproduce it are the following:

~~1. Open a rule Detail view.~~
~~2. Open a related rule after scrolling some pages.~~
~~3. Open a filter from the Detail view (A `gpg` filter)~~
~~4. Remove the filter.~~
~~5. Now the full rules list doesn't have more pagination, and it should.~~

Updated with new steps to reproduce the error:
1. Type `group:ossec` on the autocomplete search bar. Press <kbd>Enter</kbd> to add the filter.
2. Scroll to the end of the list.
3. Remove the filter.
4. The scroll no longer works.

Working on this branch: https://github.com/wazuh/wazuh-kibana-app/tree/3.2-ruleset-improvements

Regards,
Juanjo

**Comment by JuanjiJG** [comment]
New branch to work on this issue: https://github.com/wazuh/wazuh-kibana-app/tree/3.2-level-filter

This branch is the same used for #430, but this issue comes first to ensure proper behaviour for the filters.

Any future updates for this issue will be published here.

Regards,
Juanjo

**Comment by JuanjiJG** [comment]
May 8th update: after some research, I've localized the error and the steps to reproduce it:

1. Type `group:ossec` on the autocomplete searchbar. Press <kbd>Enter</kbd>to add the filter.
2. Scroll to the end of the list.
3. Remove the filter.
4. The scroll no longer works.

To fix this, click on the autocomplete searchbar, press <kbd>Enter</kbd>, and everything works fine again.

**Comment by JuanjiJG** [comment]
May 9th update: Now the arguments in a rule description are coloured.
![color](https://user-images.githubusercontent.com/10928321/39819255-480a870e-53a3-11e8-8163-898ce19ce3c1.PNG)

This way, they're more noticeable to the user.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
The remaining error has been fixed on https://github.com/wazuh/wazuh-kibana-app/pull/442, so I'm going to close this issue.

Regards,
Jesús

**Comment by JuanjiJG** [comment]
Thanks so much for your help @jesusgn90 !!

**Comment by jesusgn90** [comment]
You are welcome
