### ISSUE TITLE
Enable tag completion for Ruleset

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-kibana-app#4285]
**Describe the solution you'd like**
When writing XML, tag completion is very useful, speeds up and simplifies development and reduces human error.

Thankfully the Wazuh dashboard text editor allows this as showcased in the screens to edit configuration.

However this is not the case for Rules and Decoders and it is likely trivial to activate this feature for those screens.

**Additional context**
Video demonstration where the feature is shown in the manager's configuration editor and its absence is observed for the rule editor:

https://user-images.githubusercontent.com/36071202/175342504-4209096b-d60f-45d5-8d89-cd0d55dead5a.mp4

**Comment by havidarou** [comment]
Closing this as the new analysis engine will not use XML format.
