### ISSUE TITLE
Release 4.3.5 RC1 - Wazuh UI Manual Testing

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#4286]
# Wazuh v4.3.5 - Kibana 7.10.2, 7.16.x, 7.17.x - Revision 4306

| Test   | Chrome | Safari | Firefox | Package |
|--------|--------|--------|---------|---------|
| Test 1 | 🟢/🔴  | 🟢/🔴 | 🟢/🔴    | 🟢/🔴  |
 
Status legend:
⚫ - None
🔴 - Rejected
🟢 - Approved

In the case of 🔴, create and link the issue. 

### Added

- Added to the interface API messages in the Ruleset test module [#4244](https://github.com/wazuh/wazuh-kibana-app/pull/4244)
- Added authorization prompt in Mitre > Intelligence [#4261](https://github.com/wazuh/wazuh-kibana-app/pull/4261)

### Changed

- Changed the reference from Manager to Wazuh server in the guide to deploy a new agent [#4239](https://github.com/wazuh/wazuh-kibana-app/pull/4239)
- Removed the filtered tags because they were not supported by the API endpoint [#4267](https://github.com/wazuh/wazuh-kibana-app/pull/4267)
- Changed styles in visualizations. [#4254](https://github.com/wazuh/wazuh-kibana-app/pull/4254)

### Fixed

- Fixed type error when changing screen size in agents section [#4233](https://github.com/wazuh/wazuh-kibana-app/pull/4233)
- Removed a logged error that appeared when the `statistics` tasks tried to create an index with the same name, causing the second task to fail on the creation of the index because it already exists [#4235](https://github.com/wazuh/wazuh-kibana-app/pull/4235)
- Fixed a UI crash due to a query with syntax errors in `Modules/Security events` [#4237](https://github.com/wazuh/wazuh-kibana-app/pull/4237)
- Fixed an error when generating a module report after changing the selected agent [#4240](https://github.com/wazuh/wazuh-kibana-app/pull/4240)
- Fixed an unhandled error when a Wazuh API request failed in the dev tools [#4266](https://github.com/wazuh/wazuh-kibana-app/pull/4266)
- Fixed an error related to `API not available` when saving the manager configuration and restarting the manager from `Management/Configuration/Edit configuration` on manager mode [#4264](https://github.com/wazuh/wazuh-kibana-app/pull/4264)
- Fixed a UI problem that required scrolling to see the logs in Management/Logs and Settings/Logs [#4253](https://github.com/wazuh/wazuh-kibana-app/pull/4253)

### Scenario: An error message should be displayed when a rule is duplicated.
 Precondition: It’s needed to have a duplicated rule
```
 Given: The Kibana admin user is logged in using xpack and the Wazuh logo is displayed
 When: The user navigates to Ruleset Test 
 And: The user enters the test message 
And: The user clicks on the test button
Then: A error message is displayed on the console section  description of the problem
```

### Test comments

To create a duplicated rule:

1. Navigate to management/rule 
1. Access to any rule
1. Copy the rule code
1. Navigate back to management/rules
1. Create a custom rule
1. Paste the rule code
1. Saved the rule

### Scenario: Access denied to a Mitre Module
Precondition: It’s needed to log on to Wazuh Dashboard with a user that was not read permission for mitre 
```
Given: The user without reading permission on mitre  is logged in using Wazuh Dashboard and the Wazuh logo is displayed
When: The user navigates to Mitre Module
Then: The access denied screen is displayed
And: The user can’t access any submodule of mitre
```

### Test comments

All the test steps are described on the associated PR.
	
### Scenario: Validate the information to add a new Agent Red Hat / CentOS SO from CentOS6 or higher version with armhf architecture
```
Given: The Kibana admin user is logged in using xpack and the Wazuh logo is displayed
And: navigate on the new deploy agent page
When: the user selects `Red Hat / CentOS SO` from CentOS6 or higher version with `armhf` architecture
Then: the new sixth step is added with a "title", a "description", a "message", a "Wazuh documentation" link, and "console command", and a Copy command button are displayed

        | title | Install and enroll the agent |
        | description | You can use this command to install and enroll the Wazuh agent in one or more hosts. |
        | message | Running this command on a host with an agent already installed upgrades the agent package without enrolling the agent. To enroll in it, see the Wazuh documentation. |
        | Wazuh documentation | https://documentation.Wazuh.com/current/user-manual/registering/index.html |
        | console command | sudo WAZUH_MANAGER='172.19.0.4' yum install https://packages.Wazuh.com/4.x/yum/Wazuh-agent-4.3.0-1.armv7hl.rpm |

And: the new seventh step is added with a "title", the "Systemd" and "SysV init" tabs, a Copy command button, a message, and a "document" link are displayed

        | title |
        | Start the agent |

        | Systemd |
        | sudo systemctl daemon-reload |
        | sudo systemctl enable Wazuh-agent |
        | sudo systemctl start Wazuh-agent |

        | SysV Init |
        | sudo chkconfig --add Wazuh-agent |
        |sudo service Wazuh-agent start |

        | message |
        | To verify the connection with the Wazuh server, please follow this document. |

        | document |
        | https://documentation.Wazuh.com/4.3/user-manual/agents/agent-connection.html |

```

### Scenario: Validate the information to add a new Red Hat / CentOS SO version with armhf architecture
```
Given: The Kibana admin user is logged in using xpack and the Wazuh logo is displayed
And: navigate on the new deploy agent page
When: the user selects `Red Hat / CentOS SO` from `RedHat6` or higher version with `armhf` architecture
Then: the new sixth step is added with a "title", a "description", a "message", a "Wazuh documentation" link, and "console command", and a Copy command button are displayed

        | title | Install and enroll the agent |
        | description | You can use this command to install and enroll the Wazuh agent in one or more hosts. |
        | message | Running this command on a host with an agent already installed upgrades the agent package without enrolling the agent. To enroll it, see the Wazuh documentation. |
        | Wazuh documentation | https://documentation.Wazuh.com/current/user-manual/registering/index.html |
        | console command | curl -so Wazuh-agent-4.3.0.deb https://packages.Wazuh.com/4.x/apt/pool/main/w/Wazuh-agent/Wazuh-agent_4.3.0-1_armhf.deb && sudo WAZUH_MANAGER='172.19.0.3' dpkg -i ./Wazuh-agent-4.3.0.deb |
- And: the new seventh step is added with a "title", the "Systemd" and "SysV init" tabs, a Copy command button, a message, and a "document" link are displayed

        | title |
        | Start the agent |

        | Systemd |
        | sudo systemctl daemon-reload |
        | sudo systemctl enable Wazuh-agent |
        | sudo systemctl start Wazuh-agent |

        | SysV Init |
        | sudo chkconfig --add Wazuh-agent |
        |sudo service Wazuh-agent start |

        | message |
        | To verify the connection with the Wazuh server, please follow this document. |

        | document |
        | https://documentation.Wazuh.com/4.3/user-manual/agents/agent-connection.html |

```

### Scenario: Validate the information to add a new Agent Debian / Ubuntu SO version with armhf architecture
```
Given: The Kibana admin user is logged in using xpack and the Wazuh logo is displayed
And: navigate on the new deploy agent page
When: the user selects `Debian / Ubuntu SO` with `armhf` architecture
Then: the new sixth step is added with a "title", a "description", a "message", a "Wazuh documentation" link, and "console command", and a Copy command button are displayed

        | title | Install and enroll the agent |
        | description | You can use this command to install and enroll the Wazuh agent in one or more hosts. |
        | message | Running this command on a host with an agent already installed upgrades the agent package without enrolling the agent. To enroll in it, see the Wazuh documentation. |
        | Wazuh documentation | https://documentation.Wazuh.com/current/user-manual/registering/index.html |
        | console command | curl -so Wazuh-agent-4.3.0.deb https://packages.Wazuh.com/4.x/apt/pool/main/w/Wazuh-agent/Wazuh-agent_4.3.0-1_armhf.deb && sudo WAZUH_MANAGER='172.19.0.3' dpkg -i ./Wazuh-agent-4.3.0.deb |
- And: the new seventh step is added with a "title", the "Systemd" and "SysV init" tabs, a Copy command button, a message, and a "document" link are displayed

        | title |
        | Start the agent |

        | Systemd |
        | sudo systemctl daemon-reload |
        | sudo systemctl enable Wazuh-agent |
        | sudo systemctl start Wazuh-agent |

        | SysV Init |
        | sudo chkconfig --add Wazuh-agent |
        |sudo service Wazuh-agent start |

        | message |
        | To verify the connection with the Wazuh server, please follow this document. |

        | document |
        | https://documentation.Wazuh.com/4.3/user-manual/agents/agent-connection.html |

```

### Scenario: Filter tags
Precondition: It’s needed to have the GCP integration enabled and set
```
Given The Kibana admin user is logged in using xpack and the Wazuh logo is displayed
When The user navigates to management/logs
And The user clicks on the log selector
And The user clicks on the GCP bucket log
Then The log message is displayed
```

### Test comments
To integrate GCP module:
1. Navigate to management/configuration
1. On the manager, create an empty file named credentials.json on the path ossec/wodles
1. Add these configuration to the ossec.file
	```xml
    <gcp-bucket>
    	<run_on_start>yes</run_on_start>
    	<interval>1m</interval>
            <logging>debug</logging>
    	<bucket type="access_logs">
     	 <name>custom</name>
             <credentials_file>wodles/credentials.json</credentials_file>
    	</bucket>
    </gcp-bucket>
    ```
1. Save the changes
1. Restart the manager

### Scenario:
```
Given The Kibana admin user is logged in using xpack and the Wazuh logo is displayed
And navigate on the Vulnerabilities modules
When the dashboard with the plots is displayed with an styles
And the user select Agent 
Then the dashboards with plot is displayed with the same styles of vulnerabilities
```

### Scenario:
```
Given The Kibana admin user is logged in using xpack and the Wazuh logo is displayed
And  navigate the setting options
When the user select the Log tab
Then the app los message is displayed wit the log file located url `/usr.share/Wazuh-dashboard/data/Wazuh/log/Wazuhapp.log`
And on the log isn’t displayed a error message
```

### Scenario: Resize Screen 
```
Given The Kibana admin user is logged in using xpack and the Wazuh logo is displayed
When The user navigates to the agent dashboard 
And The user resizes the browser screen
Then  there aren’t errors displayed in the Browser Dev Console
```

### Scenario: Wrong query search
```
Given The Kibana admin user is logged in using xpack and the Wazuh logo is displayed
When The user navigates to the <Module Name>
And The user insert a wrong query at the search field
Then a toast should be displayed with an error message 
And The user should not be redirected to an error screen
```

### Scenario: Wrong query search 
```
Given The Kibana admin user is logged in using xpack and the Wazuh logo is displayed
When The user navigates to the devtools
And The user use an wrong query expression
Then The console should display an friendly error message
```

### Scenario: Resize Screen - Management - Logs
```
Given The Kibana admin user is logged in using xpack and the Wazuh logo is displayed
When The user navigates to `Management/Logs`
And The user changes the screen resolution (zoom-in/zoom-out) 
Then the number of lines displayed on the logs screen changes according to the zoom level.
```

### Scenario: Generate a module report
```
Given The Kibana admin user is logged in using xpack and the Wazuh logo is displayed
When The user navigates to `Modules/<Module>`
And Select an agent with the Explore agent button 
And generate a module report clicking on the Generate report
And Change the selected agent to another one, and generate a module report
Then This should be done
    Examples:

        | Module               |
        | Security Events      |
        | Integrity Monitoring |
        | System Auditing      |
        | Mitre & Attack       |
        | GDPR                 |
        | HIPAA                |
        | NIST                 |
        | TSC                  |
        | Policy Monitoring    |
        | PCIDSS               |
```

### Scenario: Generate a module report
```
Given The Kibana admin user is logged in using xpack and the Wazuh logo is displayed
When The user navigates to `Management > Configuration`
And Click on `Edit configuration`
And Change `vulnerability-detector` to enabled or disabled
And Click save, restart manager button, Wait for it to restart
Then the waiting time to see if the manager is active again
```

**Comment by Desvelao** [comment]
Kibana 7.16.3 (X-Pack)
| Test | Chrome | Safari | Firefox | Package |
| --- | --- | --- | --- | --- |
| 4244 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.16.3-1 |
| 4261 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.16.3-1 |
| 4239.1 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.16.3-1 |
| 4239.2 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.16.3-1 |
| 4239.3 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.16.3-1 |
| 4267 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.16.3-1 |
| 4254 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.16.3-1 |
| 4235 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.16.3-1 |
| 4233 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.16.3-1 |
| 4237 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.16.3-1 |
| 4266 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.16.3-1 |
| 4253 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.16.3-1 |
| 4240 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.16.3-1 |
| 4264 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.16.3-1 |

**Comment by Desvelao** [comment]
Kibana 7.10.2 (ODFE)

| Test | Chrome | Safari | Firefox | Package |
| --- | --- | --- | --- | --- |
| 4244 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.10.3-1 |
| 4261 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.10.3-1 |
| 4239.1 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.10.3-1 |
| 4239.2 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.10.3-1 |
| 4239.3 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.10.3-1 |
| 4267 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.10.3-1 |
| 4254 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.10.3-1 |
| 4235 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.10.3-1 |
| 4233 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.10.3-1 |
| 4237 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.10.3-1 |
| 4266 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.10.3-1 |
| 4253 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.10.3-1 |
| 4240 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.10.3-1 |
| 4264 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.10.3-1 |

**Comment by yenienserrano** [comment]
Kibana 7.16.3 (X-Pack)
| Test | Chrome | Safari | Firefox | Package |
| --- | --- | --- | --- | --- |
| 4244 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.4-1 |
| 4261 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.4-1 |
| 4239.1 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.4-1 |
| 4239.2 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.4-1 |
| 4239.3 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.4-1 |
| 4267 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.4-1 |
| 4254 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.4-1 |
| 4235 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.4-1 |
| 4233 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.4-1 |
| 4237 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.4-1 |
| 4266 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.4-1 |
| 4253 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.4-1 |
| 4240 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.4-1 |
| 4264 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.4-1 |

**Comment by yenienserrano** [comment]
Kibana 7.17.3 (X-Pack)
| Test | Chrome | Safari | Firefox | Package |
| --- | --- | --- | --- | --- |
| 4244 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.3-1 |
| 4261 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.3-1 |
| 4239.1 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.3-1 |
| 4239.2 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.3-1 |
| 4239.3 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.3-1 |
| 4267 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.3-1 |
| 4254 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.3-1 |
| 4235 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.3-1 |
| 4233 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.3-1 |
| 4237 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.3-1 |
| 4266 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.3-1 |
| 4253 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.3-1 |
| 4240 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.3-1 |
| 4264 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.3-1 |

**Comment by yenienserrano** [comment]
Kibana 7.17.2 (X-Pack)
| Test | Chrome | Safari | Firefox | Package |
| --- | --- | --- | --- | --- |
| 4244 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.2-1 |
| 4261 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.2-1 |
| 4239.1 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.2-1 |
| 4239.2 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.2-1 |
| 4239.3 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.2-1 |
| 4267 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.2-1 |
| 4254 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.2-1 |
| 4235 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.2-1 |
| 4233 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.2-1 |
| 4237 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.2-1 |
| 4266 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.2-1 |
| 4253 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.2-1 |
| 4240 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.2-1 |
| 4264 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.2-1 |

**Comment by Desvelao** [comment]
Wazuh dashboard 4.3.5
| 4244 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.16.3-1 |
| 4261 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.16.3-1 |
| 4239.1 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.16.3-1 |
| 4239.2 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.16.3-1 |
| 4239.3 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.16.3-1 |
| 4267 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.16.3-1 |
| 4254 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.16.3-1 |
| 4235 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.16.3-1 |
| 4233 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.16.3-1 |
| 4237 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.16.3-1 |
| 4266 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.16.3-1 |
| 4253 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.16.3-1 |
| 4240 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.16.3-1 |
| 4264 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.16.3-1 |

<details>
  <summary>4244<summary>
  
  ![image](https://user-images.githubusercontent.com/34042064/175887627-1756474f-4426-4fd0-8914-4445f484a874.png)
</details>

<details>
  <summary>4261<summary>
  
![image](https://user-images.githubusercontent.com/34042064/175893040-4b0313d2-ceb8-4a17-8f35-0dc575c54972.png)
![image](https://user-images.githubusercontent.com/34042064/175893069-8c4dada9-33bc-45f9-9ca9-cbfa278826e4.png)
</details>

<details>
  <summary>4239.1<summary>
  
![image](https://user-images.githubusercontent.com/34042064/175888598-89788c64-f18a-4b0e-8ef6-dfc36230726e.png)
![image](https://user-images.githubusercontent.com/34042064/175888846-1bf5de27-483b-4e3f-8cbf-ccc88dcecb86.png)
</details>

<details>
  <summary>4239.2<summary>
  
![image](https://user-images.githubusercontent.com/34042064/175889282-30a482b4-a7f0-4d03-937e-639cc4b11eae.png)
![image](https://user-images.githubusercontent.com/34042064/175889372-6b352299-5074-41c2-83ae-572df71b2972.png)

</details>

<details>
  <summary>4239.3<summary>
  
![image](https://user-images.githubusercontent.com/34042064/175889020-4a2a4311-730a-4cb4-a2fe-89516ab7d109.png)
![image](https://user-images.githubusercontent.com/34042064/175889078-98d7f9a8-6d0b-48a5-bae4-f0d3b4c4c3a8.png)
</details>

<details>
  <summary>4267<summary>
  
  
![image](https://user-images.githubusercontent.com/34042064/175889828-940d9b02-082e-4c3b-976f-f3e74cf3bcd9.png)
![image](https://user-images.githubusercontent.com/34042064/175889874-8b90eca2-9bec-48ab-ad9e-fd3638a35b8b.png)
</details>

<details>
  <summary>4254<summary>
  
  ![image](https://user-images.githubusercontent.com/34042064/175890074-b4887659-b5d7-4d97-a577-096a5e6d50b1.png)
</details>

<details>
  <summary>4235<summary>
  
  ![image](https://user-images.githubusercontent.com/34042064/175890247-6b6f233c-f00d-480c-94da-17c3c13b844c.png)

</details>

<details>
  <summary>4233<summary>
  
![image](https://user-images.githubusercontent.com/34042064/175890416-a659b518-ed67-4ee0-96c4-6e4c969fd463.png)

</details>

<details>
  <summary>4237<summary>
  
![image](https://user-images.githubusercontent.com/34042064/175890626-1bd21e90-6fb1-46e5-a6fa-5401e8e2eafe.png)

</details>

<details>
  <summary>4266<summary>
  
![image](https://user-images.githubusercontent.com/34042064/175890912-1ba83284-b422-4be5-be14-28d2709f010d.png)

</details>

<details>
  <summary>4253<summary>
  
![image](https://user-images.githubusercontent.com/34042064/175891164-85572fef-e9d3-4c1c-a848-b93738799033.png)

</details>

<details>
  <summary>4240<summary>
  
![image](https://user-images.githubusercontent.com/34042064/175891343-f51aa770-daea-4225-8371-7b47782c1ccb.png)
![image](https://user-images.githubusercontent.com/34042064/175891409-f101e66b-1191-447c-8eef-3dd60062d225.png)

</details>

<details>
  <summary>4264<summary>
  
![image](https://user-images.githubusercontent.com/34042064/175891729-b15ded86-47fb-431f-bcf6-41828e8b2636.png)
![image](https://user-images.githubusercontent.com/34042064/175891768-7259ad39-cc5d-4805-9036-494f168deb06.png)

</details>
