### ISSUE TITLE
Broken link to documentation

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#4294]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
The link to the old `Registration Service` is broken. This section now corresponds to `Agent Enrollment`, so this link should be used instead: [https://documentation.wazuh.com/current/user-manual/agent-enrollment/index.html](https://documentation.wazuh.com/current/user-manual/agent-enrollment/index.html).

Also, the title of the link is confusing, and should be changed to something more appropriate:

- [x] Change the broken link to https://documentation.wazuh.com/current/user-manual/agent-enrollment/index.html.
- [x] Change the title to `How the Agent Enrollment works`

**Steps to reproduce**
1. Navigate to `Management < Configuration < Registration Service`
2. Click on the question mark (?) to show the help.
3. Click on `How to use the registration service`

**Expected Result**
1. The link redirects to the correct section: Agent Enrollment

**Actual Result**
1. The link is broken

**Comment by Desvelao** [comment]
# Changes
- Changed the URL
- Changed the title

Solved in: https://github.com/wazuh/wazuh-kibana-app/pull/4301

**Comment by AlexRuiz7** [comment]
The title [How to agent enrollment](https://documentation.wazuh.com/4.3/user-manual/agent-enrollment/index.html) needs to be changed to `Agent enrollment`
or `How agent enrollment works`.
