### ISSUE TITLE
Documentation links must redirect to the App version

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#4296]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
The documentation links of the App are built to point to the current (latest) version of the documentation, independently of the App version. These links should redirect to the App version instead, so the App for Wazuh 4.3 provides documentation links to Wazuh 4.3, and not any other version.

- [x] Make the documentation links redirect to the App version.

Similar issue: https://github.com/wazuh/wazuh-kibana-app/issues/4152.

**Comment by Desvelao** [comment]
# Changes
Created a service to generate the web documentation URLs
Replaced the hardcoded web documentation URLs using the new service
Fixed some broken URLs

Solved in: https://github.com/wazuh/wazuh-kibana-app/pull/4301
