### ISSUE TITLE
Enhance the message displayed when there is a mismatch in API and plugin versions

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#4299]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
Some users don't know what is the problem and how to solve it when they see the error related to mismatching API and plugin versions.

Tasks:
- [x] Find a better way to inform the problem and how to solve it to the user
- [x] Remove the `<a>` tag of the message

**Screenshots**
![image](https://user-images.githubusercontent.com/34042064/176664257-4377e3eb-c49d-4324-a136-9b8c041cc7c5.png)

**Comment by Tostti** [comment]
Currently working on this issue. 

Analyzing it, I think that the best approach would be to make a shorter message with the important information and a link to the Troubleshooting documentation, in which we should specify in detail how to solve the issue.

Example of the new message:
![image](https://user-images.githubusercontent.com/42900763/190483635-bf0b9216-d0f4-4885-b624-1746442a0240.png)

**Comment by Tostti** [comment]
Blocked by https://github.com/wazuh/wazuh-documentation/pull/5594

**Comment by Tostti** [comment]
Merged corresponding PRs
