### ISSUE TITLE
wazuh-alerts-* Pattern is not found in Kibana 5.6.2

### ISSUE THREAD

**Issue by Mugen1991** [wazuh/wazuh-kibana-app#43]
When I use the Wazuh-Tab in Kibana the Plugin doesnt find my wazuh-alerts-* pattern.

![problem_1](https://user-images.githubusercontent.com/7630306/32282034-d0479232-bf20-11e7-979b-39a866c8f9b3.png)

I noticed that it says "wazu-alerts-" instead of "wazuh-alerts-*" but it says "logstash-*" Could it be, that the wildcard gets interpretet wrong? 

This is my Index-Pattern:

![problem_2](https://user-images.githubusercontent.com/7630306/32282207-451a46f4-bf21-11e7-834f-a2e464a94779.png)

I am sending via filebeats to logstash. My Elasticsearch and Kibana is currently on Version 5.6.2
This is my elasticsearch output ( logstash configuration ):
```

    elasticsearch {
      hosts => ["some_server","some_server","some_server"]
      template_name => "wazuh"
      template => "/etc/logstash/templates/wazuh-elastic5-template.json"
      document_type => "wazuh"
      template_overwrite => true
      index => "wazuh-alerts-%{+YYYY.MM.dd}"
}

```

Thanks in advance

**Comment by havidarou** [comment]
Hi @Mugen1991 this is happening because you need to set up wazuh-alerts-* as your default index-pattern, instead of logstash-*

To set it as default, select it and click in the star icon on the right part of the screen.

Regards.

**Comment by Mugen1991** [comment]
Thanks for your quick reply. Sadly this did not really fix the problem, 
Now it doesnt use logstash-* but some cryptic pattern.
![image](https://user-images.githubusercontent.com/7630306/32324685-83a3834e-bfcc-11e7-8181-413218ddff2c.png)

![image](https://user-images.githubusercontent.com/7630306/32324653-68882696-bfcc-11e7-96fd-83a06be4d8db.png)

**Comment by Mugen1991** [comment]
The funny thing is: When I go on "discover" under the wazuh tab,  It even shows me the documents 
![image](https://user-images.githubusercontent.com/7630306/32332791-a72032da-bfe6-11e7-81f9-d1db80d6c4a8.png)

**Comment by havidarou** [comment]
Maybe the .kibana index is somehow corrupted.

Stop Kibana:

```systemctl stop kibana```

You can create a backup of .kibana (just in case) and then delete it:

```curl -XDELETE url_to_elastic:9200/.kibana```

Then delete the .wazuh index (you'll have to reintroduce the credentials afterwards):

```curl -XDELETE url_to_elastic:9200/.wazuh```

And then start Kibana again:

```systemctl start kibana```

Regards.

**Comment by JuanjiJG** [comment]
It's been more than a month since the last response to this issue, so we proceed to close it.

Regards.
