### ISSUE TITLE
Api error - 3099 - ERROR3099 - Wazuh not ready yet - Already configured Wazuh API(s)

### ISSUE THREAD

**Issue by Diegojs5** [wazuh/wazuh-kibana-app#4306]
| Wazuh|
| ------- |
| v4.3.5 |

| Browser |
| ------- |
| Chrome,|

**Description**

Hello Everyone,

I was testing out recently released Google Cloud Platform Integration ([gcp-pubsub] 

**Preconditions**
Create  topics and subscriptions in GCP pub-sub using the commands following [gcloud] and https://documentation.wazuh.com/current/gcp/prerequisites/pubsub.html and https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/gcp-pubsub.html 

**Steps to reproduce**
Edit /var/ossec/etc/ossec.conf 
at the end of the file

**Screenshots**

![Captura de tela de 2022-07-04 21-14-58](https://user-images.githubusercontent.com/24316167/177227598-a7494bb7-2ddb-4f92-9ff0-ddaa595a2d88.png)

![Captura de tela de 2022-07-04 21-14-29](https://user-images.githubusercontent.com/24316167/177227609-4969a552-b131-4a28-826b-cac0e0a87117.png)

**Additional context**
Log
INFO: No current API selected
INFO: Getting API hosts...
INFO: API hosts found: 1
INFO: Checking API host id [default]...
INFO: Could not connect to API id [default]: 3099 - ERROR3099 - Wazuh not ready yet
INFO: Removed [navigate] cookie
ERROR: No API available to connect

2022/07/04 19:42:07 wazuh-csyslogd: ERROR: (1230): Invalid element in the configuration: 'gcp-pubsub'.
2022/07/04 19:42:07 wazuh-csyslogd: CRITICAL: (1202): Configuration error at 'etc/ossec.conf'.

I have try to restart all services, reboot the server, but the error is still present...

**ystemctl status wazuh-manager**

 wazuh-manager.service - Wazuh manager
     Loaded: loaded (/lib/systemd/system/wazuh-manager.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2022-07-05 00:06:47 UTC; 11min ago
    Process: 470 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=1/FAILURE)
        CPU: 598ms

Jul 05 00:06:45 wazuh-vm systemd[1]: Starting Wazuh manager...
Jul 05 00:06:47 wazuh-vm env[694]: 2022/07/05 00:06:47 wazuh-csyslogd: ERROR: (1230): Invalid element in the c>
Jul 05 00:06:47 wazuh-vm env[694]: 2022/07/05 00:06:47 wazuh-csyslogd: CRITICAL: (1202): Configuration error a>
Jul 05 00:06:47 wazuh-vm env[470]: wazuh-csyslogd: Configuration error. Exiting
Jul 05 00:06:47 wazuh-vm systemd[1]: wazuh-manager.service: Control process exited, code=exited, status=1/FAIL>
Jul 05 00:06:47 wazuh-vm systemd[1]: wazuh-manager.service: Failed with result 'exit-code'.
Jul 05 00:06:47 wazuh-vm systemd[1]: Failed to start Wazuh manager.

**Steps to reproduce**
Edit /var/ossec/etc/ossec.conf 
at the end of the file

<gcp-pubsub>
    <pull_on_start>yes</pull_on_start>`
    <interval>1m</interval>
    <project_id>d-security</project_id>
    <subscription_name>wazuh-gcloud-sub</subscription_name>
    <logging>debug</logging>
    <credentials_file>/var/ossec/etc/key/d-security-9f4818e4.json</credentials_file>
  </gcp-pubsub>

**Comment by Desvelao** [comment]
Hi @Diegojs5 

It seems you have a misconfiguration in the `gcp-pubsub` module indicated by these errors:
```
2022/07/04 19:42:07 wazuh-csyslogd: ERROR: (1230): Invalid element in the configuration: 'gcp-pubsub'.
2022/07/04 19:42:07 wazuh-csyslogd: CRITICAL: (1202): Configuration error at 'etc/ossec.conf'.
```

Due to these errors, the Wazuh API of that manager doesn't start and the Wazuh plugin can't connect to the configurated Wazuh API. 

What version of Wazuh manager are you using?

You should solve the problem with the configuration of the Wazuh manager. There is some element that is not expected in your configuration. After solving and applying changes in the Wazuh manager configuration, you have to restart the Wazuh manager. By default, the Wazuh manager configuration is located in `/var/ossec/etc/ossec.conf`.

Documentation for the `gcp-pubsub` Wazuh module: https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/gcp-pubsub.html

**Comment by Diegojs5** [comment]
<ossec_config>
  <global>
    <jsonout_output>yes</jsonout_output>
    <alerts_log>yes</alerts_log>
    <logall>no</logall>
    <logall_json>no</logall_json>
    <email_notification>no</email_notification>
    <smtp_server>smtp.example.wazuh.com</smtp_server>
    <email_from>wazuh@example.wazuh.com</email_from>
    <email_to>recipient@example.wazuh.com</email_to>
    <email_maxperhour>12</email_maxperhour>
    <email_log_source>alerts.log</email_log_source>
    <agents_disconnection_time>10m</agents_disconnection_time>
    <agents_disconnection_alert_time>0</agents_disconnection_alert_time>
  </global>

  <alerts>
    <log_alert_level>3</log_alert_level>
    <email_alert_level>12</email_alert_level>
  </alerts>

  
  <logging>
    <log_format>plain</log_format>
  </logging>

  <remote>
    <connection>secure</connection>
    <port>1514</port>
    <protocol>tcp</protocol>
    <queue_size>131072</queue_size>
  </remote>

  
  <rootcheck>
    <disabled>no</disabled>
    <check_files>yes</check_files>
    <check_trojans>yes</check_trojans>
    <check_dev>yes</check_dev>
    <check_sys>yes</check_sys>
    <check_pids>yes</check_pids>
    <check_ports>yes</check_ports>
    <check_if>yes</check_if>

    
    <frequency>43200</frequency>

    <rootkit_files>etc/rootcheck/rootkit_files.txt</rootkit_files>
    <rootkit_trojans>etc/rootcheck/rootkit_trojans.txt</rootkit_trojans>

    <skip_nfs>yes</skip_nfs>
  </rootcheck>

  <wodle name="cis-cat">
    <disabled>yes</disabled>
    <timeout>1800</timeout>
    <interval>1d</interval>
    <scan-on-start>yes</scan-on-start>

    <java_path>wodles/java</java_path>
    <ciscat_path>wodles/ciscat</ciscat_path>
  </wodle>

  
  <wodle name="osquery">
    <disabled>yes</disabled>
    <run_daemon>yes</run_daemon>
    <log_path>/var/log/osquery/osqueryd.results.log</log_path>
    <config_path>/etc/osquery/osquery.conf</config_path>
    <add_labels>yes</add_labels>
  </wodle>

  
  <wodle name="syscollector">
    <disabled>no</disabled>
    <interval>1h</interval>
    <scan_on_start>yes</scan_on_start>
    <hardware>yes</hardware>
    <os>yes</os>
    <network>yes</network>
    <packages>yes</packages>
    <ports all="no">yes</ports>
    <processes>yes</processes>

    
    <synchronization>
      <max_eps>10</max_eps>
    </synchronization>
  </wodle>

  <sca>
    <enabled>yes</enabled>
    <scan_on_start>yes</scan_on_start>
    <interval>12h</interval>
    <skip_nfs>yes</skip_nfs>
  </sca>

  <vulnerability-detector>
    <enabled>no</enabled>
    <interval>5m</interval>
    <min_full_scan_interval>6h</min_full_scan_interval>
    <run_on_start>yes</run_on_start>

    
    <provider name="canonical">
      <enabled>no</enabled>
      <os>trusty</os>
      <os>xenial</os>
      <os>bionic</os>
      <os>focal</os>
      <update_interval>1h</update_interval>
    </provider>

    
    <provider name="debian">
      <enabled>no</enabled>
      <os>stretch</os>
      <os>buster</os>
      <os>bullseye</os>
      <update_interval>1h</update_interval>
    </provider>

    
    <provider name="redhat">
      <enabled>no</enabled>
      <os>5</os>
      <os>6</os>
      <os>7</os>
      <os>8</os>
      <update_interval>1h</update_interval>
    </provider>

    
    <provider name="alas">
      <enabled>no</enabled>
      <os>amazon-linux</os>
      <os>amazon-linux-2</os>
      <update_interval>1h</update_interval>
    </provider>

    
    <provider name="arch">
      <enabled>no</enabled>
      <update_interval>1h</update_interval>
    </provider>

    
    <provider name="msu">
      <enabled>yes</enabled>
      <update_interval>1h</update_interval>
    </provider>

    
    <provider name="nvd">
      <enabled>yes</enabled>
      <update_from_year>2010</update_from_year>
      <update_interval>1h</update_interval>
    </provider>

  </vulnerability-detector>

  
  <syscheck>
    <disabled>no</disabled>

    
    <frequency>43200</frequency>

    <scan_on_start>yes</scan_on_start>

    
    <alert_new_files>yes</alert_new_files>

    
    <auto_ignore frequency="10" timeframe="3600">no</auto_ignore>

    
    <directories>/etc,/usr/bin,/usr/sbin</directories>
    <directories>/bin,/sbin,/boot</directories>

    
    <ignore>/etc/mtab</ignore>
    <ignore>/etc/hosts.deny</ignore>
    <ignore>/etc/mail/statistics</ignore>
    <ignore>/etc/random-seed</ignore>
    <ignore>/etc/random.seed</ignore>
    <ignore>/etc/adjtime</ignore>
    <ignore>/etc/httpd/logs</ignore>
    <ignore>/etc/utmpx</ignore>
    <ignore>/etc/wtmpx</ignore>
    <ignore>/etc/cups/certs</ignore>
    <ignore>/etc/dumpdates</ignore>
    <ignore>/etc/svc/volatile</ignore>

    
    <ignore type="sregex">.log$|.swp$</ignore>

    
    <nodiff>/etc/ssl/private.key</nodiff>

    <skip_nfs>yes</skip_nfs>
    <skip_dev>yes</skip_dev>
    <skip_proc>yes</skip_proc>
    <skip_sys>yes</skip_sys>

    
    <process_priority>10</process_priority>

    
    <max_eps>100</max_eps>

    
    <synchronization>
      <enabled>yes</enabled>
      <interval>5m</interval>
      <max_interval>1h</max_interval>
      <max_eps>10</max_eps>
    </synchronization>
  </syscheck>

  
  <global>
    <white_list>127.0.0.1</white_list>
    <white_list>^localhost.localdomain$</white_list>
    <white_list>169.254.169.254</white_list>
  </global>

  <command>
    <name>disable-account</name>
    <executable>disable-account</executable>
    <timeout_allowed>yes</timeout_allowed>
  </command>

  <command>
    <name>restart-wazuh</name>
    <executable>restart-wazuh</executable>
  </command>

  <command>
    <name>firewall-drop</name>
    <executable>firewall-drop</executable>
    <timeout_allowed>yes</timeout_allowed>
  </command>

  <command>
    <name>host-deny</name>
    <executable>host-deny</executable>
    <timeout_allowed>yes</timeout_allowed>
  </command>

  <command>
    <name>route-null</name>
    <executable>route-null</executable>
    <timeout_allowed>yes</timeout_allowed>
  </command>

  <command>
    <name>win_route-null</name>
    <executable>route-null.exe</executable>
    <timeout_allowed>yes</timeout_allowed>
  </command>

  <command>
    <name>netsh</name>
    <executable>netsh.exe</executable>
    <timeout_allowed>yes</timeout_allowed>
  </command>

  

  
  <localfile>
    <log_format>command</log_format>
    <command>df -P</command>
    <frequency>360</frequency>
  </localfile>

  <localfile>
    <log_format>full_command</log_format>
    <command>netstat -tulpn | sed 's/\([[:alnum:]]\+\)\ \+[[:digit:]]\+\ \+[[:digit:]]\+\ \+\(.*\):\([[:digit:]]*\)\ \+\([0-9\.\:\*]\+\).\+\ \([[:digit:]]*\/[[:alnum:]\-]*\).*/\1 \2 == \3 == \4 \5/' | sort -k 4 -g | sed 's/ == \(.*\) ==/:\1/' | sed 1,2d</command>
    <alias>netstat listening ports</alias>
    <frequency>360</frequency>
  </localfile>

  <localfile>
    <log_format>full_command</log_format>
    <command>last -n 20</command>
    <frequency>360</frequency>
  </localfile>

  <ruleset>
    
    <decoder_dir>ruleset/decoders</decoder_dir>
    <rule_dir>ruleset/rules</rule_dir>
    <rule_exclude>0215-policy_rules.xml</rule_exclude>
    <list>etc/lists/audit-keys</list>
    <list>etc/lists/amazon/aws-eventnames</list>
    <list>etc/lists/security-eventchannel</list>

    
    <decoder_dir>etc/decoders</decoder_dir>
    <rule_dir>etc/rules</rule_dir>
  </ruleset>

  <rule_test>
    <enabled>yes</enabled>
    <threads>1</threads>
    <max_sessions>64</max_sessions>
    <session_timeout>15m</session_timeout>
  </rule_test>

  
  <auth>
    <disabled>no</disabled>
    <port>1515</port>
    <use_source_ip>no</use_source_ip>
    <purge>yes</purge>
    <use_password>no</use_password>
    <ciphers>HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH</ciphers>
    
    <ssl_verify_host>no</ssl_verify_host>
    <ssl_manager_cert>etc/sslmanager.cert</ssl_manager_cert>
    <ssl_manager_key>etc/sslmanager.key</ssl_manager_key>
    <ssl_auto_negotiate>no</ssl_auto_negotiate>
  </auth>

  <cluster>
    <name>wazuh</name>
    <node_name>node01</node_name>
    <node_type>master</node_type>
    <key></key>
    <port>1516</port>
    <bind_addr>0.0.0.0</bind_addr>
    <nodes>
        <node>NODE_IP</node>
    </nodes>
    <hidden>no</hidden>
    <disabled>yes</disabled>
  </cluster>

</ossec_config>

<ossec_config>
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/ossec/logs/active-responses.log</location>
  </localfile>

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/messages</location>
  </localfile>

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/auth.log</location>
  </localfile>

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/syslog</location>
  </localfile>

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/dpkg.log</location>
  </localfile>

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/kern.log</location>
  </localfile>

</ossec_config>

  <gcp-pubsub>
    <pull_on_start>yes</pull_on_start>
    <interval>1m</interval>
    <project_id>c-security</project_id>
    <subscription_name>wazuh-gcloud-sub</subscription_name>
    <logging>debug</logging>
    <credentials_file>/var/ossec/etc/key/c-security-9f4818e314.json</credentials_file>
 </gcp-pubsub>

**Comment by Diegojs5** [comment]
Hello, @Desvelao 
 logs related to gcp-pubsub

 **grep gcp-pubsub /var/ossec/logs/ossec.log**
2022/07/04 19:42:07 wazuh-csyslogd: ERROR: (1230): Invalid element in the configuration: 'gcp-pubsub'.
2022/07/04 19:44:40 wazuh-csyslogd: ERROR: (1230): Invalid element in the configuration: 'gcp-pubsub'.
2022/07/04 19:53:37 wazuh-csyslogd: ERROR: (1230): Invalid element in the configuration: 'gcp-pubsub'.
2022/07/04 20:13:59 wazuh-csyslogd: ERROR: (1230): Invalid element in the configuration: 'gcp-pubsub'.
2022/07/04 20:14:16 wazuh-csyslogd: ERROR: (1230): Invalid element in the configuration: 'gcp-pubsub'.
2022/07/04 21:05:17 wazuh-csyslogd: ERROR: (1230): Invalid element in the configuration: 'gcp-pubsub'.
2022/07/04 21:06:22 wazuh-csyslogd: ERROR: (1230): Invalid element in the configuration: 'gcp-pubsub'.
2022/07/04 21:17:05 wazuh-csyslogd: ERROR: (1230): Invalid element in the configuration: 'gcp-pubsub'.
2022/07/04 23:55:37 wazuh-csyslogd: ERROR: (1230): Invalid element in the configuration: 'gcp-pubsub'.
2022/07/05 00:06:47 wazuh-csyslogd: ERROR: (1230): Invalid element in the configuration: 'gcp-pubsub'.
2022/07/05 00:18:39 wazuh-csyslogd: ERROR: (1230): Invalid element in the configuration: 'gcp-pubsub'.
2022/07/05 00:46:40 wazuh-csyslogd: ERROR: (1230): Invalid element in the configuration: 'gcp-pubsub'.
2022/07/05 00:52:38 wazuh-csyslogd: ERROR: (1230): Invalid element in the configuration: 'gcp-pubsub'.

configuration file obfuscating the sensitive data
[ossec.txt](https://github.com/wazuh/wazuh-kibana-app/files/9045541/ossec.txt)

**Comment by Desvelao** [comment]
The `gcp-pubsub` goes within a `ossec_config` block. In your Manager configuration, you have the `gcp-pupsub` block in the root of the configuration. The module configuration should be within a `ossec_config` block. For example:

```
<ossec_config>
  <!-- Some configurations -->
  <gcp-pubsub>
    <!-- GCP module configuration -->
  </gcp-pubsub>
</ossec_config>
```

**Comment by Diegojs5** [comment]
**grep gcp-pubsub /var/ossec/logs/ossec.log**

2022/07/05 00:52:38 wazuh-csyslogd: ERROR: (1230): Invalid element in the configuration: 'gcp-pubsub'.
2022/07/05 11:50:38 wazuh-modulesd:gcp-pubsub: INFO: Module started.
![Captura de tela de 2022-07-05 09-14-49](https://user-images.githubusercontent.com/24316167/177325587-d0c02852-3c03-4e9d-bb49-c74d529a23c3.png)

**Comment by Desvelao** [comment]
Is the API of the Wazuh manager up? Do you can pass the check related to this screenshot in the Wazuh plugin for Kibana/Wazuh dashboard?

> ![Captura de tela de 2022-07-04 21-14-58](https://user-images.githubusercontent.com/24316167/177227598-a7494bb7-2ddb-4f92-9ff0-ddaa595a2d88.png)

> ![Captura de tela de 2022-07-04 21-14-29](https://user-images.githubusercontent.com/24316167/177227609-4969a552-b131-4a28-826b-cac0e0a87117.png)

**Comment by Diegojs5** [comment]
**3099 - ERROR3099 - Wazuh not ready yet**

![Captura de tela de 2022-07-05 11-49-39](https://user-images.githubusercontent.com/24316167/177356104-71c9d269-6421-42ba-8dfc-
![Captura de tela de 2022-07-05 11-48-50](https://user-images.githubusercontent.com/24316167/177356163-27d9170a-eb40-4fa6-a03b-bee563cb3149.png)
e28c2a457428.png)

**Comment by Diegojs5** [comment]
![Captura de tela de 2022-07-05 11-49-39](https://user-images.githubusercontent.com/24316167/177356269-83eb405c-24e0-4916-8f4d-5334d0d27f7c.png)

**Comment by Desvelao** [comment]
Could you review the Wazuh manager is working and up? Share the output:
```
# depending on your service manager
systemctl status wazuh-manager

# or

service wazuh-manager status
```

Are the Kibana and the Wazuh manager in the same host? If not, then you should modify the configuration of Wazuh plugin to point to the host of Wazuh manager instead of `localhost`.

**Comment by Diegojs5** [comment]
Hi, @Desvelao 

First of all, sorry for my English

The error was syntax mistake. Thanks for the reply.

Best regards,

**Comment by Desvelao** [comment]
No problem. I am glad you could solve the problem! :smile: 

Best regards.
