### ISSUE TITLE
Version 4.3.5 not compatible with Elasticsearch 7.17.5

### ISSUE THREAD

**Issue by jareddewitt** [wazuh/wazuh-kibana-app#4308]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3.5   | 7.17.5    | 46953| Basic, ODFE, Xpack |

| Browser |
| ------- |
Chrome

**Description**
Wazuh Plugin not compatible with elasticsearch version 7.17.5.  

**Actual Result**
Failed to initialize plugins:\n\tPlugin \"wazuh\" is only compatible with Kibana version \"7.17.4\", but used Kibana version is \"7.17.5\". (incompatible-version, /usr/share/kibana/plugins/wazuh/kibana.json)\n

**Additional context**
https://github.com/wazuh/wazuh-kibana-app/wiki/Compatibility#wazuh---kibana---open-distro-for-elasticsearch-version-compatibility-matrix

Will there be a new version of Wazuh to support this version of elasticsearch?  I tried to downgrade both elasticsearch and kibana, but they don't support a downgrade.  The node just fails out.  So have to move forward with upgrading Wazuh.

**Comment by AlexRuiz7** [comment]
Hello @jareddewitt 

Kibana 7.17.5 will be officially compatible with Wazuh on our next patch release 4.3.6, whose release date is the 20th of July, if everything goes as planned.

Regards,
Alex
