### ISSUE TITLE
compatibility Kibana 8.2.2

### ISSUE THREAD

**Issue by patrick10071990** [wazuh/wazuh-kibana-app#4311]
Hello, is there already a schedule when the Wazuh Kibana App will be supported for Kibana 8.2.x or 8.3.x?

**Comment by yenienserrano** [comment]
Hi @patrick10071990 thanks for using Wazuh.

There is still no schedule for wazuh kibana app to support kibana versions 8.2.x or 8.3.x.

Regards

**Comment by AlexRuiz7** [comment]
We're planning to make the app compatible with Elastic 8.x.
We'll use this issue to track the progress: #4567
