### ISSUE TITLE
The search bar removes parentheses from the values

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#4313]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
The search bar removes parentheses from the query, even using the suggested value.

**Preconditions**
1. A Wazuh agent installed and with vulnerability-detector enabled.
2. Vulnerable apps or packages that contain parentheses on their name. 

**Steps to reproduce**
1. Navigate to the Vulnerabilities module.
3. Pin the agent with the vulnerabilities.
4. Try to filter by the vulnerable package or app that has parentheses on its name.

**Screenshots**
![searchbar_parentheses](https://user-images.githubusercontent.com/15186973/177590736-553be27d-9aef-4fca-98ac-7fc84877c3a1.gif)

**Comment by Desvelao** [comment]
# Alternative

We are working on a new search bar, so I checked if this problem is present on it.

I reviewed this use case for the new search bar and the parenthesis are not removed
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/7b28c89d-4e82-4062-b96a-36918b15e2c8)
