### ISSUE TITLE
Vulnerabilites Summary is misleading - count doesn't match with severity and details

### ISSUE THREAD

**Issue by architosch** [wazuh/wazuh-kibana-app#4325]
**Describe the solution you'd like**
Say I have 13 vulnerabilites. Then I'll have a sum of 13 for severity, 13 for details, but only the sum of the top 4 for summary. This is highly irritating for users. 
I therefore suggest to show the top 3 in the summary and sum up all the rest as "other" as fourth entry of the summary diagram.

**Describe alternatives you've considered**
The alternative would be to list all findings under summary, but this might become hard to read really quickly.
<img width="1721" alt="Bildschirmfoto 2022-07-13 um 14 10 36" src="https://user-images.githubusercontent.com/109212070/178730416-c1e4bfe4-ca4c-44d2-a147-374854824c1a.png">

**Additional context**
see screenshot for visualization of the problem.

**Comment by Desvelao** [comment]
Hi @architosch,

Currently, the visualization in the `Summary` panel shows the top 4 vulnerabilities with more counts sorted by the selected property.

Grouping the rest of the alerts in a new entry for that visualization could be an approach that we should discuss. Maybe the panel name is a little confusing.

Thank you so much for the suggestion!

**Comment by Desvelao** [comment]
I will close the issue due to inactivity.
