### ISSUE TITLE
Release 4.3.6 RC1 - Wazuh UI Manual Testing

### ISSUE THREAD

**Issue by Mayons95** [wazuh/wazuh-kibana-app#4334]
# Wazuh v4.3.6 - Kibana 7.10.2, 7.16.x, 7.17.x - Revision 4307

| Test   | Chrome | Safari | Firefox | Package |
|--------|--------|--------|---------|---------|
| Test 1 | 🟢/🔴  | 🟢/🔴 | 🟢/🔴    | 🟢/🔴  |
 
Status legend:
⚫ - None
🔴 - Rejected
🟢 - Approved

In the case of 🔴, create and link the issue. 

### Fixed

- Fix documentation link titles to match the documentation sections to redirect to [#4301](https://github.com/wazuh/wazuh-kibana-app/pull/4301)
- Fix missing documentation references to the Agent's overview, Agent's Integrity monitoring, and Agent's Inventory data sections, when the agent has never connected. [#4301](https://github.com/wazuh/wazuh-kibana-app/pull/4301)
- The references to the documentation site now links to the appropriate version [#4301](https://github.com/wazuh/wazuh-kibana-app/pull/4301)
- Fixed missing documentation link in the Docker Listener module [#4301](https://github.com/wazuh/wazuh-kibana-app/pull/4301)
- Fixed broken links to the documentation site [#4301](https://github.com/wazuh/wazuh-kibana-app/pull/4301)
- Fix Rules, Decoders and CDB lists uploaders to show errors appropriately [#4307](https://github.com/wazuh/wazuh-kibana-app/pull/4307)
- Sanitize report's inputs and usernames [#4330](https://github.com/wazuh/wazuh-kibana-app/pull/4330)

### @Rules/Decoders/CBDList
Fix Rules/Decoders/CDB lists uploader to show errors appropriately [#4307](https://github.com/wazuh/wazuh-kibana-app/pull/4307)
Scenario: Upload large files 
   Precondition: It needed to have a large CBD file (more than 10 MB)
   Given The Wazuh admin user is logged
   When The user navigates to Management/CBD
   And The user clicks the import file option
   And The user uploads a large CBD list file
   Then An information modal should be displayed informing the user that the maximum length of the file is 1048576.

### @Rules/Decoders/CBDList
Fix Rules/Decoders/CDB lists uploader to show errors appropriately  [#4307](https://github.com/wazuh/wazuh-kibana-app/pull/4307)
Scenario: Edit files with names with special characters
   Precondition: It’s needed to have a CBD file created with an special character in the name, eg: file_test_12,5MB (here the special character is the comma)
   Given The Wazuh admin user is logged
   When The user navigates to Management/CBD
   And The user edit’s a CBD file that has a name with a special character
   Then A popup should be displayed informing that the format it’s invalid.

### @Rules/Decoders/CBDList
Fix Rules/Decoders/CDB lists uploader to show errors appropriately  [#4307](https://github.com/wazuh/wazuh-kibana-app/pull/4307)
Scenario: Edit large files 
   Precondition: It needed to have a large CBD file (more than 10 MB)
   Given The Wazuh admin user is logged
   When The user navigates to Management/CBD
   And The user edit’s a CBD large file
   And The request takes more than 20 seconds
   Then A popup should be displayed informing a time-out.

### @External-Documentation-Links
Fix Links to Wazuh Documentations depends on the installed version[#4301](https://github.com/wazuh/wazuh-kibana-app/pull/4301)
Scenario: Documentation links redirect to Wazuh documentation
   Precondition: It needed to have a not connect agent
   Given The Wazuh admin user is logged
   When The user navigates to a never connect agent
   And A link to the documentation should be displayed
   And The user clicks on the documentation link
   Then The user should be redirected to the Wazuh documentation regarding the same version of Wazuh and the version of the documentation. 
For example: If the app is on the 4.2 version, the user should be redirected to the 4.2 version and not the current version.

### @Search Bar
Search Bar- Conjuction[#4326](https://github.com/wazuh/wazuh-kibana-app/pull/4326)
Scenario: Search by parameters with AND
   Given The Wazuh admin user is logged
   When The user navigates to any module (Ex: Vulnerabilities)
   And The user types a particular search on the search bar like: “name=vim AND severity=critical ”
   And The user applies the filters
   Then The query is accepted and the results should be displayed.

### @Search Bar
Search Bar- Conjuction[#4326](https://github.com/wazuh/wazuh-kibana-app/pull/4326)
Scenario: Search by parameters with OR
   Given The Wazuh admin user is logged
   When The user navigates to any module (Ex: Vulnerabilities)
   And The user types a particular search on the search bar like: “severity=critical OR severity=High”
   And The user applies the filters
   Then The query is accepted and the results should be displayed.

**Comment by Desvelao** [comment]
Kibana 7.16.3 (X-Pack)
| Test | Chrome | Safari | Firefox | Package |
| --- | --- | --- | --- | --- |
| 4307.1 | :green_circle: | :black_circle: | :green_circle: | 4.3.6_7.17.4-1 |
| 4307.2 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.4-1 |
| 4307.3 | :green_circle: | :black_circle: | :green_circle: | 4.3.5_7.17.4-1 |

<details>
  <summary>4307.1</summary>
  
![image](https://user-images.githubusercontent.com/34042064/179706302-bebeef82-ae44-4734-9790-3671a25a07b4.png)

</details>
<details>

  <summary>4307.2</summary>
    
![image](https://user-images.githubusercontent.com/34042064/179705847-fd6cfd46-2552-4a84-aafe-ba10684f97b2.png)

</details>

<details>

  <summary>4307.3</summary>
    
![image](https://user-images.githubusercontent.com/34042064/179710108-de30418f-171d-4f5b-b9e8-c19ee0fbac83.png)

</details>

<details>

  <summary>4031</summary>
    

</details>

**Comment by yenienserrano** [comment]
Kibana 7.17.5 (X-Pack)
| Test | Chrome | Safari | Firefox | Package |
| --- | --- | --- | --- | --- |
| 4307.1 | :green_circle: | :black_circle: | :green_circle: | 4.3.6_7.17.5-1 |
| 4307.2 | :green_circle: | :black_circle: | :green_circle: | 4.3.6_7.17.5-1 |
| 4307.3 | :green_circle: | :black_circle: | :green_circle: | 4.3.6_7.17.5-1 |
| 4301    | :green_circle: | :black_circle: | :green_circle: | 4.3.6_7.17.5-1 |
| 4326.1 | :green_circle: | :black_circle: | :green_circle: | 4.3.6_7.17.5-1 |
| 4326.2 | :green_circle: | :black_circle: | :green_circle: | 4.3.6_7.17.5-1 |

In progress

<details>
  <summary>4307.1</summary>
  
![image](https://user-images.githubusercontent.com/63758389/179726913-d6abc279-e918-4f84-8a68-be1ecec63f5c.png)

</details>
<details>
  <summary>4307.2</summary>
    
![image](https://user-images.githubusercontent.com/63758389/179729829-d607819d-b944-4cfb-90e4-d0f8ae8e3ca0.png)

</details>

<details>
  <summary>4307.3</summary>
    
![image](https://user-images.githubusercontent.com/63758389/179732415-e1528395-2c9e-4786-9685-c14ced84ca3c.png)

</details>

<details>
  <summary>4031</summary>
    
![image](https://user-images.githubusercontent.com/34042064/179721365-d6a2051c-6907-48a7-8fb6-41263ab186c6.png)
![image](https://user-images.githubusercontent.com/34042064/179721432-4f4db519-0c19-44c5-8ce3-9d5830d308e3.png)
![image](https://user-images.githubusercontent.com/34042064/179721532-de984f10-505f-44c7-baa0-9530def1dba9.png)
![image](https://user-images.githubusercontent.com/63758389/179733266-386b1228-f096-4a7a-9461-4e9633b125ab.png)

</details>

<details>
  <summary>4326.1</summary>
    
![image](https://user-images.githubusercontent.com/34042064/179725594-7aac0cc9-60ea-4063-bfc1-45a1ada8c23a.png)

</details>

<details>
  <summary>4326.2</summary>
    
![image](https://user-images.githubusercontent.com/34042064/179725316-2904cd6d-7d06-434b-be1e-484ef7794495.png)

</details>

**Comment by Machi3mfl** [comment]
Kibana 7.16.3 (X-Pack)
| Test | Chrome | Safari | Firefox | Package |
| --- | --- | --- | --- | --- |
| 4307.1 | :green_circle: | :black_circle: | :green_circle: | 4.3.6_7.16.3-1 |
| 4307.2 | :green_circle: | :black_circle: | :green_circle: | 4.3.6_7.16.3-1 |
| 4307.3 | :green_circle: | :black_circle: | :green_circle: | 4.3.6_7.16.3-1 |
| 4301    | :green_circle: | :black_circle: | :green_circle: | 4.3.6_7.16.3-1 |
| 4326.1 | :green_circle: | :black_circle: | :green_circle: | 4.3.6_7.16.3-1 |
| 4326.2 | :green_circle: | :black_circle: | :green_circle: | 4.3.6_7.16.3-1 |


In progress

<details>
  <summary>4307.1</summary>
  

</details>
<details>
  <summary>4307.2</summary>
    

</details>

<details>
  <summary>4307.3</summary>
    

</details>

<details>
  <summary>4031</summary>
    


</details>

<details>
  <summary>4326.1</summary>
    


</details>

<details>
  <summary>4326.2</summary>
    

</details>

**Comment by Mayons95** [comment]
Wazuh - Dashboard
| Test | Chrome | Safari | Firefox | Package |
| --- | --- | --- | --- | --- |
| 4307.1 | :green_circle: | :green_circle: | :black_circle: | 4.3.6_7.16.3-1 |
| 4307.2 | :green_circle: | :green_circle: | :black_circle: | 4.3.6_7.16.3-1 |
| 4307.3 | :green_circle: | :green_circle: | :black_circle: | 4.3.6_7.16.3-1 |
| 4301    | :green_circle: | :green_circle: | :black_circle: | 4.3.6_7.16.3-1 |
| 4326.1 | :green_circle: | :green_circle: | :black_circle: | 4.3.6_7.16.3-1 |
| 4326.2 | :green_circle: | :green_circle: | :black_circle: | 4.3.6_7.16.3-1 |

<details>
  <summary>4307.1</summary>

<img width="1440" alt="Screen Shot 2022-07-19 at 11 24 39" src="https://user-images.githubusercontent.com/6089438/179777911-fd3ceaf8-ec70-4f53-bae6-dd1df20ccd17.png">


</details>
<details>
  <summary>4307.2</summary>
    
<img width="1423" alt="Screen Shot 2022-07-19 at 11 38 39" src="https://user-images.githubusercontent.com/6089438/179777850-667aad81-f827-4cf2-a8a0-83df3a2adf2c.png">


</details>

<details>
  <summary>4307.3</summary>
<img width="1263" alt="Screen Shot 2022-07-19 at 11 57 36" src="https://user-images.githubusercontent.com/6089438/179782189-9ee197c1-e2fd-4f7d-8ca6-def1dd92bc0f.png">


</details>

<details>
  <summary>4031</summary>
    
<img width="1440" alt="Screen Shot 2022-07-19 at 11 48 36" src="https://user-images.githubusercontent.com/6089438/179780076-d6e31243-1db8-467b-adb4-b44621e48ba6.png">

<img width="1437" alt="Screen Shot 2022-07-19 at 11 49 15" src="https://user-images.githubusercontent.com/6089438/179780170-040ea67a-35d6-4b85-8fd2-3e30a6398011.png">

<img width="1439" alt="Screen Shot 2022-07-19 at 11 51 28" src="https://user-images.githubusercontent.com/6089438/179780696-df8d0fc7-7106-4536-b89d-57d595ee2d09.png">

<img width="1437" alt="Screen Shot 2022-07-19 at 11 53 22" src="https://user-images.githubusercontent.com/6089438/179781102-fde335fb-5d09-441e-81f4-b672f69839dc.png">


</details>

<details>
  <summary>4326.1</summary>
    
<img width="1425" alt="Screen Shot 2022-07-19 at 11 54 56" src="https://user-images.githubusercontent.com/6089438/179781533-ae6f5847-f76f-4e9e-9414-47e1e563bdc6.png">


</details>

<details>
  <summary>4326.2</summary>

<img width="1427" alt="Screen Shot 2022-07-19 at 11 56 11" src="https://user-images.githubusercontent.com/6089438/179781850-1a1ef478-5e47-4be9-93bd-2b17223614d1.png">


</details>

**Comment by davidjiglesias** [comment]
We should test upgrading to 4.3.6 with Opendistro and 7.10.2
