### ISSUE TITLE
4.3.5 unable to execute SQL Query for Windows CIS Benchmark View

### ISSUE THREAD

**Issue by sempervictus** [wazuh/wazuh-kibana-app#4340]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3.5  | 7.10.2     | 4xxx | Basic |

| Browser |
| ------- |
| Chrome|

**Description**
Attempting to view the CIS security baseline data for a 2019 server results in two errors:
```
Error

The filter contains invalid characters
```
```js
013 - Error in wazuhdb request: Cannot execute SQL query
Error: 3013 - Error in wazuhdb request: Cannot execute SQL query
    at createError (https://elk-host.fqdn/36136/bundles/plugin/wazuh/wazuh.plugin.js:2:31654)
    at settle (https://elk-host.fqdn/36136/bundles/plugin/wazuh/wazuh.plugin.js:8:15184)
    at XMLHttpRequest.onloadend (https://elk-host.fqdn/36136/bundles/plugin/wazuh/wazuh.plugin.js:2:29447)
```
and
```
TypeError

Cannot read properties of undefined (reading 'some')
```
```js
TypeError: Cannot read properties of undefined (reading 'some')
    at SuggestHandler.someItem (https://elk-host.fqdn/36136/bundles/plugin/wazuh/wazuh.chunk.9.js:5:2045799)
    at _callee$ (https://elk-host.fqdn/36136/bundles/plugin/wazuh/wazuh.chunk.9.js:5:2048891)
    at l (https://elk-host.fqdn/36136/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:380:982071)
    at Generator._invoke (https://elk-host.fqdn/36136/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:380:981824)
    at forEach.e.<computed> [as next] (https://elk-host.fqdn/36136/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:380:982428)
    at suggest_handler_asyncGeneratorStep (https://elk-host.fqdn/36136/bundles/plugin/wazuh/wazuh.chunk.9.js:5:2040653)
    at _next (https://elk-host.fqdn/36136/bundles/plugin/wazuh/wazuh.chunk.9.js:5:2040979)
    at https://elk-host.fqdn/36136/bundles/plugin/wazuh/wazuh.chunk.9.js:5:2041161
    at new Promise (<anonymous>)
    at https://elk-host.fqdn/36136/bundles/plugin/wazuh/wazuh.chunk.9.js:5:2040891


Close
```
**Expected Result**
1.  Presentation of CIS benchmark view with brows-able details

**Actual Result**
1. Error 3013

**Additional context**
This was originally deployed as 4.2.7 and upgraded to 4.3.5 in-place.
The Windows Baseline audit is accessible and works fine

**Comment by sempervictus** [comment]
@AlexRuiz7 - persists with 4.3.6, procedure is:
* navigate to SCA module
* select agent
* observe errors and see no results

![image](https://user-images.githubusercontent.com/1331084/180322043-2476debc-2b46-4797-b0b6-5dacf6678449.png)

**Comment by AlexRuiz7** [comment]
Thanks, @sempervictus 

We do have a related issue: #4347 

We'll address this issue together with that one.

Thanks for the report!

Regards,
Alex

**Comment by Machi3mfl** [comment]
Hi @sempervictus. 
I was testing the search bar functionally on SCA inventory on 4.3.6 and the error doesn't happen.
I leave a short video with the cases I've tested.
https://user-images.githubusercontent.com/6089438/181767012-f724745a-38ad-4d93-bd35-951a8725f0f3.mov

**Comment by sempervictus** [comment]
@Machi3mfl the video shows you searching through the agent view - try doing that inside the CIS status view for an agent.

**Comment by Machi3mfl** [comment]
@sempervictus  Sorry, I uploaded the wrong video. I updated the comment below.

**Comment by sempervictus** [comment]
Thanks @Machi3mfl - that is exactly what i would expect to see in our views too. For some reason i'm getting the broken view in the lab and two production deployments. We have venerable/well-tested Chef code deploying all of the server-side components for us, including some Nokogiri magic to deal with the config XML format and i'm wondering if something changed as relating to SCA/CIS configuration which could cause this though i'm not seeing it skimming through the docs. _Was_ there some significant change between 4.2.x & 4.3.6 relating to CIS?

**Comment by Machi3mfl** [comment]
I'm glad to hear that. I don't know specifically all the changes related to CIS. But I suggest you read the release notes in our web. I leave you the link here: [https://documentation.wazuh.com/current/release-notes/release-4-3-6.html](https://documentation.wazuh.com/current/release-notes/release-4-3-6.html)
@sempervictus thanks for your feedback.
Best regards

**Comment by sempervictus** [comment]
@Machi3mfl - the issue isn't resolved, i still cannot access CIS benchmarks in any of the three environments running 4.3.6.
I'm seeing an error about invalid characters:
![image](https://user-images.githubusercontent.com/1331084/182363226-9b2c8630-b929-4417-b095-eefa848738e5.png)
which is a yellow->red flag when dealing with SQL: might mean you have an injectable surface in your database.
That error is generated _simply by clicking on the host's findings_ and there _are_ findings, so CIS is being run:
![image](https://user-images.githubusercontent.com/1331084/182363457-d15d20f3-8533-49be-9ead-f8f494894329.png)
... we just can't access them.
Do you guys run injection tests against your app? Fuzzing the stack might yield some interesting stuff if SQL queries can be impacted from the contents of Kibana's presentation layer since those are potentially user-controlled (from the DOM).

**Comment by Machi3mfl** [comment]
Hi @sempervictus, Can you tell me what specific query are you trying to do? If you can upload a short video with the use cases could be great. Thanks you

**Comment by sempervictus** [comment]
None, i am simply clicking on the CS benchmark row in the page and getting those errors (2nd screenshot).

**Comment by Machi3mfl** [comment]
Hi @sempervictus, I was researching your use case and I see that when you enter into the `"CIS Benchmark for Windows Server 2019 RTM"` details table you don't have items to show `("No found items")` (In both screenshots).  This means that the request to the `/sca` API endpoint with the policy selected (CIS Windows Server) is falling.  This can bring problems when you are trying to use the search bar and filter the results. 
If you want, you can check your browser console and check the request details to try to find out why the request for the sca policy is falling.
The request should look like the below screenshot. You will find in the tab `Payload` the request params and in the `Preview/Response` the returned data.
<img width="1439" alt="Screen Shot 2022-08-03 at 10 14 30" src="https://user-images.githubusercontent.com/6089438/182616798-3f0f408f-9bb4-4a5b-84d2-8001581487c1.png">
This is important to get more context about your environment because all the environments are different and can have different kinds of errors.

**Comment by sempervictus** [comment]
Unfortunately the issue persists in 4.3.9.
Back-end logs from Kibana say:
```json
Dec 06 20:25:08 host node[3136382]: {"type":"error","@timestamp":"2022-12-06T20:25:08Z","tags":[],"pid":3136382,"level":"error","error":{"message":"Internal Server Error","name":"Error","stack":"Error: Internal Server Error\n    at HapiResponseAdapter.toError (/usr/share/kibana/src/core/server/http/router/response_adapter.js:132:19)\n    at HapiResponseAdapter.toHapiResponse (/usr/share/kibana/src/core/server/http/router/response_adapter.js:86:19)\n    at HapiResponseAdapter.handle (/usr/share/kibana/src/core/server/http/router/response_adapter.js:81:17)\n    at Router.handle (/usr/share/kibana/src/core/server/http/router/router.js:164:34)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":null,"query":{},"pathname":"/api/request","path":"/api/request","href":"/api/request"},"message":"Internal Server Error"}
Dec 06 20:25:08 host node[3136382]: {"type":"response","@timestamp":"2022-12-06T20:25:08Z","tags":[],"pid":3136382,"method":"post","statusCode":500,"req":{"url":"/api/request","method":"post","headers":{"host":"127.0.0.1:5601","connection":"close","content-length":"78","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0","accept":"application/json, text/plain, */*","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","content-type":"application/json","kbn-xsrf":"kibana","origin":"https://host.fqdn.local","dnt":"1","referer":"https://host.fqdn.local/app/wazuh","sec-fetch-dest":"empty","sec-fetch-mode":"cors","sec-fetch-site":"same-origin"},"remoteAddress":"127.0.0.1","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0","referer":"https://host.fqdn.local/app/wazuh"},"res":{"statusCode":500,"responseTime":71,"contentLength":9},"message":"POST /api/request 500 71ms - 9.0B"}
```
The browser console just shows a 500 error but the endpoint is `/api/request` not `/sca` as suggested:
![image](https://user-images.githubusercontent.com/1331084/206017393-44092472-dd48-476e-97b2-a08ac4cb10e0.png)

**Comment by rneto12** [comment]
I have the same issue with the CIS Benchmark for Windows 10 21H2 on wazuh 4.3.10.

This error appears only in "Inventory" tab, If I change to "Events" I can find all data.

![image](https://user-images.githubusercontent.com/5262260/215578693-b9aa181e-8c35-41ca-8d31-847d9721d033.png)

**Comment by sempervictus** [comment]
@AlexRuiz7 - could this get some love please? It seems to have something to do with how Kibana passes data to sqlite3 query for the agents DB...
