### ISSUE TITLE
TypeError in the browser's developer console

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-kibana-app#4346]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3.6   | 7.x     | 4307 | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Firefox|

**Description**
When accessing `Home` from another Opensearch module we get:

```
TypeError: NetworkError when attempting to fetch resource.
    Wrapper https://demo-436-info-wazuh-5d79494dfa1b98ee.elb.us-west-1.amazonaws.com/1/bundles/core/core.entry.js:6
    _createSuperInternal https://demo-436-info-wazuh-5d79494dfa1b98ee.elb.us-west-1.amazonaws.com/1/bundles/core/core.entry.js:6
    HttpFetchError https://demo-436-info-wazuh-5d79494dfa1b98ee.elb.us-west-1.amazonaws.com/1/bundles/core/core.entry.js:6
    _callee3$ https://demo-436-info-wazuh-5d79494dfa1b98ee.elb.us-west-1.amazonaws.com/1/bundles/core/core.entry.js:6
    tryCatch https://demo-436-info-wazuh-5d79494dfa1b98ee.elb.us-west-1.amazonaws.com/1/bundles/plugin/indexManagementDashboards/indexManagementDashboards.plugin.js:1
    invoke https://demo-436-info-wazuh-5d79494dfa1b98ee.elb.us-west-1.amazonaws.com/1/bundles/plugin/indexManagementDashboards/indexManagementDashboards.plugin.js:1
```

**Preconditions**
1. Demo environment

**Steps to reproduce**
1. Navigate to any module outside Wazuh
2. Click on `Home`

**Expected Result**
1. No errors in the browser's developer console

**Actual Result**
1. TypeError

**Screenshots**

https://user-images.githubusercontent.com/80041853/179730835-93aded68-5947-4e22-8e0b-21a0549cb580.mp4

**Comment by chantal-kelm** [comment]
In `public/plugin.ts` a get is done with a kibana resource '`core.http.get(`/api/check-wazuh`);`'.
That resource fails in Chrome and Firefox browsers.
The kibana core get resource is set up to catch the error with an `HttpFetchError` class that is a child of the Node Error class. Which is compatible only with browsers with V8 engine.
For this reason in Chrome it shows the error in the console as a debug and in Firefox it shows it in the console as an unrecognized error.

Proposed solution: I added a try catch in `public/plugin.ts` when making the request `'core.http.get(`/api/check-wazuh`);'` so you can catch the error when the browser does not work with a V8 engine.

**Steps to test:**
-Click on the hamburger menu
-Click on dashboard
-Click on home
-Click on Wazuh
-Check that the console does not show: 'TypeError: NetworkError when attempting to fetch resource.'

https://user-images.githubusercontent.com/99441266/181495074-7394bc97-b81b-43ae-ac15-00dc1e134231.mp4
