### ISSUE TITLE
`wazuh.yml` in-file documentation

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#4349]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3.6 | wazuh-dashboard| strep-by-step installation | Centos8 |

While working on https://github.com/wazuh/wazuh/issues/14323, using the [step-by-step](https://documentation.wazuh.com/current/installation-guide/wazuh-dashboard/step-by-step.html) guide the default `wazuh.yml` present in our package has an option related to the active modules. We need to verify whether these options work as intended.

Please review https://github.com/wazuh/wazuh-kibana-app/issues/3640 and take it into account.

**Comment by yenienserrano** [comment]
According to the tests I did, the activation of the modules in the wazuh.yml is working.

![image](https://user-images.githubusercontent.com/63758389/181486118-588e24e9-abb8-4fad-9d55-b7d5497159fc.png)

![image](https://user-images.githubusercontent.com/63758389/181486235-2e87d79e-5eab-4c40-9768-a096cc58b3d9.png)

![image](https://user-images.githubusercontent.com/63758389/181486252-f9d35912-7293-4431-aadf-68ec8b4bd425.png)

**Comment by AlexRuiz7** [comment]
I've been reviewing the `wazuh.yml` in-file documentation and found some issues that need to be resolved:

- [ ] The URL to the Wazuh documentation page for this configuration file is outdated. Correct URL is https://documentation.wazuh.com/current/user-manual/wazuh-dashboard/config-file.html
- [ ] The documentation contains grammar errors.
- [ ] Default values for some settings are wrong in the documentation.
Related issue: TBD
- [ ] Some settings described here are not documented in the documentation page.
   - Every [cron](https://g.co/kgs/Mh1TYS) related setting, included these related to the wazuh-statistics index.
   - Both settings related to the agents' enrollment.
   - disabled_roles: Related issue: #3164
- [ ] Some settings described here have been deprecated.
Related issue: #3911
