### ISSUE TITLE
Devel Tools to run Wazuh-API commands

### ISSUE THREAD

**Issue by jlruizmlg** [wazuh/wazuh-kibana-app#435]
We can find in Kibana an option to run commands through the API to Elasticsearch, it would be very convenient to have the same option inside Wazuh-APP to run commands through the Wazuh API to the manager inside the Wazuh-APP.
![dev tools](https://user-images.githubusercontent.com/13950509/39448207-3b5667f2-4c92-11e8-8510-da8834aa22c0.png)

**Comment by jesusgn90** [comment]
Hello team, this feature is being developed just now. @jlruizmlg you could track the progress on this branch: https://github.com/wazuh/wazuh-kibana-app/tree/3.2-dev-tools

For now, we have a prototype with a basic usage and a non-style interface. We are currently working on the way we parse the query and the way we show the output. Now it's validating most of possible inputs, discarding wrong inputs and accepting queries like this:

```js
/foo?bar=12&fuzz=tar
```

Next step is to accept queries like this (Kibana like):

 ```js
/foo
{
  "bar":2,
  "fuzz": "tar"
}
```

The feature is coming soon but I don't know a concrete date to be released. Track the citated branch and this issue comments to stay updated.

Regards,
Jesús

**Comment by jesusgn90** [comment]
__Update:__

![devtools1](https://user-images.githubusercontent.com/8860227/39763103-9078458e-52dc-11e8-9506-38b7787c5fb8.png)

Hello team, a brief summary:

- Collapsable elements
- Different queries on the same place
- Storing current state, this way the user could store its own queries for further usages
- Matching query groups, any line of a group is valid to launch the query
- Going to settings whenever there is no API
- Initializing default value if there is no previous value
- Closer to Kibana dev tool

Regards,
Jesús

**Comment by jesusgn90** [comment]
Done here https://github.com/wazuh/wazuh-kibana-app/pull/449
