### ISSUE TITLE
Unable to see anything in Intergrity Monitoring dashboard

### ISSUE THREAD

**Issue by luffysan92** [wazuh/wazuh-kibana-app#4354]
I have downloaded and installed wazuh OVA 4.3.5 and agents are installed and running. But I dont see anything on the Dashboard for Integrity monitoring. My agent ossec.config has been edited to report changes. I see events in the Inventory that have been tracked but nothing in the Dashboard. I am New to Wazuh so appreciate help. 

![image](https://user-images.githubusercontent.com/10840500/180581350-049c567b-8a8c-4e7c-81ba-19e174119099.png)

**Comment by AlexRuiz7** [comment]
Hello @luffysan92 

Welcome! Thanks for using Wazuh.

I'll help you out with this.


By default, File Integrity Monitoring is disabled for the agents, so you'll need to configure and enable it by editing the agent's `ossec.conf` file, which I think you have already done, but let's start from there and double-check the configuration is correct. [Here](https://documentation.wazuh.com/current/user-manual/capabilities/file-integrity/fim-configuration.html#configuring-syscheck-basic-usage), you can find lots of examples about configuring FIM, check it out.

```xml
  <!-- File integrity monitoring -->
  <syscheck>
    <disabled>no</disabled>
```

Make sure to have it enabled.

Let me know when you have checked that.

**Comment by luffysan92** [comment]
Hi @AlexRuiz7 ,

Thanks for your reply. Please find snip of my agent ossec.conf file for File Integrity monitoring below

![image](https://user-images.githubusercontent.com/10840500/180875933-a7ae8fd2-0e18-46f2-8c6f-691328dbbe00.png)

Cant wait to configure more when I sort out the dashboard. Let me know what else you might need to troubleshoot.

Appreciate your help.

Cheers

**Comment by AlexRuiz7** [comment]
Hello @luffysan92 

You won't be able to see any data until there is actually something to show, this is, that some alerts are generated due to changes in the monitored directory.

Here's an example.

I configured my Linux agent to monitor the `/tmp` directory. Then, I created, modified and deleted a test file.

Here's the result:
![image](https://user-images.githubusercontent.com/15186973/180992916-62c39634-c41c-42c3-a247-a32e61d71693.png)

**Comment by luffysan92** [comment]
Hi @AlexRuiz7 

In my previous snip you can see at the bottom I have added 
<directories check_all="yes" realtime="yes" report_changes="yes">C:\FileIntergritycheck</directories>
to monitor folder in the c drive.

Changes are reflected in Inventory>Files
![image](https://user-images.githubusercontent.com/10840500/181121782-e0dbc452-9cc3-465f-b81b-b1c9ee7408fd.png)

But still nothing in the dashboard even after I've added file syscheck.path and rule.description 
![image](https://user-images.githubusercontent.com/10840500/181121876-2c26f965-63a6-4ef2-bd46-fa85f85666fa.png)

Thanks

**Comment by AlexRuiz7** [comment]
Hello @luffysan92 

Are you able to see events in other dashboards, as Security Events? 

If not, there might be a problem forwarding data to the UI. 

To check so, check if the alerts are generated in the `alerts.log` file, or i the `alerts.json`. You can use [this as a guide](https://documentation.wazuh.com/current/user-manual/capabilities/log-data-collection/how-it-works.html#alert).

Another way to check it is by checking the indices in order to know if the store events. In this case, you need to navigate to the platform Dev Tools (not Wazuh's), and execute `GET _cat/indices`. Check the `wazuh-alerts-4x-{most_recent_date}` index.

Regards,
Alex

**Comment by luffysan92** [comment]
Hi @AlexRuiz7 

There are alerts in both alerts.json and alerts.log.

Here the results for `GET _cat/indices`

#! Deprecation: this request accesses system indices: [.opendistro_security], but in a future major version, direct access to system indices will be prevented by default
green open wazuh-alerts-4.x-2022.06.15     qI9lTsKTSWeNQ_SLnIvQ 3 0  429 0     1mb     1mb
green open wazuh-alerts-4.x-2022.06.29     9UAO9xXsSZi9nEu5lEvw 3 0  853 0   2.6mb   2.6mb
green open wazuh-monitoring-2022.28w       YMLhuURnS8C-1K2O_gGg 1 0 1406 0 818.2kb 818.2kb
green open wazuh-monitoring-2022.26w       vpmeDU-oSSuYDcL9UB7Q 1 0    7 0  66.4kb  66.4kb
green open .opendistro-reports-definitions y9sNqeZKTO6NfY_vp2zw 1 0    0 0    208b    208b
green open .opendistro-reports-instances   _Ka4zspOR6WYh1jaVoXQ 1 0    0 0    208b    208b
green open .opendistro_security            o0PKJjALTNyw4og11Z0Q 1 0    9 8  92.6kb  92.6kb
green open .kibana_1                       qunmYO3KTlWI95KRgGgg 1 0    6 8  65.1kb  65.1kb
green open wazuh-monitoring-2022.29w       lkNKPDlYSd670A5g4dSQ 1 0 2986 0 957.1kb 957.1kb
green open wazuh-monitoring-2022.30w       3mkVu6VJR2ib99drUeig 1 0 1480 0 954.6kb 954.6kb
green open wazuh-monitoring-2022.24w       OkldITIHTx2qYqTH4dTQ 1 0    0 0    208b    208b
green open wazuh-statistics-2022.30w       -1BjgLeATrey8EjFydojuA 1 0 1762 0   2.6mb   2.6mb
green open wazuh-statistics-2022.28w       QZDr74onTd6l6tEKXtkA 1 0 2803 0   1.5mb   1.5mb
green open wazuh-statistics-2022.29w       D1zdUA_tTqygFqMVMiyQ 1 0 4027 0   1.4mb   1.4mb
green open wazuh-statistics-2022.26w       bz3l7XBGTxGkDVM_1Kjw 1 0   19 0 124.2kb 124.2kb

**Comment by luffysan92** [comment]
> Hello @luffysan92
> 
> Are you able to see events in other dashboards, as Security Events?
> 
> If not, there might be a problem forwarding data to the UI.
> 
> To check so, check if the alerts are generated in the `alerts.log` file, or i the `alerts.json`. You can use [this as a guide](https://documentation.wazuh.com/current/user-manual/capabilities/log-data-collection/how-it-works.html#alert).
> 
> Another way to check it is by checking the indices in order to know if the store events. In this case, you need to navigate to the platform Dev Tools (not Wazuh's), and execute `GET _cat/indices`. Check the `wazuh-alerts-4x-{most_recent_date}` index.
> 
> Regards, Alex

No events in other Dashboards too like Security Events.

Cheers

**Comment by AlexRuiz7** [comment]
Hello @luffysan92 

In that case, it's very possible that the data is not being indexed correctly.


Please, run the following command:

```sh
filebeat test output
```

Share the output with me.

Regards,
Alex

**Comment by luffysan92** [comment]
Hi @AlexRuiz7 

this is the result

[root@wazuh-server /]# filebeat test output
elasticsearch: https://127.0.0.1:9200...
  parse url... OK
  connection...
    parse host... OK
    dns lookup... OK
    addresses: 127.0.0.1
    dial up... OK
  TLS...
    security: server's certificate chain verification is enabled
    handshake... OK
    TLS version: TLSv1.3
    dial up... OK
  talk to server... ERROR 401 Unauthorized: Unauthorized
[root@wazuh-server /]#

**Comment by AlexRuiz7** [comment]
Hello @luffysan92 

Sorry for the delay, I've been out for a few days.

That confirms there is a problem with Filebeat, and more concretely with the credentials.

Check the user and password set in the file `/etc/filebeat/filebeat.yml`. These credentials must match the credentials used in the files `/etc/wazuh-dashboard/opensearch_dashboards.yml` and 

All components included in the OVA are configured to work out-of-the-box, without the need to modify any settings, so I assume you have changed the user and/or password by hand.

Rollback to default user and password or use [this tool](https://documentation.wazuh.com/current/user-manual/securing-wazuh/wazuh-indexer.html) to change credentials.

Regards,
Alex

**Comment by luffysan92** [comment]
Hi @AlexRuiz7 welcome back.

Yes I did change the username and password for filebeat. I think I was trying to change the password for wazuh as I couldnt because of error Failed to reset password. {"status":"FORBIDDEN","message":"Resource 'admin' is read-only."}.

But I think it still wasn't working then. I should've noted the previous filebeat password and username but it was something like ${username} and ${password}. Is that the default? 

So the `/etc/wazuh-dashboard/opensearch_dashboards.yml` password and username were # commented out. I've removed the comment and changed the password and username to be the same as filebeat. 

Still talk to server error even after restarting filebeat.

**Comment by luffysan92** [comment]
Its working.

Thanks for your help @AlexRuiz7 . I had to change the filebeat.yml username and password to be the same with the credentials that i use to login wazuh web interface. Web interface credentials might have been the default or changed by the other guy. Didn't think much of it because credentials seemed as default as they come. Restarted all and now loading. Looking forward to exploring wazuh and capabilities. Hope this helps someone else

**Comment by AlexRuiz7** [comment]
Awesome. I'm so glad to hear that.

Thank you very much for your patience. I hope you find Wazuh useful.

Please, get in touch with us if you need assistance with anything else.
