### ISSUE TITLE
403 on latest release

### ISSUE THREAD

**Issue by fluential** [wazuh/wazuh-kibana-app#436]
```
wget https://packages.wazuh.com/wazuhapp/wazuhapp-3.2.2_6.2.4.zip                                                     mcz
--2018-05-01 15:02:38--  https://packages.wazuh.com/wazuhapp/wazuhapp-3.2.2_6.2.4.zip
Resolving packages.wazuh.com (packages.wazuh.com)... 54.230.108.44, 54.230.108.61, 54.230.108.139, ...
Connecting to packages.wazuh.com (packages.wazuh.com)|54.230.108.44|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2018-05-01 15:02:39 ERROR 403: Forbidden.
```

**Comment by JuanjiJG** [comment]
Hello @fluential,

We're very sorry for this error. Our latest available Wazuh app version is for Wazuh 3.2.1 and Kibana 6.2.4. We've addressed this error on our README file. Thanks for letting us know.

Our next release will be available on the next days, we'll let you know when it's available.

Regards,
Juanjo

**Comment by Max0r** [comment]
Having this issue with 3.7.0 as well:

https://packages.wazuh.com/wazuhapp/wazuhapp-3.7.0_6.4.2.zip giving 403 -- is this not released yet either?

**Comment by jesusgn90** [comment]
Hi @Max0r,

Our latest release is for Wazuh 3.6.1 + Elastic 6.4.3. Your desired link is https://packages.wazuh.com/wazuhapp/wazuhapp-3.6.1_6.4.3.zip. You must install Wazuh 3.6.1 and Elastic stack 6.4.3 to make the app work properly.

Regards
