### ISSUE TITLE
Develop performance script tests

### ISSUE THREAD

**Issue by Mayons95** [wazuh/wazuh-kibana-app#4366]
## Description
This issue is created to track the effort to develop scripts to measure the performance of the modules of the app.

We need to create scripts that do the following:

- Login to the platform (Kibana, OSD, WZD).
- Navigate to the Wazuh App.
- Navigate to a particular module (FIM, AWS, GitHub, ...)
- Check the visualizations (charts, tables, ...) are properly loaded (contains data).
- If the module has submodules (like the MITRE Att&ck module), create additional tests for these submodules. 

## Summary

> Note: All the scripts are using CSS selectors for Wazuh Kibana app development environment.

We need to create scripts for the following modules:

- [x] File Integrity Monitoring
  - #4368
- [x] Security Events
  - #4369
- [x] MITRE Att&ck
  - #4371
- [x] Vulnerabilities
  - #4372
- [x] PCI-DSS
    - #4374
    - #4375
- [x] GDPR
    - #4374
    - #4375
- [x] NIST
    - #4374
    - #4375
- [x] TSC
    - #4375
- [x] HIPAA 
     - #4371 
- [x] Policy Monitoring
      - #4371 
- [x] SCA   
    - #4377

**Comment by Mayons95** [comment]
Security events, Integrity Monitoring and Mitre atta&ck are covered in these branches:

feature/security-events-module-performance-test
feature/mitre-attack-test-module
feature/performance-add-integrity-monitoring-module

**Comment by mauceballos** [comment]
Vulnerabilities Modules

- Inventory
- Events

**Comment by mauceballos** [comment]
PCI-DSS && GDPR modules

- Controls
- Dashboard
- Events

branches:

**Comment by mauceballos** [comment]
TSC module and  following tabs:

- Controls
- Dashboard
- Events

branch: https://github.com/wazuh/wazuh-kibana-app/tree/feature/TSC

**Comment by AlexRuiz7** [comment]
Hello guys!

Please check this review: https://github.com/wazuh/wazuh-kibana-app/issues/4155#issuecomment-1207833522

Keep it up the great work.

Regards,
Alex

**Comment by Mayons95** [comment]
Hello guys, did you agree if we close this issue to end the first part of the scripting and when we want to continue with this we open a new issue?
C.C @asteriscos @AlexRuiz7 @mauceballos

**Comment by AlexRuiz7** [comment]
LGTM!
