### ISSUE TITLE
Allowing configuration options for "wazuh-monitoring" indices management

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#440]
Hello team,

we need to improve the way we manage the "wazuh-monitoring" indices, each user could has its own preferences. 

- Change the frequency we are inserting data on the indices
  - The frequency needs to be configurable
- The user should be able to enable/disable the monitoring indices at any time
  - If disabled, the _Agents status_ visualization is replaced by the metrics from _Agents preview_ 
  - If disabled, it'll be disabled for the whole system, not only a specific API entry

**Comment by jesusgn90** [comment]
@JPLachance this is the issue I meant, you could stay updated tracking the branch: https://github.com/wazuh/wazuh-kibana-app/tree/3.2-better-wz-monitoring

Regards,
Jesús

**Comment by jesusgn90** [comment]
__Update__:

From last changes now we can enable/disable _wazuh-monitoring_ using the configuration file:

```yml
wazuh.monitoring.enabled: true / false
```

Default is `true`.

Now if it is disabled:

- No new _wazuh-monitoring_ are created
- The template is still being inserted
- The overview controller is adapted to fetch this value
  - The overview view is showing the visualization or the metrics depending on the value
- If an index was created before we disable the feature, the index will live unless we delete it but no new data will be inserted on it

Next step is to parse the frequency given in seconds to cron format, then we can say this is done.

```yml
wazuh.monitoring.frequency: 3600
```

Regards,
Jesús

**Comment by jesusgn90** [comment]
__Update:__

Now we are parsing seconds input from the configuration file. This is how we do it:

- If value is < 60, frequency is 1 insertion / minute
- If value is >= 84600, frequency is 1 insertion / hour
- If value is >= 60 and < 84600, frequency is 1 insertion / calculated minutes
- If no value or wrong value or something goes wrong while parsing, frequency is 1 insertion / hour

This value could be modified multiple times at the same day. 

If the feature is disabled this value doesn't matter since it won't be applied.

Best regards,
Jesús

**Comment by JPLachance** [comment]
Greetings,

I don't understand the number of insertion per frequency VS the number of monitoring indices created by your application. In my original issue (https://github.com/wazuh/wazuh-kibana-app/issues/344), my concern was the fact the Wazuh Kibana application is creating one index per day for monitoring events. Instead, we would like to create one index per week. We need that simply because creating an index per day could lead us to have too many indices in our Elasticsearch cluster.

So, will we be able to configure the frequency of monitoring index creation? 😄 

Thanks for your help,
Jean-Philippe

**Comment by jesusgn90** [comment]
Hello @JPLachance ,

Using this feature your index creation will still be one per day. What we have added now is:

- Now you are able to change the static frequency we had hardcoded to 10 minutes by your desired frequency (from 1 min to 23 h 59 min). 
- Also you could fully disable the wazuh-monitoring features, replacing the visualization Agents status by some useful metrics from the Wazuh API.

Regarding to change the number of created indices, it needs to wait for further releases, it's not as simple as we want. Any case we'll study it for all use cases and what implies if we modify the creation frequency. Have an index per day is useful for emergency cases, we can delete only one day, etc.

Regards,
Jesús

**Comment by jesusgn90** [comment]
Done here https://github.com/wazuh/wazuh-kibana-app/pull/441
