### ISSUE TITLE
Release 4.3.7 RC1 - Wazuh UI Manual Testing - Kibana 7.10.2, 7.16.x, 7.17.x, WZD - Revision 4308

### ISSUE THREAD

**Issue by Mayons95** [wazuh/wazuh-kibana-app#4402]
| Test   | Chrome | Safari | Firefox | Package |
|--------|--------|--------|---------|---------|
| Test 1 | 🟢/🔴  | 🟢/🔴 | 🟢/🔴    | 🟢/🔴  |
 
Status legend:
⚫ - None
🔴 - Rejected
🟢 - Approved

In the case of 🔴, create and link the issue. 

### Change Log
All notable changes to the Wazuh app project will be documented in this file.

Wazuh v4.3.7 - Kibana 7.10.2, 7.16.x, 7.17.x - Revision 4308
### Fixed
Wazuh.yml review: fixed link to web documentation, improved in-file documentation and fixed some grammatical errors. https://github.com/wazuh/wazuh-kibana-app/pull/4378 https://github.com/wazuh/wazuh-kibana-app/pull/4399
Fixed an error during the generation of a group's report, if the request to the Wazuh API fails https://github.com/wazuh/wazuh-kibana-app/pull/4350
Fixed a problem with the group's report, when the group has no agents https://github.com/wazuh/wazuh-kibana-app/pull/4350
Fixed path in logo customization section https://github.com/wazuh/wazuh-kibana-app/pull/4352
Fixed a TypeError in Firefox. Change the Get request that was made with a Kibana core.http.get(/api/check-wazuh) resource to the WzRequest.genericReq resource and it no longer fails, also add a test capture to public/plugin.ts that wraps the request and in case of failure, the error is detected when the browser does not work with the V8 engine. https://github.com/wazuh/wazuh-kibana-app/pull/4362
Fixed an error of an undefined username hash related to reporting when using Kibana with X-Pack and security was disabled https://github.com/wazuh/wazuh-kibana-app/pull/4358
Fixed persistence of the plugin registry file between updates https://github.com/wazuh/wazuh-kibana-app/pull/4359
Fixed searchbar error on SCA Inventory table https://github.com/wazuh/wazuh-kibana-app/pull/4367
Fixed a routes loop when reinstalling Wazuh indexer https://github.com/wazuh/wazuh-kibana-app/pull/4373
Fixed Wazuh restart UI https://github.com/wazuh/wazuh-kibana-app/pull/4365
### Removed
Removed the use of manager_host field related to agent information of Wazuh API responses, which is obsolete https://github.com/wazuh/wazuh-kibana-app/pull/4350

### [4293](https://github.com/wazuh/wazuh-kibana-app/issues/4293) Infinite loop trying to check alerts index patterns after reinstalling Wazuh indexer
Happy path steps:

Using a Wazuh stack deployment (Wazuh dashboard, Wazuh indexer, Wazuh server), configure and start de the components. The Wazuh indexer should be in an independent machine.
Access to Wazuh dashboard and navigate to Wazuh plugin, configure the API host to work as expected. Secure the index pattern related to Wazuh are created. Keep the browser tab in the Wazuh plugin.
Remove, reinstall and start the Wazuh indexer using the Wazuh install assistant following the next steps:

This could be reproduced removing elasticsearch or wazuh-indexer container and rebuild it again

Returns to the browser tab that has the Wazuh plugin and navigates to another plugin section. The plugin health check should run and it should finish each check successfully, then it should redirect to /overview plugin path and instantly should redirect to the /health-check path again.

### [4359](https://github.com/wazuh/wazuh-kibana-app/pull/4359) Fix modules settings persistence between updates

Manual
Same plugin version and revision, restart the plugin platform. The registry file should not be changed.
For different plugin versions or revisions, restart the plugin platform. The registry file should be rebuilt and keeps the host configuration.
Different plugin version or revision removes some extension of any host in the registry file, and restart the plugin platform. The registry file should be rebuilt and keeps the host configuration. The removed extension should be included in the host and have the default value.

### [4337](https://github.com/wazuh/wazuh-kibana-app/issues/4337) Wrong path for Wazuh logo customization
Given the user is in Wazuh Kibana App.
When the user navigate to Settings --> Configuration --> Logo Customization
Then on the Logo Customization section,  ‘/usr/share/wazuh-dashboard/plugins/wazuh/public/assets/’ url of the path is displayed.

### [4346](https://github.com/wazuh/wazuh-kibana-app/issues/4346) TypeError in the browser's developer console 

Given the user is in Wazuh Kibana App.
And The user opens the developer console of the dev tool on the browser
When the user navigates any modules outside Wazuh
And the user clicks the Home button
Then no error in the browser's developer console is displayed

### [4350](https://github.com/wazuh/wazuh-kibana-app/pull/4350) Fixed errors in group reports
Scenario: Error due to accessing a property of undefined
Given the user is in Wazuh Kibana App.
And Logged user in Management/Groups//Information, wait the time to the Wazuh API token expires.
When The user clicks on the "Export PDF" button.
Then The PDF should be generated without errors. Check the generated PDF.

Scenario: Missing agents in the agent in the group table of group report.
Given the user is in Wazuh Kibana App.
And the group with more than 500 agents.
When The user clicks on the "Export PDF" button.
Then The PDF should be generated without errors and it should contain all the agents in the group displayed in a table.

### [4181](https://github.com/wazuh/wazuh-kibana-app/issues/4181) Short refresh timeout on manager restart 
Given the user is in Wazuh Kibana App
And the user navigates to Management --> Configuration
When the user selects the Edit Configuration link
Then the manager configuration XML file to edit is displayed
When the user finds and edits the vulnerability detector tag
And the user changes enable tag with No value
And the user selects the Save button
Then the manager configuration is saved
When the user selects the restart manager button
And the user confirms the restart manager
Then the wazuh app is restarted and the error is not displayed

### [4340](https://github.com/wazuh/wazuh-kibana-app/issues/4340) 4.3.5 unable to execute SQL Query for Windows CIS Benchmark View 
Given the user is in Wazuh Kibana App
And the user navigates to Modules  --> SCA
When the user selects the agent
Then the inventory tab is displayed
When the user writes on the filter or search field
Then the dropdown options are displayed 
And no error on the dropdown options is displayed

### [4277](https://github.com/wazuh/wazuh-kibana-app/issues/4277) Centralized service to restart Wazuh 

Scenario: Install from [Cluster Mode](https://documentation.wazuh.com/current/installation-guide/wazuh-server/step-by-step.html).
Given the user is in Wazuh Kibana App
And the wazuh app was installed on cluster mode
And the user navigates to management->configuration
When the user selects the Edit Configuration link
Then the manager configuration XML file to edit is displayed
When the user finds and edits the vulnerability detector tag
And the user changes enable tag with No value
And the user selects the Save button
Then the manager configuration is saved
When the user selects the restart manager button
And the user confirms the restart manager
Then the wazuh node is restarted
When the user navigates to Managements/Rules
Then the user is redirected correctly.

Scenario: Cluster/Manager installation
Given the user navigates to Management/Rules
When the user add a new rule file
And the user restart Wazuh 
Then the user can navigate to another module.

Scenario: Install from [Manager Mode](https://documentation.wazuh.com/current/deployment-options/elastic-stack/distributed-deployment/elasticsearch-cluster/index.html).
Given the user is in Wazuh Kibana App
And the wazuh app was installed on Manager mode
And the user navigates to management->configuration
When the user selects the Edit Configuration link
Then the manager configuration XML file to edit is displayed
When the user finds and edits the vulnerability detector tag
And the user changes enable tag with No value
And the user selects the Save button
Then the manager configuration is saved
When the user selects the restart manager button
And the user confirms the restart manager
Then the wazuh app is restarted 
And no error message is displayed 
When the user navigates to management -> rules
Then the module section is displayed
And no health check is displayed

### [4349](https://github.com/wazuh/wazuh-documentation/issues/5500) wazuh.yml in-file documentation 

Test Comment: This test is to check the documentation, so with one complete check it’s consider pass.

Access to: https://documentation.wazuh.com/current/user-manual/wazuh-dashboard/config-file.html

This URL  should redirect you to the current version of Wazuh Documentation 
Settings should be displayed:
checks.metaFields
checks.timeFilter
checks.maxBuckets
extensions.hipaa
extensions.nist
extensions.tsc
extensions.oscap
extensions.gcp
This setting allows hiding Wazuh for the specified roles. Related issue: [wazuh/wazuh-kibana-app#3164](https://github.com/wazuh/wazuh-kibana-app/issues/3164)
disabled_roles
Name for the sample alerts index
alerts.sample.prefix
[cron](https://g.co/kgs/Mh1TYS) related settings: these settings configure the behavior of background tasks performed by the App.
cron.prefix
cron.statistics.status
cron.statistics.apis
cron.statistics.interval
cron.statistics.index.name
cron.statistics.index.creation
cron.statistics.shards
cron.statistics.replicas
These settings are used in the agents' enrollment interactive helper.
enrollment.dns
enrollment.password
Custom logos
customization.logo.app
customization.logo.sidebar
customization.logo.healthcheck
customization.logo.reports
Settings should not be displayed
wazuh-version.*: deprecated since 4.3.0. To be removed completely.
api.selector: deprecated. To be removed.
admin: seems to be no longer used. I assume it's been deprecated.
timeout: default value is set to 8000. Actual value is 20000.
wazuh.monitoring.shards: default value is set to 2. Actual value is 1.
wazuh.monitoring.creation: default value is d (daily). Actual value is w (weekly).

**Comment by Mayons95** [comment]
| Test   | Chrome | Safari | Firefox | Package |
|--------|--------|--------|---------|---------|
| 4293 | 🟢| 🟢/🔴 | 🟢/🔴    | 🟢  | 4.3.7 - ODFE

**Comment by asteriscos** [comment]
| Test   | Chrome | Safari | Firefox | Package |
|--------|--------|--------|---------|---------|
| 4346 | 🟢| :black_circle:  | 🟢    | 4.3.7 - 7.16.0 - x-pack | 

https://github.com/wazuh/wazuh-kibana-app/issues/4346 TypeError in the browser's developer console

![image](https://user-images.githubusercontent.com/9343732/184938184-76e9e4d6-c645-4bf2-9e0e-6c9ddd984d6f.png)

**Comment by asteriscos** [comment]
| Test   | Chrome | Safari | Firefox | Package |
|--------|--------|--------|---------|---------|
| [5502](https://github.com/wazuh/wazuh-documentation/pull/5502) | 🟢| :black_circle:  | 🟢    | 4.3.7 - 7.16.0 - x-pack | 

wazuh.yml update #5502
![image](https://user-images.githubusercontent.com/9343732/184938833-dd3e7a5a-35dd-4ca8-8fc0-27a3cd4f6206.png)

**Comment by mauceballos** [comment]
| Test   | Chrome | Safari | Firefox | Package |
|--------|--------|--------|---------|---------|
| 4293 | 🟢| :black_circle:  | 🟢    | 4.3.7 - ODFE | 
| 4359 | :black_circle: | :black_circle:  | :black_circle:  | 4.3.7 - ODFE | 
| 4337| 🟢| :black_circle:  | 🟢    | 4.3.7 - ODFE | 
| 4346| 🟢| :black_circle:  | 🟢    | 4.3.7 - ODFE | 
| 4350 - 1| 🟢| :black_circle:  | 🟢    | 4.3.7 - ODFE | 
| 4350 - 2| :yellow_circle: | :black_circle:  | :yellow_circle:     | 4.3.7 - ODFE |
| 4181| :green_circle: | :black_circle:  | :green_circle:     | 4.3.7 - ODFE |
| 4340| :green_circle: | :black_circle:  | :green_circle:     | 4.3.7 - ODFE |
| 4277 -1| :green_circle: | :black_circle:  | :green_circle:     | 4.3.7 - ODFE |
| 4277 -2| :green_circle: | :black_circle:  | :green_circle:     | 4.3.7 - ODFE |
| 4349| :green_circle: | :black_circle:  | :green_circle:     | 4.3.7 - ODFE |

**Comment by Machi3mfl** [comment]
| Test   | Chrome | Safari | Firefox | Package |
|--------|--------|--------|---------|---------|
| 4293 | 🟢| :black_circle:  | 🟢    | 4.3.7 - 7.17.5 | 
| 4359 |🟢 | :black_circle:  | 🟢  | 4.3.7 - 7.17.5 | 
| 4337| 🟢| :black_circle:  | 🟢    | 4.3.7 - 7.17.5 | 
| 4346| 🟢| :black_circle:  | 🟢    | 4.3.7 - 7.17.5 | 
| 4350 - 1| 🟢| :black_circle:  | 🟢    | 4.3.7 - 7.17.5 | 
| 4350 - 2| 🟢 | :black_circle:  | 🟢     | 4.3.7 - 7.17.5 |
| 4181| :green_circle: | :black_circle:  | :green_circle:     | 4.3.7 - 7.17.5 |
| 4340| :green_circle: | :black_circle:  | :green_circle:     | 4.3.7 - 7.17.5 |
| 4277 -1| :green_circle: | :black_circle:  | :green_circle:     | 4.3.7 - 7.17.5 |
| 4277 -2| :green_circle: | :black_circle:  | :green_circle:     | 4.3.7 - 7.17.5 |
| 4349| :green_circle: | :black_circle:  | :green_circle:     | 4.3.7 - 7.17.5 |

### [4293](https://github.com/wazuh/wazuh-kibana-app/issues/4293) Infinite loop trying to check alerts index patterns after reinstalling Wazuh indexer
<details>

[Grabación de pantalla desde 17-08-22 11:56:00.webm](https://user-images.githubusercontent.com/6089438/185172483-d13124e7-a4a2-4eab-bf56-6c8849b8524b.webm)

</details>

### [4337](https://github.com/wazuh/wazuh-kibana-app/issues/4337) Wrong path for Wazuh logo customization
<details>

![image](https://user-images.githubusercontent.com/6089438/185157014-944d5c6b-f4d4-4e08-acc2-73d5db034d2b.png)

</details>

### [4346](https://github.com/wazuh/wazuh-kibana-app/issues/4346) TypeError in the browser's developer console 

<details>

![image](https://user-images.githubusercontent.com/6089438/185157797-bdf8be66-a5ad-40a1-8ff9-95b4f3b290c7.png)

</details>

### [4350](https://github.com/wazuh/wazuh-kibana-app/pull/4350) Fixed errors in group reports - Scenario 1

<details>

[Grabación de pantalla desde 17-08-22 11:20:39.webm](https://user-images.githubusercontent.com/6089438/185158590-970bccf8-7be0-47c3-b9b8-0bb50cebf57c.webm)

</details>
 
### [4350](https://github.com/wazuh/wazuh-kibana-app/pull/4350) Fixed errors in group reports - Scenario 2 - 500 agents

<details>


</details>

### [4181](https://github.com/wazuh/wazuh-kibana-app/issues/4181) Short refresh timeout on manager restart 

<details>

[Grabación de pantalla desde 17-08-22 11:48:50.webm](https://user-images.githubusercontent.com/6089438/185170901-445d3d0f-ebcd-4674-8dd3-54c44a3fc2cd.webm)
</details>

### [4340](https://github.com/wazuh/wazuh-kibana-app/issues/4340) 4.3.5 unable to execute SQL Query for Windows CIS 

<details>

[Grabación de pantalla desde 17-08-22 11:27:41.webm](https://user-images.githubusercontent.com/6089438/185160267-2da22d6b-1bcb-4f20-a7fb-0d42ed7794e8.webm)

</details>

### [4277](https://github.com/wazuh/wazuh-kibana-app/issues/4277) Centralized service to restart Wazuh 

<details>


### In Management > Configuration - Manager Mode
[Grabación de pantalla desde 17-08-22 11:33:43.webm](https://user-images.githubusercontent.com/6089438/185162957-7c0841dc-4566-43f2-b720-7c00064b6338.webm)

### In Management > Configuration - Cluster Mode
[Grabación de pantalla desde 17-08-22 11:38:08.webm](https://user-images.githubusercontent.com/6089438/185165657-fb23a7bd-f8aa-41ae-9332-9ea1243569d7.webm)

### In Management > Rules
 
[Grabación de pantalla desde 17-08-22 11:43:57.webm](https://user-images.githubusercontent.com/6089438/185168866-05fb798f-2a44-497c-b0be-d5d61066545d.webm)

### In Management > CDB Lists
[Grabación de pantalla desde 17-08-22 11:45:56.webm](https://user-images.githubusercontent.com/6089438/185169689-93b2809c-3ddd-4802-89f4-e22b7d1df2bf.webm)

</details>


### [4349](https://github.com/wazuh/wazuh-documentation/issues/5500) wazuh.yml in-file documentation 

<details>

![image](https://user-images.githubusercontent.com/6089438/185160792-46621625-1382-407e-829c-a1f44eb2298e.png)

</details>

**Comment by chantal-kelm** [comment]
| Test   | Chrome | Safari | Firefox | Package |
|--------|--------|--------|---------|---------|
| 4293 | 🟢| :black_circle:  | 🟢    | 4.3.7-7.16.3 - X-PACK | 
| 4359 | :black_circle: | :black_circle:  | :black_circle:  | 4.3.7-7.16.3 - X-PACK | 
| 4337| 🟢| :black_circle:  | 🟢    | 4.3.7-7.16.3 - X-PACK | 
| 4346| 🟢| :black_circle:  | 🟢    | 4.3.7-7.16.3 - X-PACK | 
| 4350 - 1| 🟢| :black_circle:  | 🟢    | 4.3.7-7.16.3 - X-PACK | 
| 4350 - 2| :black_circle: | :black_circle:  | :black_circle:     | 4.3.7-7.16.3 - X-PACK |
| 4181| :green_circle: | :black_circle:  | :green_circle:     | 4.3.7-7.16.3 - X-PACK |
| 4340| :green_circle: | :black_circle:  | :green_circle:     | 4.3.7-7.16.3 - X-PACK |
| 4277 | :green_circle: | :black_circle:  | :green_circle:     | 4.3.7-7.16.3 - X-PACK |
| 4349| :green_circle: | :black_circle:  | :green_circle:     | 4.3.7-7.16.3 - X-PACK |

#### 4293 Infinite loop trying to check alerts index patterns after reinstalling Wazuh indexer
<details>

https://user-images.githubusercontent.com/99441266/185177104-66527d18-a40c-4cde-b3bd-784ffe59fdcc.mp4

</details>

#### 4337 Wrong path for Wazuh logo customization
<details>

![Screenshot from 2022-08-17 10-30-19](https://user-images.githubusercontent.com/99441266/185169532-f172aec9-5581-4298-ba06-80f5dea40f21.png)

</details>

#### 4346 TypeError in the browser's developer console

<details>

![Screenshot from 2022-08-17 10-35-04](https://user-images.githubusercontent.com/99441266/185169891-a499a65b-5bed-41a6-b499-06276bfc1a75.png)

I don't see any type error on the console 
</details>

#### 4350 - Scenario 1 - Fixed errors in group reports

<details>

https://user-images.githubusercontent.com/99441266/185180432-578a1a83-b97a-4b57-946c-90d03cd23fe6.mp4

</details>

#### 4350 - Scenario 2

<details>


</details>

#### 4181 Short refresh timeout on manager restart

<details>

https://user-images.githubusercontent.com/99441266/185171193-37fe154a-ef1d-4299-af96-4358634a18af.mp4

</details>

#### 4340 4.3.5 unable to execute SQL Query for Windows CIS Benchmark View

<details>

https://user-images.githubusercontent.com/99441266/185177233-e77cd14b-81c6-4c01-8799-33e2cbff1ef9.mp4

</details>

#### 4277 Centralized service to restart Wazuh

<details>

Uploading restartvideo.mp4…

</details>

#### 4349 wazuh.yml in-file documentation

<details>

https://documentation.wazuh.com/current/user-manual/wazuh-dashboard/config-file.html

</details>

**Comment by Mayons95** [comment]
| Test   | Chrome | Safari | Firefox | Package |
|--------|--------|--------|---------|---------|
| 4293 | 🟢| :black_circle:  | 🟢    | 4.3.7 - WZD | 
| 4359 | :black_circle: | :black_circle:  | :black_circle:  | 4.3.7 - WZD | 
| 4337| 🟢| :black_circle:  | 🟢    | 4.3.7 - WZD | 
| 4346| 🟢| :black_circle:  | 🟢    | 4.3.7 - WZD | 
| 4350 - 1| 🟢| :black_circle:  | 🟢    | 4.3.7 - WZD | 
| 4350 - 2| :yellow_circle: | :black_circle:  | :yellow_circle:     | 4.3.7 - WZD |
| 4181| :green_circle: | :black_circle:  | :green_circle:     | 4.3.7 - WZD |
| 4340| :green_circle: | :black_circle:  | :green_circle:     | 4.3.7 - WZD |
| 4277 -1| :green_circle: | :black_circle:  | :green_circle:     | 4.3.7 - WZD |
| 4277 -2| :green_circle: | :black_circle:  | :green_circle:     | 4.3.7 - WZD |
| 4349| :green_circle: | :black_circle:  | :green_circle:     | 4.3.7 - WZD |

#### 4293 Infinite loop trying to check alerts index patterns after reinstalling Wazuh indexer
<details>

![Screenshot from 2022-08-16 12-01-36](https://user-images.githubusercontent.com/104914131/184934917-16fda0d3-6bda-4439-8e13-3910f5f9059b.png)
![Screenshot from 2022-08-16 13-42-10](https://user-images.githubusercontent.com/104914131/184935003-6058c68b-cb3e-4988-b7c6-103b0d5d44ed.png)

</details>

#### 4337 Wrong path for Wazuh logo customization
<details>

![Screenshot from 2022-08-16 14-18-13](https://user-images.githubusercontent.com/104914131/184940316-da3f35d0-f8dd-41c4-b510-6ccb1a4ef583.png)

</details>

#### 4346 TypeError in the browser's developer console

<details>

![image](https://user-images.githubusercontent.com/104914131/184941802-4267e7ad-df9b-4ee1-9e47-4101277c0af6.png)

I don't see any type error on the console 
</details>

#### 4350 - Scenario 1 - Fixed errors in group reports

<details>

![Screenshot from 2022-08-16 15-17-25](https://user-images.githubusercontent.com/104914131/184951356-1ced2717-d207-4eed-9013-2fc54f18f788.png)


</details>
 
#### 4350 - Scenario 2 - In Progress

<details>


</details>

#### 4181 Short refresh timeout on manager restart

<details>

[Screencast from 16-08-22 15:27:00.webm](https://user-images.githubusercontent.com/104914131/184952770-a4b16323-dbea-44c1-a923-7acc9b688efe.webm)


</details>

#### 4340 4.3.5 unable to execute SQL Query for Windows CIS Benchmark View

<details>

[Screencast from 16-08-22 15:34:30.webm](https://user-images.githubusercontent.com/104914131/184953843-30eb6cd5-9e07-47dc-ba99-3ca0a51f089f.webm)


</details>

#### 4277 -1 Centralized service to restart Wazuh

<details>

[Screencast from 16-08-22 15:44:06.webm](https://user-images.githubusercontent.com/104914131/184955627-1335c56b-ada1-4ae4-8c66-2ea09b256244.webm)


</details>

#### 4277 -2 Centralized service to restart Wazuh

<details>

[Screencast from 16-08-22 16:01:32.webm](https://user-images.githubusercontent.com/104914131/184961362-88889e8a-9475-487c-839e-83e7b1406734.webm)


</details>


#### 4349 wazuh.yml in-file documentation

<details>

https://documentation.wazuh.com/current/user-manual/wazuh-dashboard/config-file.html


</details>

**Comment by Mayons95** [comment]
Test Finished
