### ISSUE TITLE
Node down during node restarting isn't informed

### ISSUE THREAD

**Issue by mauceballos** [wazuh/wazuh-kibana-app#4404]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3.7  | 7.x    | 4xxx | ODFE, Xpack , Wzd|

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
When restarting a node. this disconnected during restart

**Steps to reproduce**
1. up the cluster with 3 or more workers 
2. install the wazuh app and up the environment
3. go to management/configuration and edit configuration
4. restart and in the same time stop a worker 
5 go to the app and check cluster list.

**Expected Result**

- Should indicate with a pop-up message or other key the worker/ running and stopped with icons, for this use case when It has more than 10 workers, the pop-up should have pagination.

**Actual Result**

-  The list of the cluster is shown, but the user is never told the worker stopped

**Screenshots**
<details>

![Screenshot from 2022-08-19 14-12-16](https://user-images.githubusercontent.com/76791841/185684211-e3803606-1209-421b-91c4-7fff55553649.png)

[Screencast from 19-08-22 14_09_40.webm](https://user-images.githubusercontent.com/76791841/185684266-ac839a95-43f8-4ee5-8351-9d73ae8c22bf.webm)

[Screencast from 19-08-22 15_04_29.webm](https://user-images.githubusercontent.com/76791841/185684286-8367c538-d1b4-4bca-9f76-226ecfd749a7.webm)

![Screenshot from 2022-08-19 15-02-40](https://user-images.githubusercontent.com/76791841/185684308-fa359bc7-ffcc-435b-aa6f-586a5f6a6c28.png)

</details>

**Additional context**

related and detected ([3178](https://github.com/wazuh/wazuh-qa/issues/3178#issuecomment-1217200688))

**Comment by gdiazlo** [comment]
Let's use the original issue:
- https://github.com/wazuh/wazuh-kibana-app/issues/4277 

The initial PR was retired, to work on the modal designs and user feedback.
