### ISSUE TITLE
Release 4.3.7 RC2 - Wazuh UI Smoke Manual testing - Kibana 7.10.2, 7.16.x, 7.17.x

### ISSUE THREAD

**Issue by mauceballos** [wazuh/wazuh-kibana-app#4408]
| Test   | Chrome | Safari | Firefox | Package |
|--------|--------|--------|---------|---------|
| Test 1 | 🟢/🔴  | 🟢/🔴 | 🟢/🔴    | 🟢/🔴  |
 
Status legend:
⚫ - None
🔴 - Rejected
🟢 - Approved

In the case of 🔴, create and link the issue. 

### Change Log
All notable changes to the Wazuh app project will be documented in this file.

**Comment by yenienserrano** [comment]
| Chrome | Safari | Firefox | Package |
|--------|--------|---------|---------|
| 🟢| :black_circle:  | 🟢    | 4.3.7 - 7.17.5 | 
| 🟢| :black_circle:  | 🟢    | 4.3.7 - 7.16.2 | 
| 🟢| :black_circle:  | 🟢    | 4.3.7 - 1.2.0 |

**Comment by chantal-kelm** [comment]
| Chrome | Safari | Firefox | Package |
|--------|--------|---------|---------|
| 🟢| :black_circle:  | 🟢    | 4.3.7 - 7.10.2 (ODFE) | 
| 🟢| :black_circle:  | 🟢    | 4.3.7 - 7.16.0 |
