### ISSUE TITLE
ECONNREFUSED and invalid request errors in demo environment.

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh-kibana-app#4409]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3.7   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
Multiple errors in the logs 

- ```{"date":"2022-08-16T16:09:58.578Z","level":"error","location":"monitoring:getApiInfo","message":"connect ECONNREFUSED 10.0.0.107:55000"}```

- ```{"date":"2022-08-16T16:30:00.109Z","level":"info","location":"Cron-scheduler","data":{"message":"Request failed with status code 400","stack":"Error: Request failed with status code 400\n at createError (/usr/share/wazuh-dashboard/plugins/wazuh/node_modules/axios/lib/core/createError.js:16:15)\n at settle (/usr/share/wazuh-dashboard/plugins/wazuh/node_modules/axios/lib/core/settle.js:17:12)\n at IncomingMessage.handleStreamEnd (/usr/share/wazuh-dashboard/plugins/wazuh/node_modules/axios/lib/adapters/http.js:269:11)\n at IncomingMessage.emit (events.js:203:15)\n at endReadableNT (_stream_readable.js:1145:12)\n at process._tickCallback (internal/process/next_tick.js:63:19)","config":{"url":"https://10.0.0.195:55000/cluster/nodes?select=name","method":"get","data":"{}","params":{}}}}```

- ```{"date":"2022-08-16T16:30:00.122Z","level":"error","location":"monitoring:getApiInfo","message":"Request failed with status code 400"}```

**Steps to reproduce**
Execute the following command in the server

`egrep -Ei "ERR|WARN" /usr/share/wazuh-dashboard/data/wazuh/logs/wazuhapp.log`

**Expected Result**
1. No error logs (probably the ECONNREFUSED is temporal and it is accepted, but the invalid request errors need review) 

**Actual Result**
1. Multiple error logs shown

**Additional context**
The errors were found during E2E exploratory as part of the 4.3.7 release. 
https://github.com/wazuh/wazuh/issues/14674

**Comment by gdiazlo** [comment]
Closing, as this seems to be related to an environment no longer exists.
