### ISSUE TITLE
Improve warning message when exceeding file upload limits

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-kibana-app#4411]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3.6   | 7.x     | | Basic |

| Browser |
| ------- |
| Chrome|

**Description**
When trying to upload a file into the rules/lists/decoders section in the app, If the file exceeds the allowed size it shows a message `Payload content length greater than maximum allowed 1048576`. This message is not intuitive, since this does not specify if the unit of measure used is bytes, characters, lines, etc. Also it should be clarified if this is for the whole lot of files being added or if it applies to each file (when trying to upload multiple files at once.

**Steps to reproduce**
1. Navigate to `Management/rules`
2. Click on `upload a file`
3. Try to upload a large xml file

**Expected Result**
1. The message shown should clarify to the user in a concise way the allowed file size (ex: 1Mb, 3Mb, etc).

**Actual Result**
1. An unclear `Payload content length greater than maximum allowed 1048576` message is shown

**Screenshots**
https://user-images.githubusercontent.com/14501079/185997522-84552be4-2b82-48d8-afed-6237fd65746e.png

**Comment by yenienserrano** [comment]
I have not been able to reproduce it and there is no such text in the code


![image](https://github.com/wazuh/wazuh-kibana-app/assets/63758389/a4f74e1d-09cd-450f-bafc-2862a3c96c16)
