### ISSUE TITLE
Setting a Wazuh test environment to execute automated test

### ISSUE THREAD

**Issue by Mayons95** [wazuh/wazuh-kibana-app#4419]
This issue aims to create a new environment that allows us to test our automated test cases on Wazuh Dashboard.
The use of the mock server was generated some problems (On the login, creation and edition of rules, decoders, etc)
So, with the QA team we decided to create a new environment with an VM with Wazuh installed, so the automated test could interact with a healthy and real environment.

- [x] Create a ubuntu VM with a Wazuh complete installation with the last version (Wazuh indexer, wazuh manager, wazuh indexer)
- [x] Execute the automated test suite to check the health of the test for Wazuh Dashboard
- [x] Fix test cases if it's necessary
  https://github.com/wazuh/wazuh-kibana-app/issues/4417
  https://github.com/wazuh/wazuh-kibana-app/issues/4415
- [x] Perform a complete head-less execution and generate the report

**Comment by Mayons95** [comment]
Related PR 
https://github.com/wazuh/wazuh-kibana-app/pull/4439
https://github.com/wazuh/wazuh-kibana-app/pull/4441
https://github.com/wazuh/wazuh-kibana-app/pull/4449

**Comment by Mayons95** [comment]
Move this issue to Done, Fix are integrated on develop branches

**Comment by mauceballos** [comment]
## Test suite execution on wzd:

<details>

![screencapture-file-home-mauri-repo-kibana-app-wazuh-kibana-app-test-cypress-cypress-report-output-html-2022-09-09-15_15_53](https://user-images.githubusercontent.com/76791841/189417629-1319b4b0-dd15-47cf-99cb-1c98602543c0.png)


</details>
