### ISSUE TITLE
Add delay to search on the DataHandler service

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#443]
Hello team,

We have to implement a delay on the search on the DataHandler service. Currently, every time we type a letter in a search bar, the app makes a request and this can lead to multiple simultaneous requests, making the app performance a bit slower.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
Done here https://github.com/wazuh/wazuh-kibana-app/pull/445
