### ISSUE TITLE
Dashboards don't filter properly nested fields

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-kibana-app#4430]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 7.10.2     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
Dashboard KPIs and tables don't filter properly **nested fields**. In the evidence can be seen _kibana-vis_ visualizations do recognize nested fields and structure properly their query, but custom KPIs metrics and tables don't identify nested fields therefore their requests  don't filter nested fields as expected.

**Preconditions**
1. Have alerts with nested fields

**Steps to reproduce**
1. Navigate to **Security Events** / **Dashboard**
2. Filter information using nested fields
3. Verify the consistency of the visualizations results
4. In the browser dev tools verify the queries have identified nested fields

<details>
<summary>Screenshots</summary>

#### Visualization request
![image](https://user-images.githubusercontent.com/9343732/187723701-7244387c-bf9c-415b-8749-01934b597b7f.png)

#### Table request
![image](https://user-images.githubusercontent.com/9343732/187724211-04394fc4-f9e9-43da-8cc0-e9ea9f023d81.png)

</details>

**Additional context**
Related to https://github.com/wazuh/wazuh/issues/14547

**Comment by Mayons95** [comment]
TR :heavy_check_mark: 
LGTM ! 

![Screenshot from 2022-09-05 15-36-51](https://user-images.githubusercontent.com/104914131/188501313-dfc78f46-10db-4c80-ad3a-fee30860bd56.png)
![Screenshot from 2022-09-05 15-36-39](https://user-images.githubusercontent.com/104914131/188501315-1617b12f-c22f-4508-8375-55aa9242ebfa.png)
![Screenshot from 2022-09-05 15-35-08](https://user-images.githubusercontent.com/104914131/188501316-5cf4c36f-43a5-4b97-86e6-019d4e6a8ecf.png)
