### ISSUE TITLE
Vulnerability Detector summary dashboard

### ISSUE THREAD

**Issue by xvdadw** [wazuh/wazuh-kibana-app#4431]
Dashboard in the Vulnerabilities module to briefly present the general state of all agents. 
As it was in version 4.2.6

**Comment by sempervictus** [comment]
This would be really great to have back in wazuh 4.3 - the current agent-by-agent modality is not very useful in terms of app presentation requiring fallback to various discover searches where we save searches presenting the relevant data.

**Comment by fuzzaqqq** [comment]
Would also like it back.

**Comment by jaykumarjp** [comment]
even if i create a visualize is also not useful.

**Comment by AlexRuiz7** [comment]
Hello

We have created a proposal for a new [Global vulnerabilities dashboard](https://github.com/wazuh/wazuh-kibana-app/issues/5763), based on the [development](https://github.com/wazuh/wazuh/issues/8737) mentioned previously.

I'm closing this issue as all the chatting will take place there.

Please, join the conversation and share your concerns.

- #5763
