### ISSUE TITLE
Review custom styles for Kibana 7.9.0

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#4480]
## Description

Our source code contains [custom styles for Kibana 7.9.0](https://github.com/wazuh/wazuh-kibana-app/tree/v4.3.6-7.10.2/public/styles/7.9.0), introduced when the support for this version was added.

We need to check if OpenSearch Dashboards use any of these styles, in such case, we'll be overwritten them.

If not, the custom styles can be safely removed, at least for the OpenSearch / Wazuh Dashboard application, keeping them in the Kibana app just in case.

## Strategy
- Remove the custom styles in a dev environment and compare with the latest stable Wazuh Dashboard version in order to detect any changes on the layout or styling.

**Comment by yenienserrano** [comment]
From what I could investigate I saw that in the archive there are many class names with references to Kibana that in Opensearch dashboard are changed to osd for example: `kbnDocViewer` change to `osdDocViewer`.

The other classes, for the most part, are in osd and have the same values.

From what I've been testing, these files can be deleted.
