### ISSUE TITLE
Inaccurate macOS reference on `Deploy a new agent` section

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-kibana-app#4484]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**

Currently every supported macOS version by Wazuh (from Sierra to Ventura) is called `macOS` and not `MacOS`, but `Deploy a new agent` guide is inaccurate about this.

![image](https://user-images.githubusercontent.com/1791430/189348621-1fd6d1d5-c421-4fc1-bf82-d53f1d272baa.png)

https://support.apple.com/en-us/HT201260

**Preconditions**
1. Wazuh Manager

**Steps to reproduce**
1. Navigate into Deploy New Agent

**Expected Result**
1. Apple OS macOS name is shown as `macOS` 

**Actual Result**
1. Apple OS macOS name is shown as `MacOS` 

**Screenshots**
![image](https://user-images.githubusercontent.com/1791430/189348095-746abc65-59d9-48d3-82bb-18a47408a4ba.png)

**Additional context**
Related issue: wazuh/wazuh#14729

**Comment by chantal-kelm** [comment]
Updated the way the macOS operating system name was displayed in the 'Deploy a new Agent' section.

Screenshots:

![image](https://user-images.githubusercontent.com/99441266/189395223-9a1f82f5-f7f1-44f6-be7b-9d34f7aabd49.png)

**Comment by chantal-kelm** [comment]
This issue is being resolved together with this other issue https://github.com/wazuh/wazuh-kibana-app/issues/4178 in the same PR.

This issue is blocked by https://github.com/wazuh/wazuh-documentation/issues/5561 as we need to link the additional installation steps for agents being installed in EOL operating systems.
