### ISSUE TITLE
Improve Wazuh Dashboard UI error management 

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-kibana-app#4546]
Hello team,

After installing Wazuh Dashboard in an old browser, we observed the following error from one of the tabs:
![image](https://user-images.githubusercontent.com/23264276/190993359-a08f7146-85be-4e17-8f9a-799976164bca.png)

The reason behind this error was that the browser version was not supported. 

Another error, due to the cluster process being down, the screen shows a misleading message:

![image](https://user-images.githubusercontent.com/23264276/191005931-1ef7e5a0-f3e8-4c72-b5ce-f9dcfd8e06fb.png)

Also, it considers the Wazuh API to be down but it's not true. The cluster process is down:
![image](https://user-images.githubusercontent.com/23264276/191006005-e00df6a1-6990-4904-ba9a-cadd9fbfdfe0.png)

We should handle better these kinds of errors to help properly to the users. Not only this error but others that don't show proper information.

Regards,

Miguel Casares

**Comment by gdiazlo** [comment]
We would look into this when we finish the wazuh-dashboard fork from opensearch-dashboards (see https://github.com/wazuh/wazuh-dashboard/ ). We could potentially contribute back a browser check honoring the `.browrserrc `settings to opensearch-dashboards.

**Comment by gdiazlo** [comment]
We're closing this issue, as we're not going to support browsers the opensearch platform does not support.
