### ISSUE TITLE
Agent's IPv6 visualization is too long

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-kibana-app#4566]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.4   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox|

**Description**
During https://github.com/wazuh/wazuh/issues/14988 validation, it was found that there's a problem related to IPv6 visualization and their length

**Preconditions**
1. Install a Linux/BSD/macOS Wazuh Agent and enroll it with the Wazuh Manager

**Steps to reproduce**
1. Navigate to Agents section
2. Check agent's IPv6 on the table
3. Click on that agent
4. Check agent summary IP information

**Expected Result**
1. IPv6 on Agents table can be seen by wrapping it or by expanding the column
2. IPv6 on Agent summary information can be seen by wrapping it 

**Actual Result**
1. IPv6 on Agents table could not be seen because columns cannot be expanded
2. IPv6 on Agent summary information overlaps Status information

**Screenshots**

![image](https://user-images.githubusercontent.com/1791430/191640065-6d84d7ba-f9bb-4c18-8868-e173c6142379.png)
![image](https://user-images.githubusercontent.com/1791430/191640079-8490e807-de37-42ce-8ccd-6febbd8a9169.png)

** Aditional information **

Related issue: https://github.com/wazuh/wazuh/issues/14729

**Comment by Tostti** [comment]
Merged PR
