### ISSUE TITLE
Add agent name as part of the agent deployment form

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-kibana-app#4573]
**Describe the solution you'd like**
  
Currently, there's an agent deployment form that users can fill in to obtain a command line to deploy the agent based on the options they select from the form.

![image](https://user-images.githubusercontent.com/5363328/191987608-7a7b356d-f816-4a74-8969-a84975c3a340.png)

We should add another step to use the WAZUH_AGENT_NAME deployment variable so users can customize the name of the agent.

Javier.

**Comment by chantal-kelm** [comment]
This is the finished issue of adding the WAZUH_AGENT_NAME variable to the Deploy new agent section form.

When the user has permissions

https://user-images.githubusercontent.com/99441266/197206470-3aa60eea-61e8-47dc-93c6-dcdde54bdb70.mp4

When the user does not have permissions

https://user-images.githubusercontent.com/99441266/197206745-a3d52f20-4a7c-437b-b864-132df8c549d6.mp4
