### ISSUE TITLE
WZD - Feature - An error message should be displayed when a rule is duplicated.

### ISSUE THREAD

**Issue by mauceballos** [wazuh/wazuh-kibana-app#4580]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3.8 | 7.17.4  | 4308 |  WZD |

| Browser |
| ------- |
| Chrome |

Description:

The feature increases the coverage of the Rules Module.

### Feature

```
Given: The Kibana admin user is logged in using wzd and the Wazuh logo is displayed
When: The user navigates to Ruleset Test 
And: The user enters the test message 
And: The user clicks on the test button
Then: A error message is displayed on the console section description of the problem
```

**Comment by gdiazlo** [comment]
This should be fixed when we deploy the new error management code.
