### ISSUE TITLE
Centralized Vulnerability Detector Dashboard

### ISSUE THREAD

**Issue by sempervictus** [wazuh/wazuh-kibana-app#4611]
**Describe the solution you'd like**
The vulnerability detector view requires selection of an agent, precluding the ability to visually cross-correlate between agents.
![image](https://user-images.githubusercontent.com/1331084/192680315-6fdc9816-04ce-4dfa-90cb-4a497814e7e4.png)
It would be great to have dashboards for vulnerabilities spanning all agents (or query-filtered agents/vulns) much like normal security events but with their context-specific presentation.

**Comment by AlexRuiz7** [comment]
Hello @sempervictus 

There is an issue already tracking this feature request. #4431 

Would you mind comment your interest in such feature request in that issue?

Thank you!

I'll close this issue as it's duplicated.

**Comment by sempervictus** [comment]
My apologies! Will update that issue
