### ISSUE TITLE
Remove router Internal Error in server console

### ISSUE THREAD

**Issue by Machi3mfl** [wazuh/wazuh-kibana-app#4650]
| Wazuh | Elastic |
| ----- | ------- |
| 4.4   | >1.x     | 

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
The server console log shows an `Internal Server Erro`r when the browser makes a request and fails.
We need to make this error more readable.

**Steps to reproduce**
1. Navigate into the Wazuh plugin
2. Check the server console

**Screenshots**
![image](https://user-images.githubusercontent.com/6089438/194137180-74ad24ec-68e0-49d2-86f0-b193c92e7a33.png)

**Comment by asteriscos** [comment]
So far I tried to force an error making bad requests, but still couldn't replicate the error.

![image](https://user-images.githubusercontent.com/9343732/195635987-6670eab0-9bec-463f-9676-2cf69fb89beb.png)

![image](https://user-images.githubusercontent.com/9343732/195636060-17b60c20-d5ea-4fe9-b9b4-91864684f978.png)


Navigating to Wazuh plugin Home page was not enough. If possible, please share more context or details on how to trigger the error. In the meantime, I will continue with the tests.

**Comment by asteriscos** [comment]
I ran tests with Kibana 7.10.2 and Opensearch 2.3.0 without being able to reproduce the issue at will. The first time I started the Opensearch environment the error the error was thrown after logging in, but I couldn't replicate it after several tries.

![image](https://user-images.githubusercontent.com/9343732/195667428-2d295345-c93e-4c59-b01a-22b18a893f95.png)

![Screenshot from 2022-10-13 18-56-03](https://user-images.githubusercontent.com/9343732/195667989-b88969fa-82dd-43b9-984d-5108296df9cf.png)

I couldn't find any relevant log, tests are still in progress.

**Comment by asteriscos** [comment]
Related Kibana issue:
https://github.com/elastic/kibana/issues/117371

**Comment by asteriscos** [comment]
Tested with Kibana 7.10.2 X-Pack without results:

![image](https://user-images.githubusercontent.com/9343732/195839764-a3c9db49-f859-4c3b-beb1-029f84c60ff0.png)


In this test some other security errors happened, but nothing related to this issue:

![image](https://user-images.githubusercontent.com/9343732/195839982-2dce2f3b-0a13-4dcb-ba62-8d8b2bf1c154.png)

**Comment by asteriscos** [comment]
According to the logs, the exception is thrown here:
https://github.com/elastic/kibana/blob/v7.10.2/src/core/server/http/router/response_adapter.ts#L129

**Comment by Desvelao** [comment]
I didn't get to replicate the error.

My test environments were:
- Kibana 7.10.2 ODFE (Development environment Branch 4.3-7.10) Branch
- Kibana 7.17.4 X-Pack (Production) Wazuh 4.3.8

**Comment by Desvelao** [comment]
I tried with the suggested environment and I could not replicate the problem.

Test environment:
- OpenSearch Dashboards tag `2.3.0` in development mode
- Wazuh plugin branch `4.4-1.2-wzd`
- OpenSearch Dashboards Security plugin tag `2.3.0.0`

**Comment by asteriscos** [comment]
Here's a reference mentioning a possible template issue:
https://discuss.elastic.co/t/kibana-metrics-500-internal-server-error/238260/2

**Comment by asteriscos** [comment]
I managed to replicate it at will with the new environments with Opensearch 1.2.4 and some fake Wazuh Manager API configurations. 

![Screenshot from 2022-10-17 17-27-40](https://user-images.githubusercontent.com/9343732/196220750-f86c11ec-0fea-48b9-99f7-22e2e2d52e6c.png)

Whenever a connection fails, it logs this exception. What I'm still trying to figure out, is why in other dev environments this does not happen.

**Comment by asteriscos** [comment]
It seems Opensearch logs an exception in the console when Wazuh plugin API returns a code `500` error, regardless if it is controlled. This does not happen when some other code error is returned, like a code `503` _Service unavailable_ for example.

In this case, the exception is produced when our plugin checks if Wazuh API is available, which is an expected possibility. So a possible solution to avoid the error in the console would be use a code `503` **_Service unavailable_** when Wazuh API is down.

I suggest to review Wazuh plugin API code errors to avoid using a **_generic Internal server error_** code `500`.
