### ISSUE TITLE
The field "timestamp" associated with this object no longer exists in the index pattern. Please use another field.

### ISSUE THREAD

**Issue by kiiru4reals** [wazuh/wazuh-kibana-app#4666]
I have been having this issue when I view agents.
Steps taken to reproduce this:
1. Visit agents/

The full error is shown below
```js
Error: The field "timestamp" associated with this object no longer exists in the index pattern. Please use another field.
    at FieldParamType.e.write.write (https://35.195.32.17/46953/bundles/plugin/data/kibana/data.plugin.js:1:361872)
    at https://<ip>/46953/bundles/plugin/data/kibana/data.plugin.js:1:324773
    at Array.forEach (<anonymous>)
    at d (https://<ip>/46953/bundles/plugin/data/kibana/data.plugin.js:1:324750)
    at AggConfig.write (https://<ip>/46953/bundles/plugin/data/kibana/data.plugin.js:1:313506)
    at AggConfig.toDsl (https://<ip>/46953/bundles/plugin/data/kibana/data.plugin.js:1:314193)
    at https://<ip>/46953/bundles/plugin/data/kibana/data.plugin.js:1:141274
    at Array.forEach (<anonymous>)
    at agg_configs_AggConfigs.toDsl (https://<ip>/46953/bundles/plugin/data/kibana/data.plugin.js:1:140375)
    at https://<ip>/46953/bundles/plugin/wazuh/4.3.8-4309/wazuh.chunk.3.js:54:1156071
```

**Comment by Desvelao** [comment]
Hi @kiiru4reals,

In the `Agents` section of the plugin, there is a visualization that uses the data from the index pattern used for the monitoring job of the plugin. This job retrieves the agent status data and indexes it in Elasticsearch indices. 

I think there is a problem with this index pattern or its indices.

0. Environment. Share the next information about your applications.
0.1 Wazuh plugin version
0.2 Kibana version
0.3 Elasticsearch version

1. Monitoring index pattern.
1..1. Do you have a custom index pattern for this job? Could you share what is your configuration for `wazuh.monitoring.pattern`? You could share a piece of the configuration file (`wazuh.yml`) where you set this setting or share a screenshot of the `Settings/Configuration` where it appears the mentioned setting.
1.2. Check the index pattern is listed in `Stack management/Index patterns`.

2. Check you have indices that match the index pattern.
Using a privileged user, go to the `Dev tools` plugin of the Kibana, and run the next request:
```
GET /_cat/indices
```
> This request displays all the indices.

I am interested to see if you have indices related to the monitoring index pattern. If you are not sure, share the output. Obfuscate any information you consider to be sensible.

**Comment by AlexRuiz7** [comment]
Closed due to inactivity.
