### ISSUE TITLE
Test the plugin in Wazuh Dashboard

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#4740]
## Description

We have fixed some issues in the plugin to bring it up to date with OpenSearch and OpenSearch Dashboards 2.3.x.

In parallel, @wazuh-cloud-cicd has also made some changes to Wazuh Dashboard, with the same goal.

We now need to test the plugin and the platform together to ensure that there are no bugs that we have overlooked, or that have been introduced as a result of the changes made.

## Tasks
- [x] Install the test-package (platform + plugin) and test they work as expected.

Notify any problems found.

**Comment by yenienserrano** [comment]
The issues found in this epic are working correctly, so far a black square has been found above the wazuh menu.

**Comment by yenienserrano** [comment]
I am still investigating, but it seems to work correctly, I am investigating some logs that appear to know if they are from the environments I have, or if it is a change due to the security plugin.

**Comment by yenienserrano** [comment]
From investigating some error logs I was having it was a problem with the environment in which the package was raised with the roles being given to the users, and the problem is fixed for future testing in the environment.

**Comment by yenienserrano** [comment]
In the last tests it has worked as expected, I share some images of the app.

![image](https://user-images.githubusercontent.com/63758389/201350569-a0d1f3d2-150c-484f-a998-dcdacbef4dd2.png)

![image](https://user-images.githubusercontent.com/63758389/201350644-cba928a8-bf71-4b9d-a66c-cbb075c8e015.png)

![image](https://user-images.githubusercontent.com/63758389/201350780-05b02638-dc83-4d72-81d3-b2cbc5a8ed36.png)

![image](https://user-images.githubusercontent.com/63758389/201350845-6995bcc9-2dc1-4eea-b394-10949a94cb55.png)
