### ISSUE TITLE
Fix the remote protocols are not displayed correctly when there are more than one

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#4767]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| <=4.3.9   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
Short description of your issue.

**Preconditions**
1. Configure the manager with `tcp` and `udp` protocols.

```xml
<remote>
    <connection>secure</connection>
    <port>1514</port>
    <protocol>tcp,udp</protocol>
    <queue_size>131072</queue_size>
</remote>

```

**Steps to reproduce**
1. Navigate to Management/Configuration
2. Select the manager that was configurated with multiple protocols
3. The protocol column displays the configurated values without any separation

**Expected Result**
1. The values should be separated

**Screenshots**
![image](https://user-images.githubusercontent.com/34042064/197995592-a2895a76-8398-4877-83d9-8a2a674cf988.png)

**Comment by Tostti** [comment]
Merged corresponding PRs
