### ISSUE TITLE
Cannot log out when OpenID Connect is set up

### ISSUE THREAD

**Issue by zbalkan** [wazuh/wazuh-kibana-app#4780]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4..9   | Wazuh-Indexer | N/A| Basic |

| Browser |
| ------- |
| N/A |

**Description**
When OIDC is set up, the logout action redirects to https://hostname/logout page without any redirection and actually logging out of OIDC provider. So, when a user logs in, there is no way to log out.

**Preconditions**
1. Install Wazuh 4.3.9 using Wazuh-Indexer and Wazuh-Dashboard.
2. Have a OIDC Provider, e.g. Keycloak.
3. Set up OpenID Connect according to the documents [OpenSearch documents](https://opensearch.org/docs/latest/security-plugin/configuration/openid-connect/).

**Steps to reproduce**
1. Log in to Wazuh using OpenID Connect SSO.
5. Click on 'Logout'

**Expected Result**
1. Redirect to `http://auth-server/auth/realms/{realm-name}/protocol/openid-connect/logout?redirect_uri=encodedRedirectUri`, where encoded redirect URI is the encoded format of `https://hostname/app/login`: `https%3A%2F%2Fhostname%2Fapp%2Flogin`.
2. Log out of the session by the use of redirection.
3. Display Wazuh login page.

**Actual Result**
1. Redirects to `https://hostname/logout` and gets HTTP 404 Not Found result.

**Screenshots**
![image](https://user-images.githubusercontent.com/39981909/198964649-f23665a0-4327-4b07-80d9-376acb4d9c02.png)
Sample Wazuh SSO login screen using Keycloak

![image](https://user-images.githubusercontent.com/39981909/198964890-2f42ef16-0e15-45e7-9a5d-a369d7240726.png)
Logging out

![image](https://user-images.githubusercontent.com/39981909/198964481-2f7bb6ec-646b-42cf-971b-a19b62d6e645.png)
Logout result
**Additional context**

- There is a similar [issue](https://github.com/wazuh/wazuh-kibana-app/issues/4026) related to logout created in April.
- When you look at the [code for logging out](https://github.com/wazuh/wazuh-kibana-app/blob/a9e7d31a2f6bbba60c6acb400e931857ffe201cd/public/app.js#L118), there is no mention of handling those kinds of requests.

**Comment by gdiazlo** [comment]
Thanks for reporting this @zbalkan we're fixing this also for SAML in #4779, I believe the same fix will apply to all the auth methods which differ from the internal one.

**Comment by zbalkan** [comment]
Hi @gdiazlo ,

I see that the related PR uses Keycloak. Will there be a Keycloak SSO documentation for SAML and OIDC?
