### ISSUE TITLE
Custom branding: 7.17 - QA test

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#4801]
## Description

We need to test the new custom branding capabilities of the app for newer versions of Kibana, in order to verify the backports have ported the functionalities correctly.

## Test cases
The tests cases are defined on each pull request:

- #4501
- #4503
- #4785
- #4504
- #4505
- #4507

**Comment by Mayons95** [comment]
TR: :heavy_check_mark: 
LGTM
Test Details

<details>

[Screencast from 03-11-22 23:58:31.webm](https://user-images.githubusercontent.com/104914131/199876274-823f644f-9e00-4460-b0a1-2cd3ec4c3d98.webm)

[Screencast from 04-11-22 00:01:39.webm](https://user-images.githubusercontent.com/104914131/199876316-e1f6123a-156c-481c-9d1d-70c72fb7f77c.webm)

</details>
