### ISSUE TITLE
Custom branding: WzD - QA test

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#4802]
## Description

We need to test the new custom branding capabilities of the app for Wazuh Dashboard, in order to verify the backports have ported the functionalities correctly.

## Test cases
The tests cases are defined on each pull request:

- #4501
- #4503
- #4785
- #4504
- #4505
- #4507

**Comment by Mayons95** [comment]
Test successfully executed :heavy_check_mark: 
LGTM

[Screencast from 03-11-22 15:58:26.webm](https://user-images.githubusercontent.com/104914131/199811267-2e15210a-2da4-482d-8b86-0d7fd3cddb1d.webm)
