### ISSUE TITLE
Automation - create a new policy

### ISSUE THREAD

**Issue by Mayons95** [wazuh/wazuh-kibana-app#4843]
This issue is created to track the effort to create new test cases that cover the functionality of create a new Wazuh Policy

**Comment by Mayons95** [comment]
I moved this issue too on hold because to proceed with this development the PR https://github.com/wazuh/wazuh-kibana-app/pull/4873 need's to be implemented on the main branch.

**Comment by gdiazlo** [comment]
We will revisit this in a per-release basis, designing a testing plan in sync with the changelog.
