### ISSUE TITLE
Run Regression Testing - Release 4.3.10 - Release Candidate 1

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#4858]
## Description

Run regression test for Wazuh Kibana app and Wazuh Dashboard for the upcoming release Wazuh 4.3.10, which includes the following issue in our side:

## Target versions

- [x] Kibana 7.10.2 (ODFE)
- [x] Kibana 7.16.3
- [x] Kibana 7.17.4
- [x] Kibana 7.17.5
- [x] Kibana 7.17.6
- [x] OpenSearch Dashboards 1.2.0
- [x] Wazuh Dashboard 4.3.10

## Issues

- #4779 

## Test cases

Scenario: have an environment with xPack
When the user opens the Wazuh plugin and clicks on log out
Then the session should be closed and the user redirected to the login page

Scenario: have an environment with OpenDistro
When the user opens the Wazuh plugin and clicks on log out
Then the session should be closed and the user redirected to the login page

Scenario: have an environment with OpenSearch
When the user opens the Wazuh plugin and clicks on log out
Then the session should be closed and the user redirected to the login page

Scenario: have an environment with SAML
When the user opens the Wazuh plugin and clicks on log out
Then the session should be closed and the user redirected to the login page

## Conclusions

🟢 No errors were found. The SAML issues has been resolved, according to the test scenarios described above.

**Comment by Mayons95** [comment]
Testing for Kibana 7.10.2 - Open-Distro Security 
<details>

![image](https://user-images.githubusercontent.com/104914131/201677094-d7cbcd46-fb3b-454b-aa4f-7943691f8d23.png)

[Screencast from 14-11-22 10:52:38.webm](https://user-images.githubusercontent.com/104914131/201677353-bff8dfd8-2d71-418c-827e-df5e0d1ba9fa.webm)

</details>

**Comment by Mayons95** [comment]
Report from the automated test suite:
[Kibana 7.17.6 Report .pdf](https://github.com/wazuh/wazuh-kibana-app/files/10005493/Kibana.7.17.6.Report.pdf)

**Comment by Mayons95** [comment]
Report from the automated test suite for WZD:

[WZD - Report 4.3.10.pdf](https://github.com/wazuh/wazuh-kibana-app/files/10006037/WZD.-.Report.4.3.10.pdf)

The errors displayed are related at the absence of test data in those test cases

**Comment by AlexRuiz7** [comment]
✔️ Testing SAML logout in Wazuh Dashboard 4.3.10-rc1 

- IDP login page
![image](https://user-images.githubusercontent.com/15186973/202159301-415d262a-dd4b-42ec-b3bd-7a1a4c79b845.png)

- On successful login, the IDP redirects us to Wazuh
![image](https://user-images.githubusercontent.com/15186973/202159364-d9c34c46-4789-4416-ab5f-ce0a961b66c1.png)

- Clicking on the logout button closes the session and we are redirected to the IdP login page again.
![image](https://user-images.githubusercontent.com/15186973/202159676-b1ff6cc4-bcb2-459a-945c-371cd2991126.png)
