### ISSUE TITLE
Pressing enter on the top-bar Discover tab is not working

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#487]
Hello team,

If we type something on the Discover search bar from the top menu bar, it won't work.

This doesn't happen on the Discover from the Overview or Agents tabs, where pressing Enter starts the search.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
Done here https://github.com/wazuh/wazuh-kibana-app/pull/488
