### ISSUE TITLE
Release 4.4.0 - Alpha 1 - Kibana UI regression testing

### ISSUE THREAD

**Issue by Mayons95** [wazuh/wazuh-kibana-app#4895]
This issue aims to track the effort to perform complete regression testing on Wazuh App 4.4.0 Alpha1

| Test   | Chrome | Safari | Firefox | Package |
|--------|--------|--------|---------|---------|
| Example test | 🟢/🔴  | 🟢/🔴 | 🟢/🔴    | 🟢/🔴  |
 
Status legend:
⚫ - None
🔴 - Rejected
🟢 - Approved

In the case of 🔴, create and link the issue. 
Kibana version that are going to be tested

Testing plan:
- https://github.com/wazuh/wazuh-kibana-app/issues/4451

Testing notes: 
Test plan to be used for testing RC: https://github.com/wazuh/wazuh-kibana-app/issues/4451
1) All the mentioned version are need to be tested
2) It's necessary to include evidence of each test performed
3) In case to identify a bug/problem, the new feature should be linked on this issue

- [x] 7.17.7 
- [x]  7.17.6
- [ ] 7.17.5 
- [ ] 7.17.4
- [x] 7.16.3
- [x] 7.10.2
- [x] WZD 

Bug tracking:
https://github.com/wazuh/wazuh-kibana-app/issues/4906
https://github.com/wazuh/wazuh-kibana-app/issues/4907
https://github.com/wazuh/wazuh-kibana-app/issues/4908
https://github.com/wazuh/wazuh-kibana-app/issues/4910

**Comment by Mayons95** [comment]
| Test   | Chrome | Safari | Firefox | Package |
|--------|--------|--------|---------|---------|
|https://github.com/wazuh/wazuh-kibana-app/pull/4428 | 🔴  | 🔴 | :black_circle:    | 🔴  |

**Comment by Mayons95** [comment]
| Test   | Chrome | Firefox | Safari | Package |
|--------|--------|--------|---------|---------|
|https://github.com/wazuh/wazuh-kibana-app/pull/4428 | 🔴  | 🔴 | :black_circle:    | 7.16.3 |
|https://github.com/wazuh/wazuh-kibana-app/pull/4425 | :green_circle:  | :green_circle:  | :black_circle:    | 7.16.3  |

**Comment by Mayons95** [comment]
Automatic Test Execution
[7.17.5 - Report.pdf](https://github.com/wazuh/wazuh-kibana-app/files/10075306/7.17.5.-.Report.pdf)

[7.16.3 Report.pdf](https://github.com/wazuh/wazuh-kibana-app/files/10075308/7.16.3.Report.pdf)

<details>

The errors displayed on the test report were analyzed and are properly working in the app, test should be updated to the next release

</details>

**Comment by Machi3mfl** [comment]
## Wazuh dashboard 4.4 testing

**In progress :hourglass_flowing_sand:**

**Comment by Mayons95** [comment]
| Test   | Chrome | Firefox | Safari | Package |
|--------|--------|--------|---------|---------|
|https://github.com/wazuh/wazuh-kibana-app/pull/4428 |:green_circle  | :green_circle | :black_circle:    | 7.10.2 |
|https://github.com/wazuh/wazuh-kibana-app/pull/4425 | :green_circle:  | :green_circle:  | :black_circle:    | 7.10.2  |
|https://github.com/wazuh/wazuh-kibana-app/pull/4174 | :green_circle:  | :green_circle:  | :black_circle:    | 7.10.2  |
|https://github.com/wazuh/wazuh-kibana-app/pull/4508 | :green_circle:  | :green_circle:  | :black_circle:    | 7.10.2  |
|https://github.com/wazuh/wazuh-kibana-app/pull/4238 | :green_circle:  | :green_circle:  | :black_circle:    | 7.10.2  |
|https://github.com/wazuh/wazuh-kibana-app/pull/4512 | :green_circle:  | :green_circle:  | :black_circle:    | 7.10.2  |
|https://github.com/wazuh/wazuh-kibana-app/pull/4501 | :green_circle:  | :green_circle:  | :black_circle:    | 7.10.2| 
|https://github.com/wazuh/wazuh-kibana-app/pull/4504 | :green_circle:  | :green_circle:  | :black_circle:    | 7.10.2 | 
|https://github.com/wazuh/wazuh-kibana-app/pull/4503 | :green_circle:  | :green_circle:  | :black_circle:    | 7.10.2 | 
|https://github.com/wazuh/wazuh-kibana-app/pull/4507 | :green_circle:  | :green_circle:  | :black_circle:    | 7.10.2 | 
|https://github.com/wazuh/wazuh-kibana-app/issues/3836 | :green_circle:  | :green_circle:  | :black_circle:    | 7.10.2 | 
|https://github.com/wazuh/wazuh-kibana-app/issues/3950 | :green_circle:  | :green_circle:  | :black_circle:    | 7.10.2 | 
|https://github.com/wazuh/wazuh-kibana-app/issues/4178 | :green_circle:  | :green_circle:  | :black_circle:    | 7.10.2 | 
|https://github.com/wazuh/wazuh-kibana-app/issues/3931 | :green_circle:  | :green_circle:  | :black_circle:    | 7.10.2 | 
|https://github.com/wazuh/wazuh-kibana-app/issues/4426 | :green_circle:  | :green_circle:  | :black_circle:    | 7.10.2 | 
|https://github.com/wazuh/wazuh-kibana-app/issues/4314 | :green_circle:  | :green_circle:  | :black_circle:    | 7.10.2 |

**Comment by Machi3mfl** [comment]
### WZD 4.4 Automation tests Status Report 

- [Wazuh dashboard 4.4 - Automation tests report](https://github.com/wazuh/wazuh-kibana-app/files/10087025/wzd44-241122.pdf) :card_file_box:

**Comment by Machi3mfl** [comment]
### WZD 4.4 Automation tests Status Report with Agent add

- [Wazuh dashboard 4.4 with agent added - Automation tests report](https://github.com/wazuh/wazuh-kibana-app/files/10087025/wzd44-241122.pdf)](https://github.com/wazuh/wazuh-kibana-app/files/10094873/wzd44-251122.pdf)

**Comment by Machi3mfl** [comment]
### Kibana 7.17.7 Automation tests Status Report with Agent added

- [Kibana 7.17.7 - Automation tests report](https://github.com/wazuh/wazuh-kibana-app/files/10116926/kibana7177-291122.pdf)
