### ISSUE TITLE
Nested fields are not displayed on Kibana

### ISSUE THREAD

**Issue by Mayons95** [wazuh/wazuh-kibana-app#4906]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.4   | 7.17.6, 7.16.3    | Xpack |

| Browser |
| ------- |
| Chrome, Firefox|

**Description**
Testing the feature implemented on PR https://github.com/wazuh/wazuh-kibana-app/pull/4428 I found that trying to open nested field using Kibana 7.17.6 an error it's displayed

**Preconditions**
It's needs to have alerts with nested fields

**Steps to reproduce**
1. Navigate to security events dashboard
2. Click on one alert that has nested fields

**Expected Result**
1. The alert should be displayed correctly

**Actual Result**
1. A error it's displayed

**Screenshots**

[Screencast from 18-11-22 15:10:38.webm](https://user-images.githubusercontent.com/104914131/202774643-e8a6f528-9bbf-46c9-9048-66859b6b1d48.webm)

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by asteriscos** [comment]
## Solution

`formatHit` is no longer a method of the IndexPattern class in Kibana 7.16+, so to detect if a field is known we have to use our own formatHit function in:
`public/kibana-integrations/lib/format_hit.ts`

And also enhance this function to detect if a field value is an array, so we can format it whether is known or not.
