### ISSUE TITLE
Wrong WAZUH_PROTOCOL variable content shown in `Deploy a new agent`

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-kibana-app#4914]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3.10   | Wazuh-indexer     | 4311 | Wazuh-indexer |

| Browser |
| ------- |
| Chrome |

**Description**

When defining multiple `secure` blocks in the Wazuh manager configuration, if the Syslog block is configured with UDP and the Remote block is configured with TCP, but the Syslog block appears before the Remote one, like this:

```
<remote>
  <connection>syslog</connection>
  <port>514</port>
  <protocol>udp</protocol>
  <allowed-ips>192.168.0.0/16</allowed-ips>
  <allowed-ips>172.0.0.0/8</allowed-ips>
</remote>

<remote>
  <connection>secure</connection>
  <port>1514</port>
</remote>
```

The instructions showing up in the `Deploy a new agent` section will show the WAZUH_PROTOCOL="UDP" variable when it shouldn't:

```
Invoke-WebRequest -Uri https://packages.wazuh.com/4.x/windows/wazuh-agent-4.3.10-1.msi -OutFile ${env:tmp}\wazuh-agent-4.3.10.msi; msiexec.exe /i ${env:tmp}\wazuh-agent-4.3.10.msi /q WAZUH_MANAGER='10.0.0.202' WAZUH_REGISTRATION_SERVER='10.0.0.202' WAZUH_PROTOCOL='UDP' 
```

**Comment by gdiazlo** [comment]
I believe this is a duplicate of https://github.com/wazuh/wazuh-kibana-app/issues/4318
