### ISSUE TITLE
Unmapped field filter in the Security Events table throws an exception

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-kibana-app#4932]
### Description
Adding an unmapped field filter in the Security Events table throws an exception.

Unmapped fields are disabled for filtering in the Discover events view. This behavior should be replicated in the Security Events table.

![image](https://user-images.githubusercontent.com/9343732/208703642-710eca4e-3a29-4768-8a96-191c7142d19e.png)

![image](https://user-images.githubusercontent.com/9343732/208703690-96726b33-a9a8-4c86-8ed2-cfbba8f6fb78.png)

#### Preconditions

- Have alerts with unmapped fields.

#### Steps to reproduce

1. Navigate to Security Events
2. In the lower events table select an alert with unmapped fields
3. Scroll to the unmapped field and click on the magnifier glass to add the filter
4. See the exception

#### Expected Result

- Unmapped fields should have the magnifier glass disabled

#### Actual Result

- The magnifier glass is enabled and allows to filter by that field

#### Additional context
Happens in 7.10.2, 7.16.x and Wazuh Dashboard

**Comment by davidjiglesias** [comment]
Does this problem replicates in v4.3.X?

**Comment by yenienserrano** [comment]
I couldn't reproduce it in 4.3.9, but I think it is something that was added in 4.4 from this issue 

- #4429
