### ISSUE TITLE
Wazuh logo does not display correctly on 4.4.0 Alpha 1

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-kibana-app#4937]
## Describe the bug

During the 4.4.0 Release testing, it was found the Wazuh logo at the top of the dashboard is not displayed correctly. 

The Error was found on:
- Centos 8, using step-by step installation: https://github.com/wazuh/wazuh/issues/15542#issuecomment-1332270282
- Centos 7, using installation script: https://github.com/wazuh/wazuh/issues/15531#issuecomment-1331941180

### Evidence
![imagen](https://user-images.githubusercontent.com/14501079/204844045-5b3369b7-dfb4-4eb6-9bbb-c823bcde2f20.png)

**Current behavior**
The Wazuh logo at the top of the dashboard is not displayed correctly. 

**Expected behavior**
The Wazuh logo is displayed correctly

**Comment by Tostti** [comment]
This issue is solved on https://github.com/wazuh/wazuh-kibana-app/issues/4502

The problem was that the Dashboard packages were built with a previous version. Packages have been rebuilt and the issue was solved. 

Thread:
https://wazuh-team.slack.com/archives/C02A737S5MJ/p1669822576791769
