### ISSUE TITLE
Toast with error 3013 in Kibana 

### ISSUE THREAD

**Issue by verdx** [wazuh/wazuh-kibana-app#4938]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.4   | 7.17     | 1 | |

| Browser |
| ------- |
| Firefox|

**Description**
Elastic Stack with single-node cluster both for Elastic and Wazuh, Kibana on a separate host, all Debian 10, fresh installations.

After reloading the Kibana WUI, a toast appears for a few seconds  saying there has been an error with the Wazuh cluster.
The full error is:
```
e.exports@https://192.168.57.124/47018/bundles/plugin/wazuh/4.4.0-4400/wazuh.plugin.js:3:6402
e.exports@https://192.168.57.124/47018/bundles/plugin/wazuh/4.4.0-4400/wazuh.plugin.js:9:9612
v@https://192.168.57.124/47018/bundles/plugin/wazuh/4.4.0-4400/wazuh.plugin.js:3:5001
```

**Steps to reproduce**
1. Install Elastic Stack environment following documentation:
  - Single-node Elastic cluster on Debian 10
  - Single-node Wazuh cluster on Debian 10
  - Kibana on dedicated host, Debian 10
2. Access Kibana WUI

**Expected Result**
1. No error toast.

**Actual Result**
1. Error toast

**Screenshots**
![3013_error](https://user-images.githubusercontent.com/61122643/204851676-0bced821-1056-45ef-b354-d6ad04165104.png)
![3013_full_error](https://user-images.githubusercontent.com/61122643/204851669-024503e9-7986-4e67-b07c-2ce6bc28d091.png)

**Comment by yenienserrano** [comment]
The endpoints corresponding to manager mode have been added.

### PR

- #4981
