### ISSUE TITLE
TypeError if empty rule is created

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-kibana-app#4946]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.4   | 7.17     | 1 |  |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**

The creation of a new rule file, without any rule defined, causes an unexpected TypeError.

<details>

<summary> Full log </summary>

**this.props.state is undefined**:
```
_callee$@https://172.31.17.26/440/bundles/plugin/wazuh/wazuh.chunk.10.js:5:3983852
tryCatch@https://172.31.17.26/440/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:6:84173
invoke@https://172.31.17.26/440/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:6:88197
defineIteratorMethods/</<@https://172.31.17.26/440/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:6:85368
file_editor_asyncGeneratorStep@https://172.31.17.26/440/bundles/plugin/wazuh/wazuh.chunk.10.js:5:3976974
_throw@https://172.31.17.26/440/bundles/plugin/wazuh/wazuh.chunk.10.js:5:3977424
```

</details>

**Steps to reproduce**
1. Navigate to Management>Rules
2. Set a valid rule filename
3. Save the new empty rule file

**Expected Result**
1. Only `Error file content is incorrect` should appear

**Actual Result**
1. A non-expected `TypeError` pannel appears at save time.

**Screenshots**
![typeerror](https://user-images.githubusercontent.com/11089305/205279310-44390439-f114-44b9-9304-7eb492410121.png)

**Video**

[typeerror.webm](https://user-images.githubusercontent.com/11089305/205279489-3a8a5016-0732-4f68-ad8f-9f87304cb174.webm)

**Comment by Machi3mfl** [comment]
### Solution

Added conditions to show enabled the "Save" button in the File Editor

- The file must have filename, and the content must change and not empty
