### ISSUE TITLE
Export formatted is not disabled when no logs appears in the log menu

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-kibana-app#4948]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.4   | 7.17     | 1 |  |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**

The `export formatted` option should be disabled if there are no results that match the research. This is the default behavior in the CDB list. However, this option is enabled in the logs menu, producing a `3034-No results` when no logs match the search.

**Steps to reproduce**
1. Navigate to Management>Logs
2. Produce an empty result search
3. Click on `Export formatted`
4. A `3034-No result` error should appear

**Expected Result**
1. If there are no matching results for the search, Export formatted should be disabled

**Actual Result**
1. Export formatted of empty results produce  a `3034-No result` error

**Video**

[log_export_error.webm](https://user-images.githubusercontent.com/11089305/205288759-bf69f9c0-301e-47fe-b3c7-ae58208e547a.webm)

**Comment by Desvelao** [comment]
# Changes
Now, the `Export formatted` button is disabled when there are no results for the selected filters.
