### ISSUE TITLE
Wrong command to start Windows agent

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-kibana-app#4949]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.4.0   | 7.x     | 4400 | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Firefox|

**Description**
After the testing performed [here](https://github.com/wazuh/wazuh/issues/15523#issuecomment-1332021717), we could see that the app shows a wrong command to start the Windows agent.

**Steps to reproduce**
1. Navigate to 'Deploy a ne agent'
2. Select a Windows agent
3. Scroll down to 'Start the agent'

**Expected Result**
1. `NET START WazuhSvc`

**Actual Result**
1. `update-rc.d wazuh-agent defaults && service wazuh-agent start`

**Screenshots**

![image](https://user-images.githubusercontent.com/80041853/205289773-eccc25f3-32a7-4fe9-88bd-825f2319d616.png)

**Comment by gdiazlo** [comment]
Fixed in https://github.com/wazuh/wazuh-kibana-app/issues/4931
