### ISSUE TITLE
Deploy agent server address wrong pasted value

### ISSUE THREAD

**Issue by Machi3mfl** [wazuh/wazuh-kibana-app#4950]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.4   | all     | 4xxx | Basic, ODFE, Xpack, |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
The server address input in the deploy agent page pastes the node name instead the node IP.

Related issue #4109 

**Steps to reproduce**
1. Go to Agent > Add new agent
2. In Server address input, select one option
3. Check if the WAZUH_MANAGER param in the command shows the IP instead node name

**Screenshots**

![image](https://user-images.githubusercontent.com/6089438/205291258-8d502a81-b4b8-40c6-a650-96f0ab71667e.png)

**Comment by Desvelao** [comment]
# Changes
- Use the manager IP instead of the manager name as the value for the `WAZUH_MANAGER_NAME` and `WAZUH_REGISTRATION_SERVER` deployment variables
