### ISSUE TITLE
Agent's events mitre links do not work

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-kibana-app#4951]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.4   | 7.17     | 1 | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
The event's Mitre links do not work properly

**Steps to reproduce**
1. Navigate to Modules>Agent Name> MITRE ATTACK
2. Click on one of the Mitre id links
3. Check that link does not work

**Video**

[mitre-link-does-not-work.webm](https://user-images.githubusercontent.com/11089305/205291652-1cdacbba-937c-498d-a83b-0420bed7bdb6.webm)

**Comment by Machi3mfl** [comment]
## Reproducing in 4.4 installed using Wazuh Official Quickstart commands

https://user-images.githubusercontent.com/6089438/207130117-171a5c8d-db6a-4a06-9855-4142a498f477.mp4

**Comment by davidjiglesias** [comment]
Does this replicate in v4.3.X?

**Comment by gdiazlo** [comment]
Closing it because we're unable to reproduce the cause of it. If it does appear again, we need to ensure we take notes on how to reproduce the issue.
