### ISSUE TITLE
SCA result filters do not work

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-kibana-app#4952]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.4   | 7.17     | 1 |  |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
CIS benchmark status filters do not work properly

**Preconditions**
1. Have a registered agent
2. Have a finished SCA scan of the agent

**Steps to reproduce**
1. Navigate to Modules>Agent name>Security configuration assessment
3. Click on one of the filter buttons (Pass, Fail, or Not applicable)
4. Check that no filter is applied.

**Video**

[sca.webm](https://user-images.githubusercontent.com/11089305/205292819-d9731d95-50ff-48db-9fc1-de79c0098311.webm)

**Comment by Machi3mfl** [comment]
### Replicating issue 

- CIS benchmark status filters do not work properly when the user clicks the stats (Pass, Failed, Not Applicable)

**Correct behavior**

When the user clicks the stats the checks table should be filtered by the selected stat
