### ISSUE TITLE
Style issue in Wazuh menu

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-kibana-app#4957]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
Some elements in the main Wazuh navigation menu have a disabled style and some others don't. This should be normalized.

**Screenshots**
![Peek 2022-12-05 12-45](https://user-images.githubusercontent.com/9343732/205700389-832d9313-8721-4bd7-9ed7-8ad784b60f16.gif)

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by Desvelao** [comment]
Duplicated https://github.com/wazuh/wazuh-kibana-app/issues/5097.
