### ISSUE TITLE
Vulnerabilities default last scan date not displayed properly

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-kibana-app#4959]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
The last scan date format has changed and this causes a workaround to prevent showing the default date returned by Wazuh API.

This lines should be updated to detect the default date and show `-` whenever no scan is run.

https://github.com/wazuh/wazuh-kibana-app/blob/v4.3.10-7.10.2/public/components/agents/vuls/inventory/detail.tsx#L172
https://github.com/wazuh/wazuh-kibana-app/blob/v4.3.10-7.10.2/public/components/agents/vuls/inventory.tsx#L179

**Preconditions**
1. No vulnerability scan has ever ran.

**Steps to reproduce**
1. Navigate to Vulnerabilities / Inventory
2. See the Last Scan dates

**Expected Result**
1. Should show `-` when no scan was ever executed

**Actual Result**
1. Shows default database date

**Screenshots**

![Screenshot from 2022-12-05 12-35-28](https://user-images.githubusercontent.com/9343732/205702218-a0506148-3dc2-4111-932a-10a71abf1a49.png)

**Comment by davidjiglesias** [comment]
Does this replicate in v4.3.X?

**Comment by yenienserrano** [comment]
In 4.3.9 it has the expected behavior

![image](https://user-images.githubusercontent.com/63758389/207642740-bdc758c5-ed4b-4d57-84f5-aad8b98786e7.png)

**Comment by Desvelao** [comment]
# Changes
- Fixed for vulnerabilities inventory and flyout with details
