### ISSUE TITLE
Add or remove Filebeat data fields from indices

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#496]
Hello team,

When using Filebeat to send alerts to Logstash, we can see some new fields on each alert document and a warning, indicating that the field is not mapped.

![alerts](https://user-images.githubusercontent.com/10928321/40540047-09a99696-6017-11e8-8489-db0dd8044f72.PNG)

We have to fix this, either by adding the fields to the Elasticsearch template, or by removing them on the Logstash configuration.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
Done here https://github.com/wazuh/wazuh-kibana-app/pull/497
