### ISSUE TITLE
Many filters added in Agent dashboard 

### ISSUE THREAD

**Issue by marciofoz** [wazuh/wazuh-kibana-app#500]
Hi!
The Agent dashboard in Kibana have a bug: in some circumstances after click some options sequence, the line of filters still with many options (filters): the issue allways start after select the option 'configuration'

To reproduce: select any agent, then on the agent's dasboard use this sequence: general, scap, configuration, vulnerabilities, configuration, pci dss, configuration, file integrity, configuration, general.

After doing it, the filter line show: manager.name:, agent.id:, rules.groups:"oscap", rule.groups:"vulnerability-detector", rule.pci_dss:"exists", rule.groups:"syscheck".

With this search filters, nothing are returned from search.

The correct must be keep only the last filter, and not stacking filters

BR

![img](https://user-images.githubusercontent.com/10158758/40554574-7dbe6836-601c-11e8-8e2d-f3acd526aef7.png)

**Comment by JuanjiJG** [comment]
Hello @marciofoz,

This is a known bug that was solved in https://github.com/wazuh/wazuh-kibana-app/pull/452 for the next Wazuh app package. We hope to release it very soon.

I apologize for the inconveniences this bug causes to you. You can reload the page as a workaround to solve this bug temporarily.

Let us know if you have more problems or questions.

Regards,
Juanjo

**Comment by marciofoz** [comment]
Hi JuanjiJG
Thank you by the reply.
Lets wait :)
