### ISSUE TITLE
Remove unneeded string substitution

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#5037]
We want to remove unneeded string substitution, where a single character is replaced by itself.

Tracking issue for:
- [x] [CodeQL#12](https://github.com/wazuh/wazuh-kibana-app/security/code-scanning/12)
- [x] [CodeQL#13](https://github.com/wazuh/wazuh-kibana-app/security/code-scanning/13)
- [x] [CodeQL#15](https://github.com/wazuh/wazuh-kibana-app/security/code-scanning/15)
- [x] [CodeQL#16](https://github.com/wazuh/wazuh-kibana-app/security/code-scanning/16)
- [x] [CodeQL#17](https://github.com/wazuh/wazuh-kibana-app/security/code-scanning/17)
- [x] [CodeQL#18](https://github.com/wazuh/wazuh-kibana-app/security/code-scanning/18)

**Comment by yenienserrano** [comment]
Solve: https://github.com/wazuh/wazuh-kibana-app/pull/5201
