### ISSUE TITLE
Show in agent table the disconnection reason

### ISSUE THREAD

**Issue by yenienserrano** [wazuh/wazuh-kibana-app#5051]
As a result of this [issue](https://github.com/wazuh/wazuh/issues/11011), new agent information will be added, this new information in principle will be details of the connection status, for the states never connected and disconnected, it would be necessary to analyze how it would be shown in the table, in case of having or not information and add it to the table.

**Comment by gdiazlo** [comment]
We must display this additional information as tooltips, instead of a new column or text in the status column, to simplify the UI.

**Comment by Tostti** [comment]
PR was successfully merged
