### ISSUE TITLE
Testing of the `Deploy new agent` section

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#5053]
## Description

Due to recent changes to this section, we need to perform a deep test to this component in order to ensure it works as expected, and that the command provided to install and enroll a Wazuh agent is correct.

## Summary

:green_circle: - Passed
:yellow_circle: - Doubt/comment to verify
:red_circle: - Failed

| OS           | Version           | Arch                | Status          | Comments                                                       |     |
| ------------ | ----------------- | ------------------- | --------------- | -------------------------------------------------------------- | --- |
| Red Hat      | 5                 | i386                | :green_circle:  |                                                                |     |
| Red Hat      | 5                 | x86_64              | :green_circle:  |                                                                |     |
| Red Hat      | 6                 | i386                | :green_circle:  |                                                                |     |
| Red Hat      | 6                 | x86_64              | :green_circle:  |                                                                |     |
| Red Hat      | 6                 | armhf               | :green_circle:  |                                                                |     |
| Red Hat      | 6                 | aarch64             | :green_circle:  |                                                                |     |
| Red Hat      | 7                 | i386                | :green_circle:  |                                                                |     |
| Red Hat      | 7                 | x86_64              | :green_circle:  |                                                                |     |
| Red Hat      | 7                 | armhf               | :green_circle:  |                                                                |     |
| Red Hat      | 7                 | aarch64             | :green_circle:  |                                                                |     |
| Red Hat      | 7                 | PowerPC             | :green_circle:  |                                                                |     |
| CentOS       | 5                 | i386                | :green_circle:  |                                                                |     |
| CentOS       | 5                 | x86_64              | :green_circle:  |                                                                |     |
| CentOS       | 6                 | i386                | :green_circle:  |                                                                |     |
| CentOS       | 6                 | x86_64              | :green_circle:  |                                                                |     |
| CentOS       | 6                 | armhf               | :green_circle:  |                                                                |     |
| CentOS       | 6                 | aarch64             | :green_circle:  |                                                                |     |
| CentOS       | 7 +               | i386                | :green_circle:  |                                                                |     |
| CentOS       | 7 +               | x86_64              | :green_circle:  |                                                                |     |
| CentOS       | 7 +               | armhf               | :green_circle:  |                                                                |     |
| CentOS       | 7 +               | aarch64             | :green_circle:  |                                                                |     |
| CentOS       | 7 +               | PowerPC             | :green_circle:  |                                                                |     |
| Ubuntu       | 14                | i386                | :green_circle:  |                                                                |     |
| Ubuntu       | 14                | x86_64              | :green_circle:  |                                                                |     |
| Ubuntu       | 14                | armhf               | :green_circle:  |                                                                |     |
| Ubuntu       | 14                | aarch64             | :green_circle:  |                                                                |     |
| Ubuntu       | 15+               | i386                | :green_circle:  |                                                                |     |
| Ubuntu       | 15+               | x86_64              | :green_circle:  |                                                                |     |
| Ubuntu       | 15+               | armhf               | :green_circle:  |                                                                |     |
| Ubuntu       | 15+               | aarch64             | :green_circle:  |                                                                |     |
| Windows      | XP                | i386/x86_64         | :green_circle:  |                                                                |     |
| Windows      | Server 2008       | i386/x86_64         | :green_circle:  |                                                                |     |
| Windows      | 7+                | i386/x86_64         | :green_circle:  |                                                                |     |
| macOS        | Sierra+           | Intel/Apple Silicon | :green_circle:  |                                                                |     |
| AIX          | 6.1 TL9 +         | PowerPC             | :green_circle:  |                                                                |     |
| Alpine       | 3.12.12 +         | i386                | :green_circle:  |                                                                |     |
| Alpine       | 3.12.12 +         | x86                 | :green_circle:  |                                                                |     |
| Alpine       | 3.12.12 +         | x86_64              | :green_circle:  |                                                                |     |
| Alpine       | 3.12.12 +         | armhf               | :green_circle:  |                                                                |     |
| Alpine       | 3.12.12 +         | aarch64             | :green_circle:  |                                                                |     |
| Alpine       | 3.12.12 +         | PowerPC             | :green_circle:  |                                                                |     |
| Amazon Linux | 1                 | i386                | :green_circle:  |                                                                |     |
| Amazon Linux | 1                 | x86_64              | :green_circle:  |                                                                |     |
| Amazon Linux | 1                 | armhf               | :green_circle:  |                                                                |     |
| Amazon Linux | 1                 | aarch64             | :green_circle:  |                                                                |     |
| Amazon Linux | 2                 | i386                | :green_circle:  |                                                                |     |
| Amazon Linux | 2                 | x86_64              | :green_circle:  |                                                                |     |
| Amazon Linux | 2                 | armhf               | :green_circle:  |                                                                |     |
| Amazon Linux | 2                 | aarch64             | :green_circle:  |                                                                |     |
| Amazon Linux | 2022              | i386                | :green_circle:  |                                                                |     |
| Amazon Linux | 2022              | x86_64              | :green_circle:  |                                                                |     |
| Amazon Linux | 2022              | armhf               | :green_circle:  |                                                                |     |
| Amazon Linux | 2022              | aarch64             | :green_circle:  |                                                                |     |
| Debian       | 7                 | i386                | :green_circle:  |                                                                |     |
| Debian       | 7                 | x86_64              | :green_circle:  |                                                                |     |
| Debian       | 7                 | armhf               | :green_circle:  |                                                                |     |
| Debian       | 7                 | aarch64             | :green_circle:  |                                                                |     |
| Debian       | 8                 | i386                | :green_circle:  |                                                                |     |
| Debian       | 8                 | x86_64              | :green_circle:  |                                                                |     |
| Debian       | 8                 | armhf               | :green_circle:  |                                                                |     |
| Debian       | 8                 | aarch64             | :green_circle:  |                                                                |     |
| Debian       | 9                 | i386                | :green_circle:  |                                                                |     |
| Debian       | 9                 | x86_64              | :green_circle:  |                                                                |     |
| Debian       | 9                 | armhf               | :green_circle:  |                                                                |     |
| Debian       | 9                 | aarch64             | :green_circle:  |                                                                |     |
| Debian       | 9                 | PowerPC             | :green_circle:  |                                                                |     |
| Fedora       | 22+               | i386                | :green_circle:  |                                                                |     |
| Fedora       | 22+               | x86_64              | :green_circle:  |                                                                |     |
| Fedora       | 22+               | armhf               | :green_circle:  |                                                                |     |
| Fedora       | 22+               | aarch64             | :green_circle:  |                                                                |     |
| Fedora       | 22+               | PowerPC             | :green_circle:  |                                                                |     |
| HP-UX        | 11.31+            | Itanium2            | :green_circle:  |                                                                |     |
| openSUSE     | Leap 15+          | i386                | :green_circle:  |                                                                |     |
| openSUSE     | Leap 15+          | x86_64              | :green_circle:  |                                                                |     |
| openSUSE     | Leap 15+          | armhf               | :green_circle:  |                                                                |     |
| openSUSE     | Leap 15+          | aarch64             | :green_circle:  |                                                                |     |
| openSUSE     | Leap 15+          | PowerPC             | :green_circle:  |                                                                |     |
| Oracle Linux | 5                 | i386                | :green_circle:  |                                                                |     |
| Oracle Linux | 5                 | x86_64              | :green_circle:  |                                                                |     |
| Oracle Linux | 6+                | i386                | :green_circle:  |                                                                |     |
| Oracle Linux | 6+                | x86_64              | :green_circle:  |                                                                |     |
| Oracle Linux | 6+                | armhf               | :green_circle:  |                                                                |     |
| Oracle Linux | 6+                | aarch64             | :green_circle:  |                                                                |     |
| Raspbian     | Buster or greater | i386                | :yellow_circle: | Should it be "Buster +" to be consistent with the rest of OSs? |     |
| Raspbian     | Buster or greater | x86_64              | :yellow_circle: | Should it be "Buster +" to be consistent with the rest of OSs? |     |
| Raspbian     | Buster or greater | armhf               | :yellow_circle: | Should it be "Buster +" to be consistent with the rest of OSs? |     |
| Raspbian     | Buster or greater | aarch64             | :yellow_circle: | Should it be "Buster +" to be consistent with the rest of OSs? |     |
| Raspbian     | Buster or greater | PowerPC             | :yellow_circle: | Should it be "Buster +" to be consistent with the rest of OSs? |     |
| Solaris      | 10                | i386                | :green_circle:  |                                                                |     |
| Solaris      | 10                | SPARC               | :green_circle:  |                                                                |     |
| Solaris      | 11                | i386                | :green_circle:  |                                                                |     |
| Solaris      | 11                | SPARC               | :green_circle:  |                                                                |     |
| SUSE         | 11                | i386                | :green_circle:  |                                                                |     |
| SUSE         | 11                | x86_64              | :green_circle:  |                                                                |     |
| SUSE         | 12                | i386                | :green_circle:  |                                                                |     |
| SUSE         | 12                | x86_64              | :green_circle:  |                                                                |     |
| SUSE         | 12                | armhf               | :green_circle:  |                                                                |     |
| SUSE         | 12                | aarch64             | :green_circle:  |                                                                |     |
| SUSE         | 12                | PowerPC             | :green_circle:  |                                                                |     |

## Related issues

- https://github.com/wazuh/wazuh-kibana-app/issues/4926
- https://github.com/wazuh/wazuh-kibana-app/issues/4927
- https://github.com/wazuh/wazuh-kibana-app/issues/4928
- https://github.com/wazuh/wazuh-kibana-app/issues/4931
- https://github.com/wazuh/wazuh-kibana-app/issues/4958

**Comment by AlexRuiz7** [comment]
For simplicity, only the package URL is shown. Every URL is prepended by the deployment variables, as follows:

```
sudo WAZUH_MANAGER='wazuh-master' WAZUH_AGENT_GROUP='default' WAZUH_AGENT_NAME='agent_01' yum install -y https://packages.wazuh.com/4.x/yum5/i386/wazuh-agent-4.4.0-1.el5.i386.rpm
``` 

#### RedHat Linux 5

- i386 🟢 
```
yum install -y https://packages.wazuh.com/4.x/yum5/i386/wazuh-agent-4.4.0-1.el5.i386.rpm
```

- x86_64 🟢 
```
yum install -y https://packages.wazuh.com/4.x/yum5/x86_64/wazuh-agent-4.4.0-1.el5.x86_64.rpm
```

#### RedHat Linux 6

- i386 🟢 
```
yum install -y https://packages.wazuh.com/4.x/yum/wazuh-agent-4.4.0-1.i386.rpm
```

- x86_64 🟢 
```
yum install -y https://packages.wazuh.com/4.x/yum/wazuh-agent-4.4.0-1.x86_64.rpm
```

- armhf 🟢 
```
yum install -y https://packages.wazuh.com/4.x/yum/wazuh-agent-4.4.0-1.armv7hl.rpm
```

- aarch64 🟢 
```
yum install -y https://packages.wazuh.com/4.x/yum/wazuh-agent-4.4.0-1.aarch64.rpm
```

#### RedHat Linux 7

- i386 🟢 
```
yum install -y https://packages.wazuh.com/4.x/yum/wazuh-agent-4.4.0-1.i386.rpm
```

- x86_64 🟢 
```
yum install -y https://packages.wazuh.com/4.x/yum/wazuh-agent-4.4.0-1.x86_64.rpm
```

- armhf 🟢 
```
yum install -y https://packages.wazuh.com/4.x/yum/wazuh-agent-4.4.0-1.armv7hl.rpm
```

- aarch64 🟢 
```
yum install -y https://packages.wazuh.com/4.x/yum/wazuh-agent-4.4.0-1.aarch64.rpm
```

- PowerPC 🟢 
```
yum install -y https://packages.wazuh.com/4.x/yum/wazuh-agent-4.4.0-1.ppc64le.rpm
```

**Comment by Tostti** [comment]
#### Debian 7

- 🟢 i386 
```
curl -so wazuh-agent.deb https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.4.0-1_i386.deb && sudo WAZUH_MANAGER='wazuh-master' WAZUH_AGENT_GROUP='default' WAZUH_AGENT_NAME='agent_01' dpkg -i ./wazuh-agent.deb
```

- 🟢 x86_64 
```
curl -so wazuh-agent.deb https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.4.0-1_amd64.deb && sudo WAZUH_MANAGER='wazuh-master' WAZUH_AGENT_GROUP='default' WAZUH_AGENT_NAME='agent_01' dpkg -i ./wazuh-agent.deb
```

- 🟢 armhf
```
curl -so wazuh-agent.deb https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.4.0-1_armhf.deb && sudo WAZUH_MANAGER='wazuh-master' WAZUH_AGENT_GROUP='default' WAZUH_AGENT_NAME='agent_01' dpkg -i ./wazuh-agent.deb
```

- 🟢 aarch64 
```
curl -so wazuh-agent.deb https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.4.0-1_arm64.deb && sudo WAZUH_MANAGER='wazuh-master' WAZUH_AGENT_GROUP='default' WAZUH_AGENT_NAME='agent_01' dpkg -i ./wazuh-agent.deb
```
#### Debian 8

- 🟢 i386 
```
curl -so wazuh-agent.deb https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.4.0-1_i386.deb && sudo WAZUH_MANAGER='wazuh-master' WAZUH_AGENT_GROUP='default' WAZUH_AGENT_NAME='agent_01' dpkg -i ./wazuh-agent.deb
```

- 🟢 x86_64 
```
curl -so wazuh-agent.deb https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.4.0-1_amd64.deb && sudo WAZUH_MANAGER='wazuh-master' WAZUH_AGENT_GROUP='default' WAZUH_AGENT_NAME='agent_01' dpkg -i ./wazuh-agent.deb
```

- 🟢 armhf
```
curl -so wazuh-agent.deb https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.4.0-1_armhf.deb && sudo WAZUH_MANAGER='wazuh-master' WAZUH_AGENT_GROUP='default' WAZUH_AGENT_NAME='agent_01' dpkg -i ./wazuh-agent.deb
```

- 🟢 aarch64 
```
curl -so wazuh-agent.deb https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.4.0-1_arm64.deb && sudo WAZUH_MANAGER='wazuh-master' WAZUH_AGENT_GROUP='default' WAZUH_AGENT_NAME='agent_01' dpkg -i ./wazuh-agent.deb
```

#### Debian 9+

- 🟢 i386 
```
curl -so wazuh-agent.deb https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.4.0-1_i386.deb && sudo WAZUH_MANAGER='wazuh-master' WAZUH_AGENT_GROUP='default' WAZUH_AGENT_NAME='agent_01' dpkg -i ./wazuh-agent.deb
```

- 🟢 x86_64 
```
curl -so wazuh-agent.deb https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.4.0-1_amd64.deb && sudo WAZUH_MANAGER='wazuh-master' WAZUH_AGENT_GROUP='default' WAZUH_AGENT_NAME='agent_01' dpkg -i ./wazuh-agent.deb
```

- 🟢 armhf
```
curl -so wazuh-agent.deb https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.4.0-1_armhf.deb && sudo WAZUH_MANAGER='wazuh-master' WAZUH_AGENT_GROUP='default' WAZUH_AGENT_NAME='agent_01' dpkg -i ./wazuh-agent.deb
```

- 🟢 aarch64 
```
curl -so wazuh-agent.deb https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.4.0-1_arm64.deb && sudo WAZUH_MANAGER='wazuh-master' WAZUH_AGENT_GROUP='default' WAZUH_AGENT_NAME='agent_01' dpkg -i ./wazuh-agent.deb
```

- 🟢 PowerPC
```
curl -so wazuh-agent.deb https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.4.0-1_ppc64el.deb && sudo WAZUH_MANAGER='wazuh-master' WAZUH_AGENT_GROUP='default' WAZUH_AGENT_NAME='agent_01' dpkg -i ./wazuh-agent.deb
```

#### Fedora 22+

- 🟢 i386 
```
sudo WAZUH_MANAGER='wazuh-master' WAZUH_AGENT_GROUP='default' WAZUH_AGENT_NAME='agent_01' yum install -y https://packages.wazuh.com/4.x/yum/wazuh-agent-4.4.0-1.i386.rpm
```

- 🟢 x86_64 
```
sudo WAZUH_MANAGER='wazuh-master' WAZUH_AGENT_GROUP='default' WAZUH_AGENT_NAME='agent_01' yum install -y https://packages.wazuh.com/4.x/yum/wazuh-agent-4.4.0-1.x86_64.rpm
```

- 🟢 armhf
```
sudo WAZUH_MANAGER='wazuh-master' WAZUH_AGENT_GROUP='default' WAZUH_AGENT_NAME='agent_01' yum install -y https://packages.wazuh.com/4.x/yum/wazuh-agent-4.4.0-1.armv7hl.rpm
```

- 🟢 aarch64 
```
sudo WAZUH_MANAGER='wazuh-master' WAZUH_AGENT_GROUP='default' WAZUH_AGENT_NAME='agent_01' yum install -y https://packages.wazuh.com/4.x/yum/wazuh-agent-4.4.0-1.aarch64.rpm
```

- 🟢 PowerPC
```
sudo WAZUH_MANAGER='wazuh-master' WAZUH_AGENT_GROUP='default' WAZUH_AGENT_NAME='agent_01' yum install -y https://packages.wazuh.com/4.x/yum/wazuh-agent-4.4.0-1.ppc64le.rpm
```

#### HP-UX 11.31 +

- 🟢 Itanium2 
```
cd / && sudo curl -so wazuh-agent.tar https://packages.wazuh.com/4.x/hp-ux/wazuh-agent-4.4.0-1-hpux-11v3-ia64.tar && sudo groupadd wazuh && sudo useradd -G wazuh wazuh && sudo tar -xvf wazuh-agent.tar
```
