### ISSUE TITLE
The menus show one agent but the list doesn't show.

### ISSUE THREAD

**Issue by jlruizmlg** [wazuh/wazuh-kibana-app#506]
If we have only one agent (manager 000), the agent list doesn't show any agent but then in the different menus show like one is registered.

<img width="1492" alt="27b25eb5-352d-4473-8e06-490fcf2d2cf5" src="https://user-images.githubusercontent.com/13950509/40629326-aab20720-62ca-11e8-8e0e-fa8bacf3fa8a.png">

**Comment by jesusgn90** [comment]
You are right @jlruizmlg , working on it, thanks!

**Comment by jesusgn90** [comment]
Done here https://github.com/wazuh/wazuh-kibana-app/pull/517
