### ISSUE TITLE
Update angular-material dependency to the latest version

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#507]
Hello team,

It's time to update our [angular-material](https://www.npmjs.com/package/angular-material) dependency to the latest available version.

Currently, we're using `angular-material` 1.1.1, and a lot has changed since the release of that version. Bugfixes, new features, etc. I think that if we want to re-design the Wazuh app UI, we could also take the chance to update this dependency and use the latest features.

This issue will start with a research, only modifying the dependency in our `package.json` file, to see what UI elements are now broken and if it requires a lot of work to fix them.

Regards,
Juanjo

**Comment by JuanjiJG** [comment]
**June 4th update:**

Working on this on the branch [`3.2-app-redesign`](https://github.com/wazuh/wazuh-kibana-app/tree/3.2-app-redesign).

Regards,
Juanjo

**Comment by JuanjiJG** [comment]
**June 7th update:**

We've found that the `md-autocomplete` component is not properly working on the app with the latest `angular-material` version.

We're going to revert the app to the previous version until we can find out the cause of this problem, and then update the dependency with the proper bugfix.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
Done in https://github.com/wazuh/wazuh-kibana-app/pull/743
