### ISSUE TITLE
Missing packages inventory on Solaris agents

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-kibana-app#5079]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Any|

**Description**

Currently we are not able to show agent's package inventory information for OSes different from

- Linux
- macOS
- Windows
- FreeBSD

Any other OS is not allowed, despite the package count being displayed. Some currently supported OSes are affected

- Solaris

It's desirable to show the inventory in a more flexible way for those explicitly mentioned OSes. This way, in case wazuh add the inventory capability on a new OS, at least some information is displayed

**Preconditions**
1. Enroll a Solaris Agent on a Wazuh Manager

**Steps to reproduce**
1. Navigate to Agent's section
2. Click on Solaris Agent
3. Click on Inventory
4. Scroll down to Packages information

**Expected Result**
1. Packages and packages count are listed

**Actual Result**
1.  Packages count is shown but not the information

**Screenshots**

![image](https://user-images.githubusercontent.com/1791430/210841504-b5dd1ab1-b013-4484-aa89-cbb08dbb57a2.png)

**Additional context**
 
Could be related to the next snippet

https://github.com/wazuh/wazuh-kibana-app/blob/fe7ebdfa00e32ba449ed9849e7780f7ea2a6e59a/public/components/agents/syscollector/inventory.tsx#L50-L58
https://github.com/wazuh/wazuh-kibana-app/blob/fe7ebdfa00e32ba449ed9849e7780f7ea2a6e59a/public/components/agents/syscollector/columns/packages-columns.ts#L1-L35

**Comment by gdiazlo** [comment]
This behavior is already present in releases 4.3.X and earlier.

**Comment by Dwordcito** [comment]
@gdiazlo note that the syscollector packages collection feature is added in 4.4

**Comment by Tostti** [comment]
Discovered another issue, that caused the application to crash if  `<hardware>` was enabled, due to missing fields.
 
![imagen](https://user-images.githubusercontent.com/42900763/213786493-92fd7aca-4635-495c-a3a3-4d8091741871.png)

That problem will be fixed in the same PR.
