### ISSUE TITLE
Misspelling in the NIST report

### ISSUE THREAD

**Issue by francobep** [wazuh/wazuh-kibana-app#5099]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| >4.3   | 7.x     | 4xxx | Wazuh Indexer |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
Misspelling in the NIST report

**Preconditions**
1. None 

**Steps to reproduce**
1. Generate the NIST Report

**Expected Result**
1. "Requirements"

**Actual Result**
1. "Requiments"

**Screenshots**
![image](https://user-images.githubusercontent.com/632969/211686151-2838bcfb-370c-4602-9a84-7c85a1e4c9d3.png)

**Additional context**
Bug reported on our slack channel by user Neil Underwood. https://wazuh.slack.com/archives/C0A933R8E/p1673390642744979
The error still remains in 4.4.x https://github.com/wazuh/wazuh-kibana-app/blob/281c807d7935e6b99dcad90728e80dbe30ec9c07/public/components/visualize/visualizations.js#L417

**Comment by AlexRuiz7** [comment]
Thanks @francobep 

We'll fix that asap.
