### ISSUE TITLE
Fix and update Overview and Agents "Audit" visualizations

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#511]
Hello team,

We've discovered that our Audit visualizations have some mismatches and incorrect queries according to what they're meant to show to the user, so we have to review and update all of them to make consistency.

There are even differences between the Overview and Agents visualizations for the Audit tab, so if they're showing the exact same content, they have to be built under the same search query.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
Done here https://github.com/wazuh/wazuh-kibana-app/pull/572
