### ISSUE TITLE
not getting audit dashboard

### ISSUE THREAD

**Issue by prashantvidja** [wazuh/wazuh-kibana-app#512]
Hello,

i have installed wazuh-kibana app with elk stack. i have one issue i am not getting data at audit dashboard,
but in general dashboard i see audit-alert coming but not displaying at dashboard.
i am attached two screenshots of my dashboard of manager
image-1)general dashboard
image-2)audit dashboard

![audit_issue](https://user-images.githubusercontent.com/26060662/40826454-477170b2-6598-11e8-80d0-8729f0874d37.png)
![audit_issue_2](https://user-images.githubusercontent.com/26060662/40826461-4b616902-6598-11e8-8ccc-25d09450ca64.png)

Thanks

**Comment by jesusgn90** [comment]
Well @prashantvidja , it's right since some Audit event alerts are not matching `rule.groups: "audit" `so you could see "Audit" alerts at the Overview tab but Agents tab is applying specific filter. 

Example, the alerts you are seeing at Overview from audits are matching the next fields:


```
 rule.description --> System Audit event.
 rule.groups --> ossec, rootcheck
```

So it's right they don't appear at Audit tab due to specific filter.

We'll review this for sure, thanks.

Regards,
Jesús

**Comment by prashantvidja** [comment]
hello @jesusgn90 ,

so what should I do for change group of alert? Because I want display audit log at audit dashboard.

Thanks for precious replay

**Comment by jesusgn90** [comment]
Hello again @prashantvidja ,

The team will review some rules to verify if they should be included in `audit` group too. Additionally you could force that alert modifying the rule 516 from https://github.com/wazuh/wazuh-ruleset/blob/3.2/rules/0015-ossec_rules.xml, add audit to its groups:

```
<rule id="516" level="3">
    <if_sid>510</if_sid>
    <match>^System Audit</match>
    <description>System Audit event.</description>
    <group>rootcheck,gdpr_IV_30.1.g,audit,</group>
</rule>
```
The modified line:

```
<group>rootcheck,gdpr_IV_30.1.g,audit,</group>
```

Restart the Wazuh manager:

```
/var/ossec/bin/ossec-control restart
```

Now you'll see them at Audit tab. 

__Note:__ Regardless that specific rule, the fully Audit features must to be configured following https://documentation.wazuh.com/current/user-manual/capabilities/system-calls-monitoring/audit-configuration.html, this way you can see more Audit related alerts, now you are __only__ seeing some alerts from rootcheck with Audit in their description.

Hope it helps,
Jesús

**Comment by jesusgn90** [comment]
Hello @prashantvidja , Is your problem solved? Please let us know, this way we can help you if the problem still persists or close the issue if it's now solved. Thanks in advance.

Regards,
Jesús

**Comment by HireLabs** [comment]
I am facing same, but my issue is not resolved.

**Comment by sulaiman35** [comment]
I am trying to add archive.json in kibana, can anyone help.

**Comment by jesusgn90** [comment]
Hello @HireLabs ,

Audit needs to be installed in each Linux agent you want to check. Following https://documentation.wazuh.com/current/user-manual/capabilities/system-calls-monitoring/audit-configuration.html we can see the command to install audit by OS:

Red Hat, CentOS and Fedora:
```
# yum install audit
```

Debian and Ubuntu based Linux distributions:

```
# apt-get install auditd
```
Once done, let's say we want to check the folder `/home/my_dir/` from agent 001:

- SSH into the agent 001 machine and execute the next commands:

```
auditctl -w /home/my_dir/ -p w -k audit-wazuh-w
auditctl -w /home/my_dir/ -p a -k audit-wazuh-a
auditctl -w /home/my_dir/ -p r -k audit-wazuh-r
auditctl -w /home/my_dir/ -p x -k audit-wazuh-x
```
After few minutes you'll see alerts from audit in the audit tab from Kibana.

I hope it helps,
Jesús

**Comment by jesusgn90** [comment]
Hello @sulaiman35 , I'm going to reply you at https://github.com/wazuh/wazuh/issues/954

Regards,
Jesús

**Comment by jagannathan123** [comment]
Hello Folks,

-> I installed with the wazuh-manager 3.6.2, wazuh-agent 3.6.1 , kibana -6.4.3 ,elasticsearch -6.4.3, logstash -6.4.3 . I am unable to getting the ossec-restart alert, But i get the alert for added manager and agent alerts.  

-> Please give me suggestion for fixing this alert issue asap.
![imageedit_2_8754110381](https://user-images.githubusercontent.com/20808448/51828785-5ab97d80-2312-11e9-878a-13f46e8dea95.png)
![imageedit_4_4120073579](https://user-images.githubusercontent.com/20808448/51828787-5ab97d80-2312-11e9-8392-02b32cbf91e8.png)
