### ISSUE TITLE
Error when using invalid configuration for agent.conf

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-kibana-app#5133]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | ODFE |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
Short description of your issue.

If we use an incorrect configuration in `agent.conf`  the dashboard shows an error page and sends us to the dashboard's initial page. This forces the user to navigate to the `agent.conf ` page again if they want to continue editing the file.

We would expect this error to be integrated into the page and the dashboard to show where the configuration error is.

**Preconditions**
1. 

**Steps to reproduce**
1. Navigate to `Management -> Groups -> Default -> Files -> agent.conf`
2. Set an incorrect configuration.
```
    <localfile>
      <location>/var/ossec/logs/ossec.log</location>
      <log_format>syslog</log_format>
    </localfile>
```
For example, this one is missing the <agent_config> tag.
3. Save configuration

**Expected Result**
1.  Report error.
2. Indicate error.
3. Allow continuing to edit file to solve error

**Actual Result**
1. Error window appears.
2. User is sent to a different page.

**Screenshots**

https://user-images.githubusercontent.com/19505384/212887861-94434d89-7eb4-4c56-9963-03edac9d7675.mp4

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by yenienserrano** [comment]
This behavior is already present in releases 4.3.X and earlier.

https://user-images.githubusercontent.com/63758389/212925405-53a74c17-e20a-4242-ae55-628646834328.mp4
