### ISSUE TITLE
[Alerts index pattern] No template found for the selected index-pattern title [wazuh-alerts-*]

### ISSUE THREAD

**Issue by cagatayyaman** [wazuh/wazuh-kibana-app#5139]
INFO: Index pattern id in cookie: yes [wazuh-alerts-*]
INFO: Getting list of valid index patterns...
INFO: Valid index patterns found: 1
INFO: Found default index pattern with title [wazuh-alerts-*]: yes
INFO: Checking the app default pattern exists: id [wazuh-alerts-*]...
INFO: Default pattern with id [wazuh-alerts-*] exists: yes
ACTION: Default pattern id [wazuh-alerts-*] set as default index pattern
INFO: Checking the index pattern id [wazuh-alerts-*] exists...
INFO: Index pattern id exists [wazuh-alerts-*]: yes
INFO: Index pattern id in cookie: yes [wazuh-alerts-*]
INFO: Checking if the index pattern id [wazuh-alerts-*] exists...
INFO: Index pattern id [wazuh-alerts-*] found: yes title [wazuh-alerts-*]
INFO: Checking if exists a template compatible with the index pattern title [wazuh-alerts-*]
INFO: Template found for the selected index-pattern title [wazuh-alerts-*]: no
ERROR: No template found for the selected index-pattern title [wazuh-alerts-*]
INFO: Index pattern id in cookie: [wazuh-alerts-*]
INFO: Getting index pattern data [wazuh-alerts-*]...
INFO: Index pattern data found: [yes]
INFO: Refreshing index pattern fields: title [wazuh-alerts-*], id [wazuh-alerts-*]...
ACTION: Refreshed index pattern fields: title [wazuh-alerts-*], id [wazuh-alerts-*]
![Ekran Resmi 2023-01-18 20 53 20](https://user-images.githubusercontent.com/77554129/213257576-5acfe024-9c41-4a63-a7e5-fae5a5927e0f.png)

**Comment by cagatayyaman** [comment]
how can i solve this problem.

**Comment by gdiazlo** [comment]
Hello @cagatayyaman the index pattern needs to be configured with the field mappings. This is automatically done in the wazuh installation by the filebeat's wazuh module. how did you install Wazuh? did you follow any of the guides on the [documentation site](https://documentation.wazuh.com)? 

By the looks of the screen, it looks like you're using an older version. Which platform are you deploying Wazuh into?  I would suggest you try the latest version.

**Comment by AlexRuiz7** [comment]
Close due to inactivity

**Comment by s-cuadro-r** [comment]
curl https://raw.githubusercontent.com/wazuh/wazuh/4.3.9/extensions/elasticsearch/7.x/wazuh-template.json"
    dest: "/path/to/wazuh-template.json
    
curl --silent -XPUT 'https://localhost:9200/_template/wazuh' -H 'Content-Type: application/json' --data-binary @wazuh-template.json -u admin:pass

**Comment by KDGundermann** [comment]
> curl https://raw.githubusercontent.com/wazuh/wazuh/4.3.9/extensions/elasticsearch/7.x/wazuh-template.json" dest: "/path/to/wazuh-template.json

Sadly the link is not working ...

**Comment by s-cuadro-r** [comment]
https://raw.githubusercontent.com/wazuh/wazuh/master/extensions/elasticsearch/7.x/wazuh-template.json
