### ISSUE TITLE
Deploy new agent - repeated requests

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#5140]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.4.0  | -    | beta1 | - |

| Browser |
| ------- |
| Firefox|

**Description**

The deploy agent page repeats each request four times.

**Steps to reproduce**
1. Navigate to agents
2. Click in Deploy new agent
3. Select any operating system

Every time a user selects an operating system, all request are repeated.

**Expected Result**
1. Only one request of each type is sent

**Actual Result**
1. Four request of each type is sent

**Screenshots**

![imagen](https://user-images.githubusercontent.com/2181918/213258104-12874228-37ed-4d8e-80fe-ca5dcc560b35.png)

**Comment by Machi3mfl** [comment]
This issue is resolved in https://github.com/wazuh/wazuh-kibana-app/pull/5166 pull request.
Evidence in PR [comment](https://github.com/wazuh/wazuh-kibana-app/pull/5166#issuecomment-1403867001)
