### ISSUE TITLE
Fix `msg_sent` field was removed from the manager stats

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#5151]
### Description

I was reviewing a pull request related to the indexation of manager stats in the indices `wazuh-statistics-*`. In the Wazuh plugin for Kibana/Wazuh dashboard, there is a visualization that uses the property `msg_sent` that should be returned by the remoted stats endpoints.
Endpoint: `GET /manager/stats/remoted` (same for the cluster endpoint). Screenshot of the response using a manager based in 4.4
![image](https://user-images.githubusercontent.com/34042064/214002232-a515903d-c627-4543-a9b2-e27242008872.png)

Visualization in the plugin:
![image](https://user-images.githubusercontent.com/34042064/214002187-d0f42bd2-6153-4bae-988b-6259c5f5b602.png)

I checked the API example responses of the Wazuh API, and it seems that in 4.3 the response doesn't include this field and in 4.2 this was included attending to the example response.
4.3: https://documentation.wazuh.com/4.3/user-manual/api/reference.html#operation/api.controllers.manager_controller.get_stats_remoted
4.2 https://documentation.wazuh.com/4.2/user-manual/api/reference.html#operation/api.controllers.manager_controller.get_stats_remoted

I asked the framework team, and @davidjiglesias found the related pull request that removed the `msg_sent` field in the core [https://github.com/wazuh/wazuh/pull/10326](https://github.com/wazuh/wazuh/pull/10326/files).

Related thread: https://wazuh-team.slack.com/archives/GNW3K8S6N/p1674464026145099

### Tasks
- [ ] Remove the `msg_sent` field from the
  - [ ] visualization
  - [ ] index template
  - [ ] indexed data
- [ ] Research if another field should be displayed in the visualization (indexed data and index template).

In my opinion, we should review the used fields in the visualization related to statistics too and ensure that the indexed data is being used in the defined visualizations.

**Comment by Desvelao** [comment]
Information provided by @vikman90:
> `msg_sent` was replaced by `queued_msgs` and `sent_bytes`, but stats were then replaced by the metrics ([#13713](https://github.com/wazuh/wazuh/pull/13713)) for 4.4
https://wazuh-team.slack.com/archives/GNW3K8S6N/p1674467667758009?thread_ts=1674464026.145099&cid=GNW3K8S6N

**Comment by asteriscos** [comment]
This issue will be solved in the refactoring of the statistics visualizations done in: 
[Statistics Histograms don't update X axis with large time intervals#5258](https://github.com/wazuh/wazuh-kibana-app/issues/5258)
