### ISSUE TITLE
Office365 and Github Panel information tab

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-kibana-app#5164]
| Wazuh | Opensearch | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.4.1   | 2.4.1     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
The left collapsibleNavBar in the modules Office365 and Github Panel tab doesn't work properly in Opensearch 2.4.1. When clicking the left tab with the _`i`_ icon it doesn't display the navbar with the module information.

**Preconditions**
1. Enable Github or Office365 module

**Steps to reproduce**
1. Navigate to Modules -> Github / Office365
2. Click on the `Panel` tab
3. Click on the laft tab with the _`i`_ icon

**Expected Result**
1. Display the navbra with the module configuration information

**Actual Result**
1. Nothing seems to be displayed

**Screenshots**

![Peek 2023-01-25 12-45](https://user-images.githubusercontent.com/9343732/214602541-4e92dc2d-cb06-4cf4-ad49-79fb8187295c.gif)

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by Desvelao** [comment]
# Changes

- Adapted to the `@opensearch-project/oui 1.0.0` used in OpenSearch Dashboards 2.4.1.
