### ISSUE TITLE
`Top rules` table in the Office 365 `Panel` tab displays data when should not

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#5175]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
The `Top rules` table of the `Office 365` module display unrelated data.

Someone should verify that is happening this behavior following the replication steps.

**Preconditions**
1. 

**Steps to reproduce**
> I experienced it with Wazuh 4.4.0 and Kibana 7.17.6

0. With an environment with alerts
1. Navigate to `Security events` module
2. Select an agent to explore through the `Explore agent` button
3. Go to the `Office 365` module
4. Go to the `Panel` tab of the `Office 365` module
5. Unpin the selected agent
6. The `Top rules` table  displays unrelated data

**Expected Result**
1. 

**Actual Result**
1. 

**Screenshots**
![image](https://user-images.githubusercontent.com/34042064/215066828-7149c82d-8e7f-46d0-b692-29054dba5241.png)

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by chantal-kelm** [comment]
Could not reproduce the error in Wazuh 4.6.0 Opensearch 2.6.0

https://github.com/wazuh/wazuh-kibana-app/assets/99441266/053a050b-aafa-46d6-9d9f-5c9d8e714405

**Comment by chantal-kelm** [comment]
An attempt was made to reproduce the error in Wazuh 4.4.5 Kibana 7.17.6 but the error did not occur.

<img width="1792" alt="image" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/28096fe0-3a36-42bb-9374-4abb7e068573">

https://github.com/wazuh/wazuh-kibana-app/assets/99441266/245ac888-8343-484d-9762-b54bb5306f07

**Comment by Machi3mfl** [comment]
# Reproducing

## 4.5.0 - 7.10.2 with a manager

![image](https://github.com/wazuh/wazuh-kibana-app/assets/6089438/d3ae655e-c255-4b34-a9d7-183b264e4f8c)

![image](https://github.com/wazuh/wazuh-kibana-app/assets/6089438/79cbd9fd-e985-4796-aa16-067185af073a)


## 4.5.0 - 7.16 with a manager

![image](https://github.com/wazuh/wazuh-kibana-app/assets/6089438/8849cbea-2371-4af4-8170-7e84124b59df)

![image](https://github.com/wazuh/wazuh-kibana-app/assets/6089438/97709d2a-3d6a-4a95-a043-228440077831)

### Conclusion

Tested it with a real manager for wazuh version 4.5.0 and the behavior mentioned in this issue doesn't occur.

**Comment by chantal-kelm** [comment]
The incident has been closed because it could not be reproduced.
