### ISSUE TITLE
Release 4.4.0 - RC1 - Kibana UI regression testing

### ISSUE THREAD

**Issue by Tostti** [wazuh/wazuh-kibana-app#5180]
## Description

This issue aims to track the effort to perform complete regression testing on Wazuh App 4.4.0 rev 01 for RC1

| Test         | Chrome | Safari | Firefox | Package |
|--------------|--------|--------|---------|---------|
| Example test | 🟢/🔴  | 🟢/🔴  | 🟢/🔴   | 🟢/🔴   |
 
### Status legend
⚫ - None
🔴 - Rejected
🟢 - Approved

In the case of 🔴, **create and add** the issue to the Bug Tracking section. 

### Testing plan

- [Office365 and Github Panel information tab](https://github.com/wazuh/wazuh-kibana-app/issues/5164)
- [Disable sync information in agent table by default](https://github.com/wazuh/wazuh-kibana-app/issues/5141)
- [Alerts Summary table results truncated](https://github.com/wazuh/wazuh-kibana-app/issues/5130)
- [The "Deploy a new agent" section misleads users with an all-in-one deployment](https://github.com/wazuh/wazuh-kibana-app/issues/5138)
- [Missing packages inventory on Solaris agents](https://github.com/wazuh/wazuh-kibana-app/issues/5079)
- [Deploy new agent - repeated requests](https://github.com/wazuh/wazuh-kibana-app/issues/5140)
- [Render button with different styles in events](https://github.com/wazuh/wazuh-kibana-app/issues/5136)
- [Mapper parsing exception in demo dashboard](https://github.com/wazuh/wazuh-automation/issues/1020)

### Testing notes

1) All the mentioned versions will be tested
2) It's necessary to include evidence of each test performed
3) In case to identify a bug/problem, the new feature should be linked to this issue

  - [x] 7.17.8
  - [x] 7.17.7
  - [x] 7.16.3
  - [x] 7.10.2
  - [x] WzD 4.4.0-01

Testing template: [template_testing_4.4.0-RC1.md](https://github.com/wazuh/wazuh-kibana-app/files/10522255/template_testing_4.4.0-RC1.md)

**Comment by Tostti** [comment]
# 7.10.2

Legend:
:black_circle:: none
:green_circle:: passed
:red_circle:: failed
:yellow_circle:: warning
:white_circle:: not applicable

| Test | Chrome | Firefox | Safari | Package |
| --- |  --- | --- | --- | --- |
| [Office365 and Github Panel information tab](https://github.com/wazuh/wazuh-kibana-app/issues/5164) | :black_circle: | :black_circle: | :black_circle: | 7.10.2 |
| [Disable sync information in agent table by default](https://github.com/wazuh/wazuh-kibana-app/issues/5141) | :black_circle: | :black_circle: | :black_circle: | 7.10.2 |
| [Alerts Summary table results truncated](https://github.com/wazuh/wazuh-kibana-app/issues/5130) | :black_circle: | :black_circle: | :black_circle: | 7.10.2 |
| [The "Deploy a new agent" section misleads users with an all-in-one deployment](https://github.com/wazuh/wazuh-kibana-app/issues/5138) | :black_circle: | :black_circle: | :black_circle: | 7.10.2 |
| [Missing packages inventory on Solaris agents](https://github.com/wazuh/wazuh-kibana-app/issues/5079)| :black_circle: | :black_circle: | :black_circle: | 7.10.2 |
| [Deploy new agent - repeated requests](https://github.com/wazuh/wazuh-kibana-app/issues/5140) | :black_circle: | :black_circle: | :black_circle: | 7.10.2 |
| [Render button with different styles in events](https://github.com/wazuh/wazuh-kibana-app/issues/5136) | :black_circle: | :black_circle: | :black_circle: | 7.10.2 |
| [Mapper parsing exception in demo dashboard](https://github.com/wazuh/wazuh-automation/issues/1020) | :black_circle: | :black_circle: | :black_circle: | 7.10.2 |


**Details**
<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5164" target="_blank">Office365 and Github Panel information tab</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5141" target="_blank">Disable sync information in agent table by default</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5130" target="_blank">Alerts Summary table results truncated</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5138" target="_blank">The "Deploy a new agent" section misleads users with an all-in-one deployment</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5079" target="_blank">Missing packages inventory on Solaris agents</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5140" target="_blank">Deploy new agent - repeated requests</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5136" target="_blank">Render button with different styles in events</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-automation/issues/1020" target="_blank">Mapper parsing exception in demo dashboard</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

**Comment by Machi3mfl** [comment]
# 7.16.3 (In progress)

Legend:
:black_circle:: none
:green_circle:: passed
:red_circle:: failed
:yellow_circle:: warning
:white_circle:: not applicable

| Test | Chrome | Firefox | Safari | Package |
| --- |  --- | --- | --- | --- |
| [Office365 and Github Panel information tab](https://github.com/wazuh/wazuh-kibana-app/issues/5164) | :black_circle: | :black_circle: | :black_circle: | 7.16.3 |
| [Disable sync information in agent table by default](https://github.com/wazuh/wazuh-kibana-app/issues/5141) | :black_circle: | :black_circle: | :black_circle: | 7.16.3 |
| [Alerts Summary table results truncated](https://github.com/wazuh/wazuh-kibana-app/issues/5130) | :black_circle: | :black_circle: | :black_circle: | 7.16.3 |
| [The "Deploy a new agent" section misleads users with an all-in-one deployment](https://github.com/wazuh/wazuh-kibana-app/issues/5138) | :black_circle: | :black_circle: | :black_circle: | 7.16.3 |
| [Missing packages inventory on Solaris agents](https://github.com/wazuh/wazuh-kibana-app/issues/5079)| :black_circle: | :black_circle: | :black_circle: | 7.16.3 |
| [Deploy new agent - repeated requests](https://github.com/wazuh/wazuh-kibana-app/issues/5140) | :black_circle: | :black_circle: | :black_circle: | 7.16.3 |
| [Render button with different styles in events](https://github.com/wazuh/wazuh-kibana-app/issues/5136) | :black_circle: | :black_circle: | :black_circle: | 7.16.3 |
| [Mapper parsing exception in demo dashboard](https://github.com/wazuh/wazuh-automation/issues/1020) | :black_circle: | :black_circle: | :black_circle: | 7.16.3 |


**Details**
<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5164" target="_blank">Office365 and Github Panel information tab</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5141" target="_blank">Disable sync information in agent table by default</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5130" target="_blank">Alerts Summary table results truncated</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5138" target="_blank">The "Deploy a new agent" section misleads users with an all-in-one deployment</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5079" target="_blank">Missing packages inventory on Solaris agents</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5140" target="_blank">Deploy new agent - repeated requests</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5136" target="_blank">Render button with different styles in events</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-automation/issues/1020" target="_blank">Mapper parsing exception in demo dashboard</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

**Comment by chantal-kelm** [comment]
# 7.10.2 ODFE (In progress)

Legend:
:black_circle:: none
:green_circle:: passed
:red_circle:: failed
:yellow_circle:: warning
:white_circle:: not applicable

| Test | Chrome | Firefox | Safari | Package |
| --- |  --- | --- | --- | --- |
| [Office365 and Github Panel information tab](https://github.com/wazuh/wazuh-kibana-app/issues/5164) | :black_circle: | :black_circle: | :black_circle: | 7.16.3 |
| [Disable sync information in agent table by default](https://github.com/wazuh/wazuh-kibana-app/issues/5141) | :black_circle: | :black_circle: | :black_circle: | 7.16.3 |
| [Alerts Summary table results truncated](https://github.com/wazuh/wazuh-kibana-app/issues/5130) | :black_circle: | :black_circle: | :black_circle: | 7.16.3 |
| [The "Deploy a new agent" section misleads users with an all-in-one deployment](https://github.com/wazuh/wazuh-kibana-app/issues/5138) | :black_circle: | :black_circle: | :black_circle: | 7.16.3 |
| [Missing packages inventory on Solaris agents](https://github.com/wazuh/wazuh-kibana-app/issues/5079)| :black_circle: | :black_circle: | :black_circle: | 7.16.3 |
| [Deploy new agent - repeated requests](https://github.com/wazuh/wazuh-kibana-app/issues/5140) | :black_circle: | :black_circle: | :black_circle: | 7.16.3 |
| [Render button with different styles in events](https://github.com/wazuh/wazuh-kibana-app/issues/5136) | :black_circle: | :black_circle: | :black_circle: | 7.16.3 |
| [Mapper parsing exception in demo dashboard](https://github.com/wazuh/wazuh-automation/issues/1020) | :black_circle: | :black_circle: | :black_circle: | 7.16.3 |


**Details**
<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5164" target="_blank">Office365 and Github Panel information tab</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5141" target="_blank">Disable sync information in agent table by default</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5130" target="_blank">Alerts Summary table results truncated</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5138" target="_blank">The "Deploy a new agent" section misleads users with an all-in-one deployment</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5079" target="_blank">Missing packages inventory on Solaris agents</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5140" target="_blank">Deploy new agent - repeated requests</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5136" target="_blank">Render button with different styles in events</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-automation/issues/1020" target="_blank">Mapper parsing exception in demo dashboard</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

**Comment by Machi3mfl** [comment]
# Wazuh Dashboard 2.4.1

Legend:
:black_circle:: none
:green_circle:: passed
:red_circle:: failed
:yellow_circle:: warning
:white_circle:: not applicable

| Test | Chrome | Firefox | Safari | Package |
| --- |  --- | --- | --- | --- |
| [Office365 and Github Panel information tab](https://github.com/wazuh/wazuh-kibana-app/issues/5164) | :green_circle: | :green_circle: | :black_circle: | Wazuh Dashboard 2.4.1 |
| [Disable sync information in agent table by default](https://github.com/wazuh/wazuh-kibana-app/issues/5141) | :green_circle: | :green_circle: | :black_circle: | Wazuh Dashboard 2.4.1 |
| [Alerts Summary table results truncated](https://github.com/wazuh/wazuh-kibana-app/issues/5130) | :green_circle: | :green_circle: | :black_circle: | Wazuh Dashboard 2.4.1 |
| [The "Deploy a new agent" section misleads users with an all-in-one deployment](https://github.com/wazuh/wazuh-kibana-app/issues/5138) | :green_circle: | :green_circle: | :black_circle: | Wazuh Dashboard 2.4.1 |
| [Missing packages inventory on Solaris agents](https://github.com/wazuh/wazuh-kibana-app/issues/5079)| :black_circle: | :black_circle: | :black_circle: | Wazuh Dashboard 2.4.1 |
| [Deploy new agent - repeated requests](https://github.com/wazuh/wazuh-kibana-app/issues/5140) | :green_circle: | :green_circle: | :black_circle: | Wazuh Dashboard 2.4.1 |
| [Render button with different styles in events](https://github.com/wazuh/wazuh-kibana-app/issues/5136) | :green_circle: | :green_circle: | :black_circle: | Wazuh Dashboard 2.4.1 |
| [Mapper parsing exception in demo dashboard](https://github.com/wazuh/wazuh-automation/issues/1020) | :green_circle: | :green_circle: | :black_circle: | Wazuh Dashboard 2.4.1 |


**Details**
<details>
<summary>:green_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5164" target="_blank">Office365 and Github Panel information tab</a></summary>

Chrome - :green_circle: :

![image](https://user-images.githubusercontent.com/6089438/215550144-c930fba7-d50f-41f2-b971-ff1fdf9dac24.png)

Firefox - :green_circle:

![image](https://user-images.githubusercontent.com/6089438/215550377-7ac58ce0-5970-4efa-ae9b-0dec70d2ece3.png)

Safari - :black_circle:


</details>

<details>
<summary>:green_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5141" target="_blank">Disable sync information in agent table by default</a></summary>

Chrome - :green_circle:

![image](https://user-images.githubusercontent.com/6089438/215550659-942c4a32-56ea-4173-9ba7-786d109a77fd.png)

Firefox - :green_circle:

![image](https://user-images.githubusercontent.com/6089438/215550744-fe6e4c06-50eb-4737-be18-f5a9fe71ee3d.png)

Safari - :black_circle:


</details>

<details>
<summary>:green_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5130" target="_blank">Alerts Summary table results truncated</a></summary>

Chrome - :green_circle:

![image](https://user-images.githubusercontent.com/6089438/215550868-fbc180aa-48b0-42b7-8715-cdc8081adfe4.png)

Firefox - :green_circle:

![image](https://user-images.githubusercontent.com/6089438/215550996-9b9b4ba7-5734-4b07-b366-9856427e4fed.png)

Safari - :black_circle:


</details>

<details>
<summary>:green_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5138" target="_blank">The "Deploy a new agent" section misleads users with an all-in-one deployment</a></summary>

Chrome - :green_circle:

![image](https://user-images.githubusercontent.com/6089438/215551259-d61dea72-9856-49b8-9dbf-9c22b95d88c9.png)

Firefox - :green_circle:

![image](https://user-images.githubusercontent.com/6089438/215551439-6062aa7d-2fde-4548-838d-46173133145c.png)

Safari - :black_circle:


</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5079" target="_blank">Missing packages inventory on Solaris agents</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

<details>
<summary>:green_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5140" target="_blank">Deploy new agent - repeated requests</a></summary>

Chrome - :green_circle:

![image](https://user-images.githubusercontent.com/6089438/215551651-7e152aab-d068-4f24-abae-1a322f11129f.png)


Firefox - :green_circle:

https://user-images.githubusercontent.com/6089438/215551905-a17e2427-56fe-4e2b-b254-7e6de6b69a8e.mp4

Safari - :black_circle:


</details>

<details>
<summary> :green_circle:  <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5136" target="_blank">Render button with different styles in events</a></summary>

Chrome - :green_circle:

![image](https://user-images.githubusercontent.com/6089438/215552063-e4691dde-b1a1-4429-bfd1-534fc8b5cd99.png)

Firefox - :green_circle:

![image](https://user-images.githubusercontent.com/6089438/215552287-79352e90-361a-44bd-9af4-e3176e91dc16.png)

Safari - :black_circle:


</details>

<details>
<summary>:green_circle: <a href="https://github.com/wazuh/wazuh-automation/issues/1020" target="_blank">Mapper parsing exception in demo dashboard</a></summary>

Chrome - :green_circle:

![image](https://user-images.githubusercontent.com/6089438/215559842-836565d4-ae99-4136-9412-efcd997f196d.png)

Firefox - :green_circle:

![image](https://user-images.githubusercontent.com/6089438/215560258-1235f8c5-92a2-476e-9995-4b3e7baa876c.png)


Safari - :black_circle:


</details>

**Comment by Tostti** [comment]
# 7.10.2 (In progress)

Legend:
:black_circle:: none
:green_circle:: passed
:red_circle:: failed
:yellow_circle:: warning
:white_circle:: not applicable

| Test | Chrome | Firefox | Safari | Package |
| --- |  --- | --- | --- | --- |
| [Office365 and Github Panel information tab](https://github.com/wazuh/wazuh-kibana-app/issues/5164) | :black_circle: | :black_circle: | :black_circle: | 7.10.2 |
| [Disable sync information in agent table by default](https://github.com/wazuh/wazuh-kibana-app/issues/5141) | :black_circle: | :black_circle: | :black_circle: | 7.10.2 |
| [Alerts Summary table results truncated](https://github.com/wazuh/wazuh-kibana-app/issues/5130) | :black_circle: | :black_circle: | :black_circle: | 7.10.2 |
| [The "Deploy a new agent" section misleads users with an all-in-one deployment](https://github.com/wazuh/wazuh-kibana-app/issues/5138) | :black_circle: | :black_circle: | :black_circle: | 7.10.2 |
| [Missing packages inventory on Solaris agents](https://github.com/wazuh/wazuh-kibana-app/issues/5079)| :black_circle: | :black_circle: | :black_circle: | 7.10.2 |
| [Deploy new agent - repeated requests](https://github.com/wazuh/wazuh-kibana-app/issues/5140) | :black_circle: | :black_circle: | :black_circle: | 7.10.2 |
| [Render button with different styles in events](https://github.com/wazuh/wazuh-kibana-app/issues/5136) | :black_circle: | :black_circle: | :black_circle: | 7.10.2 |
| [Mapper parsing exception in demo dashboard](https://github.com/wazuh/wazuh-automation/issues/1020) | :black_circle: | :black_circle: | :black_circle: | 7.10.2 |


**Details**
<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5164" target="_blank">Office365 and Github Panel information tab</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5141" target="_blank">Disable sync information in agent table by default</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5130" target="_blank">Alerts Summary table results truncated</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5138" target="_blank">The "Deploy a new agent" section misleads users with an all-in-one deployment</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5079" target="_blank">Missing packages inventory on Solaris agents</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5140" target="_blank">Deploy new agent - repeated requests</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5136" target="_blank">Render button with different styles in events</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-automation/issues/1020" target="_blank">Mapper parsing exception in demo dashboard</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

**Comment by Desvelao** [comment]
**New package were created for Kibana 7.16-7.17** with a change that was not included in the previous package.

# 7.17.8

Legend:
:black_circle:: none
:green_circle:: passed
:red_circle:: failed
:yellow_circle:: warning
:white_circle:: not applicable

| Test | Chrome | Firefox | Safari | Package |
| --- |  --- | --- | --- | --- |
| [Render button with different styles in events](https://github.com/wazuh/wazuh-kibana-app/issues/5136) | :green_circle: | :red_circle: | :red_circle: | 7.17.8 |

**Details**
<details>
<summary>:red_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5136" target="_blank">Render button with different styles in events</a></summary>

Chrome - :green_circle:
![image](https://user-images.githubusercontent.com/34042064/216032485-a8dd7aed-02cb-4eca-851f-8393184b6b71.png)
![image](https://user-images.githubusercontent.com/34042064/216032524-a22a8c7a-67fa-46d8-a418-7d3394e6f500.png)

Firefox - :green_circle:
![image](https://user-images.githubusercontent.com/34042064/216032766-9cab2dc9-5889-42bb-9c86-58f72e2445d5.png)
![image](https://user-images.githubusercontent.com/34042064/216032800-551cd3eb-3dff-4aef-9df2-32a207337913.png)

Safari - :black_circle:

</details>

**Comment by Desvelao** [comment]
**New package were created for Kibana 7.16-7.17** with a change that was not included in the previous package.

# 7.16.3

Legend:
:black_circle:: none
:green_circle:: passed
:red_circle:: failed
:yellow_circle:: warning
:white_circle:: not applicable

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| [Render button with different styles in events](https://github.com/wazuh/wazuh-kibana-app/issues/5136) | :green_circle: | :green_circle: | :black_circle: |

**Details**
<details>
<summary>:green_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5136" target="_blank">Render button with different styles in events</a></summary>

Chrome - :green_circle:
![image](https://user-images.githubusercontent.com/34042064/216037310-1fb34653-185e-4707-8126-8567487e45f1.png)
![image](https://user-images.githubusercontent.com/34042064/216037506-a33f911f-81f6-43a1-9a5b-46ffb1cfba3e.png)
![image](https://user-images.githubusercontent.com/34042064/216037942-be4e5098-2b7a-4201-a1ab-4ea04989730a.png)

Firefox - :green_circle:
![image](https://user-images.githubusercontent.com/34042064/216038002-5c78c2e2-ece7-441b-837f-418928c1e931.png)
![image](https://user-images.githubusercontent.com/34042064/216038071-55a4fee2-f098-4df6-86ad-ede2b3621890.png)

Safari - :black_circle:

</details>

**Comment by AlexRuiz7** [comment]
No issues were found, however, the release was delayed, and we were required to include new changes, for which we will create a new RC regression test, testing these new changes.

Closed as done. We'll open a new issue for the new test iteration.
