### ISSUE TITLE
Upgrade project dependencies

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-kibana-app#5189]
## Description
We need to review these pull requests to upgrade the dependencies to the latest version available. Even though we found no vulnerability to address, we have to improve the app's robustness.

Only pull request pointing to **4.5** will be taken into account.

## Related pull requests
- https://github.com/wazuh/wazuh-kibana-app/pulls/app%2Fdependabot

**Comment by AlexRuiz7** [comment]
To make any roll-back easier, we'll merge all the pull requests into a temporal branch, test and then squash every bump into a single commit.

1. Create branch `5189-bump-dependencies`
2. Merge dependabot's pull requests there
3. Test
4. Open pull request to `4.5`
5. Squash merge

**Comment by AlexRuiz7** [comment]
Each pull request has been tests and managed indepedently.
