### ISSUE TITLE
The agent deploy section should allow the Apple silicon architecture for macOS

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-kibana-app#5202]
**Epic:** https://github.com/wazuh/wazuh/issues/15055
## Summary
Wazuh agent will be able to be installed in macOS with Apple silicon processors natively. New installers will be created, so the agent deploy section needs to allow the architecture selection and give a correct link to the corresponding installer. 

The package name in the script should be:
`wazuh-agent-${VERSION}-${REVISION}.${ARCH}.pkg`
Where `ARCH` can be `intel64` or `arm64` depending on the selected architecture.

**Comment by giladreich** [comment]
Hi @alberpilot, @asteriscos and @DFolchA, what about [FAT Mach-O](https://en.wikipedia.org/wiki/Fat_binary) Package? No plans adding support for Universal Binaries? Can be done with few `lipo` commands.
Let me know if you need help with this and thank you!

**Comment by vikman90** [comment]
Hi @giladreich, our plan initially is to provide one package for each macOS architecture, just as we do with other platforms (refer to [Packages list](https://documentation.wazuh.com/current/installation-guide/packages-list.html)).

IMHO one package per architecture has the advantage of taking up less space and is easily classifiable by a DevOps team.

We are open to proposals, feel free to open an issue as a feature request for this issue!
