### ISSUE TITLE
Flyout does not close when clicking out of them in vulnerabilities

### ISSUE THREAD

**Issue by yenienserrano** [wazuh/wazuh-kibana-app#5209]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3.10   | 7.10.2     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
The vulnerability flyout, in kibana 7.10.2, has by default the ownFocus set to false, so clicking outside the flyout does not close it, and you can interact with the table below the flyout.

As of kibana 7.16 and in OSD 2.4 you are not having the problem because the default value of that property is true. 

**Preconditions**
1. 

**Steps to reproduce**
1. Navigate to 'Vulnerabilities'
2. Click on 'some vulnerabilidy'
3. Click outside 'flyout'
4. See that the flyout does not close

**Expected Result**
1. 
![image](https://user-images.githubusercontent.com/63758389/218449073-85ba4302-0a00-4926-9137-c190bef3d130.png)

**Actual Result**
1. 
![image](https://user-images.githubusercontent.com/63758389/218448983-7c7ea61f-ec20-477f-8387-7ffccbf37ec8.png)

**Screenshots**

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by gdiazlo** [comment]
Won't do. Supported platforms do not suffer from this situation.
