### ISSUE TITLE
Create redistributable boards for Splunk

### ISSUE THREAD

**Issue by chantal-kelm** [wazuh/wazuh-kibana-app#5222]
## Description

We want to implement new boards and panels based on our documentation, which will cover the following:

- [Security analysis](https://documentation.wazuh.com/current/_images/screenshot-01-Wazuh-Security-Analytics1.png)
- [Intrusion detection](https://documentation.wazuh.com/current/_images/screenshot-02-Wazuh-Intrusion-Detection1.png)
- [Log data analysis](https://documentation.wazuh.com/current/_images/screenshot-03-Wazuh-Log-Data-Analysis1.png)
- [File integrity monitoring](https://documentation.wazuh.com/current/_images/screenshot-04-Wazuh-File-Integrity-Monitoring1.png)
- [Vulnerability detection](https://documentation.wazuh.com/current/_images/screenshot-05-Wazuh-Vulnerability-Detection1.png)
- [Configuration assessment](https://documentation.wazuh.com/current/_images/screenshot-06-Wazuh-Configuration-Assessment1.png)
- [Incident response](https://documentation.wazuh.com/current/_images/screenshot-07-Wazuh-Incident-Response1.png)
- [Regulatory compliance](https://documentation.wazuh.com/current/_images/screenshot-08-Wazuh-Regulatory-Compliance1.png)
- [Cloud security](https://documentation.wazuh.com/current/_images/screenshot-09-Wazuh-Cloud-Security1.png)
- [Containers security](https://documentation.wazuh.com/current/_images/screenshot-10-Wazuh-Containers-Security1.png)

We want to use our sample data as the base for its creation. 

- Create a Splunk environment using the latest version
- Upload our sample data collection
- Using Splunk dashboard studio, create each query and dashboard to compose each of the dashboards

Tracked in: 
- https://github.com/wazuh/wazuh-kibana-app/issues/5182

**Comment by chantal-kelm** [comment]
Doing some research on exporting and importing dashboards in Splunk, I set up another testing environment.
After a lot of reading in documentation and community, I have seen that Splunk does not yet offer an option to export dashboards.
I have come up with an option that may be useful for the user to make use of these dashboards created in Splunk, and it is the following:

When entering a dashboard created with Splunk Dashboard Studio, clicking on the **source** button we can see the code of the dashboard we have created, we copy the code and save it in a file that is the one we will provide to the user.

**The following video shows the example with the Amazon AWS dashboard:**

https://user-images.githubusercontent.com/99441266/221947412-7e159480-7e1b-4e44-8aff-777b70d11029.mov

The user must choose the option to create a new dashboard with Dashboard Studio, click on the source button, paste the code from the file we provide and the dashboard will be loaded.

**The following video shows the example with the Amazon AWS dashboard:**

https://user-images.githubusercontent.com/99441266/221949016-e24b5306-e3f1-466d-81ff-f72678b610ae.mov

**Comment by chantal-kelm** [comment]
Researching Splunk Cloud to see if it could help us with the problem of exporting and importing dashboards and after doing some testing in Splunk Cloud with my partner @Desvelao we have seen that it is not possible to import Dashboards from Splunk Enterprise to Splunk Cloud or vice versa as they are two different products and the way and syntax in which the dashboards are built in each is totally different.

I am currently working on importing dashboards with curl to Splunk Enterprise.

**Comment by chantal-kelm** [comment]
I am working on applying time filters to each dashboard, here is an example of how the time filter is applied to the entire dashboard:

https://user-images.githubusercontent.com/99441266/223228660-d8f4bc20-61fc-4878-8793-674a222202c1.mov

https://user-images.githubusercontent.com/99441266/223232225-a3c6feb8-9d62-4172-99cc-2c8a5339e443.mov

**Comment by chantal-kelm** [comment]
Creation of Splunk search bar:

https://user-images.githubusercontent.com/99441266/223814864-6bbab3b1-0609-4b92-9da3-d0e5b4fa163e.mov

**Comment by Tostti** [comment]
Today I fixed little issues in these dashboards

**Comment by Tostti** [comment]
Today I updated the Security Events dashboard

**Comment by chantal-kelm** [comment]
I am working on the search filters, I have added a default search text in the text search filter, and I am also working on the number of results filter

**Comment by chantal-kelm** [comment]
We were with my colleague @Desvelao reviewing the pipeline transformations in Filebeat, to see if it was necessary to do them in Logstash, but in this case it is not necessary because those fields are not used in any of the dashboards.

Also, my colleague @Desvelao suggested to add a versioning for the dahboards, that we decided with @gdiazlo to add in the name of each dashboard, this way we have them identified and if later we are making updates or releasing more dashboards and some user is asking us some query, we can know which version he has. Also by @Desvelao suggestion we add the word Wazuh to the name of each dashboard, this way the user can identify them better.

### Splunk

<img width="290" alt="Captura de pantalla 2023-04-24 a la(s) 13 53 04" src="https://user-images.githubusercontent.com/99441266/234064225-7f539391-caf8-4b73-8b8d-e6c7831cc927.png">
