### ISSUE TITLE
Cannot access to Users administration with other role than administrator

### ISSUE THREAD

**Issue by Tostti** [wazuh/wazuh-kibana-app#5235]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
By default, Wazuh contains a role called `users_admin`, that should be able to edit the configuration of Wazuh internal users. However, from the frontend is not possible to access that menu without having the `administrator` role

![imagen](https://user-images.githubusercontent.com/42900763/222511699-164590b9-70f7-4462-991b-3ea298928fac.png)

The API allows editing users only with that role, that can be verified making the request manually. I created a `test` user with only that role:
```console
root@tostti:/home/tostti# TOKEN=$(curl -u test:Test1234! -k -X GET "https://localhost:55000/security/user/authenticate?raw=true")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   400  100   400    0     0   1225      0 --:--:-- --:--:-- --:--:--  1226
root@tostti:/home/tostti# echo $TOKEN
eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjc3Nzc4OTE2LCJleHAiOjE2Nzc3Nzk4MTYsInN1YiI6ImxhbGFsYSIsInJ1bl9hcyI6ZmFsc2UsInJiYWNfcm9sZXMiOlszXSwicmJhY19tb2RlIjoid2hpdGUifQ.AauiYwCf-y2uxbw1nxxK9nXHUH4E_jbBcT1YndltQyZbZNqlp01ocggEVkXwwI5suQGn6au9I9sxE7qBgeMFYWr5AbTIbNT8kA1bLoS307x6xpoMfjGUi5XcOTagIEXtYqTYMRPomSAc6m6vjmZcZb9p2rshiQ6h4yPrTpX0QyN-nmru
root@tostti:/home/tostti# curl -k -X POST "https://localhost:55000/security/users" -H  "Authorization: Bearer $TOKEN" -H  "Content-Type: application/json" -d "{\"password\": \"Test1234!\",\"username\": \"test2\"}"
{"data": {"affected_items": [{"id": 102, "username": "lsalasdla", "allow_run_as": false, "roles": []}], "total_affected_items": 1, "total_failed_items": 0, "failed_items": []}, "message": "User was successfully created", "error": 0}root@tostti:/home/tostti#
```

**Steps to reproduce**
1. Create a user only with `users_admin` role
2. Navigate to Wazuh/Security/Users

**Expected Result**
The Users screen should be shown

**Actual Result**
An error message is shown

**Screenshots**
Expected result:
![imagen](https://user-images.githubusercontent.com/42900763/222513082-b8e72d5a-cf15-4c1c-a833-0269b766880e.png)

Actual result:
![imagen](https://user-images.githubusercontent.com/42900763/222513106-42751d12-45da-48ab-aae4-b9b984c23c67.png)

**Additional information**
The issue was discovered on the `Users` configuration, but is possible that a similar situation occurs for different roles

**Comment by Desvelao** [comment]
# Research

The `Security` section in the plugin is restricted to the users with the `administrator` role. This was a soft implementation of RBAC.

We will replace this approach with another one more specific to the actions.

## Tab analysis

| Tab | Description | API request | Permissions |
| --- | --- | --- | --- |
| Users | Display table | `GET /security/users?sort=username`| `security:read` (`user:id:*`) |
| Users | Display table | `GET /security/roles?sort=name` | `security:read` (`role:id:*`) |
| Users | Remove user from table | `DELETE /security/users?user_ids={user_id}` | `security:delete` (`user:id:user_id`) |
| Users | Create user button | `POST /security/users` | `security:create_user` (`*:*:*`) |
| Users | Create user flyout apply button | `POST /security/users` | `security:create_user` (`*:*:*`) |
| Users | Create user flyout apply button | `PUT /security/users/${userId}/run_as?allow_run_as=${allowRunAs}` | `security:edit_run_as` (`*:*:*`) |
| Users | Edit user flyout apply button | `POST /security/users` | `security:create_user` (`*:*:*`) |
| Users | Edit user flyout apply button | `PUT /security/users/${userId}/run_as?allow_run_as=${allowRunAs}` | `security:edit_run_as` (`*:*:*`) |

WIP

- Users
  - Display users table:
