### ISSUE TITLE
Wazuh API usage - Management/Configuration

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#5242]
**Description**

Analysis: https://github.com/wazuh/wazuh-kibana-app/issues/5233

> ## Configuration
> 
> #### When clicking on the `configuration` section
>
> ![image](https://user-images.githubusercontent.com/57481331/140904301-1d525d94-feb9-4c0c-8e88-a4e4004ed5b1.png)
>
> <details>
> <summary>Issue</summary>
> 
> ```
> 2021/11/08 15:04:35 INFO: wazuh-wui 172.22.0.12 "GET /cluster/status" with parameters {} and body {} done in 0.029s: 200
> 2021/11/08 15:04:35 INFO: wazuh-wui 172.22.0.12 "GET /cluster/status" with parameters {} and body {} done in 0.028s: 200
> 2021/11/08 15:04:35 INFO: wazuh-wui 172.22.0.12 "GET /cluster/nodes" with parameters {} and body {} done in 0.054s: 200
> 2021/11/08 15:04:35 INFO: wazuh-wui 172.22.0.12 "GET /cluster/nodes" with parameters {} and body {} done in 0.016s: 200
> 2021/11/09 12:21:01 INFO: wazuh-wui 172.19.0.105 "GET /agents" with parameters {"q": "id=000"} and body {} done in 0.014s: 200
> ```
> 
> </details>

> - Improvements and suggestions
> 
>    1. Don't use a query to get only one agent. The following will be always faster:
>       ``` GET /agents?agents_list=000 ```
>
>    2. The requests used to check cluster health are done twice, could we avoid the second request to each endpoint?
  
 1. We should change the request
 2. This needs a deep analysis.

> #### When choosing some configurations (global for instance)
> 
> ![image](https://user-images.githubusercontent.com/57481331/140904383-aead499b-26f6-4a5d-8e1f-9d310c352d0d.png)
> 
> <details>
> <summary>Issue</summary>
>  
> ```
> 2021/11/08 15:13:43 INFO: wazuh-wui 172.22.0.12 "GET /cluster/master-node/configuration/analysis/global" with parameters {} and body {} done in 0.017s: 200
> 2021/11/08 15:13:44 ERROR: Error connecting with socket
> Traceback (most recent call last):
>  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.4-py3.9.egg/wazuh/core/wazuh_socket.py", line 27, in _connect
>    self.s.connect(self.path)
> FileNotFoundError: [Errno 2] No such file or directory
>
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.4-py3.9.egg/wazuh/core/configuration.py", line 780, in get_active_configuration
>    s = WazuhSocket(dest_socket)
>  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.4-py3.9.egg/wazuh/core/wazuh_socket.py", line 22, in __init__
>    self._connect()
>  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.4-py3.9.egg/wazuh/core/wazuh_socket.py", line 29, in _connect
>    raise WazuhException(1013, str(e))
> wazuh.core.exception.WazuhException: Error 1013 - Unable to connect with socket: [Errno 2] No such file or directory
>
> During handling of the above exception, another exception occurred:
>
> Traceback (most recent call last):
>   File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.4-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 256, in execute_local_request
>     data = await asyncio.wait_for(task, timeout=timeout)
>   File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
>     return fut.result()
>   File "/var/ossec/framework/python/lib/python3.9/concurrent/futures/thread.py", line 52, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.4-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 230, in run_local
>     data = self.f(**self.f_kwargs)
>   File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.4-py3.9.egg/wazuh/rbac/decorators.py", line 406, in wrapper
>     result = func(*args, **kwargs) if not skip_execution else None
>   File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.4-py3.9.egg/wazuh/manager.py", line 222, in get_config
>     data = configuration.get_active_configuration(agent_id='000', component=component, configuration=config)
>   File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.4-py3.9.egg/wazuh/core/configuration.py", line 782, in get_active_configuration
>     raise WazuhInternalError(1121)
> wazuh.core.exception.WazuhInternalError: Error 1121 - Error connecting with socket
> 2021/11/08 15:13:44 INFO: wazuh-wui 172.22.0.12 "GET /cluster/master-node/configuration/mail/global" with parameters {} and body {} done in 0.019s: 500
> 2021/11/08 15:13:44 INFO: wazuh-wui 172.22.0.12 "GET /security/user/authenticate" with parameters {} and body {} done in 0.171s: 200
> 2021/11/08 15:13:44 INFO: wazuh-wui 172.22.0.12 "GET /manager/info" with parameters {} and body {} done in 0.044s: 200
> 2021/11/08 15:13:44 INFO: wazuh-wui 172.22.0.12 "GET /agents" with parameters {"agents_list": "000"} and body {} done in 0.018s: 200
> 2021/11/08 15:13:44 INFO: wazuh-wui 172.22.0.12 "GET /cluster/status" with parameters {} and body {} done in 0.020s: 200
> 2021/11/08 15:13:44 INFO: wazuh-wui 172.22.0.12 "GET /cluster/local/info" with parameters {} and body {} done in 0.017s: 200
> 2021/11/08 15:13:44 INFO: wazuh-wui 172.22.0.12 "GET /cluster/master-node/configuration/request/remote" with parameters {} and body {} done in 0.016s: 200
> 2021/11/08 15:13:44 INFO: wazuh-wui 172.22.0.12 "GET /cluster/master-node/configuration/com/logging" with parameters {} and body {} done in 0.015s: 200
> ```
> 
> </details>
> 
> - The WazuhInternalError found in the logs is caused by a request to GET /cluster/master-node/configuration/mail/global. This error should be handled, issue https://github.com/wazuh/wazuh/issues/10775 created to do it.
  
This needs a deep analysis.

**Comment by yenienserrano** [comment]
From what I was investigating the repeated requests were being executed to change the state of redux which is currently not being used and also sent by props to some components to check permissions, it was added in this [commit](https://github.com/wazuh/wazuh-kibana-app/commit/bf57893#diff-d6577d06debd0c9f476eef4cb299f810ef561232b770637fb1c8ebd1e5a72cbc) but then in this other [commit](https://github.com/wazuh/wazuh-kibana-app/commit/8b58e37) it is changed, and it is deprecated as well. Therefore, as it is code that is not being used, I am going to delete it to clean up the code.
