### ISSUE TITLE
Wazuh API usage - Modules

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#5245]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**

Analysis: https://github.com/wazuh/wazuh-kibana-app/issues/5233

> #### All modules
> 
> When clicking on `explore agent`.
> 
> ![image](https://user-images.githubusercontent.com/57481331/140919810-d66344e7-5752-44af-9584-f12a9d3100f2.png)
> 
> <details>
> <summary>Issue</summary>
> 
> ```
> 2021/11/09 11:54:01 INFO: wazuh-wui 172.19.0.105 "GET /agents" with parameters {"offset": "0", "limit": "10", "sort": "+id", "q": "id!=000"} and body {} done in 0.023s: 200
> 2021/11/09 11:54:04 INFO: wazuh-wui 172.19.0.105 "GET /agents" with parameters {"offset": "30", "limit": "40", "sort": "+id", "q": "id!=000"} and body {} done in 0.031s: 200
> ```
> 
> </details>
> 
> - Improvements and suggestions
> 
>   1. If only 10 rows per page are going to be shown, limit must be 10 instead of offset + 10.
>    ``` GET /agents?offset=40&limit=10 ```

1. I confirm this. It could be happening in the `agents-selection-table.js` component.

**Preconditions**
1. 

**Steps to reproduce**
1. Navigate to '...'

**Expected Result**
1. 

**Actual Result**
1. 

**Screenshots**

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by yenienserrano** [comment]
Closed, as this [PR](https://github.com/wazuh/wazuh-kibana-app/pull/5447) modifies and fixes this issue.

**Comment by Desvelao** [comment]
I reopened the issue because the [pull request](https://github.com/wazuh/wazuh-kibana-app/pull/5447) has not merged yet.

**Comment by asteriscos** [comment]
This pull request is closed because a [refactor in the search bar](https://github.com/wazuh/wazuh-kibana-app/issues/4312) will make this fix obsolete:
https://github.com/wazuh/wazuh-kibana-app/pull/5447
