### ISSUE TITLE
Statistics Histograms don't update X axis with large time intervals

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-kibana-app#5258]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
Histograms in Management Statistics show hours as X-axis labels even when several days/months or years are filtered.

**Preconditions**
1. Hace information in the statistics index.

**Steps to reproduce**
1. Navigate to Management -> Statistics
2. Select a filter with 90 days
3. Check the x-axis labels

**Expected Result**
1. x-axis should change the unit of reference suitable for the interval length

**Actual Result**
1. Always shows 00:00 hours in the x-axis labels

**Screenshots**

![image](https://user-images.githubusercontent.com/9343732/222774740-0883d538-5f60-4f95-8ac3-7d408bec8f14.png)

![image](https://user-images.githubusercontent.com/9343732/222774833-74cea957-a2e6-4d76-a38a-279d25678429.png)

<img width="1792" alt="image" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/6c0664b2-0e4d-44b8-baee-4e66137af9d6">

<img width="1792" alt="image" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/73d15615-8f64-4608-9661-ca3ea0d4b525">

<img width="1792" alt="image" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/cd9d991d-4f70-4f89-987b-b8691a83b945">

**Comment by asteriscos** [comment]
### Problem
This issue seems to be in the type of visualization and there's no configuration available to solve the issue of overlapping labels in the x-axis. 

### Proposed solution
So far the best available solution is to refactor the visualizations of the Statistics page using another type of visualization, like a line chart. 

![image](https://github.com/wazuh/wazuh-kibana-app/assets/9343732/a3019a7c-556b-492b-bd61-45656757fd0f)

**Comment by chantal-kelm** [comment]
Visualization one: **Total number of bytes received**

The first visualization was performed but is being investigated because it does not update with some time filters.

https://github.com/wazuh/wazuh-kibana-app/assets/99441266/2d1256f5-1078-471c-8633-44d2ce7441e5

**Comment by chantal-kelm** [comment]
Further research has been done on what was mentioned in the previous comment and more visualizations have been created.

Old visualization of events sent to analysisd:

<img width="897" alt="Captura de pantalla 2023-07-19 a la(s) 15 29 35" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/fb47b2de-ac82-4f37-9d40-ab68a8ea4f1e">

New visualization of events sent to analysisd:

<img width="897" alt="Captura de pantalla 2023-07-19 a la(s) 15 32 26" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/844a98d6-6d7d-424e-b53c-daf367805d99">

Old visualization of messages statistics:

<img width="897" alt="Captura de pantalla 2023-07-19 a la(s) 15 33 14" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/3d2bd5ec-b289-4eda-a28a-c74308dae5a5">

New visualization of messages statistics:

<img width="897" alt="Captura de pantalla 2023-07-19 a la(s) 16 20 13" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/4f23f941-a4be-4196-ab3d-3a23248f7ef5">

**Comment by chantal-kelm** [comment]
Today we have tried to construct line graphs containing percentage calculations. Research on this is ongoing.

**Comment by chantal-kelm** [comment]
### **New visualization of syscheck:**

<img width="862" alt="image" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/40b34546-9c35-4815-81b1-05ce7ac94bc3">

### **New visualization of syscollector:**

<img width="862" alt="image" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/f78f8d4c-e6a1-431f-a52a-b788487cd8bc">

### **New visualization of rootcheck:**

<img width="862" alt="image" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/acbea29d-8903-4c26-89d8-f538b9e2d048">

### **New visualization of sca:**

<img width="862" alt="image" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/75833053-77cc-4f63-bdfe-301c48789c5a">

### **New visualization of host info:**

<img width="862" alt="image" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/efb59f9e-03a2-4e22-b53d-5d91f0f37aaa">

**Comment by chantal-kelm** [comment]
### **The fields to create the following visualization are not available:**

<img width="862" alt="image" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/46394862-ee16-4275-8ae4-29569072fd95">

**Comment by chantal-kelm** [comment]
https://github.com/wazuh/wazuh-kibana-app/assets/99441266/d988f766-1d30-493f-bf5c-e3d88009e709

**Comment by Tostti** [comment]
PR Successfully merged
