### ISSUE TITLE
Can't access the infos when clicking on syscheck.path for files

### ISSUE THREAD

**Issue by Boleqs** [wazuh/wazuh-kibana-app#5260]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.10 | Integrity Monitoring | Manager | Packages | Ubuntu 22.04.1 LTS |

### **Description:**

When in Wazuh/Integrity Monitoring/Events, I see all the alerts that where generated normally.
However, when i try to click on any of the files syscheck.path (see screenshots), i get redirected to an error concerning react.

I am no dev so I don't know where to start my researches, all I can tell you for now is that the the same procedure works perfectly with registry modifications.

Do you have any idea of where the problem could come from ?

If you need any other informations please ask me.

**link of the react error :** https://reactjs.org/docs/error-decoder.html/?invariant=31&args[]=object%20with%20keys%20%7BS-1-5-21-4004115520-1377985216-48202062-4215%2C%20S-1-5-18%2C%20S-1-5-32-544%7D&args[]=

### **Screenshots :**

Alerts showing on my interface :
![Capture1](https://user-images.githubusercontent.com/80424764/222715122-984c6ac9-6006-437f-8eaf-dec483803907.PNG)

When I click on any of syscheck.path for files :
![Capture2](https://user-images.githubusercontent.com/80424764/222715479-5360b851-d1a3-4439-b01b-47d686d11925.PNG)

When I click on any of syscheck.path for registry :
![Capture4](https://user-images.githubusercontent.com/80424764/222715578-612dd923-7c64-4f15-8656-d85a4a247e8a.PNG)

**Comment by chantal-kelm** [comment]
Hello, how are you? how is your environment set up? do you use Kibana, OpenSearch, Wazuh Dashboard? which versions do you use? 
Could you record a video showing the console on click, and another video showing the network tab on click, if any request fails on the network tab on click, could you tell me which one?

Remember to cover all sensitive information when sharing photos, videos, info.

¡¡I look forward to your reply!!

Regards!!

**Comment by chantal-kelm** [comment]
Hello, how are you? I have tried to reproduce the error but it works fine for me, I attach a video and image.
Can you make a video showing the console when you click on the file path? and a video showing the network tab when you click on the file path?

Remember to cover all sensitive information from files, images and videos.

I wait for your answer! Greetings!

https://user-images.githubusercontent.com/99441266/235751341-4b74cf81-9213-490c-80f7-7bc2185a098c.mov

<img width="1792" alt="Captura de pantalla 2023-05-02 a la(s) 15 10 52" src="https://user-images.githubusercontent.com/99441266/235751385-0ff128c5-6510-41a8-8ae2-ed0d77680ec5.png">

**Comment by chantal-kelm** [comment]
I closed the topic because the customer has not responded.
