### ISSUE TITLE
Ubuntu package not installing wazuh-dashboard.service file[BUG]

### ISSUE THREAD

**Issue by Marc-Whiteman** [wazuh/wazuh-kibana-app#5261]
the /etc/systemd/system/wszuh-dashboard.service file is not there after running install wazuh-dashboard for Ubuntu 22

error after running systemctl enable wazuh-dashboard:
Failed to enable unit: Unit file wazuh-dashboard.service does not exist.

**Comment by AlexRuiz7** [comment]
Closed due to inactivity.
