### ISSUE TITLE
Wazuh main menu is not displayed when the navigation menu is locked

### ISSUE THREAD

**Issue by sultanovich** [wazuh/wazuh-kibana-app#5264]
| Wazuh | OpenSearch | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.4   | 2.4.1     | 03 | Basic |

| Browser |
| ------- |
| Chrome, Brave|

**Description**
When the navigation panel is locked, the main Wazuh menu is not visible.

**Preconditions**

**Steps to reproduce**
1. Navigate to the main menu 
![image](https://user-images.githubusercontent.com/601474/223416461-777990f7-1567-46e9-9536-bb40e075e851.png)

2. Click on 'Dock navigation'
![image](https://user-images.githubusercontent.com/601474/223416697-32993e1a-33a6-402f-aedf-889ed89486fb.png)

4. Display Wazuh's main menu
![image](https://user-images.githubusercontent.com/601474/223416983-89c39460-fdbc-4e69-a462-1ced55df29e6.png)

**Expected Result**
The Wazuh main menu should be displayed as it is shown when the navigation menu is not locked.
![image](https://user-images.githubusercontent.com/601474/223417173-97a8908f-1243-4124-8cec-36ab1d4de1cf.png)

**Screenshots**

**Actual Result**
The Wazuh main menu is currently not displayed.
![image](https://user-images.githubusercontent.com/601474/223418202-d64530a7-4afa-4482-bd6d-b7c9a5817d2b.png)

**Additional context**
The same behavior has been verified using the `OVA` image and the `.tar.gz` package.

**Comment by yenienserrano** [comment]
Trying to replicate it in kibana 7.17.6, I noticed that it does not have a button to lock the menu. 
Looking at the code of kibana 7.17.6 I saw that they are hiding the button,
They are using a component of elastic eui called [EuiShowFor](https://eui.elastic.co/#/theming/breakpoints/utilities#show-for) where you pass a parameter "sizes" that you put all the window sizes that you want to be rendered and from [kibana 7.16.0](https://github.com/elastic/kibana/blame/v7.16.0/src/core/public/chrome/ui/header/collapsible_nav.tsx#L310) and changed the value to "none", in [kibana 7.10](https://github.com/elastic/kibana/blame/v7.10.2/src/core/public/chrome/ui/header/collapsible_nav.tsx#L299) has in sizes "l" and "xl".
