### ISSUE TITLE
The message `Reserved users cannot be deleted` is not cleared

### ISSUE THREAD

**Issue by sultanovich** [wazuh/wazuh-kibana-app#5267]
| Wazuh | OpenSearch | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.4.0   | 2.4.1     | 03 | Basic |

| Browser |
| ------- |
| Chrome |

**Description**
When creating and then deleting a user, a warning message is displayed that does not disappear.

**Preconditions**

**Steps to reproduce**
1. Navigate to `Security`
![image](https://user-images.githubusercontent.com/601474/223460442-82f981c2-a361-45d6-acff-f34e09d887f8.png)

2. Click on `Users`
![image](https://user-images.githubusercontent.com/601474/223460526-78c17796-4b49-4c1c-989a-23c9558abc1c.png)

3. Click on `Create user`
![image](https://user-images.githubusercontent.com/601474/223460783-aa3ba731-c3b2-4670-96a5-656ba402e164.png)

4. Enter the required data and click on `Apply`.
![image](https://user-images.githubusercontent.com/601474/223463462-282739ac-f533-42f7-b30e-95e62566bbc5.png)

5. Delete user with delete button
![image](https://user-images.githubusercontent.com/601474/223463828-31f53ee5-0e8d-4a40-bd49-e27a4fa8b579.png)
![image](https://user-images.githubusercontent.com/601474/223464152-a7fd7b39-9431-459a-b0df-2f56d42bdc11.png)

6. Then you will see the message `Reserved users can't be deleted`.
![image](https://user-images.githubusercontent.com/601474/223464361-c5583369-0c7a-49b6-bcd6-5ed45e414b97.png)

7. If you try to create a new user by selecting the `Create user` option, the message continues to be displayed.
![image](https://user-images.githubusercontent.com/601474/223465005-bb72c475-542f-4e5a-a5d9-1b97f9094429.png)
![image](https://user-images.githubusercontent.com/601474/223465088-7e82679a-e9cf-42c6-a3c7-894ac1337f43.png)

**Expected Result**
The message should not appear when deleting an unreserved user or should disappear when changing to open a new menu.

**Actual Result**
The message is displayed until you change section or refresh the page.

**Screenshots**

**Additional context**
The same behavior has been verified using the `OVA` image and the `.tar.gz` package.

**Comment by yenienserrano** [comment]
Researching why this happens, I saw that opensearch oui has the same problem, so it is a bug in the OUI tooltip component, in Elastic EUI the same thing happens until version 72, which fixed a part making it possible to show only 1 tooltip and not having several tooltips stacked. And in version 42.1 they also made another change that helps this problem.

## Elastic EUI
https://github.com/elastic/eui/pull/6520
https://github.com/elastic/eui/pull/5441

## Opensearch OUI

![image](https://github.com/wazuh/wazuh-kibana-app/assets/63758389/a3b1c2d1-12cb-4c87-ae6a-1105c2087aaf)
