### ISSUE TITLE
The Deploy new agent doesn't display the extra requirements in the install and enroll the agent

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#5283]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.4   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
The Deploy new agent page doesn't display the extra requirements for some operating system/versions of the Wazuh agent. For example, for Solaris 10 or 11: https://github.com/wazuh/wazuh-kibana-app/blob/4.4-2.4-wzd/public/controllers/agent/components/register-agent.js#L1155-L1190. There are others messages for others operating systems.

I was researching and this could be caused by a property that will always be `undefined` https://github.com/wazuh/wazuh-kibana-app/blob/4.4-2.4-wzd/public/controllers/agent/components/register-agent.js#L209

By another hand, there are 3 conditionals to render some callouts and the command to use in the install and enroll the agent. In only one of them, messages related to extra requirements could be displayed. I am not sure if in the other cases, they should be displayed too. We should review.
Conditionals:
- https://github.com/wazuh/wazuh-kibana-app/blob/4.4-2.4-wzd/public/controllers/agent/components/register-agent.js#L1092-L1336 (Some messages related to extra requirements are displayed)
- https://github.com/wazuh/wazuh-kibana-app/blob/4.4-2.4-wzd/public/controllers/agent/components/register-agent.js#L1336-L1416
- https://github.com/wazuh/wazuh-kibana-app/blob/4.4-2.4-wzd/public/controllers/agent/components/register-agent.js#L1416-L1478

**Preconditions**
1. 

**Steps to reproduce**
1. Navigate to deploy new agent page
2. Select the Solaris operating system and Solaris 10 version
3. A message about extra requirements should be displayed in the install and deploy guide step

**Expected Result**
1. 

**Actual Result**
1. 

**Screenshots**

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by Machi3mfl** [comment]
The related PR solves the uses case when we need to know if the connection is secure or not (UDP/TCP)

For the following question, we need to search for documentation about the new features added in the `Register Agent section.`

> By another hand, there 3 conditionals to render some callouts and the command to use in the install and enroll the agent. In only one of them, messages related to extra requirements could be displayed. I am not sure if in the other cases, they should be displayed too. We should review.
> Conditionals:
> 
> https://github.com/wazuh/wazuh-kibana-app/blob/4.4-2.4-wzd/public/controllers/agent/components/register-agent.js#L1092-L1336 (Some messages related to extra requirements are displayed)
> https://github.com/wazuh/wazuh-kibana-app/blob/4.4-2.4-wzd/public/controllers/agent/components/register-agent.js#L1336-L1416
> https://github.com/wazuh/wazuh-kibana-app/blob/4.4-2.4-wzd/public/controllers/agent/components/register-agent.js#L1416-L1478

**Comment by Tostti** [comment]
All PRs merged
