### ISSUE TITLE
When the search bar language is `Lucene` the events view is broken

### ISSUE THREAD

**Issue by yenienserrano** [wazuh/wazuh-kibana-app#5284]
| Wazuh | OSD | 
| ----- | ------- |
| 4.4 and 4.5   | 2.4.1 and 2.6.0     | 

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
When you have the search bar syntax language set to Lucene and navigate to events, the page remains blank, and the console shows the error `Cannot read properties of undefined (reading 'luceneQuerySyntax')`

This error is coming up because here you are looking for the property "query.luceneQuerySyntax" and it does not exist, in opensearch dashboards they changed to the property "opensearch.queryDSL.base"

Wazuh-kibana-app: https://github.com/wazuh/wazuh-kibana-app/blob/v4.3.11-2.4.0/public/kibana-integrations/discover/application/angular/directives/no_results.js#L166

OpenSearch Dashboards: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/2.6.0/src/plugins/discover/public/application/angular/directives/no_results.js#L177

and in [this text](https://github.com/wazuh/wazuh-kibana-app/blob/v4.3.11-2.4.0/public/kibana-integrations/discover/application/angular/directives/no_results.js#L160) it says elastic when in reality it would have to say opensearch

**Steps to reproduce**
1. Navigate to 'Security events'
2. Click on 'Syntax options from search bar'
3. Change 'OpenSearch Dashboards Query Language' to 'off'
3. Navigate to 'Events' and see error

**Expected Result**
1. 
![image](https://user-images.githubusercontent.com/63758389/224702290-d3932673-3be3-4628-bb8e-7a3ab31cefe7.png)

**Actual Result**
1. 
![image](https://user-images.githubusercontent.com/63758389/224701568-94846991-abc6-4f8f-8da7-4a8b11710b2f.png)

**Screenshots**

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by Desvelao** [comment]
I confirm this is happening in 4.4.0. Tested with the current `4.4-2.4-wzd` branch.

Screenshots
![image](https://user-images.githubusercontent.com/34042064/224707319-6ae746a3-a135-47f0-826c-7221a5e0e432.png)

**Comment by yenienserrano** [comment]
Solve: 
- #5286
