### ISSUE TITLE
Agents evolution time picker does not close

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#5300]
| Wazuh  |
| -----  |
| >= 4.4 |

## Description

The dropdown of the time picker of the agents evolution dashboard doesn't behave correctly.

### Steps to reproduce
  - Open the file picker
  - Click again in the same spot to close it
  - Click anywhere outside the time picker: the dropdown does not close until an option is selected
- Not reproducible in 4.3.10.
- Reproducible in 4.4.0.
![image](https://user-images.githubusercontent.com/15186973/225660314-4494ba76-2bbf-40b0-a481-e4a3347cc9c4.png)

### Expected result

- [ ] The dropdown does not flicker when opened.
- [ ] The dropdown can be closed when the root element is pressed again (the same element clicked to open it)
- [ ] The dropdown must close when you click outside of it.

**Comment by Tostti** [comment]
All PRs merged
