### ISSUE TITLE
Release 4.4.0 - RC2 - Kibana UI regression testing

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#5301]
## Description

This issue aims to track the effort to perform complete regression testing on Wazuh App 4.4.0 rev 04 for RC2

| Test         | Chrome | Safari | Firefox | Package |
|--------------|--------|--------|---------|---------|
| Example test | 🟢/🔴  | 🟢/🔴  | 🟢/🔴   | 🟢/🔴   |
 
### Status legend
⚫ - None
🔴 - Rejected
🟢 - Approved

In the case of 🔴, **create and add** the issue to the `Errors found` section. 

### Testing plan

- #5273 
- #5286 
- #5285 
- #5291 
- #5295 

### Testing notes

1) All the mentioned versions will be tested
2) It's necessary to include evidence of each test performed
3) In case to identify a bug/problem, the new feature should be linked to this issue

  - [x] 7.17.9
  - [x] 7.17.8
  - [x] 7.16.3
  - [x] 7.10.2
  - [x] WzD 4.4.0-04

Testing template: 
[template_testing_4.4.0-rc2-kbn-7.10.2.md](https://github.com/wazuh/wazuh-kibana-app/files/10999483/template_testing_4.4.0-rc2-kbn-7.10.2.md)
[template_testing_4.4.0-rc2-kbn-7.16.3.md](https://github.com/wazuh/wazuh-kibana-app/files/10999484/template_testing_4.4.0-rc2-kbn-7.16.3.md)
[template_testing_4.4.0-rc2-kbn-7.17.8.md](https://github.com/wazuh/wazuh-kibana-app/files/10999485/template_testing_4.4.0-rc2-kbn-7.17.8.md)
[template_testing_4.4.0-rc2-wzd.md](https://github.com/wazuh/wazuh-kibana-app/files/10999486/template_testing_4.4.0-rc2-wzd.md)

**Comment by yenienserrano** [comment]
# Kibana 7.10.2

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| [In the deploy new agent guide, select Solaris 10, and 2 messages should be displayed in the Install and enroll step about extra requirements](https://github.com/wazuh/wazuh-kibana-app/pull/5285) | :black_circle: | :black_circle: | :black_circle: |
| [In the deploy new agent guide, select Solaris 11, and 2 messages should be displayed in the Install and enroll step about extra requirements](https://github.com/wazuh/wazuh-kibana-app/pull/5285) | :black_circle: | :black_circle: | :black_circle: |
| [In the deploy new agent guide, select HP - 11.31, and 2 messages should be displayed in the Install and enroll step about extra requirements](https://github.com/wazuh/wazuh-kibana-app/pull/5285) | :black_circle: | :black_circle: | :black_circle: |
| [In the deploy new agent guide, select Alpine 3.12.12, and 2 messages should be displayed in the Install and enroll step about extra requirements](https://github.com/wazuh/wazuh-kibana-app/pull/5285) | :black_circle: | :black_circle: | :black_circle: |
| [In the deploy new agent guide, select Aix - 6.1 TL9, and 1 message should be displayed in the Install and enroll step about extra requirements](https://github.com/wazuh/wazuh-kibana-app/pull/5285) | :black_circle: | :black_circle: | :black_circle: |
| [In the deploy new agent guide, select Debian 7 and for each architecture, and 1 message should be displayed in the Install and enroll step about extra requirements](https://github.com/wazuh/wazuh-kibana-app/pull/5285) | :black_circle: | :black_circle: | :black_circle: |
| [In the deploy new agent guide, select Debian 8 and for each architecture, and 1 message should be displayed in the Install and enroll step about extra requirements](https://github.com/wazuh/wazuh-kibana-app/pull/5285) | :black_circle: | :black_circle: | :black_circle: |
| [In the deploy new agent guide, select Debian 9+ and for each architecture, and 1 message should be displayed in the Install and enroll step about extra requirements](https://github.com/wazuh/wazuh-kibana-app/pull/5285) | :black_circle: | :black_circle: | :black_circle: |
| [The buttons Inventory data, Stats, and Configuration in the agent view header should be displayed to the right of the screen](https://github.com/wazuh/wazuh-kibana-app/pull/5291) | :black_circle: | :black_circle: | :black_circle: |
| [Set a remote secure connection with TCP protocol and in the deploy new agent guide checks that the Install and enroll step for OSs appear some messages. See https://github.com/wazuh/wazuh-kibana-app/pull/5295#issuecomment-1468437776](https://github.com/wazuh/wazuh-kibana-app/pull/5295) | :black_circle: | :black_circle: | :black_circle: |
| [Set a remote secure connection with UDP protocol and in the deploy new agent guide checks that the Install and enroll step for OSs appear some messages. See https://github.com/wazuh/wazuh-kibana-app/pull/5295#issuecomment-1468437776](https://github.com/wazuh/wazuh-kibana-app/pull/5295) | :black_circle: | :black_circle: | :black_circle: |
| [Ensure there is no remote secure connection and in the deploy new agent guide checks that the Install and enroll step displays a warning message about the agent will not be able to communicate with the manager. See https://github.com/wazuh/wazuh-kibana-app/pull/5295#issuecomment-1468437776](https://github.com/wazuh/wazuh-kibana-app/pull/5295) | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5285" target="_blank">In the deploy new agent guide, select Solaris 10, and 2 messages should be displayed in the Install and enroll step about extra requirements</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5285" target="_blank">In the deploy new agent guide, select Solaris 11, and 2 messages should be displayed in the Install and enroll step about extra requirements</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5285" target="_blank">In the deploy new agent guide, select HP - 11.31, and 2 messages should be displayed in the Install and enroll step about extra requirements</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5285" target="_blank">In the deploy new agent guide, select Alpine 3.12.12, and 2 messages should be displayed in the Install and enroll step about extra requirements</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5285" target="_blank">In the deploy new agent guide, select Aix - 6.1 TL9, and 1 message should be displayed in the Install and enroll step about extra requirements</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5285" target="_blank">In the deploy new agent guide, select Debian 7 and for each architecture, and 1 message should be displayed in the Install and enroll step about extra requirements</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5285" target="_blank">In the deploy new agent guide, select Debian 8 and for each architecture, and 1 message should be displayed in the Install and enroll step about extra requirements</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5285" target="_blank">In the deploy new agent guide, select Debian 9+ and for each architecture, and 1 message should be displayed in the Install and enroll step about extra requirements</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5291" target="_blank">The buttons Inventory data, Stats, and Configuration in the agent view header should be displayed to the right of the screen</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5295" target="_blank">Set a remote secure connection with TCP protocol and in the deploy new agent guide checks that the Install and enroll step for OSs appear some messages. See https://github.com/wazuh/wazuh-kibana-app/pull/5295#issuecomment-1468437776</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5295" target="_blank">Set a remote secure connection with UDP protocol and in the deploy new agent guide checks that the Install and enroll step for OSs appear some messages. See https://github.com/wazuh/wazuh-kibana-app/pull/5295#issuecomment-1468437776</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5295" target="_blank">Ensure there is no remote secure connection and in the deploy new agent guide checks that the Install and enroll step displays a warning message about the agent will not be able to communicate with the manager. See https://github.com/wazuh/wazuh-kibana-app/pull/5295#issuecomment-1468437776</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Comment by Desvelao** [comment]
# Wazuh dashboard

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| [The plugin menu should display over the platform menu when this is locked](https://github.com/wazuh/wazuh-kibana-app/pull/5273) | :black_circle: | :black_circle: | :black_circle: |
| [The plugin menu should display under the platform menu when this is opened and not locked](https://github.com/wazuh/wazuh-kibana-app/pull/5273) | :black_circle: | :black_circle: | :black_circle: |
| [Selecting the Lucene syntax, go to the Modules/<Module>/Events, and apply a search that has no results, the view should not crash](https://github.com/wazuh/wazuh-kibana-app/pull/5286) | :black_circle: | :black_circle: | :black_circle: |
| [Selecting the Lucene syntax, go to the Modules/<Module>/Events, and apply a search that has no results, the Query String syntax link should point to a OpenSearch link](https://github.com/wazuh/wazuh-kibana-app/pull/5286) | :black_circle: | :black_circle: | :black_circle: |
| [Selecting the Lucene syntax, go to the Modules/<Module>/Events, and apply a search that has no results, should display OpenSearch in the text](https://github.com/wazuh/wazuh-kibana-app/pull/5286) | :black_circle: | :black_circle: | :black_circle: |
| [In the deploy new agent guide, select Solaris 10, and 2 messages should be displayed in the Install and enroll step about extra requirements](https://github.com/wazuh/wazuh-kibana-app/pull/5285) | :black_circle: | :black_circle: | :black_circle: |
| [In the deploy new agent guide, select Solaris 11, and 2 messages should be displayed in the Install and enroll step about extra requirements](https://github.com/wazuh/wazuh-kibana-app/pull/5285) | :black_circle: | :black_circle: | :black_circle: |
| [In the deploy new agent guide, select HP - 11.31, and 2 messages should be displayed in the Install and enroll step about extra requirements](https://github.com/wazuh/wazuh-kibana-app/pull/5285) | :black_circle: | :black_circle: | :black_circle: |
| [In the deploy new agent guide, select Alpine 3.12.12, and 2 messages should be displayed in the Install and enroll step about extra requirements](https://github.com/wazuh/wazuh-kibana-app/pull/5285) | :black_circle: | :black_circle: | :black_circle: |
| [In the deploy new agent guide, select Aix - 6.1 TL9, and 1 message should be displayed in the Install and enroll step about extra requirements](https://github.com/wazuh/wazuh-kibana-app/pull/5285) | :black_circle: | :black_circle: | :black_circle: |
| [In the deploy new agent guide, select Debian 7 and for each architecture, and 1 message should be displayed in the Install and enroll step about extra requirements](https://github.com/wazuh/wazuh-kibana-app/pull/5285) | :black_circle: | :black_circle: | :black_circle: |
| [In the deploy new agent guide, select Debian 8 and for each architecture, and 1 message should be displayed in the Install and enroll step about extra requirements](https://github.com/wazuh/wazuh-kibana-app/pull/5285) | :black_circle: | :black_circle: | :black_circle: |
| [In the deploy new agent guide, select Debian 9+ and for each architecture, and 1 message should be displayed in the Install and enroll step about extra requirements](https://github.com/wazuh/wazuh-kibana-app/pull/5285) | :black_circle: | :black_circle: | :black_circle: |
| [The buttons Inventory data, Stats, and Configuration in the agent view header should be displayed to the right of the screen](https://github.com/wazuh/wazuh-kibana-app/pull/5291) | :black_circle: | :black_circle: | :black_circle: |
| [Set a remote secure connection with TCP protocol and in the deploy new agent guide checks that the Install and enroll step for OSs appear some messages. See https://github.com/wazuh/wazuh-kibana-app/pull/5295#issuecomment-1468437776](https://github.com/wazuh/wazuh-kibana-app/pull/5295) | :black_circle: | :black_circle: | :black_circle: |
| [Set a remote secure connection with UDP protocol and in the deploy new agent guide checks that the Install and enroll step for OSs appear some messages. See https://github.com/wazuh/wazuh-kibana-app/pull/5295#issuecomment-1468437776](https://github.com/wazuh/wazuh-kibana-app/pull/5295) | :black_circle: | :black_circle: | :black_circle: |
| [Ensure there is no remote secure connection and in the deploy new agent guide checks that the Install and enroll step displays a warning message about the agent will not be able to communicate with the manager. See https://github.com/wazuh/wazuh-kibana-app/pull/5295#issuecomment-1468437776](https://github.com/wazuh/wazuh-kibana-app/pull/5295) | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5273" target="_blank">The plugin menu should display over the platform menu when this is locked</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5273" target="_blank">The plugin menu should display under the platform menu when this is opened and not locked</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5286" target="_blank">Selecting the Lucene syntax, go to the Modules/<Module>/Events, and apply a search that has no results, the view should not crash</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5286" target="_blank">Selecting the Lucene syntax, go to the Modules/<Module>/Events, and apply a search that has no results, the Query String syntax link should point to a OpenSearch link</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5286" target="_blank">Selecting the Lucene syntax, go to the Modules/<Module>/Events, and apply a search that has no results, should display OpenSearch in the text</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5285" target="_blank">In the deploy new agent guide, select Solaris 10, and 2 messages should be displayed in the Install and enroll step about extra requirements</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5285" target="_blank">In the deploy new agent guide, select Solaris 11, and 2 messages should be displayed in the Install and enroll step about extra requirements</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5285" target="_blank">In the deploy new agent guide, select HP - 11.31, and 2 messages should be displayed in the Install and enroll step about extra requirements</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5285" target="_blank">In the deploy new agent guide, select Alpine 3.12.12, and 2 messages should be displayed in the Install and enroll step about extra requirements</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5285" target="_blank">In the deploy new agent guide, select Aix - 6.1 TL9, and 1 message should be displayed in the Install and enroll step about extra requirements</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5285" target="_blank">In the deploy new agent guide, select Debian 7 and for each architecture, and 1 message should be displayed in the Install and enroll step about extra requirements</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5285" target="_blank">In the deploy new agent guide, select Debian 8 and for each architecture, and 1 message should be displayed in the Install and enroll step about extra requirements</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5285" target="_blank">In the deploy new agent guide, select Debian 9+ and for each architecture, and 1 message should be displayed in the Install and enroll step about extra requirements</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5291" target="_blank">The buttons Inventory data, Stats, and Configuration in the agent view header should be displayed to the right of the screen</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5295" target="_blank">Set a remote secure connection with TCP protocol and in the deploy new agent guide checks that the Install and enroll step for OSs appear some messages. See https://github.com/wazuh/wazuh-kibana-app/pull/5295#issuecomment-1468437776</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5295" target="_blank">Set a remote secure connection with UDP protocol and in the deploy new agent guide checks that the Install and enroll step for OSs appear some messages. See https://github.com/wazuh/wazuh-kibana-app/pull/5295#issuecomment-1468437776</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5295" target="_blank">Ensure there is no remote secure connection and in the deploy new agent guide checks that the Install and enroll step displays a warning message about the agent will not be able to communicate with the manager. See https://github.com/wazuh/wazuh-kibana-app/pull/5295#issuecomment-1468437776</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>
