### ISSUE TITLE
Move settings checks to alerts index check on health check page

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#5310]
## Description
We want to move the settings checks (the last three on the checklist) of the health check page into the logs section of the check alerts index pattern item. 

<img width="615" alt="screenshot" src="https://user-images.githubusercontent.com/2181918/226636826-e25858cf-7013-41dc-b89e-9f0295939212.png">

We want these checks to be hidden from the list and be included into the Check alerts index pattern
- Check timeline:max_buckets setting
- Check metaFields settings
- Check timepickler:timeDefault settings

The result of these tests should appear inside the Check alerts index pattern log:

<img width="730" alt="screenshot" src="https://user-images.githubusercontent.com/2181918/226637567-6e27fc22-6f19-49b6-be11-7a410be49c9e.png">

## Tasks

- [x] Move the output of the checks to the logs of the alerts index check
- [x] Remove the items from the health check list

**Comment by Desvelao** [comment]
I don't think this request makes sense to me.

The checks to move inside the check alert index pattern are related to the platform setting that I consider that are different things.

The initial refactor of the health check was to inform the user of the things that are happening in the health check. This request remove the visibility of these things.
