### ISSUE TITLE
Table `Top 5 users` in FIM::Dashboard overflows

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#5317]
## Description

There is a visual problem in the `Top 5 users` table at FIM::Dashboard, as it overflows from the parent element. This happens in any resolution and browser.

![image](https://user-images.githubusercontent.com/15186973/227268068-43b5846b-bb1d-4cc1-996c-86f044c92889.png)

**Comment by yenienserrano** [comment]
Solve: https://github.com/wazuh/wazuh-kibana-app/pull/5334/
