### ISSUE TITLE
Refactor the controllers and optimize them for new UI navigability

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#534]
Now that we have a new user experience after the app redesign, we should improve the current controllers and adapt the switching tab methods for this new user navigation flow.

Now we have a Welcome screen on some of the tabs, and in some cases, this is the only tab without visualizations and could run into problems when changing between tabs with or without visualizations.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
First approach done here https://github.com/wazuh/wazuh-kibana-app/pull/564
