### ISSUE TITLE
Reloading the page on Agents configuration doesn't load agent name and status

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#535]
Hello team,

If we reload the page with F5 while we're on the *Agents Configuration* tab, the loading process won't ask for the agent object, and we won't get the ID, name and status on the top bar.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
Thanks @JuanjiJG , done here https://github.com/wazuh/wazuh-kibana-app/pull/536

**Comment by JuanjiJG** [comment]
You are welcome @jesusgn90.
