### ISSUE TITLE
Release 4.4.1 - RC1 - Kibana UI regression testing

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#5356]
## Description

This issue aims to track the effort to perform complete regression testing on Wazuh App 4.4.0 rev 04 for RC2

| Test         | Chrome | Safari | Firefox | Package |
|--------------|--------|--------|---------|---------|
| Example test | 🟢/🔴  | 🟢/🔴  | 🟢/🔴   | 🟢/🔴   |
 
### Status legend
⚫ - None
🔴 - Rejected
🟢 - Approved

In the case of 🔴, **create and add** the issue to the `Errors found` section. 

### Testing plan

#5198
#5317
#5336
#5318
#5300

### Testing notes

1) All the mentioned versions will be tested
2) It's necessary to include evidence of each test performed
3) In case to identify a bug/problem, the new feature should be linked to this issue

  - [x] 7.17.9
  - [x] 7.17.8
  - [x] 7.16.3
  - [x] 7.10.2
  - [ ] WzD 4.4.1-00

Testing template: 
[template_testing_4.4.1-rc1-kbn-7.10.2.md](https://github.com/wazuh/wazuh-kibana-app/files/11156996/template_testing_4.4.1-rc1-kbn-7.10.2.md)
[template_testing_4.4.1-rc1-kbn-7.16.3.md](https://github.com/wazuh/wazuh-kibana-app/files/11156997/template_testing_4.4.1-rc1-kbn-7.16.3.md)
[template_testing_4.4.1-rc1-kbn-7.17.8.md](https://github.com/wazuh/wazuh-kibana-app/files/11156998/template_testing_4.4.1-rc1-kbn-7.17.8.md)
[template_testing_4.4.1-rc1-kbn-7.17.9.md](https://github.com/wazuh/wazuh-kibana-app/files/11156999/template_testing_4.4.1-rc1-kbn-7.17.9.md)
[template_testing_4.4.1-rc1-wzd.md](https://github.com/wazuh/wazuh-kibana-app/files/11157004/template_testing_4.4.1-rc1-wzd.md)

**Comment by Desvelao** [comment]
# Kibana 7.10.2

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| [Empty input in the search bar of the agent inventory tables should display all the results](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [Add a search text input in the search bar of the agent inventory tables should display filtered the results](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [Export to CSV each table in agents inventory with an empty search query should display all the results](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [Export to CSV each table in agents inventory with a search query should display results filtered](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [The agent inventory search bar placeholder of Network ports should be Search](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [The agent inventory search bar placeholder of Packages should be Search](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [The agent inventory search bar placeholder of Processes ports should be Search](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [The Malware detection link in Management/Configuration/Policy monitoring/System audit should open a valid link with the related documentation](https://github.com/wazuh/wazuh-kibana-app/pull/5329) | :black_circle: | :black_circle: | :black_circle: |
| [The timepicker in the Evolution visualization of Agents section should close when clicking on it](https://github.com/wazuh/wazuh-kibana-app/pull/5341) | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">Empty input in the search bar of the agent inventory tables should display all the results</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">Add a search text input in the search bar of the agent inventory tables should display filtered the results</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">Export to CSV each table in agents inventory with an empty search query should display all the results</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">Export to CSV each table in agents inventory with a search query should display results filtered</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">The agent inventory search bar placeholder of Network ports should be Search</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">The agent inventory search bar placeholder of Packages should be Search</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">The agent inventory search bar placeholder of Processes ports should be Search</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5329" target="_blank">The Malware detection link in Management/Configuration/Policy monitoring/System audit should open a valid link with the related documentation</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5341" target="_blank">The timepicker in the Evolution visualization of Agents section should close when clicking on it</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Comment by yenienserrano** [comment]
# Kibana 7.17.9

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| [Empty input in the search bar of the agent inventory tables should display all the results](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [Add a search text input in the search bar of the agent inventory tables should display filtered the results](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [Export to CSV each table in agents inventory with an empty search query should display all the results](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [Export to CSV each table in agents inventory with a search query should display results filtered](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [The agent inventory search bar placeholder of Network ports should be Search](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [The agent inventory search bar placeholder of Packages should be Search](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [The agent inventory search bar placeholder of Processes ports should be Search](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [The Malware detection link in Management/Configuration/Policy monitoring/System audit should open a valid link with the related documentation](https://github.com/wazuh/wazuh-kibana-app/pull/5329) | :black_circle: | :black_circle: | :black_circle: |
| [The timepicker in the Evolution visualization of Agents section should close when clicking on it](https://github.com/wazuh/wazuh-kibana-app/pull/5341) | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">Empty input in the search bar of the agent inventory tables should display all the results</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">Add a search text input in the search bar of the agent inventory tables should display filtered the results</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">Export to CSV each table in agents inventory with an empty search query should display all the results</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">Export to CSV each table in agents inventory with a search query should display results filtered</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">The agent inventory search bar placeholder of Network ports should be Search</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">The agent inventory search bar placeholder of Packages should be Search</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">The agent inventory search bar placeholder of Processes ports should be Search</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5329" target="_blank">The Malware detection link in Management/Configuration/Policy monitoring/System audit should open a valid link with the related documentation</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5341" target="_blank">The timepicker in the Evolution visualization of Agents section should close when clicking on it</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Comment by Desvelao** [comment]
# Kibana 7.16.3

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| [Empty input in the search bar of the agent inventory tables should display all the results](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [Add a search text input in the search bar of the agent inventory tables should display filtered the results](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [Export to CSV each table in agents inventory with an empty search query should display all the results](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [Export to CSV each table in agents inventory with a search query should display results filtered](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [The agent inventory search bar placeholder of Network ports should be Search](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [The agent inventory search bar placeholder of Packages should be Search](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [The agent inventory search bar placeholder of Processes ports should be Search](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [The Malware detection link in Management/Configuration/Policy monitoring/System audit should open a valid link with the related documentation](https://github.com/wazuh/wazuh-kibana-app/pull/5329) | :black_circle: | :black_circle: | :black_circle: |
| [The timepicker in the Evolution visualization of Agents section should close when clicking on it](https://github.com/wazuh/wazuh-kibana-app/pull/5341) | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">Empty input in the search bar of the agent inventory tables should display all the results</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">Add a search text input in the search bar of the agent inventory tables should display filtered the results</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">Export to CSV each table in agents inventory with an empty search query should display all the results</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">Export to CSV each table in agents inventory with a search query should display results filtered</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">The agent inventory search bar placeholder of Network ports should be Search</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">The agent inventory search bar placeholder of Packages should be Search</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">The agent inventory search bar placeholder of Processes ports should be Search</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5329" target="_blank">The Malware detection link in Management/Configuration/Policy monitoring/System audit should open a valid link with the related documentation</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5341" target="_blank">The timepicker in the Evolution visualization of Agents section should close when clicking on it</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Comment by yenienserrano** [comment]
# Kibana 7.17.8

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| [Empty input in the search bar of the agent inventory tables should display all the results](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [Add a search text input in the search bar of the agent inventory tables should display filtered the results](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [Export to CSV each table in agents inventory with an empty search query should display all the results](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [Export to CSV each table in agents inventory with a search query should display results filtered](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [The agent inventory search bar placeholder of Network ports should be Search](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [The agent inventory search bar placeholder of Packages should be Search](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [The agent inventory search bar placeholder of Processes ports should be Search](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [The Malware detection link in Management/Configuration/Policy monitoring/System audit should open a valid link with the related documentation](https://github.com/wazuh/wazuh-kibana-app/pull/5329) | :black_circle: | :black_circle: | :black_circle: |
| [The timepicker in the Evolution visualization of Agents section should close when clicking on it](https://github.com/wazuh/wazuh-kibana-app/pull/5341) | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">Empty input in the search bar of the agent inventory tables should display all the results</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">Add a search text input in the search bar of the agent inventory tables should display filtered the results</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">Export to CSV each table in agents inventory with an empty search query should display all the results</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">Export to CSV each table in agents inventory with a search query should display results filtered</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">The agent inventory search bar placeholder of Network ports should be Search</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">The agent inventory search bar placeholder of Packages should be Search</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">The agent inventory search bar placeholder of Processes ports should be Search</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5329" target="_blank">The Malware detection link in Management/Configuration/Policy monitoring/System audit should open a valid link with the related documentation</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5341" target="_blank">The timepicker in the Evolution visualization of Agents section should close when clicking on it</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Comment by yenienserrano** [comment]
# Wazuh dashboard

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| [Empty input in the search bar of the agent inventory tables should display all the results](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [Add a search text input in the search bar of the agent inventory tables should display filtered the results](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [Export to CSV each table in agents inventory with an empty search query should display all the results](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [Export to CSV each table in agents inventory with a search query should display results filtered](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [The agent inventory search bar placeholder of Network ports should be Search](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [The agent inventory search bar placeholder of Packages should be Search](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [The agent inventory search bar placeholder of Processes ports should be Search](https://github.com/wazuh/wazuh-kibana-app/pull/5196) | :black_circle: | :black_circle: | :black_circle: |
| [The Top 5 agents visualization of Modules/Integrity monitoring should not overflow the panel](https://github.com/wazuh/wazuh-kibana-app/pull/5334) | :black_circle: | :black_circle: | :black_circle: |
| [Navigate to Settings/About and confirm that the Welcome to the Wazuh dashboard and Community containers, and the blue bar that contains the App version, App revision and Install date on top of them doesn't reach the horizontal end of the screen in any of the sides](https://github.com/wazuh/wazuh-kibana-app/pull/5337) | :black_circle: | :black_circle: | :black_circle: |
| [The icon images in Settings/About should be spaced](https://github.com/wazuh/wazuh-kibana-app/pull/5337) | :black_circle: | :black_circle: | :black_circle: |
| [The Malware detection link in Management/Configuration/Policy monitoring/System audit should open a valid link with the related documentation](https://github.com/wazuh/wazuh-kibana-app/pull/5329) | :black_circle: | :black_circle: | :black_circle: |
| [The timepicker in the Evolution visualization of Agents section should close when clicking on it](https://github.com/wazuh/wazuh-kibana-app/pull/5341) | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">Empty input in the search bar of the agent inventory tables should display all the results</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">Add a search text input in the search bar of the agent inventory tables should display filtered the results</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">Export to CSV each table in agents inventory with an empty search query should display all the results</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">Export to CSV each table in agents inventory with a search query should display results filtered</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">The agent inventory search bar placeholder of Network ports should be Search</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">The agent inventory search bar placeholder of Packages should be Search</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5196" target="_blank">The agent inventory search bar placeholder of Processes ports should be Search</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5334" target="_blank">The Top 5 agents visualization of Modules/Integrity monitoring should not overflow the panel</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5337" target="_blank">Navigate to Settings/About and confirm that the Welcome to the Wazuh dashboard and Community containers, and the blue bar that contains the App version, App revision and Install date on top of them doesn't reach the horizontal end of the screen in any of the sides</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5337" target="_blank">The icon images in Settings/About should be spaced</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5329" target="_blank">The Malware detection link in Management/Configuration/Policy monitoring/System audit should open a valid link with the related documentation</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/pull/5341" target="_blank">The timepicker in the Evolution visualization of Agents section should close when clicking on it</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>
