### ISSUE TITLE
Update Wazuh Alpine (APK) repository RSA key on the `Deploy a new Agent` section

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-kibana-app#5358]
Related issue: https://github.com/wazuh/wazuh-jenkins/issues/4958

## Description
Since v4.4.0, Wazuh officially released Alpine packages that were signed using `https://packages.wazuh.com/key/alpine-devel%40wazuh.com-633d7457.rsa.pub` key.

Naming `alpine-devel%40wazuh.com-633d7457.rsa.pub` to the key could lead to the false interpretation of it as a development key.

![image](https://user-images.githubusercontent.com/1791430/230167380-c9f59125-2302-4a5b-8ccf-1738ae624b3d.png)
![image](https://user-images.githubusercontent.com/1791430/230167431-d6f97235-1dd7-460d-8f8c-928e3feb9bb7.png)

## Tasks
The steps that have to be completed in order to close the issue.

- [ ] Update such key URL based on wazuh/wazuh-jenkins#4966 implementation

## Additional information
Add here any additional information relevant to the issue or that will help to close it: chunks of code, logs, additional error messages, related issues and so on.

**Comment by teddytpc1** [comment]
@AlexRuiz7 we were not able to fix this on the APK repository. Let's move this to the next release (`4.4.3`).

**Comment by jnasselle** [comment]
Hi @gdiazlo,

Ok then, so this will be mainly addressed in https://github.com/wazuh/wazuh-documentation/issues/6018.

Thanks!
Nico
