### ISSUE TITLE
The GitHub and Office365 modules appear in the menu when these should be disabled

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#5369]
| Wazuh |
| ----- |
| 4.4   |

**Description**
The GitHub and Office365 modules appear in the menu when these should be disabled according to `Settings/Modules`.

This is happening in fresh installation or environments that never configured these modules.

**Screenshots**
![image](https://user-images.githubusercontent.com/34042064/231714210-bb5deeb9-26b2-404d-8b24-b785bd2e2dfa.png)
![image](https://user-images.githubusercontent.com/34042064/231714318-9a92ef71-79bf-4f23-bbea-565bd21d4d7a.png)

**Comment by Desvelao** [comment]
# Research

The problem was caused because the module ids of GitHub and Office 365 were not found in the configurated extensions, then it was treated as if the module visibility can not be configurated ( it means the module is always visible).

The changes in the pull request https://github.com/wazuh/wazuh-kibana-app/pull/5376 are solving the problem.

**Comment by AlexRuiz7** [comment]
Blocked

Reason: https://github.com/wazuh/wazuh-kibana-app/pull/5376#pullrequestreview-1388516407
