### ISSUE TITLE
wazuh-dashboard don't update external plugins on upgrade

### ISSUE THREAD

**Issue by uhlhosting** [wazuh/wazuh-kibana-app#5380]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.4   | -     | 4xxx | - |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
When a user has Wazuh deployed, and he adds any other plugin from Open Search repo, the upgrade will fail.

**Preconditions**
1. Must have Wazuh installed, tested with Open Search.

**Steps to reproduce**
1. Deploy a new plugin with ./bin/opensearch-plugin install desired plugin.
2. Upgrade Wazuh, to next release. My case I was on previous to current stable release. 4.4.0 and went to 4.4.1.
3. The Wazuh will fail to start after upgrade.

**Expected Result**
1. Have Wazuh upgraded and fully functional.

**Actual Result**
1. Wazuh cannot start, because the plugins added manually, were not upgraded in the upgrade process. And thus leaving Wazuh with discrepancies in the plugin versions. Wazuh seems to only upgrade the built in plugins shipped with.

**Screenshots**
N/A

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

Based on discussion from: https://wazuh.slack.com/archives/C0A933R8E/p1681315245491939

**Comment by AlexRuiz7** [comment]
Hello @uhlhosting 

To our understanding, non-wazuh plugins should be upgraded by the users. We understand that this must be stated in our documentation. For this reason, we have included a note in the upgrade guide to clarify this situation.

![image](https://github.com/wazuh/wazuh-kibana-app/assets/15186973/da6993a9-5e06-4819-ad8e-8f92e95b2140)

Regards,
Alex
