### ISSUE TITLE
Agent deploy command for macOS

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#5466]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x4.1  | -   | - | - |

| Browser |
| ------- |
| all |

**Description**

The command to start the agent in macOS should be run by root, so we need to add sudo as part of the command.

<img width="894" alt="image" src="https://github.com/wazuh/wazuh-kibana-app/assets/2181918/efb82540-b513-4c92-b373-2ca042463896">

The command

`/Library/Ossec/bin/wazuh-control start`

should be

`sudo /Library/Ossec/bin/wazuh-control start`

Also, the package name is going to be updated. We must update the installation command with the new name when it is available.

**Comment by jnasselle** [comment]
Hi @gdiazlo ,

As part of https://github.com/wazuh/wazuh-packages/issues/2205 implementation, `Deploy a new agent` section will need some changes related to deployment variables usage. Now the template will be the next one

```console
echo -e  'WAZUH_MANAGER="192.168.1.10"\nWAZUH_AGENT_GROUP="default"' > /tmp/wazuh_envs
```

Old environment variables should
- Be '\n' separated
- KEY="value"

**Comment by jnasselle** [comment]
# Update

Due to some optimizations in terms of usability and macOS availability of certain commands, the final specs about CLI installation command are

- Creation of a temp file by `echo` command stdout redirection
  - Command: `sudo echo`
  - Flags: none
  - Args:  ' && '-separated concatenation of list of KEY='VALUE', being KEY the available development variables and VALUE the one specified by the user
  - Output file: `/tmp/wazuh_envs` 
  - Considerations:
    - Command won't be used if no deployment variable was set. 
    - Command Args will be between double quotes, while each of the deployment variables values will be between single quotes
    - Deployment variable values need to be escaped if double quotes exist

Examples:

```console
sudo echo "WAZUH_MANAGER='1.1.1.1' && WAZUH_MANAGER_PORT='7777' && WAZUH_PROTOCOL='udp' && WAZUH_REGISTRATION_SERVER='2.2.2.2' && WAZUH_REGISTRATION_PORT='8888' && WAZUH_REGISTRATION_PASSWORD='password' && WAZUH_KEEP_ALIVE_INTERVAL='10' && WAZUH_TIME_RECONNECT='10' && WAZUH_REGISTRATION_CA='/Library/Ossec/etc/testsslmanager.cert' && WAZUH_REGISTRATION_CERTIFICATE='/Library/Ossec/etc/testsslmanager.cert' && WAZUH_REGISTRATION_KEY='/Library/Ossec/etc/testsslmanager.key' && WAZUH_AGENT_NAME='test-agent' && WAZUH_AGENT_GROUP='test-group' && ENROLLMENT_DELAY='10'" > /tmp/wazuh_vars && sudo installer -pkg wazuh-agent-4.4.3-0.commitb384726.pkg -target /
```
