### ISSUE TITLE
Updating an API with wrong credentials makes it unusable

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#549]
Hello team,

We've found an error when updating an existing API entry on the *Settings* tab. These are the steps to reproduce it:
1. Add an API as usual.
2. Reload the page with F5.
3. Click on the Edit button and insert, for example, a bad password.
4. Press <kbd>Enter</kbd> to start the updating process.
5. The app will throw a "Connection success" message.
6. Now if you press the Check button, it will show a "Wrong credentials" error.
7. If you try again to edit the API it will show a "Wrong credentials" error even if you insert the right password.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
Done here https://github.com/wazuh/wazuh-kibana-app/pull/558
