### ISSUE TITLE
Release 4.4.3 - RC1 - Kibana UI regression testing

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#5492]
## Description

This issue aims to track the effort to perform complete regression testing on Wazuh App 4.4.3 rev 01 for RC3

| Test         | Chrome | Safari | Firefox | Package |
|--------------|--------|--------|---------|---------|
| Example test | 🟢/🔴  | 🟢/🔴  | 🟢/🔴   | 🟢/🔴   |
 
### Status legend
⚫ - None
🔴 - Rejected
🟢 - Approved

In the case of 🔴, **create and add** the issue to the `Errors found` section. 

### Testing plan

- #5466 

### Testing notes

1) All the mentioned versions will be tested
2) It's necessary to include evidence of each test performed
3) In case to identify a bug/problem, the new feature should be linked to this issue

  - [x] 7.17.9
  - [x] 7.16.3
  - [x] WzD 4.4.3
  - [x] 7.10.2 + ODFE 1.2.0

**Comment by asteriscos** [comment]
# Kibana 7.10.2 ODFE

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| [The command to start the macOS agent in the deploy agent wizard uses sudo](https://github.com/wazuh/wazuh-kibana-app/issues/5466) | :green_circle: | :green_circle: | :black_circle: |
| [The command to install the macOS agent in the deploy agent wizard uses the echo command to set the environment variables when they are defined](https://github.com/wazuh/wazuh-kibana-app/issues/5466) | :green_circle: | :green_circle: | :black_circle: |
| [The command to install the macOS agent in the deploy agent wizard doesn't use the echo command to set the environment variables when they are not defined](https://github.com/wazuh/wazuh-kibana-app/issues/5466) | :green_circle: | :green_circle: | :black_circle: |

**Details**
<details>
<summary>:green_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5466" target="_blank">The command to start the macOS agent in the deploy agent wizard uses sudo</a></summary>

Chrome - :green_circle:
![image](https://github.com/wazuh/wazuh-kibana-app/assets/9343732/2df14a4a-e883-46d5-aa24-9c29ebc95c49)


Firefox - :green_circle:
![image](https://github.com/wazuh/wazuh-kibana-app/assets/9343732/4f5a0366-cbbc-4069-9d10-93ac3bf9c4ab)


Safari - :black_circle:

</details>

<details>
<summary>:green_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5466" target="_blank">The command to install the macOS agent in the deploy agent wizard uses the echo command to set the environment variables when they are defined</a></summary>

Chrome - :green_circle:
![Screenshot from 2023-05-25 13-05-10](https://github.com/wazuh/wazuh-kibana-app/assets/9343732/ec18a644-9d8a-4219-94a8-b960f46b62ab)


Firefox - :green_circle:
![image](https://github.com/wazuh/wazuh-kibana-app/assets/9343732/463328d4-3b2e-4d44-a935-e97e0063aca9)


Safari - :black_circle:

</details>

<details>
<summary>:green_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5466" target="_blank">The command to install the macOS agent in the deploy agent wizard doesn't use the echo command to set the environment variables when they are not defined</a></summary>

Chrome - :green_circle:
![image](https://github.com/wazuh/wazuh-kibana-app/assets/9343732/c8f931f1-b62d-4609-95bf-fc9eaad277aa)


Firefox - :green_circle:
![image](https://github.com/wazuh/wazuh-kibana-app/assets/9343732/5fceac69-d9d4-4693-8162-c48ea77f70f9)


Safari - :black_circle:

</details>

**Comment by Desvelao** [comment]
# Kibana 7.16.3

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| [The command to start the macOS agent in the deploy agent wizard uses sudo](https://github.com/wazuh/wazuh-kibana-app/issues/5466) | :green_circle: | :green_circle: | :black_circle: |
| [The command to install the macOS agent in the deploy agent wizard uses the echo command to set the environment variables when they are defined](https://github.com/wazuh/wazuh-kibana-app/issues/5466) | :green_circle: | :green_circle: | :black_circle: |
| [The command to install the macOS agent in the deploy agent wizard doesn't use the echo command to set the environment variables when they are not defined](https://github.com/wazuh/wazuh-kibana-app/issues/5466) | :green_circle: | :green_circle: | :black_circle: |

**Details**
<details>
<summary>:green_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5466" target="_blank">The command to start the macOS agent in the deploy agent wizard uses sudo</a></summary>

Chrome - :green_circle:
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/b365b1f9-e21c-4cbf-92f7-ee8f401f73e2)

Firefox - :green_circle:
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/6d9b5f3b-efb4-4970-a824-3925ffe0fa4a)

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5466" target="_blank">The command to install the macOS agent in the deploy agent wizard uses the echo command to set the environment variables when they are defined</a></summary>

Chrome - :green_circle:
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/ccb9ac37-8a52-4f21-ba72-320510f8e266)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/7587769d-44b7-458f-a349-ce5e0a9e7103)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/d1c5174f-6291-4a52-957c-ccb4364167ce)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/b62555f8-0bbb-461b-85b2-378ae3d45a3f)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/02acf047-b96b-423c-b58f-f940a231f623)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/e6dd9271-c167-42ce-bc1a-8d44be67d7db)

Firefox - :green_circle:
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/88e65d23-3b73-41b6-9d72-85aa38ad4047)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/ee02f16f-0214-43f0-aced-4631b0659427)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/012a228d-ec20-4797-b00e-98fda9019485)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/de994cad-44ab-44d4-9b85-16db6a1fcf38)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/00579728-9191-486a-add8-b61e5e98c6c0)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/a0c89c31-5f58-44ed-bd44-bf64d60afb19)

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5466" target="_blank">The command to install the macOS agent in the deploy agent wizard doesn't use the echo command to set the environment variables when they are not defined</a></summary>

Chrome - :green_circle:
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/03cefcfb-07d0-4285-86fc-3e222cb4da30)

Firefox - :green_circle:
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/46812c4d-8b06-4243-8f64-18c67cf93c77)

Safari - :black_circle:

</details>

**Comment by Desvelao** [comment]
# Wazuh dashboard 4.4.3

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| [The command to start the macOS agent in the deploy agent wizard uses sudo](https://github.com/wazuh/wazuh-kibana-app/issues/5466) | :black_circle: | :black_circle: | :black_circle: |
| [The command to install the macOS agent in the deploy agent wizard uses the echo command to set the environment variables when they are defined](https://github.com/wazuh/wazuh-kibana-app/issues/5466) | :black_circle: | :black_circle: | :black_circle: |
| [The command to install the macOS agent in the deploy agent wizard doesn't use the echo command to set the environment variables when they are not defined](https://github.com/wazuh/wazuh-kibana-app/issues/5466) | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5466" target="_blank">The command to start the macOS agent in the deploy agent wizard uses sudo</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5466" target="_blank">The command to install the macOS agent in the deploy agent wizard uses the echo command to set the environment variables when they are defined</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5466" target="_blank">The command to install the macOS agent in the deploy agent wizard doesn't use the echo command to set the environment variables when they are not defined</a></summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>
