### ISSUE TITLE
Agent register wizard doesn't handle properly special characters in password

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-kibana-app#5493]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.2   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
The password input in the Agent register wizard doesn't validate or handle special characters like single or double quotes for every operating system.

**Preconditions**
1. Set `use_password` to true in the manager configuration

**Screenshots**
![Screenshot from 2023-05-24 19-13-28](https://github.com/wazuh/wazuh-kibana-app/assets/9343732/a90180fe-c70d-4e40-b39e-ee74b13e4281)
![Screenshot from 2023-05-24 19-13-15](https://github.com/wazuh/wazuh-kibana-app/assets/9343732/75f9c236-af1b-47b4-b587-8f3e658cf199)

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by Machi3mfl** [comment]
## Testing enrollment comments

```bash
curl -so wazuh-agent.pkg https://packages.wazuh.com/4.x/macos/wazuh-agent-4.7.0-1.intel64.pkg && echo -e "WAZUH_MANAGER='192.168.0.19'\nWAZUH_AGENT_GROUP='default'\nWAZUH_AGENT_NAME='test-name'\nWAZUH_REGISTRATION_PASSWORD='password\"with\"doubleq\\'usds\\\"es'\n" > /tmp/wazuh_envs && sudo installer -pkg ./wazuh-agent.pkg -target /
```

- check when running the enrollment command and if the `authd.pass` agent file is created with correct password

## Possible Solution

```bash
echo -e "WAZUH_MANAGER='192.168.0.19'\nWAZUH_AGENT_GROUP='default'\nWAZUH_AGENT_NAME='test-name'\nWAZUH_REGISTRATION_PASSWORD=$'password\"with\"doubleq\\'usds\\\"es'\n" > /tmp/wazuh_envs && sudo installer -pkg ./wazuh-agent.pkg -target /
```

- Using Check to add $ character in parameters definitions. (on macOS, Linux)
- Possible `'` scaping `'"'"'`

## And check the test E2E

**Comment by Machi3mfl** [comment]
## Commands 

## Api in authd.pass

```
password"with"doubleq\'usds\"es
```

## Password from /config/auth/auth API endpoint

- in this case, the API scape the special characters " and \
```
"password\"with\"doubleq\\'usds\\\"es
```

## Password in command

```bash
wget https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.7.0-1_amd64.deb && sudo WAZUH_MANAGER='10.10.10.10' WAZUH_REGISTRATION_PASSWORD=$'password"with"doubleq\\'"'"'usds\"es' dpkg -i ./wazuh-agent_4.7.0-1_amd64.deb

// password"with"doubleq\\'"'"'usds\"es
```

## Linux 

## RPM
```bash
curl -o wazuh-agent-4.4.5-1.x86_64.rpm https://packages.wazuh.com/4.x/yum/wazuh-agent-4.4.5-1.x86_64.rpm && sudo WAZUH_MANAGER='10.10.10.10' WAZUH_REGISTRATION_PASSWORD=$'password"with"doubleq'"'"'usds\"es' rpm -ihv wazuh-agent-4.4.5-1.x86_64.rpm

```

## DEB
```bash
wget https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.4.5-1_amd64.deb && sudo WAZUH_MANAGER='10.10.10.10' WAZUH_REGISTRATION_PASSWORD=$'password"with"doubleq\'"'"'usds\"es' dpkg -i ./wazuh-agent_4.4.5-1_amd64.deb

```

# macOS

```bash
curl -so wazuh-agent.pkg https://packages.wazuh.com/4.x/macos/wazuh-agent-4.4.5-1.pkg && echo -e "WAZUH_MANAGER='10.10.10.10'\nWAZUH_REGISTRATION_PASSWORD=$'password\"with\"doubleq\\'usds\\\"es'\n" > /tmp/wazuh_envs && sudo installer -pkg ./wazuh-agent.pkg -target /
```
