### ISSUE TITLE
Remove agent name from the ribbon in agent detail page

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#5496]
## Description

In the agent detail page, the agent name is present in two places. We want to remove one, freeing up space and making the UI cleaner.

<img width="1322" alt="image" src="https://github.com/wazuh/wazuh-kibana-app/assets/2181918/7bd02a79-e723-4362-8e79-1c762075a54e">

**Comment by Desvelao** [comment]
Removed the agent name in the ribbon: https://github.com/wazuh/wazuh-kibana-app/pull/5497
