### ISSUE TITLE
The plugin does not display information properly

### ISSUE THREAD

**Issue by Anbu42** [wazuh/wazuh-kibana-app#5517]
| Wazuh | Elastic | 
| ----- | ------- | 
| 4.4   | 7.17     | 

| Browser |
| ------- |
| Firefox|

**Description**
The plugin does not display information properly. I also see an error when checking the index pattern.

**Screenshots**
![Screenshot from 2023-05-31 15-26-26](https://github.com/wazuh/wazuh-kibana-app/assets/18647322/cb1d811f-9174-4942-9d0b-0764ecce0c5f)

![Screenshot from 2023-05-31 15-27-18](https://github.com/wazuh/wazuh-kibana-app/assets/18647322/0263b2da-16d0-4ff3-8666-ac65fb287b9d)

![Screenshot from 2023-05-31 15-28-04](https://github.com/wazuh/wazuh-kibana-app/assets/18647322/cb2fdd0c-cccf-4b69-80c4-755442e74fa1)

**Additional context**
In the logs I see the following:
error: 2023/05/31 13:16:5: e.initializeVis: Request failed with status code 404
error: 2023/05/31 13:16:6: agents_preview_AgentsPreviewController.getMostActive: Request failed with status code 400

**Comment by AlexRuiz7** [comment]
Hello @Anbu42 

I see that you have changed the default index pattern for wazuh-alerts. Could you please tell me which changes have you done, so I can try to replicate this issue? I have changed it using the UI, but everything still works correctly.

Also, having more information about the error would help. Could you open the browsers' dev tools and look for the failing requests in the network tab?

Regards
Alex

**Comment by Anbu42** [comment]
Hello @AlexRuiz7 
I changed this `pattern: 'wazuh-logstash-*'` setting in /usr/share/kibana/data/wazuh/config/wazuh.yml

Failing request:
`{"error":"Incorrect HTTP method for uri [/template/wazuh-logstash-*] and method [GET], allowed: [POST]","status":405}`
![Screenshot from 2023-06-23 15-55-56](https://github.com/wazuh/wazuh-kibana-app/assets/18647322/07a6038d-a135-41b1-86e3-1543899a7519)

**Comment by AlexRuiz7** [comment]
Thanks!

Let me research this a bit deeper. I'll be back asap.

**Comment by AlexRuiz7** [comment]
Hello again @Anbu42 

First, sorry for the delay.

In that case, the malfunction is expected. The index pattern is used to match the indexes created by Wazuh, which follow the pattern `wazuh-alerts-4.x-:date:`. The default index pattern `wazuh-alerts-*` matches these indexes.

Your index pattern `wazuh-logstash` is probably not matching any indexes, and probably doesn't exist either (changing its name is not enough), so it's normal that no information is displayed, cause there is no matching data.

https://files.slack.com/files-pri/TMYFNFQ3W-F05EDHQMZ0S/image.png
_creation of a new index pattern_

![image](https://github.com/wazuh/wazuh-kibana-app/assets/15186973/f94282f3-ca5f-4026-8aea-bc7fd1a2c21e)


May I ask why you changed the index pattern to better understand your use case??

To resolve this problem, revert the index pattern back to `wazuh-alerts-*` and the app should be working properly again.

**Comment by Anbu42** [comment]
@AlexRuiz7 Hi.
I have a `wazuh-logstash-*` template and indexes that match this template.
![Screenshot from 2023-06-27 17-20-50](https://github.com/wazuh/wazuh-kibana-app/assets/18647322/cbe49cdc-b37b-40d1-a34e-168afdcca701)

I also tried to set up an entry in the `wazuh-alerts-*` index, but the result was the same.

**Comment by AlexRuiz7** [comment]
That looks good @Anbu42 

Does the index pattern show up in the Stack management < Index patterns section of the UI?

![image](https://github.com/wazuh/wazuh-kibana-app/assets/15186973/dec52dfb-54d0-44b7-b3e7-1a5d67296b4e)

**Comment by AlexRuiz7** [comment]
Closed due to inactivity
