### ISSUE TITLE
Display all available information for the agent when the hardware details aren't available

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh-kibana-app#5527]
## Description

During the exploratory testing wazuh/wazuh#17364, it was found that for those agents that don't have yet the hardware details collecting implemented, this message is shown

![242382053-2c4c8987-afb1-491f-a188-2e7dd894f6e0](https://github.com/wazuh/wazuh-kibana-app/assets/65046601/6cad6a22-3ee7-4184-a71f-eec98465792d)

But in the case of Solaris for example, the OS is obtained properly and that information could at least be shown 

![242382164-88d03b59-5a39-4768-b185-c873596eda79](https://github.com/wazuh/wazuh-kibana-app/assets/65046601/87874fae-2478-4fb2-8e13-cd44da291183)

Also the **last scan** field is important.

## Tasks
The steps that have to be completed in order to close the issue.

- [ ] Show the OS information of the agent even if the hardware information isn't available
- [ ] Show the last scan field

**Comment by gdiazlo** [comment]
We decided to not do it right now.
