### ISSUE TITLE
Compatibility with Wazuh 4.6.0

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#5548]
## Description
We need to ensure the UI compatibility with the next version of Wazuh, and the latest version of wazuh-indexer and wazuh-dashboard
This update is still being discussed, but we need to be aware of potential issues.

For that, we need to:

- [x] Review wazuh-indexer and wazuh-dashboard latest stable changelog. 
- [x] Identify improvements and potential impact on the UI.
- [x] Develop a testing environment to verify our components would work under this new build.
- [x] Update imposter with the changes made to Wazuh 4.6.0 for testing
- [x] Verify that the images for the testing environment works as expected

## Issues
- https://github.com/wazuh/wazuh-dashboard/issues/68
- https://github.com/wazuh/wazuh-dashboard/issues/62

**Comment by Tostti** [comment]
All tasks were successfully completed
