### ISSUE TITLE
Font overlapping in agent panel

### ISSUE THREAD

**Issue by snaow** [wazuh/wazuh-kibana-app#5562]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.4.4   | We dont use Elastic anymore     |  Its says 01 | Not sure |

| Browser |
| ------- |
| Chrome|

**Description**

IP Address value overlaps Version.

![image](https://github.com/wazuh/wazuh-kibana-app/assets/1519428/b178470e-4015-4c4d-a517-5b3c21929292)

**Comment by gdiazlo** [comment]
The fix will be released in 4.4.5 take a look at:
- https://github.com/wazuh/wazuh-kibana-app/issues/5464
