### ISSUE TITLE
Compatibility with Elastic 7.17.10

### ISSUE THREAD

**Issue by m09nrs** [wazuh/wazuh-kibana-app#5564]
## Description

> Hi,
> 
> Last month, on May 2nd, Elastic released Kibana version 7.17.10, which includes important security patches.
> See https://discuss.elastic.co/t/elastic-stack-8-7-0-7-17-10-security-updates/332327.
> 
> The two latest releases of the Wazuh Kibana plugin, v4.4.3 and v4.4.4, released on May 26th and yesterday respectively, only support Kibana 7.17.x up to patch version 7.17.9.
> 
> Do you plan to support 7.17.10 in the next release of the Wazuh Kibana plugin?
> 
> I apologize in advance if I've missed a post already discussing this issue.
> 
> Regards,

---
We need to ensure the UI compatibility with the next version of Elastic v7.17.10.
This update is approved, so we need to be aware of potential issues.

For that, we need to:

- [x] Review Elastic and Kibana latest stable changelog. 
- [x] Identify improvements and potential impact on the UI.
- [x] Develop a testing environment to verify our components would work under this new build.

## Issues
-  Lack of compatibility with the latest 7.17.x patch version of Kibana (7.17.10), which includes important security patches.

**Comment by AlexRuiz7** [comment]
Hello @m09nrs 

Thanks your getting in touch with us. In reply to your question, yes, the next release will be compatible with Elastic 7.1.10, unless we found major problems, which we don't expect.

Regards,
Alex

**Comment by AlexRuiz7** [comment]
## [Kibana 7.17.10 release notes](https://www.elastic.co/guide/en/kibana/7.17/release-notes-7.17.10.html)

> Dashboard
Fixes z-index of embPanel__header--floater [#136463](https://github.com/elastic/kibana/pull/136463)

**Comment by Desvelao** [comment]
# Research

I tested with the current `4.4-7.16` development branch using Kibana 7.17.10 (development mode) and didn't find any problem.

<details>
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/33940efc-6f06-4b99-8135-c42c66953a5c)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/c0dc1a28-f4a5-45b1-80dc-400988c3d0f3)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/6d0796f3-61c6-4b71-8d59-edc5371b5e2c)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/cf39d9a8-6451-4497-b48a-fefe02a1296f)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/75b03c92-3104-42dd-ade5-12264a4e073d)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/d1ec1eca-dd93-462d-a80e-7ddae7dcc9f9)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/cfcfbd27-0484-4b72-bbb0-a1f4aec743d8)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/599ae7ec-d164-4dbe-9705-615ca2800d07)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/d6a02cda-b4eb-4109-8506-e73a31d792b1)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/c2d8b034-0897-4527-83b3-23837b0adf54)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/463a97b2-d5c9-49d5-ac3e-fe6f462766c7)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/c1f92ed1-071f-47ad-9adb-718b42fe8b53)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/117d6a92-78a7-4ecb-b6fc-e93f8206216e)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/c1df87d3-b307-4829-af00-89816e98f76b)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/268e370e-07ca-45ba-b6e2-da452e19ac4c)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/e289dba4-201d-458e-8983-7fa195f7a580)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/5d2433e5-8406-4409-a801-2974472bfcb6)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/b3ed4317-0f7b-4dad-b204-4720ca8efe71)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/9474880c-0218-4023-a7cd-fb3e68c8c092)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/431e2206-2c95-4b2e-87bb-3bad83fb0d96)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/ee00733c-e30c-4cef-abbe-f619c4bbf37c)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/36910f9f-139e-4e9c-b246-231948010bbe)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/f3f75ea6-0342-4d35-b2b0-dd432709c308)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/bd3a8b4c-0fd5-42f5-be83-fbbb2ac36287)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/05a485fb-1207-40c0-9034-38bfb8dc0335)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/d5de460e-4b62-43d5-a48c-b02344eb9d1c)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/60f9c86e-7344-4593-81c7-f6fbfa63760e)

</details>
