### ISSUE TITLE
3013 - Permission denied: Resource type: *:* Wazuh plugin

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-kibana-app#5609]
| Wazuh | Rev  | Security |
| ----- | ---- | -------- |
| 4.4.4  | 1 | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Firefox|

I have a case coming from this [community](https://wazuh.slack.com/archives/C0A933R8E/p1686943088020279), the user is trying to create roles so that certain users can see only certain groups of users. You are following this documentation: https://documentation.wazuh.com/current/user-manual/user-administration/rbac.html#use-case-give-a-user-permissions-to-read-and-manage-a agent group

But get this error:
![image](https://github.com/wazuh/wazuh-kibana-app/assets/64099752/c8504ff5-7520-4835-9860-eac316126d33)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/64099752/7ec0a0ec-a62d-4e61-881c-62865dbd5442)

I was doing tests to try to replicate the user error:
- Register 4 agents, 3 Linux and 1 Window
- Create 2 groups of agents: Linux servers and Windows servers
- Create roles, groups, etc. following the documentation step by step
- When I logged in for the first time as a user with permissions for Windows servers, it did not show any error and it worked correctly.
- Then try to replicate the user's error, so that the user changes the run_as described in this step to false:
```console
For the role assignment to take effect, make sure run_as is set to true in the /usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml configuration file. Restart the Wazuh control panel service and clear your browser's cache and cookies.
```
- I rebooted the Wazuh dashboard and the error started to appear, then I changed it back to true, rebooted again and the error persisted.

In the documentation, I don't see any missing permissions, and I don't know if this change to run_as of the Wazuh plugin causes this error to appear and persist.

Despite this error message, I can verify the agents belonging to the group without problems

windows-user:
![image](https://github.com/wazuh/wazuh-kibana-app/assets/64099752/aca1e87d-4c88-4421-bc94-cbbe43310dbf)

linux-user:
![image](https://github.com/wazuh/wazuh-kibana-app/assets/64099752/ed4c8382-d233-476f-a537-2e61758ab014)

Wazuh All in One: Centos 7
![image](https://github.com/wazuh/wazuh-kibana-app/assets/64099752/bb0c1d2b-3d5d-43d8-b03c-ac74879feeb6)

**Comment by gdiazlo** [comment]
This is a known bug, and it is fixed in https://github.com/wazuh/wazuh-kibana-app/pull/5201 it is planned to be released in 4.6.0.
