### ISSUE TITLE
Move the Wazuh logs and reporting folders inside the app folder

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#562]
Hello team,

We have to discuss about moving the `wazuh-logs` and `wazuh-reporting` folders inside the `wazuh` one.

Currently, if we use the Kibana plugin command to list all installed plugins, it throws an error message because it detects those folders, but are not real Kibana plugins.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
A solution is done here https://github.com/wazuh/wazuh-kibana-app/pull/563, if the team decides to change the logic used by that PR, we'll reopen this issue.

Regards
