### ISSUE TITLE
Agent name is not clearly visible in dark mode

### ISSUE THREAD

**Issue by Damian-Mangold** [wazuh/wazuh-kibana-app#5662]
| Wazuh |  Rev  | 
| ----- | ---- |
| 4.4.4  | 1 | 

| Browser |
| ------- |
| Chrome, Firefox|

**Description**
[This problem was reported by a user](https://groups.google.com/u/1/g/wazuh/c/yDwmmJqtMvY). In the group configuration `Management -> Group -> Manage agents`, the agent's name is not clearly visible in dark mode. 

**Preconditions**
Adding at most one agent to the manager.

**Steps to reproduce**
Enable a dark mode for the OpenSearch Dashboards UI `Management -> Stack Management -> Advanced Settings -> Enable a dark mode`

**Expected Result**
The agent's name can be read in dark mode.

**Actual Result**
Default mode
![image](https://github.com/wazuh/wazuh-kibana-app/assets/106940255/2e65e08f-09b1-4d29-b6d0-f457360ad876)

Dark mode
![image](https://github.com/wazuh/wazuh-kibana-app/assets/106940255/609b69e3-ae98-4013-bb2b-3a197bdf4610)

**Comment by chantal-kelm** [comment]
This is how the agent's name in the groups section looked in dark mode:

<img width="1792" alt="Captura de pantalla 2023-07-12 a la(s) 13 07 44" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/62bd2075-d25f-432d-9a89-71ce7a6b7ebf">

This is how it looks now:

<img width="1792" alt="Captura de pantalla 2023-07-12 a la(s) 13 49 03" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/7fa08db3-fd25-4001-a321-2e25544bd66f">
