### ISSUE TITLE
Release 4.4.5 - Release Candidate 2 - Wazuh UI regression testing

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#5663]
The following issue aims to run manual tests for the current release candidate, report the results, and open new issues for any encountered errors.

## Wazuh UI tests information
|                                        |                                             |
|----------------------------------------|---------------------------------------------|
| **Main release candidate issue**       | https://github.com/wazuh/wazuh/issues/17844 |
| **Version**                            | 4.4.5                                       |
| **Release candidate #**                | 2                                           |
| **Tag**                                | v4.4.5-rc2                                  |
| **Previous UI regression tests issue** | #5646                                       |

## Test report procedure

**TL;DR**
   1. The specified tests will be executed in every platform and version mentioned in this issue.
   1. Include evidence of each test performed.
   1. Report any problem or bug. Open a new issue for each of them and link them here.
   1. Justify skipped tests.

All test results must have one the following statuses: 
|                 |                                                                      |
|-----------------|----------------------------------------------------------------------|
| :black_circle:  | The test hasn't started yet.                                         |
| :green_circle:  | All checks passed.                                                   |
| :red_circle:    | There is at least one failed check.                                  |
| :yellow_circle: | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause.
It must be included in the `Problems` section of the current release candidate issue.

Any expected fail or skipped test must be justified with a reason. 
All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a zip, txt or images. 
This report can be used by the auditors to dig deeper into any possible failures and details.

## Test template

| Test | Chrome         | Firefox        | Safari         |
|------|----------------|----------------|----------------|
| -    | :black_circle: | :black_circle: | :black_circle: |

## Test plan

1. Verify the app package installs and operates as expected.

## Conclusions

| Status         | Platform                   |
|----------------|----------------------------|
| :green_circle: | Wazuh dashboards 4.4.5-rc2 |
| :green_circle: | Kibana 7.17.9              |
| :green_circle: | Kibana 7.16.3              |
| :green_circle: | Kibana 7.10.2 + ODFE 1.2.0 |

## Conclusions

All tests have been skipped as the build process fails.

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @AlexRuiz7

**Comment by Tostti** [comment]
# Kibana 7.10.2 + ODFE 1.2.0


Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Verify the app package installs and operates as expected | :green_circle: | :green_circle: | :black_circle: |



**Details**
<details>
<summary>:green_circle: Verify the app package installs and operates as expected</summary>

Chrome - :green_circle:

![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/6936ffb5-f7c6-437a-ad03-424830776065)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/0beff282-b861-4bfb-8b11-34bbabf36bb6)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/952642b3-cb98-4069-ad2d-5ada7a59e073)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/da1ad76b-a3c4-4387-bc47-d82ce9dbea8b)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/e8b3cbbf-f992-49ec-b328-1896baebddf0)



Firefox - :green_circle:
![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/98c29647-4eb3-45fb-b66a-13677ce8532c)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/0df81323-d167-401b-9877-7390e8731f80)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/2eb38d6f-dcd6-4caf-b4fe-891408657e94)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/8910dc1f-8347-4b39-a28e-bc0c29b9e316)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/0169cd78-6a70-45aa-ab20-948c8ac138d6)



Safari - :black_circle:

</details>

**Comment by Tostti** [comment]
# Kibana 7.17.9


Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Verify the app package installs and operates as expected | :green_circle: | :green_circle: | :black_circle: |



**Details**
<details>
<summary>:green_circle: Verify the app package installs and operates as expected</summary>

Chrome - :green_circle:

![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/e1316544-0bfc-408c-b7db-55a66c08a450)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/525aab72-9655-4eb6-bbd4-845741c699f9)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/031630bf-d169-4cbe-97e2-4fb97834c7ab)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/ee19727b-aad9-4eda-96fa-25a9b4aff86a)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/0c4945ee-b984-4b99-896a-f24b3edf704d)




Firefox - :green_circle:
![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/70f6db5c-b15b-4dd9-96ce-ea899c21a878)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/c266a4ae-e6dd-48cf-a892-6b78f75c2384)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/20add6a9-38fc-4eb2-bc3d-d3a224f0dffd)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/95051b45-f385-4bd8-891c-0d7bdd5a5545)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/2ec5fde4-2be6-47fa-9f4b-9bff97d591cf)




Safari - :black_circle:

</details>

**Comment by Tostti** [comment]
# Kibana 7.16.3


Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Verify the app package installs and operates as expected | :green_circle: | :green_circle: | :black_circle: |



**Details**
<details>
<summary>:green_circle: Verify the app package installs and operates as expected</summary>

Chrome - :green_circle:

![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/cea7935f-ff86-437f-bf45-71b171a2ad8c)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/04f94d32-e3ae-4927-a341-72b09b406684)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/da30c4ff-55c3-44eb-8c72-7d2c5b88eb0d)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/ad5577ed-bca2-4769-bc81-799463a3dfe8)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/ea9f2953-f590-47cb-aafb-ac7ddd73c66b)



Firefox - :green_circle:
![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/bec71f98-ae2e-4bc0-8e30-7872e420d819)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/dca54deb-df92-4a97-8519-dcde22cc6496)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/d302ebeb-3fb1-4c3c-9119-466fdbd7b40e)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/f444f005-e85b-4f72-bfa1-5e9ecd654e11)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/42900763/03b168d8-cfe1-4c19-b3e3-0a9d3b4f22e7)





Safari - :black_circle:

</details>
