### ISSUE TITLE
The command indicated in the WUI to start the agent on Oracle Linux is incorrect

### ISSUE THREAD

**Issue by sultanovich** [wazuh/wazuh-kibana-app#5713]
| Wazuh | OpenSearch | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.4.x   | 2.6.0 (Rev 02)     | 40413 | Basic |

| Browser |
| ------- |
| Chrome|

**Description**
The commands described in the WUI to install Wazuh agent on Oracle Linux are not correct in `v4.4.x`. This fix is related to issue [#2223](https://github.com/wazuh/wazuh-packages/issues/2223).

**Preconditions**
None

**Steps to reproduce**
1. Navigate to 'Agents.'
2. Click on 'Deploy a new agent'
3. Choose the operating system 'Oracle Linux'
![image](https://github.com/wazuh/wazuh-kibana-app/assets/601474/a75b400e-4de8-4c64-86d0-7ff304025395)

4. Choose the version 'Oracle Linux 6 +'
![image](https://github.com/wazuh/wazuh-kibana-app/assets/601474/db8aa8f0-af0e-43be-b1fb-0e8009ff01ae)

5. Scroll down to 'Start the agent'
![image](https://github.com/wazuh/wazuh-kibana-app/assets/601474/34ccbfaf-cde7-4091-b003-d334008d5f1e)

**Expected Result**
The appropriate commands that should be included here is the following:

![image](https://github.com/wazuh/wazuh-kibana-app/assets/601474/583bee35-4032-4b59-b5d7-b65bb3a18bdc)

**Additional context**
It is necessary to update the commands offered to the user to start the service in Oracle Linux.

This problem occurs in Oracle Linux 6 or higher environments, if the Oracle Linux 5 option is chosen, the commands are correct.

|  Oracle Linux 5  | Oracle Linux 6 + |
| ------------- | ------------- |
| ![image](https://github.com/wazuh/wazuh-kibana-app/assets/601474/22272d47-0a62-4cc4-9b04-331e81e4c814)  |  ![image](https://github.com/wazuh/wazuh-kibana-app/assets/601474/c19bb0d0-f97c-4b27-b34e-2aaf2e0c5d61)  |

**Comment by AlexRuiz7** [comment]
Thanks @sultanovich 

We'll fix this in 4.5.2.
