### ISSUE TITLE
Cannot read property 'setBlankScr' of undefined

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#574]
A Wazuh team member reported the title message as error, we need to review it.

Regards,
Jesús

**Comment by jesusgn90** [comment]
Done here https://github.com/wazuh/wazuh-kibana-app/pull/575

**Comment by RealLinkers** [comment]
Still got the error!

**Comment by jesusgn90** [comment]
Hello @RealLinkers , it was fixed but maybe not in your package. Which revision have you installed?

```
cat /usr/share/kibana/plugins/wazuh/package.json | grep revision
```
Regards,
Jesús

**Comment by RealLinkers** [comment]
"revision": "0397"

**Comment by jesusgn90** [comment]
@RealLinkers seems weird cause that package has the fix indeed. Maybe you have cached files in the server side and/or in the client side.

Only to be sure, we are going to fully clean your environment to discard cache issues:

```
# systemctl stop kibana
# rm -rf /usr/share/kibana/optimize/bundles
# systemctl restart kibana
```

The last command takes few minutes, please wait until finished. You can check the status as follow:

`# watch 'systemctl status kibana -l' `

Look at the optimizing progress.

Once done, please open a new _incognito_ window in your browser or ensure your cache/cookies are fully removed before try again.

Regards,
Jesús

**Comment by RealLinkers** [comment]
Doesn't seem to be helping.
I extracted the following Kibana logs. 

`{"type":"log","@timestamp":"2018-06-29T05:53:43Z","tags":["info","optimize"],"pid":5203,"message":"Optimizing and caching bundles for ml, wazuh, stateSessionStorageRedirect, status_page, timelion, graph, monitoring, login, logout, dashboardViewer, apm, analyze-api-ui-plugin, own_home and kibana. This may take a few minutes"}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["info","optimize"],"pid":5203,"message":"Optimization of bundles for ml, wazuh, stateSessionStorageRedirect, status_page, timelion, graph, monitoring, login, logout, dashboardViewer, apm, analyze-api-ui-plugin, own_home and kibana complete in 237.09 seconds"}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["status","plugin:kibana@6.3.0","info"],"pid":5203,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["status","plugin:elasticsearch@6.3.0","info"],"pid":5203,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["status","plugin:xpack_main@6.3.0","info"],"pid":5203,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["status","plugin:searchprofiler@6.3.0","info"],"pid":5203,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["status","plugin:ml@6.3.0","info"],"pid":5203,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["status","plugin:tilemap@6.3.0","info"],"pid":5203,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["status","plugin:watcher@6.3.0","info"],"pid":5203,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["status","plugin:license_management@6.3.0","info"],"pid":5203,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["status","plugin:index_management@6.3.0","info"],"pid":5203,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["\u001b[34mwazuh\u001b[39m","initialize","info"],"pid":5203,"message":"Kibana index: .kibana"}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["\u001b[34mwazuh\u001b[39m","monitoring","info"],"pid":5203,"message":"wazuh.monitoring.enabled: true"}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["\u001b[34mwazuh\u001b[39m","monitoring","info"],"pid":5203,"message":"wazuh.monitoring.frequency: 3600 (0 */60 * * * *)"}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["\u001b[34mwazuh\u001b[39m","monitoring","info"],"pid":5203,"message":"Waiting for Kibana and Elasticsearch servers to be ready..."}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["status","plugin:wazuh@3.3.1","info"],"pid":5203,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["status","plugin:timelion@6.3.0","info"],"pid":5203,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["status","plugin:graph@6.3.0","info"],"pid":5203,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["status","plugin:monitoring@6.3.0","info"],"pid":5203,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["status","plugin:security@6.3.0","info"],"pid":5203,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["security","warning"],"pid":5203,"message":"Generating a random key for xpack.security.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.security.encryptionKey in kibana.yml"}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["security","warning"],"pid":5203,"message":"Session cookies will be transmitted over insecure connections. This is not recommended."}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["status","plugin:grokdebugger@6.3.0","info"],"pid":5203,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["status","plugin:dashboard_mode@6.3.0","info"],"pid":5203,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["status","plugin:logstash@6.3.0","info"],"pid":5203,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["status","plugin:apm@6.3.0","info"],"pid":5203,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["status","plugin:console@6.3.0","info"],"pid":5203,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["status","plugin:console_extensions@6.3.0","info"],"pid":5203,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["status","plugin:analyze-api-ui-plugin@6.3.0","info"],"pid":5203,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["status","plugin:own_home@6.3.0","info"],"pid":5203,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["status","plugin:metrics@6.3.0","info"],"pid":5203,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-06-29T05:57:41Z","tags":["plugin:own-home","info"],"pid":5203,"message":"Proxy server started at http://localhost:19200"}
{"type":"log","@timestamp":"2018-06-29T05:57:42Z","tags":["reporting","warning"],"pid":5203,"message":"Generating a random key for xpack.reporting.encryptionKey. To prevent pending reports from failing on restart, please set xpack.reporting.encryptionKey in kibana.yml"}
{"type":"log","@timestamp":"2018-06-29T05:57:42Z","tags":["status","plugin:reporting@6.3.0","info"],"pid":5203,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-06-29T05:57:42Z","tags":["error","elasticsearch","data"],"pid":5203,"message":"Request error, retrying\nHEAD http://localhost:19200/.kibana => connect ECONNREFUSED 127.0.0.1:19200"}
{"type":"log","@timestamp":"2018-06-29T05:57:42Z","tags":["error","elasticsearch","data"],"pid":5203,"message":"Request error, retrying\nGET http://localhost:19200/_template/wazuh-agent => connect ECONNREFUSED 127.0.0.1:19200"}
{"type":"log","@timestamp":"2018-06-29T05:57:42Z","tags":["listening","info"],"pid":5203,"message":"Server running at http://<disclosed_ip>:5601"}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["status","plugin:elasticsearch@6.3.0","info"],"pid":5203,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["\u001b[34mwazuh\u001b[39m","monitoring","info"],"pid":5203,"message":"Updating wazuh-monitoring template..."}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["license","info","xpack"],"pid":5203,"message":"Imported license information from Elasticsearch for the [data] cluster: mode: basic | status: active"}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["status","plugin:xpack_main@6.3.0","info"],"pid":5203,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["status","plugin:searchprofiler@6.3.0","info"],"pid":5203,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["status","plugin:ml@6.3.0","info"],"pid":5203,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["status","plugin:tilemap@6.3.0","info"],"pid":5203,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["status","plugin:watcher@6.3.0","info"],"pid":5203,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["status","plugin:index_management@6.3.0","info"],"pid":5203,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["status","plugin:graph@6.3.0","info"],"pid":5203,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["status","plugin:security@6.3.0","info"],"pid":5203,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["status","plugin:grokdebugger@6.3.0","info"],"pid":5203,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["status","plugin:logstash@6.3.0","info"],"pid":5203,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["status","plugin:reporting@6.3.0","info"],"pid":5203,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["info","monitoring-ui","kibana-monitoring"],"pid":5203,"message":"Starting all Kibana monitoring collectors"}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["\u001b[34mwazuh\u001b[39m","initialize","info"],"pid":5203,"message":"Checking .wazuh index."}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["\u001b[34mwazuh\u001b[39m","initialize","info"],"pid":5203,"message":"Checking .wazuh-version index."}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["\u001b[34mwazuh\u001b[39m","monitoring","info"],"pid":5203,"message":"Creating today index..."}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["license","info","xpack"],"pid":5203,"message":"Imported license information from Elasticsearch for the [monitoring] cluster: mode: basic | status: active"}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["\u001b[34mwazuh\u001b[39m","[initialize][checkAPIEntriesExtensions]","info"],"pid":5203,"message":"Checking extensions consistency for all API entries"}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["\u001b[34mwazuh\u001b[39m","monitoring","info"],"pid":5203,"message":"Checking if wazuh-monitoring pattern exists..."}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["\u001b[34mwazuh\u001b[39m","initialize","info"],"pid":5203,"message":".wazuh-version document already exists. Updating version information..."}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["\u001b[34mwazuh\u001b[39m","initialize","info"],"pid":5203,"message":"Successfully updated .wazuh-version index"}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["\u001b[34mwazuh\u001b[39m","monitoring","info"],"pid":5203,"message":"Skipping wazuh-monitoring creation. Already exists."}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["\u001b[34mwazuh\u001b[39m","[initialize][checkAPIEntriesExtensions]","info"],"pid":5203,"message":"Successfully updated API entry extensions with ID: 1530251435570"}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["\u001b[34mwazuh\u001b[39m","reindex","info"],"pid":5203,"message":"Old version detected. Proceeding to reindex."}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["\u001b[34mwazuh\u001b[39m","initialize","info"],"pid":5203,"message":"x-pack enabled and using security: no"}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["\u001b[34mwazuh\u001b[39m","initialize","info"],"pid":5203,"message":"Found 7 index patterns"}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["\u001b[34mwazuh\u001b[39m","initialize","info"],"pid":5203,"message":"Found 1 valid index patterns for Wazuh alerts"}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["\u001b[34mwazuh\u001b[39m","initialize","info"],"pid":5203,"message":"Default index pattern found"}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["\u001b[34mwazuh\u001b[39m","initialize","info"],"pid":5203,"message":"Refreshing known fields for \"index-pattern:wazuh-alerts-3.x-*\""}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["\u001b[34mwazuh\u001b[39m","reindex","info"],"pid":5203,"message":"Successfully backed up .wazuh index"}
{"type":"log","@timestamp":"2018-06-29T05:57:43Z","tags":["\u001b[34mwazuh\u001b[39m","initialize","info"],"pid":5203,"message":"App ready to be used."}
{"type":"log","@timestamp":"2018-06-29T05:57:46Z","tags":["\u001b[34mwazuh\u001b[39m","reindex","info"],"pid":5203,"message":"Deleting old .wazuh index."}
{"type":"log","@timestamp":"2018-06-29T05:57:46Z","tags":["\u001b[34mwazuh\u001b[39m","reindex","info"],"pid":5203,"message":"Reindexing into the new .wazuh"}
{"type":"log","@timestamp":"2018-06-29T05:57:49Z","tags":["\u001b[34mwazuh\u001b[39m","reindex","info"],"pid":5203,"message":"Reaching undefined"}
{"type":"log","@timestamp":"2018-06-29T05:57:49Z","tags":["\u001b[34mwazuh\u001b[39m","reindex","info"],"pid":5203,"message":"Nothing to be done for undefined as it is already a 3.x version."}`

**Comment by JuanjiJG** [comment]
Hello @RealLinkers,

Thanks for sending your logs.

I can see some `ECONNREFUSED` error messages. Looks like Kibana is not capable of connecting with Elasticsearch. Are Elasticsearch and Kibana on the same machine?

Please, paste here your Kibana and Elasticsearch configuration files, (removing sensitive information, such as passwords, if so):
```
cat /etc/kibana/kibana.yml
cat /etc/elasticsearch/elasticsearch.yml
```

Regards,
Juanjo

**Comment by RealLinkers** [comment]
This is the Kibana config:
`server.port: 5601
server.host: "<disclosed_ip>"
elasticsearch.url: "http://<disclosed_ip>:9200"
logging.dest: /var/log/kibana/kibana.log`

Elasticsearch:
`cluster.name:` xxx-cluster
node.name: elk-co
node.master: false
node.data: false
node.ingest: false
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
network.host: <disclosed_ip>.114
http.port: 9200
discovery.zen.ping.unicast.hosts: ["<disclosed_ip>.111", "<disclosed_ip>.112", "<disclosed_ip>.113", `"<disclosed_ip>.114"]`

This is a coordinating node on which Kibana is running on and querying. I also had Own_home plugin installed, which proxied some requests I removed that aswell, but it didn't solve the issue in any way.

**Comment by JuanjiJG** [comment]
Hello again @RealLinkers,

Did you upgrade your Elastic stack installation from a previous version such as 5.x?

Let's try something different.

1. Stop the Kibana service:
```
systemctl stop kibana
```
2. Delete the `` and `` indices to restore your Wazuh app. Keep in mind that you'll lose your currently saved APIs from Settings, so you'll have to insert them again.
```
curl -XDELETE <ELASTICSEARCH_IP>:9200/.wazuh,.wazuh-version
``` 
3. Restart the Kibana service:
```
systemctl restart kibana
```

Now open again the app on an incognito window on your Internet browser and try to open the app again and insert the API credentials. Let me know about the results.

Regards,
Juanjo

**Comment by RealLinkers** [comment]
Juanj, thank you for your time. I am really appreciating the quick responses you are giving.
I did the following, and it fixed the issue at hand.
I ran into another issue by clicking on a section called Agents.
I did the steps provided by you there, they didn't seem to solve the issue.
https://github.com/wazuh/wazuh/issues/496

Are there any steps I could do, to completley wipe Wazuh index and than recreate it properly?

**Comment by RealLinkers** [comment]
Managed to get it to work with:
/bin/systemctl stop wazuh-api wazuh-manager && \
  /usr/bin/curl -XDELETE 'http://localhost:9200/wazuh-*' && \
  /usr/bin/curl -XDELETE 'http://localhost:9200/_template/*' && \
  /bin/systemctl restart kibana && \
  /bin/systemctl start wazuh-api wazuh-manager

Thank you for everything!

**Comment by JuanjiJG** [comment]
Hello @RealLinkers,

Your `Field data is disabled on text fields by default` means that somehow, something on the mappings changed and some fields expected to be `keyword` are now `text`, so that's why the app showed that error.

I'm glad you finally solved your issue. Just to clarify, your second `XDELETE` command doesn't make any effect, because you didn't specify any template name after `/_template/`. In any case, it's not necessary to do that step.

I'll proceed to close this issue. Don't hesitate to open a new issue if you have more questions or problems.

Regards,
Juanjo
