### ISSUE TITLE
Does not show events in the 'Docker Listener', 'VirusTotal' and 'System Auditing' Modules when they are enabled

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-kibana-app#5749]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.5.0   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Firefox 115.0.2 (64-bit)|
---

### **Description**

We detected that when we activate some modules they don't show alerts.

In this case we are working in the 4.5.0 Demo environment that has 2 APIs (env-1 and env-2).

**Note: You need to have a Demo with 2 environments.**
---

**Steps to reproduce**

1. On Env 2, go to Wazuh > Settings > Modules 
2. Go to the `Threat Detection and Response` section > Activate each option (VirusTotal, Docker listener, Osquery).
3.  Go to the `Auditing and Policy Monitoring` section > Check that System auditing is activated.

--- 

### **Expected Result**
1. It shows alerts for each module 

### **Actual Result**

1. The modules show events except Docker Listener, VirusTotal, and System Auditing when they are activated.

**Screenshots**

<details>
<summary>Details of modules activated</summary>

![modulenv2](https://github.com/wazuh/wazuh-kibana-app/assets/3978434/e21b6fb9-b2f1-4cc7-95aa-dc2b0e780604)
</details>
<details>
<summary>Details of modules without alerts</summary>

![env2Docker](https://github.com/wazuh/wazuh-kibana-app/assets/3978434/2f2cb861-1bfe-46c8-8723-cfa5cd9cb89b)

![env2System](https://github.com/wazuh/wazuh-kibana-app/assets/3978434/4a62d9e1-88bb-4a60-9544-a71064586c39)

![env2Virustotal](https://github.com/wazuh/wazuh-kibana-app/assets/3978434/26e574eb-3efa-4b6d-8926-6be547381296)

</details>

**Comment by davidjiglesias** [comment]
This is expected based on comment from @teddytpc1 here https://github.com/wazuh/wazuh/issues/18065#issuecomment-1660475563
