### ISSUE TITLE
Alert settings using Web UI

### ISSUE THREAD

**Issue by arvindjkhr** [wazuh/wazuh-kibana-app#5754]
## Description
Can we create alert rules/settings from Web UI based on specific conditions like we can do in Zabbix and other software, so admin does not need to go to console and restart service every time they want create some new rule sets or alerts. 

## Tasks
The steps that have to be completed in order to close the issue.

- Applying SMTP Settings using Web UI
- Create (rule id / agent id) based alerts from Web UI Itself without restarting Wazuh manager every time.
- Apply Webhook related settings from Web UI and create rules for it based on client specific conditions.

**Comment by AlexRuiz7** [comment]
Closed due to inactivity
