### ISSUE TITLE
Outdated year in PDF report footer copyright

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-kibana-app#5765]
| Wazuh | Elastic | Rev  | 
| ----- | ------- | ---- | 
| 4.4.5   | 7.x     | 4xxx |

**Description**
PDF reports have an outdated year in the footer copyright. We need to analyze the possibility to make it dynamic instead of being hardcoded.

https://github.com/wazuh/wazuh-kibana-app/blob/v4.4.5-2.6.0/common/constants.ts#L281

**Screenshots**

![image](https://github.com/wazuh/wazuh-kibana-app/assets/9343732/2f7e4164-3ac7-463f-8696-fcb55be650d9)

**Comment by Tostti** [comment]
All PRs successfully merged
