### ISSUE TITLE
Dev tools: Allow params in the same line

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh-kibana-app#577]
We should include both ways to do a request: json and one line. It is a common syntax for GET requests.

![image](https://user-images.githubusercontent.com/1523318/41406806-bf830c66-6fcd-11e8-8d08-54db3a9067c1.png)

**Comment by jesusgn90** [comment]
You are right @jesuslinares and it makes sense. Once the adapting to 6.3.0 finishes we'll add one-line queries feature to our dev tools.

Regards,
Jesús

**Comment by jesusgn90** [comment]
Hello team and @jesuslinares , this feature is added in https://github.com/wazuh/wazuh-kibana-app/pull/583, thanks for your suggestion.

Now you could use the dev tools as follow:

Single path
```
GET /agents
```

Inline query
```
GET /agents?limit=1&node=node01
```

JSON query
```
GET /agents
{
  "limit": 1
}
```

Inline query + JSON query
```
GET /agents?limit=1
{
  "node": "node01"
}
```

__Note__. Inline queries have precedence to JSON input, this means:

```
GET /agents?limit=22
{
  "limit": 1
}
```
The above request will use `limit=22` and not `limit=1`.

Regards,
Jesús
