### ISSUE TITLE
Creating and OpenSearch Plugin (/usr/share/wazuh-dashboard/plugins/)

### ISSUE THREAD

**Issue by Rohr2827** [wazuh/wazuh-kibana-app#5801]
I have been utilizing Wazuh for about a year and began to wonder if I am able to create my own plugin/custom pages on the dashboard. After looking into it for a while, I have not found an easy way of creating one. It seems that any way of creating one through kibana or opensearch has been removed. I tried to use this guide https://opensearch.org/blog/dashboards-plugins-intro/. Is there a way to create a base template or to copy an existing plugin to make it your own? The only ones that I have been able to use have been created already and are shown on opensearch but with slightly different names https://opensearch.org/docs/latest/install-and-configure/install-dashboards/plugins/.

**Comment by asteriscos** [comment]
Hi @Rohr2827,
to create your own custom plugin in an easy way you can use the plugin generator tool that both OpenSearch and Kibana offer:

- https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/packages/osd-plugin-generator/README.md
- https://github.com/elastic/kibana/blob/main/packages/kbn-plugin-generator/README.md

On the other hand, if what you need is actually create your custom dashboard using Wazuh alerts in the Indexer, I suggest you use de Dashboard plugin to create your own visualizations and custom dashboards to fit your needs.

Hope it helps.
