### ISSUE TITLE
Generate new routes for the apps

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#5820]
## Description

The new design based on applications needs the relative redirections will be modified to application redirections.

## Analyze the redirections

| Application       | Old URL                                                                    | New URL                                                                                           | Affected files                                                                                     | Comment                  |
|-------------------|----------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------|--------------------------|
| {app}/heal-check  | /app/wazuh#/settings                                                       | /app/server-api                                                                                | plugins/main/public/components/health-check/container/health-check.container.tsx                   |                          |
| Overview          | #/agents-preview                                                           | /app/endpoints-summary#/agents-preview                                                         | plugins/main/public/controllers/overview/components/stats.js                                       |                          |
| Endpoints summary | #/agents-preview?                                                          | /app/endpoints-summary#/agents-preview?                                                        | plugins/main/public/components/common/welcome/overview-welcome.js                                  |                          |
| Endpoints summary | #/agents?tab=welcome&agent={agentID}                                       | /app/it-hygiene#/agents?tab=welcome&agent={agentID}                                            | plugins/main/public/controllers/agent/components/agents-table.js                                   |                          |
| IT Hygiene        | /app/wazuh#/manager/?tab=groups                                            | /app/endpoint-groups#/manager/?tab=groups                                                                  | plugins/main/public/components/common/util/agent-group-truncate/group-truncate.tsx                 | Use share agents service |
| IT Hygiene        | #/overview?tab=mitre                                                       | /app/mitre-attack                                                                              | plugins/main/public/components/common/welcome/agents-welcome.js                                    |                          |
| IT Hygiene        | #/overview/?tab=fim                                                        | /app/file-integrity-monitoring                                                                      | plugins/main/public/components/common/welcome/agents-welcome.js                                    |                          |
| IT Hygiene        | #/overview?tab={module}                                                    | /app/{app}                                                                                        | plugins/main/public/components/common/welcome/agents-welcome.js                                    |                          |
| IT Hygiene        | #/overview?tab=sca&redirectPolicy=${lastScan.policy_id}                    | /app/configuration-assessment#/overview/?tab=sca&redirectPolicy=${lastScan.policy_id} | plugins/main/public/components/common/welcome/components/sca_scan/sca_scan.tsx                     |                          |
| IT Hygiene        | #/overview?tab=sca                                                         | /app/configuration-assessment                                                         | plugins/main/public/components/common/welcome/components/sca_scan/sca_scan.tsx                     |                          |
| Groups            | #/agents (with selected agent)                                             | /app/it-hygiene#/agents/                                                                          | Use share agents service                                                                           |                          |
| {old_modules}     | #/agents?tab=welcome&agent={agentID}                                       | /app/it-hygiene#/agents?tab=welcome&agent={agentID}                                    | plugins/main/public/components/common/modules/events-enhance-discover-fields.ts                    | agent.id enhanced cell   |
| {old_modules}     | #/agents?tab=welcome&agent={agentID}                                       | /app/it-hygiene#/agents?tab=welcome&agent={agentID}                                    | plugins/main/public/components/common/modules/events-enhance-discover-fields.ts                    | agent.name enhanced cell |
| {old_modules}     | #/manager/rules?tab=rules&redirectRule={ruleID}                            | /app/rules#/manager/rules?tab=rules&redirectRule={ruleID}                                      | plugins/main/public/components/common/modules/events-enhance-discover-fields.ts                    |                          |
| {old_modules}     | #/settings?tab=sample_data                                                 | /app/server-data                                                                               |                                                                                                    |                          |
| IT Hygiene        |                                                                            |                                                                                                   |                                                                                                    |                          |
| Docker            | #/manager/rules?tab=rules&redirectRule={ruleID}                            | /app/rules#/manager/rules?tab=rules&redirectRule={ruleID}                                      | plugins/main/public/components/common/modules/events-enhance-discover-fields.ts                    |                          |
| Groups            | #/agents?_g=(filters:                                        | /app/endpoints-summary#/agents?agent=**param**&_g=(filters:                                    | plugins/main/public/controllers/management/components/management/groups/group-agents-table.js      |                          |
| Rules             | #/overview?tab=general&tabView=panels&addRuleFilter=**param** | /app/threat-hunting#/overview?tab=general&tabView=panels&addRuleFilter=**param**              | plugins/main/public/controllers/management/components/management/ruleset/views/rule-info.tsx       |                          |
| Cluster           | #/agents-preview/?                              | /app/endpoints-summary#/agents-preview/?                                         | plugins/main/public/controllers/management/monitoring.js                                           |                          |
| Statistics        | #/settings?tab=configuration&category=statistics         | /app/wazuh-plugin-settings#/settings?tab=configuration&category=statistics                             | plugins/main/public/controllers/management/components/management/statistics/statistics-overview.js |                          |

## Health check redirections

When the health check is run, it should redirect to the expected view, but it does not do.

## Page is reloaded when accessing to a Wazuh application

The current monolith reloads the page when this is accessed, if the cookies service is not started or the previous history entry was pushed. We should avoid, the page will be refreshed. Removing this reload displays an error that we should research.

**Comment by JuanGarriuz** [comment]
Inside plugins/main/common/wazuh-modules.ts we add "appId" to fix redirection in the agents page. But some sections inside monolithic aren't not found in the new menu. I link it to IT Hygiene section. 

![image](https://github.com/wazuh/wazuh-kibana-app/assets/124377319/f9949881-f227-48da-9fd3-e57ab415b314)

**Comment by JuanGarriuz** [comment]
Inside plugins/main/common/wazuh-modules.ts we found "testConfiguration" section. We should research if that code is vulnerable to deletion.

![image](https://github.com/wazuh/wazuh-kibana-app/assets/124377319/6388a05e-f12f-4fab-9f5f-4eaa0243b534)

**Comment by Desvelao** [comment]
# Problem

The IT Hygiene application displays data about an agent. The current view doesn't support accessing without a selected agent, so it should be enhanced.

- Without an agent being selected, the user can not select it.
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/802fec91-894e-430c-bf98-127be8690371)
- With a selected agent, the user should be able to change the selected agent. Currently, the view doesn't have this button.

## Digging

I was researching to add a way to select the agent, and there are multiple problems to solve.
- If access to the section and the agent is not stored in the shareAgent singleton, then a message is displayed. This view is managed by AngularJS.
- In the current application we have a way to select the agent through a modal. This modal is done in ReactJS. This means if we want the user can use this selector, we should think of a way to render this component:
  - Remove the rendering with AngularJS and allow to rendering of the existing ReactJS component that displays the agent data. Then we could wrap this component with the prompt component of no selected agent.
  - Add to the AngularJS template the rendering of the prompt component of no selected agent.
  
I was working on one of these approaches and I got more problems:
- There are 2 ways for the modal to select the agent that can be opened. One of them is global and the other one is local when rendering a current module. The current agent selector component is related to the module. The agent view doesn't render this logic, so the button to open the agent modal selector doesn't cause the modal to be opened.
- The selected agent in this section is managed for a variable in the controller scope, but selecting one in the agent selector will change the value in the Redux store, so the view doesn't know you selected an agent.

**Screenshot**
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/f2ae35a8-1a9c-4b75-a62a-67e56228d50d)
> I could add the agent selector, but there are more problems to solve

**Comment by AlexRuiz7** [comment]
I would not prefix every route with `wz-`

**Comment by Desvelao** [comment]
> I would not prefix every route with `wz-`

We will remove the `wz-` prefix from the application URLs.

This was initially done to minimize the conflicts with other applications.

**Comment by Desvelao** [comment]
> > I would not prefix every route with `wz-`
> 
> We will remove the `wz-` prefix from the application URLs.
> 
> * Update related pull request
> * Update comment: [Generate new routes for the apps #5820 (comment)](https://github.com/wazuh/wazuh-kibana-app/issues/5820#issue-1869277343)
> 
> This was initially done to minimize the conflicts with other applications.

I found a problem due to a conflict ID in the `status` application (current Management > Status). It prevents the application can be registered, so I changed the ID to `server-status`. This ID will be displayed in the URL.

**Comment by yenienserrano** [comment]
Some problems have been found,
1- When you change application quickly, sometimes it gives you an error in the console and shows you the previous view to the currently selected one.

![image](https://github.com/wazuh/wazuh-kibana-app/assets/63758389/ed7d479c-4799-4288-ac66-9b3eda83bdff)

2- Sometimes when you want to enter to some module it always redirects you to the Endpoints summary.

![image](https://github.com/wazuh/wazuh-kibana-app/assets/63758389/434782f6-9a35-4bd1-a3cf-c4592a6bf5f9)

3- Problems with the tabView in the url, in the views you should change the value but then returns to the previous value.

![image](https://github.com/wazuh/wazuh-kibana-app/assets/63758389/27a59e3e-1290-487d-8729-4eaca8da8b1b)

![image](https://github.com/wazuh/wazuh-kibana-app/assets/63758389/6f1981a9-8189-49e4-8f63-3fee14b621eb)

**Comment by Desvelao** [comment]
> Some problems have been found,
> 1- When you change application quickly, sometimes it gives you an error in the console and shows you the previous view to the currently selected one.
> 
> <details><summary>screenshot</summary>
> 
> ![image](https://github.com/wazuh/wazuh-kibana-app/assets/63758389/ed7d479c-4799-4288-ac66-9b3eda83bdff)
> 
> </details> 
> 
> 
> 
> 2- Sometimes when you want to enter to some module it always redirects you to the Endpoints summary.
> <details><summary>screenshot</summary>
> 
> ![image](https://github.com/wazuh/wazuh-kibana-app/assets/63758389/434782f6-9a35-4bd1-a3cf-c4592a6bf5f9)
> 
> </details> 
> 
> 
> 3- Problems with the tabView in the url, in the views you should change the value but then returns to the previous value.
> <details><summary>screenshot</summary>
> 
> ![image](https://github.com/wazuh/wazuh-kibana-app/assets/63758389/27a59e3e-1290-487d-8729-4eaca8da8b1b)
> 
> ![image](https://github.com/wazuh/wazuh-kibana-app/assets/63758389/6f1981a9-8189-49e4-8f63-3fee14b621eb)
> 
> </details> 
> 
> 
> Problem 1 and 2 may be related because it occurs when you click twice in a row on the endpoint summary and then want to go to another module, or click twice in a row on a module and navigate to the endpoint summary.
> 

It was moved to https://github.com/wazuh/wazuh-kibana-app/issues/5900.
