### ISSUE TITLE
Import Nessus report into vulnerabilities

### ISSUE THREAD

**Issue by spartantri** [wazuh/wazuh-kibana-app#584]
Hi,

How can I get the fields required to create entries in Wazuh so I can populate it with Nessus report results and make it compatible with current visualizations?

**Comment by jesusgn90** [comment]
Hello @spartantri unfortunately we haven't an integration with Nessus and it's not in our roadmap, any case the team will discuss about this software which could enrichs our stack. Also it implies modifications at different levels from the Wazuh manager to the Wazuh app. Maybe further packages have an integration.

I'm going to close the issue but don't hesitate to open as many issues as you need @spartantri your feedback is always welcome!

Regards,
Jesús

**Comment by spartantri** [comment]
Hi Jesus, maybe you can consider at least consuming nessus csv reports from local file system to feed the vulnerability dashboards :)

**Comment by jesusgn90** [comment]
Hi @spartantri , the team will take a second look into this, I'm going to reopen this issue and let you know in few days.

Regards,
Jesús

**Comment by jesusgn90** [comment]
Hello again @spartantri , after discussing about your suggestion with the core team, this is mostly a feature request with no release date. My suggestion at this point is to open a issue in https://github.com/wazuh/wazuh/issues and give a deep explanation about your desired feature. Also any log data, example report, etc could be useful for the team. Thanks in advance.

Regards,
Jesús
