### ISSUE TITLE
Error: 3034 - Request failed with status code 400 (Cannot export Windows registry)

### ISSUE THREAD

**Issue by thony4uu** [wazuh/wazuh-kibana-app#5845]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.5.1 | 00 | Chrome, Firefox, Safari, etc |

**Description**
Hi team

When I try to export the Windows registry inventory from the FIM module on an agent dashboard, I get the below error message 

Error: 3034 - Request failed with status code 400
    at createError (https://192.168.X.X/45103/bundles/plugin/wazuh/wazuh.plugin.js:2:28658)
    at settle (https://192.168.X.X/45103/bundles/plugin/wazuh/wazuh.plugin.js:8:19613)
    at XMLHttpRequest.onloadend (https://192.168.71.172/45103/bundles/plugin/wazuh/wazuh.plugin.js:2:26451)

**Steps to reproduce**
1. Navigate to agent -> Integrity monitoring -> Inventory -> Windows Registry -> 
2. Click on Export formatted

**Screenshots**
![image](https://github.com/wazuh/wazuh-kibana-app/assets/108103499/9e707f14-b8d8-47b1-93ff-eb4440a94e0f)

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by Tostti** [comment]
This issue is solved in `4,6,0` with the [New search bar component](https://github.com/wazuh/wazuh-kibana-app/issues/4312)

**Comment by gdiazlo** [comment]
I'll close this, please reopen it for further inquiries related to this problem.
