### ISSUE TITLE
Release 4.6.0 - Alpha 1 - Wazuh UI regression testing

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#5862]
The following issue aims to run manual tests for the current release candidate, report the results, and open new issues for any encountered errors.

## Wazuh UI tests information
|                                        |                                             |
|----------------------------------------|---------------------------------------------|
| **Main release candidate issue**       | https://github.com/wazuh/wazuh/issues/18858 |
| **Version**                            | 4.6.0                                       |
| **Release candidate #**                | Alpha 1                                     |
| **Tag**                                | v4.6.0-alpha1                               |
| **Previous UI regression tests issue** | -                                           |

## Test report procedure

**TL;DR**
   1. The specified tests will be executed in every platform and version mentioned in this issue.
   1. Include evidence of each test performed.
   1. Report any problem or bug. Open a new issue for each of them and link them here.
   1. Justify skipped tests.

All test results must have one of the following statuses: 
|                 |                                                                      |
|-----------------|----------------------------------------------------------------------|
| :black_circle:  | The test hasn't started yet.                                         |
| :green_circle:  | All checks passed.                                                   |
| :red_circle:    | There is at least one failed check.                                  |
| :yellow_circle: | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause.
It must be included in the `Problems` section of the current release candidate issue.

Any expected fail or skipped test must be justified with a reason. 
All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a zip, txt or images. 
This report can be used by the auditors to dig deeper into any possible failures and details.

## Test template

| Test | Chrome         | Firefox        | Safari         |
|------|----------------|----------------|----------------|
| -    | :black_circle: | :black_circle: | :black_circle: |

## Test plan

1. Verify the app package installs and operates as expected.
2. #4312
3. #4205
4. #5233
5. #5040
6. #4145
7. #5310
8. #4628
9. #5376
10. #4772
11. #5520 

## Conclusions

| Status         | Platform                       |
|----------------|--------------------------------|
| :red_circle: | Wazuh dashboards v4.6.0-alpha1 |

### Failed checks

- [x] #5865
- [x] #5866
- [ ] #5867
- [x] #5868
- [x] #5880
- [x] #5883 

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @davidjiglesias 
- [x] @wazuh/frontend

**Comment by AlexRuiz7** [comment]
### Tests results

| Test                                                      | Chrome         | Firefox        | Safari         |
|-----------------------------------------------------------|----------------|----------------|----------------|
| Verify the app package installs and operates as expected. | :green_circle: | :black_circle: | :black_circle: |


| Test                                                      | Chrome         | Firefox        | Safari         |
|-----------------------------------------------------------|----------------|----------------|----------------|
| New search bar component | :black_circle: | :black_circle: | :black_circle: |


| Test                                                      | Chrome         | Firefox        | Safari         |
|-----------------------------------------------------------|----------------|----------------|----------------|
| Redesign of add agent page | :black_circle: | :black_circle: | :black_circle: |


| Test                                                      | Chrome         | Firefox        | Safari         |
|-----------------------------------------------------------|----------------|----------------|----------------|
| Improvements of the Wazuh API usage | :black_circle: | :black_circle: | :black_circle: |

**Comment by Desvelao** [comment]
LGTM!

**Comment by davidjiglesias** [comment]
LGTM!
