### ISSUE TITLE
Screenshots of the wizard in the documentation are outdated

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#5866]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.6.0-alpha1 | 01 | All |

## Description

The `Deploy new agent` section has been redesigned for 4.6.0, but the screenshots in the documentation have not been updated.

We need to update these screenshots. 

https://documentation-dev.wazuh.com/v4.6.0-alpha1/installation-guide/wazuh-agent/index.html

**Comment by Desvelao** [comment]
Pull request: https://github.com/wazuh/wazuh-documentation/pull/6481
