### ISSUE TITLE
The documentation link for WQL is not working

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#5867]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.6.0-alpha1 | 01 | All |

## Description

The documentation link for the WQL language in the search bar component is broken.

It points to the tag v4.6.0, but we use a two term tag, composed by Wazuh's and OpenSearch's version: v4.6.0-2.6.0

![image](https://github.com/wazuh/wazuh-kibana-app/assets/15186973/75a5773d-5232-420e-8ada-cb94d2ca5da3)

### Options

- Change the tag pattern to a single term.
- Change the link to the correct tag
- Move the documentation to the documentation page (preferred)

**Comment by Desvelao** [comment]
I created a new page in the documentation on this pull request: https://github.com/wazuh/wazuh-documentation/pull/6500
