### ISSUE TITLE
Configured indices are not found: `[.opendistro-alerting-config]` in Demo environment

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-kibana-app#5869]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.6.0 | 46000 | Brave/Firefox |

**Description**

The following error has been found in the browser console indicating a problem with the `.opendistro-alerting-config` index

```
error getting monitors: 
{ok: false, resp: '[alerting_exception] Configured indices are not found: [.opendistro-alerting-config]'}
  ok: false
  resp:  "[alerting_exception] Configured indices are not found: [.opendistro-alerting-config]"
  [[Prototype]]: Object
```

**Preconditions**
1. --

**Steps to reproduce**
1. Open Side Panel
2. Click on Alerting

**Expected Result**
1.  No abnormal changes in WUI are observed

**Actual Result**
1.  No abnormal changes in WUI are observed

**Screenshots**

![image](https://github.com/wazuh/wazuh-kibana-app/assets/14913942/67f470a2-0939-48cc-b505-48c8354a8f47)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/14913942/1d1559c0-3b51-4f55-959a-f3f3af362455)

**Comment by gdiazlo** [comment]
This comes from the upstream platform. We will close it as this component is being worked on by them. We cannot modify this behavior without forking the plugin.
