### ISSUE TITLE
[Register agent] Wrong installation command aarch64 architectures

### ISSUE THREAD

**Issue by Machi3mfl** [wazuh/wazuh-kibana-app#5870]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.6.0 | alpha1 | Chrome, Firefox, Safari, etc |

**Description**
Wrong package URL in one-line installation command for aarch64 architectures.

**Screenshots**

## Linux - DEB aarch64 

![image](https://github.com/wazuh/wazuh-kibana-app/assets/6089438/8736cb24-e551-4bd7-8f12-49a2a791aede)

![image](https://github.com/wazuh/wazuh-kibana-app/assets/6089438/4d959159-c737-47b8-9acf-f85df9add8e3)

### Expected

```bash
wget https://packages-dev.wazuh.com/pre-release/apt/pool/main/w/wazuh-agent/wazuh-agent_4.6.0-1_arm64.deb && sudo WAZUH_MANAGER='192.168.0.45' dpkg -i ./wazuh-agent_4.6.0-1_arm64.deb
```

## Linux - RPM aarch64 

![image](https://github.com/wazuh/wazuh-kibana-app/assets/6089438/b1e7c12f-6170-404a-a634-38d82e51dd09)

![image](https://github.com/wazuh/wazuh-kibana-app/assets/6089438/d645b5a1-302d-4144-805d-3d62277c3b3b)

### Expected

```bash
curl -o wazuh-agent-4.6.0-1.x86_64.rpm https://packages-dev.wazuh.com/pre-release/yum/wazuh-agent-4.6.0-1.aarch64.rpm && sudo WAZUH_MANAGER='192.168.0.45' rpm -ihv wazuh-agent-4.6.0-1.aarch64.rpm
```

**Comment by Tostti** [comment]
PR merged
