### ISSUE TITLE
Pop-up appears always even if I refresh (The index pattern was refreshed ...)

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-kibana-app#5872]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.6.0 | 40600 | Edge |

**Description**

Every time I access the Security Events view the pop-up appears even if I refresh the page as the message suggests.

**Screenshots**

https://github.com/wazuh/wazuh-kibana-app/assets/39094716/929c9d24-8cef-4804-a0bd-2f03344ab0ee

**Comment by gdiazlo** [comment]
We believe this happens because we do not have the appropriate mappings for these fields. We're going to open a new issue to solve the mappings issue and will test this again when that's done.
