### ISSUE TITLE
Compatibility with Elastic 7.17.13

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#5874]
## Description
We need to ensure the UI compatibility with the next version of Elastic v7.17.13.
This update is still being discussed, but we need to be aware of potential issues.

For that, we need to:

- [x] Review Elastic and Kibana latest stable changelog. 
- [x] Identify improvements and potential impact on the UI.
- [x] Develop a testing environment to verify our components would work under this new build.
- [x] Update official [documentation](https://github.com/wazuh/wazuh-documentation/issues)
  - [x] https://github.com/wazuh/wazuh-documentation/issues/6530

## Issues

- **Node** version was **bumped** to `18.17.1`. We did the same in our project.
- `eslint-plugin-filenames-simple` was bumped from `0.7.0` to `0.8.0` due to the new Node version.
-  Unit tests were failing due to:
  ```js
  ● Validation Error:
  
    Module jest-raw-loader in the transform option was not found.
           <rootDir> is: /home/node/kbn/plugins/wazuh
  ```

Caused by using the version `7.17.13` in the `package.json`. `jest-raw-loader` dependency is missing. We reverted the change to use `7.16.0` just for development/testing.

**Comment by AlexRuiz7** [comment]
Docker image uploaded to quay.io

**Comment by JuanGarriuz** [comment]
### Elasticsearch version 7.17.13

[Release Notes](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/es-release-notes.html)


Regarding the Elasticsearch update, some enhancements like the regex performance. 

### Kibana 7.17.13

[Release Notes](https://www.elastic.co/guide/en/kibana/7.17/release-notes.html)

For Kibana, they fixed bugs related to editing an ML rule in Uptime.

**Comment by JuanGarriuz** [comment]
### Docker File Changes

Node version has changed

![image](https://github.com/wazuh/wazuh-kibana-app/assets/124377319/f25f0034-c82e-4690-95d4-f28a0b761524)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/124377319/7c6acf57-4d90-4dfa-9c49-ae1d5e77da3f)

**Comment by JuanGarriuz** [comment]
![image](https://github.com/wazuh/wazuh-kibana-app/assets/124377319/301bb17e-d930-4c8b-8fa3-6957e66df87a)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/124377319/98d2f62f-fc80-49b0-af20-51b4f81172a9)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/124377319/26f46606-2ab8-4dcb-b874-131b08dfa7d8)

**Comment by JuanGarriuz** [comment]
Documentation team issue => https://github.com/wazuh/wazuh-documentation/issues/6530
