### ISSUE TITLE
[Register Agent] Wrong macos installation command - 4.6.0

### ISSUE THREAD

**Issue by Machi3mfl** [wazuh/wazuh-kibana-app#5886]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.6.0 | alpha1 | Chrome, Firefox, Safari, etc |

**Description**

Fix the installation command line in the register new agent page.

<img width="883" alt="Captura de pantalla 2023-09-12 a la(s) 11 50 03" src="https://github.com/wazuh/wazuh-kibana-app/assets/6089438/bb671d96-213f-4924-8cbc-a5ff53cb7abf">

### Steps:

1. Go to Agents section
2. Click `Deploy new agent` button
3. Select macOS operting system and complete the form
4. Check the installation and start commands

### Current solution

```bash
curl -so wazuh-agent.pkg https://packages.wazuh.com/4.x/macos/wazuh-agent-4.6.0-1.[intel64|arm64].pkg && echo -e "WAZUH_MANAGER='0.0.0.0'\nWAZUH_AGENT_NAME='agent-name'\n" > /tmp/wazuh_envs && sudo installer -pkg ./wazuh-agent.pkg -target /
```

### Expected

```bash
curl -so wazuh-agent.pkg https://packages.wazuh.com/4.x/macos/wazuh-agent-4.6.0-1.intel64.pkg && echo "WAZUH_MANAGER='0.0.0.0' && WAZUH_AGENT_NAME='agent-name'" > /tmp/wazuh_envs && sudo installer -pkg ./wazuh-agent.pkg -target /
```

### Related research/tests:

- https://github.com/wazuh/wazuh-packages/issues/2205#issuecomment-1560013292
- https://github.com/wazuh/wazuh/pull/17195#issuecomment-1560044584
- https://github.com/wazuh/wazuh-kibana-app/issues/5466#issuecomment-1559922195

**Comment by Machi3mfl** [comment]
### macOS installation commands are correct in 4.5.2 release

<img width="955" alt="Screenshot 2023-09-12 at 16 21 47" src="https://github.com/wazuh/wazuh-kibana-app/assets/6089438/49038a5e-fb16-46f0-9bb2-a0cd14c05388">

<img width="973" alt="Screenshot 2023-09-12 at 16 23 01" src="https://github.com/wazuh/wazuh-kibana-app/assets/6089438/311511fe-8762-4807-abb4-12df1590f6a9">


<img width="958" alt="Screenshot 2023-09-12 at 16 23 22" src="https://github.com/wazuh/wazuh-kibana-app/assets/6089438/2a25769d-34bb-4c36-b8e8-a512b71caca8">

<img width="976" alt="Screenshot 2023-09-12 at 16 23 36" src="https://github.com/wazuh/wazuh-kibana-app/assets/6089438/7be8558c-4d94-42e7-a910-a861732c93d6">

### Changes applied

- https://github.com/wazuh/wazuh-kibana-app/pull/5487

**Comment by Tostti** [comment]
Fix merged
