### ISSUE TITLE
Add support for ELK 6.3.x

### ISSUE THREAD

**Issue by minorOffense** [wazuh/wazuh-kibana-app#589]
New release of ELK stack came out. Wondering what the plans are for supporting it.

**Comment by havidarou** [comment]
Hi @minorOffense ,

we hope to have it ready in a few days.

Already been adapted, we are testing it.

Regards!

**Comment by minorOffense** [comment]
Sweet thanks. I'll close this up then.

**Comment by JuanjiJG** [comment]
Hello @minorOffense,

We released a new version of the Wazuh app compatible with Elastic v6.3.0. You can read our [upgrading guide](https://documentation.wazuh.com/current/installation-guide/upgrading/latest_wazuh3_minor.html) to get it installed.

Take a look into our [changelog](https://github.com/wazuh/wazuh-kibana-app/blob/master/CHANGELOG.md) file to learn about the latest featured added into the app.

Regards,
Juanjo
