### ISSUE TITLE
Kibana front-end unusually slow

### ISSUE THREAD

**Issue by phillycheeze** [wazuh/wazuh-kibana-app#59]
After setting up a pretty basic kibana app, I've noticed that the UI is especially slow for the Wazuh App. This issue doesn't happen in Kibana when via the Discover tab (or others).

I added a screenshot below, showing that it hangs on loading a favicon for about 20 seconds. I thought it might be a network issue, but I haven't been able to track down the root cause.

![image](https://user-images.githubusercontent.com/6655673/32628745-7b62c358-c55c-11e7-955d-c950cab0fb89.png)

**Comment by havidarou** [comment]
Hi @phillycheeze ,

we'll look into this.

What is the Kibana and Wazuh app version?

Regards.

**Comment by phillycheeze** [comment]
Kibana & Elasticsearch 5.6.0 

I am going to try and do some more digging today. I can tell you that even when that request is waiting, the CPU on the server doesn't spike at all (staying under 8% utilization). I'll test with other browsers and report back.

**Comment by phillycheeze** [comment]
I have uploaded a chrome profile here: [Chrome Profile](https://drive.google.com/file/d/104I32g37Sa0D5nGrg6sQSods1V4Uyymn/view?usp=sharing)

I'm not exactly sure how to debug this, but hopefully someone with more experience can deduce the bottleneck from importing this profile into Chrome.

**Comment by havidarou** [comment]
Hi @phillycheeze thanks for the report.

At first glance it seems a petition Kibana is doing, either on the Wazuh app plugin's behalf or its own behalf.

I'll look into it.

Thanks again.

Regards.

**Comment by JuanjiJG** [comment]
It's been more than a month since the last response to this issue, so we proceed to close it.

Regards.
