### ISSUE TITLE
Modify app logic to show content on the interface

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#595]
Hello team,

The app has a weird logic on some tables to show the different values and configurations. For example, we have a lot of `ng-if` statements on Rule/Decoder detail view to show the information regarding if it's on the API response.

That said, we should use iteration on some interface sections to just show the contents, regardless of the amount and/or name of them.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
Moved to https://github.com/wazuh/wazuh-kibana-app/issues/1050
