### ISSUE TITLE
Error ocurred in Delayed API Request on Demo Enviroment

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-kibana-app#5958]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.6.0 | Beta 1 | Chrome, Firefox, Safari, etc |

**Description**
During testing of Release 4.6.0 Beta 1 https://github.com/wazuh/wazuh/issues/19157, an error message was detected in the dashboard's `wazuhapp.log`.

```
#egrep -i "err|warn" /usr/share/wazuh-dashboard/data/wazuh/logs/wazuhapp.log
{"date":"2023-09-28T12:26:15.066Z","level":"error","location":"queue:delayApiRequest","message":"An error ocurred in the delayed request: \"DELETE /security/user/authenticate\": Request failed with status code 401"}
```

More research is needed to determine the cause and impact.

**Comment by gdiazlo** [comment]
That error happens if you execute the action (delete) and the token expires before it is executed. The API returns a 401 unauthorized. It looks like it is working as designed.
