### ISSUE TITLE
Automation of Sysmon 

### ISSUE THREAD

**Issue by guilhermebasalia** [wazuh/wazuh-kibana-app#607]
Good evening gentlemen,
The Sysmon tool of Windows, get logs of extreme importance, it would be very interesting to have let it default in Windows agent and with dashboards in kibana, 
I await the return. 
Thank you

**Comment by JuanjiJG** [comment]
Hello @guilhermebasalia,

Thanks for your suggestion! Currently, we don't have that feature in our roadmap, but we will research about it, and maybe in the future we'll consider developing it.

For now, I strongly recommend you to go to our [Wazuh core repository](https://github.com/wazuh/wazuh/issues) and open an issue there, describing what you would like to see on the Wazuh agents using this tool.

The team will provide you better support and information on the approppriate repository. For now, I'll proceed to close this issue, but don't hesitate to open an issue here if you have questions or problems about the Wazuh app. 😃

Regards,
Juanjo
