### ISSUE TITLE
Where is the selected fields save button in Wazuh kibana app ?

### ISSUE THREAD

**Issue by gagantous** [wazuh/wazuh-kibana-app#617]
Hi Team.

I have a question about kibana app. Where could i save my own custom fields like in kibana dashboard ? seems like i couldnt find any in wazuh kibana app

Kibana dashboard

![kibana dashboard](https://user-images.githubusercontent.com/24579576/41883819-115feffa-7923-11e8-8fde-2a18af393af9.JPG)

Wazuh Kibana Dashboard 

![wazuh kibana dashboard](https://user-images.githubusercontent.com/24579576/41883832-18ff10ec-7923-11e8-9ea0-64ebb4225b1d.JPG)

Thanks in advance

**Comment by JuanjiJG** [comment]
Hello @gagantous,

Currently, the Wazuh app is not capable of manage saved searches just like Kibana's Discover tab. Maybe we could add this feature in the future, but it's not on our roadmap at this moment.

For now, you can use Kibana's discover tab to save your own searches. Sorry for the inconveniences.

Regards,
Juanjo
