### ISSUE TITLE
The "wazuhapp.log" file is not created the very first time after starting the Kibana service

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#618]
Hello team,

I've noticed that the very first time we start the Kibana service after installing the app (`systemctl enable/start kibana`) the `wazuhapp.log` file is not created. We have to restart the Kibana service in order to finally create it.

This is due to module initialization times when we start Kibana, and it's not an error _per se_, but it could be interesting to get the file created at the beginning.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
Done here https://github.com/wazuh/wazuh-kibana-app/pull/667
