### ISSUE TITLE
Several improvements for new tables

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#621]
Hello team,

The new table directive works much better than the previous one, but we can still improve it a little bit with some tweaks:

- Make the current page "active" with a different colour or maybe a background colour.
- Disable the "Next" or "Prev" buttons if there's no more pagination before or after the current page.
- Make all the pages appear if we have only 2 for example (see attached screenshot).
![groups content](https://user-images.githubusercontent.com/10928321/41918601-fbc66860-795c-11e8-8c3b-18a091d173f9.PNG)
Regards,
Juanjo

**Comment by jesusgn90** [comment]
Done here https://github.com/wazuh/wazuh-kibana-app/pull/627
