### ISSUE TITLE
Plans for Kibana 6?

### ISSUE THREAD

**Issue by jamesspi** [wazuh/wazuh-kibana-app#63]
Hi All,

Just wondering what the plans are for kibana and elastic version 6?

Thanks!
James

**Comment by havidarou** [comment]
Hi @jamesspi,

We are (and have been) hard working on it.

It will be released hopefully very soon.

Regards.

**Comment by jamesspi** [comment]
Brilliant! Thanks for the quick response @havidarou !

**Comment by sumeshms** [comment]
Excellent waiting for that!

**Comment by JuanjiJG** [comment]
Hi everyone!

We've just released Wazuh 3.0 and the new version of the Wazuh Kibana App.
You can get more information on the documentation: https://documentation.wazuh.com/3.x/index.html

From the documentation, or the app repository you can get the new packages for the app: https://github.com/wazuh/wazuh-kibana-app#installation

Thank you so much for your patience and I hope you enjoy this brand-new release of Wazuh.

Best regards,
Juanjo

**Comment by jamesspi** [comment]
Fantastic! Thanks!
