### ISSUE TITLE
Avoid showing Inventory interface if the agent doesn't have it enabled

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#631]
Hello team,

Currently, the Welcome tab doesn't show the Inventory card if the agent doesn't have `syscollector` enabled, but you can see that tab if you use the autocomplete bar from an agent with Inventory enabled.

We have to add a condition to show a warning card if you open the Inventory tab on an agent without `syscollector`.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
Done https://github.com/wazuh/wazuh-kibana-app/pull/744
