### ISSUE TITLE
Improve app routing

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#648]
Hello team,

Currently, we use a method to switch the tab in the app. This method usually changes a variable that is used as an URL parameter on the browser search bar. Using this method, we can't use the <kbd>Back</kbd> and <kbd>Forward</kbd> browser buttons, because it only changes the URL parameter, without any actual change on the currently viewed tab.

AngularJS provides a routing system that currently we're using, but not completely. If we use `/manager/monitoring`, it will load the Monitoring tab, but the route won't change if we use the in-app buttons.

A good improvement for this is using properly the AngularJS routing system. It is known that we have to be careful with the tab switching on critical tabs such as Overview and Agents, due to the visualizations, and also we should take care of the navigation experience to make it feel more seamless and more like a SPA (single page application).

Any comments or thoughts about this would be really appreciated.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
Currently it is not possible to change the routing system. We can study it for future releases but not right now so at the moment it is cancelled.

Regards
