### ISSUE TITLE
Password field on edit API form not cleared after submitting

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#653]
Hello team,

The first time we open the Edit API form, the password field is empty, but when we edit an API entry and open again any form on any of our inserted APIs, the password field is filled.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
https://github.com/wazuh/wazuh-kibana-app/commit/2611eb4cc244b31627a08abc848a29929bad3f90
