### ISSUE TITLE
Add WhoData to the app

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#657]
Hello team,

We have to add the WhoData functionality to the app, analyze the new fields on the alerts, UI changes, etc.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
Known fields added in https://github.com/wazuh/wazuh-kibana-app/pull/746

**Comment by jesusgn90** [comment]
Included in https://github.com/wazuh/wazuh-kibana-app/issues/856, closing.
