### ISSUE TITLE
Normalize naming convention

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#660]
Hello team, we must normalize our naming convention. This means we can't have files with different name pattern. Also it means we must declare variables using always the same convention and so on.

Regards,
Jesús

**Comment by JuanjiJG** [comment]
This issue also applies to the existing CSS. We should always use the same `wz-*` naming convention for custom CSS classes, especially if we're overriding Angular Material components.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
Moved to https://github.com/wazuh/wazuh-kibana-app/issues/1052
