### ISSUE TITLE
API indicator on the top navbar is not updated when clicking on "Check connection"

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#665]
When changing the manager name (for example, editing the `ossec.conf` file, clicking on the <kbd>Check connection</kbd> button on _Settings > API_ updates the manager name on the API list, but not on the top navbar.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
Done here https://github.com/wazuh/wazuh-kibana-app/pull/668
