### ISSUE TITLE
Agent's Vulnerability section missing in 4.9.0

### ISSUE THREAD

**Issue by Cyber-MKO** [wazuh/wazuh-kibana-app#6972]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0 | Wazuh Dashboard| Manager | Wazuh OVA | Amazon Linux 2 |

The recently released 4.9.0 does not include the vulnerability section when selecting an agent from the agent summary.

Steps to reproduce:

Agents Summary > Select an agent > Navigate the more option; Vulnerability Detection is missing.

See below image;
![image](https://github.com/user-attachments/assets/ea6b73d6-d9b3-4d36-93d5-8b30077635a8)

**Comment by Desvelao** [comment]
Issue transffered to wazuh/wazuh-dashboard-plugins repository.

**Comment by Desvelao** [comment]
I have added the missing `Vulnerabilities detection` link to the agent menu of `Endpoints Summary` application in this pull request https://github.com/wazuh/wazuh-dashboard-plugins/pull/6983
