### ISSUE TITLE
wazuh APP display problem，partial correct partial error ！

### ISSUE THREAD

**Issue by myh0st** [wazuh/wazuh-kibana-app#698]
Policy monitoring about the windows：

![1](https://user-images.githubusercontent.com/26624320/42609587-dbf70e1c-85bf-11e8-8cf3-5b2747c8a078.png)

about wazuh server：

![2](https://user-images.githubusercontent.com/26624320/42609595-e8b7620a-85bf-11e8-8611-89367ed7bf4b.png)

others wazuh agent：

![3](https://user-images.githubusercontent.com/26624320/42609613-f6409356-85bf-11e8-9412-9cc0ed3503c1.png)

What caused this ?

**Comment by jesusgn90** [comment]
Hello @myh0st , I think your problem is same as https://github.com/wazuh/wazuh-kibana-app/issues/697 one more time. It doesn't make sense, I think you have an Elasticsearch problem regarding to the mapping or indexing procedure.

Please paste the output of the following commands to verify a bit your indices:

```
 //  Mapping for the last index (long output, paste entire output)
curl elastic_ip:9200/wazuh-alerts-3.x-2018.07.12/_mapping?pretty

// Wazuh alerts template
curl elastic_ip:9200/_cat/templates/wazuh
```

Please replace `2018.07.12` by your last index date created. You can check the indices as follow:

```
curl elastic_ip:9200/_cat/indices/wazuh-alerts*
```

Regards,
Jesús

**Comment by myh0st** [comment]
//  wazuh-alerts-3.x-2018.07.12/_mapping?pretty

`{
  "wazuh-alerts-3.x-2018.07.12" : {
    "mappings" : {
      "wazuh" : {
        "dynamic_templates" : [
          {
            "string_as_keyword" : {
              "match_mapping_type" : "string",
              "mapping" : {
                "doc_values" : "true",
                "type" : "keyword"
              }
            }
          }
        ],
        "properties" : {
          "@timestamp" : {
            "type" : "date",
            "format" : "dateOptionalTime"
          },
          "@version" : {
            "type" : "text"
          },
          "AlertsFile" : {
            "type" : "keyword"
          },
          "GeoLocation" : {
            "properties" : {
              "area_code" : {
                "type" : "long"
              },
              "city_name" : {
                "type" : "keyword"
              },
              "continent_code" : {
                "type" : "text"
              },
              "coordinates" : {
                "type" : "double"
              },
              "country_code2" : {
                "type" : "text"
              },
              "country_code3" : {
                "type" : "text"
              },
              "country_name" : {
                "type" : "keyword"
              },
              "dma_code" : {
                "type" : "long"
              },
              "ip" : {
                "type" : "keyword"
              },
              "latitude" : {
                "type" : "double"
              },
              "location" : {
                "type" : "geo_point"
              },
              "longitude" : {
                "type" : "double"
              },
              "postal_code" : {
                "type" : "keyword"
              },
              "real_region_name" : {
                "type" : "keyword"
              },
              "region_name" : {
                "type" : "keyword"
              },
              "timezone" : {
                "type" : "text"
              }
            }
          },
          "agent" : {
            "properties" : {
              "id" : {
                "type" : "keyword"
              },
              "ip" : {
                "type" : "keyword"
              },
              "name" : {
                "type" : "keyword"
              }
            }
          },
          "cluster" : {
            "properties" : {
              "name" : {
                "type" : "keyword"
              },
              "node" : {
                "type" : "keyword"
              }
            }
          },
          "command" : {
            "type" : "keyword"
          },
          "data" : {
            "properties" : {
              "action" : {
                "type" : "keyword"
              },
              "audit" : {
                "properties" : {
                  "acct" : {
                    "type" : "keyword"
                  },
                  "auid" : {
                    "type" : "keyword"
                  },
                  "command" : {
                    "type" : "keyword"
                  },
                  "cwd" : {
                    "type" : "keyword"
                  },
                  "dev" : {
                    "type" : "keyword"
                  },
                  "directory" : {
                    "properties" : {
                      "inode" : {
                        "type" : "keyword"
                      },
                      "mode" : {
                        "type" : "keyword"
                      },
                      "name" : {
                        "type" : "keyword"
                      }
                    }
                  },
                  "egid" : {
                    "type" : "keyword"
                  },
                  "enforcing" : {
                    "type" : "keyword"
                  },
                  "euid" : {
                    "type" : "keyword"
                  },
                  "exe" : {
                    "type" : "keyword"
                  },
                  "exit" : {
                    "type" : "keyword"
                  },
                  "file" : {
                    "properties" : {
                      "inode" : {
                        "type" : "keyword"
                      },
                      "mode" : {
                        "type" : "keyword"
                      },
                      "name" : {
                        "type" : "keyword"
                      }
                    }
                  },
                  "fsgid" : {
                    "type" : "keyword"
                  },
                  "fsuid" : {
                    "type" : "keyword"
                  },
                  "gid" : {
                    "type" : "keyword"
                  },
                  "id" : {
                    "type" : "keyword"
                  },
                  "key" : {
                    "type" : "keyword"
                  },
                  "list" : {
                    "type" : "keyword"
                  },
                  "old-auid" : {
                    "type" : "keyword"
                  },
                  "old-ses" : {
                    "type" : "keyword"
                  },
                  "old_enforcing" : {
                    "type" : "keyword"
                  },
                  "old_prom" : {
                    "type" : "keyword"
                  },
                  "op" : {
                    "type" : "keyword"
                  },
                  "pid" : {
                    "type" : "keyword"
                  },
                  "ppid" : {
                    "type" : "keyword"
                  },
                  "prom" : {
                    "type" : "keyword"
                  },
                  "res" : {
                    "type" : "keyword"
                  },
                  "session" : {
                    "type" : "keyword"
                  },
                  "sgid" : {
                    "type" : "keyword"
                  },
                  "srcip" : {
                    "type" : "keyword"
                  },
                  "subj" : {
                    "type" : "keyword"
                  },
                  "success" : {
                    "type" : "keyword"
                  },
                  "suid" : {
                    "type" : "keyword"
                  },
                  "syscall" : {
                    "type" : "keyword"
                  },
                  "tty" : {
                    "type" : "keyword"
                  },
                  "type" : {
                    "type" : "keyword"
                  },
                  "uid" : {
                    "type" : "keyword"
                  }
                }
              },
              "command" : {
                "type" : "keyword"
              },
              "data" : {
                "type" : "keyword"
              },
              "dstip" : {
                "type" : "keyword"
              },
              "dstport" : {
                "type" : "keyword"
              },
              "dstuser" : {
                "type" : "keyword"
              },
              "file" : {
                "type" : "keyword"
              },
              "id" : {
                "type" : "keyword"
              },
              "oscap" : {
                "properties" : {
                  "check" : {
                    "properties" : {
                      "description" : {
                        "type" : "text"
                      },
                      "id" : {
                        "type" : "keyword"
                      },
                      "identifiers" : {
                        "type" : "text"
                      },
                      "oval" : {
                        "properties" : {
                          "id" : {
                            "type" : "keyword"
                          }
                        }
                      },
                      "rationale" : {
                        "type" : "text"
                      },
                      "references" : {
                        "type" : "text"
                      },
                      "result" : {
                        "type" : "keyword"
                      },
                      "severity" : {
                        "type" : "keyword"
                      },
                      "title" : {
                        "type" : "keyword"
                      }
                    }
                  },
                  "scan" : {
                    "properties" : {
                      "benchmark" : {
                        "properties" : {
                          "id" : {
                            "type" : "keyword"
                          }
                        }
                      },
                      "content" : {
                        "type" : "keyword"
                      },
                      "id" : {
                        "type" : "keyword"
                      },
                      "profile" : {
                        "properties" : {
                          "id" : {
                            "type" : "keyword"
                          },
                          "title" : {
                            "type" : "keyword"
                          }
                        }
                      },
                      "return_code" : {
                        "type" : "long"
                      },
                      "score" : {
                        "type" : "double"
                      }
                    }
                  }
                }
              },
              "protocol" : {
                "type" : "keyword"
              },
              "pwd" : {
                "type" : "keyword"
              },
              "srcip" : {
                "type" : "keyword"
              },
              "srcport" : {
                "type" : "keyword"
              },
              "srcuser" : {
                "type" : "keyword"
              },
              "status" : {
                "type" : "keyword"
              },
              "system_name" : {
                "type" : "keyword"
              },
              "title" : {
                "type" : "keyword"
              },
              "tty" : {
                "type" : "keyword"
              },
              "type" : {
                "type" : "keyword"
              },
              "uid" : {
                "type" : "keyword"
              },
              "url" : {
                "type" : "keyword"
              },
              "vulnerability" : {
                "properties" : {
                  "cve" : {
                    "type" : "text",
                    "fielddata" : true
                  },
                  "package" : {
                    "properties" : {
                      "condition" : {
                        "type" : "keyword"
                      },
                      "name" : {
                        "type" : "text",
                        "fielddata" : true
                      },
                      "version" : {
                        "type" : "keyword"
                      }
                    }
                  },
                  "published" : {
                    "type" : "date"
                  },
                  "reference" : {
                    "type" : "text",
                    "fielddata" : true
                  },
                  "severity" : {
                    "type" : "text",
                    "fielddata" : true
                  },
                  "state" : {
                    "type" : "keyword"
                  },
                  "title" : {
                    "type" : "text",
                    "fielddata" : true
                  },
                  "updated" : {
                    "type" : "date"
                  }
                }
              }
            }
          },
          "decoder" : {
            "properties" : {
              "accumulate" : {
                "type" : "long"
              },
              "fts" : {
                "type" : "long"
              },
              "ftscomment" : {
                "type" : "keyword"
              },
              "name" : {
                "type" : "keyword"
              },
              "parent" : {
                "type" : "keyword"
              }
            }
          },
          "full_log" : {
            "type" : "text"
          },
          "host" : {
            "type" : "keyword"
          },
          "id" : {
            "type" : "keyword"
          },
          "location" : {
            "type" : "keyword"
          },
          "manager" : {
            "properties" : {
              "name" : {
                "type" : "keyword"
              }
            }
          },
          "message" : {
            "type" : "text"
          },
          "offset" : {
            "type" : "keyword"
          },
          "predecoder" : {
            "properties" : {
              "hostname" : {
                "type" : "keyword"
              },
              "program_name" : {
                "type" : "keyword"
              },
              "timestamp" : {
                "type" : "keyword"
              }
            }
          },
          "previous_log" : {
            "type" : "text"
          },
          "program_name" : {
            "type" : "keyword"
          },
          "rule" : {
            "properties" : {
              "cis" : {
                "type" : "keyword"
              },
              "cve" : {
                "type" : "keyword"
              },
              "description" : {
                "type" : "keyword"
              },
              "firedtimes" : {
                "type" : "long"
              },
              "frequency" : {
                "type" : "long"
              },
              "gdpr" : {
                "type" : "keyword"
              },
              "gpg13" : {
                "type" : "keyword"
              },
              "groups" : {
                "type" : "keyword"
              },
              "id" : {
                "type" : "keyword"
              },
              "info" : {
                "type" : "keyword"
              },
              "level" : {
                "type" : "long"
              },
              "mail" : {
                "type" : "boolean"
              },
              "pci_dss" : {
                "type" : "keyword"
              }
            }
          },
          "source" : {
            "type" : "keyword"
          },
          "syscheck" : {
            "properties" : {
              "diff" : {
                "type" : "keyword"
              },
              "event" : {
                "type" : "keyword"
              },
              "gid_after" : {
                "type" : "keyword"
              },
              "gid_before" : {
                "type" : "keyword"
              },
              "gname_after" : {
                "type" : "keyword"
              },
              "gname_before" : {
                "type" : "keyword"
              },
              "inode_after" : {
                "type" : "keyword"
              },
              "inode_before" : {
                "type" : "keyword"
              },
              "md5_after" : {
                "type" : "keyword"
              },
              "md5_before" : {
                "type" : "keyword"
              },
              "mtime_after" : {
                "type" : "date",
                "format" : "dateOptionalTime"
              },
              "mtime_before" : {
                "type" : "date",
                "format" : "dateOptionalTime"
              },
              "path" : {
                "type" : "keyword"
              },
              "perm_after" : {
                "type" : "keyword"
              },
              "perm_before" : {
                "type" : "keyword"
              },
              "sha1_after" : {
                "type" : "keyword"
              },
              "sha1_before" : {
                "type" : "keyword"
              },
              "size_after" : {
                "type" : "long"
              },
              "size_before" : {
                "type" : "long"
              },
              "uid_after" : {
                "type" : "keyword"
              },
              "uid_before" : {
                "type" : "keyword"
              },
              "uname_after" : {
                "type" : "keyword"
              },
              "uname_before" : {
                "type" : "keyword"
              }
            }
          },
          "title" : {
            "type" : "keyword"
          },
          "type" : {
            "type" : "text"
          }
        }
      }
    }
  }
}`
// _cat/templates/wazuh

`wazuh [wazuh-alerts-3.x-*] 0 `

//_cat/indices/wazuh-alerts*

·yellow open wazuh-alerts-3.x-2018.07.11 qwSyrfYwQuO3zgB3Amb24Q 5 1 1071 0 1mb 1mb
yellow open wazuh-alerts-3.x-2018.07.12 rNCjo6TISUiWG5Du4Ya0ww 5 1 1268 0 1mb 1mb·

**Comment by myh0st** [comment]
windows:

![1](https://user-images.githubusercontent.com/26624320/42619449-a5497a78-85ea-11e8-995a-fb22a3744a3c.png)

linux:

![2](https://user-images.githubusercontent.com/26624320/42619466-aee57d34-85ea-11e8-882e-229c165dfc26.png)

**Comment by jesusgn90** [comment]
Hello again @myh0st  it looks like your Windows agent is not parsing properly some fields or your Wazuh manager is not doing its job as expected. The team is currently testing it in order to reproduce your situation. By the meantime, can you provide us the next information?

- Version of the next Wazuh agents: "windows_200_2", "windows_200_73"
- Version of the Wazuh manager

Also it would be nice if you provide us the language being used in these machines.

Thanks in advance,
Jesús

**Comment by myh0st** [comment]
wazuh server 3.31 , windows agent: v3.3.1, Chinese version system

**Comment by jesusgn90** [comment]
Ok @myh0st , usually we don't use chinese systems, but the team is currently testing more in deep some features using chinese agent machines. Once we conclude if is agent related error or not I'll let you know. Sorry about the inconveniences.

Regards,
Jesús

**Comment by myh0st** [comment]
I found the problem, it is the problem of the old data, it is a problem for you, thank you.

**Comment by myh0st** [comment]
Vulnerabilities ：

![1](https://user-images.githubusercontent.com/26624320/42622057-0294e972-85f2-11e8-885e-9f1afdbf614a.png)

and：

localhost:5601/app/https

{"statusCode":404,"error":"Not Found","message":"Unknown app https"}

**Comment by jesusgn90** [comment]
Have you upgraded from Wazuh 2.x to Wazuh 3.x? Also, can you change the time filter from Kibana in the top right corner of the screen and set it to "Last 24 hours" to be sure you are using only modern alerts?

Regards

**Comment by myh0st** [comment]
I installed it directly,

![1](https://user-images.githubusercontent.com/26624320/42622830-e40628f2-85f3-11e8-87e0-5da2e6c8c500.png)

I feel like a template problem ：

![2](https://user-images.githubusercontent.com/26624320/42622916-1b098fb0-85f4-11e8-8772-52598b645ca6.png)
