### ISSUE TITLE
Add control to disable checking for updates in the app settings

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-kibana-app#7152]
## Description

We need to add a switch to the App settings view that handles if the checking for updates feature is enabled.

![image](https://github.com/user-attachments/assets/535031c4-59ec-4bbb-b5b3-31e80e86ee68)

## Tasks

- [ ] https://github.com/wazuh/wazuh-dashboard-plugins/pull/7156
- [ ] https://github.com/wazuh/wazuh-documentation/pull/7977

**Comment by Desvelao** [comment]
# Research

Regarding the  `wazuh.updates.disabled` setting definition, it seems this was intentionally added without the ability to configure from UI. A related comment about this requirement can be found in https://github.com/wazuh/wazuh-dashboard/issues/158#issue-2206029437.

**Comment by Desvelao** [comment]
We have decided to add the ability to edit the `wazuh.updates.disabled` setting from UI.
