### ISSUE TITLE
Deprecate use of mapping types

### ISSUE THREAD

**Issue by fuhry** [wazuh/wazuh-kibana-app#724]
ElasticSearch is in the process of [deprecating mapping types](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/removal-of-types.html). Our own production infrastructure is future-proofing this by enforcing a mapping type of `_doc` on all new documents. In our case, this means we cannot save the configuration because the wazuh plugin attempts to add the type "wazuh-configuration" to the configuration documents; ES6 removes support for multiple mapping types on a single doc.

The suggested workaround in Elastic's documentation is to add your own `type` field and filter on that, with the understanding that this really only fits at the application level.

I'm working on a PR to take a stab at implementing this.

Disclaimer: I am fairly new to working with ES at this level, so please correct me if my vocabulary or understanding is wrong.

Off topic: is there an IRC channel or other public realtime chat facility where y'all hang out? `#wazuh` on Freenode seems dead, there's only one other person in there besides me.

**Comment by havidarou** [comment]
Hi @fuhry ,

you shouldn't have that problem as we make sure we are not using more than one document type per index.

Where are you exactly having problems with this?

We can't completely remove types in Wazuh 3.x due to compatibility issues across existent installations.

Best regards.

**Comment by fuhry** [comment]
@havidarou -
Thanks for your reply. We're unable to set up the app or API configuration in a brand new installation of the app on a cluster running ES 6.x and Kibana 6.3.1.

This is a fairly large scale deployment (~3000 agents) with an ELK cluster being used for many different purposes besides just Wazuh. We just finished a very painful migration from ES 2.x up to 6.x, and the lead engineer on that upgrade has asked that great care be taken to avoid introducing anything that could impede compatibility with future upgrades. As such, our default index template is forcing `"_type": "_doc"`.

I think for now, we will work around this by applying a different index template that sets `"_type": "wazuh-configuration"` for the `.wazuh` index, but this is something that will need to be fixed upstream for ES 7.0.

**Comment by havidarou** [comment]
Hi @fuhry ,

sorry for the late response.

It is in our roadmap to completely remove types for ES 7.0, but unfortunately, for now, we can't remove them.

Thanks for your feedback, and don't hesitate to open new issues regarding any problem you face.

Best regards.
