### ISSUE TITLE
Adapt Wazuh 3.5

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-kibana-app#749]
- API checksum changed.
- New data in inventory tab.

**Comment by jesusgn90** [comment]
From my view https://github.com/wazuh/wazuh-kibana-app/pull/752 and https://github.com/wazuh/wazuh-kibana-app/pull/753 are a first approach. Inventory tab needs its own issue and it must be explained out of this issue cause there are some new API calls we can use, we can also enrich our reports, etc.

Regards,
Jesús
