### ISSUE TITLE
OSSEC agent_control shows agent connected but wazuh status is "Never connected"

### ISSUE THREAD

**Issue by jayjayswal** [wazuh/wazuh-kibana-app#756]
Hi Team,

sudo /var/ossec/bin/agent_control -l
Shows agent is active but wazuh app is showing agent is Never connected. Please help.

![screenshot from 2018-07-28 12 26 33](https://user-images.githubusercontent.com/7957956/43354042-6a625a86-9262-11e8-88fe-b6dd92e75926.png)
![screenshot from 2018-07-28 12 26 08](https://user-images.githubusercontent.com/7957956/43354044-6ab354fe-9262-11e8-93c8-74d5e2d775ca.png)

**Comment by jesusgn90** [comment]
Hi @jayjayswal , 

There are different reasons to fall into your situation. Another user described a similar problem here https://github.com/wazuh/wazuh/issues/1014, maybe it's your same situation, we can start by restarting the Wazuh manager and looking its log file: 

```
cat /var/ossec/logs/ossec.log | grep -i -E "(error|warn)"
```

Regards,
Jesús
