### ISSUE TITLE
Wrong filter by path in Ruleset dashboard

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-kibana-app#774]
When clicking on 'path' option after entering on a certain rule view, the applied filter is named as 'File' instead of 'Path':

![image](https://user-images.githubusercontent.com/10210567/43527222-5abd49a0-95a6-11e8-9f63-31aa92cb7dc3.png)

Regards

**Comment by JuanjiJG** [comment]
Fixed here: https://github.com/wazuh/wazuh-kibana-app/commit/6226b0c7b1bbf127d5542ebfd9254ad7597d0f53

Thanks @manuasir for your report!

Regards,
Juanjo
