### ISSUE TITLE
Dev-tools throws error when the first line is a comment

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#776]
This error happens when the user leaves the Dev tools tab with a comment on the first line.

I think this is caused by the fact that the tab will always execute the first line when the user opens the app, and if it's a comment, it won't work.

![devtools](https://user-images.githubusercontent.com/10928321/43717960-743a1db8-9989-11e8-94e7-41629a88a564.png)

Regards,
Juanjo

**Comment by jesusgn90** [comment]
Done https://github.com/wazuh/wazuh-kibana-app/pull/790
