### ISSUE TITLE
Unpredictable JSON parse error when loading the app

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#778]
Hi team,

We have a weird JSON parse error, but still, we can't find the exact steps to reproduce it.

![bug](https://user-images.githubusercontent.com/10928321/43883200-a839e5fa-9bb2-11e8-829e-c0a17e28a812.png)

It happened once on the environment, but the next time we opened the app, the error won't appear anymore.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
The PR https://github.com/wazuh/wazuh-kibana-app/pull/806 tries to catch affected JSON.parse statements.
