### ISSUE TITLE
Sort all app filters alphabetically

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#784]
We need to update all the app filters to sort the items alphabetically.

### Currently defined tasks:
- [x] Update index patterns lists.
- [x] Update daemons filter list on Management > Logs.
- [x] Update filters on Agents preview list.

**Comment by JuanjiJG** [comment]
Working on branch `issue-784`

Regards,
Juanjo

**Comment by JuanjiJG** [comment]
First approach done here: https://github.com/wazuh/wazuh-kibana-app/pull/787

Regards,
Juanjo

**Comment by jesusgn90** [comment]
_Update daemons filter list on Management > Logs._ https://github.com/wazuh/wazuh-kibana-app/pull/787/commits/eeb29fbf16ce45c192fef59517449fb843e21c75

**Comment by jesusgn90** [comment]
_Update filters on Agents preview list._ https://github.com/wazuh/wazuh-kibana-app/pull/787/commits/cb5265704c15d521de877d58dc276bcf4cf9ee9c

**Comment by JuanjiJG** [comment]
Thank you sooo much @jesusgn90 !! :smile:
