### ISSUE TITLE
Several bugs for first-time app loading

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#789]
Hello team,

We encountered two new bugs related to the first time you open the app without an API inserted.

- [x] The app shows 2 warning messages instead of only one.
- [x] After inserting the API and clicking on "Management", it will redirect to Overview. This only happens the first time.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
Done https://github.com/wazuh/wazuh-kibana-app/pull/791
