### ISSUE TITLE
Add "wazuh-monitoring" shards and replicas settings to app configuration file

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#801]
Hello team,

We should discuss adding the shards and replicas settings to the `config.yml` file for the monitoring indices, just like the .wazuh and .wazuh-version indices.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
Done: https://github.com/wazuh/wazuh-kibana-app/pull/809
