### ISSUE TITLE
Adapt Wazuh app for Elastic Stack v6.4.0

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#803]
According to [this Elastic team blog](https://www.elastic.co/blog/upcoming-kibana-plugin-api-changes-in-6-4), several important changes are coming for the next minor release of the Elastic Stack, v6.4.0.

We should start testing this new release and find possible bugs with our app and fix them in order to make it fully compatible with the new version.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
Working in https://github.com/wazuh/wazuh-kibana-app/tree/adapt-6.4

After a large refactor and right now, the app seems to be stable and the core functions have been adapted. Next steps are:

- Use all the Elastic stack in 6.4.0 (for now it has been tested using Kibana 6.4.0 faking the version but other Elastic components were in 6.3.2)
- Review all filtering functions
- Review search bar behaviour
- Review Kuery language usage
- Optimize visualizations even more (we have new events and methods)
- Debug some functions that still must be adapted
- Test it using production mode

**Comment by jesusgn90** [comment]
Done: https://github.com/wazuh/wazuh-kibana-app/pull/813

__Note:__ 23/08/2018 12:33, branch `3.5-6.4` has next branches `3.5-6.3` + `rename` + `adapt-6.4`
