### ISSUE TITLE
Incorrect version

### ISSUE THREAD

**Issue by shauryagarg2006** [wazuh/wazuh-kibana-app#818]
I am running the following command:
/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.5.0_6.3.2.zip

My ELK Stack is on 6.3.2 version.

I am getting the following error:

Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [wazuh]. Expected [6.4.0]; found [6.3.2]"

**Comment by JuanjiJG** [comment]
Hello @shauryagarg2006,

According to the error message, your Kibana installation was expecting a plugin with a version number of 6.4.0, but our current app is only compatible with Kibana 6.3.2.

You can check your current Kibana version with the following command:
```
cat /usr/share/kibana/package.json | grep version
```
Check our Elastic Stack [installation guide](https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/index.html).

Let us know if this helps.

Regards,
Juanjo

**Comment by shauryagarg2006** [comment]
Yes, I am sorry for the trouble It was the other way round. I had pinned the ELK version but somehow 6.4.0 was installed. We can close this issue.
