### ISSUE TITLE
Format agent coverage metric when there are no agents (multiple tabs)

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#826]

**Comment by JuanjiJG** [comment]
Hello @jesusgn90,

There's three locations in the app showing the current agents coverage:

1. **Overview > Security Events** (When `wazuh.monitoring.enabled` is set to `false`)
![1](https://user-images.githubusercontent.com/10928321/44843524-cc4cad00-ac48-11e8-8576-ff0cc1d8d4fc.PNG)
2. **Management > Status**
![2](https://user-images.githubusercontent.com/10928321/44843527-cc4cad00-ac48-11e8-8346-9bfc7dea233c.PNG)
3. **Agents list**
![3](https://user-images.githubusercontent.com/10928321/44843528-cc4cad00-ac48-11e8-9930-37135e05198a.PNG)

As you can see, the `0%` coverage is correctly shown on the interface.

If you consider this correct, then we can close this issue.

Regards,
Juanjo

**Comment by JuanjiJG** [comment]
Done here: https://github.com/wazuh/wazuh-kibana-app/pull/849

Regards,
Juanjo
