### ISSUE TITLE
The inventory tab is missing when reloading using F5

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#832]
When the user is on the _Agent Configuration_ tab and press F5 to reload the page, the Inventory tab will disappear from the navbar, and also from the Welcome tab, until the user reloads the page for example from the Welcome tab.

This is **only** happening on the _Agent Configuration_ tab.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
Fixed: https://github.com/wazuh/wazuh-kibana-app/commit/e0acc7c76735373c69cea39fcc691d0c93bddf27

This fix must be merged to 3.5-6.3 and 3.5-6.4, thanks for reporting @JuanjiJG .

**Comment by JuanjiJG** [comment]
You are welcome @jesusgn90 :+1:

**Comment by jesusgn90** [comment]
Done: https://github.com/wazuh/wazuh-kibana-app/pull/844
