### ISSUE TITLE
Dev tools don't work when blank lines precede the request

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-kibana-app#866]
If blank lines are inserted and any comment is written, the request don't work. 

![image](https://user-images.githubusercontent.com/10210567/45089699-509da500-b10d-11e8-9557-c629330cf962.png)

**Comment by jesusgn90** [comment]
Done https://github.com/wazuh/wazuh-kibana-app/pull/871, thanks @manuasir !
