### ISSUE TITLE
Error block parsing in dev-tools

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-kibana-app#867]
When any invalid block is inserted after a comment, the JSON parse fails in the previous blocks.

![image](https://user-images.githubusercontent.com/10210567/45089809-b0944b80-b10d-11e8-8c63-4606fe3082d5.png)

**Comment by jesusgn90** [comment]
Moved to https://github.com/wazuh/wazuh-kibana-app/issues/1050
