### ISSUE TITLE
Pinned filters that match with implicit filters will get stuck and unremovable forever

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#876]
This is the sequence of steps to reproduce this error:

1. On _Overview > Security Events_, create a filter like `rule.groups:syscheck`.
2. Pin the filter.
3. Go to the _Integrity Monitoring_ tab.
4. Go again to _Security Events_.
5. Now the pinned filter cannot be removed and will be permanent because it's treated like pinned and implicit at the same time, making other tabs unusable.

**Comment by jesusgn90** [comment]
Hi @JuanjiJG , thanks in advance for reporting this issue, GJ

Done: https://github.com/wazuh/wazuh-kibana-app/pull/878
