### ISSUE TITLE
Aborting Elastic searches when switching tabs produces false "No data found" message

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#877]
This is not always reproducible, but here are the steps:

1. Go to an agent, _Security Events_.
2. Enable a new filter (with filter pill).
3. Go to _Overview > Security Events_.
4. The filter won't be there (as expected), but the tab will show the "No data found" message when it's obvious that there's data available.
5. To fix this, open the _Discover_ subtab, and go again to _Dashboard_ subtab.

Tipically this will happen if the user changes tabs really quickly without even waiting for the app to finish loading the pages.

**Comment by jesusgn90** [comment]
Related https://github.com/wazuh/wazuh-kibana-app/pull/957, closing.
