### ISSUE TITLE
click  "Wazuh-agent"

### ISSUE THREAD

**Issue by xisafe** [wazuh/wazuh-kibana-app#884]
Agents Preview. Error. 4004 - [illegal_argument_exception] Fielddata is disabled on text fields by default. Set fielddata=true on [agent.name] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.

**Comment by xisafe** [comment]
3.6 version

**Comment by jesusgn90** [comment]
Hello @xisafe ,

My is bet about a wrong Elasticsearch template or a missing Elasticsearch template. First of all we are going to look for template existance:

```
curl elastic:9200/_cat/templates/wazuh
```

You should see:

```
wazuh [wazuh-alerts-3.x-*] 0 
```

**Template exists**

If the template exists, then it means the index was created before inserting the template. The solution now is as follow:

- Stop Logstash, delete today's index, restart Logstash.

```
systemctl stop logstash
curl -XDELETE elastic:9200/wazuh-alerts-3.x-2018.09.09
systemctl restart logstash
```
**Missing template**

If the template is missing, then it means the index was created without a template. The solution now is as follow:

- Stop Logstash, delete today's index, insert the template, restart Logstash.

```
systemctl stop logstash
curl -XDELETE elastic:9200/wazuh-alerts-3.x-2018.09.09
curl https://raw.githubusercontent.com/wazuh/wazuh/3.6/extensions/elasticsearch/wazuh-elastic6-template-alerts.json | curl -XPUT 'http://elastic:9200/_template/wazuh' -H 'Content-Type: application/json' -d @-
systemctl restart logstash
```
**Note:** you may don't want to lose today's index data, if so, let us know.

Regards,
Jesús

**Comment by xisafe** [comment]
Thank you. It was settled yesterday, as you said

**Comment by jesusgn90** [comment]
You are welcome @xisafe !

**Comment by smtpchecking01** [comment]
Hello Folks,

   -> I installed the wazuh-manager : 3.8.1 , wazuh-api : 3.8.1 and ELK version 6.5.4.

   -> After installed issue on adding the agent in UI level, Below pasted issue i am facing.

    " Agents Preview. Error. 4004 - [illegal_argument_exception] Fielddata is disabled on text fields by default. Set fielddata=true on [agent.name] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead ".

    -> Below i attached for your's reference verification snap's.


![agent_issue](https://user-images.githubusercontent.com/47144788/51910019-038bd980-23f4-11e9-8135-7f054358aac5.jpg)

**Comment by jesusgn90** [comment]
Hi @smtpchecking01 ,

You have a template issue. You can check steps from https://github.com/wazuh/wazuh-kibana-app/issues/884#issuecomment-419866833 because it's almost the same.

If you need to retain today's index, we must reindex today's index. Let me know if you need it.

Regards

**Comment by smtpchecking01** [comment]
jesusgn90 ,

-> I already checked the above template comment it's not working.

-> If you need to retain today's index, we must reindex today's index. Let me know if you need it. yes i need .

**Comment by jesusgn90** [comment]
#### How to fix already created indices

Stop Logstash:

```
systemctl stop logstash
```

Ensure the template is inserted:

```
curl https://raw.githubusercontent.com/wazuh/wazuh/3.8/extensions/elasticsearch/wazuh-elastic6-template-alerts.json | curl -XPUT 'http://elastic_ip:9200/_template/wazuh' -H 'Content-Type: application/json' -d @-
```

Check if the template was inserted:

```
curl elastic:9200/_cat/templates/wazuh
```

You should see:

```
wazuh [wazuh-alerts-3.x-*] 0 
```

#### Reindex

Assuming the only one affected index is `wazuh-alerts-3.x-2019.01.29` (repeat this procedure if you have more affected indices):

1) Reindex affected index into a backup index:

```
curl -X POST "elastic_ip:9200/_reindex" -H 'Content-Type: application/json' -d'
{
	"source": {
		"index": "wazuh-alerts-3.x-2019.01.29"
	},
	"dest": {
		"index": "wazuh-alerts-3.x-backup"
	}
}
'
```

2) Remove affected index:

```
curl -XDELETE elastic_ip:9200/wazuh-alerts-3.x-2019.01.29
```


3) Reindex backup index into a new index (using same name as before):

```
curl -X POST "elastic_ip:9200/_reindex" -H 'Content-Type: application/json' -d'
{
	"source": {
		"index": "wazuh-alerts-3.x-backup"
	},
	"dest": {
		"index": "wazuh-alerts-3.x-2019.01.29"
	}
}
'
```

4) Remove backup index:

```
curl -XDELETE elastic_ip:9200/wazuh-alerts-3.x-2019.01.29
```

#### Resume Logstash once finished

```
systemctl restart logstash
```

I hope it helps.

Best regards,
Jesús
