### ISSUE TITLE
Add CVE column on Vulnerabilities tab

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#891]
We have to think about adding a column to the _Vulnerabilities_ tab for the `data.vulnerability.cve` field.

Currently, we have the _Reference_ column, including a functional link to the official CVE webpage. The charts visualizations are heavy and impact on the app performance, so we have to make sure that this addition will increase the app value and usability.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
Moved to https://github.com/wazuh/wazuh-kibana-app/issues/1051
