### ISSUE TITLE
Update known fields to correct Whodata typo

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#900]
![bug](https://user-images.githubusercontent.com/10928321/45613939-24b4e480-ba68-11e8-998e-92aaa81038a4.PNG)

Reference: https://github.com/wazuh/wazuh/pull/1242

Regards,
Juanjo

**Comment by jesusgn90** [comment]
Done: https://github.com/wazuh/wazuh-kibana-app/pull/901
