### ISSUE TITLE
Multi selector

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh-kibana-app#906]
I would like to select several nodes at the same time:

![image](https://user-images.githubusercontent.com/1523318/45771313-11ab3b80-bc45-11e8-86c1-5cd4667430e0.png)

It will be useful for status, platforms and versions too.

**Comment by jesusgn90** [comment]
It's time to use the new API query operators!

**Comment by jesusgn90** [comment]
Included here https://github.com/wazuh/wazuh-kibana-app/issues/1002, all the selectors from the app will be replaced by #1002
