### ISSUE TITLE
Add a new directive for tables that don't fetch data externally

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#931]
Create a new directive for a table that will be similar to the existing `wz-table` directive, but without fetching data from external sources. It will receive valid data as input to show it on the user interface.

Tasks:

- [x] It must be a directive
- [x] All the style parameters should work like in the current table directive
- [x] The input is now an array instead of an API endpoint
- [x] All the fields must be sortable
- [x] It must include pages always

**Comment by jesusgn90** [comment]
Taks:

- [ ] It must be a directive
- [ ] All the style parameters should work like in the current table directive
- [ ] The input is now an array instead of an API endpoint
- [ ] All the fields must be sortable
- [ ] It must include pages always

**Comment by juankaromo** [comment]
PR https://github.com/wazuh/wazuh-kibana-app/pull/1067
