### ISSUE TITLE
Amazon AWS tab rework

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#936]
Improve our current Amazon AWS extension to include:

- [x] Service name selector, using native Kibana selector visualization. This modifies the filters depending on the selected service.
- [x] Show the accounts in use.
- [x] Show active rules in AWS config (regions and accounts).
- [x] Review Elasticsearch template depending on https://github.com/wazuh/wazuh/issues/1522 additions.
- [x] Add/Modify visualizations
- [x] Fully test this tab including the data flow, Elasticsearch,...
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/1053

Regards,
Juanjo

**Comment by jesusgn90** [comment]
Working on this branch https://github.com/wazuh/wazuh-kibana-app/tree/issue-936
