### ISSUE TITLE
[Discover] Preserve time range when clicking on agent ID

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#958]
Currently, the newest feature to redirect the user to an agent's page when clicking on its ID on the Discover panels will reset the currently selected time range. We could improve this and preserve the time range, so the user experience will be improved.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
Moved to https://github.com/wazuh/wazuh-kibana-app/issues/1051
