### ISSUE TITLE
How we can watch all manager and worker node status in kibana wazuh app ?

### ISSUE THREAD

**Issue by YashMangla** [wazuh/wazuh-kibana-app#967]
Guyz, I know from commandline to check status but  I unable to find setting to watch manager and worker node status in kibana wazuh app..
if anyone done it before kindly help in this regards..

**Comment by jesusgn90** [comment]
Hi @YashMangla ,

If I understood what you meant, you are talking about the daemon status, right? Looking for the node status and a few other things. Currently we are working in a distributed Wazuh API, this way we can fetch data like in the master node, but not possible for now unless you install a Wazuh API in that node then you can use our Dev Tools in the Wazuh App to execute some queries but I understand that's not the solution at all. 

On the other hand, we have a section under Management > Monitoring which provides you some useful information about the cluster nodes, but it's not what you are looking for.

![issue-01](https://user-images.githubusercontent.com/8860227/46824623-c55da200-cd91-11e8-88f1-801b7aebce95.png)

![issue-02](https://user-images.githubusercontent.com/8860227/46824642-d6a6ae80-cd91-11e8-9058-4429870f2798.png)

It's in our roadmap for sure, and next releases (don't know a precise date) we'll include that information. Thanks for your patience, we understand your request and it's in our roadmap as I said.

Kind regards,
Jesús

**Comment by jesusgn90** [comment]
Hi @YashMangla , related https://github.com/wazuh/wazuh-kibana-app/issues/975, stay updated tracking that ticket!

**Comment by jesusgn90** [comment]
Hello again @YashMangla , take a look at https://github.com/wazuh/wazuh-kibana-app/pull/976, not published yet, but we take into account your comment as you can see!
