### ISSUE TITLE
Wazuh App failed in Kibana

### ISSUE THREAD

**Issue by fl4nker** [wazuh/wazuh-kibana-app#968]
Hi, I installed Wazuh manager and api on an existing ELK Stack(Wazuh3.6.1 & ELK6.3.2 ). But when I try to open the Wazuh app in Kibana, the following errors occured:
```
outes. Error. 2001 - [security_exception] action [indices:data/read/search] is unauthorized for user [kibana]
Settings. Error. Error getting API entries\
Settings. Error. Error when loading Wazuh setup info
```
I  tried this solution—[issue382](https://github.com/wazuh/wazuh-kibana-app/issues/382), but it didn't work for me.Can you help me out ? Any solution will be appreciated.Below here is my config that related

**Kibana Configiration**
```
elasticsearch.username: "elastic"
elasticsearch.password: "PASSWORD"
```

**Wazuh-API**
```
curl -u "wazuh:PASSWORD" -ssl -k "https://127.0.0.1:55000/?pretty"
{
   "error": 0,
   "data": {
      "msg": "Welcome to Wazuh HIDS API",
      "api_version": "v3.6.1",
      "hostname": "sec",
      "timestamp": "Fri Oct 12 2018 17:35:44 GMT+0800 (CST)"
   }
}
```

**Wazuh-Manager**
```
/var/ossec/bin/agent_control -V
 
Wazuh v3.6.1 - Wazuh Inc.
 
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License (version 2) as 
published by the Free Software Foundation. For more details, go to 
https://www.gnu.org/licenses/gpl.html
```

**Elasticsearch**
```
 curl -u 'elastic:PASSWORD' -ssl -k "https://127.0.0.1:9200/?pretty"
{
  "name" : "Z3VxNL8",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "7sdKA-bARwymOd5r5uM7Ug",
  "version" : {
    "number" : "6.3.2",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "053779d",
    "build_date" : "2018-07-20T05:20:23.451332Z",
    "build_snapshot" : false,
    "lucene_version" : "7.3.1",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

**wazuh-kibana-app**
```
cat /usr/share/kibana/plugins/wazuh/package.json 
{
    "name": "wazuh",
    "version": "3.6.1",
    "revision": "0408",
    "kibana": {
        "version": "6.3.2"
    },
    "description": "Wazuh app",
    "main": "index.js",
    "keywords": [
        "kibana",
        "wazuh",
        "ossec"
    ],
    "author": "Wazuh, Inc",
    "license": "GPL-2.0",
    "repository": {
        "type": "git",
        "url": "https://github.com/wazuh/wazuh-kibana-app.git"
    },
    "bugs": {
        "url": "https://github.com/wazuh/wazuh-kibana-app/issues"
    },
    "homepage": "https://www.wazuh.com/",
    "dependencies": {
        "angular-animate": "1.6.5",
        "angular-cookies": "1.6.5",
        "angular-material": "1.1.10",
        "dom-to-image": "^2.6.0",
        "install": "^0.10.1",
        "js2xmlparser": "^3.0.0",
        "json2csv": "^4.1.2",
        "needle": "^2.0.1",
        "node-cron": "^1.1.2",
        "pdfmake": "^0.1.37",
        "querystring-browser": "1.0.4",
        "simple-tail": "^1.1.0",
        "timsort": "^0.3.0",
        "winston": "3.0.0"
    }
}
```

**Browser Error**
- https://10.28.100.110:5601/api/wazuh-api/apiEntries
```
message | 2001 - [security_exception] action [indices:data/read/search] is unauthorized for user [kibana]
-- | --
code | 2001
statusCode | 500
```

- https://10.28.100.110:5601/api/wazuh-elastic/setup
```
message | 4005  - Could not get data from elasticsearch due to [security_exception]  action [indices:data/read/search] is unauthorized for user [kibana]
-- | --
code | 4005
statusCode | 500
```

**Comment by jesusgn90** [comment]
Hello @fl4nker  ,

The problem you are facing comes from X-Pack security roles. The message `[indices:data/read/search] is unauthorized for user [kibana]` means the user `kibana` is having troubles for fetching `.wazuh` index, that index is a Wazuh app index. 

At this point you have two solutions:

1) Use the `elastic` user instead of the `kibana` user when login the UI, and use it in your `kibana.yml` file too.
2) Follow our X-Pack guide to fully configure each role https://documentation.wazuh.com/current/user-manual/kibana-app/configure-xpack/index.html

I hope it helps. Best regards,
Jesús

**Comment by fl4nker** [comment]
thanks for your help! @jesusgn90 
As mentioned in my post, I use the **elastic** user in my kibana configuration file and also use it login the Kibana UI, it doesn't work. I'll try the second solution, thanks again

**Comment by jesusgn90** [comment]
Hi @fl4nker ,

The second solution is the right way, in any case, ` is unauthorized for user [kibana]` is telling you that you are using the user `kibana` when login the UI, give a try to use `elastic` user because it's the admin user so it must work.

Let us know @fl4nker !

Best regards,
Jesús

**Comment by fl4nker** [comment]
thanks again! @jesusgn90 

But I'm so sorry to say, that solution2 also failed. I'm so confused !!
I go through all steps that you mentioned in solution2 ([wazuh-configure-xpack](https://documentation.wazuh.com/current/user-manual/kibana-app/configure-xpack/index.html)), but it just failed, no matter I use the **elastic** user or the new create **wazuh_system** user. 

Let me give you some screenshot here:
- solution 1
<img width="417" alt="kibana_config" src="https://user-images.githubusercontent.com/44086409/46989637-56d16900-d130-11e8-9edd-a5508bd1e8d3.png">

<img width="920" alt="kibana_ui" src="https://user-images.githubusercontent.com/44086409/46989579-212c8000-d130-11e8-8074-bee1c441acb5.png">

- solution 2
<img width="619" alt="1" src="https://user-images.githubusercontent.com/44086409/46989595-32758c80-d130-11e8-866e-a8f2789f80bb.png">
<img width="546" alt="2" src="https://user-images.githubusercontent.com/44086409/46989596-33a6b980-d130-11e8-82aa-63b76b6bd630.png">
<img width="387" alt="3" src="https://user-images.githubusercontent.com/44086409/46989601-386b6d80-d130-11e8-9b54-8c9cfc410387.png">
<img width="524" alt="4" src="https://user-images.githubusercontent.com/44086409/46989605-3b665e00-d130-11e8-83be-d3e520e85eca.png">
<img width="772" alt="5" src="https://user-images.githubusercontent.com/44086409/46989609-3e614e80-d130-11e8-83d0-0e0f4058be01.png">

**Comment by jesusgn90** [comment]
Hello again @fl4nker ,

That's pretty weird because we've tested it again a week ago. In any case, it seems like you are still using `kibana` as the UI user (`[indices:data/read/search] is unauthorized for user [kibana]`). 

Let's use the `elastic` user for both UI and server. Please take a look into your /etc/kibana/kibana.yml and ensure you are using `elastic` as the server user:

```yml
elasticsearch.username: "elastic"
elasticsearch.password: "elastic_pass"
```
If you modified the file, please restart Kibana:

```
# systemctl restart kibana
```
Now please open a new incognito window in your browser (it works better with Chrome) and login the Kibana UI using the user `elastic` (same as the kibana.yml user).

This must works because the `elastic` user is superadmin in Elasticsearch.

Once you are done using the `elastic` user we can continue creating more users and roles, for now, my goal is to make it work using only the `elastic` user.

Best regards,
Jesús

**Comment by fl4nker** [comment]
@jesusgn90 
I'm definitely using the **elastic** user in my Kibana configuration and Kibana UI. And everytime I modified the kibana configuration, I restarted the Kibana. Please reference my screenshot 
[Kibana Config](https://user-images.githubusercontent.com/44086409/46989637-56d16900-d130-11e8-9edd-a5508bd1e8d3.png)
[Kibana UI](https://user-images.githubusercontent.com/44086409/46989605-3b665e00-d130-11e8-83be-d3e520e85eca.png)

It's so weird, and I'm sooo confused. 
Never mind, I'd like to give it up,and try another installtion from scratch.

**Comment by fl4nker** [comment]
@jesusgn90 
sorry, paste wrong picture!

[Kibana config](https://user-images.githubusercontent.com/44086409/46989637-56d16900-d130-11e8-9edd-a5508bd1e8d3.png)
[Kibana UI](https://user-images.githubusercontent.com/44086409/46989579-212c8000-d130-11e8-8074-bee1c441acb5.png)

**Comment by jesusgn90** [comment]
There is still something wrong, the user `elastic` is the admin user. Please, can we try to open a new incognito window on your browser and login as `elastic` one more time? (https://support.mozilla.org/en-US/kb/private-browsing-use-firefox-without-history, https://www.lifewire.com/incognito-mode-google-chrome-4103635)

Regards

**Comment by fl4nker** [comment]
still not working.it's soooo weird,I'll try another way
thanks for your help @jesusgn90 

<img width="453" alt="screenshot_20181018_165910328" src="https://user-images.githubusercontent.com/44086409/47143212-37d10380-d2f7-11e8-9df8-e571a4f323dc.png">

<img width="619" alt="screenshot_20181018_170923597" src="https://user-images.githubusercontent.com/44086409/47143805-96e34800-d2f8-11e8-8fe7-3eae2ab5a1d9.png">

**Comment by jesusgn90** [comment]
That's pretty weird @fl4nker , let's see _Management > Users_ and _Management > Roles_, please.

![image](https://user-images.githubusercontent.com/8860227/47149323-8b315a80-d2d3-11e8-925e-96e55bff17f0.png)

Regards

**Comment by fl4nker** [comment]
@jesusgn90 
I installed Wazuh on another ELK Stack from scratch, ELK6.4.1 without X-Pack security enabled, it works fine. 
Here, I'll help the community debug the previous issue. 
<img width="595" alt="screenshot_20181019_103128896" src="https://user-images.githubusercontent.com/44086409/47194551-5c29f000-d38a-11e8-89bb-b51cc216df67.png">

<img width="422" alt="screenshot_20181019_10322316" src="https://user-images.githubusercontent.com/44086409/47194555-5fbd7700-d38a-11e8-960a-02412f47c700.png">

**Comment by mathieu83470** [comment]
Hello,

I have the same issue but i can't disable Xpack , anyone know to resolve it?
In kibana.yml => I use "elastic" user
In kibana UI => Logged with same "elastic" user

Error message : {"message":"2001 - [security_exception] action [indices:data/read/search] is unauthorized for user [kibana]","code":2001,"statusCode":500}

Thanks for your help

**Comment by jesusgn90** [comment]
Hi @mathieu83470 ,

That's weird because the log is saying `for user [kibana]`, are you sure Kibana is using `elastic` user both sides (UI and server)?

Can you show us the `kibana.yml` content? (replace your password with "****")

Which version is your app? (Wazuh version + Kibana version)

Regards
