### ISSUE TITLE
Add the ability to see syscheck files for an agent

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#988]
It would be nice if we can see Syscheck files and navigate through them using the Wazuh app.

This issue gonna have the following tasks:
- [x] Include it under the FIM tab.
- [x] Create a new HTML card for this table
- [x] Query bar  
- [x] File table
- [x] Test correct results and filter works properly
- [x] Check useful fields when the agent uses Windows and when the agent uses MacOS. Not all the fields are valid or filled depending on the OS.
- [x] "Formatted" download button should work taking into account the table filters.
- [x] Split it into two tables (files and registry) when the agent uses Windows
- [x] Add a switch option in FIM tab in order to switch between alerts and files
- [x] Ensure that visualizations reload properly with the recently added events once switch from the table to the dashboard

**Comment by juankaromo** [comment]
Working on this branch https://github.com/wazuh/wazuh-kibana-app/tree/issue-988
