### ISSUE TITLE
Back button not working due to routing module

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#994]
Due to the Kibana routing system, the app has an unexpected behavior for the user when he uses the back button from the browser. We must add some logic to our routing system so we can handle properly where to go or what show depending on the user expected navigation.

Tasks:

- [x] Define a system to keep safe where we go to and where we come from.
- [x] Overview
- [x] Management
- [x] Agents list
- [x] Dev Tools
- [x] Settings
 
The above tasks must match these requirements:

- [x] Regardless of the section we are using, the back button must go to the last one state
- [x] If there is no last state, Kibana decides where to go

Regards

**Comment by juankaromo** [comment]
Working on this branch https://github.com/wazuh/wazuh-kibana-app/tree/issue-994

**Comment by juankaromo** [comment]
Merged with this branch https://github.com/wazuh/wazuh-kibana-app/tree/issue-1161

**Comment by juankaromo** [comment]
I'm doing the finishing touches to make it work in the new configuration editing views. I found a strange behavior when entering the XML files edition. In these cases, the button does not work.  I continue to improve it and test it on branch https://github.com/wazuh/wazuh-kibana-app/tree/issue-1161
